### PR TITLE
fix(inccommand): don't preview when in ex mode

### LINKED ISSUE #26056: inccommand should default to false in ex mode
### Problem

In ex mode, I expect the screen to only redraw explicitly when I issue a command.

Because `inccommand` defaults to "nosplit", the view jumps around for live preview while writing a substitution command.

### Steps to reproduce

nvim -E somefile
:%s/example

### Expected behavior

No visual changes while typing.

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

no, 9.0.1894

### Operating system/version

macOS 14.1.1

### Terminal name/version

iTerm 3.4.22

### $TERM environment variable

xterm-256color

### Installation

homebrew

### PR DESCRIPTION
**Pull request by glepnir**
Probelem: inccommand has default value, when run substitute in exmode will show preview.

Solution: check if its in exmode.

Fix #26056

### CODE REVIEW

File: src/nvim/ex_getln.c [hunk 1]
```diff
@@ -2632,7 +2632,7 @@ static int command_line_changed(CommandLineState *s)
   const bool prev_cmdpreview = cmdpreview;
   if (s->firstc == ':'
       && current_sctx.sc_sid == 0    // only if interactive
-      && *p_icm != NUL       // 'inccommand' is set
+      && (*p_icm != NUL && !exmode_active)  // 'inccommand' is set and not in ex mode
```
Comment (zeertzjq) [inline src/nvim/ex_getln.c:2635]:
```suggestion
      && *p_icm != NUL       // 'inccommand' is set
      && !exmode_active      // not in ex mode
```

**Comment by glepnir** [comment]
@gpanders  i get the failed on windows with 
`vim/_defaults.lua:339: module 'vim.termcap' not found: `.  does there also need check ex mode or something i need to change ?

File: test/functional/core/startup_spec.lua [hunk 2]
```diff
@@ -1097,3 +1097,23 @@ describe('user session', function()
...
   end)
 end)
+
+describe('inccommand on ex mode', function()
+  it('should not preview', function()
+    clear()
+    local screen
+    screen = Screen.new(60, 10)
+    screen:attach()
+    local id = funcs.termopen({ nvim_prog, '-u', 'NONE', '-c', 'set termguicolors', '-E', 'test/README.md' })
```
Comment (zeertzjq) [inline test/functional/core/startup_spec.lua:1107]:
```suggestion
    local id = funcs.termopen({ nvim_prog, '--clean', '-c', 'set termguicolors', '-E', 'test/README.md' })
```

Comment (glepnir) [reply test/functional/core/startup_spec.lua]: seems like if add `--clean` also need set VIMRUNTIMPATH. because in main.c will source syntax.vim ..

```C
  if (!vimrc_none || params.clean) {
    // Sources filetype.lua unless the user explicitly disabled it with :filetype off.
    filetype_maybe_enable();
    // Sources syntax/syntax.vim. We do this *after* the user startup scripts so that users can
    // disable syntax highlighting with `:syntax off` if they wish.
    syn_maybe_enable();
  }
```

File: test/functional/core/startup_spec.lua [hunk 3]
```diff
@@ -1097,3 +1097,23 @@ describe('user session', function()
...
   end)
 end)
+
+describe('inccommand on ex mode', function()
+  it('should not preview', function()
+    clear()
+    local screen
+    screen = Screen.new(60, 10)
+    screen:attach()
+    local id = funcs.termopen({ nvim_prog, '--clean', '-u', 'NONE', '-E', 'test/README.md' })
```
Comment (zeertzjq) [inline test/functional/core/startup_spec.lua:1107]: Oh wait, actually `VIMRUNTIME` is what is missing here
```suggestion
    local id = funcs.termopen({ nvim_prog, '-u', 'NONE', '-E', 'test/README.md' }, {
      env = { VIMRUNTIME = os.getenv('VIMRUNTIME') }
    })
```

Comment (glepnir) [reply test/functional/core/startup_spec.lua]: yup .. i also find it just now.

Comment (glepnir) [reply test/functional/core/startup_spec.lua]: also failed but not relate i think. could you please review again.

**Comment by glepnir** [comment]
seems like missing highlight in windows ? no any color in test 
```
screen:expect{grid=[[
  ^                                                            |
                                                              |*6
  Entering Ex mode.  Type "visual" to go to Normal mode.      |
  :%s/N                                                       |
                                                              |
]]}
```

File: test/functional/core/startup_spec.lua (hunk 2 above)
Comment (wookayin) [reply test/functional/core/startup_spec.lua]: Regardless of `VIMRUNTIMEPATH`, we should do either `--clean` or `-u NONE -i NONE`, shouldn't we?
