### PR TITLE
vim-patch:8.2.{3484,5007,5123}: spell suggestion fixes

### LINKED ISSUE #8965: heap-buffer-overflow in vim at vim_strncpy (src/strings.c:509)
Hello,

We are currently working on fuzz testing feature, and we found a **heap-buffer-overflow** on `vim`.

The stack traces are as follow:
```st
==25575==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000058936 at pc 0x7fd83c27e806 bp 0x7ffc875a9740 sp 0x7ffc875a8ee8
READ of size 1 at 0x602000058936 thread T0
    #0 0x7fd83c27e805 in __interceptor_strncpy (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x94805)
    #1 0x55f2497160d1 in vim_strncpy .../vim-git/src/strings.c:509
    #2 0x55f24970f2aa in check_suggestions .../vim-git/src/spellsuggest.c:3620
    #3 0x55f2496fb99f in spell_suggest_intern .../vim-git/src/spellsuggest.c:1055
    #4 0x55f2496faa38 in spell_find_suggest .../vim-git/src/spellsuggest.c:870
    #5 0x55f2496f7e08 in spell_suggest .../vim-git/src/spellsuggest.c:545
    #6 0x55f24951c890 in nv_zet .../vim-git/src/normal.c:3218
    #7 0x55f24950f93b in normal_cmd .../vim-git/src/normal.c:1099
```
Here is the full stack trace : [full_stacktrace_poc_7.zip](https://github.com/vim/vim/files/7288158/full_stacktrace_poc_7.zip)

**Step to reproduce**

We configured `vim` using `CFLAGS="-g -O0 -fsanitize=address" CXXFLAGS="-g -O0 -fsanitize=address" LDFLAGS="-g -O0 -fsanitize=address" ./configure --prefix=$(pwd)/` and build it using `make -j10`, and run it with:

```
./vim -u NONE -X -Z -e -s -S <attached file> -c ':qa!'
```
Attachment: [input_vim_poc_7.zip](https://github.com/vim/vim/files/7288160/input_vim_poc_7.zip)

**Environment**
- OS: Ubuntu 18.04.5 LTS
- GCC version: gcc 7.5.0
- vim version: latest commit (f67d3fb7) of master branch in github ([link](https://github.com/vim/vim/tree/f67d3fb7363ebc9454f9bb582de3978609a4fd6b))

Thank you.

### PR DESCRIPTION
**Pull request by zeertzjq**
#### vim-patch:8.2.3484: crash when going through spell suggestions

Problem:    Crash when going through spell suggestions.
Solution:   Limit the text length for finding suggestions to the original
            length.  Do not update buffers when exiting. (closes vim/vim#8965)
https://github.com/vim/vim/commit/e275ba4fc994474155fbafe8b87a6d3b477456ba

#### vim-patch:8.2.5007: spell suggestion may use uninitialized memory

Problem:    Spell suggestion may use uninitialized memory. (Zdenek Dohnal)
Solution:   Avoid going over the end of the word.
https://github.com/vim/vim/commit/6d24b4ff69913270ce1e5267dd6bd8454f75e2b9

#### vim-patch:8.2.5123: using invalid index when looking for spell suggestions

Problem:    Using invalid index when looking for spell suggestions.
Solution:   Do not decrement the index when it is zero.
https://github.com/vim/vim/commit/156d3911952d73b03d7420dc3540215247db0fe8

### CODE REVIEW

**Comment by zeertzjq** [comment]
There is something strange with the test in this PR:
1. It tries to delete a file `Xtmpfile` which it has never created.
2. It doesn't fail ASAN in Vim without the fix.

**Review by justinmk — APPROVED** [review]

**Comment by zeertzjq** [comment]
I cannot find any other way to clear the word list. Making setting `'encoding'` clear word list is the only make to make these spell tests pass.

**Review by justinmk — APPROVED** [review]
Not ideal, but not worth blocking on.

Side note: spell_reload() was not used until this PR? :)

File: src/nvim/option.c [hunk 1]
```diff
@@ -2596,6 +2596,8 @@ static char *did_set_string_option(int opt_idx, char_u **varp, bool new_value_al
         // only encoding=utf-8 allowed
         if (STRCMP(p_enc, "utf-8") != 0) {
           errmsg = e_unsupportedoption;
+        } else {
+          spell_reload();
```
Comment (justinmk) [inline src/nvim/option.c:2600]: Perhaps we could call this from `:set all&` ? Then the test could do that, though it might require setting some other options or sourcing `testdir/setup.vim` again.

Then we could avoid this weird special case.

**Comment by zeertzjq** [comment]
In Vim it is called from `mb_init()`, which is called when `'encoding'` is changed.
