### PR TITLE
fix(aucmd_win): ensure aucmd_win stays floating

### LINKED ISSUE #13104: Quickfix window broken after e82b8ddef16eb7ce96e1d3d063ff529f79ed6bb2
- `nvim --version`: NVIM v0.5.0-756-g288f7f855
- `vim -u DEFAULTS` (version: ) behaves differently? Unknown.
- Operating system/version: nixos 21.03pre246591.8294af02845
- Terminal name/version: alacritty 0.5.0 + tmux 3.1b
- `$TERM`: tmux-256color

### Steps to reproduce

Plugins used:
[1] https://github.com/neovim/nvim-lspconfig
[2] https://github.com/nvim-lua/diagnostic-nvim (to populate the location list)
~~[3] https://github.com/romainl/vim-qf~~

On this sample file:
```
#!/usr/bin/env python3


this is a syntax error
```

With the following configuration:
```
$ cat config/nvim/init.vim
autocmd Filetype qf wincmd J

$ cat config/nvim/after/plugin/something.vim
lua require'nvim_lsp'.pyls.setup{on_attach=require'diagnostic'.on_attach}
```

And plugins placed under data/nvim/site/pack/...

Loaded by setting `XDG_DATA_HOME` and `XDG_CONFIG_HOME`

Do:
1. Edit `repro.py`
2. Open the location list
3. Fix the syntax error
4. Close the location list
5. Undo 3.
6. Observe the broken window

Some notes: 
 - ~~Whether or not the mapping from vim-qf is used does not seem to matter, however I have not managed to reproduce the issue without loading the plugin.~~
- ~~I'm unfamiliar with how to go about populating the location list in the background without using [1] and [2], and so have not tried reproducing this in vim.~~
- Having slept on it I realise that I'd completely forgotten about Neomake/ALE. Still, I'll trust @mechkblife on vim reproducibility. 

### Actual behaviour

After resizing it using the mouse with `set mouse=a`:

### Expected behaviour

No broken window/statusline.

### Bisect

```
e82b8ddef16eb7ce96e1d3d063ff529f79ed6bb2 is the first bad commit
commit e82b8ddef16eb7ce96e1d3d063ff529f79ed6bb2
Author: Jan Edmund Lazo <jan.lazo@mail.utoronto.ca>
Date:   Sat Oct 10 13:11:34 2020 -0400

    vim-patch:8.1.0877: new buffer used every time the quickfix window is opened

    Problem:    New buffer used every time the quickfix window is opened.
    Solution:   Reuse the buffer. (Yegappan Lakshmanan, closes vim/vim#3902)
    https://github.com/vim/vim/commit/ee8188fc74a7cf9ee7acb634b2bb7a032d0cb24c

 src/nvim/buffer.c                  | 14 ++-----
 src/nvim/quickfix.c                | 77 +++++++++++++++++++++++++-------------
 src/nvim/testdir/test_quickfix.vim | 43 +++++++++++++++++++++
 3 files changed, 99 insertions(+), 35 deletions(-)
```

### LINKED ISSUE #13699: Glitched layout / crash with quickfix, autocmd and tabs
- `nvim --version`: master (NVIM v0.5.0-dev+1008-gadbf2dd86)
- `vim -u DEFAULTS` (version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31) Included patches: 1-2269): no bug
- Operating system/version: Ubuntu 20.04
- Terminal name/version: alacritty 0.6.0-dev (3a71300)
- `$TERM`: xterm-256color

It happened a few times but finally managed to find a reproducing sequence.
In my setup, it is triggered by the use of [vim-qf](https://github.com/romainl/vim-qf)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC somefile
:autocmd FileType qf wincmd J
:grep x %
:cwin
:tabe
:b1
:grep x %
```

### Actual behaviour

The layout in the second tab is broken, half of the window is visible and modifiable, the second half keeps displaying the result of the grep. The first tab seems to work mostly fine.

By playing around, grepping more, playing with tabs, opening the quickfix window, it's possible to crash neovim but I haven't found a reliable sequence so far. Here is a back-trace:

```
#0  frame_minwidth (topfrp=topfrp@entry=0x3c0000003c, next_curwin=next_curwin@entry=0x0) at ../src/nvim/window.c:3540
#1  0x0000562976d16981 in frame_minwidth (topfrp=topfrp@entry=0x5629791b7060, next_curwin=next_curwin@entry=0x0)
    at ../src/nvim/window.c:3554
#2  0x0000562976d1a9ab in frame_setwidth (curfrp=0x5629791e8190, width=20) at ../src/nvim/window.c:5396
#3  0x0000562976d1c572 in win_setwidth_win (width=<optimized out>, wp=0x5629791dfa70) at ../src/nvim/window.c:5360
#4  0x0000562976d1c59a in win_setwidth (width=<optimized out>) at ../src/nvim/window.c:5340
#5  0x0000562976d1d39c in win_enter_ext (wp=0x5629791dfa70, undo_sync=<optimized out>, curwin_invalid=curwin_invalid@entry=0,
    trigger_new_autocmds=trigger_new_autocmds@entry=0, trigger_enter_autocmds=trigger_enter_autocmds@entry=1,
    trigger_leave_autocmds=trigger_leave_autocmds@entry=1) at ../src/nvim/window.c:4631
#6  0x0000562976d1d3cd in win_enter (wp=<optimized out>, undo_sync=<optimized out>) at ../src/nvim/window.c:4501
#7  0x0000562976f0da02 in aucmd_prepbuf (aco=0x7ffd97722e20, buf=0x5629791941c0) at ../src/nvim/autocmd.c:1145
#8  0x0000562976dc7469 in qf_update_buffer (qi=qi@entry=0x5629771537a0 <ql_info.lto_priv>, old_last=old_last@entry=0x0)
    at ../src/nvim/quickfix.c:3881
#9  0x0000562976dcbb77 in qf_init_ext (qi=0x5629771537a0 <ql_info.lto_priv>, qf_idx=5,
    efile=efile@entry=0x5629791deab0 "/tmp/nvimfvAzOs/6", buf=0x562978e44d80, tv=tv@entry=0x0,
    errorformat=errorformat@entry=0x56297703dbed "%f:%l:%m,%f:%l%m,%f  %l%m", newlist=true, lnumfirst=0, lnumlast=0,
    qf_title=0x562977153dc0 <qftitle_str> ":grep -n l src/coverity-model.c /dev/null", enc=0x562978e49f90 "")
    at ../src/nvim/quickfix.c:1201
#10 0x0000562976dcbbdd in qf_init (wp=wp@entry=0x0, efile=efile@entry=0x5629791deab0 "/tmp/nvimfvAzOs/6",
    errorformat=0x56297703dbed "%f:%l:%m,%f:%l%m,%f  %l%m", newlist=1,
    qf_title=0x562977153dc0 <qftitle_str> ":grep -n l src/coverity-model.c /dev/null", enc=enc@entry=0x562978e49f90 "")
    at ../src/nvim/quickfix.c:313
#11 0x0000562976dcbd3b in ex_make (eap=0x7ffd977230a0) at ../src/nvim/quickfix.c:4217
#12 0x0000562976e8bfb1 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffd977232d8, flags=flags@entry=0,
    cstack=cstack@entry=0x7ffd97723360, fgetline=fgetline@entry=0x562976e772f7 <getexline>, cookie=cookie@entry=0x0)
    at ../src/nvim/ex_docmd.c:1972
#13 0x0000562976e8dbf3 in do_cmdline (cmdline=<optimized out>, fgetline=0x562976e772f7 <getexline>, cookie=0x0, flags=0)
    at ../src/nvim/ex_docmd.c:601
#14 0x0000562976dfd2a4 in nv_colon (cap=0x7ffd97723998) at ../src/nvim/normal.c:4659
#15 0x0000562976e03ff1 in normal_execute (state=0x7ffd97723910, key=<optimized out>) at ../src/nvim/normal.c:1142
#16 0x0000562976d5ead9 in state_enter (s=0x7ffd97723910) at ../src/nvim/state.c:69
#17 0x0000562976e0409d in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at ../src/nvim/normal.c:463
#18 0x0000562976e3ab38 in main (argc=<optimized out>, argv=<optimized out>) at ../src/nvim/main.c:562
```

### Expected behaviour

No glitch.

### PR DESCRIPTION
**Pull request by seandewar**
Nvim uses a floating window for the autocmd window, but in certain situations,
it can be made non-floating (`:wincmd J`), which can cause issues due to the
previous setup and cleanup logic for a non-floating aucmd_win being removed from
aucmd_prepbuf and aucmd_restbuf.

This can cause glitchiness and crashes due to the aucmd_win's frame being
invalid after closing its tabpage, for example.

Ensure aucmd_win cannot be made non-floating. The only place this happens is in
win_split_ins.

Closes #13699.
Also fixes #13104 after re-applying the reverted patches in #13123.

### CODE REVIEW

**Comment by bfredl** [comment]
Hmm, I would go one step further and forbid it to be made non-floating in the first place? any downsides to that (like any popular plugin we would upset)?

**Comment by seandewar** [comment]
No idea. I can't see any legitimate use for moving around the aucmd window that isn't a mistake (like in #13699 where people expected it to move the qf window again).

I wonder if it's worth raising an error with that approach (or just silently do nothing?)

**Comment by bfredl** [comment]
yes, perhaps the simplest is to just  make any `wincmd J` like command silently do nothing.

**Comment by seandewar** [comment]
Hmm, at the very least I've gone ahead and made splitting return `FAIL` from `win_split_ins`. Calling code can technically complain about that if they want to, but the window commands and most other places are fine with it.

I still need to recompute the window layout in `aucmd_restbuf` as in some cases the return value of `win_split_ins` is ignored and calling code does some resizing anyway.

File: src/nvim/autocmd.c [hunk 1]
```diff
@@ -1152,6 +1152,7 @@ void aucmd_prepbuf(aco_save_T *aco, buf_T *buf)
     globaldir = NULL;
 
     block_autocmds();  // We don't want BufEnter/WinEnter autocommands.
+    make_snapshot(SNAP_AUCMD_IDX);
```
Comment (bfredl) [inline src/nvim/autocmd.c:1155]: Is this really needed, now what we banned inserting the aucmdwin? saving/restoring window layout was the anti-pattern we aimed at getting rid of in the first place..

Comment (seandewar) [reply src/nvim/autocmd.c:1155]: Tests fail without it. If I remember correctly, the problem is that even if we do not allow `aucmd_win` to be messed around in `win_split_ins`, calling code still ignores the return value and messes with the window layout?

Comment (bfredl) [reply src/nvim/autocmd.c:1155]: So, shouldn't we fix the calling code then?

**Comment by zeertzjq** [comment]
BTW, I noticed that Vim makes autocmd window the first window in the window list (having window number 1), whereas Nvim makes it the last one since #9798. I'm not sure which one is better, but I noticed this when trying to port <https://github.com/vim/vim/commit/832adf9bb8cd39d8e982d8a35ed8a6d39b974494> to Nvim.

File: src/nvim/autocmd.c (hunk 1 above)
Comment (seandewar) [reply src/nvim/autocmd.c]: Looks like the other way around, layout is messed with _before_ `win_split_ins`, in preparation for it.

This only seems to be called in places that want to move a window to a different split.
To do this, `win_split_ins` is called with `new_wp != NULL`, to insert an existing window into a new split.
Layout is messed with to remove the old split (otherwise you'd have 2 splits referring to the same window...).

Calling `win_split_ins` first to check its return value beforehand would potentially cause problems with other windows, I think (e.g: you may get `e_noroom` because the old split is still taking up space).

Instead I just test for `aucmd_win` before the only 2 places that mess with the layout.
`win_split` isn't affected as it creates a new split of a new window from `curwin` (`new_wp == NULL`; `aucmd_win` should be allowed to do that).

**Comment by bfredl** [comment]
I'd say let keep the behavior of being last in the window list, and update ported tests as needed. a plugin which breaks on that could just as well break on aucmd_win being floating at all.
