### PR TITLE
fix: update last cursor on first CursorMoved

### LINKED ISSUE #12923: CursorMoved event closes float to early if there is a pending cursor move
- `nvim --version`: v0.5.0-f34eeba2d
- `vim -u DEFAULTS` (version: ) behaves differently?  only neovim 
- Operating system/version: macos 10.15.6
- Terminal name/version: kitty
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

```lua
function  jump_to()
  api.nvim_win_set_cursor(0,{4,3})
  vim.lsp.util.open_floating_preview({"test"},'markdown')
end
```

### Actual behaviour

 The `nvim_win_set_cursor` doesn't immediately trigger CursorMoved. The util function opens a float and immediately registers the CursorMoved aucmd. On next event loop "tick", the float is closed even if the cursor was not moved again.

### Expected behaviour

The autocmd being debounced/delayed somehow. Like wait for two `CursorMoved` before closing the window (if one is pending already).

### LINKED ISSUE #16625: CursorMoved is immediately triggered when defining an autocommand on first definition
### Neovim version (nvim -v)

0.6.0

### Language server name/version

tsserver, rust_analyzer

### Operating system/version

Arch linux

### :checkhealth

```markdown
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: pyright: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - INFO: texlab: configuration checked.
  - INFO: tsserver: configuration checked.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $SSH_TTY='/dev/pts/6'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - WARNING: `focus-events` is not enabled. |'autoread'| may not work.
    - ADVICE:
      - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
          set-option -g focus-events on
  - INFO: $TERM: alacritty
  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - ADVICE:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ
```

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
local on_windows = vim.loop.os_uname().version:match 'Windows'
vim.g.loaded_matchparen = 1

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir
if on_windows then
  temp_dir = vim.loop.os_getenv 'TEMP'
else
  temp_dir = '/tmp'
end

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'tsserver'
  -- local cmd = { 'pyright-langserver', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    -- cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### Expected behavior

Should instantly show the hover window without having to press "K" twice

### Actual behavior

I have to press K twice to show the hover window (when matchparen is equal to 1)

### Log file

https://gist.github.com/foodornt/7a8441b2be311414bfc3a10255fe9265

### PR DESCRIPTION
**Pull request by mjlbach**
Closes https://github.com/neovim/neovim/issues/16625
Closes https://github.com/neovim/neovim/issues/12923

Supersedes https://github.com/neovim/neovim/pull/13867

The first defined CursorMoved autocommand will immediately
fire if the cursor has previously moved upon definition
of the autocommand.

Plugins add dummy autocommands such as:

```lua
autocmd CursorMoved * execute ''
```

to avoid this behavior.

Instead, when defining a new CursorHold autocommand, force
update the last cursor position.

See https://github.com/vim/vim/issues/2053

### CODE REVIEW

**Comment by zeertzjq** [comment]
I'm considering making a PR at Vim repository.

**Comment by zeertzjq** [comment]
Oh, this is not applicable to Vim, as Vim doesn't stores last `CursorMoved` position and only triggers `CursorMoved` from main loop.

**Comment by zeertzjq** [comment]
Oh, this is not applicable to Vim, as Vim doesn't stores last `CursorMoved` position per window and only triggers `CursorMoved` from main loop.

**Review by zeertzjq — COMMENTED** [review]
I'm not sure whether this is the best solution. BTW, there are also `CursorMovedI` and `CursorMovedP`.

**Comment by mjlbach** [comment]
> I'm not sure whether this is the best solution. BTW, there are also CursorMovedI and CursorMovedP.

For whatever reason, these don't seem to have the same issue of immediately triggering.

**Comment by mjlbach** [comment]
Added a test. @zeertzjq I personally think it is fine to address the issue CursorMoved independently of other autocommands (for which we don't have reported issues yet) as this fixes a weird quirk that affects gitgutter and other plugins. LMK what you think.

File: test/functional/autocmd/cursormoved_spec.lua [hunk 1]
```diff
@@ -31,4 +31,15 @@ describe('CursorMoved', function()
     eq({'aaa'}, funcs.nvim_buf_get_lines(eval('g:buf'), 0, -1, true))
     eq(0, eval('g:cursormoved'))
   end)
+
+  it("is not triggered by cursor movement prior to first CursorMoved instantiation", function()
+    source([[
+    " Disable loading matchparen to avoid masking the behavior by pre-defining a valid autocommand
+    let g:loaded_matchparen = 1
```
Comment (bfredl) [inline test/functional/autocmd/cursormoved_spec.lua:38]: I think this is too late, you need to use `clear{args={'--cmd', 'let g:loaded_matchparen = 1'}}` before source to disable it before plugin/ files are loaded.

Comment (mjlbach) [reply test/functional/autocmd/cursormoved_spec.lua:38]: Oh really? Because it causes a failure on master, but not on this branch...

Comment (mjlbach) [reply test/functional/autocmd/cursormoved_spec.lua]: Ah, thanks. resolved (I think).

File: test/functional/autocmd/cursormoved_spec.lua [hunk 2]
```diff
@@ -31,4 +31,14 @@ describe('CursorMoved', function()
     eq({'aaa'}, funcs.nvim_buf_get_lines(eval('g:buf'), 0, -1, true))
     eq(0, eval('g:cursormoved'))
   end)
+
+  it("is not triggered by cursor movement prior to first CursorMoved instantiation", function()
+    source([[
+    let g:cursormoved = 0
+    " Move the cursor by inserting text
+    call nvim_feedkeys('aaa', 'i', v:true)
```
Comment (zeertzjq) [inline test/functional/autocmd/cursormoved_spec.lua:39]:
```suggestion
    call nvim_feedkeys('aaa<Esc>', 'i', v:true)
```

Comment (zeertzjq) [inline test/functional/autocmd/cursormoved_spec.lua:39]: `nvim_feedkeys()` does execute typeahead immediately and stays in Insert mode after typeahead is executed.
```suggestion
    normal aaa
```

Comment (mjlbach) [reply test/functional/autocmd/cursormoved_spec.lua]: I'm not sure why this matters, since the test only needs to induce a shift in the cursor position (and expectedly fails on master like it should), but I changed it.

Comment (zeertzjq) [reply test/functional/autocmd/cursormoved_spec.lua]: Oh, actually even if this line is removed, this test still fails on `master`.

**Review by zeertzjq — APPROVED** [review]

File: test/functional/autocmd/cursormoved_spec.lua (hunk 2 above)
Comment (mjlbach) [reply test/functional/autocmd/cursormoved_spec.lua]: You are right, I'm actually a bit confused about why this test would fail but the one above it would not?

Comment (zeertzjq) [reply test/functional/autocmd/cursormoved_spec.lua]: `w_last_cursormoved` is always updated when entering a new window:
<https://github.com/neovim/neovim/blob/95803f0e902278079e5876082465b1910c819947/src/nvim/window.c#L4594>

Comment (mjlbach) [reply test/functional/autocmd/cursormoved_spec.lua]: Ah, thanks! makes sense. I simplified the test.
