### PR TITLE
fix(man.lua): E95 when raw manpage content is piped into :Man

### LINKED ISSUE #30132: E95: Buffer with this name already exists when Man is invoked as a $MANPAGER
### Problem

I invoke Man as a $MANPAGER from a terminal within neovim.
I do this by using [neovim-remote](https://github.com/mhinz/neovim-remote) plugin and setting `MANPAGER="nvr +'Man!' -"`
`init_pager` in `man.lua` crashes if there's already an open buffer for the man pages.

The line responsible for the error is this one:
`vim.cmd.file({ 'man://' .. fn.fnameescape(ref):lower(), mods = { silent = true } })`
It tries to rename the buffer to a name that's already taken.

Suggested solution:
Check if there's already a buffer with that name and go to that existing buffer if so. 

### Steps to reproduce

* Add [neovim-remote](https://github.com/mhinz/neovim-remote) plugin.
* Add this line to your **init.vim**: `let $MANPAGER="nvr +'Man!' -"`
* Start a terminal: `:term`
* Run `man ls`
* Go back to the terminal
* Run `man ls` again

I don't know if it's possible to use neovim's builtin remote functionality for $MANPAGER. If it is possible, then the error could be reproduced without any plugins.

### Expected behavior

Don't crash and go to the existing buffer instead

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

No Man in vim

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

### PR DESCRIPTION
**Pull request by JTBett**
Problem: 
    When piping raw manpage content into :Man!, the buffer name is set to 'man://.. ref'. However, the existing check  only verifies whether the buffer name starts with 'man://', rather than checking for an exact match.
    `if not fn.bufname('%'):match('man://') then -- Avoid duplicate buffers, E95.`
    This allows :Man! to attempt creating a buffer with a already in use name, triggering E95: Buffer with this name already exists.

Solution:
    Instead of matching just the 'man://' prefix, the new logic checks for an exact match of the buffer name. If the buffer already exists, a unique name is assigned using the format:  `man://<ref>_copy` and `man://<ref>_copy_copy...`, for continuous calls.
    The solution preserves the previous behavior while supporting the creation of multiple buffers with the same man page contents.

Testing:

- Verified that opening a new manpage works as expected.
- Tested piping raw content into :Man!, ensuring no duplicate buffer errors occur.
- Ensured that multiple calls to :Man! create uniquely named buffers (_copy suffix).
- Added test coverage for the newly implemented behavior.

Fix #30132

### CODE REVIEW

File: runtime/lua/man.lua [hunk 1]
```diff
@@ -639,8 +639,20 @@ function M.init_pager()
...
+  -- Raw manpage into (:Man!) overlooks `match('man://')` condition,
+  -- so if the buffer already exists, create new with a non existing name.
+  if vim.fn.bufexists(man_bufname) == 1 then
+    local new_bufname = man_bufname
+    while vim.fn.bufexists(new_bufname) == 1 do
+      new_bufname = new_bufname .. '_copy'
+    end
+    vim.cmd.file({ new_bufname, mods = { silent = true } })
+  else
+    if not fn.bufname('%'):match('man://') then -- Avoid duplicate buffers, E95.
```
Comment (justinmk) [inline runtime/lua/man.lua:653]:
```suggestion
  elseif not fn.bufname('%'):match('man://') then -- Avoid duplicate buffers, E95.
```

File: runtime/lua/man.lua [hunk 2]
```diff
@@ -639,8 +639,20 @@ function M.init_pager()
...
-  if not fn.bufname('%'):match('man://') then -- Avoid duplicate buffers, E95.
-    vim.cmd.file({ 'man://' .. fn.fnameescape(ref):lower(), mods = { silent = true } })
+  local man_bufname = 'man://' .. fn.fnameescape(ref):lower()
+
+  -- Raw manpage into (:Man!) overlooks `match('man://')` condition,
+  -- so if the buffer already exists, create new with a non existing name.
+  if vim.fn.bufexists(man_bufname) == 1 then
+    local new_bufname = man_bufname
+    while vim.fn.bufexists(new_bufname) == 1 do
+      new_bufname = new_bufname .. '_copy'
```
Comment (justinmk) [inline runtime/lua/man.lua:649]: the name is a uri. how about something like this,

```suggestion
      new_bufname = man_bufname .. '/' .. tostring(i)
```

File: runtime/lua/man.lua [hunk 3]
```diff
@@ -639,8 +639,19 @@ function M.init_pager()
...
-  if not fn.bufname('%'):match('man://') then -- Avoid duplicate buffers, E95.
-    vim.cmd.file({ 'man://' .. fn.fnameescape(ref):lower(), mods = { silent = true } })
+  local man_bufname = 'man://' .. fn.fnameescape(ref):lower()
+
+  -- Raw manpage into (:Man!) overlooks `match('man://')` condition,
+  -- so if the buffer already exists, create new with a non existing name.
+  if vim.fn.bufexists(man_bufname) == 1 then
+    local new_bufname = man_bufname
+    while vim.fn.bufexists(new_bufname) == 1 do
+      new_bufname = man_bufname .. '?dedup=' .. tostring(i)
```
[the remark this answers is not in the document]
Comment (JTBett) [reply runtime/lua/man.lua:649]: From a user perspective `new` seems to be the most user-friendly designation.

**Comment by JTBett** [comment]
I will be updating the functional tests tomorrow. For lint, all i need to do is lower case 'Fix'?

**Comment by clason** [comment]
For `lintcommit`, yes (and provide a scope). For `lint`, you can start with `make formatlua` -- but the linters report actual issues beside formatting.

File: runtime/lua/man.lua [hunk 4]
```diff
@@ -639,8 +639,20 @@ function M.init_pager()
...
+  -- Raw manpage into (:Man!) overlooks `match('man://')` condition,
+  -- so if the buffer already exists, create new with a non existing name.
+  if vim.fn.bufexists(man_bufname) == 1 then
+    local new_bufname = man_bufname
+    local i = 1
+    while vim.fn.bufexists(new_bufname) == 1 do
+      new_bufname = man_bufname .. '?new=' .. tostring(i)
+      i = i + 1
+    end
+    vim.cmd.file({ new_bufname, mods = { silent = true } })
```
Comment (justinmk) [inline runtime/lua/man.lua:653]: nit (untested)
```suggestion
    local new_bufname = man_bufname
    for i = 1, 100 do
        if vim.fn.bufexists(new_bufname) == 0 then
            break
        end
        new_bufname = ('%s?new=%s'):format(man_bufname, i)
    end
    vim.cmd.file({ new_bufname, mods = { silent = true } })
```

Comment (JTBett) [reply runtime/lua/man.lua:653]: Should we define a behavior if new buffers exceed the 100 ceiling? Even if that behavior is just to avoid resulting in E95, since there were no changes to the way we avoid said error.

**Comment by JTBett** [comment]
If squash is intended, what would be the safest way to squash it in this repo?

**Comment by justinmk** [comment]
squash is intended. are you going to finish this?

File: runtime/lua/man.lua (hunk 4 above)
Comment (justinmk) [reply runtime/lua/man.lua]: idk, is that a blocker that we need to decide now?

**Comment by JTBett** [comment]
finishing as we speak

**Review by justinmk — APPROVED** [review]
