### PR TITLE
fix(lua): make vim.str_utfindex and vim.str_byteindex handle NUL bytes

### LINKED ISSUE #16290: vim.str_utfindex and vim.str_byteindex treat NUL byte as the end of the string
### Neovim version (nvim -v)

0.5.1

### How to reproduce the issue

Don't know what to say other than "proof by demonstration":
```lua
print(pcall(vim.str_utfindex, 'я\0ъ'))
print(pcall(vim.str_utfindex, 'я\0ъ', 4))
print(pcall(vim.str_byteindex, 'я\0ъ', 3))
```

### Expected behavior

```
true 3 3
true 3 3
true 5
```

### Actual behavior

```
true 1 1
true 1 1
false index out of range
```

### PR DESCRIPTION
**Pull request by bfredl**
fixes #16290

### CODE REVIEW

File: test/functional/lua/vim_spec.lua [hunk 1]
```diff
@@ -158,17 +158,20 @@ describe('lua stdlib', function()
   end)
 
   it("vim.str_utfindex/str_byteindex", function()
-    exec_lua([[_G.test_text = "xy åäö ɧ 汉语 ↥ 🤦x🦄 å بِيَّ"]])
-    local indicies32 = {[0]=0,1,2,3,5,7,9,10,12,13,16,19,20,23,24,28,29,33,34,35,37,38,40,42,44,46,48}
-    local indicies16 = {[0]=0,1,2,3,5,7,9,10,12,13,16,19,20,23,24,28,28,29,33,33,34,35,37,38,40,42,44,46,48}
+    exec_lua([[_G.test_text = "xy åäö ɧ 汉语 ↥ 🤦x🦄 å بِيَّ\x00ъ"]])
```
Comment (zeertzjq) [inline test/functional/lua/vim_spec.lua:161]:
```suggestion
    exec_lua([[_G.test_text = "xy åäö ɧ 汉语 ↥ 🤦x🦄 å بِيَّ\000ъ"]])
```
