### PR TITLE
[RDY] lsp: fix diagnostic reported on terminating EOL character

### LINKED ISSUE #13476: lsp.diagnostic.set_loclist(): invalid range returned by on_public_diagnostics() with gopls and rust-analyzer when diagnostic includes terminating newline
- `nvim --version`: `NVIM v0.5.0-31787a9`
- nvim-lsp version(commit hash): 76f11625481eddb7b
- What language server(If the problem is related to a specific language server): `gopls`
- Operating system/version: Ubuntu 18.04
- Terminal name/version: Kitty
- `$TERM`: `xterm-kitty`

### How to reproduce the problem from neovim startup

**init.vim**
```vim
set runtimepath^=~/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig

augroup UPDATE_DIAGNOSTICS_LOCLIST
	autocmd!
	autocmd InsertLeave * lua vim.lsp.diagnostic.set_loclist({open_loclist = false})
augroup END

lua << EOF

require'lspconfig'.gopls.setup{
	cmd = {"gopls", "serve"},
	settings = {
		gopls = {
			analyses = {
				unusedparams = true,
			},
			staticcheck = true,
		},
	},
}
EOF
```

**main.go**
```go
package main

func main() {

	for {
}
```

1. Open `main.go`.
1. Go into insert mode then get back to normal mode, the following error is then triggered:

```text
Error detected while processing InsertLeave Autocommands for "*":
E5108: Error executing lua ...t_nvimci4S1X/usr/share/nvim/runtime/lua/vim/lsp/util.lua:1357: Index out of bounds
```

### PR DESCRIPTION
**Pull request by mjlbach**
Closes #13476

CC: @vigoux @ChrisAmelia
 
More details in the issue, but we we report an EOL character to the language server (as vim saves files with these), so it can return the EOL character itself as part of a diagnostic range. This just sets the loclist to put the diagnostic on the last valid line, fixing gopls/rust-analyzer.

### CODE REVIEW

File: runtime/lua/vim/lsp/diagnostic.lua [hunk 1]
```diff
@@ -1185,9 +1185,13 @@ function M.set_loclist(opts)
   local items = {}
   local insert_diag = function(diag)
     local pos = diag.range.start
+    -- Offset for diagnostic reported on terminating EOL character
     local row = pos.line
-    local col = util.character_offset(bufnr, row, pos.character)
+    if row == vim.fn.line('$') then
```
Comment (vigoux) [inline runtime/lua/vim/lsp/diagnostic.lua:1190]: Maybe `nvim_buf_line_count` is better here ?

Comment (mjlbach) [reply runtime/lua/vim/lsp/diagnostic.lua]: Done

**Review by mfussenegger — COMMENTED** [review]
I wonder if `character_offset` should in general be a bit more lenient?

If diagnostics can have positions on the terminating EOL character I think other structures which use locations can do so too. Having this specific for `set_loclist` may be too narrow and we'd have to add this logic in other places too?

**Comment by mjlbach** [comment]
> I wonder if character_offset should in general be a bit more lenient?

Was also wondering about this.

> Having this specific for set_loclist may be too narrow and we'd have to add this logic in other places too?

I think in this case it's fine, because you want the loclist to point to (at most) point to the last buffer line. The other option would be to automatically check diagnostics in the handler to adjust the range of those falling out of the buffer to fall on the end line, but that feels a bit heavy to me. The language server is correct in that the diagnostics are on the terminating endline character.

**Comment by mjlbach** [comment]
I was thinking about this more, and maybe it's a good idea to fix this when we cache diagnostics instead

**Comment by mfussenegger** [comment]
How about something like this?

```
diff --git a/runtime/lua/vim/lsp/util.lua b/runtime/lua/vim/lsp/util.lua
index e33e0109b..6dc683e4b 100644
--- a/runtime/lua/vim/lsp/util.lua
+++ b/runtime/lua/vim/lsp/util.lua
@@ -1420,10 +1420,14 @@ end
 --@param buf buffer id (0 for current)
 --@param row 0-indexed line
 --@param col 0-indexed byte offset in line
 --@returns (number, number) UTF-32 and UTF-16 index of the character in line {row} column {col} in buffer {buf}
 function M.character_offset(buf, row, col)
+  -- Data received from LSP could refer to terminating EOL character
+  if row == api.nvim_buf_get_line_count(buf) then
+    row = row - 1
+  end
   local line = api.nvim_buf_get_lines(buf, row, row+1, true)[1]
   -- If the col is past the EOL, use the line length.
   if col > #line then
     return str_utfindex(line)
   end
```

Or do you see any issue with being too lenient within `character_offset`?

**Comment by mjlbach** [comment]
@mfussenegger If I just make the modification there, I get:

```
E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:1201:
attempt to concatenate local 'line' (a nil value)
```

I'm thinking of instead modifying _diagnostic_lines to accept also the maximum line count of bufnr and check that no lines are out of bounds.

**Comment by teto** [comment]
when using this I get ` /home/teto/neovim/runtime/lua/vim/lsp/diagnostic.lua:517: Cursor position outside buffer`

**Comment by mjlbach** [comment]
@teto Can you try now? 

@mfussenegger I changed it to set the correct diagnostic linenr when we store the diagnostic lines. I tested and this resolves the issue with gopls and rust-analyzer.

File: runtime/lua/vim/lsp/diagnostic.lua [hunk 2]
```diff
@@ -212,12 +212,15 @@ local _bufs_waiting_to_update = setmetatable({}, bufnr_and_client_cacher_mt)
...
-local _diagnostic_lines = function(diagnostics)
+local _diagnostic_lines = function(diagnostics, bufnr)
   if not diagnostics then return end
 
+  local buf_line_count = vim.api.nvim_buf_line_count(bufnr)
   local diagnostics_by_line = {}
   for _, diagnostic in ipairs(diagnostics) do
     local start = diagnostic.range.start
+    -- Account for servers that place diagnostics on terminal newline
+    start.line = math.min(start.line, buf_line_count - 1)
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/diagnostic.lua:223]: What do you think of moving this into the loop here https://github.com/neovim/neovim/blob/c1fbc2ddf15b2f44b615f90b2511349ab974cb83/runtime/lua/vim/lsp/diagnostic.lua#L267-L271 so that there's only a single place where we mutate the diagnostics?

Comment (mjlbach) [reply runtime/lua/vim/lsp/diagnostic.lua:223]: Yeah, I initially did this to save the cost of getting the line count of the buffer, but I realize now it's a super bad idea for the line count in the line cache and the per buffer cache to not match

**Comment by mjlbach** [comment]
@mfussenegger @teto @vigoux Any last comments, or can we merge?

**Review by mfussenegger — APPROVED** [review]

**Comment by teto** [comment]
this seems to have fixed it for me
