### PR TITLE
fix(extmarks): account for rightleft when drawing virt text

### LINKED ISSUE #25066: Diagnostics virtual_text disappears and hides text when right to left mode is enabled
### Problem

When having an LSP set up and setting the enabling right to left text with `:set rl` two bugs will take place:
1. The diagnostics virtual_text will go away.
2.  If I enter some invalid code so that the LSP complains and shows up an error message, this invalid code becomes hidden as shown below.

[vtext_enabled.webm](https://github.com/neovim/neovim/assets/76184333/7d4ff857-7cd8-491b-89f5-d06f18dd3d97)

Disabling these diagnostics messages using `vim.diagnostic.config({ virtual_text = false })`  fixes the second problem of text being hidden, with the side effect of not having virtual text of these message of course.

[vtext_disabled.webm](https://github.com/neovim/neovim/assets/76184333/131c4c12-72b2-4ed3-a4bd-b01a3e6d3039)

### Steps to reproduce

- Ensure that you have an LSP installed in your system (I'm using `lua-language-server` in this `minimal_config.lua` example config).
- `nvim --clean -u minimal_config.lua`
- Type some invalid code for the LSP to  show an error message.
- :set rl

Minimal config:
```
for name, url in pairs{
    -- Plugins
    lspconfig = "https://www.github.com/neovim/nvim-lspconfig.git"
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

-- Assuming you have lua-language-server installed in your $PATH
require'lspconfig'.lua_ls.setup{}
```

### Expected behavior

- The diagnostics messages should not go away.
- The text should not hide.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1058+gc422722b2e

### Vim (not Nvim) behaves the same?

Vim doesn't have native LSP support.

### Operating system/version

Arch Linux

### Terminal name/version

XTerm(384)

### $TERM environment variable

xterm-256color

### Installation

https://aur.archlinux.org/neovim-git.git

### PR DESCRIPTION
**Pull request by SleepySwords**
Fixes #25066

### CODE REVIEW

File: src/nvim/drawline.c [hunk 1]
```diff
@@ -346,20 +358,27 @@ static int draw_virt_text_item(buf_T *buf, int col, VirtText vt, HlMode hl_mode,
...
+      } else {
+        col++;
+      }
     }
-    if (col < max_col && linebuf_char[col] == 0) {
-      // If the left half of a double-width char is overwritten,
-      // change the right half to a space so that grid redraws properly,
-      // but don't advance the current column.
+    // If the left half of a double-width char is overwritten,
+    // change the right half to a space so that grid redraws properly,
```
Comment (zeertzjq) [inline src/nvim/drawline.c:378]:
```suggestion
    // If the half of a double-width char is overwritten,
    // change the other half to a space so that grid redraws properly,
```
