### PR TITLE
fix(filetype): make vim.filetype.match() work with contents only

### LINKED ISSUE #22180: Filetype detection by contents causes error
### Describe the bug

Running the last example shown in `:h vim.filetype.match()` results in an error:
```
E5108: Error executing lua vim/filetype.lua:0: attempt to index a nil value                                                                                                                                                   
stack traceback:
        vim/filetype.lua: in function ''
        vim/filetype.lua: in function 'match'
        [string ":lua"]:1: in main chunk
```

### Steps to reproduce

- `nvim --clean`
- `:lua =vim.filetype.match({ contents = { '#!/usr/bin/env bash' } })`

### Expected behavior

No error

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1983+g80bede1df  

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux Mint 20.2

### Terminal name/version

Kitty 0.15

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by smjonas**
Fixes #22180.

### CODE REVIEW

File: runtime/lua/vim/filetype.lua [hunk 1]
```diff
@@ -2449,6 +2449,11 @@ local function match_pattern(name, path, tail, pat)
       return false
     end
   end
+
+  if not name then
```
Comment (gpanders) [inline runtime/lua/vim/filetype.lua:2453]: Maybe move this to the start of the function so it exits right away if name is nil.

**Comment by gpanders** [comment]
Why is `match_pattern` being called at all in this case? If `name` is nil, then `path` and `tail` are either also nil or they are garbage/meaningless values.

We should instead modify `vim.filetype.match` to skip all of the filename-based checks if both `args.filename` and `args.bufnr` are nil, and skip straight to the end where we do content-based matching.

**Comment by gpanders** [comment]
Right now we have

```lua
  if name then
    name = normalize_path(name)
  end
```

But we should put all of the filename based checks in that if branch.

Patch:

```diff
diff --git a/runtime/lua/vim/filetype.lua b/runtime/lua/vim/filetype.lua
index 1f605b72f..be9c6f88d 100644
--- a/runtime/lua/vim/filetype.lua
+++ b/runtime/lua/vim/filetype.lua
@@ -2526,64 +2526,64 @@ function M.match(args)
     name = api.nvim_buf_get_name(bufnr)
   end
 
-  if name then
-    name = normalize_path(name)
-  end
-
   local ft, on_detect
 
-  -- First check for the simple case where the full path exists as a key
-  local path = vim.fn.fnamemodify(name, ':p')
-  ft, on_detect = dispatch(filename[path], path, bufnr)
-  if ft then
-    return ft, on_detect
-  end
+  if name then
+    name = normalize_path(name)
 
-  -- Next check against just the file name
-  local tail = vim.fn.fnamemodify(name, ':t')
-  ft, on_detect = dispatch(filename[tail], path, bufnr)
-  if ft then
-    return ft, on_detect
-  end
+    -- First check for the simple case where the full path exists as a key
+    local path = vim.fn.fnamemodify(name, ':p')
+    ft, on_detect = dispatch(filename[path], path, bufnr)
+    if ft then
+      return ft, on_detect
+    end
 
-  -- Next, check the file path against available patterns with non-negative priority
-  local j = 1
-  for i, v in ipairs(pattern_sorted) do
-    local k = next(v)
-    local opts = v[k][2]
-    if opts.priority < 0 then
-      j = i
-      break
+    -- Next check against just the file name
+    local tail = vim.fn.fnamemodify(name, ':t')
+    ft, on_detect = dispatch(filename[tail], path, bufnr)
+    if ft then
+      return ft, on_detect
     end
 
-    local filetype = v[k][1]
-    local matches = match_pattern(name, path, tail, k)
-    if matches then
-      ft, on_detect = dispatch(filetype, path, bufnr, matches)
-      if ft then
-        return ft, on_detect
+    -- Next, check the file path against available patterns with non-negative priority
+    local j = 1
+    for i, v in ipairs(pattern_sorted) do
+      local k = next(v)
+      local opts = v[k][2]
+      if opts.priority < 0 then
+        j = i
+        break
+      end
+
+      local filetype = v[k][1]
+      local matches = match_pattern(name, path, tail, k)
+      if matches then
+        ft, on_detect = dispatch(filetype, path, bufnr, matches)
+        if ft then
+          return ft, on_detect
+        end
       end
     end
-  end
 
-  -- Next, check file extension
-  local ext = vim.fn.fnamemodify(name, ':e')
-  ft, on_detect = dispatch(extension[ext], path, bufnr)
-  if ft then
-    return ft, on_detect
-  end
+    -- Next, check file extension
+    local ext = vim.fn.fnamemodify(name, ':e')
+    ft, on_detect = dispatch(extension[ext], path, bufnr)
+    if ft then
+      return ft, on_detect
+    end
 
-  -- Next, check patterns with negative priority
-  for i = j, #pattern_sorted do
-    local v = pattern_sorted[i]
-    local k = next(v)
+    -- Next, check patterns with negative priority
+    for i = j, #pattern_sorted do
+      local v = pattern_sorted[i]
+      local k = next(v)
 
-    local filetype = v[k][1]
-    local matches = match_pattern(name, path, tail, k)
-    if matches then
-      ft, on_detect = dispatch(filetype, path, bufnr, matches)
-      if ft then
-        return ft, on_detect
+      local filetype = v[k][1]
+      local matches = match_pattern(name, path, tail, k)
+      if matches then
+        ft, on_detect = dispatch(filetype, path, bufnr, matches)
+        if ft then
+          return ft, on_detect
+        end
       end
     end
   end
```

**Review by gpanders — APPROVED** [review]
