### PR TITLE
fix: fix empty line in lsp log after each run

### LINKED ISSUE #13879: lsp.log file gets filled up with line feed characters
### Actual behaviour
The log file generated by nvim's built-in LSP implementation gets filled up with line feed characters and no other contents in it.

```
$ wc -l ~/.cache/nvim/lsp.log
      21 /Users/gian/.cache/nvim/lsp.log
```
```
$ hexdump -C ~/.cache/nvim/lsp.log
00000000  0a 0a 0a 0a 0a 0a 0a 0a  0a 0a 0a 0a 0a 0a 0a 0a  |................|
00000010  0a 0a 0a 0a 0a                                    |.....|
00000015
```

I also pasted the log file as-is below to show that it's effectively empty.

### Expected behaviour
I expect the log file to just stay empty, with no spurious line feed characters if nothing is to be logged.
I don't know if one of the language servers I use is at fault here but I mainly use Go with `gopls` and Rust with `rust-analyzer`, in Neovim.
 
### Health check
<details>
<summary>Checkhealth result</summary>

```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: rust_analyzer: configuration checked.
  - INFO: gopls: configuration checked.
```

</details>

### LSP log (located at `~/.cache/nvim/lsp.log`)

<details>
<summary>Log file</summary>

```






















```
</details>

### Nvim version
<details>
<summary>version</summary>

```
NVIM v0.5.0-dev+nightly-16-gb96db38af
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210204-13668-10drhzx/build/config -I/tmp/neovim-20210204-13668-10drhzx/src -I/opt/homebrew/include -I/tmp/neovim-20210204-13668-10drhzx/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20210204-13668-10drhzx/build/src/nvim/auto -I/tmp/neovim-20210204-13668-10drhzx/build/include
Compiled by gian@mercury.fritz.box

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-b96db38/share/nvim"

Run :checkhealth for more info
```

</details>

`nvim-lspconfig` version: `2eb8567`

### PR DESCRIPTION
**Pull request by TheAlakazam**
Fixes: #13879
Instead of empty line at the end of session, create the following at the start of the session:
`[ START ] LSP logging initiated <timestamp>`

### CODE REVIEW

File: runtime/lua/vim/lsp/log.lua [hunk 1]
```diff
@@ -32,6 +32,8 @@ do
 
   vim.fn.mkdir(vim.fn.stdpath('cache'), "p")
   local logfile = assert(io.open(logfilename, "a+"))
+  -- Start message for logging
+  logfix:write(string.format("[ START ] LSP logging initiated: %s\n", os.date(log_date_format)))
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/log.lua:36]:
```suggestion
  logfile:write(string.format("[ START ] LSP logging initiated: %s\n", os.date(log_date_format)))
```

Typo

Might also be worth sticking to the format of the regular log messages and move the date further to the start?


```suggestion
  logfile:write(string.format("[ START ] %s ] LSP logging initiated\n", os.date(log_date_format)))
```

**Comment by mjlbach** [comment]
@mfussenegger This looks fine to me?

**Comment by mjlbach** [comment]
@TheAlakazam Can you squash your commits, we also typically prefix commit messages to the lsp components with the feature name, for example: `lsp: add explicit log mention on language server log start`

**Comment by mfussenegger** [comment]
> @mfussenegger This looks fine to be merged now?

yes :+1:
