### PR TITLE
[RFC] vim-patch:8.0.0308,8.0.0325,8.0.0326,8.0.0437,8.0.0612,8.0.0680

### LINKED ISSUE #6869: packloadall seems to augment the runtimepath incorrectly
- `nvim --version`: v0.2.0
- Vim (version: 8.0 patches: 1-563) behaves differently? yes
- Operating system/version: macOS 10.12.4 (16E195)
- Terminal name/version: iTerm2 v3 (Build 3.1.20170530-nightly)
- `$TERM`: tmux-256color

### Actual behaviour

After running `:packloadall` the `'runtimepath'`, all pack plugin files get appended to the end:

```
$HOME/.config/nvim
/etc/xdg/nvim
$HOME/.local/share/nvim/site
/usr/local/share/nvim/site
/usr/share/nvim/site
/usr/local/Cellar/neovim/0.2.0/share/nvim/runtime
/usr/share/nvim/site/after
/usr/local/share/nvim/site/after
$HOME/.local/share/nvim/site/after
/etc/xdg/nvim/after
$HOME/.config/nvim/after
                             <-- pack plugin files here                       
                             <-- pack "after" plugin files here                       
```

This means, for example, that a pack-provided syntax file cannot prevent the bundled `$VIMRUNTIME` one from loading; example: https://stackoverflow.com/questions/10079521/vim-loading-multiple-syntax-files-instead-of-just-one

### Expected behaviour

The `'runtimepath'` should be augmented in the same order that Vim does:

```
$HOME/.vim,
                             <-- pack plugin files here
$VIM/vimfiles,
$VIMRUNTIME,
$VIM/vimfiles/after,
$HOME/.vim/after
                             <-- pack "after" plugin files here                       
```

### LINKED ISSUE #7200: Neovim Doesn't load a plugin which uses `b:did_ftplugin` while Vim does
I don't know if it's a problem with the plugin or the editor. I believe it's the editor because Vim behaves differently.

```
$ nvim --version
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: 8.0) behaves differently? **YES**
- Operating system/version: Arch Linux
- Terminal name/version (`$TERM`): `rxvt-unicode-256color`

### Steps to reproduce
```
cd ~/.config
mv nvim nvim.tmp
mkdir nvim
cd nvim
mkdir -p pack/not-loading/start
git clone https://github.com/lervag/vimtex pack/not-loading/start/tex
curl 'http://abacus.bates.edu/~etowne/beamersample.tex' -O
nvim beamersample.tex
:VimtexCompile
```

### Actual behaviour

`nvim` doesn't call `vimtex#init()` in `pack/not-loading/start/tex/ftplugin/tex.vim` because the 2nd condition `if exists('b:did_ftplugin')` comes out as true and the `tex.vim` `finish`es it.

### Expected behaviour

`nvim` will load `vimtex` just like `vim`.

### PR DESCRIPTION
**Pull request by jamessan**
#### vim-patch:8.0.0308

Problem:    When using a symbolic link, the package path will not be inserted
            at the right position in 'runtimepath'. (Dugan Chen, Norio Takagi)
Solution:   Resolve symbolic links when finding the right position in
            'runtimepath'. (Hirohito Higashi)

https://github.com/vim/vim/commit/2f9e575583c2ad3978ee3d0f790eeff7df56bd6c

#### vim-patch:8.0.0325

Problem:    Packadd test does not clean up symlink.
Solution:   Delete the link. (Hirohito Higashi)

https://github.com/vim/vim/commit/913727e56761d57aaba61197c2d3485418dea7eb

#### vim-patch:8.0.0326

Problem:    Packadd test uses wrong directory name.
Solution:   Use the variable name value. (Hirohito Higashi)

https://github.com/vim/vim/commit/24f8f543d4036c5d2ce4ea6973a174cf2176cb72

#### vim-patch:8.0.0437

Problem:    The packadd test does not create the symlink correctly and does
            not test the right thing.
Solution:   Create the directory and symlink correctly.

https://github.com/vim/vim/commit/644df41c44cbdfacdedbba55ef77a6c6031eccd8

#### vim-patch:8.0.0612

Problem:    Package directories are added to 'runtimepath' only after loading
            non-package plugins.
Solution:   Split off the code to add package directories to 'runtimepath'.
            (Ingo Karkat, closes vim/vim#1680)

https://github.com/vim/vim/commit/ce876aaa9a250a5a0d0e34b3a2625e51cf9bf5bb

#### vim-patch:8.0.0680

Problem:    Plugins in start packages are sourced twice. (mseplowitz)
Solution:   Use the unmodified runtime path when loading plugins (test by Ingo
            Karkat, closes vim/vim#1801)

https://github.com/vim/vim/commit/07ecfa64a18609a986f21d6132d04ee8934f3200

Closes #7200 
Closes #6869

### CODE REVIEW

File: src/nvim/main.c [hunk 1]
```diff
@@ -1291,15 +1291,22 @@ static void set_window_layout(mparm_T *paramp)
...
     // :packloadall command.
+    // Make a copy of 'runtimepath', so that source_runtime does not use the
+    // pack directories.
     if (!did_source_packages) {
+      rtp_copy = vim_strsave(p_rtp);
       add_pack_start_dirs();
     }
 
-    source_runtime((char_u *)"plugin/**/*.vim", DIP_ALL | DIP_NOAFTER);  // NOLINT
+    source_in_path(rtp_copy, (char_u *)"plugin/**/*.vim",  // NOLINT
```
Comment (justinmk) [inline src/nvim/main.c]: the vim patch does `rtp_copy == NULL ? p_rtp : rtp_copy`

Comment (jamessan) [inline src/nvim/main.c]: Vim checks for `NULL`, we don't.  `vim_strsave` is a very thin wrapper around `xstrdup` for us, mainly handling casting.

Comment (justinmk) [inline src/nvim/main.c]: yes, but isn't it possible that `rtp_copy` is null if the condition on line 1302 is false?

**Review by justinmk — APPROVED** [review]
