### PR TITLE
Fix out of bounds error when vim.lsp.buf.format does full line replacements

### LINKED ISSUE #20116: vim.lsp.buf.format() failing when using clangd to sort includes
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1039-gf32fd19f1

### Language server name/version

clangd version 13.0.0

### Operating system/version

Windows 10

### Steps to reproduce using "nvim -u minimal_init.lua"

0. Create a test directory and put the `minimal_init.lua` in it. switch to the test directory.
1. open a new file with `nvim -u minimal_init.lua test.cpp`
2. go to insert mode and enter the text:
```
#include <algorithm>
#include "whatever.h"
```
3. goto normal mode and write `:lua vim.lsp.buf.format()` and press enter.

### Expected behavior

The include lines should be sorted so that the buffer contains:
```
#include "whatever.h"
#include <algorithm>
```
and no error message displayed.

### Actual behavior

no changes are applied to the buffer and an error message is displayed:
```
E5108: Error Executing lua:  ...ram Files\Neovim\share\nvim\runtime/lua/vim/lsp/util.lua: end_col out of bounds
stack traceback:
        [C]: in function 'nvim_buf_set_text'
        ...ram Files\Neovim\share\nvim\runtime/lua/vim/lsp/util.lua:477: in function 'apply_text_edits'
        ...gram Files\Neovim\share\nvim\runtime/lua/vim/lsp/buf.lua:230: in function <...gram Files\Neovim\share\nvim\runtime/lua/vim/lsp/buf.lua:188>
```

### Log file

https://gist.github.com/ofwinterpassed/88786c8bf3152afc4c02194b4f7c6924

### PR DESCRIPTION
**Pull request by ofwinterpassed**
fixes #20116 

This takes care of the out of bounds error reported in #20116 and replaces #20118

### CODE REVIEW

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -474,7 +474,20 @@ function M.apply_text_edits(text_edits, bufnr, offset_encoding)
       end
       has_eol_text_edit = true
     end
-    api.nvim_buf_set_text(bufnr, e.start_row, e.start_col, e.end_row, e.end_col, e.text)
+
+    local last_line = get_line(bufnr, e.end_row)
+
+    -- If the replacement is over full lines it is safer to use api.nvim_buf_set_lines
+    if e.end_col >= #last_line and e.start_col == 0 then
+      -- When replacing whole lines there seem to always be an extra newline at the end of the new
```
Comment (smjonas) [inline runtime/lua/vim/lsp/util.lua:482]:
```suggestion
      -- When replacing whole lines there seems to always be an extra newline at the end of the new
```

**Comment by ofwinterpassed** [comment]
Hi, this is my first contribution to neovim and also my first attempt at lua except for my neovim config. What I can see the error in the FreeBSD build is not related to my changes. Would be awesome if someone with more experience with the neovim codebase could help me out a bit. This PR makes a quite big improvement for my workflow.

File: runtime/lua/vim/lsp/util.lua [hunk 2]
```diff
@@ -474,7 +474,20 @@ function M.apply_text_edits(text_edits, bufnr, offset_encoding)
...
-    api.nvim_buf_set_text(bufnr, e.start_row, e.start_col, e.end_row, e.end_col, e.text)
+
+    local last_line = get_line(bufnr, e.end_row)
+
+    -- If the replacement is over full lines it is safer to use api.nvim_buf_set_lines
+    if e.end_col >= #last_line and e.start_col == 0 then
+      -- When replacing whole lines there seems to always be an extra newline at the end of the new
+      -- text. So we remove it.
+      if e.text[#e.text] == '' then
+        table.remove(e.text, #e.text)
```
Comment (zeertzjq) [inline runtime/lua/vim/lsp/util.lua:485]: The test failure may be caused by `e.text` becoming empty here.

File: runtime/lua/vim/lsp/util.lua [hunk 3]
```diff
@@ -474,7 +474,20 @@ function M.apply_text_edits(text_edits, bufnr, offset_encoding)
       end
       has_eol_text_edit = true
     end
-    api.nvim_buf_set_text(bufnr, e.start_row, e.start_col, e.end_row, e.end_col, e.text)
+
+    local last_line = get_line(bufnr, e.end_row)
+
+    -- If the replacement is over full lines it is safer to use api.nvim_buf_set_lines
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/util.lua:480]: Why is it safer?

File: runtime/lua/vim/lsp/util.lua (hunk 2 above)
Comment (ofwinterpassed) [reply runtime/lua/vim/lsp/util.lua:485]: Thanks!  That seems to have been the issue. I'm still not super happy about the whole solution but the two use cases I got errors for works with the current change. It would be awesome if someone could help me write a test for this.

File: runtime/lua/vim/lsp/util.lua [hunk 4]
```diff
@@ -474,7 +474,20 @@ function M.apply_text_edits(text_edits, bufnr, offset_encoding)
...
+    if e.end_col >= #last_line and e.start_col == 0 then
+      -- When replacing whole lines there seems to always be an extra newline at the end of the new
+      -- text. So we remove it.
+      if #e.text > 1 and e.text[#e.text] == '' then
+        table.remove(e.text, #e.text)
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/util.lua:485]: Isn't this kinda similar to what is happening above in line 464 and 471?

**Review by mfussenegger — COMMENTED** [review]
Could you add a test case for this?

File: runtime/lua/vim/lsp/util.lua (hunk 4 above)
Comment (ofwinterpassed) [reply runtime/lua/vim/lsp/util.lua:485]: Similar yes but not the same. Those cases looks at the line ranges in the buffer that are to be replaced. I'm looking at the column ranges in the buffer to know if they represent a full set on lines (i.e. if the first line start at the beginning and the last lines ends at the end). The inner if looks at the new text that is to be inserted and ensures that there isn't an extra empty line in there. That happens because the replacement text in these cases include the newline at the end of the block but neovim does replacement in a way that it wants to handle the linebreaks by itself. Another solution would be if we could do the replacement in a way that included the new line in the buffer and replace with the exact content of `text_edit.newText` without splitting it to several lines manually. I tried to find alternatives to `nvim_buf_set_text` that can do that but I was unsuccessful.

File: runtime/lua/vim/lsp/util.lua (hunk 3 above)
Comment (ofwinterpassed) [reply runtime/lua/vim/lsp/util.lua:480]: Because it handles the case of `e.end_col` being out of bounds.

Comment (ofwinterpassed) [reply runtime/lua/vim/lsp/util.lua:480]: To add some context this is from the nvim documentation:
```
                                                         *nvim_buf_set_text()*
nvim_buf_set_text({buffer}, {start_row}, {start_col}, {end_row}, {end_col},
                  {replacement})
    Sets (replaces) a range in the buffer

    This is recommended over |nvim_buf_set_lines()| when only modifying parts
    of a line, as extmarks will be preserved on non-modified parts of the
    touched lines.

    Indexing is zero-based. Row indices are end-inclusive, and column indices
    are end-exclusive.

    To insert text at a given `(row, column)` location, use `start_row =
    end_row = row` and `start_col = end_col = col`. To delete the text in a
    range, use `replacement = {}`.

    Prefer |nvim_buf_set_lines()| if you are only adding or deleting entire
    lines.
```
So the set_text is recommended when **only** modifying parts of a line and the set_lines is recommended when replacing whole lines.

**Comment by ofwinterpassed** [comment]
@mfussenegger  I will try to add a test case. Haven't done that before so might take me some time to figure out the correct way of doing it.

**Comment by ofwinterpassed** [comment]
Is there a step by step guide on how to compile and run the tests? I tried running `make test` which seems to do nothing, `make unittest` and `make functionaltest` which gives me `make: *** no rule to make target 'functionaltest'. Stop.`

**Comment by clason** [comment]
> make functionaltest

That _should_ work. You need to be at the top level of the repo, though.

**Comment by ofwinterpassed** [comment]
Oh, I assumed you would call make from the build directory. Works fine from the root of the repo. Thank you very much @clason

**Comment by ofwinterpassed** [comment]
@mfussenegger I added two tests representing the two cases that I identified as failing. I tested them without the fix and both fails and with the fix and they pass. I'm ready for more feedback :smile:

**Comment by ofwinterpassed** [comment]
I changed this to draft since I realized that I can improve the solution.

**Comment by ofwinterpassed** [comment]
Reopened with an improved solution and more tests.

**Comment by ofwinterpassed** [comment]
@mfussenegger can we run the workflows on this again?

File: runtime/lua/vim/lsp/util.lua [hunk 5]
```diff
@@ -474,7 +474,31 @@ function M.apply_text_edits(text_edits, bufnr, offset_encoding)
...
+    -- Make sure we don't go out of bounds for e.end_col
+    e.end_col = math.min(#last_line, e.end_col)
+
+    -- If the replacement is over full lines it is recommended to use nvim_buf_set_lines
+    -- see. https://neovim.io/doc/user/api.html#nvim_buf_set_test()
+    if e.end_col == #last_line and e.start_col == 0 then
+      api.nvim_buf_set_lines(bufnr, e.start_row, e.end_row + 1, false, e.text)
+    else
+      api.nvim_buf_set_text(bufnr, e.start_row, e.start_col, e.end_row, e.end_col, e.text)
+    end
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/util.lua:501]: Even if it is recommended to use `nvim_buf_set_lines` when inserting or deleting lines, this comment still doesn't explain why it is necessary to use it here. If `end_col` is sanitized to avoid out-of-bounds errors, why is using `nvim_buf_set_text` not good enough in all cases?

**Review by mfussenegger — COMMENTED** [review]
I still think that some of this could be integrated into the clipping logic already in place further above in the method.

File: runtime/lua/vim/lsp/util.lua (hunk 5 above)
Comment (ofwinterpassed) [reply runtime/lua/vim/lsp/util.lua:501]: It strictly isn't necessary for this fix anymore.  I kept it after the refactor since I already did the change and it is recommended. There is no explanation in the docs for why it is recommended but my guess is that it is faster. If you prefer that I remove that part from this PR I can do that and investigate the difference before possibly suggesting the change in a separate PR. Tell me which way you prefer.

**Comment by ofwinterpassed** [comment]
The clipping logic further above is handling a special case where the row is out of bounds while my code handles a case when the column is out of bounds. While it is true that some hypothetical edits might have both errors and the code above are sufficient in those cases. I can't  see a way to integrate the cases since the column out of bounds error can (and do) happen completely independently of the rows being out of bounds.

**Comment by ofwinterpassed** [comment]
I have an idea about how to share a small part of my code with the clipping logic for the row out of bounds code. I'll make this a draft again until I've had the time to do that.

**Comment by ofwinterpassed** [comment]
So, another round. I did my best to combine the clipping with the code above it in the file for handling rows being out of bounds for the buffer. This took me to the conclusion that the best way to handle the case of the whole replacement being out of bounds is to treat that case as a line replacement at the end of the buffer and thus skipping over most of the code in the rest of the loop iteration since it isn't needed for that case. Hopefully you're satisfied with this approach.

**Comment by ofwinterpassed** [comment]
@mfussenegger is this more to your liking?

**Comment by mfussenegger** [comment]
> @mfussenegger is this more to your liking?

Yes looks good now. Thanks for giving it another iteration. I'll give it a try and merge soon
