### PR TITLE
input: never escape CSI bytes and clean up related names and comments

### LINKED ISSUE #13032: Mapping actions to "ě" does not work
- `nvim --version`:
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include

Features: +acl +iconv +tui

- `vim -u DEFAULTS` (version: ) behaves differently? Yes, Vim handles this correctly.
- Operating system/version: Arch linux
- Terminal name/version: Konsole 20.08.1
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:nnoremap ě :echo 'asdf'<CR>
ě
```

### Actual behaviour

Nothing happens.

### Expected behaviour

"asdf" should be printed.

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #13032 

Code in `getchar.c` that treats `CSI` specially has already been removed from Nvim with the removal of `FEAT_GUI`, so there is no need to escape `CSI` bytes.

A lot of comments related to `CSI` reference `FEAT_GUI` code that has already been removed from Nvim, so I cleaned up the comments, and renamed some function names to make them more accurate.

The `<xCSI>` key is now obsolete, as all code that may produce that key has been removed, mostly with the removal of `FEAT_GUI`, and I removed the remaining bits in the first commit of this PR.

Some code unescaping `CSI` has already been removed with the removal of `FEAT_GUI`, so I'll remove all unescaping of `CSI` as well.

### CODE REVIEW

**Comment by zeertzjq** [comment]
The last test fails on `master`:
```
[  ERROR   ] test/functional/ui/input_spec.lua @ 136: input utf sequences that contains CSI (0x9B) can be mapped
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(string) 'ě'
Expected:
(string) 'C49B'
```

File: src/nvim/getchar.c [hunk 1]
```diff
@@ -4041,20 +4012,17 @@ char_u *vim_strsave_escape_csi(char_u *p)
...
+/// vim_strsave_escape_ks().  Works in-place.
+void vim_unescape_ks_csi(char_u *p)
 {
   char_u *s = p, *d = p;
 
   while (*s != NUL) {
     if (s[0] == K_SPECIAL && s[1] == KS_SPECIAL && s[2] == KE_FILLER) {
       *d++ = K_SPECIAL;
       s += 3;
-    } else if ((s[0] == K_SPECIAL || s[0] == CSI)
```
Comment (zeertzjq) [inline src/nvim/getchar.c:4056]: Keeping this should be harmless, as `CSI KS_EXTRA KE_CSI` is not valid UTF-8 anyway. But since other similar unescaping code has already been removed from other functions like `vgetc()` (with the removal of `FEAT_GUI`), I'll remove this `s[0] == CSI` as well.

**Comment by zeertzjq** [comment]
I found some code unescaping `CSI` has already been removed previously, so I'll remove all unescaping of `CSI`.

File: src/nvim/keymap.h [hunk 2]
```diff
@@ -220,7 +220,7 @@ enum key_extra {
   KE_KINS = 79,             // keypad Insert key
   KE_KDEL = 80,              // keypad Delete key
 
-  KE_CSI = 81,              // CSI typed directly
+  // KE_CSI = 81,
```
Comment (bfredl) [inline src/nvim/keymap.h:223]: perhaps some comment text to this like "disabled as this key cannot be typed in neovim UI:s".

**Review by bfredl — APPROVED** [review]

File: src/nvim/keymap.h (hunk 2 above)
Comment (zeertzjq) [reply src/nvim/keymap.h]: I'll add "Nvim doesn't need escaping CSI".
