### PR TITLE
[RDY] vim-patch:8.0.{1514,1519},8.1.1360

### LINKED ISSUE #2641: `getchangelist()` doesn't recognize the `'%'` string
- `vim --version`:      VIM - Vi IMproved 8.0  Included patches: 1-1515
 - Operating system:     Ubuntu 16.04.3 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.6
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.3.1

Hello,

from `:h getchangelist()`:

    Returns the |changelist| for the buffer {expr}. For the use
    of {expr}, see |bufname()| above.

Then, from `:h bufname()`:

    "" or "%" can be used for the current buffer, "#" for the
    alternate buffer.

So, I expected the following command to return the changelist for the current buffer:

    :echo getchangelist('%')

But instead, it returns an empty list, even though `:changes` reports that the buffer has a non-empty changelist.

### LINKED ISSUE #4403: Regression: Buffer is nomodifiable after :s/../\=Function/gn (after 8.1.1345)
**Describe the bug**
Two of my plugins collect match information with `:substitute/.../\=Function()/gn`. Since

    patch 8.1.1345: stuck in sandbox with ":s/../\=Function/gn"
    
    Problem:    Stuck in sandbox with ":s/../\=Function/gn".
    Solution:   Don't skip over code to restore sandbox. (Christian Brabandt)

the buffer is left `nomodifiable`. So it looks like the sandbox is mistakenly kept active after the `:substitute` ends. The above patch (that supposedly should correct this exact issue) does not test `'modifiable'`, and only deals with error cases (normal error and `:throw`) inside `Function()`, but not the normal, successful execution. Vim versions prior to the patch work fine.

**To Reproduce**

    vim --clean -S <(cat <<'EOF'
    func! Foo()
        return submatch(0)
    endfunc
    call setline(1, ['1 aaa', '2 aaa', '3 aaa'])
    %s/aaa/\=Foo()/gn
    if &modifiable | quit! | else | cquit! | endif
    EOF
    )

**Environment:**
 - Vim version 8.1.1345
 - OS: Ubuntu 16.04 64-bit
 - Terminal: GNOME Terminal, GUI

### PR DESCRIPTION
**Pull request by janlazo**
**vim-patch:8.0.1514: getting the list of changes is not easy**
Problem:    Getting the list of changes is not easy.
Solution:   Add the getchangelist() function. (Yegappan Lakshmanan,
            closes vim/vim#2634)
vim/vim@07ad816

**vim-patch:8.0.1519: getchangelist() does not use argument as bufname()**
Problem:    Getchangelist() does not use argument as bufname().
Solution:   Use get_buf_tv(). (Yegappan Lakshmanan, closes vim/vim#2641)
vim/vim@341a64c

**vim-patch:8.1.1360: buffer left 'nomodifiable' after :substitute**
Problem:    Buffer left 'nomodifiable' after :substitute. (Ingo Karkat)
Solution:   Save the value of 'modifiable' earlier' (Christian Brabandt,
            closes vim/vim#4403)
vim/vim@80341bc

Added 8.1.1360 to followup on https://github.com/neovim/neovim/pull/10028. I missed a line change from 8.1.1345.

### CODE REVIEW

File: src/nvim/eval.c [hunk 1]
```diff
@@ -9547,6 +9547,40 @@ static void f_getbufvar(typval_T *argvars, typval_T *rettv, FunPtr fptr)
   }
 }
 
+// "getchangelist()" function
+static void f_getchangelist(typval_T *argvars, typval_T *rettv, FunPtr fptr)
+{
+  tv_list_alloc_ret(rettv, 2);
+  (void)tv_get_number(&argvars[0]);  // issue errmsg if type error
```
Comment (janlazo) [inline src/nvim/eval.c]: Is this actually required for Neovim to issue an error message? I left it WIP because of this and the compiler warning from gcc for an unused return value.

Comment (justinmk) [reply src/nvim/eval.c]: Very weird.  I guess that's why `emsg_off++`  is needed after.

Can assign it to the `vim_ignored` global, to avoid the failed CI.

If the tests pass then let's leave it at that :)

**Comment by justinmk** [comment]
LGTM, still WIP?
