### PR TITLE
lsp: fix utf16 ranges for incremental sync

### LINKED ISSUE #14230: diagnostic became out-of-sync with incremental_sync enabled
- `nvim --version`: NVIM v0.5.0-dev+1180-gacd643bd4
- `vim -u DEFAULTS` (version: ) behaves differently? it doesn't have builtin LSP client
- Operating system/version: Archlinux
- Terminal name/version: kitty 0.19.3 created by Kovid Goyal
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

1. Use this minimal init.vim

```vim
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'neovim/nvim-lspconfig'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close

lua << EOF
-- don't forget to modify this line :) 
local sumneko_root = os.getenv("HOME") .. "/repos/lua-language-server"

require('lspconfig').sumneko_lua.setup {
  cmd = {
    sumneko_root .. "/bin/Linux/lua-language-server",
    "-E",
    sumneko_root .. "/main.lua",
  }
}
require('lspconfig').tsserver.setup {}
EOF
```
2. Setup lua-language-server or tsserver, though the issue is more noticable in sumneko_lua
3. open a file that looks something like this
```lua
-- this is a comment
-- a multiline comment, that is
local foo = 2

print(foo)
```
4. insert multibyte character at the end of the second line, write the file, remove that inserted text
5. the diagnostic became out of sync (or the position get messed up?)

### Actual behaviour

Here are some screencast to better illustrate what I meant. Sorry if the video isn't clear :laughing: 

Here's one with Nerdfont character
https://user-images.githubusercontent.com/51877647/112737033-f7771480-8f89-11eb-854c-827305db091e.mp4

..and here's one with Japanese character, just to make sure it happens with multibyte character and not caused by unicode private use area.
https://user-images.githubusercontent.com/51877647/112737032-ededac80-8f89-11eb-9824-f6f438185719.mp4

also, here's the one with tsserver
https://user-images.githubusercontent.com/51877647/112737073-550b6100-8f8a-11eb-9871-421a81f86e85.mp4

### Expected behaviour

Should work just fine.

### PR DESCRIPTION
**Pull request by mjlbach**
closes #14230 (?)

### CODE REVIEW

**Comment by elianiva** [comment]
I can confirm that it works, thank you :)

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -373,9 +373,12 @@ function M.compute_diff(old_lines, new_lines, start_line_idx, end_line_idx)
     adj_end_char = #old_lines[#old_lines + end_line + 1] + end_char + 1
   end
 
+  start_char = vim.str_utfindex(old_lines[start_line], start_char - 1)
```
Comment (bfredl) [inline runtime/lua/vim/lsp/util.lua:376]: It should be the second return value for `vim.str_utfindex` for UTF-16 (the difference will only be noticable with non-BMP chars)

Comment (mjlbach) [reply runtime/lua/vim/lsp/util.lua:376]: https://github.com/mjlbach/neovim/pull/new/fix_utf16_ranges_again
