### PR TITLE
fix(buffer_updates): save and restore current window cursor

### LINKED ISSUE #16729: Calling nvim_buf_call within an `on_lines` handler added with nvim_buf_attach causes Ctrl-A and Ctrl-X to misbehave
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

pacman, official repositories

### How to reproduce the issue

1. Open an empty buffer
2. Run this Lua code:
   ```lua
   vim.api.nvim_buf_attach(0, false, {
     on_lines = function()
       vim.api.nvim_buf_call(0, function() end)
     end,
   })
   ```
3. Type `test 0` in Insert mode
4. Exit the Insert mode
5. Press Ctrl-A

Here's a script which automates this process:

```vim
function! Test() abort
  enew
  lua <<EOF
  vim.api.nvim_buf_attach(0, false, {
    on_lines = function()
      vim.api.nvim_buf_call(0, function() end)
    end,
  })
EOF
  call nvim_input("itest 0\<Esc>\<C-a>")
endfunction
autocmd VimEnter * call Test()
```

It can be used with `nvim -u repro.vim`

(Interestingly enough, the bug only happens with the number 0 and not others.)

### Expected behavior

The buffer contains text `test 1`.

### Actual behavior

The buffer contains text `test1` instead (without the whitespace in between).

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #16729

When a buffer update callback is called, textlock is active so buffer text cannot be changed, but cursor can still be moved. This can cause problems when the buffer update is in the middle of an operator, like the one mentioned in #16729. The solution is to save cursor position and restore it afterwards, like how cursor is saved and restored when evaluating an `<expr>` mapping.

The test I added fails on `master`:
```
[  ERROR   ] test/functional/lua/buffer_updates_spec.lua @ 299: lua buffer event callbacks: on_lines calling nvim_buf_call() from callback does not cause Normal mode CTRL-A to misbehave #16729
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(string) 'tes124t'
Expected:
(string) 'test124'
```

### CODE REVIEW

**Comment by zeertzjq** [comment]
I feel this is not the right solution, as this doesn't make sense if the changed buffer is not changed by an operator and not in the current window (e.g. a terminal buffer).

**Comment by zeertzjq** [comment]
Lint CI hangs because of server problems.

**Comment by zeertzjq** [comment]
@bfredl Do you think this is a good solution?

**Comment by zeertzjq** [comment]
Alternative PR: #16647

File: src/nvim/buffer_updates.c [hunk 1]
```diff
@@ -366,10 +388,16 @@ void buf_updates_changedtick(buf_T *buf)
...
+        save_cursor = curwin->w_cursor;
+      }
       textlock++;
-      Object res = nlua_call_ref(cb.on_changedtick, "changedtick",
-                                 args, true, NULL);
+      Object res = nlua_call_ref(cb.on_changedtick, "changedtick", args, true, NULL);
       textlock--;
+      if (curwin != NULL) {
+        curwin->w_cursor = save_cursor;
+      }
```
Comment (justinmk) [inline src/nvim/buffer_updates.c:400]: lots of common code in all of these functions. do we need a `buf_updates_prepare`/`..._restore` util functions? Or should we add a `textlock` param to `nlua_call_ref()` ?

**Comment by justinmk** [comment]
from https://github.com/neovim/neovim/pull/16647#issuecomment-1164622626 : 

> One thing though that seems to be missing from that other PR which I would like to see is resetting the cursor to e.g. `firstline` so that user callbacks do not ever see a bad cursor position.
> 
> Also, for completeness, here is the test case that I had lying around which currently fails on NVIM v0.7.0:
> 
> ```viml
> function! G()
> endfunction
> function! F()
> 	call G()
> endfunction
> 
> let fname = tempname()
> call writefile(['', '0'], fname)
> silent execute 'edit!' fname
> lua vim.api.nvim_buf_attach(0, false, {on_lines = function(...) vim.api.nvim_call_function("F", {}) end})
> 2delete _
> 1put ='0'
> normal! u
> ```

**Comment by zeertzjq** [comment]
I'm not sure if there is a case where a buffer update callback may need to get the cursor position.

**Comment by justinmk** [comment]
This seems like a good change to have for 0.9. Don't see anything blocking it, though as [mentioned](https://github.com/neovim/neovim/pull/16732/files#r905071393) it's probably wise to put this pattern in a macro at least, so we have breadcrumbs in the future.

File: src/nvim/buffer_updates.c [hunk 2]
```diff
@@ -281,9 +288,17 @@ void buf_updates_send_changes(buf_T *buf, linenr_T firstline, int64_t num_added,
         args.items[6] = INTEGER_OBJ((Integer)deleted_codepoints);
         args.items[7] = INTEGER_OBJ((Integer)deleted_codeunits);
       }
+
+      pos_T save_cursor;
+      if (curwin != NULL) {
```
Comment (bfredl) [inline src/nvim/buffer_updates.c:293]: is `curwin` being null in a text change something that ever happens?

Comment (zeertzjq) [reply src/nvim/buffer_updates.c:293]: When I created this PR unload callbacks were called on exit. It guess it shouldn't happen now.

**Comment by zeertzjq** [comment]
I introduce a macro `TEXTLOCK_WRAP`. Currently only used for buffer updates.
