### PR TITLE
LUA: add options to highlight.on_yank

### LINKED ISSUE #12540: Allow `autocmd TextYankPost * silent! lua require'vim.highlight'.on_yank()` to be disabled in macros
- `nvim --version`:

```                                                                                                 ─╯
NVIM v0.5.0-574-g352831229
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/usr/local/opt/gettext/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Actual behaviour

Currently, when this `autocmd` is set, when a user yanks text it highlights the yanked region. If a user yanks text as part of a macro, it will highlight the corresponding region during each invocation of the playback of the macro.

### Expected behaviour

Don't highlight region during playback of macro.

### Reasoning

It's a little slow to play macros when this is enabled. I've also experienced a neovim crash once when playing back the same macro over 1000 times (using `1000@@`).

Pinging @clason @tjdevries

### PR DESCRIPTION
**Pull request by clason**
closes #12540 (thanks to @kdheepak for the suggestion and for digging up the correct variable to check for this!)

This PR adds an (optional) dictionary argument to the `vim.highlight.on_yank()` function that contains options controlling the highlight:
1. `on_macro` (default false) specifies whether to highlight when executing a macro
2. `on_visual` (default true) specifies whether to highlight when yanking a visual selection (replacing the previously documented approach)
3. `event` (default `vim.v.event`)

The rationale for including the latter (which used to be an optional positional argument) is that a) I still don't see a practical use case for _not_ using `vim.v.event` and hence b) think it shouldn't take up a positional argument (otherwise we'd either have to always specify it when setting options or moving the position of the argument, which would be needlessly breaking).

In a similar vein, I'd actually prefer to move `timeout` and `higroup` into the dictionary as well (in effect, making all arguments keyword arguments) to allow overriding one without having to specify the other, but that would also be a breaking change.  

**EDIT:** All options are now dictionary fields. In addition, `vim.highlight` is now exposed, i.e., you'd do

```viml
au TextYankPost * lua vim.highlight.on_yank {higroup="IncSearch", timeout=250, on_visual=false}
```

While I was at it, I've reduced the default timeout after using this a while and seeing others prefer a shorter timeout, too. Let me know if I should drop that commit.

@tjdevries

### CODE REVIEW

**Comment by tjdevries** [comment]
I like the idea of moving it all to one dictionary -- we haven't actually "released" this yet, so I think it's OK to change it.  I don't know if there is a way that we can more gracefully do the breaking change (for example, a better message if the type is wrong?), but it's probably worth it to do so.

Probably a good idea going forward that we actually try and move towards "keyword" arguments more often, rather than positional in Lua, since those are so much easier to keep backwards compat on. That is just a side note though.

File: runtime/lua/vim/highlight.lua [hunk 1]
```diff
@@ -28,16 +28,30 @@ end
 --- use from init.vim via
 ---   au TextYankPost * lua require'vim.highlight'.on_yank()
 --- customize highlight group and timeout via
----   au TextYankPost * lua require'vim.highlight'.on_yank("IncSearch", 500)
+---   au TextYankPost * lua require'vim.highlight'.on_yank({higroup="IncSearch", timeout=250})
```
Comment (tjdevries) [inline runtime/lua/vim/highlight.lua:31]: I think the "pretty" way to do this is to drop the `()` and just use `on_yank { higroup = "IncSearch", timeout = 250 }`.

That is just personal preference though. I like this for all "keyword argument" style lua functions.

File: runtime/lua/vim/highlight.lua [hunk 2]
```diff
@@ -28,16 +28,30 @@ end
...
+--- customize conditions (do not highlight a visual selection) via
+---   au TextYankPost * lua require'vim.highlight'.on_yank({visual=false})
```
Comment (tjdevries) [inline runtime/lua/vim/highlight.lua:33]: Maybe what would be better is we expose `highlight` on `vim.highlight` directly, so we don't need to have the `require` business at all

File: runtime/lua/vim/highlight.lua [hunk 3]
```diff
@@ -28,16 +28,30 @@ end
...
+--              - higroup highlight group for yanked region
+--              - timeout time in ms before highlight is cleared
+--              - macro (bool) highlight when executing macro (default false)
+--              - visual (bool) highlight when yanking visual selection (default true)
+--              - event  (struct) event structure (default vim.v.event)
+function highlight.on_yank(opts)
+  opts = opts or {}
+  local event = opts.event or vim.v.event
+  local macro = opts.macro or false
+  local visual = (opts.visual ~= false)
```
Comment (tjdevries) [inline runtime/lua/vim/highlight.lua:47]: Maybe `macro_enabled` and `visual_enabled`? It's unclear if it's the setting or if it's the status here.

File: runtime/lua/vim/highlight.lua (hunk 2 above)
Comment (clason) [reply runtime/lua/vim/highlight.lua]: How would we do that?

File: runtime/lua/vim/highlight.lua (hunk 3 above)
Comment (clason) [reply runtime/lua/vim/highlight.lua:47]: `on_visual` and `on_macro`?

File: runtime/lua/vim/highlight.lua (hunk 2 above)
Comment (tjdevries) [reply runtime/lua/vim/highlight.lua]: I don't remember off-hand, but you can see how `lsp` did it somewhere... I can look around later if you want. I'm on my laptop w/ only chrome setup, not for nvim dev, so it's hard for me to look it up. Or for other `vim.*` style things that are auto loaded. For example, `vim.inspect` is a good one. I think it's either `shared.lua` or maybe `vim.lua` somewhere.

File: runtime/lua/vim/highlight.lua (hunk 3 above)
Comment (tjdevries) [reply runtime/lua/vim/highlight.lua]: Ah, I just meant the local variables, not the dictionary keys -- I think they made sense in the dictionary, but not in the function... i don't know if that's just me being weird though.

Comment (clason) [reply runtime/lua/vim/highlight.lua]: I think they should have the same name, since the local variable (should) inherit from the option.

Comment (tjdevries) [reply runtime/lua/vim/highlight.lua]: 👍 makes sense to me.

Comment (tjdevries) [reply runtime/lua/vim/highlight.lua]: `on_*` probably works, I'll think a bit if we can get a better name for that.

**Comment by tjdevries** [comment]
Basically LGTM. Will come back later and check it out -- dinner time :)

File: runtime/doc/lua.txt [hunk 4]
```diff
@@ -698,25 +698,26 @@ VIM.HIGHLIGHT                  				*lua-highlight*
...
-        that is fired ({event}, default `vim.v.event`).
-
+vim.highlight.on_yank({opts})                         *vim.highlight.on_yank()*
+        Highlights the yanked text. The fields of the optional dict {opts}
+        control the highlight: the highlight group to use ({higroup}, default
+        `"IncSearch"`), the duration of highlighting in milliseconds
+        ({timeout}, default `250`), whether to highlight a visual selection
+        ({on_visual}, default `true`), whether to highlight when executing a
+        macro ({on_macro}, default `false`), and the {event} (struct, default
+        `vim.v.event`).
```
Comment (tjdevries) [inline runtime/doc/lua.txt:720]: I think this section should just be listed out like how you have it in the doc string.

It's easier to grok each of the keys that way IMO

File: runtime/lua/vim/highlight.lua [hunk 5]
```diff
@@ -26,18 +26,32 @@ end
...
----   au TextYankPost * lua require'vim.highlight'.on_yank()
+---   au TextYankPost * lua vim.highlight.on_yank()
 --- customize highlight group and timeout via
----   au TextYankPost * lua require'vim.highlight'.on_yank("IncSearch", 500)
+---   au TextYankPost * lua vim.highlight.on_yank {higroup="IncSearch", timeout=250}
+--- customize conditions (do not highlight a visual selection) via
+---   au TextYankPost * lua vim.highlight.on_yank {visual=false}
 ---
 -- @param higroup highlight group for yanked region
 -- @param timeout time in ms before highlight is cleared
```
Comment (tjdevries) [inline runtime/lua/vim/highlight.lua:36]: These need to be removed, correct?

**Comment by tjdevries** [comment]
After small doc nits, I think it LGTM.

May want to get another core member to check it out since we'll be breaking some stuff from head. I think we'll also want to update this: https://github.com/neovim/neovim/wiki/Following-HEAD to mention that we made a breaking change w/in a release version.

cc @h-michael or @teto or anyone either of you think should look at this as well.

**Comment by clason** [comment]
Just a small heads-up that the current github incident dropped some of the documentation fixes I pushed to my branch -- I'll try to get the PR to sync again.

**Comment by tjdevries** [comment]
Will you add info to following head after we merge this @clason ?

**Comment by clason** [comment]
Added validation of options and a deprecation message (that might -- or might not -- be removed before release?)

**Comment by tjdevries** [comment]
It's OK to leave since it directs them to the right place to fix their configuration regardless of whether they did it from pre-release or just made a mistake. It's a good validation message.

File: runtime/doc/lua.txt [hunk 6]
```diff
@@ -698,25 +698,26 @@ VIM.HIGHLIGHT                  				*lua-highlight*
...
 https://github.com/machakann/vim-highlightedyank). To enable it, add
 >
- au TextYankPost * silent! lua require'vim.highlight'.on_yank()
+ au TextYankPost * silent! lua vim.highlight.on_yank()
 <
 to your `init.vim`. You can customize the highlight group and the duration of
 the highlight via
 >
- au TextYankPost * silent! lua require'vim.highlight'.on_yank("IncSearch", 500)
+ au TextYankPost * silent! lua vim.highlight.on_yank {higroup="IncSearch", timeout=250}
```
Comment (nhooyr) [inline runtime/doc/lua.txt:706]: Thoughts on defaulting this timeout to 150 ms? The default of 500 ms is quite long and feels clunky to me.

Love this feature btw!

Comment (nhooyr) [reply runtime/doc/lua.txt:706]: Ah, just noticed the PR already reduced it from 500 to 250. I'm good with 250.

Comment (nhooyr) [reply runtime/doc/lua.txt:706]: I do feel 150 is better, it feels really snappy to me whereas 250 still sorta feels clunky.

Comment (tjdevries) [reply runtime/doc/lua.txt:706]: I have no preference -- @clason what do you think?

Comment (clason) [reply runtime/doc/lua.txt:706]: I thought 250 was a reasonable compromise. Let's make a brief poll:

* 👍 500ms
* 😄 250ms
* ❤️ 200ms (split the difference)
* 👎 150ms

Comment (tjdevries) [reply runtime/doc/lua.txt:706]: K, do 150 and then let's ship it.

Comment (clason) [reply runtime/doc/lua.txt:706]: Should have picked a friendlier emoji for the shortest option :)

**Comment by clason** [comment]
Now that we have a much shorter timeout, I have changed the `on_yank` highlight to use a persistent namespace. This should be more robust (@kdheepak mentioned seeing a crash when triggering a lot of yanks quickly via a macro) and behave correctly when yanking beyond the current viewport.

I think this is ready for merging now. @tjdevries?

File: runtime/lua/vim/highlight.lua [hunk 7]
```diff
@@ -26,21 +26,38 @@ end
...
-  higroup = higroup or "IncSearch"
-  timeout = timeout or 500
+  if (not on_visual) and event.visual then return end
+
+  local higroup = opts.higroup or "IncSearch"
+  local timeout = opts.timeout or 150
 
   local bufnr = api.nvim_get_current_buf()
-  local yank_ns = api.nvim_create_namespace('')
+  local yank_ns = api.nvim_create_namespace('hlyank')
```
Comment (tjdevries) [inline runtime/lua/vim/highlight.lua:60]: yeah, this should be fine. Only thing would be we might as well move this out of the function call and just set it as a local variable, so we don't have to call the function every time. NANOSECONDS ARE BEING WASTED.

Comment (clason) [reply runtime/lua/vim/highlight.lua]: Done!
