### PR TITLE
fix(decoration): call providers in win_update() earlier

### LINKED ISSUE #20651: Extmarks in `CursorMoved` autocmd with floating window prevents redrawing
### Neovim version (nvim -v)

0.8.0 commit 9931db2e3

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

macOS 12.6

### Terminal name/version

Kitty

### $TERM environment variable

xterm-kitty

### Installation

Source

### How to reproduce the issue

- Create `test.lua`:
```lua
local ns = vim.api.nvim_create_namespace('ns')

local bufnr = vim.api.nvim_create_buf(false, true)
vim.api.nvim_open_win(bufnr, false, { relative = 'win', height = 1, width = 1, row = 0, col = 0 })

vim.api.nvim_create_autocmd('CursorMoved', { callback = function()
  local row = vim.api.nvim_win_get_cursor(0)[1] - 1
  vim.api.nvim_buf_set_lines(bufnr, 0, -1, true, {})
  vim.api.nvim_buf_set_extmark(0, ns, row, 0, { id = 1, })
  vim.schedule(function()
    vim.api.nvim_buf_set_extmark(0, ns, row, 0, {
      id = 1,
      virt_text = {{'HELLO', 'Normal'}},
    })
  end)
end
})

vim.cmd'normal 100oXXX'
vim.cmd'normal gg'
```

- `nvim --clean -c 'source test.lua'`

- Move the cursor around with `j`/`k`.

### Expected behavior

The virtual text `HELLO` should only appear on the cursor line.

### Actual behavior

https://user-images.githubusercontent.com/7904185/195875130-0c1ce197-e18e-46c8-8d02-c53dcf248aba.mov

### PR DESCRIPTION
**Pull request by lewis6991**
Fix another issue revealed by #20249

The `goto` for decor providers in `win_update()` can cause changes to `wp_redraw_top/bot` to be lost since those variables are reset before the `goto`. Most of the logic above the `goto` is mostly calculating/tweaking certain variables to use for the actual redraw so it makes sense to me that this logic should go *after* the decor provider callbacks.

Fixes #20651

### CODE REVIEW

File: test/functional/ui/decorations_spec.lua [hunk 1]
```diff
@@ -2120,4 +2120,49 @@ describe('decorations: virt_text', function()
     ]]}
   end)
 
+  it('XXX', function()
```
Comment (zeertzjq) [inline test/functional/ui/decorations_spec.lua:2123]: Needs a better name

Comment (lewis6991) [reply test/functional/ui/decorations_spec.lua:2123]: I'm not even sure if we should even include this test, as it's quite convoluted. What do you think?
