### PR TITLE
[RDY] Fix error-handling of strtoimax boundary conditions

### LINKED ISSUE #5279: segfault with foldmarker
- `nvim --version`:

```
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Vim (version: ) behaves differently?

~~before recent archlinux package update~~ (*edit* didn't try, don't think it is relevant)

- Operating system/version:

arch linux (updated 09/01/2016)

- Terminal name/version:
```st 0.7 (c) 2010-2016 st engineers```, ```tmux 2.2```
- `$TERM`:
screen-256color

### Actual behaviour
When opening this file: https://gist.github.com/b1b9377ea3841290ce9682921d6afc73
```
nvim: /build/neovim/src/neovim-0.1.5/src/nvim/charset.c:1743: getdigits: Assertion `errno != ERANGE' failed.
```

### Expected behaviour
file opens

### Steps to reproduce using `nvim -u NORC`

no idea, but I reduced my init.vim to this:

```
set foldmethod=marker
set foldmarker=/\*\*,\/
```

Manually setting the commands after starting with ```-u NORC``` doesn't lead to crash.

### PR DESCRIPTION
**Pull request by jamessan**
strtoimax is only required to set errno if there is an
underflow/overflow.  In those conditions, strtoimax returns
INTMAX_MIN/INTMAX_MAX respectively, so that's the only time we should be
checking the value of errno.

Even in those conditions, errno needs to be set to a known good value
before calling strtoimax to differentiate between "value is actually
INTMAX_MAX/MIN" and "value over/underflows".

Closes #5279

### CODE REVIEW

**Comment by jamessan** [comment]
The lint error is due to clint thinking `(char *)*pp` is a multiplication, not a cast.  This needs a fix to clint.

File: src/nvim/charset.c [hunk 1]
```diff
@@ -1739,8 +1739,11 @@ char_u* skiptowhite_esc(char_u *p) {
 /// @return Number read from the string.
 intmax_t getdigits(char_u **pp)
 {
+  errno = 0;
   intmax_t number = strtoimax((char *)*pp, (char **)pp, 10);
-  assert(errno != ERANGE);
```
Comment (oni-link) [inline src/nvim/charset.c]: Why is this `assert()` not enough with the new `errno = 0`?

Comment (jamessan) [inline src/nvim/charset.c]: I haven't taken a look at the implementation of `strtoimax`, so I don't know if anything it calls could set errno.  The contract only guarantees that errno is valid to check if the return value is INTMAX_MAX or INTMAX_MIN.

**Comment by justinmk** [comment]
LGTM
