### PR TITLE
fix(diagnostic): clamp line numbers in display layer

### LINKED ISSUE #15591: show_position_diagnostics doesn't display diagnostics for multiple servers
### Neovim version (nvim -v)

0.6.0-dev+3f526feeb

### Language server name/version

pyright 1.1.157 / null-ls 5b0e21625a920cf4a2d1ce1c516dd503b7a32ca9

### Operating system/version

macOS 11.5.2

### :checkhealth

_No response_

### Steps to reproduce using "nvim -u minimal_init.lua"

[minimal_init.txt](https://github.com/neovim/neovim/files/7122371/minimal_init.txt)

1. Install flake8 and pyright
2. Rename attached file to have lua extension
4. `nvim -u minimal_init.lua test.py`
5. Copy below contents into file
5. `]d` repeatedly to jump through diagnostics
6. Popup is not displayed for null-ls diagnostics i.e. flake8 only pyright.

```py
#comment
import test

if __name__ == "__main__":
    main()

```

### Expected behavior

The popup displaying diagnostics should be shown for all servers. Looks like this stems from the changes in #14795. Maybe the `client_id` needs passed to the new `show_position_diagnostics` similar to what is done with `show_line_diagnostics`.

### Actual behavior

Cursor jumps to the position of each diagnostic but the popup with more information is only displayed for pyright.

### Log file

_No response_

### PR DESCRIPTION
**Pull request by gpanders**
Some parts of LSP need to use cached diagnostics as sent from the LSP server unmodified. Rather than fixing invalid line numbers when diagnostics are first set, fix them when they are displayed to the user (e.g. in `show()` or one of the `get_next`/`get_prev` family of functions).

Closes #15591.
Ref #15616.

### CODE REVIEW

File: runtime/lua/vim/diagnostic.lua [hunk 1]
```diff
@@ -430,15 +431,15 @@ local function next_diagnostic(position, search_forward, bufnr, opts, namespace)
         sort_diagnostics = function(a, b) return a.col > b.col end
         is_next = function(diagnostic) return diagnostic.col < position[2] end
       end
-      table.sort(line_diagnostics, sort_diagnostics)
+      table.sort(line_diagnostics[lnum], sort_diagnostics)
       if i == 0 then
-        for _, v in pairs(line_diagnostics) do
+        for _, v in ipairs(line_diagnostics[lnum]) do
```
Comment (mjlbach) [inline runtime/lua/vim/diagnostic.lua:436]: is there a reason to change to ipairs here?

Comment (gpanders) [reply runtime/lua/vim/diagnostic.lua:436]: Nope, just habit, I'll switch it back.

**Comment by mjlbach** [comment]
This otherwise lgtm. I'm not sure the best way to test it, but we should verify that sending a code action matching the last line (terminating newline) diagnostic works... although that might be tricky

**Review by mfussenegger — APPROVED** [review]

**Review by mjlbach — APPROVED** [review]
