### PR TITLE
fix(windows): restore `tee` functionality on Windows

### LINKED ISSUE #32504: windows nightly: :grep breaks because tee is not on path
### Problem

on the latest release and nightly from before I updated this isn't an issue. `:grep` simply breaks

Image

### Steps to reproduce

nvim --clean
:grep foo

### Expected behavior

normal behavior of :grep

### Nvim version (nvim -v)

v0.11.0-dev-1771+gbd0a65bc15

### Vim (not Nvim) behaves the same?

N/A (vim doesn't call ripgrep)

### Operating system/version

windows 10 home 22h2

### Terminal name/version

command prompt

### $TERM environment variable

none (windows)

### Installation

 scoop install neovim-nightly

### PR DESCRIPTION
**Pull request by AaronSteen**
### Problem

Neovim no longer ships with a tee binary on Windows, which breaks functionality for the :grep and :make commands.

### Solution

Include a simple, no-dependency tee.c source file in the src/ directory. Update CMakeLists.txt to build a tee executable alongside neovim during the build process, and ensure the tee.exe program appears alongside the neovim executable in the bin/ directory so that it is accessible for :grep and :make.

The tee.c was obtained from the vim codebase [here](https://github.com/vim/vim/blob/master/src/tee/tee.c). I ran a search of the strings in the tee binary that used to ship with neovim; strings that appeared in the binary show that this tee.c was very likely the source of that binary. I considered other available tee sources (see below), but felt that this was by far the most simple option for restoring the desired functionality. It builds without any required tinkering. 

### How to reproduce (before)

On Windows:

nvim --clean
:grep foo or :make, after setting a file to the makeprg option.

Screenshot 2025-10-27 134646

### How to verify (after)

nvim --clean
:grep foo or :make, after setting a file to the makeprg option.
Verify that :grep results and error output from a compiler appear in the message pane.

Screenshot 2025-10-27 135006

### Tests

This is a draft and I have not done any testing yet; would welcome any direction. At minimum, we should verify that tee is able to correctly pipe text back into neovim that displays properly in the quickfix list.

### Notes

Other tee options:
- [tee-win32](https://github.com/dEajL3kA/tee-win32):  (this is MIT-licensed. However, I couldn't get it to build on my machine even after updating its makefile to call my install of MSVC. It's also super optimized and uses some processor intrinsics for multithreading. On the whole very impressive but not very portable, so not very suitable, I think.)

- [gnu coreutils tee](https://gnuwin32.sourceforge.net/packages/coreutils.htm): (Windows coreutils contains a tee.c. Last updated 2005. Did not build immediately on my machine; we'd have to determine which definitions from elsewhere in coreutils tee.c needs and incorporate them somehow.)

- [WinTee](https://github.com/mpderbec/WinTee): (Has no license. Last updated 11 years ago. Relies on Visual Studio to build.)

### Related discussions

https://github.com/neovim/neovim/issues/32431 (about the suspicious original tee binary)
fix https://github.com/neovim/neovim/issues/32504 (demonstration of broken tee functionality)

### Todo

- Testing
- Update zig build file with tee.c instruction

### CODE REVIEW

File: src/tee/tee.c
Comment (justinmk) [inline src/tee/tee.c:1]: running `make formatc` should fix most lint issues in this file

File: src/tee/CMakeLists.txt [hunk 1]
```diff
@@ -0,0 +1,10 @@
+add_executable(tee tee.c)
+
+# tee has to be in the same directory as the nvim executable
```
Comment (justinmk) [inline src/tee/CMakeLists.txt:3]: this is a Windows-only feature, btw. on non-Windows we always need to use either `./tee`, or the absolute path, or the parent dir needs to be in `$PATH`.

in test, you can use `n.testprg('tee')` to get the fullpath. (but this might be irrelevant since the purpose of including `tee` is that Nvim should automatically find it.) https://github.com/neovim/neovim/blob/7088441de41c468e22dc5daffd377c00211ce45b/test/functional/testnvim.lua#L941-L943

**Comment by AaronSteen** [comment]
@justinmk an update after taking some time to understand the testing framework. i'm going to address two things here: performance of the new tee.exe, and possible updates to [test\functional\ex_cmds\grep_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/ex_cmds/grep_spec.lua).

### New tee performance
on huge inputs, the windows version of tee that we'd be adding here performs much worse than what test\functional\ex_cmds\grep_spec.lua seems to want. this test greps the letter "a", recursively, on the test directory. on windows, it takes about 60 seconds with the new tee.exe. however, because the test only tries to determine whether large input causes :grep to hang, it still passes.

(note: as far as i can tell, grep_spec.lua is the only test that specifically examines the process of executing a shell command and echoing its output back into the message pane, in a platform-agnostic way (for example, make_spec.lua only examines the behavior of powershell).)

i ran some tests of my own just to better understand what's happening here. i ran the same "a" search with ripgrep with four configs that either use -uu, -uuu, and either do pipe to tee or don't. i tried the same test with both the new tee and the old tee binary that nvim still shipped with as of version 0.10.3. times were basically identical; here's a sample run:

image

i timed it with rg and command prompt as a sanity check; times are almost the same. so this tee is slow on huge inputs. BUT in a typical use case for me, where it's echoing back a few dozen lines from the compiler at most, i notice no slowdown.

### about grep_spec.lua
if my interpretation is correct, currently grep_spec.lua doesn't run on windows builds because the test hardcodes grep itself, rather than referencing grepprg:

image

[now that we look for rg and set it as grepprg if it's available by default](https://github.com/neovim/neovim/commit/20b38677c22b0ff19ea54396c7718b5a8f410ed4), we should probably update grep_spec.lua to use grepprg.

ok i can see that as i write this, all builds are failing the test on the line

`ok(eval('len(getqflist())') > 9000) -- IT'S OVER 9000!!1`

maybe the test dir that github runs this test in has fewer files than what i have on my machine...? (update: ok yes, it passes if we set the check on the quickfix list length to 100. this seems fine given that we're mainly wanting to see lines echoed to the message pane properly.)

### anyway, conclusions

my view is that if we were fine with tee performance on windows before the tee binary was killed, then we will be fine with this version. for any typical use case, a user isn't likely to notice. 

however, grep_spec.lua should probably be updated to run with whatever is set as grepprg, if our goal is to test under a typical use case.

a final thread to consider re:testing: since we are now building tee instead of shipping a binary, maybe we want to check it built properly. to me, the simplest approach would just be adding a line to test_windows.yml.

File: src/tee/tee.c [hunk 2]
```diff
@@ -0,0 +1,165 @@
...
+
+int
+main(int argc, char *argv[])
+{
+	int	append = 0;
+	size_t	numfiles;
+	int	maxfiles;
+	FILE	**filepointers;
+	int	i;
+	char	buf[BUFSIZ];
```
Comment (justinmk) [inline src/tee/tee.c]: How big is BUFSIZ? Does changing this to something big, improve the performance?


```suggestion
	char	buf[65536];
```

File: src/tee/tee.c [hunk 3]
```diff
@@ -0,0 +1,165 @@
...
+#ifdef _WIN32
+	setmode(fileno(stdin),  O_BINARY);
+	fflush(stdout);	/* needed for _fsetmode(stdout) */
+	setmode(fileno(stdout),  O_BINARY);
+#endif
+
+	while ((n = myfread(buf, sizeof(char), sizeof(buf), stdin)) > 0)
+	{
+		fwrite(buf, sizeof(char), n, stdout);
+		fflush(stdout);
```
Comment (justinmk) [inline src/tee/tee.c]: try removing this (or comment it, as a reminder for future), is it faster?

actually, here's what chatgpt suggests (and it looks like a good idea to me):

```c
int n;
while ((n = fread(buf, 1, sizeof(buf), stdin)) > 0) {
    fwrite(buf, 1, n, stdout);
    for (i = 0; i < numfiles; i++)
        if (filepointers[i])
            fwrite(buf, 1, n, filepointers[i]);
    fflush(stdout);  // flush once per block, not per byte
}
```

> Now fread() does large reads (e.g., 4–8 KB), and fflush() happens per block.

another optional thing to try:

```c
setvbuf(stdout, NULL, _IONBF, 0);   // fully unbuffered
```

> Set stdout to line-buffered or unbuffered mode if you want immediate output.
>
> That’s exactly what GNU tee effectively does — it disables buffering on stdout if it’s a terminal or pipe.

File: src/tee/tee.c [hunk 4]
```diff
@@ -0,0 +1,165 @@
...
+ * We could use fgets, but I want to be able to handle binary blubber.
+ */
+
+int
+myfread(char *buf, int elsize /*ignored*/, int max, FILE *fp)
+{
+	int	c;
+	int	n = 0;
+
+	while ((n < max) && ((c = getchar()) != EOF))
```
Comment (justinmk) [inline src/tee/tee.c]: from chatgpt:

- getchar() reads one byte at a time using fully buffered stdio calls.
    - On Linux, this may still get internally buffered at a reasonable chunk size, so it’s not disastrous.
     - On Windows, especially when stdin is a pipe, each getchar() often results in a real system call (ReadFile of size 1) — that’s excruciatingly slow for large inputs.

suggested fix:

> Change myfread() to a real buffered read:

```c
int myfread(char *buf, int elsize, int max, FILE *fp)
{
    return fread(buf, elsize, max, fp);
}
```

and call it like this:

```c
while ((n = myfread(buf, 1, sizeof(buf), stdin)) > 0)
{
    fwrite(buf, 1, n, stdout);
    for (i = 0; i < numfiles; i++)
        if (filepointers[i]) fwrite(buf, 1, n, filepointers[i]);
}
```

File: CMakeLists.txt [hunk 5]
```diff
@@ -121,6 +121,7 @@ if(WIN32 OR APPLE)
   set(CASE_INSENSITIVE_FILENAME TRUE)
 endif()
 
+
```
Comment (justinmk) [inline CMakeLists.txt]: remove

File: CMakeLists.txt [hunk 6]
```diff
@@ -315,6 +316,10 @@ add_subdirectory(cmake.config)
 add_subdirectory(runtime)
 add_subdirectory(test)
 
+if(WIN32)
+  add_subdirectory(src/tee)
```
Comment (justinmk) [inline CMakeLists.txt]: feel free to drop the `if(WIN32)` check. that make the build more uniform, and it should be harmless on non-Windows.

the binary should be produced at `./build/bin/tee`.

**Comment by justinmk** [comment]
> this tee is slow on huge inputs. BUT in a typical use case for me, where it's echoing back a few dozen lines from the compiler at most, i notice no slowdown.

see https://github.com/neovim/neovim/pull/36363#discussion_r2521136338

> it passes if we set the check on the quickfix list length to 100. this seems fine given that we're mainly wanting to see lines echoed to the message pane properly.)

The test was done that way intentionally. It is testing the performance of quickfix, as well as the codepaths that collect big results. It should not be changed, except to unblock this PR we can special-case it for Windows (but that might not be necessary if the perf issues can be fixed).

I would like to get the PR over the fence, so please avoid changing unrelated things :)

> maybe we want to check it built properly

Doesn't the test that uses `tee` confirm that already?

> however, grep_spec.lua should probably be updated to run with whatever is set as grepprg

 We aren't testing the performance of grep/rg, that seems irrelevant.

**Comment by justinmk** [comment]
side-note (not a blocker):

- we should add this source file to `UNCRUSTIFY_NVIM_SOURCES` so that `lintc` and `formatc` check it https://github.com/neovim/neovim/blob/653871da1b5507d3391239854982438872ad4032/src/nvim/CMakeLists.txt#L425
- and to `LINT_NVIM_SOURCES` https://github.com/neovim/neovim/blob/653871da1b5507d3391239854982438872ad4032/src/nvim/CMakeLists.txt#L456

**Comment by AaronSteen** [comment]
> > this tee is slow on huge inputs. BUT in a typical use case for me, where it's echoing back a few dozen lines from the compiler at most, i notice no slowdown.
> 
> see [#36363 (comment)](https://github.com/neovim/neovim/pull/36363#discussion_r2521136338)
> 
> > it passes if we set the check on the quickfix list length to 100. this seems fine given that we're mainly wanting to see lines echoed to the message pane properly.)
> 
> The test was done that way intentionally. It is testing the performance of quickfix, as well as the codepaths that collect big results. It should not be changed, except to unblock this PR we can special-case it for Windows (but that might not be necessary if the perf issues can be fixed).
> 
> I would like to get the PR over the fence, so please avoid changing unrelated things :)
> 
> > maybe we want to check it built properly
> 
> Doesn't the test that uses `tee` confirm that already?
> 
> > however, grep_spec.lua should probably be updated to run with whatever is set as grepprg
> 
> We aren't testing the performance of grep/rg, that seems irrelevant.

i'm sorry about the changes to grep_spec.lua. I reverted them. i fundamentally misunderstood the nature of the CI tests...my assumption was that this line

`if eval("executable('grep')") == 0 then`

would always be true on windows because windows doesn't have grep by default, and then there would be no test coverage on windows...but seems like the github CI runners for windows use git bash [per this discussion](https://github.com/actions/runner/issues/497), so grep is available. might still be missing something here; let me know if any other changes required, thx~

**Comment by justinmk** [comment]
Cool, so the performance issues are resolved for you?

The failing CI can be ignored, that will be fixed by https://github.com/neovim/neovim/pull/36609

Rebasing will fix CI.

File: test/functional/ex_cmds/grep_spec.lua [hunk 7]
```diff
@@ -7,16 +7,27 @@ describe(':grep', function()
...
     end
 
-    n.command([[set grepprg=grep\ -r]])
     -- Change to test directory so that the test does not run too long.
     n.command('cd test')
-    n.feed(':grep a **/*<cr>')
+    n.feed(grepcmd)
     n.feed('<cr>') -- Press ENTER
-    ok(eval('len(getqflist())') > 9000) -- IT'S OVER 9000!!1
+    ok(eval('len(getqflist())') > 100)
```
Comment (justinmk) [inline test/functional/ex_cmds/grep_spec.lua]: can this change be reverted, i.e. is the performance ok now?

File: src/tee/tee.c (hunk 4 above)
Comment (AaronSteen) [reply src/tee/tee.c]: > from chatgpt:
> 
>     * getchar() reads one byte at a time using fully buffered stdio calls.
>       
>       * On Linux, this may still get internally buffered at a reasonable chunk size, so it’s not disastrous.
>       * On Windows, especially when stdin is a pipe, each getchar() often results in a real system call (ReadFile of size 1) — that’s excruciatingly slow for large inputs.
> 
> 
> suggested fix:
> 
> > Change myfread() to a real buffered read:
> 
> ```c
> int myfread(char *buf, int elsize, int max, FILE *fp)
> {
>     return fread(buf, elsize, max, fp);
> }
> ```
> 
> and call it like this:
> 
> ```c
> while ((n = myfread(buf, 1, sizeof(buf), stdin)) > 0)
> {
>     fwrite(buf, 1, n, stdout);
>     for (i = 0; i < numfiles; i++)
>         if (filepointers[i]) fwrite(buf, 1, n, filepointers[i]);
> }
> ```

made a bunch of changes per your suggestions and it's way faster (ignore newly built tee):

image

i think the original approach was to echo compiler messages back as they were generated, so that someone running a 200 MHz CPU in 1996 could kill compilation immediately if they saw something they didn't like

File: test/functional/ex_cmds/grep_spec.lua [hunk 8]
```diff
@@ -7,16 +7,27 @@ describe(':grep', function()
   before_each(clear)
 
   it('does not hang on large input #2983', function()
-    if eval("executable('grep')") == 0 then
-      pending('missing "grep" command')
+    local whichgrep = eval('&grepprg')
+
+    if whichgrep == '' then
+      pending('no grepprg configured')
```
Comment (justinmk) [inline test/functional/ex_cmds/grep_spec.lua]: ?? this should never happen. tests always set up nvim with the same settings. or if not, then we should just fail.

File: test/functional/ex_cmds/grep_spec.lua (hunk 7 above)
Comment (AaronSteen) [reply test/functional/ex_cmds/grep_spec.lua]: yes.

File: test/functional/ex_cmds/grep_spec.lua (hunk 8 above)
Comment (AaronSteen) [reply test/functional/ex_cmds/grep_spec.lua]: this and what you highlight below should have been reverted. that is, grep_spec.lua should be identical to upstream/master in my last commit. i think they're just showing up because of the commit history? i believe i can rebase to make them go away, if that's preferred.

also, not to overcomplicate, but grep_spec.lua is indeed skipped on windows:

image

compared with ubuntu:

image

Comment (justinmk) [reply test/functional/ex_cmds/grep_spec.lua]: rebase and force-push is ok 👍

Comment (justinmk) [reply test/functional/ex_cmds/grep_spec.lua]: > also, not to overcomplicate, but grep_spec.lua is indeed skipped on windows:

oh, that's a good to try `rg` in the test then. so if the test works on Windows now, please keep the `rg` support in it :)

**Comment by justinmk** [comment]
> also, not to overcomplicate, but grep_spec.lua is indeed skipped on windows:

It looks like it ran in your latest push, right?

    2025-11-19T21:52:35.7930340Z RUN T2399 :grep does not hang on large input #2983: 4906.00 ms OK

**Comment by AaronSteen** [comment]
> > also, not to overcomplicate, but grep_spec.lua is indeed skipped on windows:
> 
> It looks like it ran in your latest push, right?
> 
> ```
> 2025-11-19T21:52:35.7930340Z RUN T2399 :grep does not hang on large input #2983: 4906.00 ms OK
> ```

Yes...ugh, last night when I was certain I had restored grep_spec.lua, I had actually failed to stage it along with the other files. When I diffed the restored version with upstream/master to double-check, it of course showed they were identical. I should have diffed with HEAD instead, I think...anyway, sorry for much ado about nothing!

File: CMakeLists.txt [hunk 9]
```diff
@@ -316,6 +316,8 @@ add_subdirectory(cmake.config)
 add_subdirectory(runtime)
 add_subdirectory(test)
 
+add_subdirectory(src/tee)
```
Comment (justinmk) [inline CMakeLists.txt]: nit: move this just after line 314

File: src/tee/tee.c [hunk 10]
```diff
@@ -0,0 +1,133 @@
...
+int main(int argc, char *argv[])
+{
+  int append = 0;
+  size_t numfiles;
+  int maxfiles;
+  FILE **filepointers;
+  int i;
+  char buf[65536];
+  int n;
+  int optind = 1;
```
Comment (justinmk) [inline src/tee/tee.c]: rename this (and the usages below) to fix the failing lint CI
```suggestion
  int optnr = 1;
```

**Comment by justinmk** [comment]
Thanks for driving this forward and testing it on Windows! Eager to merge this, there is just one failing lint CI.

In order to make this available to actual Windows users, we may need to add an "install" statement in cmake somwhere (probably just a 1-line change) in order to fully close https://github.com/neovim/neovim/issues/32504 , but we can deal with that as a followup.

**Comment by AaronSteen** [comment]
> Thanks for driving this forward and testing it on Windows! Eager to merge this, there is just one failing lint CI.
> 
> In order to make this available to actual Windows users, we may need to add an "install" statement in cmake somwhere (probably just a 1-line change) in order to fully close #32504 , but we can deal with that as a followup.

thanks for helping me along. happy to do whatever followup would be useful.

**Comment by justinmk** [comment]
I pushed some fixes let's see if CI is good

**Comment by justinmk** [comment]
~~This shows a couple ways to "install" stuff (i.e. when the user runs `make install`):~~ https://github.com/neovim/neovim/blob/4f2c49f0078f13753f2d6947d1f14b8fddacf903/cmake.deps/CMakeLists.txt#L159-L162


Edit: oops it looks like `add_subdirectory` already will include tee in the install. Need to make that conditional for Windows only.
