### PR TITLE
[RDY] Fix click on foldcolumn if it has tabline

### LINKED ISSUE #13872: #13244 breaks click on foldcolumn
Commit 368403a9e60ba3695717fa224b8fa249d8e6425b (PR #13244) breaks click on foldcolumn.
When the tab page label is displayed, clicking the `+` sign on the foldcolumn does nothing.

### Steps to reproduce 
```
nvim --clean -c 'set mouse=a fdc=1 stal=2'
```
Input some text and create a fold. Click the `+` sign on the fold column to unfold it.

### Actual behaviour
Nothing happens. 

### Expected behaviour
Unfold.

### PR DESCRIPTION
**Pull request by tksrsk**
Fixes: #13872
But don't pass the test, and worked in progress.

### CODE REVIEW

File: src/nvim/mouse.c [hunk 1]
```diff
@@ -308,10 +308,11 @@ int jump_to_mouse(int flags,
   if (ui_has(kUIMultigrid)) {
     gp = &curwin->w_grid;
```
Comment (teto) [inline src/nvim/mouse.c:309]: one worry I have is that we dont use   `int grid = mouse_grid;` ? we are not necessarily clicking on the current window

**Comment by teto** [comment]
may be relevant https://github.com/neovim/neovim/pull/12667

File: src/nvim/mouse.c (hunk 1 above)
Comment (tk-shirasaka) [reply src/nvim/mouse.c:309]: @teto 
That's true.
Then I will think about using `wp` instead of `curwin`.

I'd like to know your opinion on two related points.

1.
I think it is correct to use `default_grid` when `ext_multigrid` is invalid.
What do you think?
2.
`curwin` is used not only for retrieving clicked characters but also for comparing retrieved characters, but I think it should be changed to use `wp` as well.

**Comment by tk-shirasaka** [comment]
@teto 

Fixed the issue and change it to use `mouse_grid`, so please review this PR.

**Review by teto — APPROVED** [review]
@Kethku @akiyosi would you mind test this with your multigrid implementation ? works in TUI

**Comment by Kethku** [comment]
Looking now. Is there a build I can use or should I build it myself?

**Comment by akiyosi** [comment]
Hi,
I have checked this issue and it seems that the problem occurs in the supposedly fixed branch `tk-shirasaka:fix/click-foldcolumn-with-tabs`, but not in the current `master` branch of neovim.
Note that goneovim uses the old nvim_input() api in mouse input.

**Comment by tk-shirasaka** [comment]
@Kethku 
Sorry, build is not exists.
Would you build it yourself, please?

**Comment by tk-shirasaka** [comment]
@akiyosi 
Thank you for test this PR!
I'll try fix your reported issue.

**Comment by tk-shirasaka** [comment]
@akiyosi 
When used nvim_input() or grid was 0, should used row and col rather than mouse_row and mouse_col, so that has been fixed.
I'm sorry to keep repeating this, but could you please check again?

**Comment by akiyosi** [comment]
@tk-shirasaka 
I checked 4bb2dae8 and confirmed that the problem has been fixed :D

**Comment by teto** [comment]
One step closer to 0.5 thanks

**Comment by tomtomjhj** [comment]
hmm this didn't fix the `vsplit` case

**Comment by tk-shirasaka** [comment]
@tomtomjhj 
I'm sorry! !!

I overlooked that case.
I'll check and fix it.
