### PR TITLE
fix(vim.fs): root() should always return absolute path

### LINKED ISSUE #34208: Skip `vim.fs.root()` fallback to Nvim's current-directory
### Problem

Is it reasonable that `vim.fs.root()` search falls back to Nvim's current-directory for unnamed and special buffers? If for example, current-directory is `/` or `~` and a marker matches, we might end up with `/` or `~` as `root_dir`. To have a `root_dir` with so many files could be problematic depending on the language server and configuration?

I'd be happy to make a pull request if agreement is reached.

### Expected behavior

`vim.fs.root()` returns `nil` when `source` is an unnamed or a special buffer.

### LINKED ISSUE #36464: LSP: Duplicate servers with incorrect rootPath started for non-file backed buffers
### Problem

When opening a non-file backed buffer that still matches a lsp filetype, duplicate lsp servers are started with a rootPath set to `/.`

For example, with `emmylua_ls`, opening a file named `diffview:///Users/cam/Dev/neovim-dev/opencode.nvim/.git/:0:/lua/opencode/state.lua` will start a duplicate `emmylua_ls` server and that server will start indexing `/` (i.e. the whole filesystem).

I traced it down and it's happening in `lsp.start`:

https://github.com/neovim/neovim/blob/16c8152229c6d11ed3647ba01c4bcd70d11b7f11/runtime/lua/vim/lsp.lua#L668-L678 

For non-file backed buffers, `vim.fs.root` starts looking in the current directory and, if it matches, it returns a relative directory.

That relative directory doesn't match the checks in `reuse_client_default` so new servers are spawned.

The incorrect `rootPath` comes from `Client:initialize`:

https://github.com/neovim/neovim/blob/16c8152229c6d11ed3647ba01c4bcd70d11b7f11/runtime/lua/vim/lsp/client.lua#L503-L515

`vim.uri_to_fname` translates the `file://.` to `/.` which is what the language server receives.

To fix, I think we just have to pass the return from `vim.fs.root` to `vim.fn.fnamemodify`:

```lua
    config.root_dir = vim.fn.fnamemodify(vim.fs.root(bufnr, opts._root_markers), ':p:h')
```

### Steps to reproduce using "nvim -u minimal_init.lua"

minimal_init.lua
```lua
local pattern = 'lua'
local cmd = { 'emmylua_ls' }
-- Add files/folders here that indicate the root of a project
local root_markers = { '.luarc.json', '.emmyrc.json', '.luacheckrc', '.git' }
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    vim.lsp.start({
      name = 'emmylua_ls',
      cmd = cmd,
      settings = settings,
    }, { _root_markers = root_markers })
  end,
})
```

Repro:
1. touch `.emmyrc.json`
2. `nvim -u minimal_init.lua minimal_init.lua` (second arg is to load a lua file to trigger `emmylua_ls`)
3. `:e diffview:///Users/cam/Dev/neovim-dev/opencode.nvim/.git/:0:/lua/opencode/state.lua` (diffview is not required, file does not need to exist)
4. `:lua print(vim.inspect(#vim.lsp.get_active_clients()))`

### Expected behavior

No new lsp servers should be spawned (and, even if they were, they should have the correct rootPath).

### Nvim version (nvim -v)

NVIM v0.12.0-dev-1569+g16c8152229

### Language server name/version

emmylua_ls 0.16.0

### Operating system/version

macOS 15.6.1

### Log file

https://gist.github.com/cameronr/3e9ee385af755fcbe5c2b5d333c04b0b

### PR DESCRIPTION
**Pull request by cameronr**
We may get a relative path from `vim.fs.root` if the buffer isn't backed by a file. That relative path will prevent us from re-using a client and will lead to us sending the lsp a `rootDir` of `/.``

Fix #36464
Fix #34208

### CODE REVIEW

**Comment by mfussenegger** [comment]
Note in https://github.com/neovim/neovim/issues/34208 the discussion outcome was that `vim.fs.root` should probably make sure to always return absolute paths.

File: test/functional/lua/fs_spec.lua [hunk 1]
```diff
@@ -432,6 +432,13 @@ describe('vim.fs', function()
       command('file lua://')
       eq(test_source_path, exec_lua([[return vim.fs.root(0, 'CMakePresets.json')]]))
     end)
+
+    it('returns an absolute path for an invalid filename', function()
+      command('new')
+      command('set buftype=nofile')
+      command('file lua://')
+      eq(test_source_path, exec_lua([[return vim.fs.root('file://asd', 'CMakePresets.json')]]))
+    end)
```
Comment (justinmk) [inline test/functional/lua/fs_spec.lua:442]: windows ci fail, need `t.fix_slashes`

i will push a fix + rebase

```
FAILED   test/functional/lua/fs_spec.lua @ 436: vim.fs root() returns an absolute path for an invalid filename
test/functional\lua\fs_spec.lua:440: Expected objects to be the same.
Passed in:
(string) 'D:\a\neovim\neovim'
Expected:
(string) 'D:/a/neovim/neovim'
```

File: test/functional/lua/fs_spec.lua [hunk 2]
```diff
@@ -432,6 +432,13 @@ describe('vim.fs', function()
       command('file lua://')
       eq(test_source_path, exec_lua([[return vim.fs.root(0, 'CMakePresets.json')]]))
     end)
+
+    it('returns an absolute path for an invalid filename', function()
+      command('new')
+      command('set buftype=nofile')
+      command('file lua://')
+      eq(test_source_path, exec_lua([[return vim.fs.root('file://asd', 'CMakePresets.json')]]))
```
Comment (justinmk) [inline test/functional/lua/fs_spec.lua]: this test is not actually asserting a full path...

Comment (cameronr) [reply test/functional/lua/fs_spec.lua]: Thanks for taking a look!

I'm not sure I understand your comment.

Before my change, `vim.fs.root('file:/asd')` would return `.` and after my change it returns the absolute path for the current working directory instead. For the test, `test_source_path` matches the absolute path for the current test and it passes with the change but fails with original code (because `.` doesn't match).

Maybe I'm missing something?

Comment (justinmk) [reply test/functional/lua/fs_spec.lua]: yes, I just meant that the test should actually check that `test_source_path` is absolute. see test update
