### PR TITLE
fix(api): limit depth of nvim_cmd

### LINKED ISSUE #27210: nvim_cmd: stack overflow when user command invokes itself
### Problem

I attempted to "wrap" a user-defined command like so:

```lua
vim.api.nvim_create_user_command('Test', 'echo "test"', {})

-- Get a callable function to the command
old = vim.cmd.Test

-- Use it in the new definition
vim.api.nvim_create_user_command('Test', function()
    old()
    vim.cmd('echo "test 2"')
end, {})
```

Sourcing the above and trying to execute `:Test` crashes neovim with a segmentation fault. Nothing is printed.

### Steps to reproduce

The above works with `nvim --clean -u NORC`

Note: run `tput rmcup` after neovim crashes to re-enable scrolling in the terminal.

### Expected behavior

It would be nice if it were somehow possible to do this (I currently use a `BufNew` autocmd to modify the behaviour of the `:Man` plugin command before it executes), but at the very least, Neovim shouldn't ever segfault from inside Lua code.

### Neovim version (nvim -v)

v0.10.0-dev-2150+ge68decab0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Debian sid

### Terminal name/version

wezterm 20240124-220416-642bfbb6

### $TERM environment variable

xterm-256color

### Installation

Nightly GitHub release tarball

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #27210

### CODE REVIEW

File: test/functional/api/vim_spec.lua [hunk 1]
```diff
@@ -399,6 +399,19 @@ describe('API', function()
...
+
+    it('errors properly when command too recursive', function()
+      exec_lua([[
+        _G.success = false
+        vim.api.nvim_create_user_command('Test', function()
+          vim.api.nvim_exec2('Test', {})
+          _G.success = true
+        end, {})
+      ]])
+      pcall_err(command, 'Test')
```
Comment (wookayin) [inline test/functional/api/vim_spec.lua:411]: It'd be great if the error message printed when stack overflows can be improved. (e.g. E169) The current one might look too messy? lots of repeated `Vim: Error executing Lua callback ....` string in a single line.

Comment (zeertzjq) [reply test/functional/api/vim_spec.lua:411]: This sounds quite complicated as the nesting can happen in any arbitrary structure.
