### PR TITLE
fix(runtime): 'includeexpr' with non-Nvim-style Lua modules

### LINKED ISSUE #33862: includeexpr for lua filetypes does not honour `path` and assumes lua directory for modules
### Problem

I noticed 'gf' was no longer working while working on some wezterm modules. So there are two (maybe more) problems with the `vim._ftplugin.lua` code, specifically:

https://github.com/neovim/neovim/blame/1e7406fa38eef8cb9812272196a97cf530218c4e/runtime/lua/vim/_ftplugin/lua.lua#L10C11-L10C11

1. Hardcoding 'lua/' directory as search location for modules doesn't work for Wezterm (which looks in `plugins/` relative to config file, not `lua/plugins/` like this code assumes), and
2. Hardcoding like this is not honouring any local `set path+=` I have done to add specific places to look when doing `gf` and friends.

@brianhuster 

### Steps to reproduce

```
cd /tmp
mkdir plugins
touch plugins/gohere.lua
nvim --clean
```

in neovim:

```
:set path+=plugins/
:e test.lua
```

input text:
```
require('plugins.gohere')
```

try `gf` on it, you should get `E447: Can't find file "plugins.gohere" in path`. Check `:set path?` and
you should have `path=.,,,plugins/`

This works in Vim, but not in Neovim because of `:e $VIMRUNTIME/lua/vim/_ftplugin/lua.lua`

### Expected behavior

`gf` to honour any `path` set by the user, and to not assume user is using lua in neovim codebase.

### Nvim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

No, latest Vim does not have this special lua file

### Operating system/version

Debian buster

### Terminal name/version

alacritty

### $TERM environment variable

tmux-256color

### Installation

source build

### PR DESCRIPTION
**Pull request by brianhuster**
Closes #33862

### CODE REVIEW

File: test/functional/editor/ftplugin_spec.lua [hunk 1]
```diff
@@ -94,4 +99,11 @@ describe("ftplugin: Lua 'includeexpr'", function()
     eq(temp_dir .. '/lua/runtime-foo/init.lua', lua_includeexpr('runtime-foo'))
     eq(temp_dir .. '/lua/runtime-foo/bar.lua', lua_includeexpr('runtime-foo.bar'))
   end)
+
+  it('Non-Nvim-style Lua modules', function()
```
Comment (justinmk) [inline test/functional/editor/ftplugin_spec.lua:103]:
```suggestion
  it('non-Nvim-style Lua modules', function()
```
