### PR TITLE
fix(exrc): exrc knows its own location

### LINKED ISSUE #34577: 'exrc' .nvim.lua script can know its location
### Problem

'exrc' `.nvim.lua` scripts don't have a way to [find their own location](https://github.com/neovim/nvim-lspconfig/issues/3910#issuecomment-2980236531).

> `debug.getinfo(1, 'S').source:sub(2)` could not be used since `.source` value it returns from inside of `.nvim.lua` is just `"<nvim>"`, there's no file path.

This is rather relevant for 'exrc' scripts since they are by definition project-local / workspace-local, and they need to know the project they are in.

### Expected behavior

Either we need to source 'exrc' scripts in a way that allows `debug.getinfo(...).source` to work, or we need some other mechanism that provides a way for scripts to reliably know their location:

- https://github.com/neovim/neovim/issues/32116

### PR DESCRIPTION
**Pull request by yochem**
Problem:
Unable to get script location in .nvim.lua using `debug.info(...)`.

Solution:
Provide the filename as `chunkname` argument to `loadstring()`.

Fixes: #34577

### CODE REVIEW

**Review by gpanders — CHANGES_REQUESTED** [review]
Use of loadstring over dofile is intentional to avoid TOCTOU bugs. The `trusted` string represents the buffer contents that are actually trusted by the user. The file contents can change, so that `dofile(file)` and `loadstring(trusted)` do not execute the same code.

All of vim.secure and the new exec implementation is designed around the concept of reading buffer contents into memory and then *only using those contents, always assuming the file can change afterwards*.

We need to find another way to solve the problem this PR is trying to address.

**Comment by yochem** [comment]
Of course! how could I forget about that, sorry. I'll see if I can find a solution.

**Comment by yochem** [comment]
I think the solution for this problem is [`load()`](https://www.lua.org/manual/5.1/manual.html#pdf-load), which has an optional chunk name of the string to be executed. Setting this chunkname to the filename ensures that `debug.getinfo(1, 'S')` can return the script name.

MWE:
1. Put the following in a `.nvim.lua` file in a parent directory (**not** current dir):
   ```lua
   local info = debug.getinfo(1, "S")
   local script_path = info.source:sub(2)
   local dir = script_path:match("(.*/)")
   print("My directory is:", dir)
   ```
4. `gh pr checkout 34638`
5. `make && VIMRUNTIME=./runtime ./build/bin/nvim --luamod-dev`
6. See `"My directory is: <full path to parent dir>"`

Again, this does not work yet for the exrc file in the current directory as it is handled in main.c. Furthermore, I'm not sure yet if this already worked for Vimscript files, probably not. If we were to also add support for vimscript files, maybe it would be better to include this in `vim.secure`? `vim.secure.execute()`?

File: runtime/lua/vim/_defaults.lua [hunk 1]
```diff
@@ -952,7 +952,8 @@ do
         local trusted = vim.secure.read(file) --[[@as string|nil]]
         if trusted then
           if vim.endswith(file, '.lua') then
-            assert(loadstring(trusted))()
+            local chunk = assert(load(trusted, '@' .. file))
+            chunk()
```
Comment (gpanders) [inline runtime/lua/vim/_defaults.lua]: `loadstring()` accepts a `chunkname` argument too so this could just be

```suggestion
            assert(loadstring(trusted, '@' .. file))()
```

**Comment by justinmk** [comment]
> this does not work yet for the exrc file in the current directory 

what does it return in that case?

> as it is handled in main.c

what do you mean by this?

**Comment by yochem** [comment]
> what does it return in that case?

The old behaviour, `'<nvim>'`.

> what do you mean by this?

The code in `_defaults.lua` merely extends the 'exrc' functionality to searching exrc files in *parent directories* of the current directory. The 'exrc' functionality for the current directory is already handled in https://github.com/neovim/neovim/blob/0b91e9f83b8807bf3fb584a70607deb1360824bd/src/nvim/main.c#L2057

The advantage of this is that if the user wants to revert to the old behaviour of only loading 'exrc' files found in the current directory, they simply disable the autocmd that searches the parent directories: `autocmd! nvim.exrc`. 

Of course I'm planning to also add the functionality to exrc files in the current directory, but my C and liblua knowledge is not that great, so it'll take me a bit more time to work on that.

**Comment by yochem** [comment]
It seems like `nlua_exec` sets the `'<nvim>'` string for the context. Would it be okay here to add a 'optional' param `chunkname` that can set the chunkname? Currently nlua_exec seems to be called 5 times in total, so the additional LOC changes are low. I.e.:

From:
```c
/// @param[in]  str  String to execute.
/// @param[in]  args array of ... args
/// @param[in]  mode Whether and how the the return value should be converted to Object
/// @param[in] arena  can be NULL, then nested allocations are used
/// @param[out]  err  Location where error will be saved.
```

To:
```c
/// @param[in]  str  String to execute.
/// @param[in]  chunkname Optional chunkname for executed Lua string.
/// @param[in]  args array of ... args
/// @param[in]  mode Whether and how the the return value should be converted to Object
/// @param[in] arena  can be NULL, then nested allocations are used
/// @param[out]  err  Location where error will be saved.
```

File: src/nvim/lua/executor.c [hunk 2]
```diff
@@ -1512,17 +1512,19 @@ int typval_exec_lua_callable(LuaRef lua_cb, int argcount, typval_T *argvars, typ
 /// Used for nvim_exec_lua() and internally to execute a lua string.
 ///
 /// @param[in]  str  String to execute.
+/// @param[in]  chunkname Optional chunkname of executed string.
```
Comment (justinmk) [inline src/nvim/lua/executor.c]:
```suggestion
/// @param[in]  name Chunkname, defaults to "<nvim>".
```

**Comment by yochem** [comment]
How do I fix the lint CI? It shows the following:

```
FAIL: /home/runner/work/neovim/neovim/src/nvim/lua/executor.c (File size changed from 65348 to 65365)
```

I get the same error locally. Any idea?

---

Other than that, I think this is ready for review. Should I update docs? E.g. mentioning `|debug.getinfo()|` at `|<script>|` or `'exrc'`?

**Comment by zeertzjq** [comment]
`make format`

**Comment by clason** [comment]
`make formatc` should do the trick.

**Comment by justinmk** [comment]
> Should I update docs? E.g. mentioning `|debug.getinfo()|` at `|<script>|` or `'exrc'`?

yes

**Review by gpanders — APPROVED** [review]

**Comment by justinmk** [comment]
probably worth a 1-line assert in an existing exrc test
