### PR TITLE
fix(tui): resize at startup

### LINKED ISSUE #11330: Neovim does not resize itself when launched as initial command for terminal.
- `nvim --version`: 0.4.2
- Operating system/version: Void Linux 5.3.8
- Terminal name/version: Alacritty 0.3.3

### Steps to reproduce:
1) Launch Alacritty, then type `nvim`, hit Return;
2) Launch Alacritty, enter command `alacritty --command nvim`, hit Return;

### Actual behaviour
In first case nvim is sized correctly.
In second case nvim has default size, which is independent of Alacritty window size.

### Expected behaviour
Neovim expected to be sized incorrectly in second case.

### LINKED ISSUE #15044: Window resize shortly after start is ignored
- `nvim --version`: 0.5.0
- Operating system/version: Debian 10
- Terminal name/version: xfce4terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

In the i3 window manager open a terminal window and type:

```
xfce4-terminal -x nvim -u NORC; xfce4-terminal
```

The above simulates the opening of 2 windows, where the second shortly appears after the first and causes a resize of the former. With the `i3` window manager this is a very common scenario. 

### Actual behaviour

The window resize caused by opening the last window is ignored. All lines are formatted wrongly (see screenshot).

Screenshot_2021-07-10_09-08-46

### Expected behaviour

Neovim should buffer the resize event in case it can not execute it immediately.

### LINKED ISSUE #17285: SIGWINCH is not honored, window does not resize itself correctly
### Neovim version (nvim -v)

v0.7.0-dev+1002-g59fa5f4ec

### Vim (not Nvim) behaves the same?

no, 8.2.4293

### Operating system/version

macOS 12.1

### Terminal name/version

iTerm2, 3.4.12

### $TERM environment variable

tmux-256color

### Installation

brew install nvim -s --HEAD

### How to reproduce the issue

Hard to reproduce, first open nvim in such a way that it does not occupy the entire terminal screen. In my case it happens with a combination of tmux+tmux-resurrect at times. Then find the PID of the tty and nvim running in it, I use htop. Finally send SIGWINCH to both tty and nvim. In my case it just messes up the nvim buffer, things look haywire.

### Expected behavior

Neovim should not open erratically such that it does not occupy the full size of tty it is opened in. Moreover, if it has opened like this, it should honor SIGWINCH and resize itself.

### Actual behavior

Neovim does not open to fully occupy the size of tty it is opened in. If it does open like this, it does not honor a SIGWINCH sent from another tty command line.

### PR DESCRIPTION
**Pull request by muniter**
I've changed the PR of this approach to follow-on @erw7 https://github.com/neovim/neovim/issues/11330#issuecomment-1086617448

Which has two parts:

1. Removing the following code:

https://github.com/neovim/neovim/blob/af1b61f342618aa8d27c6e1dcbb0e360920ca89e/src/nvim/tui/tui.c#L1481-L1489

I debugged that this was the main issue in my system and perhaps in tiling window managers in general.

When the function `tui_guess_size` is called twice during startup the non-default 'columns' and 'lines' is usually true after the first time, because this same function already changed those values. Basically it's tricking itself, unrelated if the "lines" and "columns" options was set or not.

Added a test with the provided repro which fails before these changes.

2. Making got_winch a counter

If I understand things correctly this avoids resizing the host terminal until we have processed the last sigwinch, compared to the previous state of things:

> The second bug is that tui_grid_resize may change the size of the host terminal between the signal handler and the call to sigwinch_cb (note: the signal handle (uv__signal_handle) does not directly call the callback) when multiple SIGWINCH occur. I have confirmed that this actually happens in the following way using nvim with DLOG added.

Also removed the volatile since is not needed: https://github.com/neovim/neovim/pull/19210

PD: I'd be thrilled if @erw7 took over this, it's his proposed solution :D

Fixes #17285
Fixes #15044
Fixes #11330

### CODE REVIEW

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -496,7 +498,19 @@ static void sigcont_cb(SignalWatcher *watcher, int signum, void *data)
...
+  int width = ui->width;
+  int height = ui->height;
+  sigwinch_logic(timer->data);
+  if (width != ui->width || height != ui->height) {
+    // Don't try again if the size changed.
+    uv_timer_stop(timer);
+  }
+}
+
+static inline void sigwinch_logic(void *data)
```
Comment (zeertzjq) [inline src/nvim/tui/tui.c:513]: This name looks a bit strange. Maybe `handle_sigwinch` is better?

**Comment by zeertzjq** [comment]
Hmm, this seems to cause a memory leak with `--version`.

**Comment by zeertzjq** [comment]
This causes a memory leak:
```
./build/bin/nvim --clean +qa
```

File: src/nvim/tui/tui.c [hunk 2]
```diff
@@ -508,6 +522,11 @@ static void sigwinch_cb(SignalWatcher *watcher, int signum, void *data)
   ui_schedule_refresh();
```
Comment (bfredl) [inline src/nvim/tui/tui.c:522]: we should change this to only schedule a refresh if the TUI size actually changed (could be done in a follow-up PR if it gets too messy)

File: src/nvim/tui/tui.c [hunk 3]
```diff
@@ -939,6 +962,15 @@ static void tui_grid_resize(UI *ui, Integer g, Integer width, Integer height)
   UGrid *grid = &data->grid;
   ugrid_resize(grid, (int)width, (int)height);
 
+  // When the UI starts, it might not be possible to resize correctly.
+  // https://github.com/neovim/neovim/issues/15044
```
Comment (justinmk) [inline src/nvim/tui/tui.c:966]:
```suggestion
  // When the UI starts, it might not be possible to resize correctly. #15044
```

File: src/nvim/tui/tui.c [hunk 4]
```diff
@@ -135,6 +136,7 @@ typedef struct {
   char *space_buf;
 } TUIData;
 
+static bool volatile first_resize = true;
```
Comment (justinmk) [inline src/nvim/tui/tui.c:139]: usual convention is "did" prefix:
```suggestion
static bool volatile did_resize = true;
```

Comment (muniter) [reply src/nvim/tui/tui.c]: Went ahead an renamed, and also moved into scope where I think its purpose clearer, it also didn't need `volatile`.

Semantically `did_user_set_dimensions` is to not resize the **host terminal window**.

This PR and the new variable `did_first_resize` is about resizing the **TUI** correctly and **only at startup**.

File: src/nvim/tui/tui.c [hunk 5]
```diff
@@ -474,6 +477,7 @@ static void tui_main(UIBridgeData *bridge, UI *ui)
   signal_watcher_stop(&data->cont_handle);
   signal_watcher_close(&data->cont_handle, NULL);
   signal_watcher_close(&data->winch_handle, NULL);
+  uv_close((uv_handle_t *)&data->initial_resize_timer, NULL);
```
Comment (zeertzjq) [inline src/nvim/tui/tui.c:480]: Is is possible that `initial_resize_timer` can be uninitialized here?

**Comment by muniter** [comment]
I think this is in a nice state. Haven't been able to test it. I had the following idea:

1. Launch nvim
2. Immediately block SIGWINCH using ffi (also tried `trap`).
3. Resize the host tty `job_resize`.
4. Check than nvim resized correctly.

But I'm failing at step 2. Wrote this code, nvim is still receiving SIGWINCH.

```lua
local ffi = require("ffi")
ffi.cdef[=[
typedef struct
{
  unsigned long int __val[(1024 / (8 * sizeof (unsigned long int)))];
} __sigset_t;
typedef __sigset_t sigset_t;
int sigaddset(sigset_t *set, int signo);
int sigprocmask(int how, const sigset_t *set, sigset_t *oset);
]=]

local defs = {
  SIG_BLOCK = 0,
  SIGWINCH = 28,
}

local mask_pt = ffi.new("sigset_t[1]")
local add = ffi.C.sigaddset(mask_pt[0], defs.SIGWINCH)
local mask = ffi.C.sigprocmask(defs.SIG_BLOCK, mask_pt[0], nil)
assert(add == 0 and mask == 0)  -- This is working
```

So I will run this build for a few days and report back.

CI failures seem unrelated, perhaps a re run?

**Comment by erw7** [comment]
I have checked the following steps and I do not believe this change will solve the problem.

```vim
nvim --clean
:call termopen(['nvim', '--clean', '--cmd', 'let start = reltime() | while v:true | if reltimefloat(reltime(start)) > 2 | break | endif | endwhile']) | slee
p 500m | vs
```

**Comment by erw7** [comment]
The cause and fix for the bug you attempted to fix in this PR is described by me in https://github.com/neovim/neovim/issues/11330#issuecomment-1086617448. Unfortunately, I don't think this PR method will fix it.

**Comment by muniter** [comment]
I've updated the PR description, with the change of direction.

File: test/functional/terminal/tui_spec.lua [hunk 6]
```diff
@@ -85,6 +85,23 @@ describe('TUI', function()
     assert_alive()
   end)
 
+  it('works correctly at startup', function()
+    screen:try_resize(50, 10)
+    feed_command([[call termopen(['build/bin/nvim', '--clean', '--cmd', 'let start = reltime() | while v:true | if reltimefloat(reltime(start)) > 2 | break | endif | endwhile']) | sleep 500m | vs new]])
```
Comment (justinmk) [inline test/functional/terminal/tui_spec.lua:90]:
```suggestion
    feed_command([[call termopen([v:progpath, '--clean', '--cmd', 'let start = reltime() | while v:true | if reltimefloat(reltime(start)) > 2 | break | endif | endwhile']) | sleep 500m | vs new]])
```

File: test/functional/terminal/tui_spec.lua [hunk 7]
```diff
@@ -85,6 +85,23 @@ describe('TUI', function()
     assert_alive()
   end)
 
+  it('works correctly at startup', function()
```
Comment (justinmk) [inline test/functional/terminal/tui_spec.lua:88]: "works correctly" is almost always unnecessary in a test description, because tests are usually testing that things work correctly.
```suggestion
  it('resize at startup', function()
```

File: test/functional/terminal/tui_spec.lua [hunk 8]
```diff
@@ -85,6 +85,23 @@ describe('TUI', function()
...
+    feed_command([[call termopen(['build/bin/nvim', '--clean', '--cmd', 'let start = reltime() | while v:true | if reltimefloat(reltime(start)) > 2 | break | endif | endwhile']) | sleep 500m | vs new]])
+    screen:expect([[
+      {1: }                        │                        |
+      {4:~                        }│{4:~                       }|
+      {4:~                        }│{4:~                       }|
+      {4:~                        }│{4:~                       }|
+      {4:~                        }│{4:~                       }|
+      {4:~                        }│{5:[No Name]   0,0-1    All}|
+      {4:~                        }│                        |
+      {5:new                       }{1:</neovim/build/bin/nvim }|
```
Comment (justinmk) [inline test/functional/terminal/tui_spec.lua:99]: can use `{MATCH:x}` so that we don't hardcode the path, see `screen.lua`.

```suggestion
      {5:new                       }{MATCH:<.*[/\]nvim }|
```

**Comment by justinmk** [comment]
Very eager to get this fixed! Has a minor conflict because of https://github.com/neovim/neovim/commit/436747752bf1016d93101de24e39e192a0b721b4

**Comment by muniter** [comment]
Found a bug in screen.lua that was reproduced by the test in this PR when using `MATCH`. 
Added it here since it was such a small change and if I move it to another PR this one has to be rebased on top of it. But I'm fine moving it if needed.

**Comment by justinmk** [comment]
Oh, we need to update the doc here: https://github.com/neovim/neovim/issues/17285#issuecomment-1030512165

**Comment by muniter** [comment]
> Do we need to update the doc here?: [#17285 (comment)](https://github.com/neovim/neovim/issues/17285#issuecomment-1030512165)

I don't think so, the code indicates we follow that process. From my point of view we  actually removed an undocumented case 🤔
