### PR TITLE
[RDY] lsp: clear diagnostics on client shutdown

### LINKED ISSUE #13695: lsp doesn't seem to erase old error messages
- `nvim --version`: NVIM v0.5.0-dev+950-g5ce328df4
- language server name/version: typescript-language-server 0.4.0
- Operating system/version: Ubuntu 20.04.1 x86_64

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>

```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: tsserver: configuration checked.
```

</details>

<details>
<summary>lsp.log</summary>

```
[ ERROR ] 2021-01-05T11:32:00-0500 ] ...imjR0wyh/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:265 ]	'[tsserver] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})\n\n'
```
</details>

### Steps to reproduce using `nvim -u NORC`

Will have a reproducible project up soon.

```
nvim -u NORC
```

### Actual behaviour
After tabopening a new file, lsp seems to stop working. then on restarting the lsp with
`lua vim.lsp.stop_client(vim.lsp.get_active_clients())`
and `:edit`, the old error messages don't go away or get updated

### Expected behaviour
Old error messages should go away

### PR DESCRIPTION
**Pull request by mjlbach**
closes #13695

I also want to be able to list buffers by client for better reporting in `:LspInfo`, which this PR addresses as well 
with `vim.lsp.get_buffers_by_client_id()`

@pretentious7 try this out. It will respect the list of client_ids you pass in, so you can limit it to the client attached to the current buffer as well.

https://user-images.githubusercontent.com/13316262/104971905-131bd880-59a5-11eb-9457-d26d7d1e97b0.mov

### CODE REVIEW

**Comment by mjlbach** [comment]
Lualint is failing because of #13789 (nothing to do with this PR)

File: runtime/lua/vim/lsp.lua [hunk 1]
```diff
@@ -948,6 +951,14 @@ function lsp.buf_attach_client(bufnr, client_id)
       utf_sizes = true;
     })
   end
+
+  local client_buffer_ids = all_client_active_buffers[client_id]
+  if not client_buffer_ids then
+    all_client_active_buffers[client_id] = { bufnr }
+  else
+    table.insert(all_client_active_buffers[client_id], bufnr)
+  end
```
Comment (tjdevries) [inline runtime/lua/vim/lsp.lua:960]: I usually prefer to write:

```lua
if not all_client_active_buffers[client_id] then
  all_client_active_buffers[client_id] = {}
end

table.insert(all_client_active_buffers[client_id], bufnr)
```

**Comment by tjdevries** [comment]
Doesn't look like we remove the references anywhere to the table? We should nil them out I think (maybe I just missed it)

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp.lua:960]: Thanks! That's cleaner.

**Comment by mjlbach** [comment]
You did not. Thanks for catching that, I added it here https://github.com/neovim/neovim/pull/13788/files#diff-c6a4160a416b22cd1fd833b8f852c4fbaf1f25adf75053e82a1025aa2c607ac9R1037.

The test failure seems to be due to my ill-fated attempts towards xdg log compliance 

```
stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/core/startup_spec.lua:238: in function <test/functional/core/startup_spec.lua:236>


 21 SKIPPED TESTS
 1 ERROR
-- Tests exited non-zero: 1
-- Output to stderr:
ERROR 2021-01-18T18:29:01.934 39015 open_log_file:211: Logging to stderr, failed to open $NVIM_LOG_FILE: Xtest-startup-xdg-logpath/nvim/log
WARN  2021-01-18T18:29:01.934 39015 call_set_error:627: RPC: ch 1 was closed by the client
ERROR 2021-01-18T18:29:01.938 39015 open_log_file:211: Logging to stderr, failed to open $NVIM_LOG_FILE: Xtest-startup-xdg-logpath/nvim/log
INFO  2021-01-18T18:29:01.938 39015 os_exit:586: Nvim exit: 0

CMake Error at /Users/michael/Repositories/neovim_development/neovim/cmake/RunTests.cmake:85 (message):
  functional tests failed with error: 1
```

**Comment by teto** [comment]
cool feature. I wonder about exposing get_buffers_by_client_id, it seems quite specific ?

**Comment by mjlbach** [comment]
The main reason I'm exposing it, is I'd like to add a "Buffers attached:" line to `:LspInfo` which will come in handy when I add multi-root workspace support (which is there, but not automatic)
