### PR TITLE
fix(lsp): ignore out-of-range items from inline completion

### LINKED ISSUE #35971: LSP: inline completion errors with Index out of bounds
### Problem

Error index out of bound appears when removing characters on the last row in insert mode while using copilot with inline completion enabled.
I am using configuration for copilot from [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/lsp/copilot.lua).

Error:
```
Error in CursorMovedI Autocommands for "*":
Lua callback: ...cal/share/nvim/runtime/lua/vim/lsp/inline_completion.lua:223: Index out of bounds
stack traceback:
        [C]: in function 'nvim_buf_get_lines'
        ...cal/share/nvim/runtime/lua/vim/lsp/inline_completion.lua:223: in function 'show'
        ...cal/share/nvim/runtime/lua/vim/lsp/inline_completion.lua:296: in function 'automatic_request'
        ...cal/share/nvim/runtime/lua/vim/lsp/inline_completion.lua:80: in function <...cal/share/nvim/runtime/lua/vim/lsp/inline_completion.lua:79>
```

### Steps to reproduce using "nvim -u minimal_init.lua"

1. [minimal_init.lua](https://gist.github.com/danbulgar/d025e3cadeb68052ba6817cd4aab8010#file-minimal_init-lua) is just a config from nvim-lspconfig and inline completion enabled. Copy its content to `minimal_init.lua`.
2. Install [copilot-language-server](https://github.com/github/copilot-language-server-release).
2. Open a file using `nvim --clean -u minimal_init.lua`, for example `nvim --clean -u minimal_init.lua minimal_init.lua`.
3. Go to last line, remove all characters, in insert mode press backspace to move to the previous line.

### Expected behavior

Expected to move to previous line without error.

### Nvim version (nvim -v)

v0.12.0-dev-1329+ga053186a

### Language server name/version

copilot-language-server 1.378.0

### Operating system/version

WSL 2 / Ubuntu 24.04.2

### Log file

_No response_

### PR DESCRIPTION
**Pull request by ofseed**
Fixes https://github.com/neovim/neovim/issues/35971.

### CODE REVIEW

**Comment by arkriny** [comment]
#35992 should prevent OOB cases, but I think it's still may be worth being less strict about invalid ranges

**Comment by ofseed** [comment]
There are many ways to implement OOB checks, but apart from immediately discarding expired candidates, none of them are absolutely reliable. The reason I didn’t choose this approach is explained in the comments of this PR. 

To add further context, given the feature of inline completion, I place very high priority on “what you see is what you get,” which inevitably requires us to display positions from past versions of the buffer—even though those positions may no longer be valid. Considering Neovim’s extensibility, it’s difficult for us to enumerate every possible use case and filter which ones we should address.

**Comment by arkriny** [comment]
> To add further context, given the feature of inline completion, I place very high priority on “what you see is what you get,” which inevitably requires us to display positions from past versions of the buffer—even though those positions may no longer be valid.

If the line number is OOB, we can't display virtual text for the completion, so it should be discarded to prevent accepting it. Currently, this PR prevents the error on rendering but does not discard the completion, allowing it to be accepted within the 200ms debounce window and causing another OOB error from `nvim_buf_set_text`. I wonder why `nvim_buf_set_extmark` does not fail when given an OOB `row` parameter.

**Comment by ofseed** [comment]
> this PR prevents the error on rendering but does not discard the completion

It’s not this PR that prevents those out-of-bounds completions from being rendered; what actually ignores them is `nvim_buf_set_extmark`. The logic modified by this PR is independent; it is used to skip some virtual text that overlaps with the text in the buffer, while the out-of-bounds access occurs when reading from the buffer.

**Comment by arkriny** [comment]
> > this PR prevents the error on rendering but does not discard the completion
> 
> It’s not this PR that prevents those out-of-bounds completions from being rendered; what actually ignores them is `nvim_buf_set_extmark`. 

I literally said "prevents the error": previously, an error occurred in case of OOB. Now, this PR prevents the error in `.show()` but doesn't discard the completion, which allows an OOB error to occur later in `.accept()`.

> while the out-of-bounds access occurs when reading from the buffer.

I understand; that's why the completion should be discarded.

**Comment by ofseed** [comment]
Because my reply to #35992 was also a reply to this, I’m putting it here:

> No, I meant that the state used for accepting a completion should match the actual extmarks in the buffer. In other words - if `.show()` fails for any reason (for example, if the range is OOB), we should discard the state by setting `self.current = nil` and prevent accepting the completion.

I support this idea; it aligns with WYSIWYG, but I think this is a new issue beyond the scope of these two PRs we are discussing. It should be described as "illegal completions that were not rendered can still be `accept`ed," whereas the common point of the two PRs we're discussing now is "which completions should be considered illegal." Given how unlikely it is that someone would `accept()` an illegal completion in the very short time before a valid completion is updated without seeing the illegal completion, I would give such an issue a low priority.

That said, I do have an idea to synchronize this state. When completing the inline completion feature, I also added the initial support of `vim.range`, and I plan to add a method so we have a general way to check whether a range is out of bounds. Then we can prevent OOB completions from being rendered and discharge them. However, I'm extremely busy this year, so I don't have time to continue pushing `vim.range` at this moment.

**Comment by arkriny** [comment]
> I support this idea; it aligns with WYSIWYG, but I think this is a new issue beyond the scope of these two PRs we are discussing.

I believe that previously, either `nvim_buf_get_lines` or `nvim_buf_set_extmark` would fail on an invalid range. Now, with this PR, when the error from `nvim_buf_get_lines` is suppressed, it becomes possible to accept an invalid (and thus not rendered) completion. If you address https://github.com/neovim/neovim/pull/35990#issuecomment-3360865412 and fix this, I think both PRs would be ok to merge. Though I agree that it would also be good to generalize the "discarding" logic for both cases.

**Comment by ofseed** [comment]
I'm not arguing about which PR should be merged; my focus is on finding the simplest possible approach to implement one solution that covers as many use cases as possible while minimizing attention to individual edge cases. Such an effort may make more sense for a repository this large.

**Comment by ribru17** [comment]
I often run into this issue when not on the last line, after deleting a few characters from the end of a line which has an active completion

**Comment by arkriny** [comment]
> I often run into this issue when not on the last line, after deleting a few characters from the end of a line which has an active completion

This is probably not a line OOB issue, but rather `Invalid 'col': out of range`, if it occurs not on the last line. It likely happens because the completion range start moves past the end of the line (though language servers should "prefer replacements over insertions to provide a better experience when the user deletes typed text" as stated in the spec).
It seems all we need to do is validate both `col` and `row` and discard the completion if it's invalid.

**Comment by arkriny** [comment]
Something similar exists in [semantic_tokens](https://github.com/neovim/neovim/blob/28ccebd138ac1bccb13f7515bb647ed550fa94c5/runtime/lua/vim/lsp/semantic_tokens.lua#L434). The difference here is that we also need a cleanup step, so we can't just rely on `strict = false`. Maybe we could do something like this instead:
```lua
  if not pcall(api.nvim_buf_set_extmark,self.bufnr, namespace, row, col, {
    virt_text = virt_text,
    virt_lines = virt_lines,
    virt_text_pos = current.range and 'overlay' or 'inline',
    hl_mode = 'combine',
  }) then
    self.current = nil
  end
```
@ofseed WDYT?

**Comment by ofseed** [comment]
I pushed a change for the same purpose.

File: runtime/lua/vim/lsp/inline_completion.lua [hunk 1]
```diff
@@ -214,15 +214,25 @@ function Completor:show(hint)
...
-  -- which should be skipped before displaying the virtual text.
   local pos = current.range and current.range.start:to_extmark()
     or vim.pos.cursor(api.nvim_win_get_cursor(vim.fn.bufwinid(self.bufnr))):to_extmark()
   local row, col = unpack(pos)
+
+  -- To ensure that virtual text remains visible continuously (without flickering)
+  -- while the user is editing the buffer, we allow displaying expired virtual text.
+  -- Since the position of virtual text may become invalid after document changes,
+  -- out-of-range items are ignored.
+  local line_text = api.nvim_buf_get_lines(self.bufnr, row, row + 1, false)[1]
```
Comment (arkriny) [inline runtime/lua/vim/lsp/inline_completion.lua:225]: We can skip this check when  `current.range == nil` since in that case `pos = vim.pos.cursor(api.nvim_win_get_cursor(vim.fn.bufwinid(self.bufnr))):to_extmark()`, which is always valid.

I also think this check could be performed earlier, before the expensive `for in vim.gsplit` on L210

Comment (justinmk) [reply runtime/lua/vim/lsp/inline_completion.lua:225]: can that be a followup or does it block this pr

Comment (arkriny) [reply runtime/lua/vim/lsp/inline_completion.lua:225]: not blocking, just perf improvements. Can be follow up after rebasing in #35992.
