### PR TITLE
Make session restoration compatible with tab-local working directories

### LINKED ISSUE #9753: Buffers are not correctly reloaded from saved sessions when using :tcd
- `nvim --version`:

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/config -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/src/nvim/auto -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.4/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently?

N/A. AFAIK `:tcd` (tab-local working directories) is a neovim-exclusive feature

- Operating system/version: macOS Majave 10.14.3
- Terminal name/version: iTerm2 3.2.7
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```sh
mkdir repro
mkdir repro/foo
mkdir repro/bar
echo 'foo' > repro/foo/foo.txt
echo 'bar' > repro/bar/bar.txt
cd repro
```

```vim
nvim -u NORC
:tcd foo
:edit foo.txt
:tabnew
:edit ../bar/bar.txt
:mksession! ~/broken-session.vim
:qa
nvim -u NORC -S ~/broken-session.vim
:echo expand('%:p')
```

### Actual behaviour

```
bar/bar.txt
```

The contents of `bar.txt` are not displayed. 

### Expected behaviour

```
/Users/chris.larose/dev/repro/bar/bar.txt
```

The contents of `bar.txt` are displayed.

### Additional info

<details>
<summary>
~/broken-session.vim
</summary>

```vim
let SessionLoad = 1
let s:so_save = &so | let s:siso_save = &siso | set so=0 siso=0
let v:this_session=expand("<sfile>:p")
silent only
cd ~/dev/repro
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
set shortmess=aoO
badd +0 foo/foo.txt
badd +0 bar/bar.txt
argglobal
silent! argdel *
set stal=2
edit foo/foo.txt
set splitbelow splitright
set nosplitbelow
set nosplitright
wincmd t
set winminheight=0
set winheight=1
set winminwidth=0
set winwidth=1
argglobal
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
silent! normal! zE
let s:l = 1 - ((0 * winheight(0) + 26) / 53)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
1
normal! 0
if has('nvim') | tcd ~/dev/repro/foo | endif
tabedit bar/bar.txt
set splitbelow splitright
set nosplitbelow
set nosplitright
wincmd t
set winminheight=0
set winheight=1
set winminwidth=0
set winwidth=1
argglobal
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
silent! normal! zE
let s:l = 1 - ((0 * winheight(0) + 26) / 52)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
1
normal! 0
if has('nvim') | tcd ~/dev/repro/foo | endif
tabnext 2
set stal=1
if exists('s:wipebuf') && getbufvar(s:wipebuf, '&buftype') isnot# 'terminal'
  silent exe 'bwipe ' . s:wipebuf
endif
unlet! s:wipebuf
set winheight=1 winwidth=20 winminheight=1 winminwidth=1 shortmess=filnxtToOF
let s:sx = expand("<sfile>:p:r")."x.vim"
if file_readable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &so = s:so_save | let &siso = s:siso_save
doautoall SessionLoadPost
unlet SessionLoad
" vim: set ft=vim :
```
</details>

The problem, I think, is that after issuing `:tcd ~/dev/repro/foo`, paths after that command are interpreted to be relative to that directory. However, the command `tabedit bar/bar.txt` assumes that the path will be interpreted relative to the "global" working directory.

### PR DESCRIPTION
**Pull request by cjlarose**
Fixes #9753

The implementation here is pretty quick-n-dirty. Basically, when writing a session file, there's a flag that is set to `false` initially called `did_lcd`, and gets flipped to `true` if any `:lcd` command is written to the session file. The flag is read when writing any file path out to the session file to determine if a "short path" should be written or not:

https://github.com/neovim/neovim/blob/291d7d75223c3aa2334fc780de50a7dc0565d0c3/src/nvim/ex_docmd.c#L9579-L9589

The proposed change abuses the same flag for whenever a `:tcd` command is written to the session file, guaranteeing that we write out correct paths after that command.

A more elegant solution might be to use a new flag (`did_tcd`) or rename the flag (`did_lcd_or_tcd`). I'm open to collaborating on another solution if the proposed one is too janky.

### CODE REVIEW

**Comment by cjlarose** [comment]
CI looks like it's failing because it's timing out on the new test. It passes for me locally. Any ideas on what might be going on?

**Comment by mhinz** [comment]
I just did a quick checkout and it hangs for me locally (macOS) as well. And since it hangs for all CI platforms, there must be a bug in your code.

Will have a look later.

**Comment by mhinz** [comment]
Okay, it's actually a quite common issue with Vim: the `:h press-enter` prompt.

When doing `:source ...`, it tries to print the path, but the path is very long in your case, it doesn't fit into one line and thus triggers the press-enter prompt.

How to find what's going on? Visalizing the screen!

```
diff --git i/test/functional/ex_cmds/mksession_spec.lua w/test/functional/ex_cmds/mksession_spec.lua
index d1589892b..6db2d0c67 100644
--- i/test/functional/ex_cmds/mksession_spec.lua
+++ w/test/functional/ex_cmds/mksession_spec.lua
@@ -64,7 +64,11 @@ describe(':mksession', function()
     -- Create a new test instance of Nvim.
     clear()

+    local Screen = require('test.functional.ui.screen')
+    local screen = Screen.new()
+    screen:attach()
     command('source ' .. session_path)
+    screen:snapshot_util()
     command('tabnext 1')
     eq(cwd_dir .. get_pathsep() .. tmpfile_base .. '1', eval("fnamemodify(bufname('%'), ':p')"))
     command('tabnext 2')
```

Before the tests starts hanging, it would print:

```
screen:expect([[
                                                       |
  {1:~                                                    }|
  {1:~                                                    }|
  {1:~                                                    }|
  {1:~                                                    }|
  {1:~                                                    }|
  {1:~                                                    }|
  {1:~                                                    }|
  {1:~                                                    }|
  {1:~                                                    }|
  {2:                                                     }|
  "/data/github/neovim/neovim/Xtest-functional-ex_cmds-|
  mksession_spec-tmpfile2" [New File]                  |
  {3:Press ENTER or type command to continue}^              |
]], {
  [1] = {bold = true, foreground = Screen.colors.Blue1},
  [2] = {bold = true, reverse = true},
  [3] = {bold = true, foreground = Screen.colors.SeaGreen4},
})
```

See my long local path? Not good. :) In this case we can simply use `:silence source ...` instead.

File: test/functional/ex_cmds/mksession_spec.lua [hunk 1]
```diff
@@ -47,4 +48,26 @@ describe(':mksession', function()
...
+    command('tcd ' .. tab_dir)
+    command('tabnew')
+    command('edit ' .. cwd_dir .. get_pathsep() .. tmpfile_base .. '2')
+    command('tabfirst')
+    command('mksession ' .. session_path)
+
+    -- Create a new test instance of Nvim.
+    clear()
+
+    command('source ' .. session_path)
```
Comment (mhinz) [inline test/functional/ex_cmds/mksession_spec.lua]:
```suggestion
    command('silent source ' .. session_path)
```

File: test/functional/ex_cmds/mksession_spec.lua [hunk 2]
```diff
@@ -47,4 +48,26 @@ describe(':mksession', function()
...
+    command('tabnext 1')
+    eq(cwd_dir .. get_pathsep() .. tmpfile_base .. '1', eval("fnamemodify(bufname('%'), ':p')"))
```
Comment (mhinz) [inline test/functional/ex_cmds/mksession_spec.lua]:
```suggestion
    eq(cwd_dir .. get_pathsep() .. tmpfile_base .. '1', funcs.expand('%:p'))
```

File: test/functional/ex_cmds/mksession_spec.lua [hunk 3]
```diff
@@ -47,4 +48,26 @@ describe(':mksession', function()
...
+    command('tabnext 2')
+    eq(cwd_dir .. get_pathsep() .. tmpfile_base .. '2', eval("fnamemodify(bufname('%'), ':p')"))
```
Comment (mhinz) [inline test/functional/ex_cmds/mksession_spec.lua]:
```suggestion
    eq(cwd_dir .. get_pathsep() .. tmpfile_base .. '2', funcs.expand('%:p'))
```

Comment (mhinz) [reply test/functional/ex_cmds/mksession_spec.lua]: Afterwards, `local eval = helpers.eval` can be removed again.

**Comment by cjlarose** [comment]
Thanks for debugging the failure, @mhinz! That screenshot utility is very handy! It might be worth a mention in `tests/README.md` if it's not already documented somewhere.

**Review by mhinz — APPROVED** [review]
LGTM

**Comment by cjlarose** [comment]
@mhinz Tests are green now. Is there anything else required from me to move this PR along?

File: test/functional/ex_cmds/mksession_spec.lua [hunk 4]
```diff
@@ -47,4 +47,27 @@ describe(':mksession', function()
     command('tabnext 2')
     eq(cwd_dir .. get_pathsep() .. tab_dir, funcs.getcwd())
   end)
+
+  it('restores buffers when using tab-local working directories', function()
```
Comment (justinmk) [inline test/functional/ex_cmds/mksession_spec.lua]: this is almost identical to the `restores tab-local working directories` test, so that test should just be enhanced rather than creating a new one.

**Comment by mhinz** [comment]
Thanks!

https://github.com/neovim/neovim/blob/master/test/README.md#debugging-tests was also improved as suggested.
