### PR TITLE
win/Terminal: Change to use ConPTY, if available

### LINKED ISSUE #9016: Windows: TUI: messed up screen after resizing :terminal
- `nvim --version`:
- Vim (version: ) behaves differently?
- Operating system/version:
   windows 10
- Terminal name/version:
    nvim 0.3.1
- `$TERM`:

### Steps to reproduce using `nvim`

1.  Just start nvim from windows 10 cmd.
2.  start the :terminal mode.
3.  **npm start**.
4.   Win+upRow resize the nvim window.

### Actual behaviour
The window is weird  : 
image

### Expected behaviour

Should be normal window.

### PR DESCRIPTION
**Pull request by erw7**
This PR allows you to use 24-bit color on Windows terminals.

conpty

Edited: This may fix #9016.

### CODE REVIEW

File: src/nvim/option_defs.h [hunk 1]
```diff
@@ -645,6 +645,7 @@ EXTERN char_u *p_titleold;      ///< 'titleold'
 EXTERN char_u *p_titlestring;   ///< 'titlestring'
 EXTERN char_u *p_tsr;           ///< 'thesaurus'
 EXTERN int p_tgc;               ///< 'termguicolors'
+EXTERN char_u *p_twt;           ///< 'termwintype'
```
Comment (justinmk) [inline src/nvim/option_defs.h]: why do we need an option? We can just enable it always, depending on the detected Windows version.

nit: Nvim doesn't have a "terminal window" so it would be unfortunate if we had to copy this Vim option.

File: src/nvim/os/os_win_conpty.c [hunk 2]
```diff
@@ -0,0 +1,181 @@
+#include <uv.h>
```
Comment (justinmk) [inline src/nvim/os/os_win_conpty.c]: not sure if PVS studio works at source level but maybe add [the header](https://github.com/neovim/neovim/blob/21fdfc87284d4f58bc17883429b0a152013c618a/src/nvim/os/tty.c#L1) anyways.

File: src/nvim/os/pty_process_win.c [hunk 3]
```diff
@@ -192,8 +229,18 @@ void pty_process_resize(PtyProcess *ptyproc, uint16_t width,
...
+    assert(width <= SHRT_MAX);
+    assert(height <= SHRT_MAX);
+    COORD size = { (int16_t)width, (int16_t)height };
+    if (pResizePseudoConsole(
+        ptyproc->pty_object.conpty_object->pty, size) != S_OK) {
+      ELOG("ResizePseudoConsoel failed: error code: %d",
+           os_translate_sys_error((int)GetLastError()));
+    }
+  } else if (ptyproc->pty_object.winpty_object != NULL) {
+    winpty_set_size(ptyproc->pty_object.winpty_object, width, height, NULL);
```
Comment (justinmk) [inline src/nvim/os/pty_process_win.c]: can we hide the win32 API code in something similar to `winpty_set_size` (preferably in `os_win_conpty.c` or similar isolated module)? We want to minimize the "scattered" changes.

File: src/nvim/os/pty_process_win.c [hunk 4]
```diff
@@ -152,9 +183,14 @@ int pty_process_spawn(PtyProcess *ptyproc)
     uv_run(&proc->loop->uv, UV_RUN_ONCE);
   }
 
-  ptyproc->winpty_object = winpty_object;
+  if (ptyproc->type == PTY_TYPE_CONPTY) {
+    ptyproc->pty_object.conpty_object = conpty_object;
+  } else {
+    ptyproc->pty_object.winpty_object = winpty_object;
+  }
```
Comment (justinmk) [inline src/nvim/os/pty_process_win.c]: ternary avoids nesting and is clearer.

File: src/nvim/os/pty_process_win.h [hunk 5]
```diff
@@ -6,12 +6,22 @@
...
 
 typedef struct pty_process {
   Process process;
   char *term_name;
   uint16_t width, height;
-  winpty_t *winpty_object;
+  union {
+    winpty_t *winpty_object;
+    conpty_t *conpty_object;
+  } pty_object;
```
Comment (justinmk) [inline src/nvim/os/pty_process_win.h]:
```suggestion
  union {
    winpty_t *winpty;
    conpty_t *conpty;
  } object;
```

**Comment by justinmk** [comment]
@erw7 this looks great! The changes seem mostly isolated so it's low-risk enough that we could merge it quickly.

File: src/nvim/option_defs.h (hunk 1 above)
Comment (erw7) [reply src/nvim/option_defs.h]: In the vim manual:

> Windows 10 October 2018	Update is the first version that supports ConPTY, however it is still considered unstable.  ConPTY might become stable in the next release of Windows 10.

Therefore, I think that it is possible to switch with an option.

Comment (justinmk) [reply src/nvim/option_defs.h]: It's not worth the extra code/complication. And the option has a name that doesn't fit with Neovim, since there is no "terminal window" in Neovim.

File: src/nvim/channel.c [hunk 6]
```diff
@@ -441,8 +444,34 @@ uint64_t channel_from_stdio(bool rpc, CallbackReader on_output,
...
+    close(STDOUT_FILENO);
+    const HANDLE conout_handle =
+      CreateFile("CONOUT$", GENERIC_READ | GENERIC_WRITE,
+                 FILE_SHARE_READ, (LPSECURITY_ATTRIBUTES)NULL,
+                 OPEN_EXISTING, 0, (HANDLE)NULL);
+    assert(conout_handle != INVALID_HANDLE_VALUE);
+    const int conout_fd = _open_osfhandle((intptr_t)conout_handle, 0);
+    assert(conout_fd == STDOUT_FILENO);
+  }
+#endif
```
Comment (justinmk) [inline src/nvim/channel.c]: I think we can extract this code somewhere else. Then only make a function call here to get the `stdin_dup_fd`/`stdout_dup_fd`.

File: src/nvim/os/os_win_conpty.c [hunk 7]
```diff
@@ -0,0 +1,196 @@
...
+#include "nvim/os/os_win_conpty.h"
+
+#ifndef EXTENDED_STARTUPINFO_PRESENT
+# define EXTENDED_STARTUPINFO_PRESENT 0x00080000
+#endif
+#ifndef PROC_THREAD_ATTRIBUTE_PSEUDOCONSOLE
+# define PROC_THREAD_ATTRIBUTE_PSEUDOCONSOLE 0x00020016
+#endif
+
+static bool conpty_working = false;
```
Comment (justinmk) [inline src/nvim/os/os_win_conpty.c]:
```suggestion
static bool has_conpty = false;
```

File: src/nvim/main.c [hunk 8]
```diff
@@ -225,6 +228,9 @@ void early_init(void)
 
   init_signs();
   ui_comp_syn_init();
+#ifdef WIN32
+  os_dyn_conpty_init();
```
Comment (justinmk) [inline src/nvim/main.c]: Instead of doing this here, `os_dyn_conpty_init` could be called on the first call to `os_has_conpty`. Similar to how `pty_process_spawn` calls `init_termios` its first time.

That avoids adding code and a new import to `main.c`.

File: src/nvim/os/os_win_conpty.c [hunk 9]
```diff
@@ -0,0 +1,196 @@
...
+
+HRESULT (WINAPI *pCreatePseudoConsole)(COORD, HANDLE, HANDLE, DWORD, HPCON *);
+HRESULT (WINAPI *pResizePseudoConsole)(HPCON, COORD);
+void (WINAPI *pClosePseudoConsole)(HPCON);
+
+bool os_has_conpty_working(void)
+{
+  return conpty_working;
```
Comment (justinmk) [inline src/nvim/os/os_win_conpty.c]:
```
if (has_conpty == kNone) {
  os_dyn_conpty_init();
}
return has_conpty;
```

File: src/nvim/os/pty_process_win.c [hunk 10]
```diff
@@ -12,6 +12,7 @@
 #include "nvim/memory.h"
 #include "nvim/mbyte.h"  // for utf8_to_utf16, utf16_to_utf8
 #include "nvim/os/pty_process_win.h"
+#include "nvim/os/os_win_conpty.h"
```
Comment (justinmk) [inline src/nvim/os/pty_process_win.c]: Let's try to follow the naming pattern of other `os/*_win.{h,c}` files. Instead of `os/os_win_conpty.h`, I suggest:

    os/pty_conpty_win.h

That helps discovery because `pty_*` files will sort next to each other.

File: src/nvim/os/pty_process_win.h [hunk 11]
```diff
@@ -6,12 +6,22 @@
 
 #include "nvim/event/process.h"
 #include "nvim/lib/queue.h"
+#include "nvim/os/os_win_conpty.h"
+
+typedef enum {
+  PTY_TYPE_WINPTY,
+  PTY_TYPE_CONPTY
+} pty_type_t;
```
Comment (justinmk) [inline src/nvim/os/pty_process_win.h]: normally we use this naming convention:

```
typedef enum {
  kWinpty,
  kConPty,
} PtyType;
```

File: src/nvim/option_defs.h (hunk 1 above)
Comment (erw7) [reply src/nvim/option_defs.h]: > It's not worth the extra code/complication.

Even the [Windows Terminal](https://github.com/microsoft/terminal) created by Microsoft has a preview status. If there is a problem with `ConPTY`, neovim may not be able to fix it. Besides, you can use a mouse with `winpty`, but you cannot use a mouse with `ConPTY` yet. From these, I think it is better to allow the user to select the backend.

Comment (justinmk) [reply src/nvim/option_defs.h]: I'm really not in favor of this. If it turns out to be a serious problem, we can revisit it later. 

The "preview" status of conpty is temporary. If it has any problems, they will go away as time goes on. Whereas the extra code and documentation we would add for the extra option, won't go away.

**Comment by bfredl** [comment]
@justinmk There seems to be no outstanding issues here right? I think we should just merge this, and 0.5 cycle is still long enough to figure out any obvious trouble that it could case.

File: src/nvim/option_defs.h (hunk 1 above)
Comment (janlazo) [reply src/nvim/option_defs.h]: Terminal tests depend on winpty implementation. They fail in the CI if using conpty.

https://github.com/neovim/neovim/pull/13177
