### PR TITLE
vim-patch:8.1.1120

### LINKED ISSUE #12212: Unknown function: readdir()
- `nvim --version`: v0.5.0-477-gf9055c585 (also tested on 0.4.3 release)
- `vim -u DEFAULTS` behaves the same.
- Operating system/version: Arch Linux
- Terminal name/version: Konsole
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```vim
nvim -u NORC
:echo readdir('/') " Can be any directory
```

### Actual behaviour
Unknown function: readdir('/')

### Expected behaviour
List of files in specified directory.

### Vim
I tested it in Vim and it works as expected. Neovim and Vim documentation says that this function is present.

### PR DESCRIPTION
**Pull request by Shatur**
Hi all! I trying to port https://github.com/vim/vim/commit/543c9b1921d7605498b54afdef518e312f1b4515 (closes #12212). This patch just adds `readdir()` Vimscript function. I noticed that the documentation was partially updated in Neovim (mistake after merge?), but the function itself does not exists.
I updated documentation and `eval.c`. But currently I have an issue with porting ` src/evalfunc.c` to `src/nvim/eval/funcs.c`. Neovim does not have `vim_free`, `list_append_string`, `list_alloc`, `ga_init2`, `rettv_list_alloc` and `clear_tv` (used in original patch). What should I use instead? I'm not familiar with Neovim codebase, but want to help.

### CODE REVIEW

**Comment by janlazo** [comment]
Refer to https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim for porting Vim patches to Neovim. Check https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim#code-differences to know which Vim functions to replace with Neovim equivalents. For functions like list_append_string, list_alloc, rettv_list_alloc and clear_tv, use the functions prefixed with `tv_`. For others, you have to check how other C functions in `src/nvim/eval/funcs.c` work. Neovim aborts on error so you can omit some of the error checking that Vim does.

You have to redo all commits here to something that https://github.com/neovim/neovim/blob/master/scripts/vim-patch.sh generates so that the patch can be attributed to Vim.

**Comment by erw7** [comment]
Regarding the porting of 8.1.1120, I think it is better to use `os_scandir`, `os_scandir_next` and `os_closedir` instead of `opendir`, `readdir` and `closedir`. I think that would eliminate the need for an implementation in `#ifdef MSWIN`.

**Comment by Shatur95** [comment]
@janlazo, thank you for the information! I missed the wiki page about porting Vim patches. I force pushed changes branch created by `vim-patch.sh`.

@erw7, thanks for the suggestion. The code looks much cleaner now.

I tested the added function locally and it works as Vim.

File: src/nvim/eval/funcs.c [hunk 1]
```diff
@@ -6314,6 +6314,97 @@ static void f_range(typval_T *argvars, typval_T *rettv, FunPtr fptr)
...
+    for (;;) {
+      int ignore;
+
+      path = os_scandir_next(&dir);
+      if (path == NULL)
+        break;
+
+      ignore = path[0] == '.' &&
+        (path[1] == NUL ||
+         (path[1] == '.' && path[2] == NUL));
```
Comment (Shatur95) [inline src/nvim/eval/funcs.c:6374]: How should I write this lines? Now it looks as in Vim, but as for this is not very readable.

File: src/nvim/eval/funcs.c [hunk 2]
```diff
@@ -6314,6 +6314,97 @@ static void f_range(typval_T *argvars, typval_T *rettv, FunPtr fptr)
...
+  garray_T ga;
+  Directory dir;
+
+  tv_list_alloc_ret(rettv, kListLenUnknown);
+  path = tv_get_string(&argvars[0]);
+  expr = &argvars[1];
+  ga_init(&ga, (int)sizeof(char *), 20);
+
+  if(!os_scandir(&dir, path)) {
+    smsg(_(e_notopen), path);
```
Comment (Shatur95) [inline src/nvim/eval/funcs.c:6363]: `e_notopen` corresponds to "E484: Can't open file %s" as in Vim. But as for me this is not related to directories. Should I leave it as is?

File: src/nvim/eval/funcs.c [hunk 3]
```diff
@@ -6314,6 +6314,99 @@ static void f_range(typval_T *argvars, typval_T *rettv, FunPtr fptr)
...
+          break;
+        }
+        if (r == 0) {
+          ignore = true;
+        }
+      }
+
+      if (!ignore) {
+        ga_grow(&ga, 1);
+        ((char_u **)ga.ga_data)[ga.ga_len++] = vim_strsave((char_u *)path);
```
Comment (erw7) [inline src/nvim/eval/funcs.c:6387]: `vim_strsave()` is defined as follows. Therefore, if you use `xsrdup()` instead of `vim_strsave()`, you don't need to cast the `path`.

```C
char_u *vim_strsave(const char_u *string)
  FUNC_ATTR_NONNULL_RET FUNC_ATTR_MALLOC FUNC_ATTR_NONNULL_ALL
{
  return (char_u *)xstrdup((char *)string);
}
```

Ref. #459.

**Review by erw7 — APPROVED** [review]

File: src/nvim/eval/funcs.c (hunk 3 above)
Comment (Shatur95) [reply src/nvim/eval/funcs.c:6387]: Okay! Should I also replace `char_u` with `uint8_t`?

Comment (erw7) [reply src/nvim/eval/funcs.c:6387]: > where only characters are used it's ok to use plain char

Therefore, I think `char` is fine.

Comment (Shatur95) [reply src/nvim/eval/funcs.c:6387]: Thank you, I will do.

Comment (erw7) [reply src/nvim/eval/funcs.c:6387]: I don't think you have to go that far.

Comment (Shatur95) [reply src/nvim/eval/funcs.c:6387]: Okay, I will only replace `vim_strsave`.

Comment (Shatur95) [reply src/nvim/eval/funcs.c]: Okay :)

Comment (Shatur95) [reply src/nvim/eval/funcs.c]: Done! `uint8_t` It was only in one place, except for `argv[0].val.v_string` and `sort_strings()`.

**Comment by Shatur95** [comment]
The Travis CI build was failed, but it looks like it is the CI problem.
