### PR TITLE
fix(tui): handle padding requirements for visual bell

### LINKED ISSUE #20234: Visualbell not working
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.26.2 

### $TERM environment variable

xterm-kitty

### Installation

Arch official repository (community)

### How to reproduce the issue

`nvim --clean`
`:set belloff=""`
`:set visualbell`
Press `<Esc>` a couple of times from normal mode.

### Expected behavior

The screen will flash.

### Actual behavior

No UI change. Also tried `:set errorbells`, no change.

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #20234

### CODE REVIEW

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -1658,6 +1659,37 @@ static void out(void *ctx, const char *str, size_t len)
   data->bufpos += len;
 }
 
+/// Called by unibi_format() for padding.
```
Comment (justinmk) [inline src/nvim/tui/tui.c:1662]: hard to find the docs for `unibi_format` and its `pad` param. Here are the full docs from https://github.com/neovim/unibilium/blob/6688d83c91501d81fec9a1a0fbf67993d2d338f0/doc/unibi_format.pod#L32


```
I<pad> is used when the format string contains C<< $<...> >> padding
instructions. In the calls to I<pad> the first argument is always I<ctx2>, the
second argument is the delay in tenths of milliseconds, the third argument is a
boolean flag indicating whether C<*> (proportional delay) was specified in the
format string, and the fourth argument is a boolean flag indicating whether
C</> (forced padding) was specified in the format string. Thus a format string
of C<< $<5/> >> would translate into C<pad(ctx2, 50, 0, 1)>. You may pass a
null pointer for I<pad>; in that case padding instructions are silently
skipped.
```

can we summarize the relevant part here (very concisely)? Something like:

> The `pad` parameter of `unibi_format` handles padding instructions. If it is NULL then padding instructions are silently skipped.

File: src/nvim/tui/tui.c [hunk 2]
```diff
@@ -1658,6 +1659,37 @@ static void out(void *ctx, const char *str, size_t len)
...
+static void pad(void *ctx, size_t delay, int scale, int force)
```
Comment (justinmk) [inline src/nvim/tui/tui.c:1663]: // TODO: the delay impl is mostly copied from loop_poll_events(). Can we extract this pattern to a common function?

File: src/nvim/tui/tui.c (hunk 1 above)
Comment (zeertzjq) [reply src/nvim/tui/tui.c:1662]: I guess it is better to add doxygen comments for the parameters instead.
