### PR TITLE
fix: check for valid buffer handles in modify_keymap

### LINKED ISSUE #13541: Specify non-existent buffer in nvim_buf_set_keymap
- `nvim --version`:
NVIM v0.5.0-dev+939-g4f9e7a512
Build type: Release
LuaJIT 2.1.0-beta3
- Operating system/version: Win10
- Terminal name/version: nvim-qt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
As an ex-command execute:
:lua vim.api.nvim_buf_set_keymap(100, 'n', '<CR>', '', {noremap = true})
```

### Actual behaviour

Neovim closes unexpectedly.

### Expected behaviour

Display an error message that the buffer is not existent.

### PR DESCRIPTION
**Pull request by vigoux**
Fixes #13541

### CODE REVIEW

File: src/nvim/api/private/helpers.c [hunk 1]
```diff
@@ -820,6 +820,12 @@ void modify_keymap(Buffer buffer, bool is_unmap, String mode, String lhs,
   }
   buf_T *target_buf = find_buffer_by_handle(buffer, err);
 
+  if (!target_buf) {
+    api_set_error(err, kErrorTypeValidation,
```
Comment (bfredl) [inline src/nvim/api/private/helpers.c:824]: not needed, `find_buffer_by_handle` already does this.

Comment (vigoux) [reply src/nvim/api/private/helpers.c]: Done
