### PR TITLE
fix(tui): wait for embedded server's exit code

### LINKED ISSUE #21608: TUI: cannot see server stderr when Nvim server process crashes
### Neovim version (nvim -v)

NVIM v0.9.0-dev-590+g6ba34e21f

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Run `nvim --clean`
2. Try to trigger an assert failure (for example the one in #7889)

### Expected behavior

The assert failure can be seen

### Actual behavior

The assert failure cannot be seen

### LINKED ISSUE #34365: TUI: server --listen error is only briefly visible
### Problem

TUI: server --listen error is only briefly visible

### Steps to reproduce

1. Run `nvim --clean`
2. Run `:echo serverlist()` in Nvim
3. Run another `nvim --clean --listen` followed by the previous Nvim's server address
4. The `Failed to --listen: address already in use` error is only briefly visible

### Expected behavior

The `Failed to --listen: address already in use` error is visible until the user clears the screen.

### Nvim version (nvim -v)

v0.12.0-dev-525+g52c61d9690

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.42.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #21608
Fix #34365

Uses the undocumented "error_exit" UI event for a different purpose:
When :detach is used on the server, send an "error_exit" with 0 `status`
to indicate that the server shouldn't wait for client exit.

### CODE REVIEW

File: src/nvim/event/proc.c [hunk 1]
```diff
@@ -437,16 +438,25 @@ static void on_proc_exit(Proc *proc)
...
+        && proc == &server_chan->stream.proc) {
+      // Need to call ui_client_may_restart_server() here as well, as sometimes
+      // rpc_close_event() hasn't been called yet (also see comments above).
+      ui_client_may_restart_server();
+      if (ui_client_channel_id == server_chan_id) {
+        // If the current embedded server has exited and no new server is started,
+        // the client should exit with the same status.
+        exit_on_closed_chan(proc->status);
+      }
+    }
```
Comment (zeertzjq) [inline src/nvim/event/proc.c:458]: This change makes `:restart` work on Windows.

File: src/nvim/event/proc.c [hunk 2]
```diff
@@ -437,16 +438,25 @@ static void on_proc_exit(Proc *proc)
   Loop *loop = proc->loop;
   ILOG("child exited: pid=%d status=%d" PRIu64, proc->pid, proc->status);
 
-#ifdef MSWIN
-  // XXX: This assumes the TUI never spawns any other processes...?
```
Comment (justinmk) [inline src/nvim/event/proc.c:441]: this is still true and seems worth calling out. could remove the "?" at the end.

File: src/nvim/ex_docmd.c [hunk 3]
```diff
@@ -5578,7 +5578,7 @@ static void ex_detach(exarg_T *eap)
 
     // Server-side UI detach. Doesn't close the channel.
     Error err2 = ERROR_INIT;
-    nvim_ui_detach(chan->id, &err2);
+    remote_ui_disconnect(chan->id, &err2, true);
```
Comment (justinmk) [inline src/nvim/ex_docmd.c:5581]: on line 5563 the "TODO" can be changed to:

    // 1. Send "error_exit" UI-event (notification only).

File: src/nvim/event/proc.c (hunk 2 above)
Comment (zeertzjq) [reply src/nvim/event/proc.c:441]: No, the conditions I added below check if the process that exited is the Nvim server.

**Review by justinmk — APPROVED** [review]
Thank you @zeertzjq !
