### PR TITLE
test/unit: ensure event_init()

### LINKED ISSUE #4635: os_breackcheck() crashes
See https://github.com/neovim/neovim/pull/4070#discussion_r50626558

I've started investigating from a symptoms point of view. If you look at https://github.com/neovim/neovim/blob/master/test/unit/buffer_spec.lua#L96, there are 3 calls to `eq`. The third produces the crash (well, I've confirmed it actually the call to `buflist_findpath`, of course), but _only_ if the other 2 happen before. If you comment out 1 or 2 of them, everything passes (I tried all possible combinations).

Slightly below, there's https://github.com/neovim/neovim/blob/master/test/unit/buffer_spec.lua#L110. The crash happens at line 117, but _only_ if line 114 is there. If you comment out line 114 (and ofc 127 and 131 so you don't get a lua error), the test passes.

The crash does not happen at https://github.com/neovim/neovim/blob/master/test/unit/buffer_spec.lua#L134.

I've run the tests selectively using TEST_FILTER. I'll try to produce a minimal example later on.

### PR DESCRIPTION
**Pull request by justinmk**
Ye olde unit test quirk.

Closes #4635
References #4630
References #4070 (comment)

### CODE REVIEW

File: test/unit/helpers.lua [hunk 1]
```diff
@@ -140,6 +140,7 @@ do
   local time = cimport('./src/nvim/os/time.h')
   time.time_init()
   main.early_init()
+  main.event_init()
```
Comment (justinmk) [inline test/unit/helpers.lua]: This is the only functional change in this PR.

File: test/unit/os/shell_spec.lua [hunk 2]
```diff
@@ -27,16 +27,16 @@ describe('shell functions', function()
...
     shell.event_init()
     -- os_system() can't work when the p_sh and p_shcf variables are unset
-    shell.p_sh = to_cstr('/bin/bash')
-    shell.p_shcf = to_cstr('-c')
+    cimported.p_sh = to_cstr('/bin/bash')
+    cimported.p_shcf = to_cstr('-c')
   end)
 
   teardown(function()
     shell.event_teardown()
```
Comment (justinmk) [inline test/unit/os/shell_spec.lua]: I left this and the `event_init()` call in `setup()` above just in case they were around for some SAN-related reason.

File: test/unit/os/shell_spec.lua [hunk 3]
```diff
@@ -25,18 +25,18 @@ local NULL = ffi.cast('void *', 0)
...
     -- os_system() can't work when the p_sh and p_shcf variables are unset
-    shell.p_sh = to_cstr('/bin/bash')
-    shell.p_shcf = to_cstr('-c')
+    cimported.p_sh = to_cstr('/bin/bash')
+    cimported.p_shcf = to_cstr('-c')
   end)
 
   teardown(function()
-    shell.event_teardown()
+    cimported.event_teardown()
```
Comment (justinmk) [inline test/unit/os/shell_spec.lua]: I left this and the `event_init()` call in `setup()` above just in case they were around for some SAN-related reason.
