### PR TITLE
vim-patch:8.2.0235: draw error when an empty group is removed from 'statusline'

### LINKED ISSUE #11240: ui_comp_raw_line: Assertion `attrs[i] >= 0' failed (via statusline)
Given t-crash.vim:
```vim
scriptencoding utf-8
let &statusline = '%#StatColorHi2#%(✓%#StatColorHi2#%) Q≡'
```

Running `nvim -u t-crash.vim -q <(echo '')` crashes:
```
(gdb) thread apply all bt

Thread 2 (Thread 0x7f3f93e11700 (LWP 4073652)):
#0  0x00007f3f94531436 in epoll_pwait () from /usr/lib/libc.so.6
#1  0x000055cd9f9f44e1 in uv__io_poll (loop=loop@entry=0x7f3f93e10890, timeout=20) at …/Vcs/neovim/.deps/build/src/libuv/src/unix/linux-core.c:284
#2  0x000055cd9f9e4d84 in uv_run (loop=0x7f3f93e10890, mode=UV_RUN_ONCE) at …/Vcs/neovim/.deps/build/src/libuv/src/unix/core.c:375
#3  0x000055cd9f79936f in loop_poll_events (loop=0x7f3f93e10890, ms=20) at ../src/nvim/event/loop.c:62
#4  0x000055cd9f960bfc in tui_main (bridge=0x55cda0031e90, ui=0x55cda0031d70) at ../src/nvim/tui/tui.c:432
#5  0x000055cd9f96d272 in ui_thread_run (data=0x55cda0031e90) at ../src/nvim/ui_bridge.c:104
#6  0x00007f3f949864cf in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007f3f945312d3 in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7f3f9424e780 (LWP 4073651)):
#0  0x00007f3f9446df25 in raise () from /usr/lib/libc.so.6
#1  0x00007f3f94457897 in abort () from /usr/lib/libc.so.6
#2  0x00007f3f94457767 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007f3f94466526 in __assert_fail () from /usr/lib/libc.so.6
#4  0x000055cd9f96fa38 in ui_comp_raw_line (ui=0x55cda0008ff0, grid=1, row=34, startcol=0, endcol=174, clearcol=174, clearattr=0, flags=0, chunk=0x7f3f949ece3c, attrs=0x55cda0038f48) at ../src/nvim/ui_compositor.c:549
#5  0x000055cd9f9680cb in ui_call_raw_line (grid=1, row=34, startcol=0, endcol=174, clearcol=174, clearattr=0, flags=0, chunk=0x7f3f949ece3c, attrs=0x55cda0038f48) at src/nvim/auto/ui_events_call.generated.h:230
#6  0x000055cd9f96adf2 in ui_line (grid=0x55cd9fbc1960 <default_grid>, row=34, startcol=0, endcol=174, clearcol=174, clearattr=0, wrap=false) at ../src/nvim/ui.c:366
#7  0x000055cd9f8eccc8 in grid_puts_line_flush (set_cursor=false) at ../src/nvim/screen.c:5546
#8  0x000055cd9f8ebd6c in win_redr_custom (wp=0x55cda000c1e0, draw_ruler=0) at ../src/nvim/screen.c:5225
#9  0x000055cd9f8eb3e9 in redraw_custom_statusline (wp=0x55cda000c1e0) at ../src/nvim/screen.c:4997
#10 0x000055cd9f8eaf08 in win_redr_status (wp=0x55cda000c1e0) at ../src/nvim/screen.c:4896
#11 0x000055cd9f8de895 in update_screen (type=40) at ../src/nvim/screen.c:502
#12 0x000055cd9f8677c9 in normal_redraw (s=0x7ffd8c9f1e40) at ../src/nvim/normal.c:1247
#13 0x000055cd9f8679bc in normal_check (state=0x7ffd8c9f1e40) at ../src/nvim/normal.c:1324
#14 0x000055cd9f93b62d in state_enter (s=0x7ffd8c9f1e40) at ../src/nvim/state.c:28
#15 0x000055cd9f8656f0 in normal_enter (cmdwin=false, noexmode=false) at ../src/nvim/normal.c:463
#16 0x000055cd9f828ca6 in main (argc=5, argv=0x7ffd8c9f21c8) at ../src/nvim/main.c:576
```
/cc @bfredl

### PR DESCRIPTION
**Pull request by bfredl**
Problem:    Draw error when an empty group is removed from 'statusline'.
Solution:   Do not use highlighting from a removed group.
https://github.com/vim/vim/commit/dbe5d361feb65137099644329cf0ecfd4a945a14

fixes #11240. Should probably still do #11756 for robustness.

### CODE REVIEW

File: test/functional/ui/multibyte_spec.lua [hunk 1]
```diff
@@ -174,4 +174,9 @@ describe('multibyte rendering: statusline', function()
                                             |
     ]])
   end)
+
+  it('hidden group %( %) does not cause invalid unicode', function()
+    command("let &statusline = '%#StatColorHi2#%(✓%#StatColorHi2#%) Q≡'")
+    screen:snapshot_util()
```
Comment (justinmk) [inline test/functional/ui/multibyte_spec.lua]: is this intentional? Perhaps `assert_alive()` is enough.

**Comment by justinmk** [comment]
Regarding the travis `lsp_spec` failure: https://github.com/neovim/neovim/pull/11837 should help

File: test/functional/ui/multibyte_spec.lua (hunk 1 above)
Comment (bfredl) [reply test/functional/ui/multibyte_spec.lua]: just forgot to push the last push

**Comment by bfredl** [comment]
now treesitter-c is failing on MSVC_32, seems indeterministic (weird cache behavior?)
