### PR TITLE
fix(tui): initialize clear attrs with current terminal background

### LINKED ISSUE #28667: 0.10 colorscheme flickering
### Problem

There are a few conditions when colorscheme flickers when launching neovim. By flickering I mean that it between changin background from terminal background to neovim background, there is a period of time when the background is black.

I think it is somewhat related to #19362 . These only reproduce on nightly, 0.9.5 is fine.

### Steps to reproduce

For any of this, run `nvim --clean -u minimal.lua` with the contents of `minimal.lua` described below.

#### termguicolors

After setting `termguicolor`, background switches to black before switching to the user-defined one. Run with `sleep` to pause on black background, or with some synchronous code to see flickering.

I know that `termguicolors` is enabled automatically in 0.10, however this causes 0.9 configs to flicker and people waste time debugging. Also, I don't know how this works under the hood, but automatic setting of `termguicolors` seems to happen after `init.lua` is loaded, because `vim.o.termguicolors` returns `false` if printed inside user config (when not set manually).

```lua
vim.opt.termguicolors = true
-- vim.cmd.sleep(1)
vim.fn.system("notify-send loading")

vim.cmd.colorscheme("blue")
```

#### VimEnter

If you have a VimEnter autocommand with any synchronous action, the same thing happens. There are 3 cases. 

If you run (1) - you will see the same effect as with `termguicolors` - background switches to black. 
If you run (2) - you may see very subtle flickering of the screen. I choose `fn.system` as a generic synchronous side-effect. The same happens with `system():wait`.
If you run (3) - no flickering. The same is described in https://github.com/neovim/neovim/issues/19362#issuecomment-1924993842

```lua
vim.api.nvim_create_autocmd("VimEnter", {
	callback = function()
		--[[ (1) ]] vim.cmd.sleep(1)
		--[[ (2) ]] vim.fn.system("notify-send vimenter")
		--[[ (3) ]] vim.print("asdf")
	end,
})
vim.cmd.colorscheme("blue")
```

#### unnamedplus

Same flickering, however you cannot pause on it by running `sleep`, maybe it happens at different point in time. But, if you run synchronous commands, then you can see the flickering.

```lua
vim.opt.clipboard = "unnamedplus"
vim.fn.system("notify-send loading")
vim.cmd.colorscheme("blue")
```

### Expected behavior

No flickering like on 0.9.5. 

### Neovim version (nvim -v)

0.10.0-dev-3097+g064f3e42e

### Operating system/version

Linux/X11

### Terminal name/version

Tested on: kitty + tmux; kitty; wezterm; alacritty

### $TERM environment variable

Respectively^: tmux-256color; xterm-kitty; xterm-256color; alacritty

### Installation

Build from repo

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Invalidated regions that are flushed during startup are
          cleared with unitialized "clear_attrs", which is perceived as
          flickering.
Solution: Initialize "clear_attrs" with current terminal background color.

Fix #28667

### CODE REVIEW

**Comment by luukvbaal** [comment]
Was unsuccessful in adding a test for this so far, can try again tomorrow if this fix seems right to you @bfredl.

**Comment by gpanders** [comment]
I am not sure this fixes #28667. Using the init script mentioned in that file:

```vim
colorscheme blue
au VimEnter * sleep 1
```

with `VIMRUNTIME=runtime build/bin/nvim --clean -u init.vim`, I still see the black screen.

**Comment by luukvbaal** [comment]
Oh? I don't see the black screen. Are you actually seeing a black screen or is your terminal background black and is that what you're seeing? That's what I see and what I would expect after this change.

**Comment by luukvbaal** [comment]
> Hmm seems terminal dependent, I do still get a black screen in wezterm, not in st or kitty. Not sure about the fix then.

The following change also gets rid of the black screen in wezterm, guess I'll change it to that for now.

```diff
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 4c87612e87..7f8a92b3c0 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -1438,7 +1438,7 @@ void tui_flush(TUIData *tui)
   while (kv_size(tui->invalid_regions)) {
     // We don't want to flush invalid regions during startup to avoid clearing
     // with attributes different from the visible background after startup.
-    if (tui->is_starting) {
+    if (starting != 0) {
       kv_size(tui->invalid_regions) = 0;
       break;
     }
```

**Comment by gpanders** [comment]
>EDIT: Hmm seems terminal dependent, I do still get a black screen in wezterm, not in st or kitty. Not sure about the fix then

Weird, I still see the black screen on every terminal I've tried (Ghostty, Alacritty, WezTerm, and Kitty).

>Are you actually seeing a black screen or is your terminal background black and is that what you're seeing?

My terminal background color is #2e3440, which is not black. The "black" is, I believe, the default colorscheme background, which is #14161b.

**Comment by luukvbaal** [comment]
> Weird, I still see the black screen on every terminal I've tried (Ghostty, Alacritty, WezTerm, and Kitty).

Probably timing related instead then(for me the results are consistent depending on the terminalon a relatively old laptop)...

> My terminal background color is #2e3440, which is not black. The "black" is, I believe, the default colorscheme background, which is #14161b.

No I don't think it is the default colorscheme background in this case(the ones from #28667 and #28668). What we're seeing is actually black(#000000) because the `clear_attr` becomes `0` when the grid is completely undrawn during startup.

**Comment by luukvbaal** [comment]
Updated to avoid flushing in a way that shouldn't be inter-process timing dependent, while still avoiding any flickering without breaking any existing expected results. Still not sure how to add a test for this...

File: test/functional/terminal/tui_spec.lua [hunk 1]
```diff
@@ -2003,6 +2003,39 @@ describe('TUI', function()
     ]])
   end)
 
+  it('invalidated regions are cleared with terminal background attr', function()
+    local screen = Screen.new(50, 10)
+    screen:set_default_attr_ids({ [1] = { foreground = Screen.colors.Black } })
```
Comment (luukvbaal) [inline test/functional/terminal/tui_spec.lua:2008]: Added a test that at least fails on master, although I'm not sure if it tests for the behavior correctly. Presumably `Screen.colors.Black` **is** `normal_bg`, in which case it does. Could also mean that the test still produces an unwanted black screen here? I can no longer reproduce that locally.

**Comment by gpanders** [comment]
Confirmed this fixes both #28667 and #28668 for me.

**Review by gpanders — APPROVED** [review]
