### PR TITLE
fix(diagnostics): fixed virtual_text cursormoved autocmd error

### LINKED ISSUE #34081: `Invalid 'line': out of range` when deleting text with diagnostics at bottom
### Problem

When deleting lines of text with diagnostics at bottom, `Invalid 'line': out of range` will be thrown in `CursorMoved` autocommand, from `runtime/lua/vim/diagnostic.lua:1605`.
I've confirmed that this problem is LSP-independent, tested on multiple servers (`clangd`, `denols` and `csharpls` currently) and they all have the same behavior.

Image
Here is a screenshot that I made some errors in a CSharp file and then `gg=G` to delete all text.

### Steps to reproduce

Setup some LSP and setup diagnostics virtual text with
```lua
vim.diagnostic.config {
    virtual_text = { prefix = icons.ui.VirtualPrefix, current_line = false },
    update_in_insert = true,
    underline = true,
    severity_sort = true,
}
```
And create a buffer with the LSP enabled, create some diagnostic messages and `ggdG` to delete all text.

### Expected behavior

The text should be deleted without any error, of course.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-398+ga87aa68ed0

### Vim (not Nvim) behaves the same?

that feature doesn't exist in vim at all

### Operating system/version

Linux onion27-archlinux 6.14.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 09 May 2025 17:36:18 +0000 x86_64 GNU/Linux

### Terminal name/version

wezterm 20250511-222309-475e9f57

### $TERM environment variable

xterm-256color

### Installation

`neovim-git` from AUR, fresh build just at the moment before I creating the issue and reproduced it one more time

### PR DESCRIPTION
**Pull request by rijulkap**
Problem:
Selecting and deleting all lines in a file with multiple diagnostics leads to the following error:
```
Error in CursorMoved Autocommands for "<buffer=9>":
Lua callback: ...nvimdcgMep/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1587: Invalid 'line': out of range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...nvimdcgMep/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1587: in function 'render_virtual_text'
        ...nvimdcgMep/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1645: in function <...nvimdcgMep/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1644>
```
This seems to have been introduced along with the changes made in the following PR [#33517](https://github.com/neovim/neovim/pull/33517)

How to Reproduce:
 - Use a minimal lsp diagnostic config:   ` vim.diagnostic.config({virtual_lines  = {current_line = true}, virtual_text = {current_line = false}})`
- Create a test file named test.lua
- Ensure you have a lua lsp active 
- Write 3-4 lines of errors (I used the following): 
```
asd
asd
asd
asd
```
- Select and delete all lines in the file (for example using the vim motion VggD from the bottom of the file)

Solution:
This PR introduces a check to verify that the line number does not exceed the number of lines within the buffer. This allows the CursorMoved auto-command to run as intended.

Fixes https://github.com/neovim/neovim/issues/34081

### CODE REVIEW

**Comment by MariaSolOs** [comment]
Fixes https://github.com/neovim/neovim/issues/34081

**Comment by MariaSolOs** [comment]
Could we add a test?

File: runtime/lua/vim/diagnostic.lua [hunk 1]
```diff
@@ -1594,12 +1594,14 @@ M.handlers.underline = {
...
 local function render_virtual_text(namespace, bufnr, diagnostics, opts)
   local lnum = api.nvim_win_get_cursor(0)[1] - 1
+  local bufferlength = api.nvim_buf_line_count(bufnr)
   api.nvim_buf_clear_namespace(bufnr, namespace, 0, -1)
 
   for line, line_diagnostics in pairs(diagnostics) do
     local virt_texts = M._get_virt_text_chunks(line_diagnostics, opts)
     local skip = (opts.current_line == true and line ~= lnum)
       or (opts.current_line == false and line == lnum)
+      or (opts.current_line == false and line >= bufferlength)
```
Comment (MariaSolOs) [inline runtime/lua/vim/diagnostic.lua:1604]: I think that instead of skipping the diagnostic here we should clamp the line as `vim.diagnostic.get` does. That would make the API behavior more consistent (as suggested by https://github.com/neovim/neovim/issues/34013).

Comment (rijulkap) [reply runtime/lua/vim/diagnostic.lua:1604]: Thanks for the suggestion! That makes complete sense. I have implemented this, but moved clamping it to the uppermost call such that all diagnostic handlers obey this (I can't think of a reason why any handler would need this, but I might be wrong of course). 

Do you reckon this is appropriate?

Comment (rijulkap) [reply runtime/lua/vim/diagnostic.lua:1604]: Ideally clamping diagnostic values makes absolute sense. But from my understanding (and please correct me if I'm wrong), the current implementation makes use of a "CursorMoved" autocommand when displaying virtual_text (and virtual_lines for the matter). 
The diagnostic table is not currently recomputed within this callback but when diagnostics are updated, and hence on CursorMoved you end up with diagnostic_lines table containing lnums that can potentially exceed the buffer length on deleting lines. We could recompute diagnostic_lines (and clamp to bufferlength) within the callback, however i fear this might be a tad too expensive.
Does this sound right? Wouldn't the curently implemented check be the most efficient way to do this instead?

Sorry if i've misunderstood something. This is my first PR to this repo ^^.

Comment (MariaSolOs) [reply runtime/lua/vim/diagnostic.lua:1604]: > however i fear this might be a tad too expensive with having to loop through diagnostics an additional time per cursor movement.

I don't think that clamping would have any performance impact.

> Wouldn't the curently implemented check be the most efficient way to do this instead?

I'm not smart enough to determine which approach is the most efficient. I was making a suggestion, feel free to pursue your approach instead.

Comment (rijulkap) [reply runtime/lua/vim/diagnostic.lua]: Does this current approach seem more in line with previously existing methods?

**Comment by rijulkap** [comment]
> Could we add a test?

Had a go at adding tests for this. This behavior seems to stem from the "CursorMoved" auto command, which I cannot seem to trigger from within the diagnostic functional test framework :( Any pointers?

File: runtime/lua/vim/diagnostic.lua (hunk 1 above)
Comment (gpanders) [reply runtime/lua/vim/diagnostic.lua]: I think skipping the diagnostic as you had originally is better, that way we don't compute yet another filtered table (CursorMoved is fired a lot).

You don't need to check `opts.current_line == false` though. If `line` is greater than the number of lines in the buffer, the diagnostic should always be skipped because.

```lua
local skip = line >= bufferlength or ...
```

We should also check that `skip` is false before we ever compute the virt text chunks, as right now we compute those unconditionally and they just get thrown away.

**Comment by gpanders** [comment]
> > Could we add a test?
> 
> Had a go at adding tests for this. This behavior seems to stem from the "CursorMoved" auto command, which I cannot seem to trigger from within the diagnostic functional test framework :( Any pointers?

You can try using `vim.api.nvim_exec_autocmds()`.

File: runtime/lua/vim/diagnostic.lua (hunk 1 above)
Comment (rijulkap) [reply runtime/lua/vim/diagnostic.lua]: Done! Have cleaned up the implementation a bit as well.

**Comment by rijulkap** [comment]
@gpanders  Should be good to go if you're happy!

**Review by MariaSolOs — APPROVED** [review]

File: runtime/lua/vim/diagnostic.lua [hunk 2]
```diff
@@ -1594,21 +1594,33 @@ M.handlers.underline = {
...
+  local function should_render(line)
+    if
+      (line >= buf_len)
+      or (opts.current_line == true and line ~= lnum)
       or (opts.current_line == false and line == lnum)
+    then
+      return false
+    else
+      return true
+    end
```
Comment (gpanders) [inline runtime/lua/vim/diagnostic.lua:1609]:
```suggestion
    if
      (line >= buf_len)
      or (opts.current_line == true and line ~= lnum)
      or (opts.current_line == false and line == lnum)
    then
      return false
    end
    
    return true
```

**Review by gpanders — APPROVED** [review]
