### PR TITLE
[RFC] vim-patch:8.0.0{791,831,1072,1078,1088}

### LINKED ISSUE #1901: Patch 8.0.0754 (commit eeac677) breaks bold colours on xterm t_Co=8
Potentially involved commits:

https://github.com/vim/vim/commit/eeac67788677a9ea81bcab69f81b4fc22c2adc00 (8.0.0754)
https://github.com/vim/vim/commit/b41bf8e6b45a773456031954bca1bc4212cbffbe (8.0.0791)

I recent upgraded my FreeBSD 10.3 vim-lite package from 8.0.0742 to 8.0.0809 and was surprised to find that colours looked incorrect -- specifically, they were darker (i.e. bold bit no longer being set on terminal output).

FreeBSD's TERM=xterm uses t_Co=8 and has for decades.  The terminal truly only supports 8 colours, but in the terminal emulator (PuTTY), bold being set causes the colours to be brighter.  This behaviour is "ANSI-like" (where bold means "brighter colour" rather than a bolded font) and is extremely common.

I do not use t_Co=256 because the colours look weird to me ("washed out", purely an aesthetic dislike), and I do not use TERM=xterm-color (which uses t_Co=256 anyway) because not all *IX software works correctly with xterm-color.

Attached are screenshots of FreeBSD 10.3 vim-lite 8.0.0809 vs. FreeBSD 9.3 vim-lite 8.0.0134.  There are irrelevant termcap differences (I reviewed them), but visually you can see the difference I'm referring to (re: lack of bold).  FreeBSD binary package updates do not have have a native way to revert to a previous package, so I cannot roll back to 8.0.0742.

Crummy workaround, which may or not be accurate (can't tell if 0754 or 0791 is responsible):

```
if has("patch-8.0.0754") && &term =~ "xterm"
  set t_Co=16
endif
```
with_patch
without_patch

### PR DESCRIPTION
**Pull request by janlazo**
**vim-patch:8.0.0791: terminal colors depend on the system**

Problem:    Terminal colors depend on the system.
Solution:   Use the highlight color lookup tables.
https://github.com/vim/vim/commit/b41bf8e6b45a773456031954bca1bc4212cbffbe

**vim-patch:8.0.0831: with 8 colors the bold attribute is not set properly**

Problem:    With 8 colors the bold attribute is not set properly.
Solution:   Move setting HL_TABLE() out of lookup_color. (closes vim/vim#1901)
vim/vim@12d853f

**vim-patch:8.0.1072: :highlight command causes a redraw even when nothing changed**

Problem:    The :highlight command causes a redraw even when nothing changed.
Solution:   Only set "need_highlight_changed" when an attribute changed.
vim/vim@9943329

**vim-patch:8.0.1078: using freed memory with ":hi Normal"**

Problem:    Using freed memory with ":hi Normal".
Solution:   Get "item" again after updating the table.
vim/vim@b4ea191

**vim-patch:8.0.1088: occasional memory use after free**

Problem:    Occasional memory use after free.
Solution:   Use the highlight table directly, don't keep a pointer.
vim/vim@414168d

~~Prep for 8.0.0890.~~ There are `terminal.c` changes to fix code from 8.0.0{754,755,760} via `lookup_color` (new function added) but idk where to put it.

I'll handle 8.0.0890 in a separate PR.

### CODE REVIEW

**Comment by janlazo** [comment]
I'm assuming that 8.0.0{754,755,760}  are N/A (no feedback on what to do with them) so I'll proceed with other patches.

**Comment by janlazo** [comment]
I will be refactoring functions and struct members to match the type changes (`short` to `int16_t`) in 8.0.1541. I will leave 8.0.0914, 8.0.1038, and 8.0.1146 for another PR.

**Comment by janlazo** [comment]
I removed 8.0.1541 to investigate #8782.

**Comment by justinmk** [comment]
It will be nice to have something similar to Vim's `terminal.c:color2index()` for Nvim's `:terminal`, but I agree it's out of scope for now.

File: src/nvim/syntax.c [hunk 1]
```diff
@@ -6944,6 +6945,9 @@ void do_highlight(const char *line, const bool forceit, const bool init)
         // redraw below will still handle usages of guibg=fg etc.
         ui_default_colors_set();
       }
+      item = &HL_TABLE()[idx];
```
Comment (justinmk) [inline src/nvim/syntax.c]: the vim patch has a comment which is a useful hint:

    item = &HL_TABLE()[idx];  // table may have changed

File: src/nvim/syntax.h [hunk 2]
```diff
@@ -3,6 +3,7 @@
 
 #include <stdbool.h>
 
+#include "nvim/globals.h"
```
Comment (justinmk) [inline src/nvim/syntax.h]: seems like this isn't needed so I removed it in the merge-commit.

Comment (janlazo) [reply src/nvim/syntax.h]: It didn't work last time when I used TriState for `boldp` in patch 8.0.0831 (
0c0318f)

File: src/nvim/syntax.c [hunk 3]
```diff
@@ -6385,6 +6385,90 @@ int load_colors(char_u *name)
...
+  1, 5, 3, 3,
+  7, 7, 7, 7,
+  0+8, 0+8,
+  4+8, 4+8, 2+8, 2+8,
+  6+8, 6+8, 1+8, 1+8, 5+8,
+  5+8, 3+8, 3+8, 7+8, -1 };
+
+// Lookup the "cterm" value to be used for color with index "idx" in
+// color_names[].
+// "boldp" will be set to TRUE or FALSE for a foreground color when using 8
```
Comment (janlazo) [inline src/nvim/syntax.c]: It should be `kTrue or kFalse` but TRUE/kTrue and FALSE/kFalse evaluate to the same integer value.
