### PR TITLE
fix(env): force uppercase environ() keys on Windows

### LINKED ISSUE #39443: `vim.fn.environ()` letter casing of keys on Windows
### Problem

Hi, since https://github.com/neovim/neovim/pull/39176 the behavior of `vim.fn.environ()` changed on Windows, with keys no longer being uppercased. This was originally implemented in https://github.com/neovim/neovim/pull/14579 (issue https://github.com/neovim/neovim/issues/14541). I'm not sure if this is still an issue within Neovim on Windows but it did cause some breakage in user code. I'm accessing the `PATH` variable via `vim.fn.environ()`, something that up until #39176 worked fine on all platforms.

Figured I'd raise an issue in case this might cause regressions internally but also inform that it might break user code and probably deserves being highlighted in the next release changelog.

### Steps to reproduce

On a Windows machine:

```vim
" On latest stable (0.12.2) this returns environment variables with all keys UPPERCASED
" On nightly/master this returns environment variables as-is
:=vim.fn.environ()
```

### Expected behavior

For `vim.fn.environ()` to return keys uppercased, consistent with previous behavior.

### Nvim version (nvim -v)

NVIM v0.13.0-dev-347+g689c824ef7

### Vim (not Nvim) behaves the same?

no, 9.2.0323. Vim does return some environments "as-is", but `PATH` gets uppercased.

### Operating system/version

Windows 11

### Terminal name/version

Windows Terminal

### $TERM environment variable

N/A

### Installation

Official release assets

### PR DESCRIPTION
**Pull request by justinmk**
fix https://github.com/neovim/neovim/issues/39443

### CODE REVIEW

File: src/nvim/eval/funcs.c [hunk 1]
```diff
@@ -3434,15 +3443,18 @@ dict_T *create_environment(const dictitem_T *job_env, const bool clear_env, cons
...
     TV_DICT_ITER(job_env->di_tv.vval.v_dict, var, {
-      // Always use upper-case keys for Windows so we detect duplicate keys
-      char *const key = strcase_save(var->di_key, true);
-      size_t len = strlen(key);
-      dictitem_T *dv = tv_dict_find(env, key, len);
+      // Force uppercase keys on Windows (dedup).
+      const char *name = var->di_key;
+      size_t namelen = strlen(name);
+      if (namelen < MAXPATHL / MB_MAXBYTES) {
+        namelen = mb_strup_buf(name, NameBuff);
```
Comment (justinmk) [inline src/nvim/eval/funcs.c:3450]: avoid allocation by `strcase_save`
