### PR TITLE
[RFC] vim-patch:8.1.{0309,0362,0365,0515,1946}

### LINKED ISSUE #2499: Assertion `!(handle->flags & (UV_CLOSING | UV_CLOSED))' failed.
Hey, I don't have steps to reproduce or anything, but nvim suddenly froze up as I was working and I had to kill it from another terminal. Only happened once, not a recurring bug as far as I know. When it exited, it produced this message:

```
vim: /build/buildd/neovim-0.0.0+git201504231825+1546+8+9~ubuntu14.10.1/.deps/build/src/libuv/src/unix/core.c:95: uv_close: Assertion `!(handle->flags & (UV_CLOSING | UV_CLOSED))' failed.
```

I figured someone might want to know about it. Please close this issue if it's not helpful.

### PR DESCRIPTION
**Pull request by erw7**
**vim-patch:8.1.0362: cannot get the script line number when executing a function**
Problem:    Cannot get the script line number when executing a function.
Solution:   Store the line number besides the script ID. (Ozaki Kiichi, closes vim/vim#3362)  Also display the line number with ":verbose set".
https://github.com/vim/vim/commit/f29c1c6aa3f365c025890fab5fb9efbe88eb1761

**vim-patch:8.1.0309: profiling does not show a count for condition lines**
Problem:    Profiling does not show a count for condition lines.  (Daniel Hahler)
Solution:   Count lines when not skipping. (Ozaki Kiichi, closes #2499)
vim/vim@7feb35e

**vim-patch:8.1.0365: function profile doesn't specify where it was defined**
Problem:    Function profile doesn't specify where it was defined.
Solution:   Show the script name and line number.
vim/vim@4c7b08f

**vim-patch:8.1.0515: reloading a script gives errors for existing functions**
Problem:    Reloading a script gives errors for existing functions.
Solution:   Allow redefining a function once when reloading a script.
vim/vim@ded5f1b

**vim-patch:8.1.1946: memory error when profiling a function without a script ID**
Problem:    Memory error when profiling a function without a script ID.
Solution:   Check for missing script ID.  (closes vim/vim#4877)
vim/vim@1635880

### CODE REVIEW

**Comment by justinmk** [comment]
@erw7 thanks, this is appreciated! @abdelhakeem will this conflict with your PR?

**Comment by abdelhakeem** [comment]
> will this conflict with your PR?

Yeah, no problem, I'll rebase and resolve it before pushing some other local changes

**Comment by erw7** [comment]
Since https://github.com/neovim/neovim/pull/10869/commits/c005c4b727bc995db95edb030b0cf3cb1a9a0caf is required by vim, vim/vim#4877 was created.

File: src/nvim/eval.c [hunk 1]
```diff
@@ -22041,16 +22041,18 @@ void func_dump_profile(FILE *fd)
...
-        const LastSet last_set = (LastSet){
-          .script_ctx = fp->uf_script_ctx,
-          .channel_id = 0,
-        };
-        char_u *p = get_scriptname(last_set, &should_free);
-        fprintf(fd, "    Defined: %s line %" PRIdLINENR "\n",
-                p, fp->uf_script_ctx.sc_lnum);
-        if (should_free) {
-          xfree(p);
+        if (fp->uf_script_ctx.sc_sid != 0) {
```
Comment (janlazo) [inline src/nvim/eval.c]: [vim-patch:8.1.1946](https://github.com/vim/vim/commit/163588005da3a240e49416093d0d0251951d60a1)

Comment (erw7) [reply src/nvim/eval.c]: Changes to `test_profile.vim` in [vim-patch:8.1.1946](https://github.com/vim/vim/commit/163588005da3a240e49416093d0d0251951d60a1) cannot be imported due to lack of patches. Isn't it necessary to reflect changes to `test_profile.vim` because it is a test that is not run?

Comment (janlazo) [reply src/nvim/eval.c]: That test is N/A so you can omit the test. Comment out the line, `source screendump.vim`.

Comment (justinmk) [reply src/nvim/eval.c]: We could have an empty `screendump.vim` so that such lines don't need to be commented-out.

File: src/nvim/globals.h [hunk 2]
```diff
@@ -332,8 +332,8 @@ EXTERN int garbage_collect_at_exit INIT(= false);
 #define SID_LUA         -7      // for Lua scripts/chunks
 #define SID_API_CLIENT  -8      // for API clients
 
-// ID of script being sourced or was sourced to define the current function.
-EXTERN scid_T current_SID INIT(= 0);
+// Script CTX being sourced or was sourced to define the current function.
+EXTERN sctx_T current_sctx INIT(= { 0 COMMA 0 });
```
Comment (justinmk) [inline src/nvim/globals.h]: I wonder if we actually need `COMMA`. It's from https://github.com/vim/vim/commit/ac77aec4daea8d73468fcf4690cb4ccab1d807ed . 

We use `,` (literal comma) when defining `g_stats`, and we don't get a clang warning.

File: src/nvim/ex_docmd.c [hunk 3]
```diff
@@ -1498,22 +1482,61 @@ static char_u * do_one_cmd(char_u **cmdlinep,
...
+  // %  (entire file)
+  // $  [+-NUM]
+  // 'x [+-NUM] (where x denotes a currently defined mark)
+  // .  [+-NUM]
+  // [+-NUM]..
+  // NUM
+  //
+  // The ea.cmd pointer is updated to point to the first character following the
+  // range spec. If an initial address is found, but no second, the upper bound
+  // is equal to the lower.
```
Comment (justinmk) [inline src/nvim/ex_docmd.c]: lost some formatting here. I'll fix it in the merge.

**Comment by justinmk** [comment]
@erw7  thank you!
