### PR TITLE
fix(window): crash closing split if autocmds close other splits

### LINKED ISSUE #37211: sigsegv on WinClosed when enable vim._extui
## Steps to reproduce

`nvim --clean -u repro.lua`
```lua
local api = vim.api
vim.g.loaded_netrw = 1
require('vim._extui').enable({})
vim.cmd.tabnew()
local buf1 = api.nvim_create_buf(false, true)
local win1 = api.nvim_open_win(buf1, true, { split = 'right' })
local buf2 = api.nvim_create_buf(false, true)
local win2 = api.nvim_open_win(buf2, true, { split = 'below' })
api.nvim_create_autocmd('WinClosed', { callback = function() api.nvim_buf_delete(buf1, { force = true }) api.nvim_buf_delete(buf2, { force = true }) end })
api.nvim_create_autocmd('BufEnter', { buffer = buf1, callback = function() api.nvim_set_current_win(win2) return true end })
vim.schedule(function()
  vim.fn.win_gotoid(win1)
  vim.cmd('wincmd w|q|q')
end)
```

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  win_close (win=<optimized out>, free_buf=<optimized out>, force=<optimized out>) at /usr/src/debug/neovim-git/neovim/src/nvim/window.c:2892
2892       curwin = wp;
(gdb) bt
#0  win_close (win=<optimized out>, free_buf=<optimized out>, force=<optimized out>) at /usr/src/debug/neovim-git/neovim/src/nvim/window.c:2892
#1  0x000055e4fc28c435 in execute_cmd0 (retv=retv@entry=0x7ffcf95ec744, eap=eap@entry=0x7ffcf95ec750, errormsg=errormsg@entry=0x7ffcf95ec748, preview=preview@entry=false)
    at /usr/src/debug/neovim-git/neovim/src/nvim/ex_docmd.c:1762
#2  0x000055e4fc28dbac in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffcf95ec9f8, flags=flags@entry=7, cstack=cstack@entry=0x7ffcf95eca80, 
    fgetline=fgetline@entry=0x55e4fc48b990 <getsourceline>, cookie=cookie@entry=0x7ffcf95ed050) at /usr/src/debug/neovim-git/neovim/src/nvim/ex_docmd.c:2392
#3  0x000055e4fc28ec1e in do_cmdline (cmdline=<optimized out>, fgetline=0x55e4fc48b990 <getsourceline>, cookie=0x7ffcf95ed050, flags=7)
    at /usr/src/debug/neovim-git/neovim/src/nvim/ex_docmd.c:679
#4  0x000055e4fc48c251 in do_source_ext (fname=<optimized out>, check_other=<optimized out>, is_vimrc=<optimized out>, ret_sid=<optimized out>, eap=<optimized out>, 
    ex_lua=<optimized out>, str=0x55e53b058358 "wincmd w|q|q") at /usr/src/debug/neovim-git/neovim/src/nvim/runtime.c:2301
#5  0x000055e4fc16f981 in do_source_str (str=<optimized out>, traceback_name=<optimized out>) at /usr/src/debug/neovim-git/neovim/src/nvim/runtime.c:2064
#6  exec_impl (channel_id=<optimized out>, src=..., opts=0x7ffcf95ed307, err=0x7ffcf95ed310) at /usr/src/debug/neovim-git/neovim/src/nvim/api/vimscript.c:82
#7  0x000055e4fc34a0f6 in nvim_exec2 (channel_id=9223372036854775809, src=..., opts=0x7ffcf95ed307, err=0x7ffcf95ed310)
    at /usr/src/debug/neovim-git/neovim/src/nvim/api/vimscript.c:58
#8  nlua_api_nvim_exec2 (lstate=0x7f54d22c4380) at /usr/src/debug/neovim-git/neovim/build/src/nvim/auto/lua_api_c_bindings.generated.h:7367
#9  0x00007f54d21b0f46 in ?? () from /usr/lib/libluajit-5.1.so.2
#10 0x00007f54d21c66f0 in lua_pcall () from /usr/lib/libluajit-5.1.so.2
#11 0x000055e4fc357120 in nlua_pcall (nresults=0, lstate=0x7f54d22c4380, nargs=0) at /usr/src/debug/neovim-git/neovim/src/nvim/lua/executor.c:180
#12 nlua_schedule_event (argv=<optimized out>) at /usr/src/debug/neovim-git/neovim/src/nvim/lua/executor.c:382
#13 0x000055e4fc4d0e49 in state_handle_k_event () at /usr/src/debug/neovim-git/neovim/src/nvim/state.c:118
#14 0x000055e4fc3e61d6 in nv_event (cap=<optimized out>) at /usr/src/debug/neovim-git/neovim/src/nvim/normal.c:6653
#15 0x000055e4fc3d6a06 in normal_execute (state=0x7ffcf95ed580, key=<optimized out>) at /usr/src/debug/neovim-git/neovim/src/nvim/normal.c:1254
#16 0x000055e4fc4d8ea8 in state_enter (s=0x7ffcf95ed580) at /usr/src/debug/neovim-git/neovim/src/nvim/state.c:100
#17 0x000055e4fc3d31f6 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /usr/src/debug/neovim-git/neovim/src/nvim/normal.c:523
#18 0x000055e4fc12402d in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/neovim-git/neovim/src/nvim/main.c:660
```

## System info

- Nvim version (nvim -v): `v0.12.0-dev-1917 gc53fb58c15` neovim/neovim@c53fb58c15
- Vim (not Nvim) behaves the same?: ?
- Operating system/version: Linux 6.18.2-zen2-1-zen
- Terminal name/version: kitty
- $TERM environment variable: `xterm-kitty`
- Installation: ?

### PR DESCRIPTION
**Pull request by zeertzjq**
Problem:  Crash when closing a split window if autocmds close other
          split windows but there are still floating windows.
Solution: Bail out and give the window back its buffer.

Fix #37211

### CODE REVIEW

**Comment by benja2998** [comment]
I tested this, and it does fix the segmentation fault.

File: src/nvim/window.c [hunk 1]
```diff
@@ -2848,8 +2875,18 @@ int win_close(win_T *win, bool free_buf, bool force)
 
   // Autocommands may have closed the window already, or closed the only
   // other window or moved to another tab page.
-  if (!win_valid(win) || (!win->w_floating && last_window(win))
-      || close_last_window_tabpage(win, free_buf, prev_curtab)) {
+  if (!win_valid(win)) {
+    return FAIL;
+  }
+  if (!win->w_floating && one_window(win, NULL)
```
Comment (seandewar) [inline src/nvim/window.c]:
```suggestion
  if (one_window(win, NULL)
```

Maybe implied by `one_window`?

File: src/nvim/window.c [hunk 2]
```diff
@@ -2697,6 +2700,27 @@ static void win_close_buffer(win_T *win, int action, bool abort_if_last)
...
+/// call this to make the window have a buffer again.
+///
+/// @param bufref         reference to win->w_buffer before calling close_buffer()
+/// @param did_decrement  whether close_buffer() decremented b_nwindows
+static void win_unclose_buffer(win_T *win, bufref_T *bufref, bool did_decrement)
+{
+  if (win->w_buffer == NULL) {
+    // If the buffer was removed from the window we have to give it any buffer.
+    win->w_buffer = firstbuf;
+    firstbuf->b_nwindows++;
```
Comment (seandewar) [inline src/nvim/window.c:2717]: Maybe I missed this in #34950, but this might not be safe if `firstbuf->b_locked_split > 0`?

No need to look into it now, though.

**Review by seandewar — APPROVED** [review]
Review's a bit sloppy as I've gotta go, but LGTM. :+1:

File: src/nvim/window.c (hunk 1 above)
Comment (zeertzjq) [reply src/nvim/window.c]: Ah yes.

File: src/nvim/window.c (hunk 2 above)
Comment (zeertzjq) [reply src/nvim/window.c:2717]: I'm not sure. The same commit that added this (<https://github.com/vim/vim/commit/347538fad0c503249ebdedd5884c2081257c9f61>) also avoids freeing buffer when `b_nwindows` is non-zero, so not checking `b_locked_split` is less of a problem (and may be intentional).

Comment (zeertzjq) [reply src/nvim/window.c:2717]: It turns out that's still a problem, but it's a bit hard to solve, as it's possible that all buffers have `b_locked_split`: https://github.com/vim/vim/pull/19088#issuecomment-3710172769

Comment (seandewar) [reply src/nvim/window.c:2717]: Oof. Is it possible to create a new buffer in that case? But I guess if that also fails, then things are screwed... :rocket:
