### PR TITLE
fix(diagnostics): diagnostic just after EOL is not drawn

### LINKED ISSUE #34013: Diagnostic handlers for diagnostics at EOL are inconsistent
### Problem

The diagnostic handler for opening the floating preview window has [special handling](https://github.com/neovim/neovim/blob/570e62d0f99dbc99e4f506ad1b874bb1842159d0/runtime/lua/vim/diagnostic.lua#L2181) for diagnostics at the end of the line.
https://github.com/neovim/neovim/blob/570e62d0f99dbc99e4f506ad1b874bb1842159d0/runtime/lua/vim/diagnostic.lua#L2181-L2189
However, other handlers, such as the underline one, do not do this, which can lead to a surprising user experience (e.g., if you auto-summon the window when on a diagnostic, it will appear in places where there aren't diagnostic indicators). Can the handlers be made consistent?

### Nvim version (nvim -v)

0.11.1

### PR DESCRIPTION
**Pull request by faergeek**
Fixes #34013

Problem:
when diagnostic is set right after EOL, underline handler looks inconsistent compared to other handlers, visually underline is shown starting from the next line. On top of that it's also inconsistent with open_float and jump.

Solution:
clamp starting column position in underline handler to be right before EOL to make it visible and consistent with other handlers, open_float and jump.

### CODE REVIEW

**Comment by faergeek** [comment]
Not really sure where to add a test for it. Doesn't look like there are tests dedicated to an underline handler unless I'm missing something.

File: runtime/lua/vim/diagnostic.lua [hunk 1]
```diff
@@ -1566,11 +1566,14 @@ M.handlers.underline = {
         end
       end
 
+      local lines =
+        vim.api.nvim_buf_get_lines(diagnostic.bufnr, diagnostic.lnum, diagnostic.lnum + 1, true)
+
```
Comment (faergeek) [inline runtime/lua/vim/diagnostic.lua:1571]: Not really sure if this destroys performance. Should this be cached instead similar to `buf_line_count` metatable in `get_diagnostics`?

Comment (justinmk) [reply runtime/lua/vim/diagnostic.lua:1586]: instead of this, would it help to allow callers of `vim.hl.range()` to control  `eol` here? https://github.com/neovim/neovim/blob/322a6d305d088420b23071c227af07b7c1beb41a/runtime/lua/vim/hl.lua#L94-L97

Comment (justinmk) [reply runtime/lua/vim/diagnostic.lua:1586]: I mean would `eol=false` solve the problem. It looks like your workaround here is essentially doing that in a different way.

Comment (justinmk) [reply runtime/lua/vim/diagnostic.lua:1586]: should those images be swapped? your problem statement says:

> visually underline is shown starting from the next line

**Comment by justinmk** [comment]
> Not really sure if this destroys performance. Should this be cached instead similar to `buf_line_count` metatable in `get_diagnostics`?

Definitely don't want more caches. We are using the [same approach](https://github.com/neovim/neovim/blob/570e62d0f99dbc99e4f506ad1b874bb1842159d0/runtime/lua/vim/diagnostic.lua#L2181-L2182) elsewhere as mentioned in the linked issue.

I wonder if any of this logic could be shared instead of repeated in multiple places...

File: runtime/lua/vim/diagnostic.lua (hunk 1 above)
Comment (faergeek) [reply runtime/lua/vim/diagnostic.lua:1586]: Diagnostic here is set on a line with `foo = 'bar'`, right after the last `'`.

First screenshot shows that without this change there's currently no visible underline anywhere in the `foo = 'bar'` line. Instead it's shown starting only from the following `baz = 'quux',` line.

Second screenshot shows how with the change from this PR an underline being shifted to be right on the last `'` to be visible.

Not sure where the confusion comes from.

**Comment by faergeek** [comment]
>Definitely don't want more caches. We are using the [same approach](https://github.com/neovim/neovim/blob/570e62d0f99dbc99e4f506ad1b874bb1842159d0/runtime/lua/vim/diagnostic.lua#L2181-L2182) elsewhere as mentioned in the linked issue.
>
>I wonder if any of this logic could be shared instead of repeated in multiple places...

I have [another PR open](https://github.com/neovim/neovim/pull/34014) which removes the code you linked to. Instead it creates extmarks to track positions of diagnostics and uses it in `open_float` and `jump`. Extmark positions include this workaround as well. We could probably make all handlers use either that extmark's position for handlers or use that single extmark for all handlers, by adding/removing highlighting, virtual text, lines, signs, etc. to reuse this logic.

Though currently extmark end positions in that PR are shifted one column to the left to avoid showing a float after the visible underline. And if we use that extmark for underline, underline itself will be shifted as well. But I'm almost sure that this shifting could be moved to `open_float` instead without affecting anything else.

**Comment by faergeek** [comment]
>shifting could be moved to `open_float` instead without affecting anything else.

Just pushed a commit to do that.

It would now be possible to reuse that position or the extmark itself for handlers, for example, to avoid repeating that workaround in multiple places. I'm not sure if it makes sense to actually do that change in the same PR. I could start working on a new PR on top of it if that approach with using extmarks (or their positions) sounds like a good idea.

File: runtime/lua/vim/diagnostic.lua (hunk 1 above)
Comment (justinmk) [reply runtime/lua/vim/diagnostic.lua:1586]: the confusion is:

1. the 2nd image just looks like a mistake and doesn't seem very important.
2. the pr title is "avoid starting an underline beyond EOL" which sounds like it *doesn't* want to start the underline on the previous line.
3. the pr description just says "looks inconsistent" instead of saying the actual problem.

how is that not confusing?

Comment (faergeek) [reply runtime/lua/vim/diagnostic.lua:1586]: Now I see it. Sorry. It wasn't obvious to me that "starting" sounds like it's visible there. I should've described the problem better.

File: runtime/lua/vim/diagnostic.lua [hunk 2]
```diff
@@ -1581,11 +1581,14 @@ M.handlers.underline = {
         end
       end
 
+      local lines =
+        vim.api.nvim_buf_get_lines(diagnostic.bufnr, diagnostic.lnum, diagnostic.lnum + 1, true)
```
Comment (justinmk) [inline runtime/lua/vim/diagnostic.lua:1585]: TODO: after https://github.com/neovim/neovim/issues/31903 we could add `opts` to `nvim_buf_line_count()` for a more performant way to count lines in a partial buffer.
