### PR TITLE
VimL/confirm(): Show dialog even if :silent

### LINKED ISSUE #8788: confirm doesn't show options when used with autocmd's
- `nvim --version`: 0.3.1
- Operating system/version: Arch
- Terminal name/version: alacritty 0.1.0
- `$TERM`: screen-256color 

### Steps to reproduce using

```
cat > test-init.vim <<HERE
autocmd BufNewFile * call confirm('test')
HERE
```
```
nvim -u test-init.vim

```

run the following command
```
:e myfile.we
```

### Actual behaviour

Nothing seems to happen. File doesn't open. No confirm dialog is displayed but, if you hit enter you will go to the file. Seems that confirm is working but not being visually displayed.

### Expected behaviour
I expected to see a confirm dialog at the bottom of the screen, like if I ran the following by itself (which does work)
```
:call confirm('test')
```

Appreciate you people for looking into this :)

### PR DESCRIPTION
**Pull request by justinmk**
closes #8788

### CODE REVIEW

File: test/functional/eval/input_spec.lua [hunk 1]
```diff
@@ -439,3 +440,40 @@ describe('inputdialog()', function()
...
+    command('set shortmess+=F')
+    feed(':edit foo<cr>')
+    check_and_clear(':edit foo                |\n')
+
+    -- With :silent
+    feed(':silent edit foo<cr>')
+    check_and_clear(':silent edit foo         |\n')
+
+    -- With API (via eval/VimL) call and shortmess+=F
+    feed(':call nvim_command("edit x")<cr>')
```
Comment (bfredl) [inline test/functional/eval/input_spec.lua]: What about just `command('edit x')` (rpc api), will it work the same? Regardless it could be added to the test.

Comment (justinmk) [reply test/functional/eval/input_spec.lua]: Not sure how to test that since it will block, currently.

Comment (justinmk) [reply test/functional/eval/input_spec.lua]: Oh, could send it as a notification.
