### PR TITLE
fix: pasting in terminal buffer on windows

### LINKED ISSUE #14621: pasting into nvim terminal is ignoring newlines
- `nvim --version`: v0.4.4
- Operating system/version: windows
- Terminal name/version: git bash version 4.4.23(1)-release
- `$TERM`: i dont know what i should write here, if someone know please let me know so i can edit this

so i installed nvim today, and here is my init.vim file: https://pastebin.com/nRyCPTqk
and say i have this c++ code (which doesnt really matter): https://pastebin.com/18rSSvMA
and this input:
```
2
4
1 2 1 1
4
1 2 3 4
```

### Actual behaviour
when i press `f5` to compile the file im working on and open `a.exe` file, and paste the input above, this is how its being pasted:
`241 2 1 141 2 3 4`

### Expected behaviour
but it is supposed to be pasted as this:

```
2
4
1 2 1 1
4
1 2 3 4
```

im using this commmand to open a new terminal with nvim 
```
augroup compileandrun
    autocmd!
    autocmd filetype python nnoremap <f5> :w <bar> :!python % <cr>
    autocmd filetype cpp nnoremap <f5> :w <bar> !g++ -std=c++17 % <cr> :vnew <bar> :te "a.exe" <cr><cr>
    autocmd filetype cpp nnoremap <f6> :vnew <bar> :te "a.exe" <cr>
augroup END 
```
and i also have this in init.vim file: `set shell=cmd.exe` because nvim is showing this when i press `f5` if i dont have that: `/usr/bin/bash: /s: No such file or directory`
how can i fix this.

i also attached an image of input

Screenshot (659)

### PR DESCRIPTION
**Pull request by 3N4N**
fix: pasting in terminal buffer on windows

Problem:
On Windows, pasting multiple lines on a terminal buffer cause all the
lines to appear on the same line, i.e., the line breaks are lost.

Cause:
Windows shells expect '\r\n' as line break but 'terminal_paste' function
uses '\n'.

Solution:
Use '\r\n' as line break for pasting in terminal buffer on Windows.

Note:
Although this issue was reported with powershell set as 'shell', it
occurs in cmd too.

Fixes #14621

### CODE REVIEW

**Comment by 3N4N** [comment]
@dundargoc could you take a look at the test.  I repurposed two existing tests.  Works fine.  But I don't know Lua and don't know the way I did it is proper.

Pinging you because you worked on a similar if not the same bug a while ago so you should know how to test it.

File: test/functional/terminal/buffer_spec.lua [hunk 1]
```diff
@@ -170,6 +176,30 @@ describe(':terminal buffer', function()
...
+
+  it('sends data to the terminal when the "put" operator is used', function()
+    test_terminal_put_operator()
+  end)
+
+  it('sends data to the powershell terminal when the "put" operator is used', function()
+    if not helpers.has_powershell() then
+      pending("powershell not found", function() end)
+      return
+    end
```
Comment (justinmk) [inline test/functional/terminal/buffer_spec.lua:189]: can use skip()

```suggestion

    skip(helpers.has_powershell(), 'missing powershell')
```

File: test/functional/terminal/buffer_spec.lua [hunk 2]
```diff
@@ -170,6 +176,30 @@ describe(':terminal buffer', function()
...
+    test_terminal_put_operator()
+  end)
+
+  it('sends data to the terminal when the ":put" command is used', function()
+    test_terminal_put_command()
+  end)
+
+  it('sends data to the powershell terminal when the ":put" command is used', function()
+    if not helpers.has_powershell() then
```
Comment (justinmk) [inline test/functional/terminal/buffer_spec.lua:198]: skip()

File: test/functional/terminal/buffer_spec.lua (hunk 1 above)
Comment (3N4N) [reply test/functional/terminal/buffer_spec.lua:185]: > merge the powershell tests into the non-powershell tests

Something like this?
```
  it('sends data to the terminal when the "put" operator is used', function()
    test_terminal_put_operator()
    if helpers.has_powershell() then
      helpers.set_shell_powershell(false)
      test_terminal_put_operator()
    end
  end)
```
This^ fails.  Probably needs to clear the terminal window in between the two tests.

Or did you mean something else?

Comment (justinmk) [reply test/functional/terminal/buffer_spec.lua:185]: yes

Comment (3N4N) [reply test/functional/terminal/buffer_spec.lua:185]: > Probably needs to clear the terminal window in between the two tests.

I don't know how to do this.  I tried calling `clear()` but that pauses/halts the test.

Comment (justinmk) [reply test/functional/terminal/buffer_spec.lua]: oh I see the `before_each` is doing too much extra stuff. Ok, let's keep the separate tests :)

I pushed a commit

File: src/nvim/terminal.c [hunk 3]
```diff
@@ -724,7 +724,11 @@ void terminal_paste(long count, char **y_array, size_t y_size)
     for (size_t j = 0; j < y_size; j++) {
       if (j) {
         // terminate the previous line
+#ifdef MSWIN
+        terminal_send(curbuf->terminal, "\r\n", 2);
```
Comment (justinmk) [inline src/nvim/terminal.c:728]: Do the tests correctly fail if this is changed to `"\n", 1` ?

**Review by justinmk — APPROVED** [review]

File: src/nvim/terminal.c (hunk 3 above)
Comment (3N4N) [reply src/nvim/terminal.c:728]: No it doesn't.  I don't know why.  Any idea how to fix the test?

(I don't have busted installed, so I had to test with [CI][1].)

[1]: https://github.com/3N4N/neovim/actions/runs/4376063722/jobs/7657639577#step:9:230

Comment (justinmk) [reply src/nvim/terminal.c:728]: These tests use https://github.com/neovim/neovim/blob/64d3f68c07f7e67bbbd5db11b289705f7569b949/test/functional/terminal/helpers.lua#L54

Maybe `feed_command()` in the tests isn't sending multi-line input, or maybe `tty-test.c` is not being "strict" enough about CRLF vs LF: https://github.com/neovim/neovim/blob/64d3f68c07f7e67bbbd5db11b289705f7569b949/test/functional/fixtures/tty-test.c#L128-L132

Actually, it looks like `tty-test.c` is being invoked once per line, which does not test what we want. Confirmed by this change:

```diff
diff --git a/test/functional/fixtures/tty-test.c b/test/functional/fixtures/tty-test.c
index 6ee77150213d..81398cb77768 100644
--- a/test/functional/fixtures/tty-test.c
+++ b/test/functional/fixtures/tty-test.c
@@ -110,6 +110,7 @@ static void read_cb(uv_stream_t *stream, ssize_t cnt, const uv_buf_t *buf)
   };
   uv_write(&req, STRUCT_CAST(uv_stream_t, &out), &b, 1, NULL);
   uv_run(&write_loop, UV_RUN_DEFAULT);
+  fprintf(stderr, "xxxxxxxxx\n");
 
   uv_close(STRUCT_CAST(uv_handle_t, &out), NULL);
   uv_run(&write_loop, UV_RUN_DEFAULT);
```

Comment (erw7) [reply src/nvim/terminal.c:728]: It is clear from the following code that even after calling `set_shell_powershell()`, the command that `thelper.screen_setup()` executes is `tty-test.exe`.

https://github.com/neovim/neovim/blob/8065fc9aaeff734f38109aec52bf852379a5a183/test/functional/terminal/helpers.lua#L54-L58

Therefore, if you want to test pasting into PowerShell, you need to pass `powershell.exe` as the command argument to pass to `thelper.screen_setup()`.

Comment (justinmk) [reply src/nvim/terminal.c:728]: Good suggestion, though I think we could also test it by modifying `tty-test` to mimic cmd.exe / powershell behavior?

Comment (erw7) [reply src/nvim/terminal.c:728]: I remember a long time ago that `libuv` used to convert newline codes. Therefore, it is easier to use `PowerShell`.

https://github.com/neovim/neovim/blob/d15abd1be4ae85b10174e3ee139d3b7605e87577/src/nvim/tui/tui.c#L1775

Comment (3N4N) [reply src/nvim/terminal.c:728]: > Therefore, if you want to test pasting into PowerShell, you need to pass powershell.exe as the command argument to pass to `thelper.screen_setup()`

I am having trouble implementing this.  First I didn't know how to change an instruction in `before_each()` block because changing it would affect all tests.  I found that I can call `clear()` and reassign a new screen with `screen_setup()`.  Using pwsh was successful.  But pwsh starts with a unique prompt, containing current working directory and other stuff.  I thought I could change the prompt to a simple `PS> `, but my input aren't being accepted.  It's being registered in the screen, I can confirm that with `screenshot_util`, but the pwsh prompt isn't changing.  In fact, the next pwsh prompt doesn't appear at all, no matter how many times I `feed('<cr>')` into it.

I'll try again next week but I don't think I can make any progress.  I don't really know lua neither the test-suite and I can't really spend time on it.  Someone needs to take this PR over from me.

Comment (erw7) [reply src/nvim/terminal.c:728]: I don't think `test_terminal_put_operator()`, etc. can be used as is for `PowerShell`. Therefore, why not try using a separate 
`describe` clause such as the following  (I haven't tried it to see if it works because the MinGW test is broken and I haven't actually run it)? I'm doing something weird like `[char]0x3E` due to quoting, but the prompt should be `>`.

```lua
describe('powershell on terminal', function()
  local screen

  before_each(function()
    clear()
    feed_command('set modifiable swapfile undolevels=20')
    poke_eventloop()
    local command = '["' .. is_os('win') and 'powershell' or 'pwsh' .. '", "-NoLogo", "-NoProfile", "-NoExit", "-Command", "function Prompt{[char]0x3E}"]'
    screen = thelpers.screen_setup(nil, command)
  end)

  it('":put" command sends data normally', function()
    feed('<c-\\><c-n>gg"ayj')
    feed_command('let @a = "1\n2\n3\n" . @a')
    feed_command('put a')
    screen:expect([[
    …
    ]])
  end)

  it('send data normally when "put" operator is used', function()
  …
  end)
end)
```

Comment (3N4N) [reply src/nvim/terminal.c:728]: Thanks.  I didn't realize I can pass args in the list/dictionary of `command`.  Massively useful.

Unfortunately, the results of `:put a` or `"ap` aren't what's expected.

Here's the snapshot of `:put a`.  "1\n2\n3" doesn't appear on screen.
```
screen:expect{grid=[[
                                                    |
  {2: }                                                 |
                                                    |
                                                    |
                                                    |
  ^                                                  |
  :put a                                            |
]]}
```

If I remove `feed('<c-\\><c-n>gg"ayj')` from your example, the output contains more stuff but not "1\n2\n3":

```
screen:expect{grid=[[
  :let @a = "1                                      |
  2                                                 |
  3                                                 |
  "                                                 |
  :put a                                            |
  {1: }                                                 |
  {3:-- TERMINAL --}                                    |
]]}
```

You might think the @a has been put somewhere above visible screen.  But I extended `extra_rows` arg of `screen_setup()` and it just shows empty rows below, not "1\n2\n3".

Any idea?

Comment (3N4N) [reply src/nvim/terminal.c:728]: Wait.  This may be a different problem.  `feed_command('let @a = "1\n2\n3\n"')` doesn't work properly.  It gets `E114: Missing quote: "1`.  I think maybe because it's literally putting a newline in the command.

**Comment by 3N4N** [comment]
Um... PowerShell requires "\r\n" in Linux, too.  Should we consider making "\r\n" the linefeed for _all_ shells and OS?

File: src/nvim/terminal.c (hunk 3 above)
Comment (3N4N) [reply src/nvim/terminal.c:728]: Any idea how to `screen:expect` `{UNEXPECTED foreground = tonumber('0x000002')`?  This is what powershell is emitting.

**Comment by 3N4N** [comment]
> Does it _require_ \r\n or does it merely _support_ it?

It requires CRLF.  Pasting multiline in terminal buffer causes all lines to appear on the same line (which is the same bug this PR fixes for Windows).

> I would expect it to support \n as a line-ending on unix (see below).

Right.  It should be considered a bug in pwsh itself.  I will report it once I figure out how to reproduce it outside nvim.

As pwsh is working in an unexpected way in Linux, I am thinking we test the Windows thing with cmd only.  I have made it work.  If you think that's enough for now, I can clean stuff up and push.

**Comment by justinmk** [comment]
> I am thinking we test the Windows thing with cmd only. I have made it work.

Awesome, let's not block this then.

File: src/nvim/terminal.c (hunk 3 above)
Comment (erw7) [reply src/nvim/terminal.c:728]: It seems to be possible to pass different `cmd` to `before_each` for each `it` in the following way without having to separate the `describe` clause. This may not be useful information as it seems to have been implemented already, but it is for your information.

```lua
describe('Test', function()
  local cmd = nil
  before_each(function() print('before ' .. tostring(cmd)) end)

  it('1', function()
    assert.is_equal(1, 1)
    cmd = 'powershell'
  end)

  it('2', function()
    assert.is_equal(1, 1)
    cmd = 'pwsh'
  end)

  it('3', function()
    assert.is_equal(1, 1)
  end)
end)
```

result

```
before nil
●before powershell
●before pwsh
●
3 successes / 0 failures / 0 errors / 0 pending : 0.001516 seconds
```

Comment (3N4N) [reply src/nvim/terminal.c:728]: Thank you.  It's useful.  (Although, I am confused as to how it works this way, but doesn't matter.)

**Comment by 3N4N** [comment]
> Do the tests correctly fail if this is changed to "\n", 1 ?

I confirm that the current test (with cmd.exe) correctly fails.

[1}: https://github.com/3N4N/neovim/actions/runs/4418211693/jobs/7745017177#step:8:312

File: test/functional/terminal/buffer_spec.lua [hunk 4]
```diff
@@ -429,3 +429,71 @@ it('terminal truncates number of composing characters to 5', function()
...
+
+if is_os('win') then
+  describe(':terminal in Windows', function()
+    local screen
+
+    before_each(function()
+      clear()
+      feed_command('set modifiable swapfile undolevels=20')
+      poke_eventloop()
+      local cmd = '["' .. 'cmd.exe' .. '","/K","PROMPT=$g$s"]'
```
Comment (justinmk) [inline test/functional/terminal/buffer_spec.lua:441]:
```suggestion
      local cmd = '["cmd.exe","/K","PROMPT=$g$s"]'
```
