### PR TITLE
viml/profile: revert proftime_T to unsigned type

### LINKED ISSUE #10452: reltimestr(reltime(newer_time, older_time)) does not return negative number
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-tWk8pe/neovim-0.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wn
o-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-tWk8pe/neovim-0.3.4/build/confi
g -I/build/neovim-tWk8pe/neovim-0.3.4/src -I/usr/include -I/build/neovim-tWk8pe/neovim-0.3.4/build/src/nvim/auto -I/build/neovim-tWk8pe/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Steps to reproduce using `nvim -u NORC`

```
let older_time = reltime()
sleep 1m
let newer_time = reltime()
echo reltimestr(reltime(newer_time, older_time))
```

### Actual behaviour
 Very large positive number.

### Expected behaviour
Very small negative number.

I see other issues around the handling of a single `reltime()` which have been correctly closed as wontfix, but the end result of a comparison should be the same for all Vim implementations, no?

### PR DESCRIPTION
**Pull request by justinmk**
- reltimestr(): Produce negative value by comparing the unsigned  proftime_T value to INT64_MAX.

https://github.com/neovim/neovim/issues/10452#issuecomment-511155132
1. The interfaces of nearly all platforms return uint64_t. INT64_MAX is   only half of that.
2. Low-level interfaces like this typically define that there is no   fixed starting point. The only guarantees are that it's (a)   monotonically increasing at a rate that (b) matches real time.

ref 06af88cd72ea
fix #10452

cc @aktau

### CODE REVIEW

File: test/functional/eval/reltime_spec.lua [hunk 1]
```diff
@@ -38,9 +38,9 @@ describe('reltimestr(), reltimefloat()', function()
     local older_time = reltime()
     command('sleep 1m')
     local newer_time = reltime()
-    -- Should be something like -0.002123.
-    local rv = tonumber(reltimestr(reltime(newer_time, older_time)))
-    ok(rv < 0)
-    ok(rv > -10)
```
Comment (justinmk) [inline test/functional/eval/reltime_spec.lua]: Removed this check, because now it yields something like `-9923233`.

File: src/nvim/profile.c [hunk 2]
```diff
@@ -176,22 +169,31 @@ bool profile_equal(proftime_T tm1, proftime_T tm2) FUNC_ATTR_CONST
   return tm1 == tm2;
 }
 
-/// Calculates the sign of a 64-bit integer.
+/// Converts a proftime_T value `tm` to a signed integer.
 ///
-/// @return -1, 0, or +1
-static inline int sgn64(int64_t x) FUNC_ATTR_CONST
+/// @return signed representation of the given time value
```
Comment (aktau) [inline src/nvim/profile.c]: Sorry for the extremely delayed review. I think the CL is good, but I had one more thought.

Being exposed to Go a lot made me think that I would solve it with two distinct types:

  - A type for points in time (proftime_T).
  - A type for the subtraction of two points in time (duration_T or something else). This could be unsigned for negative durations. `profile_sub` would take two `proftime_T`'s and return a `duration_T`.

(It's been a while, but I think C's automatic type conversion might make accidentally assigning one to the other far too easy, and it's not worth defining two types.)

At first sight, they're semantically quite different. One is an absolute point in time (though we don't know the starting point), and the other is a duration.

On second look, there's also something to be said for keeping them as the same type. Essentially, proftime_T (as defined above) is the duration since the processor was started. When subtracting two proftime_T's, it's just rebasing the starting point to the second operand.

I guess what I'm trying to say is: the way it is right now is IMHO a decent tradeoff, as C won't provide too much protection either way (Go would complain if one doesn't cast, even for the same underlying type). 

The only thing I'd change is to document that `profile_signed` is meant to be used `proftime_T`s that are (perhaps indirectly) the result of `profile_sub` calls.

The comment itself is not that important, maybe if you ever pass over the code again.

Comment (justinmk) [reply src/nvim/profile.c]: Thanks. I will update the comment.

> Essentially, proftime_T (as defined above) is the duration since the processor was started.

That was my conclusion as well, though I didn't inspect every call site in the codebase.
