### PR TITLE
[RFC] Always resize the embedded vterm properly

### LINKED ISSUE #4820: loadview clobbers :term height
- Neovim version: NVIM v0.1.5-280-g176f223
- [ ] Vim behaves differently? Vim version: N/A
- Operating system/version: Arch Linux
- Terminal name/version: gnome-terminal/3.20.2
- `$TERM`: xterm-256color

### Actual behaviour
All terminal buffer's height are restricted to 1/2 of full window height after running `loadview`
### Expected behaviour
terminal buffer height is unaffected
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NONE +'set hidden' /tmp/non-existent-file
:terminal
# note cursor is at bottom of screen
<C-\><C-n>
:bn
:bn
i #note cursor is still at bottom of screen
<C-\><C-n>
:bn
:mkview
(can go and verify cursor is still at bottom of screen in terminal in insert mode)
:loadview
:bn
i # (cursor is now at middle of screen)
```

See https://asciinema.org/a/07f8qqrb1dzbabzwo4lqb1e75

### PR DESCRIPTION
**Pull request by mhinz**
Fixes #4820.

### CODE REVIEW

File: src/nvim/fileio.c [hunk 1]
```diff
@@ -6147,6 +6147,11 @@ void ex_doautoall(exarg_T *eap)
     /* restore the current window */
     aucmd_restbuf(&aco);
 
+    if (aco.new_curbuf->terminal) {
+      terminal_resize(aco.new_curbuf->terminal, aco.save_curwin->w_width,
+                      aco.save_curwin->w_height);
+    }
```
Comment (justinmk) [inline src/nvim/fileio.c]: This should probably go in `aucmd_restbuf`. The fact that the bug was only trigger in doautoall is just an accident isn't it?

Comment (mhinz) [inline src/nvim/fileio.c]: Yes, or maybe even more general.. because the actual problem is a terminal buffer shown multiple times in different windows.

E.g. http://imgur.com/MTJIB2p

Here, the terminal buffer was created in the bottom right window. Then I switched to that buffer in the left window and can only scroll to the middle, since it's the height of the window the terminal buffer was created in.

So.. it should probably done in `win_enter()` instead?

**Comment by justinmk** [comment]
Yes, if you do it on buf-enter it may fix https://github.com/neovim/neovim/issues/3864 ... which would be awesome. (Perhaps skip the resize if the dimensions did not change...)

**Comment by mhinz** [comment]
Okay, it's breaking 5 tests at the moment, but the current state should fix 3864.

Here a small demo that shows how it resizes on BufEnter and WinEnter: https://asciinema.org/a/di92pifp4m36aljdeswze3f7g

(BTW, `terminal_resize()` iself does the dimension check already.)

**Comment by justinmk** [comment]
I read the tests, but I don't see why an extra column was added in the mouse spec.

**Comment by mhinz** [comment]
@justinmk 

I also scratched my head about that, but it's actually quite simple:

By default 50 columns are used for the whole screen. When I have 2 windows, one of them will be smaller than the other (25 cols for win A, 1 col vertical split column, 24 cols win B). And since the previous behaviour was to limit the vterm size to that of the smallest window, it would be 24 columns in both cases.

With the new behaviour, we properly resize the terminal (on entering the window) to fit the window dimensions exactly now.

**Comment by justinmk** [comment]
Oh darn, there's a bit of a regression here. Try this:

```
:te
:vsplit
:vsplit
:tabnew
:buffer term
echo 'foo bar baz 1 foo bar baz 2 foo bar baz 3 foo bar baz 4 foo bar baz 5 foo bar baz 6'
gt
gt
```

The echo'd text is now permanently truncated.

**Comment by mhinz** [comment]
Argh. Hmm. I see how the previous behaviour of keeping the vterm size to that of the smallest window showing that vterm was a workaround, but a workaround nevertheless.

It would be awesome if this could be fixed in libvterm, but the current behaviour is an improvement already.

**Comment by justinmk** [comment]
Instead of forcing this behavior, why don't we make it part of `:redraw!` / `<C-L>` ? Those who want to force it unconditionally can set up a handler:

    au TermOpen * au <buffer> WinEnter redraw!

**Comment by mhinz** [comment]
Also, https://github.com/neovim/neovim/pull/5045.
