### PR TITLE
fix(health): false positive causes entire python check to fail

### LINKED ISSUE #23622: CheckHealth, Python, unclear and apparently unwarranted WARNING about $VIRTUAL_ENV and python-argcomplete-check-easy-install-script
### Problem

I'm getting this broken warning from python CheckHealth. Notice the blank-space after "But $PATH yields this python-argcomplete...". Every check that I do looks correct.

NVIM v0.9.0

Wrapper script that activates venv.
[We suffer from slow NFS, so I like to run nvim out of the fastest filesystem I could find: /dev/shm.]
```
#!/bin/sh
source /proj/*****/envs/globals_python3.11/bin/activate
[ -r /dev/shm/nvim/usr/bin/nvim ] && exec /dev/shm/nvim/usr/bin/nvim $*
mkdir /dev/shm/nvim
nvim_usr_dir="/proj/*****/bin/$(readlink /proj/*****/bin/latest-nvim)/squashfs-root/usr"
/bin/cp -r $nvim_usr_dir /dev/shm/nvim
exec /dev/shm/nvim/usr/bin/nvim $*
```

`:CheckHealth`
```
Python 3 provider (optional)
- Using: g:python3_host_prog = "/proj/*****/envs/globals_python3.11/bin/python3"
- Executable: /proj/*****/envs/globals_python3.11/bin/python3
- Python version: 3.11.3
- pynvim version: 0.4.3
- WARNING Could not contact PyPI to get latest version.
- ERROR HTTP request failed: unable to get pypi response

Python virtualenv
- WARNING $VIRTUAL_ENV is set to: /proj/*****/envs/globals_python3.11
  And its /bin directory contains: python, python-argcomplete-check-easy-install-script, python3, python3.11
  But $PATH yields this python-argcomplete-check-easy-install-script executable:
  This script is part of the Python argcomplete package (https:/github.com/kislyuk/argcomplete).
  It is used to check if an EASY-INSTALL-SCRIPT wrapper redirects to a script that contains the string
  "PYTHON_ARGCOMPLETE_OK". If you have enabled global completion in argcomplete, the completion hook will run it every
  time you press <TAB> in your shell.

  Usage:
  python-argcomplete-check-easy-install-script <input executable file>

  And $PATH in subshells yields this python-argcomplete-check-easy-install-script executable:
  This script is part of the Python argcomplete package (https:/github.com/kislyuk/argcomplete).
  It is used to check if an EASY-INSTALL-SCRIPT wrapper redirects to a script that contains the string
  "PYTHON_ARGCOMPLETE_OK". If you have enabled global completion in argcomplete, the completion hook will run it every
  time you press <TAB> in your shell.

  Usage:
  python-argcomplete-check-easy-install-script <input executable file>

  So invoking Python may lead to unexpected results.
  - ADVICE:
    - $PATH ambiguities arise if the virtualenv is not properly activated prior to launching Nvim. Close Nvim, activate the virtualenv, check that invoking Python from the command line launches the correct one, then relaunch Nvim.
    - $PATH ambiguities in subshells typically are caused by your shell config overriding the $PATH previously set by the virtualenv. Either prevent them from doing so, or use this workaround: https://vi.stackexchange.com/a/34996
```

Checking the path find for this script, it looks correct.
```
:!type -a python-argcomplete-check-easy-install-script
python-argcomplete-check-easy-install-script is /proj/*****/envs/globals_python3.11/bin/python-argcomplete-check-easy-install-script
```

My path doesn't have any spaces. The venv bin dir is first in the list as expected.
```
:!echo $PATH
/proj/*****/envs/globals_python3.11/bin:<lots-of-other-stuff-with-no-spaces-or-other-weird-characters>
```

### Steps to reproduce

nvim (both --clean and normal)
:CheckHealth

### Expected behavior

No WARNINGs unless there's something potentially wrong with my environment.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Redhat 8

### Terminal name/version

KiTTY

### $TERM environment variable

screen-256color

### Installation

appimage --appimage-extract

### PR DESCRIPTION
**Pull request by juditnovak**
fix https://github.com/neovim/neovim/issues/23622

# Problem

Currently there is no distinction between executables in `$VIRTUAL_ENV` called `python.*` and Python interpreter excutables. For example in the following case (assuming `$VIRTUAL_ENV == '.venv'`)
```
.venv/python-argcomplete-check-easy-install-script
.venv/bin/python3.13
.venv/bin/python
```
the `.venv/python-argcomplete-check-easy-install-script` is evaluated as if it was another Python version,  triggering the error described in https://github.com/neovim/neovim/issues/23622.

# Solution

Strict check on the executable name format.

### CODE REVIEW

File: runtime/lua/vim/provider/health.lua [hunk 1]
```diff
@@ -791,7 +791,7 @@ local function python()
   --- @param v string
   venv_bins = vim.tbl_filter(function(v)
     -- XXX: Remove irrelevant executables found in bin/.
-    return not v:match('python.*%-config')
+    return v:match('python[%-_%d%.]*$') or v:match('python[%-_%d%.]*.exe$')
```
Comment (juditnovak) [inline runtime/lua/vim/provider/health.lua]: In case this attempt may be too restrictive, an alternative solution can remain inclusive at this level, and skip false-positive executables on later checks (`python_exepath()`).

Comment (justinmk) [reply runtime/lua/vim/provider/health.lua]: We also need to match `pynvim-python` since https://github.com/neovim/neovim/pull/35273 . Is that relevant here?

Comment (juditnovak) [reply runtime/lua/vim/provider/health.lua]: From what I understand --please correct if I'm wrong-- the point of this check is to evaluate the Python setup corresponding to the active virtual environment, together with the (safe) availability of `!python` in command mode.

There is a separate check on Python integration (i.e. `pynvim`) preceeding the virtual env verification. Within the scope of this check, the `pynvim-python` command is also evaluated (as of https://github.com/neovim/neovim/pull/35273)

image


While technically it is possible to have `pynvim-python` command installed within the current virtual environment, it does not have relevance for the virtual environment's standard Python setup. In this case the Python Provider check would take note of the `pynvim-python` command availability (and also highlight that the setup is "un-optimal"):

image

Comment (juditnovak) [reply runtime/lua/vim/provider/health.lua]: On the other hand I'm wondering to allow for `3.4.1a2` format as well? (https://docs.python.org/3/c-api/apiabiversion.html)

**Comment by justinmk** [comment]
> On the other hand I'm wondering to allow for `3.4.1a2` format as well? (https://docs.python.org/3/c-api/apiabiversion.html)

Probably. 

I don't get why https://github.com/neovim/neovim/issues/23622 is a problem. It's just a warning. The real check is to execute the python bin and try to run code with it. That is done elsewhere in the healthcheck, I think. 

So trying to come up with a perfect pattern for the name is not going to work. Filtering out false positives is good, and worthwhile, but the check should be much looser than what's currently in this PR.

The old `not v:match` approach is better, i.e. filter out known false-positives.

We know that `python-argcomplete*` is false positive, so just add that to the `not` match pattern (or add another one: `not v:match(...) and not v:match(...)`).

**Comment by juditnovak** [comment]
@justinmk Thx much for your response.

The issue is more than a warning. The `assert` in original code line `368` quits the healthcheck, preventing further evaluations.

I made an attempt to:
 - follow your advice and filter the false-positive
 - make sure that a warning may be raised in case, however not exiting execution

File: runtime/lua/vim/provider/health.lua [hunk 2]
```diff
@@ -364,8 +364,14 @@ end
 
 -- Resolves Python executable path by invoking and checking `sys.executable`.
 local function python_exepath(invocation)
+  if invocation == "" or invocation == nil then
```
Comment (justinmk) [inline runtime/lua/vim/provider/health.lua]:
```suggestion
  if invocation == '' or invocation == nil then
```
