### PR TITLE
fix(api): nvim_create_user_command addr option should allow ranges

### LINKED ISSUE #25920: Using "addr" without "range" in nvim_create_user_command leads to confusing behavior
### Problem

Using `addr` without `range` in `nvim_create_user_command` leads to confusing behavior that is different from using `-addr` without `-range` in `:command`.

### Steps to reproduce

1. Run `:command -addr=other Test1 :`.
2. Run `:1,2Test1`, which doesn't give an error.
3. Run `:call nvim_create_user_command('Test2', ':', #{addr: 'other'})`.
4. Run `:1,2Test2`, which gives `E481: No range allowed`. This is confusing as it is different from the behavior of `:command`, and such a difference is not documented.

### Expected behavior

Less confusing behavior or a documentation update to suggest that "addr" should be used with "range".

### Neovim version (nvim -v)

v0.10.0-dev-1487+g88ed9ffcd

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.30.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by glepnir**
Problem: Using `addr` without `range` in nvim_create_user_command gives "No range allowed" error, inconsistent with `:command -addr` behavior.

Solution: Set EX_RANGE flag when `addr` option is specified to match `:command` behavior.

Fix #25920

### CODE REVIEW

File: test/functional/api/command_spec.lua [hunk 1]
```diff
@@ -782,6 +782,10 @@ describe('nvim_create_user_command', function()
     eq(5, #api.nvim_list_tabpages())
     eq(1, fn.tabpagenr())
   end)
+  it('addr option allows ranges without explicit range option', function()
```
Comment (justinmk) [inline test/functional/api/command_spec.lua]: nit: each it() is separated by a blank line
```suggestion

  it('"addr" flag allows ranges without explicit "range" flag', function()
```

File: test/functional/api/command_spec.lua [hunk 2]
```diff
@@ -782,6 +782,10 @@ describe('nvim_create_user_command', function()
...
+    feed([[:call nvim_create_user_command('Test2', 'echo "hello"', #{addr: 'other'})<CR>]])
```
Comment (justinmk) [inline test/functional/api/command_spec.lua]: should we test that the lines actually got received?
```suggestion
    feed([[:call nvim_create_user_command('Test2', 'echo "hello <line1><line2>"', #{addr: 'other'})<CR>]])
```

File: test/functional/api/command_spec.lua [hunk 3]
```diff
@@ -782,6 +782,11 @@ describe('nvim_create_user_command', function()
     eq(5, #api.nvim_list_tabpages())
     eq(1, fn.tabpagenr())
   end)
+
+  it('"addr" flag allows ranges without explicit "range" flag', function()
+    feed([[:call nvim_create_user_command('Test2', 'echo "hello <line1><line2>"', #{addr: 'other'})<CR>]])
+    eq('hello', n.exec_capture('1,2Test2'))
```
Comment (justinmk) [inline test/functional/api/command_spec.lua]:
```suggestion
    eq('hello 12', n.exec_capture('1,2Test2'))
```

**Comment by justinmk** [comment]
If I change the test to specify `range` instead of `addr`:

    feed([[:call nvim_create_user_command('Test2', 'echo "hello <line1><line2>"', #{range: '%'})<CR>]])
    eq('hello 12', n.exec_capture('1,2Test2'))

it fails with: 

    test/functional/testnvim.lua:139: nvim_exec2(), line 1: Vim:E16: Invalid range: 1,2Test2

whereas with the current PR, `<line1><line2>` just are empty, which makes me think that `adder:'other'` isn't actually working? Where can the user get the `1,2` values? That should be tested.

**Comment by glepnir** [comment]
emm .. the line1 and line2 is escaped ..this is passed.

```lua
it('"addr" flag allows ranges without explicit "range" flag #test', function()
  exec_lua([[
    vim.api.nvim_create_user_command('Test2', 'echo "hello <line1><line2>"', {addr = 'other'})
  ]])
  eq('hello 12', exec_capture('1,2Test2'))
end)
```
