### PR TITLE
fix(autocmds): separate command from desc

### LINKED ISSUE #17588: `command` and `desc` fields are the same in return of `nvim_get_autocmds()`
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1177-g7211d8ef2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 11.6

### Terminal name/version

iTerm2 Build 3.5.0beta4

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

```sh
nvim --clean -u minimal.lua
```

`minimal.lua`
```lua
vim.api.nvim_create_autocmd({ 'InsertEnter' }, {
  callback = function ()
  end,
})
vim.api.nvim_create_autocmd({ 'InsertEnter' }, {
  desc = 'It is desc',
  callback = function ()
  end,
})
print(vim.inspect(vim.api.nvim_get_autocmds({ event = { 'InsertEnter' } })))
```

### Expected behavior

When `nvim_create_autocmd()` with `callback` but without `desc` was called,  the `desc` field of the return of `nvim_get_autocmds()` should be empty. Also, when that with `callback` and `desc` is called the `command` field should be `<Lua function n>` or something else.

```
{ {
    buflocal = false,
    command = "<Lua function 4>",
    desc = "",
    event = "InsertEnter",
    id = 1,
    once = false,
    pattern = "*"
  }, {
    buflocal = false,
    command = "<Lua function 4>",
    desc = "It is desc",
    event = "InsertEnter",
    id = 2,
    once = false,
    pattern = "*"
  } }
```

### Actual behavior

The `command` and `desc` fields are the same.

```
{ {
    buflocal = false,
    command = "<Lua function 4>",
    desc = "<Lua function 4>",
    event = "InsertEnter",
    id = 1,
    once = false,
    pattern = "*"
  }, {
    buflocal = false,
    command = "It is desc",
    desc = "It is desc",
    event = "InsertEnter",
    id = 2,
    once = false,
    pattern = "*"
  } }
```

### PR DESCRIPTION
**Pull request by kylo252**
Fixes the mangling of `desc` and `command` for `callbacks` when reading from `nvim_get_autocmds`.

I assume it was done to help support readability when using `:autocmd`, so I made sure to keep that behavior but with a small twist (appending callback type before), see examples below.

This also adds the benefit of seeing the description for string commands from `:autocmds`

Fixes #17588

Note: possibly related to https://github.com/neovim/neovim/issues/17639

### Example

```lua
  -- vim.api.nvim_create_augroup("test_group", { clear = true })
vim.api.nvim_create_autocmd("BufWritePre", {
  pattern = "*.py",
  group = "test_group",
  command = "echo 'hello1'",
  desc = "dispatch hello1",
})
vim.api.nvim_create_autocmd("BufWritePre", {
  pattern = "*.py",
  group = "test_group",
  callback = function()
    print "hello2"
  end,
  desc = "dispatch hello2",
})
```

- before

  with `:lua =vim.api.nvim_get_autocmds { group = "test_group" })`

  ```lua
  { {
    buflocal = false,
    command = "echo 'hello1'",
    desc = "dispatch hello1",
    event = "BufWritePre",
    group = 54,
    group_name = "test_group",
    id = 52,
    once = false,
    pattern = "*.py"
  }, {
    buflocal = false,
    command = "dispatch hello2",
    desc = "dispatch hello2",
    event = "BufWritePre",
    group = 54,
    group_name = "test_group",
    id = 53,
    once = false,
    pattern = "*.py"
  } }
  ```

  with `:autocmd BufWritePre`

  ```console
  --- Autocommands ---
  test_group  BufWritePre
      *.py      echo 'hello1'
                dispatch hello2
  ```

- after

  with `:lua =vim.api.nvim_get_autocmds { group = "test_group" })`

  ```lua
  { {
      buflocal = false,
      command = "echo 'hello1'",
      desc = "dispatch hello1",
      event = "BufWritePre",
      group = 54,
      group_name = "test_group",
      id = 55,
      once = false,
      pattern = "*.py"
    }, {
      buflocal = false,
      command = "<Lua function 113>",
      desc = "dispatch hello2",
      event = "BufWritePre",
      group = 54,
      group_name = "test_group",
      id = 56,
      once = false,
      pattern = "*.py"
    } }
  ```

  with `:autocmd BufWritePre`

  ```console
  --- Autocommands ---
  test_group  BufWritePre
      *.py      echo 'hello1' [dispatch hello1]
                <Lua function 113> [dispatch hello2]
  ```

### CODE REVIEW

**Comment by clason** [comment]
This is not a refactor if it changes observable behavior!

**Comment by kylo252** [comment]
possibly similar to https://github.com/neovim/neovim/issues/17639

**Comment by clason** [comment]
(sorry, meant to delete my own obsolete command!)

**Comment by kylo252** [comment]
> But the linked issue was in fact not related 

I messed up the link, but I did actually mean https://github.com/neovim/neovim/issues/17639, since they probably need to get on the same page.

adding a `desc` for `vim.api.nvim_create_user_command()` is overriding the "definition" part when using a callback.

> did you mean #17588 (which this would indeed fix)?

oh nice! I'll mark this one as well then

**Comment by clason** [comment]
> I messed up the link, but I did actually mean https://github.com/neovim/neovim/issues/17639, since they probably need to get on the same page. 

No. That was about _user_ commands, not _auto_commands. Please don't drag unrelated discussions into it.

**Comment by kylo252** [comment]
> Please don't drag unrelated discussions into it.

I should've clarified that is about re-using [*_callback_to_string()](https://github.com/neovim/neovim/blob/1bc3bbe2f34925c26ef3d694bfcc8cba03cfd4c5/src/nvim/autocmd.c#L2476-L2501) in

https://github.com//neovim/neovim/blob/d7dd6007167eac919205404bc4e556237118a7a7/src/nvim/api/private/helpers.c#L1614-L1598

**Comment by clason** [comment]
> I think it would be better if we added a new column to the output of :autocmd that lists the description.

Would flip that (command first, (optional) description second) -- otherwise you risk wasting a lot of space?

> It seems weird to me that command is not just an empty string (or nil) in the second autocmd. 

Hmm, I'd prefer the status quo, as this conveys at least _some_ information (first, immediately and explicitly that it's a Lua callback; second, that it is -- or is not -- a different callback than some other autocommand).

**Comment by clason** [comment]
Note that the linked issue also reports a problem when `desc` is _not_ set. Can you test that behaviour as well and verify that it is fixed?

**Comment by gpanders** [comment]
>Hmm, I'd prefer the status quo, as this conveys at least some information (first, immediately and explicitly that it's a Lua callback; second, that it is -- or is not -- a different callback than some other autocommand).

But Nvim already knows how to print Lua function refs:

```vim
:lua vim.pretty_print(function() end)
<function 1>
```

So why not return the Luaref as the `callback` field of that table and let it print out as `<function 42>` or whatever. That would also be useful as a way to actually get a reference to the function itself in Lua code, if one needed to for any reason.

So with this suggestion it would instead look like this:

```lua
{
    buflocal = false,
    command = "",
    callback = <function 113>,
    desc = "dispatch hello2",
    event = "BufWritePre",
    group = 54,
    group_name = "test_group",
    id = 56,
    once = false,
    pattern = "*.py"
}
```

**Comment by clason** [comment]
Yes, that would be even better. (I was merely comparing against `""` or `nil`.)

File: src/nvim/autocmd.c [hunk 1]
```diff
@@ -2465,45 +2472,44 @@ bool autocmd_delete_id(int64_t id)
...
-      char *msg = (char *)xmallocz(msglen);
-      snprintf(msg, msglen, "<vim partial: %s>", acc.callable.cb.data.partial->pt_name);
-      return msg;
-    }
-    default:
-      return NULL;
-    }
+  switch (cb.type) {
+  case kCallbackLua: {
+    snprintf(msg, msglen, "<Lua function %d>", cb.data.luaref);
```
Comment (justinmk) [inline src/nvim/autocmd.c:2485]:
```suggestion
    snprintf(msg, msglen, "<Lua: %d>", cb.data.luaref);
```

File: test/functional/api/autocmd_spec.lua [hunk 2]
```diff
@@ -157,8 +160,11 @@ describe('autocmd api', function()
           })
         ]])
 
-        eq(nil, meths.get_autocmds({ event = 'BufReadPost' })[1].desc)
-        matches('<Lua function %d>', meths.get_autocmds({ event = 'BufReadPost' })[1].command)
+      local aus = meths.get_autocmds({ event = 'BufReadPost' })
+      local first = aus[1]
+        eq(nil, first.desc)
+        eq(nil, first.command)
+        eq("userdata", type(first.callback))
```
Comment (gpanders) [inline test/functional/api/autocmd_spec.lua:167]: This isn't needed.

```suggestion
```

**Review by gpanders — CHANGES_REQUESTED** [review]

File: test/functional/api/autocmd_spec.lua [hunk 3]
```diff
@@ -144,8 +144,11 @@ describe('autocmd api', function()
           })
         ]])
 
-        eq(desc, meths.get_autocmds({ event = 'BufReadPost' })[1].desc)
-        matches('<Lua function %d>', meths.get_autocmds({ event = 'BufReadPost' })[1].command)
+      local aus = meths.get_autocmds({ event = 'BufReadPost' })
+      local first = aus[1]
+        eq(desc, first.desc)
+        eq(nil, first.command)
+        eq("userdata", type(first.callback))
```
[the remark this answers is not in the document]
Comment (kylo252) [reply test/functional/api/autocmd_spec.lua:151]: thanks! I was wondering what was up with tests failing for "function", so I thought I could show what they are so someone can help me figure it out :)

File: test/functional/api/autocmd_spec.lua [hunk 4]
```diff
@@ -195,33 +197,29 @@ describe('autocmd api', function()
...
+        local id = vim.api.nvim_create_autocmd("User", {
+          group = vim.g.group_name,
+          pattern = "RemovalTest",
+          desc = "A test autocommand",
+          callback = function()
+            return vim.g.some_condition
+          end,
+        })
+        vim.g.some_condition = true
+        vim.api.nvim_exec_autocmds("User", {pattern = "RemovalTest"})
```
Comment (gpanders) [inline test/functional/api/autocmd_spec.lua:216]: Still need to check that the autocommand still exists after it runs and the callback returns `false` (like the existing test does).

File: test/functional/api/autocmd_spec.lua [hunk 5]
```diff
@@ -163,8 +167,6 @@ describe('autocmd api', function()
       local aus = meths.get_autocmds({ event = 'BufReadPost' })
       local first = aus[1]
         eq(nil, first.desc)
```
[the remark this answers is not in the document]
Comment (kylo252) [reply test/functional/api/autocmd_spec.lua]: it would've helped if the file was formatted originally, with stylua or otherwise :(

File: test/functional/api/autocmd_spec.lua (hunk 4 above)
Comment (kylo252) [reply test/functional/api/autocmd_spec.lua:221]: commenting out the call to `nvim_get_autocmds()` will get the test-case to pass.  it looks like a race-condition between `nvim_get_autocmds()` and `au_cleanup()` (or whatever is responsible for clearing the autocmds)
if this is actually the case, then I'm afraid that the solution won't be trivial

the first thing that jumps to mind is that we'd need to mark the `autocmd` for deletion individually, instead of marking the entire state as "not clean", but that means a large-ish refactor for the logic of clearing the autocmds. see 
https://github.com/neovim/neovim/blob/2c72dc39d718955ac485a08eecd8407641b98599/src/nvim/autocmd.c#L96-L94

Comment (kylo252) [reply test/functional/api/autocmd_spec.lua]: as discussed, we'll handle this in a separate PR, see #18642

**Comment by clason** [comment]
ASAN is still failing at test `autocmd api nvim_create_autocmd desc will not add a description unless it was provided`.

File: src/nvim/autocmd.c [hunk 6]
```diff
@@ -2465,45 +2476,53 @@ bool autocmd_delete_id(int64_t id)
...
 
+/// Generate a string description for the command/callback of an autocmd
 char *aucmd_exec_to_string(AutoCmd *ac, AucmdExecutable acc)
   FUNC_ATTR_PURE
 {
   switch (acc.type) {
   case CALLABLE_EX:
     return acc.callable.cmd;
-  case CALLABLE_CB:
-    return ac->desc;
```
Comment (kylo252) [inline src/nvim/autocmd.c:2506]: @tjdevries used the `ac->desc` to store this info, but since we want to separate the `command` from the `desc`, that would require separate memory management for the return value of this function, AFAICS.

- alt1 (current solution):  return the string for the command without any further validation, and without including anything about callbacks, except that they're a "function"
- alt2: create a new entry exec_str that's part of the AutoCmd struct, which has auto memory management, same as desc

File: src/nvim/autocmd.c [hunk 7]
```diff
@@ -190,7 +190,18 @@ static void aupat_show(AutoPat *ap, event_T event, int previous_group)
...
+    if (ac->desc != NULL) {
+      size_t msglen = 100;
+      char *msg = (char *)xmallocz(msglen);
+      snprintf(msg, msglen, "%s [%s]", exec_to_string, ac->desc);
+      msg_outtrans((char_u *)msg);
+      xfree(msg);
+    } else {
+      msg_outtrans((char_u *)exec_to_string);
+    }
+    xfree(exec_to_string);
```
Comment (gpanders) [inline src/nvim/autocmd.c:204]: If `ac->exec.type` is CALLABLE_EX then you are freeing the autocommand's command string (which is returned from `aucmd_exec_to_string`. `aucmd_exec_to_string` should `strdup` the command string.

File: src/nvim/autocmd.c [hunk 8]
```diff
@@ -2470,45 +2481,53 @@ bool autocmd_delete_id(int64_t id)
...
+  return "";
 }
 
+/// Generate a string description for the command/callback of an autocmd
 char *aucmd_exec_to_string(AutoCmd *ac, AucmdExecutable acc)
   FUNC_ATTR_PURE
 {
   switch (acc.type) {
   case CALLABLE_EX:
     return acc.callable.cmd;
```
Comment (gpanders) [inline src/nvim/autocmd.c:2527]:
```suggestion
    return xstrdup(acc.callable.cmd);
```

File: src/nvim/autocmd.c (hunk 6 above)
Comment (gpanders) [reply src/nvim/autocmd.c:2511]: I'm not sure I understand your argument here, but I think you're overcomplicating things. It's fine to alloc memory in `aucmd_callback_to_string` and return it from this function. We just need to make sure every call site of `aucmd_exec_to_string` frees it (which is no problem).

File: src/nvim/autocmd.c [hunk 9]
```diff
@@ -2470,45 +2481,53 @@ bool autocmd_delete_id(int64_t id)
...
-    }
-    case kCallbackPartial: {
-      char *msg = (char *)xmallocz(msglen);
-      snprintf(msg, msglen, "<vim partial: %s>", acc.callable.cb.data.partial->pt_name);
-      return msg;
-    }
-    default:
-      return NULL;
-    }
+  // FIXME: enabling dynamic memory will cause problems when called from `nvim_get_autocmds()`
```
Comment (gpanders) [inline src/nvim/autocmd.c:2490]: In `nvim_get_autocmds` change this line

```c
        PUT(autocmd_info,
            "command",
            STRING_OBJ(cstr_to_string(aucmd_exec_to_string(ac, ac->exec))));
```

to

```c
        PUT(autocmd_info,
            "command",
            STRING_OBJ(cstr_as_string(aucmd_exec_to_string(ac, ac->exec))));
```

Then the API layer will take care of freeing the alloc'd memory.

**Review by gpanders — CHANGES_REQUESTED** [review]

File: src/nvim/autocmd.c (hunk 9 above)
Comment (kylo252) [reply src/nvim/autocmd.c:2490]: this seems to be the missing puzzle piece 🙌 
any call to `free()` in this function was causing all sorts of memory issues, even in the cleanup section.

**Comment by gpanders** [comment]
LGTM. Is the lint failure relevant? (On mobile at the moment and hard to read through GHA logs)

**Comment by clason** [comment]
@gpanders  Lint failure is not relevant and fixed by #18673 (go ahead and merge that if it looks good to you)
