### PR TITLE
fix(floating, lsp): set winfixbuf for window opened by open_floating_preview()

### LINKED ISSUE #38913: Floating window opened by `vim.lsp.util.open_floating_preview()` allows buffer switching
### Problem

It is possible to swap out the buffer in a window opened by `vim.lsp.util.open_floating_preview()`.

This function is used by e.g. `vim.diagnostic.open_float()` and `vim.lsp.buf.hover()`. The content in these windows can be rather short. Being able to switch out the buffer in what is a preview window (you're not able to edit diagnostics in the float, neither can you edit the content of `vim.lsp.buf.hover()`) does not feel intuitive. 

### Steps to reproduce

Version with a focused floating window:

nvim --clean
:lua namespace_index = vim.api.nvim_create_namespace("Test")
:lua vim.diagnostic.set(namespace_index, vim.fn.bufnr(), {{lnum=0,col=0,message="Test"}})
:lua vim.diagnostic.open_float()
:lua vim.diagnostic.open_float()
:e test

Version without focusing the floating window: 

:lua namespace_index = vim.api.nvim_create_namespace("Test")
:lua vim.diagnostic.set(namespace_index, vim.fn.bufnr(), {{lnum=0,col=0,message="Test"}})
:lua bufnr, winid = vim.diagnostic.open_float()
:lua vim.api.nvim_win_set_buf(winid, vim.fn.bufnr())

### Expected behavior

You should not be able to switch out buffers in windows opened by `vim.lsp.util.open_floating_preview()`.

I have two candidate solutions for this in mind:

1. The easiest would probably be to set the `winfixbuf` option for the window created by `vim.lsp.util.open_floating_preview()`. 
2. Check if there is a floating window opened by `vim.lsp.util.open_floating_preview()`, return to the previous window and then open the new buffer. I'm not sure if this is something that's realistically implementable. Feel like this has a lot of potential implementation efforts without bringing a lot of value. However, I still think this would be a nice approach.

### Nvim version (nvim -v)

0.12.1

### Vim (not Nvim) behaves the same?

No

### Operating system/version

6.6.87.2-microsoft-standard-WSL2 (Ubuntu 24.04.4 LTS)

### Terminal name/version

Windows Terminal 1.23.20211.0

### $TERM environment variable

tmux-256color

### Installation

bob-nvim (neovim version manager)

### PR DESCRIPTION
**Pull request by Raizento**
Problem:
The window opened by `vim.lsp.util.open_floating_preview()`
allows its buffer to be switched. Presumably that only happens
by accident and is disorienting.

Solution:
Set 'winfixbuf' in the open_floating_preview() window.

Fixes https://github.com/neovim/neovim/issues/38913

### CODE REVIEW

**Comment by justinmk** [comment]
We definitely don't need a 15 line test for this trivial change. Just add an assert to an existing test. The net code increased should be 2-3 lines max.

**Comment by Raizento** [comment]
Fair enough. Was thinking about that as well, but most of the other test cases for `open_floating_preview()` seemed to test other use cases and it didn't feel fitting. But I'll just grab one of them and add an assert to check that `winfixbuf` is set

File: test/functional/plugin/lsp/utils_spec.lua [hunk 1]
```diff
@@ -296,14 +296,16 @@ describe('vim.lsp.util', function()
     end)
 
     it('clean bufvar after CursorMoved', function()
```
Comment (justinmk) [inline test/functional/plugin/lsp/utils_spec.lua:298]: this test description is hard to understand. but yes this test is a good place to check various state on the `open_floating_preview` window.

these tests need cleanup, i'll do so in a followup pr.
