### PR TITLE
fix(api): nvim_parse_cmd don't put key 'range' when ea.addr_count == 0

### LINKED ISSUE #33394: Cannot `nvim_parse_cmd` then `nvim_cmd` command `bd`.
### Problem

The command `"bd"` parsed with `nvim_parse_cmd` cannot be executed with `nvim_cmd` : `Invalid 'range'`.
IIUC this is a bug as per the claim in #20051.
Possibly related: #21313 #21918 #24081.

### Steps to reproduce

```
$ nvim --clean
:lua vim.api.nvim_cmd(vim.api.nvim_parse_cmd("bd", {}), {})
E5108: Error executing lua [string ":lua"]:1: Invalid 'range'
```

### Expected behavior

Equivalent to `:bd`.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-103+g2c960e8f04

### Vim (not Nvim) behaves the same?

no lua in Vim (not Nvim)

### Operating system/version

Arch Linux x86_64

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

AUR (neovim-git)

### PR DESCRIPTION
**Pull request by acehinnnqru**
Fixes: #33394.

Why change the tests?
Adding a condition of `ea.addr_count > 0` would change the behavior,
- We won't add the `range` field to the `result` if the conditions are not matched.
- But the result used to contain a `range` field, which is `{}`.

### CODE REVIEW

**Comment by clason** [comment]
Could you add a self-contained description ("Problem: ... Solution: ... Notes: ...") to the commit message(!), please?

**Comment by acehinnnqru** [comment]
> * We won't add the `range` field to the `result` if the conditions are not matched.

I'm sorry, I have reword it. Sorry to bother you.

**Comment by justinmk** [comment]
Perhaps worth adding the explicit `vim.api.nvim_cmd(vim.api.nvim_parse_cmd("bd", {}), {})` case as a test? From https://github.com/neovim/neovim/issues/33394

File: test/functional/api/vim_spec.lua [hunk 1]
```diff
@@ -4775,6 +4809,7 @@ describe('API', function()
       eq('foo', api.nvim_cmd(api.nvim_parse_cmd('echo "foo"', {}), { output = true }))
       api.nvim_cmd(api.nvim_parse_cmd('set cursorline', {}), {})
       eq(true, api.nvim_get_option_value('cursorline', {}))
+      eq(true, pcall(api.nvim_cmd, api.nvim_parse_cmd('bd', {}), {}))
```
Comment (justinmk) [inline test/functional/api/vim_spec.lua:4812]:
```suggestion
      -- Exercise roundtrip. #33394
      api.nvim_cmd(api.nvim_parse_cmd('bdelete', {}), {}))
```

**Comment by justinmk** [comment]
Does this change the status of any of: #21313 #21918 #24081 ?

**Comment by acehinnnqru** [comment]
> Does this change the status of any of: #21313 #21918 #24081 ?

No. I am missing these issues. I would try to dive into these issue, maybe raise a new PR to solve them.
