### PR TITLE
[RFC] ui: fix glitch with both ext_cmdline and cmd_wildmenu

### LINKED ISSUE #7689: ext_cmdline and tabbing through results prints dots in message/cmd line
- `nvim --version`: 0.2.2 & 0.2.3-80-ga494c9991
- Vim (version: ) behaves differently?
- Operating system/version: Mac OS 10.12.6
- Terminal name/version: external GUI
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

Set `ext_cmdline: true` when calling `nvim_ui_attach`

I put together a minimal remote-ui implementation demonstrating this behavior in the following repo: https://github.com/deomitrus/nvderp

### Actual behaviour

When using external command line and pressing wildchar (e.g. `nvim_input('<Tab'>)` ) the messages line prints out dots:

### Expected behaviour

I would expect no dots to be printed out.

I'm not sure if i'm missing some option that enables/disables this? Am I doing something wrong? Anything else I can test out? Do I have a bug in both of my remote-ui implementations? Has anyone else observed this while using `ext_cmdline`?

I have tested both in 0.2.2 and master (built at the time of this post). I tried it in my own GUI implementation and in a new repo using only the node neovim library (linked above).

I have only observed this to happen on wildchar triggers. There does not seem to be any difference if wildmenu is set to external or not.

Thoughts?

### PR DESCRIPTION
**Pull request by bfredl**
fixes #7689

### CODE REVIEW

File: test/functional/ui/cmdline_spec.lua [hunk 1]
```diff
@@ -476,50 +489,160 @@ describe('external cmdline', function()
...
+      {EOB:~                        }|
+      {EOB:~                        }|
+      {EOB:~                        }|
+                               |
+    ]], nil, nil, function()
+      expect_cmdline(1, '{RBP1:(}a{RBP2:(}b{RBP2:)}a{RBP1:)}')
+    end)
+  end)
+
+  it('works togheter with ext_wildmenu', function()
```
Comment (jamessan) [inline test/functional/ui/cmdline_spec.lua]: `togheter` -> `together`

File: test/functional/ui/cmdline_spec.lua [hunk 2]
```diff
@@ -476,50 +489,160 @@ describe('external cmdline', function()
...
+      {EOB:~                        }|
+      {EOB:~                        }|
+      {EOB:~                        }|
+                               |
+    ]], nil, nil, function()
+      expect_cmdline(1, '{RBP1:(}a{RBP2:(}b{RBP2:)}a{RBP1:)}')
+    end)
+  end)
+
+  it('works together withr ext_wildmenu', function()
```
Comment (brcolow) [inline test/functional/ui/cmdline_spec.lua]: typo: withr => with
