### PR TITLE
fix(api): check type in nlua_pop_keydict (#15940)

### LINKED ISSUE #15940: Regression: `:lua vim.api.nvim_set_keymap('', '', '', '')` crashes with `LuaJIT ASSERT lj_api.c:921: lua_next: stack slot -2 is not a table`
### Neovim version (nvim -v)

NVIM v0.6.0-dev+424-gc61a3865e

### Vim (not Nvim) behaves the same?

N/A, this is a Lua-specific issue

### Operating system/version

Tested on newly-initialized Ubuntu 20.04 (from Docker), MacOS using home-manager on the unstable channel, and NixOS unstable.

### Terminal name/version

Kitty 0.23.1

### $TERM environment variable

xterm-kitty (but also occurs on xterm-256color)

### Installation

This happens both from nightly (nixpkgs) and when built from repo in a blank environment.

### How to reproduce the issue

Run `nvim`, then type `:lua vim.api.nvim_set_keymap('', '', '', '')`.

### Expected behavior

Not to crash.

### Actual behavior

On a release build, this segfaults; on a debug build, it fails with a LuaJIT error: 
```
LuaJIT ASSERT lj_api.c:921: lua_next: stack slot -2 is not a table
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by virchau13**
This should fix #15940. It just checks the type of the stack before popping it in `nlua_pop_keydict`. There is also a test to check that it works.

### CODE REVIEW

File: src/nvim/lua/converter.c [hunk 1]
```diff
@@ -1303,6 +1303,12 @@ void nlua_init_types(lua_State *const lstate)
 
 void nlua_pop_keydict(lua_State *L, void *retval, field_hash hashy, Error *err)
 {
+  if (!lua_istable(L, -1)) {
+    api_set_error(err, kErrorTypeValidation, "Expected lua table");
+    lua_pop(L, -1);
```
Comment (chernetskyi) [inline src/nvim/lua/converter.c:1308]: Shouldn't this pop only one element?
```suggestion
    lua_pop(L, 1);
```
