### PR TITLE
fix(lsp): stop repeatedly resuming dead coroutine

### LINKED ISSUE #33564: Nightly build breaks C# LSP
### Problem

I have the `omnisharp_mono` LSP installed for C# development (via Mason), and its been working great for the past number of months. I stepped away from C# for a few weeks, and when I returned I was unable to open `.cs` files without neovim freaking out:
```
Error executing callback:                                                                                                                                                                                                                                                 
...nvim-linux-x86_64/share/nvim/runtime/lua/vim/lsp/rpc.lua:195: cannot resume dead coroutine                                                                                                                                                                                     
stack traceback:                                                                                                                                                                                                                                                                  
        [C]: in function 'parse_chunk'                                                                                                                                                                                                                                            
        ...nvim-linux-x86_64/share/nvim/runtime/lua/vim/lsp/rpc.lua:195: in function 'handler'                                                                                                                                                                                    
        ...nvim-linux-x86_64/share/nvim/runtime/lua/vim/_system.lua:172: in function <...nvim-linux-x86_64/share/nvim/runtime/lua/vim/_system.lua:171>
```
I would hit enter, and the error message would just reappear, again and again. It wouldn't actually let me edit the file as I couldn't get past it. I disabled `omnisharp_mono` and the issue went away. So, I thought that was the culprit. Except, Omnisharp hasn't had an update since Dec. 2024, which is before the problem started. So I decided to mess with my LSP config. I stripped all my Omnisharp customization and configuration away until the only thing I was essentially `ensure_installed = { 'omnisharp_mono' }`, but still no cigar.

Now, I use the nightly build of neovim, and keep it up-to-date (update it roughly once a week?). My final troubleshooting step was to revert back to the latest stable neovim release (v0.11.0). Lo-and-behold, it fixed my issue. I've been running fine on stable ever since, even with all my customization/configs.

I don't know enough to say what caused it; but some change between the stable release and the nightly build broke my LSP.
I have the latest versions of all packages/language servers, as well as the latest version of Mono installed on my system.

### Steps to reproduce

Open a `.cs` file with the `omnisharp_mono` LSP installed on the latest nightly build. Observe errors.
Then, using the exact same LSP setup/config, switch to the stable release, open the same file, and see no errors.

I was able to reproduce it with a blank lspconfig that basically only had `ensure_installed = { 'omnisharp_mono' }` in the Mason section, but if it helps, [here is my current lspconfig](https://github.com/Zman350x/nvim-config/blob/main/lua/zman/plugins/lsp/lspconfig.lua).

### Expected behavior

Able to open/edit a `.cs` file without issue, and with a working LSP.

### Nvim version (nvim -v)

v0.12.0-dev-178+gd3cded796c

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

KDE Neon 6.3

### Terminal name/version

konsole 25.04.0

### $TERM environment variable

tmux-256color

### Installation

other, extracting the `.tag.gz` (either nightly or release) into my `/usr/local/bin`

### PR DESCRIPTION
**Pull request by ntdiary**
Problem:
Error extracting content-length causes all future coroutine resumes to
fail.

Solution:
Replace `coroutine.wrap` with `coroutine.create` in `create_read_loop`
so that we can check its status and catch any errors, allowing us to
stop the lsp client and avoid repeatedly resuming the dead coroutine.

close https://github.com/neovim/neovim/issues/33564

### CODE REVIEW

**Comment by justinmk** [comment]
This looks rather specific (`get_content_length` is presumably not the only place where a BOM could cause problems in the LSP layer), but when problems like #33564 happen with unclear symptoms, we should at *minimum* detect and show useful errors. 

So even if there are objections to this PR as it currently is, at least detecting the BOM and showing a useful error is something we should do.

**Comment by ntdiary** [comment]
Hi, sorry it took so long to update, I spent about a month looking deeper into this and some findings might help.  😄

> `get_content_length` is presumably not the only place where a BOM could cause problems in the LSP layer

For issue #33564, BOM only appears once, at the beginning of `stdout` stream and as part of header field name.
I also created [#2691](https://github.com/OmniSharp/omnisharp-roslyn/issues/2691) in `omnisharp-roslyn`. BTW, if I understand [#2647](https://github.com/OmniSharp/omnisharp-roslyn/issues/2647) correctly, once they drop mono and require users to install .NET runtime, this problem will disappear, since the .NET runtime stopped writing BOM to `stdout` [years ago](https://github.com/dotnet/runtime/blob/aed1aadd99f8825f913f9eb862da0bb2f7b74433/src/libraries/Common/src/System/Text/ConsoleEncoding.cs#L19-L20), while mono still does.

> So even if there are objections to this PR as it currently is, at least detecting the BOM and showing a useful error is something we should do.

The latest commit shows a simple message when extracting `Content-Length` fails, terminates the client and stops repeatedly resuming dead coroutine:
```log
LSP[omnisharp_mono]: Error INVALID_SERVER_MESSAGE: "...ary/www/github/neovim/neovim/runtime/lua/vim/lsp/rpc.lua:33: Content-Length not found in header: <feff>Content-Length: 185\r\n"
```

Additionally, I ran simple startup tests for 373 LSP configs in `nvim-lspconfig`, result is
* 366 ✅
* 1 doesn't actually implement lsp (i.e., [statix](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#statix), which only reads file content from stdin and returns diagnostics) 
* 6 ❌

| config | invalid lsp header | repo | last_commit |
|--------|----------|--------|--------|
| [bright_script](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#bright_script) | `[11:30:33:468 PM][LOG  ] prj0 Using config file: "/xxxx/bsconfig.json"\n[11:30:33:470 PM][LOG  ] prj0 Loading 0 plugins for cwd "/xxxx" []\n[11:30:33:475 PM][LOG  ] prj0 Parsing files\n[11:30:33:483 PM][LOG  ] prj0 Parsing files finished. (7.753ms)\n[11:30:33:484 PM][LOG  ] prj0 Validating project\n[11:30:33:484 PM][LOG  ] prj0 Validating project finished. (0.643ms)\nContent-Length: 387\r\n` | [brighterscript](https://github.com/RokuCommunity/brighterscript) | 2 days ago |
| [custom_elements_ls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#custom_elements_ls) | `NODE VERSION:  v22.15.1\nStartup at  2025-10-12T15:38:57.914Z\nInitializing connection\nInitializing documents\nInitializing workspaces.\nInitializing workspace /xxxx @ file:///xxxx\nPackage JSON path  /xxxx/package.json\nContent-Length: 275\r\n` | [custom-elements-language-server](https://github.com/Matsuuu/custom-elements-language-server) | 2 years ago |
| [ltex](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#ltex) | `WARN: no common words file defined for Khmer - this language might not be correctly auto-detected\nWARN: no common words file defined for Japanese - this language might not be correctly auto-detected\nContent-Length: 260\r\n` | [ltex-ls](https://github.com/valentjn/ltex-ls) | 2 years ago |
| [pico8_ls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#pico8_ls) | `PICO-8 Language Server starting.\nPICO-8 Language Server launched.\nContent-Length: 535\r\n` | [pico8-ls](https://github.com/japhib/pico8-ls) | 3 weeks ago |
| [sqlls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#sqlls) | `addCandidatesForFunctions: 0.046ms\ncomplete: 4.274ms\nContent-Length: 36\r\n` | [sql-language-server](https://github.com/joe-re/sql-language-server) | 10 months ago | 
| [pug](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#pug) | `[TODO]: "Is 5 enough?"\nContent-Length: 299\r\n` | [pug-lsp](https://github.com/opa-oz/pug-lsp) | 11 months ago |

The commonality among them is that they all write one or more log lines to `stdout` before the real lsp header, and each ending with `\n`. They may be primarily designed for vscode client, and can work well in its `TransportKind.ipc` mode, but cause header parsing issue in `stdio` mode. My tests were fairly simple, so I’m not sure if other configs might also write log lines to `stdout` in some cases.

If we think the message in this commit is enough and keep strict parsing, then no changes to `get_content_length` are needed. However, if we want to show more specific message (like, `invalid token: <feff>`) or be more lenient by ignoring invalid log lines so these servers can still run, we might need a small header parser function. I’ve also experimented with a rough implementation, which is faster than the current regex, I can provide it later if needed.

File: runtime/lua/vim/lsp/rpc.lua [hunk 1]
```diff
@@ -175,27 +175,34 @@ end
 --- @private
 --- @param handle_body fun(body: string)
 --- @param on_exit? fun()
---- @param on_error fun(err: any)
+--- @param on_error? fun(errkind: vim.lsp.rpc.ClientErrors, err: any)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/rpc.lua]: Technically this is a breaking change. But it's marked as `@private` so not going to worry. But I would probably add `errkind` as the 2nd arg just to avoid accidents.

**Review by justinmk — APPROVED** [review]
Thanks for your analysis, can you include the key parts in your commit message? 

There is an existing test which uses `create_read_loop`, maybe it's not too hard to force a failure to exercise your changes in a test? https://github.com/neovim/neovim/blob/470585b5d063b374bc2efed14a7978b6eabf090c/test/functional/plugin/lsp_spec.lua#L5743

Ideally @mfussenegger can check this too. Will merge in a few days otherwise.

**Review by mfussenegger — APPROVED** [review]
I second https://github.com/neovim/neovim/pull/35743/files#r2462107498 and the request for a test case, otherwise looks okay to me.

I also wouldn't be opposed making the parsing a bit more lenient again and allow the first line to contain some garbage. E.g. one scenario I recently ran into where it also breaks is if you want to debug language servers written in Java with the jdwp agentlib attached. That will also cause an extra line to be printed, and there's no way to suppress that on the JDK/language server side.

**Comment by ntdiary** [comment]
Thanks for your reviews! I learned a lot while writing the test case. I've also briefly summarized the key changes in the commit message. BTW, I initially thought the test below might be related, but after digging into it, I feel it’s outdated, and the validation in `on_handler` is no longer called, It might be safe to remove it in the future?
If there's anything else that needs to be updated, please feel free to let me know. :)
https://github.com/neovim/neovim/blob/29e093c8f262007dd87412cf4a4c47cefef3c963/test/functional/plugin/lsp_spec.lua#L1950-L1970

**Comment by justinmk** [comment]
> BTW, I initially thought the test below might be related, but after digging into it, I feel it’s outdated, and the validation in `on_handler` is no longer called, It might be safe to remove it in the future?

yes that sounds helpful, in a new PR!

> I also wouldn't be opposed making the parsing a bit more lenient again and allow the first line to contain some garbage. E.g. one scenario I recently ran into where it also breaks is if you want to debug language servers written in Java with the jdwp agentlib attached. That will also cause an extra line to be printed, and there's no way to suppress that on the JDK/language server side.

Is that implemented here or should we track it, or do you plan to implement it @ntdiary ?

**Comment by ntdiary** [comment]
> Is that implemented here or should we track it, or do you plan to implement it @ntdiary ?

will try to implement it in a follow PR. 😄
