### PR TITLE
fix(grid): don't use utfc_ptr2char_len() when printing until NUL

### LINKED ISSUE #19447: vim exit from session in multi byte typing
### Neovim version (nvim -v)

NVIM v0.7.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

i dont know realy

### Operating system/version

Linux  5.4.0-121-generic #137-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux

### Terminal name/version

oh-my-posh 7.69.0

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

i install from this wiki : https://github.com/neovim/neovim/wiki/Building-Neovim

### Expected behavior

screenshot : https://ibb.co/94b7NNN

### Actual behavior

when i typing multi byte characters (persian)
"لطفا ادرس کیف پول ..."
the nvim throw error in the curser location and exit from vim 
error was : "nvim: ../src/nvim/mbyte.c:794: utfc_ptr2char_len: Assertion `maxlen > 0' failed."
the view of screen not change just not any more in nvim
my terminal command line was in next line and the nvim view still in terminal

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #19447

### CODE REVIEW

File: src/nvim/grid.c [hunk 1]
```diff
@@ -248,8 +248,11 @@ void grid_puts_len(ScreenGrid *grid, char_u *text, int textlen, int row, int col
         nc = NUL;
         nc1 = NUL;
       } else {
-        nc = utfc_ptr2char_len(ptr + mbyte_blen, pcc,
-                               (int)((text + len) - ptr - mbyte_blen));
+        if (len >= 0) {
+          nc = utfc_ptr2char_len(ptr + mbyte_blen, pcc, (int)((text + len) - ptr - mbyte_blen));
+        } else {
+          nc = utfc_ptr2char(ptr + mbyte_blen, pcc);
```
Comment (justinmk) [inline src/nvim/grid.c:254]: could use a ternary

File: test/functional/ui/statusline_spec.lua [hunk 2]
```diff
@@ -368,3 +368,10 @@ describe('global statusline', function()
     eq(1, meths.get_option('cmdheight'))
   end)
 end)
+
+it('statusline does not crash if it has Arabic characters #19447', function()
+  clear()
+  meths.set_option('statusline', 'غً')
+  meths.set_option('laststatus', 2)
+  command('redraw!')
```
Comment (justinmk) [inline test/functional/ui/statusline_spec.lua:376]: assert_alive ?
