### PR TITLE
fix(tui): do not emit resize screen sequence after host terminal is resized

### LINKED ISSUE #35324: Resize loop in tui
### Problem

I am investigating this user report about neovim in iTerm2: https://gitlab.com/gnachman/iterm2/-/issues/12324#note_2679593924

When nvim is running in two tabs of the same window, they can get into a loop where they repeatedly resize the window. It only occurs when DECSET 2048 was enabled, causing the terminal to send `CSI 48` window resize notifications.

I noticed that `tui_grid_resize` already contains logic to prevent this issue when the window resize notification comes via a SIGWINCH:

https://github.com/neovim/neovim/blob/master/src/nvim/tui/tui.c#L1228

But since the resize notification comes through this path instead:

https://github.com/neovim/neovim/blob/master/src/nvim/tui/input.c#L727

Then `got_winch` is never set to true and it attempts to resize the window in response to the window resize request. 

It looks like `got_winch` was added in 1803b0ffd7f08b50a3f59272ebe7290ffd21e90f for a completely different purpose, accidentally preventing the issue in question until DECSET 48 support was added somewhat recently.

### Steps to reproduce

Per the original user's repro steps (which I was able to replicate):

1. have 2 iterm2 window tabs open, open nvim on them both.
2. have a split pane in one of the window tabs.
3. set the font to SauceCodePro Nerd Font Regular 17

You'll probably need to use their iTerm2 config since it depends on various settings like having window resizing enabled.

### Expected behavior

No resize loops.

### Nvim version (nvim -v)

0.11.0

### Vim (not Nvim) behaves the same?

Didn't test it

### Operating system/version

macOS 15

### Terminal name/version

iTerm2 3.6.0beta1

### $TERM environment variable

xterm-256color

### Installation

homebrew

### PR DESCRIPTION
**Pull request by gpanders**
Some terminals support the CSI 8 t sequence to resize their own window area. Neovim will emit this sequence when the TUI is resized programatically, but it should not be emitted when the TUI is resized because the host terminal was resized, as that results in an infinite resize loop.

Fixes: https://github.com/neovim/neovim/issues/35324

### CODE REVIEW

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -1864,9 +1866,6 @@ void tui_guess_size(TUIData *tui)
 
   tui_set_size(tui, width, height);
 
-  // Redraw on SIGWINCH event if size didn't change. #23411
-  ui_client_set_size(width, height);
```
Comment (justinmk) [inline src/nvim/tui/tui.c:1868]: https://github.com/neovim/neovim/pull/23415 added tests for #23411, which still pass in this PR 👍

**Review by justinmk — APPROVED** [review]
