### PR TITLE
fix(diagnostic): virtual_lines diagnostic columns

### LINKED ISSUE #32694: Virtual line diagnostics are highlighting incorrect column
### Problem

Consider the following Python code:
```py
def bar(x: int, /, y: str, *, z: float): ...
```

Use Pyright language server with `nvim-lspconfig` and you'll get that the diagnostics for unused parameter `y` and `z` are not in the correct column:

Image

When fetching the diagnostic information via `vim.diagnostic.get(0, {lnum = 0})`, the column numbers are:
```
{ {
    col = 8,                                                                                                                                                 
    end_col = 9,                                                                                                                                             
    end_lnum = 0,                                                                                                                                            
    lnum = 0,                                                                                                                                                
    message = '"x" is not accessed',
}, {
    col = 19,                                                                                                                                                
    end_col = 20,                                                                                                                                            
    end_lnum = 0,                                                                                                                                            
    lnum = 0,                                                                                                                                                
    message = '"y" is not accessed',
}, {
    col = 30,                                                                                                                                                
    end_col = 31,                                                                                                                                            
    end_lnum = 0,                                                                                                                                            
    lnum = 0,                                                                                                                                                
    message = '"z" is not accessed',
} }
```

Note: I've omitted diagnostic information which isn't useful in this context.

Navigating the diagnostic does take me to the correct location. Here, I'm using the default <kbd>]d</kbd> and <kbd>[d</kbd> keybindings:

https://github.com/user-attachments/assets/10edcbe4-2461-41a5-9ff7-5ab7de1d9f1b

### Steps to reproduce

Using the following `minimal.lua`:
```lua
-- Run this file as `nvim --clean -u minimal.lua`

for name, url in pairs({
	-- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
	"https://github.com/neovim/nvim-lspconfig",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS _NECESSARY_ FOR REPRODUCING THE ISSUE
vim.diagnostic.config({ virtual_lines = true })

local lspconfig = require("lspconfig")
lspconfig.pyright.setup({})
```

And, the following `t.py` content:
```python
def bar(x: int, /, y: str, *, z: float): ...
```

Open using `nvim --clean -u minimal.lua t.py`

### Expected behavior

Expected the rendering at the correct location.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1887+gb45a44dd3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 15.2

### Terminal name/version

kitty 0.39.1

### $TERM environment variable

xterm-kitty

### Installation

built from source

### PR DESCRIPTION
**Pull request by jamestrew**
When multiple diagnostics appear on a single line, the virtual lines for all diagnostics except the first were rendered with progressively fewer columns.

fixes: https://github.com/neovim/neovim/issues/32694

### CODE REVIEW

File: runtime/lua/vim/diagnostic.lua [hunk 1]
```diff
@@ -1757,8 +1757,7 @@ local function render_virtual_lines(namespace, bufnr, diagnostics)
         string.rep(
           ' ',
           -- +1 because indexing starts at 0 in one API but at 1 in the other.
-          -- -1 for non-first lines, since the previous column was already drawn.
-          distance_between_cols(bufnr, diag.lnum, prev_col + 1, diag.col) - 1
```
Comment (jamestrew) [inline runtime/lua/vim/diagnostic.lua:1761]: Originally a fix for the same issue as the issue my PR aims to fix.
 https://todo.sr.ht/~whynothugo/lsp_lines.nvim/13
https://git.sr.ht/~whynothugo/lsp_lines.nvim/commit/22ef87c

But clearly enough has changed since then that this isn't necessary.

**Review by MariaSolOs — APPROVED** [review]

File: test/functional/lua/diagnostic_spec.lua [hunk 2]
```diff
@@ -2231,6 +2231,110 @@ describe('vim.diagnostic', function()
       eq('Another error there!', result[2][4].virt_lines[1][3][1])
     end)
 
+    it('highlights multiple diagnostics in a single line by default', function()
```
Comment (gpanders) [inline test/functional/lua/diagnostic_spec.lua:2234]:
```suggestion
    it('highlights multiple diagnostics in a single line by default #32694', function()
```

**Comment by gpanders** [comment]
Thanks!
