### PR TITLE
[RDY] vim-patch:8.0.{879,890,1160,1168,1169,1216,1446,1575,1577,1579,1600,1601,1705,1811},8.1.0007

### LINKED ISSUE #2467: heap-use-after-free in win_equal_rec
Hello.

I found a heap-use-after-free bug in vim.

Please confirm.

Thanks.

Summary: heap-use-after-free
OS: CentOS 7 64bit
Version: b254af3
PoC Download:  [free_win_equal_rec.zip](https://github.com/vim/vim/files/1569825/free_win_equal_rec.zip)

Steps to reproduce:
1.Download the .POC files.
2.Compile the source code with ASan.
3.Execute the following command
: ./vim -u NONE -Z -X -e -s -S $POC -c :qa!

```
=================================================================
==21216==ERROR: AddressSanitizer: heap-use-after-free on address 0x60600000c2e0 at pc 0x0000014a6cf1 bp 0x7ffed15aaf70 sp 0x7ffed15aaf68
READ of size 8 at 0x60600000c2e0 thread T0
    #0 0x14a6cf0 in win_equal_rec /home/karas/vim/src/window.c:2046:14
    #1 0x147cad1 in win_equal /home/karas/vim/src/window.c:1767:5
    #2 0x1476bce in win_close /home/karas/vim/src/window.c:2454:2
    #3 0x53f6be in do_arg_all /home/karas/vim/src/buffer.c:5045:4
    #4 0x8727fa in ex_all /home/karas/vim/src/ex_docmd.c:7698:5
    #5 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #6 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #7 0x813fb7 in do_source /home/karas/vim/src/ex_cmds2.c:4411:5
    #8 0x810477 in cmd_source /home/karas/vim/src/ex_cmds2.c:4024:14
    #9 0x810596 in ex_source /home/karas/vim/src/ex_cmds2.c:3999:2
    #10 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #11 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #12 0x82c835 in do_cmdline_cmd /home/karas/vim/src/ex_docmd.c:671:12
    #13 0x1658084 in exe_commands /home/karas/vim/src/main.c:2953:2
    #14 0x1651bc6 in vim_main2 /home/karas/vim/src/main.c:800:2
    #15 0x1642d2d in main /home/karas/vim/src/main.c:429:12
    #16 0x7fcbfc6d882f in __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291
    #17 0x41aaa8 in _start (/home/karas/vim/src/vim+0x41aaa8)

0x60600000c2e0 is located 32 bytes inside of 64-byte region [0x60600000c2c0,0x60600000c300)
freed by thread T0 here:
    #0 0x4baa50 in __interceptor_cfree.localalias.0 (/home/karas/vim/src/vim+0x4baa50)
    #1 0xbf0b8b in vim_free /home/karas/vim/src/misc2.c:1801:2
    #2 0x14abde7 in win_free_mem /home/karas/vim/src/window.c:2571:5
    #3 0x1475d99 in win_close /home/karas/vim/src/window.c:2413:10
    #4 0x53f6be in do_arg_all /home/karas/vim/src/buffer.c:5045:4
    #5 0x8727fa in ex_all /home/karas/vim/src/ex_docmd.c:7698:5
    #6 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #7 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #8 0x813fb7 in do_source /home/karas/vim/src/ex_cmds2.c:4411:5
    #9 0x810477 in cmd_source /home/karas/vim/src/ex_cmds2.c:4024:14
    #10 0x810596 in ex_source /home/karas/vim/src/ex_cmds2.c:3999:2
    #11 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #12 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #13 0x82c835 in do_cmdline_cmd /home/karas/vim/src/ex_docmd.c:671:12
    #14 0x1658084 in exe_commands /home/karas/vim/src/main.c:2953:2
    #15 0x1651bc6 in vim_main2 /home/karas/vim/src/main.c:800:2
    #16 0x1642d2d in main /home/karas/vim/src/main.c:429:12
    #17 0x7fcbfc6d882f in __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291

previously allocated by thread T0 here:
    #0 0x4babd8 in malloc (/home/karas/vim/src/vim+0x4babd8)
    #1 0xbece08 in lalloc /home/karas/vim/src/misc2.c:954:21
    #2 0xbed227 in alloc_clear /home/karas/vim/src/misc2.c:876:9
    #3 0x148e317 in new_frame /home/karas/vim/src/window.c:3513:31
    #4 0x1483b8f in win_split_ins /home/karas/vim/src/window.c:1011:2
    #5 0x146fac5 in win_split /home/karas/vim/src/window.c:744:12
    #6 0x8761b5 in ex_splitview /home/karas/vim/src/ex_docmd.c:8277:14
    #7 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #8 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #9 0x9bc1d0 in apply_autocmds_group /home/karas/vim/src/fileio.c:9719:2
    #10 0x9bdc0c in apply_autocmds_retval /home/karas/vim/src/fileio.c:9296:15
    #11 0x4f64d1 in open_buffer /home/karas/vim/src/buffer.c:353:6
    #12 0x792100 in do_ecmd /home/karas/vim/src/ex_cmds.c:4213:23
    #13 0x540ff9 in do_arg_all /home/karas/vim/src/buffer.c:5139:12
    #14 0x8727fa in ex_all /home/karas/vim/src/ex_docmd.c:7698:5
    #15 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #16 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #17 0x813fb7 in do_source /home/karas/vim/src/ex_cmds2.c:4411:5
    #18 0x810477 in cmd_source /home/karas/vim/src/ex_cmds2.c:4024:14
    #19 0x810596 in ex_source /home/karas/vim/src/ex_cmds2.c:3999:2
    #20 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #21 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #22 0x82c835 in do_cmdline_cmd /home/karas/vim/src/ex_docmd.c:671:12
    #23 0x1658084 in exe_commands /home/karas/vim/src/main.c:2953:2
    #24 0x1651bc6 in vim_main2 /home/karas/vim/src/main.c:800:2
    #25 0x1642d2d in main /home/karas/vim/src/main.c:429:12
    #26 0x7fcbfc6d882f in __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291

SUMMARY: AddressSanitizer: heap-use-after-free /home/karas/vim/src/window.c:2046:14 in win_equal_rec
Shadow bytes around the buggy address:
  0x0c0c7fff9800: fa fa fa fa 00 00 00 00 00 00 00 00 fa fa fa fa
  0x0c0c7fff9810: fd fd fd fd fd fd fd fa fa fa fa fa fd fd fd fd
  0x0c0c7fff9820: fd fd fd fd fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c0c7fff9830: fa fa fa fa fd fd fd fd fd fd fd fa fa fa fa fa
  0x0c0c7fff9840: fd fd fd fd fd fd fd fa fa fa fa fa fd fd fd fd
=>0x0c0c7fff9850: fd fd fd fa fa fa fa fa fd fd fd fd[fd]fd fd fd
  0x0c0c7fff9860: fa fa fa fa fd fd fd fd fd fd fd fa fa fa fa fa
  0x0c0c7fff9870: fd fd fd fd fd fd fd fd fa fa fa fa 00 00 00 00
  0x0c0c7fff9880: 00 00 00 00 fa fa fa fa fd fd fd fd fd fd fd fa
  0x0c0c7fff9890: fa fa fa fa fd fd fd fd fd fd fd fa fa fa fa fa
  0x0c0c7fff98a0: fd fd fd fd fd fd fd fa fa fa fa fa 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==21216==ABORTING
```
=================
[Acknowledgement]
This work was supported by ICT R&D program of MSIP/IITP. [R7518-16-1001, Innovation hub for high Performance Computing]

### LINKED ISSUE #2611: Splitting the window doesn't remove -- VISUAL -- from the status line
Splitting the window returns you to the normal mode but the bottom line still says "-- VISUAL --" until you change the mode again.

Steps to reproduce:
```
$ vim -N -u NONE
ia
b
c
d
<Esc>kkvk<Ctrl+W>v
```

Then do any movement-based action to convince yourself that you are indeed in the normal mode but that the status line still says **-- VISUAL --**.

Replicated with vim version from Homebrew: `brew install vim --HEAD`:
```
[07:37:40 ~]$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  2 2018 19:36:59)
macOS version
Included patches: 1-1451
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python            +vreplace
+conceal           +linebreak         -python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               +ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.5.0 -lobjc
```

### PR DESCRIPTION
**Pull request by janlazo**
**vim-patch:8.0.0879: crash when shifting with huge number**

Problem:    Crash when shifting with huge number.
Solution:   Check for overflow. (Dominique Pelle, closes vim/vim#1945)
vim/vim@bae5a17

**vim-patch:8.0.0890: still many old style tests**

Problem:    Still many old style tests.
Solution:   Convert several tests to new style. (Yegappan Lakshmanan)
https://github.com/vim/vim/commit/75373f38087dd756babdbbf9f14fd4711712c5de

**vim-patch:8.0.1160: getting tab-local variable fails after closing window**

Problem:    Getting tab-local variable fails after closing window.
Solution:   set tp_firstwin and tp_lastwin. (Jason Franklin, closes vim/vim#2170)
vim/vim@816968d

**vim-patch:8.0.1168: wrong highlighting with combination of match and 'cursorline'**

Problem:    wrong highlighting with combination of match and 'cursorline'.
Solution:   Use "line_attr" when appropriate. (Ozaki Kiichi, closes vim/vim#2111)
            But don't highlight more than one character.
vim/vim@0aa398f

**vim-patch:8.0.1169: highlignting one char too many with 'list' and 'cul'**

Problem:    Highlignting one char too many with 'list' and 'cul'.
Solution:   Check for 'list' being active. (Ozaki Kiichi, closes vim/vim#2177)
vim/vim@5ece3e3

**vim-patch:8.0.1216: tabline is not always updated for :file command**

Problem:    Tabline is not always updated for :file command. (Norio Takagi)
Solution:   Set redraw_tabline. (Hirohito Higashi)
vim/vim@6ce6504

**vim-patch:8.0.1446: acessing freed memory after window command in auto command**

Problem:    Acessing freed memory after window command in auto command.
            (gy741)
Solution:   Adjust the pointer in the parent frame. (Christian Brabandt,
            closes vim/vim#2467)
vim/vim@6f361c9

**vim-patch:8.0.1575: crash when using virtual replace**

Problem:    Crash when using virtual replace.
Solution:   Adjust orig_line_count.  Add more tests. (Christian Brabandt)
vim/vim@63e82db

**vim-patch:8.0.1577: virtual replace test fails on MS-Windows**

Problem:    Virtual replace test fails on MS-Windows.
Solution:   Make adding a termcap entry work for a builtin terminal.
            Restore terminal keys in a better way.
vim/vim@e780848

**vim-patch:8.0.1579: virtual replace test fails in GUI**

Problem:    Virtual replace test fails in GUI.
Solution:   Don't save key options if they were not set.
vim/vim@df0d24b

**vim-patch:8.0.1600: crash when setting t_Co to zero when 'termguicolors' is set**

Problem:    Crash when setting t_Co to zero when 'termguicolors' is set.
Solution:   Use IS_CTERM instead of checking the number of colors.
            (closes vim/vim#2710)
vim/vim@f708ac5

**vim-patch:8.0.1601: highlight test fails on Win32**

Problem:    Highlight test fails on Win32.
Solution:   Check for vtp and vcon support.
vim/vim@ff1e879

**vim-patch:8.0.1705: when making a vertical split the mode message isn't updated**

Problem:    When making a vertical split the mode message isn't always
            updated, "VISUAL" remains. (Alexei Averchenko)
Solution:   Only reset clear_cmdline when filling all columns of the last
            screen line. (Tom M. closes vim/vim#2611)
vim/vim@5bab555

**vim-patch:8.0.1811: no test for winrestcmd()**

Problem:    No test for winrestcmd().
Solution:   Add a test. (Dominique Pelle, closes vim/vim#2894)
vim/vim@72cf47a

**vim-patch:8.1.0007: no test for "o" and "O" in Visual block mode**

Problem:    No test for "o" and "O" in Visual block mode.
Solution:   Add a test. (Dominique Pelle, closes vim/vim#2932)
vim/vim@2e94976

I separated 8.0.0890 from https://github.com/neovim/neovim/pull/8742 to focus on patches for `test_highlight.vim` and `test_getvar.vim`. I thought 8.0.0890 needed earlier patches but nvim doesn't support `highlight xxx term=bold` (`term=` is noop).

### CODE REVIEW

**Comment by janlazo** [comment]
I'm done with patches for `test_highlight.vim` and `test_getvar.vim` so it's ready for review.

**Comment by janlazo** [comment]
Done with `test_visual.vim`. Next is `test_window.cmd.vim`.

**Comment by janlazo** [comment]
Unless I touched a TriState variable in https://github.com/neovim/neovim/pull/8749, I'd want this merged before https://github.com/neovim/neovim/pull/8749 or my other PRs.

**Comment by janlazo** [comment]
Ping.

File: src/nvim/edit.c [hunk 1]
```diff
@@ -7475,17 +7475,23 @@ static void ins_shift(int c, int lastc)
...
-  int temp;
-
-  if (stop_arrow() == FAIL)
+  if (stop_arrow() == FAIL) {
     return;
-  if (gchar_cursor() == NUL) {          /* delete newline */
-    temp = curwin->w_cursor.col;
+  }
+  if (gchar_cursor() == NUL) {          // delete newline
+    const int temp = curwin->w_cursor.col;
```
Comment (justinmk) [inline src/nvim/edit.c]: This may add friction later if a vim patch mutates the variable. That's another reason why we generally don't do this.

File: src/nvim/eval.c [hunk 2]
```diff
@@ -10210,25 +10210,26 @@ static void f_gettabinfo(typval_T *argvars, typval_T *rettv, FunPtr fptr)
...
-  dictitem_T  *v;
+  tabpage_T *oldtabpage;
   bool done = false;
 
   rettv->v_type = VAR_STRING;
   rettv->vval.v_string = NULL;
 
   const char *const varname = tv_get_string_chk(&argvars[1]);
-  tp = find_tabpage((int)tv_get_number_chk(&argvars[0], NULL));
+  tabpage_T *const tp = find_tabpage((int)tv_get_number_chk(&argvars[0], NULL));
```
Comment (justinmk) [inline src/nvim/eval.c]: `f_gettabvar` is something we just don't change very much. It's maintained by Vim. It's better not to `const` stuff in vim-maintained code, I think.

**Comment by justinmk** [comment]
quickbuild linux has an unusual error, might want to tickle it again:

```
13:34:20,108 INFO  - not ok 924 - system() with output containing NULs replaces NULs by SOH characters
13:34:20,108 INFO  - # test/functional/eval/system_spec.lua @ 359
13:34:20,108 INFO  - # Failure message: test/functional/eval/system_spec.lua:360: Expected objects to be the same.
13:34:20,108 INFO  - # Passed in:
13:34:20,108 INFO  - # (string) '
13:34:20,108 INFO  - # 123456789
13:34:20,108 INFO  - # '
13:34:20,108 INFO  - # Expected:
13:34:20,108 INFO  - # (string) 'part1part2part3
13:34:20,108 INFO  - # '
13:34:20,108 INFO  - # stack traceback:
13:34:20,108 INFO  - # 	test/functional/eval/system_spec.lua:360: in function <test/functional/eval/system_spec.lua:359>
13:34:20,108 INFO  - # 
```

File: src/nvim/eval.c (hunk 2 above)
Comment (janlazo) [reply src/nvim/eval.c]: Isn't it suppose to be the other way around because we don't change it much? It's a constant pointer as of master. I'll get back to it anyway in a later patch.

File: src/nvim/edit.c (hunk 1 above)
Comment (janlazo) [reply src/nvim/edit.c]: The main intent is to `int temp = ...` on the same line. `const` is a bonus.

I keep doing these things because there's too many variables at the top level when they shouldn't be and some functions are very long, sometimes with `#ifdef`, such as patch 8.0.0685. I would expect loop variables to be local to its `for` loop scope but it rarely happens. There are helpers functions but they don't have `const` so I still have to go through each line when debugging. `const` is half-baked but it's preferable to note as many invariants as possible, especially on cleanup and if `goto` is used, like 8.0.0493.

I like to `const` the pointer contents as well but it's hard to add it on a non-constant pointer; it could be passed to another variable or its address could be passed to a function via `&`. Think of local `const` as in-between step so that it's safer to `const` all the way across callers.

**Comment by justinmk** [comment]
latest quickbuild failure looks like a msgpack error, probably unrelated. So this is ready?

**Comment by janlazo** [comment]
It's been ready for awhile (even before #8749 for `TriState`) . I was making cosmetic changes to restart the build on master.

**Comment by janlazo** [comment]
@justinmk Thanks.
