### PR TITLE
os/fs: introduce os_fopen()

### LINKED ISSUE #10586: E484: Can't open file with non-latin chars
Hello! Thanks for the great neovim

- `nvim --version`:

> NVIM v0.3.8
> Build type: RelWithDebInfo
> LuaJIT 2.0.5
> Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
> Compiled by appveyor@APPVYR-WIN
> 
> Features: -acl +iconv -jemalloc +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM\sysinit.vim"
>   fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
> 
> Run :checkhealth for more info

- `vim -u DEFAULTS` (version: ) behaves differently?

The same

- Operating system/version:
Windows 8.1 6.3.9600 N/A Build 9600

- Terminal name/version:
The same on: cmder.exe, cmd.exe, powershell.exe

### Steps to reproduce using `nvim -u NORC`
```
1. Open cmd.exe
2. Run `nvim -u DEFAULTS` (which is empty)
3. Type: `:call readfile('C:\Users\wild\Desktop\testwiki\тест.md')`  
```
(Step 3 updated: it was 'readline')

### Actual behaviour
Message: "E484: Can't open file C:/Users/wild/Desktop/testwiki/тест.md"

### Expected behaviour
No such message. It works if run for test.md

### PR DESCRIPTION
**Pull request by justinmk**
Windows: Using fopen() directly may need UTF-16 filepath conversion. To achieve that, os_fopen() goes through os_open().

fix #10586

- [x] docstring
- [x] test
- [x] remove mch_fopen macro
- [ ] factor out `os_fs_fopen2open_flags()` ?

### CODE REVIEW

File: src/nvim/os/fs.c [hunk 1]
```diff
@@ -429,6 +430,64 @@ int os_open(const char *path, int flags, int mode)
...
+      case 'a':
+        iflags = O_RDWR | O_CREAT | O_APPEND;
+        break;
+      default:
+        abort();
+    }
+  }
+  // Per open(2) manpage.
+  assert((iflags|O_RDONLY) || (iflags|O_WRONLY) || (iflags|O_RDWR));
+  int fd = os_open(path, iflags, 0666);
```
Comment (bfredl) [inline src/nvim/os/fs.c]: seems `os_open` will return negative value on error. Perhaps explicitly return NULL then?

Comment (justinmk) [reply src/nvim/os/fs.c]: For reference: returning NULL is enough, because all existing calls to `mch_fopen` don't check `errno`.
