### PR TITLE
fix(api)!: nvim_parse_cmd omit "count" "range" "reg" if not supported

### LINKED ISSUE #20051: Make result of `nvim_parse_cmd` usable directly by `nvim_cmd`
### Feature already in Vim?

_No response_

### Feature description

For some fields, `nvim_parse_cmd` returns a value that is invalid for `nvim_cmd` if the command does not support that field or that field is not specified, so passing the result of `nvim_parse_cmd` to `nvim_cmd` will lead to an error. For example:
```lua
vim.api.nvim_cmd(vim.api.nvim_parse_cmd('echo', {}), {})
```
leads to `Command cannot accept a range`.

There are two ways to make this better:
1. Make `nvim_parse_cmd` omit some fields if they are not specified. This will, however, lead to inconsistency with `nvim_create_user_command`.
2. Make `nvim_cmd` ignore some fields if they have the default value returned by `nvim_parse_cmd`.

Related: <https://github.com/neovim/neovim/pull/20039#issuecomment-1234421987>

### PR DESCRIPTION
**Pull request by zeertzjq**
Close #20051

### CODE REVIEW

File: src/nvim/api/command.c [hunk 1]
```diff
@@ -149,8 +149,6 @@ Dictionary nvim_parse_cmd(String str, Dictionary opts, Error *err)
     }
     ADD(range, INTEGER_OBJ(ea.line2));
     PUT(result, "range", ARRAY_OBJ(range));
-  } else {
-    PUT(result, "range", ARRAY_OBJ(ARRAY_DICT_INIT));
```
Comment (zeertzjq) [inline src/nvim/api/command.c:153]: Another approach is to use an empty array if range is not specified, but omit if cannot cannot accept a range. Will this be better (e.g. more consistent with when `count` is present and allows telling whether command supports a range)?

**Comment by justinmk** [comment]
cc @famiu

File: src/nvim/api/command.c (hunk 1 above)
Comment (famiu) [reply src/nvim/api/command.c:153]: I think that would be better, yes

File: src/nvim/api/command.c [hunk 2]
```diff
@@ -31,14 +31,15 @@
...
-///                          specified and two elements if both range items were specified.
-///         - count: (number) Any |<count>| that was supplied to the command. -1 if command cannot
-///                           take a count.
-///         - reg: (string) The optional command |<register>|, if specified. Empty string if not
-///                         specified or if command cannot take a register.
+///         - range: (optional) (array) Command |<range>|. Omitted if command doesn't accept a range
+///                                     or if no range was specified.  Otherwise, has no elements if
+///                                     no range was specified, one element if only a single range
+///                                     item was specified, or two elements if both range items were
+///                                     specified.
```
Comment (famiu) [inline src/nvim/api/command.c:38]:
```suggestion
///         - range: (optional) (array) Command |<range>|. Omitted if command doesn't accept a range.
///                                     Otherwise, has no elements if no range was specified, one element if only
///                                     a single range item was specified, or two elements if both range items were
///                                     specified.
```

File: src/nvim/api/command.c [hunk 3]
```diff
@@ -142,15 +143,17 @@ Dictionary nvim_parse_cmd(String str, Dictionary opts, Error *err)
...
+    if (ea.addr_count > 0) {
+      Array range = ARRAY_DICT_INIT;
+      if (ea.addr_count > 1) {
+        ADD(range, INTEGER_OBJ(ea.line1));
+      }
+      ADD(range, INTEGER_OBJ(ea.line2));
+      PUT(result, "range", ARRAY_OBJ(range));
+    } else {
+      PUT(result, "range", ARRAY_OBJ(ARRAY_DICT_INIT));
     }
```
Comment (famiu) [inline src/nvim/api/command.c:156]:
```suggestion
    Array range = ARRAY_DICT_INIT;
    if (ea.addr_count > 0) {
      if (ea.addr_count > 1) {
        ADD(range, INTEGER_OBJ(ea.line1));
      }
      ADD(range, INTEGER_OBJ(ea.line2));
    }
    PUT(result, "range", ARRAY_OBJ(range));
```

**Review by famiu — CHANGES_REQUESTED** [review]

**Review by famiu — APPROVED** [review]

File: runtime/doc/api.txt [hunk 4]
```diff
@@ -1805,15 +1805,14 @@ nvim_parse_cmd({str}, {opts})                               *nvim_parse_cmd()*
     Return: ~
         Dictionary containing command information, with these keys:
         • cmd: (string) Command name.
-        • range: (array) Command <range>. Can have 0-2 elements depending on
```
Comment (zeertzjq) [inline runtime/doc/api.txt:1808]: Using `<range>` is a bit misleading here as `<range>` is the number of items in the range.

Comment (famiu) [reply runtime/doc/api.txt:1808]: Should just change it to "range" then
