### PR TITLE
vim-patch:8.1.{475,800,868,1007,1027,1031,1033,1037,1058,1435,1484,1485}

### LINKED ISSUE #3835: memory leak when assigning a:000 to a local variable
It seems as though reference counting is done incorrectly for `a:000` and memory is leaked when local references are made to it.

To reproduce:

```vim
function s:dofoo(first, ...)
	let l:opts = a:000
	" unlet l:opts 
endfunction

for x in range(10000)
	call s:dofoo(10)
endfor
```

Run `watch 'cat /proc/$(pgrep vim | tail -1)/status | grep Vm'` and `vim --clean test.vim`

Repeatedly do `:so %` and watch the VmRSS shoot up rapidly.  Uncomment the `unlet` and the problem disappears.

Originally reported at https://github.com/vim-airline/vim-airline/issues/1858 ,  https://github.com/vim-airline/vim-airline/pull/1859

### LINKED ISSUE #3894: Vim 8.1.800+ repeatable crash/lockup due to `heap-use-after-free`
Vim 8.1.800 and later exhibit crashes and lockups under repeatable conditions explained below.  Patch 8.1.800 introduced code to invoke `garbage_collect` every 10,000 times a copy is made.  Under certain patterns of Vimscript usage, this leads to crashes.

The bug can be triggered using some test code unknowingly written by Christian Brabant (that is, a particular version of his vim-airline plugin triggers the crashing).

# To reproduce the crash

- Prepare a suitable Linux environment (I'm using Ubuntu 18.04 on x86_64, but presumably others would work as well).

- Setup a clean user environment with the particular version of vim-airline as the only content:

```sh
mv ~/.vimrc ~/orig.vimrc
mv ~/.vim ~/orig.vim
git clone https://github.com/vim-airline/vim-airline ~/.vim
cd ~/.vim
git checkout c7fb175
```

- Checkout the most recent Vim source (tested in this ticket using 8.1.0867):

```sh
git clone https://github.com/vim/vim ~/vim
cd ~/vim
```

- Apply the following patch in the Makefile to turn on the address sanitizer:

```diff
diff --git a/src/Makefile b/src/Makefile
index 3f5418456..639f6370b 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -690,7 +690,7 @@ LINT_OPTIONS = -beprxzF
 # address sanitizer or with the undefined sanitizer.  Works with gcc and
 # clang.  May make Vim twice as slow.  Errors reported on stderr.
 # More at: https://code.google.com/p/address-sanitizer/
-#SANITIZER_CFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer
+SANITIZER_CFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer
 #SANITIZER_CFLAGS = -g -O0 -fsanitize=undefined -fno-omit-frame-pointer
 SANITIZER_LIBS = $(SANITIZER_CFLAGS)
```

- Apply the following patch to make the garbage collector run after every copy instead of every 10,000 copies to trigger the bug more rapidly:

```diff
diff --git a/src/userfunc.c b/src/userfunc.c
index aae3fd334..a54361c42 100644
--- a/src/userfunc.c
+++ b/src/userfunc.c
@@ -675,7 +675,7 @@ cleanup_function_call(funccall_T *fc)
        for (li = fc->l_varlist.lv_first; li != NULL; li = li->li_next)
            copy_tv(&li->li_tv, &li->li_tv);

-	if (++made_copy == 10000)
+	if (++made_copy == 1)
        {
            // We have made a lot of copies.  This can happen when
            // repetitively calling a function that creates a reference to
```

- Configure and build Vim:

```sh
./configure
make
```

- Invoke Vim; it should abort during startup and write debugging information to stderr.  Reset the terminal afterward (necessary on my machine, at least):

```sh
./src/vim 2> crash.txt; reset; cat crash.txt
```

- Examine the crash output; it should look similar to sample shown at the bottom of this ticket.

I haven't tried to figure out what is special about the version of vim-airline that allows it to trigger the bug.  The HEAD revision of vim-airline doesn't seem to crash (at least, not at Vim startup).

# Sample crash.txt output

```
=================================================================
==27891==ERROR: AddressSanitizer: heap-use-after-free on address 0x60700001ea58 at pc 0x55cc0fe49b0f bp 0x7ffc019565e0 sp 0x7ffc019565d0
READ of size 4 at 0x60700001ea58 thread T0
    #0 0x55cc0fe49b0e in copy_tv /home/drmikehenry/vim/src/eval.c:8140
    #1 0x55cc0fe48cbc in set_var /home/drmikehenry/vim/src/eval.c:7947
    #2 0x55cc0fe2d20b in set_var_lval /home/drmikehenry/vim/src/eval.c:2343
    #3 0x55cc0fe298d4 in ex_let_one /home/drmikehenry/vim/src/eval.c:1825
    #4 0x55cc0fe26e68 in ex_let_vars /home/drmikehenry/vim/src/eval.c:1304
    #5 0x55cc0fe2f86a in next_for_item /home/drmikehenry/vim/src/eval.c:2690
    #6 0x55cc0ff232ef in ex_while /home/drmikehenry/vim/src/ex_eval.c:1097
    #7 0x55cc0fee7f37 in do_one_cmd /home/drmikehenry/vim/src/ex_docmd.c:2520
    #8 0x55cc0fedf44f in do_cmdline /home/drmikehenry/vim/src/ex_docmd.c:1033
    #9 0x55cc1030719a in call_user_func /home/drmikehenry/vim/src/userfunc.c:967
    #10 0x55cc10309a27 in call_func /home/drmikehenry/vim/src/userfunc.c:1501
    #11 0x55cc10304829 in get_func_tv /home/drmikehenry/vim/src/userfunc.c:455
    #12 0x55cc10314649 in ex_call /home/drmikehenry/vim/src/userfunc.c:3184
    #13 0x55cc0fee7f37 in do_one_cmd /home/drmikehenry/vim/src/ex_docmd.c:2520
    #14 0x55cc0fedf44f in do_cmdline /home/drmikehenry/vim/src/ex_docmd.c:1033
    #15 0x55cc1030719a in call_user_func /home/drmikehenry/vim/src/userfunc.c:967
    #16 0x55cc10309a27 in call_func /home/drmikehenry/vim/src/userfunc.c:1501
    #17 0x55cc10304829 in get_func_tv /home/drmikehenry/vim/src/userfunc.c:455
    #18 0x55cc10314649 in ex_call /home/drmikehenry/vim/src/userfunc.c:3184
    #19 0x55cc0fee7f37 in do_one_cmd /home/drmikehenry/vim/src/ex_docmd.c:2520
    #20 0x55cc0fedf44f in do_cmdline /home/drmikehenry/vim/src/ex_docmd.c:1033
    #21 0x55cc1030719a in call_user_func /home/drmikehenry/vim/src/userfunc.c:967
    #22 0x55cc10309a27 in call_func /home/drmikehenry/vim/src/userfunc.c:1501
    #23 0x55cc10304829 in get_func_tv /home/drmikehenry/vim/src/userfunc.c:455
    #24 0x55cc10314649 in ex_call /home/drmikehenry/vim/src/userfunc.c:3184
    #25 0x55cc0fee7f37 in do_one_cmd /home/drmikehenry/vim/src/ex_docmd.c:2520
    #26 0x55cc0fedf44f in do_cmdline /home/drmikehenry/vim/src/ex_docmd.c:1033
    #27 0x55cc1030719a in call_user_func /home/drmikehenry/vim/src/userfunc.c:967
    #28 0x55cc10309a27 in call_func /home/drmikehenry/vim/src/userfunc.c:1501
    #29 0x55cc10304829 in get_func_tv /home/drmikehenry/vim/src/userfunc.c:455
    #30 0x55cc10314649 in ex_call /home/drmikehenry/vim/src/userfunc.c:3184
    #31 0x55cc0fee7f37 in do_one_cmd /home/drmikehenry/vim/src/ex_docmd.c:2520
    #32 0x55cc0fedf44f in do_cmdline /home/drmikehenry/vim/src/ex_docmd.c:1033
    #33 0x55cc1030719a in call_user_func /home/drmikehenry/vim/src/userfunc.c:967
    #34 0x55cc10309a27 in call_func /home/drmikehenry/vim/src/userfunc.c:1501
    #35 0x55cc10304829 in get_func_tv /home/drmikehenry/vim/src/userfunc.c:455
    #36 0x55cc10314649 in ex_call /home/drmikehenry/vim/src/userfunc.c:3184
    #37 0x55cc0fee7f37 in do_one_cmd /home/drmikehenry/vim/src/ex_docmd.c:2520
    #38 0x55cc0fedf44f in do_cmdline /home/drmikehenry/vim/src/ex_docmd.c:1033
    #39 0x55cc1030719a in call_user_func /home/drmikehenry/vim/src/userfunc.c:967
    #40 0x55cc10309a27 in call_func /home/drmikehenry/vim/src/userfunc.c:1501
    #41 0x55cc10304829 in get_func_tv /home/drmikehenry/vim/src/userfunc.c:455
    #42 0x55cc10314649 in ex_call /home/drmikehenry/vim/src/userfunc.c:3184
    #43 0x55cc0fee7f37 in do_one_cmd /home/drmikehenry/vim/src/ex_docmd.c:2520
    #44 0x55cc0fedf44f in do_cmdline /home/drmikehenry/vim/src/ex_docmd.c:1033
    #45 0x55cc0fdaea40 in apply_autocmds_group /home/drmikehenry/vim/src/autocmd.c:2072
    #46 0x55cc0fdad3a6 in apply_autocmds_retval /home/drmikehenry/vim/src/autocmd.c:1622
    #47 0x55cc0fdb51a4 in open_buffer /home/drmikehenry/vim/src/buffer.c:332
    #48 0x55cc103f8577 in create_windows /home/drmikehenry/vim/src/main.c:2746
    #49 0x55cc103f172b in vim_main2 /home/drmikehenry/vim/src/main.c:736
    #50 0x55cc103f0eeb in main /home/drmikehenry/vim/src/main.c:441
    #51 0x7fa5e7e72b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #52 0x55cc0fda5e79 in _start (/home/drmikehenry/vim/src/vim+0x111e79)

0x60700001ea58 is located 56 bytes inside of 80-byte region [0x60700001ea20,0x60700001ea70)
freed by thread T0 here:
    #0 0x7fa5eb1577b8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8)
    #1 0x55cc10030126 in vim_free /home/drmikehenry/vim/src/misc2.c:1817
    #2 0x55cc0ffd4772 in list_free_list /home/drmikehenry/vim/src/list.c:208
    #3 0x55cc0ffd484b in list_free_items /home/drmikehenry/vim/src/list.c:225
    #4 0x55cc0fe3d5fd in free_unref_items /home/drmikehenry/vim/src/eval.c:5503
    #5 0x55cc0fe3d4f8 in garbage_collect /home/drmikehenry/vim/src/eval.c:5449
    #6 0x55cc10305673 in cleanup_function_call /home/drmikehenry/vim/src/userfunc.c:685
    #7 0x55cc10307e72 in call_user_func /home/drmikehenry/vim/src/userfunc.c:1066
    #8 0x55cc10309a27 in call_func /home/drmikehenry/vim/src/userfunc.c:1501
    #9 0x55cc10304829 in get_func_tv /home/drmikehenry/vim/src/userfunc.c:455
    #10 0x55cc0fe37926 in eval7 /home/drmikehenry/vim/src/eval.c:4382
    #11 0x55cc0fe35e64 in eval6 /home/drmikehenry/vim/src/eval.c:3985
    #12 0x55cc0fe35017 in eval5 /home/drmikehenry/vim/src/eval.c:3781
    #13 0x55cc0fe34773 in eval4 /home/drmikehenry/vim/src/eval.c:3665
    #14 0x55cc0fe34307 in eval3 /home/drmikehenry/vim/src/eval.c:3585
    #15 0x55cc0fe33e65 in eval2 /home/drmikehenry/vim/src/eval.c:3517
    #16 0x55cc0fe338ee in eval1 /home/drmikehenry/vim/src/eval.c:3445
    #17 0x55cc0fe335f3 in eval0 /home/drmikehenry/vim/src/eval.c:3403
    #18 0x55cc0fe26afe in ex_let /home/drmikehenry/vim/src/eval.c:1260
    #19 0x55cc0fee7f37 in do_one_cmd /home/drmikehenry/vim/src/ex_docmd.c:2520
    #20 0x55cc0fedf44f in do_cmdline /home/drmikehenry/vim/src/ex_docmd.c:1033
    #21 0x55cc1030719a in call_user_func /home/drmikehenry/vim/src/userfunc.c:967
    #22 0x55cc10309a27 in call_func /home/drmikehenry/vim/src/userfunc.c:1501
    #23 0x55cc10304829 in get_func_tv /home/drmikehenry/vim/src/userfunc.c:455
    #24 0x55cc10314649 in ex_call /home/drmikehenry/vim/src/userfunc.c:3184
    #25 0x55cc0fee7f37 in do_one_cmd /home/drmikehenry/vim/src/ex_docmd.c:2520
    #26 0x55cc0fedf44f in do_cmdline /home/drmikehenry/vim/src/ex_docmd.c:1033
    #27 0x55cc1030719a in call_user_func /home/drmikehenry/vim/src/userfunc.c:967
    #28 0x55cc10309a27 in call_func /home/drmikehenry/vim/src/userfunc.c:1501
    #29 0x55cc10304829 in get_func_tv /home/drmikehenry/vim/src/userfunc.c:455

previously allocated by thread T0 here:
    #0 0x7fa5eb157b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x55cc1002ddce in lalloc /home/drmikehenry/vim/src/misc2.c:944
    #2 0x55cc1002dc41 in alloc_clear /home/drmikehenry/vim/src/misc2.c:853
    #3 0x55cc0ffd40b1 in list_alloc /home/drmikehenry/vim/src/list.c:75
    #4 0x55cc0fddd6ae in dict_list /home/drmikehenry/vim/src/dict.c:875
    #5 0x55cc0fe765ad in f_items /home/drmikehenry/vim/src/evalfunc.c:7393
    #6 0x55cc0fe58535 in call_internal_func /home/drmikehenry/vim/src/evalfunc.c:1117
    #7 0x55cc10309b7f in call_func /home/drmikehenry/vim/src/userfunc.c:1520
    #8 0x55cc10304829 in get_func_tv /home/drmikehenry/vim/src/userfunc.c:455
    #9 0x55cc0fe37926 in eval7 /home/drmikehenry/vim/src/eval.c:4382
    #10 0x55cc0fe35e64 in eval6 /home/drmikehenry/vim/src/eval.c:3985
    #11 0x55cc0fe35017 in eval5 /home/drmikehenry/vim/src/eval.c:3781
    #12 0x55cc0fe34773 in eval4 /home/drmikehenry/vim/src/eval.c:3665
    #13 0x55cc0fe34307 in eval3 /home/drmikehenry/vim/src/eval.c:3585
    #14 0x55cc0fe33e65 in eval2 /home/drmikehenry/vim/src/eval.c:3517
    #15 0x55cc0fe338ee in eval1 /home/drmikehenry/vim/src/eval.c:3445
    #16 0x55cc0fe335f3 in eval0 /home/drmikehenry/vim/src/eval.c:3403
    #17 0x55cc0fe2efd6 in eval_for_line /home/drmikehenry/vim/src/eval.c:2608
    #18 0x55cc0ff231c7 in ex_while /home/drmikehenry/vim/src/ex_eval.c:1091
    #19 0x55cc0fee7f37 in do_one_cmd /home/drmikehenry/vim/src/ex_docmd.c:2520
    #20 0x55cc0fedf44f in do_cmdline /home/drmikehenry/vim/src/ex_docmd.c:1033
    #21 0x55cc1030719a in call_user_func /home/drmikehenry/vim/src/userfunc.c:967
    #22 0x55cc10309a27 in call_func /home/drmikehenry/vim/src/userfunc.c:1501
    #23 0x55cc10304829 in get_func_tv /home/drmikehenry/vim/src/userfunc.c:455
    #24 0x55cc10314649 in ex_call /home/drmikehenry/vim/src/userfunc.c:3184
    #25 0x55cc0fee7f37 in do_one_cmd /home/drmikehenry/vim/src/ex_docmd.c:2520
    #26 0x55cc0fedf44f in do_cmdline /home/drmikehenry/vim/src/ex_docmd.c:1033
    #27 0x55cc1030719a in call_user_func /home/drmikehenry/vim/src/userfunc.c:967
    #28 0x55cc10309a27 in call_func /home/drmikehenry/vim/src/userfunc.c:1501
    #29 0x55cc10304829 in get_func_tv /home/drmikehenry/vim/src/userfunc.c:455

SUMMARY: AddressSanitizer: heap-use-after-free /home/drmikehenry/vim/src/eval.c:8140 in copy_tv
Shadow bytes around the buggy address:
  0x0c0e7fffbcf0: fd fd fd fd fd fd fd fd fd fa fa fa fa fa 00 00
  0x0c0e7fffbd00: 00 00 00 00 00 00 02 fa fa fa fa fa fd fd fd fd
  0x0c0e7fffbd10: fd fd fd fd fd fa fa fa fa fa 00 00 00 00 00 00
  0x0c0e7fffbd20: 00 00 02 fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c0e7fffbd30: 00 00 fa fa fa fa 00 00 00 00 00 00 00 00 00 00
=>0x0c0e7fffbd40: fa fa fa fa fd fd fd fd fd fd fd[fd]fd fd fa fa
  0x0c0e7fffbd50: fa fa fd fd fd fd fd fd fd fd fd fd fa fa fa fa
  0x0c0e7fffbd60: fd fd fd fd fd fd fd fd fd fd fa fa fa fa fd fd
  0x0c0e7fffbd70: fd fd fd fd fd fd fd fd fa fa fa fa fd fd fd fd
  0x0c0e7fffbd80: fd fd fd fd fd fd fa fa fa fa fd fd fd fd fd fd
  0x0c0e7fffbd90: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==27891==ABORTING
```

### PR DESCRIPTION
**Pull request by erw7**
- [x] vim-patch:8.1.1485
- [x] vim-patch:8.1.1536
- [ ] ~vim-patch:8.1.1575~
- [ ] ~vim-patch:8.1.1583~

**vim-patch:8.1.0475: memory not freed on exit when quit in autocmd**
Problem:    Memory not freed on exit when quit in autocmd.
Solution:   Remember funccal stack when executing autocmd.
https://github.com/vim/vim/commit/27e80c885bcb5c5cf6a6462d71d6c81b06ba2451

**vim-patch:8.1.0800: may use a lot of memory when a function refers itself**
Problem:    May use a lot of memory when a function creates a cyclic reference.
Solution:   After saving a funccal many times, invoke the garbage collector. (closes vim/vim#3835)
vim/vim@4456ab5

**vim-patch:8.1.0868: crash if triggering garbage collector after a function call**
Problem:    Crash if triggering garbage collector after a function call. (Michael Henry)
Solution:   Don't call the garbage collector right away, do it later. (closes vim/vim#3894)
vim/vim@889da2f

**vim-patch:8.1.1007: using closure may consume a lot of memory**
Problem:    Using closure may consume a lot of memory.
Solution:   unreference items that are no longer needed. Add a test. (Ozaki Kiichi, closes vim/vim#3961)
vim/vim@209b8e3

**vim-patch:8.1.1027: memory usage test sometimes fails**
Problem:    Memory usage test sometimes fails.
Solution:   Use 80% of before.last as the lower limit. (Christian Brabandt)
vim/vim@08cda65

**vim-patch:8.1.1031: memory usage test may still fail**
Problem:    Memory usage test may still fail.
Solution:   Drop the unused min value. (Christian Brabandt)
vim/vim@f7e47af

**vim-patch:8.1.1033: memory usage test may still fail on some systems**
Problem:    Memory usage test may still fail on some systems. (Elimar Riesebieter)
Solution:   Increase tolerance from 1% to 3%.

**vim-patch:8.1.1037: memory usage test may still fail on some systems**
Problem:    Memory usage test may still fail on some systems.
Solution:   Increase tolerance from 3% to 20%.
vim/vim@6b6f7aa

**vim-patch:8.1.1058: memory usage test may still fail on some systems**
Problem:    Memory usage test may still fail on some systems.
Solution:   Use 98% of the lower limit. (Christian Brabandt)
vim/vim@3a731ee

**vim-patch:8.1.1435: memory usage test is a bit too flaky**
Problem:    Memory usage test is a bit too flaky.
Solution:   Adjust the tolerances a bit. (Christian Brabandt)
vim/vim@5d508dd

**vim-patch:8.1.1484: some tests are slow**
Problem:    Some tests are slow.
Solution:   Add timing to the test messages.  Fix double free when quitting in VimLeavePre autocmd.
vim/vim@75ee544

**vim-patch:8.1.1485: double free when garbage_collect() is used in autocommand**
Problem:    Double free when garbage_collect() is used in autocommand.
Solution:   Have garbage collection also set the copyID in funccal_stack.
vim/vim@c07f67a

### CODE REVIEW

**Comment by justinmk** [comment]
still WIP? Scheduled for 0.5 since this does not seem to fix any serious problems.

**Comment by erw7** [comment]
> still WIP?

@justinmk I want to put vim-patch:`8.1.1485`, `8.1.1536`, `8.1.1575`, and `8.1.1583` in this PR.

File: src/nvim/eval.c [hunk 1]
```diff
@@ -22796,6 +22886,23 @@ void call_user_func(ufunc_T *fp, int argcount, typval_T *argvars,
       if (islambda) {
         addlocal = true;
       }
+
+      // evaluate named argument default expression
+      isdefault = ai + fp->uf_def_args.ga_len >= 0
+        && (i >= argcount || (argvars[i].v_type == VAR_SPECIAL
+                              && argvars[i].vval.v_number == kSpecialVarNull));
```
Comment (erw7) [inline src/nvim/eval.c]: Since neovim does not have `v:none`, `v:null` is used instead. Should this feature be omitted? It seems difficult to define `v:none` because there is no type corresponding to `msgpack`. Please let me know if you have a good idea.

Comment (justinmk) [reply src/nvim/eval.c]: We do not want `v:none` in any form. It is useless, and only exists to provide "loose" JSON in Vim, whereas the Nvim JSON parser only supports valid JSON.

Comment (bfredl) [reply src/nvim/eval.c]: This should be omitted entirely. `v:null` is a perfectly valid value (in both vim and nvim), it should not be implicitly replaced by the default.

Comment (justinmk) [reply src/nvim/eval.c]: The Vim `v:none` behavior for "default args" will make some scripts break since Nvim doesn't support `v:none`. But I think we should still avoid `v:none`. We're going to have to make some choices as Vim continues to add weird Vimscript features.

**Comment by teto** [comment]
could you rebase I will look into it.

**Comment by erw7** [comment]
> could you rebase I will look into it.

If #11851 is merged, this conflicts again. In my opinion, it would be less work to merge #11851 first and then rebase it, so I haven't rebased it.

**Comment by erw7** [comment]
> could you rebase I will look into it.

Done. Please review.

**Review by archseer — APPROVED** [review]

**Comment by janlazo** [comment]
https://github.com/neovim/neovim/pull/12203 includes 8.1.0800 and 8.1.0868 so this PR needs a rebase.

**Comment by teto** [comment]
I've reviewed up to vim-patch:8.1.1485 since 8.1.310 looks tricky (and the follwing ones too) and I would like to test it a bit. Would it make sense to merge up to vim-patch:8.1.1485 in a different PR ? I can do it if that's the issue.

**Comment by erw7** [comment]
@teto 8.1.1310 and 8.1.1563 have been separated into #12377.

**Comment by teto** [comment]
thanks !
