### PR TITLE
fix(tui): do not toggle cursor visibility when flushing the buffer

### LINKED ISSUE #26054: Cursor flickering when using 'termsync' option
### Problem

In certain terminals (e.g. Wezterm) and when using certain plugins (e.g. [fidget.nvim](https://github.com/j-hui/fidget.nvim)) the cursor will flicker at a high frequency when the `'termsync'` option is on.

### Steps to reproduce

```
mkdir repro
cd repro
git clone https://github.com/j-hui/fidget.nvim
cat >test.vim <<EOF
set runtimepath+=fidget.nvim
lua require('fidget').setup({})
lua vim.lsp.start({cmd = {'rust-analyzer'})
EOF
cargo init
nvim --clean -u test.vim src/main.rs
```

### Expected behavior

The cursor should not flicker.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1571+gba58c6f8a

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

Wezterm

### $TERM environment variable

wezterm

### Installation

Source

### PR DESCRIPTION
**Pull request by gpanders**
Fixes: https://github.com/neovim/neovim/issues/26054

When writing large amounts of data to the tty it is common to first hide
the cursor to avoid a flickering effect. This has been done in Nvim for
a long time and was implemented in the function that actually flushed
the TUI buffer out to the TTY.

However, when using synchronized updates with the 'termsync' option this
is no longer necessary, as the terminal emulator will buffer all of the
updates and display them atomically. Thus there is no need to toggle the
cursor visibility when flushing the buffer when synchronized updates are
used. In fact, doing so can actually reintroduce cursor flickering in
certain scenarios because the visibility state is itself being
synchronized by the terminal.

In addition, the management of the cursor visibility should not happen
when the TUI _buffer_ is flushed, but rather when the TUI itself is
flushed. This is a subtle but meaningful distinction: the former
literally writes bytes to the TTY while the latter flushes the TUI's
grid into its buffer. There is no need to hide the cursor every time we
write bytes to the TTY, only at the beginning of a full TUI "flush"
event.

### CODE REVIEW

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -1305,18 +1296,30 @@ void tui_default_colors_set(TUIData *tui, Integer rgb_fg, Integer rgb_bg, Intege
...
-  unibi_out_ext(tui, tui->unibi_ext.sync);
+/// Finish flushing the TUI. If 'termsync' is set and the terminal supports synchronized updates,
+/// end a synchronized update. Otherwise, make the cursor visible again.
+static void tui_flush_end(TUIData *tui)
+  FUNC_ATTR_NONNULL_ALL
+{
+  if (tui->sync_output && tui->unibi_ext.sync != -1) {
+    UNIBI_SET_NUM_VAR(tui->params[0], 0);
+    unibi_out_ext(tui, tui->unibi_ext.sync);
+  } else if (!tui->want_invisible) {
```
Comment (gpanders) [inline src/nvim/tui/tui.c:1320]: Do we need to also check `tui->busy` in this condition?

Comment (gpanders) [reply src/nvim/tui/tui.c]: Yes. Yes we do.

Comment (justinmk) [reply src/nvim/tui/tui.c]: @jdebp @teto
