### PR TITLE
vim-patch:8.1.2008,v8.2.{844,853,3348,3795,4379}

### LINKED ISSUE #4908: "E16 Invalid Range" error when undoing cG with listener_add callback
**Describe the bug**

Undoing a change to end of buffer (`cG`) with a  `listner_add` callback function that itself includes a function call fails with:

```
E16: Invalid range
```

**To Reproduce**

Create `repro.vim`:

```vim
" repro.vim

set nocp
set noswapfile
function DoIt()
  echom "Hello"
endfunction
function EchoChanges(bufnr, start, end, added, changes)
  call DoIt()
endfunction
call listener_add("EchoChanges")
```

Then:

* open Vim: `vi -u repro.vim`
* create a number of lines of content
* move the cursor to the first line
* `cG`
* `<Esc>u` to undo the change

**Expected behavior**

The undo succeeds

**Screenshots**

n/a

**Environment (please complete the following information):**
 - Vim version

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  3 2019 11:32:52)
Included patches: 1-1967
Compiled by myitcv@myitcv
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            -netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     -perl              +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           +python            +visual
+cmdline_info      +libcall           -python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       +xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        -mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/myitcv/usr/vim/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl  -L/usr/lib/x86_64-linux-gnu -lluajit-5.1  -L/home/myitcv/.pythons/2.7.15/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic       
```

- OS: Ubuntu 19.04
- Terminal: XTerm(330)

**Additional context**

### PR DESCRIPTION
**Pull request by janlazo**
Problem:    Error for invalid range when using listener and undo. (Paul Jolly)
Solution:   Do not change the cursor before the lines are restored.
            (closes vim/vim#4908)

https://github.com/vim/vim/commit/4544bd2f247425c9dd743c76618dd70f53c72538

v8.2.0845 could be later until I figure out why exactly tests are failing.

### CODE REVIEW

**Comment by janlazo** [comment]
`vim-patch:8.1.0688 text properties are not restored by undo`
doesn't seem N/A in the interest of porting v8.2.0844 and later patches. https://github.com/neovim/neovim/pull/26008

**Comment by janlazo** [comment]
[vim-patch:8.1.0579](https://github.com/vim/vim/commit/98aefe7c3250bb5d4153b994f878594d1745424e) cannot attach properties to text
is not N/A for v8.2.0845. Helps to reduce/avoid `strlen()`.

**Review by justinmk — APPROVED** [review]

File: src/nvim/ops.c [hunk 1]
```diff
@@ -4014,7 +4014,8 @@ int do_join(size_t count, bool insert_space, bool save_undo, bool use_formatopti
   colnr_T col = sumsize - currsize - spaces[count - 1];
 
   // allocate the space for the new line
-  char *newp = xmalloc((size_t)sumsize + 1);
+  size_t newp_len = (size_t)sumsize + 1;
```
Comment (janlazo) [inline src/nvim/ops.c]: Off-by-one error because of `+ 1`???

```
TEST_FILE=test/functional/api/buffer_updates_spec.lua make functionaltest
TEST_FILE=test/functional/legacy/069_multibyte_formatting_spec.lua make functionaltest
```

will pass.

```diff
diff --git a/src/nvim/ops.c b/src/nvim/ops.c
index 92258c6..9d410ab 100644
--- a/src/nvim/ops.c
+++ b/src/nvim/ops.c
@@ -4014,7 +4014,7 @@ int do_join(size_t count, bool insert_space, bool save_undo, bool use_formatopti
   colnr_T col = sumsize - currsize - spaces[count - 1];
 
   // allocate the space for the new line
-  size_t newp_len = (size_t)sumsize + 1;
+  size_t newp_len = (size_t)sumsize;
   char *newp = xmalloc(newp_len);
   cend = newp + sumsize;
   *cend = 0;
```

File: src/nvim/memline.c [hunk 2]
```diff
@@ -2487,7 +2502,19 @@ int ml_replace(linenr_T lnum, char *line, bool copy)
 ///
 /// @return  FAIL for failure, OK otherwise
 int ml_replace_buf(buf_T *buf, linenr_T lnum, char *line, bool copy, bool noalloc)
+  FUNC_ATTR_NONNULL_ARG(1)
 {
+  size_t len = line != NULL ? strlen(line) : (size_t)-1;
```
Comment (janlazo) [inline src/nvim/memline.c]: `-1` shouldn't matter here because of early `return FAIL;`

File: src/nvim/ops.c (hunk 1 above)
Comment (janlazo) [reply src/nvim/ops.c]: Rest of v8.2.0845 breaks legacy 068 test regardless of the above patch.

File: src/nvim/undo.c [hunk 3]
```diff
@@ -2372,12 +2378,15 @@ static void u_undoredo(bool undo, bool do_buf_event)
...
 
-    changed_lines(curbuf, top + 1, 0, bot, newsize - oldsize, do_buf_event);
-    // When text has been changed, possibly the start of the next line
-    // may have SpellCap that should be removed or it needs to be
-    // displayed.  Schedule the next line for redrawing just in case.
-    if (spell_check_window(curwin) && bot <= curbuf->b_ml.ml_line_count) {
-      redrawWinline(curwin, bot);
+    if (oldsize > 0 || newsize > 0) {
+      changed_lines(curbuf, top + 1, 0, bot, newsize - oldsize, do_buf_event);
+
```
Comment (zeertzjq) [inline src/nvim/undo.c]:
```suggestion
```

File: src/nvim/memline.c [hunk 4]
```diff
@@ -1973,12 +1973,11 @@ int ml_line_alloced(void)
 /// @param lnum  append after this line (can be 0)
 /// @param line  text of the new line
 /// @param len  length of line, including NUL, or 0
-/// @param newfile  flag, see above
+/// @param flags  ML_APPEND_ flags
 /// @param mark  mark the new line
```
Comment (zeertzjq) [inline src/nvim/memline.c]:
```suggestion
```

File: src/nvim/memline.h [hunk 5]
```diff
@@ -10,3 +10,16 @@
 
 /// LINEEMPTY() - return true if the line is empty
 #define LINEEMPTY(p) (*ml_get(p) == NUL)
+
+// Values for the flags argument of ml_delete_flags().
+enum {
+  ML_DEL_MESSAGE = 1,  // may give a "No lines in buffer" message
+  ML_DEL_UNDO = 2,     // called from undo, do not update textprops
```
Comment (zeertzjq) [inline src/nvim/memline.h]: Not sure about this, but `ML_DEL_UNDO` actually doesn't do anything in Nvim...
```suggestion
  ML_DEL_UNDO = 2,     // called from undo
```

Comment (janlazo) [reply src/nvim/memline.h]: Could comment it out or rename plus reassign to 0
or use `ml_delete()` with a comment for `ML_DEL_UNDO`
if no one else finds a use for it.

**Review by zeertzjq — APPROVED** [review]

**Comment by zeertzjq** [comment]
I think the last two commits should be squashed into a single `refactor:` commit, as they are small changes that do not change behavior.

**Comment by janlazo** [comment]
> I think the last two commits should be squashed into a single `refactor:` commit, as they are small changes that do not change behavior.

Split up the fixes and fixup-rebase-squash each fix to their respective patches.
Missed ML_APPEND_UNDO for the same reason ML_DEL_UNDO is commented out; both are for textprop so both flags are N/A.
