### PR TITLE
vim-patch:9.0.{1512,1513}

### LINKED ISSUE #23495: `smoothscroll` + `wrap` + `wincmd w` can draw a copy of the line below the cursor
### Problem

Screen seems to be not redrawn at the switching between windows.

image

 

Probably it happens only for some lines. 

### Steps to reproduce

Having `smswrap.lua` with
```lua
vim.wo.sms = true
vim.g.mapleader = ','
vim.go.mouse = 'a'

vim.cmd.help({args = {'sms'}, mods = {tab = 1}})
vim.cmd.vnew()
vim.cmd.wincmd 'w'
vim.api.nvim_win_set_width(0, 52)
vim.cmd.normal('/wrap' .. vim.keycode('<CR>') .. 'zt' .. vim.keycode('<C-e>'))
```
and nvim under `~/tmp/nvim-from-src/bin/nvim` run `~/tmp/nvim-from-src/bin/nvim --clean -u smswrap.lua`. Inside press `<C-w>w` once or more. 

### Expected behavior

Don't draw redundant content (or redraw the view). 

### Neovim version (nvim -v)

NVIM v0.10.0-dev-273+gc8ebb04e9

### Vim (not Nvim) behaves the same?

not checked

### Operating system/version

Debian Sid

### Terminal name/version

kitty 0.26.5-4 + tmux 3.3a-3

### $TERM environment variable

tmux-256color

### Installation

from source

### PR DESCRIPTION
**Pull request by luukvbaal**
Fix #23495

**vim-patch:9.0.1513: text scrolls unnecessarily when splitting**

Problem:    Text scrolls unnecessarily when splitting and 'splitkeep' is not
            "cursor".
Solution:   Avoid resetting w_skipcol. (Luuk van Baal, closes vim/vim#12334)

https://github.com/vim/vim/commit/b926bf47d61360a4ec5e4867714a08d70fd49965

**vim-patch:9.0.1512: inserting lines when scrolling with 'smoothscroll' set**

Problem:    Inserting lines when scrolling with 'smoothscroll' set.
Solution:   Adjust line height computation for w_skipcol. (Luuk van Baal,
            closes vim/vim#12350)

https://github.com/vim/vim/commit/c8502f9b880b6d23baa4f9d28b60e1ceb442e35f

### CODE REVIEW

**Comment by luukvbaal** [comment]
The ported test for `v9.0.1512` is a different repro for now for the same problem. I couldn't seem to reproduce it with the same steps as for vim, apparently we don't do a scrolling redraw when moving the cursor? IDK, I can check again later if we need a more similar test.

**Comment by luukvbaal** [comment]
Good to go, needed `'concealcursor'` set to trigger the issue with cursor movement.

File: src/nvim/drawscreen.c [hunk 1]
```diff
@@ -2101,7 +2101,12 @@ static void win_update(win_T *wp, DecorProviders *providers)
             if (hasFoldingWin(wp, l, NULL, &l, true, NULL)) {
               new_rows++;
             } else if (l == wp->w_topline) {
-              new_rows += plines_win_nofill(wp, l, true) + wp->w_topfill;
+              int n = plines_win_nofill(wp, l, false) + wp->w_topfill;
+              n = adjust_plines_for_skipcol(wp, n);
+              if (n > wp->w_height) {
+                n = wp->w_height;
+              }
```
Comment (zeertzjq) [inline src/nvim/drawscreen.c:2108]:
```suggestion
              if (n > wp->w_height_inner) {
                n = wp->w_height_inner;
              }
```

**Review by zeertzjq — APPROVED** [review]
