### PR TITLE
fix(vim.fs): make `rm()` work with symlink to a directory

### LINKED ISSUE #37724: `vim.fs.rm()` doesn't remove with symlink to a directory
### Problem

`vim.fs.rm()` can not  remove symlink to a directory. Although doing `rm` from the shell works by removing the symlink without removing linked directory content, so `vim.fs.rm()` should work the same (as per #30457).

### Steps to reproduce

1. `nvim --clean`
2. Prepare directory to symlink:

    ```lua
    vim.fn.mkdir('dir-to-link')
    vim.fn.writefile({ 'Lines' }, 'dir-to-link/file')
    ```

3. Make directory symlink:

    ```lua
    local cwd = vim.uv.cwd()
    vim.uv.fs_symlink(cwd .. '/dir-to-link', cwd .. '/dir-as-link', { dir = true })
    ```

4. Try to remove the symlink:
    4.1. `vim.fs.rm('dir-as-link')` throws `E5108: Lua: vim/fs.lua:0: dir-as-link is a directory` error.
    4.2. `vim.fs.rm('dir-as-link', { force = true })` throws `E5108: Lua: vim/fs.lua:0: ENOTDIR: not a directory: dir-as-link`
    4.3. `vim.fs.rm('dir-as-link', { recursive = true })` removes content from the original directory before throwing `E5108: Lua: vim/fs.lua:0: ENOTDIR: not a directory: dir-as-link`

### Expected behavior

`vim.fs.rm('link-to-dir')` only removes the symlink itself without touching original directory. Just as `rm link-to-dir` in shell does.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-2200+g396edf1e46

### Vim (not Nvim) behaves the same?

No, doesn't have this functionality

### Operating system/version

EndeavourOS Linux x86_64, 6.18.7-arch1-1

### Terminal name/version

Ghostty 1.2.3-arch2

### $TERM environment variable

xterm-ghostty

### Installation

Appimage

### PR DESCRIPTION
**Pull request by echasnovski**
Fix #37724.

### CODE REVIEW

**Comment by clason** [comment]
For the record, here's what nvim-treesitter uses:
```lua
local function rmpath(path)
  local stat = uv.fs_lstat(path)
  if not stat then
    return
  end

  if stat.type == 'directory' then
    for file in fs.dir(path) do
      rmpath(fs.joinpath(path, file))
    end
    return uv_rmdir(path)
  else
    return uv_unlink(path)
  end
end
```
(`uv_foo` are async wrappers for `vim.uv.fs_foo`)

**Comment by lewis6991** [comment]
Tests from #37724 would be valuable.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/37724#issuecomment-3853388692

> Should its behavior depend on the trailing `/` ? In shell, `rm -r symlink/` removes the directory + contents, whereas `rm -r symlink` only unlinks the symlink file.
>
> I suppose we can let the `recursive` flag decide this. That avoids subtle behavior depending on trailing `/`.

**Comment by echasnovski** [comment]
> Tests from #37724 would be valuable.

There is no tests for `vim.fs.rm()` at all. So there is nowhere to add those and covering other functionality with tests is a bit out of scope for this PR.

**Comment by echasnovski** [comment]
Documented the way to delete symlink's origin (as per [this comment](https://github.com/neovim/neovim/issues/37724#issuecomment-3853865261)).

**Comment by lewis6991** [comment]
> There is no tests for vim.fs.rm() at all. So there is nowhere to add those and covering other functionality with tests is a bit out of scope for this PR.

Tests not existing for a feature is not sufficient justification to not add them, especially when asked.

**Review by lewis6991 — CHANGES_REQUESTED** [review]
Added new resolution in https://github.com/neovim/neovim/issues/37724#issuecomment-3854016030

**Comment by echasnovski** [comment]
> Tests not existing for a feature is not sufficient justification to not add them, especially when asked.

Contributor not being overly eager to enter discussions about how to organize these tests (when they should have been the part of #30457) is sufficient enough.

**Comment by justinmk** [comment]
#30457 was lifting a testutil which all tests use, so it was considered "covered". But yeah now that we are making changes, let's add a `describe('rm()'` to `test/functional/lua/fs_spec.lua` . It only needs to exercise the symlink case for now.

**Comment by echasnovski** [comment]
> But yeah now that we are making changes, let's add a `describe('rm()'` to `test/functional/lua/fs_spec.lua` . It only needs to exercise the symlink case for now.

Should be already done. I've tried my best to make it both concise yet covering enough.

File: test/functional/lua/fs_spec.lua [hunk 1]
```diff
@@ -714,4 +715,38 @@ describe('vim.fs', function()
       end
     end)
   end)
+
+  describe('rm()', function()
+    before_each(function()
+      fn.mkdir('Xtest_fs-rm')
```
Comment (lewis6991) [inline test/functional/lua/fs_spec.lua]: `fn` runs everything through the embedded `nvim` instance whereas calling `vim.fs` will use `vim.fs` from the test runner instance. 

Ideally the tests should be using the embedded instance (via `exec_lua`), but it's probably fine as they are if you want to keep it that way. If we use `vim.fs` directly, then we should probably avoid using `fn` in `before_each`/`after_each`.

I think you can just use `mkdir_p`, `rmdir` and `n.write_file`

Comment (echasnovski) [reply test/functional/lua/fs_spec.lua]: > Ideally the tests should be using the embedded instance (via `exec_lua`), but it's probably fine as they are if you want to keep it that way.

I don't want to, this is how other `vim.fs` tests are done. Ideally indeed every test should be done in a fresh `nvim` instance.

**Review by lewis6991 — APPROVED** [review]
