### PR TITLE
cmdheight=0: fix bugs

### LINKED ISSUE #18953: Mappings that trigger the commandline do not set cmdheight to 1 with initial cmdheight=0
### Neovim version (nvim -v)

NVIM v0.8.0-dev+1875-g663cbe262

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.4

### Terminal name/version

Kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### How to reproduce the issue

* `nvim --clean`
* `:set cmdheight=0`
* `:nnoremap <space> :help<space><CR>`
* Press `<Space>`

The cursor will stick and input will not be entered into the command line, the cursor is also not visible till you press `<Esc>`

### Expected behavior

The commandline should be set to `cmdheight=1` and populated with `:help `

### Actual behavior

The cursor is not visible, the commandline height does not change and no other keys (that I tried) respond till `<Esc>` is pressed

### LINKED ISSUE #18955: `statusline` is not pushed one line upward when starting ex commands in Visual Mode
### Neovim version (nvim -v)

v0.8.0-dev+419-g837360868

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Fedora 36

### Terminal name/version

kitty 0.25.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

`nvim --clean`
`:set cmdheight=0`
Press `v:`

### Expected behavior

`statusline` should be pushed one line upward when entering ex commands

### Actual behavior

`statusline` overlays the `cmdline` visually blocking ex command input

### LINKED ISSUE #18958: cmdheight = 0: Confirmation during search and replace doesn't show prompt
### Neovim version (nvim -v)

NVIM v0.8.0-dev (commit e13c36e31)

### Vim (not Nvim) behaves the same?

no, vim doesn't have this feature

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

build from source

### How to reproduce the issue

nvim --clean --noplugins -u NONE
:set cmdheight=0
(load any file with some strings that can be replaced)
:%s/somestring/otherstring/gc

### Expected behavior

Either statusline is pushed up to show interactive replacement prompt, or it replaces the statusline

### Actual behavior

Interactive replacement prompt cannot be seen - although y/n/etc. keys still work.

### LINKED ISSUE #18960: cmdheight=0: `:file` only outputs `<`
### Neovim version (nvim -v)

NVIM v0.8.0-dev+421-g7f8f8d6cb

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Fedora Workstation 36

### Terminal name/version

GNOME Terminal v3.44.1

### $TERM environment variable

xterm-256color

### Installation

Source

### How to reproduce the issue

nvim --clean
:set cmdheight=0
:file

### Expected behavior

Displays file info, possibly without truncating, like `:file!` or when `t` is not set in `shortmess` (as truncating wouldn't avoid a hit ENTER prompt anyway)

### Actual behavior

Outputs `<` (and displays a hit ENTER prompt)

I'm guessing `msg_may_trunc` needs to be changed?

### LINKED ISSUE #18970: cmdheight=0: crash with laststatus=0 rulerformat
### Neovim version (nvim -v)

NVIM v0.8.0-dev+428-g1493efdc14

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux coorie 5.10.121-1-MANJARO #1 SMP PREEMPT Thu Jun 9 09:56:12 UTC 2022 x86_64 GNU/Linux

### Terminal name/version

alacritty 0.11.0-dev (d9c6c8d5)

### $TERM environment variable

tmux-256color

### Installation

aur/neovim-git

### How to reproduce the issue

Execute neovim with min.vim
```
set laststatus=0
set rulerformat=%l,%c%=
set cmdheight=0
```
I got an assertion failure
```
nvim: /home/octaltree/.cache/yay/neovim-git/src/neovim-git/src/nvim/grid.c:335: grid_puts_line_flush: アサーション `put_dirty_row != -1' に失敗しました。
                                                                     zsh: IOT instruction (core dumped)  nvim -u min.vim
```

### Expected behavior

Since the noruler is explicitly stated in the test, I want error messages to users or documentation or automatic noruler settings.

### Actual behavior

Ruler drawing causes panic

### LINKED ISSUE #18983: screen not updated after cmdline-completion when cmdheight=0
### Neovim version (nvim -v)

v0.8.0-dev+428-g1493efdc1

### Vim (not Nvim) behaves the same?

cmdheight=0 not available in vim

### Operating system/version

x86_64 GNU/Linux Arch Linux

### Terminal name/version

st 0.8.5

### $TERM environment variable

st-256color

### Installation

neovim-nightly-bin

### How to reproduce the issue

nvim --clean
:set cmdheight=0
:set wildmode=list:longest
:l<TAB> " So anything to trigger cmdline-completion then click <Esc> or <Ctrl-c>

### Expected behavior

The top of the cmdline should be moved after abording the completion

https://user-images.githubusercontent.com/62812018/174012330-4e194d9a-b6b7-41dc-9ab0-cc82df9f319f.mov

### Actual behavior

The top of the cmdline sticks and to get rid of it, i have to use :mod or <ctrl-l>

### LINKED ISSUE #18995: cmdheight set to 1 when <C-w>+ with cmdheight=0 and no split
### Neovim version (nvim -v)

NVIM v0.8.0-dev+440-g98e2da7d50

### Vim (not Nvim) behaves the same?

cmdheight=0 not available in vim

### Operating system/version

x86_64 GNU/Linux Arch Linux

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

Arch User Repository through paru -S neovim-git

### How to reproduce the issue

nvim --clean
`:set cmdheight=0`
type `<C-w>+`
cmdline apperes and `:set cmdheight?` returns `cmdheight=1`

### Expected behavior

nvim --clean
`:set cmdheight=0`
type `<C-w>+`
cmdline **do not** apperes and `:set cmdheight?` returns **`cmdheight=0`**

### Actual behavior

Explained in `How to reproduce the issue`.

>nvim --clean
`:set cmdheight=0`
type `<C-w>+`
cmdline apperes and `:set cmdheight?` returns `cmdheight=1`

### LINKED ISSUE #19112: cmdheight=0: (1) :s unexpectedly scroll screen up by one line; (2) msgArea background color inconsistent
### Neovim version (nvim -v)

NVIM v0.8.0-dev+428-g1493efdc1

### Vim (not Nvim) behaves the same?

no, vim does not have this feature

### Operating system/version

Ubuntu 22.04

### Terminal name/version

alacritty Version 0.11.0-dev (ad3ebba5)

### $TERM environment variable

xterm-256color

### Installation

sudo apt install ./nvim-linux64.deb

### How to reproduce the issue

```
nvim --clean
:set cmdheight=0
:set laststatus=0
:hi msgArea ctermbg=red
```
insert many lines (200~)
```
:s
```

### Expected behavior

screen does not scroll, the whole command line is red
expected

### Actual behavior

- screen scroll up by 1 line
- command line color is not completely red
actual

### PR DESCRIPTION
**Pull request by Shougo**
Continue of #16251

Fix #18953
Fix #18960
Fix #18958
Fix #18955
Fix #18970
Fix #18983
Fix #18995
Fix #19112

### CODE REVIEW

**Comment by Shougo** [comment]
I have fixed the substitute problem and add tests.

**Comment by vimpostor** [comment]
Is it intended that the "recording @q" message is shown when recording a macro?

In any case the behaviour is very buggy, for example when I press `q` three times, neovim is not recording anymore, but it still shows "recording @q" in the cmdline.

**Comment by Shougo** [comment]
> Is it intended that the "recording @q" message is shown when recording a macro?

I cannot reproduce the behavior.  The message is not shown.
Please create the minimal init.vim with the reproduce instruction from neovim starting.

**Comment by vimpostor** [comment]
> Please create the minimal init.vim with the reproduce instruction

It seems to be an issue in combination with `set display=lastline`
```bash
build/bin/nvim --clean -Nu <(cat<<EOF
set display=lastline
set cmdheight=0
norm qq
EOF
)
```

**Comment by Shougo** [comment]
OK.  I have reproduced it.

**Comment by Shougo** [comment]
Fixed.

File: src/nvim/ex_cmds.c [hunk 1]
```diff
@@ -3638,6 +3638,13 @@ static int do_sub(exarg_T *eap, proftime_T timeout, long cmdpreview_ns, handle_T
     sub_needs_free = cmdpreview && sub != source;
   }
 
+  bool cmdheight0 = p_ch < 1 && !ui_has(kUIMessages);
```
Comment (justinmk) [inline src/nvim/ex_cmds.c:3641]: is this here because of cmdpreview? would it make sense to move this to `cmdpreview_show` ?

Comment (zeertzjq) [reply src/nvim/ex_cmds.c:3641]: This should be for the substitute prompt.

File: src/nvim/ex_getln.c [hunk 2]
```diff
@@ -985,6 +985,9 @@ static uint8_t *command_line_enter(int firstc, long count, int indent, bool init
   if (cmdheight0) {
     // Restore cmdheight
     set_option_value("ch", 0L, NULL, 0);
+
+    // Redraw is needed for command line completion
+    redraw_all_later(CLEAR);
```
Comment (justinmk) [inline src/nvim/ex_getln.c:990]: is CLEAR really needed or does something less drastic work, such as REDRAW_TOP, SOME_VALID, ..?

File: src/nvim/ops.c [hunk 3]
```diff
@@ -2797,7 +2797,7 @@ static void op_yank_reg(oparg_T *oap, bool message, yankreg_T *reg, bool append)
     xfree(reg->y_array);
   }
 
-  if (message) {  // Display message about yank?
+  if (message && p_ch > 0) {  // Display message about yank?
```
Comment (justinmk) [inline src/nvim/ops.c:2800]: I suppose we can do this for now, but we'll want to revert this later when we have a "never show press-enter" feature. So the message would still display but the hit-enter prompt is avoided.

File: src/nvim/screen.c [hunk 4]
```diff
@@ -6153,6 +6153,10 @@ void clearmode(void)
 
 static void recording_mode(int attr)
 {
+  if (p_ch <= 0) {
+    return;
```
Comment (justinmk) [inline src/nvim/screen.c:6157]: Here's another case where we're adding guards just to avoid a message. Maybe we should change the message code now to _never show hit-enter_ when `p_ch==0`.

File: src/nvim/window.c [hunk 5]
```diff
@@ -5543,9 +5543,10 @@ static void frame_setheight(frame_T *curfrp, int height)
   if (curfrp->fr_parent == NULL) {
     // topframe: can only change the command line
     if (height > ROWS_AVAIL) {
-      // If height is greater than the available space, try to create space for the frame by
-      // reducing 'cmdheight' if possible, while making sure `cmdheight` doesn't go below 1.
-      height = MIN(ROWS_AVAIL + (p_ch - 1), height);
+      // If height is greater than the available space, try to create space for
+      // the frame by reducing 'cmdheight' if possible, while making sure
+      // `cmdheight` doesn't go below 1.
```
Comment (justinmk) [inline src/nvim/window.c:5548]: Last year we changed the style guide to allow lines up to 100 chars long. Don't need to reformat this comment.

File: src/nvim/ex_cmds.c (hunk 1 above)
Comment (Shougo) [reply src/nvim/ex_cmds.c:3641]: This does not depend on inccommand preview.
It is for substitute prompt.

Please see this.

https://github.com/neovim/neovim/issues/18958

File: src/nvim/ex_getln.c (hunk 2 above)
Comment (Shougo) [reply src/nvim/ex_getln.c:990]: Unfortunately, `CLEAR` is really needed.  Other modes does not work....
I have tested them.

File: src/nvim/ops.c (hunk 3 above)
Comment (Shougo) [reply src/nvim/ops.c:2800]: OK.

File: src/nvim/screen.c (hunk 4 above)
Comment (Shougo) [reply src/nvim/screen.c:6157]: OK.

File: src/nvim/window.c (hunk 5 above)
Comment (Shougo) [reply src/nvim/window.c:5548]: Oh, I have not know this.
I just found the comment line is too long.

**Comment by Shougo** [comment]
All tests are passed.

**Comment by Shougo** [comment]
I have fixed the conflicts and rebased.

**Comment by Shougo** [comment]
Many fatal `cmdheight` bugs are fixed in the PR.
I think it is ready to merge.

**Comment by justinmk** [comment]
Thank you @Shougo for this followup! Merged because this fixes many bugs, but I still am hoping to see a PR that tries https://github.com/neovim/neovim/pull/18961#discussion_r901078775 : maybe somewhere in `wait_return()` we could just always skip hit-enter if `p_ch < 1`.

Meanwhile, I squashed the commits here because the changes are self-contained enough that if we end up needing to bisect an issue here, it's easy to comment-out specific changes.

**Comment by Shougo** [comment]
Thank you.
