### PR TITLE
fix(ui2): always route to dialog when cmdline is open

### LINKED ISSUE #37652: ui2: error in cmdline mode keymap is not shown
## Steps to reproduce

```
nvim --clean --cmd "lua require('vim._extui').enable{}" --cmd "cnoremap <c-a> <cmd>lua error('test')<cr>"
```

## Expected behavior
show error when press `<c-a>`
```
E5108: Lua: [string ":lua"]:1: test     
stack traceback:                        
        [C]: in function 'error'        
        [string ":lua"]:1: in main chunk
```

## System info

- Nvim version (nvim -v): `v0.12.0-dev-2160 g1355640d6a-dirty` neovim/neovim@1355640d6a
- Vim (not Nvim) behaves the same?: ?
- Operating system/version: Linux 6.18.7-zen1-1-zen
- Terminal name/version: kitty
- $TERM environment variable: `xterm-kitty`
- Installation: ?

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Messages emitted while cmdline is open are not shown with
          cmdline message target.
Solution: Route to dialog window when cmdline is open.

Fix #37652

### CODE REVIEW

File: runtime/lua/vim/_core/ui2/messages.lua [hunk 1]
```diff
@@ -398,21 +402,23 @@ function M.msg_show(kind, content, replace_last, _, append, id)
...
+  elseif
+    (ui.cmd.prompt or (ui.cmd.level > 0 and ui.cfg.msg.target == 'cmd')) and ui.cmd.srow == 0
+  then
+    -- Route to dialog when a prompt is active, or message would overwrite active cmdline.
     replace_last = api.nvim_win_get_config(ui.wins.dialog).hide or kind == 'wildlist'
     if kind == 'wildlist' then
       api.nvim_buf_set_lines(ui.bufs.dialog, 0, -1, false, {})
-      ui.cmd.prompt = true -- Ensure dialog is closed when cmdline is hidden.
     end
+    ui.cmd.dialog = true -- Ensure dialog is closed when cmdline is hidden.
```
Comment (justinmk) [inline runtime/lua/vim/_core/ui2/messages.lua:413]: is the comment still correct?

Comment (luukvbaal) [reply runtime/lua/vim/_core/ui2/messages.lua:413]: Yes see lines 142-147 in cmdline.lua:cmdline_hide(). `prompt` is now just used to divert from the msg target if a prompt is active.
