### PR TITLE
fix(terminal): memory leak in pending `TermRequest` `StringBuilder`

### LINKED ISSUE #39332: terminal: leak in `schedule_termrequest`/`emit_termrequest` on buffer destroy
### Problem

memory leak

### Steps to reproduce

1. Build master with ASAN & LSAN
2. save file:
 ```lua
 local buf  = vim.api.nvim_create_buf(false, true)
 local chan = vim.api.nvim_open_term(buf, {})
 vim.api.nvim_create_autocmd('TermRequest', { buffer = buf, callback = function() end })
 vim.api.nvim_chan_send(chan, '\x1b]7;file:///a\x1b\\')
 vim.api.nvim_chan_send(chan, '\x1b]7;file:///b\x1b\\')
 vim.api.nvim_buf_delete(buf, { force = true })
```
3. `ASAN_OPTIONS=detect_leaks=1 <pathtonvim>/nvim --headless --clean -c 'luafile /tmp/nvim-termreq-leak.lua' -c 'qa!'`

```
=================================================================
==2038791==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f843e721c2b in malloc (/nix/store/ihpdbhy4rfxaixiamyb588zfc3vj19al-gcc-15.2.0-lib/lib/libasan.so.8+0x121c2b)
    #1 0x556e02e272b3 in try_malloc /tmp/neovim/bughunt/src/nvim/memory.c:113
    #2 0x556e02e273c8 in xmalloc /tmp/neovim/bughunt/src/nvim/memory.c:147
    #3 0x556e0317e848 in schedule_termrequest /tmp/neovim/bughunt/src/nvim/terminal.c:304
    #4 0x556e03180007 in on_osc /tmp/neovim/bughunt/src/nvim/terminal.c:367
    #5 0x556e0328f8d8 in on_osc /tmp/neovim/bughunt/src/nvim/vterm/state.c:1985
    #6 0x556e03272876 in string_fragment /tmp/neovim/bughunt/src/nvim/vterm/parser.c:89
    #7 0x556e0327321a in vterm_input_write /tmp/neovim/bughunt/src/nvim/vterm/parser.c:323
    #8 0x556e0318d347 in terminal_receive /tmp/neovim/bughunt/src/nvim/terminal.c:1378
    #9 0x556e0298fca0 in channel_send /tmp/neovim/bughunt/src/nvim/channel.c:638
    #10 0x556e02903b91 in nvim_chan_send /tmp/neovim/bughunt/src/nvim/api/vim.c:1275
    #11 0x556e02d1f1d9 in nlua_api_nvim_chan_send /tmp/neovim/bughunt/asanbuild/src/nvim/auto/lua_api_c_bindings.generated.h:6159
    #12 0x556e03381545 in lj_BC_FUNCC (/tmp/neovim/bughunt/asanbuild/bin/nvim+0x180a545)

SUMMARY: AddressSanitizer: 24 byte(s) leaked in 1 allocation(s).
```

### Expected behavior

no leak

***NOTE***: I already have a fix for this. I'm putting it up rn

### Nvim version (nvim -v)

0.12

### Vim (not Nvim) behaves the same?

no (N/A)

### Operating system/version

nixos

### Terminal name/version

ghostty

### $TERM environment variable

tmux-256color

### Installation

local build

### PR DESCRIPTION
**Pull request by barrettruth**
## Problem

Destroying a terminal buffer with pending `TermRequest` events leaks a `StringBuilder` per orphaned event.

Don't ask how i found this...

## Solution

I moved ownership of `pending_send` onto the queued `emit_termrequest`. Eacg and every live `term->pending.send` has a queued emit that will free it.

Closes #39332.

### CODE REVIEW

**Comment by superatomic** [comment]
> Don't ask how i found this...

Well now I'm curious.

**Review by zeertzjq — DISMISSED** [review]

File: test/functional/terminal/parser_spec.lua [hunk 1]
```diff
@@ -92,4 +92,21 @@ describe(':terminal', function()
...
+      vim.api.nvim_create_autocmd('TermRequest', { buffer = b, callback = function() end })
+    end, buf)
+    -- Two back-to-back OSC 7 sequences: the second overwrites `term->pending.send`,
+    -- orphaning the first StringBuilder (only referenced from the queued emit).
+    api.nvim_chan_send(chan, OSC_PREFIX .. '7;file:///a' .. ST)
+    api.nvim_chan_send(chan, OSC_PREFIX .. '7;file:///b' .. ST)
+    -- `terminal_destroy` used to free only the current `term->pending.send`;
+    -- the orphan then hit the early return in `emit_termrequest` which freed
+    -- `sequence` but leaked `pending_send`. ASan/LSan CI catches this.
+    api.nvim_buf_delete(buf, { force = true })
```
Comment (zeertzjq) [inline test/functional/terminal/parser_spec.lua]: You need to put these calls in a single RPC request, otherwise the test doesn't fail without the fix.
```suggestion
    exec_lua(function()
      -- Two back-to-back OSC 7 sequences: the second overwrites `term->pending.send`,
      -- orphaning the first StringBuilder (only referenced from the queued emit).
      vim.api.nvim_chan_send(chan, OSC_PREFIX .. '7;file:///a' .. ST)
      vim.api.nvim_chan_send(chan, OSC_PREFIX .. '7;file:///b' .. ST)
      -- `terminal_destroy` used to free only the current `term->pending.send`;
      -- the orphan then hit the early return in `emit_termrequest` which freed
      -- `sequence` but leaked `pending_send`. ASan/LSan CI catches this.
      vim.api.nvim_buf_delete(buf, { force = true })
    end)
```

Comment (barrettruth) [reply test/functional/terminal/parser_spec.lua]: Sheesh. I do not know enough about the test harness. fixed ty

**Review by zeertzjq — APPROVED** [review]
