### PR TITLE
fix(help): force tree reparse after local addition insertion

### LINKED ISSUE #99: Vimdoc parser breaks down around LOCAL ADDITIONS in the help section
The text changes based on installed plugins, so it's not always apparent. Minimal reproduction:

```
LOCAL ADDITIONS:				*local-additions*
|lazy.nvim.txt|         For Neovim >= 0.8.0         Last change: 2023 March 07
|nvim-treesitter|  Treesitter configurations and abstraction layer for Neovim.
|matchit.txt|	Extended "%" matching
```

### PR DESCRIPTION
**Pull request by clason**
Problem: `*local-additions*` in `help.txt` are inserted via `ml_append`,
which messes up treesitter highlighting of this file as the buffer
becomes desynced from the tree.

Solution: Add hack on top of hack by explicitly calling `mark_adjust`
and `changed_lines_buf` after each insertion.

Should be covered by old `test_help.vim`.

Also massage the column headers in that section for consistency and correct vimdoc parsing.

Closes https://github.com/neovim/tree-sitter-vimdoc/issues/99

@bfredl

### CODE REVIEW

File: src/nvim/help.c [hunk 1]
```diff
@@ -817,6 +818,10 @@ void fix_help_buffer(void)
                 convert_setup(&vc, NULL, NULL);
 
                 ml_append(lnum, cp, (colnr_T)0, false);
+                // todo(clason): adjust extmarks and mark added line as changed to force reparsing
+                // of tree for treesitter
+                mark_adjust(lnum + 1, (linenr_T)MAXLNUM, (linenr_T)1, 0L, kExtmarkUndo);
```
Comment (bfredl) [inline src/nvim/help.c:823]: normally we do this after an entire change loop, like this https://github.com/neovim/neovim/compare/master...bfredl:neovim:nochange

Comment (clason) [reply src/nvim/help.c]: much better, thank you!
