### PR TITLE
[RFC] normal.c: No garbage collection while handling an event in normal mode

### LINKED ISSUE #3588: List needs to be protected against garbage collection
Started nvim with `nvim src/regexp_nfa.c +975` and waited until YCM wanted me to confirm
the use of `.ycm_extra_conf.py`.  Waited a bit more and pressed [O]k.

```c
==25885==ERROR: AddressSanitizer: heap-use-after-free on address 0x6080001000b0 at pc 0x000000d9f395 bp 0x7ffcb94a4e00 sp 0x7ffcb94a4df8
READ of size 4 at 0x6080001000b0 thread T0
    #0 0xd9f394 in list_unref /home/oni-link/git/neovim/src/nvim/eval.c:4842:20
    #1 0xdb8ba3 in clear_tv /home/oni-link/git/neovim/src/nvim/eval.c:17867:7
    #2 0xdd5144 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7502:5
    #3 0xe77491 in eval7 /home/oni-link/git/neovim/src/nvim/eval.c:4211:15
    #4 0xe730b5 in eval6 /home/oni-link/git/neovim/src/nvim/eval.c:3921:7
    #5 0xe70282 in eval5 /home/oni-link/git/neovim/src/nvim/eval.c:3773:7
    #6 0xe6b6f4 in eval4 /home/oni-link/git/neovim/src/nvim/eval.c:3517:7
    #7 0xe6ac73 in eval3 /home/oni-link/git/neovim/src/nvim/eval.c:3437:7
    #8 0xe6a213 in eval2 /home/oni-link/git/neovim/src/nvim/eval.c:3374:7
    #9 0xdb9c62 in eval1 /home/oni-link/git/neovim/src/nvim/eval.c:3307:7
    #10 0xdb75dc in eval0 /home/oni-link/git/neovim/src/nvim/eval.c:3269:9
    #11 0xe4592c in ex_return /home/oni-link/git/neovim/src/nvim/eval.c:20607:10
    #12 0x1347e50 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #13 0x1326bed in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #14 0xdf485a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #15 0xdc0b41 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #16 0xe58ee2 in eval_call_provider /home/oni-link/git/neovim/src/nvim/eval.c:21713:9
    #17 0x5a3288 in script_host_execute /home/oni-link/git/neovim/src/nvim/ex_cmds2.c:3311:11
    #18 0x5a2ab1 in ex_python /home/oni-link/git/neovim/src/nvim/ex_cmds2.c:785:3
    #19 0x1347e50 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #20 0x1326bed in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #21 0xdf485a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #22 0xdc0b41 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #23 0xdd5024 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #24 0xdcf48b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #25 0x1347e50 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #26 0x1326bed in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #27 0xdf485a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #28 0xdc0b41 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #29 0xdd5024 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #30 0xdcf48b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #31 0x1347e50 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #32 0x1326bed in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #33 0xdf485a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #34 0xdc0b41 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #35 0xdd5024 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #36 0xdcf48b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #37 0x1347e50 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #38 0x1326bed in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #39 0x824d97 in apply_autocmds_group /home/oni-link/git/neovim/src/nvim/fileio.c:6588:5
    #40 0x81521a in apply_autocmds /home/oni-link/git/neovim/src/nvim/fileio.c:6207:10
    #41 0x16506b4 in cursorhold_event /home/oni-link/git/neovim/src/nvim/os/input.c:79:3
    #42 0x172349f in queue_process_events /home/oni-link/git/neovim/src/nvim/event/queue.c:142:7
    #43 0x1047ec4 in nv_event /home/oni-link/git/neovim/src/nvim/normal.c:7692:3
    #44 0xfea374 in normal_execute /home/oni-link/git/neovim/src/nvim/normal.c:1153:3
    #45 0x1245d03 in state_enter /home/oni-link/git/neovim/src/nvim/state.c:55:26
    #46 0xfa1300 in normal_enter /home/oni-link/git/neovim/src/nvim/normal.c:470:3
    #47 0xf6d68e in main /home/oni-link/git/neovim/src/nvim/main.c:537:3
    #48 0x7f13d292072f in __libc_start_main (/lib64/libc.so.6+0x2072f)
    #49 0x443018 in _start (/home/oni-link/git/neovim/build/bin/nvim+0x443018)

0x6080001000b0 is located 16 bytes inside of 88-byte region [0x6080001000a0,0x6080001000f8)
freed by thread T0 here:
    #0 0x4db6c0 in __interceptor_cfree.localalias.1 /home/oni-link/git/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:35
    #1 0xac8064 in xfree /home/oni-link/git/neovim/src/nvim/memory.c:108:3
    #2 0xddd8a7 in list_free /home/oni-link/git/neovim/src/nvim/eval.c:4874:3
    #3 0xde80f8 in free_unref_items /home/oni-link/git/neovim/src/nvim/eval.c:5743:7
    #4 0xda2976 in garbage_collect /home/oni-link/git/neovim/src/nvim/eval.c:5678:16
    #5 0x1188e4f in before_blocking /home/oni-link/git/neovim/src/nvim/getchar.c:1335:5
    #6 0x164ca13 in os_inchar /home/oni-link/git/neovim/src/nvim/os/input.c:110:9
    #7 0x109e102 in get_keystroke /home/oni-link/git/neovim/src/nvim/misc1.c:2385:9
    #8 0x163538c in do_dialog /home/oni-link/git/neovim/src/nvim/message.c:2673:9
    #9 0xe91097 in f_confirm /home/oni-link/git/neovim/src/nvim/eval.c:8474:28
    #10 0xdc10b1 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7643:11
    #11 0xdd5024 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #12 0xe77491 in eval7 /home/oni-link/git/neovim/src/nvim/eval.c:4211:15
    #13 0xe730b5 in eval6 /home/oni-link/git/neovim/src/nvim/eval.c:3921:7
    #14 0xe70282 in eval5 /home/oni-link/git/neovim/src/nvim/eval.c:3773:7
    #15 0xe6b6f4 in eval4 /home/oni-link/git/neovim/src/nvim/eval.c:3517:7
    #16 0xe6ac73 in eval3 /home/oni-link/git/neovim/src/nvim/eval.c:3437:7
    #17 0xe6a213 in eval2 /home/oni-link/git/neovim/src/nvim/eval.c:3374:7
    #18 0xdb9c62 in eval1 /home/oni-link/git/neovim/src/nvim/eval.c:3307:7
    #19 0xdb75dc in eval0 /home/oni-link/git/neovim/src/nvim/eval.c:3269:9
    #20 0xdbdb28 in eval_expr /home/oni-link/git/neovim/src/nvim/eval.c:1149:7
    #21 0x1668732 in vim_eval /home/oni-link/git/neovim/src/nvim/api/vim.c:149:27
    #22 0x51c247 in handle_vim_eval /home/oni-link/git/neovim/build/src/nvim/auto/msgpack_dispatch.c:906:15
    #23 0x16d668a in on_request_event /home/oni-link/git/neovim/src/nvim/msgpack_rpc/channel.c:481:19
    #24 0x172349f in queue_process_events /home/oni-link/git/neovim/src/nvim/event/queue.c:142:7
    #25 0x16cbb57 in channel_send_call /home/oni-link/git/neovim/src/nvim/msgpack_rpc/channel.c:223:3
    #26 0xeda661 in f_rpcrequest /home/oni-link/git/neovim/src/nvim/eval.c:14063:19
    #27 0xdc10b1 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7643:11
    #28 0xdf9cdd in func_call /home/oni-link/git/neovim/src/nvim/eval.c:8238:9
    #29 0xe8d1f1 in f_call /home/oni-link/git/neovim/src/nvim/eval.c:8279:9

previously allocated by thread T0 here:
    #0 0x4db9d0 in calloc /home/oni-link/git/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:56
    #1 0xac8102 in xcalloc /home/oni-link/git/neovim/src/nvim/memory.c:122:15
    #2 0xd9c51a in list_alloc /home/oni-link/git/neovim/src/nvim/eval.c:4813:18
    #3 0x5a2e0a in script_host_execute /home/oni-link/git/neovim/src/nvim/ex_cmds2.c:3304:20
    #4 0x5a2ab1 in ex_python /home/oni-link/git/neovim/src/nvim/ex_cmds2.c:785:3
    #5 0x1347e50 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #6 0x1326bed in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #7 0xdf485a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #8 0xdc0b41 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #9 0xdd5024 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #10 0xdcf48b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #11 0x1347e50 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #12 0x1326bed in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #13 0xdf485a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #14 0xdc0b41 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #15 0xdd5024 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #16 0xdcf48b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #17 0x1347e50 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #18 0x1326bed in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #19 0xdf485a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #20 0xdc0b41 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #21 0xdd5024 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #22 0xdcf48b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #23 0x1347e50 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #24 0x1326bed in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #25 0x824d97 in apply_autocmds_group /home/oni-link/git/neovim/src/nvim/fileio.c:6588:5
    #26 0x81521a in apply_autocmds /home/oni-link/git/neovim/src/nvim/fileio.c:6207:10
    #27 0x16506b4 in cursorhold_event /home/oni-link/git/neovim/src/nvim/os/input.c:79:3
    #28 0x172349f in queue_process_events /home/oni-link/git/neovim/src/nvim/event/queue.c:142:7
    #29 0x1047ec4 in nv_event /home/oni-link/git/neovim/src/nvim/normal.c:7692:3

SUMMARY: AddressSanitizer: heap-use-after-free /home/oni-link/git/neovim/src/nvim/eval.c:4842:20 in list_unref
```
Problem seems to be that the list `args` created in `script_host_execute()` is not protected
against garbage collection (while waiting for user input), because it is not included in any other list or dictionary:

```
static void script_host_execute(char *name, exarg_T *eap)
{
  uint8_t *script = script_get(eap, eap->arg);

  if (!eap->skip) {
    list_T *args = list_alloc();
    // script
    list_append_string(args, script ? script : eap->arg, -1);
    // current range
    list_append_number(args, eap->line1);
    list_append_number(args, eap->line2);
    // args->lv_watch=1;   // uncomment HACK to protect against garbage collection
    (void)eval_call_provider(name, "execute", args);
    // args->lv_watch=0;   // uncomment HACK to protect against garbage collection
  }

  xfree(script);
}
```
If I misuse list member `lv_watch` like shown in the code, I cannot reproduce the problem anymore.
@tarruda fixed a similar problem in 2b7f460716e5c979817f23ba5d9e33d3ab3c9ca0 for dictionaries, introducing an internal refcount to protect against garbage collection.

### PR DESCRIPTION
**Pull request by oni-link**
eval.c: Protect saved funccalls against garbage collection

When the current function call pointer is saved with a call to
save_funccal(), the funccall is not protected anymore against garbage
collection.

To fix this we collect a list of all saved but not yet restored
funccalls and tell the garbage collection not to free them.

Fixes #3588

@ZyX-I , @tarruda

### CODE REVIEW

**Comment by tarruda** [comment]
LGTM, but have you actually experienced this bug? It seems `may_garbage_collect` is only set by `normal_check` if both `cmdwin` and `noexmode`(`normal_enter` parameters)  are false(which I don't think could happen while pending function calls). There are other calls to `garbage_collect()` that are not protected by `may_garbage_collect`, but they only seem to happen during exit and when `try_to_free_memory()` is called.

**Comment by tarruda** [comment]
nevermind previous question, just saw your [comment](https://github.com/neovim/neovim/issues/3588#issuecomment-154733998)

**Comment by ZyX-I** [comment]
I do not think that you are fixing the bug. As I said it should not have `may_garbage_collect` set that deep inside a stack, not protect your structures. Also why did you remove one of the `restore_funccal` calls?

**Comment by tarruda** [comment]
> As I said it should not have may_garbage_collect set that deep inside a stack, not protect your structures

Here's the output of `ag may_garbage_collect`:

```
nvim/globals.h
349: * "may_garbage_collect" when we are at the toplevel.
354:EXTERN int may_garbage_collect INIT(= FALSE);

nvim/getchar.c
1334:  if (may_garbage_collect)
1375:  if (may_garbage_collect && want_garbage_collect)
1499:   * In the main loop "may_garbage_collect" can be set to do garbage
1503:  may_garbage_collect = FALSE;

nvim/eval.c
5612:  may_garbage_collect = false;

nvim/normal.c
1371:  // "may_garbage_collect" is reset in vgetc() which is invoked through
1373:  may_garbage_collect = s->toplevel;
```

In other words, `may_garbage_collect` is only set `s->toplevel == true` call. Here's the output of `ag normal_enter`:

```
nvim/ex_docmd.c
6547:        normal_enter(false, true);

nvim/main.c
537:  normal_enter(false, false);

nvim/README.md
139:2. `main()` function(main.c). After all startup, `normal_enter` is called
141:3. `normal_enter()` function(normal.c) is a small wrapper for setting

nvim/ex_getln.c
5064:  normal_enter(true, false);

nvim/normal.c
463:void normal_enter(bool cmdwin, bool noexmode)
```

The only place it is called with both arguments false is at the main function. The only other place where `s->toplevel` could be true is at `normal_cmd` calls, `ag '\bnormal_cmd\('`

```
nvim/search.c
1176:      *dircp = dirc;            /* restore second '/' or '?' for normal_cmd() */

nvim/spell.c
8543:    // don't delay for 'smd' in normal_cmd()

nvim/ex_docmd.c
7793:   * Execute normal_cmd() until there is no typeahead left.
7801:    normal_cmd(&oa, TRUE);      /* execute a Normal mode cmd */

nvim/getchar.c
1284:      normal_cmd(&oa, FALSE);           /* execute one command */

nvim/main.c
522:   * call normal_cmd(), which will then start Insert mode. */

nvim/option.c
3626:   * at the end of normal_cmd() */

nvim/window.c
75: * all CTRL-W window commands are handled here, called from normal_cmd().

nvim/message.c
99: *               Used in normal_cmd() before the mode message is drawn.

nvim/normal.c
479:  // we return from normal_cmd() and come back here, the "3" is remembered in
1372:  // do_exmode() and normal_cmd().
3375: * scrolled.  Called from normal_cmd() and edit().
7704:void normal_cmd(oparg_T *oap, bool toplevel)
```

So the problem could be fixed by changing `normal_cmd(&oa, TRUE)` to `normal_cmd(&oa, false)`

**Comment by ZyX-I** [comment]
@tarruda In `try_to_free_memory` `garbage_collect` call is harmful: I described why in https://github.com/neovim/neovim/issues/3588#issuecomment-153498800. I think it should be removed from there. But here the problem is that you had a case with more then 29 levels in stack (backtrace from #3588 describing where `garbage_collect` was called and memory was freed) `may_garbage_collect` appeared to be set to true, while it should be set to true only when running `vgetc` at the top level. This PR is *not* fixing this issue, I am sure it will only hide the bug until garbage_collect will free some other temporary list that will not be referenced anywhere.

As a temporary and easy fix `f_confirm` should set `may_garbage_collect` to `false`.

**Comment by tarruda** [comment]
@oni-link  can you test if this patch fixes the issue? It contains the change to `normal_cmd` call and the suggested fix by @ZyX-I

```diff
diff --git a/src/nvim/ex_docmd.c b/src/nvim/ex_docmd.c
index 7b5e393..2ff638e 100644
--- a/src/nvim/ex_docmd.c
+++ b/src/nvim/ex_docmd.c
@@ -7764,7 +7764,7 @@ void exec_normal_cmd(char_u *cmd, int remap, bool silent)
   while ((!stuff_empty() || (!typebuf_typed() && typebuf.tb_len > 0))
          && !got_int) {
     update_topline_cursor();
-    normal_cmd(&oa, TRUE);      /* execute a Normal mode cmd */
+    normal_cmd(&oa, false);      /* execute a Normal mode cmd */
   }
 }

diff --git a/src/nvim/memory.c b/src/nvim/memory.c
index d25dc7c..6d386f3 100644
--- a/src/nvim/memory.c
+++ b/src/nvim/memory.c
@@ -42,8 +42,6 @@ void try_to_free_memory(void)
   clear_sb_text();
   // Try to save all buffers and release as many blocks as possible
   mf_release_all();
-  // cleanup recursive lists/dicts
-  garbage_collect();

   trying_to_free = false;
 }
```

**Comment by oni-link** [comment]
> Also why did you remove one of the restore_funccal calls?

@ZyX-I , the last `save_funccal()` needs a `restore_funccal()` that set `current_funccal` to it's old value. This keeps the `ga_array` intact. The replaced call to `restore_funccal()` does not do this.

**Comment by oni-link** [comment]
@tarruda, no the patch does not fix it:
```c
==15787==ERROR: AddressSanitizer: heap-use-after-free on address 0x60800016eb30 at pc 0x000000d9f185 bp 0x7fff36a94500 sp 0x7fff36a944f8
READ of size 4 at 0x60800016eb30 thread T0
    #0 0xd9f184 in list_unref /home/oni-link/git/neovim/src/nvim/eval.c:4842:20
    #1 0xdb8993 in clear_tv /home/oni-link/git/neovim/src/nvim/eval.c:17867:7
    #2 0xdd4f34 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7502:5
    #3 0xe77281 in eval7 /home/oni-link/git/neovim/src/nvim/eval.c:4211:15
    #4 0xe72ea5 in eval6 /home/oni-link/git/neovim/src/nvim/eval.c:3921:7
    #5 0xe70072 in eval5 /home/oni-link/git/neovim/src/nvim/eval.c:3773:7
    #6 0xe6b4e4 in eval4 /home/oni-link/git/neovim/src/nvim/eval.c:3517:7
    #7 0xe6aa63 in eval3 /home/oni-link/git/neovim/src/nvim/eval.c:3437:7
    #8 0xe6a003 in eval2 /home/oni-link/git/neovim/src/nvim/eval.c:3374:7
    #9 0xdb9a52 in eval1 /home/oni-link/git/neovim/src/nvim/eval.c:3307:7
    #10 0xdb73cc in eval0 /home/oni-link/git/neovim/src/nvim/eval.c:3269:9
    #11 0xe4571c in ex_return /home/oni-link/git/neovim/src/nvim/eval.c:20607:10
    #12 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #13 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #14 0xdf464a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #15 0xdc0931 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #16 0xe58cd2 in eval_call_provider /home/oni-link/git/neovim/src/nvim/eval.c:21713:9
    #17 0x5a315e in script_host_execute /home/oni-link/git/neovim/src/nvim/ex_cmds2.c:3309:11
    #18 0x5a2a91 in ex_python /home/oni-link/git/neovim/src/nvim/ex_cmds2.c:784:3
    #19 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #20 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #21 0xdf464a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #22 0xdc0931 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #23 0xdd4e14 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #24 0xdcf27b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #25 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #26 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #27 0xdf464a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #28 0xdc0931 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #29 0xdd4e14 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #30 0xdcf27b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #31 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #32 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #33 0xdf464a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #34 0xdc0931 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #35 0xdd4e14 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #36 0xdcf27b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #37 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #38 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #39 0x824b87 in apply_autocmds_group /home/oni-link/git/neovim/src/nvim/fileio.c:6588:5
    #40 0x81500a in apply_autocmds /home/oni-link/git/neovim/src/nvim/fileio.c:6207:10
    #41 0x164f1a4 in cursorhold_event /home/oni-link/git/neovim/src/nvim/os/input.c:79:3
    #42 0x1721f8f in queue_process_events /home/oni-link/git/neovim/src/nvim/event/queue.c:142:7
    #43 0x1047c74 in nv_event /home/oni-link/git/neovim/src/nvim/normal.c:7692:3
    #44 0xfea124 in normal_execute /home/oni-link/git/neovim/src/nvim/normal.c:1153:3
    #45 0x1245a43 in state_enter /home/oni-link/git/neovim/src/nvim/state.c:55:26
    #46 0xfa10b0 in normal_enter /home/oni-link/git/neovim/src/nvim/normal.c:470:3
    #47 0xf6d43e in main /home/oni-link/git/neovim/src/nvim/main.c:537:3
    #48 0x7f11f0f7c72f in __libc_start_main (/lib64/libc.so.6+0x2072f)
    #49 0x442ff8 in _start (/home/oni-link/git/neovim/build/bin/nvim+0x442ff8)

0x60800016eb30 is located 16 bytes inside of 88-byte region [0x60800016eb20,0x60800016eb78)
freed by thread T0 here:
    #0 0x4db6a0 in __interceptor_cfree.localalias.1 /home/oni-link/git/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:35
    #1 0xac7e54 in xfree /home/oni-link/git/neovim/src/nvim/memory.c:106:3
    #2 0xddd697 in list_free /home/oni-link/git/neovim/src/nvim/eval.c:4874:3
    #3 0xde7ee8 in free_unref_items /home/oni-link/git/neovim/src/nvim/eval.c:5743:7
    #4 0xda2766 in garbage_collect /home/oni-link/git/neovim/src/nvim/eval.c:5678:16
    #5 0x1188b8f in before_blocking /home/oni-link/git/neovim/src/nvim/getchar.c:1335:5
    #6 0x164b503 in os_inchar /home/oni-link/git/neovim/src/nvim/os/input.c:110:9
    #7 0x109deb2 in get_keystroke /home/oni-link/git/neovim/src/nvim/misc1.c:2384:9
    #8 0x1633e7c in do_dialog /home/oni-link/git/neovim/src/nvim/message.c:2673:9
    #9 0xe90e87 in f_confirm /home/oni-link/git/neovim/src/nvim/eval.c:8474:28
    #10 0xdc0ea1 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7643:11
    #11 0xdd4e14 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #12 0xe77281 in eval7 /home/oni-link/git/neovim/src/nvim/eval.c:4211:15
    #13 0xe72ea5 in eval6 /home/oni-link/git/neovim/src/nvim/eval.c:3921:7
    #14 0xe70072 in eval5 /home/oni-link/git/neovim/src/nvim/eval.c:3773:7
    #15 0xe6b4e4 in eval4 /home/oni-link/git/neovim/src/nvim/eval.c:3517:7
    #16 0xe6aa63 in eval3 /home/oni-link/git/neovim/src/nvim/eval.c:3437:7
    #17 0xe6a003 in eval2 /home/oni-link/git/neovim/src/nvim/eval.c:3374:7
    #18 0xdb9a52 in eval1 /home/oni-link/git/neovim/src/nvim/eval.c:3307:7
    #19 0xdb73cc in eval0 /home/oni-link/git/neovim/src/nvim/eval.c:3269:9
    #20 0xdbd918 in eval_expr /home/oni-link/git/neovim/src/nvim/eval.c:1149:7
    #21 0x1667222 in vim_eval /home/oni-link/git/neovim/src/nvim/api/vim.c:149:27
    #22 0x51c227 in handle_vim_eval /home/oni-link/git/neovim/build/src/nvim/auto/msgpack_dispatch.c:906:15
    #23 0x16d517a in on_request_event /home/oni-link/git/neovim/src/nvim/msgpack_rpc/channel.c:481:19
    #24 0x1721f8f in queue_process_events /home/oni-link/git/neovim/src/nvim/event/queue.c:142:7
    #25 0x16ca647 in channel_send_call /home/oni-link/git/neovim/src/nvim/msgpack_rpc/channel.c:223:3
    #26 0xeda451 in f_rpcrequest /home/oni-link/git/neovim/src/nvim/eval.c:14063:19
    #27 0xdc0ea1 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7643:11
    #28 0xdf9acd in func_call /home/oni-link/git/neovim/src/nvim/eval.c:8238:9
    #29 0xe8cfe1 in f_call /home/oni-link/git/neovim/src/nvim/eval.c:8279:9
    #30 0xdc0ea1 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7643:11
    #31 0xdd4e14 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #32 0xe77281 in eval7 /home/oni-link/git/neovim/src/nvim/eval.c:4211:15
    #33 0xe72ea5 in eval6 /home/oni-link/git/neovim/src/nvim/eval.c:3921:7
    #34 0xe70072 in eval5 /home/oni-link/git/neovim/src/nvim/eval.c:3773:7
    #35 0xe6b4e4 in eval4 /home/oni-link/git/neovim/src/nvim/eval.c:3517:7
    #36 0xe6aa63 in eval3 /home/oni-link/git/neovim/src/nvim/eval.c:3437:7
    #37 0xe6a003 in eval2 /home/oni-link/git/neovim/src/nvim/eval.c:3374:7
    #38 0xdb9a52 in eval1 /home/oni-link/git/neovim/src/nvim/eval.c:3307:7
    #39 0xdb73cc in eval0 /home/oni-link/git/neovim/src/nvim/eval.c:3269:9
    #40 0xe4571c in ex_return /home/oni-link/git/neovim/src/nvim/eval.c:20607:10
    #41 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #42 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #43 0xdf464a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #44 0xdc0931 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #45 0xe58cd2 in eval_call_provider /home/oni-link/git/neovim/src/nvim/eval.c:21713:9
    #46 0x5a315e in script_host_execute /home/oni-link/git/neovim/src/nvim/ex_cmds2.c:3309:11
    #47 0x5a2a91 in ex_python /home/oni-link/git/neovim/src/nvim/ex_cmds2.c:784:3
    #48 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #49 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #50 0xdf464a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #51 0xdc0931 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #52 0xdd4e14 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #53 0xdcf27b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #54 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #55 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #56 0xdf464a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #57 0xdc0931 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #58 0xdd4e14 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #59 0xdcf27b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #60 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #61 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #62 0xdf464a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #63 0xdc0931 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #64 0xdd4e14 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #65 0xdcf27b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #66 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #67 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #68 0x824b87 in apply_autocmds_group /home/oni-link/git/neovim/src/nvim/fileio.c:6588:5
    #69 0x81500a in apply_autocmds /home/oni-link/git/neovim/src/nvim/fileio.c:6207:10
    #70 0x164f1a4 in cursorhold_event /home/oni-link/git/neovim/src/nvim/os/input.c:79:3
    #71 0x1721f8f in queue_process_events /home/oni-link/git/neovim/src/nvim/event/queue.c:142:7
    #72 0x1047c74 in nv_event /home/oni-link/git/neovim/src/nvim/normal.c:7692:3
    #73 0xfea124 in normal_execute /home/oni-link/git/neovim/src/nvim/normal.c:1153:3
    #74 0x1245a43 in state_enter /home/oni-link/git/neovim/src/nvim/state.c:55:26
    #75 0xfa10b0 in normal_enter /home/oni-link/git/neovim/src/nvim/normal.c:470:3
    #76 0xf6d43e in main /home/oni-link/git/neovim/src/nvim/main.c:537:3
    #77 0x7f11f0f7c72f in __libc_start_main (/lib64/libc.so.6+0x2072f)

previously allocated by thread T0 here:
    #0 0x4db9b0 in calloc /home/oni-link/git/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:56
    #1 0xac7ef2 in xcalloc /home/oni-link/git/neovim/src/nvim/memory.c:120:15
    #2 0xd9c30a in list_alloc /home/oni-link/git/neovim/src/nvim/eval.c:4813:18
    #3 0x5a2de4 in script_host_execute /home/oni-link/git/neovim/src/nvim/ex_cmds2.c:3303:20
    #4 0x5a2a91 in ex_python /home/oni-link/git/neovim/src/nvim/ex_cmds2.c:784:3
    #5 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #6 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #7 0xdf464a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #8 0xdc0931 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #9 0xdd4e14 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #10 0xdcf27b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #11 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #12 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #13 0xdf464a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #14 0xdc0931 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #15 0xdd4e14 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #16 0xdcf27b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #17 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #18 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #19 0xdf464a in call_user_func /home/oni-link/git/neovim/src/nvim/eval.c:20409:3
    #20 0xdc0931 in call_func /home/oni-link/git/neovim/src/nvim/eval.c:7626:11
    #21 0xdd4e14 in get_func_tv /home/oni-link/git/neovim/src/nvim/eval.c:7492:11
    #22 0xdcf27b in ex_call /home/oni-link/git/neovim/src/nvim/eval.c:2782:9
    #23 0x1347b90 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2196:5
    #24 0x132692d in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:622:20
    #25 0x824b87 in apply_autocmds_group /home/oni-link/git/neovim/src/nvim/fileio.c:6588:5
    #26 0x81500a in apply_autocmds /home/oni-link/git/neovim/src/nvim/fileio.c:6207:10
    #27 0x164f1a4 in cursorhold_event /home/oni-link/git/neovim/src/nvim/os/input.c:79:3
    #28 0x1721f8f in queue_process_events /home/oni-link/git/neovim/src/nvim/event/queue.c:142:7
    #29 0x1047c74 in nv_event /home/oni-link/git/neovim/src/nvim/normal.c:7692:3
    #30 0xfea124 in normal_execute /home/oni-link/git/neovim/src/nvim/normal.c:1153:3
    #31 0x1245a43 in state_enter /home/oni-link/git/neovim/src/nvim/state.c:55:26
    #32 0xfa10b0 in normal_enter /home/oni-link/git/neovim/src/nvim/normal.c:470:3
    #33 0xf6d43e in main /home/oni-link/git/neovim/src/nvim/main.c:537:3
    #34 0x7f11f0f7c72f in __libc_start_main (/lib64/libc.so.6+0x2072f)

SUMMARY: AddressSanitizer: heap-use-after-free /home/oni-link/git/neovim/src/nvim/eval.c:4842:20 in list_unref

```

**Comment by ZyX-I** [comment]
Note that in the stack where it is freed `normal_enter` appears only once, near the very start. And steps to reproduce this bug include not typing anything until `confirm` call, so `may_garbage_collect` cannot be unset in a `vgetc()`. I think you need to set it to false, but not sure whether it should go to `do_dialog` or `get_keystroke`.

**Comment by tarruda** [comment]
@oni-link After looking more carefully at the stack trace I can understand the problem. It is as @ZyX-I suggested: `may_garbage_collect` needs to be set to false before executing events:

```diff
diff --git a/src/nvim/normal.c b/src/nvim/normal.c
index fce3558..d6bc416 100644
--- a/src/nvim/normal.c
+++ b/src/nvim/normal.c
@@ -7701,6 +7701,16 @@ static void nv_open(cmdarg_T *cap)
 // Handle an arbitrary event in normal mode
 static void nv_event(cmdarg_T *cap)
 {
+  // Garbage collection should have been executed before blocking for events in
+  // the `os_inchar` in `state_enter`, but we also disable it here in case the
+  // `os_inchar` branch was not executed(!queue_empty(loop.events), which could
+  // have `may_garbage_collect` set to true in `normal_check`).
+  //
+  // That is because here we may run code that calls `os_inchar`
+  // later(`f_confirm` or `get_keystroke` for example), but in these cases it is
+  // not safe to perform garbage collection because there could be unreferenced
+  // lists or dicts being used.
+  may_garbage_collect = false;
   queue_process_events(loop.events);
   cap->retval |= CA_COMMAND_BUSY;       // don't call edit() now
 }
```

Can you try this one and if it fixes, update the PR(also integrating the previous patch, which removes the `garbage_collect()` call in `try_to_free_memory()`?

**Comment by tarruda** [comment]
I wonder if we should make `f_garbagecollect()` a no-op? We already know it is only safe to do it in the top level, the only thing this function does is set `want_garbage_collect` which would result in garbage collection in the top level even if there are queued characters. I can see no use case for this function.

**Comment by oni-link** [comment]
@tarruda, your patch fixes the problem. Should this diff also be included from your first patch?
```diff
diff --git a/src/nvim/ex_docmd.c b/src/nvim/ex_docmd.c
index 7b5e393..2ff638e 100644
--- a/src/nvim/ex_docmd.c
+++ b/src/nvim/ex_docmd.c
@@ -7764,7 +7764,7 @@ void exec_normal_cmd(char_u *cmd, int remap, bool silent)
   while ((!stuff_empty() || (!typebuf_typed() && typebuf.tb_len > 0))
          && !got_int) {
     update_topline_cursor();
-    normal_cmd(&oa, TRUE);      /* execute a Normal mode cmd */
+    normal_cmd(&oa, false);      /* execute a Normal mode cmd */
   }
 }

```

**Comment by tarruda** [comment]
> Should this diff also be included from your first patch?

Here's my analysis of `ag s->toplevel`:

```
nvim/normal.c
514:  if (s->toplevel && readbuf1_empty()) {
839:    if (s->toplevel && readbuf1_empty()) {
941:  if (curwin->w_p_scb && s->toplevel) {
946:  if (curwin->w_p_crb && s->toplevel) {
1053:  if (s->toplevel && readbuf1_empty()) {
1373:  may_garbage_collect = s->toplevel;
```

At first sight it may seem fine to remove the second argument of `normal_cmd` and set s->toplevel to false because `:normal` can't execute events, but three of these conditions are used for setting `v:count` in expression mappings(`: :map-expression`) and `:normal` can map commands(setting s->toplevel would break v:count for expression mappings reached from `:normal`). The other two conditions are used for scrollbind/cursorbind which I think are fine to ignore while in `:normal`.

This does bring another issue: mappings can execute arbitrary functions which could call `garbagecollect()`. This could result in garbage collection in the next vgetc call while processing `:normal`, and consequently trigger the use-after-free bug. Another possible issue can arise if it is possible for an expression mapping to force a `os_inchar` call(get characters from the user) bypassing the typeahead buffers(possibly through `f_confirm`?).

My guess is that the `toplevel` parameter in `normal_cmd` is being reused for too many things, we may need to introduce another flag to `NormalState` that controls if `v:count` is set independently from `s->toplevel`.

I could be missing something though. @ZyX-I what are your thoughts?

**Comment by tarruda** [comment]
About my previous comment, let me worry about it later. For now, feel free to merge this PR as it is(Just need to update PR title)

File: src/nvim/memory.c [hunk 1]
```diff
@@ -42,8 +42,6 @@ void try_to_free_memory(void)
   clear_sb_text();
   // Try to save all buffers and release as many blocks as possible
   mf_release_all();
-  // cleanup recursive lists/dicts
-  garbage_collect();
```
Comment (ZyX-I) [inline src/nvim/memory.c]: I think that this part should be present in the same commit which marks Vim patch 916 present.

Comment (oni-link) [inline src/nvim/memory.c]: I add a vim-patch commit.

**Comment by justinmk** [comment]
> I am wondering whether it is permitted to change the description of the patch: 

Yes. In fact I'd say you own the copyright on that patch.

**Comment by oni-link** [comment]
@ZyX-I , should I add a "This patch actually fixes a use-after-free" remark to the vim-patch or should I change the problem description?

**Comment by ZyX-I** [comment]
@oni-link This question needs to be asked to those who invented the current convention.

**Comment by justinmk** [comment]
Treat the patch as a normal Neovim patch which also updates version.c. The patch originated from ZyX, he's the author, the commit message does not need to reflect the vim patch.

**Comment by oni-link** [comment]
Updated the commit message for the patch related to vim-patch 7.4.916.
