### PR TITLE
fix(marktree): correct qsort usage

### LINKED ISSUE #25145: SIGABRT in `marktree.c`
### Problem

_I apologize if this isn't the right way to report this kind of crashes. I haven't been able to pinpoint exactly what's causing these errors._

After updating Neovim yesterday (which I did after https://github.com/neovim/neovim/commit/7a76fb8547548304450b59624f9c75a554396504), I've been having regular crashes where Neovim will just SIGABRT. It seems to happen when I'm saving a file that has errors.

### Steps to reproduce

I truly apologize for the lack of repro steps here. I do have the following crash report from the Mac console (all reports have a similar stack trace):

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               nvim [4402]
Path:                  /Users/USER/*/nvim
Identifier:            nvim
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        Exited process [4401]
Responsible:           kitty [837]
User ID:               501

Date/Time:             2023-09-13 09:42:17.5478 -0700
OS Version:            macOS 13.5.2 (22G91)
Report Version:        12
Anonymous UUID:        F3614BE4-6673-C567-7F9D-312F48D5041B

Sleep/Wake UUID:       5583D443-D243-4484-A90B-EA50B88C908F

Time Awake Since Boot: 1600 seconds
Time Since Wake:       325 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   nvim [4402]

Kernel Triage:
VM - (arg = 0x0) pmap_enter retried due to resource shortage


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x191924764 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x19195bc28 pthread_kill + 288
2   libsystem_c.dylib             	       0x191869ae8 abort + 180
3   libsystem_c.dylib             	       0x191868e44 __assert_rtn + 272
4   nvim                          	       0x102ea43b8 marktree_intersect_pair + 560
5   nvim                          	       0x102ea982c marktree_splice + 4180
6   nvim                          	       0x102e36860 extmark_splice_impl + 740
7   nvim                          	       0x102d55a20 del_lines + 560
8   nvim                          	       0x102efed40 op_delete + 2100
9   nvim                          	       0x102f089c0 do_pending_operator + 5060
10  nvim                          	       0x102eea0f8 normal_execute + 10096
11  nvim                          	       0x102fcb5cc state_enter + 160
12  nvim                          	       0x102cda054 main + 15176
13  dyld                          	       0x191603f28 start + 2236

Thread 1:
0   libsystem_kernel.dylib        	       0x19191bf54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x19192e280 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x191924bb8 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x19191c2d0 mach_msg + 24
4   CoreFoundation                	       0x191a3a7e4 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x191a390c4 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x191a384b8 CFRunLoopRunSpecific + 612
7   CoreFoundation                	       0x191abd57c CFRunLoopRun + 64
8   nvim                          	       0x102cd5580 uv__cf_loop_runner + 124 (fsevents.c:723)
9   libsystem_pthread.dylib       	       0x19195bfa8 _pthread_start + 148
10  libsystem_pthread.dylib       	       0x191956da0 thread_start + 8

Thread 2:
0   libsystem_pthread.dylib       	       0x191956d8c start_wqthread + 0

Thread 3:
0   libsystem_kernel.dylib        	       0x19191f750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19195c574 _pthread_cond_wait + 1232
2   nvim                          	       0x102cccd34 uv_cond_wait + 32 (thread.c:793)
3   nvim                          	       0x102ca96e4 worker + 272 (threadpool.c:76)
4   libsystem_pthread.dylib       	       0x19195bfa8 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x191956da0 thread_start + 8

Thread 4:
0   libsystem_kernel.dylib        	       0x19191f750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19195c574 _pthread_cond_wait + 1232
2   nvim                          	       0x102cccd34 uv_cond_wait + 32 (thread.c:793)
3   nvim                          	       0x102ca96e4 worker + 272 (threadpool.c:76)
4   libsystem_pthread.dylib       	       0x19195bfa8 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x191956da0 thread_start + 8

Thread 5:
0   libsystem_kernel.dylib        	       0x19191f750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19195c574 _pthread_cond_wait + 1232
2   nvim                          	       0x102cccd34 uv_cond_wait + 32 (thread.c:793)
3   nvim                          	       0x102ca96e4 worker + 272 (threadpool.c:76)
4   libsystem_pthread.dylib       	       0x19195bfa8 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x191956da0 thread_start + 8

Thread 6:
0   libsystem_kernel.dylib        	       0x19191f750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19195c574 _pthread_cond_wait + 1232
2   nvim                          	       0x102cccd34 uv_cond_wait + 32 (thread.c:793)
3   nvim                          	       0x102ca96e4 worker + 272 (threadpool.c:76)
4   libsystem_pthread.dylib       	       0x19195bfa8 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x191956da0 thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x000000000000002e   x6: 0x0000000000000001   x7: 0x0000000000000000
    x8: 0x357be99a73fffccb   x9: 0x357be99b9f621c4b  x10: 0xcccccccccccccccd  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000033  x14: 0x0000000000000003  x15: 0x0000000000000000
   x16: 0x0000000000000148  x17: 0x00000001f15033a0  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x00000001ec9de080  x21: 0x0000000000000103  x22: 0x00000001ec9de160  x23: 0x00000001030c2885
   x24: 0x00000001ea08a000  x25: 0x000000016d241520  x26: 0x000000011f7214a0  x27: 0x0000000000000000
   x28: 0x0000000000000004   fp: 0x000000016d2410f0   lr: 0x000000019195bc28
    sp: 0x000000016d2410d0   pc: 0x0000000191924764 cpsr: 0x40001000
   far: 0x00000001036c0000  esr: 0x56000080  Address size fault

Binary Images:
       0x102bbc000 -        0x1030ebfff nvim (*) <41573c74-7648-3783-b6c9-ce2fffab39c2> /Users/USER/*/nvim
       0x10330c000 -        0x103317fff libintl.8.dylib (*) <2b7b2fac-969c-3b08-82a1-a60bb7156b81> /opt/homebrew/*/libintl.8.dylib
       0x103c18000 -        0x103c23fff lua.so (*) <edb68822-13a8-3a43-85b8-848edac9cb3a> /Users/USER/*/lua.so
       0x104c60000 -        0x104d8ffff vim.so (*) <ccc30a21-e369-3bdb-bdf6-8670c8d543ac> /Users/USER/*/vim.so
       0x19191b000 -        0x191954ff7 libsystem_kernel.dylib (*) <08c5fe2a-b0bf-3ab6-bb42-460c18917d33> /usr/lib/system/libsystem_kernel.dylib
       0x191955000 -        0x191961fff libsystem_pthread.dylib (*) <1f30fb9a-bdf9-32db-a709-8417666a7e45> /usr/lib/system/libsystem_pthread.dylib
       0x1917f3000 -        0x191871ff7 libsystem_c.dylib (*) <949943e2-52cb-3c95-ab08-7ed984333d03> /usr/lib/system/libsystem_c.dylib
       0x1915fe000 -        0x19168c587 dyld (*) <e7a99595-e0f8-34af-be8b-9347d0d658a4> /usr/lib/dyld
       0x1919bb000 -        0x191e94fff com.apple.CoreFoundation (6.9) <b3b2df49-2db8-370e-84ae-e0a2704515b8> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=920.9M resident=0K(0%) swapped_out_or_unallocated=920.9M(100%)
Writable regions: Total=1.9G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.9G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           298.2M       39 
MALLOC guard page                   96K        4 
MALLOC_MEDIUM (reserved)           1.2G       10         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        7 
Stack                             48.7M        7 
VM_ALLOCATE                       47.9M      384 
__AUTH                             309K       58 
__AUTH_CONST                      3713K      142 
__DATA                            1691K      140 
__DATA_CONST                      4226K      147 
__DATA_DIRTY                       361K       58 
__LINKEDIT                       803.8M        5 
__OBJC_RO                         66.4M        1 
__OBJC_RW                         2012K        1 
__TEXT                           117.2M      154 
dyld private memory                272K        2 
shared memory                       32K        2 
===========                     =======  ======= 
TOTAL                              3.0G     1164 
TOTAL, minus reserved VM space     1.4G     1164 
```

### Expected behavior

For Neovim to not crash.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1102+gdf1e91982

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Mac Ventura 13.5.2

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

From source

### PR DESCRIPTION
**Pull request by llllvvuu**
fixes #25145

> The application shall ensure that the function returns an integer less
than, equal to, or greater than 0, if the first argument is considered
respectively less than, equal to, or greater than the second. If two
members compare as equal, their order in the sorted array is unspecified.

https://pubs.opengroup.org/onlinepubs/009696899/functions/qsort.html

### CODE REVIEW

File: src/nvim/marktree.c [hunk 1]
```diff
@@ -2267,7 +2273,7 @@ void mt_inspect_dotfile_node(MarkTree *b, garray_T *ga, MTNode *n, MTPos off, ch
   if (parent != NULL) {
     snprintf(namebuf, sizeof namebuf, "%s_%c%d", parent, 'a' + n->level, n->p_idx);
   } else {
-    snprintf(namebuf, sizeof namebuf, "Node");
```
Comment (llllvvuu) [inline src/nvim/marktree.c:2270]: This is because "Node" is a reserved word in Graphviz.

File: src/nvim/marktree.c [hunk 2]
```diff
@@ -1626,7 +1626,12 @@ static int damage_cmp(const void *s1, const void *s2)
 {
   Damage *d1 = (Damage *)s1, *d2 = (Damage *)s2;
   assert(d1->id != d2->id);
-  return d1->id > d2->id;
+  if (d1->id < d2->id) {
```
Comment (bfredl) [inline src/nvim/marktree.c:1629]: given the assert above, `return d1->id > d2->id ? 1 : -1` would be enough.

Comment (llllvvuu) [reply src/nvim/marktree.c]: Amen

**Comment by bfredl** [comment]
Thanks!
