### PR TITLE
vim-patch:8.2.{3684,3687}: blockwise insert does not handle autoindent properly

### LINKED ISSUE #9229: Vim9: leaving colon in 'indentkeys' breaks blockwise edition of dictionary containing lambdas
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var lines =<< trim END
            var d = {
            a: () => 0,
            b: () => 0,
            c: () => 0,
            }
        END
        lines->setline(1)
        filetype indent on
        &filetype = 'vim'
        execute "normal! jf)\<C-V>jjA: number"
    EOF
    )

The buffer contains this:

    var d = {
            a: (): number => 0,
    b: ()   a: (): number => 0,
    c: ()   a: (): number => 0,
    }

**Expected behavior**

The buffer contains this:

    var d = {
    a: (): number => 0,
    b: (): number => 0,
    c: (): number => 0,
    }

**Operating system**

Ubuntu 20.04.3 LTS

**Version of Vim**

8.2 Included patches: 1-3682

**Additional Context**

The issue comes from the `:` item in the value of the `'indentkeys'` option.

From `:help indentkeys-format`:

   > ":"      if you type ':' after a label or case statement

AFAIK, there is no label or case statement in Vim script.

Can we drop `:`?  If we do, the issue is fixed:
```diff
diff --git a/runtime/indent/vim.vim b/runtime/indent/vim.vim
index d5d0d94b5..3f0c17a3b 100644
--- a/runtime/indent/vim.vim
+++ b/runtime/indent/vim.vim
@@ -12,6 +12,7 @@ let b:did_indent = 1
 setlocal indentexpr=GetVimIndent()
 setlocal indentkeys+==end,=},=else,=cat,=finall,=END,0\\,0=\"\\\ 
 setlocal indentkeys-=0#
+setlocal indentkeys-=:
 
 let b:undo_indent = "setl indentkeys< indentexpr<"
 
```

### PR DESCRIPTION
**Pull request by clason**
Problem:    Blockwise insert does not handle autoindent properly.
Solution:   Adjust text column for indent. (closes vim/vim#9229)
https://github.com/vim/vim/commit/e9b0b40b7978f683977922233b42dd439ef31920

Problem:    Blockwise insert does not handle autoindent properly when tab is inserted.
Solution:   Adjust text column for indent before computing column.
            (closes vim/vim#9229)
https://github.com/vim/vim/commit/59f4f9505ae7ca2499904b94100db103e5ada5a6

### CODE REVIEW

File: src/nvim/ops.c [hunk 1]
```diff
@@ -2311,6 +2311,13 @@ void op_insert(oparg_T *oap, long count1)
         }
       }
       bd.textcol = bd2.textcol;
+      /*
+       * If the insert was in the indent then include the indent
+       * change in the new text, otherwise don't.
+       */
+      if (did_indent && bd.textcol > ind_pre) {
+          bd.textcol += ind_post - ind_pre;
+      }
```
Comment (zeertzjq) [inline src/nvim/ops.c:2320]:
```suggestion
      if (did_indent && bd.textcol > ind_pre) {
          // If the insert was in the indent then include the indent
          // change in the new text, otherwise don't.
          bd.textcol += ind_post - ind_pre;
      }
```

Comment (clason) [reply src/nvim/ops.c:2320]: Man, did I get the style guide wrong 🤦🏻 

(Sorry, @dundargoc !)

**Comment by zeertzjq** [comment]
There is another patch with the same message
<https://github.com/vim/vim/commit/59f4f9505ae7ca2499904b94100db103e5ada5a6>

**Review by zeertzjq — APPROVED** [review]
