### PR TITLE
fix(env.c): drop envmap, callers must free os_getenv() result

### LINKED ISSUE #32550: vim.uv.os_setenv / vim.uv.os_unsetenv doesn't seem to work much at all
### Problem

vim.uv.os_setenv seems to only get called once per-key.

### Steps to reproduce

`nvim -u NONE`

```
:echo $FOO  <-- prints nothing
:lua vim.uv.os_setenv("FOO", "bar")
:echo $FOO  <-- prints bar (as expected)
:lua vim.uv.os_setenv("FOO", "fizz")
:echo $FOO  <-- prints bar, still (not expected. Should be "fizz")
:lua vim.uv.os_unsetenv("FOO")
:echo $FOO  <-- prints bar, still (not expected. Should be nothing)
:lua vim.uv.os_setenv("FOO", "buzz")
:echo $FOO  <-- prints bar, still (not expected. Should be "buzz")
```

You can basically set an environment variable once per key and find this issue. e.g. you can set FOO and BAR in a session once but then the value appears "stuck"

### Expected behavior

`vim.uv.os_unsetenv` should unset the environment variable. And I assume setting and changing an environment variable using `:lua vim.uv.os_setenv` should be possible without needing to call `vim.uv.os_unsetenv` first. But idk libuv well so could be wrong.

### Nvim version (nvim -v)

Linux: NVIM v0.11.0-dev-1723+ge6b84fab83
Windows: NVIM v0.10.4

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Linux and Windows

### Terminal name/version

tmux

### $TERM environment variable

screen-256color

### Installation

Linux (from source) / Windows (from .msi)

### PR DESCRIPTION
**Pull request by juditnovak**
## Problem

Inconsistency in terms of dynamic environment variable changes. The problem relates an internal cache, that may not be available for all necessary access. 

## Solution

Following the suggesiton from [comment](https://github.com/neovim/neovim/issues/32550#issuecomment-2674327903) by @justinmk , the internal cache is removed.

Note: removing the cache implies memory allocation on occasions when `os_getenv()` is called. Corresponding memory has to be `xfree()`-d after.

fix  https://github.com/neovim/neovim/issues/32550

### CODE REVIEW

**Comment by juditnovak** [comment]
@justinmk Thanks for noticing my contribution here :-) 
May I ask, what does the "needs:response" label stand for? I couldn't find a question (this PR, referred issue, etc.) but I wonder if it may have potential further meaning? Thx in advance.

File: src/nvim/os/env.c [hunk 1]
```diff
@@ -429,6 +411,7 @@ void init_homedir(void)
   homedir = NULL;
 
   const char *var = os_getenv("HOME");
+  const char *setmefree = var;
```
Comment (justinmk) [inline src/nvim/os/env.c:414]: `must_free` seems like the most common name in the codebase
```suggestion
  const char *must_free = var;
```

File: src/nvim/os/env.c [hunk 2]
```diff
@@ -919,7 +892,9 @@ char *vim_getenv(const char *name)
 
   const char *kos_env_path = os_getenv(name);
   if (kos_env_path != NULL) {
-    return xstrdup(kos_env_path);
+    char *retval = xstrdup(kos_env_path);
+    xfree((char *)kos_env_path);
```
Comment (justinmk) [inline src/nvim/os/env.c:896]: this kind of casting is never done for free() in this codebase. sometimes a `(void *)` cast is needed, but otherwise unless the build fails, don't cast.

Comment (justinmk) [reply src/nvim/os/env.c:896]:
```suggestion
    xfree(kos_env_path);
```

File: src/nvim/msgpack_rpc/server.c [hunk 3]
```diff
@@ -120,12 +126,12 @@ char *server_address_new(const char *name)
   static uint32_t count = 0;
   char fmt[ADDRESS_MAX_SIZE];
 #ifdef MSWIN
-  (void)get_appname(true);
+  appname_init_namebuf();
```
Comment (justinmk) [inline src/nvim/msgpack_rpc/server.c:129]: don't think we need a new `appname_init_namebuf` function. just modify `get_appname` somehow.

File: src/nvim/os/env.c [hunk 4]
```diff
@@ -52,10 +52,6 @@
 # include "os/env.c.generated.h"
 #endif
 
-// Because `uv_os_getenv` requires allocating, we must manage a map to maintain
-// the behavior of `os_getenv`.
-static PMap(cstr_t) envmap = MAP_INIT;
-
 /// Like getenv(), but returns NULL if the variable is empty.
```
Comment (justinmk) [inline src/nvim/os/env.c:55]: /// Caller must free the return value.

File: src/nvim/mbyte.c [hunk 5]
```diff
@@ -2410,22 +2410,37 @@ char *enc_locale(void)
...
+  const char *setmefree = NULL;
+
 #ifdef HAVE_NL_LANGINFO_CODESET
   if (!(s = nl_langinfo(CODESET)) || *s == NUL)
 #endif
   {
     if (!(s = setlocale(LC_CTYPE, NULL)) || *s == NUL) {
       if ((s = os_getenv("LC_ALL"))) {
+        memfree = true;
         if ((s = os_getenv("LC_CTYPE"))) {
```
Comment (justinmk) [inline src/nvim/mbyte.c:2426]: do we need to `xfree(s)` before calling os_getenv again here?

File: src/nvim/mbyte.c [hunk 6]
```diff
@@ -2410,22 +2410,37 @@ char *enc_locale(void)
...
           s = os_getenv("LANG");
         }
       }
     }
   }
 
-  if (!s) {
+  if (s != NULL) {
```
Comment (justinmk) [inline src/nvim/mbyte.c:2433]: Note that `xfree(NULL)` is 100% safe. Does that simplify any of the code in this PR?

File: src/nvim/os/env.c (hunk 2 above)
Comment (juditnovak) [reply src/nvim/os/env.c:896]: The build fails otherwise with the following error:

```
error: passing 'const char *' to parameter of type 'void *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
```
In case there's an alternative solution to avoid it, I'm glad to go with that.

File: src/nvim/msgpack_rpc/server.c (hunk 3 above)
Comment (juditnovak) [reply src/nvim/msgpack_rpc/server.c:129]: Sure, if preferred.

File: src/nvim/mbyte.c (hunk 5 above)
Comment (juditnovak) [reply src/nvim/mbyte.c:2426]: Totally, very good call, thank you.

**Comment by juditnovak** [comment]
@justinmk Thanks very much for the review.

I had a question while working on this code. Isn't it an "overkill" to add the amount of (sensitive) changes to fix an --after all-- small issue? In case your judgement is to rather have this change, I'm more than happy to polish it to perfect :-)
(I'm actively working on tracking down the issue of the windows pipeline.)

File: src/nvim/os/env.c (hunk 4 above)
Comment (juditnovak) [reply src/nvim/os/env.c:55]: Absolutely. Sry, my bad, I thought I added this.

File: src/nvim/os/env.c (hunk 1 above)
Comment (justinmk) [reply src/nvim/os/env.c:414]: > However, don't you agree that it may be conceptually beneficial to distinguish between `bool` and `const [char|int|..] *` deallocation helper variables?

That's a good thought, but unless both kinds are in the same function body, risk of ambiguity/confusion is very low.

File: src/nvim/os/os_win_console.c [hunk 7]
```diff
@@ -117,7 +118,8 @@ void os_title_reset(void)
 /// @param out_fd stdout file descriptor
 void os_tty_guess_term(const char **term, int out_fd)
 {
-  bool conemu_ansi = strequal(os_getenv("ConEmuANSI"), "ON");
+  const char *conemuansi_env = os_getenv("ConEmuANSI");
+  bool conemu_ansi = strequal(conemuansi_env, "ON");
```
Comment (justinmk) [inline src/nvim/os/os_win_console.c:122]: can immediately `xfree(conemuansi_env)` here (also don't need to check NULL).

File: src/nvim/os/stdpaths.c [hunk 8]
```diff
@@ -188,6 +212,9 @@ char *stdpaths_get_xdg_var(const XDGVarType idx)
     ret = xdg_remove_duplicate(ret, ENV_SEPSTR);
   }
 
+  if (memfree) {
```
Comment (justinmk) [inline src/nvim/os/stdpaths.c:215]: could avoid the need for `memfree` by changing line 192 to:

    env_val = xstrdup("");

**Comment by justinmk** [comment]
> Isn't it an "overkill" to add the amount of (sensitive) changes to fix an --after all-- small issue?

I wouldn't say https://github.com/neovim/neovim/issues/32550 is a small issue. It's pointing to a bug I had worried about, and could affect other libraries loaded by nvim.

`envmap` was never really a good solution, and I'm glad you are finally getting rid of it :) It's true that this work is delicate and will require careful review, but we don't really have an alternative.

I think `memfree` can be avoided in some of these cases. Also, if there are many cases that only want to quickly check the result of `os_getenv`, we could add `os_getenv_noalloc` which writes to `NameBuff` (and returns a pointer to it), to save the caller the trouble of freeing the result.

File: src/nvim/os/env.c (hunk 1 above)
Comment (zeertzjq) [reply src/nvim/os/env.c:414]: `tofree`

**Comment by juditnovak** [comment]
@justinmk Thank you very much for additional suggestions and most importantly the confirmation of the value of this work.
I'm very glad it's useful :-)  
Also thanks for the foreseen particularly careful review -- keeps me re-assured :-)

I carry on accordingly, evaluating cases for a potential `os_getenv_noalloc`. Thx very much :-)

File: src/nvim/os/os_win_console.c (hunk 7 above)
Comment (juditnovak) [reply src/nvim/os/os_win_console.c:122]: Here I have a conceptual question, please let me know which policy is preferred:

1. `xfree()` as soon as the var is not used anymore
   - cons: may be fragile, leaving space for future bugs (code change may introduce additional usage of the variable after `xfree()`)
2. have an "`xfree() block" at the end of corresponding scope, de-allocating all occupied memory when it surely won't be needed anymore

Comment (justinmk) [reply src/nvim/os/os_win_console.c:122]: (1) is preferred, especially when it can be done immediately after usage. We have static analyzers running in CI, which will catch use-after-free, so I'm not worried about that (though I would have been in 2014 :).

(2) is for cases where there are multiple usages in the function body, thus grouping all the resource releasing in one place is better.

Comment (juditnovak) [reply src/nvim/os/os_win_console.c:122]: Cool, thx very much for the explanation! Changing the code accordingly.

File: src/nvim/mbyte.c (hunk 5 above)
Comment (juditnovak) [reply src/nvim/mbyte.c:2427]: Should be OK now.

File: src/nvim/os/os_win_console.c (hunk 7 above)
Comment (juditnovak) [reply src/nvim/os/os_win_console.c:122]: Done.

File: src/nvim/mbyte.c (hunk 6 above)
Comment (juditnovak) [reply src/nvim/mbyte.c]: Fixed on all occurences (simplifying the PR).

**Comment by juditnovak** [comment]
Simple changes are applied, pipelines are :green_circle: :tada: 

Making an attempt for `os_getenv_noalloc` in an upcoming commit.

File: src/nvim/msgpack_rpc/server.c [hunk 9]
```diff
@@ -120,12 +125,14 @@ char *server_address_new(const char *name)
   static uint32_t count = 0;
   char fmt[ADDRESS_MAX_SIZE];
 #ifdef MSWIN
-  (void)get_appname(true);
+  const char *appname = get_appname(true);    // Call to initialize NameBuf with appname
+  xfree((char *)appname);
```
Comment (juditnovak) [inline src/nvim/msgpack_rpc/server.c:129]: I'm wondering that this may be the cleanest / most_consistent solution for the two occasions when only `NameBuff` population is needed.

Other alternatives, similar to 
```
const char *get_appname(bool namelike, bool return_value_needed) {
    const char *env_val = os_getenv("NVIM_APPNAME");
    
    [add env val to NameBuff]
 
    if (return_value_needed) {
       return env_val;
    } else {
       // Potential xfree(env_val) here, so caller only needs to free if 
       // no return value is consumed
       return NULL;
    }
}
```
 just feel more confusing (signature, return value, potential side effects)... 
 
 In case there may be a straightforward, elegant solution in mind, I'm glad to go with your suggestion.

File: src/nvim/msgpack_rpc/server.c [hunk 10]
```diff
@@ -120,12 +125,14 @@ char *server_address_new(const char *name)
...
   int r = snprintf(fmt, sizeof(fmt), "\\\\.\\pipe\\%s.%" PRIu64 ".%" PRIu32,
                    name ? name : NameBuff, os_get_pid(), count++);
 #else
   char *dir = stdpaths_get_xdg_var(kXDGRuntimeDir);
-  (void)get_appname(true);
+  const char *appname = get_appname(true);    // Call to initialize NameBuf with appname
+  xfree((char *)appname);
```
Comment (juditnovak) [inline src/nvim/msgpack_rpc/server.c:135]: See [comment](https://github.com/neovim/neovim/pull/32683/files#r1989856185) above.

File: src/nvim/msgpack_rpc/server.c (hunk 9 above)
Comment (juditnovak) [reply src/nvim/msgpack_rpc/server.c:129]: Hmmm.... Or is this assumption correct (mapping to current usage): *either* a return value, *or* data in the `NameBuff` is expected? Never both? 

That could allow for an execution flow as such:
```
const char *get_appname(bool namelike) {
    const char *env_val = os_getenv("NVIM_APPNAME");
    
    if (namelike) {
      [add env val to NameBuff]
      xfree(env_var)
      return NULL
    }
    return env_val;
}
```
If the parameter is expressing exclusive usage of buffer or return value -- then it can make sense if the caller needs to `xfree()` or not accordingly. It's not consistent in terms of side-effects, yet alongside a clear logic.

**Review by zeertzjq — COMMENTED** [review]
In cases where it's not actually using the value of the returned string, the allocation may be unnecessary. How about adding another function that is similar to `os_env_exists()` but checks for empty string?

**Comment by juditnovak** [comment]
@zeertzjq Thanks for your response. `os_env_exists` uses cool trick :-) 
But I'm a bit confused, how to benefit from a similar approach here. Would you suggest to use `uv_os_getenv()` to retrieve the value to `NameBuff` directly? (I apologize if I'm overlooking something obvious...)

**Comment by zeertzjq** [comment]
No, I mean there are some cases where the caller only needs to check if an environment variable is empty. In such cases an allocation can be avoided.

**Comment by zeertzjq** [comment]
I was talking about `vim_mktempdir()` etc.

File: src/nvim/mbyte.c [hunk 11]
```diff
@@ -2410,22 +2410,37 @@ char *enc_locale(void)
 {
   int i;
   char buf[50];
+  bool memfree = false;
 
   const char *s;
```
Comment (justinmk) [inline src/nvim/mbyte.c:2415]: can avoid `memfree`
```suggestion
  const char *s = NULL;
```

File: src/nvim/os/stdpaths.c [hunk 12]
```diff
@@ -161,11 +167,11 @@ char *stdpaths_get_xdg_var(const XDGVarType idx)
 
 #ifdef MSWIN
   if (env_val == NULL && xdg_defaults_env_vars[idx] != NULL) {
-    env_val = os_getenv(xdg_defaults_env_vars[idx]);
+    env_val = os_getenv(xdg_defaults_env_vars[idx]);    // 'env_val' was NULL, no xfree() is needed
```
Comment (justinmk) [inline src/nvim/os/stdpaths.c:170]: probably don't need that comment. lots of places in the codebase like that.

**Comment by juditnovak** [comment]
@zeertzjq Thanks for the clarification, now your message is clear. (The context was confusing, I thought the suggestion was targeting [this issue](https://github.com/neovim/neovim/pull/32683#discussion_r1989856185).)

The existence check only appears on a few occasions, yet I agree that an `os_env_defined()` (similar to `os_env_exists()`) could increase clarity and avoid memory allocation. I'm adding it with in the next round. Thanks.

File: src/nvim/msgpack_rpc/server.c (hunk 9 above)
Comment (justinmk) [reply src/nvim/msgpack_rpc/server.c:129]: Maybe simpler for `get_appname` to *never* allocate its result, instead it always writes to NameBuff (and perhaps for convenience, returns a pointer to it).

Then the caller can `xstrdup(get_appname(..))` if it wants to.

File: src/nvim/option.c [hunk 13]
```diff
@@ -196,6 +196,7 @@ static void set_init_default_shell(void)
     } else {
       set_string_default(kOptShell, (char *)shell, false);
```
Comment (justinmk) [inline src/nvim/option.c:197]: if `_noalloc` were used above, then could do this this here:
```suggestion
      set_string_default(kOptShell, (char *)shell, true);
```

File: src/nvim/os/env.c [hunk 14]
```diff
@@ -932,12 +917,13 @@ char *vim_getenv(const char *name)
   char *vim_path = NULL;
   if (vimruntime
       && *default_vimruntime_dir == NUL) {
-    kos_env_path = os_getenv("VIM");
+    kos_env_path = os_getenv("VIM");    // No xfree() needed for kos_env_path, as it must be NULL if we got here
```
Comment (justinmk) [inline src/nvim/os/env.c:920]:
```suggestion
    kos_env_path = os_getenv("VIM");  // kos_env_path was NULL.
```

File: src/nvim/os/lang.c [hunk 15]
```diff
@@ -70,16 +70,19 @@ char *get_mess_lang(void)
 }
 
 /// Get the language used for messages from the environment.
+/// Result must be freed by the caller.
 ///
 /// This uses LC_MESSAGES when available, which it is for most systems we build for
 /// except for windows. Then fallback to get the value from the environment
 /// ourselves, and use LC_CTYPE as a last resort.
 static char *get_mess_env(void)
```
Comment (justinmk) [inline src/nvim/os/lang.c:78]: will `_noalloc` help here?

File: src/nvim/os/os_win_console.c [hunk 16]
```diff
@@ -117,7 +118,9 @@ void os_title_reset(void)
...
```
Comment (justinmk) [inline src/nvim/os/os_win_console.c:122]: `_noalloc`

File: src/nvim/os/time.c [hunk 17]
```diff
@@ -101,11 +102,19 @@ struct tm *os_localtime_r(const time_t *restrict clock,
   const char *tz = os_getenv("TZ");
   if (tz == NULL) {
     tz = "";
```
Comment (justinmk) [inline src/nvim/os/time.c:104]: xstrdup(), eliminates `memfree`

File: src/nvim/msgpack_rpc/server.c (hunk 9 above)
Comment (juditnovak) [reply src/nvim/msgpack_rpc/server.c:129]: Cool, I agree, it's an elegant solution. Thx, implementing so :-)

File: src/nvim/os/env.c [hunk 18]
```diff
@@ -1229,7 +1219,9 @@ bool os_shell_is_cmdexe(const char *sh)
   }
   if (striequal(sh, "$COMSPEC")) {
     const char *comspec = os_getenv("COMSPEC");
-    return striequal("cmd.exe", path_tail(comspec));
+    bool retval = striequal("cmd.exe", path_tail(comspec));
+    xfree((char *)comspec);
+    return retval;
```
[the remark this answers is not in the document]
Comment (juditnovak) [reply src/nvim/os/env.c:1224]: Exactly. Coming soon :-)

File: src/nvim/os/os_win_console.c (hunk 16 above)
Comment (juditnovak) [reply src/nvim/os/os_win_console.c:122]: Clearly ;-)

File: src/nvim/os/time.c (hunk 17 above)
Comment (juditnovak) [reply src/nvim/os/time.c]: Done.

File: src/nvim/os/lang.c (hunk 15 above)
Comment (juditnovak) [reply src/nvim/os/lang.c:78]: Yes it will, see [PR II.](https://github.com/juditnovak/neovim/pull/1) :-)

File: src/nvim/os/env.c (hunk 18 above)
[the remark this answers is not in the document]
Comment (juditnovak) [reply src/nvim/os/env.c:1224]: Done in [PR II.](https://github.com/juditnovak/neovim/pull/1)

File: src/nvim/os/env.c (hunk 14 above)
Comment (juditnovak) [reply src/nvim/os/env.c]: Done.

**Comment by juditnovak** [comment]
In order to keep individually fully functional stages separate, I've left this PR as a fully "polished" version of `os_getenv()` usage on each occasion.

I'm introducting the code with `os_env_defined()` and `os_getenv_noalloc()` in [PR II.](https://github.com/juditnovak/neovim/pull/1), demonstrating the transition the code discussed here.

File: src/nvim/option.c (hunk 13 above)
Comment (juditnovak) [reply src/nvim/option.c:197]: Technically you are right, `set_string_default()` could change accordingly. 

However, in case we do that, we run into the following problem.

1. In one of the `if` branche we apply `malloc()` for `kOptShell` defaults
2. In the other `if` branch we use statically allocated memory

This becomes an issue when the `free_all_options() -> optval_free()` calls are applied. While 1) would require `xfree()`, 2) would be throwing an error if `xfree()` applied at this point...

File: src/nvim/mbyte.c (hunk 11 above)
Comment (juditnovak) [reply src/nvim/mbyte.c:2415]: I apologize, I'm confused about this one... :-(

The `memfree` is mostly there in case `s` was defined by the `setlocale()` call. In this case --if I understand correctly-- `xfree()` must not be applied. 

I'm sorry if I can't see something obvious here :-(

File: src/nvim/msgpack_rpc/server.c (hunk 9 above)
Comment (juditnovak) [reply src/nvim/msgpack_rpc/server.c]: Done in [PR II.](https://github.com/juditnovak/neovim/pull/1)

File: src/nvim/os/stdpaths.c (hunk 12 above)
Comment (juditnovak) [reply src/nvim/os/stdpaths.c]: Done.

**Comment by juditnovak** [comment]
Added changes from [PR II.](https://github.com/juditnovak/neovim/pull/1), including fixes for comments:
 - @zeertzjq:
  - https://github.com/juditnovak/neovim/pull/1#discussion_r1996402380
  - https://github.com/juditnovak/neovim/pull/1#discussion_r1996402865
 - @justinmk:
  - https://github.com/juditnovak/neovim/pull/1#discussion_r1996825716

File: src/nvim/eval/funcs.c [hunk 19]
```diff
@@ -3939,9 +3939,8 @@ dict_T *create_environment(const dictitem_T *job_env, const bool clear_env, cons
       size_t len = strlen(required_env_vars[i]);
       dictitem_T *dv = tv_dict_find(env, required_env_vars[i], (ptrdiff_t)len);
       if (!dv) {
-        const char *env_var = os_getenv(required_env_vars[i]);
-        if (env_var) {
-          tv_dict_add_str(env, required_env_vars[i], len, env_var);
+        if (os_env_exists(required_env_vars[i], true)) {
+          tv_dict_add_str(env, required_env_vars[i], len, os_getenv(required_env_vars[i]));
```
Comment (zeertzjq) [inline src/nvim/eval/funcs.c:3943]: `tv_dict_add_allocated_str()`

Comment (juditnovak) [reply src/nvim/eval/funcs.c]: Fixed, thanks for noticing.

File: src/nvim/os/env.c [hunk 20]
```diff
@@ -96,32 +82,55 @@ const char *os_getenv(const char *name)
...
+{
+  if (name[0] == NUL) {
+    return NULL;
+  }
+
+  size_t size = sizeof(NameBuff);
+  int r = uv_os_getenv(name, NameBuff, &size);
+  if (r != 0 || size == 0 || NameBuff[0] == NUL) {
+    if (r != 0 && r != UV_ENOENT && r != UV_UNKNOWN) {
+      ELOG("uv_os_getenv_noalloc(%s) failed: %d %s", name, r, uv_err_name(r));
```
Comment (justinmk) [inline src/nvim/os/env.c:105]:
```suggestion
      ELOG("uv_os_getenv(%s) failed: %d %s", name, r, uv_err_name(r));
```

File: src/nvim/os/env.c [hunk 21]
```diff
@@ -96,32 +82,55 @@ const char *os_getenv(const char *name)
...
+char *os_getenv_noalloc(const char *name)
+  FUNC_ATTR_NONNULL_ALL
+{
+  if (name[0] == NUL) {
+    return NULL;
+  }
+
+  size_t size = sizeof(NameBuff);
+  int r = uv_os_getenv(name, NameBuff, &size);
+  if (r != 0 || size == 0 || NameBuff[0] == NUL) {
```
Comment (justinmk) [inline src/nvim/os/env.c:103]: `NameBuff[0] == NUL` seems suspicious, can that actually happen and is it actually a failure?

File: src/nvim/os/env.c [hunk 22]
```diff
@@ -96,32 +82,55 @@ const char *os_getenv(const char *name)
...
+  }
+  return NameBuff;
+}
+
 /// Returns true if environment variable `name` is defined (even if empty).
 /// Returns false if not found (UV_ENOENT) or other failure.
-bool os_env_exists(const char *name)
+///
+/// @param name the environment variable in question
+/// @param defined whether the variable has a valid value, or may be empty
```
Comment (justinmk) [inline src/nvim/os/env.c:116]:
```suggestion
/// @param defined Return true if the env var is defined but empty.
```

File: src/nvim/os/env.c [hunk 23]
```diff
@@ -917,9 +926,9 @@ char *vim_getenv(const char *name)
   }
 #endif
 
-  const char *kos_env_path = os_getenv(name);
+  char *kos_env_path = (char *)os_getenv(name);
```
Comment (justinmk) [inline src/nvim/os/env.c:929]: seems like the retval of `os_getenv` should no longer be `const`. Because we don't have an envmap anymore?

File: src/nvim/os/time.c [hunk 24]
```diff
@@ -98,14 +98,16 @@ struct tm *os_localtime_r(const time_t *restrict clock,
...
+  const char *tz = os_getenv_noalloc("TZ");
+  if (!tz) {
     tz = "";
   }
+
   if (strncmp(tz_cache, tz, sizeof(tz_cache) - 1) != 0) {
     tzset();
     xstrlcpy(tz_cache, tz, sizeof(tz_cache));
   }
+
```
Comment (justinmk) [inline src/nvim/os/time.c:110]: remove

File: test/unit/os/env_spec.lua [hunk 25]
```diff
@@ -34,17 +34,41 @@ describe('env.c', function()
...
+  local function os_getenv_noalloc(name)
+    local rval = cimp.os_getenv_noalloc(to_cstr(name))
+    if rval ~= NULL then
+      return ffi.string(rval)
+    else
+      return NULL
+    end
+  end
+
   itp('os_env_exists', function()
```
Comment (justinmk) [inline test/unit/os/env_spec.lua:46]:
```suggestion
  itp('os_env_exists(…, false)', function()
```

File: src/nvim/os/env.c (hunk 21 above)
Comment (zeertzjq) [reply src/nvim/os/env.c:103]: I think this is for consistency with `os_getenv()`.

File: src/nvim/eval/funcs.c [hunk 26]
```diff
@@ -3939,9 +3939,9 @@ dict_T *create_environment(const dictitem_T *job_env, const bool clear_env, cons
       size_t len = strlen(required_env_vars[i]);
       dictitem_T *dv = tv_dict_find(env, required_env_vars[i], (ptrdiff_t)len);
       if (!dv) {
-        const char *env_var = os_getenv(required_env_vars[i]);
-        if (env_var) {
-          tv_dict_add_str(env, required_env_vars[i], len, env_var);
+        if (os_env_exists(required_env_vars[i], true)) {
+          tv_dict_add_allocated_str(env, required_env_vars[i], len,
+                                    os_getenv_noalloc(required_env_vars[i]));
```
Comment (justinmk) [inline src/nvim/eval/funcs.c:3944]: `tv_dict_add_allocated_str` requires an alloc'd string

File: src/nvim/os/env.c (hunk 22 above)
Comment (zeertzjq) [reply src/nvim/os/env.c:116]: I think that's `false`, not `true`.

File: src/nvim/os/env.c (hunk 21 above)
Comment (juditnovak) [reply src/nvim/os/env.c:103]: Indeed, as @zeertzjq suggested. I found the same check in `os_getenv()` code following both `uv_os_getenv()` calls.

File: src/nvim/os/env.c (hunk 22 above)
Comment (juditnovak) [reply src/nvim/os/env.c:116]: Indeed, @zeertzjq is right. 
I'm not sure what is the best terminology here, I'm open for suggestions.

Currently `os_env_exists(name, defined)` means:
```
Return false if the env var exists but it's empty -- i.e. the variable's value is not defined.)
       ^^^^^
```
My terminology was:
- `os_exists(defined=false)` - 'exists': the variable should exists at all ()
- `os_exists(defined=true)` -  'defined': the variable should to have an actual value ()

File: src/nvim/os/env.c (hunk 23 above)
Comment (juditnovak) [reply src/nvim/os/env.c:929]: Fair point. I go ahead changing it to `char *` instead.

File: src/nvim/eval/funcs.c (hunk 19 above)
Comment (juditnovak) [reply src/nvim/eval/funcs.c]: Actually, according to [comment](https://github.com/neovim/neovim/pull/32683#discussion_r1998759094) we shouldn't use that one.

Comment (zeertzjq) [reply src/nvim/eval/funcs.c]: No, you shouldn't use `allocated` and `noalloc` together.

File: src/nvim/eval/funcs.c (hunk 26 above)
Comment (zeertzjq) [reply src/nvim/eval/funcs.c:3944]:
```suggestion
          tv_dict_add_allocated_str(env, required_env_vars[i], len,
                                    os_getenv(required_env_vars[i]));
```

File: src/nvim/eval/funcs.c (hunk 19 above)
Comment (juditnovak) [reply src/nvim/eval/funcs.c]: Indeed your original suggestion was with `os_getenv()`. Sry, I got lost in the transition. Your suggestion was accurate at the time.

File: src/nvim/os/time.c (hunk 24 above)
Comment (juditnovak) [reply src/nvim/os/time.c]: Done

File: src/nvim/os/env.c (hunk 20 above)
Comment (juditnovak) [reply src/nvim/os/env.c]: Done.

File: src/nvim/os/env.c [hunk 27]
```diff
@@ -96,32 +82,55 @@ const char *os_getenv(const char *name)
...
   }
-  pmap_put(cstr_t)(&envmap, xstrdup(name), e);
 end:
   if (r != 0 && r != UV_ENOENT && r != UV_UNKNOWN) {
     ELOG("uv_os_getenv(%s) failed: %d %s", name, r, uv_err_name(r));
   }
   return e;
 }
 
+/// Like getenv(), loading the result to `NameBuff`
```
[the remark this answers is not in the document]
Comment (juditnovak) [reply src/nvim/os/env.c]: Done.

File: src/nvim/eval/funcs.c (hunk 19 above)
Comment (juditnovak) [reply src/nvim/eval/funcs.c]: Closing as it's moved to the [conversation below](https://github.com/neovim/neovim/pull/32683#discussion_r1998759094)

File: src/nvim/eval/funcs.c (hunk 26 above)
Comment (juditnovak) [reply src/nvim/eval/funcs.c]: So.... Which of the two? :-)  If I'm following right, there are two correct solutions. 
(The current code has `tv_dict_add_str()` - `os_getenv_noalloc()`)

Comment (zeertzjq) [reply src/nvim/eval/funcs.c]: `os_getenv()` is more accurate as it's not limited by the size of `NameBuff`

Comment (juditnovak) [reply src/nvim/eval/funcs.c]: Done.

File: src/nvim/os/env.c [hunk 28]
```diff
@@ -137,15 +146,22 @@ int os_setenv(const char *name, const char *value, int overwrite)
     return -1;
   }
 #ifdef MSWIN
-  if (!overwrite && os_getenv(name) != NULL) {
+  bool return_donothing = false;
+  char *env = os_getenv(name);
+  if (!overwrite && env != NULL) {
+    return_donothing = true;
+  }
+  xfree(env);
```
Comment (zeertzjq) [inline src/nvim/os/env.c:154]: You can use `os_env_exists(..., true)` here

**Comment by juditnovak** [comment]
NOTE: All commits will be squashed into the first commit (that has the correct, linted structure) once the review process is over. Until then, lint test errors could be ignored.

File: src/nvim/os/env.c [hunk 29]
```diff
@@ -137,15 +146,22 @@ int os_setenv(const char *name, const char *value, int overwrite)
...
+  if (return_donothing) {
     return 0;
   }
+
```
Comment (zeertzjq) [inline src/nvim/os/env.c:158]:
```suggestion
  if (!overwrite && os_env_exists(name, true)) {
    return 0;
  }
```

File: src/nvim/os/env.c [hunk 30]
```diff
@@ -932,12 +941,13 @@ char *vim_getenv(const char *name)
...
   if (vimruntime
       && *default_vimruntime_dir == NUL) {
-    kos_env_path = os_getenv("VIM");
+    kos_env_path = os_getenv("VIM");    // kos_env_path was NULL.
     if (kos_env_path != NULL) {
       vim_path = vim_version_dir(kos_env_path);
       if (vim_path == NULL) {
         vim_path = xstrdup(kos_env_path);
       }
+      xfree(kos_env_path);
```
Comment (zeertzjq) [inline src/nvim/os/env.c:950]:
```suggestion
        vim_path = kos_env_path;
      } else {
        xfree(kos_env_path);
      }
```

File: src/nvim/eval/funcs.c [hunk 31]
```diff
@@ -3939,9 +3939,9 @@ dict_T *create_environment(const dictitem_T *job_env, const bool clear_env, cons
       size_t len = strlen(required_env_vars[i]);
       dictitem_T *dv = tv_dict_find(env, required_env_vars[i], (ptrdiff_t)len);
       if (!dv) {
-        const char *env_var = os_getenv(required_env_vars[i]);
-        if (env_var) {
-          tv_dict_add_str(env, required_env_vars[i], len, env_var);
+        if (os_env_exists(required_env_vars[i], true)) {
+          tv_dict_add_allocated_str(env, required_env_vars[i], len,
+                                    os_getenv(required_env_vars[i]));
```
Comment (zeertzjq) [inline src/nvim/eval/funcs.c:3944]: Wait, it seems that you can just change `tv_dict_add_str` to `tv_dict_add_allocated_str` in the original code.
```suggestion
        const char *env_var = os_getenv(required_env_vars[i]);
        if (env_var) {
          tv_dict_add_allocated_str(env, required_env_vars[i], len, env);
```

File: src/nvim/msgpack_rpc/server.c [hunk 32]
```diff
@@ -120,12 +120,12 @@ char *server_address_new(const char *name)
   static uint32_t count = 0;
   char fmt[ADDRESS_MAX_SIZE];
 #ifdef MSWIN
-  (void)get_appname(true);
+  const char *appname = get_appname(true);    // Call to initialize NameBuf with appname
```
Comment (zeertzjq) [inline src/nvim/msgpack_rpc/server.c:123]:
```suggestion
  (void)get_appname(true);    // Call to initialize NameBuf with appname
```

File: src/nvim/os/stdpaths.c [hunk 33]
```diff
@@ -64,31 +64,33 @@ static const char *const xdg_defaults[] = {
 };
 
 /// Gets the value of $NVIM_APPNAME, or "nvim" if not set.
+/// Result must be freed by the caller, if called with 'retval_needed == true'.
```
Comment (zeertzjq) [inline src/nvim/os/stdpaths.c:67]: This comment seems outdated

File: src/nvim/os/lang.c [hunk 34]
```diff
@@ -70,34 +70,37 @@ char *get_mess_lang(void)
...
 /// Get the language used for messages from the environment.
+/// The function may be using NameBuff.
 ///
 /// This uses LC_MESSAGES when available, which it is for most systems we build for
 /// except for windows. Then fallback to get the value from the environment
 /// ourselves, and use LC_CTYPE as a last resort.
 static char *get_mess_env(void)
 {
+  char *p;
+
```
Comment (zeertzjq) [inline src/nvim/os/lang.c:81]: Moving the definition of `char *p` back to the `#else` branch seems easier to understand.

File: src/nvim/os/lang.c [hunk 35]
```diff
@@ -70,34 +70,37 @@ char *get_mess_lang(void)
...
 #ifdef LC_MESSAGES
-  return get_locale_val(LC_MESSAGES);
+  p = get_locale_val(LC_MESSAGES);   // Making sure that we can free() the return value
```
Comment (zeertzjq) [inline src/nvim/os/lang.c:83]: This comment seems outdated.

File: src/nvim/os/lang.c [hunk 36]
```diff
@@ -107,8 +110,7 @@ void set_lang_var(void)
   const char *loc = get_locale_val(LC_CTYPE);
   set_vim_var_string(VV_CTYPE, loc, -1);
 
-  loc = get_mess_env();
-  set_vim_var_string(VV_LANG, loc, -1);
+  set_vim_var_string(VV_LANG, get_mess_env(), -1);
```
Comment (zeertzjq) [inline src/nvim/os/lang.c:113]: This change seems inconsistent with the other assignments to `loc`.

File: src/nvim/os/stdpaths.c [hunk 37]
```diff
@@ -64,31 +64,33 @@ static const char *const xdg_defaults[] = {
...
 }
 
 /// Ensure that APPNAME is valid. Must be a name or relative path.
 bool appname_is_valid(void)
 {
   const char *appname = get_appname(false);
+  bool valid = true;
   if (path_is_absolute(appname)
       // TODO(justinmk): on Windows, path_is_absolute says "/" is NOT absolute. Should it?
       || strequal(appname, "/")
```
Comment (zeertzjq) [inline src/nvim/os/stdpaths.c:96]: The changes to this function seem no longer necessary.

File: src/nvim/os/stdpaths.c [hunk 38]
```diff
@@ -188,6 +191,7 @@ char *stdpaths_get_xdg_var(const XDGVarType idx)
     ret = xdg_remove_duplicate(ret, ENV_SEPSTR);
   }
 
+  xfree(env_val);
```
Comment (zeertzjq) [inline src/nvim/os/stdpaths.c:194]: You can remove the `xstrdup()` in the `if (env_val != NULL)` branch above, so that this `xfree()` is not needed.

File: src/nvim/tui/terminfo.c [hunk 39]
```diff
@@ -49,7 +49,7 @@ bool terminfo_is_bsd_console(const char *term)
 # if defined(__FreeBSD__)
   // FreeBSD console sets TERM=xterm, but it does not support xterm features
   // like cursor-shaping. Assume that TERM=xterm is degraded. #8644
-  return strequal(term, "xterm") && !!os_getenv("XTERM_VERSION");
+  return strequal(term, "xterm") && !!os_getenv_noalloc("XTERM_VERSION");
```
Comment (zeertzjq) [inline src/nvim/tui/terminfo.c:52]:
```suggestion
  return strequal(term, "xterm") && os_env_exists("XTERM_VERSION", true);
```

File: src/nvim/eval/funcs.c (hunk 31 above)
Comment (juditnovak) [reply src/nvim/eval/funcs.c:3944]: `env_var` at the end, but yes :-)

File: src/nvim/os/env.c [hunk 40]
```diff
@@ -96,32 +82,55 @@ const char *os_getenv(const char *name)
...
+    return NULL;
+  }
+
+  size_t size = sizeof(NameBuff);
+  int r = uv_os_getenv(name, NameBuff, &size);
+  if (r != 0 || size == 0 || NameBuff[0] == NUL) {
+    if (r != 0 && r != UV_ENOENT && r != UV_UNKNOWN) {
+      ELOG("uv_os_getenv(%s) failed: %d %s", name, r, uv_err_name(r));
+    }
+    return NULL;
```
Comment (justinmk) [inline src/nvim/os/env.c:107]: https://docs.libuv.org/en/v1.x/misc.html#c.uv_os_getenv

> If the environment variable exceeds the storage available in buffer, UV_ENOBUFS is returned

Looks like we will return NULL for `UV_ENOBUFS`. But perhaps we should instead return `NameBuff`, and update the docstring to say `value may be truncated if it exceeds MAXPATHL`

File: src/nvim/os/env.c (hunk 22 above)
Comment (justinmk) [reply src/nvim/os/env.c:116]: "Defined" means the variable exists and may be empty, which sounds like the opposite of your terminology. So I think the logic should be changed to match my suggested docstring.

File: src/nvim/os/env.c [hunk 41]
```diff
@@ -162,7 +178,6 @@ int os_setenv(const char *name, const char *value, int overwrite)
   assert(r != UV_EINVAL);
   // Destroy the old map item. Do this AFTER uv_os_setenv(), because `value`
   // could be a previous os_getenv() result.
-  pmap_del2(&envmap, name);
```
Comment (justinmk) [inline src/nvim/os/env.c:165]: the comment was referring to this deleted line.

File: src/nvim/main.c [hunk 42]
```diff
@@ -932,16 +932,25 @@ static void remote_request(mparm_T *params, int remote_args, char *server_addr,
...
 
   if (is_ui) {
+    char *nvim_env = os_getenv("NVIM");
+    bool exit = false;
     if (!chan) {
       fprintf(stderr, "Remote ui failed to start: %s\n", connect_error);
-      os_exit(1);
-    } else if (strequal(server_addr, os_getenv("NVIM"))) {
+      exit = true;
+    } else if (strequal(server_addr, nvim_env)) {
```
Comment (justinmk) [inline src/nvim/main.c:940]:
```suggestion
    } else if (strequal(server_addr, os_getenv_noalloc("NVIM"))) {
```

File: src/nvim/lua/executor.c [hunk 43]
```diff
@@ -1283,7 +1282,9 @@ static int nlua_empty_dict_tostring(lua_State *lstate)
 /// @param  lstate  Lua interpreter state.
 static int nlua_getenv(lua_State *lstate)
 {
-  lua_pushstring(lstate, os_getenv(luaL_checkstring(lstate, 1)));
+  char *lstate_var = os_getenv(luaL_checkstring(lstate, 1));
+  lua_pushstring(lstate, lstate_var);
```
Comment (justinmk) [inline src/nvim/lua/executor.c:1286]: noalloc?

File: src/nvim/os/lang.c [hunk 44]
```diff
@@ -340,7 +342,7 @@ char *get_locales(expand_T *xp, int idx)
 void lang_init(void)
 {
 #ifdef __APPLE__
-  if (os_getenv("LANG") == NULL) {
+  if (!os_env_exists("LANG", true)) {
```
Comment (justinmk) [inline src/nvim/os/lang.c:345]: it was only checking NULL, which means the arg should be `false` ?
```suggestion
  if (!os_env_exists("LANG", false)) {
```

File: src/nvim/os/time.c [hunk 45]
```diff
@@ -98,8 +98,8 @@ struct tm *os_localtime_r(const time_t *restrict clock,
   // Call tzset(3) to update the global timezone variables if it has.
   // POSIX standard doesn't require localtime_r() implementations to do that
   // as it does with localtime(), and we don't want to call tzset() every time.
-  const char *tz = os_getenv("TZ");
-  if (tz == NULL) {
+  const char *tz = os_getenv_noalloc("TZ");
+  if (!tz) {
```
Comment (justinmk) [inline src/nvim/os/time.c:102]: `NameBuff` can never be NULL. It looks like what's wanted here is `os_env_exits("TZ", false)`.

File: src/nvim/os/lang.c (hunk 44 above)
Comment (zeertzjq) [reply src/nvim/os/lang.c:345]: `os_getenv` returns `NULL` for empty string

File: src/nvim/os/env.c [hunk 46]
```diff
@@ -52,31 +52,17 @@
 # include "os/env.c.generated.h"
 #endif
 
-// Because `uv_os_getenv` requires allocating, we must manage a map to maintain
-// the behavior of `os_getenv`.
-static PMap(cstr_t) envmap = MAP_INIT;
-
 /// Like getenv(), but returns NULL if the variable is empty.
+/// Result must be freed by the caller.
 /// @see os_env_exists
```
Comment (justinmk) [inline src/nvim/os/env.c:57]:
```suggestion
/// @see os_getenv_noalloc
/// @see os_env_exists
```

File: src/nvim/os/time.c (hunk 45 above)
Comment (zeertzjq) [reply src/nvim/os/time.c:102]: `os_getenv_noalloc` doesn't always return `NameBuff`

File: src/nvim/tui/tui.c [hunk 47]
```diff
@@ -401,23 +401,27 @@ static void terminfo_start(TUIData *tui)
...
+  char *konsole_dbus_session = os_getenv("KONSOLE_DBUS_SESSION");
+  char *term_program_version_env = os_getenv("TERM_PROGRAM_VERSION");
+
   int vtev = vte_version_env ? (int)strtol(vte_version_env, NULL, 10) : 0;
   bool iterm_env = termprg && strstr(termprg, "iTerm.app");
   bool nsterm = (termprg && strstr(termprg, "Apple_Terminal"))
                 || terminfo_is_term_family(term, "nsterm");
   bool konsole = terminfo_is_term_family(term, "konsole")
-                 || os_getenv("KONSOLE_PROFILE_NAME")
-                 || os_getenv("KONSOLE_DBUS_SESSION");
```
Comment (justinmk) [inline src/nvim/tui/tui.c:413]: could use noalloc here

File: src/nvim/os/env.c (hunk 41 above)
Comment (juditnovak) [reply src/nvim/os/env.c:165]: I should have noticed that, sorry.

File: src/nvim/os/env.c (hunk 40 above)
Comment (juditnovak) [reply src/nvim/os/env.c:107]: I'm wondering, should we add a log message (like `WLOG`) as well?

Comment (justinmk) [reply src/nvim/os/env.c:107]: I think the caller needs to decide that.

File: src/nvim/os/env.c (hunk 29 above)
Comment (juditnovak) [reply src/nvim/os/env.c]: Done.

File: src/nvim/os/env.c (hunk 30 above)
Comment (juditnovak) [reply src/nvim/os/env.c]: Done.

File: src/nvim/eval/funcs.c (hunk 31 above)
Comment (juditnovak) [reply src/nvim/eval/funcs.c]: Done.

File: src/nvim/msgpack_rpc/server.c (hunk 32 above)
Comment (juditnovak) [reply src/nvim/msgpack_rpc/server.c]: Done.

File: src/nvim/os/stdpaths.c (hunk 33 above)
Comment (juditnovak) [reply src/nvim/os/stdpaths.c]: Done.

File: src/nvim/os/lang.c (hunk 34 above)
Comment (juditnovak) [reply src/nvim/os/lang.c]: Done.

File: src/nvim/os/lang.c (hunk 35 above)
Comment (juditnovak) [reply src/nvim/os/lang.c]: Done.

File: src/nvim/os/lang.c (hunk 36 above)
Comment (juditnovak) [reply src/nvim/os/lang.c]: Reverted to original.

File: src/nvim/os/stdpaths.c (hunk 37 above)
Comment (juditnovak) [reply src/nvim/os/stdpaths.c]: Done.

File: src/nvim/os/stdpaths.c (hunk 38 above)
Comment (juditnovak) [reply src/nvim/os/stdpaths.c]: Done.

File: src/nvim/tui/terminfo.c (hunk 39 above)
Comment (juditnovak) [reply src/nvim/tui/terminfo.c]: Done.

File: src/nvim/os/env.c (hunk 41 above)
Comment (juditnovak) [reply src/nvim/os/env.c:165]: Done.

File: src/nvim/main.c (hunk 42 above)
Comment (juditnovak) [reply src/nvim/main.c]: Done.

File: src/nvim/lua/executor.c (hunk 43 above)
Comment (juditnovak) [reply src/nvim/lua/executor.c]: Done.

File: src/nvim/os/env.c (hunk 46 above)
Comment (juditnovak) [reply src/nvim/os/env.c:57]: Done.

File: src/nvim/os/env.c [hunk 48]
```diff
@@ -137,15 +157,17 @@ int os_setenv(const char *name, const char *value, int overwrite)
     return -1;
   }
 #ifdef MSWIN
-  if (!overwrite && os_getenv(name) != NULL) {
+  bool return_donothing = false;
```
Comment (zeertzjq) [inline src/nvim/os/env.c:160]: This variable is never used.
```suggestion
```

File: src/nvim/os/env.c [hunk 49]
```diff
@@ -137,15 +157,17 @@ int os_setenv(const char *name, const char *value, int overwrite)
...
+  if (!overwrite && !os_env_exists(name, true)) {
     return 0;
   }
+
```
Comment (zeertzjq) [inline src/nvim/os/env.c:164]:
```suggestion
```

File: src/nvim/os/env.c (hunk 40 above)
Comment (justinmk) [reply src/nvim/os/env.c:118]: Ok, I see that you only allocate if `UV_ENOBUFS` is returned. That's good.

Comment (juditnovak) [reply src/nvim/os/env.c:118]: ...and we can `xfree()` the allocated area right after :-)

File: src/nvim/os/env.c (hunk 49 above)
Comment (juditnovak) [reply src/nvim/os/env.c]: Done.

File: src/nvim/os/env.c (hunk 48 above)
Comment (juditnovak) [reply src/nvim/os/env.c]: Done.

File: src/nvim/os/env.c (hunk 22 above)
Comment (juditnovak) [reply src/nvim/os/env.c]: Done.

File: src/nvim/mbyte.c (hunk 11 above)
Comment (juditnovak) [reply src/nvim/mbyte.c:2414]: Outdated: `memfree` is not needed once using `os_getenv_noalloc()` :-)

**Comment by juditnovak** [comment]
Requests completed + added a few more simplifications and tests.

**Comment by juditnovak** [comment]
(Once final, I'd squash all commits into the 1st one, that already has the correct commit message format.)

**Review by zeertzjq — APPROVED** [review]

**Comment by zeertzjq** [comment]
Yes

**Comment by juditnovak** [comment]
@justinmk @zeertzjq Are there any outstanding actions on my side? Please let me know in case I may be missing something...
(No pressure in case it's for you to take action. I just wanted to double-check if I may be blocking progress :-) )

File: src/nvim/os/env.c [hunk 50]
```diff
@@ -96,32 +83,65 @@ const char *os_getenv(const char *name)
...
+  return NameBuff;
+}
+
 /// Returns true if environment variable `name` is defined (even if empty).
 /// Returns false if not found (UV_ENOENT) or other failure.
-bool os_env_exists(const char *name)
+///
+/// @param name the environment variable in question
+/// @param nonempty whether the variable has a valid value, or may be empty
+/// @return whether the variable exists (and is defined)
```
Comment (justinmk) [inline src/nvim/os/env.c:128]: this is  very confusing. "defined" and "exists" are synonyms usually. 

```suggestion
/// @return whether the variable exists (and is nonempty)
```

File: src/nvim/os/env.c [hunk 51]
```diff
@@ -96,32 +83,65 @@ const char *os_getenv(const char *name)
...
+  }
+  return NameBuff;
+}
+
 /// Returns true if environment variable `name` is defined (even if empty).
 /// Returns false if not found (UV_ENOENT) or other failure.
-bool os_env_exists(const char *name)
+///
+/// @param name the environment variable in question
+/// @param nonempty whether the variable has a valid value, or may be empty
```
Comment (justinmk) [inline src/nvim/os/env.c:127]: description is ambiguous, let's say more clearly what is *activated* by setting this param:

```suggestion
/// @param nonempty Require a non-empty value. Treat empty as "does not exist".
```

File: src/nvim/msgpack_rpc/server.c [hunk 52]
```diff
@@ -120,12 +120,12 @@ char *server_address_new(const char *name)
   static uint32_t count = 0;
   char fmt[ADDRESS_MAX_SIZE];
 #ifdef MSWIN
-  (void)get_appname(true);
+  (void)get_appname(true);    // Call to initialize NameBuf with appname
```
Comment (justinmk) [inline src/nvim/msgpack_rpc/server.c:123]:
```suggestion
  (void)get_appname(true);  // Writes appname to NameBuf.
```

File: src/nvim/msgpack_rpc/server.c [hunk 53]
```diff
@@ -120,12 +120,12 @@ char *server_address_new(const char *name)
...
   int r = snprintf(fmt, sizeof(fmt), "\\\\.\\pipe\\%s.%" PRIu64 ".%" PRIu32,
                    name ? name : NameBuff, os_get_pid(), count++);
 #else
   char *dir = stdpaths_get_xdg_var(kXDGRuntimeDir);
-  (void)get_appname(true);
+  (void)get_appname(true);    // Call to initialize NameBuf with appname
```
Comment (justinmk) [inline src/nvim/msgpack_rpc/server.c:128]:
```suggestion
  (void)get_appname(true);  // Writes appname to NameBuf.
```

File: src/nvim/os/lang.c [hunk 54]
```diff
@@ -79,17 +80,18 @@ static char *get_mess_env(void)
 #ifdef LC_MESSAGES
   return get_locale_val(LC_MESSAGES);
 #else
-  char *p = (char *)os_getenv("LC_ALL");
+  char *p;
+  p = os_getenv_noalloc("LC_ALL");
```
Comment (justinmk) [inline src/nvim/os/lang.c:84]:
```suggestion
  char *p = os_getenv_noalloc("LC_ALL");
```

File: src/nvim/tui/tui.c [hunk 55]
```diff
@@ -1781,10 +1792,12 @@ void tui_guess_size(TUIData *tui)
...
   const char *val;
+  lines = os_getenv("LINES");
+  columns = os_getenv("COLUMNS");
   int advance;
-  if ((val = os_getenv("LINES"))
+  if ((val = lines)
       && sscanf(val, "%d%n", &height, &advance) != EOF && advance
-      && (val = os_getenv("COLUMNS"))
+      && (val = columns)
       && sscanf(val, "%d%n", &width, &advance) != EOF && advance) {
```
Comment (justinmk) [inline src/nvim/tui/tui.c:1801]: could use `_noalloc` since `sscanf` doesn't use NameBuf, but maybe that's too clever.

File: src/nvim/ui_client.c [hunk 56]
```diff
@@ -63,7 +63,7 @@ uint64_t ui_client_start_server(int argc, char **argv)
 
 #ifdef MSWIN
   // TODO(justinmk): detach breaks `tt.setup_child_nvim` tests on Windows?
-  bool detach = os_env_exists("__NVIM_DETACH");
+  bool detach = os_env_exists("__NVIM_DETACH", false);
```
Comment (justinmk) [inline src/nvim/ui_client.c:66]: should require nonempty here

File: src/nvim/ui_client.c [hunk 57]
```diff
@@ -172,7 +172,7 @@ void ui_client_run(bool remote_ui)
   ui_client_attach(width, height, term, rgb);
 
   // TODO(justinmk): this is for log_spec. Can remove this after nvim_log #7062 is merged.
-  if (os_env_exists("__NVIM_TEST_LOG")) {
+  if (os_env_exists("__NVIM_TEST_LOG", false)) {
```
Comment (justinmk) [inline src/nvim/ui_client.c:175]: require nonempty

File: test/unit/os/env_spec.lua [hunk 58]
```diff
@@ -13,8 +13,8 @@ local OK = 0
 local cimp = cimport('./src/nvim/os/os.h')
 
 describe('env.c', function()
-  local function os_env_exists(name)
-    return cimp.os_env_exists(to_cstr(name))
+  local function os_env_exists(name, defined)
+    return cimp.os_env_exists(to_cstr(name), defined)
```
Comment (justinmk) [inline test/unit/os/env_spec.lua:17]:
```suggestion
  local function os_env_exists(name, nonempty)
    return cimp.os_env_exists(to_cstr(name), nonempty)
```

**Review by justinmk — APPROVED** [review]
LGTM after comments. Also worth a rebase.

Thank you!

**Comment by justinmk** [comment]
Maybe we should also have a test for `vim.uv.os_unsetenv` (the repro steps from https://github.com/neovim/neovim/issues/32550 ) in `test/functional/` (not `test/unit/`)? May need a new `test/functional/core/env_spec.lua` file.

File: test/unit/os/env_spec.lua (hunk 58 above)
Comment (juditnovak) [reply test/unit/os/env_spec.lua]: Done.

File: src/nvim/msgpack_rpc/server.c (hunk 52 above)
Comment (juditnovak) [reply src/nvim/msgpack_rpc/server.c]: Done.

File: src/nvim/os/env.c [hunk 59]
```diff
@@ -96,32 +83,65 @@ const char *os_getenv(const char *name)
...
   }
-  pmap_put(cstr_t)(&envmap, xstrdup(name), e);
 end:
   if (r != 0 && r != UV_ENOENT && r != UV_UNKNOWN) {
     ELOG("uv_os_getenv(%s) failed: %d %s", name, r, uv_err_name(r));
   }
   return e;
 }
 
+/// Like getenv(), but returns a pointer to `NameBuff` instead of allocating.
```
[the remark this answers is not in the document]
Comment (juditnovak) [reply src/nvim/os/env.c]: Done.

File: src/nvim/os/env.c (hunk 50 above)
Comment (juditnovak) [reply src/nvim/os/env.c]: I agree, I was much struggling with the terminology here. Suggestion added as proposed.

File: src/nvim/os/env.c (hunk 51 above)
Comment (juditnovak) [reply src/nvim/os/env.c]: Done.

File: src/nvim/os/lang.c (hunk 54 above)
Comment (juditnovak) [reply src/nvim/os/lang.c]: Done.

File: src/nvim/tui/tui.c (hunk 55 above)
Comment (juditnovak) [reply src/nvim/tui/tui.c]: Indeed. Done.

File: src/nvim/ui_client.c (hunk 56 above)
Comment (juditnovak) [reply src/nvim/ui_client.c]: Done.

**Comment by juditnovak** [comment]
@justinmk Functional test added as requested (with reference to the original issue). Pls check.

Once all approved, I'm squashing the new commits into 1st one (and of course do a rebase at that point as well :-) )

**Comment by justinmk** [comment]
> Once all approved, I'm squashing the new commits into 1st one (and of course do a rebase at that point as well :-) )

no need since you merged master here. we can squash at merge-time.

thanks!

**Comment by justinmk** [comment]
> Functional test added as requested

was it pushed? don't see it

**Comment by juditnovak** [comment]
@justinmk I apologize :facepalm: 

Added now in the corresponding, last commit.
(Previous content of this commit, i.e. variable rename on a unittest was added to the rest of the requested fixes.)

**Comment by juditnovak** [comment]
:tada:

:-) :-) :-)
