### PR TITLE
fix(defaults): improve error handling for unimpaired mappings

### LINKED ISSUE #30625: Improve error handling for new unimpaired mappings
Pressing `]q` at the end of the quickfix list shows:

```
E5108: Error executing lua: vim/_defaults.lua:0: Vim:E553: No more items
stack traceback:
        [C]: in function 'cnext'
        vim/_defaults.lua: in function <vim/_defaults.lua:0>
```

when it should simply show

```
E553: No more items
```

just as if the user had used `:cnext` directly.

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #30625

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

File: runtime/lua/vim/_defaults.lua [hunk 1]
```diff
@@ -215,173 +215,126 @@ do
...
     -- Quickfix mappings
-    vim.keymap.set('n', '[q', function()
+    create_unimpaired_mapping('[q', function()
       vim.cmd.cprevious({ count = vim.v.count1 })
-    end, {
-      desc = ':cprevious',
-    })
-
-    vim.keymap.set('n', ']q', function()
+    end, ':cprevious')
```
Comment (lewis6991) [inline runtime/lua/vim/_defaults.lua:233]: I think instead of creating multiple function to implement this we can should do:

```lua
vim.keymap.set('n', '[q', '<cmd>cprevious<cr>')
```

I don't think we even need desc since the output of `map [q` with this is:

```
n  [q          * <Cmd>cprevious<CR>
```

Comment (gpanders) [reply runtime/lua/vim/_defaults.lua:233]: This won’t work with counts. And will get ugly for some of the other mappings.

We already discussed this so not sure why it’s being brought up again. There’s nothing wrong with using functions here. It’s more explicit, better typed, and doesn’t suffer the obscure workarounds and edge cases of the Vimscript commands.

Look at vim-unimpaired’s source code if you want to see what the Vimscript implementations look like.

Comment (lewis6991) [reply runtime/lua/vim/_defaults.lua:233]: > This won’t work with counts. And will get ugly for some of the other mappings.

Ok fair enough.

> We already discussed this so not sure why it’s being brought up again.

It was talked about here https://github.com/neovim/neovim/pull/28525#discussion_r1781850866 but I don't think that really covers this fully.

> There’s nothing wrong with using functions here. It’s more explicit, better typed, and doesn’t suffer the obscure workarounds and edge cases of the Vimscript commands.

I was only suggesting that using `rhs` as a single command name (no expression) would be cleaner and remove several layers of code (`create_unimpaired_mapping -> pcall -> vim.cmd -> nvim_cmd`). Obviously, I forgot about counts, so this doesn't work.

> Look at vim-unimpaired’s source code if you want to see what the Vimscript implementations look like.

Done. And you are right.

File: runtime/lua/vim/_defaults.lua [hunk 2]
```diff
@@ -215,173 +215,126 @@ do
 
   --- vim-unimpaired style mappings. See: https://github.com/tpope/vim-unimpaired
   do
+    ---@param lhs string
+    ---@param rhs function
+    ---@param desc string
+    local function create_unimpaired_mapping(lhs, rhs, desc)
```
Comment (lewis6991) [inline runtime/lua/vim/_defaults.lua:221]: I think it might be better if `desc` is placed as the first or second argument as this will then make the `rhs` the last argument which is generally preferred for functions.

> - Any function signature that accepts a callback (example: |table.foreach()|)
  should place it as the LAST parameter (after opts), if possible (or ALWAYS
  for "continuation callbacks"—functions called exactly once).

Though this is only guidance, but I think it will help here.

**Review by lewis6991 — COMMENTED** [review]
nit: the previous code was nicely separated out with line breaks between each mapping which have been removed in this change. I now find this more difficult to read as the code is now one contiguous block.

**Comment by justinmk** [comment]
Since there are only "nit" comments, let's merge for now and if anyone feels strongly can send another PR.

**Comment by BarrensZeppelin** [comment]
Was the removal of `]Q` and `[Q` mappings intentional?

**Comment by MariaSolOs** [comment]
> Was the removal of `]Q` and `[Q` mappings intentional?

No
