### PR TITLE
fix(lsp): properly handle `documentColor` from multiple servers

### LINKED ISSUE #33625: `textDocument/documentColor` should handle colors from multiple language servers
### Problem

Thank you to all the contributors on #33440 for this lovely feature.

When running multiple language servers that all provide documentColor, I believe a race condition occurs which overrides presentations from one server in favour of another.

Here is a screenshot of vscodium with css-ls and my own design-tokens-language-server running on a test document:

Image

Observe:
- css-ls provides colors like `green`
- dtls provides colors like `--token-color-green`

Now here's a screenshot from today's nightly, with both css-ls and dtls enabled, and document_color enabled:

Image

Note that only css-ls presents

Here's a screenshot with css-ls disabled, but dtls enabled:

Image

### Steps to reproduce

0. install deno
1. clone dtls repo and install

```shell
$ git clone https://github.com/bennypowers/design-tokens-language-server
$ cd design-tokens-language-server
$ deno install
```

alternatively download a [dtls release binary](https://github.com/bennypowers/design-tokens-language-server/releases/)

2. configure nvim for dtls

```lua
-- lsp/design_tokens_ls
---@type vim.lsp.ClientConfig
return {
  cmd = {
    -- if you'd like to confirm that dtls is sending legit documentColors
    -- 'lsp-devtools', 'agent', '--', 'design-tokens-language-server',
    -- otherwise 
    'design-tokens-language-server',
  },
  root_markers = { '.git', 'package.json' },
  filetypes = { 'css' },
  on_attach = function(client, bufnr)
    if vim.lsp.document_color then
      vim.lsp.document_color.enable(true, bufnr, {
        style = 'virtual'
      })
    end
  end,
}
```

3. configure css ls

```lua
---@type vim.lsp.ClientConfig
return {
  cmd = { 'vscode-css-language-server', '--stdio' },
  filetypes = { 'css', 'scss', 'less' },
  root_markers = { 'package.json', '.git' },
  settings = {
    css = { validate = true, lint = false },
    scss = { validate = true, lint = false },
    less = { validate = true, lint = false },
  },
}

```

3. open the `test/test.css` file from dtls repo with neovim nightly and observe

### Expected behavior

something along these lines:

Image

### Nvim version (nvim -v)

NVIM v0.12.0-dev-213+g1670fbee0f Build type: RelWithDebInfo LuaJIT 2.1.1744317938 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

no, this is an nvim feature

### Operating system/version

silverblue 42

### Terminal name/version

ptyxis

### $TERM environment variable

xterm-256color

### Installation

nightly binary

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #33625

### CODE REVIEW

**Comment by MariaSolOs** [comment]
@bennypowers could you please check that this fixes the issue for you? I tested it with `cssls` and `css-variables-language-server` and highlights from both servers are now being displayed (`css-variables-language-server` highlights the stuff inside `var()` and `cssls` highlights everything else):


https://github.com/user-attachments/assets/4b85eb1c-3e51-4466-b606-a4816e9c96c3

**Review by justinmk — APPROVED** [review]

File: runtime/lua/vim/lsp/document_color.lua [hunk 1]
```diff
@@ -15,9 +15,10 @@ local M = {}
 
 --- @class (private) vim.lsp.document_color.BufState
 --- @field enabled boolean Whether document_color is enabled for the current buffer
---- @field buf_version? integer Buffer version for which the color ranges correspond to
+--- @field processed_version table<integer, integer?> (client_id -> buffer version) Buffer version for which the color ranges correspond to
 --- @field applied_version table<integer, integer?> (client_id -> buffer version) Last buffer version for which we applied color ranges
 --- @field hl_info table<integer, vim.lsp.document_color.HighlightInfo[]?> (client_id -> color highlights) Processed highlight information
+--- @field ns table<integer, integer?> (client_id -> namespace ID) documentColor namespace ID for each client.
```
Comment (echasnovski) [inline runtime/lua/vim/lsp/document_color.lua:21]: A minor nitpick: storing `client_id -> namespace ID` map for every buffer client attaches to (although it doesn't depend on the buffer) seems like not the best abstraction. It is not wrong per se to store duplicating info and memory overhead is not huge (although scales `O(nm)` instead of `O(n)`), but still.

Perhaps an extra `clientstates` for (at the moment) only a client's namespace id is a better long-term approach here?

**Review by echasnovski — APPROVED** [review]
If it fixes both problems with multiple clients (being able to show colors from several servers that support capability and not being affected by servers that don't support it), then looks good to me. The separate `client_id -> namespace ID` map is nice to have but not crucial.

File: runtime/lua/vim/lsp/document_color.lua (hunk 1 above)
Comment (MariaSolOs) [reply runtime/lua/vim/lsp/document_color.lua:21]: I don’t fully understand the suggestion. Are you saying I could use a single namespace?

Comment (echasnovski) [reply runtime/lua/vim/lsp/document_color.lua:21]: No, on the contrary. Having separate namespaces for each client is good. And that is indeed what is done in the PR (`api.nvim_create_namespace('nvim.lsp.document_color.client_' .. client_id)`).

But as namespace depends only on the client id, storing namespace identifiers inside state for each buffer (`bufstates[bufnr].ns[client_id]`) leads to duplicating information: `bufstates[1].ns[1]` is the same as `bufstates[2].ns[1]`, etc. That in itself is not a huge issue (yet), but leads to wrong abstraction.

Storing namespace identifiers in a more direct map, so it can be accessed as `client_ns[client_id]` (or `clientstates[client_id].ns`), is more future-proof.

Comment (MariaSolOs) [reply runtime/lua/vim/lsp/document_color.lua:21]: Ohhhh gotcha, good point. I’ll fix it!

**Comment by bennypowers** [comment]
@MariaSolOs lgtm
image

**Comment by MariaSolOs** [comment]
> @MariaSolOs lgtm image

Wonderful, thanks for checking!
