### PR TITLE
fix(float): improve error message when reconfig failed

### LINKED ISSUE #18368: `non-float cannot have 'row'` for `nvim_win_set_config` on floating window
### Neovim version (nvim -v)

a1542b091dd7b919fa8524c1c909ef897dde9299

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

From source

### How to reproduce the issue

```
local buf = vim.api.nvim_create_buf(false, true)
local win = vim.api.nvim_open_win(buf, true, {
  relative = 'editor',
  row = 5, col = 5,
  width = 10, height = 10,
})

vim.api.nvim_win_set_config(win, {
  width = 3, height = 3,
  row = 10, col = 10, -- Runs fine without this line,
                      -- this line gives:
--[[

E5113: Error while calling lua chunk: mwe.lua:8: non-float cannot have 'row'
stack traceback:
        [C]: in function 'nvim_win_set_config'
        mwe.lua:8: in main chunk

--]]
  -- relative = 'editor', -- Adding this fixes it.
})
```

### Expected behavior

You shouldn't have to re-specify `relative` -- the `nvim_win_set_config` docs state that existing config options will be kept:

image

See: `parse_float_config` in `win_config.c`.

### Actual behavior

You can't set `row`/`col` without re-specifying `relative`.

### PR DESCRIPTION
**Pull request by glepnir**
Problem: current error message is less readable when reconfig a floating window failed.

Solution: improve error message when reconfig float window.

Fix #18368

### CODE REVIEW

**Comment by zeertzjq** [comment]
This paragraph needs to be removed:
```
    When reconfiguring a floating window, absent option keys will not be
    changed. `row`/`col` and `relative` must be reconfigured together.
```

File: src/nvim/api/win_config.c [hunk 1]
```diff
@@ -207,9 +207,6 @@ Window nvim_open_win(Buffer buffer, Boolean enter, Dict(float_config) *config, E
 /// Configures window layout. Currently only for floating and external windows
 /// (including changing a split window to those layouts).
 ///
-/// When reconfiguring a floating window, absent option keys will not be
```
Comment (bfredl) [inline src/nvim/api/win_config.c:210]: is this no longer the case?

File: test/functional/ui/float_spec.lua [hunk 2]
```diff
@@ -295,6 +295,34 @@ describe('float window', function()
...
+        style = 'minimal'
+      }
+
+      local win_id = vim.api.nvim_open_win(bufnr, true, opts)
+
+      vim.api.nvim_win_set_config(win_id, {
+	width = 3,
+	height = 3,
+	row = 10,
+	col = 10,
```
Comment (bfredl) [inline test/functional/ui/float_spec.lua:318]: not sure this is an improvement. `row` and `col` is more meaningful with the information relative _what_ being completely local. #18368 is correct the _error message_ is quite confusing and could be improved tho.

File: src/nvim/api/win_config.c (hunk 1 above)
Comment (glepnir) [reply src/nvim/api/win_config.c:210]: it work likes before I think..only check when second reconfig missed relative field it can be before value.

File: src/nvim/api/win_config.c [hunk 3]
```diff
@@ -1023,6 +1023,18 @@ static void parse_border_style(Object style, WinConfig *fconfig, Error *err)
...
 }
 
+static void generate_api_error(win_T *wp, const char *attribute, Error *err)
+{
+  char fmt[256];
+  if (wp->w_floating) {
+    snprintf(fmt, sizeof(fmt), "Missing relative field when reconfiguring floating window %d",
+             wp->handle);
+  } else {
+    snprintf(fmt, sizeof(fmt), "non-float cannot have '%s'", attribute);
```
Comment (zeertzjq) [inline src/nvim/api/win_config.c:1033]: Can't you use `api_set_error()` here directly?

Comment (glepnir) [reply src/nvim/api/win_config.c:1033]: The first time this was done. some line breaks are needed

Comment (glepnir) [reply src/nvim/api/win_config.c:1033]: oh yup ..

File: src/nvim/api/win_config.c [hunk 4]
```diff
@@ -1023,6 +1023,17 @@ static void parse_border_style(Object style, WinConfig *fconfig, Error *err)
   }
 }
 
+static void generate_api_error(win_T *wp, const char *attribute, Error *err)
+{
+  if (wp->w_floating) {
+    api_set_error(err, kErrorTypeValidation,
+                  "Missing relative field when reconfiguring floating window %d",
```
Comment (zeertzjq) [inline src/nvim/api/win_config.c:1030]:
```suggestion
                  "Missing 'relative' field when reconfiguring floating window %d",
```
