### PR TITLE
vim-patch:8.2.{0174,1933,1935,1946,2286,2287}

### LINKED ISSUE #14394: `:sort` can't sort Chinese in pinyin alphabetical order
- `nvim --version`: 0.4.4 and v0.5.0-dev+1263-ga129887c0
- `vim -u DEFAULTS` (version: ) behaves differently? yes, 8.2
- Operating system/version: windows 10 and arch linux
- Terminal name/version: alacritty
- `$TERM`: alacritty

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC somefile
:sort
```

### Actual behaviour

Chinese are not sort in pinyin alphabetical order

### Expected behaviour

Chinese are sort in pinyin alphabetical order

### More Information

Default vim 8.2 can sort Chinese in pinyin alphabetical order but neovim can't.

If I set vim encoding to utf-8, vim can not sort Chinese in pinyin alphabetical order either.\
 Vim is not perfect in sort on windows, I have no idea why it put 黏 and 笙 at the end for the attached example. However, vim will sort perfectly on Arch Linux.\
So I guess it might because neovim default encoding is not latin1.\
I think I can't change the encoding in neovim, so I try to change fileencoding in neovim but still can not sort Chinese in pinyin alphabetical order.

Is it a feature or BUG? If it is a feature, what is the easiest way to sort Chinese in pinyin alphabetical order in neovim?

Attached file vim_ex.txt is vim output on windows after :sort.\
Attached file nvim_ex.txt is neovim output on windows after :sort.\
vim_ex.txt contains most Chinese in pinyin alphabetical order but nvim_ex is not.\
In order to display vim_ex.txt with vim properly, you need :e ++enc=utf8 after open it with vim.

[nvim_ex.txt](https://github.com/neovim/neovim/files/6331316/nvim_ex.txt)
[vim_ex.txt](https://github.com/neovim/neovim/files/6331317/vim_ex.txt)

### PR DESCRIPTION
**Pull request by seandewar**
Main goal of this PR is to port v8.2.1933.

- v8.2.0174 isn't strictly necessary. I can remove this patch from the PR if it makes it easier to review.
- v8.2.0988 is partially ported so `v:collate` is available for v8.2.1933 and the test patches thereafter.
- vim/vim@3132cdd is partially ported as it has up-to-date docs for the locale-based `:sort`.
- The Mac-specific `oldtest` patches are indeed needed to have the OSX CI succeed on my fork. :smile:

CC @flyxyz123; does this fix your issue?

Closes #14394 _(if I didn't screw up)_.

### CODE REVIEW

**Comment by flyxyz123** [comment]
@seandewar Thank you for your help. I build it on Arch Linux and it sorts Chinese perfectly like vim-nightly 8.2.2779. 

The neovim output file after sort [nvim_patch_arch_ex.txt](https://github.com/neovim/neovim/files/6341597/nvim_patch_arch_ex.txt) is identical to vim output after a sort for my example in #14394 following the same steps.

I have not yet built and test it on windows 10. I may try that when I have time.

I think it fixes my issue.

**Comment by seandewar** [comment]
@flyxyz123 Awesome to hear! Thanks for the help. 🚀

File: src/nvim/ex_cmds.c [hunk 1]
```diff
@@ -381,6 +382,13 @@ typedef struct {
   } st_u;
 } sorti_T;
 
+static int string_compare(const void *s1, const void *s2) FUNC_ATTR_NONNULL_ALL
+{
+  if (sort_lc) {
+    return strcoll((char *)s1, (char *)s2);
+  }
+  return sort_ic ? STRICMP(s1, s2) : STRCMP(s1, s2);
```
Comment (janlazo) [inline src/nvim/ex_cmds.c:390]: What's the point of check `sort_lc` twice when `strcoll` doesn't modify it?
This came from the patch but it looks wrong to me.

**Review by janlazo — APPROVED** [review]
LGTM

File: src/nvim/ex_cmds.c (hunk 1 above)
Comment (seandewar) [reply src/nvim/ex_cmds.c:390]: This checks `sort_ic` (for case-insensitivity), not `sort_lc`.
