### PR TITLE
Reset background color before scroll

### LINKED ISSUE #11893: color glitches when scrolling buffer
- `nvim --version`: NVIM v0.5.0-384-ga2efc9cf8
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version: debian testing (bullseye)
- Terminal name/version: alacritty 0.4.2-dev
- `$TERM`: alacritty (also happens on gnome-terminal)

### Steps to reproduce (debug build)

testrc.vim
```vim
" note: issue occurs also without vim-syntax-extra but less frequent
call plug#begin('~/.local/share/nvim/plugged')
Plug 'justinmk/vim-syntax-extra'
call plug#end()
hi StatusLine ctermbg=red ctermfg=yellow cterm=NONE
```

```sh
# sha1sum is just used for making some background CPU load,
# it makes this more reproducible, 8 is nr of cores
$ for i in {1..8}; do  sha1sum /dev/zero &  done && \
  build/bin/nvim -u testrc.vim src/nvim/eval.c && \
  killall sha1sum
```
inside nvim, just press (and hold) `CTRL-D' to scroll down

### Actual behaviour
There are moments, when color used for `ctermbg` of statusline coveres lower portion of buffer.

vim-status

### Expected behaviour
buffer background should remain the same during scrolling

### PR DESCRIPTION
**Pull request by doubleloop**
fixes #11893

### CODE REVIEW

**Comment by doubleloop** [comment]
This change fixed the issue form me.

Questions:
* What is a difference between `unibi_set_a_background` and `unibi_set_background`
* Did I correctly assume that `clear_attrs` is a good source of default background value
* Should I check if bg is `-1` (if so, what exactly is the meaning of `-1` for color attr)

Notes:
* Visible flickering still occurs on area of signcolumn (if it has color different from buffer background). It is less annoying and it also occurs in vim. Still I guess it potentially could be fixed.

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -1100,6 +1100,19 @@ static void tui_grid_scroll(UI *ui, Integer g, Integer startrow, Integer endrow,
     }
     cursor_goto(ui, top, left);
 
+    int bg;
```
Comment (bfredl) [inline src/nvim/tui/tui.c]: `print_attr_id` would be need to be changed. Though we could just replace the entire added block by `update_attrs(ui, 0);` which would do that as well.

**Comment by bfredl** [comment]
> Did I correctly assume that clear_attrs is a good source of default background value

This is the best we can do for now with the basic UI protocol that the TUI uses. A later multigrid-aware TUI could try to be "smart" and use local winhl value, scroll sign column separately etc, but that is probably quite a bit ahead in the future.
