### PR TITLE
fix(startuptime): multiprocess startuptime

### LINKED ISSUE #23036: TUI: recurring --startuptime output from both processes
### Problem

The output when using `--startuptime` includes two blocks of data.

I noticed this when using Neovim 0.9 with a plugin I wrote that reports startuptime measurements, [vim-startuptime](https://github.com/dstein64/vim-startuptime).

### Steps to reproduce

```
# first remove any existing startuptime output (assumed file tmpfile), otherwise the startuptime
# output is appended to the existing file.
rm tmpfile

nvim --clean --startuptime tmpfile
:quit
```

This results in two blocks of data in `tmpfile` (I replaced some of the output with `...`). The numbers in the second block do not match the first, and also the second block has less lines than the first.

```

times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.004  000.004: --- NVIM STARTING ---
000.091  000.087: event init
000.168  000.077: early init
000.211  000.043: locale set
000.252  000.041: init first window
000.469  000.217: inits 1
000.483  000.014: window checked
000.487  000.004: parsing arguments
000.812  000.038  000.038: require('vim.shared')
000.885  000.027  000.027: require('vim._meta')
000.887  000.072  000.046: require('vim._editor')
000.888  000.147  000.037: require('vim._init_packages')
...
012.380  000.002: editing files in windows
012.440  000.060: VimEnter autocommands
012.442  000.002: UIEnter autocommands
012.443  000.001: before starting main loop
013.327  000.885: first screen update
013.329  000.001: --- NVIM STARTED ---


times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.006  000.006: --- NVIM STARTING ---
009.772  009.766: event init
017.254  007.482: early init
017.296  000.042: locale set
021.391  004.095: init first window
027.266  005.875: inits 1
027.273  000.007: window checked
027.276  000.003: parsing arguments
031.589  000.031  000.031: require('vim.shared')
031.668  000.034  000.034: require('vim._meta')
031.669  000.077  000.043: require('vim._editor')
031.670  000.141  000.033: require('vim._init_packages')
031.673  004.255: init lua interpreter
032.279  000.606: expanding arguments
032.307  000.028: inits 2
032.544  000.237: init highlight
```

### Expected behavior

I expected a single block of data:

```
times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.004  000.004: --- NVIM STARTING ---
000.091  000.087: event init
000.168  000.077: early init
000.211  000.043: locale set
000.252  000.041: init first window
000.469  000.217: inits 1
000.483  000.014: window checked
000.487  000.004: parsing arguments
000.812  000.038  000.038: require('vim.shared')
000.885  000.027  000.027: require('vim._meta')
000.887  000.072  000.046: require('vim._editor')
000.888  000.147  000.037: require('vim._init_packages')
...
012.380  000.002: editing files in windows
012.440  000.060: VimEnter autocommands
012.442  000.002: UIEnter autocommands
012.443  000.001: before starting main loop
013.327  000.885: first screen update
013.329  000.001: --- NVIM STARTED ---
```

### Neovim version (nvim -v)

NVIM v0.9.0

### Vim (not Nvim) behaves the same?

No (9.0.242)

### Operating system/version

Kubuntu 22.10

### Terminal name/version

Konsole 22.08.2

### $TERM environment variable

xterm-256color

### Installation

appimage

### PR DESCRIPTION
**Pull request by pabloariasal**
Running the TUI as an external process (commit https://github.com/neovim/neovim/commit/24488169564c39a506c235bf6a33b8e23a8cb528) causes issues with the reporting of startup times (`--startuptime`), as there are now two different processes running concurrently, each writing its relative times to the same file simultaneously (see issue #23036).

This can potentially mess up the formatting of the file and makes its interpretation very hard as it interleaves two startup sequences into the same timeline.

There are multiple solutions to this problem:

### 1. Only report the startup times of the "main" process (recognized by `--embed` flag)

Pros:
* The output file will contain a single timeline (only main process writes to the file)
* Easiest to implement

Cons:
* we will lose the startup times of the TUI process

### 2. Combine the output of both processes into single timeline

Pros:
* single timeline for both processes

Cons:
* hard two implement as each process starts at a different time and has a different clock (hence, can't be modelled by same timeline)

```
clock  event
0.0     main startes
0.5     main does something
0.0     tui starts
0.7     main does something
0.3     tui does something
```

### 3. Each process has its own timeline

Pros:
* relatively easy to implement
* no loss of information

Cons:
* Multiple timelines instead of one

This MR implements option 3, meaning that we report the timeline of each process independently.
It introduces the following changes:

1. each process writes the startup times to a memory buffer first *no concurrent writing takes place)
2. when the process has finished with the initialization the buffer is flushed and appended to the report
3. the report now consists of different sections, one for each process

The new report looks like this:

```
--- Startup times for TUI process ---

times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.006  000.006: --- NVIM STARTING ---
000.428  000.422: event init
000.728  000.301: early init
...
005.880  000.713: init highlight
005.882  000.002: --- NVIM STARTED ---

--- Startup times for Main process ---

times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.006  000.006: --- NVIM STARTING ---
000.409  000.403: event init
000.557  000.148: early init
000.633  000.077: locale set
...
014.383  000.430: first screen update
014.387  000.003: --- NVIM STARTED ---
```

### Implementation notes

Originally I tried to use [open_memstream](https://man7.org/linux/man-pages/man3/open_memstream.3.html) which allocates a dynamic memory buffer where each process can write its the startup times, but I had the sad realization that it doesn't exist on windows....

However, if we can assume that all timings fit in a large enough buffer (currently set to 8k) we can use controlled buffering (setvbuf) to delay the flushing only after the initialization has concluded.

Fix #23036

### CODE REVIEW

File: src/nvim/profile.c [hunk 1]
```diff
@@ -943,3 +943,43 @@ void time_msg(const char *mesg, const proftime_T *start)
   g_prev_time = now;
   fprintf(time_fd, ": %s\n", mesg);
 }
+
+/// Initializes the time time_fd stream used to write startup times
+///
+/// @param startup_time_file the startuptime report file path
+/// @param process_name the name of the current process to write in the report. Example: "Main" or "TUI"
+void time_init(const char *startup_time_file, const char *process_name)
```
Comment (zeertzjq) [inline src/nvim/profile.c:951]: Better name these `startuptime_init()` and `startuptime_finish()`

Comment (zeertzjq) [reply src/nvim/profile.c]: Update: I didn't realized there are already many other functions with `time_` prefix. Maybe `time_` prefix is fine then. (although not straightforward enough)

Comment (pabloariasal) [reply src/nvim/profile.c:951]: yeah, I agree. Just reverted.

**Review by lewis6991 — APPROVED** [review]

File: src/nvim/main.c [hunk 2]
```diff
@@ -1494,9 +1498,18 @@ static void init_params(mparm_T *paramp, int argc, char **argv)
...
 {
+  // check if we are currently running as the tui or the main process
+  // the main process is always called with the --embed flag
+  bool is_main_process = false;
+  for (int i = 1; i < paramp->argc - 1; i++) {
+    if (STRICMP(paramp->argv[i], "--embed") == 0) {
+      is_main_process = true;
+      break;
+    }
+  }
```
Comment (zeertzjq) [inline src/nvim/main.c:1509]: This will recognize a headless instance as the TUI process.

Comment (zeertzjq) [reply src/nvim/main.c:1509]: Meanwhile it's hard to decide whether Nvim will be launched in headless mode without parsing arguments, so maybe it's necessary to parse arguments earlier?

Comment (pabloariasal) [reply src/nvim/main.c:1509]: good point. Can't we just explicitly search for the `--headless` option here?

```
bool is_main_process = hasFlagBeenSet("--headless") || hasFlagBeedSet("--embed");
```

Comment (zeertzjq) [reply src/nvim/main.c:1509]: No, there are other flags that imply headless mode.

Comment (pabloariasal) [reply src/nvim/main.c:1509]: In that case the easiest solution would probably be to rename the process in the report to something like "Primary/TUI". In that case in case of headless mode this will be the primary process, otherwise its the TUI process.

Comment (zeertzjq) [reply src/nvim/main.c:1509]: Then the variable should be called `is_embedded_process` instead of `is_main_process`.

Comment (pabloariasal) [reply src/nvim/main.c]: yes, agree with you

Comment (zeertzjq) [reply src/nvim/main.c]: It's "embedded", not "embeded"

Comment (pabloariasal) [reply src/nvim/main.c]: oops, english is hard ;)

File: src/nvim/main.c [hunk 3]
```diff
@@ -1494,9 +1498,18 @@ static void init_params(mparm_T *paramp, int argc, char **argv)
 /// Initialize global startuptime file if "--startuptime" passed as an argument.
 static void init_startuptime(mparm_T *paramp)
 {
+  // check if we are currently running as the tui or the main process
+  // the main process is always called with the --embed flag
```
Comment (zeertzjq) [inline src/nvim/main.c:1502]: I think this comment can just be deleted. It's quite obvious what the code does.

File: src/nvim/profile.c [hunk 4]
```diff
@@ -944,3 +944,43 @@ void time_msg(const char *mesg, const proftime_T *start)
   g_prev_time = now;
   fprintf(time_fd, ": %s\n", mesg);
 }
+
+/// Initializes the time time_fd stream used to write startup times
+///
+/// @param startup_time_file the startuptime report file path
+/// @param process_name the name of the current process to write in the report. Example: "Main" or "TUI"
```
Comment (zeertzjq) [inline src/nvim/profile.c:951]: This comment now also needs change.

File: src/nvim/main.c (hunk 3 above)
Comment (pabloariasal) [reply src/nvim/main.c:1502]: done

File: src/nvim/profile.c (hunk 4 above)
Comment (pabloariasal) [reply src/nvim/profile.c:951]: done

File: src/nvim/globals.h [hunk 5]
```diff
@@ -977,6 +977,8 @@ EXTERN const char bot_top_msg[] INIT(= N_("search hit BOTTOM, continuing at TOP"
 EXTERN const char line_msg[] INIT(= N_(" line "));
 
 EXTERN FILE *time_fd INIT(= NULL);  // where to write startup timing
+#define STARTUP_TIME_BUF_SIZE 8192
+EXTERN char *startup_time_buf INIT(= NULL); // startup timing buffer
```
Comment (justinmk) [inline src/nvim/globals.h:981]: Avoid unnecessary entropy. The option is named `--startuptime`.
```suggestion
EXTERN char *startuptime_buf INIT(= NULL); // --startuptime buffer
```

File: runtime/doc/news.txt [hunk 6]
```diff
@@ -393,6 +393,8 @@ The following changes to existing APIs or features add new behavior.
 • |:checkhealth| buffer can now be opened in a split window using modifiers like
   |:vertical|, |:horizontal| and |:botright|.
 
+• `--startuptime` now reports the startup times per process individually.
```
Comment (justinmk) [inline runtime/doc/news.txt:396]:
```suggestion
• |--startuptime| now reports the startup times per process individually.
```

File: src/nvim/main.c [hunk 7]
```diff
@@ -1494,9 +1498,16 @@ static void init_params(mparm_T *paramp, int argc, char **argv)
 /// Initialize global startuptime file if "--startuptime" passed as an argument.
 static void init_startuptime(mparm_T *paramp)
 {
+  bool is_embedded_process = false;
+  for (int i = 1; i < paramp->argc - 1; i++) {
+    if (STRICMP(paramp->argv[i], "--embed") == 0) {
+      is_embedded_process = true;
```
Comment (justinmk) [inline src/nvim/main.c:1504]: `init_startuptime` is called after `init_params`. Can you use the existing `embedded_mode` instead of re-scanning the args?

File: src/nvim/main.c [hunk 8]
```diff
@@ -1494,9 +1498,16 @@ static void init_params(mparm_T *paramp, int argc, char **argv)
...
+      break;
+    }
+  }
   for (int i = 1; i < paramp->argc - 1; i++) {
     if (STRICMP(paramp->argv[i], "--startuptime") == 0) {
-      time_fd = fopen(paramp->argv[i + 1], "a");
+      time_init(paramp->argv[i + 1], is_embedded_process ? "Embedded" : "Primary/TUI");
```
Comment (justinmk) [inline src/nvim/main.c:1510]:
```suggestion
      time_init(paramp->argv[i + 1], embedded_mode ? "Embedded" : "Primary/TUI");
```

File: src/nvim/profile.c [hunk 9]
```diff
@@ -944,3 +944,43 @@ void time_msg(const char *mesg, const proftime_T *start)
...
+void time_init(const char *startup_time_file, const char *process_name)
+{
+  time_fd = fopen(startup_time_file, "a");
+  if (time_fd == NULL) {
+    semsg(_(e_notopen), startup_time_file);
+    return;
+  }
+  startup_time_buf = xmalloc(sizeof(char) * (STARTUP_TIME_BUF_SIZE + 1));
+  // set a large buffer so that flushing only happens after initialization
+  if (setvbuf(time_fd, startup_time_buf, _IOFBF, STARTUP_TIME_BUF_SIZE + 1) != 0) {
```
Comment (justinmk) [inline src/nvim/profile.c:961]: Is there any more insight that can be given in the comment here about how `setvbuf` is being leveraged? It's somewhat subtle (and not common in the codebase).

File: src/nvim/normal.c [hunk 10]
```diff
@@ -1455,9 +1455,7 @@ static int normal_check(VimState *state)
     // has been done, close any file for startup messages.
     if (time_fd != NULL) {
       TIME_MSG("first screen update");
```
Comment (justinmk) [inline src/nvim/normal.c:1457]: might as well move this into `time_finish` also?

**Comment by justinmk** [comment]
Is there an extra assert you can add to the existing test for `--startuptime` : https://github.com/neovim/neovim/blob/95cbedaa1798a7c1489b68dd60380a41443ed34b/test/functional/core/startup_spec.lua#L70-L78

File: runtime/doc/news.txt (hunk 6 above)
Comment (pabloariasal) [reply runtime/doc/news.txt]: just for my own understanding, `|foo|` is a link to the help, right? How can I know when I need to use `|foo|`?

File: src/nvim/main.c (hunk 7 above)
Comment (pabloariasal) [reply src/nvim/main.c:1504]: maybe I'm confused but `init_params` just initializes the `paramp` struct to default values and doesn't actually parse anything.

```
static void init_params(mparm_T *paramp, int argc, char **argv)
{
  CLEAR_POINTER(paramp);
  paramp->argc = argc;
  paramp->argv = argv;
  paramp->use_debug_break_level = -1;
  paramp->window_count = -1;
  paramp->listen_addr = NULL;
  paramp->server_addr = NULL;
  paramp->remote = 0;
  paramp->luaf = NULL;
  paramp->lua_arg0 = -1;
}
```
https://github.com/pabloariasal/neovim/blob/fix_startup_time/src/nvim/main.c#L1484

Comment (justinmk) [reply src/nvim/main.c:1504]: Ah sorry I was thinking of `command_line_scan`. 

I guess we can't move this down, since the profiling needs to start here. We could set `embedded_mode` here and remove the duplicate logic from `command_line_scan` ... not sure if that helps anything. 

Can leave this as-is for now.

File: src/nvim/main.c [hunk 11]
```diff
@@ -1494,9 +1498,16 @@ static void init_params(mparm_T *paramp, int argc, char **argv)
...
+  for (int i = 1; i < paramp->argc - 1; i++) {
+    if (STRICMP(paramp->argv[i], "--embed") == 0) {
+      is_embedded_process = true;
+      break;
+    }
+  }
   for (int i = 1; i < paramp->argc - 1; i++) {
     if (STRICMP(paramp->argv[i], "--startuptime") == 0) {
-      time_fd = fopen(paramp->argv[i + 1], "a");
+      time_init(paramp->argv[i + 1], embedded_mode ? "Embedded" : "Primary/TUI");
```
Comment (justinmk) [inline src/nvim/main.c:1510]: Is "primary" used anywhere else? Don't think that will help anyone by introducing extra jargon.
```suggestion
      time_init(paramp->argv[i + 1], embedded_mode ? "Embedded" : "TUI");
```

File: runtime/doc/news.txt (hunk 6 above)
Comment (justinmk) [reply runtime/doc/news.txt]: the help docs give lots of examples :) 

use `|tag|` whenever there is a `*tag*` defined somewhere.

File: src/nvim/main.c (hunk 11 above)
Comment (pabloariasal) [reply src/nvim/main.c:1510]: yes, I was very unsure on how to call the processes in the report. My first approach was to name "TUI" the client process and "Main" the server, however @zeertzjq correctly realized that the name "TUI" breaks the moment nvim is invoked in headless mode. That's why I started to think in more general terms like, "primary" or "secondary" process, to account for the headless scenario.

File: src/nvim/profile.c (hunk 9 above)
Comment (pabloariasal) [reply src/nvim/profile.c]: tried to give more information in the comment

File: src/nvim/main.c (hunk 11 above)
Comment (justinmk) [reply src/nvim/main.c]: `TUI/client` addresses that edge-case.

File: src/nvim/main.c [hunk 12]
```diff
@@ -1494,9 +1498,16 @@ static void init_params(mparm_T *paramp, int argc, char **argv)
 /// Initialize global startuptime file if "--startuptime" passed as an argument.
 static void init_startuptime(mparm_T *paramp)
 {
+  bool is_embedded_process = false;
```
Comment (justinmk) [inline src/nvim/main.c:1501]: variables in small scopes really don't need such verbose names.
```suggestion
  bool is_embed = false;
```

**Review by justinmk — APPROVED** [review]
LGTM after remaining nits.

File: src/nvim/main.c (hunk 11 above)
Comment (zeertzjq) [reply src/nvim/main.c]: I don't think it's "client" as headless instance are usually servers.

File: src/nvim/profile.c [hunk 13]
```diff
@@ -944,3 +944,50 @@ void time_msg(const char *mesg, const proftime_T *start)
...
+    return;
+  }
+  startuptime_buf = xmalloc(sizeof(char) * (STARTUP_TIME_BUF_SIZE + 1));
+  // the startuptime file is (potentially) bein written by several nvim processes concurrently.
+  // in order to avoid messing up the file with concurrent writes all startuptimes are written
+  // to a memory buffer first and flushed to disk only after the process is done with the
+  // is done with the initialization.
+  // in order to achieve this we set a large-enough buffer to the file stream, big enough to store
+  // all startup times. The _IOFBF mode makes sure that the buffer is not automatically flushed
+  // ("controlled buffering").
```
Comment (justinmk) [inline src/nvim/profile.c:966]: - correct punctuation in code comments, reduces ambiguity and increases consistency, at negligible cost.
- there were typos and the comment was verbose, so I condensed it (without losing information).

please consider these guidelines in the future.

```suggestion
  // The startuptime file is (potentially) written by multiple nvim processes concurrently. So
  // startuptime info is buffered, and flushed to disk only after startup completed. To achieve that
  // we set a buffer big enough to store all startup times. The `_IOFBF` mode ensures the buffer is
  // not auto-flushed ("controlled buffering").
```

File: src/nvim/profile.c [hunk 14]
```diff
@@ -944,3 +944,50 @@ void time_msg(const char *mesg, const proftime_T *start)
...
+  // The times are flushed to disk manually when "time_finish" is called.
+  if (setvbuf(time_fd, startuptime_buf, _IOFBF, STARTUP_TIME_BUF_SIZE + 1) != 0) {
+    xfree(startuptime_buf);
+    fclose(time_fd);
+    time_fd = NULL;
+    semsg("Error initializing startup time");
+    return;
```
Comment (justinmk) [inline src/nvim/profile.c:973]: untested but should work:

```suggestion
  int r = setvbuf(time_fd, startuptime_buf, _IOFBF, STARTUP_TIME_BUF_SIZE + 1);
  if (r != 0) {
    xfree(startuptime_buf);
    fclose(time_fd);
    time_fd = NULL;
    // Might as well ELOG also I guess.
    ELOG("time_init: setvbuf failed: %d %s", r, uv_err_name(r));
    semsg("time_init: setvbuf failed: %d %s", r, uv_err_name(r));
    return;
```

File: src/nvim/profile.c [hunk 15]
```diff
@@ -944,3 +944,50 @@ void time_msg(const char *mesg, const proftime_T *start)
...
+  }
+  assert(startuptime_buf != NULL);
+  TIME_MSG("--- NVIM STARTED ---\n");
+
+  // flush buffer to disk
+  fclose(time_fd);
+  time_fd = NULL;
+
+  xfree(startuptime_buf);
+  startuptime_buf = NULL;
```
Comment (justinmk) [inline src/nvim/profile.c:992]:
```suggestion
  XFREE_CLEAR(startuptime_buf);
```

File: src/nvim/main.c (hunk 11 above)
Comment (pabloariasal) [reply src/nvim/main.c]: changed

File: src/nvim/main.c (hunk 12 above)
Comment (pabloariasal) [reply src/nvim/main.c]: changed

File: src/nvim/profile.c (hunk 13 above)
Comment (pabloariasal) [reply src/nvim/profile.c:966]: done

File: runtime/doc/news.txt [hunk 16]
```diff
@@ -415,6 +415,7 @@ The following changes to existing APIs or features add new behavior.
 
 • 'errorfile' (|-q|) accepts `-` as an alias for stdin.
 
+• |--startuptime| reports the startup times for both processes (TUI + server) as separate sections.
 ==============================================================================
```
Comment (justinmk) [inline runtime/doc/news.txt:419]:
```suggestion
• |--startuptime| reports the startup times for both processes (TUI + server) as separate sections.

==============================================================================
```

**Review by justinmk — APPROVED** [review]
