### PR TITLE
Fix issues revealed by gcc10 setting -fno-common by default

### LINKED ISSUE #12423: Build fails with GCC 10
Note that `gcc 10.1.0` has switch default to `-fno-common` and it leads to the following list of errors:

```
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/__/__/config/auto/pathdef.c.o (symbol from plugin): in function `compiled_sys':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/buffer.c.o (symbol from plugin): in function `nvim_buf_line_count':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/buffer.c.o (symbol from plugin): in function `nvim_buf_line_count':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/private/dispatch.c.o (symbol from plugin): in function `handle_nvim_buf_line_count':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/private/dispatch.c.o (symbol from plugin): in function `handle_nvim_buf_line_count':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/private/handle.c.o (symbol from plugin): in function `handle_get_buffer':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/private/helpers.c.o (symbol from plugin): in function `try_enter':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/private/helpers.c.o (symbol from plugin): in function `try_enter':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/tabpage.c.o (symbol from plugin): in function `nvim_tabpage_list_wins':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/tabpage.c.o (symbol from plugin): in function `nvim_tabpage_list_wins':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/ui.c.o (symbol from plugin): in function `remote_ui_init':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/ui.c.o (symbol from plugin): in function `remote_ui_init':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/vim.c.o (symbol from plugin): in function `api_vim_init':
[   79s] (.text+0x0): multiple definition of `ch_before_blocking_events'; CMakeFiles/nvim.dir/api/ui.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/vim.c.o (symbol from plugin): in function `api_vim_init':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/vim.c.o (symbol from plugin): in function `api_vim_init':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/window.c.o (symbol from plugin): in function `nvim_win_get_buf':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/api/window.c.o (symbol from plugin): in function `nvim_win_get_buf':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/arabic.c.o (symbol from plugin): in function `arabic_shape':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/aucmd.c.o (symbol from plugin): in function `do_autocmd_uienter':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/buffer.c.o (symbol from plugin): in function `set_bufref':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/buffer.c.o (symbol from plugin): in function `set_bufref':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/buffer_updates.c.o (symbol from plugin): in function `buf_updates_active':
[   79s] (.text+0x0): multiple definition of `ch_before_blocking_events'; CMakeFiles/nvim.dir/api/ui.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/buffer_updates.c.o (symbol from plugin): in function `buf_updates_active':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/buffer_updates.c.o (symbol from plugin): in function `buf_updates_active':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/change.c.o (symbol from plugin): in function `change_warning':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/channel.c.o (symbol from plugin): in function `channels':
[   79s] (.text+0x0): multiple definition of `ch_before_blocking_events'; CMakeFiles/nvim.dir/api/ui.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/channel.c.o (symbol from plugin): in function `channels':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/channel.c.o (symbol from plugin): in function `channels':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/charset.c.o (symbol from plugin): in function `str_foldcase':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/context.c.o (symbol from plugin): in function `ctx_size':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/context.c.o (symbol from plugin): in function `ctx_size':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/cursor.c.o (symbol from plugin): in function `getviscol':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/cursor_shape.c.o (symbol from plugin): in function `mode_style_array':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/cursor_shape.c.o (symbol from plugin): in function `mode_style_array':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/diff.c.o (symbol from plugin): in function `diff_internal':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/digraph.c.o (symbol from plugin): in function `get_digraph_for_char':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/digraph.c.o (symbol from plugin): in function `get_digraph_for_char':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/edit.c.o (symbol from plugin): in function `pum_want':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/edit.c.o (symbol from plugin): in function `pum_want':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/eval.c.o (symbol from plugin): in function `current_funccal':
[   79s] (.text+0x0): multiple definition of `ch_before_blocking_events'; CMakeFiles/nvim.dir/api/ui.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/eval.c.o (symbol from plugin): in function `current_funccal':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/eval.c.o (symbol from plugin): in function `current_funccal':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/eval/decode.c.o (symbol from plugin): in function `decode_create_map_special_dict':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/eval/encode.c.o (symbol from plugin): in function `encode_list_write':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/eval/executor.c.o (symbol from plugin): in function `eexe_mod_op':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/eval/gc.c.o (symbol from plugin): in function `gc_first_list':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/eval/typval.c.o (symbol from plugin): in function `tv_list_watch_add':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/event/libuv_process.c.o (symbol from plugin): in function `libuv_process_spawn':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/event/process.c.o (symbol from plugin): in function `process_spawn':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/event/rstream.c.o (symbol from plugin): in function `rstream_init':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/event/socket.c.o (symbol from plugin): in function `socket_watcher_init':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/event/wstream.c.o (symbol from plugin): in function `wstream_init':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ex_cmds.c.o (symbol from plugin): in function `do_ascii':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ex_cmds.c.o (symbol from plugin): in function `do_ascii':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ex_cmds2.c.o (symbol from plugin): in function `do_debug':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ex_cmds2.c.o (symbol from plugin): in function `do_debug':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ex_docmd.c.o (symbol from plugin): in function `ex_ni':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ex_docmd.c.o (symbol from plugin): in function `ex_ni':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ex_eval.c.o (symbol from plugin): in function `aborting':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ex_getln.c.o (symbol from plugin): in function `text_locked':
[   79s] (.text+0x0): multiple definition of `ExprParserFlags'; CMakeFiles/nvim.dir/api/vim.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ex_getln.c.o (symbol from plugin): in function `text_locked':
[   79s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ex_getln.c.o (symbol from plugin): in function `text_locked':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   79s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/file_search.c.o (symbol from plugin): in function `vim_findfile_stopdir':
[   79s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/fileio.c.o (symbol from plugin): in function `getnextac':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/fileio.c.o (symbol from plugin): in function `getnextac':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/fold.c.o (symbol from plugin): in function `foldmethodIsManual':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/garray.c.o (symbol from plugin): in function `ga_clear':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/getchar.c.o (symbol from plugin): in function `free_buff':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/getchar.c.o (symbol from plugin): in function `free_buff':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/hardcopy.c.o (symbol from plugin): in function `parse_printoptions':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/hashtab.c.o (symbol from plugin): in function `hash_removed':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/highlight.c.o (symbol from plugin): in function `highlight_init':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/highlight.c.o (symbol from plugin): in function `highlight_init':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/if_cscope.c.o (symbol from plugin): in function `get_cscope_name':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/indent.c.o (symbol from plugin): in function `get_indent_str':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/indent_c.c.o (symbol from plugin): in function `find_start_comment':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/keymap.c.o (symbol from plugin): in function `name_to_mod_mask':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/log.c.o (symbol from plugin): in function `log_init':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/lua/converter.c.o (symbol from plugin): in function `nlua_pop_typval':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/lua/converter.c.o (symbol from plugin): in function `nlua_pop_typval':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/lua/executor.c.o (symbol from plugin): in function `nlua_debug':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/lua/executor.c.o (symbol from plugin): in function `nlua_debug':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/main.c.o (symbol from plugin): in function `headless_mode':
[   80s] (.text+0x0): multiple definition of `ch_before_blocking_events'; CMakeFiles/nvim.dir/api/ui.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/main.c.o (symbol from plugin): in function `headless_mode':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/main.c.o (symbol from plugin): in function `headless_mode':
[   80s] (.text+0x0): multiple definition of `channels'; CMakeFiles/nvim.dir/channel.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/main.c.o (symbol from plugin): in function `headless_mode':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/map.c.o (symbol from plugin): in function `kh_init_int_int_map':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/mark.c.o (symbol from plugin): in function `free_fmark':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/mbyte.c.o (symbol from plugin): in function `enc_canon_props':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/memfile.c.o (symbol from plugin): in function `mf_new_page_size':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/memline.c.o (symbol from plugin): in function `ml_open':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/memline.c.o (symbol from plugin): in function `ml_open':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/memory.c.o (symbol from plugin): in function `try_to_free_memory':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/menu.c.o (symbol from plugin): in function `menu_name_skip':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/menu.c.o (symbol from plugin): in function `menu_name_skip':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/message.c.o (symbol from plugin): in function `msg_grid_set_pos':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/message.c.o (symbol from plugin): in function `msg_grid_set_pos':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/misc1.c.o (symbol from plugin): in function `get_leader_len':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/misc1.c.o (symbol from plugin): in function `get_leader_len':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/mouse.c.o (symbol from plugin): in function `mouse_comp_pos':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/move.c.o (symbol from plugin): in function `reset_cursorline':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/msgpack_rpc/channel.c.o (symbol from plugin): in function `ch_before_blocking_events':
[   80s] (.text+0x0): multiple definition of `ch_before_blocking_events'; CMakeFiles/nvim.dir/api/ui.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/msgpack_rpc/channel.c.o (symbol from plugin): in function `ch_before_blocking_events':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/msgpack_rpc/channel.c.o (symbol from plugin): in function `ch_before_blocking_events':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/msgpack_rpc/helpers.c.o (symbol from plugin): in function `msgpack_rpc_helpers_init':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/msgpack_rpc/helpers.c.o (symbol from plugin): in function `msgpack_rpc_helpers_init':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/msgpack_rpc/server.c.o (symbol from plugin): in function `server_teardown':
[   80s] (.text+0x0): multiple definition of `ch_before_blocking_events'; CMakeFiles/nvim.dir/api/ui.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/msgpack_rpc/server.c.o (symbol from plugin): in function `server_teardown':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/normal.c.o (symbol from plugin): in function `init_normal_cmds':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/normal.c.o (symbol from plugin): in function `init_normal_cmds':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ops.c.o (symbol from plugin): in function `get_op_type':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ops.c.o (symbol from plugin): in function `get_op_type':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/option.c.o (symbol from plugin): in function `set_options_bin':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/option.c.o (symbol from plugin): in function `set_options_bin':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/dl.c.o (symbol from plugin): in function `os_libcall':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/env.c.o (symbol from plugin): in function `env_init':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/fileio.c.o (symbol from plugin): in function `file_open_fd':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/fs.c.o (symbol from plugin): in function `fs_init':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/input.c.o (symbol from plugin): in function `ch_before_blocking_events':
[   80s] (.text+0x0): multiple definition of `ch_before_blocking_events'; CMakeFiles/nvim.dir/api/ui.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/input.c.o (symbol from plugin): in function `ch_before_blocking_events':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/input.c.o (symbol from plugin): in function `ch_before_blocking_events':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/lang.c.o (symbol from plugin): in function `lang_init':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/mem.c.o (symbol from plugin): in function `os_get_total_mem_kib':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/process.c.o (symbol from plugin): in function `os_proc_tree_kill':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/process.c.o (symbol from plugin): in function `os_proc_tree_kill':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/pty_process_unix.c.o (symbol from plugin): in function `pty_process_save_termios':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/shell.c.o (symbol from plugin): in function `shell_build_argv':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/signal.c.o (symbol from plugin): in function `signal_init':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/stdpaths.c.o (symbol from plugin): in function `stdpaths_get_xdg_var':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/time.c.o (symbol from plugin): in function `time_init':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/tty.c.o (symbol from plugin): in function `ListLenSpecials':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os/users.c.o (symbol from plugin): in function `os_get_usernames':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os_unix.c.o (symbol from plugin): in function `mch_get_acl':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/os_unix.c.o (symbol from plugin): in function `mch_get_acl':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/path.c.o (symbol from plugin): in function `vim_ispathsep':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/popupmnu.c.o (symbol from plugin): in function `pum_redraw':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/popupmnu.c.o (symbol from plugin): in function `pum_redraw':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/profile.c.o (symbol from plugin): in function `profile_start':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/quickfix.c.o (symbol from plugin): in function `qf_init':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/quickfix.c.o (symbol from plugin): in function `qf_init':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/rbuffer.c.o (symbol from plugin): in function `rbuffer_new':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/regexp.c.o (symbol from plugin): in function `re_multiline':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/screen.c.o (symbol from plugin): in function `redraw_win_later':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/screen.c.o (symbol from plugin): in function `redraw_win_later':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/search.c.o (symbol from plugin): in function `get_search_pat':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/search.c.o (symbol from plugin): in function `get_search_pat':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/sha256.c.o (symbol from plugin): in function `sha256_start':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/shada.c.o (symbol from plugin): in function `shada_write_file':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/shada.c.o (symbol from plugin): in function `shada_write_file':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/sign.c.o (symbol from plugin): in function `init_signs':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/spell.c.o (symbol from plugin): in function `spelltab':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/spell.c.o (symbol from plugin): in function `spelltab':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/spellfile.c.o (symbol from plugin): in function `spell_load_file':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/state.c.o (symbol from plugin): in function `state_enter':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/state.c.o (symbol from plugin): in function `state_enter':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/strings.c.o (symbol from plugin): in function `vim_strsave':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/strings.c.o (symbol from plugin): in function `vim_strsave':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/syntax.c.o (symbol from plugin): in function `syn_set_timeout':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/syntax.c.o (symbol from plugin): in function `syn_set_timeout':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/tag.c.o (symbol from plugin): in function `tag_freematch':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/terminal.c.o (symbol from plugin): in function `terminal_init':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/terminal.c.o (symbol from plugin): in function `terminal_init':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/tui/input.c.o (symbol from plugin): in function `tinput_init':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/tui/input.c.o (symbol from plugin): in function `tinput_init':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/tui/terminfo.c.o (symbol from plugin): in function `terminfo_is_term_family':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/tui/tui.c.o (symbol from plugin): in function `tui_start':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/tui/tui.c.o (symbol from plugin): in function `tui_start':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ugrid.c.o (symbol from plugin): in function `ugrid_init':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ui.c.o (symbol from plugin): in function `ui_call_mode_info_set':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ui.c.o (symbol from plugin): in function `ui_call_mode_info_set':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ui_bridge.c.o (symbol from plugin): in function `ui_bridge_attach':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ui_bridge.c.o (symbol from plugin): in function `ui_bridge_attach':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ui_compositor.c.o (symbol from plugin): in function `layers':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/ui_compositor.c.o (symbol from plugin): in function `layers':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/undo.c.o (symbol from plugin): in function `undo_allowed':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/version.c.o (symbol from plugin): in function `has_nvim_version':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/version.c.o (symbol from plugin): in function `has_nvim_version':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/viml/parser/expressions.c.o (symbol from plugin): in function `viml_pexpr_next_token':
[   80s] (.text+0x0): multiple definition of `ExprParserFlags'; CMakeFiles/nvim.dir/api/vim.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/viml/parser/expressions.c.o (symbol from plugin): in function `viml_pexpr_next_token':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/window.c.o (symbol from plugin): in function `win_set_minimal_style':
[   80s] (.text+0x0): multiple definition of `RemapValues'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here
[   80s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/nvim.dir/window.c.o (symbol from plugin): in function `win_set_minimal_style':
[   80s] (.text+0x0): multiple definition of `ListLenSpecials'; CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o (symbol from plugin):(.text+0x0): first defined here

```

### PR DESCRIPTION
**Pull request by cryptomilk**
Hi,

these fixes issues revealed by gcc10 which sets -fno-common by default.

See https://bugzilla.redhat.com/show_bug.cgi?id=1799680

### CODE REVIEW

File: src/nvim/msgpack_rpc/channel.c [hunk 1]
```diff
@@ -41,6 +41,8 @@
 static PMap(cstr_t) *event_strings = NULL;
 static msgpack_sbuffer out_buffer;
 
+extern MultiQueue *ch_before_blocking_events;
```
Comment (bfredl) [inline src/nvim/msgpack_rpc/channel.c]: This is a regression, now the sharing is implicit rather than explicit. Better to keep it in the `.h` file and use the EXTERN/INIT pattern (and make sure it is included in main.c to make the INIT work).

File: src/nvim/channel.h [hunk 2]
```diff
@@ -85,7 +85,7 @@ struct Channel {
   bool callback_scheduled;
 };
 
-EXTERN PMap(uint64_t) *channels;
+extern PMap(uint64_t) *channels;
```
Comment (bfredl) [inline src/nvim/channel.h]: `EXTERN PMap(uint64_t) *channels INIT(= NULL);`

File: src/nvim/msgpack_rpc/channel.c (hunk 1 above)
Comment (cryptomilk) [reply src/nvim/msgpack_rpc/channel.c]: Lets see if this works. Thanks.

File: src/nvim/channel.h (hunk 2 above)
Comment (cryptomilk) [reply src/nvim/channel.h]: Thanks, will change it.

**Comment by cryptomilk** [comment]
Ouch, on FreeBSD it finds a lot issues if you set `-fno-common`.

**Comment by cryptomilk** [comment]
@bfredl I've created a test build with the changes you requested for channels, it still complains:

https://koji.fedoraproject.org/koji/taskinfo?taskID=41554555

This EXTERN and INIT doesn't work that very well. Instead of extern it would be nicer to have globals as static global variables in .c files and have getter and setter for it.

Also the `-fno-common` commit I pushed shows there are probably much more issues.

**Comment by bfredl** [comment]
> This EXTERN and INIT doesn't work that very well.

The __first attempt__ at adding EXTERN/INIT to this particular variable didn't work. We need to "make sure it is included in main.c to make the INIT work" also in this case. The initialization in src/nvim/channel.c needs to be removed then.

> Instead of extern it would be nicer to have globals as static global variables in .c files and have getter and setter for it.

This would be adding an insane amount of bureaucracy in order to solve something which never was a problem, and is not "nicer"  in any way.

**Comment by cryptomilk** [comment]
I hope this works now.

**Comment by cryptomilk** [comment]
clang-asan in travis reports a memory leak in `src/libuv/src/unix/core.c`. I haven't touched that code.

**Comment by cryptomilk** [comment]
I think this is good to go ...

File: src/nvim/os/input.c [hunk 3]
```diff
@@ -7,13 +7,18 @@
 
 #include <uv.h>
 
+// This needs to be included before we define EXTERN
+#include "nvim/ui.h"
+#include "nvim/msgpack_rpc/channel.h"
+
+#undef EXTERN
+#define EXTERN
```
Comment (bfredl) [inline src/nvim/os/input.c]: what is this for?

Comment (cryptomilk) [reply src/nvim/os/input.c]: `EXTERN` gets defined by macros.h to:

``
7 # define EXTERN extern
``

which gets included by globals.h. globals.h gets included by ui.h. But this fine wants to define global variables with EXTERN defined to extern. So we need to undefine the EXTERN from macros.h ...

Comment (cryptomilk) [reply src/nvim/os/input.c]: s/fine/file/

Comment (cryptomilk) [reply src/nvim/os/input.c]: I've added comments to make it clearer in the code.

File: CMakeLists.txt [hunk 4]
```diff
@@ -306,6 +306,11 @@ if(UNIX)
     add_compile_options(-fstack-protector --param ssp-buffer-size=4)
     link_libraries(-fstack-protector --param ssp-buffer-size=4)
   endif()
+
+  check_c_compiler_flag(-fno-common HAVE_FNO_COMMON)
+  if (HAVE_FNO_COMMON)
+    add_compile_options(-fno-common)
+  endif()
```
Comment (justinmk) [inline CMakeLists.txt]: why is this in the `if(UNIX)` block? Is there a reason to avoid it on non-unix, if the flag is supported there?

File: src/nvim/os/input.c [hunk 5]
```diff
@@ -7,13 +7,27 @@
...
+// For ui.h and channel.h we want to have 'extern' global
+// variables, so we need to include them before we define
+// EXTERN to an empty value.
+#include "nvim/macros.h"
+
+#include "nvim/ui.h"
+#include "nvim/msgpack_rpc/channel.h"
+
+// We want to define global variables here, so set EXTERN
+// to an emtpy define and set INIT()
```
Comment (justinmk) [inline src/nvim/os/input.c]: typo. Though the comment doesn't really explain anything. "set EXTERN to empty" just above `#undef EXTERN` is not helpful...

Comment (bfredl) [reply src/nvim/os/input.c]: This should be done by including `os/input.h` in `main.c`, as is done exactly all other global variable definitions.

This currently changes the interpretation of 14 unrelated header file which is not an improvement in any way, shape or form. "Robustness" improvements like this should be done by following some set of rules, not by randomly changing #defines and #includes around until it complies without warnings by accident.

File: CMakeLists.txt (hunk 4 above)
Comment (cryptomilk) [reply CMakeLists.txt]: I've moved it out of the UNIX if-clause.

File: src/nvim/os/input.c (hunk 5 above)
Comment (cryptomilk) [reply src/nvim/os/input.c]: Sorry, I'm new to the neovim codebase and need to find my way first. Don't blame me for doing this wrong. I did not `#define EXTERN` it was already in that file.

 I'm trying to fix this and get it working correctly. It looks like we just need to remove the `#define EXTERN` from that file then. The `nvim/os/input.h` is already correctly included in main.c

Comment (bfredl) [reply src/nvim/os/input.c]: Hmm are you sure? I can't find "#define EXTERN` anywhere except `macros.h` and `main.c` .

Comment (cryptomilk) [reply src/nvim/os/input.c]: Ups :-) Should be fixed now.

**Comment by cryptomilk** [comment]
Looks like finally all passed, but there is an unrelated issue on MacOSX:

```
sudo: cpanm: command not found
cat: /Users/travis/.cpanm/build.log: No such file or directory
The command "ci/install.sh" failed and exited with 1 during .
```

**Comment by cryptomilk** [comment]
I've rebased on master and pushed again to get a new CI run with fixes for homebrew.

**Comment by bfredl** [comment]
Looks good now, merged!

**Comment by cryptomilk** [comment]
Thanks! I'm fixing the fedora package now.

**Comment by cryptomilk** [comment]
@mcepl You might be interested in this patchset too.
