### PR TITLE
[RFC] don't wait_return in the middle of a vim_err_write message

### LINKED ISSUE #2547: vim_err_write might ask "Press ENTER" in the middle of an (async) message
In a python remote plugin, I wanted to echo traceback on error also from notification handlers. However, when `nvim` recieves `vim_err_write` asynchronously, sometimes, the message is split on every newline, except for the first one. I e
```
import neovim
vim = neovim.attach(...)
vim.err_write("1\n2\n3\n4\n")
```
(from an external python) gives
```
1 
2 
Press ENTER or type command to continue 
3
Press ENTER or type command to continue  
4     
Press ENTER or type command to continue
```
While, a err_write during a blocking request, for instance `:python vim.err_write("1\n2\n3\n4\n")` works as expected (one single interrupt).
 It seems, `emsg()` is very dependent on the "context" of the error to group several messages (and `vim_err_write` must currently split each line to `emsg()`), and during an async event this context is not well defined.

### PR DESCRIPTION
**Pull request by bfredl**
fixes #2547 .I don't really now if/how #1802 relates to this issue anymore, but this just fixes by reusing the existing logic e.g. used for do_cmdline.

### CODE REVIEW

**Comment by justinmk** [comment]
:+1: this only affects the API.

**Comment by justinmk** [comment]
It should be straightforward to write a test for this, no?

**Comment by bfredl** [comment]
Almost straightforward, needs neovim/lua-client#12

**Comment by bfredl** [comment]
I tried rebase after #3281  but something went wrong: (both travis and locally)
```
[100%] Generating usr/lib/luarocks/rocks/nvim-client
Warning: falling back to curl - install luasec to get native HTTPS support

Missing dependencies for nvim-client:
coxpcall 
lua-messagepack 

Using https://luarocks.org/coxpcall-1.15.0-1.src.rock... switching to 'build' mode
Updating manifest for /home/bjorn/dev/neovim/.deps/usr/lib/luarocks/rocks
coxpcall 1.15.0-1 is now built and installed in /home/bjorn/dev/neovim/.deps/usr (license: MIT/X11)

Using https://luarocks.org/lua-messagepack-0.3.3-1.src.rock... switching to 'build' mode
Updating manifest for /home/bjorn/dev/neovim/.deps/usr/lib/luarocks/rocks
lua-messagepack 0.3.3-1 is now built and installed in /home/bjorn/dev/neovim/.deps/usr (license: MIT/X11)


Error: Build error: Missing build.modules table
CMakeFiles/nvim-client.dir/build.make:60: recipe for target 'usr/lib/luarocks/rocks/nvim-client' failed
```

**Comment by justinmk** [comment]
I dropped the ball here, sorry. Could you modify the luarocks task to build in verbose mode? See https://github.com/neovim/neovim/issues/3107#issuecomment-125055289 for the line to change. Then we can see what's failing.

**Comment by bfredl** [comment]
```
os.execute: 	'curl' -k -f -L --user-agent 'LuaRocks/scm linux-x86_64 via curl' --connect-timeout 30 'https://github.com/neovim/lua-client/archive/0.0.1-13.tar.gz' 2> /dev/null 1> '/tmp/luarocks_luarocks-source-nvim-client-0.0.1-13-5520/0.0.1-13.tar.gz'
Results: 1
  1 (number): 0

os.execute: 	gunzip -c 0.0.1-13.tar.gz|tar -xf -
Results: 1
  1 (number): 0

Error: Build error: Missing build.modules table
```

**Comment by bfredl** [comment]
no obviously broken url:s what I see...

**Comment by justinmk** [comment]
Oh, I get it. In https://github.com/neovim/lua-client/pull/14 I removed the `make_plat` call which was _also_ build the `modules` value.  This was sloppy on my part, I did not realize that `make_plat` was our function.

This should fix it (untested):

```diff
diff --git a/nvim-client-0.0.1-13.rockspec b/nvim-client-0.0.1-13.rockspec
index 7ff8041..c841a82 100644
--- a/nvim-client-0.0.1-13.rockspec
+++ b/nvim-client-0.0.1-13.rockspec
@@ -19,6 +19,17 @@ external_dependencies = {
   }
 }

+local modules = {
+  ['nvim.msgpack_stream'] = 'nvim/msgpack_stream.lua',
+  ['nvim.async_session'] = 'nvim/async_session.lua',
+  ['nvim.session'] = 'nvim/session.lua',
+  ['nvim.loop'] = {
+    sources = {'nvim/loop.c'},
+    incdirs = {"$(LIBUV_INCDIR)"},
+    libdirs = {"$(LIBUV_LIBDIR)"}
+  }
+}
+
 -- based on:
 -- https://github.com/diegonehab/luasocket/blob/master/luasocket-scm-0.rockspec
 local function make_plat(plat)
@@ -33,21 +44,17 @@ local function make_plat(plat)
     libs[#libs + 1] = 'dl'
   end

-  local modules = {
-    ['nvim.msgpack_stream'] = 'nvim/msgpack_stream.lua',
-    ['nvim.async_session'] = 'nvim/async_session.lua',
-    ['nvim.session'] = 'nvim/session.lua',
-    ['nvim.loop'] = {
-      sources = {'nvim/loop.c'},
-      libraries = libs,
-      incdirs = {"$(LIBUV_INCDIR)"},
-      libdirs = {"$(LIBUV_LIBDIR)"}
-    }
-  }
+  modules.libraries = libs

   return {modules = modules}
 end

 build = {
   type = 'builtin',
+  modules = modules,
+  -- per-platform overrides
+  platforms = {
+    linux = make_plat('linux'),
+    freebsd = make_plat('freebsd'),
+  }
 }

```

**Comment by justinmk** [comment]
Updated the patch.

**Comment by justinmk** [comment]
Fixing this now.

**Comment by justinmk** [comment]
Not sure what to make of the logs now.  I cleared cache and re-ran this build:

```
os.execute: 	cd '/tmp/luarocks_luarocks-rock-lua_cliargs-2.5-1-587' && 'curl' -k -f -L --user-agent 'LuaRocks/scm linux-x86_64 via curl' --connect-timeout 30 'https://luarocks.org/lua_cliargs-2.5-1.src.rock' 2> /dev/null 1> '/tmp/luarocks_luarocks-rock-lua_cliargs-2.5-1-587/lua_cliargs-2.5-1.src.rock'
Results: 1
  1 (number): 0

os.execute: 	cd '/' && rm '-rf' '/tmp/luarocks_luarocks-rock-lua-messagepack-0.3.3-1-7247'
Results: 1
  1 (number): 0

Error: /home/travis/nvim-deps/usr/lib/luarocks/rocks/manifest.tmp: No such file or directory
make[2]: *** [usr/lib/luarocks/rocks/lua-messagepack] Error 1
make[1]: *** [CMakeFiles/lua-messagepack.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Results: 1
  1 (number): 0

os.execute: 	cd '/home/travis/nvim-deps' && mkdir -p '/tmp/luarocks_lua_cliargs-2.5-1-6480'
Results: 1
  1 (number): 0
```

**Comment by justinmk** [comment]
Ok trying again.

**Comment by justinmk** [comment]
Ok, seems to be fixed now, if you rebase.

**Comment by bfredl** [comment]
Thanks! rebased.

File: test/functional/api/vim_spec.lua [hunk 1]
```diff
@@ -177,6 +178,62 @@ describe('vim_* functions', function()
...
+      screen:attach()
+      screen:set_default_attr_ids({
+        [1] = {foreground = Screen.colors.White, background = Screen.colors.Red},
+        [2] = {bold = true, foreground = Screen.colors.SeaGreen}
+      })
+      screen:set_default_attr_ignore( {{bold=true, foreground=Screen.colors.Blue}} )
+    end)
+
+    it('can show one line', function()
+      nvim_async('err_write', 'has bork\n')
```
Comment (justinmk) [inline test/functional/api/vim_spec.lua]: @bfredl  What if `nvim_async('err_write, ...)` is called multiple times? Do we need a test for that? E.g.:

```
nvim_async('err_write', 'has bork\n')
nvim_async('err_write', 'has bork\n')
nvim_async('err_write', 'has bork\n')
```

What will the result be?

Comment (bfredl) [inline test/functional/api/vim_spec.lua]: It would show up to `&cmdheight` lines, i.e two, then showing more will be blocked on pressing RETURN. Given the async nature, the behaviour could very well be different when nvim happens to be in some "global" processing mode, so that all are shown at once, but certainly a test could be added for the simple case (nvim is idle).
