### PR TITLE
fix: inccommand segfault with `:filter`

### LINKED ISSUE #19057: inccommand: segfault when typing `:filter s`
### Neovim version (nvim -v)

v0.8.0-dev+467-g1b75094e3

### Vim (not Nvim) behaves the same?

No, 8.2.5046

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Run `nvim --clean`
2. Type `:filter s`

### Expected behavior

No segfault

### Actual behavior

Segfault

ASAN log:
```
=================================================================
==108999==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7fff28b01490 sp 0x7fff28b00b18 T0)
==108999==Hint: pc points to the zero page.
==108999==The signal is caused by a READ memory access.
==108999==Hint: address points to the zero page.
    #0 0x0  (<unknown module>)
    #1 0x555f3b810f56 in cmdpreview_show **/src/nvim/ex_getln.c:2456:25
    #2 0x555f3b7fc64d in command_line_changed **/src/nvim/ex_getln.c:2568:5
    #3 0x555f3b80ec9e in command_line_handle_key **/src/nvim/ex_getln.c:2244:10
    #4 0x555f3b7f7614 in command_line_execute **/src/nvim/ex_getln.c:1539:10
    #5 0x555f3c3c1c7e in state_enter **/src/nvim/state.c:88:26
    #6 0x555f3b7ba044 in command_line_enter **/src/nvim/ex_getln.c:891:3
    #7 0x555f3b7b59dc in getcmdline **/src/nvim/ex_getln.c:2626:10
    #8 0x555f3b7bc928 in getexline **/src/nvim/ex_getln.c:2812:18
    #9 0x555f3b6e806f in do_cmdline **/src/nvim/ex_docmd.c:516:30
    #10 0x555f3bd3b0bb in nv_colon **/src/nvim/normal.c:3955:20
    #11 0x555f3bd267f7 in normal_execute **/src/nvim/normal.c:1157:3
    #12 0x555f3c3c1c7e in state_enter **/src/nvim/state.c:88:26
    #13 0x555f3bcfb790 in normal_enter **/src/nvim/normal.c:450:3
    #14 0x555f3ba8271f in main **/src/nvim/main.c:571:3
    #15 0x7f763c42928f  (/usr/lib/libc.so.6+0x2928f)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>) 
==108999==ABORTING
```

### PR DESCRIPTION
**Pull request by famiu**
Closes #19057 

~This is the best fix I found, any other fix will interfere with legacy Vim tests.~

### CODE REVIEW

File: src/nvim/ex_getln.c [hunk 1]
```diff
@@ -2398,6 +2398,13 @@ static void cmdpreview_show(CommandLineState *s)
     emsg_off--;
     goto end;
   }
+
+  // Command is invalid, return.
+  // This check can be removed if there's ever a preview function added for :filter.
```
Comment (kylo252) [inline src/nvim/ex_getln.c:2403]: Just a small advice, I'd try to create a test that includes the repro from https://github.com/neovim/neovim/issues/19057 and validates whatever behavior you decided is the valid outcome, in case someone else (or even future you) misses this comment (which may get outdated) for one reason or another.

File: src/nvim/ex_getln.c [hunk 2]
```diff
@@ -2398,6 +2398,13 @@ static void cmdpreview_show(CommandLineState *s)
...
+  if (ea.cmdidx == CMD_filter) {
+    return;
```
Comment (zeertzjq) [inline src/nvim/ex_getln.c:2405]:
```suggestion
    goto end;
```

File: src/nvim/ex_getln.c [hunk 3]
```diff
@@ -2564,7 +2569,6 @@ static int command_line_changed(CommandLineState *s)
       && *p_icm != NUL       // 'inccommand' is set
       && curbuf->b_p_ma      // buffer is modifiable
       && cmdline_star == 0   // not typing a password
-      && cmd_can_preview((char *)ccline.cmdbuff)
       && !vpeekc_any()) {
     cmdpreview_show(s);
```
Comment (zeertzjq) [inline src/nvim/ex_getln.c:2573]: `cmdpreview_may_show` may be a more appropriate name

File: test/functional/ui/inccommand_spec.lua [hunk 4]
```diff
@@ -3008,3 +3008,10 @@ it('long :%s/ with inccommand does not collapse cmdline', function()
     AAAAAAA^     |
   ]])
 end)
+
+it(":filter with a previewable command doesn't segfault", function()
```
Comment (zeertzjq) [inline test/functional/ui/inccommand_spec.lua:3012]:
```suggestion
it(":filter with a previewable command doesn't segfault #19057", function()
```

File: src/nvim/ex_getln.c [hunk 5]
```diff
@@ -2385,12 +2385,15 @@ static void cmdpreview_close_win(void)
 ///    5. If the return value of the preview callback is not 0, update the screen while the effects
 ///       of the preview are still in place.
 ///    6. Revert all changes made by the preview callback.
-static void cmdpreview_show(CommandLineState *s)
+///
+/// @return whether preview or shown or not.
```
Comment (zeertzjq) [inline src/nvim/ex_getln.c:2389]:
```suggestion
/// @return whether preview is shown or not.
```

**Review by justinmk — APPROVED** [review]
Much nicer!!

**Comment by zeertzjq** [comment]
Oh I just found a bug in `nvim_parse_cmd`
