### PR TITLE
[WIP] Correctly splice extmarks on tab with `noexpandtab`

### LINKED ISSUE #14111: Treesitter/extmarks: highlighting breaks with `noexpandtab` and `softtabstop/shiftwidth` set
### Steps to reproduce using `nvim -u NORC`

Edit a file with the following contents:

```
asdf
```

Then, run the following commands:

```
set noet
set softtabstop=2
lua vim.api.nvim_buf_set_extmark(0, vim.api.nvim_create_namespace("tmp"), 0, 0, {end_col=4, hl_group="search"})
```

Then go to the start of the line and press TAB once.

### Actual behaviour

The highlighting disappears.

### Expected behaviour

Highlighting doesn't disappear.

As far as I can tell, this issue is due to the implementation of `ins_tab()`, which works by first inserting spaces and then replacing them by tab characters (if shiftwidth/softtabstop is set). The buffer updates seem to track the insertion of spaces but not the replace operations - this seems to happen because `ins_tab()` directly modifies the buffer line rather than calling `ins_bytes` or something.

I think I can probably make a PR to fix this, but if anyone else wants to beat me to it they're welcome to :)

### PR DESCRIPTION
**Pull request by chentoast**
Fixes #14111 .

This now adds an `extmark_splice` call to `ins_tab`, so that buffer updates are correctly sent. Previously, neovim would send buffer updates for the insertion of spaces, but not the updates for the replacing of spaces with tab characters.

### CODE REVIEW

File: test/functional/lua/buffer_updates_spec.lua [hunk 1]
```diff
@@ -666,6 +666,36 @@ describe('lua: nvim_buf_attach on_bytes', function()
...
+
+      local ns = helpers.request('nvim_create_namespace', "ns1")
+      meths.buf_set_extmark(0, ns, 0, 0, {})
+
+      command("set noet")
+      command("set ts=4")
+      command("set sw=4")
+      command("set sts=2")
+
+      local check_events = setup_eventcheck(verify, nil)
```
Comment (bfredl) [inline test/functional/lua/buffer_updates_spec.lua:682]: pass the `[[asdfasdf]]` string here.

File: test/functional/lua/buffer_updates_spec.lua [hunk 2]
```diff
@@ -666,6 +666,36 @@ describe('lua: nvim_buf_attach on_bytes', function()
       }
     end)
 
+    it("tab with noexpandtab and softtabstop", function()
+      helpers.insert(dedent([[
+      asdfasdf
+      ]]))
+
+      local ns = helpers.request('nvim_create_namespace', "ns1")
```
Comment (bfredl) [inline test/functional/lua/buffer_updates_spec.lua:674]: no need to create an extmark in buffer_updates test.

**Comment by chentau** [comment]
@bfredl this pr should be ready for review :)

File: test/functional/lua/buffer_updates_spec.lua [hunk 3]
```diff
@@ -666,6 +666,74 @@ describe('lua: nvim_buf_attach on_bytes', function()
       }
     end)
 
+    it("tab with noexpandtab and softtabstop", function()
+      helpers.insert(dedent([[
```
Comment (bfredl) [inline test/functional/lua/buffer_updates_spec.lua:670]: you can delete this, `setup_eventcheck` will already set it.

**Comment by bfredl** [comment]
Thanks, merged :)
