### PR TITLE
vim-patch:9.0.1578: SpellCap highlight not always updated when needed

### LINKED ISSUE #12420: SpellCap highlight not shown if blank line above is folded
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
call setline(1, ['hello', 'world', '', 'hello', 'world'])
set spell
```
3. The `hello` on lines 1 and 4 are highlighted
4. Run `1,3fold`
5. The `hello` on line 4 is no longer highlighted

### Expected behaviour

The `hello` on line 4 is still highlighted

### Version of Vim

9.0.1506

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:    SpellCap highlight not always updated when needed.
Solution:   Handle updating line below closed fold and other situations where
            only part of the window is redrawn. (Luuk van Baal, closes vim/vim#12428,
            closes vim/vim#12420)

https://github.com/vim/vim/commit/2ac6497f0ef186f0e3ba67d7f0a485bfb612bb08

### CODE REVIEW

File: src/nvim/spell.c [hunk 1]
```diff
@@ -2536,30 +2536,32 @@ int spell_casefold(const win_T *wp, char *str, int len, char *buf, int buflen)
...
-      line = ml_get(lnum - 1);
+      line = ml_get_buf(wp->w_buffer, lnum - 1, false);
       if (*skipwhite(line) == NUL) {
         need_cap = true;
       } else {
         // Append a space in place of the line break.
         line_copy = concat_str(line, " ");
+        if (line_copy == NULL) {
+          return false;
+        }
```
Comment (zeertzjq) [inline src/nvim/spell.c:2564]: `concat_str()` has `FUNC_ATTR_NONNULL_RET`
```suggestion
```

File: test/functional/ui/spell_spec.lua [hunk 2]
```diff
@@ -140,6 +141,43 @@ describe("'spell'", function()
       {0:~                                                                               }|
                                                                                       |
     ]])
+    -- Folding an empty line does not remove Cap in next line
```
Comment (zeertzjq) [inline test/functional/ui/spell_spec.lua:144]: The description of this test need to be changed. I think just `SpellCap highlight` is a better name.

**Review by zeertzjq — APPROVED** [review]
