### PR TITLE
terminal: do not call redraw_buf_later()

### LINKED ISSUE #8290: terminal updates clear 'hlsearch'
- `nvim --version`:
```
NVIM v0.2.3-874-g739fb93a9
Build type: Debug
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/barries/neovim/neovim/build/config -I/home/barries/neovim/neovim/src -I/home/barries/neovim/neovim/.deps/usr/include -I/usr/include -I/home/barries/neovim/neovim/build/src/nvim/auto -I/home/barries/neovim/neovim/build/include
Compiled by barries@IV3-Station1

Features: +acl +iconv +jemalloc +tui
```
- Vim (version: ) behaves differently? `N/A`
- Operating system/version:  `Linux IV3-Station1 4.9.0-1-amd64 #1 SMP Debian 4.9.2-2 (2017-01-12) x86_64 GNU/Linux`
- Terminal name/version: `Putty 0.69`
- `$TERM`: `screen-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:split<CR>
:term<CR>
a<CR>
top<CR>
s 0.1<CR>
<c-\><c-n>
<c-W>b
:e <a file><CR>
/...
```

### Actual behaviour

When typing the `...`, the incremental search highlight flickers on, then back off.

I have also noticed that, occasionally, `nvim` with a running terminal seems to lose its settings for `expandtab`, `autoindent`, `smartindent`, etc., but I can't reproduce that reliably so I'm not 100% sure except I don't recall noticing it happen when not running a terminal. This may or not be related.

### Expected behaviour

The highlight is stable.

### Postscript

We don't really run `top` at that rate, but it helps to demonstrate the issue.  I checked the FAQ and tried searching open & closed issues, but I'm surprised I didn't find it because it seems rather likely.

### PR DESCRIPTION
**Pull request by justinmk**
fixes #8290

### CODE REVIEW

File: src/nvim/terminal.c [hunk 1]
```diff
@@ -1097,7 +1097,6 @@ static void refresh_terminal(Terminal *term)
     refresh_size(term, buf);
     refresh_scrollback(term, buf);
     refresh_screen(term, buf);
-    redraw_buf_later(buf, NOT_VALID);
```
Comment (justinmk) [inline src/nvim/terminal.c]: I don't know why it was needed (it's been there since `:terminal` was first implemented).
