### PR TITLE
fix(shada): update marks when using delmarks!

### LINKED ISSUE #24963: shada: "delmarks!" is not persisted in shada
### Problem

PR #24936 recently updated the code so that using `:delmarks <MARKS>` is persisted in the shada file.

This led to closing #4295.

This PR is for a similar issue, here for `:delmarks!` as opposed to `:delmarks <MARKS>`.

`:delmarks!` deletes all marks for the current buffer (but not A-Z or 0-9). When using `:delmarks!`, the outcome is not persisted across Neovim sessions.

### Steps to reproduce

```sh
nvim -u NONE tmp.txt
```
```vim
" insert  20 lines
20o<esc>
" Add a mark
mm
" Save and exit
ZZ
```
```sh
nvim -u NONE tmp.txt
```
```vim
" delete all marks
:delmarks!
" Save and exit
ZZ
```
```sh
nvim -u NONE tmp.txt
```
```vim
" goto mark
`m
```

### Expected behavior

I expected that using `delmarks!` would be persisted and `` `m `` would not work, resulting in `E20: Mark not set`.

### Actual behavior

`:delmarks!` was not persisted and using `` `m `` worked as it would have had `:delmarks!` not been used.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1009+ga1bec02c1

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Kubuntu 23.04

### Terminal name/version

Konsole 22.12.3

### $TERM environment variable

xterm-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #24963

### CODE REVIEW

File: test/functional/shada/marks_spec.lua [hunk 1]
```diff
@@ -269,4 +269,19 @@ describe('ShaDa support code', function()
...
+    feed('ggifoobar<esc>')
+    nvim_command('wshada')
+    nvim_command('normal! `a`.')
+    nvim_command('delmarks!')
+    nvim_command('wshada')
+
+    reset()
+    eq('Vim(normal):E20: Mark not set', exc_exec('normal! `a'))
+    eq('Vim(normal):E20: Mark not set', exc_exec('normal! `.'))
+  end)
```
Comment (zeertzjq) [inline test/functional/shada/marks_spec.lua:286]: This test always succeeds because it doesn't edit the file after `reset()`.

If it edits the file, however, then it fails, so somehow it still isn't working.
```diff
diff --git a/test/functional/shada/marks_spec.lua b/test/functional/shada/marks_spec.lua
index 47750e52c..fa6133b98 100644
--- a/test/functional/shada/marks_spec.lua
+++ b/test/functional/shada/marks_spec.lua
@@ -281,6 +281,7 @@ describe('ShaDa support code', function()
     nvim_command('wshada')
 
     reset()
+    nvim_command('edit ' .. testfilename)
     eq('Vim(normal):E20: Mark not set', exc_exec('normal! `a'))
     eq('Vim(normal):E20: Mark not set', exc_exec('normal! `.'))
   end)
```

Comment (MariaSolOs) [reply test/functional/shada/marks_spec.lua:286]: I wrote this test by following the one [for `delmarks`](https://github.com/MariaSolOs/neovim/blob/3c78d17f7636dd57f5702f05d0492535c1a459b5/test/functional/shada/marks_spec.lua#L273). Does this mean that the other test has the same issue?

Comment (MariaSolOs) [reply test/functional/shada/marks_spec.lua:286]: Oh wait you just actually modified the test in `master`.

File: src/nvim/mark.c [hunk 2]
```diff
@@ -922,17 +922,33 @@ void ex_delmarks(exarg_T *eap)
   int lower;
   int digit;
   int n;
+  const Timestamp timestamp = os_time();
```
Comment (zeertzjq) [inline src/nvim/mark.c:925]: I think `os_time()` should be called in the two branches where it is used separately. It doesn't need to be called when there is an error.

File: src/nvim/mark.c [hunk 3]
```diff
@@ -925,7 +925,24 @@ void ex_delmarks(exarg_T *eap)
...
+    }
+    curbuf->b_last_cursor.timestamp = timestamp;
+    CLEAR_FMARK(&curbuf->b_last_cursor);
+    curbuf->b_last_cursor.mark.lnum = 1;
+    curbuf->b_last_insert.timestamp = timestamp;
+    CLEAR_FMARK(&curbuf->b_last_insert);
+    curbuf->b_last_change.timestamp = timestamp;
+    CLEAR_FMARK(&curbuf->b_last_change);
+    curbuf->b_op_start.lnum = 0;  // start/end op mark cleared
+    curbuf->b_op_end.lnum = 0;
```
[the remark this answers is not in the document]
Comment (MariaSolOs) [reply src/nvim/mark.c:941]: @justinmk: @zeertzjq made [a commit](https://github.com/neovim/neovim/commit/f32a69630d0360cd73db6e7507bceb4104ec790d) after this PR went it that cleaned up this code.
