### PR TITLE
[RFC] Fix use-after-free by dictwatcher

### LINKED ISSUE #11494: Memory access after free by dictwatcher
- `nvim --version`: HEAD
- `vim -u DEFAULTS` (version: ) behaves differently? N/A(vim has no dictwatcher)
- Operating system/version: N/A
- Terminal name/version: N/A
- `$TERM`: N/A

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:function W(...) abort
: unlet g:d
:endfunction
:let g:d={}
:call dictwatcheradd(g:d, '*', function('W'))
:let g:d.foo=123
```

### Actual behaviour

Access to freed memory occurs in `tv_dict_watcher_notify`.

[valgrind log](https://gist.github.com/erw7/13e427b7004dc1a7dc0151770b718aeb)

### Expected behaviour

Access to memory after free should not occur.

### PR DESCRIPTION
**Pull request by erw7**
fixes #11494.

### CODE REVIEW

File: src/nvim/eval/typval.c [hunk 1]
```diff
@@ -1205,9 +1205,11 @@ void tv_dict_watcher_notify(dict_T *const dict, const char *const key,
     DictWatcher *watcher = tv_dict_watcher_node_data(w);
     if (!watcher->busy && tv_dict_watcher_matches(watcher, key)) {
       rettv = TV_INITIAL_VALUE;
+      dict->dv_refcount++;
       watcher->busy = true;
       callback_call(&watcher->callback, 3, argv, &rettv);
       watcher->busy = false;
+      dict->dv_refcount--;
```
Comment (blueyed) [inline src/nvim/eval/typval.c]: Should maybe use `tv_dict_unref`?  https://github.com/neovim/neovim/blob/1a6efa4719c906fe67f2c21ec1a2b33ae92ca17b/src/nvim/eval/typval.c#L1419-L1424

File: test/functional/ex_cmds/dict_notifications_spec.lua [hunk 2]
```diff
@@ -357,4 +357,18 @@ describe('VimL dictionary notifications', function()
     eq(2, eval('1+1')) -- Still alive?
   end)
 
+  it('does not case use-after-free when unletting from callback', function()
```
Comment (justinmk) [inline test/functional/ex_cmds/dict_notifications_spec.lua]:
```suggestion
  it('does not cause use-after-free when unletting from callback', function()
```

**Review by justinmk — APPROVED** [review]

**Review by blueyed — APPROVED** [review]
