### PR TITLE
fix(file_search): path with spaces in finddir() and findfile()

### LINKED ISSUE #25324: `finddir` and `findfile` returning empty strings for paths with whitespace (on Windows)
### Problem

Screencast demonstrating the problem:
https://youtu.be/oG8lgCJjDn0

Sometime between stable 0.9.2 and the current nightly release (c88bb65) the plugin [git-messenger.vim](https://github.com/rhysd/git-messenger.vim) stopped working for me in certain directories.
After looking into it I found the offending lines to be these:
https://github.com/rhysd/git-messenger.vim/blob/8a61bdfa351d4df9a9118ee1d3f45edbed617072/autoload/gitmessenger/git.vim#L4-L5
Containing calls to `finddir` and `findfile` which return an empty string in nightly, but return a valid path in stable.
Investigating this further, I noticed that these functions return valid path strings on nightly if the working directory does not contain whitespace.

As an aside, I know this worked in a former nightly build, but I did not keep track of which commit that was, and since the CI deletes these I can't do a bisection of the binaries to find out which it was.  Sorry (；´∀｀)

### Steps to reproduce

On Windows, call `findedir` or `findfile` on a path containing whitespace. The return value should be an empty string no matter what.

### Expected behavior

A file path is returned from `finddir` and `findfile` when the argument contains the query.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-c88bb65

### Vim (not Nvim) behaves the same?

Did not check

### Operating system/version

Windows 11 25951.1000

### Terminal name/version

Microsoft Terminal (86ad3c8)

### $TERM environment variable

Not set

### Installation

GitHub release (using custom installer)

### PR DESCRIPTION
**Pull request by lsvmello**
# Problem

LibUV doesn't find files and directories when calling `uv_fs_stat` with escaped spaces (`'\ '`).

# Solution

Unescape the file name and path before calling `uv_fs_stat`. 

Fixes #25324.

I have confirmed that the new tests failed before the changes.

### CODE REVIEW

File: src/nvim/file_search.c [hunk 1]
```diff
@@ -1372,6 +1372,11 @@ char *find_file_in_path_option(char *ptr, size_t len, int options, int first, ch
           memmove(ptr, ptr + 1, strlen(ptr));
         }
       }
+      for (ptr = path_option; *ptr != NUL; ptr++) {
+        if (ptr[0] == '\\' && ptr[1] == ' ') {
+          memmove(ptr, ptr + 1, strlen(ptr));
+        }
+      }
```
Comment (zeertzjq) [inline src/nvim/file_search.c:1379]: This is changing the value of the option itself. At least it should make a copy first.

Comment (lsvmello) [reply src/nvim/file_search.c]: My bad, I'm not a C developer. Didn't thought about the consequences of changing an in parameter.

**Comment by justinmk** [comment]
asan ci is failing.

```
[OLDTEST] Running test_gf
Failed: test_gf :: Nvim exited with non-zero code

=================================================================
==34128==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 28 byte(s) in 7 object(s) allocated from:
    #0 0x55c420f48dbe in __interceptor_malloc (/home/runner/work/neovim/neovim/build/bin/nvim+0xce8dbe) (BuildId: 22f06af9b4131d58f39963471aa56766964bd5c2)
    #1 0x55c421d82196 in try_malloc /home/runner/work/neovim/neovim/src/nvim/memory.c:89:15
    #2 0x55c421d8237c in xmalloc /home/runner/work/neovim/neovim/src/nvim/memory.c:123:15
    #3 0x55c421d826fa in xmallocz /home/runner/work/neovim/neovim/src/nvim/memory.c:195:15
    #4 0x55c421d8284b in xmemdupz /home/runner/work/neovim/neovim/src/nvim/memory.c:213:17
    #5 0x55c421d83baf in xstrdup /home/runner/work/neovim/neovim/src/nvim/memory.c:432:10
    #6 0x55c4219954ac in find_file_in_path_option /home/runner/work/neovim/neovim/src/nvim/file_search.c:1376:14
    #7 0x55c421994a0e in find_file_in_path /home/runner/work/neovim/neovim/src/nvim/file_search.c:1291:10
    #8 0x55c4220aaee0 in find_file_name_in_path /home/runner/work/neovim/neovim/src/nvim/path.c:1707:17
    #9 0x55c42291938f in file_name_in_line /home/runner/work/neovim/neovim/src/nvim/window.c:7015:10
    #10 0x55c42291705f in file_name_at_cursor /home/runner/work/neovim/neovim/src/nvim/window.c:6917:10
    #11 0x55c4228a5c3c in grab_file_name /home/runner/work/neovim/neovim/src/nvim/window.c:6901:10
    #12 0x55c421f029a8 in nv_gotofile /home/runner/work/neovim/neovim/src/nvim/normal.c:3912:9
    #13 0x55c421ee48f3 in nv_g_cmd /home/runner/work/neovim/neovim/src/nvim/normal.c:5559:5
    #14 0x55c421ebab69 in normal_execute /home/runner/work/neovim/neovim/src/nvim/normal.c:1227:3
    #15 0x55c421eb2ff2 in normal_cmd /home/runner/work/neovim/neovim/src/nvim/normal.c:6639:9
    #16 0x55c4218b5bdf in exec_normal /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:6541:5
    #17 0x55c4218b58eb in exec_normal_cmd /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:6524:3
    #18 0x55c4218c728e in ex_normal /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:6456:7
    #19 0x55c421892f19 in execute_cmd0 /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:1636:7
    #20 0x55c42186f518 in do_one_cmd /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:2295:7
    #21 0x55c42185f79f in do_cmdline /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:594:20
    #22 0x55c421864b20 in do_cmdline_cmd /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:293:10
    #23 0x55c4226182e7 in f_assert_fails /home/runner/work/neovim/neovim/src/nvim/testing.c:542:3
    #24 0x55c42165c4f9 in call_internal_func /home/runner/work/neovim/neovim/src/nvim/eval/funcs.c:273:3
    #25 0x55c42176a3be in call_func /home/runner/work/neovim/neovim/src/nvim/eval/userfunc.c:1719:15
    #26 0x55c4217667c6 in get_func_tv /home/runner/work/neovim/neovim/src/nvim/eval/userfunc.c:557:11
    #27 0x55c4217a13b2 in ex_call_inner /home/runner/work/neovim/neovim/src/nvim/eval/userfunc.c:3160:9
    #28 0x55c42179f43e in ex_call /home/runner/work/neovim/neovim/src/nvim/eval/userfunc.c:3396:14
    #29 0x55c421892f19 in execute_cmd0 /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:1636:7
```

File: src/nvim/file_search.c [hunk 2]
```diff
@@ -1372,6 +1373,12 @@ char *find_file_in_path_option(char *ptr, size_t len, int options, int first, ch
           memmove(ptr, ptr + 1, strlen(ptr));
         }
       }
+      path = xstrdup(path_option);
+      for (ptr = path; *ptr != NUL; ptr++) {
```
Comment (justinmk) [inline src/nvim/file_search.c:1377]: `path` is never freed (that's why asan ci is failing).

File: test/functional/core/path_spec.lua [hunk 3]
```diff
@@ -129,4 +129,48 @@ describe('file search (gf, <cfile>)', function()
     test_cfile([[\\.\UNC\LOCALHOST\c$\temp\test-file.txt]], [[.]], [[\\.\UNC\LOCALHOST\c$\temp\test-file.txt]])
     test_cfile([[\\127.0.0.1\c$\temp\test-file.txt]], [[127.0.0.1]], [[\\127.0.0.1\c$\temp\test-file.txt]])
   end)
+
+  describe('using `finddir`', function()
```
Comment (justinmk) [inline test/functional/core/path_spec.lua:133]: backticks are not useful in a test name, it's more visually useful to use parens to indicate a function
```suggestion
  describe('using finddir()', function()
```

File: test/functional/core/path_spec.lua [hunk 4]
```diff
@@ -129,4 +129,48 @@ describe('file search (gf, <cfile>)', function()
...
+    end)
+
+    it('with "\\ " on name', function()
+      local folder1 = 'dir'
+      mkdir(folder1)
+      local folder2 = 'folder name'
+      local expected_path = join_path(folder1, folder2)
+      mkdir(expected_path)
+      eq(expected_path, eval('finddir(fnameescape("'..folder2..'"),"'..folder1..'")'))
+      rmdir(folder1)
```
Comment (justinmk) [inline test/functional/core/path_spec.lua:151]: all of these tests look pretty similar, is there a way to de-dupe the code?

it also can be noisy to have many separate it() tests for each variation of an input. when testing many inputs, all the variations can live in one test (see `test_cfile` cases above).

File: src/nvim/file_search.c (hunk 2 above)
Comment (lsvmello) [reply src/nvim/file_search.c:1377]: Thanks!

I'm setting up ASAN locally to try the fix, just using `xfree` raised another error. Probably because I we reference that value on a static pointer (a wild guess from a non-C developer).

File: test/functional/core/path_spec.lua [hunk 5]
```diff
@@ -130,3 +130,40 @@ describe('file search (gf, <cfile>)', function()
...
+    test_find_func('dir', 'folder name', 'directory')
+    test_find_func('dir', 'directory', 'folder name')
+  end)
+
+  it('findfile()', function()
+    test_find_func('file', 'directory', 'file.txt')
+    test_find_func('file', 'folder name', 'file.txt')
+    test_find_func('file', 'directory', 'file name.txt')
+  end)
+end)
```
Comment (lsvmello) [inline test/functional/core/path_spec.lua:169]: @justinmk what about this approach?

I moved out the `describe('file search (gf, <cfile>)', ...` to not turn that into a `describe('file search (gf, <cfile>, finddir(), findfile())', ...`.

And used the `setup` and `teardown` to avoid multiple `rmdir` calls, but that might had a problem with Windows, I'll look into that later.

**Comment by justinmk** [comment]
Is this change still needed if https://github.com/neovim/neovim/issues/25324#issuecomment-1751730550 is applied? 

The tests added here may still be worth adding in any case.

**Comment by lsvmello** [comment]
> Is this change still needed if [#25324 (comment)](https://github.com/neovim/neovim/issues/25324#issuecomment-1751730550) is applied?

Reverting that line fixed the case where there are spaces on the **path** (second parameter of `finddir` and `findfile`), adding the `FNAME_UNESC` flag allows the user to pass escaped spaces on the **name** (first parameter of the functions). This was not reported as a problem, should we keep this change?

**Comment by justinmk** [comment]
> This was not reported as a problem, should we keep this change?

Does a test fail without that change? Could be a followup PR.

**Comment by lsvmello** [comment]
> Does a test fail without that change? Could be a followup PR.

Yes, because I created tests for this scenario, I'll leave those commented out to uncomment on the followup PR.

File: test/functional/core/path_spec.lua [hunk 6]
```diff
@@ -130,3 +130,40 @@ describe('file search (gf, <cfile>)', function()
...
+  local function test_find_func(option, folder, item)
+    local folder_path = join_path(test_folder, folder)
+    mkdir(folder_path)
+    local expected = join_path(folder_path, item)
+    if option == "dir" then
+      mkdir(expected)
+    else
+      write_file(expected, '')
+    end
+    eq(expected, eval('find'..option..'(fnameescape(\''..item..'\'),fnameescape(\''..folder_path..'\'))'))
```
Comment (justinmk) [inline test/functional/core/path_spec.lua:155]: Nit: this is unnecessarily abstracted/indirect. The caller can just pass "finddir" or "findfile".
