### PR TITLE
fix: invoke changed_bytes when rewriting tabs

### LINKED ISSUE #25092: LSP: incremental sync breaks when softtabstop < 0
### Problem

The lsp client doesn't send `<TAB>` character correctly in the `textDocument/didChange` event when using `softtabstop = -1`. I ran into this because [vim-sleuth](https://github.com/tpope/vim-sleuth) sets `softtabstop` to `-1` by default.

**edit:** This also happens if you set `tabstop` and `shiftwidth` to different values.

### Steps to reproduce using "nvim -u minimal_init.lua"

``` lua
vim.o.shiftwidth = 0
vim.o.softtabstop = -1

vim.cmd.packadd("nvim-lspconfig")

vim.lsp.set_log_level("debug")

require('lspconfig').gopls.setup({})
```

I've created a repo with a minimal `init.lua` and steps to reproduce. https://github.com/icholy/nvim-lsp-bug

tty

**Note**: I've been able to reproduce this with several lsp servers.

### Expected behavior

Send a single tab character in `textDocument/didChange`

``` lua
{
    jsonrpc = "2.0",
    method = "textDocument/didChange",
    params = {
        contentChanges = {
            {
                range = {["end"] = {character = 0, line = 0}, start = {character = 0, line = 0}},
                rangeLength = 0,
                text = "\t"
            }
        },
        textDocument = {uri = "file:///home/icholy/src/github.com/icholy/nvim-lsp-bug/main.go", version = 4}
    }
}
```

### Neovim version (nvim -v)

v0.10.0-dev

### Language server name/version

gopls v0.13.2

### Operating system/version

Ubuntu 22.04

### Log file

https://gist.github.com/icholy/b3216e005787bf39c250ada7a2b6a88a

Relevant section:
```
{
    jsonrpc = "2.0",
    method = "textDocument/didChange",
    params = {
        contentChanges = {
            {
                range = {["end"] = {character = 0, line = 0}, start = {character = 0, line = 0}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 1, line = 0}, start = {character = 1, line = 0}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 2, line = 0}, start = {character = 2, line = 0}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 3, line = 0}, start = {character = 3, line = 0}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 4, line = 0}, start = {character = 4, line = 0}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 5, line = 0}, start = {character = 5, line = 0}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 6, line = 0}, start = {character = 6, line = 0}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 7, line = 0}, start = {character = 7, line = 0}},
                rangeLength = 0,
                text = " "
            }
        },
        textDocument = {uri = "file:///home/icholy/src/github.com/icholy/nvim-lsp-bug/main.go", version = 11}
    }
}
```

### PR DESCRIPTION
**Pull request by icholy**
Fixes https://github.com/neovim/neovim/issues/25092

### CODE REVIEW

File: src/nvim/edit.c [hunk 1]
```diff
@@ -4429,6 +4429,7 @@ static bool ins_tab(void)
           }
         }
         if (!(State & VREPLACE_FLAG)) {
+          changed_bytes(fpos.lnum, change_col);
           extmark_splice_cols(curbuf, (int)fpos.lnum - 1, change_col,
                               cursor->col - change_col, fpos.col - change_col,
                               kExtmarkUndo);
```
Comment (bfredl) [inline src/nvim/edit.c:4435]: you could use `inserted_bytes()` wrapper for this pattern

**Comment by justinmk** [comment]
your [explanation](https://github.com/neovim/neovim/issues/25092#issuecomment-1716378192) would be great to have in the commit message.

File: test/functional/lua/buffer_updates_spec.lua [hunk 2]
```diff
@@ -826,53 +826,53 @@ describe('lua: nvim_buf_attach on_bytes', function()
 
       feed("<esc>u")
       check_events {
-        { "test1", "bytes", 1, 8, 0, 0, 0, 0, 1, 1, 0, 4, 4 },
-        { "test1", "bytes", 1, 8, 0, 0, 0, 0, 4, 4, 0, 0, 0 }
+        { "test1", "bytes", 1, 9, 0, 0, 0, 0, 1, 1, 0, 4, 4 },
+        { "test1", "bytes", 1, 9, 0, 0, 0, 0, 4, 4, 0, 0, 0 }
```
Comment (icholy) [inline test/functional/lua/buffer_updates_spec.lua:830]: I just blindly changed these so that the tests pass, but I'll need some more time to prove to myself that these new values make sense.

**Comment by icholy** [comment]
@justinmk @bfredl is that failing test a flake or do I need to investigate?

**Comment by icholy** [comment]
I've squashed the commits & updated the commit message.

**Review by justinmk — APPROVED** [review]
