### PR TITLE
fix(lua): make `vim.wait()` handle `math.huge` timeout

### LINKED ISSUE #36854: `vim.wait(math.huge)` fails on some systems
### Problem

when write a `nvim -l` scripts, to wait for all events I use `vim.wait()` in a loop.
but `vim.wait(0)` will use 100% of a cpu core. Can we remove this condition to make `vim.wait(-1)` wait forever?

https://github.com/neovim/neovim/blob/e42050f4aed5ee332cc95bacd622bfbc9a31dbe0/src/nvim/lua/executor.c#L455-L457

https://github.com/neovim/neovim/blob/442f297c633375074a88133a9b3d8c08cad58dd0/src/nvim/event/loop.c#L76

so `while true do vim.wait(0) end` can be used as -> `vim.wait(-1)`.

### Expected behavior

`vim.wait(-1)` wait forever.

### PR DESCRIPTION
**Pull request by arkriny**
Problem:
`nlua_wait()` uses `luaL_checkinteger()` which doesn't support `math.huge` since it's double type. On PUC Lua this fails with 'number has no integer representation' error and on LuaJIT this overflows int.

Solution:
Use `luaL_checknumber()` and handle `math.huge`.

Fix #36854

### CODE REVIEW

**Comment by eamonburns** [comment]
I can confirm this fix works for me as well.

File: src/nvim/lua/executor.c [hunk 1]
```diff
@@ -451,10 +452,19 @@ static int nlua_wait(lua_State *lstate)
...
     return luaL_error(lstate, "timeout must be >= 0");
   }
+  int timeout;
+  if (isinf(timeout_number)) {
+    timeout = INT_MAX;
+  } else {
+    if (isnan(timeout_number) || timeout_number != trunc(timeout_number)) {
+      return luaL_error(lstate, "timeout has no integer representation");
+    }
+    timeout = (int)timeout_number;
```
Comment (justinmk) [inline src/nvim/lua/executor.c]: oldtest failure. also not sure that casting a double to an int is always valid?

```
[OLDTEST] Running test_perl
/home/runner/work/neovim/neovim/src/nvim/lua/executor.c:466:15: runtime error: 4.29497e+09 is outside the range of representable values of type 'int'
```

Comment (arkriny) [reply src/nvim/lua/executor.c]: > also not sure that casting a double to an int is always valid?

ah yes, need a check that timeout_number <= INT_MAX. I think it's ok to fallback to INT_MAX in that case instead of error?

File: test/functional/lua/vim_spec.lua [hunk 2]
```diff
@@ -2474,6 +2474,20 @@ stack traceback:
         feed('<C-C>')
         eq({ 'notification', 'wait', { -2 } }, next_msg(500))
       end)
+
+      it('handles math.huge #36854', function()
```
Comment (justinmk) [inline test/functional/lua/vim_spec.lua]: nit: this is in the wrong `describe()` block. oh but you are using `g.channel` , ok.

Comment (justinmk) [reply test/functional/lua/vim_spec.lua]: this is basically the same test so let's just use `math.huge` in the above 2 tests?

Comment (arkriny) [reply test/functional/lua/vim_spec.lua]: > oh but you are using `g.channel` , ok.

Yea since it has to be interrupted to avoid hanging.

> this is basically the same test so let's just use `math.huge` in the above 2 tests?

We've been conservative about adding new tests lately :) But I get it, just thought the clear separation on what’s being tested is in priority. But in this case, these two tests are interdependent anyway.

File: src/nvim/lua/executor.c [hunk 3]
```diff
@@ -451,10 +452,19 @@ static int nlua_wait(lua_State *lstate)
...
 
-  intptr_t timeout = luaL_checkinteger(lstate, 1);
-  if (timeout < 0) {
+  double timeout_number = luaL_checknumber(lstate, 1);
+  if (timeout_number < 0) {
     return luaL_error(lstate, "timeout must be >= 0");
   }
+  int timeout;
+  if (isinf(timeout_number) || timeout_number > INT_MAX) {
+    timeout = INT_MAX;
```
Comment (justinmk) [inline src/nvim/lua/executor.c]: `LOOP_PROCESS_EVENTS_UNTIL` supports `int64_t` , any reason we wouldn't use that here?

Comment (arkriny) [reply src/nvim/lua/executor.c]: I don't see a reason not to. Previously there was a cast to int, which is why I kept it.

**Comment by phanen** [comment]
it don't work with conform.nvim's timeout:
https://github.com/stevearc/conform.nvim/blob/67fc160a07530c8b14dbcd44e01eecb02a69578d/lua/conform/runner.lua#L699

should be fixed there? vim.wait accept integer only, not sure why it work before.

**Comment by justinmk** [comment]
?

**Comment by zeertzjq** [comment]
After this PR `vim.wait(1000.0001)` no longer works.

File: src/nvim/lua/executor.c [hunk 4]
```diff
@@ -451,10 +452,19 @@ static int nlua_wait(lua_State *lstate)
...
-  if (timeout < 0) {
+  double timeout_number = luaL_checknumber(lstate, 1);
+  if (timeout_number < 0) {
     return luaL_error(lstate, "timeout must be >= 0");
   }
+  int64_t timeout;
+  if (isinf(timeout_number) || timeout_number > (double)INT64_MAX) {
+    timeout = INT64_MAX;
+  } else {
+    if (isnan(timeout_number) || timeout_number != trunc(timeout_number)) {
```
Comment (justinmk) [inline src/nvim/lua/executor.c:463]: the `timeout_number != trunc(timeout_number)` condition looks sus

**Comment by arkriny** [comment]
Turns out `luaL_checkinteger()` does not validate overflows in luajit and always casts to int, while PUC lua raises an error in those cases. The reference allows this incompatible behavior tho:

> lua_Integer luaL_checkinteger (lua_State *L, int arg);
> Checks whether the function argument arg is an integer (or can be converted to an integer) and returns this integer cast to a [lua_Integer]

IMO the validation behavior is more useful, since the cast can be done easily in the same line, while validating that a value is an integer introduces much more friction.

Nevertheless, because we already need to use `luaL_checknumber()` here to compare against inf, the solution is to perform the cast ourselves and skip validation of the fractional part (which was not present to begin with).

File: src/nvim/lua/executor.c (hunk 4 above)
Comment (arkriny) [reply src/nvim/lua/executor.c:463]: Opened https://github.com/neovim/neovim/pull/36900
