### PR TITLE
fix(lua): correct line number reporting for options set in coroutines

### LINKED ISSUE #37402: `last_set_linenr` is inaccurate when set option in coroutine
## Steps to reproduce
`nvim --clean -u a.lua`
```lua
vim.o.verbose = 1
coroutine.wrap(function()
	vim.o.busy = 2 print(debug.getinfo(1, "Snl").currentline)
	print(vim.api.nvim_get_option_info2("busy", {}).last_set_linenr)
end)()
```
print `3 5`

## Expected behavior
print `3 3`

## System info

- Nvim version (nvim -v): `v0.12.0-dev-2033 g83552847f3-dirty` neovim/neovim@83552847f3
- Vim (not Nvim) behaves the same?: ?
- Operating system/version: Linux 6.18.4-zen1-1-zen
- Terminal name/version: kitty
- $TERM environment variable: `xterm-kitty`
- Installation: ?

### PR DESCRIPTION
**Pull request by xguot**
Fixes #37402

### Problem
Previously, `active_lstate` in `executor.c` often pointed to the main Lua thread, even when code was executing inside a coroutine. This caused `nlua_set_sctx` (used by `:verbose`) to inspect the wrong stack, resulting in incorrect 'last_set_linenr' reporting.

### Solution
This PR ensures the C-side `active_lstate` is always synchronized with the executing Lua thread during API calls.

- Create `active_lstate` and state-switching macros globally visible in `src/nvim/lua/executor.h`.
- Updated the API dispatch generator `src/gen/gen_api_dispatch.lua` to inject `ENTER_LUA_ACTIVE_STATE(lstate)` and `LEAVE_LUA_ACTIVE_STATE()` into all generated C API wrapper functions.

This ensures that whenever Lua calls into C, the C layer knows exactly which Lua thread is active, allowing `debug.getinfo` to retrieve the correct line number.

### CODE REVIEW

**Comment by xguot** [comment]
#### I verified this locally with a reproduction script. The output is 4, 3, which confirms the fix:

- 4: The current running line (from debug.getinfo).
- 3: The last_set_linenr, which correctly identifies the line where the option was modified inside the coroutine.

```lua
vim.o.verbose = 1
coroutine.wrap(function()
  vim.o.busy = 2
  print(debug.getinfo(1, 'Snl').currentline)
  print(vim.api.nvim_get_option_info2('busy', {}).last_set_linenr)
end)()
```

image

**Comment by zeertzjq** [comment]
Are the `ENTER_LUA_ACTIVE_STATE()` and `LEAVE_LUA_ACTIVE_STATE()` calls in lua/executor.c needed? These are calling from C into Lua, not from Lua into C.

**Comment by xguot** [comment]
> Are the `ENTER_LUA_ACTIVE_STATE()` and `LEAVE_LUA_ACTIVE_STATE()` calls in lua/executor.c needed? These are calling from C into Lua, not from Lua into C.

Let me check again quickly

**Comment by xguot** [comment]
> Are the `ENTER_LUA_ACTIVE_STATE()` and `LEAVE_LUA_ACTIVE_STATE()` calls in lua/executor.c needed? These are calling from C into Lua, not from Lua into C.



> > Are the `ENTER_LUA_ACTIVE_STATE()` and `LEAVE_LUA_ACTIVE_STATE()` calls in lua/executor.c needed? These are calling from C into Lua, not from Lua into C.
> 
> Let me check again quickly

Yes they are needed, otherwise the 'active_lstate' will NULL by default.

**Comment by zeertzjq** [comment]
> Yes they are needed, otherwise the 'active_lstate' will NULL by default.

Why will it be NULL by default? Isn't it set to the same value as `global_lstate` in `nlua_init()`?

**Comment by xguot** [comment]
> Are the `ENTER_LUA_ACTIVE_STATE()` and `LEAVE_LUA_ACTIVE_STATE()` calls in lua/executor.c needed? These are calling from C into Lua, not from Lua into C.

I originally added them to ensure active_lsate was initialized before lua code ran, but since (Lua -> C) handles the state explicitly, now those lines are redundant. Sorry for the inconvenience. I will remove them now 🙏🏻

**Comment by xguot** [comment]
I removed the redundant 'ENTER_LUA_ACTIVE_STATE()' and 'LEAVE_LUA_ACTIVE_STATE()' calls in lua/executor.c. Thanks for you advice and support.

**Comment by zeertzjq** [comment]
Please add a new test case to test/functional/ex_cmds/verbose_spec.lua (just add a piece of code to the end of `script_file` and then add a corresponding `it()` block below).

**Comment by xguot** [comment]
@zeertzjq Just added test case.

**Comment by zeertzjq** [comment]
It seems that you accidentally squashed your commit into the previous one on master.

**Comment by xguot** [comment]
Sorry, just fixed it.

File: src/gen/gen_api_dispatch.lua [hunk 1]
```diff
@@ -718,6 +718,7 @@ local function process_function(fn)
 
   static int %s(lua_State *lstate)
   {
+    ENTER_LUA_ACTIVE_STATE(lstate);
```
Comment (zeertzjq) [inline src/gen/gen_api_dispatch.lua]: `LEAVE_LUA_ACTIVE_STATE()` is not called if the function returns here:
```c
    if (!nlua_is_deferred_safe()) {
      return luaL_error(lstate, e_fast_api_disabled, "%s");
    }
```
Additionally, is it necessary to call `ENTER_LUA_ACTIVE_STATE()` this early? I think only the actual API call may use `active_lstate`.

Also I remembered I did something else that also involves saving and restoring in <https://github.com/neovim/neovim/pull/32622/files#diff-a9e7b6d06d43f0fab9faeacbd587790177f028f8118d867082513193fbdb4fb4> (not all the changes there are related) by just adding the saving and restoring above and below the actual function call.

Comment (xguot) [reply src/gen/gen_api_dispatch.lua]: Let me fix it

**Comment by xguot** [comment]
Moved 'ENTER_LUA_ACTIVE_STATE()' right before the API call and add 'LEAVE_LUA_ACTIVE_STATE()' in side 'if (!nlua_is_deferred_safe())'.

**Review by xguot — COMMENTED** [review]
I force pushed the new changes.

File: src/gen/gen_api_dispatch.lua [hunk 2]
```diff
@@ -740,6 +741,7 @@ local function process_function(fn)
     write_shifted_output(
       [[
     if (!nlua_is_deferred_safe()) {
+      LEAVE_LUA_ACTIVE_STATE();
```
Comment (bfredl) [inline src/gen/gen_api_dispatch.lua]: if we move the ENTER to be below all these preparing checks, we could avoid this extra LEAVE no ?

File: src/gen/gen_api_dispatch.lua [hunk 3]
```diff
@@ -864,6 +866,7 @@ exit_0:
     lua_pushstring(lstate, err.msg);
     api_clear_error(&err);
     lua_concat(lstate, err_param ? 5 : 2);
+    LEAVE_LUA_ACTIVE_STATE();
```
Comment (bfredl) [inline src/gen/gen_api_dispatch.lua]: we call also avoid this if we delay the ENTER until after all args are parsed

Comment (xguot) [reply src/gen/gen_api_dispatch.lua]: Added fix, than you!

**Comment by xguot** [comment]
Rebased on master and applied the suggested optimization, thanks to @bfredl.

File: src/gen/gen_api_dispatch.lua [hunk 4]
```diff
@@ -840,6 +840,8 @@ local function process_function(fn)
   else
     cparams = cparams:gsub(', $', '')
   end
+
+  write_shifted_output('  ENTER_LUA_ACTIVE_STATE(lstate);\n')
```
Comment (zeertzjq) [inline src/gen/gen_api_dispatch.lua]: `write_shifted_output()` reduces indent by 2, so the indent should be 4 spaces here.
```suggestion
  write_shifted_output('    ENTER_LUA_ACTIVE_STATE(lstate);\n')
```

File: src/gen/gen_api_dispatch.lua [hunk 5]
```diff
@@ -903,6 +905,7 @@ exit_0:
     -- NOTE: we currently assume err_throw needs nothing from arena
     write_shifted_output(
       [[
+      LEAVE_LUA_ACTIVE_STATE();
```
Comment (zeertzjq) [inline src/gen/gen_api_dispatch.lua]: Same here.
```suggestion
    LEAVE_LUA_ACTIVE_STATE();
```

**Review by zeertzjq — APPROVED** [review]

**Comment by xguot** [comment]
Fixed commit message formatting to pass lint checks.
