### PR TITLE
vim-patch:8.2.4912: using execute() to define a lambda doesn't work

### LINKED ISSUE #10375: Problems dynamically creating functions
### Steps to reproduce

The issue comes from consideration of passing a small lambda into a small function. I thought the biggest performance issue might come from PCALL/RETURN and its frame maintenance. Wondered if I could dynamically build a function that put it all together.

I didn't expect it to work, but the following does work. 
```
vim9script

def BuildFunc(expr: string): func
    var x =<< trim eval END
        g:SomeRandomFunc = (d: dict<any>) => {expr}
    END
    execute(x)
    return g:SomeRandomFunc
enddef

var ResultPlus = BuildFunc('d.k1 + d.k2')
var ResultMinus = BuildFunc('d.k1 - d.k2')
echo ResultPlus({k1: 3, k2: 4}) ResultMinus({k1: 3, k2: 4})
```
Output: 7 -1

However trying this with a multiline lambda behaves strangley. Run the following and vim appears to hang; hit ESC and an error shows up
```
vim9script
def BuildFuncMultiLine(expr: string): func
    var x =<< trim END
        g:SomeRandomFunc = (d: dict<any>) => {
            return 42
        }
    END
    execute(x)
    return g:SomeRandomFunc
enddef
var ResultPlus = BuildFuncMultiLine('d.k1 + d.k2')
echo ResultPlus({k1: 3, k2: 4})
```
This is the error seen after hitting ESC
```
Error detected while processing :source buffer=2[29]..function <SNR>41_BuildFuncMultiLine:
line    6:
E1171: Missing } after inline function
```

BTW, a multiline define works OK. The following is a workaround, and having to name the function doesn't seem right, and I presume prevents it from being garbage collected.  There might be some tricks I'm missing...
```

vim9script

def BuildFunc(name: string, expr: string): func
    var x =<< trim eval END
        def {name}(): number
            return {expr}
        enddef
        g:MyRandomFunc = {name}
    END

    execute(x)
    var t = g:MyRandomFunc
    g:MyRandomFunc = null
    return t
enddef

var G = BuildFunc('F1', '42')
echo G()

G = BuildFunc('F2', '999')
echo G()
```

### Expected behaviour

BuildFuncMultiLine does not give an error and produces a usable function.

### Version of Vim

8.2.4891

### Environment

ubuntu, gtk3

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by janlazo**
Problem:    Using execute() to define a lambda doesn't work. (Ernie Rael)
Solution:   Put the getline function in evalarg. (closes vim/vim#10375)

https://github.com/vim/vim/commit/a7583c42cd6b64fd276a5d7bb0db5ce7bfafa730

### CODE REVIEW

File: src/nvim/eval.c [hunk 1]
```diff
@@ -25,6 +25,7 @@
 #include "nvim/errors.h"
 #include "nvim/eval.h"
 #include "nvim/eval/encode.h"
+#include "nvim/eval/funcs.h"
 #include "nvim/eval/executor.h"
```
Comment (zeertzjq) [inline src/nvim/eval.c]:
```suggestion
#include "nvim/eval/executor.h"
#include "nvim/eval/funcs.h"
```
