### PR TITLE
fix(clipboard): make getreg accurate for clipboard registers

### LINKED ISSUE #24257: getreg("+") disagrees with :registers
### Problem

This is motivated by a possible bug in how `getreg` works. Running the following vimscript demonstrates the issue (you'll need wl-copy or an analogous tool):

```vim
" this comment will be copied into both registers
call system("wl-copy --primary --clear && wl-copy --clear")
normal! "+yy
let primary = getreg("*")
let clipboard = getreg("+")
echo "*: " primary
echo "+: " clipboard
registers
```

The output of `getreg` disagrees with the output of `:registers`. After the clipboard is cleared by an external tool and text is copied into `"+`, the same text appears to have been copied into `"*`, as well. This also works the other way around, if `normal! "+yy` is replaced by `normal! "*yy`. I'm not sure if this is the intended behavior or not, but it would be nice to have a Lua API function for working with registers that coincides with the output of `:registers`.

Screenshot of the script's output:

`"*` is not present in `:registers`, as expected.

### Expected behavior

`"*` should be empty. It would be convenient to have something in the Lua API that makes this apparent.

This happens on Neovim version 0.9.1. I'm using Sway on NixOS. The terminal emulator is `foot 1.14.0`. `$TERM = foot`.

### PR DESCRIPTION
**Pull request by rudiejd**
Problem: getreg("*") / getreg("+") disagree with registers (fixes https://github.com/neovim/neovim/issues/24257)
Solution: use a different mode for getting the register to avoid falling back if a register is unset

### CODE REVIEW

**Comment by rudiejd** [comment]
I suspect some of the failing functional tests might have been relying on this behavior in `getreg`

File: test/functional/provider/clipboard_spec.lua [hunk 1]
```diff
@@ -752,4 +752,11 @@ describe('clipboard (with fake clipboard.vim)', function()
     expect('some some')
     eq('some', eval('getreg("*")'))
   end)
+
+  it('has correct value for clipboard registers #24257', function ()
+    eval('setreg("*", "")')
+    eval('setreg("+", "waddup")')
+    eq(eval('getreg("*")'), "")
```
Comment (wookayin) [inline test/functional/provider/clipboard_spec.lua:759]:
```suggestion
    eq("", eval('getreg("*")'))
    eq("waddup", eval('getreg("+")'))
```
`eq` has a signature of `(expected, actual, context?)`

Comment (rudiejd) [reply test/functional/provider/clipboard_spec.lua]: thank you for catching that! I'm new to writing lua tests

**Comment by rudiejd** [comment]
> I suspect some of the failing functional tests might have been relying on this behavior in `getreg`

these were actually failing because I wasn't making `YREG_PUT` work the same way as `YREG_PASTE`,  but it should be fixed now.

File: test/functional/provider/clipboard_spec.lua [hunk 2]
```diff
@@ -752,4 +752,11 @@ describe('clipboard (with fake clipboard.vim)', function()
     expect('some some')
     eq('some', eval('getreg("*")'))
   end)
+
+  it('has correct value for clipboard registers #24257', function ()
+    eval('setreg("*", "")')
+    eval('setreg("+", "waddup")')
+    eq("", eval('getreg("*")'))
+    eq("waddup", eval('getreg("+")'))
```
Comment (wookayin) [inline test/functional/provider/clipboard_spec.lua:760]: On a non-X11 system where there is no distinction between `"*` and `"+"`, those two registers are linked; so aren't they supposed to return the same register result `"waddup"`? How can the test pass?

Comment (rudiejd) [reply test/functional/provider/clipboard_spec.lua:760]: That's a great callout! Correct me if I'm wrong, but I don't think they're _necessarily_ linked, just linked by default. a user in MacOS could technically override `g:clipboard` to set them to do whatever they want. For example, `*` could be configured to use the tmux clipboard while `+` uses the system clipboard (source: [provider docs](https://neovim.io/doc/user/provider.html)).

I think the easiest way to avoid non-X11 weirdness in this test is to disable to clipboard provider, ensuring that `get_clipboard` will fail, then running this test.

**Comment by rudiejd** [comment]
the mac os tests are passing now, but the freebsd ones mysterious fail  😄 https://cirrus-ci.com/task/5148950529835008?logs=functionaltest#L5136

File: test/functional/provider/clipboard_spec.lua [hunk 3]
```diff
@@ -752,4 +752,13 @@ describe('clipboard (with fake clipboard.vim)', function()
...
   end)
+
+  it('has correct value for clipboard registers #24257', function ()
+    -- disable clipboard provider to test this behavior on non-X11 systems
+    command('let g:clipboard = ""')
+    eval('setreg("*", "")')
+    eval('setreg("+", "waddup")')
+    eq('', eval('getreg("*")'))
+    eq('waddup', eval('getreg("+")'))
+  end)
```
Comment (zeertzjq) [inline test/functional/provider/clipboard_spec.lua:763]: The test is wrong and has nothing to do the the issue.
```suggestion
  it('does not fall back to unnamed register with getreg() #24257', function ()
    eval('setreg("", "wrong")')
    command('let g:cliperror = 1')
    eq('', eval('getreg("*")'))
    eq('', eval('getreg("+")'))
  end)
```

Comment (rudiejd) [reply test/functional/provider/clipboard_spec.lua]: This is definitely better more descriptive, since falling back to unnamed is the behavior we don't have to happen. My test accomplished the same thing because the second `setreg` sets the unnamed register to "waddup", but yours is more direct and readable 👍

Comment (zeertzjq) [reply test/functional/provider/clipboard_spec.lua]: But you didn't set the unnamed register. You set the `+` register.

Comment (rudiejd) [reply test/functional/provider/clipboard_spec.lua]: oh interesting, I thought the unnamed register would always be set as a result of setreg, but maybe that is not the case.

File: src/nvim/ops.c [hunk 4]
```diff
@@ -815,9 +815,17 @@ yankreg_T *get_yank_register(int regname, int mode)
...
+  if ((mode == YREG_PASTE || mode == YREG_PUT)
+      && get_clipboard(regname, &reg, false)) {
     // reg is set to clipboard contents.
     return reg;
+  } else if (mode == YREG_PUT && (regname == '*' || regname == '+')) {
+    // in case clipboard not available and we aren't actually pasting,
+    // return an empty register
+    reg = xmalloc(sizeof(yankreg_T));
+    reg->y_array = NULL;
+    reg->y_size = 0;
```
Comment (zeertzjq) [inline src/nvim/ops.c:827]: Hmm, the register returned by this function should not be allocated, so it has to be a pointer to a static variable instead.
```suggestion
    static yankreg_T empty_reg = { .y_array = NULL };
    reg = &empty_reg;
```

File: src/nvim/ops.c [hunk 5]
```diff
@@ -815,9 +815,17 @@ yankreg_T *get_yank_register(int regname, int mode)
...
+    return reg;
```
Comment (zeertzjq) [inline src/nvim/ops.c:828]: Hmm, the register returned by this function should not be allocated, so it has to be a pointer to a static variable instead.
```suggestion
    static yankreg_T empty_reg = { .y_array = NULL };
    return &empty_reg;
```
