### PR TITLE
fix(lsp): restore marks after `apply_text_edits`

### LINKED ISSUE #14307: LSP: vim.lsp.buf.formatting_sync() messes up marks
- `nvim --version`:
```
NVIM v0.5.0-dev+1157-g0ab88c2ea
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1616045056542.local

Features: +acl +iconv +tui
```
- language server name/version: N/A
- Operating system/version: macos

### Steps to reproduce using nvim -u minimal_init.lua
1. Set up some language server that does formatting. For instance diagnosticls:
(You will need prettier installed in the example below, but I don't think the particular formatter matters)
```lua
lspconfig.diagnosticls.setup {
  root_dir = function(filepath)
    return vim.fn.expand("~")
  end,
  filetypes = {
    "javascript",
  },
  init_options = {
    formatFiletypes = {
      javascript = {"prettier"},
    },
    formatters = {
      prettier = {
        command = "prettier",
        args = {"--stdin", "--stdin-filepath", "%filepath"},
        isStdout = true,
        rootPatterns = {".prettierrc", ".prettierrc.json"}
      }
    }
  },
  on_init = function(client)
    client.resolved_capabilities.document_formatting = true
  end,
  on_attach = function()
      vim.api.nvim_command [[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync({}, 5000) ]]
  end,
}

```

2. Open a js file with a bunch of code in it
3. add mark A on line 3 for example
4. move to line 7, add a bunch of whitespace lines, then save to trigger formatter

### Actual behaviour
Mark is removed (or moved to the top of the file)

Observation:
If `:wshada!` is executed before saving and `:rshada!` after, the marks are restored to proper position

### Expected behaviour
Marks stay in place.

### A hacky workaround:
Wasn't sure how expensive `:wshada/rshada` are so wrote the following instead to use on BufWritePre
```lua
LspFormatBuffer = function(bufnr) 
  local marks = {}
  local letters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
  for i = 1, #letters do
    local letter = letters:sub(i, i)
    local markLocation = vim.api.nvim_buf_get_mark(bufnr, letter)
    marks[letter] = markLocation;
  end

  vim.lsp.buf.formatting_sync({}, 5000) 

  for i = 1, #letters do
    local letter = letters:sub(i, i)
    local markLocation = marks[letter];
    local linenr = markLocation[1]
    if (linenr ~= 0) then
      vim.api.nvim_command("" .. linenr .. "mark " .. letter)
    end
  end
end

```

### PR DESCRIPTION
**Pull request by folke**
Right now, whenever any text edits are applied to the buffer, all `marks` part of those lines will be lost.

This is mostly problematic for code formatters that format the whole buffer like `prettier`, `luafmt`, ... (Fixes #14307)

This PR does the following:
* saves marks right before `nvim_buf_set_lines` is called inside `apply_text_edits`
* checks if any marks were lost after doing `nvim_buf_set_lines`
* restores those marks to the previous positions

AFAIK, restoring those marks to their previous position is the best short-term solution.

When doing atomic changes inside a vim doc, vim keeps track of those changes and can update the positions of marks accordingly, but in this case we have a whole doc that changed. There's no simple way to update the positions of all marks from the previous document state to the new document state.  We would need to do a line-based diff in order to track the changes to mark positions. But even then, it's pretty tricky.

## Testing

The easiest way to test this is:
* have a formatter enabled
* open any file
* create a couple of marks
* indent the whole file to the right
* save the file

Without this PR, all marks will be removed.
With this PR, they will be preserved

## Other
Based on a suggestion by @mjlbach, I also tried creating `extmarks` from the `marks` positions right before the text edits to restore them afterwards, but we have similar problems there. All the `extmarks` were moved to the end of the document.

### CODE REVIEW

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -207,6 +207,7 @@ end
 --@param text_edits (table) list of `TextEdit` objects
 --@param buf_nr (number) Buffer id
 function M.apply_text_edits(text_edits, bufnr)
+  bufnr = bufnr or api.nvim_get_current_buf()
```
Comment (folke) [inline runtime/lua/vim/lsp/util.lua:210]: I noticed that `bufnr` is `nil` when called though `vim.lsp.buf.formatting_sync()`
Most functions accept `0` as the current buffer, but not all functions (like `getmarklist`) accept `nil`

**Comment by mjlbach** [comment]
Out of curiosity, did you try with a formatter that wasn't EFM? I'm wondering if extended marks are invalidated because EFM writes new text, then wipes the original buffer. Still not sure how I feel about this half-solution, as it may entirely shuffle the marks so they are effectively meaningless if there are any line-wise changes :/

**Comment by folke** [comment]
This is not what's happening. The `apply_text_edits`, calculates all edits and then sets the new lines in one call, so there's no wiping of the original buffer.

See a simple example below:
image

I added a `mark` for every line and just inserted a `<space>` character in front of `l3`. (didnt save it yet)

This is the EFM textedit:
image

Internally this will be applied as two lines passed to `nvim_buf_set_lines` in **one** call.

After saving, the `marks` for l3 and l4 are gone:
image

> Still not sure how I feel about this half-solution

* I agree to some extent, but the current situation is far worse.
* whenever a text edit is applied to a line with that has a mark, that mark is removed
* the problem is not EFM, but `nvim_buf_set_lines`. See [here](https://github.com/neovim/neovim/blob/c57a85d53490fe53158a0cbd768941b732926d83/src/nvim/api/buffer.c#L508)
 ```
// Adjust marks. Invalidate any which lie in the
// changed range, and move any in the remainder of the buffer.
// Only adjust marks if we managed to switch to a window that holds 
// the buffer, otherwise line numbers will be invalid.
```

The only way to tackle this correctly would be by using a line and character-based diff algorithm to compare the new lines and the lines that are replaced. 

If you can think of a better approach, let me know.

**Comment by mjlbach** [comment]
> This is not what's happening. The apply_text_edits, calculates all edits and then sets the new lines in one call, so there's no wiping of the original buffer.

I think we're talking about two separate things. When you call EFM on a malformatted buffer (of more than one line, with some lines being "correctly" formatted), do you receive more than two textEdit entries in the result table? My understanding is that EFM is appending the formatted buffer in the second result, and then wiping the original buffer in the first result. I think if the textEdits were applied granularly only to the changed lines, the extended marks, at least some of them, would be preserved after https://github.com/neovim/neovim/pull/13703 or similar is applied.

> I agree to some extent, but the current situation is far worse

I'm not sure, I think the current situation is people should assume no marks are preserved on a formatted buffer, after this PR only some marks will be valid, some marks will point to garbage.

> The only way to tackle this correctly would be by using a line and character-based diff algorithm to compare the new lines and the lines that are replaced.

Probably, I think after 13703 the extended mark approach will work for servers that return more granular text edits for formatting

**Comment by folke** [comment]
In the example I posted above, the `formatting` result has `two` text edits.
This is what happens inside [`apply_text_edits`](https://github.com/neovim/neovim/blob/f17542a6ab20e26061a1f8b467c5129cfd009321/runtime/lua/vim/lsp/util.lua#L218):

1. `apply_text_edits` is called with the result table (including those two edits)
2. the two edits are calculated and applied in a table called `cleaned`
3. that `cleaned` list, contains the lines after applying *all* the text edits
4. up until now, the buffer has not been changed in any way
5. at the end of `apply_text_edits` the `cleaned` list is set to the buffer with `nvim_buf_set_lines`

So to clarify, `nvim_buf_set_lines` is called exactly **once** with the granular text edit.

Even if you'd get a result with 50 text edits, the end result would still be exactly one call with the granular calculated edit.

I haven't looked into it too much, but as can be seen [here](https://github.com/neovim/neovim/blob/c57a85d53490fe53158a0cbd768941b732926d83/src/nvim/api/buffer.c#L748), `nvim_buf_set_text`, processes marks in exactly the same way as `nvim_buf_set_lines`, so I don't see how #13703 would fix this?

> I'm not sure, I think the current situation is people should assume no marks are preserved on a formatted buffer, after this PR only some marks will be valid, some marks will point to garbage.

I work  a lot with Typescript / prettier and have format on save enabled. Unfortunately this currently means I can't really use `marks`. Even if I'm editing a line to add a character at the end, the mark is removed.

But I do understand your concern, so feel free to close this PR.

**Comment by justinmk** [comment]
Think we should revisit this. Best-effort is better than nothing here, even if the marks sometimes end up as garbage.

**Comment by folke** [comment]
@justinmk rebased!

**Comment by folke** [comment]
Would be really great to have this merged, since buffer marks are not usable with auto formatting right now.
I actually stopped using marks altogether because of this.

**Review by justinmk — APPROVED** [review]
needs a news.txt item at least. A basic test to exercise it (make sure it's doing _something_) also would be good, but not a blocker. Could probably just add 1-2 lines in an existing test.

**Comment by folke** [comment]
Added a news entry and a couple of tests.

I've also change the implementation so it properly handles marks that have invalid cols / lines.
They will be moved to a valid position.

**Comment by folke** [comment]
wait, messed something up :)

**Comment by folke** [comment]
All good now

**Review by justinmk — APPROVED** [review]
