### PR TITLE
fix(terminal): avoid rescheduling events onto the same queue

### LINKED ISSUE #32753: nvim hang in `vim.wait` when `cat file | nvim 63<&0 </dev/null +"term cat /dev/fd/63"`
### Problem

I use nvim as pager like this:
`nvim 63<&0 </dev/null -u NONE -i NONE --cmd "term cat /dev/fd/63 && sleep 1000"--cmd "lua require[[pager]]($1, $2, $3)"`. This is useful in kitty since it can pipe scrollback buffer to nvim.

After https://github.com/neovim/neovim/commit/35e5307af25785ac90bd00f913fc0df5cf962db3: piping kitty scrollback buffer to nvim make it hang. And this only happened when I use `fish` (maybe since it wrap its prompt with osc 133).

### Steps to reproduce

~`bash repro.sh`:~

Run this in a interactive bash:
```sh
nvim 63< <(python -c "print('\x1b]133;;\x07' + $LINES *'\n', end='')") </dev/null -u NONE -i NONE +"term cat /dev/fd/63" +"lua vim.wait(100)"
```

backtrace:
```
#0 multiqueue_remove at ../neovim/src/nvim/event/multiqueue.c:223
#1 multiqueue_process_events at ../neovim/src/nvim/event/multiqueue.c:147
#2 nlua_wait at ../neovim/src/nvim/lua/executor.c:500
#3 lj_BC_FUNCC
#4 lua_pcall at lj_api.c:1151
#5 nlua_pcall at ../neovim/src/nvim/lua/executor.c:182
#6 nlua_typval_exec  at ../neovim/src/nvim/lua/executor.c:1463
#7 ex_lua at ../neovim/src/nvim/lua/executor.c:1682
#8 execute_cmd0
    at ../neovim/src/nvim/ex_docmd.c:1714
#9 do_one_cmd at ../neovim/src/nvim/ex_docmd.c:2358
#10 do_cmdline at ../neovim/src/nvim/ex_docmd.c:669
#11 exe_commands at ../neovim/src/nvim/main.c:1898
#12 main at ../neovim/src/nvim/main.c:582
```

### Expected behavior

nvim shouldn't hang.

### Nvim version (nvim -v)

https://github.com/neovim/neovim/commit/35e5307af25785ac90bd00f913fc0df5cf962db3

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Linux arch 6.13.5-zen1-1-zen

### Terminal name/version

kitty 0.39.0

### $TERM environment variable

xterm-kitty

### Installation

built from source

### PR DESCRIPTION
**Pull request by gpanders**
Resolves: #32753 

The multiqueue_process_events function drains a given multiqueue until it is empty. If an event on that queue reschedules itself (or another event) onto the same queue, then the queue will never drain and an infinite loop occurs.

This was happening in the terminal when the shell emitted an OSC sequence, triggering a TermRequest event. The TermRequest event is rescheduled because the terminal has pending scrollback (we do this because the TermRequest event includes the buffer row and column in the event data, and those values are invalid while there is pending buffer scrollback).

The pending buffer scrollback is not cleared until the terminal is refreshed. This happens on a timer, which requires the libuv event loop to turn. Under "normal" circumstances this all works because when user input arrives, we stop draining the main event queue and continue with the libuv event loop, which runs the timer, refreshes the terminal, and allows the TermRequest event to proceed without rescheduling itself.

However, when a function like vim.wait() is used, we *continuously* drain the main event queue until it is empty, never stopping for user input. This means the libuv timer never runs and the terminal never gets refreshed, so emit_termrequest continously reschedules itself onto the same event queue, causing an infinite loop.

The solution in this commit is to use a separate "pending" event queue in the terminal which is where events that require a terminal refresh are temporarily placed. This queue is drained after a terminal refresh and events are copied back onto the main queue. This prevents infinite loops since the main event queue will always be able to properly drain.

### CODE REVIEW

**Comment by zeertzjq** [comment]
Add a test?

File: src/nvim/terminal.c [hunk 1]
```diff
@@ -178,6 +178,7 @@ struct terminal {
     bool resize;          ///< pending width/height
     bool cursor;          ///< pending cursor shape or blink change
     StringBuilder *send;  ///< When there is a pending TermRequest autocommand, block and store input.
+    MultiQueue *events;   ///< Separate queue for events waiting for refresh
```
Comment (justinmk) [inline src/nvim/terminal.c:181]:
```suggestion
    MultiQueue *events;   ///< Events waiting for refresh.
```

File: src/nvim/terminal.c [hunk 2]
```diff
@@ -2029,6 +2039,12 @@ static void refresh_terminal(Terminal *term)
 
   int ml_added = buf->b_ml.ml_line_count - ml_before;
   adjust_topline(term, buf, ml_added);
+
+  // Copy pending events back to the main event queue
+  while (!multiqueue_empty(term->pending.events)) {
+    Event event = multiqueue_get(term->pending.events);
+    multiqueue_put_event(main_loop.events, event);
```
Comment (justinmk) [inline src/nvim/terminal.c:2046]: This pattern might be useful in more places, WDYT about adding `multiqueue_move_events` ?

**Comment by justinmk** [comment]
Problem:

When a function like `vim.wait()` is used, we continuously drain the main event queue until it is empty, never stopping for user input. This means the libuv timer never runs and the terminal never gets refreshed, so `emit_termrequest` continously reschedules itself onto the same event queue, causing an infinite loop.

Analysis:

...

Solution:

Use a separate "pending" event queue, where events that require a terminal refresh are temporarily placed. Drain this queue after a terminal refresh and events are copied back onto the main queue. This prevents infinite loops since the main event queue will always be able to properly drain.

**Review by justinmk — APPROVED** [review]

File: src/nvim/terminal.c (hunk 2 above)
Comment (gpanders) [reply src/nvim/terminal.c:2046]: Yea, we use it in at least one other place already. I'll add that.

File: src/nvim/event/multiqueue.c [hunk 3]
```diff
@@ -140,6 +140,16 @@ void multiqueue_put_event(MultiQueue *self, Event event)
   }
 }
 
+/// Move events from src to dest.
+void multiqueue_move_events(MultiQueue *dest, MultiQueue *src)
```
Comment (gpanders) [inline src/nvim/event/multiqueue.c:144]: I ordered the arguments the same way as `memcpy`, `memmove`, etc. If anyone feels strongly about reversing the order let me know (putting `src` first).
