### PR TITLE
fix(languagetree): apply `resolve_lang` to `metadata['injection.language']`

### LINKED ISSUE #106: Treesitter is unable to parse `.jsx` files after seing a `jsx` block in markdown
**Describe the bug**
After opening a markdown buffer with `.jsx` codeblocks, Treesitter can't parse new `.jsx` buffers anymore.

STR:

0. Have `javscript`, `markdown` and `markdown_inline` TS Parsers installed in Neovim
1. create file `test.jsx`
```jsx
export const abc = () => {
    return <div>hello</div>;
};
```
2. create file `test.md`, look at code example below (without the `_`)
3. nvim test.md
4. `:e test.jsx`, see that jsx is not getting parsed by treesitter

**Code example**
```markdown
This is a fun component description:

```jsx
import { Form } from 'somewhere';

<Form>
	{123}
</Form>
``_`
Ignore the `_` above
```

**Expected behavior**
Highlight the code snippet as `jsx` codes

**Actual behavior**
No highlighting is applied, even worse, Treesitter does not parse `.jsx` files from now on anymore.

**Infos**
I found this here: https://github.com/nvim-treesitter/nvim-treesitter/issues/4918 
Removing `markdown` and `markdown_inline` TS Parsers fixes this issue, so I came here :)

### LINKED ISSUE #4918: Sometimes `jsx` files are not getting parsed - "No parser available for the given buffer"
### Describe the bug

Sometimes when working my highlighting for `jsx` files does not work. It may also be on `js` files or even others, but there the lsp is providing semantic information, so it doesn't catch my eye.

Typing `:Inspect` on a token in this file does only display a "Semantic tokens" and not a "Treesitter" section.

Running `:InspectTree` yields the following error:

```
Error executing Lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/playground.lua:241: No parser available for the given buffer                                                                                                           
stack traceback:                                                                                                                                                                                                                                
        [C]: in function 'assert'                                                                                                                                                                                                               
        /usr/share/nvim/runtime/lua/vim/treesitter/playground.lua:241: in function 'inspect_tree'                                                                                                                                               
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:496: in function 'inspect_tree'                                                                                                                                                          
        /usr/share/nvim/runtime/plugin/nvim.lua:18: in function </usr/share/nvim/runtime/plugin/nvim.lua:9> 
```

### To Reproduce

I don't know exactly how to reproduce. When I close Neovim and reopen it works for a while on `jsx` files.

It seems that once it fails once for a `.jsx` file it doesn't even try anymore and fails on all the other `.jsx` files as well.

### Expected behavior

_No response_

### Output of `:checkhealth nvim-treesitter`

```markdown
Error executing Lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/playground.lua:241: No parser available for the given buffer                                                                                                           
stack traceback:                                                                                                                                                                                                                                
        [C]: in function 'assert'                                                                                                                                                                                                               
        /usr/share/nvim/runtime/lua/vim/treesitter/playground.lua:241: in function 'inspect_tree'                                                                                                                                               
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:496: in function 'inspect_tree'                                                                                                                                                          
        /usr/share/nvim/runtime/plugin/nvim.lua:18: in function </usr/share/nvim/runtime/plugin/nvim.lua:9> 
```
```


### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```


### Additional context

My Treesitter config (using lazy.nvim):

```lua
    {
        'nvim-treesitter/nvim-treesitter',
        build = ':TSUpdate',
        version = false,
        event = { 'BufReadPost', 'BufNewFile' },
        dependencies = {
            'nvim-treesitter/nvim-treesitter-context',
            'RRethy/nvim-treesitter-textsubjects',
        },
        config = function()
            require('nvim-treesitter.configs').setup({
                ensure_installed = {
                    'bash',
                    'c',
                    'css',
                    'dockerfile',
                    'fish',
                    'html',
                    'java',
                    'javascript',
                    'json',
                    'lua',
                    'luadoc',
                    'luap',
                    'markdown',
                    'markdown_inline',
                    'nix',
                    'python',
                    'query',
                    'regex',
                    'ruby',
                    'rust',
                    'scss',
                    'svelte',
                    'tsx',
                    'typescript',
                    'vim',
                    'vimdoc',
                    'vue',
                    'yaml',
                },
                highlight = {
                    enable = true,
                    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
                    additional_vim_regex_highlighting = false,
                },
                indent = {
                    enable = true,
                },
                -- for nvim-treesitter-textsubjects
                textsubjects = {
                    enable = true,
                    prev_selection = ',', -- (Optional) keymap to select the previous selection
                    keymaps = {
                        ['.'] = 'textsubjects-smart',
                        ['a;'] = 'textsubjects-container-outer',
                        ['i;'] = 'textsubjects-container-inner',
                    },
                },
                -- for vim-matchup
                matchup = {
                    enable = true,
                },
            })
            require('treesitter-context').setup()
        end,
    }
```

### PR DESCRIPTION
**Pull request by llllvvuu**
`resolve_lang` is applied to `@injection.language` when it's supplied as a capture:

https://github.com/neovim/neovim/blob/f5953edbac14febce9d4f8a3c35bdec1eae26fbe/runtime/lua/vim/treesitter/languagetree.lua#L766-L768

If we want to support `metadata['injection.language']` (as per #22518 and [tree-sitter upstream](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection)) then the behavior should be consistent.

Fixes: nvim-treesitter/nvim-treesitter#4918
Fixes: MDeiml/tree-sitter-markdown#106

### CODE REVIEW

**Review by lewis6991 — APPROVED** [review]
Might be worth adding a test for this.

File: runtime/lua/vim/treesitter/languagetree.lua [hunk 1]
```diff
@@ -731,11 +731,7 @@ local has_parser = function(lang)
     or #vim.api.nvim_get_runtime_file('parser/' .. lang .. '.*', false) > 0
 end
 
---- Return parser name for language (if exists) or filetype (if registered and exists)
----
----@param alias string language or filetype name
----@return string? # resolved parser name
-local function resolve_lang(alias)
+local function resolve_lang_helper(alias)
```
Comment (clason) [inline runtime/lua/vim/treesitter/languagetree.lua:734]: can just inline this into the `resolve_lang` function? (removes indirection)

Comment (llllvvuu) [reply runtime/lua/vim/treesitter/languagetree.lua]: sure, inlined and un-rolled (no for loop)

**Comment by llllvvuu** [comment]
Sure, will design the test tomorrow, sticking in draft for now

**Comment by llllvvuu** [comment]
OK, test added

**Comment by clason** [comment]
@lewis6991 good to go?

**Comment by wookayin** [comment]
Just leaving a note: there is a performance regression caused by this, calling `has_parser` and `nvim_get_runtime_file()` too often, which is going to be fixed by #25201 ~~and #25210~~.

**Comment by clason** [comment]
This actually won't work as expected if the filesystem is case-insensitive (e.g., on macOS). I think we should just force lowercase language names unconditionally. @lewis6991 are we fine with this?

**Comment by lewis6991** [comment]
Yep, sounds good
