### PR TITLE
fix(input): only disable mapped CTRL-C interrupts when getting input

### LINKED ISSUE #15258: Can we map <C-c> to do something and also send an unmapped <C-c> that can interrupt system() ?
### Feature already in Vim?

Yes, this seems to work properly in vim 8.2

### Feature description

Hi,
Thank you all for neovim.
Without a \<C-c\> mapping, \<C-c\> works fine for me to stop a system() command.
But is there a way to map \<C-c\> to do something and also issue an unmapped \<C-c\> - which will interrupt a system() cmd ?
This seems to work ok in vim, but just not in neovim.
I have tried using nvim_input(), feedkeys() and nvim_feedkeys() - but I think the issue is that once \<C-c\> is mapped it no longer is seen asyncronously while a system() cmd is running ???
thx,
-m

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #15258

### CODE REVIEW

File: src/nvim/getchar.c [hunk 1]
```diff
@@ -2317,6 +2317,9 @@ static int vgetorpeek(bool advance)
       // try re-mapping.
       for (;;) {
         check_end_reg_executing(advance);
+        if ((mapped_ctrl_c | curbuf->b_mapped_ctrl_c) & get_real_state()) {
```
Comment (zeertzjq) [inline src/nvim/getchar.c:2320]: This check is needed because `os_breakcheck()` can call `input_enqueue()`.

File: src/nvim/os/input.c [hunk 2]
```diff
@@ -98,14 +98,20 @@ static void create_cursorhold_event(bool events_enabled)
...
+/// wait until either the input buffer is non-empty or, if `events` is not NULL
 /// until `events` is non-empty.
 int os_inchar(uint8_t *buf, int maxlen, int ms, int tb_change_cnt, MultiQueue *events)
 {
   if (maxlen && rbuffer_size(input_buffer)) {
     return (int)rbuffer_read(input_buffer, (char *)buf, (size_t)maxlen);
   }
 
+  // There is no need for CTRL-C to interrupt something, don't let
+  // it set got_int when it was mapped.
```
Comment (justinmk) [inline src/nvim/os/input.c:110]: what does this mean? If there's "no need" then we do we check if it's mapped? Why not always disable it? 

Is "low risk" a better way to word this?

```suggestion
  // No risk of a UI flood, so disable CTRL-C "interrupt" behavior if it's mapped.
```

**Review by justinmk — APPROVED** [review]

File: src/nvim/getchar.c (hunk 1 above)
Comment (justinmk) [reply src/nvim/getchar.c:2320]: That would worth a great 1-line comment here.

    // os_breakcheck() can call input_enqueue()

File: src/nvim/globals.h [hunk 3]
```diff
@@ -670,6 +670,7 @@ EXTERN bool ins_at_eol INIT(= false);   // put cursor after eol when
 EXTERN bool no_abbr INIT(= true);       // true when no abbreviations loaded
 
 EXTERN int mapped_ctrl_c INIT(= 0);  // Modes where CTRL-C is mapped.
+EXTERN bool ctrl_c_interrupts INIT(= true);  // CTRL-C sets got_int
```
[the remark this answers is not in the document]
Comment (zeertzjq) [reply src/nvim/globals.h:673]: I put it here because it used to be here in <https://github.com/neovim/neovim/commit/541eaf598c25e0b853ef441b57c9f7d1bbf3450c>. I can move it.

File: src/nvim/os/input.c [hunk 4]
```diff
@@ -482,7 +490,7 @@ static void input_read_cb(Stream *stream, RBuffer *buf, size_t c, void *data, bo
 
 static void process_interrupts(void)
```
Comment (justinmk) [inline src/nvim/os/input.c:491]: This function name is confusing. You have to read the impl to understand that it's actually setting `got_int`, not processing interrupts. 

```suggestion
static void process_ctrlc(void)
```

File: src/nvim/os/input.c (hunk 2 above)
Comment (zeertzjq) [reply src/nvim/os/input.c:110]: This comment comes from the code removed in <https://github.com/neovim/neovim/commit/541eaf598c25e0b853ef441b57c9f7d1bbf3450c>. There is also a `wtime == -1 || wtime > 100L` in the removed code, but I'm not sure if I should add that check or not, as adding this check will prevent `<C-C>` mapping from working if it is put into input buffer immediately after other keys.

Comment (justinmk) [reply src/nvim/os/input.c:110]: I _think_ my suggestion makes sense then, but I'll leave it up to you.

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
backport?
