### PR TITLE
extmark: fix crash due to invalid column values in inccommand preview

### LINKED ISSUE #11769: Crash with ``%s/\n\n/^M/g``
- `nvim --version`: my own build from the commit 71ee46acc
- `vim -u DEFAULTS` (version: ) behaves differently? yes, it doesn't crash
- Operating system/version: openSUSE/Tumbleweed as of today
- Terminal name/version: gnome-terminal-3.34.2-2.1.x86_64
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Reproduction is unreliable so I don't know what it means, I haven't mean be able to reproduce with ``-u NORC``.

Otherwise I just open a Python file to edit, and when I try command ``%s/\n\n/
/`` nvim crashes. I am not 100% sure whether it crashes already when writing the command (when writing ``\n``), or when I actually run the command.

### Actual behaviour

The stderr contains:
```sh
nvim: /home/abuild/rpmbuild/BUILD/neovim-0.5.0~git.1579742465.71ee46acc/src/nvim/marktree.c:79: relative: Předpoklad „pos_leq(base, *val)“ nesplněn.
```

and the attached gdb shows:
```gdb
~@stitny$ gdb --pid=26423
GNU gdb (GDB; openSUSE Tumbleweed) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 26423
[New LWP 26424]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007efc21a5e4ee in __GI_epoll_pwait (epfd=3, events=events@entry=0x7ffd04a00560, 
    maxevents=maxevents@entry=1024, timeout=timeout@entry=4000, set=set@entry=0x0)
    at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
42	../sysdeps/unix/sysv/linux/epoll_pwait.c: Adresář nebo soubor neexistuje.
(gdb) cont
Continuing.

Thread 1 "nvim" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Adresář nebo soubor neexistuje.
(gdb) t a a bt

Thread 2 (Thread 0x7efc213bb700 (LWP 26424)):
#0  0x00007efc21a5e4ee in __GI_epoll_pwait (epfd=15, events=events@entry=0x7efc213b7780, maxevents=maxevents@entry=1024, timeout=timeout@entry=-1, set=set@entry=0x0) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#1  0x00007efc219158f9 in uv__io_poll (loop=0x7efc213ba8c0, timeout=-1) at src/unix/linux-core.c:284
#2  0x00007efc21925834 in uv_run (loop=loop@entry=0x7efc213ba8c0, mode=UV_RUN_ONCE) at src/unix/core.c:372
#3  0x00005611432c3932 in loop_poll_events (loop=0x7efc213ba8c0, ms=-1) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/event/loop.c:62
#4  0x000056114317fa22 in tui_main (bridge=0x56114360d410, ui=0x56114360d2f0) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/tui/tui.c:442
#5  0x00005611431741d0 in ui_thread_run (data=<optimized out>) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/ui_bridge.c:104
#6  0x00007efc218edf2a in start_thread (arg=<optimized out>) at pthread_create.c:479
#7  0x00007efc21a5e38f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7efc2168cd00 (LWP 26423)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007efc2198455d in __GI_abort () at abort.c:79
#2  0x00007efc21984431 in __assert_fail_base (fmt=0x7efc20b5440b "%s%s%s:%u: %s%sPředpoklad „%s“ nesplněn.\n%n", assertion=0x5611433811dc "pos_leq(base, *val)", file=0x561143380808 "/home/abuild/rpmbuild/BUILD/neovim-0.5.0~git.1579742465.71ee46acc/src/nvim/marktree.c", line=79, function=<optimized out>) at assert.c:92
#3  0x00007efc21993592 in __GI___assert_fail (assertion=assertion@entry=0x5611433811dc "pos_leq(base, *val)", file=file@entry=0x561143380808 "/home/abuild/rpmbuild/BUILD/neovim-0.5.0~git.1579742465.71ee46acc/src/nvim/marktree.c", line=line@entry=79, function=function@entry=0x561143381c10 <__PRETTY_FUNCTION__.7021> "relative") at assert.c:101
#4  0x00005611432499b9 in relative (base=..., val=val@entry=0x561143a53120) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/marktree.c:79
#5  0x0000561143251bfe in pivot_left (b=b@entry=0x5611435df060, p=p@entry=0x561143a50e40, i=0) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/marktree.c:522
#6  0x00005611432529fb in marktree_del_itr (b=0x5611435df060, itr=0x7ffd04a01ce0, rev=<optimized out>) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/marktree.c:389
#7  0x0000561143298da5 in extmark_clear (buf=0x5611435dc210, ns_id=2, l_row=<optimized out>, l_col=<optimized out>, u_row=23, u_col=2147483647) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/extmark.c:249
#8  0x00005611432c8bc7 in do_sub (eap=0x7ffd04a02190, timeout=53377489568450, do_buf_event=<optimized out>) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/ex_cmds.c:4199
#9  0x00005611432befa9 in ex_substitute (eap=0x7ffd04a02190) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/ex_cmds.c:5758
#10 0x00005611432b62f4 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffd04a024f8, flags=flags@entry=34, cstack=cstack@entry=0x7ffd04a02580, fgetline=fgetline@entry=0x0, cookie=cookie@entry=0x0) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/ex_docmd.c:2--Type <RET> for more, q to quit, c to continue without paging--
252
#11 0x00005611432b7f15 in do_cmdline (cmdline=<optimized out>, fgetline=0x0, cookie=0x0, flags=34) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/ex_docmd.c:618
#12 0x00005611432a0f28 in command_line_changed (s=s@entry=0x7ffd04a02d90) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/ex_getln.c:1936
#13 0x00005611432a1d3b in command_line_handle_key (s=s@entry=0x7ffd04a02d90) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/ex_getln.c:1763
#14 0x00005611432a2fd5 in command_line_execute (state=0x7ffd04a02d90, key=<optimized out>) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/ex_getln.c:1055
#15 0x0000561143195c5e in state_enter (s=0x7ffd04a02d90) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/state.c:69
#16 0x00005611432a38e0 in command_line_enter (firstc=firstc@entry=58, count=count@entry=1, indent=indent@entry=0) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/ex_getln.c:427
#17 0x00005611432a3feb in getcmdline (firstc=firstc@entry=58, count=count@entry=1, indent=indent@entry=0, do_concat=do_concat@entry=true) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/ex_getln.c:2009
#18 0x00005611432a4043 in getexline (c=58, cookie=<optimized out>, indent=0, do_concat=<optimized out>) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/ex_getln.c:2188
#19 0x00005611432b7aaa in do_cmdline (cmdline=<optimized out>, fgetline=0x5611432a401d <getexline>, cookie=0x0, flags=0) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/ex_docmd.c:535
#20 0x000056114322b6cd in nv_colon (cap=0x7ffd04a03748) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/normal.c:4627
#21 0x0000561143233dbd in normal_execute (state=0x7ffd04a036c0, key=<optimized out>) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/normal.c:1149
#22 0x0000561143195c5e in state_enter (s=0x7ffd04a036c0) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/state.c:69
#23 0x0000561143233e62 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/normal.c:479
#24 0x0000561143262ff4 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/neovim-0.5.0~git.1579742465.71ee46acc-15.3.x86_64/src/nvim/main.c:580
(gdb)
```

### Expected behaviour
Of course, no crash.

### PR DESCRIPTION
**Pull request by bfredl**
This used to use -1 and MAXCOL values. Make sure in range values are used.

Fixes #11769

### CODE REVIEW

File: test/functional/ui/inccommand_spec.lua [hunk 1]
```diff
@@ -2291,6 +2292,75 @@ describe(":substitute", function()
...
+      | 2|{12: }BBB BB                   |
+      | 3|{12: }CCC CC                   |
+      | 4|{12: }AAA AA                   |
+      | 5|{12: }BBB BB                   |
+      | 6|{12: }CCC CC                   |
+      | 7|{12: }AAA AA                   |
+      {10:[Preview]                     }|
+      :%s/\n\n/{17:^M}/g^                 |
+    ]]}
+    eq(2, eval('1+1')) -- did not crash
```
Comment (justinmk) [inline test/functional/ui/inccommand_spec.lua]: `helpers.assert_alive()`

File: test/functional/ui/inccommand_spec.lua [hunk 2]
```diff
@@ -2291,6 +2292,75 @@ describe(":substitute", function()
...
+  it("inccommand=split, contraction of two subsequent NL chars", function()
+    -- luacheck: push ignore 611
+    local text = [[
+      AAA AA
+      
+      BBB BB
+      
+      CCC CC
+      
+]]
```
Comment (justinmk) [inline test/functional/ui/inccommand_spec.lua]: could avoid lucheck push/pop by:

    local text = 'AAA AA\n\nBBB BB\n\nCCC CC\n\n'

Comment (bfredl) [reply test/functional/ui/inccommand_spec.lua]: There is no reason that luacheck should care about anything that happens between `[[` and `]]`. I would rather try to fix the linter than changing a lot of multiline strings there is nothing wrong with.

Comment (justinmk) [reply test/functional/ui/inccommand_spec.lua]: there aren't a lot of these though.

Comment (bfredl) [reply test/functional/ui/inccommand_spec.lua]: > there aren't a lot of these though.

There is going to be a lot of these when writing extmark/byte-update tests. I do not like needing to completely rewrite a perfectly readable multi-line string because there is a double newline or TAB character (or something else that the linter is not supposed to care about) somewhere in there.

>  Whereas with the multiline version, one needs to understand how the dedent works with the final line.

The only thing that happens here is that the dedenter is _not broken_ w.r.t a final newline, there is nothing "extra" that one needs to understand. Avoiding to use a mechanism in any situation someone could imagine that it could break is not reasonable. That the test works as expected is enough context that nothing weird is going on.
