### PR TITLE
[RFC] rbuffer: Fix for problems with escape input sequences.

### LINKED ISSUE #2936: Mouse wheel scroll inserts text into the command window
Every so often when scrolling a buffer using the mouse wheel I get text inserted into the command window for me, which stops me scrolling as focus has shifted. The text looks like this: `.,.+6455;33M`. The numbers aren't always the same, but the rest is.

This only started after updating neovim to the current head, b656a95, from one a few days before that. 

I'm on ArchLinux and I also had to change a few AUR packages during the update: It removed `libvterm-git-neovim` and installed `libvterm-bzr` in its place.

### PR DESCRIPTION
**Pull request by oni-link**
rbuffer: Fix for problems with escape input sequences.

If at least two escape sequences were read, the beginning of the
second sequence would be off by one and the sequence would be
misinterpreted.

An escape sequence could be split in two parts and be
misinterpreted, when saved in a ring buffer with wrap around.

@ping tarruda

Fixes #2936

### CODE REVIEW

File: src/nvim/os/rstream.c [hunk 1]
```diff
@@ -168,7 +168,11 @@ void rstream_stop(RStream *rstream)
 static void alloc_cb(uv_handle_t *handle, size_t suggested, uv_buf_t *buf)
 {
   RStream *rstream = handle_get_rstream(handle);
+  // If we are at the end of the ring buffer, a (long) input sequence
+  // could be read in two steps and be misinterpreted.
+  rbuffer_reset(rstream->buffer);
   buf->base = rbuffer_write_ptr(rstream->buffer, &buf->len);
+  assert(buf->len >= 6);
```
Comment (fwalch) [inline src/nvim/os/rstream.c]: Where does this "magic number" come from? Maybe replace it by some constant for readability?
Note: I have no clue about the surrounding code, maybe then the number would make sense immediately.

Comment (oni-link) [inline src/nvim/os/rstream.c]: Scrolling the mouse wheel gives `6` input bytes like these `1b 5b 4d 61 24 3e` (=> `<ScrollWheelDown><3,29>`). That was the maximum number for a single mouse input that I saw.

Comment (fwalch) [inline src/nvim/os/rstream.c]: Okay.. maybe add this explanation as a comment?

Comment (oni-link) [inline src/nvim/os/rstream.c]: @fwalch, I removed the modifications to `alloc_cb()` and placed the call to `rbuffer_reset()` at the end of `read_cb()`. With this we can be sure the next call to `alloc_cb()` allocates the complete ring buffer. No need for an `assert()` anymore.

**Comment by oni-link** [comment]
With the last rebase:
* modifications to `alloc_cb()` were removed
* `rbuffer_reset()` is now called from `read_cb()`

**Comment by tarruda** [comment]
LGTM

**Comment by tarruda** [comment]
Thanks
