### PR TITLE
fix(terminal): interrupt/got_int hangs terminal

### LINKED ISSUE #20726: terminal mode hang at 100% CPU when interrupted with <C-c>
### Neovim version (nvim -v)

NVIM v0.8.0

### Vim (not Nvim) behaves the same?

not using vim

### Operating system/version

Void Linux kernel 5.10.147

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

screen-256color

### Installation

Void Linux xbps package manager

### How to reproduce the issue

I am able to consistently get neovim to hang at 100% CPU when using [fzf-lua](https://github.com/ibhagwan/fzf-lua), opening any interface and quickly pressing `<C-c>`.
> Note that to rerproduce this consistently [this commit](https://github.com/ibhagwan/fzf-lua/commit/c90a88b354ae12736760f623000d91b438b04234) which maps `<C-c>` to `<Esc>` in termal mode, needs to be reverted or you can test with the [`trace` branch](https://github.com/ibhagwan/fzf-lua/tree/trace) which also contains trace logging to file.

What happens behind the scenes is fzf-lua opening a new window and running `termopen` with the fzf command and then waits for the job's `on_exit` callback.

While stuck I ran  `strace -s 99 -ffp <pid> ` on the neovim pid and it seems to be polling a no longer existing thread (not sure about that, but in the below pid `27433` no longer exists), the loop below continues endlessly:
```
[pid 27433] <... epoll_wait resumed>[{events=EPOLLIN, data={u32=18, u64=18}}], 1024, -1) = 1
[pid 27432] <... write resumed>)        = 8
[pid 27433] read(18, "\1\0\0\0\0\0\0\0", 1024) = 8
[pid 27432] epoll_wait(9,  <unfinished ...>
[pid 27433] epoll_wait(15,  <unfinished ...>
[pid 27432] <... epoll_wait resumed>[], 1024, 0) = 0
[pid 27432] epoll_wait(9, [], 1024, 0)  = 0
[pid 27432] epoll_wait(9, [], 1024, 0)  = 0
[pid 27432] epoll_wait(9, [], 1024, 0)  = 0
[pid 27432] write(32, "\3", 1)          = 1
[pid 27432] write(18, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>
[pid 27433] <... epoll_wait resumed>[{events=EPOLLIN, data={u32=18, u64=18}}], 1024, -1) = 1
[pid 27432] <... write resumed>)        = 8
[pid 27433] read(18, "\1\0\0\0\0\0\0\0", 1024) = 8
[pid 27432] epoll_wait(9,  <unfinished ...>
[pid 27433] epoll_wait(15,  <unfinished ...>
[pid 27432] <... epoll_wait resumed>[], 1024, 0) = 0
[pid 27432] epoll_wait(9, [], 1024, 0)  = 0
[pid 27432] epoll_wait(9, [], 1024, 0)  = 0
[pid 27432] epoll_wait(9, [], 1024, 0)  = 0
[pid 27432] write(32, "\3", 1)          = 1
[pid 27432] write(18, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>
```

In an effort to understand where this issue comes from I added trace logging to my plugin from the moment the `termopen` succeeds until `on_exit` is called, you can enable logging to file (only with the [`trace` branch](https://github.com/ibhagwan/fzf-lua/tree/trace)) with:
```lua
require'fzf-lua'.setup({ debug_tracelog = "~/neovim.log" })
```

With the above setup the file gets overwritten each time the fzf-lua interface is open, the results indicate neovim is stuck in an endless loop calling the `vim._on_key(char)` function within the runtime `runtime/lua/vim/_editor.lua:560`, relevant part of the log right before it gets stuck:
```
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:102 nil
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:79 finish
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:81 finish
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:82 finish
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:83 finish
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:85 finish
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:104 nil
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns/manager.lua:449 nil
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns/manager.lua:450 nil
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns/manager.lua:451 nil
2022-10-18T13:26:32 @/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:258 nil
2022-10-18T13:26:32 @/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:259 nil
2022-10-18T13:26:32 @/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:260 nil
2022-10-18T13:26:32 @vim/_editor.lua:561 nil  <= first line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:562 nil
2022-10-18T13:26:32 @vim/_editor.lua:563 nil
2022-10-18T13:26:32 @vim/_editor.lua:572 nil
2022-10-18T13:26:32 @vim/_editor.lua:581 nil
2022-10-18T13:26:32 @vim/_editor.lua:561 nil  <= first line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:562 nil  <= last line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:563 nil
2022-10-18T13:26:32 @vim/_editor.lua:572 nil
2022-10-18T13:26:32 @vim/_editor.lua:581 nil  <= last line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:561 nil  <= first line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:562 nil
2022-10-18T13:26:32 @vim/_editor.lua:563 nil
2022-10-18T13:26:32 @vim/_editor.lua:572 nil
2022-10-18T13:26:32 @vim/_editor.lua:581 nil  <= last line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:561 nil  <= first line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:562 nil
2022-10-18T13:26:32 @vim/_editor.lua:563 nil
2022-10-18T13:26:32 @vim/_editor.lua:572 nil
2022-10-18T13:26:32 @vim/_editor.lua:581 nil  <= last line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:561 nil  <= first line of vim._on_key
```

I think this might be related to neovim not yet interrupting lua code as explained in #6800?

@famiu, @ZyX-I, @justinmk, if my analysis is correct, do you have any idea why this happens? What part of the code causes this? Any workarounds I can apply before #19096 is merged (aside from remapping `<C-c>`)?

### Expected behavior

Neovim should be able to handle `<C-c>`.

### Actual behavior

Neovim will occasionally become unresponsive when pressing `<C-c>`.

### PR DESCRIPTION
**Pull request by ibhagwan**
`terminal_execute` should always clear `got_int` or `safe_vgetc` will keep returning `Ctrl_C` in an endless loop.

Minimal reproduction of the issue:
> will cause neovim to hang with 100% CPU prior to this patch
```vim
:autocmd TermEnter * call timer_start(500, {-> interrupt()})
:new | term
:startinsert
```

Closes #20726

### CODE REVIEW

**Comment by justinmk** [comment]
please includes the relevant parts of your analysis, in the commit message. and also the comment from https://github.com/neovim/neovim/issues/20726#issuecomment-2290574907 is helpful: 

> The are some other places that can set got_int. For example, the hang can happen when calling interrupt() in Terminal mode.
> So got_int needs to be cleared more often

File: src/nvim/terminal.c [hunk 1]
```diff
@@ -726,6 +726,9 @@ static int terminal_execute(VimState *state, int key)
     FALLTHROUGH;
 
   default:
+    if (key == Ctrl_C) {
+      got_int = false;
```
Comment (justinmk) [inline src/nvim/terminal.c:730]: how is anyone going to know the purpose of this in the future? git spelunking which leads to... a gigantic github discussion... is costly. We can easily compress the conclusion into a minimal comment.

```suggestion
      // terminal_enter unconditionally sets `mapped_ctrl_c` to avoid got_int. 8eeda7169aa4
      // But got_int may be set elsewhere, e.g. by interrupt(). So ensure that it is cleared.
      got_int = false;
```

Comment (justinmk) [reply src/nvim/terminal.c:730]: After this change, do we even need the `mapped_ctrl_c |= ...` line?

**Comment by justinmk** [comment]
> Minimal reproduction of the issue:

can you add a test? `test/functional/terminal/buffer_spec.lua` looks like a good place

File: src/nvim/terminal.c (hunk 1 above)
Comment (ibhagwan) [reply src/nvim/terminal.c:730]: > After this change, do we even need the `mapped_ctrl_c |=` ... line?

For the purpose of `got_int` in terminals, it woild be safe to  assume it is no longer required.

That said, I’m not that acquianted with the code base to guarantee `mapped_ctrl_c` doesn’t have any other purpose, I can do some more digging and see if it’s used anywhere else but since we won’t be able to remove the condition that sets `ctrl_c_interrupts` (as it’s required for buffer ctrl-c mappings) the benefit of removing `mapped_ctrl_c` is not that impactful.

> how is anyone going to know the purpose of this in the future? git spelunking which leads to... a gigantic github discussion... is costly. We can easily compress the conclusion into a minimal comment.

Fair enough, this would be  my first commit to neovim, I am not yet familiar with comment preferences and best practices in this repo.

**Comment by ibhagwan** [comment]
> > Minimal reproduction of the issue:
> 
> can you add a test? `test/functional/terminal/buffer_spec.lua` looks like a good place

Sure, I’ll have to do some of the testing codebase exploration on how to test that the process isn’t frozen, if you can point me towards an existing similar test would be very helpful and save me some time :)

**Comment by ibhagwan** [comment]
> Maybe you can just use `feed()` and then `screen:expect()` to check if the process is responding to input.

I wasn't able to run the tests locally yet so I thought of a different way to test stolen from the `ModeChanged` tests, using the autocmd that sends a delayed `interrupt` if the process is frozen we won't be able to return from terminal (insert) mode to normal mode.

https://github.com/neovim/neovim/pull/30056/commits/7e41baf6ec57ee2daff7371b8bddb15ad551e0cf

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
confirmed that the test case fails correctly, though it hangs (so `screen:expect()` would be ideal, since it handles hangs better)

**Comment by ibhagwan** [comment]
> confirmed that the test case fails correctly, though it hangs (so `screen:expect()` would be ideal, since it handles hangs better)

Them @justinmk!


> if there are no further comments, ping me in a few days to merge this

Will do, have a great weekend.

**Comment by ibhagwan** [comment]
Tysm @zeertzjq for simplifying the CI!

@justinmk, would be a great start of the week when this gets merged and I can close the only lingering issue in fzf-lua :)

**Comment by ibhagwan** [comment]
Ty for all the help @zeertzjq @justinmk walking me through this 🙏
