### PR TITLE
fix(lsp): fix off-by-one error for omnifunc word boundary

### LINKED ISSUE #25177: LSP: completion via omnifunc deletes previous character
### Problem

Using the built in completion (omnifunc) with an LSP server deletes the previous character upon completion.

https://github.com/neovim/neovim/assets/7882157/fe4bb4a6-0a65-4479-8963-e136fadd22cc

### Steps to reproduce

1. Install language server of your choice (I tested with `clangd` and `rust_analyzer`)
2. `nvim -u NONE <test file of your choice>`
3. `:lua vim.lsp.start_client{ cmd = {"/path/to/language/serer"} }`
4. `:lua vim.lsp.buf_attach_client(vim.fn.bufnr(), 1)`
5. Trigger completion via ctrl-x + ctrl-o, notice how the character right before the cursor gets deleted.

### Expected behavior

Character before the cursor is not deleted

### Neovim version (nvim -v)

v0.10.0-dev-1113+gf5a09f1b03

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Arch Linux

### Terminal name/version

foot

### $TERM environment variable

foot

### Installation

AUR

### PR DESCRIPTION
**Pull request by mfussenegger**
Fixes https://github.com/neovim/neovim/issues/25177

I initially wanted to split this into a refactor commit to make it more
testable followed by a fix, but it appears the refactor already accidentally
fixed the issue by normalizing lnum/col to 0-indexing

### CODE REVIEW

**Comment by mfussenegger** [comment]
@SanchayanMaity @Supreeeme could you give this a try?

File: runtime/lua/vim/lsp/_completion.lua [hunk 1]
```diff
@@ -124,39 +125,77 @@ local function adjust_start_col(lnum, line, items, encoding)
...
 
+---@param line string line content
+---@param lnum integer 0-indexed line number
+---@param client_start_boundary integer 0-indexed word boundary
+---@param server_start_boundary? integer 0-indexed word boundary, based on textEdit.range.start.character
+---@param result lsp.CompletionList|lsp.CompletionItem[]
+---@param encoding string
+---@return table[] matches
+---@return integer? server_start_boundary
+function M._convert_results(
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/_completion.lua:136]: Nit: Add a `@private` annotation for LuaLS to emit a warning for external callers.

File: runtime/lua/vim/lsp/_completion.lua [hunk 2]
```diff
@@ -124,39 +125,77 @@ local function adjust_start_col(lnum, line, items, encoding)
...
+  --                                 .newText = 'plenary.async'
+  --                  ^^^
+  --                  prefix (We'd remove everything not starting with `asy`,
+  --                  so we'd eliminate the `plenary.async` result
+  --
+  -- `adjust_start_col` is used to prefer the language server boundary.
+  --
+  local candidates = get_items(result)
+  local curstartbyte = adjust_start_col(lnum, line, candidates, encoding)
+  if server_start_boundary == nil then
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/_completion.lua:161]: Nit, feel free to dismiss: Given that only `false` and `nil` are falsy in Lua, I _think_ that this repo usually leans towards `not server_start_boundary`.

Again: Ignore me if this is too nitpicky.

File: runtime/lua/vim/lsp/_completion.lua [hunk 3]
```diff
@@ -124,39 +125,77 @@ local function adjust_start_col(lnum, line, items, encoding)
...
+  return matches, server_start_boundary
+end
+
 ---@param findstart integer 0 or 1, decides behavior
 ---@param base integer findstart=0, text to match against
 ---@return integer|table Decided by {findstart}:
 --- - findstart=0: column where the completion starts, or -2 or -3
 --- - findstart=1: list of matches (actually just calls |complete()|)
 function M.omnifunc(findstart, base)
+  assert(base) -- silence luals
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/_completion.lua:177]: I don't see why this `assert` is needed from the parameter type (?).

File: runtime/lua/vim/lsp/_completion.lua [hunk 4]
```diff
@@ -124,39 +125,77 @@ local function adjust_start_col(lnum, line, items, encoding)
...
-  -- Then, perform standard completion request
-  if log.info() then
-    log.info('base ', base)
-  end
-
   local win = api.nvim_get_current_win()
-  local pos = api.nvim_win_get_cursor(win)
+  local cursor = api.nvim_win_get_cursor(win)
+  local lnum = cursor[1] - 1
+  local cursor_col = cursor[2]
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/_completion.lua:188]: Every time I see these 3 lines I dream of the day we have something like `cursor_to_lsp_pos`...

File: runtime/lua/vim/lsp/_completion.lua [hunk 5]
```diff
@@ -124,39 +125,77 @@ local function adjust_start_col(lnum, line, items, encoding)
...
   local line = api.nvim_get_current_line()
-  local line_to_cursor = line:sub(1, pos[2])
-  log.trace('omnifunc.line', pos, line)
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/_completion.lua:150]: Why was this log removed?

File: runtime/lua/vim/lsp/_completion.lua [hunk 6]
```diff
@@ -165,34 +204,18 @@ function M.omnifunc(findstart, base)
     local params = util.make_position_params(win, client.offset_encoding)
     client.request(ms.textDocument_completion, params, function(err, result)
       if err then
-        log.warn(err.message)
+        require('vim.lsp.log').warn(err.message)
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/_completion.lua:207]: Why do you re-importing `log` here?

File: runtime/lua/vim/lsp/_completion.lua (hunk 2 above)
Comment (mfussenegger) [reply runtime/lua/vim/lsp/_completion.lua:161]: Yes this is too nitpicky :)
There is nothing wrong being explicit.

File: runtime/lua/vim/lsp/_completion.lua (hunk 3 above)
Comment (mfussenegger) [reply runtime/lua/vim/lsp/_completion.lua:177]: The parameter isn't used otherwise so luals would emit a warning. But removing it or turning it into `_` isn't ideal either due to the docs/omnifunc signature.

File: runtime/lua/vim/lsp/_completion.lua (hunk 5 above)
Comment (mfussenegger) [reply runtime/lua/vim/lsp/_completion.lua:150]: I felt like it wasn't really useful. The information was quite limited and in most cases not enough to actually resolve an issue.

File: runtime/lua/vim/lsp/_completion.lua (hunk 6 above)
Comment (mfussenegger) [reply runtime/lua/vim/lsp/_completion.lua:207]: Given that this is the only use I removed the other import and placed it here to make it lazy

File: runtime/lua/vim/lsp/_completion.lua (hunk 4 above)
Comment (clason) [reply runtime/lua/vim/lsp/_completion.lua:189]: Or an abstract Position class that can handle conversion to the different conventions transparently ;)

**Comment by MariaSolOs** [comment]
@mfussenegger With this change I'm no longer getting completions in the following case:
1. Open [`mark.c`](https://github.com/neovim/neovim/blob/bc850ba2a090a9a4733a82a7555a5a70264ce1ac/src/nvim/mark.c).
2. Go to line 60.
3. Type `Om<C-x><C-o>`.
4. On `master` I get the list of completions, while on the PR branch there's a "Pattern not found" error.

**Comment by SanchayanMaity** [comment]
> @SanchayanMaity @Supreeeme could you give this a try?

Fixes things here when testing with tsserver and rust analyzer.

File: runtime/lua/vim/lsp/_completion.lua (hunk 4 above)
Comment (justinmk) [reply runtime/lua/vim/lsp/_completion.lua:189]: https://github.com/neovim/neovim/issues/25509
