### PR TITLE
Shada saving improvements

### LINKED ISSUE #31890: shada: don't store jumplist
### Problem

I use global marks for navigation across neovim instances by using the shada system. However this also means I have to sync the jumplist. Thus when I open nvim instance 2 and jump back with `<C-o>` I accidentally go back to a file previously open in nvim instance 1.

### Expected behavior

Add an option to not store the jumplist in the shada file. E.g. allow `set shada=f1` to enable file marks without needing the `'` option.

### LINKED ISSUE #33511: Bug or incorrect documentation of `shada-'`
### Problem

Currently, when saving the shada file (`wshada`) and then reading it in another neovim instance (`rshada`), the jumplist is merged.

After reading the documentation of `shada-'`, I tried `'0` in my shada option, however, this seems to be ignored. 
From the docs:
> ```
> 						*shada-'*
> 	'	Maximum number of previously edited files for which the marks
> 		are remembered.  This parameter must always be included when
> 		'shada' is non-empty.
> 		Including this item also means that the |jumplist| and the
> 		|changelist| are stored in the shada file.
> ```

However, I saw in #5078 and #31890 that this seems to be expected behavior(?)

So here my question: is this a bug or is the documentation incorrect?

### Steps to reproduce

1. Use nvim ("instance 1") with 
```lua
vim.opt.shada = "!,'0,<50,s10,h" -- default but with '0 instead of '100
```
2. navigate around
3. `:wshada`
4. Open another nvim instance ("instance 2") with the settings from above
5. `:rshada` in instance 2 -> you have the jumplist from instance 1

### Expected behavior

Either behave like stated in the docs (ie, respect the value of `shada-'`), or update the docs.

### Nvim version (nvim -v)

0.11.0

### Vim (not Nvim) behaves the same?

don't know.

### Operating system/version

6.13.8-arch1-1 

### Terminal name/version

ghostty 1.1.3-arch1

### $TERM environment variable

xterm-256color

### Installation

AUR

### PR DESCRIPTION
**Pull request by atoerien**
Yesterday was trying to prevent the jumplist from being saved in the shada file, as I've been for ages experiencing what is basically #31890. I first tried to remove the `'` item from `'shada'`, as `:h shada-'` says "Including this item also means that the jumplist and the changelist are stored in the shada file.". But then I got an error because of "This parameter must always be included when 'shada' is non-empty.". Together these two sentences are confusing, and effectively mean that you can't prevent the jumplist and changelist from being stored in the shada file. I also tried `'0` which as expected stopped local marks from being saved, but not the jumplist.

I took a look at the code and it seemed quite straighforward to fix the problem - just add a check to not call `shada_init_jumps` if `'0` is in `'shada'`.

While testing I found and fixed three more issues with `shada_write`:
- `/0` doesn't prevent saving the previous search and substitute patterns, directly contradicting `:h shada-/`
- If there is no previous `:s` replacement string, a empty zero-timestamp shada item is stored 
- `f0` correctly prevents saving global marks, except for the `'0` mark which is always saved

So with this I can now use `'0` to stop storing the jumplist in the shada file. This works for me because I also don't care for storing marks, but I think it is a valid usecase to be able to store local marks (and `v:oldfiles`) but not the jumplist. Local marks are buffer-local and the jumplist is window-local (and the shada file also only stores the jumplist of the current window), so imo the jumplist should get its own `'shada'` item, `j` makes the most sense to me.

Fixes #33511
Fixes #31890
Related #5078

### CODE REVIEW

**Comment by AThePeanut4** [comment]
Also, `:h 'shada'` isn't particularly clear on how most of the options control what is saved and what is read from the shada file. From what I can tell, everything but the changelist, buffer list and global variables are always read from the shada file even if they are disabled in `'shada'`. In my case, to actually remove all the jump items from the shada file and stop them from being restored, I had to temporarily set `'100` in `'shada'`, do `:clearjumps`, and then `:wshada!`.

I think the most reasonable way to handle this would be to save and restore everything "symmetrically" using `'shada'`, e.g. if `/0` is in `'shada'` then don't save or restore search history or search/sub patterns. But when merging into an existing shada file, everything in it should be preserved, so in this scenario the existing search history and search/sub patterns shouldn't be removed, unless you use `:wsh!`. Doing a merge this way allows for two instances to have different `'shada'` options without having them interfere with each other.

**Comment by justinmk** [comment]
Although this is fixing bugs, it's significant enough to mention it in `:help news`. What's a 1-sentence description?

> imo the jumplist should get its own `'shada'` item, `j` makes the most sense to me.

That isn't implemented here, right?

> when merging into an existing shada file, everything in it should be preserved, so in this scenario the existing search history and search/sub patterns shouldn't be removed, unless you use `:wsh!`. Doing a merge this way allows for two instances to have different `'shada'` options without having them interfere with each other.

That would be a welcome improvement.

File: src/nvim/shada.c [hunk 1]
```diff
@@ -2396,38 +2396,42 @@ static ShaDaWriteResult shada_write(FileDescriptor *const sd_writer,
     } while (var_iter != NULL);
   }
 
-  // Initialize jump list
-  wms->jumps_size = shada_init_jumps(wms->jumps, &removable_bufs);
+  if (num_marked_files > 0) {
```
Comment (justinmk) [inline src/nvim/shada.c:2399]:
```suggestion
  if (num_marked_files > 0) {  // Skip if "shada='0".
```

File: src/nvim/shada.c [hunk 2]
```diff
@@ -2396,38 +2396,42 @@ static ShaDaWriteResult shada_write(FileDescriptor *const sd_writer,
...
+    // Initialize jump list
+    wms->jumps_size = shada_init_jumps(wms->jumps, &removable_bufs);
+  }
 
-  const bool search_highlighted = !(no_hlsearch
-                                    || find_shada_parameter('h') != NULL);
-  const bool search_last_used = search_was_last_used();
+  if (dump_one_history[HIST_SEARCH] > 0) {
```
Comment (justinmk) [inline src/nvim/shada.c:2404]:
```suggestion
  if (dump_one_history[HIST_SEARCH] > 0) {  // Skip if "shada=/0".
```

File: src/nvim/shada.c [hunk 3]
```diff
@@ -2396,38 +2396,42 @@ static ShaDaWriteResult shada_write(FileDescriptor *const sd_writer,
...
-  {
+    // Initialize substitute replacement string
     SubReplacementString sub;
     sub_get_replacement(&sub);
-    wms->replacement = (PossiblyFreedShadaEntry) {
-      .can_free_entry = false,
-      .data = {
-        .type = kSDItemSubString,
-        .timestamp = sub.timestamp,
+    if (sub.sub != NULL) {
```
Comment (justinmk) [inline src/nvim/shada.c:2420]:
```suggestion
    if (sub.sub != NULL) {  // Don't store empty replacement string.
```

File: src/nvim/shada.c [hunk 4]
```diff
@@ -2557,7 +2561,7 @@ static ShaDaWriteResult shada_write(FileDescriptor *const sd_writer,
 
   // Update numbered marks: '0' should be replaced with the current position,
   // '9' should be removed and all other marks shifted.
```
Comment (justinmk) [inline src/nvim/shada.c:2563]:
```suggestion
  // Update numbered marks: replace '0 mark with the current position,
  // remove '9 and shift all other marks. Skip if "shada=f0".
```

File: test/functional/shada/marks_spec.lua [hunk 5]
```diff
@@ -51,29 +51,115 @@ describe('ShaDa support code', function()
...
-    nvim_command('kB')
     nvim_command('wshada')
     reset()
     nvim_command('language C')
     eq('Vim(normal):E20: Mark not set', exc_exec('normal! `A'))
+    eq('Vim(normal):E20: Mark not set', exc_exec('normal! `0'))
   end)
 
-  it("does read back global mark even with `'0` and `f0` in shada", function()
+  it("does read back global and numbered mark even with `'0` and `f0` in shada", function()
```
Comment (justinmk) [inline test/functional/shada/marks_spec.lua:150]:
```suggestion
  it("restores global and numbered marks even with `'0` and `f0` in shada", function()
```

File: test/functional/shada/marks_spec.lua [hunk 6]
```diff
@@ -152,6 +238,37 @@ describe('ShaDa support code', function()
     eq(saved, exec_capture('jumps'))
   end)
 
+  it("does not dump jump list if `'0` in shada", function()
```
Comment (justinmk) [inline test/functional/shada/marks_spec.lua:241]:
```suggestion
  it("does not dump jumplist if `'0` in shada", function()
```

File: test/functional/shada/marks_spec.lua [hunk 7]
```diff
@@ -51,29 +51,115 @@ describe('ShaDa support code', function()
     eq(2, nvim_current_line())
   end)
 
-  it('does not dump global mark with `f0` in shada', function()
+  it('is able to dump and read back numbered marks', function()
```
Comment (justinmk) [inline test/functional/shada/marks_spec.lua:54]:
```suggestion
  it('can dump and read back numbered marks', function()
```

**Review by justinmk — APPROVED** [review]
LGTM

**Comment by justinmk** [comment]
> Nope. It should be a straightforward change, let me know if I should make a PR.

Not sure how much demand there is for it, so maybe create an issue if there isn't one already.
