### PR TITLE
fix(floatwin): handle viewport width properly at end of window

### LINKED ISSUE #35431: wrong winborder after #33481
### Problem

after #33481 ,

`nvim --clean -u repro.lua`
```lua
vim.o.number = true
vim.api.nvim_open_win(0, true, {
  width = 3,
  height = 10,
  row = 0,
  col = 0,
  relative = 'cursor',
  border = 'rounded',
})
```

right edge missing border:
Image

### Steps to reproduce

.

### Expected behavior

.

### Nvim version (nvim -v)

bd413a2f55be7db4e4d9b821758580f59b5cc01e

### Vim (not Nvim) behaves the same?

no

### Operating system/version

linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

built from source

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #35431

Also avoid repeated calls of compute_foldcolumn().

### CODE REVIEW

File: src/nvim/drawscreen.c [hunk 1]
```diff
@@ -2408,7 +2408,7 @@ static void win_update(win_T *wp)
       wp->w_filler_rows = wp->w_view_height - srow;
     } else if (dy_flags & kOptDyFlagTruncate) {      // 'display' has "truncate"
       // Last line isn't finished: Display "@@@" in the last screen line.
-      grid_line_start(&wp->w_grid, wp->w_view_height - 1);
+      grid_line_start(&wp->w_grid, wp->w_view_height - 1, wp->w_view_width);
       grid_line_fill(0, MIN(wp->w_view_width, 3), wp->w_p_fcs_chars.lastline, at_attr);
```
Comment (bfredl) [inline src/nvim/drawscreen.c]: Hmm its a bit weird that just specifying `MIN(wp->w_view_width, 3)`  isn't enough. `grid_line_flush()` is not supposed to touch cells outside the total [min, max) range of all interleaving calls...

Comment (zeertzjq) [reply src/nvim/drawscreen.c]: `win_draw_end()` is the place where the drawing exceeded the viewport, not here.

Comment (bfredl) [reply src/nvim/drawscreen.c]: This is still a change that is happening in this PR and I want to understand what it is changing.

I looked for all the places where `grid_line_start()` is called with something else than -1 to understand what the changes in logic are and if it can be done by fixing min/max col args in the interleaving calls instead of making the signature of `grid_line_start()` more complicated. Thus I need to understand the point of every single such change.

File: src/nvim/drawscreen.c [hunk 2]
```diff
@@ -2568,7 +2568,7 @@ void win_draw_end(win_T *wp, schar_T c1, bool draw_margin, int startrow, int end
 {
   assert(hl >= 0 && hl < HLF_COUNT);
   for (int row = startrow; row < endrow; row++) {
-    grid_line_start(&wp->w_grid, row);
+    grid_line_start(&wp->w_grid, row, wp->w_view_width);
```
Comment (bfredl) [inline src/nvim/drawscreen.c]: but if this is the **only** callsite which truly is changed I'd rather wrap the grid_line_fill/put calls right here with `MIN(foo, width)` and/or if statements, than changing the signature of `grid_line_start()` (which affects code which just wants to draw with already correct column args in every other place)

File: src/nvim/drawscreen.c (hunk 1 above)
Comment (zeertzjq) [reply src/nvim/drawscreen.c]: When passing the `w_grid` of a window, the drawing should be limited to `w_view_width`. When the grid doesn't not correspond to a window, there is no such limit. This is similar to this condition in `draw_col_buf()`:
```c
  while (ptr < text + len && wlv->off < wp->w_view_width) {
```

File: src/nvim/drawscreen.c (hunk 2 above)
Comment (zeertzjq) [reply src/nvim/drawscreen.c:2571]: Hmm OK.

File: src/nvim/drawscreen.c (hunk 1 above)
Comment (bfredl) [reply src/nvim/drawscreen.c]: I agree. it is just that this is already in the `grid_line_fill()` here, is it not?

Comment (zeertzjq) [reply src/nvim/drawscreen.c]: Yes, but `grid_line_fill()` uses `grid_line_maxcol`, which is equal to `grid->cols - col`, not `w_view_width` (which may be 1 smaller due to the right border).

Comment (zeertzjq) [reply src/nvim/drawscreen.c]: Thinking about this a bit more, since there is already a `n < wp->w_view_width` check in `win_draw_end()`, adding more `MIN(wp->w_width, ` there does make sense.

File: src/nvim/drawscreen.c (hunk 2 above)
Comment (zeertzjq) [reply src/nvim/drawscreen.c]: Since there is already a `n < wp->w_view_width` check below, adding more `MIN(wp->w_width,` above that does make sense.

**Review by bfredl — APPROVED** [review]
