### PR TITLE
fix(messages): ensure msg_grid is at top at more prompt

### LINKED ISSUE #23570: nvim crashes while showing messages by `:mes` the terminal height increases
### Problem

hi folks, i just happened to find out a reliable way to crash nvim :P

### Steps to reproduce

* in a tmux window
* `$ nvim --clean +'so test.lua'`
* `q` # to dissmiss the showed messages
* `tmux-cmd :split` # now we have `a-b` pane, and nvim runs in `a`
* go back to nvim
* `:mes`
* go to pane `b`, close it
* nvim likely crashes

```
-- test.lua
for i = 1, 100 do
  vim.notify("msg#" .. i)
end
```

### Expected behavior

on such situation, nvim will not crash

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

tmux-256color

### Installation

archlinux's community repo

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #23570

### CODE REVIEW

File: src/nvim/message.c [hunk 1]
```diff
@@ -181,7 +181,7 @@ void msg_grid_validate(void)
     msg_grid.dirty_col = xcalloc((size_t)Rows, sizeof(*msg_grid.dirty_col));
 
     // Tricky: allow resize while pager or ex mode is active
```
Comment (zeertzjq) [inline src/nvim/message.c:183]: I don't think resizing has ever worked properly in Ex mode.
