### PR TITLE
fix(extmark): fix conceal

### LINKED ISSUE #19007: conceal is broken in nvim_buf_set_extmark
### Neovim version (nvim -v)

v0.8.0-dev commit 502f03fc0

### Vim (not Nvim) behaves the same?

-

### Operating system/version

ubuntu 18.04

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

ppa

### How to reproduce the issue

Create a script and run it on itself with `:so%`:
```lua
-- foo
local ns = vim.api.nvim_create_namespace('TEST')
vim.opt_local.conceallevel = 2
vim.api.nvim_buf_set_extmark(0, ns, 0, 3, {
  end_row = 0, end_col = 6,
  hl_group = 'Identifier',
  conceal = '.',
})
```

Failing test case: https://github.com/ii14/neovim/commit/bee17c8f1f104c795d058f7b3ee2a87d1c0fed1a

### Expected behavior

`foo` on the first line should be concealed with `.`.

### Actual behavior

It's not.

### PR DESCRIPTION
**Pull request by ii14**
Closes #19007

### CODE REVIEW

File: test/functional/ui/decorations_spec.lua [hunk 1]
```diff
@@ -866,6 +866,36 @@ end]]
...
+      [1] = {background=Screen.colors.DarkGrey, foreground=Screen.colors.LightGrey};
+    }
+
+    ns = meths.create_namespace 'test'
+  end)
+
+  it('conceals', function()
+    insert([[
+foo
+]])
```
Comment (justinmk) [inline test/functional/ui/decorations_spec.lua:886]: for future reference: insert()..rawfeed() does `dedent()` so the string literal can be nicely indented. Also insert() takes a list of lines.

**Comment by clason** [comment]
Test now fails with
```
ERROR    test/functional/ui/decorations_spec.lua @ 883: extmark conceal conceals
test/functional/helpers.lua:106: end_row value outside range
```

File: test/functional/ui/decorations_spec.lua [hunk 2]
```diff
@@ -866,6 +866,34 @@ end]]
   end)
 end)
 
+describe('extmark conceal', function()
+  local screen, ns
+  before_each( function()
```
Comment (justinmk) [inline test/functional/ui/decorations_spec.lua]: Don't see a reason for a new describe() group nor this before_each. So I moved the test to the above group.
