### PR TITLE
fix(lua): assert failure with vim.regex() error inside :silent!

### LINKED ISSUE #20546: crash with vim.regex call in user command preview with invalid regex
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

/

### Operating system/version

openSUSE Tumbleweed on Windows 11

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

Zypper

### How to reproduce the issue

```lua
nvim --clean
:lua vim.api.nvim_create_user_command("Crash", function() end, {preview=function() pcall(vim.regex, "\\z") end})
:Crash
```

### Expected behavior

nothing, in this example.

### Actual behavior

nvim crashes as you type out :Crash
> nvim: /home/abuild/rpmbuild/BUILD/neovim-0.8.0/src/nvim/lua/stdlib.c:308: nlua_regex: Assertion `prog' failed.
>                                                                                                                [1]    11857 IOT instruction  nvim --clean

### PR DESCRIPTION
**Pull request by ruuzia**
Fix #20546

### CODE REVIEW

File: src/nvim/lua/stdlib.c [hunk 1]
```diff
@@ -305,7 +305,11 @@ int nlua_regex(lua_State *lstate)
     api_clear_error(&err);
     return lua_error(lstate);
   }
-  assert(prog);
+  else if (prog == NULL) {
+    nlua_push_errstr(lstate, "couldn't parse regex");
+    api_clear_error(&err);
```
Comment (zeertzjq) [inline src/nvim/lua/stdlib.c:310]: `api_clear_error(&err)` returns immdiately if `ERROR_SET(&err)` is `false`, so this line is not needed.
```suggestion
```

**Review by justinmk — APPROVED** [review]
