### PR TITLE
fix(api)!: empty non-nil autocmd "pattern", "event", `nvim_exec_autocmds()` docs

### LINKED ISSUE #37014: Empty autocommand patterns are handled strangely
### Problem

**1\.** As pointed out by a Matrix user, `nvim_create_autocmd` skips empty `pattern`s, and falls back to the default of `*` if all patterns are empty.

This works well for `nil`, but means:
 - `nil` acts like `{"*"}` (good) 
 - `{}` acts like `{"*"}` (ew)
 - `""` acts like `{"*"}` (ew)
 - `{"", ""}` acts like `{"*"}` (ew)
 -  `{"", "foo", "", "bar"}` acts like `{"foo", "bar"}` (oof; empty patterns are silently ignored)

---

**2\.** Empty comma-delimited patterns in `:autocmd` are parsed strangely. Also applies when using `nvim_create_autocmd` with a string `pattern` with commas.

Example:
```vim
:autocmd User foo,bar,,baz,bazzier,,,bazziest "
:autocmd User
```
Output:
```
--- Autocommands ---
User
    foo       "
    bar       "
    ,ba       "
    z         "
    bazzier   "
    ,,bazzie  "
    st        "
```

Vim parses these fine: (but silently skips the empty patterns)
```
--- Autocommands ---
User
    foo       "
    bar       "
    baz       "
    bazzier   "
    bazziest  "
```

Haven't looked into how long that's been broken for; maybe since `nvim_create_autocmd` was introduced? (it did have to refactor a lot of autocmd stuff...)

### Steps to reproduce

1. `nvim_create_autocmd` with an empty table or string `pattern`, or a table `pattern` containing empty strings.
2. Defining autocommands via `:autocmd` while using empty comma-delimited patterns.

### Expected behavior

1. Empty `pattern`s should probably raise an error. `nil` `pattern`s should continue to fall back to `*`.
2. Parse empty comma-delimited patterns correctly, like Vim. (maybe ignore them too for compatibility)

### Nvim version (nvim -v)

NVIM v0.12.0-dev-1850+g99e8b61376

### Vim (not Nvim) behaves the same?

No, 9.1.1997

### Operating system/version

Fedora 43

### Terminal name/version

ghostty 1.2.3, tmux 3.5a

### $TERM environment variable

tmux-256color

### Installation

Source

### PR DESCRIPTION
**Pull request by seandewar**
Problem: In autocmd APIs, a non-nil "pattern" containing only empty 'sub'-patterns is silently treated as nil, causing the fallback value to be unexpectedly used instead.

Solution: For `nvim_create_autocmd()`, raise a validation error (as no autocmds would be created).
For `nvim_{exec,clear}_autocmds()`, make it a no-op (as matching no autocmds is not an error).

Also fix `nvim_exec_autocmds()` docs describing its "pattern" default incorrectly. Add a test.

Fixes #37014. Technically breaking for anyone who (probably accidentally) relied on the old behaviour.
Originally I suggested making any empty 'sub'-pattern an error, but it feels too aggressive; `:autocmd` just skips those.

That said, not sure if a non-nil "pattern" with no non-empty 'sub'-patterns should be an error in all cases.
I've only made it so for `nvim_create_autocmd()` as described above. Thoughts?

### CODE REVIEW

File: test/functional/api/autocmd_spec.lua [hunk 1]
```diff
@@ -1053,6 +1088,21 @@ describe('autocmd api', function()
...
+
+      eq('', api.nvim_buf_get_name(0))
+      api.nvim_exec_autocmds({ 'BufReadPre', 'BufReadPost' }, {})
+      eq(23, api.nvim_get_var('autocmd_executed'))
+
+      api.nvim_buf_set_name(0, 'bar')
+      api.nvim_exec_autocmds({ 'BufReadPre', 'BufReadPost' }, {})
+      eq(34, api.nvim_get_var('autocmd_executed'))
+
+      -- Non-nil, fully-empty patterns execute nothing.
```
Comment (justinmk) [inline test/functional/api/autocmd_spec.lua:1116]: These test cases make it very clear, this definitely seems like an anti-feature.

**Comment by justinmk** [comment]
> not sure if a non-nil "pattern" with no non-empty 'sub'-patterns should be an error in all cases.
> I've only made it so for `nvim_create_autocmd()` as described above. Thoughts?

The other cases being `nvim_exec_autocmds` and `nvim_clear_autocmds` ? As a followup we could make those error also, and just wait for feedback on master.

For this PR we can start with only `nvim_create_autocmd`

**Review by justinmk — APPROVED** [review]

File: test/functional/api/autocmd_spec.lua (hunk 1 above)
Comment (seandewar) [reply test/functional/api/autocmd_spec.lua:1116]: The default fallback to fname? #19113 describes the motivation for the change, but #19115 forgot to update the docs.

**Comment by seandewar** [comment]
That's fine.

After thinking some more, I'm more undecided on whether it should be an error in all cases.
Likewise, for `event`s, `nvim_exec_autocmds({}, {})` is also a no-op, but `nvim_clear_autocmds({event={}})` clears for _all_ events (that might be another bug)... Sigh.

**Edit**: yeah, the `nvim_clear_autocmds()` thing is probably a bug. It even skips type checking on `event` entirely; `nvim_clear_autocmds({event=function() end})` is allowed and also treated like `nil`. I'll fix it... :rocket:

File: test/functional/api/autocmd_spec.lua (hunk 1 above)
Comment (justinmk) [reply test/functional/api/autocmd_spec.lua:1116]: I mean the "empty patterns execute nothing" seems like an anti-feature

Comment (seandewar) [reply test/functional/api/autocmd_spec.lua:1116]: I'd be happy to make it an error. Same could be extended to `event = {}` too for `nvim_exec_autocmds()` (currently a no-op), and `nvim_clear_autocmds()` (currently clears for all events, like `nil`; this PR also made it a no-op instead).

**Review by justinmk — APPROVED** [review]

File: test/functional/api/autocmd_spec.lua (hunk 1 above)
Comment (justinmk) [reply test/functional/api/autocmd_spec.lua:1116]: I'm definitely "undecided" also... so if we do that step in a separate PR, we can let the user feedback decide for us :)

Comment (seandewar) [reply test/functional/api/autocmd_spec.lua:1116]: Sounds good. I'll backport the doc fix and the type checking fix though (but leave 0.12's fallback behaviour alone). :+1:
