### PR TITLE
vim-patch:8.2.0845: text properties crossing lines not handled correctly

### LINKED ISSUE #5683: Textprops break apart when splitting line
Any attempts at, in insert mode or whatever, splitting a continuous text property over multiple lines actually creates new separate text properties, instead of extending the one that was already there. This complicates matters when text properties are used for semantic purposes, for example snippet plugins could want to track edits to placeholders.

To reproduce: With the following, where `#` represents one continuous text property which the cursor is inside

    Lorem ###|### ipsum

typing `<CR><CR><Up>...` produces

    Lorem ###
    ...|
    ### ipsum

where `...` is not in the text property that has been split into two separate ones. This is contrary to what one would expect - that insertions/edits confined to the interior of a textprop should remain inside.

split-textprop

Environment:
 - Vim version: 8.2.251
 - OS: Ubuntu 18.04
 - Terminal: tmux in Alacritty

### PR DESCRIPTION
**Pull request by janlazo**
Problem:    Text properties crossing lines not handled correctly.
Solution:   When joining lines merge text properties if possible.
            (Axel Forsman, closes vim/vim#5839, closes vim/vim#5683)

https://github.com/vim/vim/commit/87be9be1db6b6d8fb57ef14e05f23a84e5e8bea0

Port docs from patch v8.1.0688.
Rewrite docs for ml_replace_buf_len().

Co-authored-by: Bram Moolenaar <Bram@vim.org>

### CODE REVIEW

File: src/nvim/memline.c [hunk 1]
```diff
@@ -2492,6 +2492,11 @@ int ml_replace(linenr_T lnum, char *line, bool copy)
   return ml_replace_buf(curbuf, lnum, line, copy, false);
 }
 
+int ml_replace_len(linenr_T lnum, char *line, size_t len, bool copy)
+{
+  return ml_replace_buf_len(curbuf, lnum, line, len, copy, false);
```
Comment (janlazo) [inline src/nvim/memline.c:2500]: `len` isn't suppose to account for `NUL`. `ml_replace_buf_len()` assumes `line[len] == NUL` and `xmemdupz(line, len_arg)` follows that assumption.

File: src/nvim/ops.c [hunk 2]
```diff
@@ -4014,9 +4014,9 @@ int do_join(size_t count, bool insert_space, bool save_undo, bool use_formatopti
   colnr_T col = sumsize - currsize - spaces[count - 1];
 
   // allocate the space for the new line
-  char *newp = xmalloc((size_t)sumsize + 1);
+  size_t newp_len = (size_t)sumsize;
```
Comment (janlazo) [inline src/nvim/ops.c:4017]: Diverging from Vim here by delegating `NUL` to `xmallocz()`.

File: src/nvim/memline.c [hunk 3]
```diff
@@ -2492,6 +2492,11 @@ int ml_replace(linenr_T lnum, char *line, bool copy)
   return ml_replace_buf(curbuf, lnum, line, copy, false);
 }
 
+int ml_replace_len(linenr_T lnum, char *line, size_t len, bool copy)
```
Comment (janlazo) [inline src/nvim/memline.c:2498]:
```
src/proto/memline.pro:33:int ml_replace_len(linenr_T lnum, char_u *line_arg, colnr_T len_arg, int has_props, int copy);
```

`has_props` being bool complicates porting since it's N/A for Nvim.

File: src/nvim/memline.c (hunk 1 above)
Comment (janlazo) [reply src/nvim/memline.c:2500]: Documented

**Review by zeertzjq — APPROVED** [review]
