### PR TITLE
fix(pty): prevent orphan conhost.exe on Windows 10

### LINKED ISSUE #12974: calling vim.fn.jobstop on an id returned by vim.fn.termopen causes a memory leak
- `nvim --version`: NVIM v0.5.0-702-g569e75799
- Operating system/version: Windows 10 19041
- Terminal name/version: powershell / my own gui (issue seems unrelated)

### Steps to reproduce
The easiest way to reproduce is to install [Telescope](https://github.com/nvim-lua/telescope.nvim), then
- Open some file, ideally in a folder with many files
- Run `:lua require'telescope.builtin'.find_files{}`
- Enter normal mode and hold down `j` and `k` to scroll through the files fast

### Actual behaviour
Telescope opens a new preview window with `vim.fn.termopen` and runs `cat`, if another
preview is requested before the `cat` process returns, `vim.fn.jobstop` is called on the id
returned by the previous `termopen` call, this results in a memory leak.

On my Windows 10 machine this results in a ton of conhost.exe processes staying alive 
after the termopen instance should have finished.

### Expected behaviour
`vim.fn.jobstop` should terminate and cleanup the entire `vim.fn.termopen` instance.

Note: Simply removing the `vim.fn.jobstop` calls seems to work, even then I suppose
that calling `vim.fn.jobstop` should never cause a leak like this?

### LINKED ISSUE #21830: CI: orphan "tty-test" in Windows CI
### Problem

Lots of orphan processes mentioned in Windows CI logs. Could this lead to instability or slower performance on Windows CI?

```
2023-01-16T08:32:59.9048237Z Cleaning up orphan processes
2023-01-16T08:32:59.9329053Z Terminate orphan process: pid (5444) (conhost)
2023-01-16T08:32:59.9389448Z Terminate orphan process: pid (3396) (cmd)
2023-01-16T08:32:59.9461038Z Terminate orphan process: pid (4268) (nvim)
2023-01-16T08:32:59.9531511Z Terminate orphan process: pid (1000) (nvim)
2023-01-16T08:32:59.9601955Z Terminate orphan process: pid (1940) (cmd)
2023-01-16T08:32:59.9676026Z Terminate orphan process: pid (1264) (nvim)
2023-01-16T08:32:59.9746930Z Terminate orphan process: pid (2568) (nvim)
2023-01-16T08:32:59.9799045Z Terminate orphan process: pid (3308) (cmd)
2023-01-16T08:32:59.9891301Z Terminate orphan process: pid (2952) (nvim)
2023-01-16T08:32:59.9961147Z Terminate orphan process: pid (5160) (nvim)
2023-01-16T08:33:00.0018248Z Terminate orphan process: pid (5844) (conhost)
2023-01-16T08:33:00.0079660Z Terminate orphan process: pid (4160) (conhost)
2023-01-16T08:33:00.0132098Z Terminate orphan process: pid (5092) (shell-test)
2023-01-16T08:33:00.0193207Z Terminate orphan process: pid (5816) (conhost)
2023-01-16T08:33:00.0251301Z Terminate orphan process: pid (772) (conhost)
2023-01-16T08:33:00.0309612Z Terminate orphan process: pid (2232) (conhost)
2023-01-16T08:33:00.0381139Z Terminate orphan process: pid (5896) (conhost)
2023-01-16T08:33:00.0444286Z Terminate orphan process: pid (4616) (tty-test)
2023-01-16T08:33:00.0503963Z Terminate orphan process: pid (2860) (conhost)
2023-01-16T08:33:00.0565332Z Terminate orphan process: pid (5452) (tty-test)
2023-01-16T08:33:00.0642620Z Terminate orphan process: pid (3128) (conhost)
2023-01-16T08:33:00.0704388Z Terminate orphan process: pid (3332) (tty-test)
2023-01-16T08:33:00.0763978Z Terminate orphan process: pid (2996) (conhost)
2023-01-16T08:33:00.0824184Z Terminate orphan process: pid (5620) (tty-test)
2023-01-16T08:33:00.0883577Z Terminate orphan process: pid (4272) (conhost)
2023-01-16T08:33:00.1021372Z Terminate orphan process: pid (5296) (tty-test)
2023-01-16T08:33:00.1084560Z Terminate orphan process: pid (2076) (conhost)
2023-01-16T08:33:00.1147136Z Terminate orphan process: pid (4100) (tty-test)
2023-01-16T08:33:00.1267498Z Terminate orphan process: pid (760) (conhost)
2023-01-16T08:33:00.1330970Z Terminate orphan process: pid (4012) (tty-test)
2023-01-16T08:33:00.1392988Z Terminate orphan process: pid (5752) (conhost)
2023-01-16T08:33:00.1456033Z Terminate orphan process: pid (2452) (tty-test)
2023-01-16T08:33:00.1522869Z Terminate orphan process: pid (4184) (conhost)
2023-01-16T08:33:00.1731516Z Terminate orphan process: pid (628) (tty-test)
2023-01-16T08:33:00.1791333Z Terminate orphan process: pid (2792) (conhost)
2023-01-16T08:33:00.1851797Z Terminate orphan process: pid (4024) (tty-test)
2023-01-16T08:33:00.1911012Z Terminate orphan process: pid (1720) (conhost)
2023-01-16T08:33:00.1991583Z Terminate orphan process: pid (1088) (tty-test)
2023-01-16T08:33:00.2050288Z Terminate orphan process: pid (6148) (conhost)
2023-01-16T08:33:00.2109355Z Terminate orphan process: pid (6156) (tty-test)
2023-01-16T08:33:00.2168004Z Terminate orphan process: pid (6252) (conhost)
```

### Expected behavior

Explicitly terminate `tty-test` ? Normally we send SIGHUP when `:terminal` is closed, is that failing to kill children on Windows? 

Example test: https://github.com/neovim/neovim/blob/da267f3c2b8c5c688fc0f9f85e94ab35e670497d/test/functional/terminal/tui_spec.lua#L1356

### PR DESCRIPTION
**Pull request by ntdiary**
## Problem
On Windows 10, the ConPTY closing order is strict. Calling ClosePseudoConsole after closing the output stream can easily lead to accidental deadlocks, leaving orphan conhost.exe processes.
See https://learn.microsoft.com/en-us/windows/console/closepseudoconsole#remarks
and https://learn.microsoft.com/en-us/windows/console/creating-a-pseudoconsole-session#ending-the-pseudoconsole-session

## Solution
Based on the warning in the docs above, we need to call ClosePseudoConsole on a separate thread first so that the output pipe can fully drain on the main thread.
Also, `wait_eof_timer` is outdated, so I removed it to avoid extra cleanup logic around it (it was introduced in the early winpty days).

fix #36395, fix #21830, fix #12974

### CODE REVIEW

**Comment by ntdiary** [comment]
This PR still fixes #36395 on **Windows 10**, but I can't guarantee all existing terminal-related tests will pass there since quite a few were already failing anyway; to make things more reliable, I've set up a Windows Server 2025 VM so I can run the functional tests locally before pushing changes (same as CI OS version) 😂

**Comment by ntdiary** [comment]
For now, I haven't come up with a good way to test for ohphan processes. If anyone has good ideas, I'd be happy to try adding a new test. :D

File: src/nvim/os/pty_proc_win.c [hunk 1]
```diff
@@ -17,35 +17,35 @@
...
   Proc *proc = (Proc *)ptyproc;
-
-  assert(ptyproc->finish_wait != NULL);
-  return proc->out.s.closed || proc->out.did_eof || !uv_is_readable(proc->out.s.uvstream);
+  if (ptyproc->conpty == NULL) {
+    return;
+  }
+  // On Windows 11, closing a terminal immediately after opening it can leave orphan conhost
+  // and shell processes, e.g. `during TermClose event` case in autocmd_spec.lua
+  if (proc->out.num_bytes == 0) {
```
Comment (zeertzjq) [inline src/nvim/os/pty_proc_win.c:39]: This condition is strange. Why does the behavior of closing a console depend on whether it has written output?

Comment (ntdiary) [reply src/nvim/os/pty_proc_win.c:39]: Ah, I'm trying to catch where the terminal opens and closes immediately, but I haven't found a better way. Any ideas? :D

Comment (zeertzjq) [reply src/nvim/os/pty_proc_win.c:39]: Ah, I don't have any other ideas for now.

File: src/nvim/os/pty_proc_win.c [hunk 2]
```diff
@@ -17,35 +17,35 @@
...
+  PtyProc *ptyproc = data;
   Proc *proc = (Proc *)ptyproc;
-
-  assert(ptyproc->finish_wait != NULL);
-  return proc->out.s.closed || proc->out.did_eof || !uv_is_readable(proc->out.s.uvstream);
+  if (ptyproc->conpty == NULL) {
+    return;
+  }
+  // On Windows 11, closing a terminal immediately after opening it can leave orphan conhost
+  // and shell processes, e.g. `during TermClose event` case in autocmd_spec.lua
```
Comment (justinmk) [inline src/nvim/os/pty_proc_win.c:37]:
```suggestion
  // and shell processes, e.g. `during TermClose event` case in autocmd_spec.lua
  // Checking `num_bytes` is an attempt to detect that, until we find a better way.
```

File: src/nvim/event/rstream.c [hunk 3]
```diff
@@ -298,5 +298,8 @@ static void rstream_close_cb(Stream *s, void *data)
 
 void rstream_may_close(RStream *stream)
 {
+  if (stream->before_close) {
+    stream->before_close(stream->s.internal_data);
```
Comment (justinmk) [inline src/nvim/event/rstream.c]: should this be done in `stream_may_close` (or `stream_close_handle` ) ? otherwise it may be called even if the stream was already closed. Or is that intentional?

also might as well pass `stream->s` instead of only passing `stream->s.internal_data` , since that's more consistent?

File: src/nvim/event/defs.h [hunk 4]
```diff
@@ -116,6 +117,7 @@ struct rstream {
   uv_buf_t uvbuf;
   stream_read_cb read_cb;
   size_t num_bytes;
+  stream_before_close before_close;
```
Comment (justinmk) [inline src/nvim/event/defs.h]: should this be on `stream` rather than `rstream`? even if it's not needed for other kinds of streams yet, it's confusing to have all these special properties in random places.

also seems like the convention is to suffix with `_cb` so i guess let's keep that .

**Comment by justinmk** [comment]
In the Solution description can you mention that the timer was dropped (good!), and why a thread is preferred:

> Call ClosePseudoConsole on a separate thread firstly, so the main thread can flush the final frame. *Drop the old timer approach, which unlike a timer [has problem X...]*

**Comment by ntdiary** [comment]
@justinmk, haha, your comments are spot on! I was digging into this issue and encountered so many concepts that my mind was doing somersaults—I didn't even manage to put the changes in the best spot. :D

File: src/nvim/os/pty_proc_win.c [hunk 5]
```diff
@@ -143,6 +141,7 @@ int pty_proc_spawn(PtyProc *ptyproc)
     uv_run(&proc->loop->uv, UV_RUN_ONCE);
   }
 
+  proc->out.s.before_close_cb = pty_proc_close_console;
```
Comment (justinmk) [inline src/nvim/os/pty_proc_win.c:144]: One question is why can't the existing `close_cb` do this, i.e. why do we need `before_close_cb`? Probably I just need to trace the code to understand it.

**Comment by justinmk** [comment]
This is risky, but worth it because Windows support needs the attention. And the simplified code is nice.

Thank you!

File: src/nvim/os/pty_proc_win.c (hunk 5 above)
Comment (ntdiary) [reply src/nvim/os/pty_proc_win.c:144]: Because `close_cb` runs after the pipe has already been closed, but the `conhost` requires us to call `ClosePseudoConsole` before closing the pipe. This ensures the pipe can fully drain and prevent `conhost` from waiting indefinitely. Here are the relevant stack and code from `conhost`:
```c
0, ntdll.dll!NtWaitForSingleObject+0x14
1, KernelBase.dll!WaitForSingleObjectEx+0x8e
2, conhost.exe!Microsoft::Console::Render::Renderer::TriggerTeardown+0x2b
3, conhost.exe!Microsoft::Console::Interactivity::ServiceLocator::RundownAndExit+0x21
4, conhost.exe!Microsoft::Console::VirtualTerminal::VtIo::_ShutdownIfNeeded+0x2e
5, conhost.exe!Microsoft::Console::VirtualTerminal::VtIo::CloseOutput+0x67
6, conhost.exe!Microsoft::Console::Render::VtEngine::_Flush+0xa6
```
```c
// Method Description:
// - Called when the host is about to die, to give the renderer one last chance
//      to paint before the host exits.
// Arguments:
// - <none>
// Return Value:
// - <none>
void Renderer::TriggerTeardown()
{
    // We need to shut down the paint thread on teardown.
    _pThread->WaitForPaintCompletionAndDisable(INFINITE);
```

**Comment by ntdiary** [comment]
> This is risky, but worth it because Windows support needs the attention. And the simplified code is nice.
> 
> Thank you!

All my PRs come with 1-year warranty and 24/7 support — including any new regressions 😉
