### PR TITLE
fix(lsp): correctly parse LSP snippets

### LINKED ISSUE #15522: lsp: vim.lsp.util.parse_snippet can't parse snippet correctly
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

No.

### Operating system/version

MacOS 11.5

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

```
nvim -u NONE
:lua print(vim.lsp.util.parse_snippet('aiueo${0}'))
```

### Expected behavior

Print `aiueo`

### Actual behavior

Print `aiueo$`

### PR DESCRIPTION
**Pull request by hrsh7th**
This PR aims to support fully lsp style snippet syntax. (parsing only. doesn't contain evaluation).

Fixes #15522 

If this PR isn't acceptable, feel free to close it.

### CODE REVIEW

**Comment by clason** [comment]
@L3MON4D3 @leiserfg

File: test/functional/plugin/lsp_spec.lua [hunk 1]
```diff
@@ -1444,8 +1444,10 @@ describe('LSP', function()
         { label='foocar', sortText="h", insertText='foodar(${1:var1} typ1, ${2:var2} *typ2) {$0\\}', insertTextFormat=2, textEdit={} },
         -- nested snippet tokens
         { label='foocar', sortText="i", insertText='foodar(${1:var1 ${2|typ2,typ3|} ${3:tail}}) {$0\\}', insertTextFormat=2, textEdit={} },
+        -- braced tabstop
+        { label='foocar', sortText="j", insertText='foodar()${0}', insertTextFormat=2, textEdit={} },
```
Comment (hrsh7th) [inline test/functional/plugin/lsp_spec.lua:1448]: This test-case will fail in current master.

**Comment by mjlbach** [comment]
I think we should consider elevating this directly to vim.snippet. This solves a problem, in that our current snippet implementation is extremely limited. We could then enable full snippet support in our capabilities by default, which would save a lot of hassle.

There were questions about whether to bundle lpeg, or to use some treesitter based snippet parsing. I'm personally in favor of this solution, as it's been used in multiple snippets plugins and seems well tested, while avoiding any dependencies.

We should fix the test-case though.

cc @tjdevries who I just talked about this with.

**Comment by clason** [comment]
Just to be clear: even _if_ we go for a more complicated (faster? more robust?) implementation based on `lpeg` or `tree-sitter`, this should in no way block this in now as a bugfix for 0.5.x. The improvement would be a new feature for the 0.6 release (especially if it uses tree-sitter).

**Comment by tjdevries** [comment]
I'm not sure how much we want to nitpick different aspects of this right now, but I would like to see something like:

```lua
vim.lsp.snippet.types = {
  SNIPPET = 1,
  VARIABLE = 2,
  ...
}
```

instead of comparing directly to strings. We should make the API explicit for users. We can also use metatable to make sure that it's an error to access anything not in the table (don't remember if we do that anywhere else, but it's very easy to do).

**Comment by tjdevries** [comment]
Could also use top level doc string explaining the structure of nodes / expected usage (if that makes sense)

File: runtime/lua/vim/lsp/snippet.lua [hunk 2]
```diff
@@ -0,0 +1,406 @@
...
+        parsed = true,
+        value = map(result.value),
+        pos = result.pos,
+      }
+    end
+    return P.unmatch(pos)
+  end
+end
+
+P.lazy = function(factory)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/snippet.lua:73]: looks like a lot of functional-style utilities are here. Consider moving them to a new module `runtime/lua/vim/fun.lua`.

( https://github.com/neovim/neovim/pull/12655 introduced `F.lua` but I do not think we should augment it, instead we should deprecate it because it does not follow the module naming convention of any of our other modules.)

File: runtime/lua/vim/lsp/snippet.lua [hunk 3]
```diff
@@ -0,0 +1,406 @@
...
+    }
+  end)
+end
+
+S.toplevel = P.lazy(function()
+  return P.any(S.placeholder, S.tabstop, S.variable, S.choice)
+end)
+
+S.format = P.any(
+  P.map(P.seq(S.dollar, S.int), function(values)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/snippet.lua:207]: Does it make sense to use LPEG or treesitter instead of a new DSL?

We use LPEG in some legacy code:

- https://github.com/neovim/neovim/blob/687a0b3d3e8878b6de058b02d84fbd1f78aa2e89/src/nvim/generators/gen_declarations.lua
- https://github.com/neovim/neovim/blob/687a0b3d3e8878b6de058b02d84fbd1f78aa2e89/src/nvim/generators/c_grammar.lua

Comment (clason) [reply runtime/lua/vim/lsp/snippet.lua:207]: See my comment above (TL;DR yes (ideally tree-sitter), but we should fix this now before we worry about a better implementation.)

More important is to get an API/format that snippet engines can rely on.

Comment (clason) [reply runtime/lua/vim/lsp/snippet.lua:207]: (and for the sake of completeness: right now `lpeg` is a build dependency but not a runtime dependency; unless you build from source yourself, it's not bundled.)

File: runtime/lua/vim/lsp/snippet.lua (hunk 2 above)
Comment (leiserfg) [reply runtime/lua/vim/lsp/snippet.lua:73]: Those are not high-order functions but high-order parsers so I guess they should not go in `fun.lua`  this is more like a simple `lpeg`.

Comment (clason) [reply runtime/lua/vim/lsp/snippet.lua:73]: (still agree about the `F.lua` -- that is too arcane ;)

Comment (mjlbach) [reply runtime/lua/vim/lsp/snippet.lua:73]: I think we should keep the parsers in the current file, because if we replace with lpeg as part of a `vim.snippet` those might be dead code anyways

File: runtime/lua/vim/lsp/snippet.lua (hunk 3 above)
Comment (leiserfg) [reply runtime/lua/vim/lsp/snippet.lua:207]: Another option could be to "vendorize" LPegLJ (or LuLPeg) so there is no need for including more distribution time dependencies.

**Comment by mjlbach** [comment]
TJ mentioned also possibly renaming the file to `_snippets.lua` as the underscore emphasizes this is for internal use only (for now)

File: runtime/lua/vim/lsp/snippet.lua (hunk 3 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp/snippet.lua:207]: > Another option could be to "vendorize" LPegLJ (or LuLPeg) 

If we're not modifying the source I'm not sure we should do this as it will anger the Debian gods

**Comment by leiserfg** [comment]
> TJ mentioned also possibly renaming the file to `_snippets.lua` as the underscore emphasizes this is for internal use only (for now)

I guess snippets. is fine as far as only `parse()` and constructors (properly specified) of each type of node is exposed, as those are the API, the rest (tree-sitter, lpeg or by hand) are just implementation details and should be hidden.

File: runtime/lua/vim/lsp/snippet.lua (hunk 3 above)
Comment (hrsh7th) [reply runtime/lua/vim/lsp/snippet.lua:207]: Yes. I thought we should use lpeg for it.
But at this point, I'm not thinking so now. because lpeg is not bundled now and lpeg might be only used as a "snippet" in the functionality provided to the user.

File: runtime/lua/vim/lsp/snippet.lua [hunk 4]
```diff
@@ -0,0 +1,406 @@
...
+  })
+
+  local to_string
+  to_string = function(node_)
+    local insert_text = {}
+    if node_.type == 'snippet' then
+      for _, c in ipairs(node_.children) do
+        table.insert(insert_text, to_string(c))
+      end
+    elseif node_.type == 'variable' then
```
Comment (mjlbach) [inline runtime/lua/vim/lsp/snippet.lua:384]: Can you pull node types out into an enum and validate against it instead of matching on strings? Thanks!

Comment (hrsh7th) [reply runtime/lua/vim/lsp/snippet.lua]: I've added the `require('vim.lsp._snippet').NodeType` constants. (I'm refering `vim.lsp.protocol` to implement it

**Review by mjlbach — APPROVED** [review]

**Comment by hrsh7th** [comment]
Currently, I exposed only `vim.lsp.util.parse_snippet`. Other structures are still private things. We can modify it later.

**Comment by hrsh7th** [comment]
I'm facing the error `vim.lsp._snippet` can't found...

Probably, neovim does not ships the filename starting `_` as built artifacts.

**Comment by hrsh7th** [comment]
I'm investigating it...

**Comment by hrsh7th** [comment]
Sorry. It has no problem after running the`make distclean && make clean && make CMAKE_BUILD_TYPE=Release && make install`.

**Comment by mjlbach** [comment]
nw! currently working through your other PR, I think @justinmk or @tjdevries might want to also sign off on this but I'm good with merging. Thanks for the contribution!

**Comment by hrsh7th** [comment]
Other complex snippet was tested manually on my local.

Yes. I think it should be tested. May I create the test on `test/functional/plugin/lsp/snippet_spec.lua`?

**Comment by mjlbach** [comment]
>  May I create the test on test/functional/plugin/lsp/snippet_spec.lua?

Yes

File: runtime/lua/vim/lsp/_snippet.lua [hunk 5]
```diff
@@ -0,0 +1,421 @@
...
+  return result.value
+end
+
+---Convert snippet nodes to string.
+---@param node table The result of M.parse
+---@param opts table|nil
+---  - with_placeholder boolean
+---  - resolve_variable fun(name: string): string
+---@return string
+M.to_string = function(node, opts)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/_snippet.lua:384]: why introduce this idiosyncratic to_string function instead of overriding `__tostring` ? https://stackoverflow.com/a/35327975/152142

Comment (justinmk) [reply runtime/lua/vim/lsp/_snippet.lua:384]: how does that conflict with my suggestion?

Comment (leiserfg) [reply runtime/lua/vim/lsp/_snippet.lua:384]: You are right, inspect, does not trigger   `__tostring`, so it's safe to use it there.

Comment (hrsh7th) [reply runtime/lua/vim/lsp/_snippet.lua:384]: If I implement `__tostring`, is it for each node?

Anyway, I will push the `__tostring` version.

File: runtime/lua/vim/lsp/_snippet.lua [hunk 6]
```diff
@@ -0,0 +1,421 @@
...
+local M = {}
+
+---@types table<string, number>
+---The snippet node type enum
+M.NodeType = NodeType
+
+---Parse snippet string and returns the AST
+---@param input string
+---@return table
+M.parse = function(input)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/_snippet.lua:370]: is there a reason not to use the `function M.parse(input)` form? that is the convention in most of the codebase.

Comment (hrsh7th) [reply runtime/lua/vim/lsp/_snippet.lua:370]: It has no reason. I will change it!

File: runtime/lua/vim/lsp/_snippet.lua (hunk 5 above)
Comment (justinmk) [reply runtime/lua/vim/lsp/_snippet.lua:384]: > If I implement `__tostring`, is it for each node?

isn't `parse()` already return some sort of custom object?

Comment (hrsh7th) [reply runtime/lua/vim/lsp/_snippet.lua:384]: I think `M.__tostring` is confusing because the function does not stringify `M` itself.

Comment (leiserfg) [reply runtime/lua/vim/lsp/_snippet.lua:384]: No, you have to make a table like `{__tostring =  function ....}`  and then make that table the metatable of each node.

Comment (hrsh7th) [reply runtime/lua/vim/lsp/_snippet.lua]: I've pushed the `__tostring` version. What do you think about it?
If I misunderstood it, I will revert (remove by force-push) it.

Comment (hrsh7th) [reply runtime/lua/vim/lsp/_snippet.lua]: In my personal opinion, I like the `M.to_string` way because it allows customizing the format via the arguments in the future.

Comment (justinmk) [reply runtime/lua/vim/lsp/_snippet.lua]: > I've pushed the `__tostring` version. What do you think about it?

at a glance, looks good!



> In my personal opinion, I like the `M.to_string` way because it allows customizing the format via the arguments in the future.

we could introduce `fmt()` as a convention.

**Review by justinmk — APPROVED** [review]

File: runtime/lua/vim/lsp/_snippet.lua (hunk 5 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp/_snippet.lua]: @justinmk did you want to move to the fmt convention before merging this, or are we ok to merge as is?

File: runtime/lua/vim/lsp/_snippet.lua (hunk 6 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp/_snippet.lua:391]: I think this is the other holdup, after this and the other comment is addressed regarding adding a fmt convention I am good to merge :)

File: runtime/lua/vim/lsp/_snippet.lua (hunk 5 above)
Comment (justinmk) [reply runtime/lua/vim/lsp/_snippet.lua]: > @justinmk did you want to move to the fmt convention before merging this, or are we ok to merge as is?

i'd say wait until we need it. `__tostring()` seems like it should be the first instinct.

Comment (mjlbach) [reply runtime/lua/vim/lsp/_snippet.lua]: Ok, cool, so I think the only blocking issue is the function style https://github.com/neovim/neovim/pull/15579#discussion_r704533106?

**Comment by hrsh7th** [comment]
I will add tests. Thank you for all teviews!

**Comment by hrsh7th** [comment]
I've fixed the reviews. I will self-check it a bit.

**Comment by hrsh7th** [comment]
I think it's ready to re-review now.

**Comment by clason** [comment]
Sorry for revisiting this so late, but just to make this explicit since the discussion earlier did not end with a definite decision: Is it necessary to add the additional redirection from `vim.lsp._snippet.parse` to `vim.lsp.util.parse_snippet`? Wouldn't it be simpler to just use `vim.lsp.snippet.parse` (which is exported anyway; all other functions are internal and not exported) and `require` it only where it's needed?

Or is that for API compatibility?

**Comment by hrsh7th** [comment]
In this PR, I didn't modify the public exposed interfaces and didn't expose new APIs.

We have to discuss the AST signature if we expose `vim.lsp.snippet.parse`, I think.

**Comment by clason** [comment]
Makes sense; let's keep this `fix(lsp): correctly parse LSP snippets` and open a new issue/PR about turning this into a proper API for snippet engines.

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
Does this need a documentation update?

**Comment by hrsh7th** [comment]
I think this doesn't need the documentation change. (because this PR only changes the internal implementations.)

**Comment by hrsh7th** [comment]
Thank you for merge!

**Comment by leiserfg** [comment]
Looking forward to the PR for the AST.

**Comment by clason** [comment]
@leiserfg Would you mind open an issue about it (including your thoughts about the API that LuaSnip would like)?

**Comment by leiserfg** [comment]
I'll ping @L3MON4D3  to have more opinions in that regard.
