### PR TITLE
fix(api): on_detach consistently before buf_freeall autocmds

### LINKED ISSUE #28084: When using nvim_win_close, it prints Vim:E315: ml_get: invalid lnum: 1
### Problem

I want to use `vim.api.nvim_win_close` to close window in other tabpage.
It closed window but print many error messages `Vim:E315: ml_get: invalid lnum: 1` from treesitter callback.

```
E5108: Error executing lua [string ":lua"]:1: Vim:Error executing lua callback: ....4/share/nvim/runtime/lua/vim/treesitter/highlighter
.lua:148: Vim:Error executing lua callback: Vim:E315: ml_get: invalid lnum: 1
stack traceback:
        [C]: in function 'bufload'
        vim/_editor.lua: in function 'region'
        ...ar/neovim/0.9.4/share/nvim/runtime/lua/vim/highlight.lua:35: in function 'range'
        ...re/nvim/plugins/nvim-ts-rainbow/lua/rainbow/internal.lua:82: in function 'update_range'
        ...re/nvim/plugins/nvim-ts-rainbow/lua/rainbow/internal.lua:186: in function 'cb'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:746: in function '_do_callback'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:180: in function 'invalidate'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:898: in function '_on_detach'
        ...r/neovim/0.9.4/share/nvim/runtime/lua/vim/treesitter.lua:73: in function <...r/neovim/0.9.4/share/nvim/runtime/lua/vim/trees
itter.lua:69>
        [C]: in function 'nvim_win_close'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function '__newindex'
        ....4/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:148: in function 'destroy'
        ....4/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:184: in function 'on_detach'
        ....4/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:83: in function 'cb'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:746: in function '_do_callback'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:899: in function '_on_detach'
        ...r/neovim/0.9.4/share/nvim/runtime/lua/vim/treesitter.lua:73: in function <...r/neovim/0.9.4/share/nvim/runtime/lua/vim/trees
itter.lua:69>
        [C]: in function 'nvim_win_close'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'nvim_win_close'
        [string ":lua"]:1: in main chunk
```

### Steps to reproduce

1. Use nvim to open two files whose content highlighted by treesitter on two tabpages. Each tabpage contains one window.
2. `:lua print(vim.api.nvim_get_current_win())` get current window number. For example, it prints `1000`.
3. Switch to another tabpage.
4. `:lua vim.api.nvim_win_close(1000, false)` to close the previous window. It closed window but print many error messages.

Note:
1. Empty file content will not print error.
2. Close current window in same tabpage will not print error.
3. Using `vim.api.nvim_buf_delete` has same issue with `nvim_win_close`.

### Expected behavior

Just close the window without any error.

### Neovim version (nvim -v)

NVIM v0.9.4

### Vim (not Nvim) behaves the same?

not sure

### Operating system/version

macOS 14.1.2 (23B2091)

### Terminal name/version

iTerm2 3.5.0beta17

### $TERM environment variable

xterm-256color

### Installation

homebrew

### LINKED ISSUE #33967: Internal error E38 when redrawing window to unloaded buffer via `on_detach`
### Problem

Internal error `E38: Null argument` (and maybe other weirdness) is possible under specific conditions if `nvim_buf_attach`'s `on_detach` callback redraws a window to an unloaded buffer while hlsearch is active.

### Steps to reproduce

```lua
vim.cmd "new | silent! /."
vim.bo.bufhidden = "delete"
vim.api.nvim_buf_attach(0, false, {
  on_detach = function()
    -- Buffer's ml is gone (buf_freeall called), but it's still in a window.
    -- Maybe "on_detach" should have been called before that point...
    assert(vim.fn.bufloaded(vim.api.nvim_get_current_buf()) == 0)

    -- This changes the topline from 0 to 1, which is technically outside
    -- of the buffer when we get to win_update. That dubiously causes it to
    -- attempt to draw a win_line when we redraw.
    vim.fn.winrestview(vim.empty_dict())
    vim.cmd "redraw!"
  end,
})
vim.cmd "quit!"
```

### Expected behavior

No error.

It's a bit dubious that `on_detach` is called inside an unloaded buffer, especially when it's still in a window. (At least it's textlocked 😌)

That said, `nvim_buf_call` can be used to do the same (except the unloaded buffer is shown in the autocmd window); a bit sus, but I couldn't replicate the same issue via that route.

### Nvim version (nvim -v)

0.12.0-dev-347+gbee45fc0e7

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

Source

### LINKED ISSUE #35116: regression: statusline of p causes zero division
### Problem

Zero division occurs at  
https://github.com/neovim/neovim/blob/b79ff967ac91dce40f3598ea407c5ccaa2929250/src/nvim/statusline.c#L1471-L1473

This bisects to b79ff967ac91dce40f3598ea407c5ccaa2929250 (#33723).

### Steps to reproduce

Prepare init.lua

```lua
-- min.lua
for name, url in pairs({
  "https://github.com/neovim/nvim-lspconfig",
}) do
  local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
  end
  vim.opt.runtimepath:append(install_path)
end

vim.lsp.enable("clangd")
vim.o.statusline = '%p'  -- XXX
```

and a C file named a.c:

```c
#include <stdio.h>
```

1. `nvim -u min.lua a.c`
2. ~`Ctrl-]` → now opens `/usr/include/stdio.h`~ not necessary
3. `:bw` → SIGFPE

```gdb
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x0000555fa4c8876d in build_stl_str_hl (wp=0x555fe2e1c860, out=0x7ffdc9f84860 "\327\270", outlen=4096, fmt=0x555fe2e30050 "%p",
    opt_idx=kOptStatusline, opt_scope=0, fillchar=32, maxwidth=136, hltab=0x7ffdc9f84818, hltab_len=0x0, tabtab=0x7ffdc9f84820,
    stcp=0x0) at neovim/src/nvim/statusline.c:1472
1472          num = ((wp->w_cursor.lnum * 100) / wp->w_buffer->b_ml.ml_line_count);
(gdb) print wp->w_buffer->b_ml.ml_line_count
$1 = 0
```

### Expected behavior

No crash.

### Nvim version (nvim -v)

v0.12.0-dev-b79ff96

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

EndeavourOS

### Terminal name/version

ghostty 1.1.3

### $TERM environment variable

xterm-ghostty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by seandewar**
Problem: on_detach may be called after buf_freeall and other important
things, plus its textlock restrictions are insufficient. This can cause issues
such as leaks, internal errors and crashes.

Solution: disable buffer updates in buf_freeall, before autocommands (like the
order after #35355 and when do_ecmd reloads a buffer). Don't do so in
free_buffer_stuff; it's not safe to run user code there, and buf_freeall already
runs before then; just free them to avoid leaks if buf_freeall autocommands
registered more for some reason.

Fixes #28084
Fixes #33967
Fixes #35116

### CODE REVIEW

File: src/nvim/buffer.c [hunk 1]
```diff
@@ -788,6 +784,12 @@ void buf_freeall(buf_T *buf, int flags)
   bufref_T bufref;
   set_bufref(&bufref, buf);
 
+  // Disable buffer-updates for the current buffer.
+  buf_updates_unload(buf, false);
+  if (!bufref_valid(&bufref)) {
+    // on_detach callback deleted the buffer.
+    return;
+  }
```
Comment (seandewar) [inline src/nvim/buffer.c]: `on_detach` has textlock set, and like the autocmds below has `b_locked` set here too. Makes it pretty hard to delete the buffer, but it might still be possible; it's at least consistent with below to include the check.

File: test/functional/lua/buffer_updates_spec.lua [hunk 2]
```diff
@@ -1428,42 +1430,138 @@ describe('lua: nvim_buf_attach on_bytes', function()
 end)
 
 describe('nvim_buf_attach on_detach', function()
-  it('is invoked before unloading buffer', function()
```
Comment (seandewar) [inline test/functional/lua/buffer_updates_spec.lua:1431]: My test supersedes this one, so I've removed it (but kept the case when wiping the last listed non-reusable buffer)

File: test/functional/lua/buffer_updates_spec.lua [hunk 3]
```diff
@@ -1428,42 +1430,138 @@ describe('lua: nvim_buf_attach on_bytes', function()
...
+        end,
+      })
+    end)
+    matches('E1159: Cannot split a window when closing the buffer$', pcall_err(command, 'quit!'))
+    eq({}, fn.win_findbuf(buf))
+    eq(false, api.nvim_buf_is_valid(buf))
+  end)
+end)
+
+it('nvim_buf_attach from buf_freeall autocommands does not leak', function()
```
Comment (justinmk) [inline test/functional/lua/buffer_updates_spec.lua:1553]: nit: does this fit in one of the existing describe() blocks ?

**Review by justinmk — APPROVED** [review]

File: test/functional/lua/buffer_updates_spec.lua (hunk 3 above)
Comment (seandewar) [reply test/functional/lua/buffer_updates_spec.lua:1553]: Describes seem to relate to specific callbacks, but this doesn't require any of 'em.
