### PR TITLE
fix(term): ensure terminal attr index doesn't exceed `TERM_ATTRS_MAX`

### LINKED ISSUE #30374: Out of bounds memory access in large `:term` sessions.
### Problem

If you use the neovim terminal and zoom the terminal out too far. Then when you run a command with a large horizontal output, you will get a SIGSEGV (out of bounds memory access).

I'm gonna take a stab at diving into this issue to see if I can fix it this weekend but I wanted to report it too.

### Steps to reproduce

```
nvim --clean
:term
# Zoom all the way out in alacritty with ctrl&- (Any terminal with far enough zoomout)

# In any posix-ish compliant shell (You just need to generate long enough horizontal lines)
for i in $(seq 1 10000); do echo -n $i; done
# This reliably causes a SIGSEGV (out of bounds memory access) independent of shell.
```

### Expected behavior

I would expect nvim to not segfault (even just killing the term instead of all of nvim would be better).

Also, this may seem like a niche edge case, but I frequently do this when logging buffers while debugging. 

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1723675123

### Vim (not Nvim) behaves the same?

no, 9.1.707 (It seems like vim just limits term size)

### Operating system/version

Arch Linux

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

pacman (release version)

### PR DESCRIPTION
**Pull request by The-Briel-Deal**
Problem: Currently terminal highlight attribute buffers are statically allocated
be the size of `TERM_ATTRS_MAX`. This unique case isn't respected in
some places in the ui_compositor. Due to this, when a terminal window
has lines longer them `TERM_ATTRS_MAX`, the compositor will go past the
end of the buffer causing a crash due to out of bounds access.

Solution: Add check to ensure we don't query terminal highlight attrs
past `TERM_ATTRS_MAX` in `win_line()`.

Fixes https://github.com/neovim/neovim/issues/30374

### CODE REVIEW

File: src/nvim/ui_compositor.c [hunk 1]
```diff
@@ -9,6 +9,7 @@
 #include <stdbool.h>
 #include <stdlib.h>
 #include <string.h>
+#include <sys/param.h>
```
Comment (zeertzjq) [inline src/nvim/ui_compositor.c]: ?

Comment (The-Briel-Deal) [reply src/nvim/ui_compositor.c]: Sorry about that! I just dropped it, that was from lsp auto-include.

File: src/nvim/ui_compositor.c [hunk 2]
```diff
@@ -591,11 +591,15 @@ void ui_comp_raw_line(Integer grid, Integer row, Integer startcol, Integer endco
     compose_debug(row, row + 1, startcol, endcol, dbghl_normal, endcol >= clearcol);
     compose_debug(row, row + 1, endcol, clearcol, dbghl_clear, true);
 #ifndef NDEBUG
-    for (int i = 0; i < endcol - startcol; i++) {
+    Integer cols = endcol - startcol;
+    if (max_attrs != 0) {
+      cols = MIN(cols, max_attrs - 1);
+    }
```
Comment (justinmk) [inline src/nvim/ui_compositor.c:597]:
```suggestion
    Integer cols = max_attrs == 0 ? endcol - startcol : MIN(cols, max_attrs - 1);
```

File: src/nvim/grid.h [hunk 3]
```diff
@@ -30,9 +30,12 @@ EXTERN char *linebuf_scratch INIT( = NULL);
...
 enum {
-  SLF_RIGHTLEFT = 1,
-  SLF_WRAP      = 2,
-  SLF_INC_VCOL  = 4,
+  SLF_RIGHTLEFT   = 1,
+  SLF_WRAP        = 2,
+  SLF_INC_VCOL    = 4,
+  SLF_TERM_ATTRS  = 8,  // On if this line is associated with a terminal buffer. If so then we need
+                        // to ensure we don't go past index `TERM_ATTRS_MAX` in the highlight
+                        // attributes.
```
Comment (justinmk) [inline src/nvim/grid.h]:
```suggestion
  SLF_TERMATTRS  = 8,  // Indicates the line is in a terminal buffer, so we must not exceed
                       // index `TERM_ATTRS_MAX` in the highlight attributes.
```

File: src/nvim/ui_compositor.c [hunk 4]
```diff
@@ -591,11 +591,15 @@ void ui_comp_raw_line(Integer grid, Integer row, Integer startcol, Integer endco
     compose_debug(row, row + 1, startcol, endcol, dbghl_normal, endcol >= clearcol);
     compose_debug(row, row + 1, endcol, clearcol, dbghl_clear, true);
 #ifndef NDEBUG
-    for (int i = 0; i < endcol - startcol; i++) {
+    Integer cols = endcol - startcol;
+    if (max_attrs != 0) {
+      cols = MIN(cols, max_attrs - 1);
```
Comment (justinmk) [inline src/nvim/ui_compositor.c]: Is this the only place where `max_attrs` is used? This code is only for debugging (`#ifndef NDEBUG`).

And even if it wasn't, adding a parameter in many places, and setting a special `SLF_TERM_ATTRS` flag per-line, does not seem like the right fix.

**Comment by justinmk** [comment]
> This will be set to `TERM_ATTRS_MAX` for terminals, and 0 if there is no limit.

There is always a limit, but it might be much bigger for the non-terminal case.

Wondering if there is a different way for this limit to be signaled to the UI, instead of passing it around everywhere (which is pretty redundant, and rather spread-out).

File: src/nvim/ui_compositor.c (hunk 4 above)
Comment (The-Briel-Deal) [reply src/nvim/ui_compositor.c]: So you are right, one option is to drop the assert, that would make it so I don't have to pass the max_attrs down. Another option is to find a better way to identify if this line belongs to a window on a terminal buffer. 

The final option which in my mind is ideal is to handle terminal highlight attrs the same way we handle highlight attrs in other buffers so that we don't have this special case. I believe (I would have to look into this deeper) that for other buffers, there will always be the same number of columns as highlight attrs for a line.

I couldn't figure out why the terminal is the one buffer type where we can have less highlight attrs the columns. I would honestly prefer to just limit the amount of columns and highlight attrs for terminals to 1024 rather than just highlight attrs. Ideally the ui compositor doesn't have to worry about this special case at all.

Do you have any thoughts on what solution of those you would prefer? Because I agree that I really don't like adding args an flags to all these functions just because of terminals being this one special case.

Comment (justinmk) [reply src/nvim/ui_compositor.c]: > I believe (I would have to look into this deeper) that for other buffers, there will always be the same number of columns as highlight attrs for a line.
> 
> ...
>
> I couldn't figure out why the terminal is the one buffer type where we can have less highlight attrs the columns.

@bfredl may have insight to both of those.



> The final option which in my mind is ideal is to handle terminal highlight attrs the same way we handle highlight attrs in other buffers so that we don't have this special case

ideally yes, though I may be missing something.

**Comment by The-Briel-Deal** [comment]
> > This will be set to `TERM_ATTRS_MAX` for terminals, and 0 if there is no limit.
> 
> There is always a limit, but it might be much bigger for the non-terminal case.
> 
> Wondering if there is a different way for this limit to be signaled to the UI, instead of passing it around everywhere (which is pretty redundant, and rather spread-out).

I totally agree, i'm just not familiar enough with the codebase to know how else I can pass that info to the UI. Maybe a buffer local var?

File: src/nvim/grid.h (hunk 3 above)
Comment (The-Briel-Deal) [reply src/nvim/grid.h]: Ack, i'll apply this once I'm off work later today.

**Comment by justinmk** [comment]
> Maybe a buffer local var?

no. this is too much complication just for an assert(). need to think about this differently, not by storing more state or flags somewhere.

File: src/nvim/ui_compositor.c (hunk 4 above)
Comment (The-Briel-Deal) [reply src/nvim/ui_compositor.c]: Let me look into just changing the terminal to mirror the behavior of highlight attrs on other buffers. @bfredl if you have any insight into why terminals have a cap on the number of highlight attrs while other buffers don't that would be super helpful.

Thanks for the feedback Justin! I had the same feeling about the amount of code I had to add for this small check. I'm going to make this CL draft for now until I can figure out a better solution.

File: src/nvim/drawline.c [hunk 5]
```diff
@@ -2265,7 +2265,7 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, int col_rows, b
         }
 
         if (wp->w_buffer->terminal) {
-          wlv.char_attr = hl_combine_attr(term_attrs[wlv.vcol], wlv.char_attr);
+          wlv.char_attr = hl_combine_attr(TERM_ATTRS_MAX > wlv.vcol ? term_attrs[wlv.vcol] : 0, wlv.char_attr);
```
Comment (zeertzjq) [inline src/nvim/drawline.c]: This is a bit hard to read
```suggestion
          wlv.char_attr = hl_combine_attr(wlv.vcol < TERM_ATTRS_MAX ? term_attrs[wlv.vcol] : 0, wlv.char_attr);
```

**Comment by The-Briel-Deal** [comment]
Hey @justinmk, I was able to dramatically simplify this. I had a fundamental misunderstanding of what was causing the assert to fail. I thought that the assert below was accessing the static `term_attrs[1024]` buffer directly but after looking deeper the `attrs` the assert was failing on in the ui_compositor is just derived from the static buffer. So if I just make sure we don't access garbage memory beyond that buffer the assert won't fail.

```
    for (int i = 0; i < endcol - startcol; i++) {
      assert(attrs[i] >= 0);
    }
```

File: src/nvim/drawline.c (hunk 5 above)
Comment (The-Briel-Deal) [reply src/nvim/drawline.c]: Thats fair, i'll fix that

File: test/functional/terminal/highlight_spec.lua [hunk 6]
```diff
@@ -408,3 +409,23 @@ describe(':terminal', function()
     ]])
   end)
 end)
+
+describe(':terminal max highlight attrs', function()
+  it('does not cause crash on zoomout with large horizontal output #30374', function()
```
Comment (justinmk) [inline test/functional/terminal/highlight_spec.lua]: can this just be an it() in one of the existing describe() blocks, why do we need a new describe()

**Review by justinmk — APPROVED** [review]
nice, thanks!

File: test/functional/terminal/highlight_spec.lua (hunk 6 above)
Comment (The-Briel-Deal) [reply test/functional/terminal/highlight_spec.lua]: We don't! I'll drop that!

File: test/functional/terminal/highlight_spec.lua [hunk 7]
```diff
@@ -408,3 +409,21 @@ describe(':terminal', function()
     ]])
   end)
 end)
+
+it(':terminal does not cause crash on zoomout with large horizontal output #30374', function()
```
Comment (justinmk) [inline test/functional/terminal/highlight_spec.lua]: this should be in one of the existing describe() blocks : https://github.com/neovim/neovim/blob/4ee2e365a583e26468e7ea820f5416a980515504/test/functional/terminal/highlight_spec.lua#L392

Comment (justinmk) [inline test/functional/terminal/highlight_spec.lua]:
```suggestion
it('zoomout with large horizontal output #30374', function()
```

File: test/functional/terminal/highlight_spec.lua [hunk 8]
```diff
@@ -408,3 +409,21 @@ describe(':terminal', function()
...
+  skip(is_os('win'))
+
+  clear()
```
Comment (justinmk) [inline test/functional/terminal/highlight_spec.lua]: drop this after moving to the existing describe() block as mentioned

File: test/functional/terminal/highlight_spec.lua (hunk 7 above)
Comment (The-Briel-Deal) [reply test/functional/terminal/highlight_spec.lua]: Done! Ty

**Comment by The-Briel-Deal** [comment]
Thank you @justinmk! I misread your comment about moving to an existing describe block. All comments should be addressed now!
