### PR TITLE
fix(lsp): fix workspace diagnostic request to follow spec

### LINKED ISSUE #34673: LSP:  workspace diagnostic request body does not follow spec
### Problem

For the newly added `vim.lsp.buf.workspace_diagnostics()` feature, the previousResultIds in the request to workspace/diagnostic does not follow the spec which causes errors in some lsps. 
Currently previousResultIds will look like 
```
{
   textDocument : {uri: xxx},
   previousResultId : xxx
}
```
Where as it should be
```
{
   uri: xxx
   value: xx
}
```
as described in the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#previousResultId) 

### Steps to reproduce using "nvim -u minimal_init.lua"

run vim.lsp.buf.workspace_diagnostics()

### Expected behavior

previousResultIds to follow spec when making workspace diagnostics requests

### Nvim version (nvim -v)

v0.12.0-dev-e518666f1d

### Language server name/version

rosyln_ls

### Operating system/version

Pop!_OS 22.04 LTS x86_64 

### Log file

_No response_

### PR DESCRIPTION
**Pull request by ZieMcd**
Closes [34673](https://github.com/neovim/neovim/issues/34673)

### CODE REVIEW

**Comment by justinmk** [comment]
need review from @MariaSolOs

File: runtime/lua/vim/lsp/diagnostic.lua [hunk 1]
```diff
@@ -450,8 +450,8 @@ local function previous_result_ids(client_id)
       for buf_client_id, result_id in pairs(state.client_result_id) do
         if buf_client_id == client_id then
           table.insert(results, {
-            textDocument = util.make_text_document_params(bufnr),
-            previousResultId = result_id,
+            uri = vim.uri_from_bufnr(bufnr),
+            value = result_id,
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/diagnostic.lua:454]: Let's use a type annotation to validate this from the LSP:
```lua
local function previous_result_ids(client_id)
  local results = {} ---@type lsp.PreviousResultId[]

  for bufnr, state in pairs(bufstates) do
    if state.pull_kind ~= 'disabled' then
      for buf_client_id, result_id in pairs(state.client_result_id) do
        if buf_client_id == client_id then
          results[#results + 1] = {
            uri = vim.uri_from_bufnr(bufnr),
            value = result_id,
          }
          break
        end
      end
    end
  end

  return results
end
```

**Review by MariaSolOs — CHANGES_REQUESTED** [review]

File: runtime/lua/vim/lsp/diagnostic.lua (hunk 1 above)
Comment (ZieMcd) [reply runtime/lua/vim/lsp/diagnostic.lua:454]: sure thing, 
any reason for  results[#results + 1] over table.insert?

Comment (MariaSolOs) [reply runtime/lua/vim/lsp/diagnostic.lua:454]: Because then LuaLS will ensure that the inserted item matches the type of `results`. `table.insert` doesn’t use that type information.

**Review by MariaSolOs — APPROVED** [review]
