### PR TITLE
fix(display): wrong cursor column with 'concealcursor' = "n" and virt_text

### LINKED ISSUE #33153: concealcursor=n will stop cursor from redrawin when inline extmarks are set
### Problem

As title says, I faced the issue with lsp inlay hint, and tested with a minimal init.lua with decoration provider, the same as how inlay hint set extmarks.

### Steps to reproduce

```lua
vim.o.concealcursor = "n"
local draw = false
local ns = vim.api.nvim_create_namespace("z")
vim.api.nvim_set_decoration_provider(ns, {
    on_win = function()
        if draw == true then
            draw = false
            vim.api.nvim_buf_set_extmark(0, ns, 0, 0, {
                virt_text_pos = "inline",
                virt_text = { { "VERTTEXT", "Comment" } },
            })
        end
    end,
})
vim.keymap.set("n", "f", function()
    draw = true
    vim.cmd("redraw!")
end)
```

type some text and press f, notice cursor don't get redrawn:

https://github.com/user-attachments/assets/0775c1be-dc4f-4838-bbad-94afb950e82c

### Expected behavior

 cursor should shift right

### Nvim version (nvim -v)

0.11 release

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macos 14.1

### Terminal name/version

xterm

### $TERM environment variable

xterm

### Installation

build from source

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Inline virtual text placed in a decor provider callback
          invalidates `w_virtcol`, which must be valid for `win_line()`.
Solution: Call `validate_virtcol()` after "line" decor provider callbacks.

Fix #33153

### CODE REVIEW

File: src/nvim/drawline.c [hunk 1]
```diff
@@ -1163,7 +1163,8 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, int col_rows, b
       }
     }
 
-    decor_providers_invoke_line(wp, lnum - 1);
+    decor_providers_invoke_line(wp, lnum - 1); // may invalidate wp->w_virtcol
```
Comment (zeertzjq) [inline src/nvim/drawline.c:1166]:
```suggestion
    decor_providers_invoke_line(wp, lnum - 1);  // may invalidate wp->w_virtcol
```

**Review by justinmk — APPROVED** [review]
