### PR TITLE
memory: fix memory alignment for dynamic allocation

### LINKED ISSUE #20437: armv7 crash
### Neovim version (nvim -v)

v0.8.0

### Vim (not Nvim) behaves the same?

no, 9.0.354

### Operating system/version

armv7 arch linux on arm

### Terminal name/version

kitty

### $TERM environment variable

xterm-color

### Installation

Arch Arm on Linux, AUR nvim-nightly

### How to reproduce the issue

nvim --clean

### Expected behavior

to be working...

I tried the aur "nighly" and the official package 

### Actual behavior

crash
```
% nvim --clean
zsh: bus error (core dumped)  nvim
[..]
% coredumpctl gdb 7177
[...]
#0  0x005fdfb4 in hlattrs2dict (dict=dict@entry=0xbe80940c, ae=..., use_rgb=<optimized out>, use_rgb@entry=true)
    at /usr/src/debug/neovim-0.8.0/src/nvim/highlight.c:874
874	     PUT_C(hl, "foreground", INTEGER_OBJ(ae.rgb_fg_color));
[Current thread is 1 (Thread 0xb6f35fa0 (LWP 7177))]
[...]
(gdb) r --clean
[...]
Thread 1 "nvim" received signal SIGBUS, Bus error.
                                                  0x004b88e8 in mode_style_array (arena=0xbeffe3d8, arena@entry=0xbeffe480) at /usr/src/debug/neovim-0.8.0/src/nvim/cursor_shape.c:57
57          PUT_C(dic, "short_name", STRING_OBJ(cstr_as_string(cur->name)));
```

### PR DESCRIPTION
**Pull request by jpalus**
all pointers returned by arena_alloc residing in arena block should be properly aligned

also make ARENA_ALIGN reflect what glibc does (with MALLOC_ALIGNMENT) to have proper alignment for each platform. might not be fully accurate but it's best effort approach keeping c99 compatibility. with c11 it could be reduced to single:

    #define ARENA_ALIGN _Alignof(max_align_t)

Fixes #20437

### CODE REVIEW

File: src/nvim/memory.h [hunk 1]
```diff
@@ -45,7 +45,16 @@ typedef struct consumed_blk {
   struct consumed_blk *prev;
 } *ArenaMem;
 
-#define ARENA_ALIGN sizeof(void *)
+#ifdef __GNUC__
+# if defined(__i386__)
+#  define ARENA_ALIGN 16
+# else
+#  define ARENA_ALIGN ((2 * sizeof(size_t)) < \
+                       __alignof__(long double) ? __alignof__(long double) : (2 * sizeof(size_t)))
```
Comment (bfredl) [inline src/nvim/memory.h:53]: Is there a source that the recommended alignment on x86 is 16 and not 8? and that the required one on AARCH64 is 16 and not 8? (it can be assumed we never use weird or obsolete x87 doubles, nor 128 bit ints). just hardcoding `ARENA_ALIGN` to `MAX(sizeof(void *), sizeof(double))` would have be been simpler.

Also `__GNUC__`  looks fishy. we only care what the CPU wants, not about gcc/glibc's ideas.

File: src/nvim/memory.c [hunk 2]
```diff
@@ -576,41 +577,66 @@ void alloc_block(Arena *arena)
...
-    arena->pos = (arena->pos + (ARENA_ALIGN - 1)) & ~(ARENA_ALIGN - 1);
+    if (arena_align_offset(arena->cur_blk + arena->pos, ARENA_ALIGN, &align_pos) < 0) {
+      alignment_ok = false;
+    }
   }
-  if (arena->pos + size > arena->size || !arena->cur_blk) {
-    if (size > (ARENA_BLOCK_SIZE - sizeof(struct consumed_blk)) >> 1) {
+  if (arena->pos + align_pos + size > arena->size || !alignment_ok) {
+    if (size + (align ? (ARENA_ALIGN - 1) : 0) > (ARENA_BLOCK_SIZE - sizeof(struct consumed_blk))
+        >> 1) {
```
Comment (bfredl) [inline src/nvim/memory.c:612]: This looks needlessly complicated. Expressing the constraint and doing overflow checking direct in `arena->pos` integer space was much simpler (instead of first converting to pointer so we can play-pretend "secure pointer handling" by then converting back to uintptr to do pointer-space overflow check.). Remember, this is an interface for known internal consumers, not a malloc implementation which needs be c-standard paranoia compliant.

File: src/nvim/memory.h (hunk 1 above)
Comment (jpalus) [reply src/nvim/memory.h:53]: Above logic is based purely on:
https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/generic/malloc-alignment.h;h=ef0f381f772088d3e8a8648410bba85b1a970451;hb=c804cd1c00adde061ca51711f63068c103e94eef
https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/generic/malloc-alignment.h;h=ef0f381f772088d3e8a8648410bba85b1a970451;hb=c804cd1c00adde061ca51711f63068c103e94eef

> just hardcoding `ARENA_ALIGN` to `MAX(sizeof(void *), sizeof(double))` would have be been simpler.

I don't really know what are neovim's alignment requirements hence PR attempts to be as generic as possible. If you're sure it will never reach maximum then I guess it's fine.

> Also `__GNUC__` looks fishy. we only care what the CPU wants, not about gcc/glibc's ideas.

`__GNUC__` is there to make sure `__i386__` and `__alignof__` are available.

File: src/nvim/memory.c (hunk 2 above)
Comment (jpalus) [reply src/nvim/memory.c:612]: To be clear you'd like to drop "[fix(memory): check for uintptr_t overflow](https://github.com/neovim/neovim/pull/20489/commits/df1bd1fcbf83e129ed8251433fd24459f94658c1)" correct?

Comment (bfredl) [reply src/nvim/memory.c:612]: ye, that looks like it.

File: src/nvim/memory.h (hunk 1 above)
Comment (bfredl) [reply src/nvim/memory.h:53]: I think, we should try to just do `MAX(sizeof(double), sizeof(void *))` here without any checks. the only issue I can see is that we use 4-byte alignment on ARMv7 where 8-byte is needed, due to 64-bit floats. if there is still an issue even with that people can report a new issue.

**Comment by jpalus** [comment]
Commit with overflow reverted and `ARENA_ALIGN` changed to `MAX(sizeof(void *), sizeof(double))`. If ok I will squash the commits.

**Comment by zeertzjq** [comment]
Needs a rebase

**Comment by jpalus** [comment]
Rebased and squashed.

**Comment by polyzen** [comment]
For some reason this didn't make it into 0.8.1.

**Comment by lewis6991** [comment]
That's a shame, maybe we should consider releasing 0.8.2

**Comment by clason** [comment]
This is the plan, unless 0.9 gets finished first.
