### PR TITLE
fix(float): don't trigger au event when enter is false

### LINKED ISSUE #15300: BufEnter is triggered when calling nvim_open_win with enter=false
### Neovim Version

v0.6.0-dev+111-gf22326ef0

### Installation

built from repo

### Steps to reproduce

Run
```vim
au BufEnter * echom "Entering buffer" expand("<afile>")
```
Then execute this script
```lua
local buf = vim.api.nvim_create_buf(false, true)
local win = vim.api.nvim_open_win(buf, false, {
  anchor = "SW",
    col = 0,
    height = 2,
    relative = "cursor",
    row = 0,
    style = "minimal",
    width = 53
  })
```

### Expected behavior

Since the cursor remains out of the float buffer . In the original buffer where we started at . I'd expect BufEnter to be not triggered at all (Since enter is false). Or it to be triggered twice once for going into the float buffer and one for getting out. In 1st case see no message at all and in 2nd case see 2 messages.

### Actual behavior

But you'll see Entering buffer in messages once indicating BufEnter event was emited once for an unnamed buffer (float buffer).

For this anything keeping track of current buffer with `BufEnter` will be out of sync with the editor .

### Some background
I encountered this while tracking down https://github.com/hoob3rt/lualine.nvim/issues/286

`vim.lsp.diagnostic.goto_next` calls `vim.lsp.diagnostics.show_line_diagnostics` to show diagnostics . Which creates float with `nvim_open_win` leading to the bug . It's possible to workarround this issue by passing `noautocmd` option to `nvim_open_win`.

### Possible cause

I think this is what's happening
https://github.com/neovim/neovim/blob/e7bde44d6d2a88e67d68d5a1b9f0d037179dd14e/src/nvim/window#L586 this line changes currently active window to newly created float . this https://github.com/neovim/neovim/blob/e7bde44d6d2a88e67d68d5a1b9f0d037179dd14e/src/nvim/window#L606 restores the original window . These two doesn't trigger any auto commands . In the middle this https://github.com/neovim/neovim/blob/e7bde44d6d2a88e67d68d5a1b9f0d037179dd14e/src/nvim/window#L594 line changes the buffer . This triggers `BufEnter` for float buffer . So when `nvim_open_win` is called with enter = false then we get one BufEnter and one BufLeave for getting out from current buffer and entering new one . But the cursor ends up in older win and buffer . So anything keeping track of Current active buffer with `BufEnter` or `BufLeave` gets out of sync .

### Possible solution
So what's a valid solution to this ? makeing switch_win and restore_win trigger auto commands ? ignoring BufEnter from that do_buffer call when enter is false or something else ?

### PR DESCRIPTION
**Pull request by glepnir**
Problem:  when `enter` is false it's better not trigger `BufEnter` etc events.

Solution: `noautocmd` also check `enter` value.

Fix #15300

### CODE REVIEW

**Comment by MariaSolOs** [comment]
Will also fix #25099

**Comment by MariaSolOs** [comment]
It would be nice to get this merged before #25073 so that #25099 gets fixed too 🙃

File: test/functional/ui/float_spec.lua [hunk 1]
```diff
@@ -415,6 +415,44 @@ describe('float window', function()
...
+        relative = 'editor',
+        row = 10,
+        col = 10,
+        width = 10,
+        height = 10,
+      }
+      --enter without fconfig.noautocmd
+      --enter is false doesn't trigger
+      win_id = vim.api.nvim_open_win(buf, false, fconfig)
+      vim.api.nvim_win_close(win_id, true)
```
Comment (bfredl) [inline test/functional/ui/float_spec.lua:440]: could check for times=0 already here

File: test/functional/ui/float_spec.lua [hunk 2]
```diff
@@ -415,6 +415,44 @@ describe('float window', function()
...
+
+      --enter is true trigger
+      win_id = vim.api.nvim_open_win(buf, true, fconfig)
+      vim.api.nvim_win_close(win_id, true)
```
Comment (bfredl) [inline test/functional/ui/float_spec.lua:444]: and times=1 here

File: test/functional/ui/float_spec.lua [hunk 3]
```diff
@@ -415,6 +415,46 @@ describe('float window', function()
     eq(winids, eval('winids'))
   end)
 
+  it("opened and does not trigger BufEnter see issue #15300", function()
```
Comment (justinmk) [inline test/functional/ui/float_spec.lua:418]:
```suggestion
  it("open does not trigger BufEnter #15300", function()
```
