### PR TITLE
fix(typval): don't treat v:null as truthy

### LINKED ISSUE #23279: Falsy operator does not treat `v:null` as "falsy"
### Problem

Falsy operator (`??`) has been ported from Vim in https://github.com/neovim/neovim/pull/23084, but it has a different behavior from Vim.
Falsy operator does not treat `v:null` as "falsy" in spite Vim does.

### Steps to reproduce

```vim
" In Vim v9.0.1479
:echo v:null ?? 'foo' " => 'foo'
" In Neovim v0.10.0-dev-g3ac952d4e
:echo v:null ?? 'foo' " => v:null
```

### Expected behavior

`v:null ?? 'foo'` should return `'foo'`.

### Neovim version (nvim -v)

v0.10.0-dev-g3ac952d4e

### Vim (not Nvim) behaves the same?

No, in Vim v9.0.1479

### Operating system/version

Ubuntu 22.10

### Terminal name/version

GNOME Terminal Version 3.46.2 for GNOME 43

### $TERM environment variable

tmux-256color

### Installation

Build from repo

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #23279

### CODE REVIEW

File: test/functional/vimscript/special_vars_spec.lua [hunk 1]
```diff
@@ -130,6 +130,12 @@ describe('Special values', function()
     eq("v:false", eval('"" . v:false'))
   end)
 
+  it('work with ?? (falsy operator)', function()
+    eq(true, eval('v:true ?? 42'))
+    eq(42, eval('v:false ?? 42'))
+    eq(42, eval('v:null ?? 42'))
+  end)
+
```
Comment (uga-rosa) [inline test/functional/vimscript/special_vars_spec.lua:138]: Other tests for falsy operator can be found here. Wouldn't it be better to put them all in the same place?
https://github.com/neovim/neovim/blob/3ac952d4e27f4e2454332a730310316fe13fd4a3/test/old/testdir/test_expr.vim#L64-L87

Comment (zeertzjq) [reply test/functional/vimscript/special_vars_spec.lua:138]: Not really.
