### PR TITLE
fix(diagnostic): preserve fields from LSP diagnostics

### LINKED ISSUE #15733: Code actions (for diagnostics) stopped working (eslint, typescript, ...)
### Neovim version (nvim -v)

v0.6.0-dev+nightly-977-g 340f77e78

### Vim (not Nvim) behaves the same?

/

### Operating system/version

macOS 

### Terminal name/version

kitty

### $TERM environment variable

screen-256color

### Installation

homebrow

### How to reproduce the issue

from a language server output a diagnostic and try to echo it back, the diagnostic doesn't fully match. E.g. the code field is dropped

### Expected behavior

The code field is send back when doing a code_action request

### Actual behavior

The code field is dropped

I think this broke because of https://github.com/neovim/neovim/pull/15585

### PR DESCRIPTION
**Pull request by gpanders**
Closes #15733.

(Note that the `source` field is already added in #15717).

### CODE REVIEW

File: runtime/lua/vim/lsp/diagnostic.lua [hunk 1]
```diff
@@ -102,7 +102,8 @@ local function diagnostic_lsp_to_vim(diagnostics, bufnr, client_id)
       end_lnum = _end.line,
       end_col = line_byte_from_position(buf_lines, _end.line, _end.character, offset_encoding),
       severity = severity_lsp_to_vim(diagnostic.severity),
-      message = diagnostic.message
+      message = diagnostic.message,
+      code = diagnostic.code,
```
Comment (entropitor) [inline runtime/lua/vim/lsp/diagnostic.lua:106]: Should we copy the other fields as well? e.g. tags, ...

See https://microsoft.github.io/language-server-protocol/specification.html#diagnostic for all possible official fields

**Review by entropitor — APPROVED** [review]
Seems to work with eslint language server at least!

File: runtime/lua/vim/lsp/diagnostic.lua (hunk 1 above)
Comment (gpanders) [reply runtime/lua/vim/lsp/diagnostic.lua:106]: I think that should be fine.

@neovim/lsp any thoughts here?

Comment (mjlbach) [reply runtime/lua/vim/lsp/diagnostic.lua:106]: Should we maybe store all of the original raw lsp fields under an `lsp` key?

Comment (mfussenegger) [reply runtime/lua/vim/lsp/diagnostic.lua:106]: I'd also tend to have some arbitary property bag and within that an `lsp` key, so that we can avoid extending the neovim specific diagnostic structure each time the LSP specification is extended. (Not that it happens often, but to keep it decoupled)

**Comment by mjlbach** [comment]
Linux lint issue? Otherwise good to me with the most recent changes.

**Review by mjlbach — APPROVED** [review]

File: runtime/lua/vim/lsp/diagnostic.lua [hunk 2]
```diff
@@ -102,15 +102,21 @@ local function diagnostic_lsp_to_vim(diagnostics, bufnr, client_id)
       end_lnum = _end.line,
       end_col = line_byte_from_position(buf_lines, _end.line, _end.character, offset_encoding),
       severity = severity_lsp_to_vim(diagnostic.severity),
-      message = diagnostic.message
+      message = diagnostic.message,
+      lsp = {
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/diagnostic.lua:106]: I had something like `user_data`  in mind (Similar to how it is used in `complete-items`) and nest it further - to avoid making `lsp` a first-class diagnostic item property. 

But no strong opinion.

Comment (mjlbach) [reply runtime/lua/vim/lsp/diagnostic.lua:106]: Also no strong opinion. Do we anticipate additional things populating this field? I don't know of any off the top of my head, but additional table nesting doesn't heart (apart from code beauty)

Comment (gpanders) [reply runtime/lua/vim/lsp/diagnostic.lua:106]: I don't anticipate needing to attach any other kind of non-LSP related data here, but of course I can't see the future and this would save us a refactor if that ever was the case. So SGTM.

File: runtime/lua/vim/lsp/diagnostic.lua [hunk 3]
```diff
@@ -102,15 +102,23 @@ local function diagnostic_lsp_to_vim(diagnostics, bufnr, client_id)
...
       severity = severity_lsp_to_vim(diagnostic.severity),
-      message = diagnostic.message
+      message = diagnostic.message,
+      user_data = {
+        lsp = {
+          code = diagnostic.code,
+          codeDescription = diagnostic.codeDescription,
+          tags = diagnostic.tags,
+          relatedInformation = diagnostic.relatedInformation,
+        },
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/diagnostic.lua:112]: Could you also add the `data` property? 

```
 /**
      * A data entry field that is preserved between a
      * `textDocument/publishDiagnostics` notification and
      * `textDocument/codeAction` request.
      *
      * @since 3.16.0
      */
    data?: unknown;
```

**Review by mfussenegger — APPROVED** [review]

**Comment by gpanders** [comment]
Not sure what's going on with ASAN and TSAN:

```
FAILED: usr/lib/luarocks/rocks-5.1/penlight /home/runner/nvim-deps/usr/lib/luarocks/rocks-5.1/penlight 
cd /home/runner/nvim-deps && /home/runner/nvim-deps/usr/bin/luarocks build penlight 1.5.4-1 CC=/usr/bin/cc LD=/usr/bin/cc
Warning: Failed searching manifest: Failed fetching manifest for https://luarocks.org - Failed downloading https://luarocks.org/manifest-5.1 - /home/runner/.cache/luarocks/https___luarocks.org/manifest-5.1

Error: Could not satisfy dependency luafilesystem: No results matching query were found for Lua 5.1.
Missing dependencies for penlight 1.5.4-1:
   luafilesystem (not installed)

penlight 1.5.4-1 depends on luafilesystem (not installed)
luafilesystem not found for Lua 5.1.
Checking if available for other Lua versions...
Checking for Lua 5.2...
Checking for Lua 5.3...
Checking for Lua 5.4...
ninja: build stopped: subcommand failed.
```

Looks unrelated to these changes.

**Comment by mjlbach** [comment]
@gpanders it was just a sporadic test failure with the lua dependencies. I restarted the tests and they all passed.

**Comment by gpanders** [comment]
> Did you want these commits squashed?

Doesn't matter to me, I wrote the commits so that they could all be merged in, but the latter two are pretty small.
