### PR TITLE
fix(channel): fix Windows console regressions from #37977

### LINKED ISSUE #38630: Windows: Ctrl+C does not interrupt running processes in :terminal (0.12 regression)
### Problem

On Windows, pressing `Ctrl+C` in terminal mode (`:terminal`) does not send an interrupt signal to running child processes. The keypress is received by the terminal (typing `Ctrl+C` at an idle PowerShell prompt shows `^C` and starts a new prompt line), but when a program is actively running (e.g. `ping localhost -t`, `Start-Sleep 30`), `Ctrl+C` has no effect — the process keeps running.
This also cannot be worked around via the Lua API. Sending `\x03` directly to the terminal channel with `vim.api.nvim_chan_send(chan, "\x03")` or `vim.fn.chansend(chan, "\x03")` also does NOT stop the running process, confirming the issue is at the ConPTY/channel level, not the keymap level.
This worked correctly in v0.11.x on the same machine and terminal.

### Steps to reproduce
```
nvim --clean
:terminal pwsh.exe -NoLogo
i
ping localhost -t
<Press Ctrl+C>
```
Observe: ping continues running, `Ctrl+C` has no effect.
For additional confirmation that the issue is at the channel level:
```
1. Press `Ctrl+\ Ctrl+n` to exit terminal mode
2. Run: `:lua vim.fn.chansend(vim.bo.channel, "\x03")`
3. Press `i` to re-enter terminal mode
4. Observe: ping is still running
```

### Expected behavior

Pressing Ctrl+C in terminal mode should send an interrupt signal (CTRL_C_EVENT) to the foreground process running in the terminal, causing it to terminate (same behavior as v0.11.x and standalone terminal).

### Nvim version (nvim -v)

NVIM v0.12.0 Release, LuaJIT 2.1.1774638290

### Vim (not Nvim) behaves the same?

No, not applicable (Vim does not use ConPTY on Windows in the same way)

### Operating system/version

Windows 11 (NT 10.0.26200.0)

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

winget install Neovim.Neovim

### PR DESCRIPTION
**Pull request by SanzharKuandyk**
Refactor #37977
Fix #38667
Fix #38630

## Problem
After #37977, the Windows builtin TUI startup path began treating every normal `nvim` launch like a detached-server case. That fixed `:detach` / `:restart`, but it also pulled ordinary startup into console-handling logic that was only meant for those persistence flows, causing two regressions:

1. The embedded server was started detached and allocated a hidden console on startup, so a hidden `conhost.exe` appeared on every launch and `CONOUT$` resolved to that hidden console instead of the real terminal. As a result, `io.stdout:write()` rendering such as SIXEL and Kitty image output disappeared. #38667

2. Because normal startup was still spawned as a detached Windows process, terminal jobs no longer behaved like they did in a normal attached console session. In particular, `Ctrl-C` in `:terminal` stopped interrupting foreground programs on Windows. #38630

## Solution
Keep the detached Windows builtin-TUI startup model introduced for `:detach` / `:restart`, but narrow the console-handling fallout it caused.

1. Preserve detached startup for the embedded server, so the existing Windows `:detach` and `:restart` behavior continues to work.

2. Restore useful console behavior on top of that detached model:
   - top-level builtin TUI startup may borrow the parent console so `CONOUT$` resolves to the real terminal, preserving visible `io.stdout:write()` output such as SIXEL and Kitty image rendering
   - `:restart` still allocates a hidden private console for the replacement server
   - `:detach` still swaps the running server to a hidden private console after the UI/channel is closed

3. After the detached embedded server acquires a console, restore normal `Ctrl-C` handling so terminal jobs can inherit it again on Windows.

> **Note:** skipped 'killing TUI process without :preserve #22096' test on Windows

### CODE REVIEW

**Comment by zeertzjq** [comment]
Test failure:
```
FAILED   test/functional/terminal/tui_spec.lua @ 4263: TUI client :restart works when connecting to remote instance (with its own TUI)
test/functional/terminal\tui_spec.lua:4268: Row 2 did not match.
Expected:
  |^                                                  |
  |*{100:~                                                 }|
  |*{100:~                                                 }|
  |*{100:~                                                 }|
  |*{3:[No Name]                                         }|
  |                                                  |
  |{5:-- TERMINAL --}                                    |
Actual:
  |^                                                  |
  |*[Process exited 0]                                |
  |*                                                  |
  |*                                                  |
  |*                                                  |
  |                                                  |
  |{5:-- TERMINAL --}                                    |
```
Perhaps this should be moved to `nvim__chan_set_detach()`, and `ex_detach()` should call that API.

File: src/nvim/ex_docmd.c [hunk 1]
```diff
@@ -5928,6 +5935,20 @@ static void ex_detach(exarg_T *eap)
...
+    FreeConsole();
+    AllocConsole();
+    ShowWindow(GetConsoleWindow(), SW_HIDE);
+    // Re-bind fd 0/1/2 to the new console's CONIN$/CONOUT$ so that
+    // :terminal (ConPTY) and the fwd_err relay (os_write(STDOUT_FILENO))
+    // keep working after detach.
+    os_replace_stdin_to_conin();
+    os_replace_stdout_and_stderr_to_conout();
+#endif
+
```
Comment (zeertzjq) [inline src/nvim/ex_docmd.c:5955]: I mean this part should be moved to `nvim__chan_set_detach()`.

Comment (SanzharKuandyk) [reply src/nvim/ex_docmd.c:5955]: Yeah, i get it, i am not so sure about it yet i thought that the test failed because rpc died or something

Comment (SanzharKuandyk) [reply src/nvim/ex_docmd.c:5955]: but anyway probably calling `nvim__chan_set_detach `from `ex_detach `is still kinda falls under refactor commit

Comment (zeertzjq) [reply src/nvim/ex_docmd.c:5955]: Oh maybe the problem is a bit more complicated.

**Comment by SanzharKuandyk** [comment]
Well, seems like I will add later an env something like in ef00154 so `AttachConsole(ATTACH_PARENT_PROCESS)` would attach to the parent's ConPTY and allow `io.stdout:write()` on first run, but on `:restart` it will just skip it through this env, so after `:restart` it won't work, seems pretty simple, but need to figure out some other issues like in ef00154. Though, I don't find it necessary to fix this fully just to support rendering on windows-only,  guess https://github.com/neovim/neovim/pull/37914 just wait for this one

**Comment by zeertzjq** [comment]
Or perhaps having `:restart` reattach all UIs will solve this?

**Comment by SanzharKuandyk** [comment]
> Or perhaps having `:restart` reattach all UIs will solve this?

You mean io.stdout:write() writing to hidden console? I fell like they different layers reattaching more ui's doesn't change where `$CONOUT` points to

regarding test it fails because it's nvim-inside-nvim-terminal case, so we see  `[Process exited 0]`  because the new server's console ConPTY is destroyed when the old server exits, sending CTRL_CLOSE_EVENT that kills the new process. which is attached because of `AttachConsole(ATTACH_PARENT_PROCESS))`, as i mentioned via env we prob skip this part and allocate so new nvim survivives via calling `AllocConsole()`, but it does not allow `io.stdout.write()` then. Well i don't know if there is any smart solution to this

**Comment by zeertzjq** [comment]
> so we see  `[Process exited 0]`  because the new server's console ConPTY is destroyed when the old server exits

I was speculating that this happens because the old client exits, not because the old server exits. So having the old client also reattach will solve this problem.

**Comment by zeertzjq** [comment]
#38683 reattaches all UIs.

**Comment by SanzharKuandyk** [comment]
Well this looks better now, but as it is after running `:restart/:detach` because of swap to make server survive the `io.stdout:write()` won't work. Way to go about it is forward writes to client before they go to hidden console? - maybe in another pr, though how necessary is this for https://github.com/neovim/neovim/pull/37914

**Comment by zeertzjq** [comment]
Hmm, the second commit is a bit strange. Since it only fixes the "unreadable swapfile when closing parent terminal" problem for a nested Nvim, does the problem still happen when running Nvim in another terminal? If that's the case, I think it's better to just adjust the swapfile test for now, and leave the fix for another PR.

**Comment by SanzharKuandyk** [comment]
Makes sense, updated

File: src/nvim/channel.c [hunk 2]
```diff
@@ -555,14 +550,24 @@ uint64_t channel_from_stdio(bool rpc, CallbackReader on_output, const char **err
...
-      AllocConsole();
-      ShowWindow(GetConsoleWindow(), SW_HIDE);
+      if (restart_alloc_console) {
+        AllocConsole();
+        ShowWindow(GetConsoleWindow(), SW_HIDE);
+      } else if (!AttachConsole(ATTACH_PARENT_PROCESS)) {
+        // Borrow the parent's console so CONOUT$ resolves to the real terminal,
+        // preserving io.stdout rendering (e.g. SIXEL/Kitty images).  Only fall
+        // back to a hidden AllocConsole when there is no parent console (e.g.
+        // launched from a non-console parent).
```
Comment (zeertzjq) [inline src/nvim/channel.c]: These two branches are the same. Also it's better to add a description on why `restart_attach_console` is needed here:
```suggestion
      // Borrow the parent's console so CONOUT$ resolves to the real terminal,
      // preserving io.stdout rendering (e.g. SIXEL/Kitty images).  Only fall
      // back to a hidden AllocConsole when there is no parent console (e.g.
      // launched from a non-console parent), or when the parent process is a
      // server that just executed :restart and will soon exit.
      if (restart_alloc_console || !AttachConsole(ATTACH_PARENT_PROCESS)) {
```

**Review by zeertzjq — APPROVED** [review]

File: src/nvim/ex_docmd.c [hunk 3]
```diff
@@ -5917,7 +5923,10 @@ static void ex_detach(exarg_T *eap)
       emsg(e_invchan);
       return;
     }
-    chan->detach = true;  // Prevent self-exit on channel-close.
+    // Prevent self-exit on channel-close.
+    Error detach_err = ERROR_INIT;
+    nvim__chan_set_detach(chan->id, true, &detach_err);
+    api_clear_error(&detach_err);
```
Comment (justinmk) [inline src/nvim/ex_docmd.c:5929]: was this change necessary?

Comment (zeertzjq) [reply src/nvim/ex_docmd.c:5929]: No, it was a remnant of a previous suggestion.
