### PR TITLE
fix(languagetree): don't treat unparsed nodes as occupying full range

### LINKED ISSUE #25252: bug(treesitter): parse tree in a broken state (wrong lang) after making no-op edit, leading to slow editing until full reparse
### Problem

bisected to d7ae9ae3e. Specifically the combination of https://github.com/tree-sitter/tree-sitter/commit/9564e1706de651cea6df9939b8a5dba02e7dbc71 and https://github.com/neovim/neovim/commit/2ca076e45fb3f1c08f6a1a374834df0701b8d778 causes the full issue. The latter by itself already causes a broken parse tree, but the broken tree changes after the tree-sitter update and this triggers the performance issue (probably a trigger not a cause)

At a particular part of a test file, if you add and remove a new line repeatedly, the parse tree will end up in a broken state:

Before no-op edit:

Screenshot 2023-09-19 at 7 42 37 PM

After no-op edit:

Screenshot 2023-09-19 at 7 42 59 PM

After no-op edit, if tree-sitter not upgraded (still wrong but not lag):

Screenshot 2023-09-19 at 7 40 44 PM

I did some logging and it looks like `self._regions` might be getting wiped out (shows as `nil`)

Note: the inspector will interfere with the repro by doing a full parse, unless you change to false in the following line:

https://github.com/neovim/neovim/blob/c4f4c7a356013c6f1e10b7bf239d9e3c4c0c336e/runtime/lua/vim/treesitter/dev.lua#L102

### Steps to reproduce

`repro.lua` (minimal config):
```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = { "*" },
  callback = function() vim.treesitter.start() end,
})
```
`lspconfig.lua` (the file we are editing): [download (~500 lines)](https://github.com/llllvvuu/dotfiles/blob/9e54b87b4fdb17becef516863ab623756da43ae1/vim/.config/nvim/lua/plugins-tui/lspconfig.lua)
1. `nvim --clean --noplugin -u repro.lua lspconfig.lua`.
2. Adjust winheight to 57 for this demo (`:echo winheight(0)`)
3. `/vue<CR>f}i` should place you in insert mode between the brackets. First line of screen should say "suggest = {" and last line should say "on_initialized = function()" (it's critical that the vimscript injection is just offscreen after this last line, so that it gets parsed)
4. Press `<CR><Backspace><Backspace>` to insert and remove a new line. This should be quite snappy, although the syntax highlighting should be wrong at this point.
5. Repeat step 4 over and over; it should get laggy after a few times.

### Expected behavior

Tree does not break.

### Neovim version (nvim -v)

0.10 commit 28f54a78782318cb9c356a372b9e52a3a6b1f8dd

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.4.1

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by llllvvuu**
This is incorrect in the following scenario:
1. The language tree is Lua > Vim > Lua.
2. An edit simultaneously wipes out the `_regions` of all nodes, while taking the Vim injection off-screen.
3. The Vim injection is not re-parsed, so the child Lua `_regions` is still `nil`.
4. The child Lua is assumed, incorrectly, to occupy the whole document.
5. This causes the injections to be parsed again, resulting in Lua > Vim > Lua > Vim.
6. Now, by the same process, Vim ends up with its range assumed over the whole document. Now the parse is broken and results in broken highlighting and poor performance.

It should be fine to instead treat an unparsed node as occupying nothing (i.e. effectively non-existent). Since, either:
- The parent was just parsed, hence defining `_regions`
- The parent was not just parsed, in which case this node doesn't need to be parsed either.

Additionally, the name `has_regions` is confusing; it seems to simply mean the opposite of "root" or "full_document". However, we do not touch it in this PR.

Fixes: #25252

### CODE REVIEW

**Comment by lewis6991** [comment]
How hard would it be to write a test for this?

**Comment by llllvvuu** [comment]
I have the scenario, so it should be doable. Let me see if I can simplify it first. Probably will take a look tomorrow.

**Comment by llllvvuu** [comment]
Just added a test that fails on `master`

File: test/functional/treesitter/highlight_spec.lua [hunk 1]
```diff
@@ -838,3 +838,67 @@ describe('treesitter highlighting (help)', function()
   end)
 
 end)
+
+describe('treesitter highlighting (nested injections)', function()
```
Comment (lewis6991) [inline test/functional/treesitter/highlight_spec.lua:842]: Since this is a regression it's usually good to include the issue number.

**Review by lewis6991 — APPROVED** [review]

File: test/functional/treesitter/highlight_spec.lua (hunk 1 above)
Comment (llllvvuu) [reply test/functional/treesitter/highlight_spec.lua:842]: I put it in the `it()` because I was thinking the `describe()` group could be more general, but should it be both?

Comment (lewis6991) [reply test/functional/treesitter/highlight_spec.lua:842]: Ah sorry I missed that. (Reviewing on mobile)
