### PR TITLE
fix(health): floating window closes when opening TOC (gO)

### LINKED ISSUE #34784: Floating checkhealth buffer is deleted after typing `gO`
### Problem

I want to use `gO` to see table of contents (TOC) of checkhealth buffer, and then move to the session I want using that TOC. However, when the table of contents (which is also a loclist) is opened, the checkhealth buffer is also removed, which means the TOC is now useless.

### Steps to reproduce

1. nvim --clean -c "lua vim.g.health = { style = 'float' }"
2. `:checkhealth`
3. Type `gO`
4. Press enter in the loclist to go to a session you want 
 => E92: Bufffer 2 not found

### Expected behavior

The checkhealth window should remains opened when I open its TOC

### Nvim version (nvim -v)

NVIM v0.12.0-dev-cbfc3d1cdc

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Kubuntu 24.04.1

### Terminal name/version

konsole

### $TERM environment variable

xterm-256color

### Installation

Source

### PR DESCRIPTION
**Pull request by glepnir**
Problem: Health check floating window gets closed when pressing 'gO' to show TOC because LSP floating preview system auto-closes on BufEnter events triggered by :lopen.

Solution: Temporarily disable BufEnter event for the current window during TOC operations and adjust window layout to prevent overlap.

Fix #34784

### CODE REVIEW

File: test/functional/plugin/health_spec.lua [hunk 1]
```diff
@@ -77,6 +77,14 @@ describe(':checkhealth', function()
       return vim.api.nvim_win_get_config(0).relative
     ]])
     )
+
+    -- Prevent checkhealth floating window after using gO. See #34784
```
Comment (zeertzjq) [inline test/functional/plugin/health_spec.lua]:
```suggestion
    -- Prevent checkhealth floating window closing after using gO. See #34784
```

File: test/functional/plugin/health_spec.lua [hunk 2]
```diff
@@ -68,7 +68,7 @@ describe(':checkhealth', function()
   end)
 
   it('vim.g.health', function()
-    clear()
+    clear { args = { '-u', 'NORC', '+set runtimepath+=test/functional/fixtures' } }
```
Comment (zeertzjq) [inline test/functional/plugin/health_spec.lua:71]: Why `-u NORC` instead of `-u NONE -i NONE`?

Comment (zeertzjq) [reply test/functional/plugin/health_spec.lua:71]: Actually this isn't needed at all, because `_new_argv()` merges arguments.

Comment (justinmk) [inline test/functional/plugin/health_spec.lua]: clear() specifies `-u NONE`, but I assume you are overriding it with `-u NORC` want plugins to be loaded? if so, try `args_rm` to make it clear what you want to override. And `--clean` seems more appropriate.

```lua
clear {
  args_rm = { '-u' },
  args = { '--clean', '+set runtimepath+=test/functional/fixtures' },
}
```

File: test/functional/plugin/health_spec.lua [hunk 3]
```diff
@@ -77,6 +77,14 @@ describe(':checkhealth', function()
       return vim.api.nvim_win_get_config(0).relative
     ]])
     )
+
+    -- Prevent checkhealth floating window closing after using gO. See #34784
```
Comment (justinmk) [inline test/functional/plugin/health_spec.lua]:
```suggestion
    -- gO should not close the :checkhealth floating window. #34784
```

File: test/functional/plugin/health_spec.lua [hunk 4]
```diff
@@ -77,6 +77,14 @@ describe(':checkhealth', function()
...
+    command('checkhealth full_render')
+    local win = api.nvim_get_current_win()
+    api.nvim_win_set_cursor(win, { 5, 1 })
+    n.feed('gO')
```
Comment (justinmk) [inline test/functional/plugin/health_spec.lua:88]: feed() is async. that means the assertions below this could have false negatives? maybe `command('norm gO')` instead (note: `norm` not `norm!`)?

Comment (zeertzjq) [reply test/functional/plugin/health_spec.lua:88]: But `nvim_win_is_valid` is not async.

**Comment by justinmk** [comment]
> because LSP floating preview system auto-closes on BufEnter events triggered by :lopen.

Thank for mentioning that. That explains why it [doesn't happen for a :help floatwin](https://github.com/neovim/neovim/issues/34784#issuecomment-3042549597).

But the code added in this PR looks like a lot of code for something that should be simple. And the code doesn't mention why it's doing this weird approach? And the code is too complex.

Temporarily setting 'eventignorewin' is a hack on top of another hack. 

So let's start by asking why is this `vim.lsp.util.open_floating_preview` code so complex: https://github.com/neovim/neovim/blob/4f141dca8c888d62b332f31fd51fa3e9b2e6cb89/runtime/lua/vim/lsp/util.lua#L1418

Let's figure out how to implement the behavior that we want in `vim.lsp.util.open_floating_preview` without needing big hacks to avoid it for things like checkhealth.

**Comment by justinmk** [comment]
In particular why is this defined as a global BufEnter instead of a *local* WinLeave? https://github.com/neovim/neovim/blob/4f141dca8c888d62b332f31fd51fa3e9b2e6cb89/runtime/lua/vim/lsp/util.lua#L1425-L1430

If that were a local WinLeave, then checkhealth could just remove the local WinLeave handler in its window.

Alternatively, can we add support to `close_events` here, so that callers can say "I don't want `open_floating_preview` to auto-close on BufEnter" : https://github.com/neovim/neovim/blob/4f141dca8c888d62b332f31fd51fa3e9b2e6cb89/runtime/lua/vim/lsp/util.lua#L1596

**Comment by brianhuster** [comment]
Yes, I personally don't think checkhealth window needs to be autoclosed when the cursor leave it, it should be simple for users to run `:q<Enter>` or even just type `q`

But it does make sense for checkhealth buffer to be deleted after there is no visible checkhealth window

**Comment by glepnir** [comment]
It also need to change the window height. Otherwise it will cover the quickfix window.

**Comment by justinmk** [comment]
> It also need to change the window height. Otherwise it will cover the quickfix window.

That's just too complicated. If the loclist is closed, does the height get restored? And how does the user navigated to/from the loclist?

We can fix the "close" behavior using one of the approaches I suggested. But building lots of logic around handling float positioning is out of scope for checkhealth. If we really care about that, we should fix that for all loclists, i.e. loclist should be able to anchor to the current floatwin. Writing custom logic for every floatwin for this purpose, is not maintainable.

**Comment by glepnir** [comment]
> And how does the user navigated to/from the loclist?

wincmd `<C-W>` ?

> We can fix the "close" behavior using one of the approaches I suggested.

then how to handle the height of the floating window by using `close_events = { 'BufEnter'} ` and anchor point how to solve the coverage problem is here 🤔

cursor now in quickfix window. is covered by floating window.

image

**Comment by justinmk** [comment]
> then how to handle the height of the floating window by using `close_events = { 'BufEnter'} `

we don't need to solve that right now. the floating window will overlap.

> cursor now in quickfix window. is covered by floating window.

 we can make the initial height a bit smaller, and maybe nudge it up. that avoids complicated dynamic logic.

but really, users that want floating windows are choosing not to care about interacting with conventional vim features like loclist. At least until we improve loclist's behavior (globally, not in bespoke ways with custom logic everywhere).

**Comment by brianhuster** [comment]
Is it be feasible to make any location list windows that are local to floating windows also floating window?

**Comment by justinmk** [comment]
> Is it be feasible to make any location list windows that are local to floating windows also floating window?

that's what i was hinting at re "anchoring", but it's out of scope for this PR

**Review by justinmk — APPROVED** [review]
Great solution!
