### PR TITLE
fix(lsp): convert range to byteidx before highlighting

### LINKED ISSUE #15116: lsp: document highlight and rename ranges incorrect with multibyte characters
Two primary use cases:  reference highlighting and symbol renaming.

Example code used below: https://gist.github.com/jcorbin/100a4a2b690e3028813da84733f3b5a6

Here's my [vimrc](https://github.com/jcorbin/home/blob/main/.vimrc) used below; (just builtin LSP, no legacy LSP plugins involved). Screenshots done with numbering, cursor column, and cursor line enabled. Since LSP reference highlighting and renaming requires at least some vimrc, and I don't suspect that mine has any causal nature to this issue, I've not tried to do any config minimization / reproduction yet.

## Reference Highlighting

image

With cursor on a symbol definition we see:
- correct highligh on lines 3, 7, and 11
- incorrect off by -2 highlight on lines 5 and 9 which have a unicode mid ellipsis and emoji respectively

## Symbol Renaming

Next up we use `vim.lsp.buf.rename()` to make the obvious rename of "data" to "lore":

image

- the rename succeded on all but line 9 ; so it handled the unicode mid ellipsis correctly, but not the emoji
- here the rename is off by +1 rather than -2

## Detail

The two codepoints used are U+22EF and U+1F92F, but this problem will present with any emoji, or with any multibyte unicode codepoint (something I only learned while writing this issue actually)

image

image

## Boilerplate

- `nvim --version`: this behavior has been present for a while during 0.5 dev cycle ; apologies for not reporting earlier
```
NVIM v0.6.0-dev+46-g682247b52
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/jcorbin/neovim/build/config -I/Users/jcorbin/neovim/src -I/Users/jcorbin/neovim/.deps/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/jcorbin/neovim/build/src/nvim/auto -I/Users/jcorbin/neovim/build/include
Compiled by jcorbin@anatta.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/jcorbin/.local/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: irrelevant
- Terminal name/version: irrelevant
- `$TERM`: irrelevant

### Steps to reproduce using `nvim -u NORC`

Skipped ; happy to attempt a reproduce if a "minimal LSP enabled RC" is suggested.

### Actual behaviour

See above.

### Expected behaviour

At the very least, anything that manipulates buffer content needs to be correct; highlighting is nice to have, but merely annoying if wrong.

### PR DESCRIPTION
**Pull request by elianiva**
closes https://github.com/neovim/neovim/issues/15116

converts range into byte index before applying highlight for `document_highlight()`

Before:
image

After: 
image

### CODE REVIEW

**Comment by mjlbach** [comment]
This assumes utf-16 encoding (from the server) but we also support utf-8 (and soon utf-32), so we should match on the client offset encoding. Would be good to have a small utility like the reciprocal of:
```
local function convert_byte_to_utf(line, idx, offset_encoding)
  -- convert to 0 based indexing
  idx = idx - 1

  local utf_idx
  -- Convert the byte range to utf-{8,16,32} and convert 1-based (lua) indexing to 0-based
  if offset_encoding == "utf-16" then
    _, utf_idx = vim.str_utfindex(line, idx)
  elseif offset_encoding == "utf-32" then
    utf_idx, _ = vim.str_utfindex(line, idx)
  else
    utf_idx = idx
  end

  -- convert to 1 based indexing
  return utf_idx + 1
end
```

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -1481,6 +1481,25 @@ function M.open_floating_preview(contents, syntax, opts)
   return floating_bufnr, floating_winnr
 end
 
+local function convert_utf_to_byte(line, idx, offset_encoding)
+  -- convert to 0 based indexing
+  idx = idx - 1
+  P(offset_encoding)
```
Comment (mjlbach) [inline runtime/lua/vim/lsp/util.lua:1487]: ?

**Comment by mjlbach** [comment]
Other than my ? LGTM now

**Comment by zeertzjq** [comment]
Does this need a test?

**Comment by mjlbach** [comment]
The answer is almost invariably "yes", but in this case testing highlights is a bit annoying (highlight.range, for reference, is currently not covered by tests)

File: runtime/lua/vim/lsp/util.lua (hunk 1 above)
Comment (elianiva) [reply runtime/lua/vim/lsp/util.lua:1487]: oh haha sorry, forgot to remove this leftover

**Comment by clason** [comment]
`vim.region` -- which does the heavy lifting for `highlight.range` -- _is_, though (in `test/functional/lua/vim_spec.lua`); it might be better to move the fix there so that other functions (like `highlight.on_yank`) can profit from it, too?

**Comment by mjlbach** [comment]
I don't think the fix is applicable since this solely concerns the interface of the utf encoding schema to the byte range used to set the highlight range

File: runtime/lua/vim/lsp/util.lua [hunk 2]
```diff
@@ -1481,6 +1481,24 @@ function M.open_floating_preview(contents, syntax, opts)
   return floating_bufnr, floating_winnr
 end
 
+local function convert_utf_to_byte(line, idx, offset_encoding)
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/util.lua:1484]: There's `get_line_byte_from_position` which is similar - is it possible to merge the two?

File: runtime/lua/vim/lsp/util.lua [hunk 3]
```diff
@@ -1497,18 +1515,29 @@ do --[[ References ]]
   ---@param bufnr buffer id
   ---@param references List of `DocumentHighlight` objects to highlight
   ---@see https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#documentHighlight
-  function M.buf_highlight_references(bufnr, references)
+  function M.buf_highlight_references(bufnr, references, client_id)
     validate { bufnr = {bufnr, 'n', true} }
+    local client = vim.lsp.get_client_by_id(client_id)
+
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/util.lua:1521]:
```suggestion
    local client = vim.lsp.get_client_by_id(client_id)
    if not client then
      return
    end
```


There could be a race between client exiting / receiving the highlights.
I think in this scenario it is fine to just drop the highlights.

File: runtime/lua/vim/lsp/util.lua (hunk 2 above)
Comment (elianiva) [reply runtime/lua/vim/lsp/util.lua:1484]: agreed, that makes sense. Also found a TODO regarding `offset_encoding` in that function

**Review by mjlbach — APPROVED** [review]

File: runtime/lua/vim/lsp/util.lua [hunk 4]
```diff
@@ -151,7 +151,7 @@ end
 --- Position is a https://microsoft.github.io/language-server-protocol/specifications/specification-current/#position
 --- Returns a zero-indexed column, since set_lines() does the conversion to
 --- 1-indexed
-local function get_line_byte_from_position(bufnr, position)
+local function get_line_byte_from_position(bufnr, position, offset_encoding)
   -- TODO handle offset_encoding
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/util.lua:155]:
```suggestion
```

**Review by mfussenegger — APPROVED** [review]

File: runtime/lua/vim/lsp/util.lua [hunk 5]
```diff
@@ -1497,18 +1502,30 @@ do --[[ References ]]
   ---@param bufnr buffer id
   ---@param references List of `DocumentHighlight` objects to highlight
   ---@see https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#documentHighlight
-  function M.buf_highlight_references(bufnr, references)
+  function M.buf_highlight_references(bufnr, references, client_id)
     validate { bufnr = {bufnr, 'n', true} }
+    local client = vim.lsp.get_client_by_id(client_id)
+    if not client then
+      return
+    end
```
Comment (RRethy) [inline runtime/lua/vim/lsp/util.lua:1510]: Changing the function signature in a way that breaks functionality for every single existing caller (since client_id will be nil for all existing callers as it's a new parameter) is a pretty unnecessary landmine to hide.

This caused https://github.com/RRethy/vim-illuminate/issues/85.

A default value for the `offset_encoding` when `client_id` isn't present would make more sense IMO.

Comment (RRethy) [inline runtime/lua/vim/lsp/util.lua:1510]: Changing the function signature in a way that breaks functionality for every single existing caller (since client_id will be nil for all existing callers as it's a new parameter) is a pretty unnecessary landmine to hide.

This caused https://github.com/RRethy/vim-illuminate/issues/85.

A default value for the `offset_encoding` when `client_id` isn't present would make more sense IMO.
