### PR TITLE
fix(options): do not change inccommand during preview

### LINKED ISSUE #23136: Toggling `inccommand` while mid-substitution causes a crash
### Problem

With the below plugin, while mid-search-and-replace, hitting `<C-E>` (to swap `'inccommand'` between `split` and `nosplit`) causes nvim to `exit(134)`.

It always seems to happen on the third toggle.
<details>
<summary>
Despite having a `RelWithDebugInfo` build, I can't get a backtrace better than this on macOS
</summary>

```
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 2.4
    frame #0: 0x00007ff801530ac6 libsystem_c.dylib`exit
    frame #1: 0x000000010215ba0a nvim`os_exit + 202
  * frame #2: 0x000000010227fda3 nvim`exit_event.llvm.6961691851166778423 + 99
    frame #3: 0x00000001024ac945 nvim`ui_client_run + 293
    frame #4: 0x0000000102158917 nvim`main + 10423
    frame #5: 0x00007ff801307310 dyld`start + 2432
```

and I don't get breakpoint hits on either [`exit_from_channel`](https://github.com/neovim/neovim/blob/55d346fc2683a18256320eaae75eb4f3137dcced/src/nvim/event/process.c#L434-L434) or [`exit_delay_cb`](https://github.com/neovim/neovim/blob/55d346fc2683a18256320eaae75eb4f3137dcced/src/nvim/event/process.c#L409-L409)
</details>

<details>
<summary>

I get a much better backtrace on my raspberry pi, albeit with an older nvim, centered on [this `abort`](https://github.com/neovim/neovim/blob/d215dae0e0908d464d70e5645f3e2690bd9caf60/src/nvim/ex_getln.c#L2442-L2442)

</summary>

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x76d50364 in __GI_abort () at abort.c:79
#2  0x001fa5c0 in cmdpreview_may_show (s=s@entry=0x7edd5098) at /home/pi/src/neovim/src/nvim/ex_getln.c:2442
#3  0x001fd054 in command_line_changed (s=s@entry=0x7edd5098) at /home/pi/src/neovim/src/nvim/ex_getln.c:2539
#4  0x001fd82c in command_line_handle_key (s=s@entry=0x7edd5098) at /home/pi/src/neovim/src/nvim/ex_getln.c:1796
#5  0x001fe1d0 in command_line_execute (state=0x7edd5098, key=<optimized out>) at /home/pi/src/neovim/src/nvim/ex_getln.c:1332
#6  0x000b6df0 in state_enter (s=0x7edd5098) at /home/pi/src/neovim/src/nvim/state.c:99
#7  0x001fb910 in command_line_enter (firstc=firstc@entry=58, count=count@entry=1, indent=indent@entry=0,
    clear_ccline=clear_ccline@entry=true) at /home/pi/src/neovim/src/nvim/ex_getln.c:820
#8  0x001fbe38 in getcmdline (firstc=firstc@entry=58, count=count@entry=1, indent=indent@entry=0, do_concat=do_concat@entry=true)
    at /home/pi/src/neovim/src/nvim/ex_getln.c:2601
#9  0x001fbe70 in getexline (c=58, cookie=<optimized out>, indent=0, do_concat=<optimized out>)
    at /home/pi/src/neovim/src/nvim/ex_getln.c:2846
#10 0x002106b4 in do_cmdline (cmdline=<optimized out>, fgetline=0x1fbe3c <getexline>, cookie=0x0, flags=0)
    at /home/pi/src/neovim/src/nvim/ex_docmd.c:514
#11 0x0015d104 in nv_colon (cap=0x7edd5790) at /home/pi/src/neovim/src/nvim/normal.c:3221
#12 0x001704f8 in normal_execute (state=0x7edd572c, key=<optimized out>) at /home/pi/src/neovim/src/nvim/normal.c:1181
#13 0x000b6df0 in state_enter (s=0x7edd572c) at /home/pi/src/neovim/src/nvim/state.c:99
#14 0x001673a4 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /home/pi/src/neovim/src/nvim/normal.c:478
#15 0x001b01a4 in main (argc=<optimized out>, argv=<optimized out>) at /home/pi/src/neovim/src/nvim/main.c:597
(gdb) up
#1  0x76d50364 in __GI_abort () at abort.c:79
79      abort.c: No such file or directory.
(gdb)
#2  0x001fa5c0 in cmdpreview_may_show (s=s@entry=0x7edd5098) at /home/pi/src/neovim/src/nvim/ex_getln.c:2442
2442        abort();
(gdb)
```
</details>

### OS

Observed on:
- macOS x86_64, nvim 0.10.0
- raspbian (debian) armv7l, nvim 0.9.0

### Theory

I suspect it's the same issue on the pi as on macOS - I've debugged more on the pi and it seems [`rename_buffer()` fails](https://github.com/neovim/neovim/blob/55d346fc2683a18256320eaae75eb4f3137dcced/src/nvim/ex_getln.c#L2215-L2217), caused by [a buffer name conflict / `E95`](https://github.com/neovim/neovim/blob/55d346fc2683a18256320eaae75eb4f3137dcced/src/nvim/buffer.c#L2921-L2932).

I can hack in the `BF_DUMMY` flag (on the preview buffer) to avoid this behaviour, but I end up with tons of windows open (as I toggle with `<C-E>`) and I don't believe that's a correct fix, since the buffer isn't for internal use only.
Is there some buffer cleanup code that normally runs which I'd need to trigger, or possibly something else to avoid the buffer name conflict?

### Steps to reproduce

Create this plugin:

```vim
function! IncCommandToggle()
	let prev = &inccommand

	if &inccommand ==# 'split'
		set inccommand=nosplit
	elseif &inccommand ==# 'nosplit'
		set inccommand=split
	elseif &inccommand ==# ''
		set inccommand=nosplit
	else
		throw 'unknown inccommand'
	endif

	" return a change, to trigger redraw (:redraw doesn't work)
	" (the bug occurs without this - empty string also works)
	return " \<BS>"
endfunction

cnoremap <expr> <C-E> IncCommandToggle()
```

Edit a file where you'll get a few search/replace hits.
Enter: `:%s/candidate/abc<C-E><C-E><C-E>`

Notice the first two `<C-E>` hits toggle the `inccommand` pane, and the third causes nvim to exit.

### Expected behavior

Continued `inccommand` pane toggling, no exit.

### Neovim version (nvim -v)

0.10.0 commit 55d346fc2 (macOS), 0.9.0 d215dae0e0 (raspbian)

### Vim (not Nvim) behaves the same?

n/a, no `inccommand` in vim

### Operating system/version

macOS 13.1, raspbian 11

### Terminal name/version

alacritty 0.11.0 (8dbaa0b) / tmux 3.1c

### $TERM environment variable

screen-256color (i.e. tmux)

### Installation

build from repo

### PR DESCRIPTION
**Pull request by omar25h**
Fixes #23136

### CODE REVIEW

**Comment by gpanders** [comment]
Can you please add a test to `inccommand_spec`? You can adapt the reproduction steps from #23136.

In the test, please also add a reference to the issue, e.g.

```lua
it("'inccommand' cannot be changed during preview #23136", function()
```

File: runtime/lua/vim/_meta/options.lua [hunk 1]
```diff
@@ -54,7 +54,7 @@ vim.go.ari = vim.go.allowrevins
 --- (https://www.unicode.org/reports/tr11).
 ---
 --- @type string
-vim.o.ambiwidth = "single"
+vim.o.ambiwidth = 'single'
```
Comment (clason) [inline runtime/lua/vim/_meta/options.lua:57]: Those changes should not be in this commit.

File: test/functional/ui/inccommand_spec.lua [hunk 2]
```diff
@@ -32,7 +32,7 @@ local multiline_text = [[
   7 8 9
 ]]
 
-local multimatch_text  = [[
```
Comment (clason) [inline test/functional/ui/inccommand_spec.lua:35]: Don't run stylua on the test files.

Comment (omar25h) [reply test/functional/ui/inccommand_spec.lua]: Done. Could you explain the reason why it's not run there by default?

Comment (clason) [reply test/functional/ui/inccommand_spec.lua]: Because the screen tests need to be exactly like they are, or they will fail.

File: src/nvim/optionstr.c [hunk 3]
```diff
@@ -1698,6 +1698,9 @@ const char *did_set_iconstring(optset_T *args)
 /// The 'inccommand' option is changed.
 const char *did_set_inccommand(optset_T *args FUNC_ATTR_UNUSED)
 {
+  if (cmdpreview) {
+    return e_invarg;
+  }
```
Comment (famiu) [inline src/nvim/optionstr.c:1703]: Maybe we could allow using `set inccommand` if the value has not changed? So perhaps something like:
```suggestion
  if (cmdpreview && strcmp(args->os_oldval.string, args->os_newval.string) != 0) {
    return e_invarg;
  }
```
<br />
Unsure if this is worth it though.

**Review by famiu — APPROVED** [review]

File: src/nvim/optionstr.c (hunk 3 above)
Comment (gpanders) [reply src/nvim/optionstr.c:1703]: I don't think it's worth adding any additional logic here, it just muddies the waters without providing any value. Keep it simple.
