### PR TITLE
fix: vim.lsp.omnifunc should not throw away other items

### LINKED ISSUE #32428: lsp.completion should extend completion items with results from 2nd server on different trigger characters
### Problem

With https://github.com/neovim/neovim/pull/32266 the lsp.completion auto-trigger mechanism will trigger completion items for the clients that match a given character.

For example:

client1: triggers: a
client2: triggers: b

Typing `a` will trigger client1, but typing `ab` won't trigger client2 on b unless the first client responded with `IsIncomplete`.

### Expected behavior

Triggering `b` should trigger _only_ client2, and extend the results from client1.

See discussion in the PR. We'll need either a `complete_add` extension or something like a `complete_append`. (https://github.com/neovim/neovim/pull/32266#issuecomment-2645187401)

Or some other solution altogether.

### LINKED ISSUE #35257: `complete+=o` with LSP omnifunc cancels other flags
### Problem

If 'o' is present in `'complete'`, and omnifunc is the LSP omnifunc, only LSP is used as a source for CTRL-N completion

### Steps to reproduce

```lua
vim.lsp.config('clangd', {
	cmd = { 'clangd', '--clang-tidy' },
	filetypes = { 'c', 'cpp' },
	root_markers = { '.git', 'compile_commands.json' },
})
vim.lsp.enable('clangd')

vim.o.complete = '.,o'
```

Open a C file and trigger completion with i_CTRL-N. See that buffer text is not used a completion source, only LSP

### Expected behavior

'o' flag should not cancel out other flags

### Nvim version (nvim -v)

NVIM v0.12.0-dev-972+gfa92a0b9fe

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 15.6

### Terminal name/version

ghostty

### $TERM environment variable

tmux-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by tbung**
This is a workaround to fix #35257 while https://github.com/vim/vim/pull/16662 is not resolved. It finally allows lsp completion to be combined with other sources.

Something like this can also be used to fix issue #32428, but that is somewhat more involved because we need to be smarter about tracking `isIncomplete` and filter/deduplicate items.

### CODE REVIEW

File: runtime/lua/vim/lsp/completion.lua [hunk 1]
```diff
@@ -503,7 +503,7 @@ local function trigger(bufnr, clients, ctx)
       return
     end
 
-    local matches = {}
+    local matches --[[@type table]] = vim.fn.complete_info({ 'items', 'matches' })['items']
```
Comment (glepnir) [inline runtime/lua/vim/lsp/completion.lua:506]: remove matches. it only get items which match current leader.

Comment (glepnir) [inline runtime/lua/vim/lsp/completion.lua]: Is matches needed here? When both items and matches are present, each item will have a match field. However you don't used it. So only items is needed?

Comment (tbung) [reply runtime/lua/vim/lsp/completion.lua]: Yea, good point, I had played around with #32428 and thought it might be usefull. I'll remove it.

**Comment by kristijanhusak** [comment]
Works good for me 👍🏻

**Comment by glepnir** [comment]
I experimented with a small patch that allows complete_add to extend the current compl_T linked list.

<details>

```diff
diff --git a/src/nvim/insexpand.c b/src/nvim/insexpand.c
index 329b17e6f6..8b4dca6041 100644
--- a/src/nvim/insexpand.c
+++ b/src/nvim/insexpand.c
@@ -3379,7 +3379,15 @@ void f_complete(typval_T *argvars, typval_T *rettv, EvalFuncData fptr)
 /// "complete_add()" function
 void f_complete_add(typval_T *argvars, typval_T *rettv, EvalFuncData fptr)
 {
-  rettv->vval.v_number = ins_compl_add_tv(&argvars[0], 0, false);
+  if (pum_visible()) {
+    ins_compl_add_list(argvars[0].vval.v_list);
+    if (compl_match_array) {
+      XFREE_CLEAR(compl_match_array);
+    }
+    ins_compl_show_pum();
+  } else {
+    rettv->vval.v_number = ins_compl_add_tv(&argvars[0], 0, false);
+  }
 }
```

It works under this script.
```viml
let g:async = v:false

function! AppendCandidate() abort
  if v:char == 'b'
    if g:async
      call timer_start(100, {-> complete_add([ {'word': 'bool'}, {'word': 'balon'}, {'word': 'foo'} ])})
      return
    endif
    try
      call complete_add([{'word': 'bar'}])
    catch /E1516:/
      let g:got_expected_error = 1
      return
    endtry
  endif
endfunction
set cot=menu,menuone,noinsert

inoremap <buffer> <F5> <cmd>call complete(1, ["red", "blue"])<cr>
autocmd InsertCharPre * :call AppendCandidate()
```
</details>
 But when I followed the steps in #35257, I realized the problem isn’t what I thought. f_complete calls set_completion, which resets the current compl state. So it’s not possible to keep using complete_add to append to the list there. In this context, complete_add isn’t very useful.  
 
 
 1. there can add a new paramter in `complete()` to keep the current completion items llist.. something like
 
```diff
diff --git a/runtime/lua/vim/lsp/completion.lua b/runtime/lua/vim/lsp/completion.lua
index 79a0bb950b..50ecb74e1d 100644
--- a/runtime/lua/vim/lsp/completion.lua
+++ b/runtime/lua/vim/lsp/completion.lua
@@ -503,6 +503,7 @@ local function trigger(bufnr, clients, ctx)
       return
     end

+    local keep = vim.fn.complete_info({ 'mode' }).mode == 'keyword'
     local matches = {}
     local server_start_boundary --- @type integer?
     for client_id, response in pairs(responses) do
@@ -536,7 +537,7 @@ local function trigger(bufnr, clients, ctx)
     end
     local start_col = (server_start_boundary or word_boundary) + 1
     Context.cursor = { cursor_row, start_col }
-    vim.fn.complete(start_col, matches)
+    vim.fn.complete(start_col, matches, keep)
   end)

   table.insert(Context.pending_requests, cancel_request)
diff --git a/src/nvim/eval.lua b/src/nvim/eval.lua
index d237758e7a..13d1c96f43 100644
--- a/src/nvim/eval.lua
+++ b/src/nvim/eval.lua
@@ -1337,7 +1337,7 @@ M.funcs = {
     signature = 'col({expr} [, {winid}])',
   },
   complete = {
-    args = 2,
+    args = 3,
     base = 2,
     desc = [=[
       Set the matches for Insert mode completion.
diff --git a/src/nvim/insexpand.c b/src/nvim/insexpand.c
index 329b17e6f6..b1d1f0f6fa 100644
--- a/src/nvim/insexpand.c
+++ b/src/nvim/insexpand.c
@@ -3285,7 +3285,7 @@ static void restore_orig_extmarks(void)
 ///
 /// @param startcol  where the matched text starts (1 is first column).
 /// @param list      the list of matches.
-static void set_completion(colnr_T startcol, list_T *list)
+static void set_completion(colnr_T startcol, list_T *list, int keep)
 {
   int flags = CP_ORIGINAL_TEXT;
   unsigned cur_cot_flags = get_cot_flags();
@@ -3298,7 +3298,9 @@ static void set_completion(colnr_T startcol, list_T *list)
     ins_compl_prep(' ');
   }
   ins_compl_clear();
-  ins_compl_free();
+  if (!keep) {
+    ins_compl_free();
+  }
   compl_get_longest = compl_longest;

   compl_direction = FORWARD;
@@ -3317,7 +3319,7 @@ static void set_completion(colnr_T startcol, list_T *list)
   }
   if (ins_compl_add(compl_orig_text.data, (int)compl_orig_text.size,
                     NULL, NULL, false, NULL, 0,
-                    flags | CP_FAST, false, NULL, FUZZY_SCORE_NONE) != OK) {
+                    flags | CP_FAST, keep, NULL, FUZZY_SCORE_NONE) != OK) {
     return;
   }
...skipping...
   complete = {
-    args = 2,
+    args = 3,
     base = 2,
     desc = [=[
       Set the matches for Insert mode completion.
diff --git a/src/nvim/insexpand.c b/src/nvim/insexpand.c
index 329b17e6f6..b1d1f0f6fa 100644
--- a/src/nvim/insexpand.c
+++ b/src/nvim/insexpand.c
@@ -3285,7 +3285,7 @@ static void restore_orig_extmarks(void)
 ///
 /// @param startcol  where the matched text starts (1 is first column).
 /// @param list      the list of matches.
-static void set_completion(colnr_T startcol, list_T *list)
+static void set_completion(colnr_T startcol, list_T *list, int keep)
 {
   int flags = CP_ORIGINAL_TEXT;
   unsigned cur_cot_flags = get_cot_flags();
@@ -3298,7 +3298,9 @@ static void set_completion(colnr_T startcol, list_T *list)
     ins_compl_prep(' ');
   }
   ins_compl_clear();
-  ins_compl_free();
+  if (!keep) {
+    ins_compl_free();
+  }
   compl_get_longest = compl_longest;

   compl_direction = FORWARD;
@@ -3317,7 +3319,7 @@ static void set_completion(colnr_T startcol, list_T *list)
   }
   if (ins_compl_add(compl_orig_text.data, (int)compl_orig_text.size,
                     NULL, NULL, false, NULL, 0,
-                    flags | CP_FAST, false, NULL, FUZZY_SCORE_NONE) != OK) {
+                    flags | CP_FAST, keep, NULL, FUZZY_SCORE_NONE) != OK) {
     return;
   }

@@ -3371,7 +3373,7 @@ void f_complete(typval_T *argvars, typval_T *rettv, EvalFuncData fptr)
   } else {
     const colnr_T startcol = (colnr_T)tv_get_number_chk(&argvars[0], NULL);
     if (startcol > 0) {
-      set_completion(startcol - 1, argvars[1].vval.v_list);
+      set_completion(startcol - 1, argvars[1].vval.v_list, (int)tv_get_number_chk(&argvars[2]
, NULL));
     }
   }
 }

```

It works.. I dont' test with `autocomplete` option.. because i only glanced at the code of it . I'll take a look at the details when I have time.

image


current C implementation cannot merge completion items from multiple sources, especially when those sources are asynchronous. I’ve started working on asynchronous insert-mode completion locally( progress is only **1** percent at the moment 😂). Most of the logic is implemented in lua and using coroutine for async,  `vim._completion` interface to chain multiple sources and custom callbacks.  C side call back into Lua to handle the default insert-mode completion ..

**Comment by tbung** [comment]
Really cool, thank you!

So would you propose to go forward with your patch to `complete`, or with this PR? Of course proper async ins-completion would be huge, but I think we should implement some workaround for this while that is being worked on, just so that builtin completion is fully functional.

**Comment by glepnir** [comment]
only issue is the memory allocation efficiency when items is large. However, I think it should be acceptable 🤔.  PR make sense :)

**Comment by przepompownia** [comment]
While `keep` in `vim.fn.complete` has no default value, I needed to add any 

```diff
diff --git a/runtime/lua/vim/snippet.lua b/runtime/lua/vim/snippet.lua
index 29e2487bff..ab66030446 100644
--- a/runtime/lua/vim/snippet.lua
+++ b/runtime/lua/vim/snippet.lua
@@ -331,7 +331,7 @@ local function display_choices(tabstop)
   end

   vim.defer_fn(function()
-    vim.fn.complete(start_col, matches)
+    vim.fn.complete(start_col, matches, false)
   end, 100)
 end

@@ -349,8 +349,9 @@ local function select_tabstop(tabstop)
   local mode = vim.fn.mode()

   if vim.fn.pumvisible() ~= 0 then
     -- Close the choice completion menu if open.
-    vim.fn.complete(vim.fn.col('.'), {})
+    vim.fn.complete(vim.fn.col('.'), {}, false)
   end

   -- Move the cursor to the start of the tabstop.
```

to the above patch (not sure yet if the value from `complete_info` make sense).

Edit: use false in both cases to keep choice list working.

**Comment by kristijanhusak** [comment]
Any updates on this?

**Comment by przepompownia** [comment]
I simply used this patch for those six weeks to experiment how `ac` can behave with `cpt+=o` and `vim.lsp.omnifunc`. Cases I had to focus on first was Vim specific. IIRC I encountered some minor issues that I didn't want to distract from my current work, but I can say that this patch allows at least to maintain minimal usability in this configuration (unlike on the master branch).

"Rebased" @glepnir's diff with a snippets survival fix from me:
```diff
diff --git a/runtime/lua/vim/lsp/completion.lua b/runtime/lua/vim/lsp/completion.lua
index 01f36cfc9f..8be76e5d0e 100644
--- a/runtime/lua/vim/lsp/completion.lua
+++ b/runtime/lua/vim/lsp/completion.lua
@@ -502,6 +502,7 @@ local function trigger(bufnr, clients, ctx)
       return
     end
 
+    local keep = vim.fn.complete_info({ 'mode' }).mode == 'keyword'
     local matches = {}
     local server_start_boundary --- @type integer?
     for client_id, response in pairs(responses) do
@@ -535,7 +536,7 @@ local function trigger(bufnr, clients, ctx)
     end
     local start_col = (server_start_boundary or word_boundary) + 1
     Context.cursor = { cursor_row, start_col }
-    vim.fn.complete(start_col, matches)
+    vim.fn.complete(start_col, matches, keep)
   end)
 
   table.insert(Context.pending_requests, cancel_request)
diff --git a/runtime/lua/vim/snippet.lua b/runtime/lua/vim/snippet.lua
index c147d4b88a..978efdbf33 100644
--- a/runtime/lua/vim/snippet.lua
+++ b/runtime/lua/vim/snippet.lua
@@ -331,7 +331,7 @@ local function display_choices(tabstop)
   end
 
   vim.defer_fn(function()
-    vim.fn.complete(start_col, matches)
+    vim.fn.complete(start_col, matches, false)
   end, 100)
 end
 
@@ -350,7 +350,7 @@ local function select_tabstop(tabstop)
 
   if vim.fn.pumvisible() ~= 0 then
     -- Close the choice completion menu if open.
-    vim.fn.complete(vim.fn.col('.'), {})
+    vim.fn.complete(vim.fn.col('.'), {}, false)
   end
 
   -- Move the cursor to the start of the tabstop.
diff --git a/src/nvim/eval.lua b/src/nvim/eval.lua
index eb3dae7ce5..26a73f49b4 100644
--- a/src/nvim/eval.lua
+++ b/src/nvim/eval.lua
@@ -1337,7 +1337,7 @@ M.funcs = {
     signature = 'col({expr} [, {winid}])',
   },
   complete = {
-    args = 2,
+    args = 3,
     base = 2,
     desc = [=[
       Set the matches for Insert mode completion.
diff --git a/src/nvim/insexpand.c b/src/nvim/insexpand.c
index 31ae200866..e0a610db35 100644
--- a/src/nvim/insexpand.c
+++ b/src/nvim/insexpand.c
@@ -3367,7 +3367,7 @@ static void restore_orig_extmarks(void)
 ///
 /// @param startcol  where the matched text starts (1 is first column).
 /// @param list      the list of matches.
-static void set_completion(colnr_T startcol, list_T *list)
+static void set_completion(colnr_T startcol, list_T *list, int keep)
 {
   int flags = CP_ORIGINAL_TEXT;
   unsigned cur_cot_flags = get_cot_flags();
@@ -3380,7 +3380,9 @@ static void set_completion(colnr_T startcol, list_T *list)
     ins_compl_prep(' ');
   }
   ins_compl_clear();
-  ins_compl_free();
+  if (!keep) {
+    ins_compl_free();
+  }
   compl_get_longest = compl_longest;
 
   compl_direction = FORWARD;
@@ -3399,7 +3401,7 @@ static void set_completion(colnr_T startcol, list_T *list)
   }
   if (ins_compl_add(compl_orig_text.data, (int)compl_orig_text.size,
                     NULL, NULL, false, NULL, 0,
-                    flags | CP_FAST, false, NULL, FUZZY_SCORE_NONE) != OK) {
+                    flags | CP_FAST, keep, NULL, FUZZY_SCORE_NONE) != OK) {
     return;
   }
 
@@ -3453,7 +3455,7 @@ void f_complete(typval_T *argvars, typval_T *rettv, EvalFuncData fptr)
   } else {
     const colnr_T startcol = (colnr_T)tv_get_number_chk(&argvars[0], NULL);
     if (startcol > 0) {
-      set_completion(startcol - 1, argvars[1].vval.v_list);
+      set_completion(startcol - 1, argvars[1].vval.v_list, (int)tv_get_number_chk(&argvars[2], NULL));
     }
   }
 }
```

**Comment by justinmk** [comment]
Merged to "stop the bleeding". A test would be valuable as a followup, perhaps with the other patch discussed here.

**Comment by mfussenegger** [comment]
Looks like this can lead to duplicate completion candidates in combination with `isIncomplete` if the follow up request returns the same items as the items that were retained.


Can we revert this and go with the proper fix?

**Comment by clason** [comment]
I was wondering why my LSP autocompletion results were suddenly a mess...

**Comment by glepnir** [comment]
maybe could use vim.list_unique 🤔, but its time complexity will increase as the number of items grows. didn't test this diff😮‍💨 reply on phone :)
 
```diff
diff --git a/runtime/lua/vim/lsp/completion.lua b/runtime/lua/vim/lsp/completion.lua
index 729cada68a..7f080b2204 100644
--- a/runtime/lua/vim/lsp/completion.lua
+++ b/runtime/lua/vim/lsp/completion.lua
@@ -503,6 +503,7 @@ local function trigger(bufnr, clients, ctx)
     end

     local matches --[[@type table]] = vim.fn.complete_info({ 'items' })['items']
+    local isIncomplete = Context.isIncomplete
     local server_start_boundary --- @type integer?
     for client_id, response in pairs(responses) do
       local client = lsp.get_client_by_id(client_id)
@@ -531,6 +532,11 @@ local function trigger(bufnr, clients, ctx)
           encoding
         )
         vim.list_extend(matches, client_matches)
+        if isIncomplete then
+          matches = vim.list.unique(matches, function(m)
+            return m.label
+          end)
+        end
       end
     end
     local start_col = (server_start_boundary or word_boundary) + 1
```

**Comment by tbung** [comment]
I never encounter that case while making this PR, sorry for breaking stuff!

I do agree that there should be a proper fix instead of `vim.list.unique`, except maybe as a hotfix. Would something like https://github.com/neovim/neovim/pull/35346#issuecomment-3193665378 be the proper way to do this? Should I create a PR with the `vim.list.unique` hotfix (and tests this time) or is someone else already on it?

**Comment by justinmk** [comment]
> Should I create a PR with the `vim.list.unique` hotfix (and tests this time)

please do, thanks!
