### PR TITLE
fix(lsp): cycling signatures with the default `config.focusable`

### LINKED ISSUE #33630: LSP: show all signatures in `signature_help`
### Problem

Right now hover indicates that there are overloads to a function and how many there are in addition to the one it shows. However there is currently no built-in way to list these overloads. Neither with `vim.lsp.buf.hover()` nor with `vim.lsp.buf.signature_help()`.

### Expected behavior

`vim.lsp.buf.hover()` and/or `vim.lsp.buf.signature_help()` should have a way to show all overloads as a list or cycle through them.

### PR DESCRIPTION
**Pull request by ofseed**
Closes https://github.com/neovim/neovim/issues/33630.

`config.focusable` is generally nil, but the default is `true`. https://github.com/neovim/neovim/pull/31775 makes signatures will not be displayed or cycled unless `config.focusable = true` is explicitly set. @MariaSolOs, I'd like to understand what problem this PR is trying to solve, it seems that setting mappings for windows with `focusable = false` is harmless. 

Also added a fix (possibly a feature) to display the `activeSignature` on the first call.

### CODE REVIEW

**Comment by MariaSolOs** [comment]
> Hmmm, CI failed due to the revert message being too long. Should I try to reduce the length?

Yes

**Comment by MariaSolOs** [comment]
> @MariaSolOs, I'd like to understand what problem this PR is trying to solve, it seems that setting mappings for windows with `focusable = false` is harmless.

It was a UI fix. There's no point in having a message in the window title for a keymap that isn't available.

File: runtime/lua/vim/lsp/buf.lua [hunk 1]
```diff
@@ -381,7 +385,7 @@ function M.signature_help(config)
         return
       end
 
-      local sfx = can_cycle and string.format(' (%d/%d) (<C-s> to cycle)', idx, total) or ''
+      local sfx = total > 1 and string.format(' (%d/%d) (<C-s> to cycle)', idx, total) or ''
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/buf.lua:388]: I still think we should check that `config.focusable ~= false` here. The cycle keymap is irrelevant if you can't focus the signature help window.

Comment (ofseed) [reply runtime/lua/vim/lsp/buf.lua:388]: I noticed this, but should we keep `(index/total)` and remove the key hints next to it?

**Comment by ofseed** [comment]
> Yes

Revert PRs generally include the complete commit information of the original revert PR. Should I delete the excessively long parts?

**Comment by MariaSolOs** [comment]
> Revert PRs generally include the complete commit information of the original revert PR. Should I delete the excessively long parts?

Yeah. This PR isn't really reverting https://github.com/neovim/neovim/pull/31775 anyway so it's better to use something more descriptive of all the changes you're making.

**Comment by ofseed** [comment]
Thanks. I kept `can_cycle`, so that commit is no longer a revert PR.

**Review by justinmk — APPROVED** [review]
Looking forward to this!
