### PR TITLE
fix(tui): fix piping output make nvim unusable

### LINKED ISSUE #18470: Piping NodeJS output into Neovim makes the editor unusable
### Neovim version (nvim -v)

```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 25 2022 22:13:25)

### Operating system/version

Arch Linux

### Terminal name/version

```
alacritty 0.10.1 (2844606d)
```

### $TERM environment variable

```
alacritty
```

### Installation

Arch Linux Repository (`sudo pacman -S neovim`)

### How to reproduce the issue

```
node -e 'console.log("test")' | nvim -u <(echo "let s:test = system('echo test')") -
```

### Expected behavior

I expect to be able to use the `hjkl` keys to move the cursor.

Using the following commands works fine:

- `node -e 'console.log("test")' | nvim -u <(echo '') -`
- `echo 'test' | nvim -u <(echo "let s:test = system('echo test')") -`
- `python -c 'print("test")'| nvim -u <(echo "let s:test = system('echo test')") -`

Also, piping the NodeJS output into vim also works:

- `node -e 'console.log("test")' | vim -u <(echo "let s:test = system('echo test')") -`

So there must be some weird thing happening when Neovim is trying to read from stdin from a NodeJS process, and when the `system` function is called in the config. The same thing happens if the config file contains a line like `silent execute !echo test`.

```
$ node --version
v18.1.0

$ echo $SHELL
/usr/bin/zsh

$ zsh --version
zsh 5.8.1 (x86_64-pc-linux-gnu)
```

Happens in bash too.

### Actual behavior

The cursor key letters just end up overwriting the editor content on the screen, and when I press CTRL+C it exits.

### PR DESCRIPTION
**Pull request by KevinSJ**
As discussed in the issue, ui_call_mode_change() should not be called when starting is true.

This will close #18470

### CODE REVIEW

**Comment by justinmk** [comment]
@erw7  notes: https://github.com/neovim/neovim/issues/18470#issuecomment-1153117726

**Comment by justinmk** [comment]
seeing some consistent failures in the job tests, even after retrying those CI jobs twice.

    jobs jobstart() works when closure passed directly to `jobstart`: 5.95 ms OK

File: src/nvim/ui.c [hunk 1]
```diff
@@ -520,7 +521,7 @@ void ui_flush(void)
     api_free_array(style);
     pending_mode_info_update = false;
   }
-  if (pending_mode_update) {
+  if (pending_mode_update && !starting) {
```
Comment (justinmk) [inline src/nvim/ui.c:524]: why are we only guarding `pending_mode_update` and not the other potential updates? 

Maybe we need to delay `ui_flush()` entirely?

Comment (KevinSJ) [reply src/nvim/ui.c:524]: Based on this comment from @erw7 https://github.com/neovim/neovim/issues/18470#issuecomment-1126636767, my understanding is that this issue is caused by mode transition occured incorrectly during the ui_flush (due to node changing the state of the tty on exit, according to that comment). So we should only need to guard against `pending_mode_update`, and I think delaying `ui_flush` would not solve this issue because the state change to the tty caused by node would still remain.

**Comment by KevinSJ** [comment]
@justinmk I'll take a look at the failed test in the next day or two. Merged the master in just in case the failing tests are caused by some commits that my branch missed from master.

**Comment by KevinSJ** [comment]
@justinmk looks like the failling tests passed after rebasing master branch. The two macos checks that failed are about missing lua require which should not relate to this change.

File: src/nvim/ui.c (hunk 1 above)
Comment (erw7) [reply src/nvim/ui.c:518]: Delaying `ui_flush()` also solves this problem. The reason I haven't done so in the https://github.com/neovim/neovim/issues/18470#issuecomment-1153117726 patch is that I'm not sure that delaying the entire `ui_flush()` would cause any other problems. This change is almost a workaround. While it may be better to create a new event and send it to the UI with `VimEnter`, the reason I suggested this simplified method is due to the tradeoff between the importance of the problem being solved and the effort involved.

**Comment by erw7** [comment]
> seeing some consistent failures in the job tests, even after retrying those CI jobs twice.

I have confirmed the following steps and do not believe the root cause is this change. Even `master` do not complete the test to the end. 


```
BUSTED_ARGS="--repeat=100 --no-keep-going" TEST_FILE=test/functional/core/job_spec.lua make functionaltest
```

I attached to a stopped `nvim` and took a backtrace as follows. If the `nvim` exit is close to the end of the job, it cannot detect that the process has ended and seems to be stopped waiting for the end.

<details>
<summary>backtrace</summary>

```
#0  0x00007f752087442a in epoll_wait (epfd=10, events=events@entry=0x7ffc503d4fe0, maxevents=maxevents@entry=1024, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x000056395461b487 in uv__io_poll (loop=loop@entry=0x563954806dc0 <main_loop>, timeout=<optimized out>) at /home/erw7/src/github.com/neovim/neovim/.deps/build/src/libuv/src/unix/epoll.c:236
#2  0x000056395460773c in uv_run (loop=0x563954806dc0 <main_loop>, mode=UV_RUN_ONCE) at /home/erw7/src/github.com/neovim/neovim/.deps/build/src/libuv/src/unix/core.c:389
#3  0x0000563954380722 in loop_poll_events (loop=0x563954806dc0 <main_loop>, ms=-1) at ../src/nvim/event/loop.c:60
#4  0x000056395438254e in process_teardown (loop=0x563954806dc0 <main_loop>) at ../src/nvim/event/process.c:141
#5  0x0000563954423660 in event_teardown () at ../src/nvim/main.c:145
#6  0x000056395442431c in os_exit (r=0) at ../src/nvim/main.c:588
#7  0x0000563954469a50 in exit_event (argv=0x7ffc503d81d8) at ../src/nvim/msgpack_rpc/channel.c:527
#8  0x00005639543813b2 in multiqueue_process_events (this=0x563954be0520) at ../src/nvim/event/multiqueue.c:153
#9  0x0000563954380775 in loop_poll_events (loop=0x563954806dc0 <main_loop>, ms=0) at ../src/nvim/event/loop.c:68
#10 0x0000563954382f1c in flush_stream (proc=0x563954c848f0, stream=0x563954c84ad8) at ../src/nvim/event/process.c:368
#11 0x000056395438301e in process_close_handles (argv=0x7ffc503d82e8) at ../src/nvim/event/process.c:389
#12 0x000056395455d45f in state_handle_k_event () at ../src/nvim/state.c:106
#13 0x000056395448056a in nv_event (cap=0x7ffc503d8470) at ../src/nvim/normal.c:7229
#14 0x0000563954472756 in normal_execute (state=0x7ffc503d83f0, key=-26365) at ../src/nvim/normal.c:1157
#15 0x000056395455d3ef in state_enter (s=0x7ffc503d83f0) at ../src/nvim/state.c:88
#16 0x00005639544708f4 in normal_enter (cmdwin=false, noexmode=false) at ../src/nvim/normal.c:450
#17 0x00005639544242d2 in main (argc=13, argv=0x7ffc503d8788) at ../src/nvim/main.c:571

#0  0x00007f752087442a in epoll_wait (epfd=10, events=events@entry=0x7ffc503d4fe0, maxevents=maxevents@entry=1024, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
        resultvar = 18446744073709551612
        sc_ret = <optimized out>
#1  0x000056395461b487 in uv__io_poll (loop=loop@entry=0x563954806dc0 <main_loop>, timeout=<optimized out>) at /home/erw7/src/github.com/neovim/neovim/.deps/build/src/libuv/src/unix/epoll.c:236
        no_epoll_pwait_cached = 0
        no_epoll_wait_cached = 0
        no_epoll_pwait = <optimized out>
        no_epoll_wait = <optimized out>
        events = {{events = 2892687, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 22073, data = {ptr = 0x563954806ff0 <main_loop+560>, fd = 1417703408, u32 = 1417703408, u64 = 94804230828016}}, {events = 1422809776, data = {ptr = 0x503d524000000030, fd = 48, u32 = 48, u64 = 5781867931444969520}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 1346195624, data = {ptr = 0x92f3a40000000019, fd = 25, u32 = 25, u64 = 10588987468785123353}}, {events = 3223134276, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 1421823104, data = {ptr = 0x1100005639, fd = 22073, u32 = 22073, u64 = 73014466105}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 1421822968, data = {ptr = 0x54806dc000005639, fd = 22073, u32 = 22073, u64 = 6088987367606081081}}, {events = 22073, data = {ptr = 0x563954bf4c80, fd = 1421823104, u32 = 1421823104, u64 = 94804234947712}}, {events = 1415654216, data = {ptr = 0x5639, fd = 22073, u32 = 22073, u64 = 22073}}, {events = 0, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 0, data = {ptr = 0x546187ef00000000, fd = 0, u32 = 0, u64 = 6080290432493813760}}, {events = 22073, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 2465440768, data = {ptr = 0xb4cc01d2044, fd = -1071833020, u32 = 3223134276, u64 = 12424268554308}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 1346195868, data = {ptr = 0x503d519000007ffc, fd = 32764, u32 = 32764, u64 = 5781867175530758140}}, {events = 32764, data = {ptr = 0x563954806ff0 <main_loop+560>, fd = 1417703408, u32 = 1417703408, u64 = 94804230828016}}, {events = 1415688341, data = {ptr = 0x503d511000005639, fd = 22073, u32 = 22073, u64 = 5781866625774933561}}, {events = 32764, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x2c238f, fd = 2892687, u32 = 2892687, u64 = 2892687}}, {events = 0, data = {ptr = 0x54806ff000000000, fd = 0, u32 = 0, u64 = 6088989772787744768}}, {events = 22073, data = {ptr = 0x3000000001, fd = 1, u32 = 1, u64 = 206158430209}}, {events = 1421823104, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 1415688135, data = {ptr = 0x503d517000005639, fd = 22073, u32 = 22073, u64 = 5781867038091793977}}, {events = 32764, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x503d52f800007ffc, fd = 32764, u32 = 32764, u64 = 5781868721718984700}}, {events = 0, data = {ptr = 0x2c238f, fd = 2892687, u32 = 2892687, u64 = 2892687}}, {events = 0, data = {ptr = 0x54806ff000007ffc, fd = 32764, u32 = 32764, u64 = 6088989772787777532}}, {events = 22073, data = {ptr = 0x3000000001, fd = 1, u32 = 1, u64 = 206158430209}}, {events = 2892686, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x563954806ff0 <main_loop+560>, fd = 1417703408, u32 = 1417703408, u64 = 94804230828016}}, {events = 2465440768, data = {ptr = 0x503d51e0c01d2044, fd = -1071833020, u32 = 3223134276, u64 = 5781867522351243332}}, {events = 32764, data = {ptr = 0x56395432c53e <eval2+64>, fd = 1412613438, u32 = 1412613438, u64 = 94804225738046}}, {events = 17, data = {ptr = 0xffffffff, fd = -1, u32 = 4294967295, u64 = 4294967295}}, {events = 1, data = {ptr = 0x7ffc503d52b0, fd = 1346196144, u32 = 1346196144, u64 = 140721654682288}}, {events = 1346196120, data = {ptr = 0x200007ffc, fd = 32764, u32 = 32764, u64 = 8589967356}}, {events = 1, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 2465440768, data = {ptr = 0x503d5240c01d2044, fd = -1071833020, u32 = 3223134276, u64 = 5781867934668103748}}, {events = 32764, data = {ptr = 0x56395432c357 <eval1+60>, fd = 1412612951, u32 = 1412612951, u64 = 94804225737559}}, {events = 1346197968, data = {ptr = 0x92f3a40000007ffc, fd = 32764, u32 = 32764, u64 = 10588987468785156092}}, {events = 3223134276, data = {ptr = 0x8, fd = 8, u32 = 8, u64 = 8}}, {events = 1422405251, data = {ptr = 0x503d524000005639, fd = 22073, u32 = 22073, u64 = 5781867931444991545}}, {events = 32764, data = {ptr = 0x3a5437552d, fd = 1412912429, u32 = 1412912429, u64 = 250521015597}}, {events = 1346196032, data = {ptr = 0x542fe58300007ffc, fd = 32764, u32 = 32764, u64 = 6066319573894856700}}, {events = 22073, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 1422405250, data = {ptr = 0x503d540000005639, fd = 22073, u32 = 22073, u64 = 5781869855590340153}}, {events = 32764, data = {ptr = 0x5639543779c5 <get_func_tv+768>, fd = 1412921797, u32 = 1412921797, u64 = 94804226046405}}, {events = 1422405124, data = {ptr = 0x503d546000005639, fd = 22073, u32 = 22073, u64 = 5781870267907200569}}, {events = 32764, data = {ptr = 0x7ffc503d5990, fd = 1346197904, u32 = 1346197904, u64 = 140721654684048}}, {events = 1346197968, data = {ptr = 0x54c82e0700007ffc, fd = 32764, u32 = 32764, u64 = 6109183502127759356}}, {events = 3, data = {ptr = 0x563954c35fe0, fd = 1422090208, u32 = 1422090208, u64 = 94804235214816}}, {events = 1346196144, data = {ptr = 0x543f5dba00007ffc, fd = 32764, u32 = 32764, u64 = 6070673876164050940}}, {events = 1, data = {ptr = 0xffffffff, fd = -1, u32 = 4294967295, u64 = 4294967295}}, {events = 1422405250, data = {ptr = 0x400005639, fd = 22073, u32 = 22073, u64 = 17179891257}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 2, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x563900000000, fd = 0, u32 = 0, u64 = 94802813124608}}, {events = 1422097776, data = {ptr = 0xa00005639, fd = 22073, u32 = 22073, u64 = 42949695033}}, {events = 0, data = {ptr = 0x111e1a, fd = 1121818, u32 = 1121818, u64 = 1121818}}, {events = 1422405127, data = {ptr = 0x54c37e3800005639, fd = 22073, u32 = 22073, u64 = 6107864298627814969}}, {events = 22073, data = {ptr = 0x7ffc503d5320, fd = 1346196256, u32 = 1346196256, u64 = 140721654682400}}, {events = 1413438906, data = {ptr = 0x503d581000005639, fd = 22073, u32 = 22073, u64 = 5781874322356327993}}, {events = 32764, data = {ptr = 0x3, fd = 3, u32 = 3, u64 = 3}}, {events = 1422405124, data = {ptr = 0x54c37d7000005639, fd = 22073, u32 = 22073, u64 = 6107863439634355769}}, {events = 0, data = {ptr = 0x3, fd = 3, u32 = 3, u64 = 3}}, {events = 1422405124, data = {ptr = 0x300005639, fd = 22073, u32 = 22073, u64 = 12884923961}}, {events = 0, data = {ptr = 0x563954c82e04, fd = 1422405124, u32 = 1422405124, u64 = 94804235529732}}, {events = 1422731024, data = {ptr = 0x503d538000005639, fd = 22073, u32 = 22073, u64 = 5781869305834526265}}, {events = 32764, data = {ptr = 0x563954282800 <_start>, fd = 1411917824, u32 = 1411917824, u64 = 94804225042432}}, {events = 1413821410, data = {ptr = 0x503d53b000005639, fd = 22073, u32 = 22073, u64 = 5781869511992956473}}, {events = 32764, data = {ptr = 0x4, fd = 4, u32 = 4, u64 = 4}}, {events = 1422090208, data = {ptr = 0x400005639, fd = 22073, u32 = 22073, u64 = 17179891257}}, {events = 0, data = {ptr = 0x7ffc503d53b0, fd = 1346196400, u32 = 1346196400, u64 = 140721654682544}}, {events = 1413821533, data = {ptr = 0x54c82e0400005639, fd = 22073, u32 = 22073, u64 = 6109183489242846777}}, {events = 22073, data = {ptr = 0x56395455e457 <vim_strchr+70>, fd = 1414915159, u32 = 1414915159, u64 = 94804228039767}}, {events = 0, data = {ptr = 0x546db04a00000061, fd = 97, u32 = 97, u64 = 6083712503521476705}}, {events = 22073, data = {ptr = 0x7ffc503d53e0, fd = 1346196448, u32 = 1346196448, u64 = 140721654682592}}, {events = 1414915159, data = {ptr = 0x5639, fd = 22073, u32 = 22073, u64 = 22073}}, {events = 0, data = {ptr = 0x563954c82e8b, fd = 1422405259, u32 = 1422405259, u64 = 94804235529867}}, {events = 1346209664, data = {ptr = 0x54c82e8a00007ffc, fd = 32764, u32 = 32764, u64 = 6109184064768475132}}, {events = 22073, data = {ptr = 0x7ffc503d5400, fd = 1346196480, u32 = 1346196480, u64 = 140721654682624}}, {events = 1412425091, data = {ptr = 0x300005639, fd = 22073, u32 = 22073, u64 = 12884923961}}, {events = 2, data = {ptr = 0x563954c82e8b, fd = 1422405259, u32 = 1422405259, u64 = 94804235529867}}, {events = 1346196528, data = {ptr = 0x5433783800007ffc, fd = 32764, u32 = 32764, u64 = 6067325304911724540}}, {events = 22073, data = {ptr = 0x7ffc503d5440, fd = 1346196544, u32 = 1346196544, u64 = 140721654682688}}, {events = 1346197904, data = {ptr = 0x7ffc, fd = 32764, u32 = 32764, u64 = 32764}}, {events = 6, data = {ptr = 0x563954c82e8b, fd = 1422405259, u32 = 1422405259, u64 = 94804235529867}}, {events = 1346196640, data = {ptr = 0x7ffc, fd = 32764, u32 = 32764, u64 = 32764}}, {events = 0, data = {ptr = 0x7ffc503d54a0, fd = 1346196640, u32 = 1346196640, u64 = 140721654682784}}, {events = 1412665259, data = {ptr = 0x503d550800005639, fd = 22073, u32 = 22073, u64 = 5781870989461706297}}, {events = 32764, data = {ptr = 0x7ffc503d5500, fd = 1346196736, u32 = 1346196736, u64 = 140721654682880}}, {events = 1422405253, data = {ptr = 0x100005639, fd = 22073, u32 = 22073, u64 = 4294989369}}, {events = 0, data = {ptr = 0x7ffc503d5930, fd = 1346197808, u32 = 1346197808, u64 = 140721654683952}}, {events = 1346197904, data = {ptr = 0x503d54a000007ffc, fd = 32764, u32 = 32764, u64 = 5781870542785118204}}, {events = 1, data = {ptr = 0x5639542fe583 <skipwhite+46>, fd = 1412425091, u32 = 1412425091, u64 = 94804225549699}}, {events = 1416504692, data = {ptr = 0x5639, fd = 22073, u32 = 22073, u64 = 22073}}, {events = 1086, data = {ptr = 0x7ffc503d70d0, fd = 1346203856, u32 = 1346203856, u64 = 140721654690000}}, {events = 0, data = {ptr = 0x503d574000000000, fd = 0, u32 = 0, u64 = 5781873429003108352}}, {events = 32764, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 1346197808, data = {ptr = 0x503d599000007ffc, fd = 32764, u32 = 32764, u64 = 5781875971623780348}}, {events = 32764, data = {ptr = 0x7ffc503d5810, fd = 1346197520, u32 = 1346197520, u64 = 140721654683664}}, {events = 6, data = {ptr = 0x503d550000000001, fd = 1, u32 = 1, u64 = 5781870955101945857}}, {events = 1, data = {ptr = 0x5639542fe583 <skipwhite+46>, fd = 1412425091, u32 = 1412425091, u64 = 94804225549699}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x563954c82e85, fd = 1422405253, u32 = 1422405253, u64 = 94804235529861}}, {events = 0, data = {ptr = 0x54c82e8500000000, fd = 0, u32 = 0, u64 = 6109184043293605888}}, {events = 22073, data = {ptr = 0x100000000, fd = 0, u32 = 0, u64 = 4294967296}}, {events = 1346197520, data = {ptr = 0x54c82e8500007ffc, fd = 32764, u32 = 32764, u64 = 6109184043293638652}}, {events = 22073, data = {ptr = 0x1000, fd = 4096, u32 = 4096, u64 = 4096}}, {events = 4, data = {ptr = 0xd6800000001, fd = 1, u32 = 1, u64 = 14740327759873}}, {events = 0, data = {ptr = 0xc01d204492f3a400, fd = -1829526528, u32 = 2465440768, u64 = 13843256308502078464}}, {events = 1422811584, data = {ptr = 0x54cd271000005639, fd = 22073, u32 = 22073, u64 = 6110583219084613177}}, {events = 22073, data = {ptr = 0x7ffc503d55e0, fd = 1346196960, u32 = 1346196960, u64 = 140721654683104}}, {events = 1412616950, data = {ptr = 0x54c82df500005639, fd = 22073, u32 = 22073, u64 = 6109183424818337337}}, {events = 22073, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 1346197808, data = {ptr = 0x503d599000007ffc, fd = 32764, u32 = 32764, u64 = 5781875971623780348}}, {events = 32764, data = {ptr = 0x7ffc503d58c0, fd = 1346197696, u32 = 1346197696, u64 = 140721654683840}}, {events = 18302, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x5639546e2574, fd = 1416504692, u32 = 1416504692, u64 = 94804229629300}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7ffc503d5640, fd = 1346197056, u32 = 1346197056, u64 = 140721654683200}}, {events = 1412616950, data = {ptr = 0x1542a62d00000424, fd = 1060, u32 = 1060, u64 = 1531969535463130148}}, {events = 0, data = {ptr = 0xc01d204492f3a400, fd = -1829526528, u32 = 2465440768, u64 = 13843256308502078464}}, {events = 1346197344, data = {ptr = 0x92f3a40000007ffc, fd = 32764, u32 = 32764, u64 = 10588987468785156092}}, {events = 3223134276, data = {ptr = 0x563954cd2710, fd = 1422731024, u32 = 1422731024, u64 = 94804235855632}}, {events = 1411917824, data = {ptr = 0x503d593000005639, fd = 22073, u32 = 22073, u64 = 5781875559306909241}}, {events = 32764, data = {ptr = 0x56395437477e <encode_vim_to_nothing+161>, fd = 1412908926, u32 = 1412908926, u64 = 94804226033534}}, {events = 0, data = {ptr = 0x546e257400000000, fd = 0, u32 = 0, u64 = 6083841326770552832}}, {events = 22073, data = {ptr = 0x7ffc503d70d0, fd = 1346203856, u32 = 1346203856, u64 = 140721654690000}}, {events = 0, data = {ptr = 0x546f755100000000, fd = 0, u32 = 0, u64 = 6084210612353630208}}, {events = 22073, data = {ptr = 0x43e92f3a400, fd = -1829526528, u32 = 2465440768, u64 = 4666799924224}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x563954738d32, fd = 1416858930, u32 = 1416858930, u64 = 94804229983538}}, {events = 1346198912, data = {ptr = 0x503d56a700000001, fd = 1, u32 = 1, u64 = 5781872771873112065}}, {events = 32764, data = {ptr = 0xc01d204492f3a400, fd = -1829526528, u32 = 2465440768, u64 = 13843256308502078464}}, {events = 1422731024, data = {ptr = 0x5428280000005639, fd = 22073, u32 = 22073, u64 = 6064140878719505977}}, {events = 22073, data = {ptr = 0x7ffc503d56b0, fd = 1346197168, u32 = 1346197168, u64 = 140721654683312}}, {events = 1412912429, data = {ptr = 0x5639, fd = 22073, u32 = 22073, u64 = 22073}}, {events = 0, data = {ptr = 0x7ffc503d59d0, fd = 1346197968, u32 = 1346197968, u64 = 140721654684112}}, {events = 1, data = {ptr = 0x92f3a40000000000, fd = 0, u32 = 0, u64 = 10588987468785123328}}, {events = 1, data = {ptr = 0x7ffc503d57c0, fd = 1346197440, u32 = 1346197440, u64 = 140721654683584}}, {events = 1412689759, data = {ptr = 0x100005639, fd = 22073, u32 = 22073, u64 = 4294989369}}, {events = 0, data = {ptr = 0x100000000, fd = 0, u32 = 0, u64 = 4294967296}}, {events = 0, data = {ptr = 0x800000000, fd = 0, u32 = 0, u64 = 34359738368}}, {events = 0, data = {ptr = 0x7ffc503d56e8, fd = 1346197224, u32 = 1346197224, u64 = 140721654683368}}, {events = 1, data = {ptr = 0x100007ffc, fd = 32764, u32 = 32764, u64 = 4295000060}}, {events = 0, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 1, data = {ptr = 0x300005639, fd = 22073, u32 = 22073, u64 = 12884923961}}, {events = 0, data = {ptr = 0x7f752093d8a0 <_IO_helper_jumps>, fd = 546560160, u32 = 546560160, u64 = 140141034461344}}, {events = 3432, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x563954738d32, fd = 1416858930, u32 = 1416858930, u64 = 94804229983538}}, {events = 123, data = {ptr = 0x546f742000000000, fd = 0, u32 = 0, u64 = 6084209302388604928}}, {events = 22073, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 8, data = {ptr = 0x503d575800000000, fd = 0, u32 = 0, u64 = 5781873532082323456}}, {events = 32764, data = {ptr = 0xc01d204492f3a400, fd = -1829526528, u32 = 2465440768, u64 = 13843256308502078464}}, {events = 1346197456, data = {ptr = 0x5432c89c00007ffc, fd = 32764, u32 = 32764, u64 = 6067132220361965564}}, {events = 22073, data = {ptr = 0x7f752093d8a0 <_IO_helper_jumps>, fd = 546560160, u32 = 546560160, u64 = 140141034461344}}, {events = 2465440768, data = {ptr = 0x503d593000000000, fd = 0, u32 = 0, u64 = 5781875559306887168}}, {events = 32764, data = {ptr = 0x7ffc503d5990, fd = 1346197904, u32 = 1346197904, u64 = 140721654684048}}, {events = 1346197440, data = {ptr = 0x5437552d00007ffc, fd = 32764, u32 = 32764, u64 = 6068412674666954748}}, {events = 0, data = {ptr = 0x7ffc00000002, fd = 2, u32 = 2, u64 = 140720308486146}}, {events = 1422405259, data = {ptr = 0x546e38f300005639, fd = 22073, u32 = 22073, u64 = 6083862762952349241}}, {events = 22073, data = {ptr = 0x192f3a400, fd = -1829526528, u32 = 2465440768, u64 = 6760408064}}, {events = 1346197552, data = {ptr = 0x92f3a40000007ffc, fd = 32764, u32 = 32764, u64 = 10588987468785156092}}, {events = 3223134276, data = {ptr = 0x7ffc503d5830, fd = 1346197552, u32 = 1346197552, u64 = 140721654683696}}, {events = 1412613864, data = {ptr = 0x503d59d000005639, fd = 22073, u32 = 22073, u64 = 5781876246501676601}}, {events = 32764, data = {ptr = 0x503d5990, fd = 1346197904, u32 = 1346197904, u64 = 1346197904}}, {events = 1346197808, data = {ptr = 0x503d599000007ffc, fd = 32764, u32 = 32764, u64 = 5781875971623780348}}, {events = 32764, data = {ptr = 0x100000002, fd = 2, u32 = 2, u64 = 4294967298}}, {events = 1, data = {ptr = 0x100000000, fd = 0, u32 = 0, u64 = 4294967296}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 2, data = {ptr = 0x92f3a40000000000, fd = 0, u32 = 0, u64 = 10588987468785123328}}, {events = 3223134276, data = {ptr = 0x7ffc503d5890, fd = 1346197648, u32 = 1346197648, u64 = 140721654683792}}, {events = 1412613438, data = {ptr = 0x503d5de000005639, fd = 22073, u32 = 22073, u64 = 5781880713267664441}}, {events = 32764, data = {ptr = 0x503d5e00, fd = 1346199040, u32 = 1346199040, u64 = 1346199040}}, {events = 1346197808, data = {ptr = 0x503d599000007ffc, fd = 32764, u32 = 32764, u64 = 5781875971623780348}}, {events = 32764, data = {ptr = 0x100000064, fd = 100, u32 = 100, u64 = 4294967396}}, {events = 0, data = {ptr = 0x2093d8a000000000, fd = 0, u32 = 0, u64 = 2347458012496527360}}, {events = 32629, data = {ptr = 0xd68, fd = 3432, u32 = 3432, u64 = 3432}}, {events = 0, data = {ptr = 0x92f3a40000000000, fd = 0, u32 = 0, u64 = 10588987468785123328}}, {events = 3223134276, data = {ptr = 0x7ffc503d58f0, fd = 1346197744, u32 = 1346197744, u64 = 140721654683888}}, {events = 1412612951, data = {ptr = 0x54738d3400005639, fd = 22073, u32 = 22073, u64 = 6085362775985509945}}, {events = 22073, data = {ptr = 0x92f3a400, fd = -1829526528, u32 = 2465440768, u64 = 2465440768}}, {events = 1346197808, data = {ptr = 0x503d599000007ffc, fd = 32764, u32 = 32764, u64 = 5781875971623780348}}, {events = 32764, data = {ptr = 0x7ffc503d58f0, fd = 1346197744, u32 = 1346197744, u64 = 140721654683888}}, {events = 1412912429, data = {ptr = 0x503d58f000000061, fd = 97, u32 = 97, u64 = 5781875284428980321}}, {events = 32764, data = {ptr = 0x5639542fe583 <skipwhite+46>, fd = 1412425091, u32 = 1412425091, u64 = 94804225549699}}, {events = 0, data = {ptr = 0x54c82e8b00000000, fd = 0, u32 = 0, u64 = 6109184069063409664}}, {events = 22073, data = {ptr = 0x7ffc503d5950, fd = 1346197840, u32 = 1346197840, u64 = 140721654683984}}, {events = 1412613281, data = {ptr = 0x503d592000005639, fd = 22073, u32 = 22073, u64 = 5781875490587432505}}, {events = 32764, data = {ptr = 0x5639542fe583 <skipwhite+46>, fd = 1412425091, u32 = 1412425091, u64 = 94804225549699}}, {events = 1346197968, data = {ptr = 0x92f3a40000007ffc, fd = 32764, u32 = 32764, u64 = 10588987468785156092}}, {events = 3223134276, data = {ptr = 0x563954cd2710, fd = 1422731024, u32 = 1422731024, u64 = 94804235855632}}, {events = 1411917824, data = {ptr = 0x503d596000005639, fd = 22073, u32 = 22073, u64 = 5781875765465339449}}, {events = 32764, data = {ptr = 0x56395437552d <tv_clear+57>, fd = 1412912429, u32 = 1412912429, u64 = 94804226037037}}...}
        pe = <optimized out>
        e = {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
        real_timeout = <optimized out>
        q = <optimized out>
        w = <optimized out>
        sigset = {__val = {0, 1, 0, 94804228802543, 140721654682272, 0, 2892, 687356550, 140721654681600, 13843256308502078464, 0, 94804228812743, 140721654681616, 0, 140720308486144, 0}}
        sigmask = <optimized out>
        base = <optimized out>
        have_signals = <optimized out>
        nevents = <optimized out>
        count = <optimized out>
        nfds = <optimized out>
        fd = <optimized out>
        op = <optimized out>
        i = <optimized out>
        user_timeout = <optimized out>
        reset_timeout = <optimized out>
        __PRETTY_FUNCTION__ = "uv__io_poll"
#2  0x000056395460773c in uv_run (loop=0x563954806dc0 <main_loop>, mode=UV_RUN_ONCE) at /home/erw7/src/github.com/neovim/neovim/.deps/build/src/libuv/src/unix/core.c:389
        timeout = <optimized out>
        r = <optimized out>
        ran_pending = <optimized out>
#3  0x0000563954380722 in loop_poll_events (loop=0x563954806dc0 <main_loop>, ms=-1) at ../src/nvim/event/loop.c:60
        mode = UV_RUN_ONCE
        timeout_expired = false
#4  0x000056395438254e in process_teardown (loop=0x563954806dc0 <main_loop>) at ../src/nvim/event/process.c:141
        remaining = -1
        before = 0
#5  0x0000563954423660 in event_teardown () at ../src/nvim/main.c:145
No locals.
#6  0x000056395442431c in os_exit (r=0) at ../src/nvim/main.c:588
        __func__ = "os_exit"
#7  0x0000563954469a50 in exit_event (argv=0x7ffc503d81d8) at ../src/nvim/msgpack_rpc/channel.c:527
No locals.
#8  0x00005639543813b2 in multiqueue_process_events (this=0x563954be0520) at ../src/nvim/event/multiqueue.c:153
        event = {handler = 0x563954469a28 <exit_event>, argv = {0x7f7520941be0 <main_arena+96>, 0x7, 0x563954be001c, 0x78, 0x563900000008, 0x0, 0x0, 0x7ffc503d4a98, 0x563954bf3821, 0x1}}
        __PRETTY_FUNCTION__ = "multiqueue_process_events"
#9  0x0000563954380775 in loop_poll_events (loop=0x563954806dc0 <main_loop>, ms=0) at ../src/nvim/event/loop.c:68
        mode = UV_RUN_NOWAIT
        timeout_expired = false
#10 0x0000563954382f1c in flush_stream (proc=0x563954c848f0, stream=0x563954c84ad8) at ../src/nvim/event/process.c:368
        num_bytes = 8
        system_buffer_size = 212992
        err = 0
        max_bytes = 213000
#11 0x000056395438301e in process_close_handles (argv=0x7ffc503d82e8) at ../src/nvim/event/process.c:389
        proc = 0x563954c848f0
#12 0x000056395455d45f in state_handle_k_event () at ../src/nvim/state.c:106
        event = {handler = 0x563954382fe9 <process_close_handles>, argv = {0x563954c848f0, 0x0, 0x5639544533e2 <try_malloc+50>, 0x7ffc503d4cf0, 0x78, 0x563954cd1430, 0x78, 0x7ffc503d4b70, 0xc01d204492f3a400, 0x1503d4c90}}
#13 0x000056395448056a in nv_event (cap=0x7ffc503d8470) at ../src/nvim/normal.c:7229
        may_restart = false
#14 0x0000563954472756 in normal_execute (state=0x7ffc503d83f0, key=-26365) at ../src/nvim/normal.c:1157
        s = 0x7ffc503d83f0
        __PRETTY_FUNCTION__ = "normal_execute"
#15 0x000056395455d3ef in state_enter (s=0x7ffc503d83f0) at ../src/nvim/state.c:88
        check_result = 1
        key = -26365
        execute_result = 1
#16 0x00005639544708f4 in normal_enter (cmdwin=false, noexmode=false) at ../src/nvim/normal.c:450
        state = {state = {check = 0x563954472c2f <normal_check>, execute = 0x563954471f99 <normal_execute>}, command_finished = false, ctrl_w = false, need_flushbuf = false, set_prevcount = false, previous_got_int = false, cmdwin = false, noexmode = false, toplevel = true, oa = {op_type = 0, regname = 0, motion_type = kMTCharWise, motion_force = 0, use_reg_one = false, inclusive = false, end_adjusted = false, start = {lnum = 0, col = 0, coladd = 0}, end = {lnum = 0, col = 0, coladd = 0}, cursor_start = {lnum = 0, col = 0, coladd = 0}, line_count = 0, empty = false, is_VIsual = false, start_vcol = 0, end_vcol = 0, prev_opcount = 0, prev_count0 = 0, excl_tr_ws = false}, ca = {oap = 0x7ffc503d8408, prechar = 0, cmdchar = -26365, nchar = 0, ncharC1 = 0, ncharC2 = 0, extra_char = 0, opcount = 0, count0 = 0, count1 = 1, arg = 0, retval = 0, searchbuf = 0x0}, mapped_len = 0, old_mapped_len = 0, idx = 184, c = -26365, old_col = 0, old_pos = {lnum = 1, col = 0, coladd = 0}}
#17 0x00005639544242d2 in main (argc=13, argv=0x7ffc503d8788) at ../src/nvim/main.c:571
        fname = 0x0
        params = {argc = 13, argv = 0x7ffc503d8788, use_vimrc = 0x7ffc503d9ef5 "NONE", clean = false, n_commands = 0, commands = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, cmds_tofree = "\000\000\000\000\000\000\000\000\000", n_pre_commands = 3, pre_commands = {0x7ffc503d9f08 "set shortmess+=IS background=light noswapfile noautoindent startofline laststatus=1 undodir=. directory=. viewdir=. backupdir=. belloff= wildoptions-=pum joinspaces noshowcmd noruler nomore redrawdebu"..., 0x7ffc503d9fe0 "mapclear", 0x7ffc503d9fef "mapclear!", 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, edit_type = 0, tagname = 0x0, use_ef = 0x0, input_isatty = false, output_isatty = false, err_isatty = false, input_neverscript = false, no_swap_file = 0, use_debug_break_level = -1, window_count = 1, window_layout = 0, diff_mode = 0, listen_addr = 0x0, remote = 0, server_addr = 0x0}
        cwd = 0x0
        __PRETTY_FUNCTION__ = "main"
        use_remote_ui = false
        use_builtin_ui = false
        vimrc_none = true
        __func__ = "main"
```
</details>

File: src/nvim/ui.c [hunk 2]
```diff
@@ -18,6 +18,7 @@
 #include "nvim/ex_getln.h"
 #include "nvim/fold.h"
 #include "nvim/garray.h"
+#include "nvim/globals.h"
```
Comment (erw7) [inline src/nvim/ui.c:21]: I don't think it is necessary because it is included in the following section of `vim.h`.

https://github.com/neovim/neovim/blob/7b2b44bce4bff85d9fd1bef09d294ddb889056e4/src/nvim/vim.h#L296

Comment (KevinSJ) [reply src/nvim/ui.c]: Thanks, I've removed this

**Review by erw7 — APPROVED** [review]

**Comment by justinmk** [comment]
> If the `nvim` exit is close to the end of the job, it cannot detect that the process has ended and seems to be stopped waiting for the end.

This reminds me of https://github.com/neovim/neovim/pull/15501 where we fixed a similar issue w/ jobwait().

File: src/nvim/ui.c (hunk 2 above)
Comment (justinmk) [reply src/nvim/ui.c]: Just for reference: technically the "include what you use" goal (https://github.com/neovim/neovim/issues/549) dictates that we don't want to depend on transitive includes.

File: src/nvim/ui.c (hunk 1 above)
Comment (justinmk) [reply src/nvim/ui.c:517]: > tradeoff between the importance of the problem being solved and the effort involved.

:+1: also "remote/coprocess TUI" https://github.com/neovim/neovim/pull/18375 changes the architecture entirely, so best to wait on that.

**Comment by erw7** [comment]
> If the nvim exit is close to the end of the job, it cannot detect that the process has ended and seems to be stopped waiting for the end.

I was wrong about this. After careful review of the backtrace, I found that the problem was that `os_exit` was being called during the process termination process. I have created #19082 to correct it.

**Comment by erw7** [comment]
Incidentally, the changes in #15501 do not solve any problems, as the rationale shown next.

First, `proc->events` and `chan->events` refer to the same thing, as shown below.

https://github.com/neovim/neovim/blob/88a5941598f706f447c92137521fcaf9137920fc/src/nvim/channel.c#L349

Next, the parent of `chan->events` is changed to `waiting_jobs` as shown below.

https://github.com/neovim/neovim/blob/88a5941598f706f447c92137521fcaf9137920fc/src/nvim/eval/funcs.c#L5329

Thus, the `MultiQueue` object (`waiting_jobs`) passed as the argument of `process_wait` becomes the parent of `proc->events` of all processes waiting for termination. If you read [`multiqueue_push()`](https://github.com/neovim/neovim/blob/88a5941598f706f447c92137521fcaf9137920fc/src/nvim/event/multiqueue.c#L229) and [`multiqueueitem_get_event()`](https://github.com/neovim/neovim/blob/88a5941598f706f447c92137521fcaf9137920fc/src/nvim/event/multiqueue.c#L188), it is clear that if you process the parent `MultiQueue`, all events of the child `MultiQueue` will also be processed. Therefore, even if the parent `MultiQueue` (`waiting_jobs`) is processed, `process_close_event` in `proc->events` will be processed without any problem.

However, since all events by other processes in `waiting_jobs` should have been handled by the earlier part of `process_wait`, #15501 will not cause any problems.
