### PR TITLE
fix(appimage): wrong $ARCH used by linuxdeploy

### LINKED ISSUE #36423: Nightly build appimage serves 32 bit elf instead of 64 bit.
### Problem

Problem: Downloading the latest aarch64-linux nightly release provides a 32-bit ELF rather than a 64-elf. 

Further Description:
Downloading 'nvim-linux-arm64.appimage' from https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-arm64.appimage
with sha256sum: `88d0cfc42dafade14e12cb4fdc9e760b7b76fd01a78ef0e78cec8d6580e98df4`

Running `file nvim-linux-arm64.appimage`
produces `nvim-linux-arm64.appimage: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), static-pie linked, BuildID[sha1]=1a9abc749122c8bb76290e5e39fb5f1a3014458b, stripped`

This produces an: `exec format error: ./nvim-linux-arm64.appimage`
when attempting to run.

Previous versions downloaded in the last week have worked correctly, one example of file:
ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), static-pie linked, BuildID[sha1]=8b1028122120dc38a9b51955cb51306a870c2b5f, stripped
This version is: `NVIM v0.12.0-dev-1537+g6dd6c5b523` which was correctly serving 64-bit!

### Steps to reproduce

`wget https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-arm64.appimage`
`file nvim-linux-arm64.appimage`
`chmod u+x nvim-linux-arm64.appimage`
`./nvim-linux-arm64.appimage`

### Expected behavior

File is a 32-bit instead of 64-bit elf executable. 

### Nvim version (nvim -v)

b92b95e2c26d5cea86acd3116ee029cc57676f14

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Fedora release 42 (Adams) (arm64)

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

appimage

### PR DESCRIPTION
**Pull request by yusiwen**
fix #36423 

Problem:
In scripts/genappimage.sh running on arm64 host, the $ARCH will be set to 'arm64' before calling linuxdeploy, which cause linuxdeploy to generate an 32bit ELF executable instead 64bit. See the [issue](https://github.com/neovim/neovim/issues/36423) for more details. 

Solution:
Keep $ARCH unchanged, use $ARCH_OUTPUT in the output file name. On arm64 host, $ARCH_OUTPUT will be converted to 'arm64'.

### CODE REVIEW

File: scripts/genappimage.sh [hunk 1]
```diff
@@ -78,28 +78,28 @@ cd "$APP_BUILD_DIR" || exit # Get out of AppImage directory.
 
 # We want to be consistent, so always use arm64 over aarch64
 if [[ "$ARCH" == 'aarch64' ]]; then
```
Comment (justinmk) [inline scripts/genappimage.sh]: since you set ARCH_OUTPUT=ARCH above, seems clearer to check ARCH_OUTPUT here?
```suggestion
if [[ "$ARCH_OUTPUT" == 'aarch64' ]]; then
```

**Review by justinmk — APPROVED** [review]

File: scripts/genappimage.sh (hunk 1 above)
Comment (yusiwen) [reply scripts/genappimage.sh]: Both are fine. Before this test,  $ARCH and $ARCH_OUTPUT are the same value. If on arm64 host, ARCH_OUTPUT should be changed to 'arm64' to follow the naming convention of packaing, while $ARCH  still keeps untouched with value 'aarch64', because $ARCH must be 'aarch64' for linuxdeploy to generate the correct 64-bit ELF executable.

Comment (justinmk) [reply scripts/genappimage.sh]: Yes, the suggestion is for clarity of purpose.

File: scripts/genappimage.sh [hunk 2]
```diff
@@ -77,29 +77,29 @@ chmod 755 AppRun
 cd "$APP_BUILD_DIR" || exit # Get out of AppImage directory.
 
 # We want to be consistent, so always use arm64 over aarch64
-if [[ "$ARCH" == 'aarch64' ]]; then
-  ARCH="arm64"
-  export ARCH
+if [[ "$ARCH_OUTPUT" == 'aarch64' ]]; then
+  ARCH_OUTPUT="arm64"
+  export ARCH_OUTPUT
```
Comment (justinmk) [inline scripts/genappimage.sh]: we don't need to "export" this, right? can drop this line.

Comment (justinmk) [inline scripts/genappimage.sh]:
```suggestion
```

File: scripts/genappimage.sh [hunk 3]
```diff
@@ -77,29 +77,28 @@ chmod 755 AppRun
 cd "$APP_BUILD_DIR" || exit # Get out of AppImage directory.
 
 # We want to be consistent, so always use arm64 over aarch64
-if [[ "$ARCH" == 'aarch64' ]]; then
-  ARCH="arm64"
-  export ARCH
+if [[ "$ARCH_OUTPUT" == 'aarch64' ]]; then
```
Comment (justinmk) [inline scripts/genappimage.sh]:
```suggestion
if [[ "$ARCH" == 'aarch64' ]]; then
```

File: scripts/genappimage.sh [hunk 4]
```diff
@@ -78,28 +78,27 @@ cd "$APP_BUILD_DIR" || exit # Get out of AppImage directory.
 
 # We want to be consistent, so always use arm64 over aarch64
 if [[ "$ARCH" == 'aarch64' ]]; then
```
Comment (justinmk) [inline scripts/genappimage.sh]:
```suggestion
if [[ "$ARCH_OUTPUT" == 'aarch64' ]]; then
```
