### PR TITLE
[RFC] Close wildmenu before redrawing statusline

### LINKED ISSUE #8385: Wildmenu remains visible.
### Steps to reproduce
```
nvim -u NORC
:h<Tab><Space>
```

### Actual behaviour
Wildmenu remains visible.

### Expected behaviour
Wildmenu should disappear. According to the docs and Vim behavior:
> The "wildmenu" mode is abandoned when a key is hit that is not used for selecting a completion.

Note that `wildmenumode()` does return 0.

NVIM v0.3.0-1211-g3a6b80f2f (also happening on NVIM v0.2.2)
Vim 8.0 behaves differently.
Linux, Termite. `$TERM` = `xterm-termite`.

### PR DESCRIPTION
**Pull request by akarle**
Hello! First time opening a PR here! I have a simple change that will hopefully fix #8385.

## Description

I found that in `ex_getln.c`, when a character not used by the wildmenu is pressed (not <TAB>, CTRL-P, etc) the check to close the wildmenu is already in the code at line 620.

The bug is that `redraw_statuslines()` is called before the global `wild_menu_showing` is set to 0.

`redraw_statuslines`(screen.c) calls `win_redr_status` (screen.c) which will return early if `wild_menu_showing != 0`. Thus without the one line commit I posted, the status line is not redrawn, causing the issue.

By simply setting `wild_menu_showing = 0` prior to calling `redraw_statuslines`, the issue seems to be fixed (I am no longer able to reproduce).

---

This all said, I'm new to the code base and I'm not 100% confident this will fix all cases! I'd love any input and help / feedback!

Thank you!

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks for the effort! Next step is to add a test to `test/functional/ui/wildmode_spec.lua`, see a31482db4dca for example.  

You can [run the locally](https://github.com/neovim/neovim/blob/master/test/README.md#running-tests) like this:

    TEST_FILE=test/functional/ui/wildmode_spec.lua make functionaltest

>  I'm new to the code base and I'm not 100% confident this will fix all cases! I'd love any input and help / feedback!

I would look in Vim's source for all cases of `wild_menu_showing` to see if there's a hint about where/when that's done. Then use `:Gblame` from [fugitive](https://github.com/tpope/vim-fugitive/) to see when the line was changed / read the Vim commit details for hints.

**Comment by akarle** [comment]
I did some grepping and git blaming and it appears c695443 is the culprit, specifically the following in `win_redr_status` (screen.c):

```diff
-  /* It's possible to get here recursively when 'statusline' (indirectly)
-   * invokes ":redrawstatus".  Simply ignore the call then. */
-  if (busy)
+  // May get here recursively when 'statusline' (indirectly)
+  // invokes ":redrawstatus".  Simply ignore the call then.
+  if (busy
+      // Also ignore if wildmenu is showing.
+      || (wild_menu_showing != 0 && !ui_is_external(kUIWildmenu))) {
```

I tried to checkout the code before this commit to verify that it was indeed the culprit, but the build failed due to a bad url (now a 404). Any tips on how to get around this (other than going in and updating urls) to try old builds?

Still, I'm fairly certain this is it--Vim's source code still only returns early if busy, thus they don't experience the bug if the status-line is open and wild_menu_showing != 0.

File: test/functional/ui/wildmode_spec.lua [hunk 1]
```diff
@@ -31,6 +31,21 @@ describe("'wildmenu'", function()
     ]])
   end)
 
+  it(':sign <tab> <space> hides wildmenu, selects design, when laststatus=2 #8453', function()
```
Comment (justinmk) [inline test/functional/ui/wildmode_spec.lua]: what does "selects design" mean? Can just be:

    it(':sign <tab> <space> hides wildmenu #8453', function()

Comment (akarle) [reply test/functional/ui/wildmode_spec.lua]: Ok! I'll change it--it was originally there because pressing the `<space>` selects the first option from the wildmenu ('design').

I agree though--a bit long and confusing for a test name.

File: test/functional/ui/wildmode_spec.lua [hunk 2]
```diff
@@ -31,6 +31,21 @@ describe("'wildmenu'", function()
...
+    command('set laststatus=2')
+    command('set wildmenu')
+    feed(':sign <tab> ')
+    screen:expect([[
+                               |
+      ~                        |
+      ~                        |
+      [No Name]                |
+      :sign define ^            |
+    ]])
```
Comment (justinmk) [inline test/functional/ui/wildmode_spec.lua]: To add more rigor to the test, let's add an extra `screen:expect()` before the `<space>` is input:

```lua
     feed(':sign <tab>')
     screen:expect([[
                                |
       ~                        |
       ~                        |
       define  jump  list  >    |
       :sign define^             |
     ]])
     feed('<space>')
     screen:expect([[
                                |
       ~                        |
       ~                        |
       [No Name]                |
       :sign define ^            |
     ]])
```

After that LGTM! I tested the patch locally and didn't find any new regressions.

**Comment by justinmk** [comment]
> I tried to checkout the code before this commit to verify that it was indeed the culprit, but the build failed due to a bad url (now a 404). Any tips on how to get around this (other than going in and updating urls) to try old builds?

Sadly no, other than using system libs (instead of the "bundled" libs that Nvim's build automatically installs for you). 

>  c695443 is the culprit

For future reference, it's always good to include such info in the commit message.

File: test/functional/ui/wildmode_spec.lua (hunk 2 above)
Comment (akarle) [reply test/functional/ui/wildmode_spec.lua]: Awesome! I'll make the change--thank you for the guidance!
