### PR TITLE
fix(ui): forward 'rulerformat' to msg_ruler event

### LINKED ISSUE #35682: 'rulerformat' is not passed on to msg_ruler event
### Problem

When `vim._extui` is enabled, the `rulerformat` option gets ignored(or overwritten by the default value).
Running `:se rulerformat` shows user defined value, but it's not reflected in the displayed ruler.
Disabling `vim._extui` restores expected `rulerformat` behaviour.

### Steps to reproduce

```bash
nvim --clean
```
```vim
:se laststatus=0
:se rulerformat=testing
:lua require("vim._extui").enable { enable = true }
" displayed ruler reverts to default option
:se rulerformat
" shows user defined option
:lua require("vim._extui").enable { enable = false }
" ruler uses the custom format setting
```

### Expected behavior

`rulerformat` option should be respected when `vim._extui` is enabled.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-1172+g1cb1cfead0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch linux

### Terminal name/version

kitty 0.42.2

### $TERM environment variable

xterm-kitty

### Installation

AUR: neovim-git

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  A 'rulerformat' not part of the statusline is not emitted through
          msg_ruler events.
Solution: Build the message chunks to emit as a msg_ruler event.

Fix #35682

### CODE REVIEW

File: src/nvim/statusline.c [hunk 1]
```diff
@@ -332,31 +334,54 @@ static void win_redr_custom(win_T *wp, bool draw_winbar, bool draw_ruler)
...
+    int textlen = (int)(sp->start ? sp->start - p : buf + len - p);
+    // Make all characters printable. Use an empty string instead of p, if p is beyond buf + len.
+    size_t tsize = transstr_buf(p >= buf + len ? "" : p, textlen, transbuf, sizeof transbuf, true);
+    if (!external) {
+      col += grid_line_puts(col, transbuf, (int)tsize, curattr);
+    } else {
+      Array chunk = ARRAY_DICT_INIT;
+      ADD(chunk, INTEGER_OBJ(curattr));
+      ADD(chunk, STRING_OBJ(cbuf_as_string(xmemdupz(transbuf, tsize), tsize)));
+      ADD(chunk, INTEGER_OBJ(curgroup));
```
Comment (luukvbaal) [inline src/nvim/statusline.c:359]: Caveat here that this does not convey combined highlight groups. Would need to adapt the "message chunks" API signature to include that.

Just making it `[attr_id, text, group_id, combine_id]` would technically be non-breaking I suppose. IDK if we would then include a 0 `combine_id` in other places. And/or if a breaking change removing `attr_id` and making `group_id` an array (so it can be passed to `nvim_buf_set_extmark()` directly) should be considered @bfredl.

File: src/nvim/api/vim.c [hunk 2]
```diff
@@ -2141,8 +2141,8 @@ DictAs(eval_statusline_ret) nvim_eval_statusline(String str, Dict(eval_statuslin
     if (opts->use_winbar) {
       fillchar = wp->w_p_fcs_chars.wbr;
     } else {
-      int attr;
-      fillchar = fillchar_status(&attr, wp);
+      int group;
```
Comment (zeertzjq) [inline src/nvim/api/vim.c]:
```suggestion
      hlf_T group;
```

File: src/nvim/cmdexpand.c [hunk 3]
```diff
@@ -577,7 +573,9 @@ static void redraw_wildmenu(expand_T *xp, int num_matches, char **matches, int m
     }
   }
 
-  schar_T fillchar = fillchar_status(&attr, curwin);
+  int len, group;
```
Comment (zeertzjq) [inline src/nvim/cmdexpand.c]:
```suggestion
  int len;
  hlf_T group;
```

File: src/nvim/statusline.c [hunk 4]
```diff
@@ -92,15 +91,16 @@ void win_redr_status(win_T *wp)
     redraw_custom_statusline(wp);
   }
 
+  int group = HLF_C;
```
Comment (zeertzjq) [inline src/nvim/statusline.c]:
```suggestion
  hlf_T group = HLF_C;
```

File: src/nvim/statusline.c [hunk 5]
```diff
@@ -210,13 +210,12 @@ void stl_fill_click_defs(StlClickDefinition *click_defs, StlClickRecord *click_r
...
-static void win_redr_custom(win_T *wp, bool draw_winbar, bool draw_ruler)
+/// When "external" is true emit a UI-event instead (only for ruler currently).
+static void win_redr_custom(win_T *wp, bool draw_winbar, bool draw_ruler, bool external)
 {
   static bool entered = false;
-  int attr;
-  int row;
   int col = 0;
-  int maxwidth;
+  int attr, group, row, maxwidth;
```
Comment (zeertzjq) [inline src/nvim/statusline.c]:
```suggestion
  hlf_T group;
  int attr, row, maxwidth;
```

File: src/nvim/statusline.c [hunk 6]
```diff
@@ -423,43 +448,21 @@ void redraw_ruler(void)
...
-    off = 0;
-    width = Columns;
-    part_of_status = true;
-  } else {
-    fillchar = schar_from_ascii(' ');
-    attr = HL_ATTR(HLF_MSG);
-    width = Columns;
-    off = 0;
-  }
+  int group = HLF_MSG;
```
Comment (zeertzjq) [inline src/nvim/statusline.c]:
```suggestion
  hlf_T group = HLF_MSG;
```

File: src/nvim/statusline.c [hunk 7]
```diff
@@ -542,13 +549,13 @@ void redraw_ruler(void)
 }
 
 /// Get the character to use in a status line.  Get its attributes in "*attr".
-schar_T fillchar_status(int *attr, win_T *wp)
+schar_T fillchar_status(int *group, win_T *wp)
```
Comment (zeertzjq) [inline src/nvim/statusline.c]:
```suggestion
schar_T fillchar_status(hlf_T *group, win_T *wp)
```

File: src/nvim/statusline.c [hunk 8]
```diff
@@ -332,31 +335,54 @@ static void win_redr_custom(win_T *wp, bool draw_winbar, bool draw_ruler)
...
     } else {
-      curattr = highlight_user[hltab[n].userhl - 1];
+      int *userhl = (wp != NULL && wp != curwin && wp->w_status_height != 0)
+                    ? highlight_stlnc : highlight_user;
+      char userbuf[5] = "Userx";
+      userbuf[4] = (char)sp->userhl + '0';
+      curattr = userhl[sp->userhl - 1];
+      curgroup = syn_name2id_len(userbuf, 5);
     }
+    curattr = hl_combine_attr(attr, curattr);
```
Comment (zeertzjq) [inline src/nvim/statusline.c]: Why are `User*` highlights now also combined with `StatusLine`?

File: src/nvim/statusline.c [hunk 9]
```diff
@@ -469,6 +473,10 @@ void redraw_ruler(void)
     wp->w_p_list = true;
   }
 
+  // Check if not in Insert mode and the line is empty (will show "0-1").
+  int empty_line = (State & MODE_INSERT) == 0
+                   && *ml_get_buf(wp->w_buffer, wp->w_cursor.lnum) == NUL;
```
Comment (zeertzjq) [inline src/nvim/statusline.c:478]:
```suggestion
  bool empty_line = (State & MODE_INSERT) == 0
                    && *ml_get_buf(wp->w_buffer, wp->w_cursor.lnum) == NUL;
```

File: src/nvim/statusline.c (hunk 8 above)
Comment (luukvbaal) [reply src/nvim/statusline.c]: For consistency's sake

Comment (zeertzjq) [inline src/nvim/statusline.c]: I don't think you should call `hl_combine_attr()` when `curattr == attr`.

Comment (luukvbaal) [reply src/nvim/statusline.c]: I added an early return, which I thought was already there.

EDIT: this caused an [error](https://github.com/neovim/neovim/actions/runs/17615122534/job/50046174279?pr=35707#step:10:10057) for some reason...

File: src/nvim/statusline.c [hunk 10]
```diff
@@ -210,13 +210,13 @@ void stl_fill_click_defs(StlClickDefinition *click_defs, StlClickRecord *click_r
 
 /// Redraw the status line, window bar or ruler of window "wp".
 /// When "wp" is NULL redraw the tab pages line from 'tabline'.
-static void win_redr_custom(win_T *wp, bool draw_winbar, bool draw_ruler)
+/// When "external" is true emit a UI-event instead (only for ruler currently).
+static void win_redr_custom(win_T *wp, bool draw_winbar, bool draw_ruler, bool external)
```
Comment (justinmk) [inline src/nvim/statusline.c]: nit: "External" is not a great name for this concept. Besides the fact that all UIs are technically external, the distinction is more like "default UI" vs "extensible/structured UI". 

So `ext_ui` is perhaps a more common name that avoids some confusion.

The only other place that use "external" is `win_config.c`, so this isn't a very common thing.

**Review by justinmk — APPROVED** [review]
Isn't this relevant to existing UIs, so worth mentioning in news.txt ?

File: src/nvim/statusline.c (hunk 10 above)
Comment (luukvbaal) [reply src/nvim/statusline.c]: I've read "_externalize_" in various places, but yes you're right that it is also used as short for "UI _extensions_" in others. Externalize does show up a few times with `grep "externalize" **/*`, and even in `api-ui-events.txt`. But happy to change it.

**Comment by luukvbaal** [comment]
A UI that has implemented the event correctly will just benefit from this automatically. I added a news entry regardless.

File: src/nvim/statusline.c (hunk 10 above)
Comment (justinmk) [reply src/nvim/statusline.c]: > I've read "_externalize_" in various places,

yeah, that's old stuff that we need to clean up. Avoiding it reduces the cleanup work.
