### PR TITLE
:terminal : set topline based on window height

### LINKED ISSUE #8324: Terminal window position should be at the bottom of terminal buffer
- `nvim --version`: `NVIM v0.3.0-1184-g4744142`
- Vim (version: ) behaves differently? N/A
- Operating system/version: `CentOS 6.9`
- Terminal name/version: `iterm2 3.1.6`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:terminal
i
less <nvim_repo>/src/nvim/terminal.c
<C-\><C-n>:10split
```
So far, so good:
screen shot 2018-04-28 at 3 40 26 pm

Now, hit `i` to enter insert mode and the top window starts showing the top of the terminal buffer instead of the bottom:
screen shot 2018-04-28 at 3 42 21 pm

The `:` prompt is no longer visible in the top window, making it useless.

### PR DESCRIPTION
**Pull request by mrbiggfoot**
If the same terminal buffer is displayed in multiple windows of different size, `adjust_topline()` behaves incorrectly because it sets top line based on terminal buffer height. This diff fixes #8324.

### CODE REVIEW

**Comment by mrbiggfoot** [comment]
In my environment all the tests pass (`make test`):
```
[==========] 616 tests from 29 test files ran. (81656.64 ms total)
[  PASSED  ] 616 tests.
```

**Comment by mrbiggfoot** [comment]
I had to bring back the bits of https://github.com/neovim/neovim/commit/cc8f477d18ef872b1f8850213a23c4fe333f2fcf to make sure the terminal content is of the right size. Combined with `adjust_topline()` fix and https://github.com/neovim/neovim/pull/8249, it should be closer to the right behavior.

**Comment by justinmk** [comment]
> I had to bring back the bits of cc8f477 to make sure the terminal content is of the right size

That's fine, but can you make it so that the _width_ is never decreased? Only explicit `jobresize()` should decrease `:terminal` width. At least until we do some basic detection to see if the terminal job is a shell (the common case for truncating screen text).

**Comment by mrbiggfoot** [comment]
Also, I'm getting `terminal/mouse_spec.lua` failures:
```
test/functional/ui/screen.lua:307: Row 1 did not match.
Expected:
  |*{7: 27 }line                 │line29                  |
  |{7: 28 }line                 │line30                  |
  |{7: 29 }line                 │rows: 5, cols: 25       |
  |{7: 30 }line                 │mouse enabled           |
  |{7: 31 }                     │{1: }                       |
  |==========                ==========              |
  |{3:-- TERMINAL --}                                    |
Actual:
  |*{7: 27 }line                 │line30                  |
  |{7: 28 }line                 │rows: 5, cols: 25       |
  |{7: 29 }line                 │rows: 5, cols: 24       |
  |{7: 30 }line                 │mouse enabled           |
  |{7: 31 }                     │{1: }                       |
  |==========                ==========              |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.

stack traceback:
        test/functional/ui/screen.lua:307: in function 'wait'
        test/functional/ui/screen.lua:221: in function 'expect'
        test/functional/terminal/mouse_spec.lua:142: in function <test/functional/terminal/mouse_spec.lua:98>
```

I have not had enough time to understand the unit test framework. @justinmk is this failure substantial?

**Comment by mrbiggfoot** [comment]
Disclaimer: the unit test modification was done without understanding the failure reasons.

**Comment by justinmk** [comment]
Removed 49ee7ab5ee9c3c6f34cdb4069aaef02ba0f6fbaa and 00b6f736dbaffe951691f1319d2cdda5a2d9cc7a (which are addressed by https://github.com/neovim/neovim/pull/9551) and rebased.

Will write at test for this, then merge.

File: src/nvim/terminal.c [hunk 1]
```diff
@@ -1321,7 +1321,7 @@ static void adjust_topline(Terminal *term, buf_T *buf, long added)
       if (following || (wp == curwin && is_focused(term))) {
         // "Follow" the terminal output
         wp->w_cursor.lnum = ml_end;
-        set_topline(wp, MAX(wp->w_cursor.lnum - height + 1, 1));
+        set_topline(wp, MAX(wp->w_cursor.lnum - wp->w_height_inner + 1, 1));
```
Comment (justinmk) [inline src/nvim/terminal.c]: @bfredl 	does this make sense? This PR originally used `w_height` but that fails the  `test/functional/terminal/window_spec.lua` test.

Comment (bfredl) [reply src/nvim/terminal.c]: yes, makes sense.

Comment (justinmk) [reply src/nvim/terminal.c]: Thanks. Is there a qualitative/semantic explanation somewhere of the difference between `w_height` and `w_height_inner` (and `w_height_request`)? 

For a single-grid UI is `w_height` always the same as `w_height_inner`? Then it makes sense that `terminal/window_spec.lua` failed, because it has multiple grids. But I don't understand when `w_height` would ever be preferred to `w_height_inner`.

Comment (bfredl) [reply src/nvim/terminal.c]: > when w_height would ever be preferred to w_height_inner.

For any calculation involving the split layout. But It could be that it is redundant with `wp->w_frame->fr_height`, in case it could be eliminated.
