### PR TITLE
doc: fix vim.api.nvim_buf_attach callback arguments [ci skip]

### LINKED ISSUE #12340: API documentation has argument in wrong place
I tried setting up a Lua plugin to watch changes and operates on the changed line and thereafter. According to [the API docs](https://neovim.io/doc/user/api.html#nvim_buf_attach()) the first changed line should be the third argument passed to my callback.

> • buffer handle
> • b:changedtick
> • first line that changed (zero-indexed)
> • last line that was changed
> • last line in the updated range
> • byte count of previous contents
> • deleted_codepoints (if `utf_sizes` is true)
> • deleted_codeunits (if `utf_sizes` is true)

Unfortunately the 3rd argument was some other (much smaller and incrementing) number. It turs out the fourth arg seems to whe what I was after, like this:

```lua
nvim.api.nvim_buf_attach(buffer, false, {
    on_lines = function (_, _, _, firstline, _, _)
        myfunction(firstline)
...
```

I don't know what the other args are, but it seems like they changed since the document string was written.

Using distro (Arch) built Neovim v0.4.3.

### PR DESCRIPTION
**Pull request by h-michael**
resolve: #12340

related commit https://github.com/neovim/neovim/commit/9ef16a1628722958b6e14fe9274006e50ed6682d

(We should also update `runtime/doc/api.txt`. But now, `gen_vimdoc.py` don't work latest Doxgen.)

### CODE REVIEW

File: src/nvim/api/buffer.c [hunk 1]
```diff
@@ -126,6 +126,7 @@ String buffer_get_line(Buffer buffer, Integer index, Error *err)
 /// @param  opts  Optional parameters.
 ///             - on_lines: Lua callback invoked on change.
 ///               Return `true` to detach. Args:
+///               - "lines"
```
Comment (h-michael) [inline src/nvim/api/buffer.c:129]: https://github.com/neovim/neovim/blob/f5c56f03bb9ee25c3d931034497dc76a5591b770/src/nvim/buffer_updates.c#L240

File: src/nvim/api/buffer.c [hunk 2]
```diff
@@ -136,9 +137,11 @@ String buffer_get_line(Buffer buffer, Integer index, Error *err)
 ///               - deleted_codeunits (if `utf_sizes` is true)
 ///             - on_changedtick: Lua callback invoked on changedtick
 ///               increment without text change. Args:
+///               - "changedtick"
```
Comment (h-michael) [inline src/nvim/api/buffer.c:140]: https://github.com/neovim/neovim/blob/f5c56f03bb9ee25c3d931034497dc76a5591b770/src/nvim/buffer_updates.c#L279

File: src/nvim/api/buffer.c [hunk 3]
```diff
@@ -136,9 +137,11 @@ String buffer_get_line(Buffer buffer, Integer index, Error *err)
...
 ///               - buffer handle
 ///               - b:changedtick
 ///             - on_detach: Lua callback invoked on detach. Args:
+///               - "detach"
```
Comment (h-michael) [inline src/nvim/api/buffer.c:144]: https://github.com/neovim/neovim/blob/64cdf9f78a9bfd4d08a9d9bf2df48a4b2f296190/src/nvim/buffer_updates.c#L157

File: src/nvim/api/buffer.c (hunk 1 above)
Comment (teto) [reply src/nvim/api/buffer.c:129]: just "lines" can be confusing: `the string "lines"`

**Review by tjdevries — APPROVED** [review]
LGTM based on the comments that were here before.

I'd say the only thing is we need to either regenerate the docs or just add these in manually for now into the actual api documentation.

**Comment by tjdevries** [comment]
Look good to you @teto ?

**Review by teto — APPROVED** [review]
