### PR TITLE
fix(highlight): preserve background transparency in winblend

### LINKED ISSUE #18576: Background color becomes black when using winblend option for float window
### Neovim version (nvim -v)

NVIM v0.7.0 release

### Vim (not Nvim) behaves the same?

no

### Operating system/version

MacOS 12.1

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

repo

### How to reproduce the issue

vimrc:
``` vim
let bufnr = nvim_create_buf(v:false, v:true)
call nvim_buf_set_lines(bufnr, 0, -1, v:false, repeat([''], 5))
hi MyFloat ctermfg=223 ctermbg=235 guifg=#ebdbb2
let winid = nvim_open_win(bufnr, 1, {
    \ 'relative': 'editor',
    \ 'row': 1,
    \ 'col': 1,
    \ 'height': 5,
    \ 'width': 10,
    \ 'style': 'minimal',
    \ })
call setwinvar(winid, '&winhl', 'Normal:MyFloat,NormalNC:MyFloat')
call setwinvar(winid, '&winblend', 30)

```

### Expected behavior

The background color should keep transparent when using winblend option.
When winblend is set to `0` the background is transparent as expected.

### Actual behavior

Seems black color is used when background not exists.
Screen Shot 2022-05-15 at 17 23 01

### PR DESCRIPTION
**Pull request by glepnir**
Problem: When using winblend, transparent backgrounds (-1) were forced to default colors (usually black) during attribute blending, breaking the transparency effect.

Solution: Check original background colors before blending in hl_blend_attrs(). If both background and foreground originally had transparent backgrounds, preserve transparency instead of forcing default colors.

Fix #18576

### CODE REVIEW

File: src/nvim/highlight.c [hunk 1]
```diff
@@ -753,11 +753,19 @@ int hl_blend_attrs(int back_attr, int front_attr, bool *through)
 
     cattrs.rgb_ae_attr &= ~HL_BG_INDEXED;
   }
-  cattrs.rgb_bg_color = rgb_blend(ratio, battrs.rgb_bg_color,
-                                  fattrs.rgb_bg_color);
 
-  cattrs.hl_blend = -1;  // blend property was consumed
+  HlAttrs original_back = syn_attr2entry(back_attr);
```
Comment (bfredl) [inline src/nvim/highlight.c]: We've already looked up these once so it's a bit weird to need to look up them again. perhaps rewrite the original lookup to 
```
HlAttrs battrs_raw = syn_attr2entry(back_attr);
HlAttrs battrs = get_colors_force(battrs_raw);
```
`get_colors_force` in only used for blending so it can be changed.

File: src/nvim/highlight.c [hunk 2]
```diff
@@ -753,11 +754,18 @@ int hl_blend_attrs(int back_attr, int front_attr, bool *through)
...
 
-  cattrs.hl_blend = -1;  // blend property was consumed
+  // Check if we should preserve background transparency
+  // Use the raw attributes (before forcing colors) to check original transparency
+  bool preserve_transparency = (battrs_raw.rgb_bg_color == -1) && (fattrs_raw.rgb_bg_color == -1);
 
+  if (preserve_transparency) {
+    cattrs.rgb_bg_color = -1;
+  } else {
+    cattrs.rgb_bg_color = rgb_blend(ratio, battrs.rgb_bg_color, fattrs.rgb_bg_color);
```
Comment (justinmk) [inline src/nvim/highlight.c]: ternary

File: test/functional/ui/float_spec.lua [hunk 3]
```diff
@@ -9285,10 +9292,84 @@ describe('float window', function()
...
+          {16:^qui o}{22:└}{25:Footer}{22:─────────┘}{16:ollit anim id est           }|
+          laborum.                                          |
+                                                            |
+        ]])
+      end
+
+      -- issue #18576
+      command('hi Nomral guibg=NONE ctermbg=NONE')
+      api.nvim_win_set_option(win, 'winhighlight', 'Normal:Normal')
+      api.nvim_set_option_value('winblend', 100, { win = win })
```
Comment (justinmk) [inline test/functional/ui/float_spec.lua]: can this be added to the `Check that 'winblend' applies to border/title/footer` test case above? The two test cases don't seem to conflict with each other. That would avoid 70 lines of new test code.

File: test/functional/ui/float_spec.lua [hunk 4]
```diff
@@ -9254,41 +9261,52 @@ describe('float window', function()
       api.nvim_win_set_config(win, { border = 'single', title = 'Title', footer = 'Footer' })
       api.nvim_set_option_value('winblend', 100, { win = win })
       api.nvim_set_option_value('cursorline', true, { win = 0 })
-      command('hi clear VertSplit')
+      -- test winblend with transparent background (#18576)
+      command('hi clear VertSplit | hi Nomral guibg=NONE ctermbg=NONE')
```
Comment (justinmk) [inline test/functional/ui/float_spec.lua]: typo: "Nomral"

File: src/nvim/highlight.c [hunk 5]
```diff
@@ -753,11 +754,14 @@ int hl_blend_attrs(int back_attr, int front_attr, bool *through)
...
   }
-  cattrs.rgb_bg_color = rgb_blend(ratio, battrs.rgb_bg_color,
-                                  fattrs.rgb_bg_color);
 
+  // Check if we should preserve background transparency
+  // Use the raw attributes (before forcing colors) to check original transparency
+  cattrs.rgb_bg_color = (battrs_raw.rgb_bg_color == -1)
+                        && (fattrs_raw.rgb_bg_color == -1) ? -1 : rgb_blend(ratio,
+                                                                            battrs.rgb_bg_color,
+                                                                            fattrs.rgb_bg_color);
```
Comment (justinmk) [inline src/nvim/highlight.c]: this seems a bit more readable

```suggestion
  cattrs.rgb_bg_color = (battrs_raw.rgb_bg_color == -1) && (fattrs_raw.rgb_bg_color == -1)
                        ? -1
                        : rgb_blend(ratio, battrs.rgb_bg_color, fattrs.rgb_bg_color);
```

File: test/functional/ui/float_spec.lua [hunk 6]
```diff
@@ -9254,41 +9261,52 @@ describe('float window', function()
       api.nvim_win_set_config(win, { border = 'single', title = 'Title', footer = 'Footer' })
       api.nvim_set_option_value('winblend', 100, { win = win })
       api.nvim_set_option_value('cursorline', true, { win = 0 })
-      command('hi clear VertSplit')
+      -- test winblend with transparent background (#18576)
```
Comment (justinmk) [inline test/functional/ui/float_spec.lua]:
```suggestion
      -- 'winblend' with transparent background. #18576
```

**Review by justinmk — APPROVED** [review]
