### PR TITLE
fix(messages): unwanted newlines with ext_messages

### LINKED ISSUE #36687: ui2: `verb au` looks different
## Problem:

old ui seems more compact, also extui didn't keep the indent. 
* `nvim --clean --cmd 'lua require("vim._extui").enable{}' +'verb au'`
* `nvim --clean +'verb au'`

| **extui** | **old** |
|:--:|:--:|
| Image 1 | Image 2 |

`verb func`/`verb map` looks different too

NVIM v0.12.0-dev-1684 neovim/neovim@6ef43ba8a4
Linux 6.17.8-zen1-1-zen
kitty
xterm-kitty

### LINKED ISSUE #37697: ui2: some commands have an empty newline before their output
### Problem

When running certain commands like `:hi` or `:au`, the output will include an empty newline before any output.

Image

Image

This even happens when the command is only one line long and the pager should not be opened, for example, with `:hi @attribute`:

Image

### Steps to reproduce

- `nvim --clean`
- `:lua require('vim._extui').enable {}`
- Run a command like `:hi` or `:au`.

### Expected behavior

There is not a blank newline at the top.

### Nvim version (nvim -v)

NVIM v0.12.0-dev+2173-d59440773, although this has existed for a while. I just never reported it until now.

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Fedora 43

### Terminal name/version

kitty 0.43.1

### $TERM environment variable

xterm-kitty

### Installation

Fedora COPR

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Newlines intended to write messages below the cmdline or to
          mark the start of a new message on message grid are emitted
          through ext_messages. This results in unnecessary newlines for
          a UI that has decoupled its message area from the cmdline.
          msg_col is set directly in some places which is not transmitted
          to msg_show events.
          Various missing message kind for list commands.
          Trailing newlines on various list commands.
Solution: Only emit such newlines without ext_messages enabled.
          Use msg_advance() instead of setting msg_col directly.
          Assign them the "list_cmd" kind.
          Ensure no trailing newline is printed.

Fix #36687
Fix #37697

### CODE REVIEW

File: src/nvim/ui.c [hunk 1]
```diff
@@ -782,6 +782,7 @@ void ui_call_event(char *name, Array args)
     "lua_error",
     "lua_print",
     "progress",
+    "verbose",
```
Comment (luukvbaal) [inline src/nvim/ui.c]: Making `verbose` messages non-fast is unfortunate but with commands like `:verbose au` it currently results in just the non-verbose part being printed, because the verbose events handlers need to be scheduled.

Either we make all `verbose` messages non-fast but there's some that seem more risky as opposed to "last_set" messages, risking regressing #27874.

Otherwise we need to drop the verbose kind for these commands interspersed with "last_set" messages, and just make it a single message. That would lose the verbose information. Although I can't imagine what a UI would want to do with it, so maybe that would be better. Would just make `:au verbose` a single message event, and should simplify the newline logic I added in this PR somewhat.

Comment (luukvbaal) [reply src/nvim/ui.c]: Or I guess overriding the non-fast status of _just_ last set verbose messages is a third option. But I think I'll go ahead and try to just make it a single message. The `verbose` kind information doesn't seem worth the cost of the event flood it causes with `:verb au/map`.

EDIT: latest commit has single event for "last set" messages.

File: test/old/testdir/test_signs.vim [hunk 2]
```diff
@@ -62,7 +62,7 @@ func Test_sign()
   " Check placed signs
   let a=execute('sign place')
   call assert_equal("\n--- Signs ---\nSigns for [NULL]:\n" .
-		\ "    line=3  id=41  name=Sign1  priority=10\n", a)
+		\ "    line=3  id=41  name=Sign1  priority=10", a)
```
Comment (luukvbaal) [inline test/old/testdir/test_signs.vim:65]: Is this wanted? (And does it require comments @zeertzjq?)

Comment (zeertzjq) [reply test/old/testdir/test_signs.vim:65]: I think it's fine. The difference is quite easy to understand.

File: src/nvim/ui.c (hunk 1 above)
Comment (justinmk) [reply src/nvim/ui.c]: > The `verbose` kind information doesn't seem worth the cost of the event flood it causes with `:verb au/map`.

Yes. Batching is usually the best approach.
