### PR TITLE
fix(api): auto-load buffers in nvim_buf_set_* operations 

### LINKED ISSUE #10070: neovim api calls for autocommands
I'm working on a plugin for debugging functionality and trying to optimize some of the code paths. One problem we have is that there doesn't seem to be a way to load a buffer to a window and then run autocommands on it as if the user opened the buffer themselves.

Given a sequence of steps
* user triggers event with window 2 selected
* plugin calls `nvim_win_set_buf` for window 1 with some other buffer

you get a raw buffer loaded into window 1 with no syntax highlighting and no autocommands ran for other plugins that might depend on it. So the work around I've used is

    target_window.buffer = new_buffer
    previous_window = vim.current.window
    vim.current.window = target_window
    vim.command("doauto SomeAutocmd")
    vim.current.window = previous_window

Clearly this is a clumsy workaround. Something along the lines of

    target_window.buffer = new_buffer
    vim.api.run_autocommand("BufEnter", target_window.buffer)

would be much nicer.

### PR DESCRIPTION
**Pull request by glepnir**
Problem: Setting marks, lines, or text on unloaded buffers fails because
ml_line_count is not accurate until the buffer is loaded.

Solution: Add require_loaded_buffer() helper and use it in write operations
(nvim_buf_set_lines, nvim_buf_set_text, nvim_buf_set_mark). These now
auto-load buffers as needed.

Closes #26666
Fix #10070 
Fix #34425

### CODE REVIEW

File: src/nvim/api/private/helpers.c [hunk 1]
```diff
@@ -276,6 +277,22 @@ buf_T *find_buffer_by_handle(Buffer buffer, Error *err)
   return rv;
 }
 
+buf_T *requir_loaded_buffer(Buffer buffer, Error *err)
```
Comment (zeertzjq) [inline src/nvim/api/private/helpers.c]: typo

File: test/functional/api/buffer_spec.lua [hunk 2]
```diff
@@ -2375,6 +2384,13 @@ describe('api/buf', function()
     it('fails when invalid buffer number is used', function()
       eq(false, pcall(api.nvim_buf_set_mark, 99, 'a', 1, 1, {}))
     end)
+    it('nvim_buf_set_mark auto-loads unloaded buffer', function()
```
Comment (zeertzjq) [inline test/functional/api/buffer_spec.lua]:
```suggestion
    it('auto-loads unloaded buffer', function()
```

**Comment by justinmk** [comment]
Looks like this only changed `nvim_buf_set_mark`, does that really cover the full intent of https://github.com/neovim/neovim/issues/10070 ?

**Comment by glepnir** [comment]
The APIs related to set operations will ensure that the buffer is loaded. get operations have special null values ​​for unloaded buffers.  might be sufficient for now.
