### PR TITLE
fix(column): redraw 'statuscolumn' on wrapped lines with 'relativenumber'

### LINKED ISSUE #26934: When v:relnum is used in statuscolumn it doesn't update as often as expected
### Problem

Described along with the reproduction steps.

### Steps to reproduce

`nvim --clean -c 'let &statuscolumn=\'%{v:relnum}\''`
Add some lines, press escape and move between the lines.

I would expect the relative line numbers to update as you move between lines, but they are only updated when you add new lines.
The relative line numbers in the `statuscolumn` start updating if you turn relative line numbers on via `set relativenumber`.

Even when `relativenumber` is set, the relative line numbers only update for the first visual line of a wrapped line.
Setting `relativenumber` or `number` also appears to add `numberwidth` padding after the status column, but while unexpected this is pretty useful.

### Expected behavior

The relative line numbers in the `statuscolumn` to update in the scenarios described above.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2042+g28c183b38c Build type: RelWithDebInfo LuaJIT 2.1.1702233742

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux archlinux 6.6.7-arch1-1

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

Arch User Repository

### PR DESCRIPTION
**Pull request by luukvbaal**
**fix(column): redraw 'statuscolumn' on wrapped lines with 'relativenumber'**

Problem:  The 'statuscolumn' is not redrawn on the wrapped part of a
          line when moving the cursor with 'relativenumber' set.
Solution: Redraw the 'statuscolumn' for the entire line height in the
          "col_rows" win_line() code path.

**docs(column): 'statuscolumn' redraw interaction with 'relativenumber'**

Fix #26934

### CODE REVIEW

File: src/nvim/drawline.c [hunk 1]
```diff
@@ -1551,6 +1551,11 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool number_onl
       }
       // don't clear anything after wlv.col
       win_put_linebuf(wp, wlv.row, 0, wlv.col, wlv.col, bg_attr, false);
+      // update the 'statuscolumn' for the entire line size
+      if (number_only && statuscol.draw
+          && ++wlv.row - wlv.startrow < wp->w_lines[wlv.lnum - wp->w_topline].wl_size) {
+        continue;
```
Comment (luukvbaal) [inline src/nvim/drawline.c:1557]: Might need to reset some winlinevars (wlv->off?) before continuing, I'll test later.

Comment (luukvbaal) [reply src/nvim/drawline.c:1559]: > Might need to reset some winlinevars (wlv->off?) before continuing, I'll test later.

That and set `draw_cols` to true to make sure the 'statuscolumn' is actually being re-evaluated, instead of just duplicated. Good to go now I think.

File: src/nvim/drawline.c [hunk 2]
```diff
@@ -1551,6 +1551,13 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool number_onl
       }
       // don't clear anything after wlv.col
       win_put_linebuf(wp, wlv.row, 0, wlv.col, wlv.col, bg_attr, false);
+      // update the 'statuscolumn' for the entire line size
+      if (number_only && statuscol.draw
+          && ++wlv.row - wlv.startrow < wp->w_lines[wlv.lnum - wp->w_topline].wl_size) {
```
Comment (luukvbaal) [inline src/nvim/drawline.c:1556]: Hmm this `w_lines` index breaks down with folds. Can we pass `idx` from `win_update()` to `win_line()`?

Comment (luukvbaal) [reply src/nvim/drawline.c]: @zeertzjq @bfredl any thoughts on the (already pushed) `number_only` refactor here?

**Review by bfredl — APPROVED** [review]
LGTM. reusing the `col_rows` info seems the best solution. perhaps a rebase to be sure.
