### PR TITLE
mksession: Restore buftype=terminal windows.

### LINKED ISSUE #4311: Window of terminal buffer can't be restored when setting sessionoptions-=blank
- Neovim version: 0.1.3
- Operating system: Mac OX
- Terminal emulator: iTerm2

### Actual behaviour
The terminal buffer would be restored without the associated window

### Expected behaviour
The terminal buffer should be restored with the associated window

### Steps to reproduce
* nvim some_file
* :set sessionoptions-=blank
* :mksession! tmp.vim
* nvim -S tmp.vim

I don't like blank window, so I want them get removed when session restored,  and I think window with terminal buffers should not belongs to blank window.

### PR DESCRIPTION
**Pull request by justinmk**
Closes #4311

### CODE REVIEW

File: src/nvim/ex_docmd.c [hunk 1]
```diff
@@ -8774,19 +8774,18 @@ static int ses_do_frame(frame_T *fr)
...
- */
+/// Return non-zero if window "wp" is to be stored in the Session.
 static int ses_do_win(win_T *wp)
 {
   if (wp->w_buffer->b_fname == NULL
-      /* When 'buftype' is "nofile" can't restore the window contents. */
-      || bt_nofile(wp->w_buffer)
-      )
+      // When 'buftype' is "nofile" can't restore the window contents.
+      || (!wp->w_buffer->terminal && bt_nofile(wp->w_buffer))) {
```
Comment (justinmk) [inline src/nvim/ex_docmd.c]: We use this special-case logic all over the place unfortunately, so for now this is idiomatic.
