### PR TITLE
[RDY] Fix wildmode=list,full and display+=msgsep interaction

### LINKED ISSUE #10092: Tab-line disappears after invoking completion and then cancelling with <C-c>
- `nvim --version`:
```
NVIM v0.3.5
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190429-43022-1je6td8/neovim-0.3.5/build/config -I/tmp/neovim-20190429-43022-1je6td8/neovim-0.3.5/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20190429-43022-1je6td8/neovim-0.3.5/build/src/nvim/auto -I/tmp/neovim-20190429-43022-1je6td8/neovim-0.3.5/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.5/share/nvim"

Run :checkhealth for more info
```
- Vim (version: 8.0) behaves differently? Yes, tabline does not disappear
- Operating system/version: MacOS
- Terminal name/version: tmux in kitty
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set showtabline=2
:set wildmode=list:longest,full
:co<Tab><Tab><C-c>
```

### Actual behaviour

Tab-line disappears. Can use `:redraw!` as a workaround to make it appear again.
tabline-issue

`:set display-=msgsep` eliminates the problem, but I do prefer `msgsep`.

### Expected behaviour
Tab-line does not disappear.

### PR DESCRIPTION
**Pull request by gelguy**
Fixes #10092.

### CODE REVIEW

File: src/nvim/screen.c [hunk 1]
```diff
@@ -4765,13 +4765,21 @@ win_redr_status_matches (
 
   row = cmdline_row - 1;
   if (row >= 0) {
-    if (wild_menu_showing == 0) {
+    if (wild_menu_showing == 0 || wild_menu_showing == WM_LIST) {
       if (msg_scrolled > 0) {
         /* Put the wildmenu just above the command line.  If there is
          * no room, scroll the screen one line up. */
         if (cmdline_row == Rows - 1) {
-          grid_del_lines(&default_grid, 0, 1, (int)Rows, 0, (int)Columns);
```
Comment (bfredl) [inline src/nvim/screen.c]: wouldn't it work to just replace this line by `msg_scroll_up()` ? (keeping `msg_scrolled++` but `cmdline_row = Rows - 1` shouldn't be needed.

File: test/functional/ui/messages_spec.lua [hunk 2]
```diff
@@ -681,7 +681,44 @@ describe('ui/ext_messages', function()
   end)
 end)
 
-describe('ui/builtin messages', function()
+describe('ui/ext messages', function()
```
Comment (bfredl) [inline test/functional/ui/messages_spec.lua]: `'ui/ext_messages'` with the underscore

File: test/functional/ui/messages_spec.lua [hunk 3]
```diff
@@ -681,7 +681,44 @@ describe('ui/ext_messages', function()
...
+     }},
+    cmdline={{
+      firstc = ':',
+      content = {{ 'set wildm' }},
+      pos = 9,
+    }}}
+  end)
+end)
+
+describe('ui/ext messages', function()
```
Comment (bfredl) [inline test/functional/ui/messages_spec.lua]: `'ui/builtin messages'` as it used to be.

File: test/functional/ui/wildmode_spec.lua [hunk 4]
```diff
@@ -169,6 +169,47 @@ describe("'wildmenu'", function()
...
+    screen:expect([[
+       [No Name]               |
+                               |
+      ~                        |
+                               |
+      :set wildm               |
+      wildmenu  wildmode       |
+      :set wildm^               |
+    ]])
+    feed('<tab>') -- trigger wildmode full
```
Comment (bfredl) [inline test/functional/ui/wildmode_spec.lua]: A `screen:expect()` also here would be good.

File: src/nvim/screen.c [hunk 5]
```diff
@@ -4765,13 +4765,19 @@ win_redr_status_matches (
...
-          msg_scrolled++;
+          if (dy_flags & DY_MSGSEP) {
+            // with msgsep, push the messages 1 line up
+            // and draw the wildmenu on that line
+            msg_scroll_up();
```
Comment (bfredl) [inline src/nvim/screen.c]: What I meant was that this would already handle both branches. it checks `DY_MSGSEP` internally.

File: src/nvim/screen.c [hunk 6]
```diff
@@ -4765,13 +4765,19 @@ win_redr_status_matches (
...
+          } else {
+            grid_del_lines(&default_grid, 0, 1, (int)Rows, 0, (int)Columns);
+            msg_scrolled++;
+          }
```
Comment (justinmk) [inline src/nvim/screen.c]: I think the entire `if/else` can be replaced by `msg_scroll_up()`. It does the same steps.

File: src/nvim/screen.c (hunk 5 above)
Comment (gelguy) [reply src/nvim/screen.c]: Hope I got it right this time :sweat_smile:

File: src/nvim/screen.c [hunk 7]
```diff
@@ -4765,13 +4765,12 @@ win_redr_status_matches (
...
   row = cmdline_row - 1;
   if (row >= 0) {
-    if (wild_menu_showing == 0) {
+    if (wild_menu_showing == 0 || wild_menu_showing == WM_LIST) {
       if (msg_scrolled > 0) {
         /* Put the wildmenu just above the command line.  If there is
          * no room, scroll the screen one line up. */
         if (cmdline_row == Rows - 1) {
-          grid_del_lines(&default_grid, 0, 1, (int)Rows, 0, (int)Columns);
-          msg_scrolled++;
```
Comment (bfredl) [inline src/nvim/screen.c]: the `msg_scrolled++` line should remain after `msg_scroll_up()` otherwise next scroll might be wrong.

**Comment by bfredl** [comment]
force pushed to try fix unrelated build issue

**Comment by bfredl** [comment]
Nice fix, merged!
