### PR TITLE
fix(extui): close cmdwin to enter "more" window

### LINKED ISSUE #33853: vim._extui: `:messages` error when used in the cmdwin
### Problem

Cmdwin restrictions cause an error when attempting to jump to the messages window:

```
Error in "msg_history_show" UI event handler (ns=nvim._ext_ui):
Lua: /usr/local/share/nvim/runtime/lua/vim/_extui/messages.lua:407: E11: Invalid in command-line window; <CR> executes, CTRL-C quits
stack traceback:
	[C]: in function 'nvim_set_current_win'
	/usr/local/share/nvim/runtime/lua/vim/_extui/messages.lua:407: in function 'win_set_pos'
	/usr/local/share/nvim/runtime/lua/vim/_extui/messages.lua:416: in function 'set_pos'
	/usr/local/share/nvim/runtime/lua/vim/_extui/messages.lua:374: in function 'handler'
	/usr/local/share/nvim/runtime/lua/vim/_extui.lua:33: in function 'ui_callback'
	/usr/local/share/nvim/runtime/lua/vim/_extui.lua:66: in function </usr/local/share/nvim/runtime/lua/vim/_extui.lua:62>
```

### Steps to reproduce

```vim
lua require("vim._extui").enable {}
call feedkeys("q:", "n")
au CmdwinEnter * ++once echom "foo" | messages
```

### Expected behavior

No error, though unsure what should be done about entering the messages window in this case...

### Nvim version (nvim -v)

NVIM v0.12.0-dev-315+g40351bbbbe

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

Source

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Cannot enter "more" window while cmdwin is open since it is a
          regular window and changing windows is disallowed.
Solution: Close cmdwin to enter the "more" window. Minor regression
          w.r.t. the current message grid. Resolving that will require
          somehow bypassing textlock for the "more" window.

Fix #33853

### CODE REVIEW

**Comment by luukvbaal** [comment]
🫣

**Comment by justinmk** [comment]
wdyt @seandewar  ? 

is this RFC and then tests/docs will be updated?

File: src/nvim/ex_docmd.c [hunk 1]
```diff
@@ -4732,7 +4732,7 @@ bool before_quit_autocmds(win_T *wp, bool quit_all, bool forceit)
 /// ":{nr}quit": quit window {nr}
 static void ex_quit(exarg_T *eap)
 {
-  if (cmdwin_type != 0) {
+  if (curwin == cmdwin_win) {
```
Comment (seandewar) [inline src/nvim/ex_docmd.c:4735]: Can use this to close other windows when in the messages window, which can allow for `cmdwin_old_curwin` to be closed or the cmdwin to be left as the only window; that can cause strangeness.

E.g: this causes E199, which shouldn't happen:

```vim
only!
lua require"vim._extui".enable{}
echom "foo"
call feedkeys("q:", "nt")
au CmdwinEnter * ++once mess | 1q! | qa! | au SafeState * ++once au SafeState * ++once mes
```

File: src/nvim/ex_docmd.c [hunk 2]
```diff
@@ -4845,7 +4845,7 @@ static void ex_close(exarg_T *eap)
 {
   win_T *win = NULL;
   int winnr = 0;
-  if (cmdwin_type != 0) {
+  if (curwin == cmdline_win) {
```
Comment (seandewar) [inline src/nvim/ex_docmd.c:4848]: Same here:

```vim
only!
lua require"vim._extui".enable{}
echom "foo"
call feedkeys("q:", "nt")
au CmdwinEnter * ++once mess | 1close! | qa! | au SafeState * ++once au SafeState * ++once mes
```

File: src/nvim/globals.h [hunk 3]
```diff
@@ -743,6 +743,7 @@ EXTERN bool km_startsel INIT( = false);
 EXTERN int cmdwin_type INIT( = 0);    ///< type of cmdline window or 0
 EXTERN int cmdwin_result INIT( = 0);  ///< result of cmdline window or 0
 EXTERN int cmdwin_level INIT( = 0);   ///< cmdline recursion level
+EXTERN bool cmdwin_lock INIT( = true);   ///< should lock for open cmdwin
```
Comment (seandewar) [inline src/nvim/globals.h:746]: With my suggestion from earlier, might be better to make this `cmdwin_nolock_win`/`buf` instead (can bikeshed the naming), and only allow navigation between that window/buffer and the cmdwin?

File: src/nvim/window.c [hunk 4]
```diff
@@ -213,7 +213,7 @@ void do_window(int nchar, int Prenum, int xchar)
 
 #define CHECK_CMDWIN \
   do { \
-    if (cmdwin_type != 0) { \
+    if (curwin == cmdwin_win && cmdwin_lock) { \
```
Comment (seandewar) [inline src/nvim/window.c:216]: Likewise, this allows entering other windows once in the messages window with `<C-W>w` and the like.

**Review by seandewar — COMMENTED** [review]
Haven't had time to have a thorough look yet, but here's a few observations.

I commend your bravery, soldier :saluting_face:

File: src/nvim/ex_getln.c [hunk 5]
```diff
@@ -2930,7 +2930,7 @@ int check_opt_wim(void)
 /// another window or buffer.  True when editing the command line etc.
 bool text_locked(void)
 {
-  if (cmdwin_type != 0) {
+  if (curwin == cmdwin_win && cmdwin_lock) {
```
[the remark this answers is not in the document]
Comment (luukvbaal) [reply src/nvim/ex_getln.c:2933]: Thanks for the review! I remember contemplating 'winfixbuf' but don't remember the reason for omitting it, if I had one😓 The correct buffer is restored for all extui windows on the next event anyways so 'switching the buffer shouldn't break anything but I also cant think of a reason to allow it.

**Review by justinmk — APPROVED** [review]

File: runtime/lua/vim/_extui/messages.lua [hunk 6]
```diff
@@ -405,17 +405,24 @@ function M.set_pos(type)
...
-            api.nvim_win_set_config(win, { hide = true })
-          end
-          append_more = 0
-        end,
-        desc = 'Hide inactive more window.',
-      })
-      api.nvim_set_current_win(win)
+      -- Cannot leave the cmdwin to enter the "more" window, so close it.
+      if fn.getcmdwintype() ~= '' then
+        api.nvim_win_close(0, true)
```
Comment (seandewar) [inline runtime/lua/vim/_extui/messages.lua:410]: A _slightly_ pedantic nitpick (sorry! :grin:), but it's possible for the cmdwin to not be curwin (but only temporarily).

E.g: (run this one manually)

```vim
lua require'vim._extui'.enable{}
let s:w = win_getid()
call feedkeys('q:', 'nt')
au CmdwinEnter * ++once call win_execute(s:w, 'messages')
```

_Should_ be able to get around that by just using a plain `:quit` instead (it prioritizes the cmdwin regardless of curwin), but looping through the list of windows to `nvim_win_close` the one with `win_gettype() == "command"` may be more robust.

Yeah, the cmdwin is a bit jank...

**Review by seandewar — APPROVED** [review]
