### PR TITLE
fix(edit): backspace adds extra spaces for inline virtual text

### LINKED ISSUE #26388: Strange white space padding when using  nvim_buf_set_extmark for inlay virtual text
### Problem

Please refer to the attached video
https://github.com/neovim/neovim/assets/1681295/8fe6b0af-719c-49fa-8398-1ca33a6ea3ba

### Steps to reproduce

install nvim head with brew
open following 1.lua code
```lua
local ns = vim.api.nvim_create_namespace('test')
vim.api.nvim_buf_set_extmark(0, ns, 0, 5, {
              virt_text_pos = 'inline',
              ephemeral = false,
              virt_text = {{'[virtual text]'}},
            })
```

```sh
nvim -u NORC 1.lua
```

Run `1.lua`  with `luafile %`
Change to insert mode, move cursor to `1:7` and press `<BS>`; 
`[virtual text]` shifted to right with space added.
Press `<Right>` the cursor stops on next character after virtual text `[virtual text]n|`

### Expected behavior

TBH, I am not sure what is the expected behavior. But I would expected the virtual text remain it's initial position.
Also If my cursor is around virtual text when press `<left>` and `<right>` it should stop on virtual text boundary   `|[virtual text]|` (the `|` stands for expected cursor position) 

### Neovim version (nvim -v)

NVIM v0.10.0-dev-748eae6

### Vim (not Nvim) behaves the same?

I do not know as the API may be unique to nvim

### Operating system/version

macOS 10.15.2

### Terminal name/version

kitty

### $TERM environment variable

kitty-256

### Installation

brew install --HEAD

### PR DESCRIPTION
**Pull request by vanaigr**
Fixes #26388.

The problem occurs because `want_vcol` is offset by the width of the virtual text, which increases the number of inserted spaces. Similar issue also happens for 'linebreak' and 'breakindent'.

This can be fixed by ignoring 'linebreak', 'breakindent' and inline virtual text when calculating virtual columns.

I also changed one of the conditions from `if (curwin->w_cursor.col == 0)` to `if (curwin->w_cursor.col <= revins_on)` since when `revins_on` is `true` and the cursor is at the start of the line, its `col` is 1. `vcol` and `want_vcol` are calculated for different lines in this case, which results in this behavior:
revins

### CODE REVIEW

File: test/functional/editor/mode_insert_spec.lua [hunk 1]
```diff
@@ -221,4 +221,132 @@ describe('insert-mode', function()
...
+    local feed_command = helpers.feed_command
+    local api = helpers.api
+    local function set_lines(line_b, line_e, ...)
+      api.nvim_buf_set_lines(0, line_b, line_e, true, { ... })
+    end
+    local function s(count)
+      return (' '):rep(count)
+    end
+
+    local function setup(width, height)
```
Comment (zeertzjq) [inline test/functional/editor/mode_insert_spec.lua:235]: `setup()` overshadows a global function.

File: test/functional/editor/mode_insert_spec.lua [hunk 2]
```diff
@@ -221,4 +221,132 @@ describe('insert-mode', function()
...
+      clear()
```
Comment (zeertzjq) [inline test/functional/editor/mode_insert_spec.lua:236]: This is not needed as `clear()` is already called in `before_each()`.

File: test/functional/editor/mode_insert_spec.lua [hunk 3]
```diff
@@ -221,4 +221,132 @@ describe('insert-mode', function()
     ]],
     }
   end)
+
+  describe('backspace', function()
+    local feed_command = helpers.feed_command
+    local api = helpers.api
```
Comment (zeertzjq) [inline test/functional/editor/mode_insert_spec.lua:227]: I think this should be moved to the top of the file.

File: test/functional/editor/mode_insert_spec.lua [hunk 4]
```diff
@@ -221,4 +221,132 @@ describe('insert-mode', function()
...
+    end
+    local function s(count)
+      return (' '):rep(count)
+    end
+
+    local function setup(width, height)
+      clear()
+      local screen = Screen.new(width, height + 1)
+      screen:attach()
+      feed_command('setl listchars=space:.,tab:>- list')
```
Comment (zeertzjq) [inline test/functional/editor/mode_insert_spec.lua:239]: Why not use `command()` instead of `feed_command()`?

File: test/functional/editor/mode_insert_spec.lua [hunk 5]
```diff
@@ -221,4 +221,132 @@ describe('insert-mode', function()
...
+        { 7, 17 },
+        { 2, 9 },
+        { 1, 8 }, -- last screen cell of first tab is at vcol 8
+      })
+    end)
+
+    it('works with breakindent', function()
+      setup(17, 3)
+      feed_command('setl ts=4 sw=4 bri briopt=min:5')
+      set_lines(0, 1, '\t' .. s(4) .. '\t' .. s(9) .. '\t ' .. 'a')
```
Comment (zeertzjq) [inline test/functional/editor/mode_insert_spec.lua:318]:
```suggestion
      set_lines(0, 1, '\t' .. s(4) .. '\t' .. s(9) .. '\t a')
```

File: test/functional/editor/mode_insert_spec.lua [hunk 6]
```diff
@@ -221,4 +221,132 @@ describe('insert-mode', function()
...
+        { 7, 9 },
+        { 4, 5 },
+        { 1, 1 },
+      })
+    end)
+
+    it('works in replace mode', function()
+      setup(50, 1)
+      feed_command('setl ts=8 sw=8 sts=8')
+      set_lines(0, 1, '\t' .. s(4) .. '\t' .. s(9) .. '\t ' .. 'a')
```
Comment (zeertzjq) [inline test/functional/editor/mode_insert_spec.lua:303]:
```suggestion
      set_lines(0, 1, '\t' .. s(4) .. '\t' .. s(9) .. '\t a')
```

File: test/functional/editor/mode_insert_spec.lua [hunk 7]
```diff
@@ -221,4 +221,132 @@ describe('insert-mode', function()
...
+        { 6, 9 },
+        { 2, 5 },
+        { 1, 1 },
+      })
+    end)
+
+    it('works with inline virtual text', function()
+      setup(50, 1)
+      feed_command('setl ts=4 sw=4')
+      set_lines(0, 1, '\t' .. s(4) .. '\t' .. s(9) .. '\t ' .. 'a')
```
Comment (zeertzjq) [inline test/functional/editor/mode_insert_spec.lua:335]:
```suggestion
      set_lines(0, 1, '\t' .. s(4) .. '\t' .. s(9) .. '\t a')
```

File: src/nvim/edit.c [hunk 8]
```diff
@@ -3752,7 +3735,7 @@ static bool ins_bs(int c, int mode, int *inserted_space_p)
   }
 
   // Delete newline!
-  if (curwin->w_cursor.col == 0) {
+  if (curwin->w_cursor.col <= revins_on) {
```
Comment (zeertzjq) [inline src/nvim/edit.c:3738]: It seems that this change can cause Nvim to crash. Please remove this change from this PR.

File: src/nvim/edit.c [hunk 9]
```diff
@@ -3846,42 +3829,68 @@ static bool ins_bs(int c, int mode, int *inserted_space_p)
...
-      // the previous character.
-      getvcol(curwin, &curwin->w_cursor, &vcol, NULL, NULL);
-      colnr_T start_vcol = vcol;
-      dec_cursor();
-      getvcol(curwin, &curwin->w_cursor, NULL, NULL, &want_vcol);
-      inc_cursor();
+
+      bool const use_ts = !curwin->w_p_list || curwin->w_p_lcs_chars.tab1;
+      int const lnum = curwin->w_cursor.lnum;
+      char *const line = ml_get_buf(curbuf, lnum);
```
Comment (zeertzjq) [inline src/nvim/edit.c:3841]: The `lnum` variable seems unnecessary.
```suggestion
      char *const line = get_cursor_line_ptr();
```

File: src/nvim/edit.c [hunk 10]
```diff
@@ -3846,42 +3829,68 @@ static bool ins_bs(int c, int mode, int *inserted_space_p)
...
+      char *const end_ptr = line + curwin->w_cursor.col;
+
+      colnr_T vcol = 0;
+      colnr_T space_vcol = 0;
+      StrCharInfo sci = utf_ptr2StrCharInfo(line);
+      StrCharInfo space_sci = sci;
+      bool prev_space = false;
+      do {
+        bool cur_space = ascii_isspace(sci.chr.value);
```
Comment (zeertzjq) [inline src/nvim/edit.c:3850]: `ascii_iswhite()` should be used, not `ascii_isspace()`.
```suggestion
        bool cur_space = ascii_iswhite(sci.chr.value);
```

**Review by zeertzjq — APPROVED** [review]
