### PR TITLE
fix(ui): trigger TabNewEntered after split new tab

### LINKED ISSUE #4334: TabNew and TabNewEntered not triggered on a tab split buffer
- Neovim version: NVIM v0.1.3-211-g47b529
- Operating system: Ubuntu 14.04.3 LTS
- Terminal emulator: Gnome-terminal
### Actual behaviour

TabNew and TabNewEntered are not triggered on a tab split.
### Expected behaviour

TabNew and TabNewEntered are triggered on a tab split.
### Steps to reproduce

:au TabNew \* echom "TabNew"
:au TabNewEntered \* echom "TabNewEntered"
:tab split
#### Output:

Nothing
#### Expected output:

TabNew
TabNewEntered

### LINKED ISSUE #4434: YouCompleteMe server shutdown on E716: Key not present in Dictionary: setShowHidden'
- Neovim version: NVIM v0.1.3-331-gd9ecd06
- Operating system: Ubuntu
- Terminal emulator: Terminator

### Actual behaviour
The ycmd server SHUT DOWN

### Expected behaviour
Auto completion on Javascript file, using TernJs

### Steps to reproduce
Follow steps to install YouCompleteMe with Tern, and just open a Javascript file.

### Stdout

```
/tmp/ycm_temp/server_37444_stdout.log" 0L, 0C
Error detected while processing function <SNR>105_ToggleLogs[3]..provider#python3#Call:
line   18:
NvimError(b'Vim(call):E716: Key not present in Dictionary: setShowHidden',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/neovim/msgpack_rpc/session.py", line 181, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python3.5/dist-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/local/lib/python3.5/dist-packages/neovim/plugin/host.py", line 66, in _on_request
    rv = handler(*args)
  File "/usr/local/lib/python3.5/dist-packages/neovim/plugin/host.py", line 152, in <lambda>
    decoder = lambda fn, hook, *args: fn(*hook.walk(args))
  File "/home/guilala/Code/Bash/share/nvim/runtime/autoload/provider/script_host.py", line 77, in python_execute
    exec(script, self.module.__dict__)
neovim.api.nvim.NvimError: b'Vim(call):E716: Key not present in Dictionary: setShowHidden'
```

### PR DESCRIPTION
**Pull request by glepnir**
Fix #4334

### CODE REVIEW

File: src/nvim/window.c [hunk 1]
```diff
@@ -1131,6 +1131,7 @@ int win_split(int size, int flags)
 
   // When the ":tab" modifier was used open a new tab page instead.
   if (may_open_tabpage() == OK) {
+    apply_autocmds(EVENT_TABNEWENTERED, NULL, NULL, false, curbuf);
```
Comment (justinmk) [inline src/nvim/window.c:1134]: why isn't this in `win_new_tabpage` ? oh, I see a similar pattern here: https://github.com/neovim/neovim/blob/133e2990efa44cadf1410a452a08843dbd8ca86e/src/nvim/ex_docmd.c#L5027-L5030

everything is so spread out :( but this could instead be done in `may_open_tabpage`, at least (otherwise what's the point of having `may_open_tabpage` ?):

```diff
diff --git a/src/nvim/window.c b/src/nvim/window.c
index 16bb7f5df794..4c8c3e1049c1 100644
--- a/src/nvim/window.c
+++ b/src/nvim/window.c
@@ -4261,7 +4261,11 @@ int may_open_tabpage(void)
 
   cmdmod.cmod_tab = 0;         // reset it to avoid doing it twice
   postponed_split_tab = 0;
-  return win_new_tabpage(n, NULL);
+  int ok = win_new_tabpage(n, NULL);
+  if (ok == OK) {
+    apply_autocmds(EVENT_TABNEWENTERED, NULL, NULL, false, curbuf);
+  }
+  return ok;
 }
 
 // Create up to "maxcount" tabpages with empty windows.
```

Comment (glepnir) [reply src/nvim/window.c]: yes. plan to check may_open_tabpage carefully when I wake up :)

File: src/nvim/window.c [hunk 2]
```diff
@@ -4261,7 +4261,11 @@ int may_open_tabpage(void)
 
   cmdmod.cmod_tab = 0;         // reset it to avoid doing it twice
   postponed_split_tab = 0;
-  return win_new_tabpage(n, NULL);
+  int ok = win_new_tabpage(n, NULL);
+  if (ok == OK) {
```
Comment (bfredl) [inline src/nvim/window.c:4265]: could name variable `status` so it is `status == OK` which is a bit more readable

Comment (glepnir) [reply src/nvim/window.c]: thx done.
