### PR TITLE
fix(diagnostic): accept multiple namespaces when setting loclist/qflist

### LINKED ISSUE #21367: vim.diagnostic.setqflist's namespace argument should accept a table of namespaces
### Feature already in Vim?

_No response_

### Feature description

Similar to functions that take vim.diagnostic.severity as an optional parameter, the namespace parameter could either be a single namespace (number) or a table of namespaces (numbers).

This table can be the result of `vim.tbl_map(vim.lsp.diagnostic.get_namespace, vim.tbl_map(function(i) return i.id end, vim.lsp.get_active_clients()))`.

### PR DESCRIPTION
**Pull request by MariaSolOs**
Closes https://github.com/neovim/neovim/issues/21367

### CODE REVIEW

File: runtime/lua/vim/diagnostic.lua [hunk 1]
```diff
@@ -2348,8 +2348,8 @@ end
 --- @class vim.diagnostic.setqflist.Opts
 --- @inlinedoc
 ---
---- Only add diagnostics from the given namespace.
---- @field namespace? integer
+--- Only add diagnostics from the given namespace(s).
+--- @field namespace? integer[]|integer
```
Comment (MariaSolOs) [inline runtime/lua/vim/diagnostic.lua:2352]: No further changes are needed here besides changing the type as `vim.diagnostic.get()` already handles a single/multiple namespaces.

**Review by gpanders — APPROVED** [review]
