### PR TITLE
[RFC]  fix i<c-r> with multi-byte text

### LINKED ISSUE #6517: pasting non-ASCII characters generates garbled output
- `nvim --version`:
master
````
NVIM v0.2.0-1303-gdd391bfca
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/tmp/yaourt-tmp-zhou13/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-zhou13/aur-neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/yaourt-tmp-zhou13/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-zhou13/aur-neovim-git/src/neovim-git/build/include
Compiled by zhou13@p150sma

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
````

### Steps to reproduce using `nvim -u NORC`
Copy this character `‘`.
Paste it into neovim using `<C-r>+` in insert mode.

### Actual behaviour

The pasted characters show up something like this: `<t_^^<80>>`.

Maybe related to w0rp/ale#469

### PR DESCRIPTION
**Pull request by bfredl**
fixes #6517

### CODE REVIEW

File: test/functional/insert/ctrl_r_spec.lua [hunk 1]
```diff
@@ -0,0 +1,19 @@
+local helpers = require('test.functional.helpers')(after_each)
+local clear, feed, insert = helpers.clear, helpers.feed, helpers.insert
```
Comment (justinmk) [inline test/functional/insert/ctrl_r_spec.lua]: testlint complains that `insert` is unused

Comment (bfredl) [inline test/functional/insert/ctrl_r_spec.lua]: fixed!
