### PR TITLE
LSP: Add textDocument/codeAction support

### LINKED ISSUE #11608: LSP: The callback for workspace/applyEdit does not send a response
- `nvim --version`:
```
NVIM v0.5.0-261-g2ef72437f
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-15cad2f4-d0e5-45e9-9231-17653111c5a0

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
It does not have the lsp api
- Operating system/version: 
Linux 5.4.6-arch1-1 x86_64 GNU/Linux (Arch Linux)
- Terminal name/version: 
alacritty 0.4.0
- `$TERM`:
`xterm-256color`

### Steps to reproduce using `nvim -u NORC`
Using my PR #11607 applying any code action that returns workspace/applyEdit,
```
nvim -u NORC
:lua vim.lsp.buf.code_action()
```

### Actual behaviour
Error log with message: `Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:360: method "workspace/applyEdit": either a result
or an error must be sent to the server in response`
The edit however is applied
### Expected behaviour
No error

### PR DESCRIPTION
**Pull request by Jesse-Bakker**
Implement `textDocument/codeAction` using a preview window for choosing the preferred code action.
Also fixes #11608

### CODE REVIEW

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -822,5 +839,52 @@ function M.character_offset(buf, row, col)
...
+      for _, option in ipairs(options) do
+        table.insert(titles, title_fn(option))
+      end
+      return titles
+    end
+    )
+    vim.api.nvim_set_current_win(winnr)
+    vim.api.nvim_buf_set_keymap(
+      bufnr, 'n', '<CR>',
+      string.format('<cmd>lua vim.lsp.util.choice_option_callback("%s")<CR>', unique_name),
```
Comment (norcalli) [inline runtime/lua/vim/lsp/util.lua]:
```suggestion
      string.format('<cmd>lua vim.lsp.util.choice_option_callback(%q)<CR>', unique_name),
```

`%q` quotes the string correctly.

**Comment by pwntester** [comment]
I implemented similar support [here](https://github.com/pwntester/dotfiles/blob/master/config/nvim/lua/lsp-config.lua#L190-L243) but enabled a way to define custom choice menu. For example, in my case, I implemented it with [FZF](https://github.com/pwntester/dotfiles/blob/master/config/nvim/plugins.vim#L217-L228)

**Comment by Jesse-Bakker** [comment]
Maybe for now the best way to implement this is to use `inputlist()` by default and make it configurable, so that you can use FZF or something else if you want to. I think `inputlist` is a better default than a floating window anyway, because it follows the vim philosophy better (by being able to choose an option at speed of thought instead of having to scroll).

@norcalli I am thinking about making the choice method configurable in the same way as the callbacks, so either by modifying a global, e.g. `vim.lsp.choice_function` or by passing a `choice_function` table parameter to `vim.lsp.start_client`. What do you think?
@justinmk It might also be good to have an alternative way to "make choices" in neovim, e.g. like the quickfix/location window which has the advantage of being "scrollable", searchable, and possibly more intuitive (you are choosing by selecting and pressing enter).

**Comment by justinmk** [comment]
> Maybe for now the best way to implement this is to use `inputlist()` by default and make it configurable

It is already configurable by virtue of the fact that custom handlers can be implemented. So the inputlist() impl doesn't itself need to be configurable. 

So this PR or some other PR can be merged as a basic implementation (_not_ hyper-configurable), and more generally we should focus on fixing anything that's painful about implementing a custom handler.

> I am thinking about making the choice method configurable in the same way as the callbacks, so either by modifying a global, e.g. `vim.lsp.choice_function`

Out of scope for now.

> It might also be good to have an alternative way to "make choices" in neovim, e.g. like the quickfix/location window

Yes, this has been discussed. But we can't solve it here and it's out of scope for the near future.

**Comment by Jesse-Bakker** [comment]
Thanks for the quick reply! I will just remove my custom floating menu from this PR, implement it using inputlist and then maybe follow up in a later PR with some more configurability.

**Comment by Jesse-Bakker** [comment]
I reimpemented using `inputlist()`

**Comment by mhartington** [comment]
I tested this out, but came across a situation where when trying to remove a whole line, I get 

```
Buffer  file:///Users/mhartington/testTs/test.ts  newer than edits.
``` 

Printed out instead of having the edit applied.

lsp


It does seem to work sometimes, but it's not consistent.

**Comment by Jesse-Bakker** [comment]
That seems to be a data race, where the server handles the `textDocument/codeAction` request, generating `TextDocumentEdit`s, before it has handled a previous `DidChangeTextDocument` notification. It thus generates the actions on an old version of the document. The neovim lsp client checks whether the version of the document an edit references isn't stale before applying it, resulting in the error message you are seeing.

I think this problem lies on the server end, but I am not 100% certain

**Comment by mhartington** [comment]
I'm not entirely sure it's server related as [vim-lsp](https://github.com/prabirshrestha/vim-lsp) is setup to use the same server and handles this without issue. 

Pictured, one nvim instance with vim-lsp, another with nvim's built in lsp.

ls-difs


Also worth noting it also looks like there's a difference in the diagnostics returned between the two lsp clients. Probably beyond the scope of this PR.

**Comment by Jesse-Bakker** [comment]
I will look into it. Which language server are you using?

**Comment by Jesse-Bakker** [comment]
I have found the problem. A `textDocument/didChange` notification is only sent when text changes, but the variable used to check whether the version of a change is right (`changedtick`) can increment without text changing. This can of course be fixed by using a different `version` metric on our side

**Comment by Jesse-Bakker** [comment]
@mhartington The issue should be fixed now

File: runtime/lua/vim/lsp/callbacks.lua [hunk 2]
```diff
@@ -11,13 +12,50 @@ local function err_message(...)
...
+
+  local choice = vim.fn.inputlist(option_strings)
+  if choice < 1 or choice > #actions then
+    return
+  end
+  local action_chosen = actions[choice]
+  -- textDocument/codeAction can return either Command[] or CodeAction[].
+  -- We handle both in the same way by extracting the command
+  local command = action_chosen
+  if type(action_chosen.command) == table then
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/callbacks.lua]: For [eclipse.jdt.ls](https://github.com/eclipse/eclipse.jdt.ls) I had to add some special handling to get it working:


```lua
local action = action_chosen
if type(action_chosen.command) == table then
  action = action_chosen.command
end
if action.command == 'java.apply.workspaceEdit' then
  for _, argument in ipairs(action.arguments) do
    util.apply_workspace_edit(argument)
  end
else
  buf.execute_command(action)
end
```

A dump of the `action_chosen` looked like this:

```
["arguments"] = { 
  [1] = { 
    ["changes"] = { 
        ["file:///path/to/the/file"] = { 
          [1] = { 
            ["range"] = { 
              ["end"] = { 
                ["line"] = 24,
                ["character"] = 0,
              },
              ["start"] = { 
                ["line"] = 0,
                ["character"] = 0,
              },
            },
            ["newText"] = lots of text...,
          },
        },
      },
    },
  },
  ["title"] = Import 'Maps' (...),
  ["command"] = java.apply.workspaceEdit,
}
```

Comment (Jesse-Bakker) [reply runtime/lua/vim/lsp/callbacks.lua]: That is more something for in https://github.com/neovim/nvim-lsp

**Comment by mfussenegger** [comment]
I think other than the missing documentation (and tests?) this looks good.
I've been using it for a while and it works well.

**Comment by mhartington** [comment]
👋 Hey @Jesse-Bakker , would you be able to rebase and update buf.lua?

**Comment by Jesse-Bakker** [comment]
I am excited to see this feature land in master. Is there anything I forgot to do that would be needed to make that happen?

**Comment by mfussenegger** [comment]
I'm currently looking into how to add support for some of the functionality that vscode provides via client extensions and what they have is some kind of registry for commands.

For example, if you look at the sourceActions in [vscode-java](https://github.com/redhat-developer/vscode-java/blob/master/src/sourceAction.ts) you see that the vscode languageServer-client API has a `.registerCommand` function. Extensions can register custom handlers that are invoked in the `codeAction` callback.



Mapped to nvim and lua, I think having something as follows would be great:

```lua
M.commands = {} -- users can add <string>: function(command, code_action_params)

function M.code_action()
    local code_action_params = make_code_action_params()
    vim.lsp.buf_request(0, 'textDocument/codeAction', code_action_params, function(err, _, actions)
        if err then return end
        -- actions is (Command | CodeAction)[] | null
        -- CodeAction
        --      title: String
        --      kind?: CodeActionKind
        --      diagnostics?: Diagnostic[]
        --      isPreferred?: boolean
        --      edit?: WorkspaceEdit
        --      command?: Command
        --
        -- Command
        --      title: String
        --      command: String
        --      arguments?: any[]
        if #actions == 0 then
            print("No code actions available")
            return
        end
        local option_strings = {"Code Actions:"}
        for i, action in ipairs(actions) do
            local title = action.title:gsub('\r\n', '\\r\\n')
            title = title:gsub('\n', '\\n')
            table.insert(option_strings, string.format("%d. %s", i, title))
        end
        local choice = vim.fn.inputlist(option_strings)
        if choice < 1 or choice > #actions then
            return
        end
        local action = actions[choice]
        if action.edit then
            vim.lsp.util.apply_workspace_edit(action.edit)
            return
        end
        local command
        if type(action.command) == "table" then
            command = action.command
        else
            command = action
        end
        local fn = M.commands[command.command]
        if fn then
            fn(command, code_action_params)
        else
            M.execute_command(command)
        end
    end)
end
```

A user or language-server specific nvim plugin could then register custom handlers:

```
M.commands = {
    ['java.apply.workspaceEdit'] = function(command)
        for _, argument in ipairs(command.arguments) do
            vim.lsp.util.apply_workspace_edit(argument)
        end
    end;
    ['java.action.generateToStringPrompt'] = function(_, params)
        vim.lsp.buf_request(0, 'java/checkToStringStatus', params, function(err, _, result)
            if err then
                print("Could not execute java/checkToStringStatus: " .. err.message)
            end
            ...
        end)
    end;
}
```

What do you think?

**Comment by Jesse-Bakker** [comment]
@mfussenegger Something like that is already possible by specifying a custom callback for the code action response and your example is pretty specific to this exact use case. Maybe implementing this in [nvim-lsp](https://github.com/neovim/nvim-lsp) would, therefore, be better. In any case, let's not implement that in this PR, but maybe open an issue or PR where it can be discussed further.

**Comment by mhartington** [comment]
Not sure what's changed recently, but I have one situation where diagnostics are not reporting a fix. 


code-actions


Though the same error is reporting code actions fine in vscode


Screen Shot 2020-04-13 at 5 05 22 PM

**Comment by Jesse-Bakker** [comment]
@mhartington The problem here is that the language server positions this diagnostic at the place of the missing semicolon. You cannot however position your cursor there (without having virtualedit set), as it is one past the end of the line. Setting `virtualedit=onemore` will fix this.

**Comment by mhartington** [comment]
>virtualedit=onemore

Today I learned about virtualedit...thanks! That did the trick. everything seem to be working well then in my testing!

**Comment by Jesse-Bakker** [comment]
> Today I learned about virtualedit...thanks! 

Learned about it yesterday myself ;)

File: runtime/lua/vim/lsp/buf.lua [hunk 3]
```diff
@@ -161,5 +161,21 @@ function M.clear_references()
   util.buf_clear_references()
 end
 
+function M.code_action(context)
+  validate { context = { context, 't', true } }
+  context = context or { diagnostics = util.get_line_diagnostics() }
+  local params = util.make_range_params()
```
Comment (tjdevries) [inline runtime/lua/vim/lsp/buf.lua:167]: Would it possibly fix the problem that was mentioned about `virtualedit` if we added a `onemore` optional param to `make_range_params` that, if true, would check if you are at the end of the line and add one extra position if so? This would mean that you wouldn't have to actually go to the virtualedit location (or turn it on) but would instead get that by being at the end of the line?

I haven't tested or anything to see if that would be the case, just a thought.

Comment (Jesse-Bakker) [reply runtime/lua/vim/lsp/buf.lua:167]: It is a bit more complicated than that unfortunately. We would have to detect whether there is a diagnostic one past the end of the line and only add one to the cursor position if there is. Also, what would happen if there is also a diagnostic at the last character in the line? Would we send two requests (one with the actual position and one one past) then? We would probably also have to change the underline for the diagnostic then, to keep the behaviors of diagnostics and code actions mutually consistent.

Summed up, keeping everything consistent that way would complicate the logic considerably and I am not sure if the result would be more/equally intuitive. I will take a look at what plugins do, as this may be a solved problem.

Comment (tjdevries) [reply runtime/lua/vim/lsp/buf.lua:167]: Ah, I was suggesting that because I thought it had a start and end to request the codeActions. I did not read the spec yet, but I thought we could detect if we were on the end of the line, and if so, add `onemore` to the range so that it could include past the line without people actually having to enable that feature.

Does that make sense? I would be interested to see how other (particularly vim) plugins have handled this. Thanks for following up

Comment (Jesse-Bakker) [reply runtime/lua/vim/lsp/buf.lua:167]: A code action is only returned if the range submitted to the server lies completely inside the range of the diagnostic. This ensures that if you make a selection and get a code action for that, it is valid for the entire selection. What that means for this specific case is:

Code:
```typescript
let a = 1
```

Diagnostic range:
```json
{
    "start" : {"line": 0, "character": 9},
    "end" : {"line": 0, "character": 9}
}
```
Proposed code action range (which gives no results):
```json
{
    "start" : {"line": 0, "character": 8},
    "end" : {"line": 0, "character": 9}
}
```
Range that does give results:
```json
{
    "start" : {"line": 0, "character": 9},
    "end" : {"line": 0, "character": 9}
}
```

Comment (tjdevries) [reply runtime/lua/vim/lsp/buf.lua:167]: Ah, I see. I didn't realize that was the case. Thanks for explaining.

**Comment by tjdevries** [comment]
Hm, so as I was looking at other implementations,  I found this: 

https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/ui/vim/code_action.vim#L32

which calls: 

https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/utils/range.vim#L28

Which seems to use the length of the line?

I am okay merging this without resolving this problem (I didn't review the rest of it yet, so I'd have to do that) but I suggest maybe we make an issue about the code actions for people who don't have `onemore` enabled.

Thoughts?

**Comment by Jesse-Bakker** [comment]
I also think we should not block the PR on this issue, but if I have the time to pick it up, I will try to put the changes in this PR. Otherwise we could just create an issue, making the discussion more discoverable for others to chime in.

Regarding the example you mentioned, I am interested to see how that interacts with the issue at hand and will test to see if it works, if it improves ergonomics and if it is more intuitive. Thanks for the help!

**Comment by Jesse-Bakker** [comment]
> Hm, so as I was looking at other implementations, I found this:
> 
> https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/ui/vim/code_action.vim#L32
> 
> which calls:
> 
> https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/utils/range.vim#L28

@tjdevries 
Actually, when there is no selection, the range in the result of https://github.com/prabirshrestha/vim-lsp/blob/92a56292bb7dc4d363b0ab2c91e24232b81edf70/autoload/lsp/ui/vim/diagnostics.vim#L76 is used, which is the diagnostic that is closest to the cursor.

**Comment by tjdevries** [comment]
Ah, very interesting! Good find. Thanks for looking that up. Perhaps we will want to write some wrappers similar to that later then. I will try and review this PR today then.

**Comment by tjdevries** [comment]
LGTM

File: runtime/lua/vim/lsp/util.lua [hunk 4]
```diff
@@ -684,19 +684,27 @@ do
...
+  function M.get_line_diagnostics()
     local bufnr = api.nvim_get_current_buf()
     local line = api.nvim_win_get_cursor(0)[1] - 1
+
+    local buffer_diagnostics = M.diagnostics_by_buf[bufnr]
+    if not buffer_diagnostics then
+      return {}
+    end
+
+    local line_diagnostics = buffer_diagnostics[line]
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/util.lua:696]: I think this is now outdated as the `diagnostics_by_buf` are no longer grouped by line by default, and there is also https://github.com/neovim/neovim/pull/12244 which will change the format further.

Comment (Jesse-Bakker) [reply runtime/lua/vim/lsp/util.lua]: I have updated it to group by line first. I can change it again if that PR is merged before this one.

**Comment by dlukes** [comment]
I'm currently working on a [PR to add a sync variant of the `textDocument/formatting` request](https://github.com/neovim/neovim/pull/12252), because people often want to run formatting on file save, and with the async variant, there's a good chance it'll complete only *after* the save, [leaving the buffer in a modified state](https://github.com/neovim/nvim-lsp/issues/115#issuecomment-582319317).

The same applies to code actions -- people will want to run at least some of them on file save, e.g. [organizing imports](https://github.com/neovim/nvim-lsp/issues/115). So it would be great if there was also a `vim.lsp.buf.code_action_sync()`. Does it make sense to discuss this at this point and possibly extend the PR to include it, or would you rather merge this first, and worry about a sync variant later?

**Comment by Jesse-Bakker** [comment]
I think that would be a useful addition, but not in the current state of things. I think that before a sync variant is useful, we should first implement `CodeActionKind` so we can just request the types of actions we'd want to run automatically (like organize imports) and maybe also the `preferred` field.

**Comment by dlukes** [comment]
Understood, fair enough :)

File: runtime/lua/vim/lsp/util.lua [hunk 5]
```diff
@@ -701,19 +701,28 @@ do
...
+    local linenr = api.nvim_win_get_cursor(0)[1] - 1
+
+    local buffer_diagnostics = M.diagnostics_by_buf[bufnr]
+
+    if not buffer_diagnostics then
+      return {}
+    end
+
+    local diagnostics_by_line = M.diagnostics_group_by_line(buffer_diagnostics)
+    return diagnostics_by_line[linenr]
```
Comment (teto) [inline runtime/lua/vim/lsp/util.lua:715]: not used

**Comment by teto** [comment]
I would like to merge this. Looking at the spec, there is a part where the client advertises some capability `CodeActionClientCapabilities`. Should the PR work without that ?
(also mind rebasing please ?)

File: runtime/lua/vim/lsp/util.lua (hunk 5 above)
Comment (Jesse-Bakker) [reply runtime/lua/vim/lsp/util.lua:715]: It is used [here](https://github.com/neovim/neovim/pull/11607/files/618ed87de05a7fc1f7fc475c126d257853948b4c#diff-274652c0882365aea521edadd15ecf0dR166) for getting the diagnostics that might be involved in the code action

**Comment by Jesse-Bakker** [comment]
>Looking at the spec, there is a part where the client advertises some capability `CodeActionClientCapabilities`. Should the PR work without that ?

The `CodeActionClientCapabilites` specify whether code action literals (returning a `CodeAction` instead of a command) are supported by the client. This takes a list of `CodeActionKind`, which we do not support yet. I think that passing an empty list advertises that we support code action literals, but do not handle code action kind. The protocol specifies that our client should handle values outside the provided range gracefully, which we do, as we just ignore them.

I will adjust the capabilities to reflect our support of code action literals. I will also rebase

**Comment by tjdevries** [comment]
LGTM.

@Jesse-Bakker Would you be willing to make a separate PR that adds tests for this feature? Would like to merge this in since it looks good and people have already manually tested it and I think it's a killer feature :) but would also like to get some coverage for it as well.

@teto you can merge if you think it's good as well.

**Comment by teto** [comment]
On my first try with microsoft's python language server
```
Error executing vim.schedule lua callback: /home/teto/neovim/runtime/lua/vim/lsp.lua:485: RPC[Error] code_name = serverErrorEnd, message
 = "Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Microsoft.Python.LanguageServer.Protocol.TextDocumentClientCapab
ilities+CodeActionCapabilities+CodeActionLiteralSupport+CodeActionKind' because the type requires a JSON object (e.g. {\"name\":\"value\
"}) to deserialize correctly.\                                                                                                          
To fix this error either change the JSON to a JSON object (e.g. {\"name\":\"value\"}) or change the deserialized type to an array or a t
ype that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayA
ttribute can also be added to the type to force it to deserialize from a JSON array.\                                                   
Path 'capabilities.textDocument.codeAction.codeActionLiteralSupport.codeActionKind'." data = "   at Newtonsoft.Json.Serialization.JsonSe
rializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)\n   at Newtonsoft.Json.Serializati
on.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existi
ngValue, String id)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type object
Type, JsonContract contract, JsonProperty member, JsonContainerCon
```
In my previous post, I did not mean you had to add `CodeActionClientCapabilites`, I was just inquiring if it was mandatory to work. If it is optional we can merge a simpler PR and add it afterwards.

File: runtime/lua/vim/lsp/protocol.lua [hunk 6]
```diff
@@ -620,6 +620,13 @@ function protocol.make_client_capabilities()
         -- Send textDocument/didSave after saving (BufWritePost)
         didSave = true;
       };
+      codeAction = {
+        dynamicRegistration = false;
+
+        codeActionLiteralSupport = {
+          codeActionKind = {};
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/protocol.lua:627]:
```suggestion
            codeActionKind = {
                valueSet = {};
            };
```

I think the `valueSet` would still have to be set if it's empty. But given that it's not necessary I think it could be left out completely for now.

**Comment by Jesse-Bakker** [comment]
@teto I thought, quick fix which allows for great extra convenience (mostly extra performance, but some servers only work with code action literal support). Read the spec a bit too quickly though and forgot a layer of the struct. Fixed it now

**Comment by teto** [comment]
could you try with python-language-server ? now the error doesn't appear on startup but when running codeAction.

**Comment by Jesse-Bakker** [comment]
@teto Looks like that language server handles the protocol more strictly than the servers I tested with. Edited the response to conform. I think everything should be conforming now.

**Comment by teto** [comment]
Now seems to work even though the server has never any action to propose to me, maybe my code is just already perfect :)
Thanks for the work.
