### PR TITLE
lsp: Fix bad sortText comparison

### LINKED ISSUE #12431: vimls omnifunc throws attempt to compare nil with string
- `nvim --version`: `NVIM v0.5.0-60c581b`
- nvim-lsp version(commit hash): a7fdf268b1c51f6395900e437060728701aa8b77
- `:checkhealth` result
```
## Checking language server protocol configuration
  - INFO: vimls: configuration checked.
  - INFO: gopls: configuration checked.
  - INFO: tsserver: configuration checked.
```
- Operating system/version: macOS 10.15.5
- Terminal name/version: Terminal.app
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup

Just `<C-x><C-o>` after installing vimls in a vim file.

Throws:

```
Error executing vim.schedule lua callback: ...vim/HEAD-60c581b/share/nvim/runtime/lua/vim/lsp/util.lua:267: attempt to compare nil with string
```

Originally filed at https://github.com/neovim/nvim-lsp/issues/261

### PR DESCRIPTION
**Pull request by nhooyr**
The spec indicates we have to fallback to comparing by label
if sortText is falsy.

Closes #12431

### CODE REVIEW

**Comment by h-michael** [comment]
@nhooyr Could you add test?

**Comment by nhooyr** [comment]
@h-michael Sure will do soon.

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -263,10 +263,9 @@ end
 -- Sort by CompletionItem.sortText
 -- https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion
 local function sort_completion_items(items)
-  if items[1] and items[1].sortText then
-    table.sort(items, function(a, b) return a.sortText < b.sortText
-    end)
-  end
+  table.sort(items, function(a, b)
+    return (a.sortText or a.label) < (b.sortText or b.label)
```
Comment (tjdevries) [inline runtime/lua/vim/lsp/util.lua:267]: While we're here, perhaps we should also add `or ''` to both of these, just so that we don't completely die on the comparison if we do for some reason have nil for both. What do you think about that?

Comment (nhooyr) [reply runtime/lua/vim/lsp/util.lua:267]: It should always be there so if it isn't I think it might be a good idea to error out so that the bug causing it to be nil can be fixed.

Comment (tjdevries) [reply runtime/lua/vim/lsp/util.lua:267]: I don't feel super strongly about it. We can leave it the way it is for now.

Comment (h-michael) [reply runtime/lua/vim/lsp/util.lua:267]: According to the specifications of lsp, this should not cause an error.  When an error occurs, I think that the specification has been changed or the server is a bug, so I can leave it as it is.

**Comment by nhooyr** [comment]
Test has been added. I also switched the sorting algorithm to merge sort to keep equal keys stable.

**Comment by nhooyr** [comment]
Also, will rebase into one commit when ready for merge.

File: test/functional/plugin/lsp_spec.lua [hunk 2]
```diff
@@ -985,7 +985,7 @@ describe('LSP', function()
       }
       local completion_list_items = {items=completion_list}
       local expected = {
-        { abbr = 'foobar', dup = 1, empty = 1, icase = 1, info = ' ', kind = 'Unknown', menu = '', word = 'foobar', user_data = { nvim = { lsp = { completion_item = { label = 'foobar' } } } } },
+        { abbr = 'foobar', dup = 1, empty = 1, icase = 1, info = ' ', kind = 'Unknown', menu = '', word = 'foobar', user_data = { nvim = { lsp = { completion_item = { label='foobar' } } } } },
```
Comment (tjdevries) [inline test/functional/plugin/lsp_spec.lua:988]: nit: formatting change here

Comment (nhooyr) [reply test/functional/plugin/lsp_spec.lua:988]: I changed this to match all the other lines in that test. Should I revert?

Comment (nhooyr) [reply test/functional/plugin/lsp_spec.lua:988]: Bump. This is ready otherwise.

**Comment by tjdevries** [comment]
Have you tested this on a large set of completion items? Just wondering what the perf of this is.

**Comment by nhooyr** [comment]
Have not will do soon.

**Comment by tjdevries** [comment]
Cool, if you can compare the time it takes to compare a few thousand items the old way and then how long with the new way, that'd be great. Once we check and confirm that, we can probably merge. I'll read through again after that.

**Comment by nhooyr** [comment]
Added a benchmark!

Results on my machine:

```
$ make benchmark TEST_FILE=test/benchmark/bench_mergesort_spec.lua
[----------] Global test environment setup.
[----------] Running tests from test/benchmark/bench_mergesort_spec.lua
[ RUN      ] sort      16 quicksort: 0.05 ms OK
[ RUN      ] sort      16 mergesort: 0.10 ms OK
[ RUN      ] sort      32 quicksort: 0.04 ms OK
[ RUN      ] sort      32 mergesort: 0.29 ms OK
[ RUN      ] sort     256 quicksort: 0.13 ms OK
[ RUN      ] sort     256 mergesort: 0.82 ms OK
[ RUN      ] sort     512 quicksort: 0.30 ms OK
[ RUN      ] sort     512 mergesort: 0.36 ms OK
[ RUN      ] sort    1024 quicksort: 0.60 ms OK
[ RUN      ] sort    1024 mergesort: 0.71 ms OK
[ RUN      ] sort    4096 quicksort: 3.17 ms OK
[ RUN      ] sort    4096 mergesort: 4.92 ms OK
[ RUN      ] sort    8192 quicksort: 7.19 ms OK
[ RUN      ] sort    8192 mergesort: 16.21 ms OK
[ RUN      ] sort   65536 quicksort: 147.56 ms OK
[ RUN      ] sort   65536 mergesort: 171.51 ms OK
[ RUN      ] sort 1048576 quicksort: 5350.57 ms OK
[ RUN      ] sort 1048576 mergesort: 4635.31 ms OK
```

It's measurably slower than the old way beyond `4096` items.

I'm totally ok with deleting my changes and instead modifying the test to not use the same label/sortText. That would make this PR much less code. Preserving equality order is nice but I'm not sure if it's worth all this.

note: Please don't squash this when merging, the individual commits are well curated!

**Comment by tjdevries** [comment]
`table.move` isn't available in Lua 5.1 (at least on the version I have locally). It is available in luajit (which is why it works for you).

We should add `table.move` to the `table` if you want to use it. I found this:

```lua

function table.move(a1, f, e, t, a2)
	-- Moves elements [f, e] from array a1 into a2 starting at index t
	-- table.move implementation
	-- @param table a1 from which to draw elements from range
	-- @param number f starting index for range
	-- @param number e ending index for range
	-- @param number t starting index to move elements from a1 within [f, e]
	-- @param table a2 the second table to move these elements to
	--	@default a2 = a1
	-- @returns a2

	a2 = a2 or a1
	t = t + e

	for i = e, f, -1 do
		t = t - 1
		a2[t] = a1[i]
	end

	return a2
end
```

which seems fine. You can add that in `runtime/lua/vim/compat.lua` -- just make sure you also source that compat at the begining then of `runtime/lua/vim/shared.lua` or the `lsp` one where you're using the call.

**Comment by tjdevries** [comment]
Also, looks like lint failed.

**Comment by tjdevries** [comment]
(You can test if it works if the clang-asan test passes because it uses Lua 5.1)

**Comment by tjdevries** [comment]
I think maybe we should just do the first and third commit (simple fix + test) and we can consider doing the merge + stable sort in the future. Is that fine w/ you?

**Comment by jamessan** [comment]
> Also, looks like lint failed.

That's because the lint is checking for compliance with Lua 5.1 :)

```
Checking runtime/lua/vim/lsp/sort.lua             2 warnings
    runtime/lua/vim/lsp/sort.lua:31:13: accessing undefined field move of global table
    runtime/lua/vim/lsp/sort.lua:32:13: accessing undefined field move of global table

Checking test/benchmark/bench_mergesort_spec.lua  8 warnings
    test/benchmark/bench_mergesort_spec.lua:12:3: setting non-standard global variable charset
    test/benchmark/bench_mergesort_spec.lua:14:18: accessing undefined variable charset
    test/benchmark/bench_mergesort_spec.lua:17:18: accessing undefined variable charset
    test/benchmark/bench_mergesort_spec.lua:20:18: accessing undefined variable charset
    test/benchmark/bench_mergesort_spec.lua:22:10: accessing undefined variable charset
    test/benchmark/bench_mergesort_spec.lua:25:10: setting undefined field random of global string
    test/benchmark/bench_mergesort_spec.lua:29:10: accessing undefined field random of global string
    test/benchmark/bench_mergesort_spec.lua:35:29: accessing undefined field random of global string
```

**Comment by nhooyr** [comment]
Fixed by adding an explicit sortText to each item in the text so that the non-determinism of the builtin sort with equal items isn't a problem.
