### PR TITLE
fix(glob): avoid `subcapture nesting too deep` error

### LINKED ISSUE #26520: LSP: big workspace causes "subcapture nesting too deep" error in Lpeg.P:match
### Problem

Really strange error, and I just could not find anything online for solving that.
If I'm into a pretty large codebase (Angular monorepo) and try to save a file after editing, sometimes the following error occures and I'm unable to save:

```bash
Error detected while processing BufWritePre Autocommands for "*":
Error executing lua callback: ...vim-macos/share/nvim/runtime/lua/vim/lsp/_watchfiles.lua:85: subcapture nesting too deep
```

image

If I understand it correctly the autoformatter cannot do its stuff, but I'm not sure. I'm not a neovim ninja, therefore any help is highly appreciated.

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
--- CHANGE THESE
local pattern = 'the-filetype'
local cmd = {'name-of-language-server-executable'}
-- Add files/folders here that indicate the root of a project
local root_markers = {'.git', '.editorconfig'}
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'bugged-ls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})
```

### Expected behavior

the file should be saved and formatted as usual

### Neovim version (nvim -v)

v0.10.0-dev-1801+g2ebd328a7

### Language server name/version

typescript

### Operating system/version

MacOS 14.0

### Log file

_No response_

### PR DESCRIPTION
**Pull request by nyz93**
Use Cmt to evaluate Cond and Elem during match to avoid building the nested capture structure later.

Fixes https://github.com/neovim/neovim/issues/26520

### CODE REVIEW

File: test/functional/lua/glob_spec.lua [hunk 1]
```diff
@@ -205,6 +205,16 @@ describe('glob', function()
       eq(true, match('[!a-zA-Z0-9]', '!'))
     end)
 
+    it('should handle long patterns', function()
+      local fill_200 =
+        'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
+      local long_lit = fill_200 .. 'a'
```
Comment (j1ah0ng) [inline test/functional/lua/glob_spec.lua:211]: Perhaps
```suggestion
      eq(200, fill_200:len())
      local long_lit = fill_200 .. 'a'
```
along with a note that the LPEG max recursion depth is 200, just to be a bit clear what that's doing
