### PR TITLE
Fix terminal line wrapping detection in the TUI.

### LINKED ISSUE #7369: Copy-paste (GUI copy paste; not y/p) long lines inserting newlines
- `nvim --version`: NVIM v0.2.0, Build type: Release
- Vim (version: ) behaves differently? Yes. Expected behaviour actually happens
- Operating system/version: Arch Linux
- Terminal name/version: GNOME Terminal 3.24.2 Using VTE version 0.48.3 +GNUTLS
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC <(perl -e 'print "hello" x 300')
(highlight all the text using the cursor and hit ctrl+shift+c)
(go to some gtk textbox and ctrl+v)
```

### Actual behaviour

The line wrapping shown in the terminal is reflected in when I paste the line too; newlines are inserted every 80 characters, basically, for a standard 80x24 terminal.

The problem I have is basically this: https://unix.stackexchange.com/questions/126577/copy-a-long-single-line-text-from-a-terminal-with-undesired-change-line

### Expected behaviour

No newlines are inserted.

### PR DESCRIPTION
**Pull request by rickyz**
Fix #7369 by addressing the TODO to implement ui_add_linewrap.

### CODE REVIEW

File: src/nvim/screen.c [hunk 1]
```diff
@@ -4199,8 +4199,18 @@ win_line (
...
+      // Special trick to make copy/paste of wrapped lines work with
+      // xterm/screen: write the next character after the end of the
+      // line. This will work with all terminal types (regardless of the
+      // xn,am settings).
+      bool wrap = wp->w_p_wrap     // Wrapping enabled.
+        && filler_todo <= 0        // Not drawing diff filler lines.
+        && lcs_eol_one != -1       // Haven't printed the lcs_eol character.
+        && row != endrow - 1       // Not the last line being displayed.
+        && wp->w_width == Columns  // Window spans the width of the screen.
+        && !wp->w_p_rl;            // Not right-to-left.
```
Comment (rickyz) [inline src/nvim/screen.c]: I've removed the restriction on doing this for lines ending in multibyte characters. As far as I can tell, this restriction dates back to 2000, when it was added to work around a bug in kterm (https://marc.info/?l=vim-dev&m=96549912530900&w=2). Since the TUI operates in terms of cells rather than individual bytes, this should not do anything funny for multibyte characters.

**Comment by rickyz** [comment]
Good point re adding a param to `raw_lines`. Here's a version which does that.

I'm not super familiar with modeless selection, so I'll defer to your opinion on whether it's worth keeping `LineWraps` around - what do you think?

File: src/nvim/screen.c (hunk 1 above)
Comment (rickyz) [inline src/nvim/screen.c]: (Apologies for the repost, not super familiar with github's review processes.)

I've removed the restriction on doing this for lines ending in multibyte characters. As far as I can tell, this restriction dates back to 2000, when it was added to work around a bug in kterm (https://marc.info/?l=vim-dev&m=96549912530900&w=2). Since the TUI operates in terms of cells rather than individual bytes, this should not do anything funny for multibyte characters.

**Comment by rickyz** [comment]
Oh, also forgot to mention - the reason this always requires output is: The output for the last cell in the row must immediately precede output of the first cell in the next row (with no terminal control sequences in between)

In particular, adding a `cursor_goto` call in between the two print_cells breaks the hinting to the terminal.

Because of this, two adjacent calls to `tui_raw_line` will not trigger line wrapping (due to the `cursor_goto` call in the second call breaking the line).

If the `tui_raw_line` calls are guaranteed to occur in sequence, it may be possible to save some output by omitting the first `cursor_goto` call for continuation lines, but this a little complex, since it relies on assumptions about the ordering of calls to `tui_raw_line`. This would also need to handle the case where the final column of a wrapped line is not dirty.

**Comment by bfredl** [comment]
>  This would also need to handle the case where the first column of a line continuation is not dirty.

I was thinking of doing the same thing here as vim, force invalidate the first cell in the next line by setting the `ScreenAttrs` value to -1. This will avoid printing the continuation char twice as this branch does sometimes (if the char was going to be drawn anyway).

> Because of this, two adjacent calls to tui_raw_line will not trigger line wrapping (due to the cursor_goto call in the second call breaking the line).

`cursor_goto()` shouldn't output anything if the previous call made sure to already put the cursor in the right position. I e the first tui_raw_line should make sure to change `(0, 80)` to `(1, 0)` internally when the wrap flag is sent, by calling `final_column_wrap()` (which should be safe as nvim core promises that raw_line with wrap will be followed by another raw_line before anything else)

**Comment by rickyz** [comment]
Ah, looks like I was mistaken about the behavior of carriage return - it looks like carriage return does the right thing after a line wrap (go back to the left-most margin of the current physical line).

Here's a version that eliminates the extra output using the method you suggested - I had actually tried calling `final_column_wrap()` earlier today, but I was missing the bit to invalidate the first col of the next row.

Thanks!

File: src/nvim/screen.c [hunk 2]
```diff
@@ -4199,8 +4199,22 @@ win_line (
...
+      if (wrap) {
```
Comment (bfredl) [inline src/nvim/screen.c]: I would place this after the `screen_line` call to make it immediately clear it will affect a following `screen_line` call, and not this one.

**Comment by bfredl** [comment]
Very nice! If you don't mind, let's keep LineWraps for now, if only because #8455 will refactor this data structure, and a LineWraps removal commit made _after_ that will be easier to revert, if we ever decide to reimplement modeless selection again.

**Comment by rickyz** [comment]
Sure thing, re-added LineWraps and moved the ScreenAttrs update down.

**Comment by justinmk** [comment]
@bfredl any objection to merging this?

**Comment by bfredl** [comment]
Sorry, forgot about this. Looks good to merge.

Remote UI support (and screen tests) would be nice, but I can do it in a follow up PR.
