### PR TITLE
fix(filetype): only check first 100 and last line of buffer

### LINKED ISSUE #19817: nvim 0.8.0 slow when opening large files with "filetype on" or "syntax on"
### Neovim version (nvim -v)

v0.8.0-dev-872-gbccb5de89

### Vim (not Nvim) behaves the same?

no, vim 9.0.135

### Operating system/version

Ubuntu 22.04

### Terminal name/version

konsole 21.12.3

### $TERM environment variable

xterm-256color

### Installation

GitHub releases, PPA

### How to reproduce the issue

# Script

```bash
tmpdir=$(mktemp -d)
trap "rm -r $tmpdir" EXIT
largefile="$tmpdir/largefile"

nvim_072="$tmpdir/nvim-linux64_0.7.2"
curl -L "https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-linux64.tar.gz" -o "${nvim_072}.tar.gz" 2> /dev/null
mkdir "$nvim_072"
tar -xzf "${nvim_072}.tar.gz" -C "$nvim_072"

nvim_080="$tmpdir/nvim-linux64_0.8.0"
curl -L "https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz" -o "${nvim_080}.tar.gz" 2> /dev/null
mkdir "$nvim_080"
tar -xzf "${nvim_080}.tar.gz" -C "$nvim_080"

for i in {1..1000000}; do
    echo "ATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGC" >> "$largefile"
done
du -sh $largefile

for vim in /usr/bin/vim "$nvim_072/nvim-linux64/bin/nvim" "$nvim_080/nvim-linux64/bin/nvim"; do
    echo "********************************************************************************"
    $vim --version
    for ft in "filetype on" "filetype off"; do
        for syn in "syntax on" "syntax off"; do
            echo "$vim $ft $syn"
            time $vim --clean -u <(echo -e "$ft\n$syn") "$largefile" +q
            echo "--------------------------------------------------"
        done
    done
    echo "********************************************************************************"
done
```

### Expected behavior

nvim 0.8.0 should open moderately a large file (1,000,000 lines, 66M) just as fast as vim and nvim 0.7.2 (about 0.15s) with `filetype on` or `syntax on`.

### Actual behavior

nvim 0.8.0 takes about 3 seconds to open a moderately large file (1,000,000 lines, 66M) when either of `filetype on` or `syntax on` is set.
**Of note**, opening a large file with what I presume to be a _known_ extension is not slow: Changing `largefile="$tmpdir/largefile"` in the script above to `largefile="$tmpdir/largefile.txt"` leads to nvim 0.8.0 opening the file quickly.

## Output of the script above

```
66M     /tmp/tmp.rDyNzhkz4R/largefile
********************************************************************************
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug 03 2022 08:47:08)
Included patches: 1-135
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       +tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
+browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   +toolbar
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con_gui    +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            +X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       +xpm
+emacs_tags        +mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time -g -O2 -ffile-prefix-map=/build/vim-Z9iOBu/vim-9.0.0105+really.v9.0.0135=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lselinux -lcanberra -lsodium -lacl -lattr -lgpm -L/usr/lib -llua5.2 -Wl,-E -fstack-protector-strong -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.34/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -lpython3.10 -lcrypt -ldl -lm -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-3.0 -lm -L/usr/lib 
/usr/bin/vim filetype on syntax on

real    0m0,139s
user    0m0,093s
sys     0m0,047s
--------------------------------------------------
/usr/bin/vim filetype on syntax off

real    0m0,140s
user    0m0,114s
sys     0m0,028s
--------------------------------------------------
/usr/bin/vim filetype off syntax on

real    0m0,139s
user    0m0,094s
sys     0m0,048s
--------------------------------------------------
/usr/bin/vim filetype off syntax off

real    0m0,132s
user    0m0,080s
sys     0m0,054s
--------------------------------------------------
********************************************************************************
********************************************************************************
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az164-457

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
/tmp/tmp.rDyNzhkz4R/nvim-linux64_0.7.2/nvim-linux64/bin/nvim filetype on syntax on

real    0m0,132s
user    0m0,082s
sys     0m0,043s
--------------------------------------------------
/tmp/tmp.rDyNzhkz4R/nvim-linux64_0.7.2/nvim-linux64/bin/nvim filetype on syntax off

real    0m0,133s
user    0m0,088s
sys     0m0,039s
--------------------------------------------------
/tmp/tmp.rDyNzhkz4R/nvim-linux64_0.7.2/nvim-linux64/bin/nvim filetype off syntax on

real    0m0,135s
user    0m0,087s
sys     0m0,042s
--------------------------------------------------
/tmp/tmp.rDyNzhkz4R/nvim-linux64_0.7.2/nvim-linux64/bin/nvim filetype off syntax off

real    0m0,130s
user    0m0,090s
sys     0m0,035s
--------------------------------------------------
********************************************************************************
********************************************************************************
NVIM v0.8.0-dev-872-gbccb5de89
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az82-456

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
/tmp/tmp.rDyNzhkz4R/nvim-linux64_0.8.0/nvim-linux64/bin/nvim filetype on syntax on

real    0m3,209s
user    0m3,087s
sys     0m0,114s
--------------------------------------------------
/tmp/tmp.rDyNzhkz4R/nvim-linux64_0.8.0/nvim-linux64/bin/nvim filetype on syntax off

real    0m3,216s
user    0m3,100s
sys     0m0,109s
--------------------------------------------------
/tmp/tmp.rDyNzhkz4R/nvim-linux64_0.8.0/nvim-linux64/bin/nvim filetype off syntax on

real    0m3,208s
user    0m3,064s
sys     0m0,136s
--------------------------------------------------
/tmp/tmp.rDyNzhkz4R/nvim-linux64_0.8.0/nvim-linux64/bin/nvim filetype off syntax off

real    0m0,151s
user    0m0,104s
sys     0m0,040s
--------------------------------------------------
********************************************************************************
```

### PR DESCRIPTION
**Pull request by clason**
enough to run all test from scripts.vim but avoids performance regression for files with a large number of lines.

fixes #19817

@smjonas @osthomas

### CODE REVIEW

**Comment by clason** [comment]
This is enough to speed up the test case from #19817 to being faster than legacy filetype.vim. Nevertheless, we can check if other functions acting on `contents` can be fed only a subset of lines to further speed up (in which case we probably want to refactor the `{table.unpack(...)}` pattern).

**Comment by clason** [comment]
> I would suggest to also only pass the first 20 lines to `detect.shell` here:
> https://github.com/neovim/neovim/blob/master/runtime/lua/vim/filetype/detect.lua#L1441-L1443
> This matches Vim's behavior in `dist#ft#SetFileTypeShell`

Probably better to pass the restricted lines to `M.sh` already?

**Comment by lewis6991** [comment]
Potentially disruptive drive by comment incoming...

It seems overkill using the entire buffer contents for filetype matching. I could imagine this being slow on overly large log files. Wouldn't it be better to use head-lines and tail-lines instead?

**Comment by clason** [comment]
...maybe.

I think we could fake it by simply extracting the first 100 plus the last line and pass those as `contents`?

**Comment by smjonas** [comment]
I think we could fake it by simply extracting the first 100 plus the last line and pass those as contents?

I'd definitely prefer this for now as well. Where is the last line used btw?

**Comment by clason** [comment]
> I'd definitely prefer this for now as well. Where is the last line used btw?

CVS diff

File: runtime/lua/vim/filetype.lua [hunk 1]
```diff
@@ -2489,7 +2489,7 @@ function M.match(args)
 
   -- Finally, check file contents
   if contents or bufnr then
-    contents = contents or M.getlines(bufnr)
+    contents = contents or { unpack(M.getlines(bufnr, 1, 100)), M.getlines(bufnr, -1) }
```
Comment (smjonas) [inline runtime/lua/vim/filetype.lua:2492]: Nitpick: `M.getlines(bufnr, -1)` can be simplified to `M.getlines(bufnr)`

Comment (clason) [reply runtime/lua/vim/filetype.lua:2492]: wouldn't that get _all_ the lines?

Comment (smjonas) [reply runtime/lua/vim/filetype.lua:2492]: Yeah I'm dumb, ignore that :smile:

Comment (lewis6991) [inline runtime/lua/vim/filetype.lua:2492]: This will result in a table of 2 elements since unpack here will only expand to one element

Comment (clason) [reply runtime/lua/vim/filetype.lua:2492]: Why?

Comment (lewis6991) [reply runtime/lua/vim/filetype.lua:2492]: That's just how unpack works. It will only expand to multiple if it is placed in the last position.

Read up on lua varargs as a second class citizen if you want to learn more.

Comment (clason) [reply runtime/lua/vim/filetype.lua:2492]: I've seen this exact pattern on the net; should have known better than to trust the web...

Alternative suggestions welcome.

File: runtime/lua/vim/filetype.lua [hunk 2]
```diff
@@ -2489,7 +2489,10 @@ function M.match(args)
 
   -- Finally, check file contents
   if contents or bufnr then
-    contents = contents or M.getlines(bufnr)
+    if contents == nil then
+      contents = M.getlines(bufnr, 1, 100)
+      table.insert(contents, M.getlines(bufnr, -1))
```
Comment (lewis6991) [inline runtime/lua/vim/filetype.lua:2494]: Feel free to completely ignore this comment.

Tiny nitpick, but I pretty much always avoid `table.insert`:

```suggestion
     contents[#contents+1] = M.getlines(bufnr, -1)
```
 As it requires less 1 table access + a function call.

Obviously in this context, any perf differences are going to be absolutely negligible, however both are just as readable, so I just always opt for the latter for general consistency. There are very few cases where `table.insert` is actually worth using.

Comment (lewis6991) [reply runtime/lua/vim/filetype.lua]: Haha, you did this suggestion before I could even write this comment.

**Review by lewis6991 — APPROVED** [review]

File: runtime/lua/vim/filetype.lua (hunk 2 above)
Comment (clason) [reply runtime/lua/vim/filetype.lua]: Yeah. I checked, but I don't think we're consistent in using one or the other.

I like `table.insert` because it's more readable, but it makes the language server throw a hissy fit about something so I ended up changing it after all.

**Comment by osthomas** [comment]
Unqualified question: Would this read the last line twice if the file is less than 100 lines long? Does it matter?

**Comment by clason** [comment]
Yes, and no :)

**Comment by lewis6991** [comment]
Hmm, even though it doesn't matter, I'd be compelled to handle that case.

**Comment by clason** [comment]
I'm not, though 😇  (Honestly, I don't see any pattern where that would make a difference -- @smjonas ?)

**Comment by smjonas** [comment]
I think you're right, @clason :) This would only make a difference if we concatenate multiple lines and check them as a single string (which we only do once in `match_from_text` and there it does not matter).

**Comment by lewis6991** [comment]
Yeah it doesn't matter. I'm just thinking of cases where someone is trying to debug an unrelated issue and notices this. I would immediately assume it was a bug.

**Comment by smjonas** [comment]
Maybe we can add a comment why this can't happen :)

File: runtime/lua/vim/filetype.lua [hunk 3]
```diff
@@ -2489,7 +2489,10 @@ function M.match(args)
 
   -- Finally, check file contents
   if contents or bufnr then
-    contents = contents or M.getlines(bufnr)
+    if contents == nil then
+      contents = M.getlines(bufnr, 1, 100)
+      contents[#contents + 1] = M.getlines(bufnr, -1)
```
Comment (lewis6991) [inline runtime/lua/vim/filetype.lua:2494]: All we need is:

```suggestion
      if #contents == 100 then
        contents[#contents + 1] = M.getlines(bufnr, -1)
      end
```

but also maybe change the first `getlines` to `99`?

Comment (clason) [reply runtime/lua/vim/filetype.lua:2494]: No, because that would still duplicate if the length of `contents` is exactly 100.

I don't think catching all corner cases is worth it, which makes handling this at all not worth it.

(Adding a comment is fine, though.)

Comment (lewis6991) [reply runtime/lua/vim/filetype.lua:2494]: What about the edit?

Comment (clason) [reply runtime/lua/vim/filetype.lua:2494]: eh, still a bit cumbersome, but that's one way to do it without extracting the full buffer contents (which is a deal-breaker).

I'll come up with a better conditional using that function.

Comment (osthomas) [reply runtime/lua/vim/filetype.lua:2494]: `if vim.api.nvim_buf_line_count(bufnr) > #contents` ?

Comment (clason) [reply runtime/lua/vim/filetype.lua:2494]: I'm rather thinking `if line_count(bufnr) > 100 then ... else contents = getlines(bufnr)`.
