### PR TITLE
fix(treesitter): keep tree view open when source window is still open

### LINKED ISSUE #31196: InspectTree: Quitting a split source window closes tree inspector window
### Problem

When there is a tree view opened by ```:InspectTree``` and the source buffer is open in multiple windows, closing one of the source windows will lead to the tree view being closed as well.

### Steps to reproduce

```nvim --clean -c "InspectTree" -c "wincmd p | split" file.lua```
```:q```

### Expected behavior

Only one of the source windows should quit, leaving the tree view open.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-096cb572a-dirty

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

macOS Sequoia 15.1 arm64

### Terminal name/version

kitty 0.37.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by hyyker**
Problem: When there is a tree view opened by ```:InspectTree``` and the source buffer is open in multiple windows, closing one of the source windows will lead to the tree view being closed as well. This bug was introduced by #31181. Related issue: #31196

Solution: Check how many source windows are open when trying to quit one. If there are more than one, keep the tree view(s) open. If the only source window is closed, also close the tree view(s).

This should close #31196.

### CODE REVIEW

File: runtime/lua/vim/treesitter/dev.lua [hunk 1]
```diff
@@ -530,8 +530,13 @@ function M.inspect_tree(opts)
...
     callback = function()
+      -- don't close inpector window if source buffer
+      -- has more than one open window
+      if #vim.fn.win_findbuf(buf) > 1 then
+        return
+      end
+
       -- close all tree windows
       for _, window in pairs(vim.fn.win_findbuf(b)) do
         close_win(window)
```
Comment (lewis6991) [inline runtime/lua/vim/treesitter/dev.lua:542]: I think this now needs to `return true` to delete the autocmd.

**Review by lewis6991 — APPROVED** [review]

File: runtime/lua/vim/treesitter/dev.lua (hunk 1 above)
Comment (hykerr) [reply runtime/lua/vim/treesitter/dev.lua:542]: I think I see what you mean. Changing the return to true will make it throw ```E855: Autocommands caused command to abort``` on the last window again which I was trying to fix. Do you think not returning true will have side effects?

Comment (zeertzjq) [reply runtime/lua/vim/treesitter/dev.lua:542]: You need to `return true` after all tree windows have been closed, not when the tree windows should be kept open.

Comment (hykerr) [reply runtime/lua/vim/treesitter/dev.lua:542]: Oh nvm you meant a a return at the end right? That works
