### PR TITLE
fix(sign): do not error when defining sign without attributes

### LINKED ISSUE #875: Neovim Nightly Issue
I am using Neovim Nightly and have the following error:

```
Error detected while processing /home/parham/.local/share/nvim/site/pack/packer/start/vim-gitgutter/plugin/gitgutter.vim[109]..function gitgutter#highlight#define_signs:
line    1:
E475: Invalid argument:
```

This happens to me after the following commit on the neovim.

https://github.com/neovim/neovim/pull/25724

### PR DESCRIPTION
**Pull request by luukvbaal**
Fix https://github.com/airblade/vim-gitgutter/issues/875
Regression from #25724, apparently untested.

### CODE REVIEW

File: src/nvim/sign.c [hunk 1]
```diff
@@ -598,18 +600,15 @@ static void sign_define_cmd(char *name, char *cmdline)
       numhl = arg + 6;
     } else {
       semsg(_(e_invarg2), arg);
-      failed = true;
-      break;
+      return;
```
Comment (zeertzjq) [inline src/nvim/sign.c:603]: ?

Comment (luukvbaal) [reply src/nvim/sign.c:603]: ? This was done to free the allocated arguments strings which were removed in #25724. So we can return instead of breaking.

Comment (zeertzjq) [reply src/nvim/sign.c:603]: Oh right.

**Review by zeertzjq — APPROVED** [review]
