### PR TITLE
fix(marks): line('w$', win) incorrect with conceal_lines 

### LINKED ISSUE #36641: LSP: incorrect highlights in floating wins of height 1
### Problem

After https://github.com/neovim/neovim/commit/098da1fc2c9ba65adb9c2f7ecb76b26f6e6b0383 floating windows with height 1, concealed lines and `concealcursor=""` are wrongly highlighted prior to redraw. This applies to LSP windows since https://github.com/neovim/neovim/commit/4b8980949cd47f8206b2fbc266dfeb0920fd1191 and the issue was exposed by tests updated in https://github.com/neovim/neovim/commit/6638a58fdac7fdfa677a41e355b781616eb9dd29

It seems that it uses the ` ``` ` highlight color for the entire buffer.
1763672531_screenshot

### Steps to reproduce

`minimal.lua` which basically extracts the LSP test
```lua
local floating_bufnr = vim.api.nvim_create_buf(false, true)

vim.api.nvim_buf_set_lines(floating_bufnr, 0, -1, false, { "```lua", "local foo", "```"})

local floating_winnr = vim.api.nvim_open_win(floating_bufnr, false, {
	relative = "win",
	row = 3,
	col = 3,
	style = "minimal",
	border = "single",
	width = 10,
	height = 1,
})

vim.wo[floating_winnr].conceallevel = 2
vim.wo[floating_winnr].concealcursor = ""
vim.bo[floating_bufnr].filetype = "markdown"

vim.treesitter.start(floating_bufnr, "markdown")
```

```sh
nvim --clean -u minimal.lua
```

### Expected behavior

After `:redraw`

1763672535_screenshot

### Nvim version (nvim -v)

v0.12.0-dev-1667+gea70d2ad85

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Linux arch 6.17.3-arch2-1

### Terminal name/version

alacritty 0.17.0-dev

### $TERM environment variable

alacritty

### Installation

Build from source

### PR DESCRIPTION
**Pull request by tomtomjhj**
Background:
Suppose a window has concealed lines, and sets conceallevel>2,
concealcursor="". The concealed lines are displayed if the window is
curwin and the cursor is on the those lines.

Problem:
line('w$', win) switches curwin to win, and then does validate_botline
for curwin. It computes botline assuming the concealed lines displayed,
resulting in a smaller value than the actual botline that the user sees.

Solution:
Evaluate line('w$', win) without switching curwin.
Apply similar changes to other functions that switches curwin.

Fixes: https://github.com/neovim/neovim/issues/36641, https://github.com/neovim/neovim/pull/36609. These are already "fixed" by https://github.com/neovim/neovim/pull/36951, but it did not fix the underlying cause, as demonstrated by the test added in this PR.

### CODE REVIEW

File: src/nvim/eval/funcs.c [hunk 1]
```diff
@@ -670,32 +670,26 @@ static void get_col(typval_T *argvars, typval_T *rettv, bool charcol)
...
-  pos_T *fp = var2fpos(&argvars[0], false, &fnum, charcol);
-  if (fp != NULL && fnum == curbuf->b_fnum) {
+  int fnum = bp->b_fnum;
+  pos_T *fp = var2fpos(&argvars[0], false, &fnum, charcol, wp);
+  if (fp != NULL && fnum == bp->b_fnum) {
     if (fp->col == MAXCOL) {
       // '> can be MAXCOL, get the length of the line then
-      if (fp->lnum <= curbuf->b_ml.ml_line_count) {
+      if (fp->lnum <= bp->b_ml.ml_line_count) {
         col = ml_get_len(fp->lnum) + 1;
```
Comment (zeertzjq) [inline src/nvim/eval/funcs.c]:
```suggestion
        col = ml_get_buf_len(bp, fp->lnum) + 1;
```

File: src/nvim/eval/funcs.c [hunk 2]
```diff
@@ -704,11 +698,11 @@ static void get_col(typval_T *argvars, typval_T *rettv, bool charcol)
       col = fp->col + 1;
       // col(".") when the cursor is on the NUL at the end of the line
       // because of "coladd" can be seen as an extra column.
-      if (virtual_active(curwin) && fp == &curwin->w_cursor) {
+      if (virtual_active(wp) && fp == &wp->w_cursor) {
         char *p = get_cursor_pos_ptr();
```
Comment (zeertzjq) [inline src/nvim/eval/funcs.c]: You can't use `get_cursor_pos_ptr()` here now.

File: src/nvim/eval.c [hunk 3]
```diff
@@ -5263,11 +5263,13 @@ int buf_charidx_to_byteidx(buf_T *buf, linenr_T lnum, int charidx)
...
 /// @return Pointer to position or NULL in case of error (e.g. invalid type).
 pos_T *var2fpos(const typval_T *const tv, const bool dollar_lnum, int *const ret_fnum,
-                const bool charcol)
+                const bool charcol, win_T *wp)
   FUNC_ATTR_WARN_UNUSED_RESULT FUNC_ATTR_NONNULL_ALL
 {
   static pos_T pos;
 
+  buf_T *bp = wp->w_buffer;
+
```
Comment (zeertzjq) [inline src/nvim/eval.c:5273]: - `ml_get()` -> `ml_get_buf()`
- `ml_get_len()` -> `ml_get_buf_len()`

File: src/nvim/eval.c [hunk 4]
```diff
@@ -5328,18 +5331,18 @@ pos_T *var2fpos(const typval_T *const tv, const bool dollar_lnum, int *const ret
   pos.lnum = 0;
   if (name[0] == '.') {
     // cursor
-    pos = curwin->w_cursor;
+    pos = wp->w_cursor;
   } else if (name[0] == 'v' && name[1] == NUL) {
     // Visual start
     if (VIsual_active) {
```
Comment (zeertzjq) [inline src/nvim/eval.c]:
```suggestion
    if (VIsual_active && wp == curwin) {
```

**Review by zeertzjq — APPROVED** [review]
