### PR TITLE
fix(lua): do not allow `vim.wait()` in fast callbacks

### LINKED ISSUE #26122: Calling `vim.wait` within fast events results in crash
### Problem

Calling `vim.system` within `vim.loop` results in failure, causing Neovim to exit with a 134 status code.

### Steps to reproduce

- Create following `repro.lua`
```lua
vim.loop.timer_start(vim.loop.new_timer(), 0, 100, function()
  vim.system({ 'echo' }):wait()
end)
```
- Open `nvim` with `nvim -u NORC -u repro.lua`.

### Expected behavior

Successfully opened neovim.

### Neovim version (nvim -v)

v0.10.0-dev-1453+ge0d97d264-Homebrew

### Operating system/version

macOS 14.1.1

### Terminal name/version

wezterm

### $TERM environment variable

wezterm

### Installation

homebrew

### PR DESCRIPTION
**Pull request by lewis6991**
`vim.wait()` cannot be called in a fast callback since the main loop cannot be run in that context as it is not reentrant

Fixes #26122

### CODE REVIEW

File: src/nvim/event/loop.c [hunk 1]
```diff
@@ -87,6 +87,29 @@ bool loop_poll_events(Loop *loop, int64_t ms)
   return timeout_expired;
 }
 
+/// If`multiqueue` has events then process them and return.
+/// Otherwise `loop` is non-NULL, run it once and process it's fast events.
```
Comment (justinmk) [inline src/nvim/event/loop.c:91]:
```suggestion
/// If `multiqueue` has events then process them and return.
/// Otherwise `loop` is non-NULL, run it once and process its fast events.
```

File: test/functional/lua/vim_spec.lua [hunk 2]
```diff
@@ -2769,6 +2769,19 @@ describe('lua stdlib', function()
         eq({'notification', 'wait', {-2}}, next_msg(500))
       end)
     end)
+
+    it('should not run the main loop in fast callbacks (#26122)', function()
```
Comment (justinmk) [inline test/functional/lua/vim_spec.lua:2773]: `#` is enough to disambiguate
```suggestion
    it('should not run the main loop in fast callbacks #26122', function()
```

File: src/nvim/lua/executor.c [hunk 3]
```diff
@@ -469,7 +469,10 @@ static int nlua_wait(lua_State *lstate)
   // Flush screen updates before blocking.
   ui_flush();
 
-  LOOP_PROCESS_EVENTS_UNTIL(&main_loop,
+  // Never run the main loop when we are in a fast callback.
+  Loop *loop = in_fast_callback ? NULL : &main_loop;
```
Comment (justinmk) [inline src/nvim/lua/executor.c:473]: This makes sense to me and is the general direction I hope we can drive towards. In general scripts shouldn't have to check `vim.in_fast_event()` or manually schedule() things.

Comment (lewis6991) [reply src/nvim/lua/executor.c:473]: In general I think they still have to, it's just that `vim.wait()` was initially designed to be callable in fast callbacks, however there existed a path which caused it to run the main loop and crash.

Comment (justinmk) [reply src/nvim/lua/executor.c:473]: > In general I think they still have to,

yes, out of scope for this PR, but still something we can aspire to.

File: src/nvim/event/loop.c [hunk 4]
```diff
@@ -87,6 +87,31 @@ bool loop_poll_events(Loop *loop, int64_t ms)
...
+    return false;
+  }
+
+  if (loop) {
+    bool timeout_expired = loop_uv_run(loop, ms, true);
+    multiqueue_process_events(loop->fast_events);
+    return timeout_expired;
+  }
+
+  return true;
```
Comment (zeertzjq) [inline src/nvim/event/loop.c:112]: Why `return true`? Doesn't this cause the wait to be too short?

Comment (zeertzjq) [inline src/nvim/event/loop.c:112]: This means `vim.wait()` doesn't wait at all in a fast context, which may be confusing.

Comment (justinmk) [reply src/nvim/event/loop.c:112]: Hmm, doesn't the doc for the `fast_only` parameter imply that this is already the case? 

Do we need a `fast_loop` where non-editor, Lua-only processing is done?

```
      • {fast_only}  (boolean|nil) If true, only |api-fast| events will be
                     processed. If called from while in an |api-fast| event,
                     will automatically be set to `true`.
```

Comment (lewis6991) [reply src/nvim/event/loop.c:112]: One of the main use cases for `vim.wait()` is to for applications like `vim.system()` where we want to uv to poll and check for IO, however this only happens on the main loop.

> Or does NULL already work like that?

NULL just ensures we never run the main loop, but it will still process any outstanding fast/main events. However I think zeer is right and maybe this change is wrong.

I don't see how we can run the uv loop when we are in a fast callback, so maybe we just disallow it since it would become a massive foot gun otherwise.

> Do we need a fast_loop where non-editor, Lua-only processing is done? 

This probably surpasses my knowledge of how the event loop works, but are you suggesting we create another loop which uv binds to in fast-callbacks? Could that even work?

Comment (bfredl) [reply src/nvim/event/loop.c:112]: IMO introducing a secondary event loop would be the wrong way to go. 

if we want to allow "sync style" code inside callback (i e a `vim.system` which waits and returns, instead of taking yet another callback), we need to use something based on co-routines, so the callback can be suspended and the top-level event loop resumed.

Comment (justinmk) [reply src/nvim/event/loop.c:112]: > I don't see how we can run the uv loop when we are in a fast callback,

Another (half-baked, probably wrong) thought was for the fast callback to "re-schedule itselfon the main loop". But suspend-and-resume as @bfredl mentioned, sounds much better.

Comment (justinmk) [reply src/nvim/event/loop.c:112]: > It may just to easier to disallow `vim.wait` in fast events.

Throwing an error is fine for now, because it's a 2-way door: we can always relax it in the future.

**Comment by lewis6991** [comment]
I've pivoted this PR to just disallow `vim.wait` in api-fast, however I've raised https://github.com/neovim/neovim/pull/26198 to experiment with the suspend and resume idea.

File: test/functional/lua/vim_spec.lua [hunk 5]
```diff
@@ -2769,6 +2769,19 @@ describe('lua stdlib', function()
...
+      exec_lua([[
+        vim.uv.new_timer():start(0, 100, function()
+          local count = 0
+          vim.wait(100, function()
+            count = count + 1
+            return count == 10
+          end, 100)
+        end)
+      ]])
+      assert_alive()
```
Comment (justinmk) [inline test/functional/lua/vim_spec.lua:2783]: can we also assert the error message?

Comment (lewis6991) [reply test/functional/lua/vim_spec.lua:2783]: Not easily since the error happens in a luv callback which doesn't get sent back over RPC to busted.
