### PR TITLE
fix(api): do not re-apply win_config.style when missing

### LINKED ISSUE #20370: `nvim_win_set_config()` reapplies `style` if it is not updated
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1178-g1d337d4e2

### Vim (not Nvim) behaves the same?

No, Vim doesn't have Lua API

### Operating system/version

EndeavourOS Linux x86_64, 5.19.10-arch1-1

### Terminal name/version

xfce4-terminal 1.0.4 (Xfce 4.16)

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

- `nvim -u NONE`
- `:lua win_id = vim.api.nvim_open_win(0, false, {relative = 'editor', row = 10, col = 10, width = 10, height = 10, style = 'minimal'})`
- `:lua vim.api.nvim_win_set_option(win_id, 'signcolumn', 'yes')`
- `:lua vim.api.nvim_win_set_config(win_id, {width = 20})`

### Expected behavior

Sign column doesn't disappear. This is what happens if floating window is opened without setting `style = 'minimal'`.

### Actual behavior

Sign column disappears.

Demo:

https://user-images.githubusercontent.com/24854248/192528856-46c2c752-ec85-4455-8e00-c1c5f3df05c9.mp4

### PR DESCRIPTION
**Pull request by MunifTanjim**
> **Note**
> For `0.10` release

resolves https://github.com/neovim/neovim/issues/20370

### CODE REVIEW

**Comment by clason** [comment]
should this be backported?

File: src/nvim/api/win_config.c [hunk 1]
```diff
@@ -222,9 +223,11 @@ void nvim_win_set_config(Window window, Dict(float_config) *config, Error *err)
     win_config_float(win, fconfig);
     win->w_pos_changed = true;
   }
-  if (fconfig.style == kWinStyleMinimal) {
-    win_set_minimal_style(win);
-    didset_window_options(win, true);
+  if (prev_style != fconfig.style) {
```
Comment (bfredl) [inline src/nvim/api/win_config.c:226]: I think if you explicitly pass-in `style="minimal"` a second time it should still apply again.

Comment (MunifTanjim) [reply src/nvim/api/win_config.c]: Updated.
