### PR TITLE
fix(treesitter): fix `:InspectTree` incorrect injections

### LINKED ISSUE #147: bug: Latex injections appear multiple times in AST
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Describe the bug

When I edit a markdown file, latex injections appear multiple times in the AST shown by `:InspectTree`. I'm not sure if this is a bug, but it seems weird and I wanted to report it.

### Steps To Reproduce/Bad Parse Tree

1. Have nvim-treesitter plugin with markdown\* and latex parsers installed
2. `:set ft=markdown`
3. paste
    ```
    some text

    $\alpha = 1$
    ```
4. `:InspectTree`

Result: The inline math is present multiple times in the AST, specifically it is present where the cursor is in the picture below. If there are `n` paragraphs before the inline math in the markdown file, the inline math is is present `n+1` times in the AST.

screen_2024-05-07_051336

**Additional Info**

- Neovim: Tried with 0.9.5 and nightly
- nvim-treesitter 19c6b0c4c9b35962e45b782e2b85a3214d2ac4d5 (2024 Apr 25)

### Expected Behavior/Parse Tree

I would expect the inline math to show only once in the AST.

### PR DESCRIPTION
**Pull request by yuukibarns**
fix https://github.com/tree-sitter-grammars/tree-sitter-markdown/issues/147

### CODE REVIEW

**Comment by clason** [comment]
Can you please write a self-contained commit message (in  the format "Problem: ... Solution: ...")? And ideally add a test that fails on `master`? Otherwise this change is likely to get lost in the future.

**Comment by yuukibarns** [comment]
Sorry for casually open this PR which appears to be more like a draft.

I am not familiar with the procedure of committing code to neovim so I wonder if I should close this PR and open an issue instead?

I have to say there might be something wrong with this line

```lua
local node = assert(parent:named_descendant_for_range(r:range()))
``` 

and my pr is simply a workaround.

**Comment by clason** [comment]
You can `git commit --amend` your commit description, no need for a new PR. (Although if you do open a new one, please create a feature branch for it first.)

**Comment by justinmk** [comment]
It will save a lot of time to say what "problem" you are solving. 

> I have to say there might be something wrong with this line
> 
> ```lua
> local node = assert(parent:named_descendant_for_range(r:range()))
> ```

That's also my first question.

Is this change trying to check if `r:range()` is a descendant of `parent:range()`? If so, I would expect `parent:named_descendant_for_range(r:range())` to already do that.

**Comment by justinmk** [comment]
looking at https://github.com/neovim/neovim/blob/d2dd403693e39396632c9b0446157bb8e71d4fef/runtime/lua/vim/treesitter/languagetree.lua#L1347 , I wonder if this line needs to change to : 

```lua
local node = assert(parent:named_descendant_for_range(unpack(r:range())))
```

File: runtime/lua/vim/treesitter/dev.lua [hunk 1]
```diff
@@ -96,16 +96,22 @@ function TSTreeView:new(bufnr, lang)
...
-        if not injections[id] or r:byte_length() > injections[id].root:byte_length() then
-          injections[id] = {
-            lang = child:lang(),
-            root = r,
-          }
+        local start_row_, start_col_, end_row_, end_col_ = r:range()
+        -- Check if r is inside parent.
+        if (start_row < start_row_ or (start_row == start_row_ and start_col <= start_col_)) and
+            (end_row > end_row_ or (end_row == end_row_ and end_col >= end_col_)) then
+          local node = assert(parent:named_descendant_for_range(r:range()))
```
Comment (justinmk) [inline runtime/lua/vim/treesitter/dev.lua:107]: looking at https://github.com/neovim/neovim/blob/d2dd403693e39396632c9b0446157bb8e71d4fef/runtime/lua/vim/treesitter/languagetree.lua#L1347 , I wonder if the line in this PR needs to change to : 


```suggestion
          local node = assert(parent:named_descendant_for_range(unpack(r:range())))
```

**Comment by yuukibarns** [comment]
Exactly, and I found in original code this function does not function rightly and I try to workaround it in this pr.

**Comment by justinmk** [comment]
so can you please try the 1-line change i suggested? https://github.com/neovim/neovim/pull/33198#discussion_r2020191185

**Comment by yuukibarns** [comment]
No, they are different, here `r:range()` correctly returns four integers which is the expected behavior.

**Comment by yuukibarns** [comment]
> It will save a lot of time to say what "problem" you are solving.

The problem this pr solves is quite simple, `parent_tree` is paired with `parent_ltree` while for `parent_ltree`'s children their trees are independent with the `parent_tree`, resulting in separation of `parent` and `r`, they will be irrelevant if there are many `parent_tree`'s like the case `markdown_inline` and `latex` I mentioned above https://github.com/tree-sitter-grammars/tree-sitter-markdown/issues/147

But I think there are more to be done with the highlighting in markdown, not just a print command like `:InspectTree`, the separation between language trees and treesitter trees may result in unnecessary reparsing.

File: runtime/lua/vim/treesitter/dev.lua (hunk 1 above)
Comment (lewis6991) [reply runtime/lua/vim/treesitter/dev.lua:107]: `range()` returns varargs, not a table, so `unpack` is not needed.

**Comment by lewis6991** [comment]
Here's a before (top) and after (bottom) screenshot with the issues in https://github.com/tree-sitter-grammars/tree-sitter-markdown/issues/147

image

Before the latex injection was being inserted into both paragraphs.

**Review by justinmk — APPROVED** [review]
lint is failing
