### PR TITLE
fix(windows):exepath, stdpath return wrong slashes

### LINKED ISSUE #13787: stdpath() returns mixed path separators with shellslash option
- `nvim --version`:
```
NVIM v0.5.0-dev+1022-g77a6049e0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/projects/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-129

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently? `N/A`
- Operating system/version: `Windows 10`
- Terminal name/version: `Windows terminal 1.4.201119003-release 1.4`
- `$TERM`: `N/A`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:echo stdpath('data')
:set shellslash
:echo stdpath('data')
```

### Actual behaviour
Returns mixed \ and / path string 
`C:\Users\$USER\AppData\Local/nvim-data`

### Expected behaviour
Respect shellslash and get a forwarded slashed path 
`C:/Users/$USER/AppData/Local/nvim-data`

### PR DESCRIPTION
**Pull request by 3N4N**
Closes #13787. `exepath` and `stdpath` should respect `shellslash` and return path with
proper file separator.

### CODE REVIEW

**Comment by 3N4N** [comment]
Need someone to check if failing this test in BSD is just a GH "flake" (as Clason put it the other day), or an actual problem.

https://github.com/neovim/neovim/blob/cf23695dd748281daaf68e69ac48bf9eb27f2425/test/functional/treesitter/parser_spec.lua#L170-L189

File: test/functional/vimscript/executable_spec.lua [hunk 1]
```diff
@@ -17,6 +17,21 @@ describe('executable()', function()
     eq(1, call('executable', 'false'))
   end)
 
+  if iswin() then
+    it('exepath respects shellslash', function()
+      command('let $PATH = fnamemodify("./test/functional/fixtures/bin", ":p")')
+      eq('test\\functional\\fixtures\\bin\\null.CMD', call('fnamemodify', call('exepath', 'null'), ':.'))
+      command('set ssl')
```
Comment (justinmk) [inline test/functional/vimscript/executable_spec.lua:24]: in scripts and code it is almost always preferred to spell out the full name (helps with `grep` etc)
```suggestion
      command('set shellslash')
```

File: test/functional/vimscript/executable_spec.lua [hunk 2]
```diff
@@ -17,6 +17,21 @@ describe('executable()', function()
...
+      eq('test/functional/fixtures/bin/null.CMD', call('fnamemodify', call('exepath', 'null'), ':.'))
+    end)
+
+    it('stdpath respects shellslash', function()
+      eq('build\\Xtest_xdg\\share\\nvim-data', call('fnamemodify', call('stdpath', 'data'), ':.'))
+      command('set ssl')
```
Comment (justinmk) [inline test/functional/vimscript/executable_spec.lua:30]:
```suggestion
      command('set shellslash')
```

**Comment by 3N4N** [comment]
All suggestions committed. And thanks for the rationale behind not abbreviating.

**Comment by 3N4N** [comment]
The macos CI (the failed one) possibly needs another go.
