### PR TITLE
fix(lsp): autotrigger on last character from sequence inserted at once

### LINKED ISSUE #35417: LSP: sequence of trigger characters typed "at once" from imap may not work properly
### Problem

Assume we have attached two language servers both providing completion with single trigger characters `-` and `>` respectively. 

Then map `vim.keymap.set('i', '<A-.>', '->')`. 

When `->` is inserted from that keymap, then `>` doesn't act as a trigger character because `completion_timer` started for `-` is still alive. As the result, we get completion items from `ls1` only.

https://github.com/neovim/neovim/blob/30dae87de4c6d6c8bda9657e22e187634cfa12a8/runtime/lua/vim/lsp/completion.lua#L572-L587

### Steps to reproduce

`init.lua`:
````lua
local function createServer(opts)
  opts = opts or {}
  local server = {}
  server.messages = {}

  function server.cmd(dispatchers)
    local closing = false
    local handlers = opts.handlers or {}
    local srv = {}

    function srv.request(method, params, callback)
      table.insert(server.messages, {
        method = method,
        params = params,
      })
      local handler = handlers[method]
      if handler then
        handler(method, params, callback)
      elseif method == 'initialize' then
        callback(nil, {
          capabilities = opts.capabilities or {},
        })
      elseif method == 'shutdown' then
        callback(nil, nil)
      end
      local request_id = #server.messages
      return true, request_id
    end

    function srv.notify(method, params)
      table.insert(server.messages, {
        method = method,
        params = params,
      })
      if method == 'exit' then
        dispatchers.on_exit(0, 15)
      end
    end

    function srv.is_closing()
      return closing
    end

    function srv.terminate()
      closing = true
    end

    return srv
  end

  return server
end

local completionResultPhpactor = {
  isIncomplete = false,
  items = {
    {
      additionalTextEdits = {{
        newText = 'use ReturnTypeWillChange;\n',
        range = {
          ['end'] = {
            character = 0,
            line = 1
          },
          start = {
            character = 0,
            line = 1
          }
        },
      }},
      label = 'return',
      insertText = 'return $1;$0',
      kind = vim.lsp.protocol.CompletionItemKind.Keyword,
      insertTextFormat = vim.lsp.protocol.InsertTextFormat.Snippet,
      detail = 'Result from Phpactor',
      sortText = '-255-return ',
    },
  },
}

local completionResultNullLs = {
  isIncomplete = false,
  items = {
    {
      label = '/**',
      insertText = '/** ${1:hello} */',
      insertTextFormat = 2,
      kind = 15,
      detail = 'Result from null-ls',
    },
  },
}

local function createServerWithCompletionProvider(completionResult, triggerCharacters)
  return createServer({
    capabilities = {
      completionProvider = {
        triggerCharacters = triggerCharacters
      },
    },
    handlers = {
      ['textDocument/completion'] = function (_, _, callback)
        callback(nil, completionResult)
      end,
    },
  })
end

local function startClient(name, completionResult, triggerCharacters)
  vim.lsp.start({
    name = name,
    cmd = createServerWithCompletionProvider(completionResult, triggerCharacters).cmd,
    on_attach = function (client, bufnr0)
      vim.lsp.completion.enable(true, client.id, bufnr0, {autotrigger = true})
      vim.keymap.set('i', '<A-.>', '->', {buffer = bufnr0})
    end,
  })
end

vim.o.completeopt = 'popup,menuone,noinsert,fuzzy'
vim.fn.complete = vim.schedule_wrap(vim.fn.complete)

vim.api.nvim_create_autocmd('UIEnter', {
  callback = function ()
    startClient('fake-null-ls', completionResultNullLs, {'-'})
    startClient('fake-phpactor', completionResultPhpactor, {'>'})
  end
})
````
- `nvim -u init.lua`
- in Insert mode see effects of typing `-`, `>`, `->` (manually) and `<A-.>`.

### Expected behavior

In the repro: if `->` is typed from `<A-.>` mapping, only call to `fake-phpactor` should be triggered.

### Nvim version (nvim -v)

v0.12.0-dev-1050+g9467731865

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Debian Sid

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

from repo

### PR DESCRIPTION
**Pull request by przepompownia**
## Problem:

If there are 2 language servers with different trigger chars (`-` and `>`), and a keymap inputs both simultaneously (`->`), then `>` doesn't trigger. We get completion items from server1 only.

This happens because the `completion_timer` for the `-` trigger is still pending.

## Solution: 

If the next character arrived enough quickly (< 25 ms), replace the existing deferred autotrigger with a new one that matches this later character.

Fixes #35417

### CODE REVIEW

**Comment by przepompownia** [comment]
At the moment I cannot find how to correctly simulate inserting `->` in the test case.

**Comment by przepompownia** [comment]
@mfussenegger, let me ping here if you're still interested.

File: test/functional/plugin/lsp/completion_spec.lua [hunk 1]
```diff
@@ -1037,6 +1037,34 @@ describe('vim.lsp.completion: protocol', function()
     end)
   end)
 
+  it('insert two characters at once triggers clients matching only the second one', function()
```
Comment (justinmk) [inline test/functional/plugin/lsp/completion_spec.lua]:
```suggestion
  it('treats 2-triggers-at-once as "last char wins"', function()
```

**Comment by justinmk** [comment]
Rebasing and pinging helps, thanks. You considered the referenced issues and explained the problem well, and there's a test, so I think we should try this.

Note: the problem was hard to understand, but the example in https://github.com/neovim/neovim/issues/35417#issue-3341755960 makes it very easy to understand. It is usually much more effective to mention a concrete example as the Problem. Any other details can be in an "Analysis". So I updated the description here with that.

File: runtime/lua/vim/lsp/completion.lua [hunk 2]
```diff
@@ -571,7 +571,8 @@ local function on_insert_char_pre(handle)
 
   local char = api.nvim_get_vvar('char')
   local matched_clients = handle.triggers[char]
-  if not completion_timer and matched_clients then
+  reset_timer()
```
Comment (justinmk) [inline runtime/lua/vim/lsp/completion.lua:576]:
```suggestion
  -- Discard pending trigger char, complete the "latest" one.
  -- Can happen if a mapping inputs multiple trigger chars simultaneously.
  reset_timer()
```
