### PR TITLE
fix(highlight): refresh highlight attrs before message output

### LINKED ISSUE #17832: Message area cleared when using highlight MsgArea
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

No; 8.2.3489

### Operating system/version

macOS 12.3

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

Using `nvim --clean -u minimal.lua` where `minimal.lua` contains:

```
vim.cmd 'highlight MsgArea guifg=#aeafb0 guibg=NONE gui=NONE guisp=NONE'
print("TEST TEST TEST")
```
The `highlight` command causes the message area to be cleared such that the `print` flashes by in a millisecond. When there are 2 `print` statement this is not a problem as the pager is invoked before nvim draws the initial screen.

vim (not nvim) invokes the pager on a single print so this is not a problem on vim.

Note: I first noticed this issue using the NightFox theme and have an open problem there (https://github.com/EdenEast/nightfox.nvim/issues/98). I narrowed it down to the single highligh command show above.

### Expected behavior

Expected that a single print statement would be readable, either by be left in the MsgArea or by invoking the pager on startup. This is only a problem on startup.

### Actual behavior

I've got nothing new to say here!

### PR DESCRIPTION
**Pull request by glepnir**
Problem: When MsgArea highlight is changed, the following message
may flash and disappear because msg_start() renders with stale highlight attributes.

Solution: Call highlight_changed() in msg_start() when
need_highlight_changed is set, ensuring highlight attrs are
up-to-date before any message output.

Fix #17832

### CODE REVIEW

File: src/nvim/highlight_group.c [hunk 1]
```diff
@@ -2179,6 +2179,7 @@ void highlight_changed(void)
     if (highlight_attr[hlf] != highlight_attr_last[hlf]) {
       if (hlf == HLF_MSG) {
         clear_cmdline = true;
+        update_cmdline = true;
```
Comment (glepnir) [inline src/nvim/highlight_group.c:2182]: a new variable in there not be a good choice. tried use `redraw_cmdline` in there seems not works correctly . still use an exist global status variable will be accept I think

Comment (bfredl) [reply src/nvim/highlight_group.c:2182]: maybe `need_clr_eos` can be used instead.

File: src/nvim/message.c [hunk 2]
```diff
@@ -3022,6 +3022,13 @@ void msg_clr_eos_force(void)
     msg_row = msg_grid_pos;
   }
 
+  if (update_cmdline && msg_col > 0) {
+    for (int i = 0; i < msg_col; i++) {
+      grid_fill(&msg_grid_adj, msg_row, msg_row + 1, i,  i + 1, (int)msg_grid.chars[i],
```
Comment (bfredl) [inline src/nvim/message.c:3027]: too much of a hack, better to just let existing cells be what they are.

Comment (glepnir) [reply src/nvim/message.c:3027]: this will make exist cell use new attr . otherwise they are not take effect

Comment (glepnir) [reply src/nvim/message.c:3027]: hmm this will make terminal/buffer_spec failed

Comment (glepnir) [reply src/nvim/message.c:3027]: this more hack..can make test pass..but I think this is not allowed.

```diff
diff --git a/src/nvim/message.c b/src/nvim/message.c
index bb5bd9753..852223157 100644
--- a/src/nvim/message.c
+++ b/src/nvim/message.c
@@ -3022,7 +3022,7 @@ void msg_clr_eos_force(void)
     msg_row = msg_grid_pos;
   }

-  if (need_clr_eos && msg_col > 0) {
+  if (need_clr_eos && msg_col > 0 && msg_grid.chars[0] != '-') {
     for (int i = 0; i < msg_col; i++) {
       grid_fill(&msg_grid_adj, msg_row, msg_row + 1, i,  i + 1, (int)msg_grid.chars[i],
                 (int)msg_grid.chars[i], HL_ATTR(HLF_MSG));
```

File: src/nvim/message.c [hunk 3]
```diff
@@ -3022,6 +3022,13 @@ void msg_clr_eos_force(void)
     msg_row = msg_grid_pos;
   }
 
+  if (need_clr_eos && msg_col > 0 && msg_grid.chars[0] != '-') {
```
Comment (nwounkn) [inline src/nvim/message.c:3025]: Won't this break for multiline messages, messages that start with `-`, and cmdline drawn from right to left?

File: src/nvim/message.c [hunk 4]
```diff
@@ -3022,6 +3022,13 @@ void msg_clr_eos_force(void)
...
+    for (int i = 0; i < msg_col; i++) {
+      grid_fill(&msg_grid_adj, msg_row, msg_row + 1, i,  i + 1, (int)msg_grid.chars[i],
+                (int)msg_grid.chars[i], HL_ATTR(HLF_MSG));
```
Comment (nwounkn) [inline src/nvim/message.c:3028]: What about error messages?

File: src/nvim/message.c (hunk 2 above)
Comment (bfredl) [reply src/nvim/message.c:3027]: It is too late to change highlights here, also for the reasons nwounkn mentioned. I rather think that this is missing:
```
diff --git a/src/nvim/message.c b/src/nvim/message.c
index c1acef8b0d..d73f9562e4 100644
--- a/src/nvim/message.c
+++ b/src/nvim/message.c
@@ -32,6 +32,7 @@
 #include "nvim/globals.h"
 #include "nvim/grid.h"
 #include "nvim/highlight.h"
+#include "nvim/highlight_group.h"
 #include "nvim/indent.h"
 #include "nvim/input.h"
 #include "nvim/keycodes.h"
@@ -1418,6 +1419,10 @@ void msg_start(void)
     need_fileinfo = false;
   }
 
+  if (need_highlight_changed) {
+    highlight_changed();
+  }
+
   if (need_clr_eos || (p_ch == 0 && redrawing_cmdline)) {
     // Halfway an ":echo" command and getting an (error) message: clear
     // any text from the command.
```

File: src/nvim/message.c (hunk 3 above)
Comment (glepnir) [reply src/nvim/message.c:3025]: maybe. i thought a new way .i will rewrite here after i wake up
 🙃

File: src/nvim/message.c (hunk 2 above)
Comment (glepnir) [reply src/nvim/message.c]: oh yep. in msg_start refresh highlight will be a good point :) get it.

**Comment by bfredl** [comment]
Updated test looks good. Something weird is going on in the ` uchar (cc=gcc)` build causing the last cell of a filler line to be missed, likely some issue in underlying grid.c code..

**Comment by glepnir** [comment]
and seems like only on windows ? I don't have a windows env :thinking:

**Comment by bfredl** [comment]
Try rebase on latest master, changes were made to the CI job which might be relevant (no more uchar).

**Comment by glepnir** [comment]
still has one cell no attr in windows.

**Comment by justinmk** [comment]
needs a rebase

File: test/functional/ui/highlight_spec.lua [hunk 5]
```diff
@@ -2670,4 +2670,18 @@ describe('fg/bg special colors', function()
     eq(new_guifg, eval('synIDattr(hlID("Visual"), "bg#")'))
     eq(new_guibg, eval('synIDattr(hlID("Visual"), "sp#")'))
   end)
+
+  it('refresh cmdline after MsgArea set #17832', function()
+    local screen = Screen.new(50, 7, { rgb = true })
+    command('set termguicolors')
+    command('call nvim_set_hl(0, "MsgArea", {"fg": "Red"})')
+    command('echomsg "foo"')
```
Comment (zeertzjq) [inline test/functional/ui/highlight_spec.lua]: You need to put the highlight change and the message in a single RPC request, otherwise the test passes even without this PR.
```suggestion
    command('call nvim_set_hl(0, "MsgArea", {"fg": "Red"}) | echomsg "foo"')
```

File: src/nvim/message.c [hunk 6]
```diff
@@ -1655,6 +1655,10 @@ void msg_start(void)
     need_fileinfo = false;
   }
 
+  if (need_highlight_changed) {
+    highlight_changed();
```
Comment (justinmk) [inline src/nvim/message.c:1659]: This change makes sense and the test changes seem to indicate a needed effect. But reviewing the docstring on `highlight_changed`, and the existing refs to `need_highlight_changed`, I am wondering why the existing [call in update_screen](https://github.com/neovim/neovim/blob/501a21f3339025f7afabc2ae29ae485cce9d64e5/src/nvim/drawscreen.c#L561-L564) is not already achieving this?

I guess it's because `msg_puts_len` uses the highlights before `update_screen`. But this is something the PR description should mention.

File: test/functional/ui/highlight_spec.lua [hunk 7]
```diff
@@ -2670,4 +2670,17 @@ describe('fg/bg special colors', function()
     eq(new_guifg, eval('synIDattr(hlID("Visual"), "bg#")'))
     eq(new_guibg, eval('synIDattr(hlID("Visual"), "sp#")'))
   end)
+
+  it('refresh cmdline after MsgArea set #17832', function()
```
Comment (justinmk) [inline test/functional/ui/highlight_spec.lua]: This test description is useless and misleading. Is it about MsgArea specifically, or any highlight? Why is the test in the `describe('fg/bg special colors'` block? It seems like a more general bug, something like this (correct me if wrong):

```suggestion
  it('changed highlight is reflected in messages before redraw #17832', function()
```

File: test/functional/ui/highlight_spec.lua [hunk 8]
```diff
@@ -2670,4 +2670,17 @@ describe('fg/bg special colors', function()
...
+    local screen = Screen.new(50, 7, { rgb = true })
+    command('set termguicolors')
+    command('call nvim_set_hl(0, "MsgArea", {"fg": "Red"}) | echomsg "foo"')
```
Comment (justinmk) [inline test/functional/ui/highlight_spec.lua:2678]:
```suggestion
    -- :echomsg in the same request, before the next redraw.
    command('call nvim_set_hl(0, "MsgArea", {"fg": "Red"}) | echomsg "foo"')
```
