### PR TITLE
fix(api, lua): make blank lines in a message work properly

### LINKED ISSUE #24242: `vim.print` skips blank lines
### Problem

`vim.print` will skip blank lines.
When I tried to inspect the contents of the string, I was confused because the contents are different.

### Steps to reproduce

`:lua vim.print("a\n\nb")`

### Expected behavior

following message is printed
```
a

b
```

### Neovim version (nvim -v)

v0.10.0-dev-4fd852b

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux on WSL

### Terminal name/version

WezTerm

### $TERM environment variable

xterm-256color

### Installation

Build from source

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #24242

`nvim_echo` already handles this properly.

### CODE REVIEW

File: test/functional/api/vim_spec.lua [hunk 1]
```diff
@@ -577,7 +577,6 @@ describe('API', function()
     local start_dir
 
     before_each(function()
-      clear()
```
Comment (justinmk) [inline test/functional/api/vim_spec.lua:580]: should probably have the `nvim_set_current_dir` tests in a single `it()` instead of having multiple `it()` blocks that depend on each toher.

Comment (zeertzjq) [reply test/functional/api/vim_spec.lua:580]: They don't depend on each other, because there is still a `before_each(clear)` at the top.
