### PR TITLE
fix(memline): don't check line count for closed memline

### LINKED ISSUE #31251: `ml_get` errors after  #31042
### Problem

After 235cb5b (#31042) I'm now getting random errors. Initially from gitsigns but I've minimised below.

```
Error executing vim.schedule lua callback: /Users/lewrus01/projects/neovim/issue.lua:13: Vim:E315: ml_get: Invalid lnum: 1
stack traceback:
        [C]: in function 'quit'
        /Users/lewrus01/projects/neovim/issue.lua:13: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

### Steps to reproduce

```lua
vim.bo.filetype = 'lua'
vim.api.nvim_buf_set_lines(0, 0, -1, false, { '' })

local bufname = 'buf2'
local buf = vim.api.nvim_create_buf(false, true)
vim.api.nvim_buf_set_name(buf, bufname)
vim.bo[buf].filetype = vim.bo.filetype
vim.bo[buf].bufhidden = 'wipe'
vim.cmd('vertical diffsplit '..bufname)

vim.defer_fn(function()
  vim.api.nvim_set_current_win(1002)
  vim.cmd.quit()
end, 10)
```

`nvim -u issue.lua`

### Expected behavior

No error

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1186

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

macOS 14.6.1

### Terminal name/version

ghostty

### $TERM environment variable

xterm-ghostty

### Installation

Source

### LINKED ISSUE #32349: `ml_get` error if there is `:redrawstatus` inside `on_detach` and tabline accesses buffer-local option of scratch buffer
### Problem

Executing `:redrawstatus` inside `on_detach` can lead to `E315: ml_get: Invalid lnum: 1` error in some cases. This, for example, affects doing 'redrawstatus' inside `DiagnosticChanged` callback, as it can be triggered inside [`on_detach` from LSP](https://github.com/neovim/neovim/blob/878b3b89c316138d99f9dbc47c84f2f94591df03/runtime/lua/vim/lsp.lua#L911).

#28084 is possibly related (cc @seandewar), but it shows error while unloading is performed inside `on_detach`. The currently described issue results in an error with `on_detach` only accessing data and not doing any action.

### Steps to reproduce

1. Create the following 'init.lua':
    ```lua
    -- Make `on_detach` redraw statusline
    _G.attach_redrawstatus = function()
      local buf_id = vim.api.nvim_get_current_buf()
      vim.api.nvim_buf_attach(buf_id, false, {
        on_detach = function()
          -- Using `vim.api.nvim__redraw({ buf = buf_id, statusline = true })`
          -- does not show the error in this particular repro, but in real world
          -- use case still shows several `E315: ml_get: Invalid lnum: 1` errors.
          --
          -- Using `vim.schedule(vim.cmd.redrawstatus)` fixes the issue completely.
          vim.cmd.redrawstatus()
        end,
      })
    end

    -- Set up tabline that accesses buffer-local option of scratch buffer
    local scratch_buf_id = vim.api.nvim_create_buf(false, true)

    _G.make_tabline_string = function()
      -- NOTE: actual option name doesn't seem to matter, i.e. can be 'buftype' or
      -- something else
      local _ = vim.bo[scratch_buf_id].buflisted
      return 'Hello'
    end

    vim.o.tabline = '%!v:lua.make_tabline_string()'
    vim.o.showtabline = 2
    ```
2. `nvim --clean -u init.lua`
3. `:lua attach_redrawstatus()`
4. `:bwipeout`. Should show the `E315: ml_get: Invalid lnum: 1` error.

### Expected behavior

Executing `:redrawstatus` inside `on_detach` does not lead to errors.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1698+gaa976f0d93

### Vim (not Nvim) behaves the same?

No, doesn't have this functionality

### Operating system/version

EndeavourOS Linux x86_64, 6.12.10-arch1-1

### Terminal name/version

Ghostty 1.1.0-arch

### $TERM environment variable

xterm-ghostty

### Installation

appimage

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Error thrown for invalid line number which may be accessed
          in an `on_detach` callback at which point line count is
          intentionally set to 0.
Solution: Move empty memline check to before line number check.

Fix #31251
Fix #32349

### CODE REVIEW

**Comment by luukvbaal** [comment]
Could be submitted as a Vim patch first but I don't think the problem can manifest there.

File: test/functional/lua/buffer_updates_spec.lua [hunk 1]
```diff
@@ -305,6 +305,19 @@ describe('lua buffer event callbacks: on_lines', function()
...
+  it('no invalid lnum error for closed memline in on_detach #31251', function()
+    exec_lua([[
+      vim.api.nvim_buf_set_lines(0, 0, -1, false, { '' })
+      local bufname = 'buf2'
+      local buf = vim.api.nvim_create_buf(false, true)
+      vim.api.nvim_buf_set_name(buf, bufname)
+      vim.bo[buf].bufhidden = 'wipe'
+      vim.cmd('vertical diffsplit '..bufname)
+      vim.api.nvim_buf_attach(0, false, { on_detach = function() vim.cmd("redraw") end})
+      vim.cmd.quit()
```
Comment (justinmk) [inline test/functional/lua/buffer_updates_spec.lua:317]: usually `n.expect_exit()` is needed when actively quitting the current test Nvim instance. should we do that here?

File: test/functional/lua/buffer_updates_spec.lua [hunk 2]
```diff
@@ -305,6 +305,19 @@ describe('lua buffer event callbacks: on_lines', function()
...
 
+  it('no invalid lnum error for closed memline in on_detach #31251', function()
+    exec_lua([[
+      vim.api.nvim_buf_set_lines(0, 0, -1, false, { '' })
+      local bufname = 'buf2'
+      local buf = vim.api.nvim_create_buf(false, true)
+      vim.api.nvim_buf_set_name(buf, bufname)
+      vim.bo[buf].bufhidden = 'wipe'
+      vim.cmd('vertical diffsplit '..bufname)
+      vim.api.nvim_buf_attach(0, false, { on_detach = function() vim.cmd("redraw") end})
```
Comment (justinmk) [inline test/functional/lua/buffer_updates_spec.lua:316]: to ensure the test is "alive" should we assert that `on_detach` was actually called, e.g.

```
      eq(false, n.fn.exists('did_redraw'))

      ...

      vim.api.nvim_buf_attach(0, false, { on_detach = function()
        vim.g.did_redraw = true
        vim.cmd("redraw")
      end})

      ...

      eq(true, n.fn.exists('did_redraw'))
```

**Review by justinmk — APPROVED** [review]

File: test/functional/lua/buffer_updates_spec.lua (hunk 1 above)
Comment (justinmk) [reply test/functional/lua/buffer_updates_spec.lua:317]: Oh. Then `vim.cmd.close()` would be clearer.

Comment (luukvbaal) [reply test/functional/lua/buffer_updates_spec.lua:317]: The Nvim instance isn't closed here, just one of two split windows.

File: test/functional/lua/buffer_updates_spec.lua (hunk 2 above)
Comment (luukvbaal) [reply test/functional/lua/buffer_updates_spec.lua:316]: Sure? I took the fact that the test fails on `master` as being sufficient.

File: test/functional/lua/buffer_updates_spec.lua (hunk 1 above)
Comment (justinmk) [reply test/functional/lua/buffer_updates_spec.lua:317]: Does `vim.cmd.close()` not have the required behavior?

Comment (luukvbaal) [reply test/functional/lua/buffer_updates_spec.lua:317]: Yes that also works, `:close` being the same as `:quit` except when closing the last window. But actually we are testing deleting the buffer, so I'll update it to `:bdelete`.
