### PR TITLE
fix(lsp): define LspInlayHint highlight group

### LINKED ISSUE #24068: Inlay hints colors are inconsistent
### Problem

Like the title described, the color of the inlay hints are inconsistent, depending on the color of the text before it

Reproducible with this source code
```c
#include <stdio.h>

int main() {
  printf("Hello World");
  printf( "Hello World"); // The color of `format` inlay hints is different from above
  return 0;
}
```

### Steps to reproduce using "nvim -u minimal_init.lua"

--- CHANGE THESE
local pattern = 'c'
local cmd = {'clangd'}
-- Add files/folders here that indicate the root of a project
local root_markers = {'.git', '.editorconfig'}
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'clangd',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})

### Expected behavior

Both format to have the same color/hlgroup.

This is also reproducible with jdtls v1.24.0, and possibly other servers as well

### Neovim version (nvim -v)

NVIM v0.10.0-dev-540+gca5de9306

### Language server name/version

clangd version 15.0.7

### Operating system/version

Arch Linux 

### Log file

_No response_

### PR DESCRIPTION
**Pull request by dchinmay2**
fixes #24068

### CODE REVIEW

File: src/nvim/highlight_group.c [hunk 1]
```diff
@@ -231,6 +231,7 @@ static const char *highlight_init_both[] = {
   "default link DiagnosticSignOk DiagnosticOk",
   "default DiagnosticDeprecated cterm=strikethrough gui=strikethrough guisp=Red",
   "default link DiagnosticUnnecessary Comment",
+  "default link LspInlayHint Special",
```
Comment (MunifTanjim) [inline src/nvim/highlight_group.c:234]: `Special` might be too colorful for inlay hint? Not sure about other colorschemes, but on `gruvbox` it's orange.

image

Comment (p00f) [reply src/nvim/highlight_group.c:234]: `NonText` is also too bright in the default colorscheme - just change it in your colorscheme imo, this PR is mostly a bugfix for #24068

Comment (justinmk) [inline src/nvim/highlight_group.c:234]:
```suggestion
  "default link LspInlayHint NonText",
```
