### PR TITLE
fix(lua): not using global value in vim.opt_global

### LINKED ISSUE #21506: vim.opt_global.foobar:get() fails to get current global option value
### Neovim version (nvim -v)

NVIM v0.9.0-dev-538+gf9c62ce34

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Endeavour OS 

### Terminal name/version

wezterm 20221119-145034-49b9839f, alacritty 0.11.0 (8dbaa0bb)

### $TERM environment variable

xterm-256color

### Installation

AUR, bob, rhysd/action-setup-vim

### How to reproduce the issue

nvim --clean
:setglobal signcolumn=yes
:lua= vim.opt_global.signcolumn:get()

### Expected behavior

Returns "yes".

### Actual behavior

Returns "auto", its default.

Both `:setglobal signcolumn?` and `:lua= vim.go.signcolumn` returns "yes", and the bug doesn't happen on v0.8.1.

It only happens with "local to window" option like "wrap", not with "global or local to window" option like "scrolloff".

### PR DESCRIPTION
**Pull request by phelipetls**
Closes #21506

### CODE REVIEW

File: runtime/lua/vim/_options.lua [hunk 1]
```diff
@@ -727,7 +727,13 @@ local function create_option_accessor(scope)
...
   return setmetatable({}, {
     __index = function(_, k)
-      return make_option(k, api.nvim_get_option_value(k, {}))
+      if scope == 'global' then
+        local global_value = api.nvim_get_option_value(k, { scope = 'global' })
+        return make_option(k, global_value)
+      else
+        local global_local_value = api.nvim_get_option_value(k, {})
+        return make_option(k, global_local_value)
+      end
```
Comment (omar25h) [inline runtime/lua/vim/_options.lua:736]: Since the only difference between the if and else is the options, the logic could be simplified
```suggestion
      local opts = {}
      if scope == 'global' then
        opts = { scope = 'global' }
      end
      
      return make_option(k, api.nvim_get_option_value(k, opts))
```

Comment (phelipetls) [reply runtime/lua/vim/_options.lua]: Done. Thanks!

File: runtime/lua/vim/_options.lua [hunk 2]
```diff
@@ -727,7 +727,12 @@ local function create_option_accessor(scope)
 
   return setmetatable({}, {
     __index = function(_, k)
-      return make_option(k, api.nvim_get_option_value(k, {}))
+      local opts = {}
+      if scope == 'global' then
+        opts = { scope = 'global' }
+      end
+
+      return make_option(k, api.nvim_get_option_value(k, opts))
```
Comment (zeertzjq) [inline runtime/lua/vim/_options.lua:735]:
```suggestion
      -- vim.opt_global must get global value only
      -- vim.opt_local may fallback to global value like vim.opt
      local opts = { scope = scope == 'global' and 'global' or nil }
      return make_option(k, api.nvim_get_option_value(k, opts))
```
