### PR TITLE
fix(eval): user function should start with * in exists

### LINKED ISSUE #24587: Could `f_exists` be modified to also check for the existence of Lua functions?
### Problem

The `exists()` function [f_exists](https://github.com/neovim/neovim/blob/ef44e597294e4d0d9128ef69b6aa7481a54e17cb/src/nvim/eval/funcs.c#L1654) cannot currently report on whether a Lua function exists.

Under the assumption that both `coc#status` and `v:lua.myLuaFunc` exist:

> **Note**
> `exists('*coc#status')` == 1

> **Warning**
> `exists('*v:lua.myLuaFunc')` --> E15: Invalid expression: v:lua

Ref: https://github.com/itchyny/lightline.vim/issues/657#issuecomment-1666663760

### Expected behavior

> **Note**
> `exists('*v:lua.myLuaFunc')` == 1
>  :white_check_mark:

### PR DESCRIPTION
**Pull request by glepnir**
Problem: as `exists` doc said the user defined function or built-in funcstion should start with `*`

Solution: add `*` check .

Fix #24587

### CODE REVIEW

File: src/nvim/eval/funcs.c [hunk 1]
```diff
@@ -1726,7 +1726,7 @@ static void f_exists(typval_T *argvars, typval_T *rettv, EvalFuncData fptr)
       n = false;  // Trailing garbage.
     }
   } else if (*p == '*') {  // Internal or user defined function.
-    n = function_exists(p + 1, false);
+    n = (strncmp(p, "*v:lua.", 7) == 0) ? nlua_func_exists(p + 7) : function_exists(p + 1, false);
```
Comment (zeertzjq) [inline src/nvim/eval/funcs.c:1729]:
```suggestion
    n = strncmp(p, "*v:lua.", 7) == 0 ? nlua_func_exists(p + 7) : function_exists(p + 1, false);
```

**Review by zeertzjq — APPROVED** [review]
