### PR TITLE
fix(ui): change cursor when behind floating window

### LINKED ISSUE #35923: Cannot determine if cursor belongs to the topmost window
### Problem

If the new float, not entered window covers the current one, the user have to check or remember, which window is the current one. The cursor appears to belong to the new window (see the repro).

Image

The original discussion: https://github.com/neovim/neovim/discussions/33863

### Steps to reproduce

```lua
local api = vim.api
api.nvim_buf_set_lines(api.nvim_get_current_buf(), 0, 1, true, {'first', 'second'})
api.nvim_win_set_cursor(0, {2, 5})

local buf = api.nvim_create_buf(false, true)
api.nvim_buf_set_lines(buf, 0, 0, true, {'the only line'})
api.nvim_open_win(buf, false, {relative = 'editor', row = 0, col = 0, height = 2, width = 20})
```

### Expected behavior

Even if the statusline (for laststatus >= 2) can give useful suggestion, the cursor should look different depending on whether it is in the top or underneath (including the option of hiding it completely when covered).

I have no knowledge if it can be done by defining different highlights. 

### Nvim version (nvim -v)

v0.12.0-dev-1305+ga0c60e819d

### Vim (not Nvim) behaves the same?

n/a if I'm correct

### Operating system/version

Debian Sid

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

from repo

### PR DESCRIPTION
**Pull request by glepnir**
Problem:
cursor is hard to see when it's behind a floating window

Solution:
use underline cursor to indicate the cursor is covered by floats

Fix #35923

### CODE REVIEW

**Comment by przepompownia** [comment]
This seems like a good compromise because the Replace mode looks as before.

File: src/nvim/winfloat.c [hunk 1]
```diff
@@ -471,3 +471,31 @@ win_T *win_float_create_preview(bool enter, bool new_buf)
   }
   return wp;
 }
+
+bool win_behind_float(win_T *wp)
+{
+  if (!wp) {
+    return false;
+  }
```
Comment (seandewar) [inline src/nvim/winfloat.c]:
```suggestion
bool win_behind_float(win_T *wp)
  FUNC_ATTR_NONNULL_ALL FUNC_ATTR_WARN_UNUSED_RESULT
{
```

I suppose it's fine, but `wp` is already not NULL in the only place it's called.

**Review by seandewar — COMMENTED** [review]
This isn't considering the stacking order of floats:

```vim
call nvim_open_win(0, 0, #{relative: 'editor', width: 10, height: 10, row: 0, col: 0})
call nvim_open_win(0, 1, #{relative: 'editor', width: 10, height: 10, row: 3, col: 3})
```

```vim
call nvim_open_win(0, 1, #{relative: 'editor', width: 10, height: 10, row: 3, col: 3, zindex: 10})
call nvim_open_win(0, 0, #{relative: 'editor', width: 10, height: 10, row: 0, col: 0, zindex: 9})
```

I'd imagine the cursor shouldn't be changed in both of these cases?

(Also, I wonder if a function like `win_behind_float` exists already? I recall `ui_compositor.c` having stuff like this, but I'm not sure...)

**Comment by glepnir** [comment]
I've made a small update. It should be working now. I remember there are some functions for comparing floating z-indexes in `ui_compositor`. I'll check it again tomorrow and update the tests.

**Comment by glepnir** [comment]
tried reusing compositor code but it doesn't work in multigrid mode - compositor isn't active there.  so change to the  cursor_behind_float since it works in both modes.

```C
if (was_busy) {
        ui_call_busy_stop();
        was_busy = false;
      }
      int crow = curwin->w_winrow + curwin->w_wrow;
      int ccol = curwin->w_wincol + curwin->w_wcol;
      ScreenGrid *top_grid = ui_comp_get_grid_at_coord(crow, ccol);
      win_T *wp = (top_grid && top_grid != &curwin->w_grid_alloc && top_grid != &default_grid)
                  ? get_win_by_grid_handle(top_grid->handle) : NULL;
      bool cursor_obscured = wp && wp->w_floating && !wp->w_config.hide;
      int new_idx = cursor_obscured ? SHAPE_IDX_R : cursor_get_mode_idx();
      if (ui_mode_idx != new_idx) {
        ui_mode_idx = new_idx;
        pending_mode_update = true;
      }
    }
```

**Comment by glepnir** [comment]
reconsidered it... should only work in compositor mode. use ui_comp_get_grid_at_coord() to detect if cursor is behind a float should enough. skips entirely in multigrid mode.

File: src/nvim/ui.c [hunk 2]
```diff
@@ -543,10 +538,32 @@ void ui_flush(void)
...
+
+      int crow = curwin->w_winrow + curwin->w_wrow;
+      int ccol = curwin->w_wincol + curwin->w_wcol;
+      ScreenGrid *top_grid = ui_comp_get_grid_at_coord(crow, ccol);
+      win_T *wp = (top_grid && top_grid != &curwin->w_grid_alloc && top_grid != &default_grid)
+                  ? get_win_by_grid_handle(top_grid->handle) : NULL;
+
+      int cur_z = curwin->w_floating ? curwin->w_config.zindex : 0;
+      bool cursor_obscured = wp && wp->w_floating && !wp->w_config.hide
+                             && wp->w_config.zindex > cur_z;
```
Comment (seandewar) [inline src/nvim/ui.c]: Hmm, I'm not totally sure (and I don't have a repro for this), but until `ui_ext_win_position` is called (via `win_ui_flush`), maybe it's possible for a hidden float's grid to still be in `layers`? If that happens, the cursor may be considered unobscured despite being behind another non-hidden float that's behind the hidden float.

Might want to move cursor visibility handling until after the `win_ui_flush`es below this stuff?
That should also mean the check for `w_config.hide` can be removed.

File: src/nvim/ui.c [hunk 3]
```diff
@@ -543,10 +538,32 @@ void ui_flush(void)
...
+        was_busy = true;
+      }
+    } else {
+      if (was_busy) {
+        ui_call_busy_stop();
+        was_busy = false;
+      }
+
+      int crow = curwin->w_winrow + curwin->w_wrow;
+      int ccol = curwin->w_wincol + curwin->w_wcol;
```
Comment (seandewar) [inline src/nvim/ui.c]:
```suggestion
      int crow = curwin->w_winrow + curwin->w_winrow_off + curwin->w_wrow;
      int ccol = curwin->w_wincol + curwin->w_wincol_off
                 + (curwin->w_p_rl ? curwin->w_view_width - curwin->w_wcol - 1
                                   : curwin->w_wcol);
```

Maybe there's a better way, but this needs to at least consider `w_win{row,col}_off`, otherwise borders aren't accounted for. Plus `'rightleft'`. Add these tests:

```lua
vim.api.nvim_open_win(0, true, {relative = "editor", width = 5, height = 5, row = 8, col = 9, border = "single", zindex = 1})
vim.api.nvim_open_win(0, false, {relative = "editor", width = 10, height = 10, row = 0, col = 0, zindex = 2})
-- Cursor should be unobscured here.

vim.api.nvim_win_set_config(0, {relative = "editor", row = 9, col = 8})
-- Cursor should also be unobscured here.

vim.api.nvim_win_set_config(0, {relative = "editor", row = 8, col = 8})
vim.o.rightleft = true
-- Cursor should also be unobscured here.

vim.o.virtualedit = "all"
vim.fn.setpos(".", {0, 1, 1, 4})
-- Cursor should be *obscured* here.
```

**Review by seandewar — COMMENTED** [review]
Apart from these comments, I think this looks good, though it maybe needs a review from a UI/grid expert. 😇

File: src/nvim/ui.c (hunk 3 above)
Comment (glepnir) [reply src/nvim/ui.c]: cool updated.

File: src/nvim/ui.c [hunk 4]
```diff
@@ -571,6 +566,27 @@ void ui_flush(void)
...
     win_ui_flush(false);
   }
+
+  if (ui_comp_should_draw() && !(State & MODE_CMDLINE)) {
+    int crow = curwin->w_winrow + curwin->w_winrow_off + curwin->w_wrow;
+    int ccol = curwin->w_wincol + curwin->w_wincol_off +
+               (curwin->w_p_rl ? curwin->w_view_width - curwin->w_wcol - 1 : curwin->w_wcol);
+    if (curwin->w_cursor.coladd > 0) {
+      ccol += curwin->w_cursor.coladd;
+    }
```
Comment (seandewar) [inline src/nvim/ui.c]:
```suggestion
```

Why was this added? This fails [my prior example](https://github.com/neovim/neovim/pull/37624#discussion_r2758457545) and should have failed CI if it's including it.

File: src/nvim/ui.c [hunk 5]
```diff
@@ -571,6 +566,27 @@ void ui_flush(void)
     // by nvim core, not the compositor)
     win_ui_flush(false);
   }
+
+  if (ui_comp_should_draw() && !(State & MODE_CMDLINE)) {
```
Comment (justinmk) [inline src/nvim/ui.c]:
```suggestion
  // Show "empty box" cursor if behind a floatwin.
  if (ui_comp_should_draw() && !(State & MODE_CMDLINE)) {
```

File: src/nvim/ui.c [hunk 6]
```diff
@@ -571,6 +566,27 @@ void ui_flush(void)
...
+    win_T *wp = (top_grid && top_grid != &curwin->w_grid_alloc
+                 && top_grid != &default_grid) ? get_win_by_grid_handle(top_grid->handle) : NULL;
+    int cur_z = curwin->w_floating ? curwin->w_config.zindex : 0;
+    bool cursor_obscured = wp && wp->w_floating && wp->w_config.zindex > cur_z;
+
+    int new_idx = cursor_obscured ? SHAPE_IDX_R : cursor_get_mode_idx();
+    if (ui_mode_idx != new_idx) {
+      ui_mode_idx = new_idx;
+      pending_mode_update = true;
+    }
```
Comment (justinmk) [inline src/nvim/ui.c]: should this logic live in a new function like `ui_cursor_is_behind_floatwin`, just below `ui_cursor_shape`

File: src/nvim/ui.c (hunk 5 above)
Comment (justinmk) [inline src/nvim/ui.c]: why does it check !MODE_CMDLINE ? is that because `curwin` cursor may be behind a floatwin, while the cmdline cursor is not?

File: test/functional/ui/float_spec.lua [hunk 7]
```diff
@@ -11251,6 +11251,79 @@ describe('float window', function()
...
+
+    it('cursor shape when the cursor is covered by a floating window', function()
+      local normal_win = api.nvim_get_current_win()
+      api.nvim_buf_set_lines(0, 0, -1, true, { 'one', 'two' })
+      api.nvim_win_set_cursor(0, { 2, 2 })
+      local buf = api.nvim_create_buf(false, false)
+      api.nvim_buf_set_lines(buf, 0, 0, true, { 'the only line' })
+      local win = api.nvim_open_win(buf, false, { relative = 'editor', row = 0, col = 0, height = 2, width = 20 })
+      if not multigrid then
+        screen:expect { mode = 'replace' }
```
Comment (justinmk) [inline test/functional/ui/float_spec.lua]: seems like there are no asserts for `multigrid=true`, so perhaps just skip (early return) the test if `multigrid` is true? or alternatively, assert what we expect for multigrid case.

File: src/nvim/ui.c (hunk 5 above)
Comment (seandewar) [reply src/nvim/ui.c]: Yup, cursor's drawn in the command-line at that point, not inside `curwin`.

There's a similar check above for unhiding the cursor if `curwin` is hidden but we're in the command-line. (this used to live there before I suggested moving it after `win_ui_flush`)

File: test/functional/ui/float_spec.lua (hunk 7 above)
Comment (seandewar) [reply test/functional/ui/float_spec.lua]: I think multigrid tests for this would be a good idea.

File: test/functional/ui/float_spec.lua [hunk 8]
```diff
@@ -11251,6 +11251,79 @@ describe('float window', function()
...
     end)
+
+    it('cursor shape when the cursor is covered by a floating window', function()
+      local normal_win = api.nvim_get_current_win()
+      api.nvim_buf_set_lines(0, 0, -1, true, { 'one', 'two' })
+      api.nvim_win_set_cursor(0, { 2, 2 })
+      local buf = api.nvim_create_buf(false, false)
+      api.nvim_buf_set_lines(buf, 0, 0, true, { 'the only line' })
+      local win = api.nvim_open_win(buf, false, { relative = 'editor', row = 0, col = 0, height = 2, width = 20 })
+      if not multigrid then
```
Comment (zhangweize9-cyber) [inline test/functional/ui/float_spec.lua]: I think we should add an extra layer of type checking to determine if the variable is a boolean value.
```suggestion
      if type(multigrid) == "boolean" and not multigrid then
```

**Review by zhangweize9-cyber — COMMENTED** [review]
It's clear the developer put a lot of effort into implementing this feature; I suggest adding type checks to the variables to improve stability.

File: src/nvim/ui.c (hunk 4 above)
Comment (glepnir) [reply src/nvim/ui.c]: oh right `w_wcol` already includes the virtual edit offset

File: test/functional/ui/float_spec.lua [hunk 9]
```diff
@@ -11251,6 +11251,346 @@ describe('float window', function()
       eq('Vim(set):E474: Invalid argument: winborder=+,-,+,|,+,-,+,', pcall_err(command, [[set winborder=+,-,+,\|,+,-,+,]]))
       eq('Vim(set):E474: Invalid argument: winborder=custom', pcall_err(command, 'set winborder=custom'))
     end)
+
+    it('cursor shape when the cursor is covered by a floating window #test', function()
```
Comment (seandewar) [inline test/functional/ui/float_spec.lua]:
```suggestion
    it('cursor shape when the cursor is covered by a floating window', function()
```

File: src/nvim/ui.c (hunk 4 above)
Comment (seandewar) [reply src/nvim/ui.c]: Your tests still pass when re-adding the incorrect code. It should be failing in that case like my example.

Comment (glepnir) [reply src/nvim/ui.c]: emm when ui_flush() is called, curwin->w_cursor.coladd is already 0 🤔

Comment (seandewar) [reply src/nvim/ui.c]: That's because the cursor is not past the end of the line in your test. It needs to be in a virtual column for `coladd` to be used. :grin: 

I'd recommend faithfully porting over my examples into the test; the positions/sizes I used were deliberate. (Importantly the cursor was in the one cell overlapped by the other float while `'rightleft'` was still set)

Comment (glepnir) [reply src/nvim/ui.c]: Resolved now the case will failed when use before code. after remove  it will pass.

Comment (seandewar) [reply src/nvim/ui.c]: Thanks, looks correct now. :+1:

File: test/functional/ui/float_spec.lua [hunk 10]
```diff
@@ -11251,6 +11251,352 @@ describe('float window', function()
...
+          },
+          float_pos = {
+            [4] = { 1001, 'NW', 1, 0, 0, true, 50, 1, 0, 0 },
+            [5] = { 1002, 'NW', 1, 0, 0, true, 150, 2, 0, 0 },
+            [6] = { 1003, 'NW', 1, 0, 0, true, 160, 3, 0, 0 },
+          },
+          mode = 'normal',
+        })
+      else
+        screen:expect { mode = 'normal' }
```
Comment (seandewar) [inline test/functional/ui/float_spec.lua]: Because the full screen state isn't being asserted, this passes immediately with the old (incorrect) state before the redraw happens (because the expected cursor `mode` is the same as the previous `expect`). You can observe this with `screen:redraw_debug()`.

Might be a good idea to instead assert the new screen state in these cases:

```
warning: Screen test succeeded immediately. Try to avoid this unless the
purpose of the test really requires it.
If necessary, silence this warning with 'unchanged' argument of screen:expect.
stack traceback:
        test/functional/ui/screen.lua:912: in function '_wait'
        test/functional/ui/screen.lua:537: in function 'expect'
        test/functional/ui/float_spec.lua:11429: in function <test/functional/ui/float_spec.lua:11255>


warning: Screen test succeeded immediately. Try to avoid this unless the
purpose of the test really requires it.
If necessary, silence this warning with 'unchanged' argument of screen:expect.
stack traceback:
        test/functional/ui/screen.lua:912: in function '_wait'
        test/functional/ui/screen.lua:537: in function 'expect'
        test/functional/ui/float_spec.lua:11486: in function <test/functional/ui/float_spec.lua:11255>


warning: Screen test succeeded immediately. Try to avoid this unless the
purpose of the test really requires it.
If necessary, silence this warning with 'unchanged' argument of screen:expect.
stack traceback:
        test/functional/ui/screen.lua:912: in function '_wait'
        test/functional/ui/screen.lua:537: in function 'expect'
        test/functional/ui/float_spec.lua:11522: in function <test/functional/ui/float_spec.lua:11255>


warning: Screen test succeeded immediately. Try to avoid this unless the
purpose of the test really requires it.
There are intermediate states between the two identical expects.
Use screen:snapshot_util() or screen:redraw_debug() to find them, and add them
to the test if they make sense.

stack traceback:
        test/functional/ui/screen.lua:912: in function '_wait'
        test/functional/ui/screen.lua:537: in function 'expect'
        test/functional/ui/float_spec.lua:11560: in function <test/functional/ui/float_spec.lua:11255>
```

File: test/functional/ui/float_spec.lua [hunk 11]
```diff
@@ -11251,6 +11251,352 @@ describe('float window', function()
...
+            [2] = { height = 19, startcol = 0, startrow = 0, width = 50, win = 1000 },
+          },
+          float_pos = {
+            [7] = { 1004, 'NW', 1, 8, 9, true, 1, 1, 8, 9 },
+            [8] = { 1005, 'NW', 1, 0, 0, true, 2, 2, 0, 0 },
+          },
+          mode = 'normal',
+        })
+      else
+        screen:expect { mode = 'normal' }
```
Comment (seandewar) [inline test/functional/ui/float_spec.lua]: ditto

File: test/functional/ui/float_spec.lua [hunk 12]
```diff
@@ -11251,6 +11251,352 @@ describe('float window', function()
...
+            [2] = { height = 19, startcol = 0, startrow = 0, width = 50, win = 1000 },
+          },
+          float_pos = {
+            [7] = { 1004, 'NW', 1, 9, 8, true, 1, 1, 9, 8 },
+            [8] = { 1005, 'NW', 1, 0, 0, true, 2, 2, 0, 0 },
+          },
+          mode = 'normal',
+        })
+      else
+        screen:expect { mode = 'normal' }
```
Comment (seandewar) [inline test/functional/ui/float_spec.lua]: ditto

File: test/functional/ui/float_spec.lua [hunk 13]
```diff
@@ -11251,6 +11251,352 @@ describe('float window', function()
...
+            [2] = { height = 19, startcol = 0, startrow = 0, width = 50, win = 1000 },
+          },
+          float_pos = {
+            [7] = { 1004, 'NW', 1, 8, 8, true, 1, 1, 8, 8 },
+            [8] = { 1005, 'NW', 1, 0, 0, true, 2, 2, 0, 0 },
+          },
+          mode = 'normal',
+        })
+      else
+        screen:expect { mode = 'normal' }
```
Comment (seandewar) [inline test/functional/ui/float_spec.lua]: ditto

File: test/functional/ui/float_spec.lua (hunk 10 above)
Comment (glepnir) [reply test/functional/ui/float_spec.lua]: Yes, I took a shortcut here. Because this file is too long, I thought this would avoid increasing its length. I might try splitting the `float_spec` later.

Comment (seandewar) [reply test/functional/ui/float_spec.lua]: That's understandable. If you'd like, I suppose you could omit the `grid` from the `expect`s where the expected `mode` differs from the previous `expect` to save a few lines. :+1:

**Comment by seandewar** [comment]
I don't have any more comments, so I think this is fine. :+1:
As before, could use a review from someone who knows more about grid stuff. (I'm a grid newbie)

E.g: as you said earlier this is skipped for multigrid (via `ui_comp_should_draw`); I suppose that's because UIs may draw grids in any position they'd like?

**Comment by zhangweize9-cyber** [comment]
The principle behind drawing a grid in the terminal is actually the use of a bunch of escape sequences. Neovim simply encapsulates these escape sequences, so developers using the Lua programming language only need to call the pre-written functions.

File: test/functional/ui/float_spec.lua (hunk 10 above)
Comment (glepnir) [reply test/functional/ui/float_spec.lua]: great nice tips

**Comment by glepnir** [comment]
Thanks so much for the thorough review 👍    in multigrid mode the UI client positions grids independently, so floats don't truly obscure content the same way they do in TUI mode 🤔

File: test/functional/ui/float_spec.lua [hunk 14]
```diff
@@ -11251,6 +11251,417 @@ describe('float window', function()
       eq('Vim(set):E474: Invalid argument: winborder=+,-,+,|,+,-,+,', pcall_err(command, [[set winborder=+,-,+,\|,+,-,+,]]))
       eq('Vim(set):E474: Invalid argument: winborder=custom', pcall_err(command, 'set winborder=custom'))
     end)
+
+    it('cursor shape when the cursor is covered by a floating window #test', function()
```
Comment (seandewar) [inline test/functional/ui/float_spec.lua]:
```suggestion
    it('cursor shape when the cursor is covered by a floating window', function()
```

**Review by seandewar — APPROVED** [review]
Sounds good!

File: test/functional/ui/float_spec.lua (hunk 14 above)
Comment (glepnir) [reply test/functional/ui/float_spec.lua]: 😢 TEST_FILTER should support multiple words 💢

File: src/nvim/ui.c [hunk 15]
```diff
@@ -674,6 +680,26 @@ void ui_cursor_shape(void)
...
+  int crow = curwin->w_winrow + curwin->w_winrow_off + curwin->w_wrow;
+  int ccol = curwin->w_wincol + curwin->w_wincol_off
+             + (curwin->w_p_rl ? curwin->w_view_width - curwin->w_wcol - 1 : curwin->w_wcol);
+
+  ScreenGrid *top_grid = ui_comp_get_grid_at_coord(crow, ccol);
+  win_T *wp = (top_grid && top_grid != &curwin->w_grid_alloc && top_grid != &default_grid)
+              ? get_win_by_grid_handle(top_grid->handle) : NULL;
+
+  int cur_z = curwin->w_floating ? curwin->w_config.zindex : 0;
+  return wp && wp->w_floating && wp->w_config.zindex > cur_z;
```
Comment (seandewar) [inline src/nvim/ui.c]:
```suggestion
  return wp && curwin != wp;
```

No idea if this suggestion is correct, but as they're layered by zindex already (with `curwin` always being above if zindices are equal), maybe this'll work?

Comment (glepnir) [reply src/nvim/ui.c]: Correct. The layer has already been layered. This behavior was extracted from the previous window traversal process, no need when we use grid layer.

**Comment by przepompownia** [comment]
One related thing, probably to implement in a separate PR.

Sometimes we have created non-focusable decorational windows on top of the current non-float window and rather don't want to obscure the cursor (apparently by a new win_config option). 

image

**Comment by glepnir** [comment]
It seems there's more blank space on the left. Wouldn't it be better to utilize the space on the left instead of overlapping the main window 🤔? A better effect here would be something like moving to the left and becoming bold, and then reverting to the original state when  moves away?

File: src/nvim/ui.c (hunk 15 above)
Comment (seandewar) [reply src/nvim/ui.c]: Nice! Also looks like the `top_grid != &curwin->w_grid_alloc` check can be removed too. (Handled by `curwin != wp`)

Comment (glepnir) [reply src/nvim/ui.c]: ye if `top_grid` is neither the current window's grid nor the default grid, then it means the cursor is being obscured by another window.

Comment (seandewar) [reply src/nvim/ui.c]: Nice. Your change looks even better! :rocket:

Comment (seandewar) [reply src/nvim/ui.c]: Ah, you can also skip the `NULL` check on `top_grid` too. `ui_comp_get_grid_at_coord` never returns a `NULL` grid.

I think that's everything now. :grin:

Comment (glepnir) [reply src/nvim/ui.c]: protective behavior has become a habit when see a pointer 😊

Comment (seandewar) [reply src/nvim/ui.c]: Hah, would be nice if more functions had `FUNC_ATTR_NONNULL_RET` I suppose.

**Comment by justinmk** [comment]
Will add a news.txt item for this.

**Comment by przepompownia** [comment]
Thank you all for working on this change!
