### PR TITLE
fix(float): make `screen*()` functions respect floating windows

### LINKED ISSUE #19013: `screen*()` functions don't register floating windows
### Neovim version (nvim -v)

NVIM v0.8.0-dev+441-ge651ae586

### Vim (not Nvim) behaves the same?

Yes, with popup windows (8.2.5046)

### Operating system/version

EndeavourOS 5.18.3-arch1-1

### Terminal name/version

xfce4-terminal 1.0.4 (Xfce 4.16)

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

1. Create 'init-floating.lua' file with following content:
```lua
local buf_id = vim.api.nvim_create_buf(true, true)
vim.api.nvim_buf_set_lines(buf_id, 0, -1, true, { 'aaaaaaaaaa' })

vim.api.nvim_open_win(buf_id, false, {
  relative = 'editor',
  width = 10,
  height = 1,
  row = 0,
  col = 0,
})
```
2. `nvim -u init-floating.lua`. Should result in Neovim instance with `aaaaaaaaaa` in floating window in top left corner.
3. Run `:lua print(vim.inspect(vim.fn.screenstring(1, 1)))`. It should be `"a"`, but it is `" "`, which is a character under floating window. The same effect is for `screenchar()`, `screenchars()`, and `screenattr()`.

On the other hand, Vim behaves as expected with its popup windows. Use equivalent 'init-popup.vim' file:
```vimscript
call popup_create("aaaaaaaaaa", {"line": 1, "col": 1})
```

### Expected behavior

All `screen*()` functions respect floating windows, i.e. use them during computation of "what is displayed on the screen".

### Actual behavior

https://user-images.githubusercontent.com/24854248/174443738-e6bf6169-23f7-45fe-ba13-5dd4c91d08be.mp4

### PR DESCRIPTION
**Pull request by echasnovski**
This is an attempt to fix #19013. I hope it fixes the problem of ignoring floating windows while not breaking other tests. Tested this fix on custom `get_screenshot()` (basically calling `screenstring()` and `screenattr()` on all cells from `1..vim.o.lines x 1.vim.o.columns`) with several overlapping floating windows. Seems to work.

Disclaimer: I don't know much about Neovim C codebase (and C in general). I mostly copied and modified `ui_comp_mouse_focus()` which seems to properly handle floating windows for mouse functionality. This might be suboptimal, but works for cases I tested.

### CODE REVIEW

**Comment by echasnovski** [comment]
Pushed commit that addresses `oldtest`. Didn't realize that `make test` doesn't test for "old tests".

File: src/nvim/eval.c [hunk 1]
```diff
@@ -6860,8 +6860,10 @@ void screenchar_adjust_grid(ScreenGrid **grid, int *row, int *col)
       && *row < (msg_grid.rows + msg_grid.comp_row)
       && *col < msg_grid.cols) {
     *grid = &msg_grid;
-    *row -= msg_grid.comp_row;
```
Comment (bfredl) [inline src/nvim/eval.c:6863]: I think we can remove this special case at this point. ui_comp_get_grid_at_coord() should also handle msg grid

Comment (echasnovski) [reply src/nvim/eval.c:6863]: Do you mean whole `if...` resulting in `*grid = &msg_grid;`?

Comment (echasnovski) [reply src/nvim/eval.c]: Done. But `msg_scroll_flush()`  is still needed (`oldtest` breaks without it). Also renamed helper function to `screenchar_adjust_coords()` which seems to be better suited.

File: src/nvim/eval/funcs.c [hunk 2]
```diff
@@ -8037,12 +8038,14 @@ static void f_screenattr(typval_T *argvars, typval_T *rettv, FunPtr fptr)
 
   int row = (int)tv_get_number_chk(&argvars[0], NULL) - 1;
   int col = (int)tv_get_number_chk(&argvars[1], NULL) - 1;
-  if (row < 0 || row >= default_grid.rows
-      || col < 0 || col >= default_grid.cols) {
+
+  ScreenGrid *grid = ui_comp_get_grid_at_coord(row, col);
+  screenchar_adjust_coords(&grid, &row, &col);
```
Comment (bfredl) [inline src/nvim/eval/funcs.c:8043]: I'd suggest move the call to ui_comp_get_grid_at_coord inside `screenchar_adjust_coords`.

Comment (echasnovski) [reply src/nvim/eval/funcs.c]: Done.

File: src/nvim/eval.c [hunk 3]
```diff
@@ -6849,19 +6850,19 @@ void return_register(int regname, typval_T *rettv)
...
-  if (msg_grid.chars && msg_grid.comp_index > 0 && *row >= msg_grid.comp_row
-      && *row < (msg_grid.rows + msg_grid.comp_row)
-      && *col < msg_grid.cols) {
-    *grid = &msg_grid;
-    *row -= msg_grid.comp_row;
-  }
+
+  *grid = ui_comp_get_grid_at_coord(*row, *col);
+
+  // Make `row` and `col` be "grid relative" coordinates
```
Comment (bfredl) [inline src/nvim/eval.c:6863]: no need for "citation marks", they are just grid relative coordinates.

Comment (echasnovski) [reply src/nvim/eval.c]: Done.

File: test/functional/vimscript/screenchar_spec.lua [hunk 4]
```diff
@@ -0,0 +1,77 @@
+local helpers = require('test.functional.helpers')(after_each)
+local clear, eq, meths = helpers.clear, helpers.eq, helpers.meths
+local command, funcs = helpers.command, helpers.funcs
+
+local global_helpers = require('test.helpers')
```
Comment (justinmk) [inline test/functional/vimscript/screenchar_spec.lua:5]: can delete this; test.helpers is merged-into test.functional.helpers

File: src/nvim/eval/funcs.c [hunk 5]
```diff
@@ -8053,14 +8055,16 @@ static void f_screenchar(typval_T *argvars, typval_T *rettv, FunPtr fptr)
...
+  ScreenGrid *grid;
   int row = tv_get_number_chk(&argvars[0], NULL) - 1;
   int col = tv_get_number_chk(&argvars[1], NULL) - 1;
-  if (row < 0 || row >= default_grid.rows
-      || col < 0 || col >= default_grid.cols) {
+
+  screenchar_adjust(&grid, &row, &col);
+
+  if (row < 0 || row >= grid->rows
+      || col < 0 || col >= grid->cols) {
```
Comment (justinmk) [inline src/nvim/eval/funcs.c:8065]: nit: can be on 1 line (same for the other case)

File: test/functional/vimscript/screenchar_spec.lua (hunk 4 above)
Comment (echasnovski) [reply test/functional/vimscript/screenchar_spec.lua]: Done.

File: src/nvim/eval/funcs.c (hunk 5 above)
Comment (echasnovski) [reply src/nvim/eval/funcs.c]: Done.

File: test/functional/vimscript/screenchar_spec.lua [hunk 6]
```diff
@@ -0,0 +1,75 @@
...
+end)
+
+describe('screenstring()', function()
+  it('respects floating windows', function()
+    eq('a', funcs.screenstring(1, 1))
+    eq('a', funcs.screenstring(1, 2))
+    eq('b', funcs.screenstring(1, 3))
+    eq('c', funcs.screenstring(1, 4))
+  end)
+end)
```
Comment (bfredl) [inline test/functional/vimscript/screenchar_spec.lua:75]: this can all be a single `describe()` block.

Comment (echasnovski) [reply test/functional/vimscript/screenchar_spec.lua:75]: In all test files from 'test/functional/vimscript' that I've checked, one `describe()` block represents one exported function (even if they are related).
But sure, I'll merge them.

Comment (echasnovski) [reply test/functional/vimscript/screenchar_spec.lua]: Done.

**Comment by echasnovski** [comment]
Just to be sure, is there anything else I can/should do to get this merged?

**Comment by bfredl** [comment]
@echasnovski looks alright, squash?

**Comment by echasnovski** [comment]
> @echasnovski looks alright, squash?

Done.
