### PR TITLE
fix(extui): copy window config to new tabpage

### LINKED ISSUE #34300: vim._extui box not closed if in different tab
### Problem

vim._extui box not closed if in a different tab

### Steps to reproduce

nvim --clean +"lua require('vim._extui').enable{msg={pos='box',box={timeout=2000}}}" 
:echo "foo"|echo "bar"|echo "baz"|sleep 1|tab split|lua vim.defer_fn(vim.cmd.tabclose,1500)

### Expected behavior

vim._extui box window be closed.

### Nvim version (nvim -v)

v0.12.0-dev-ee84518

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux archlinux 6.14.9-arch1-1

### Terminal name/version

kitty 0.42.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  When opening a new tabpage, extui windows are initialized with
          their default config. Window visiblity/dimensions on other
          tabpages may get out of sync with their buffer content.
Solution: Copy the window config of the window to the new tabpage.
          No longer keep track of the various windows on each tabpage.
          Close windows on inactive tabpages instead (moving them could
          be more efficient but is currently not supported in the API).

Fix #34300

### CODE REVIEW

File: runtime/lua/vim/_extui.lua [hunk 1]
```diff
@@ -133,13 +133,13 @@ function M.enable(opts)
       end
       ext.msg.set_pos()
     end,
-    desc = 'Set cmdline and message window dimensions after startup and shell resize.',
+    desc = 'Set extui window dimensions after startup, shell resize or tabpage change.',
```
Comment (justinmk) [inline runtime/lua/vim/_extui.lua:134]: The feature definitely isn't going to be named "extui" when we release it. If this isn't about messages or the pager, we would just call this "UI", since it is a builtin feature.

**Review by justinmk — APPROVED** [review]
