### PR TITLE
fix(lsp): reset the applied hints when processing the `refresh` request

### LINKED ISSUE #32248: LSP: `textDocument/inlay_hint` not being correctly published when recieved
### Problem

When a server responds to the `textDocument/inlay_hint` response with inlay hints they aren't correctly being updated in the current buffer when recieved.

### Steps to reproduce using "nvim -u minimal_init.lua"

You can reproduce this, but you'd need a few things installed

- The Scala language server [Metals](https://scalameta.org/metals/) (most easily done with [cs install metals](https://get-coursier.io/))
- create a `inlay.worksheet.sc` file (the name is important so it matches the minimal conf)

Inside of these file you can have the following:

`inlay.worksheet.sc`

```scala
val x = 3
```

The minimal init file looks like this:

```lua
local pattern = 'scala'
local cmd = { 'metals' }
-- Add files/folders here that indicate the root of a project
local root_markers = { 'inlay.worksheet.sc' }

local settings = {
  metals = {
    enableSemanticHighlighting = false,
  }
}

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'metals',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})
```

Now open the file and let Metals fully load everything. Once completed you can do `:lua vim.lsp.inlay_hint.enable(true)` which will show you the evaluation and the inlay hint of `// : Int = 3`. It should look like this:

Image

Now, if you change the `3` in the file to a `4` and hit save, there will be a couple things that happen. Firstly a request for inlay hints is sent and a new set of inlay hints are received with the new evaluation being `//: Int = 4` however, the buffer won't be updated here. The logs for this are down below.

```
[Trace - 04:04:03 PM] Sending request 'workspace/inlayHint/refresh - (22)'
Params: null

[Trace - 04:04:03 PM] Received request 'textDocument/inlayHint - (13)'
Params: {
  "textDocument": {
    "uri": "file:///Users/ckipp/Documents/scratch/inlay/inlay.worksheet.sc"
  },
  "range": {
    "start": {
      "line": 0,
      "character": 0
    },
    "end": {
      "line": 1,
      "character": 0
    }
  }
}


[Trace - 04:04:03 PM] Received response 'workspace/inlayHint/refresh - (22)' in 1ms
Result: null
Error: null

[Trace - 04:04:03 PM] Sending response 'textDocument/inlayHint - (13)'. Processing request took 0ms
Result: [
  {
    "position": {
      "line": 0,
      "character": 9
    },
    "label": " // : Int \u003d 4",
    "tooltip": "x: Int \u003d 4"
  }
]
```

### Expected behavior

When the client receives new inlay hints I expect it to update the current buffer when inlay hints are enabled. As you can see in the logs the `textDocument/inlayHint` is received with new hints, but it's not displayed.

Sort of an aside, but I'm confused why a `workspace/inlayHint/refresh` is always sent as well. Nothing changed in the workspace configuration to trigger this and [according to the spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_inlayHint_refresh)

> This is useful if a server detects a configuration change which requires a re-calculation of all inlay hints.

In this situation, it was just a file change, so all workspace hints should really be refreshed should they?

### Nvim version (nvim -v)

NVIM v0.10.4

### Language server name/version

metals 1.5.1

### Operating system/version

Mac OS but any has the same

### Log file

_No response_

EDIT:

If you are actually using metals to try and debug this, we have a mechanism to see nicely formatting logs. You should see a `.metals/` created in the current dir and if you create a `lsp.trace.json` file in that directory and then start the server again you'll see it populated with all the LSP logs.

### LINKED ISSUE #32283: LSP: `textDocument/inlayHint` at the end of a line not being removed when the line is deleted
### Problem

When getting `textDocument/inlayHint`s that are at the end of a line from a server it seems that when you remove that line, it will remove any inlay hints that were before the end, but then the last one at the end of the line still remains when it shouldn't.

### Steps to reproduce using "nvim -u minimal_init.lua"

You can reproduce this, but you'd need a few things installed

- The Scala language server [Metals](https://scalameta.org/metals/) (most easily done with [cs install metals](https://get-coursier.io/))
- create a `inlay.worksheet.sc` file (the name is important so it matches the minimal conf)

Inside of these file you can have the following:

`inlay.worksheet.sc`

```scala
val x = 3

x * 3
```

The minimal init file looks like this:

```lua
local pattern = 'scala'
local cmd = { 'metals' }
-- Add files/folders here that indicate the root of a project
local root_markers = { 'inlay.worksheet.sc' }

local settings = {
  metals = {
    enableSemanticHighlighting = false,
    showInferredType = true
  }
}

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'metals',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})
```

Now open the file and let Metals fully load everything. Once completed you can do `:lua vim.lsp.inlay_hint.enable(true)` which will show you 3 inlay hints. One for the inferred type and 2 for the evaluations. It should look like this:

Image

Now, if you just delete fully the first line and save the buffer you'll see the first evaluation tied to the line that was just deleted is still there.

Image

Also note that in this situation if you do a `:lua vim.print(vim.lsp.inlay_hint.get({bufnr = 0}))` you'll get `{}` as the result. So there shouldn't be any inlay hints still being displayed, but both evaluations are still there.

### Expected behavior

When a user deletes a line, I'd expect _all_ of the inlay hints related to that line to be removed. Also if the server responds with no inlay hints, the client shouldn't keep this stale state. I think this is the same as the other issue I created in https://github.com/neovim/neovim/issues/32248 however the differing part here is that even before saving I think if you delete a line of text from a buffer it should remove all of the inlay hints, even at the end of the line. My guess is what is happening here is that all inlay hints that fall within the range of the text is removed, however this one falls outside of that range because it's at the end of the line. But that's just a guess.

### Nvim version (nvim -v)

v0.11.0-dev-1666+gf3381a8b64

### Language server name/version

Metals 0.5.1

### Operating system/version

Happens on multiple OS's

### Log file

_No response_

### PR DESCRIPTION
**Pull request by ofseed**
Closes https://github.com/neovim/neovim/issues/32248.
Closes https://github.com/neovim/neovim/issues/32283.

I guess this bug means that our `workspace/inlayHint/refresh` handler has never worked correctly because we treat the new hints we receive as applied and ignore them.

Considering this, I will add two tests (along with one for https://github.com/neovim/neovim/pull/32426). I forgot how to use the test suite, so I would need to do this later in this PR or a follow-up PR if this PR is merged first.

### CODE REVIEW

File: runtime/lua/vim/lsp/inlay_hint.lua [hunk 1]
```diff
@@ -94,6 +94,10 @@ function M.on_refresh(err, _, ctx)
   for _, bufnr in ipairs(vim.lsp.get_buffers_by_client_id(ctx.client_id)) do
     for _, winid in ipairs(api.nvim_list_wins()) do
       if api.nvim_win_get_buf(winid) == bufnr then
+        local bufstate = bufstates[bufnr]
+        if bufstate then
```
Comment (justinmk) [inline runtime/lua/vim/lsp/inlay_hint.lua:98]: unnecessary local declaration?
```suggestion
        if bufstates[bufnr] then
```

**Comment by justinmk** [comment]
Would you mind rebasing this?

> forgot how to use the test suite

See [test/functional/example_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/example_spec.lua) for example. You can [run the test](https://github.com/neovim/neovim/blob/master/test/README.md#filter-by-file) like this:

    TEST_FILE=test/functional/example_spec.lua make functionaltest
