### PR TITLE
Fix #5270 syntax folding optimization

### LINKED ISSUE #5270: syntax folding + completion (Ctrl+N) is slow
- `nvim --version`: 0.14-dev
- Vim (version: ) behaves differently? Nope. VIM is painfully slow when Syntax Folding is on, too
- Operating system/version: Mac OSX 10.10.5
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color
### Actual behaviour
Turn on Syntax Folding, Then collapse all the fold, then expand one fold and type Ctrl+N. It takes very a long delay until Neovim start to respond
### Expected behaviour
Neovim offer autocomplete after a fraction of second
### Steps to reproduce using `nvim -u NORC`
(no idea)

### PR DESCRIPTION
**Pull request by Shougo**
- Add compl_busy set in `complete()`
- Ignore folding update if foldmethod is "expr" or "sytax" and in insert mode like FastFold plugin

@phuongnd08 Please test it.

Note:  I will send PR for Vim, too.

### CODE REVIEW

**Comment by justinmk** [comment]
>  I will send PR for Vim, too.

Can you send it there first? Reviewing this and adding tests for it won't be a good use of our time if we have to merge back whatever changes happen upstream.

**Comment by Shougo** [comment]
I sent to vim_dev.

https://github.com/vim/vim/pull/1045

**Comment by Shougo** [comment]
I think the folding update should be ignored in insert mode.

**Comment by justinmk** [comment]
:+1:

**Comment by Shougo** [comment]
OK.  I will update it.

**Comment by Shougo** [comment]
I have pushed.  I think it is simpler and better.

**Comment by Shougo** [comment]
The patch is already todo listed in Vim.
https://github.com/vim/vim/blob/3c4ebeba17399e4ef33d004c269e667f696f0eb6/runtime/doc/todo.txt#L181

So, I think it is `[RDY]`.

**Comment by Shougo** [comment]
I have removed compl_busy changes.
It seems no means.

File: src/nvim/fold.c [hunk 1]
```diff
@@ -762,7 +762,7 @@ void clearFolding(win_T *win)
  */
 void foldUpdate(win_T *wp, linenr_T top, linenr_T bot)
 {
-  if (compl_busy) {
+  if (State & INSERT) {
```
Comment (justinmk) [inline src/nvim/fold.c]: I'd feel better if this was `compl_busy || (State & INSERT)`

Comment (Shougo) [inline src/nvim/fold.c]: Why?  compl_busy is set in insert mode.  So no means.

Comment (justinmk) [inline src/nvim/fold.c]: It probably doesn't matter currently, but `compl_busy` could be used in later Vim patches to take on more meaning.

Comment (Shougo) [inline src/nvim/fold.c]: Hm...
OK

**Comment by justinmk** [comment]
Oops, `045_folding_spec.lua` is failing. Will you be able to check that?

**Comment by Shougo** [comment]
I get the problem.  I will fix it.

**Comment by Shougo** [comment]
I have fix the problem.
https://github.com/neovim/neovim/pull/5351
