### PR TITLE
fix(treesitter): disallow empty filetypes

### LINKED ISSUE #22473: `treesitter.get_parser()` should not link empty `filetype` to `lang`
### Problem

Might caused by #22207.

`treesitter.get_parser()` (which calls `_create_parser`) unconditionally links the buffer `filetype` to `lang`, even if `filetype` is actually empty. Some plugins use TS without setting `filetype` beforehand to have finer control (e.g. [nvim-telescope](https://github.com/nvim-telescope/telescope.nvim/blob/a3f17d3baf70df58b9d3544ea30abe52a7a832c2/lua/telescope/previewers/utils.lua#L134)), causing the empty filetype to be linked to some valid TS parser. That parser might be accidentally triggered when loading a buffer with empty filetype (e.g. a huge log file like `:LspLog`), causing performance issues.

https://github.com/neovim/neovim/blob/a0292b4e5f106482edc5623eef85aa48e2e55bb7/runtime/lua/vim/treesitter.lua#L50

### Steps to reproduce

```bash
nvim --clean --headless \
  '+lua print(vim.treesitter.get_parser(0, "c"))' \
  '+lua print(vim.treesitter.get_lang(""))' \
  '+edit ~/.local/state/nvim/lsp.log' \
  '+lua print(vim.inspect(vim.treesitter.get_node()))' \
  '+q'
```

`get_lang("")` returns `"c"` and `get_node()` succeeds, and if `lsp.log` is large, it hangs for ages doing useless paring.

### Expected behavior

`get_lang("")` should return `nil`, and `get_node()` should fail immediately as `lsp.log` has empty `filetype`.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1092+gbc15b075d

### Vim (not Nvim) behaves the same?

no

### Operating system/version

linux

### Terminal name/version

wezterm

### $TERM environment variable

tmux-256color

### Installation

appimage

### PR DESCRIPTION
**Pull request by lewis6991**
Fixes #22473

### CODE REVIEW

File: runtime/lua/vim/treesitter/language.lua [hunk 1]
```diff
@@ -60,6 +60,10 @@ function M.add(lang, opts)
     filetype = { filetype, { 'string', 'table' }, true },
   })
 
+  if filetype == '' then
+    error(string.format("'%s' is not a valid filetype", filetype))
```
Comment (justinmk) [inline runtime/lua/vim/treesitter/language.lua:64]: could use a validtor function with vim.validate() above

**Review by justinmk — APPROVED** [review]

File: runtime/lua/vim/treesitter/language.lua (hunk 1 above)
Comment (lewis6991) [reply runtime/lua/vim/treesitter/language.lua:64]: Just tried it, and couldn't get it to give a nice enough error message:

```
Passed in:
(string) '.../language.lua:0: filetype: expected filetype or list of filetypes, got '
Expected:
(string) '.../language.lua:0: '' is not a valid filetype'
```

Comment (justinmk) [reply runtime/lua/vim/treesitter/language.lua:64]: > filetype: expected filetype or list of filetypes, got 

This is our standard error format, it's nice because it shows the parameter name clearly as the first item. We could enhance vim.validate() to put quotes around string values, so that it looks like this?

> filetype: expected filetype or list of filetypes, got ""

Comment (lewis6991) [reply runtime/lua/vim/treesitter/language.lua:64]: I'm not sure, I think the error message is still worse (standard or not) as we want to explicitly disallow `''`. The standard error message doesn't make that clear enough.

**Review by cairijun — COMMENTED** [review]
LGTM but I'm curious about the necessity of creating such a link on `get_parser()`... Or should we at least doc about this?

**Comment by lewis6991** [comment]
`get_parser()` ties a specific parser to a buffer, so I think it makes sense to also link the filetype. `get_string_parser()` on the other hand does not link to a buffer and thus does not link a filetype.

File: runtime/lua/vim/treesitter/language.lua (hunk 1 above)
Comment (lewis6991) [reply runtime/lua/vim/treesitter/language.lua:64]: I'll merge as is for now, but if the suggested change to `vim.validate` is done (with maybe other changes), then we can update this error message.

One idea would be if a validation function returns the error message to allow more specific error messages, so we could have both depending on input.

```
(string) '.../language.lua:0: filetype: '' is not a valid filetype'
(string) '.../language.lua:0: filetype: expected string or table'
```

Comment (justinmk) [reply runtime/lua/vim/treesitter/language.lua:64]: Sounds good, with the caveat that the message should read:

    (string) '.../language.lua:0: filetype: invalid filetype: ''

It is generally a good idea to put the variable part at the end, else random input can create hard to read messages. It's also more regular and visually predictable for users. This is also the format used for API validation.
