### PR TITLE
fix: remote UI may get invalid 'pumblend' value

### LINKED ISSUE #19340: pumblend is not clamped to 0 when sent over rpc
### Neovim version (nvim -v)

v0.8.0-dev+578-gca64b589c

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux/Arch

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

nvim-nightly-bin (aur)

### How to reproduce the issue

My specific encounter of this bug is in [neovide](https://github.com/neovide/neovide/) as reported in [this](https://github.com/neovide/neovide/issues/1392) issue, but any rpc client should show the same issue. The steps below are assuming you have neovide installed

1. run `neovide`
2. type `:set pumblend=-1` and hit enter
3. witness neovide crashes due to receiving a value of `-1` for pumblend 

### Expected behavior

pumblend should be clamped to `0` on the lower bound as it is (I think?) to 100 on the upper bound

### Actual behavior

Its not clamped

### PR DESCRIPTION
**Pull request by 0x00002a**
fixes: https://github.com/neovim/neovim/issues/19340

After looking at this function I believe the issue that caused #19340 is due to `p_pb` being updated [here](https://github.com/0x00002a/neovim/blob/0b1b37e50e6032bc9420590580c768672e43bca8/src/nvim/option.c#L4640) (which `pp` points too) but `value` (which the value of `pp` was set too) not. I did a quick search and I couldn't find anywhere `value` was updated after `*pp` was set too it so I _think_ this is ok. 

I've verified it no longer causes neovide to crash but I haven't really tested it beyond that

### CODE REVIEW

**Comment by justinmk** [comment]
yes, this change is correct. `set_num_option` first does a bunch of fixups/validation, so `ui_call_option_set` should not operate on `value`.

Next question would be, are the other calls to `ui_call_option_set`  in this file correct?

**Comment by justinmk** [comment]
can you add a test here (and check that it correctly fails before the fix): https://github.com/neovim/neovim/blob/9370e1c5111ee90f64260398b0623da4759f8f16/test/functional/ui/options_spec.lua#L80

You can [run the test](https://github.com/neovim/neovim/blob/master/test/README.md#running-tests) like this:

    TEST_FILE=test/functional/example_spec.lua make functionaltest

**Comment by 0x00002a** [comment]
@justinmk 
https://github.com/neovim/neovim/blob/5c49129c5e334a9c7da253499cd9aa19358d4ac9/src/nvim/option.c#L4346 looks suspicious, `varp` is set [here](https://github.com/neovim/neovim/blob/5c49129c5e334a9c7da253499cd9aa19358d4ac9/src/nvim/option.c#L4070) and then updated such as [here](https://github.com/neovim/neovim/blob/5c49129c5e334a9c7da253499cd9aa19358d4ac9/src/nvim/option.c#L4089)

**Comment by justinmk** [comment]
> looks suspicious, `varp` is set [here](https://github.com/neovim/neovim/blob/5c49129c5e334a9c7da253499cd9aa19358d4ac9/src/nvim/option.c#L4070) and then updated such as [here](https://github.com/neovim/neovim/blob/5c49129c5e334a9c7da253499cd9aa19358d4ac9/src/nvim/option.c#L4089)

good catch. probably not easy to test that one though, I don't think 'langremap' is part of what we call "UI options". But can still at least fix it in this PR too.

**Comment by 0x00002a** [comment]
I think I have angered the linter by using `chore(tests)`, didn't realise there was a semantic commits scheme already being used. Should I amend it and force push?

**Comment by justinmk** [comment]
> I think I have angered the linter by using `chore(tests)`, didn't realise there was a semantic commits scheme already being used. Should I amend it and force push?

no i'll fix it at merge time, if CI passes

File: test/functional/ui/options_spec.lua [hunk 1]
```diff
@@ -86,6 +86,11 @@ describe('UI receives option updates', function()
     screen:expect(function()
       eq(expected, screen.options)
     end)
+    command("set pumblend=-1")
```
Comment (justinmk) [inline test/functional/ui/options_spec.lua:89]:
```suggestion
    
    command("set pumblend=-1")
```

**Review by justinmk — APPROVED** [review]

File: test/functional/ui/options_spec.lua [hunk 2]
```diff
@@ -86,6 +86,12 @@ describe('UI receives option updates', function()
     screen:expect(function()
       eq(expected, screen.options)
     end)
+
```
Comment (justinmk) [inline test/functional/ui/options_spec.lua:89]:
```suggestion
```
