### PR TITLE
fix(lsp): limit number of created highlight groups

### LINKED ISSUE #38930: LSP: `E849` with `vim.lsp.document_color` in file with >19999 hex colors
### Problem

With enabled LSP color visualization, when file/buffer contains too many hex color strings, there are many `E849: Too many highlight and syntax groups` errors.

### Steps to reproduce

1. Have `lua-language-server` in `$PATH`.
2. Create `~/.config/nvim-repro/init.lua` file with the following content:

    ```lua
    vim.lsp.document_color.enable(true)

    _G.start_luals = function()
      local config = { name = 'lua-ls', cmd = { 'lua-language-server' }, root_dir = vim.fn.getcwd() }
      _G.client_id = vim.lsp.start(config)
    end

    _G.show_many_colors = function()
      local lines = {}
      for i = 1, 20000 do
        lines[i] = string.format('local color_%06x = "#%06x"', i, i)
      end
      vim.api.nvim_buf_set_lines(0, 0, -1, false, lines)
    end
    ```

3. `NVIM_APPNAME=nvim-repro nvim -- many-colors.lua`.
4. `:write` to create an actual file on disk.
5. `:lua start_luals()` and wait for a couple of seconds.
6. `:lua show_many_colors()`. After couple of seconds it shows `E849: Too many highlight and syntax groups` error followed by many more after pressing `<Enter>`. This happens because maximum number of highlight groups possible is 19999.

The real life file that contains more than 19999 hex colors: https://github.com/meodai/color-names/blob/HEAD/src/colornames.csv .No error with `lua-language-server` as it is not a Lua file, but there can be an LSP server for csv or all files.

### Expected behavior

Either (from best to worst):
- No upper limit on highlight groups number.
- Creating (much) more than 19999 highlight groups is possible. Maybe 100K?
- No error when creating highlight groups beyond the limit.
- No error coming from `vim.lsp.document_color` when creating many highlight groups.

### Nvim version (nvim -v)

NVIM v0.13.0-dev-133+g6d43869aa0

### Vim (not Nvim) behaves the same?

Yes and no: has upper limit on highlight group number but doesn't have `vim.lsp.document_color` functionality

### Operating system/version

EndeavourOS Linux x86_64, 6.19.11-arch1-1

### Terminal name/version

Ghostty 1.3.1-arch1

### $TERM environment variable

xterm-ghostty

### Installation

Appimage

### PR DESCRIPTION
**Pull request by echasnovski**
This is an attempt to fix #38930:

- Allow `nvim_set_hl()` (and `nvim_get_hl_id_by_name()`) be silenced if there are too many highlight groups. I've added a test for it, but it comparatively much slower to other related ones: around 2000ms compared to an average of ~7ms on my machine. Should this still be present or is it too much?
- Limit the number of highlight groups created by `vim.lsp.document_color` to 10000 (half of maximum allowed 19999 highlight groups). Just using `pcall(vim.api.nvim_set_hl, 0, ...)` does indeed silence errors from `vim.lsp.document_color`, but crossing the limit of maximum allowed highlight groups introduces problems in other areas. Like:
    - There is still an error from `DiagnosticChanged *` autocommand which I was not able to locate.
    - All the messages are still shown in pager with `ui2`.
    - Other functionality that relies on creating highlight groups will not work.

I am not entirely sure that this is the best approach to take for this use case, but at least it seems to solve the problem while it still works for most common reasonable use cases.

### CODE REVIEW

**Review by MariaSolOs — APPROVED** [review]

File: runtime/lua/vim/lsp/document_color.lua [hunk 1]
```diff
@@ -65,30 +65,37 @@ end
...
-    end
+  if color_cache[hl_name] then
+    return hl_name
+  end
 
-    color_cache[hl_name] = true
+  -- Limit number of created highlight groups to 10000 to not approach near
+  -- a hard limit of 19999 highlight groups (`:h E849`)
+  if n_color_cache > 10000 then
+    return nil
```
Comment (justinmk) [inline runtime/lua/vim/lsp/document_color.lua:89]: log a "info"  the first time this is hit? to avoid another variable, could maybe set `n_color_cache=-1` or something
