### PR TITLE
fix(ui): avoid ambiguity about chunk that clears part of line

### LINKED ISSUE #24955: Glitch for a Long Line with Trailing Spaces
### Problem

Visual glitch occurs when a line has any non-space characters whose columns are less than or equal to the terminal width, and so many trailing spaces that the line length is greater than twice of the terminal width.

long

### Steps to reproduce

Set the terminal width to 80.

Download [a.txt](https://github.com/neovim/neovim/files/12480777/a.txt) and open it. The line length of the first line is 161.
Move the cursor.

Redraw fixes the glitch.

### Expected behavior

No visual glitch.

### Neovim version (nvim -v)

v0.10.0-dev-995+gb2c3e9c72

### Vim (not Nvim) behaves the same?

no, vim 9.0.1736

### Operating system/version

EndeavourOS

### Terminal name/version

GNOME Terminal 3.48.2 using VTE 0.72.2 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #24955

### CODE REVIEW

**Comment by bfredl** [comment]
This won't handle an raw_line event which intentionally only cleared a segment. The following alternative change also satisfies the test while still allowing that.

```diff
diff --git a/src/nvim/api/ui.c b/src/nvim/api/ui.c
index 9fa5a89407..45e868afb2 100644
--- a/src/nvim/api/ui.c
+++ b/src/nvim/api/ui.c
@@ -830,6 +830,7 @@ void remote_ui_raw_line(UI *ui, Integer grid, Integer row, Integer startcol, Int
     size_t ncells = (size_t)(endcol - startcol);
     int last_hl = -1;
     uint32_t nelem = 0;
+    bool was_space = false;
     for (size_t i = 0; i < ncells; i++) {
       repeat++;
       if (i == ncells - 1 || attrs[i] != attrs[i + 1]
@@ -868,9 +869,10 @@ void remote_ui_raw_line(UI *ui, Integer grid, Integer row, Integer startcol, Int
         data->ncells_pending += MIN(repeat, 2);
         last_hl = attrs[i];
         repeat = 0;
+        was_space = strequal(chunk[i], " ");
       }
     }
-    if (endcol < clearcol) {
+    if (endcol < clearcol || was_space) {
       nelem++;
       data->ncells_pending += 1;
       mpack_array(buf, 3);
```

In case the last chunk was a space `" "` char, there must always be an extra chunk, even if empty. this would be accepted by the existing unpacker.c logic.

File: test/functional/terminal/tui_spec.lua [hunk 1]
```diff
@@ -2703,8 +2725,8 @@ describe("TUI as a client", function()
     local client_super = spawn_argv(true)
 
     set_session(server)
-    local server_pipe = eval'v:servername'
-    feed'iHalloj!<esc>'
```
Comment (bfredl) [inline test/functional/terminal/tui_spec.lua:2707]: this doesn't need to change. `set_session(server)` makes global calls, including `feed`, in the context of the server.

**Review by bfredl — APPROVED** [review]

File: test/functional/terminal/tui_spec.lua (hunk 1 above)
Comment (zeertzjq) [reply test/functional/terminal/tui_spec.lua:2707]: I just want to avoid using `feed()` in this test file, because it easy to mix it up with `feed_data()`, causing data races.

**Comment by fredizzimo** [comment]
I will create a proper bug report soon, when I have made a minimal config, but this broke at least the 0.9 branch when using Neovide. Terminal mode Neovim seems to be fine.

At least the following are broken:
* The telescope selection highlight is sometimes broken up
* When using `indent-blankline.nvim` the first character of the column is often missing.
