### PR TITLE
TUI: Konsole 18.07.70 supports DECSCUSR

### LINKED ISSUE #6778: 'guicursor': Altering cursor in tmux + konsole alters it in all tmux panes/windows
- `nvim --version`: bde46fdec
- Terminal name/version: konsole-16.12.3, tmux-2.2
- `$TERM`: screen-256color

### Steps to reproduce

1. Run `tmux new-session \; split-window`
2. Run `nvim -u NONE -i NONE`.
3. Enter insert mode. Cursor will change to vertical line.
4. Given `<TmuxPrefix>` is tmux prefix (`<C-b>` by default) run `<TmuxPrefix>:select-pane -t :.+`.

### Actual behaviour

After 4 you are in another pane where Neovim was not opened, but cursor is a vertical line. Note that if it was opened, but was not in insert mode then cursor will still be wrong.

### Expected behaviour

It is still a block like it was before Neovim was run, vertical line only in tmux pane.

---

I actually do not like Neovim messing up with the cursor by default at all, empty `guicursor` by default would be better (init.vim is not an option, not for a developer since I need to use `-u NONE` often; previous variant with environment variable was better). But this behaviour is simply wrong, *do not try bypassing tmux*, disable changing cursor shape when in tmux instead, switching cursor shape should be a tmux responisibility. Current variant works well only if tmux user uses one pane and one window.

### LINKED ISSUE #6798: nvim changes font size in KDE Konsole
- `nvim --version`:
nvim --version
NVIM v0.2.1-232-gc4a8950
- Vim (version: ) behaves differently?
Yes.
- Operating system/version:
Fedora 25
- Terminal name/version:
Konsole 16.12.3
- `$TERM`:
xterm-256color

### Actual behaviour

nvim changes font size in Konsole terminal if the current size is not the default configured in the settings.

### Expected behaviour

Font size should not change.

### Steps to reproduce using `nvim -u NORC`

Open Konsole, increase or decrease font size from default, start nvim with ``nvim -u NONE -i NONE`` and nvim changes the font size back to the default configured in Konsole settings.

Starting nvim via ``nvim -u nvim-no-cursor -i NONE`` where ``nvim-no-cursor`` contains only one line: ``set guicursor=`` doesn't exhibit this behaviour (font size doesn't change).

(It still changes with that config set when using CtrlP and probably other plugins, but that just might be related.)

### PR DESCRIPTION
**Pull request by justinmk**
ref https://github.com/KDE/konsole/commit/b0d3d83eca4f523a9e4acd3989da6be96033536a

KONSOLE_VERSION is exported as a numeric string (after removing the dots
from the version string).

ref #8300
closes #6778
closes #6798

### CODE REVIEW

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -1654,7 +1657,8 @@ static void patch_terminfo_bugs(TUIData *data, const char *term,
   }
 
   // Blacklist of terminals that cannot be trusted to report DECSCUSR support.
-  if (!(st || (vte_version != 0 && vte_version < 3900) || konsole)) {
+  if (!(st || (vte_version != 0 && vte_version < 3900)
+        || (konsolev > 0 && konsolev < 180770))) {
```
Comment (justinmk) [inline src/nvim/tui/tui.c]: @ahmadsamir is this how the version should be checked?

Comment (ahmadsamir) [reply src/nvim/tui/tui.c]: Yes, exactly. (And sorry for not replying earlier :)).
