### PR TITLE
fix(highlight): prevent Normal-linked groups from overriding CursorLine

### LINKED ISSUE #9019: CursorLine priority issues when 'linking to Normal'
- nvim 0.3.1
- all terminals and operating systems.

Since I upgraded to Neovim 0.3.1 I notice NERDTree cursorline looks broken with my preferred Vim theme of [moonfly](https://github.com/bluz71/vim-moonfly-colors).

Some Googling indicates others have the same experience as noted in [this Reddit thread](https://www.reddit.com/r/vim/comments/91b7mg/broken_cursorline_highlighting_nvim/) and following image.

9g9lht08nrb11

Notice the `CursorLine` in the NERDTree window, it does not stretch across the full width of the window, it only highlights the section after the `zsh` extension.

I get the same result with my theme.

I think this relates to Neovim changes to CursorLine priority; especially if one only sets a `ctermbg` color without setting a foreground color. Reading through some of the Neovim CursorLine priority discussions it is mentioned that if one sets foreground and background then the priority system will not come it play. That is correct from my quick testing.

However, in my case I do not want to set a foreground color for the `CursorLine`, I only set a low contrast background color whilst preserving the existing colors of the current line. Setting a CursorLine foreground color results in the loss of coloring for the current selected line (aka it looks ugly with my theme).

How can I bypass Neovim CursorLine priority changes (for 0.3.1 and above) whilst only setting the background color?

Note, Vim 8.1 renders the NERDTree current line correctly via `CursorLine` if background is the only color set. Same went for Neovim 0.3.0 and earlier.

Thanks.

### PR DESCRIPTION
**Pull request by glepnir**
fix(highlight): prevent Normal-linked groups from overriding CursorLine

Problem: CursorLine doesn't consistently highlight text using groups
linked to Normal (e.g., in quickfix, passwd files), while it works
for direct Normal usage.

Solution: Don't let normal background from linked groups override
explicit non-normal backgrounds during attribute combination.
Fix #35017
Fix #9019

### CODE REVIEW

**Comment by zeertzjq** [comment]
This looks a bit hacky

**Comment by glepnir** [comment]
how about now 🤔

File: src/nvim/highlight.c [hunk 1]
```diff
@@ -623,7 +623,9 @@ int hl_combine_attr(int char_attr, int prim_attr)
                            | (prim_aep.rgb_ae_attr & HL_FG_INDEXED));
   }
 
-  if (prim_aep.cterm_bg_color > 0) {
+  if (prim_aep.cterm_bg_color > 0
+      && !(prim_aep.cterm_bg_color == cterm_normal_bg_color && char_aep.cterm_bg_color > 0
```
Comment (bfredl) [inline src/nvim/highlight.c]: this will break any case where `prim_aep` was explicitly set to the same RGB color as Normal. if this is about special rules for low-priority CursorLine, it is better to add a specific rule for that in the cursorline code in drawline.c .

 Although "normal linked" groups should ideally just be replaced with cleared groups in the cases the present effect is undesirable (including replacing a `hi def link foo Normal` with just letting the default of `foo` being completely unset). Linking normal feels like an opt-in for allowing the normal values to work at the priority of the `foo` group.

File: test/functional/ui/highlight_spec.lua [hunk 2]
```diff
@@ -1378,6 +1378,23 @@ describe('CursorLine and CursorLineNr highlights', function()
                                                         |
     ]])
   end)
+
+  it('CursorLine works with highlight groups linked to Normal', function()
```
Comment (justinmk) [inline test/functional/ui/highlight_spec.lua]: should this say "overrides" or "overlays"? "works with" is vague.
```suggestion
  it('CursorLine overlays hl group linked to Normal', function()
```

**Review by justinmk — APPROVED** [review]
LGTM, @zeertzjq @bfredl ?

File: src/nvim/drawline.c [hunk 3]
```diff
@@ -2924,7 +2924,19 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, int col_rows, b
...
     if (wlv.filler_todo <= 0) {
       // Apply lowest-priority line attr now, so everything can override it.
-      wlv.char_attr = hl_combine_attr(wlv.line_attr_lowprio, wlv.char_attr);
+      if (wlv.line_attr_lowprio != 0) {
+        HlAttrs line_ae = syn_attr2entry(wlv.line_attr_lowprio);
+        HlAttrs char_ae = syn_attr2entry(wlv.char_attr);
+        // If line has background (CursorLine) and char's background equals Normal's background,
+        // reverse the combination order to let CursorLine override normal_bg.
+        if ((line_ae.rgb_bg_color >= 0 || line_ae.cterm_bg_color > 0)
+            && (char_ae.rgb_bg_color == normal_bg)) {
```
Comment (zeertzjq) [inline src/nvim/drawline.c]: No check for `char_ae.cterm_bg_color`?
