### PR TITLE
fix(prompt): left, c-left, home keys forces cursor to end of prompt

### LINKED ISSUE #36195: prompt buffer: fix `i_<Left>`, `i_<C-Left>`, `i_<Home>`, `i_<End>`
### Problem

- when the cursor is of the start of prompt buffer input text, `i_<Left>` and `i_<C-Left>` jumps to the end of it.
- `i_<Home>`, `i_<End>` does not work completely.

@shadmansaleh could you look? 0.11.4 works as expected, Vim too. 

### Steps to reproduce

init.vim:
```vim
set buftype=prompt
call prompt_setprompt(bufnr(''), 'shell command: ')
startinsert
call feedkeys('nvim --version', 'i')
```

- `nvim --clean -u init.vim`
- try  `<C-Left>`, `<Left>`, `<Home>`, `<End>`

### Expected behavior

All these keymaps behave like in 0.11.4 or Vim. 

### Nvim version (nvim -v)

v0.12.0-dev-1416+g29056e636e

### Vim (not Nvim) behaves the same?

no, Vim 9.1-1806

### Operating system/version

Debian Sid

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

from repo

### PR DESCRIPTION
**Pull request by shadmansaleh**
**Problem**:
Currently, whenever a user gets on the prompt-text area, we move the user to the end of the user-input area. As a result, when left/c-left, home keys are triggered at the start of user-input, the cursor gets placed at the end of user-input. But this behavior can be jarring and unintuitive. Also, it's different from previous behavior, where it'd just stay at the start of the input area. Also, previously, when insert-mode was triggered in prompt-text with n_a, for example, then the cursor was placed at the start of the user-input area, not at the end. So, that behavior was also broken.

**Solution:**
Restore previous behavior. Don't force the user to end of input when entering insert mode from read-only section. Instead, put them on the writable section of the prompt line like before. The `n_A` still puts the user at to end of input like before. Keeping consistent behavior with v0.11. 

fixes #36195

### CODE REVIEW

File: test/functional/legacy/prompt_buffer_spec.lua [hunk 1]
```diff
@@ -337,11 +337,40 @@ describe('prompt buffer', function()
...
       other buffer             |
-      % line1                  |
-      line^2                    |
+      %^ line1                  |
+      line2                    |
       {1:~                        }|*6
                                |
     ]])
+
+    -- i_<Left> i_<C-Left> i_<Home> i_<End> keys on pormpt-line doesn't put cursor
```
Comment (zeertzjq) [inline test/functional/legacy/prompt_buffer_spec.lua]:
```suggestion
    -- i_<Left> i_<C-Left> i_<Home> i_<End> keys on prompt-line doesn't put cursor
```

**Comment by shadmansaleh** [comment]
For context:

The change originally came from https://github.com/neovim/neovim/pull/33371#issuecomment-2983545388

> What's a bit odd with the changes here is that now i/a allow to edit the prompt text and also no longer jump to the end of the prompt text depending on where the cursor is. E.g. If I'm a line above a will jump to the end, but if the cursor is within the prompt text, it won't. Is that intentional?

Basically, when insert-mode is triggered from pormpt-text before the prompt-buffer rewrok it'd put the cursor at start of user-input. Afterwards, when introducing multiline support, I made it so if fi user is in read-only section user would be placed at end of user-input area when insert is triggered.

**Comment by przepompownia** [comment]
It simply works for me for a week. Is no one else interested?

**Comment by crwebb85** [comment]
> Is no one else interested?

I still want this fixed. If this solution fixes it, then I think we should go with it.

**Comment by zeertzjq** [comment]
rebase?

File: test/functional/legacy/prompt_buffer_spec.lua [hunk 2]
```diff
@@ -319,8 +319,8 @@ describe('prompt buffer', function()
     feed('<esc>')
     screen:expect([[
       other buffer             |
-      % line1                  |
-      line^2                    |
+      %^ line1                  |
+      line2                    |
```
Comment (zeertzjq) [inline test/functional/legacy/prompt_buffer_spec.lua:323]: This comment above seems no longer correct:
```lua
    -- ensure cursor gets adjusted to end of user-text to prompt when insert mode
    -- is entered from readonly region of prompt buffer
```

Comment (shadmansaleh) [reply test/functional/legacy/prompt_buffer_spec.lua:323]:
```diff
--- a/test/functional/legacy/prompt_buffer_spec.lua
+++ b/test/functional/legacy/prompt_buffer_spec.lua
@@ -302,8 +302,8 @@ describe('prompt buffer', function()
       {5:-- INSERT --}             |
     ]])
 
-    -- ensure cursor gets adjusted to end of user-text to prompt when insert mode
-    -- is entered from readonly region of prompt buffer
+    -- ensure cursor gets placed on first line of user input.
+    -- when insert mode is entered from read-only region of prompt buffer.
     local prompt_pos = api.nvim_buf_get_mark(0, ':')
     feed('<esc>')
     -- works before prompt
```

This is more appropriate now I believe.
