### PR TITLE
API: nvim_get_commands

### LINKED ISSUE #7833: API: nvim_get_commands()
- `nvim --version`: v0.2.3-384-g7c4bb23ff
- Vim (version: ) behaves differently? No
- Operating system/version: Linux
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
:command

```

### Actual behaviour

The output is misaligned

### Expected behaviour

A clean output since it exposes all the API's! Is there any ideas to make this better? It is a cosmetic issue but something that needs to be improved.

### PR DESCRIPTION
**Pull request by justinmk**
Rebase #8060 with some changes:

- Always return all keys, with at least NIL value.
- Require `opts` param to be `{"builtin":false}`
- Validate `opts` param
- Support more attributes: `-bang`, `-bar`, `-register`

closes #7833
ref #8029

### CODE REVIEW

File: src/nvim/api/buffer.c [hunk 1]
```diff
@@ -478,6 +479,44 @@ ArrayOf(Dictionary) nvim_buf_get_keymap(Buffer buffer, String mode, Error *err)
   return keymap_array(mode, buf);
 }
 
+/// Gets a list of maps describing buffer-local |user-commands|.
+///
+/// @param  buffer  Buffer handle.
+/// @param  opts  Optional parameters. Currently only supports
```
Comment (bfredl) [inline src/nvim/api/buffer.c]: Buffer commands are never builtin.  Could accept `builtin=False` as incident of implementation (as implementations are shared), but there is no point to document it as an option here.

**Comment by justinmk** [comment]
Actually why should nvim_get_commands return a list? Wouldn't a dictionary make sense?

**Comment by bfredl** [comment]
> Actually why should nvim_get_commands return a list? Wouldn't a dictionary make sense?

I suppose it does. I always wondered why `api_info().functions` is not a dict, it is not like order matters or something.

> Same question for nvim_get_keymap() ...

But here we run into a problem as mappings are not necessary unique. There might be the same LHS for different mapping modes, including overlapping ones.

File: src/nvim/api/buffer.c [hunk 2]
```diff
@@ -478,6 +478,46 @@ ArrayOf(Dictionary) nvim_buf_get_keymap(Buffer buffer, String mode, Error *err)
...
+Dictionary nvim_buf_get_commands(Buffer buffer, Dictionary opts, Error *err)
+  FUNC_API_SINCE(4)
+{
+  bool global = (buffer == -1);
+  bool builtin = false;
+
+  for (size_t i = 0; i < opts.size; i++) {
+    String k = opts.items[i].key;
+    Object v = opts.items[i].value;
+    if (global && !strequal("builtin", k.data)) {
```
Comment (bfredl) [inline src/nvim/api/buffer.c]: Not sure this is correct. If not `global` we don't check options at all?
