### PR TITLE
fix(ui2): start treesitter after deleting cmdline buffer

### LINKED ISSUE #36245: extui: treesitter highlighting don't work after `:bwipe`
### Problem

`nvim --clean +"lua require('vim._extui').enable{}" +'call nvim_input(":%bw!<cr>")'`
Then treesitter hl don't work in cmd window.

### Expected behavior

Treesitter hl work after `:bwipe`.

### Nvim version (nvim -v)

master

### Operating system/version

linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

built from source

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Treesitter is not started in new cmdline buffer after deletion.
Solution: Start treesitter when highlighter buffer no longer matches.

Fix #36245

### CODE REVIEW

File: test/functional/ui/cmdline2_spec.lua [hunk 1]
```diff
@@ -97,4 +97,13 @@ describe('cmdline2', function()
       ^                                                     |
     ]])
   end)
+
+  it('highlights after deleting buffer', function()
+    feed(':%bw!<CR>:call foo()')
```
Comment (justinmk) [inline test/functional/ui/cmdline2_spec.lua:102]: Note: it's easy for `feed()` to silently do nothing , then the test "passes" accidentally. So it's always a good idea to check that it actually did something, e.g. in this case maybe check that buffer X was actually deleted.

Comment (luukvbaal) [reply test/functional/ui/cmdline2_spec.lua:102]: I don't see how the expected screen state could occur accidentally.
