### PR TITLE
fix(winblend): treat braille blank (\u2800) as whitespace #32741

### LINKED ISSUE #32254: winblend does not display text behind blank unicode characters other than 0x20 ascii space
### Problem

I am encountering an issue which was made clear when trying to use winblend with the Isrothy/neominimap plugin but extends beyond that small usecase.

The plugin uses unicode braille characters to display the structure of text in the file in a smaller footprint. Fully empty space in the minimap is handled not using the ascii space character, but \u2800 (an empty braille character).

It seems the color blending logic that decides whether to show the character behind the floating window or the character on the floating window itself appears to be checking the floating window's character at the position against general whitespace but not considering more obscure empty characters.

I haven't looked at the code but given that tabs are also handled at expected (showing the character in the window below), I would hazard a guess as to there being a whitespace chars list or some sort of regex. Would it be possible to add unicode clear characters to this list?

### Steps to reproduce

Fill a text file with unicode \u2800
Fill another file with text
enable winblend for telescope windows
view the preview for the unicode text file in telescope above the other file
observe that the unicode character, although empty, overrides the character in the file below the telescope window.

Image 

### Expected behavior

Image

### Nvim version (nvim -v)

v0.10.2

### Vim (not Nvim) behaves the same?

N / A - winblend is a neovim only feature

### Operating system/version

Archlinux

### Terminal name/version

xterm

### $TERM environment variable

xterm-256color

### Installation

Arch User Repository (AUR)

### PR DESCRIPTION
**Pull request by SkohTV**
fix(winblend): add \u2800 as blank unicode character

Problem:
Winblend does not display text behind blank unicode characters other than 0x20 ascii space
Fix #32254

Solution:
In `ui_compositor.c` -> `compose_line()` make variable `thru` be true for either 0x20 or 0x80A0E2 (utf8 of \u2800)

~~I'm not really familiar with the codebase, so I think this solution could not work for big or small endian (see `schar_from_ascii` implementation)~~ (edit: fixed)
I'd love any feedback on how to go further

### CODE REVIEW

**Comment by zeertzjq** [comment]
Use `schar_from_char()` instead

**Comment by SkohTV** [comment]
Should be all good
Anything else or it can be merged ?

**Comment by SkohTV** [comment]
Seems like somebody else proposed another more complete fix : #32761 
Should this PR be closed without merge in favor of the other ?

**Comment by clason** [comment]
That is a much more intrusive (and questionable) approach, so let's keep this open.

Please have a bit of patience until one of the experts (which are few and very busy) has time to look at this in detail. Open source is a marathon, not a sprint.

**Comment by justinmk** [comment]
that lint failure looks like something that was resolved awhile ago, try rebasing

**Comment by SkohTV** [comment]
All green :+1: 
Should I also write a test or is it overkill for such little change ?

**Comment by justinmk** [comment]
should be possible to modify an existing 'winblend' test to add this char in the test.

File: test/functional/ui/float_spec.lua [hunk 1]
```diff
@@ -7947,7 +7947,7 @@ describe('float window', function()
         qui officia deserunt mollit anim id est
         laborum.]])
       local buf = api.nvim_create_buf(false,false)
-      api.nvim_buf_set_lines(buf, 0, -1, true, {"test", "", "popup    text"})
+      api.nvim_buf_set_lines(buf, 0, -1, true, {"test\u{2800}", "", "popup\u{2800}   text"})
```
Comment (justinmk) [inline test/functional/ui/float_spec.lua:7950]: I think the puc-lua CI job is failing because `\u` is a luajit-only feature. try this (byte literals instead of unicode codepoint) (I didn't verify the bytes, this is from AI):

```suggestion
      local braille_blank = "\226\160\128"
      api.nvim_buf_set_lines(buf, 0, -1, true, {"test" .. braille_blank, "", "popup"..braille_blank.."   text"})
```

Comment (clason) [reply test/functional/ui/float_spec.lua:7950]: I would also recommend restricting this to a single test instead of modifying all the tests; that makes isolating failures easier. (Or just copy the simplest one and add the non-space blank.)

Comment (SkohTV) [reply test/functional/ui/float_spec.lua:7950]: Ohhhh, that makes a lot more sense
The result indeed seemed weird to me
I just wanted to run this once more through CI to make sure it wasn't just github acting weird

File: test/functional/ui/float_spec.lua [hunk 2]
```diff
@@ -8020,6 +8021,45 @@ describe('float window', function()
...
+          laborum^.                                          |
+        ## grid 3
+                                                            |
+        ## grid 4
+          {9:test]] .. braille_blank .. [[          }|
+          {9:               }|
+          {9:popup]] .. braille_blank .. [[   text  }|
+        ]], float_pos={[4] = {1001, "NW", 1, 2, 5, true, 50, 1, 2, 5}}, unchanged=true}
+      else
+        screen:expect([[
```
Comment (justinmk) [inline test/functional/ui/float_spec.lua:8049]: this case doesn't test the char?

is there any way to make the test that you added, less verbose? this is a lot of code just to test a single char.

Comment (SkohTV) [reply test/functional/ui/float_spec.lua:8049]: It's on purpose
This case is for when the windows overlap, so we **don't** render the `\u2800` but we render the character underneath (because winblend > 0)

I agree the solution is verbose, but so are all the tests for winblend, so I'm not sure we can make it less verbose without refactoring some parts of the other tests
