### PR TITLE
fix(terminal): scrollback delete lines immediately

### LINKED ISSUE #11811: :terminal "set scrollback=x" is ignored if reset before redraw
- `nvim --version`: 0.4.3, also tested on v0.5.0-353-g3051342f9
- `vim -u DEFAULTS` (version: ) behaves differently? - no
- Operating system/version: Manjaro Linux / 18.1.5
- Terminal name/version: alacritty 0.4.1-dev (d774c7f3)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:term
a
for i in $(seq 0 1000); echo $i<CR>
\<C-\>\<C-n>:setl scrollback=0<CR>
gg 
```

### Actual behaviour

You scroll to the line 1 

### Expected behaviour

You scroll to the first line that's visible on screen (e.g. 900) and no further because scrollback is yet disabled and lines from it should be gone.

### What is the use case

I'm trying to clear :term buffer as it was shown in this [comment](https://github.com/neovim/neovim/issues/2637#issuecomment-282482441)

### Additional information

`setl scrollback=1` somehow will work after entering and exiting insert mode

### LINKED ISSUE #15477: Terminal-clearing 'scrollback=1' behaviour is flaky and unreliable
### Neovim version (nvim -v)

NVIM v0.5.0

### Vim (not Nvim) behaves the same?

no, no `:terminal` command

### Operating system/version

macOS 11.2.1

### Terminal name/version

Apple Terminal.app; same behaviour in GUI VimR

### $TERM environment variable

`xterm-256color`

### Installation

Homebrew

### How to reproduce the issue

```
nvim -u NORC
:function Terminal_clear()
:  set scrollback=1
:  set scrollback=10000
:  endfunction

:terminal
cat ~/.vimrc
<C-\><C-n>
:call Terminal_clear()
```

### Expected behavior

The stored scrollback (portion of the echoed `.vimrc`) *above* the visible terminal-area should be lost/discarded. The user should be unable to scroll up, anymore.

### Actual behavior

No change in scrollback. The full `.vimrc` is still visible above; nothing was cleared.

### More information
For context, I've spent about the … last two days? trying to write a plugin to solve this problem; researching all the known workarounds, as well as trying absurd new ones.

The above example is how I would *expect* this feature to work. However, it's well- and widely-known to be a bit flaky. The general advice for dealing with this tends to involve `sleep` statments (https://vi.stackexchange.com/questions/21260/how-to-clear-neovim-terminal-buffer, for example; although I've seen various, vaguely-similar cargo-culted solutions elsewhere in my years as a Neovimmer), to give Neovim time to 'realize' that the value has been changed.

```viml
function Terminal_clear()
   set scrollback=1
   sleep 100m
   set scrollback=10000
endfunction

tmap <silent> <D-k> <C-\><C-n>:call Terminal_clear()<CR>
```

Unfortunately, on my machine, even *that* hack doesn't seem to work reliably. I've tried numbers as high as 1000msec; even with a full second between the changes, Neovim fails to 'pick up' the change.

Other additions / magical invocations I've tried, in an attempt to convince Neovim to 'recognize' the change, and Actually Clear the Dang Scrollback:

```viml
function Terminal_clear()
   set scrollback=1
   call feedkeys("\<C-\\>\<C-n>i\<C-l>") " and variations various
   set scrollback=10000
endfunction
```

```viml
function Terminal_clear()
   set scrollback=1
   split
   close
   set scrollback=10000
endfunction
```

None of them are *reliable*; some don't work at all.

Clearly, there's some sort of race-condition at play here. I propose we either:

1. Ensure the changing of `'scrollback'` is an immediate, synchronous operation that *immediately* clears the scrollback, if possible, or;
2. Add a `nvim_term_clear_scrollback()` API to do exactly that, that doesn't depend on two, separate operations overriding eachother, and allowing you to leave `'scrollback'` unchanged at whatever value you prefer.

Hope this was clear; I'll be around for more questions, although I don't think this is really a problem specific to me — it's well-documented elsewhere. I just wanted to make sure it was In The Issue-Tracker, so to speak!

### PR DESCRIPTION
**Pull request by muniter**
* `on_scrollback_option_changed` renamed to `adjust_scrollback`. The
  function name did not correspond to what it was doing. It is
  called unconditionally in every refresh of the terminal
  unrelated if the scrollback option was changed.

* new `on_scrollback_option_changed` function, which calls
  `refresh_terminal`, which then calls `adjust_scrollback`

* `terminal_check_size` is not the appropriate function to call when the
  option is changed since it only conditionally adjusts the scrollback.
  Use the new `on_scrollback_option_changed`

fixes: https://github.com/neovim/neovim/issues/15477 
I think it also fixes: https://github.com/neovim/neovim/issues/11811

### CODE REVIEW

**Comment by muniter** [comment]
CI failure is flakiness: 
* asan:  the `vim.shared` log. 
* OSX CI: no idea, didn't even build

**Comment by zeertzjq** [comment]
```
[----------] Running tests from test/functional/terminal/ex_terminal_spec.lua
[ RUN      ] :terminal does not interrupt Press-ENTER prompt #2748: 58.03 ms OK
==================== File /home/runner/work/neovim/neovim/build/log/ubsan.38723 ====================
= 
= =================================================================
= ==38723==ERROR: LeakSanitizer: detected memory leaks
= 
= Direct leak of 80 byte(s) in 1 object(s) allocated from:
=     #0 0x4deaa3 in realloc ??:?
=     #1 0x1240852 in xrealloc /home/runner/work/neovim/neovim/src/nvim/memory.c:158:15
=     #2 0x1aee5ad in adjust_scrollback /home/runner/work/neovim/neovim/src/nvim/terminal.c:1510:23
=     #3 0x1ae6cf9 in refresh_scrollback /home/runner/work/neovim/neovim/src/nvim/terminal.c:1557:3
=     #4 0x1ad620a in refresh_terminal /home/runner/work/neovim/neovim/src/nvim/terminal.c:1444:3
=     #5 0x1482122 in set_num_option /home/runner/work/neovim/neovim/src/nvim/option.c:4549:7
=     #6 0x146d40a in do_set /home/runner/work/neovim/neovim/src/nvim/option.c:1310:22
=     #7 0x1465ed7 in ex_set /home/runner/work/neovim/neovim/src/nvim/option.c:946:9
=     #8 0xcfcc3a in do_one_cmd /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:2362:5
=     #9 0xcea803 in do_cmdline /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:592:20
=     #10 0x7ab69f in apply_autocmds_group /home/runner/work/neovim/neovim/src/nvim/autocmd.c:1844:5
=     #11 0x7b1b40 in apply_autocmds /home/runner/work/neovim/neovim/src/nvim/autocmd.c:1513:10
=     #12 0x1ad1798 in terminal_open /home/runner/work/neovim/neovim/src/nvim/terminal.c:237:3
=     #13 0x861b54 in channel_terminal_open /home/runner/work/neovim/neovim/src/nvim/channel.c:769:20
=     #14 0xb2ad69 in f_termopen /home/runner/work/neovim/neovim/src/nvim/eval/funcs.c:10804:3
=     #15 0xac8e33 in call_internal_func /home/runner/work/neovim/neovim/src/nvim/eval/funcs.c:196:3
=     #16 0xbe6438 in call_func /home/runner/work/neovim/neovim/src/nvim/eval/userfunc.c:1588:15
=     #17 0xbe226b in get_func_tv /home/runner/work/neovim/neovim/src/nvim/eval/userfunc.c:457:11
=     #18 0xc171a8 in ex_call /home/runner/work/neovim/neovim/src/nvim/eval/userfunc.c:2990:9
=     #19 0xcfcc3a in do_one_cmd /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:2362:5
=     #20 0xcea803 in do_cmdline /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:592:20
=     #21 0x7ab69f in apply_autocmds_group /home/runner/work/neovim/neovim/src/nvim/autocmd.c:1844:5
=     #22 0x7b1be6 in apply_autocmds_exarg /home/runner/work/neovim/neovim/src/nvim/autocmd.c:1530:10
=     #23 0xe7e1b7 in readfile /home/runner/work/neovim/neovim/src/nvim/fileio.c:312:11
=     #24 0x7c1ddd in open_buffer /home/runner/work/neovim/neovim/src/nvim/buffer.c:232:14
=     #25 0xc6e9cf in do_ecmd /home/runner/work/neovim/neovim/src/nvim/ex_cmds.c:2741:24
=     #26 0xd58961 in do_exedit /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:7962:9
=     #27 0xd6ac98 in ex_edit /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:7890:3
=     #28 0xcfcc3a in do_one_cmd /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:2362:5
=     #29 0xcea803 in do_cmdline /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:592:20
= 
= SUMMARY: AddressSanitizer: 80 byte(s) leaked in 1 allocation(s).
====================================================================================================
nan ms test/helpers.lua:257: Found runtime errors in logfile(s): /home/runner/work/neovim/neovim/build/log/ubsan.38723
```

```
[ RUN      ] 'scrollback' option :setlocal in a normal buffer: 39.36 ms OK
==================== File /home/runner/work/neovim/neovim/build/log/ubsan.38944 ====================
= 
= =================================================================
= ==38944==ERROR: LeakSanitizer: detected memory leaks
= 
= Direct leak of 800000 byte(s) in 1 object(s) allocated from:
=     #0 0x4deaa3 in realloc ??:?
=     #1 0x1240852 in xrealloc /home/runner/work/neovim/neovim/src/nvim/memory.c:158:15
=     #2 0x1aee5ad in adjust_scrollback /home/runner/work/neovim/neovim/src/nvim/terminal.c:1510:23
=     #3 0x1ae6cf9 in refresh_scrollback /home/runner/work/neovim/neovim/src/nvim/terminal.c:1557:3
=     #4 0x1ad620a in refresh_terminal /home/runner/work/neovim/neovim/src/nvim/terminal.c:1444:3
=     #5 0x1482122 in set_num_option /home/runner/work/neovim/neovim/src/nvim/option.c:4549:7
=     #6 0x146d40a in do_set /home/runner/work/neovim/neovim/src/nvim/option.c:1310:22
=     #7 0x1465ed7 in ex_set /home/runner/work/neovim/neovim/src/nvim/option.c:946:9
=     #8 0xcfcc3a in do_one_cmd /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:2362:5
=     #9 0xcea803 in do_cmdline /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:592:20
=     #10 0x7ab69f in apply_autocmds_group /home/runner/work/neovim/neovim/src/nvim/autocmd.c:1844:5
=     #11 0x7b1b40 in apply_autocmds /home/runner/work/neovim/neovim/src/nvim/autocmd.c:1513:10
=     #12 0x1ad1798 in terminal_open /home/runner/work/neovim/neovim/src/nvim/terminal.c:237:3
=     #13 0x861b54 in channel_terminal_open /home/runner/work/neovim/neovim/src/nvim/channel.c:769:20
=     #14 0xb2ad69 in f_termopen /home/runner/work/neovim/neovim/src/nvim/eval/funcs.c:10804:3
=     #15 0xac8e33 in call_internal_func /home/runner/work/neovim/neovim/src/nvim/eval/funcs.c:196:3
=     #16 0xbe6438 in call_func /home/runner/work/neovim/neovim/src/nvim/eval/userfunc.c:1588:15
=     #17 0xbe226b in get_func_tv /home/runner/work/neovim/neovim/src/nvim/eval/userfunc.c:457:11
=     #18 0xc171a8 in ex_call /home/runner/work/neovim/neovim/src/nvim/eval/userfunc.c:2990:9
=     #19 0xcfcc3a in do_one_cmd /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:2362:5
=     #20 0xcea803 in do_cmdline /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:592:20
=     #21 0xcf0150 in do_cmdline_cmd /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:279:10
=     #22 0xd88dec in ex_terminal /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:10106:3
=     #23 0xcfcc3a in do_one_cmd /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:2362:5
=     #24 0xcea803 in do_cmdline /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:592:20
=     #25 0xcf0150 in do_cmdline_cmd /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:279:10
=     #26 0x7448a4 in nvim_command /home/runner/work/neovim/neovim/src/nvim/api/vimscript.c:114:3
=     #27 0x67eee2 in handle_nvim_command /home/runner/work/neovim/neovim/build/src/nvim/auto/api/private/dispatch_wrappers.generated.h:7028:3
=     #28 0x12f1c4d in request_event /home/runner/work/neovim/neovim/src/nvim/msgpack_rpc/channel.c:373:19
=     #29 0x1a1234c in state_handle_k_event /home/runner/work/neovim/neovim/src/nvim/state.c:106:7
= 
= SUMMARY: AddressSanitizer: 800000 byte(s) leaked in 1 allocation(s).
====================================================================================================
nan ms test/helpers.lua:257: Found runtime errors in logfile(s): /home/runner/work/neovim/neovim/build/log/ubsan.38944
```

**Comment by muniter** [comment]
Leak is gone. Needed to handle the special case of `scrollback` being set inside `TermOpen` which is before the first allocation of the scrollback buffer.

File: src/nvim/option.c [hunk 1]
```diff
@@ -4544,9 +4544,9 @@ static char *set_num_option(int opt_idx, char_u *varp, long value, char *errbuf,
       check_colorcolumn(wp);
     }
   } else if (pp == &curbuf->b_p_scbk || pp == &p_scbk) {
-    if (curbuf->terminal) {
-      // Force the scrollback to take effect.
-      terminal_check_size(curbuf->terminal);
+    if (curbuf->terminal && value < old_value) {
+      // Force the scrollback to take immediate effect only when decreasing it.
```
Comment (justinmk) [inline src/nvim/option.c:4548]: good idea!

File: src/nvim/terminal.c [hunk 2]
```diff
@@ -233,6 +233,8 @@ Terminal *terminal_open(buf_T *buf, TerminalOptions opts)
   RESET_BINDING(curwin);
   // Reset cursor in current window.
   curwin->w_cursor = (pos_T){ .lnum = 1, .col = 0, .coladd = 0 };
+  // Intitialzie to check if the scrollback buffer has been allocated inside a TermOpen autocmd
```
Comment (justinmk) [inline src/nvim/terminal.c:236]: spellcheck

Comment (justinmk) [inline src/nvim/terminal.c:236]: - spellcheck
- use punctuation in comments, it avoids ambiguity.

```suggestion
  // Initialize in case the scrollback buffer has been allocated inside a TermOpen autocmd.
```

File: src/nvim/terminal.c [hunk 3]
```diff
@@ -1481,8 +1483,17 @@ static void refresh_size(Terminal *term, buf_T *buf)
   term->opts.resize_cb((uint16_t)width, (uint16_t)height, term->opts.data);
 }
 
-/// Adjusts scrollback storage after 'scrollback' option changed.
-static void on_scrollback_option_changed(Terminal *term, buf_T *buf)
+void on_scrollback_option_changed(Terminal *term)
+{
+  // Guard against adjusting a scrollback buffer that doesn't exist yet. Which happens when the user
+  // sets the scrollback option in a TermOpen autocmd.
```
Comment (justinmk) [inline src/nvim/terminal.c:1489]:
```suggestion
  // Scrollback buffer may not exist yet, e.g. if 'scrollback' is set in a TermOpen autocmd.
```

**Review by justinmk — APPROVED** [review]
It's great to see this fixed, thank you! Nice explanation + commit message too.

Another improvement we've considered is to debounce the scrollback management https://github.com/neovim/neovim/pull/8959 (or ideally put it in a ring buffer, but I'm not sure if that can work with libvterm).

**Comment by andrevmatos** [comment]
Thanks! Switched back to nightly specifically because of this, and it works great!
```vim
" <Leader><C-l> in terminal to clear scrollback buffer
nmap <silent> <leader><C-l> :set scrollback=1 \| set scrollback=100000<cr>
tmap <silent> <leader><C-l> <C-\><C-n><leader><C-l>i
```

Any chance for `scrollback` to accept `0` some day, to appease the OCD on the single line left behind?
