### PR TITLE
api: change nvim_command_output behavior

### LINKED ISSUE #7726: nvim_command_output hangs with paged output
The `nvim_command_output` RPC procedure seems to hang when --- I suspect --- output gets paged and requires a `G<Space>` input from the user to continue. Reading the source code I suspect this is indeed the case.

- `nvim --version`:

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/config -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/include
Compiled by brew@Sierra-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2/share/nvim"

Run :checkhealth for more info
```

- Operating system/version: macOS High Sierra
- Terminal name/version: iTerm 3.1.5
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC 
```

:warning: The following commands will block the terminal:

```ex
let id = jobstart(['nvim', '-u', 'NORC', '--embed'], { 'rpc': v:true })
call rpcrequest(id, 'nvim_command_output', 'command');
```

### Actual behaviour

The spawned neovim will hang not responding to the client request.

```c
String nvim_command_output(String str, Error *err)
  FUNC_API_SINCE(1)
{
  do_cmdline_cmd("redir => v:command_output");
  nvim_command(str, err);
  do_cmdline_cmd("redir END");

  if (ERROR_SET(err)) {
    return (String)STRING_INIT;
  }

  return cstr_to_string((char *)get_vim_var_str(VV_COMMAND_OUTPUT));
}
```

### Expected behaviour

A response with the command output as result.

### PR DESCRIPTION
**Pull request by justinmk**
Implement nvim_command_output with `execute({cmd},"silent")`.

Behavior changes:
- does not provoke any hit-enter prompt
- no longer prepends a newline char
- does not capture some noise (like the "[New File]" message, see the
  change to tabnewentered_spec.lua)

Technically ("bug-for-bug") this a breaking change.  But the previous
behavior of nvim_command_output meant that it probably wasn't used for
anything outside of tests.

Also remove the undocumented `v:command_output` variable which was
a hack introduced only for the purposes of nvim_command_output.

closes #7726

### CODE REVIEW

File: src/nvim/api/vim.c [hunk 1]
```diff
@@ -207,18 +208,38 @@ String nvim_replace_termcodes(String str, Boolean from_part, Boolean do_lt,
...
   FUNC_API_SINCE(1)
 {
-  do_cmdline_cmd("redir => v:command_output");
-  nvim_command(str, err);
-  do_cmdline_cmd("redir END");
+  Array args = ARRAY_DICT_INIT;
+  ADD(args, STRING_OBJ(command));
+  ADD(args, STRING_OBJ(cstr_as_string("silent")));
 
+  Object rv = nvim_call_function(cstr_as_string("execute"), args, err);
```
Comment (bfredl) [inline src/nvim/api/vim.c]: are there much reason to not use `f_execute` directly, or (maybe even better) factor out common implementation function?

File: src/nvim/api/vim.c [hunk 2]
```diff
@@ -207,18 +208,38 @@ String nvim_replace_termcodes(String str, Boolean from_part, Boolean do_lt,
   return cstr_as_string(ptr);
 }
 
-String nvim_command_output(String str, Error *err)
+/// Executes an ex-command and returns its (non-error) output.
+/// Shell |:!| output is not captured.
+///
+/// On parse error: forwards the Vim error; does not update v:errmsg.
+/// On runtime error: forwards the Vim error; does not update v:errmsg.
```
Comment (bfredl) [inline src/nvim/api/vim.c]: Are these two intended to be different? Otherwise can be simplified

File: src/nvim/api/vim.c [hunk 3]
```diff
@@ -207,18 +208,38 @@ String nvim_replace_termcodes(String str, Boolean from_part, Boolean do_lt,
...
+  api_free_array(args);
   if (ERROR_SET(err)) {
+    assert(rv.type == kObjectTypeNil);
     return (String)STRING_INIT;
   }
 
-  return cstr_to_string((char *)get_vim_var_str(VV_COMMAND_OUTPUT));
+  assert(rv.type == kObjectTypeString);
+  // execute() always(?) prepends a newline; remove it.
+  if (rv.data.string.size > 1) {
```
Comment (bfredl) [inline src/nvim/api/vim.c]: This looks like cargo-cult magic. A common implementation will avoid this.

File: src/nvim/api/vim.c (hunk 1 above)
Comment (justinmk) [reply src/nvim/api/vim.c]: One reason is I've already spent too much time on this :)

File: src/nvim/api/vim.c (hunk 3 above)
Comment (justinmk) [reply src/nvim/api/vim.c]: It's "I don't care why, but it's guarded by an assert()".

File: src/nvim/api/vim.c (hunk 2 above)
Comment (justinmk) [reply src/nvim/api/vim.c]: I plan to review all API functions again to nail down the differences.

File: src/nvim/api/vim.c (hunk 1 above)
Comment (justinmk) [reply src/nvim/api/vim.c]: Another reason is `nvim_call_function` is already taking care of the try_start dance, etc.

Comment (bfredl) [reply src/nvim/api/vim.c]: Creating typvals directly is simpler and cleared than first creating API values only to be converted to typvals. So you replaced a meaningful (and standard pattern) dance with a meaningless dance.

File: src/nvim/api/vim.c (hunk 3 above)
Comment (bfredl) [reply src/nvim/api/vim.c]: You can mark it with a TODO if noone cares to fix it right now. In the long run "the behaviour of the first error message inside a capture" doesn't sound like like something we should express uncertainty about, rather it should just do the intended thing directly.

File: src/nvim/api/vim.c (hunk 1 above)
Comment (justinmk) [reply src/nvim/api/vim.c]: It's not clearer to me. And I thought we had planned to use the API internally?

File: src/nvim/api/vim.c (hunk 3 above)
Comment (justinmk) [reply src/nvim/api/vim.c]: The behavior of execute () is vim-compatible so I don't think it can be changed. 

The `assert(...='\n')` below here serves to document the assumption.

File: src/nvim/api/vim.c (hunk 1 above)
Comment (bfredl) [reply src/nvim/api/vim.c]: Calling a vimscript function indirectly to implement an API function is definitely not "using the API internally" (that design pattern would be rather defining `execute()` in terms of an API function)
If one for some reason needs to construct an explicit typval there is no reason to construct an API _value_ and immediately convecting it to typval. This just moves _horizontally_ between different abstractions, at a performance cost, and not across whatever internal/external boundary. Not that performance matters matters in this particular case, but it is an anti-pattern to be avoided. ( i e "performance as a consequence of doing things right" and not an optimization)

File: src/nvim/api/vim.c (hunk 3 above)
Comment (bfredl) [reply src/nvim/api/vim.c]: The behavior of `execute()` is already configurable, it wouldn`t be strange for a common implementation to also have this as a flag.

I might look into the relevant parts anyway when revisiting #7466 (which in some sense is `command_output` on steroids, but continuously). If we find a better way to treat newlines, it wouldn't be completely unrealistic for vim to also implement it? (either behind a new `silent` value, or change the default on the same theory of not bug-for-bug compatibility).

File: src/nvim/api/vim.c (hunk 1 above)
Comment (ZyX-I) [reply src/nvim/api/vim.c]: I agree, it would be cleaner to make `f_execute` call API `nvim_command_output()` and not the other way around. Though given how “much” code is actually needed I would rather go with calling `do_cmdline` directly with a custom `LineGetter`: basically you need

```

{
  garray_T *const save_capture_ga = &capture_ga;
  garray_T capture_local;
  ga_init(&capture_local, 1, 80);
  capture_ga = &capture_local;
  try_start();
  do_cmdline(NULL, get_string_line, &string,
              DOCMD_NOWAIT|DOCMD_VERBOSE|DOCMD_REPEAT|DOCMD_KEYTYPED);
  try_end(&err);
  Object ret = STRING_OBJ(cstr_as_string(capture_local.ga_data));
  capture_ga = save_capture_ga;
  return ret;
}
```

BTW, `f_execute` actually needs neither `vim_strsave()` nor `ga_clear()`, that is only useless waste of time.

Comment (ZyX-I) [reply src/nvim/api/vim.c]: Plus actual get_string_line, but that is not hard either.

Comment (bfredl) [reply src/nvim/api/vim.c]: @ZyX-I if we go this route, it might make sense to define `nvim_source` which sources an API list using custom reader and also has output/error handling controlled by parameter.

Comment (justinmk) [reply src/nvim/api/vim.c]: @ZyX-I Why is `get_string_line` variant needed? `nvim_command_output` only accepts String and returns String, so I guess `do_cmdline_cmd(command.data)` should be enough.

**Comment by justinmk** [comment]
Updated with `capture_ga` implementation.

**Comment by justinmk** [comment]
travis macOS failure is unrelated. Looks like `uv__stream_connect` is called during teardown, @bfredl perhaps we should check `exiting` somewhere?

```
[ RUN      ] server -> client connecting to another (peer) nvim via ipv6 address: FAIL
...ovim/neovim/test/functional/api/server_requests_spec.lua:278: Expected objects to be the same.
Passed in:
(boolean) false
Expected:
(boolean) true
stack traceback:
	...ovim/neovim/test/functional/api/server_requests_spec.lua:278: in function 'connect_test'
	...ovim/neovim/test/functional/api/server_requests_spec.lua:329: in function <...ovim/neovim/test/functional/api/server_requests_spec.lua:320>
[ RUN      ] server -> client connecting to another (peer) nvim via hostname: 79.01 ms OK
========================= Core file /cores/core.19381 =========================
(lldb) target create "build/bin/nvim" --core "/cores/core.19381"
warning: (x86_64) /cores/core.19381 load command 73 LC_SEGMENT_64 has a fileoff + filesize (0x2742f000) that extends beyond the end of the file (0x2742e000), the segment will be truncated to match
warning: (x86_64) /cores/core.19381 load command 74 LC_SEGMENT_64 has a fileoff (0x2742f000) that extends beyond the end of the file (0x2742e000), ignoring this section
Core file '/cores/core.19381' (x86_64) was loaded.
(lldb) bt all
* thread #1: tid = 0x0000, 0x000000010796e584 nvim`uv__stream_io [inlined] uv__stream_connect + 156 at stream.c:1365, stop reason = signal SIGSTOP
  * frame #0: 0x000000010796e584 nvim`uv__stream_io [inlined] uv__stream_connect + 156 at stream.c:1365
    frame #1: 0x000000010796e4e8 nvim`uv__stream_io(loop=0x0000000000000014, w=<unavailable>, events=130865184) + 296 at stream.c:1289
    frame #2: 0x0000000107976942 nvim`uv__io_poll(loop=0x0000000107a9c5e8, timeout=<unavailable>) + 1538 at kqueue.c:307
    frame #3: 0x0000000107965cf8 nvim`uv_run(loop=0x0000000107a9c5e8, mode=UV_RUN_DEFAULT) + 456 at core.c:359
    frame #4: 0x000000010771db61 nvim`loop_close(loop=0x0000000107a9c5e8, wait=true) + 193 at loop.c:123
    frame #5: 0x00000001077bd224 nvim`event_teardown + 116 at main.c:178
    frame #6: 0x0000000107847bf1 nvim`mch_exit(r=0) + 49 at os_unix.c:144
    frame #7: 0x00000001077fbb43 nvim`exit_event(argv=0x00007fff585a0418) + 35 at channel.c:539
    frame #8: 0x000000010771e6c2 nvim`multiqueue_process_events(this=0x0000000007c18150) + 162 at multiqueue.c:150
    frame #9: 0x000000010771d538 nvim`loop_poll_events(loop=0x0000000107a9c5e8, ms=4000) + 248 at loop.c:63
    frame #10: 0x0000000107844367 nvim`input_poll(ms=4000) + 231 at input.c:349
    frame #11: 0x0000000107843330 nvim`inbuf_poll(ms=4000) + 32 at input.c:372
    frame #12: 0x0000000107843205 nvim`os_inchar(buf=0x0000000000000000, maxlen=0, ms=-1, tb_change_cnt=0) + 149 at input.c:110
    frame #13: 0x00000001078f0005 nvim`state_enter(s=0x00007fff585a0558) + 229 at state.c:55
    frame #14: 0x0000000107801127 nvim`normal_enter(cmdwin=false, noexmode=false) + 167 at normal.c:466
    frame #15: 0x00000001077bdeea nvim`main(argc=9, argv=0x00007fff585a0828) + 2666 at main.c:572
    frame #16: 0x00007fff8e4555ad libdyld.dylib`start + 1
    frame #17: 0x00007fff8e4555ad libdyld.dylib`start + 1
Tests covered by this check: 1
./test/helpers.lua:238: crash detected (see above)
stack traceback:
	./test/helpers.lua:238: in function 'check_cores'
	./test/functional/helpers.lua:752: in function <./test/functional/helpers.lua:747>
```

**Comment by bfredl** [comment]
Is `uv__stream_connect` really called? Is it not inlining that confuses the asm address inside `uv__stream_io`?

**Comment by bfredl** [comment]
Also it does not show the error, but I suppose segfault or use-after-free. One of the cases that would benefit from ASAN in libuv.
Let's first see if it reproduces with/after #7813 .
