### PR TITLE
fix(pack): account for Git's "insteadOf" in `:checkhealth`

### LINKED ISSUE #38387: `vim.pack`: recognize git aliases while doing `:checkhealth`
### Problem

Currently, `vim.pack` lockfile health checks don't recognize git `insteadOf` aliases as the same source as the expanded ones.
Image

### Expected behavior

Either implement git alias expansion here or maybe remove the check altogether? I don't know what would be better, honestly

### PR DESCRIPTION
**Pull request by echasnovski**
Problem: It is possible (and documented in `:h vim.pack`) that plugin's
  `src` uses "insteadOf" Git config. In that case comparing it directly
  to repo's `origin` will error.

Solution: Add extra check that lockfile's `src` is not equal to repo's
  `origin` when taking Git's "insteadOf" into account.

  However, still report the original lockfile's `src` in the
  `:checkhealth` output, as it seems to be a clearer indication of what
  actually is wrong.

---

Fix #38387

### CODE REVIEW

File: runtime/lua/vim/pack/health.lua [hunk 1]
```diff
@@ -137,12 +137,16 @@ local function check_plugin_lock_data(plug_name, lock_data)
...
   elseif lock_data.src ~= origin then
-    health.error(
-      ('Plugin %s has not expected source\n'):format(name_str)
-        .. ('Expected: %s\nActual:   %s\n'):format(lock_data.src, origin)
-        .. 'Delete `src` lockfile entry (do not create trailing comma) and '
-        .. 'restart Nvim to regenerate lockfile data'
-    )
+    -- Check if lockfile source relies on "insteadOf" Git config
+    local ok, src_resolved = git_cmd({ 'ls-remote', '--get-url', lock_data.src }, plug_path)
+    if not (ok and src_resolved == origin) then
```
Comment (arkriny) [inline runtime/lua/vim/pack/health.lua:142]: The code above calls `failed_git_cmd()` if the command fails. Shouldn't it be the same here? However, on my machine, `git ls-remote --get-url` only fails if no argument is provided and works even outside a git repository. Might it be better to `assert(ok)` here then?

File: runtime/lua/vim/pack/health.lua [hunk 2]
```diff
@@ -137,12 +137,16 @@ local function check_plugin_lock_data(plug_name, lock_data)
...
+      health.error(
+        ('Plugin %s has not expected source\n'):format(name_str)
+          .. ('Expected: %s\nActual:   %s\n'):format(lock_data.src, origin)
+          .. 'Delete `src` lockfile entry (do not create trailing comma) and '
+          .. 'restart Nvim to regenerate lockfile data'
+      )
+    end
     return false
```
Comment (arkriny) [inline runtime/lua/vim/pack/health.lua]:
```suggestion
      health.error(
        ('Plugin %s has not expected source\n'):format(name_str)
          .. ('Expected: %s\nActual:   %s\n'):format(lock_data.src, origin)
          .. 'Delete `src` lockfile entry (do not create trailing comma) and '
          .. 'restart Nvim to regenerate lockfile data'
      )
      return false
    end
```



Currently `health.ok('')` on L183 does not get called. Fall through to `return true` at the end if the resolved source matches.

Comment (echasnovski) [reply runtime/lua/vim/pack/health.lua]: Thanks, missed that!

File: runtime/lua/vim/pack/health.lua (hunk 1 above)
Comment (echasnovski) [reply runtime/lua/vim/pack/health.lua:142]: I don't think anything extra is needed here. The `failed_git_cmd()` is for the Git operation known to pass. Here the nature of `lock_data.src` is only know to be a string and doing `assert(ok)` will error if that string is empty. However, it should be reported as a regular `:checkhealth` error from below.
