### PR TITLE
fix(lsp): handle adjacent snippet tabstops

### LINKED ISSUE #25896: Snippet jumping can not recognize directly adjacent tabstops
### Problem

If snippet contains something like `$1$2`, then jumping forward doesn't recognize that it should change the tabstop.

### Steps to reproduce

1. Create the following config file:
```lua
vim.keymap.set('i', '<C-l>', function() vim.snippet.jump(1) end)
vim.keymap.set('i', '<C-e>', function() vim.snippet.expand('for i=1,${1:to}${2:,step} do\n\t$3\nend') end)
```
2. Start Neovim with `--clean` and this config file.
3. Start Insert mode and press <C-e> to expand the snippet.
4. Type `aaa`.
5. Press `<C-l>`. This is expected to stay in place, but it jumps to the start of the first tabstop. Typing any text afterwards removes both previously entered text (`aaa`) and placeholder for the target tabstop.

### Expected behavior

Select only the placeholder for second (target) tabstop in Select mode.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1466+gec66a95fb-dirty

### Vim (not Nvim) behaves the same?

No

### Operating system/version

EndeavourOS Linux x86_64 (6.5.9-arch2-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

From source

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #25896

### CODE REVIEW

**Comment by MariaSolOs** [comment]
Ehhh idk what's up with the tests, why is `sleep` undefined in some cases?

**Comment by MariaSolOs** [comment]
> Because you never assigned any value to it?

I did
https://github.com/neovim/neovim/blob/066fa77a964f5effcb26bfda243337bf027f0175/test/functional/lua/snippet_spec.lua#L10

**Comment by zeertzjq** [comment]
Oh, you need a rebase.

File: test/functional/lua/snippet_spec.lua [hunk 1]
```diff
@@ -216,4 +216,15 @@ describe('vim.snippet', function()
...
   end)
+
+  it('jumps through adjacent tabstops', function ()
+    test_expand_success(
+    { 'for i=1,${1:to}${2:,step} do\n\t$3\nend' },
+    { 'for i=1,to,step do', '\t', 'end' })
+    sleep(10)
+    feed('10')
+    feed('<Tab>')
+    feed(',2')
```
Comment (zeertzjq) [inline test/functional/lua/snippet_spec.lua:227]:
```suggestion
    poke_eventloop()
    feed('10')
    poke_eventloop()
    feed('<Tab>')
    poke_eventloop()
    feed(',2')
```

Comment (MariaSolOs) [reply test/functional/lua/snippet_spec.lua:227]: Could you please explain the difference between `sleep` and `poke_eventloop`?

Comment (zeertzjq) [reply test/functional/lua/snippet_spec.lua]: - `sleep()` uses a hard-coded timeout.
- `poke_eventloop()` wait for the next iteration of the loop in `state_enter()`

Comment (zeertzjq) [reply test/functional/lua/snippet_spec.lua]: And... `poke_eventloop()` is needed after the `<Tab>` because input is queued, but it is not needed after `test_expand_success()` because `exec_lua()` doesn't return until the code is fully executed.

Comment (MariaSolOs) [reply test/functional/lua/snippet_spec.lua]: Got it, thanks for explaining!

File: test/functional/lua/snippet_spec.lua [hunk 2]
```diff
@@ -216,4 +216,15 @@ describe('vim.snippet', function()
     feed('foo')
     eq({ 'public function foo() {', '\t', '}' }, buf_lines(0))
   end)
+
+  it('jumps through adjacent tabstops', function ()
```
Comment (glepnir) [inline test/functional/lua/snippet_spec.lua:220]:
```suggestion
  it('jumps through adjacent tabstops', function()
```

File: test/functional/lua/snippet_spec.lua [hunk 3]
```diff
@@ -216,4 +216,15 @@ describe('vim.snippet', function()
...
+    test_expand_success(
+    { 'for i=1,${1:to}${2:,step} do\n\t$3\nend' },
+    { 'for i=1,to,step do', '\t', 'end' })
```
Comment (glepnir) [inline test/functional/lua/snippet_spec.lua:223]:
```suggestion
      { 'for i=1,${1:to}${2:,step} do\n\t$3\nend' },
      { 'for i=1,to,step do', '\t', 'end' }
```
