### PR TITLE
fix(terminal): crash when TermClose deletes other buffers

### LINKED ISSUE #10386: TermClose autocmd can free `curbuf`
- `nvim --version`: NVIM v0.4.0-1191-g740fb337d
- `vim -u DEFAULTS` (version: 8.1) behaves differently? It doesn't have a `TermClose` event
- Operating system/version: Fedora Linux 30
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:autocmd TermClose * bd!
:term
:bd!
```

### Actual behaviour

Memory is corrupted, nvim crashes immediately or soon after

### Expected behaviour

Does something reasonable

### Notes

A few minutes in gdb suggests the problem comes down to `termincal_close()` running autocmds and reentering `do_bufdel`, which is presumably not safe to reenter.

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #10386

#### test(terminal): fix incorrect TermClose test

The test may wipe the wrong buffer if :bdelete switches to another one.

Also remove the builtin TermClose autocommand. It doesn't affect the
tests for now, but still it's better to avoid its interference.

#### fix(terminal): crash when TermClose deletes other buffers

Problem:  Crash when deleting terminal buffer and TermClose deletes
          other buffers.
Solution: Close the terminal after restoring b_nwindows.

#### fix(terminal): crash when TermClose switches back to terminal buffer

Problem:  Crash when deleting terminal buffer and TermClose switches
          back to the terminal buffer.
Solution: Set b_locked_split.

Co-authored-by: Sean Dewar <6256228+seandewar@users.noreply.github.com>

### CODE REVIEW

File: src/nvim/buffer.c [hunk 1]
```diff
@@ -675,6 +671,15 @@ bool close_buffer(win_T *win, buf_T *buf, int action, bool abort_if_last, bool i
 
   buf->b_nwindows = nwindows;
 
+  if (buf->terminal) {
+    buf_close_terminal(buf);
```
Comment (seandewar) [inline src/nvim/buffer.c:676]: I guess this needs `b_locked_split` too.

```vim
let g:b = bufnr()
call nvim_open_term(g:b, {})
au TermClose * ++once execute g:b 'b' | new
bw!
```

Hmm, I also wonder if this should be subject to the same `abort_if_last` and `curwin != the_curwin` checks like the other autocommands above? Should this happen earlier?

Comment (zeertzjq) [reply src/nvim/buffer.c:676]: Wow, `b_nwindows` is 0 even before decrementing it.

Comment (seandewar) [reply src/nvim/buffer.c:676]: Ugh, looks like even with `b_locked_split` set, this is still a UAF if you use `:sbuffer` instead:

```vim
let g:b = bufnr()
call nvim_open_term(g:b, {})
au TermClose * ++once execute g:b 'sb' | wincmd p
bw!
```

I think it's because I screwed up the condition in `do_buffer_ext`:
https://github.com/neovim/neovim/blob/ef522420f2f56f1d47ed057b0b08e14a22a049c6/src/nvim/buffer.c#L1332-L1343

I think this needs to also check `b_locked_split` if `action == DOBUF_SPLIT` (regardless of whether `buf != curbuf` in that case). Vim'll also be affected, I think. :see_no_evil:

Comment (zeertzjq) [reply src/nvim/buffer.c:676]: Added another commit.

**Review by seandewar — APPROVED** [review]
I think it's OK.

It does mean that TermClose may change windows after `close_buffer` restores `the_curwin`, but before `buf_freeall`; I dunno if that's a concern.

**Comment by zeertzjq** [comment]
> It does mean that TermClose may change windows after `close_buffer` restores `the_curwin`, but before `buf_freeall`; I dunno if that's a concern.

I'm not sure about that either. Currently `close_buffer()` ignores 'bufhidden' for terminal buffers, so `terminal_close()` is never called during `:edit`.

**Comment by zeertzjq** [comment]
> > It does mean that TermClose may change windows after `close_buffer` restores `the_curwin`, but before `buf_freeall`; I dunno if that's a concern.
> 
> I'm not sure about that either. Currently `close_buffer()` ignores 'bufhidden' for terminal buffers, so `terminal_close()` is never called during `:edit`.

With #37261 that won't be a problem.
