### PR TITLE
[RFC] save and restore clipboard batch status when entering cmdline window

### LINKED ISSUE #5544: Yanking inside cmdwin doesn't respect 'clipboard'
- `nvim --version`:

```
NVIM v0.2.0-1-g242c3d5
Build type: Dev
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/pkgbuild-0/neovim-git/src/neovim-git/build/config -I/tmp/pkgbuild-0/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/pkgbuild-0/neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/pkgbuild-0/neovim-git/src/neovim-git/build/include
Compiled by root@bianca

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: 8.0 Included patches: 1-46) behaves differently? Yes
- Operating system/version: Linux (Arch – rolling release)
- Terminal name/version: termite
- `$TERM`: xterm-termite
### Actual behaviour

Yanking with `clipboard=unnamedplus` inside a command-line window doesn't yank to the `+` register
### Expected behaviour

Yanking with `clipboard=unnamedplus` inside a command-line window yanks to the `+` register
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set clipboard=unnamedplus
q:
yy
:registers
```

Inside the command-line window returns in:

```
:echo v:register
+
```

### PR DESCRIPTION
**Pull request by bfredl**
fixes #5544.

Quick fix, another solution would be to completely rewrite it to always to the unnamed yank just before going into blocking. But the proper solution would be to reimplement slow clipboard providers in lua. "some day" I will look into that for X11 again.

### CODE REVIEW

**Comment by bfredl** [comment]
I think it is ready. Test failure looks unrelated.

File: src/nvim/ex_getln.c [hunk 1]
```diff
@@ -5714,6 +5714,7 @@ static int ex_window(void)
 
   i = RedrawingDisabled;
   RedrawingDisabled = 0;
+  int save_count = save_batch_changes();
```
Comment (justinmk) [inline src/nvim/ex_getln.c]: can this have a less generic name? e.g. `save_batch_count`

File: src/nvim/ops.c [hunk 2]
```diff
@@ -5767,12 +5766,36 @@ void end_batch_changes(void)
   }
   clipboard_delay_update = false;
   if (clipboard_needs_update) {
+    // must be wir
```
Comment (justinmk) [inline src/nvim/ops.c]: what is "wir"?

**Comment by bfredl** [comment]
updated.

**Review by justinmk — APPROVED** [review]
