### PR TITLE
Treat unmapped ALT/META as ESC+c in all modes

### LINKED ISSUE #10132: Meta-chords behaves inconsistently in modes
### Version/platform info

- NVIM v0.3.7
- Operating system: GNU/Linux
- Terminal name: xterm

### Steps to reproduce using `nvim -u NORC`

1. Open neovim with `nvim -u NORC` in xterm
2. Press `i` to go to insert mode
3. Press Alt-o
4. Press `:` to go to command mode
5. Press Alt-o

### Actual behaviour

When pressing Alt-o in insert mode the command behaves as if `<Esc>o` was pressed when Alt-o is unmapped. It leaves insert mode and opens a new line.

When pressing Alt-o in command-line mode the command behaves as if `o` was pressed when Alt-o is unmapped. It only inserts `o`. When pressing Alt-o in visual and normal-mode it behaves like command-mode and gets treated as only `o` when Alt-o is unmapped.

### Expected behaviour

In Vim the behavior is that Alt-o is always treated as if `<Esc>o` was pressed when Alt-o is unmapped. So when pressing Alt-o command-line mode it should return to normal mode and open a new line.

A behavior which deviates from insert-mode but might be more convenient than the default Vim behavior is that Alt-*char* should be treated a no-operation unless Alt-*char* is pressed. Accidentally pressing the wrong Alt-*char* chord can be frustrating because it changes modes or aborts something.

The decision to have Alt-*char* be treated as `<Esc>char` when Alt-*char* is unmapped was taken in #8213. It seems like there were valid reasons to have it be handled that way. Because that decision has already been made I think the behavior should be changed so it gets treated like `<Esc>char` in all modes, which would make the behavior consistent and  improve compatibility with Vim.

### Why this is a problem

It is inconsistent when keycodes behaves differently from mode to mode. This can cause a lot of confusion when writing mappings. For example, the mapping `<Esc>f` can be triggered in insert-mode using Alt-F, but the mapping `<Esc>f` cannot be triggered using Alt-F in normal, command-line, or visual-mode. I ran into this when developing a plugin, and after some head-scratching and investigating, I found this issue.

### PR DESCRIPTION
**Pull request by godlygeek**
In #8226 `<A-x>` and `<M-x>` were changed to behave like `<Esc>x` in insert
mode when no mapping exists. This commit backs out that change and
replaces it with a more general one that makes unmapped ALT and META
keypresses as `<Esc>+char` in all modes. This fixes an unnecessary and
confusing inconsistency between modes.

Closes #10132

### CODE REVIEW

File: src/nvim/getchar.c [hunk 1]
```diff
@@ -1528,6 +1528,17 @@ int vgetc(void)
         c = utf_ptr2char(buf);
       }
 
+      // If mappings are enabled (i.e., not Ctrl-v) and the user directly typed
+      // something with a meta- or alt- modifier that was not mapped, interpret
+      // <M-x> as <Esc>x rather than as an unbound meta keypress.
```
Comment (jamessan) [inline src/nvim/getchar.c:1533]: Would be good to keep the reference to the original discussion here.

**Review by jamessan — APPROVED** [review]

**Comment by jamessan** [comment]
Looks like this might also address #7972.

---
👋🏻 godlygeek, long time no see. :)

File: src/nvim/getchar.c (hunk 1 above)
Comment (godlygeek) [reply src/nvim/getchar.c:1533]: Good point, I'll add it.

**Comment by godlygeek** [comment]
> 👋🏻 godlygeek, long time no see. :)

Fancy meeting you here!  😀 

> Looks like this might also address #7972.

Want a reference to both issues in the source, or just reference #8213 and let them click around to different linked issues from inside GitHub?

Also, I noticed that `:help vim_diff` contains:

`  ALT in insert-mode behaves like <Esc> if not mapped. |i_ALT|`

Should I change that to:

`  ALT behaves like <Esc> if not mapped. |i_ALT| |v_ALT| |c_ALT|`

or is that excessive?

**Comment by jamessan** [comment]
> Also, I noticed that `:help vim_diff` contains:
> 
> ` ALT in insert-mode behaves like <Esc> if not mapped. |i_ALT|`
> 
> Should I change that to:
> 
> ` ALT behaves like <Esc> if not mapped. |i_ALT| |v_ALT| |c_ALT|`
> 
> or is that excessive?

Probably good to add it.  Makes it explicit that the difference applies to all modes.

> Want a reference to both issues in the source, or just reference #8213

Just #8213 is fine.

**Comment by godlygeek** [comment]
I've made both of those changes.

**Comment by godlygeek** [comment]
Pretty sure the failing Travis build is a flaky test that my change didn't affect - at least, I can't see how anything I changed could have caused this.
```
[ RUN      ] 'scrollback' option :setlocal in a :terminal buffer: 10047.57 ms FAIL
test/functional/terminal/scrollback_spec.lua:491: retry() attempts: 455
test/helpers.lua:73: bad argument #2 to 'format' (string expected, got table)
stack traceback:
	test/functional/helpers.lua:392: in function 'retry'
	test/functional/terminal/scrollback_spec.lua:491: in function <test/functional/terminal/scrollback_spec.lua:481>
```
