### PR TITLE
Extmarks: send correct buffer events on blockwise paste for nonuniform lines

### LINKED ISSUE #14189: rectangle operations past eol causes problem with treesitter
**Describe the bug**

In a python file with tree-sitter-python enabled.

When doing rectangle selction to the end of line, deleting and pasting it causes this error: ` treesitter/highlighter: Error executing lua: ...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:224: end_col value outside range`

**To Reproduce**

Create a python file with this content: 

```
def a_function():
    program = f"""gggggggggg     sssssssssssssss
gggggggggggggggggggggggg   .     ssssssssssssss
    gggggggggggggggggggggggg     ssssssssssssss

    """
    """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
    return program
```

At `2,34` perform: `<C-v>jj$dp`

see the error appear at end of line 7: `treesitter/highlighter: Error executing lua: ...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:224: end_col value outside range`

**Expected behavior**

No error

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
health#nvim_treesitter#check                                                                                                                                                                                                                 ========================================================================                                                                                                                                                                     ## Installation                                                                                                                                                                                                                                - ERROR: `tree-sitter` executable not found                                                                                                                                                                                                  - OK: `git` executable found.                                                                                                                                                                                                                - OK: `cc` executable found.                                                                                                                                                                                                                                                                                                                                                                                                                                                            ## Parser/Features H L F I                                                                                                                                                                                                                     - cpp            ✓ ✓ ✓ ✓                                                                                                                                                                                                                     - python         ✓ ✓ ✓ ✓                                                                                                                                                                                                                     - c              ✓ ✓ ✓ ✓                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Legend: H[ighlight], L[ocals], F[olds], I[ndents]                                                                                                                                                                                                    +) multiple parsers found, only one will be used                                                                                                                                                                                             x) errors found in the query, try to run :TSUpdate {lang}
</code>
</details>

**Output of `nvim --version`**

<details>
<code>
NVIM v0.5.0-dev+1165-ge5bef5974
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-comm
on -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/h
ome/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az205-228

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
</code>
</details>

### PR DESCRIPTION
**Pull request by chentoast**
Fixes #14189.

Previously, the call to `extmark_splice` assumed that padding spaces were inserted even if they actually weren't.

### CODE REVIEW

File: src/nvim/eval/funcs.c [hunk 1]
```diff
@@ -11299,11 +11300,11 @@ static void f_winrestcmd(typval_T *argvars, typval_T *rettv, FunPtr fptr)
 
   ga_init(&ga, (int)sizeof(char), 70);
   FOR_ALL_WINDOWS_IN_TAB(wp, curtab) {
-    sprintf((char *)buf, "%dresize %d|", winnr, wp->w_height);
+    snprintf((char *)buf, "%dresize %d|", winnr, wp->w_height);
```
Comment (janlazo) [inline src/nvim/eval/funcs.c:11303]: Where is the size?

Comment (chentau) [reply src/nvim/eval/funcs.c]: 😂 whoops... I was fixing the lint and forgot to check if the build compiled

File: src/nvim/ops.c [hunk 2]
```diff
@@ -3177,7 +3178,8 @@ void do_put(int regname, yankreg_T *reg, int dir, long count, int flags)
       // insert the new text
       totlen = (size_t)(count * (yanklen + spaces)
                         + bd.startspaces + bd.endspaces);
-      newp = (char_u *) xmalloc(totlen + oldlen + 1);
+      addcount = (int)totlen + lines_appended;
```
Comment (bfredl) [inline src/nvim/ops.c:3181]: declare new vars in scope: `int addcount = ...`
