### PR TITLE
fix(api): highlight attribute for underline

### LINKED ISSUE #17624: Getting underline attribute from syntax hl group returns empty string instead of '1'
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1194-g24d56116f

### Vim (not Nvim) behaves the same?

no, vim 8.2.4464

### Operating system/version

Linux

### Terminal name/version

Kitty

### $TERM environment variable

xterm-kitty

### Installation

Built from source

### How to reproduce the issue

nvim --clean
:hi UnderlineTest gui=underline
:echo synIDattr(synIDtrans(hlID('UnderlineTest')), 'underline')

### Expected behavior

Expected to get `1` returned.

This also properly works in stable versions of Neovim since 0.5.0.

Figured this issue from the tests in nvim-orgmode: https://github.com/nvim-orgmode/orgmode/runs/5439299419?check_suite_focus=true#step:7:96

Link to line where the test fails: https://github.com/nvim-orgmode/orgmode/blob/master/tests/plenary/colors/colors_spec.lua#L79

### Actual behavior

Getting the empty string.

### PR DESCRIPTION
**Pull request by kchibisov**
This commit fixes regression introduced in c365de1 when checking for
highlight attribute for underline was returning '0' when it was present

Fixes #17624.

--

cc @kristijanhusak @jamessan

### CODE REVIEW

File: test/functional/terminal/highlight_spec.lua [hunk 1]
```diff
@@ -305,10 +305,16 @@ describe('synIDattr()', function()
...
-    eq('1', eval('synIDattr(hlID("Keyword"), "strikethrough", "gui")'))
+  it('returns "1" if group has given highlight attribute', function()
+    local hl_attrs = {
+      'underline', 'underlineline', 'undercurl', 'underdot', 'underdash', 'strikethrough'
+    }
+    for _,hl_attr in ipairs(hl_attrs) do
+      command('highlight Keyword cterm=' .. hl_attr .. ' gui=' .. hl_attr)
+      eq('', eval('synIDattr(hlID("Normal"), "'.. hl_attr .. '")'))
+      eq('1', eval('synIDattr(hlID("Keyword"), "' .. hl_attr .. '")'))
+      eq('1', eval('synIDattr(hlID("Keyword"), "' .. hl_attr .. '", "gui")'))
```
Comment (jamessan) [inline test/functional/terminal/highlight_spec.lua:316]: Adding context to the test is helpful, so we know _which_ attribute is failing if it happens.

```suggestion
      local context = 'using '..hl_attr..' attr'
      command('highlight Keyword cterm=' .. hl_attr .. ' gui=' .. hl_attr)
      eq('', eval('synIDattr(hlID("Normal"), "'.. hl_attr .. '")'), context)
      eq('1', eval('synIDattr(hlID("Keyword"), "' .. hl_attr .. '")'), context)
      eq('1', eval('synIDattr(hlID("Keyword"), "' .. hl_attr .. '", "gui")'), context)
```

Comment (kchibisov) [reply test/functional/terminal/highlight_spec.lua]: Applied.
