### PR TITLE
jobs: child proc must have a separate process-group

### LINKED ISSUE #6530: jobstop not killing processes with SIGKILL
- `nvim --version`: 0.1.7
- Operating system/version: Linux Mint 17.3
- Terminal name/version: Konsole 2.14.2
- `$TERM`: xterm

### Actual behaviour

Calling `jobstop()` on a process which does not respond to SIGTERM will not later send SIGKILL, per `:help jobstop()`.

### Expected behaviour

`jobstop()` should kill the process with effectively `kill -9` after 2 seconds of waiting, in the background.

### Additional Information

I am not certain if this is happening on all machines, or on specific machines, etc. I started getting a few users of my plugin ALE reporting issues with processes hanging around when they are running NeoVim on Mac OSX, and I'm pretty certain `jobstop()` is being called with the job ID. Vim 8 users of the plugin don't seem to be having the same issues. After some experimenting, I was finally able to put together a simple Vim script for reproducing the bug, as far as I'm aware.

I'll create this issue, and see if others can reproduce the same bug. If there is no bug, and there's something or other I can do in my plugin to fix this instead, then I'll be just as happy.

### Steps to reproduce using `nvim -u NORC`

Run these lines of VimL.

```vim
" Run a command which doesn't respond to SIGTERM, and kill it right away.
call jobstop(jobstart('/bin/bash -c ''trap true SIGTERM; sleep 20000000000000'''))
" Wait longer than the 2 second timer for calling SIGKILL
sleep 3
" A PID will be printed here.
echo system('pgrep -f ''sleep 20000000000000''')
```

### PR DESCRIPTION
**Pull request by justinmk**
closes #6530 

- are PTY jobs being killed correctly?
- ~~is #6891 related?~~
- [x] win: iterate through children (`os_proc_tree_kill()`)
- [x] implement new API function: `nvim_get_proc_children()`
- [x] implement new API function: `nvim_get_proc()`
- [x] tests

Didn't fix this common test failure (maybe #7376 ?):

```
TermClose event reports the correct <abuf>: -- Output to stderr:
Vim: Caught deadly signal 'SIGHUP'
Vim: Finished.
CMake Error at /home/travis/build/neovim/neovim/cmake/RunTests.cmake:53 (message):
  Running functional tests failed with error: 1.
...
===============================================================================
NVIM_LOG_FILE: /home/travis/build/neovim/neovim/build/.nvimlog
2018/03/06 08:57:28 ERROR 11479 loop_close:133: uv_loop_close() hang?
[--I] signal   0xa310e8
[-AI] async    0xa30f30
[R--] signal   0xa2a620
```

quickbuild failure is unrelated, `spell_spec.lua` #8102

### CODE REVIEW

**Review by mhinz — APPROVED** [review]

**Comment by mhinz** [comment]
```vim
:let id = jobstart('sleep 30 | sleep 30 | sleep 30')
:call jobstop(id)
```

..finally works as expected after this patch. :+1:

File: src/nvim/os/pty_process_unix.c [hunk 1]
```diff
@@ -145,8 +145,12 @@ void pty_process_teardown(Loop *loop)
   uv_signal_stop(&loop->children_watcher);
 }
 
-static void init_child(PtyProcess *ptyproc) FUNC_ATTR_NONNULL_ALL
+static void init_child(PtyProcess *ptyproc)
+  FUNC_ATTR_NONNULL_ALL  // FUNC_ATTR_NORETURN ?
 {
+  // New session and progress-group. #6530
+  setsid();
```
Comment (oni-link) [inline src/nvim/os/pty_process_unix.c]: Why a new session instead of a new process group? Would `setpgid(0,0);` also do the job?

Comment (bfredl) [reply src/nvim/os/pty_process_unix.c]: Isn't a new session customary in a terminal emulator?

File: src/nvim/event/process.c [hunk 2]
```diff
@@ -249,15 +250,15 @@ static void children_kill_cb(uv_timer_t *handle)
...
     uint64_t elapsed = (now - proc->stopped_time) / 1000000 + 1;
 
     if (elapsed >= KILL_TIMEOUT_MS) {
       int sig = proc->type == kProcessTypePty && elapsed < KILL_TIMEOUT_MS * 2
                     ? SIGTERM
                     : SIGKILL;
-      ILOG("Sending %s to pid %d", sig == SIGTERM ? "SIGTERM" : "SIGKILL",
-           proc->pid);
-      uv_kill(proc->pid, sig);
+      ILOG("sending %s to pid %d", sig == SIGTERM ? "SIGTERM" : "SIGKILL", pid);
```
Comment (oni-link) [inline src/nvim/event/process.c]: pid -> pgid

**Comment by janlazo** [comment]
Will this fix the `invalid channel id` or the exit code for job tests for cat.exe on Windows?

**Comment by justinmk** [comment]
> Will this fix the invalid channel id or the exit code for job tests for cat.exe on Windows?

I wouldn't expect this to fix "invalid channel id". And, I don't think it will change behavior of cat.exe unless cat.exe was running in a shell.

> I'm using jobclose to get exit code 0 because jobstop can cause exit code 1.

We should probably keep that test "pending" then :)

File: src/nvim/os/process.c [hunk 3]
```diff
@@ -0,0 +1,168 @@
...
+  if (rv) {
+    xfree(p_list);
+    return 1;
+  }
+
+  // Collect processes whose parent matches `ppid`.
+  bool exists = false;
+  size_t p_count = len / sizeof(*p_list);
+  for (size_t i = 0; i < p_count; i++) {
+    exists |= (p_list[i].kp_proc.p_pid == ppid);
```
Comment (jamessan) [inline src/nvim/os/process.c]: Shouldn't this be

```c
exists ||= (p_list[i].ki_pid == ppid);
if (p_list[i].ki_ppid == ppid) {
  temp = xrealloc(temp, (*proc_count + 1) * sizeof(*temp));
  temp[*proc_count] = p_list[i].ki_pid;
```

File: src/nvim/os/process.c [hunk 4]
```diff
@@ -0,0 +1,178 @@
...
+  }
+
+#elif defined(__linux__)
+  char proc_p[256] = { 0 };
+  // Collect processes whose parent matches `ppid`.
+  // Rationale: children are defined in thread with same ID of process.
+  snprintf(proc_p, sizeof(proc_p), "/proc/%d/task/%d/children", ppid, ppid);
+  FILE *fp = fopen(proc_p, "r");
+  if (fp == NULL) {
+    return 1;  // Process not found.
```
Comment (oni-link) [inline src/nvim/os/process.c]: I'm missing the `children` entry under `proc`, because of a unset kernel option. Could one fallback to `pgrep -P ppid` or `ps --ppid ppid` in this case?

Comment (justinmk) [reply src/nvim/os/process.c]: @oni-link How does `ps` get this info without the kernel providing an API?

Comment (oni-link) [reply src/nvim/os/process.c]: Perhaps iterating through the entries (processes) under `/proc` and evaluating each entry `status` for `ppid`?

Comment (justinmk) [reply src/nvim/os/process.c]: @oni-link Added a fallback for `pgrep` since it seems to be available on linux and macOS, and hopefully xBSD.

File: src/nvim/lua/vim.lua [hunk 5]
```diff
@@ -1,3 +1,46 @@
...
+  local out = vim.api.nvim_call_function('system', { cmd })
+  local err = vim.api.nvim_get_vvar('shell_error')
+  local args_str = vim.api.nvim_call_function('string', { cmd })
+  if 0 ~= err then
+    error('command failed: '..args_str)
+  end
+  return out
+end
+
+local function systemlist(...)
```
Comment (justinmk) [inline src/nvim/lua/vim.lua]: @neovim/core I'm considering documenting these in `:help lua` as part of the `vim` module. The normal lua idiom would be to return `status, rv` pair, where `status=false` on failure. But I think it's really useful to show the failed command with `error()`. Thoughts?

File: src/nvim/lua/vim.lua [hunk 6]
```diff
@@ -1,3 +1,65 @@
...
+  local out = vim.api.nvim_call_function('system', { cmd })
+  local err = vim.api.nvim_get_vvar('shell_error')
+  local args_str = vim.api.nvim_call_function('string', { cmd })
+  if 0 ~= err then
+    error('command failed: '..args_str)
+  end
+  return out
+end
+
+local function systemlist(cmd)
```
Comment (bfredl) [inline src/nvim/lua/vim.lua]: Do we really want to commit a new system interface that mixes `stdout` and `stderr` togheter per default?

File: src/nvim/lua/vim.lua [hunk 7]
```diff
@@ -1,3 +1,65 @@
+local function system(cmd)
```
Comment (bfredl) [inline src/nvim/lua/vim.lua]: Until we have lua native job control this should probably use `systemlist` (or even better viml job control to distinguish stderr) internally and do a safe conversion to lua binary string, so that this function handles binary data correctly (unlike vimL `system()` where this is impossible)

File: src/nvim/lua/vim.lua (hunk 6 above)
Comment (justinmk) [reply src/nvim/lua/vim.lua]: @bfredl Thanks. I'll keep this internal for now.

File: src/nvim/lua/vim.lua (hunk 7 above)
Comment (teto) [reply src/nvim/lua/vim.lua]: or even remove the function to force using systemlist which is better in every way.

Comment (bfredl) [reply src/nvim/lua/vim.lua]: @teto this is not really true in Lua, the issue is just that vimL system() should not be used to define Lua system()

**Comment by justinmk** [comment]
## todo / future reference

Discussion of `vim.system[list]()` in public Lua module:

- https://github.com/neovim/neovim/pull/8107#discussion_r175254868
- https://github.com/neovim/neovim/pull/8107#discussion_r175254916

**Comment by janlazo** [comment]
Which `ps` is os_proc_info using on Windows?

**Comment by justinmk** [comment]
> Which ps is os_proc_info using on Windows?

On WIN32 it uses the WIN32 API. No ps, no tasklist.

**Comment by janlazo** [comment]
@justinmk `ping -n 1 -w 30000` exits within a second.

**Comment by justinmk** [comment]
@janlazo Gah, I changed that at the last minute to match https://github.com/neovim/neovim/blob/3bf57c117120327930fb39935d1672558f58d148/test/functional/terminal/ex_terminal_spec.lua#L51

I will fix after #8120 , when https://github.com/neovim/neovim/pull/8107/commits/ae409b5042abdbec67305a063cf921ddffcce0c8 can be reverted.

**Comment by janlazo** [comment]
My bad on that commit. I used ping for <= 1 sec. timeout but any program that exits quickly would have sufficed because of how for loops work on cmd.exe. Powershell has a long startup (2-3 sec. to run `exit 4` for `jobwait()` test) so I couldn't use `Start-Sleep -Milliseconds 100`.
