### PR TITLE
[RFC] clipboard: set v:register after startup

### LINKED ISSUE #5697: Setting clipboard+=unnamed, but v:register keep " until first yanked
- `nvim --version`: NVIM v0.2.0-1-g9956bee
- Vim (version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 20 2016 09:29:19)) behaves differently? yes
- Operating system/version: macOS/el capitain(10.11.6)
- Terminal name/version: iTerm2 3.0.12
- `$TERM`: xterm-256color

### Actual behaviour
there is "set clipboard+=unnamed" in _vimrc, but v:register returns `"` until first yanked.
 
### Expected behaviour
v:register returns `*`

### Steps to reproduce using `nvim -u NORC`

In neovim

```
% cat vimrc_test
set clipboard+=unnamed

% nvim -u vimrc_test
:echo v:register
=> returns "
:yy
:echo v:register
=> return *

```

Strangely , `set clipboard` after nvim started, it's works.
```
% nvim -u NORC
:set clipboard+=unnamed
:echo v:register
=> returns *
```

In macvim

```
% /Applications/MacVim.app/Contents/MacOS/Vim -u vimrc_test
:echo v:register
=> returns *
```

### PR DESCRIPTION
**Pull request by bfredl**
Fixes #5697.

Location is the same as in vim, so behavior with regards to VimEnter etc should be the same.

### CODE REVIEW

**Review by mhinz — APPROVED** [review]

**Comment by bfredl** [comment]
And of course it works locally but not on travis...

File: test/functional/clipboard/clipboard_provider_spec.lua [hunk 1]
```diff
@@ -365,6 +365,13 @@ describe('clipboard usage', function()
     end)
   end)
 
+  it('sets v:register after startup', function()
+    clear()
+    eq('"', eval('v:register'))
+    clear("--cmd", "set cb=unnamed")
```
Comment (justinmk) [inline test/functional/clipboard/clipboard_provider_spec.lua]: nitpick: tests should use full option names

**Comment by bfredl** [comment]
(hopefully) fixed the test...
