### PR TITLE
provider: do not incorrectly prefer python2 when python3 is working

### LINKED ISSUE #10758: &pythonx gets set to 2 despite python 2 not working
- `nvim --version`: v0.4.0-1674-gad4eb18e4
- `vim -u DEFAULTS` (version: 8.1.1843) behaves differently? yes
- Operating system/version: Ubuntu 19.04
- Terminal name/version: gnome-terminal 3.32.1 using VTE 0.56.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
python -m pip uninstall neovim pynvim
python3 -m pip install pynvim
nvim -u NORC
:set pyxversion?    " prints 0
:pyx print("hi")
:py3 print("ho")
```

### Actual behaviour

```
E319: No "python" provider found. Run ":checkhealth provider"
ho
```

### Expected behaviour

```
hi
ho
```

### Other notes

The [documentation](https://github.com/neovim/neovim/blob/90e44ecf1144cb32195da00e24d23afb111ea680/runtime/doc/options.txt#L4534-L4537) says:

>         If 'pyxversion' is 0, it is set to 2 or 3 after the first execution of
>         any python2/3 commands or functions.  E.g. :py sets to 2, and :py3
>         sets to 3. :pyx sets it to 3 if Python 3 is available, otherwise sets
>         to 2 if Python 2 is available.

so :pyx is supposed to set pyxversion to 3, since

```
:echo has("python3")
1
:echo has("python")
0
```

Also, if I try :py3 it should set pyxversion to 3, according to the documentation, but you can see this doesn't happen:

```
nvim -u NORC
:set pyxversion?
  pyxversion=0
:py3 print("hi")
:set pyxversion?
  pyxversion=0
:pyx print("hi")
E319: No "python" provider found. Run ":checkhealth provider"
```

### PR DESCRIPTION
**Pull request by bfredl**
fixes #10758.

Not sure if we tested the incorrect behaviour, or if there are no tests.

### CODE REVIEW

**Comment by mhinz** [comment]
Looks like it got ported wrongly: https://github.com/vim/vim/commit/f42dd3c3901ea0ba38e67a616aea9953cae81b8d#diff-28790a430300cd187bda51bd6a014757R3685-R3693

**Comment by blueyed** [comment]
Should have a test probably.

File: test/functional/provider/python3_spec.lua [hunk 1]
```diff
@@ -90,6 +90,11 @@ describe('python3 provider', function()
     eq({1, 2, {['key'] = 'val'}}, eval([[py3eval('[1, 2, {"key": "val"}]')]]))
   end)
 
+  it('pyxeval #10758', function()
```
Comment (bfredl) [inline test/functional/provider/python3_spec.lua]: could check `eq(0, eval([[&pyxversion]]))` as a precondition (setup did not use pyx by accident, or something)
