### PR TITLE
fix(ui): prevent xdg-open subprocess from failing due to closed file descriptors

### LINKED ISSUE #29932: xdg-open doesn't like being run by vim.system
### Problem

When running `xdg-open https://google.com` via `vim.system` nothing seems to happen. But the command outside of nvim and in either zsh or bash seems to work. A summary:
1. (in nvim) `:lua vim.system({'xdg-open', 'https://google.com'}, {text = true, detach = true})` doesn't work - no errors reported, etc.
2. (in nvim) `:! xdg-open https://google.com` doesn't work - no errors
3. (in nvim) `:! xdg-open https://google.com 1>/dev/null 2>&1` *does* work
4. (in nvim) ~`:lua vim.system({'xdg-open', 'https://google.com', '1>/dev/null', '2>&1'}, {text = true, detach = true})` doesn't work, and when examining the output via `...vim.system(...):wait().stderr` it shows "xdg-open: unexpected argument '1>/dev/null' Try 'xdg-open --help' for more information.", which I imagine means I'm not passing `1>/dev/null` etc. to the shell/process correctly?~
**update:** `:lua vim.system({'bash', '-c', 'xdg-open https://google.com 1>/dev/null 2>&1'}, {text = true, detach = true})` does work, albeit with no output
6. (outside of vim) `$ xdg-open https://google.com` works, but notably shows a bunch of "Gtk-WARNING"s etc. in stderr
7. (outside of vim) `$ firefox https://google.com` works, and shows the exact same "Gtk-WARNING"s
8. (in nvim) `:lua vim.system({'firefox', 'https://google.com'}, {text = true, detach = true})` does work, and when examining the output via `...vim.system(...):wait().stderr` it shows the same "Gtk-WARNING"s

I don't quite understand all the internals, but I'm guessing xdg-open returns an exit code before the spawned process writes to stderr, whereas firefox returns an exit code after - and given my naiive understanding about `vim.system` it closes the stdout/stderr pipes once it gets a successful exit code, which causes xdg-open's spawn'ed process to not work?

Oddly enough I put `xdg-open $@ 1>/dev/null 2>&1` in test.sh, and running the following works `:lua vim.system({'bash', 'test.sh', 'https://google.com'}, {text = true, detach = true})` albeit with no output of any kind.

### Steps to reproduce

(in nvim) `:lua vim.system({'xdg-open', 'https://google.com'}, {text = true, detach = true})`

### Expected behavior

Expect browser to open, but nothing happens.

### Neovim version (nvim -v)

v0.11.0-dev

### Vim (not Nvim) behaves the same?

Yes

### Operating system/version

Ubuntu 24.04

### Terminal name/version

kitty 0.32.2

### $TERM environment variable

xterm-kitty

### Installation

sudo apt install neovim

### PR DESCRIPTION
**Pull request by a3ng7n**
Problem: per https://github.com/neovim/neovim/issues/29932#issue-2440957530 when using `vim.ui.open` on linux systems, calls to `xdg-open` return before the subprocess it creates (launching xyz browser, etc.) is done using the file descriptors it's given. As the underlying `vim.system` closes the file descriptors once `xdg-open` returns, this causes the launched subprocess to crash if it attempts to write to stdout or stderr.

Solution: give `xdg-open` /dev/null as the file descriptor for stdout and stderr

Resolves #29932

### CODE REVIEW

File: runtime/lua/vim/ui.lua [hunk 1]
```diff
@@ -155,11 +158,13 @@ function M.open(path)
...
   elseif vim.fn.executable('xdg-open') == 1 then
     cmd = { 'xdg-open', path }
+    opts.stdout = false
+    opts.stderr = false
   else
     return nil, 'vim.ui.open: no handler found (tried: wslview, explorer.exe, xdg-open)'
   end
 
-  return vim.system(cmd, { text = true, detach = true }), nil
+  return vim.system(cmd, opts), nil
```
Comment (lewis6991) [inline runtime/lua/vim/ui.lua:167]: Do we ever need stdout or stderr for this?

**Comment by a3ng7n** [comment]
Hey! sorry to bug you two @lewis6991 @zeertzjq , but just was wondering if I could get another look at this - if it doesn't meet the mark, I understand and I'll close this out

File: runtime/lua/vim/ui.lua [hunk 2]
```diff
@@ -140,6 +140,9 @@ function M.open(path)
   end
 
   local cmd --- @type string[]
+  local opts --- @type { [string]: boolean }
```
Comment (zeertzjq) [inline runtime/lua/vim/ui.lua:143]:
```suggestion
  local opts --- @type vim.SystemOpts
```
