### PR TITLE
fix(vim.system): env=nil passes env=nil to uv.spawn

### LINKED ISSUE #34730: NixOS-specific (?) ENOENT: no such file or directory in gitsigns after 731e616
### Problem

This only happens on my Linux machine running NixOS, and not on a macOS laptop.

Not sure what's the policy for such problems here. Also not sure if this is a problem on a 'normal' linux machine or not. I'm open to offer any help.

So after updating to 731e616 gitsigns stopped working for me as it throws an error on opening each file:
```
vim.schedule callback: ...unwrapped-nightly/share/nvim/runtime/lua/vim/_system.lua:249: ENOENT: no such file or directory
stack traceback:
        [thread: 0x7f0cf87ac348] [C]: in function 'asystem'
        [thread: 0x7f0cf87ac348] ...vimPackages/start/gitsigns.nvim/lua/gitsigns/git/cmd.lua:58: in function 'git_command'
        [thread: 0x7f0cf87ac348] ...imPackages/start/gitsigns.nvim/lua/gitsigns/git/repo.lua:213: in function 'get_info'
        [thread: 0x7f0cf87ac348] ...ck/myNeovimPackages/start/gitsigns.nvim/lua/gitsigns.lua:44: in function 'get_gitdir_and_head'
        [thread: 0x7f0cf87ac348] ...ck/myNeovimPackages/start/gitsigns.nvim/lua/gitsigns.lua:131: in function <...ck/myNeovimPackages/start/gitsigns.nvim/lua/gitsigns.lua:114>
stack traceback:
        [C]: in function 'error'
        ...eovimPackages/start/gitsigns.nvim/lua/gitsigns/async.lua:229: in function '_finish'
        ...eovimPackages/start/gitsigns.nvim/lua/gitsigns/async.lua:322: in function '_resume'
        ...eovimPackages/start/gitsigns.nvim/lua/gitsigns/async.lua:317: in function <...eovimPackages/start/gitsigns.nvim/lua/gitsigns/async.lua:307>
```

### Steps to reproduce

Not sure if this is reproducible on a non-NixOS machine. For sure not on darwin.
Open to any suggestions 

I can 100% reproduce this on my flake https://github.com/konradmalik/neovim-flake. Steps:

- `git clone https://github.com/konradmalik/neovim-flake.git
- checkout the bad commit: `git reset --hard 0db63e776cbcdb221c8fdec538263a74ed94486c`
- build and see the error `nix build && ./result/bin/nvim`
- checkout the good commit which rolls the neovim-src back: `git reset --hard dbe9cf7a876fd31c9a90277e96ba14d451319c83`
- build, run, and see all is ok `nix build && ./result/bin/nvim`

### Expected behavior

should not throw errors

### Nvim version (nvim -v)

731e616

### Vim (not Nvim) behaves the same?

no

### Operating system/version

NixOS

### Terminal name/version

ghostty 1.1.3

### $TERM environment variable

tmux-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by lewis6991**
731e616a79 made it so passing `{env = nil, clear_env = true }` would
pass `{env = {}}` to `vim.uv.spawn`.

However this is not what `clear_env` is (arguably) supposed to do.
If `env=nil` then that implies the uses wants `vim.uv.spawn()` to use
the default environment. Adding `clear_env = true` simply prevents
`NVIM` (the base environment) from being added.

Fixes #34730

### CODE REVIEW

File: test/functional/lua/system_spec.lua [hunk 1]
```diff
@@ -93,6 +93,27 @@ describe('vim.system', function()
         )
       end)
 
+      it('can set environment with clear_env = true and env = nil', function()
+        exec_lua(function()
+          vim.env.TEST = 'TESTVAL'
+        end)
+
+        -- Not passing env with clear_env should not clear the environment
```
Comment (justinmk) [inline test/functional/lua/system_spec.lua:101]: seems unintuitive that `clear_env=true` does not clear the env.

**Comment by justinmk** [comment]
> Adding `clear_env = true` simply prevents `NVIM` (the base environment) from being added.

The current behavior on master is how `jobstart` works, and seems more intuitive. 

But I can understand the rationale, so my comments aren't blockers. Will try to improve the docs.

File: test/functional/lua/system_spec.lua (hunk 1 above)
Comment (lewis6991) [reply test/functional/lua/system_spec.lua:101]: I agree, but there is a real regression that is being fixed here. `clear_env` isn't a good name, but it is documented properly.

**Comment by lewis6991** [comment]
One of the motiviations for `{env = nil, clear_env=true}` behaviour, is to avoid building the env table every time we invoke `vim.system()`.

If we can set `NVIM` into the server environment, that would simplify and optimize things here, and also give more motivation to change the meaning of `clear_env`. Do you think that is possible?

**Comment by justinmk** [comment]
> If we can set `NVIM` into the server environment, that would simplify and optimize things here,

Don't see a way to do that without introducing different problems. Currently if `$NVIM` is defined, it unambiguously means "this process (which may be an Nvim process) is a child of Nvim".

**Comment by lewis6991** [comment]
Hmm ok. For 99% of use cases, I don't think `$NVIM` is useful to have, e.g.: git, shell commands, so being able to avoid building the env table is desirable. Right now the only way to do that is to pass `{env = nil, clear_env = true}`.

**Comment by justinmk** [comment]
> For 99% of use cases, I don't think `$NVIM` is useful to have

Sure, but same for `$TMUX`, `$VIMRUNTIME`, etc. They are there for the 1% where they are really needed.

~~Maybe [`base_env`](https://github.com/neovim/neovim/blob/e91224bfaa043bb85cdfa6394f417e400522ff53/runtime/lua/vim/_system.lua#L197) should never set `$NVIM` when `clear_env=true` ? But *that* would also differ vs `jobstart()`, and I haven't thought through the tradeoff matrix...~~

Let's try this PR as is for now

File: runtime/lua/vim/_system.lua [hunk 2]
```diff
@@ -208,13 +208,18 @@ end
 --- @param clear_env? boolean
 --- @return string[]?
 local function setup_env(env, clear_env)
+  if not env and clear_env then
+    return
```
Comment (justinmk) [inline runtime/lua/vim/_system.lua:212]: is this for performance? would it resolve your use-case if we stored a module-level env table and returned it here ?
```suggestion
    return _base_env
```

Comment (lewis6991) [reply runtime/lua/vim/_system.lua:212]: The env could change, and we even have a test for this.

Comment (lewis6991) [reply runtime/lua/vim/_system.lua:212]: > is this for performance? 

It's partly for:
- performance (though arguably might be a uop)
- fixing a regression
- working towards the original intent of `vim.system` which was to replace uses of `vim.uv.spawn`, and thus all the extra functionality it provides has an opt-out, e.g. setting `stdout/stderr=false`.

I might be overthinking it, but for now this is low risk and fixes downstream issues.
