### PR TITLE
Windows: Fix text overrides line number

### LINKED ISSUE #9461: Windows/TUI: Text overrides line numbers
- `nvim --version`: NVIM v0.3.3 Build type: RelWithDebInfo
- Operating system/version: Windows 10 Pro x64 latest
- Terminal name/version: cmd & ConEmu latest

Add or delete any line and buffer overrides line numbers. `Ctrl + L` helps but it's annoying.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set nu
:edit main.cpp
dd
```
Example file: main.cpp
```
#include <string>
#include <regex>


void via_regex()
{
	std::string content("4aejuj+8tr.v,ebyv-67.3yt3ktux+3.3");

	std::regex re("[+-]?\\d+\\.\\d+");

	std::sregex_iterator begin(content.cbegin(), content.cend(), re);
	std::sregex_iterator end;

	for (auto it = begin; it != end; ++it)
	{
		print_out("regex result: ", it->str(), '\n');
	}
}
```

### Actual behavior
screenshot

### Expected behaviour
screenshot

### PR DESCRIPTION
**Pull request by erw7**
Replace `cud1` with `\x1b[B` because `\n` is `CRLF` on Windows.

~Should we add the following code somewhere to solve this problem fundamentally?~

```C
_setmode( _fileno( stdout ), _O_BINARY );
```

fix #9461

### CODE REVIEW

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -1585,6 +1588,11 @@ static void patch_terminfo_bugs(TUIData *data, const char *term,
       unibi_set_if_empty(ut, unibi_set_left_margin_parm, "\x1b[%i%p1%ds");
       unibi_set_if_empty(ut, unibi_set_right_margin_parm, "\x1b[%i;%p2%ds");
     }
+
+#ifdef WIN32
+    // Replace cud1 because \n is CRLF on Windows.
+    unibi_set_str(ut, unibi_cursor_down, "\x1b[B");
```
Comment (justinmk) [inline src/nvim/tui/tui.c]: Why in `if (xterm)` ? Shouldn't it be done always on Windows?

File: src/nvim/tui/tui.c [hunk 2]
```diff
@@ -222,6 +222,9 @@ static void terminfo_start(UI *ui)
 #ifdef WIN32
   os_tty_guess_term(&term, data->out_fd);
   os_setenv("TERM", term, 1);
+  // Since the *term is released by calling os_setenv(), it is necessary to
+  // call os_getenv() again.
+  term = os_getenv("TERM");
```
Comment (justinmk) [inline src/nvim/tui/tui.c]: Why only on Windows?

**Comment by justinmk** [comment]
> Should we add the following code somewhere to solve this problem fundamentally?
> 
> ```c
> _setmode( _fileno( stdout ), _O_BINARY );
> ```

Sure. But I thought 8072f085d2edc254 did that already?

**Comment by erw7** [comment]
> Sure. But I thought 8072f08 did that already?

No, the 8072f08 is a change to the input handle, so the output handle is not affected.

As a result of my research, `WriteConsole()` does not convert `LF` to `CRLF`. `libuv` is converting from `LF` to `CRLF`. Thus, calling `_setmode()` is not a solution to this problem.

Ref. https://github.com/libuv/libuv/blob/ecff27857dafe3f5d30a6ab8646ea69a93e4940a/src/win/tty.c#L2065-L2069

File: src/nvim/tui/tui.c (hunk 1 above)
Comment (erw7) [reply src/nvim/tui/tui.c]: The `cud1` of the non-xterm terminal may not be `\x1b[B`. I think we have to add `cud1` conversion each time we find a terminal that causes a problem.

I think the fundamental solution is to implement a mode that does not convert `LF` to `CRLF` in `libuv`. If we write a patch, it may not be taken upstream, what shuld we do?

Comment (justinmk) [reply src/nvim/tui/tui.c]: > I think the fundamental solution is to implement a mode that does not convert `LF` to `CRLF` in `libuv`. If we write a patch, it may not be taken upstream, what shuld we do?

If it's a small/low-risk patch, they will probably accept it.

Comment (BYK) [reply src/nvim/tui/tui.c]: @erw7 yeah, I think the main issue here is the automatic conversion of `LF` to `CR``LF`. "Proper" terminal emulators can deal with both and I know Alacritty supports the "legacy newline mode" too if needed.

File: src/nvim/os/env.c [hunk 3]
```diff
@@ -105,6 +105,10 @@ bool os_env_exists(const char *name)
   return (r == 0 || r == UV_ENOBUFS);
 }
 
+/// Sets an environment variable.
+///
+/// @warning Existing pointers to the result of os_getenv("foo") are
+///          INVALID after os_setenv("foo", …).
 int os_setenv(const char *name, const char *value, int overwrite)
```
Comment (justinmk) [inline src/nvim/os/env.c]: Future improvement: instead of returning `int`, we could return a pointer to the new `os_getenv()` result. So the caller pattern could be like:

    term = os_setenv("TERM", term, ...)

However, after inspecting of all existing calls to `os_setenv` and `vim_setenv`, it looks like `tui.c` was the only case where a `os_getenv` result was passed to `os_setenv`.

File: src/nvim/tui/tui.c (hunk 1 above)
Comment (erw7) [reply src/nvim/tui/tui.c]: It seems that `libuvu` is not the only one that converts `CR` to `CR+LF`. It also seems to occur when `uv__vterm_state == UV_SUPPORTED`. So it seems to me that `ConEmu` and `VTP` are doing the same conversion.

Therefore, in order to solve this problem on Windows, it may be best to ignore the `TERM` environment variable even if it is set.
