### PR TITLE
fix(display): scroll redrawing doesn't account for virt_lines above fold

### LINKED ISSUE #33369: Wrong display with folded and virtual lines
### Problem

Missing buffer line, duplicated line below after placing virtual line above a folded line.

### Steps to reproduce

```lua
vim.fn.setline(1, vim.fn.range(1, 6) )
vim.cmd('2,3fold')
vim.keymap.set('n', 'v', function()
  vim.api.nvim_buf_set_extmark(0, 1, 0, 0, { virt_lines = {{{'virt_below'}}}})
end)
```

1. `nvim --clean -u minimal.lua`
2. Type <kbd>v</kbd>, observe missing line 5, duplicate line 6. 

Related: https://github.com/neovim/neovim/pull/33361#issuecomment-2781689543, #33205.

Have been looking into those issues but have yet to find a solution that resolves this properly.

### Expected behavior

No incorrect display.

Resolving this will likely require updating https://github.com/neovim/neovim/blob/ca16b54c866bca6d10fc4f60874e6469bd0751cd/test/functional/ui/decorations_spec.lua#L2904-L2914, which contains an incorrect screen state.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-102+gca16b54c86

### Vim (not Nvim) behaves the same?

no, vim 9.1.1283

### Operating system/version

Linux

### Terminal name/version

st

### $TERM environment variable

st-256color

### Installation

built from source

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Logic computing the new height of the modified area does not
          take into account virtual lines attached to a folded line.
Solution: Remove `hasFolding()` branch and let `plines_win_full()` do its job.

Fix #33369

### CODE REVIEW

File: src/nvim/drawscreen.c [hunk 1]
```diff
@@ -2188,18 +2188,11 @@ static void win_update(win_T *wp)
...
-              int n = plines_win_nofill(wp, l, false) + wp->w_topfill
-                      - adjust_plines_for_skipcol(wp);
-              n = MIN(n, wp->w_height_inner);
-              new_rows += n;
-            } else {
-              new_rows += plines_win(wp, l, true);
+            if (l == wp->w_topline) {
+              new_rows -= adjust_plines_for_skipcol(wp);
             }
+            new_rows += plines_win_full(wp, l, &l, NULL, true, true);
```
Comment (zeertzjq) [inline src/nvim/drawscreen.c:2195]: `limit_winheight == true` does not look right. With `'smoothscroll'` the return value of `adjust_plines_for_skipcol(wp)` can be large than the window height.
