### PR TITLE
fix(tests): fix flakiness on prompt mark set after buftype change

### LINKED ISSUE #35783: unreliable test: prompt_buffer_spec
### Problem

```
FAILED   test/functional/legacy/prompt_buffer_spec.lua @ 612: prompt buffer sets the ': mark
test/functional/legacy/prompt_buffer_spec.lua:628: Expected objects to be the same.
Passed in:
(table: 0x010cbaaa98) {
 *[1] = 12
  [2] = 1 }
Expected:
(table: 0x011ad67e18) {
 *[1] = 11
  [2] = 1 }

stack traceback:
	test/functional/legacy/prompt_buffer_spec.lua:628: in function 
```

### Expected behavior

cc @shadmansaleh

### PR DESCRIPTION
**Pull request by shadmansaleh**
### Problem
The test of the mark position after buftype=prompt is set is flacky. When buftype is changed the prompt get's placed at end of buffer. If a new line is added in between this can lead to unintentional failure.

### Solution
Assert against the last line of the buffer to be the `:` mark location instead of a hardcoded value. 
 
fixes #35783

### CODE REVIEW

**Comment by zeertzjq** [comment]
Test is still flaky: https://github.com/zeertzjq/neovim/actions/runs/17850496176/job/50757961057

**Comment by zeertzjq** [comment]
Hmm, I think you should not call `source_script()` in this test. You are not using the timer at all.

**Comment by shadmansaleh** [comment]
> Test is still flaky: https://github.com/zeertzjq/neovim/actions/runs/17850496176/job/50757961057

How are you testing the CI?

> Hmm, I think you should not call source_script() in this test. You are not using the timer at all.

Let's see if doing it without `source_script` fixes it.

**Comment by zeertzjq** [comment]
> How are you testing the CI?

I edited .github/workflows/test.yml to only run a single test, and test/CMakeLists.txt to run the test suite 100 times.

File: test/functional/legacy/prompt_buffer_spec.lua [hunk 1]
```diff
@@ -610,7 +610,15 @@ describe('prompt buffer', function()
   end)
 
   it("sets the ': mark", function()
-    source_script()
+    api.nvim_set_option_value('buftype', 'prompt', { buf = 0 })
+    exec_lua(function()
+      local buf = vim.api.nvim_get_current_buf()
+      vim.fn.prompt_setcallback(buf, function(str)
+        local last_line = vim.api.nvim_buf_line_count(buf)
+        vim.api.nvim_buf_set_lines(buf, last_line-1, last_line-1, true, vim.split(str, '\n'))
```
Comment (zeertzjq) [inline test/functional/legacy/prompt_buffer_spec.lua]:
```suggestion
        vim.api.nvim_buf_set_lines(buf, last_line - 1, last_line - 1, true, vim.split(str, '\n'))
```

File: test/functional/legacy/prompt_buffer_spec.lua [hunk 2]
```diff
@@ -620,12 +628,13 @@ describe('prompt buffer', function()
...
     -- ': mark is only available in prompt buffer.
-    source('set buftype=')
+    api.nvim_set_option_value('buftype', '', { buf = 0 })
     eq("Invalid mark name: ':'", t.pcall_err(api.nvim_buf_get_mark, 0, ':'))
 
     -- mark can be moved
-    source('set buftype=prompt')
-    eq({ 11, 1 }, api.nvim_buf_get_mark(0, ':'))
+    api.nvim_set_option_value('buftype', 'prompt', { buf = 0 })
+    local last_line = api.nvim_buf_line_count(0);
```
Comment (zeertzjq) [inline test/functional/legacy/prompt_buffer_spec.lua]:
```suggestion
    local last_line = api.nvim_buf_line_count(0)
```

**Comment by shadmansaleh** [comment]
https://github.com/zeertzjq/neovim/actions/runs/17855887272

I assume it works now?

**Comment by zeertzjq** [comment]
Yes
