### PR TITLE
fix(hl): set Normal hl group sg_attr value (fixes #18024)

### LINKED ISSUE #18024: nvim_get_hl_by_name("Group", true) doesn't always return colors
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1392-gdaa8ac051

### Installation

GitHub nightly builds

### How to reproduce the issue

```
nvim --clean
```

1) `:lua =vim.api.nvim_get_hl_by_name("Normal", true)` prints:

```lua
{                                                                                                             
  [true] = 6
}
```

2) Set highlight via `lua vim.api.nvim_set_hl(0, "Normal", { fg = "#ff0000", bg = "#202020" })`. 1) prints:

```lua
{                                                                                                             
  [true] = 6
}
```

3) Set highlight via `:hi Normal guifg=#ff0000 guibg=#202020`. 1) prints:

```lua
{
  background = 2105376,
  foreground = 16711680
}
```

Note: This behavior might be specific to the `Normal` group.

### Expected behavior

`nvim_get_hl_by_name("Normal", true)` returns the group's colors.

### Actual behavior

It only does so when the highlights are set the vimscript way.

### PR DESCRIPTION
**Pull request by rktjmp**
Re: https://github.com/neovim/neovim/issues/18024, see [comment for reasoning](https://github.com/neovim/neovim/issues/18024#issuecomment-1143111611).
 
This is a naive patch, it fixes the listed issue but I cant make a judgement on whether the line was intentionally omitted (because "Normal is special") or just mistakenly missed, so this probably needs at least a comment from someone knowledgeable on whether this is fine or needs more investigation.

### CODE REVIEW

File: src/nvim/highlight_group.c [hunk 1]
```diff
@@ -747,8 +749,6 @@ void set_hl_group(int id, HlAttrs attrs, Dict(highlight) *dict, int link_id)
     normal_sp = g->sg_rgb_sp;
     ui_default_colors_set();
   } else {
-    g->sg_attr = hl_get_syn_attr(0, id, attrs);
-
     // a cursor style uses this syn_id, make sure its attribute is updated.
```
Comment (rktjmp) [inline src/nvim/highlight_group.c:752]: Potential for Normal to ever need to hit this check? Should the else be completely discarded?

File: test/functional/api/highlight_spec.lua [hunk 2]
```diff
@@ -337,4 +337,10 @@ describe("API: set highlight", function()
       exec_capture('highlight Test_hl3'))
 
   end)
+
+  it ("correctly sets 'Normal' internal properties", function()
```
Comment (rktjmp) [inline test/functional/api/highlight_spec.lua:341]: Hardest part of the test was naming it and while the issue is listed with get_hl_by_name, the cause is closer to set_hl, so I stuck it here.

Comment (justinmk) [reply test/functional/api/highlight_spec.lua:341]: thank you for trying to find a meaningful name!
