### PR TITLE
Lua: format multiline messages / emsgf_multiline()

### LINKED ISSUE #7388: lua require('nonexistent') gives unnecessarily verbose error with unprintable chars
- `nvim --version`: NVIM v0.2.1-581-g253f6f3bb
- Vim (version: ) behaves differently? Irrelevant, does not support `require()`
- Operating system/version: Arch Linux
- Terminal name/version: pangoterm
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:lua require('nonexistent')
```

### Actual behaviour

E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:1: module 'nonexistent' not found:^@^Ino field package.preload['nonexistent']^@^Ino file '/home/bjorn/.config/nvim/lua/nonexistent.lua'^@^Ino file '/home/bjorn/.config/nvim/lua/nonexistent/init.lua'^@^Ino file '/etc/xdg/nvim/lua/nonexistent.lua'^@^Ino file '/etc/xdg/nvim/lua/nonexistent/init.lua'^@^Ino file '/home/bjorn/.local/share/nvim/site/lua/nonexistent.lua'^@^Ino file '/home/bjorn/.local/share/nvim/site/lua/nonexistent/init.lua'^@^Ino file '/home/bjorn/.local/share/flatpak/exports/share/nvim/site/lua/nonexistent.lua'^@^Ino file '/home/bjorn/.local/share/flatpak/exports/share/nvim/site/lua/nonexistent/init.lua'^@^Ino file '/var/lib/flatpak/exports/share/nvim/site/lua/nonexistent.lua'^@^Ino file '/var/lib/flatpak/exports/share/nvim/site/lua/nonexistent/init.lua'^@^Ino file '/usr/local/share/nvim/site/lua/nonexistent.lua'^@^Ino file '/usr/local/share/nvim/site/lua/nonexistent/init.lua'^@^Ino file '/usr/share/nvim/site/lua/nonexistent.lua'^@^Ino file '/usr/share/nvi

### Expected behaviour

Short and readable error message. Or at least one that does not contain non-printable characters.

### PR DESCRIPTION
**Pull request by bfredl**
Continuation of  #7969, rebased and tried to simplify the code by removing some duplicate code. History and "keep" logic will need to be made aware so the message can be reprinted consistently. (Should also check `ext_message` support after #7466 is rebased on top of this).

Currently works with lua errors (try `:lua require('nosuchpackage')`) and `rpcrequest` errors (such as `:py3` tracebacks, but pynvim master is needed, I will do a pynvim release in the weekend). The full error will be stored in  `v:errmsg`, not only the first line.

Related: #9519, It might make sense to use this for all `nvim_err_write` calls.

Closes #7388

### CODE REVIEW

File: src/nvim/message.c [hunk 1]
```diff
@@ -132,41 +132,92 @@ int verb_msg(char_u *s)
...
+  return msg_attr_keep_echo(s, attr, keep, false);
+}
+
+/// @param keep set keep_msg if it doesn't scroll
+bool msg_attr_keep_echo(char_u *s, int attr, bool keep, bool echo)
+  FUNC_ATTR_NONNULL_ALL
+{
+  static int entered = 0;
+
+  if (msg_attr_skip((const char *)s, attr, &entered)) {
```
Comment (bfredl) [inline src/nvim/message.c]: Note to self: indirection probably not needed anymore.

**Comment by bfredl** [comment]
Made it lua-only for now and added the tests for lua (both screen and API error access). This is useful as it is, let's consider RPC errors in a follow-up PR.

File: src/nvim/message.c [hunk 2]
```diff
@@ -126,29 +126,61 @@ int verb_msg(char_u *s)
...
 }
 
-int
-msg_attr_keep (
-    char_u *s,
-    int attr,
-    int keep                   /* TRUE: set keep_msg if it doesn't scroll */
-)
-  FUNC_ATTR_NONNULL_ARG(1)
+void msg_echo_show(const char *s, int attr)
```
Comment (justinmk) [inline src/nvim/message.c]: `msg_echo_show` is pretty confusing name, it is 3 synonyms to anyone without tribal knowledge. Maybe `msg_display` is an OK name, it is somewhat similar behavior as the existing `msg_puts_display`. (Other suggestions: `msg_fmt`, `msg_pretty`).

File: src/nvim/message.c [hunk 3]
```diff
@@ -468,17 +505,8 @@ int emsg_not_now(void)
...
-/*
- * emsg() - display an error message
- *
- * Rings the bell, if appropriate, and calls message() to do the real work
- * When terminal not initialized (yet) mch_errmsg(..) is used.
- *
- * return TRUE if wait_return not called
- */
-int emsg(const char_u *s_)
+static int emsg_echo(const char *s, bool use_echo)
```
Comment (justinmk) [inline src/nvim/message.c]: `use_echo` and the similar cases should be renamed to e.g. `pretty`. Otherwise it's too confusing, AFAICT it overlaps with other uses of the word "echo" (in this very same file) that do not behave like this.

File: src/nvim/message.c [hunk 4]
```diff
@@ -573,7 +601,20 @@ int emsg(const char_u *s_)
...
+}
+
+/*
+ * emsg() - display an error message
+ *
+ * Rings the bell, if appropriate, and calls message() to do the real work
+ * When terminal not initialized (yet) mch_errmsg(..) is used.
+ *
+ * return TRUE if wait_return not called
+ */
```
Comment (justinmk) [inline src/nvim/message.c]: may as well convert to `///` style

File: src/nvim/message.c (hunk 3 above)
Comment (bfredl) [reply src/nvim/message.c]: I agree the name is not optimal, but may I ask, what other usages in the same file? I can't find them.

File: src/nvim/message.c [hunk 5]
```diff
@@ -595,6 +636,28 @@ bool emsgf(const char *const fmt, ...)
   return ret;
 }
 
+#define MULTILINE_BUFSIZE 8192
+
+bool emsgf_echo(const char *const fmt, ...)
```
Comment (justinmk) [inline src/nvim/message.c]: `emsgf_pretty`

Comment (bfredl) [reply src/nvim/message.c]: what about "multiline" in general instead of "pretty" ?

File: src/nvim/message.h [hunk 6]
```diff
@@ -78,6 +78,7 @@ typedef struct msg_hist {
   struct msg_hist *next;  ///< Next message.
   char_u *msg;            ///< Message text.
   int attr;               ///< Message highlighting.
+  bool echo;              ///< echo-style disply
```
Comment (justinmk) [inline src/nvim/message.h]: `pretty`

File: src/nvim/message.c (hunk 3 above)
Comment (justinmk) [reply src/nvim/message.c]: the "e" in `emsg`, no?

Comment (bfredl) [reply src/nvim/message.c]: I'm pretty sure that is "error"

File: src/nvim/message.c (hunk 5 above)
Comment (justinmk) [reply src/nvim/message.c]: Sure. Or maybe `expanded`. Whatever you like best

File: src/nvim/message.c [hunk 7]
```diff
@@ -595,6 +635,28 @@ bool emsgf(const char *const fmt, ...)
...
+bool emsgf_multiline(const char *const fmt, ...)
+{
+  bool ret;
+  va_list ap;
+
+  va_start(ap, fmt);
+
+  static char  errbuf[MULTILINE_BUFSIZE];
+  if (emsg_not_now()) {
+    return true;
```
Comment (justinmk) [inline src/nvim/message.c]: I think `va_start` must be paired with `va_end`. So this should be checked before `va_*` stuff.

**Review by justinmk — APPROVED** [review]
LGTM after `va_end` fix.

File: src/nvim/message.c (hunk 7 above)
Comment (bfredl) [reply src/nvim/message.c]: I checked the docs, you seem to be right. Also by the docs the `va_copy` in `api_set_error` seem to be unnecessary, one is allowed several `va_start/va_end` on the same arg list (noting in case we choose to reuse the pattern).
