### PR TITLE
fix(autocmd): api functions accepting garbage after event name

### LINKED ISSUE #25517: nvim_create_autocmd accepts invalid event names
### Problem

The first parameter of `nvim_create_autocmd` accepts garbage text after event names, ie. `"User Testing"` is parsed as a `User` event, but then the trailing `" Testing"` is ignored. Trying to provide the pattern after event name like this is an easy mistake to make for people used to `:autocmd`.

### Steps to reproduce

```
nvim --clean
:lua vim.api.nvim_create_autocmd('VimEnter foo', {command=''})
```

### Expected behavior

Reject invalid event names and return an error.

### Neovim version (nvim -v)

v0.10.0-dev, 7bd6bd1ef

### Vim (not Nvim) behaves the same?

-

### Operating system/version

ubuntu 20.04

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

ppa

### PR DESCRIPTION
**Pull request by ii14**
"VimEnter foo" was accepted as a valid event name for "VimEnter". Events delimited with commas, eg. "VimEnter,BufRead", were also accepted, even though only the first event was actually parsed.

Fix #25517

### CODE REVIEW

File: src/nvim/api/autocmd.c [hunk 1]
```diff
@@ -33,9 +33,8 @@
 // Copy string or array of strings into an empty array.
 // Get the event number, unless it is an error. Then goto `goto_name`.
 #define GET_ONE_EVENT(event_nr, event_str, goto_name) \
-  char *__next_ev; \
   event_T event_nr = \
-    event_name2nr(event_str.data.string.data, &__next_ev); \
+    event_name2nr_str(event_str.data.string); \
   if (event_nr >= NUM_EVENTS) { \
     api_set_error(err, kErrorTypeValidation, "unexpected event"); \
     goto goto_name; \
```
Comment (justinmk) [inline src/nvim/api/autocmd.c:40]: off topic, would be nice to mention the event name in the error :)

```c
VALIDATE_S((event_nr < NUM_EVENTS), "event", event_str.data.string, {
  goto goto_name;
});

**Comment by ii14** [comment]
Comma delimited events will return an error right now, but maybe they should be actually accepted?

**Review by famiu — APPROVED** [review]
LGTM, besides the change Justin suggested

File: src/nvim/autocmd.c [hunk 2]
```diff
@@ -623,6 +623,18 @@ event_T event_name2nr(const char *start, char **end)
   return event_names[i].event;
 }
 
+// Return the event number for event name "str".
+// Return NUM_EVENTS if the event name was not found.
```
Comment (zeertzjq) [inline src/nvim/autocmd.c:627]:
```suggestion
/// Return the event number for event name "str".
/// Return NUM_EVENTS if the event name was not found.
```
