### PR TITLE
fix(messages): :map output with ext_messages

### LINKED ISSUE #20715: Formatting of `msg_show` for `map` is missing newlines with `ext_messages`
### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

bob

### How to reproduce the issue

Runnig the code below, you willl see that newlines are missing between each keymap.

```lua
local ns = vim.api.nvim_create_namespace("test")
local messages = {}

vim.ui_attach(ns, { ext_messages = true }, function(event, kind, content)
  if event == "msg_show" and kind == "return_prompt" then
    vim.api.nvim_input("<cr>")
  elseif kind == "" then
    table.insert(messages, content)
  end
end)

vim.cmd([[map]])

vim.defer_fn(function()
  vim.ui_detach(ns)
  vim.pretty_print(messages)
end, 1000)
```

### Expected behavior

The output should be formatted the same as normal

image

### Actual behavior

Newlines are missing between the different mappings.

image

See also https://github.com/folke/noice.nvim/issues/77

### PR DESCRIPTION
**Pull request by BaraTudor2025**
fix #20715

### CODE REVIEW

**Comment by zeertzjq** [comment]
Can you add a test? There are several tests in `test/functional/ui/messages_spec.lua`

File: src/nvim/mapping.c [hunk 1]
```diff
@@ -220,7 +221,7 @@ static void showmap(mapblock_T *mp, bool local)
     return;
   }
```
Comment (zeertzjq) [inline src/nvim/mapping.c:223]:
```suggestion

  // When ext_messages is active, msg_didout is never set.
```

**Comment by BaraTudor2025** [comment]
Sure, I'll have to add it tomorrow tho.
