### PR TITLE
fix: win_close from other tabpage

### LINKED ISSUE #15313: make tabpage's active window invalid by win_close from other tab
### Neovim Version

NVIM v0.6.0-dev+1594-g68f61b167

### Operating system/version:

Ubuntu 20.04

### Terminal name/version:

wsltty

### TERM environment variable

xterm-256color

### Installation

build from repo

### Steps to reproduce

```
build/bin/nvim -u NORC +'luafile minimal.lua'
```

minimal.lua
```lua
vim.cmd("tabedit")
local bufnr = vim.api.nvim_create_buf(false, true)
local window_id = vim.api.nvim_open_win(bufnr, true, {
  width = 50,
  height = 10,
  relative = "editor",
  row = 10,
  col = 10,
})

_G._on_win_closed = function()
  vim.api.nvim_win_close(window_id, true)
  vim.api.nvim_tabpage_get_win(vim.api.nvim_list_tabpages()[2])
end
vim.cmd("autocmd WinClosed * ++once lua _on_win_closed()")

vim.cmd("tabprevious | +tabclose")
```

### Vim

N/A (WinClosed event)

### Expected behavior

I'm not sure, but I think the following:

- `nvim_win_close` raises an invalid window id error
- `nvim_list_tabpages` does not return closed tab id.

### Actual behavior

```
Aborted (core dumped)
```

<details>
<summary>Full backtrace</summary>

```
[New LWP 14881]
[New LWP 14882]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/notomo/workspace/neovim/build/bin/nvim -u NORC +luafile ./minimal.lua +qu'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fac39c86740 (LWP 14881))]

Thread 2 (Thread 0x7fac397fd700 (LWP 14882)):
#0  0x00007fac39dab5ce in epoll_wait (epfd=15, events=events@entry=0x7fac397f96f0, maxevents=maxevents@entry=1024, timeout=timeout@entry=20) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
        resultvar = 18446744073709551612
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00000000007f8d44 in uv__io_poll (loop=<optimized out>, loop@entry=0x7fac397fc8e0, timeout=20) at /home/notomo/workspace/neovim/.deps/build/src/libuv/src/unix/linux-core.c:309
        max_safe_timeout = <optimized out>
        no_epoll_pwait = 0
        no_epoll_wait = 0
        events = {{events = 1, data = {ptr = 0x12, fd = 18, u32 = 18, u64 = 18}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}} <repeats 525 times>, {events = 973485148, data = {ptr = 0x39e9650000007fac, fd = 32684, u32 = 32684, u64 = 4172977580409913260}}, {events = 32684, data = {ptr = 0xaf067c12, fd = -1358529518, u32 = 2936437778, u64 = 2936437778}}, {events = 4243088, data = {ptr = 0x39e96c8800000000, fd = 0, u32 = 0, u64 = 4172985861106827264}}, {events = 32684, data = {ptr = 0x7fac39c8eea8, fd = 969469608, u32 = 969469608, u64 = 140377680572072}}, {events = 973486218, data = {ptr = 0x39700007fac, fd = 32684, u32 = 32684, u64 = 3947074977708}}, {events = 0, data = {ptr = 0x7fac39c9e330, fd = 969532208, u32 = 969532208, u64 = 140377680634672}}, {events = 971597056, data = {ptr = 0x397fb08800007fac, fd = 32684, u32 = 32684, u64 = 4143224280366219180}}, {events = 32684, data = {ptr = 0x7fac397fb084, fd = 964669572, u32 = 964669572, u64 = 140377675772036}}, {events = 0, data = {ptr = 0x39c9e33000000000, fd = 0, u32 = 0, u64 = 4164109125778669568}}, {events = 32684, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x39c9054800000000, fd = 0, u32 = 0, u64 = 4163865137276518400}}, {events = 32684, data = {ptr = 0x42bbf7, fd = 4373495, u32 = 4373495, u64 = 4373495}}, {events = 2936437778, data = {ptr = 0x2bc19f000000000, fd = 0, u32 = 0, u64 = 197061002280304640}}, {events = 0, data = {ptr = 0x7fac397fb084, fd = 964669572, u32 = 964669572, u64 = 140377675772036}}, {events = 0, data = {ptr = 0x397fb15000000000, fd = 0, u32 = 0, u64 = 4143225139359645696}}, {events = 32684, data = {ptr = 0x40be90, fd = 4243088, u32 = 4243088, u64 = 4243088}}, {events = 964669760, data = {ptr = 0x7fac, fd = 32684, u32 = 32684, u64 = 32684}}, {events = 0, data = {ptr = 0x7fac39e96be8, fd = 971598824, u32 = 971598824, u64 = 140377682701288}}, {events = 10, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0xaf067c12, fd = -1358529518, u32 = 2936437778, u64 = 2936437778}}, {events = 973632760, data = {ptr = 0x397fb1e800007fac, fd = 32684, u32 = 32684, u64 = 4143225792194707372}}, {events = 32684, data = {ptr = 0x42bbf7, fd = 4373495, u32 = 4373495, u64 = 4373495}}, {events = 964669760, data = {ptr = 0x397fb15000007fac, fd = 32684, u32 = 32684, u64 = 4143225139359678380}}, {events = 32684, data = {ptr = 0x7fac3a0641e9 <_dl_lookup_symbol_x+281>, fd = 973488617, u32 = 973488617, u64 = 140377684591081}}, {events = 8, data = {ptr = 0x39e96c8800000000, fd = 0, u32 = 0, u64 = 4172985861106827264}}, {events = 32684, data = {ptr = 0x5, fd = 5, u32 = 5, u64 = 5}}, {events = 0, data = {ptr = 0x100000000, fd = 0, u32 = 0, u64 = 4294967296}}, {events = 0, data = {ptr = 0x7fac3a087190, fd = 973631888, u32 = 973631888, u64 = 140377684734352}}, {events = 0, data = {ptr = 0x39e96c8800000000, fd = 0, u32 = 0, u64 = 4172985861106827264}}, {events = 32684, data = {ptr = 0x7fac3a087190, fd = 973631888, u32 = 973631888, u64 = 140377684734352}}, {events = 973632760, data = {ptr = 0x7fac, fd = 32684, u32 = 32684, u64 = 32684}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x100000000, fd = 0, u32 = 0, u64 = 4294967296}}, {events = 0, data = {ptr = 0xffffffff, fd = -1, u32 = 4294967295, u64 = 4294967295}}, {events = 0, data = {ptr = 0x39c95b7000000000, fd = 0, u32 = 0, u64 = 4163959867075198976}}, {events = 32684, data = {ptr = 0x7fac39e96500, fd = 971597056, u32 = 971597056, u64 = 140377682699520}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x9ca8a000000000, fd = 0, u32 = 0, u64 = 44095501515096064}}, {events = 0, data = {ptr = 0x7fac397fc240, fd = 964674112, u32 = 964674112, u64 = 140377675776576}}, {events = 4089134974, data = {ptr = 0xf3bb3f7f00007ffd, fd = 32765, u32 = 32765, u64 = 17562700986554810365}}, {events = 32765, data = {ptr = 0x7ffdf3bb4008, fd = -205832184, u32 = 4089135112, u64 = 140728692588552}}, {events = 964677568, data = {ptr = 0x3a06918700007fac, fd = 32684, u32 = 32684, u64 = 4181189313066729388}}, {events = 32684, data = {ptr = 0x5, fd = 5, u32 = 5, u64 = 5}}, {events = 973509098, data = {ptr = 0x7fac, fd = 32684, u32 = 32684, u64 = 32684}}, {events = 0, data = {ptr = 0x7fac39c95b70, fd = 969497456, u32 = 969497456, u64 = 140377680599920}}, {events = 964670848, data = {ptr = 0x3a070b6e00007fac, fd = 32684, u32 = 32684, u64 = 4181323346111135660}}, {events = 32684, data = {ptr = 0x7fac3401a14f, fd = 872522063, u32 = 872522063, u64 = 140377583624527}}, {events = 964674048, data = {ptr = 0x397fc20000007fac, fd = 32684, u32 = 32684, u64 = 4143243487459966892}}, {events = 32684, data = {ptr = 0x8f59d0, fd = 9394640, u32 = 9394640, u64 = 9394640}}, {events = 872522063, data = {ptr = 0x810fe000007fac, fd = 32684, u32 = 32684, u64 = 36327726742798252}}, {events = 0, data = {ptr = 0x7fac397fc288, fd = 964674184, u32 = 964674184, u64 = 140377675776648}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x1fa100000000, fd = 0, u32 = 0, u64 = 34776350195712}}, {events = 65535, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7fac39d24773 <_int_malloc+2947>, fd = 970082163, u32 = 970082163, u64 = 140377681184627}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0xff00000000000000, fd = 0, u32 = 0, u64 = 18374686479671623680}}, {events = 0, data = {ptr = 0xff0000, fd = 16711680, u32 = 16711680, u64 = 16711680}}, {events = 0, data = {ptr = 0xffffffffffffffff, fd = -1, u32 = 4294967295, u64 = 18446744073709551615}}, {events = 872415504, data = {ptr = 0x76f11500007fac, fd = 32684, u32 = 32684, u64 = 33479119748497324}}, {events = 0, data = {ptr = 0xffff, fd = 65535, u32 = 65535, u64 = 65535}}, {events = 872418768, data = {ptr = 0x11a772000007fac, fd = 32684, u32 = 32684, u64 = 79506922755096492}}, {events = 0, data = {ptr = 0x6, fd = 6, u32 = 6, u64 = 6}}, {events = 872522171, data = {ptr = 0x11a772000007fac, fd = 32684, u32 = 32684, u64 = 79506922755096492}}, {events = 0, data = {ptr = 0x7fac397fc000, fd = 964673536, u32 = 964673536, u64 = 140377675776000}}, {events = 8446787, data = {ptr = 0x782d6e6f00000000, fd = 0, u32 = 0, u64 = 8659699081523757056}}, {events = 1836213620, data = {ptr = 0x5b1b00325d1b002e, fd = 1562050606, u32 = 1562050606, u64 = 6564841098133045294}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x2000000020, fd = 32, u32 = 32, u64 = 137438953504}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7fac397fc23c, fd = 964674108, u32 = 964674108, u64 = 140377675776572}}, {events = 964674071, data = {ptr = 0x100007fac, fd = 32684, u32 = 32684, u64 = 4294999980}}, {events = 33619968, data = {ptr = 0x226, fd = 550, u32 = 550, u64 = 550}}, {events = 550, data = {ptr = 0x397fc01600000000, fd = 0, u32 = 0, u64 = 4143241382925959168}}, {events = 32684, data = {ptr = 0x186, fd = 390, u32 = 390, u64 = 390}}, {events = 872502038, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 4849814, data = {ptr = 0x20000, fd = 131072, u32 = 131072, u64 = 131072}}, {events = 0, data = {ptr = 0x2, fd = 2, u32 = 2, u64 = 2}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}} <repeats 20 times>, {events = 6, data = {ptr = 0x2000000000, fd = 0, u32 = 0, u64 = 137438953472}}, {events = 0, data = {ptr = 0x6, fd = 6, u32 = 6, u64 = 6}}, {events = 964670864, data = {ptr = 0x81103500007fac, fd = 32684, u32 = 32684, u64 = 36328091815018412}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 6, data = {ptr = 0x397fc28800000000, fd = 0, u32 = 0, u64 = 4143244071575486464}}, {events = 32684, data = {ptr = 0x6, fd = 6, u32 = 6, u64 = 6}}, {events = 872522048, data = {ptr = 0x397fc28800007fac, fd = 32684, u32 = 32684, u64 = 4143244071575519148}}, {events = 32684, data = {ptr = 0x7fac397fc240, fd = 964674112, u32 = 964674112, u64 = 140377675776576}}, {events = 8446787, data = {ptr = 0xffff007c00000000, fd = 0, u32 = 0, u64 = 18446463131308785664}}, {events = 8454143, data = {ptr = 0x76f115 <out+197>, fd = 7794965, u32 = 7794965, u64 = 7794965}}, {events = 65529, data = {ptr = 0x34000dd000000000, fd = 0, u32 = 0, u64 = 3747010076976611328}}, {events = 32684, data = {ptr = 0x11a7720, fd = 18511648, u32 = 18511648, u64 = 18511648}}, {events = 7, data = {ptr = 0x3401a10e00000000, fd = 0, u32 = 0, u64 = 3747453446450577408}}, {events = 32684, data = {ptr = 0x11a7720, fd = 18511648, u32 = 18511648, u64 = 18511648}}, {events = 964674192, data = {ptr = 0x80e34300007fac, fd = 32684, u32 = 32684, u64 = 36278673921310636}}, {events = 0, data = {ptr = 0xffffffffffffffff, fd = -1, u32 = 4294967295, u64 = 18446744073709551615}}, {events = 19661096, data = {ptr = 0x13e013a01360132, fd = 20316466, u32 = 20316466, u64 = 89510391234036018}}, {events = 21627204, data = {ptr = 0x160015c01560150, fd = 22413648, u32 = 22413648, u64 = 99080686473183568}}, {events = 23461887, data = {ptr = 0x173016e0169ffff, fd = 23724031, u32 = 23724031, u64 = 104428788341407743}}, {events = 25035127, data = {ptr = 0x19101890185ffff, fd = 25559039, u32 = 25559039, u64 = 112873153608679423}}, {events = 4294967295, data = {ptr = 0xffffffffffffffff, fd = -1, u32 = 4294967295, u64 = 18446744073709551615}}, {events = 4294967295, data = {ptr = 0x199ffffffffffff, fd = -1, u32 = 4294967295, u64 = 115404740451368959}}, {events = 4294902178, data = {ptr = 0x1bd01b401abffff, fd = 28049407, u32 = 28049407, u64 = 125258237270032383}}, {events = 30343622, data = {ptr = 0x1f301ea01e101d8, fd = 31523288, u32 = 31523288, u64 = 140458117944115672}}, {events = 4294902268, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 38076994, data = {ptr = 0x258025502530250, fd = 38994512, u32 = 38994512, u64 = 168887550160863824}}, {events = 4294902453, data = {ptr = 0xffffffffffff02b8, fd = -64840, u32 = 4294902456, u64 = 18446744073709486776}}, {events = 45809663, data = {ptr = 0x2ca02c602c202be, fd = 46269118, u32 = 46269118, u64 = 200976182844457662}}, {events = 4294967295, data = {ptr = 0xffff0303ffff02ce, fd = -64818, u32 = 4294902478, u64 = 18446465914447528654}}, {events = 50855935, data = {ptr = 0xffffffffffff030d, fd = -64755, u32 = 4294902541, u64 = 18446744073709486861}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0xffffffff00000000, fd = 0, u32 = 0, u64 = 18446744069414584320}}, {events = 4294967295, data = {ptr = 0xffffffffffffffff, fd = -1, u32 = 4294967295, u64 = 18446744073709551615}}, {events = 4294967295, data = {ptr = 0xffffffffffffffff, fd = -1, u32 = 4294967295, u64 = 18446744073709551615}}, {events = 4294967295, data = {ptr = 0xffffffffffffffff, fd = -1, u32 = 4294967295, u64 = 18446744073709551615}}, {events = 4294967295, data = {ptr = 0x31bffffffffffff, fd = -1, u32 = 4294967295, u64 = 224054081461682175}}, {events = 4294967295, data = {ptr = 0xffffffffffff0322, fd = -64734, u32 = 4294902562, u64 = 18446744073709486882}}, {events = 53084159, data = {ptr = 0xffffffff03370330, fd = 53936944, u32 = 53936944, u64 = 18446744069468521264}}, {events = 4294902590, data = {ptr = 0xffffffffffff0345, fd = -64699, u32 = 4294902597, u64 = 18446744073709486917}}, {events = 4294902604, data = {ptr = 0xffffffffffffffff, fd = -1, u32 = 4294967295, u64 = 18446744073709551615}}, {events = 56165203, data = {ptr = 0x374036d0366035f, fd = 57017183, u32 = 57017183, u64 = 248827646155555679}}, {events = 58917755, data = {ptr = 0x3a3039b0393038b, fd = 59966347, u32 = 59966347, u64 = 262057167632401291}}, {events = 62063531, data = {ptr = 0x3d003c903c203bb, fd = 63046587, u32 = 63046587, u64 = 274723739155956667}}, {events = 64947159, data = {ptr = 0x3ff03f703ef03e7, fd = 65995751, u32 = 65995751, u64 = 287953260632802279}}, {events = 68092935, data = {ptr = 0x42c0425041e0417, fd = 69075991, u32 = 69075991, u64 = 300619832156357655}}, {events = 70976563, data = {ptr = 0x45b0453044b0443, fd = 72025155, u32 = 72025155, u64 = 313849353633203267}}, {events = 74122339, data = {ptr = 0x4880481047a0473, fd = 75105395, u32 = 75105395, u64 = 326515925156758643}}, {events = 77005967, data = {ptr = 0x4b704af04a7049f, fd = 78054559, u32 = 78054559, u64 = 339745446633604255}}, {events = 80151743, data = {ptr = 0x7fac397fb908, fd = 964671752, u32 = 964671752, u64 = 140377675774216}}, {events = 4278519017, data = {ptr = 0xffffffff00000000, fd = 0, u32 = 0, u64 = 18446744069414584320}}, {events = 4294967295, data = {ptr = 0xffffffffffffffff, fd = -1, u32 = 4294967295, u64 = 18446744073709551615}}, {events = 0, data = {ptr = 0x397fbef000000000, fd = 0, u32 = 0, u64 = 4143240120205574144}}, {events = 32684, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 10, data = {ptr = 0x397fbf2000000000, fd = 0, u32 = 0, u64 = 4143240326364004352}}, {events = 32684, data = {ptr = 0xffffffff, fd = -1, u32 = 4294967295, u64 = 4294967295}}, {events = 969867882, data = {ptr = 0x585ffff00007fac, fd = 32684, u32 = 32684, u64 = 398005612773932972}}, {events = 4294967295, data = {ptr = 0xffffffffffffffff, fd = -1, u32 = 4294967295, u64 = 18446744073709551615}}, {events = 4294967295, data = {ptr = 0xffffffff058affff, fd = 92995583, u32 = 92995583, u64 = 18446744069507579903}}, {events = 4294967295, data = {ptr = 0x6, fd = 6, u32 = 6, u64 = 6}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}} <repeats 54 times>, {events = 7, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}} <repeats 165 times>...}
        e = {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
        sigset = {__val = {0 <repeats 16 times>}}
        w = <optimized out>
        q = <optimized out>
        op = <optimized out>
        sigmask = <optimized out>
        real_timeout = 20
        count = 48
        base = 1338843341
        nfds = <optimized out>
        have_signals = <optimized out>
        nevents = <optimized out>
        i = <optimized out>
        pe = <optimized out>
        fd = <optimized out>
#2  0x00000000007ea5b1 in uv_run (loop=0x7fac397fc8e0, mode=UV_RUN_ONCE) at /home/notomo/workspace/neovim/.deps/build/src/libuv/src/unix/core.c:375
        r = <optimized out>
        ran_pending = <optimized out>
        timeout = 964663024
#3  0x0000000000545b70 in loop_poll_events (loop=0x7fac397fc8e0, ms=20) at ../src/nvim/event/loop.c:62
        mode = UV_RUN_ONCE
        timeout_expired = false
#4  0x000000000076e3e8 in tui_main (bridge=0x11a7860, ui=0x11a7720) at ../src/nvim/tui/tui.c:449
        ms = 26
        tui_loop = {uv = {data = 0x7fac397fc8e0, active_handles = 5, handle_queue = {0x7fac397fcb68, 0x7fac34010f08}, active_reqs = {unused = {0x0, 0x0}, count = 0}, stop_flag = 0, flags = 0, backend_fd = 15, pending_queue = {0x7fac397fc928, 0x7fac397fc928}, watcher_queue = {0x7fac397fc938, 0x7fac397fc938}, watchers = 0x7fac34000b60, nwatchers = 30, nfds = 3, wq = {0x7fac397fc958, 0x7fac397fc958}, wq_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, wq_async = {data = 0x0, loop = 0x7fac397fc8e0, type = UV_ASYNC, close_cb = 0x0, handle_queue = {0x7fac397fce38, 0x7fac397fcb68}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 20, async_cb = 0x7e6b70 <uv__work_done>, queue = {0x7fac397fce80, 0x7fac397fca90}, pending = 0}, cloexec_lock = {__data = {__readers = 0, __writers = 0, __wrphase_futex = 0, __writers_futex = 0, __pad3 = 0, __pad4 = 0, __cur_writer = 0, __shared = 0, __rwelision = 0 '\000', __pad1 = "\000\000\000\000\000\000", __pad2 = 0, __flags = 0}, __size = '\000' <repeats 55 times>, __align = 0}, closing_handles = 0x0, process_handles = {0x7fac397fca50, 0x7fac397fca50}, prepare_handles = {0x7fac397fca60, 0x7fac397fca60}, check_handles = {0x7fac397fca70, 0x7fac397fca70}, idle_handles = {0x7fac397fca80, 0x7fac397fca80}, async_handles = {0x7fac397fc9f8, 0x7fac397fce80}, async_unused = 0x0, async_io_watcher = {cb = 0x7e9f90 <uv__async_io>, pending_queue = {0x7fac397fcab0, 0x7fac397fcab0}, watcher_queue = {0x7fac397fcac0, 0x7fac397fcac0}, pevents = 1, events = 1, fd = 18}, async_wfd = -1, timer_heap = {min = 0x7fac397fcde8, nelts = 1}, timer_counter = 9, time = 1338843341, signal_pipefd = {16, 17}, signal_io_watcher = {cb = 0x7f3550 <uv__signal_event>, pending_queue = {0x7fac397fcb18, 0x7fac397fcb18}, watcher_queue = {0x7fac397fcb28, 0x7fac397fcb28}, pevents = 1, events = 1, fd = 16}, child_watcher = {data = 0x0, loop = 0x7fac397fc8e0, type = UV_SIGNAL, close_cb = 0x0, handle_queue = {0x7fac397fc9b0, 0x7fac397fc8f0}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 16, signal_cb = 0x0, signum = 0, tree_entry = {rbe_left = 0x0, rbe_right = 0x0, rbe_parent = 0x0, rbe_color = 0}, caught_signals = 0, dispatched_signals = 0}, emfile_fd = 19, inotify_read_watcher = {cb = 0x0, pending_queue = {0x0, 0x0}, watcher_queue = {0x0, 0x0}, pevents = 0, events = 0, fd = 0}, inotify_watchers = 0x0, inotify_fd = -1}, events = 0x7fac34000cf0, thread_events = 0x7fac34000d70, fast_events = 0x7fac34000d30, children = 0x7fac34000c70, children_watcher = {data = 0x6f6e6b6e55646574, loop = 0x7fac397fc8e0, type = UV_SIGNAL, close_cb = 0x0, handle_queue = {0x7fac397fcd08, 0x7fac397fce38}, u = {fd = 538976288, reserved = {0x2020202020202020, 0x2020202020202020, 0x0, 0x0}}, next_closing = 0x0, flags = 8, signal_cb = 0xffffffff00ffffff, signum = 0, tree_entry = {rbe_left = 0x2000000020, rbe_right = 0x0, rbe_parent = 0x0, rbe_color = 0}, caught_signals = 0, dispatched_signals = 0}, children_kill_timer = {data = 0x0, loop = 0x7fac397fc8e0, type = UV_TIMER, close_cb = 0x0, handle_queue = {0x7fac397fcda0, 0x7fac397fcc70}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 8, timer_cb = 0x0, heap_node = {0x0, 0x0, 0x0}, timeout = 0, repeat = 0, start_id = 0}, poll_timer = {data = 0x7fac34000db0, loop = 0x7fac397fc8e0, type = UV_TIMER, close_cb = 0x0, handle_queue = {0x7fac34011668, 0x7fac397fcd08}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 12, timer_cb = 0x545be0 <timer_cb>, heap_node = {0x0, 0x0, 0x0}, timeout = 1338843361, repeat = 20, start_id = 8}, async = {data = 0x0, loop = 0x7fac397fc8e0, type = UV_ASYNC, close_cb = 0x0, handle_queue = {0x7fac397fcc70, 0x7fac397fc9b0}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 12, async_cb = 0x5459e0 <async_cb>, queue = {0x7fac397fca90, 0x7fac397fc9f8}, pending = 0}, mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, recursive = 1}
        data = 0x7fac34000dd0
#5  0x0000000000782d70 in ui_thread_run (data=0x11a7860) at ../src/nvim/ui_bridge.c:105
        bridge = 0x11a7860
#6  0x00007fac3a018609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140377675781888, -7943739794541314189, 140728692588414, 140728692588415, 140728692588552, 140377675780032, 7969779526785498995, 7969786658932981619}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007fac39dab293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7fac39c86740 (LWP 14881)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0 <repeats 13 times>, 21090832, 20750672, 21090832}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fac39cae859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 11 times>, 4528720, 8596352181, 140728692578752, 4705074, 20750672}}, sa_flags = 20750672, sa_restorer = 0x7fac3987e550}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x000000000048445c in nvim_tabpage_get_win (tabpage=2, err=0x7ffdf3bb1a38) at ../src/nvim/api/tabpage.c:124
        rv = 0
        tab = 0x13ca150
#3  0x000000000044c8f5 in nlua_msgpack_nvim_tabpage_get_win (lstate=0x7fac3987e380) at src/nvim/auto/msgpack_lua_c_bindings.generated.c:1778
        err = {type = kErrorTypeNone, msg = 0x0}
        arg1 = 2
        ret = 20739056
#4  0x000000000085c9bd in lj_BC_FUNCC ()
No symbol table info available.
#5  0x00000000008424a0 in lua_pcall (L=0x7fac3987e380, nargs=<optimized out>, nresults=<optimized out>, errfunc=<optimized out>) at lj_api.c:1169
        g = 0x7fac3987e3e0
        oldh = <optimized out>
        ef = 0
        status = <optimized out>
#6  0x00000000005e786c in nlua_typval_exec (lcmd=0x141fd70 "_on_win_closed()", lcmd_len=16, name=0x8f49c8 ":lua", args=0x0, argcount=0, special=false, ret_tv=0x0) at ../src/nvim/lua/executor.c:1133
        lstate = 0x7fac3987e380
#7  0x00000000005e8431 in ex_lua (eap=0x7ffdf3bb1c98) at ../src/nvim/lua/executor.c:1308
        len = 16
        code = 0x141fd70 "_on_win_closed()"
#8  0x000000000056a9d8 in do_one_cmd (cmdlinep=0x7ffdf3bb2028, flags=7, cstack=0x7ffdf3bb2030, fgetline=0x49de80 <getnextac>, cookie=0x7ffdf3bb2638) at ../src/nvim/ex_docmd.c:1964
        p = 0x142d243 " _on_win_closed()"
        lnum = 425201762305
        n = 553844939988
        errormsg = 0x0
        after_modifier = 0x142d240 "lua _on_win_closed()"
        ea = {arg = 0x142d244 "_on_win_closed()", nextcmd = 0x0, cmd = 0x142d240 "lua _on_win_closed()", cmdlinep = 0x7ffdf3bb2028, cmdidx = CMD_lua, argt = 524421, skip = 0, forceit = 0, addr_count = 0, line1 = 1, line2 = 1, addr_type = ADDR_LINES, flags = 0, do_ecmd_cmd = 0x0, do_ecmd_lnum = 0, append = 0, usefilter = 0, amount = 0, regname = 0, force_bin = 0, read_edit = 0, force_ff = 0, force_enc = 0, bad_char = 0, useridx = 0, errmsg = 0x0, getline = 0x49de80 <getnextac>, cookie = 0x7ffdf3bb2638, cstack = 0x7ffdf3bb2030, verbose_save = -1, save_msg_silent = -1, did_esilent = 0, did_sandbox = false}
        save_msg_scroll = 1
        save_cmdmod = {split = 0, tab = 0, browse = false, confirm = false, hide = false, keepalt = false, keepjumps = false, keepmarks = false, keeppatterns = false, lockmarks = false, noswapfile = false, save_ei = 0x0, filter_regmatch = {regprog = 0x0, startp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, endp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, rm_ic = false}, filter_force = false}
        save_reg_executing = 0
        cmd = 0x142d240 "lua _on_win_closed()"
        ni = 0
#9  0x000000000056772e in do_cmdline (cmdline=0x0, fgetline=0x49de80 <getnextac>, cookie=0x7ffdf3bb2638, flags=7) at ../src/nvim/ex_docmd.c:595
        recursive = 3
        call_depth = 3
        next_cmdline = 0x142d240 "lua _on_win_closed()"
        cmdline_copy = 0x142d240 "lua _on_win_closed()"
        used_getline = true
        msg_didout_before_start = false
        count = 1
        did_inc = 0
        retval = 1
        cstack = {cs_flags = {0 <repeats 50 times>}, cs_pending = '\000' <repeats 49 times>, cs_pend = {csp_rv = {0x0 <repeats 50 times>}, csp_ex = {0x0 <repeats 50 times>}}, cs_forinfo = {0x0 <repeats 50 times>}, cs_line = {0 <repeats 50 times>}, cs_idx = -1, cs_looplevel = 0, cs_trylevel = 0, cs_emsg_silent_list = 0x0, cs_lflags = 0}
        lines_ga = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 16, ga_growsize = 10, ga_data = 0x0}
        current_line = 0
        fname = 0x0
        breakpoint = 0x0
        dbg_tick = 0x0
        debug_saved = {trylevel = 0, force_abort = 0, caught_stack = 0x0, vv_exception = 0x0, vv_throwpoint = 0x0, did_emsg = 0, got_int = 0, need_rethrow = 0, check_cstack = 0, current_exception = 0x0}
        initial_trylevel = 1
        saved_msg_list = 0x7ffdf3bb2df0
        private_msg_list = 0x0
        cmd_getline = 0x49de80 <getnextac>
        cmd_cookie = 0x7ffdf3bb2638
        cmd_loop_cookie = {lines_gap = 0x49de80 <getnextac>, current_line = 5498480, repeating = 0, getline = 0x7ffdf3bb27c8, cookie = 0x49de80 <getnextac>}
        real_cookie = 0x7ffdf3bb2638
        getline_is_func = 0
#10 0x000000000049cb87 in apply_autocmds_group (event=EVENT_WINCLOSED, fname=0x142d610 "1003", fname_io=0x7ffdf3bb2740 "1003", force=false, group=-3, buf=0x1411480, eap=0x0) at ../src/nvim/autocmd.c:1631
        nesting = 1
        filechangeshell_busy = 0
        sfname = 0x142d2a0 "1003"
        tail = 0x142d610 "1003"
        save_changed = false
        old_curbuf = 0x114aaf0
        retval = true
        save_sourcing_name = 0x7ffdf3bb33c0 "nvim_exec() called at command line:0"
        save_sourcing_lnum = 0
        save_autocmd_fname = 0x0
        save_autocmd_bufnr = 0
        save_autocmd_match = 0x0
        save_autocmd_busy = 0
        save_autocmd_nested = 0
        patcmd = {curpat = 0x142d200, nextcmd = 0x0, group = -3, fname = 0x142d610 "1003", sfname = 0x142d2a0 "1003", tail = 0x142d610 "1003", event = EVENT_WINCLOSED, arg_bufnr = 3, next = 0x0}
        ap = 0x142d200
        save_cmdarg = 0x0
        save_cmdbang = 0
        wait_time = 140728692582672
        did_save_redobuff = true
        save_redo = {sr_redobuff = {bh_first = {b_next = 0x0, b_str = ""}, bh_curr = 0x0, bh_index = 0, bh_space = 0}, sr_old_redobuff = {bh_first = {b_next = 0x0, b_str = ""}, bh_curr = 0x0, bh_index = 0, bh_space = 0}}
        save_KeyTyped = false
        save_current_sctx = {sc_sid = -10, sc_seq = 0, sc_lnum = 0}
        funccal_entry = {top_funccal = 0x0, next = 0x7ffdf3bb33a0}
#11 0x000000000049d97e in apply_autocmds (event=EVENT_WINCLOSED, fname=0x7ffdf3bb2740 "1003", fname_io=0x7ffdf3bb2740 "1003", force=false, buf=0x1411480) at ../src/nvim/autocmd.c:1277
No locals.
#12 0x00000000007c1704 in do_autocmd_winclosed (win=0x141d210) at ../src/nvim/window.c:2585
        recursive = true
        winid = "1003\000\000\000\000\300\063\273\363\375\177\000\000\000\000\000\000\000\000\000\001\240a\347\071\254\177", '\000' <repeats 11 times>, "\315B\001", '\000' <repeats 12 times>, "\360\252\024\001\000\000\000", <incomplete sequence \375>
#13 0x00000000007c0dd5 in win_close_othertab (win=0x141d210, free_buf=0, tp=0x13ca150) at ../src/nvim/window.c:2610
        dir = 32684
        ptp = 0x0
        free_tp = 0
#14 0x0000000000572e87 in ex_win_close (forceit=0, win=0x141d210, tp=0x13ca150) at ../src/nvim/ex_docmd.c:6543
        need_hide = 0
        buf = 0x1411480
#15 0x0000000000572fd1 in tabpage_close_other (tp=0x13ca150, forceit=0) at ../src/nvim/ex_docmd.c:6647
        done = 1
        wp = 0x141d210
        h = 1
        prev_idx = "2\000\273\363\375\177\000\000G\312V\000\002\000\000\000z\316B\001\000\000\000\000y\316B\001\000\000\000\000z\316B\001\000\000\000\000\270*\273\363\375\177\000\000\001\000\000\000\002\000\000\000\270*\273\000\002\000\000\000P"
#16 0x000000000057e10a in ex_tabclose (eap=0x7ffdf3bb2ab8) at ../src/nvim/ex_docmd.c:6568
        tab_number = 2
        tp = 0x13ca150
#17 0x000000000056a9d8 in do_one_cmd (cmdlinep=0x7ffdf3bb2e48, flags=7, cstack=0x7ffdf3bb2e50, fgetline=0x563780 <get_str_line>, cookie=0x7ffdf3bb34f8) at ../src/nvim/ex_docmd.c:1964
        p = 0x142ce7a ""
        lnum = 0
        n = 0
        errormsg = 0x0
        after_modifier = 0x142ce71 "+tabclose"
        ea = {arg = 0x142ce7a "", nextcmd = 0x0, cmd = 0x142ce72 "tabclose", cmdlinep = 0x7ffdf3bb2e48, cmdidx = CMD_tabclose, argt = 528663, skip = 0, forceit = 0, addr_count = 1, line1 = 2, line2 = 2, addr_type = ADDR_TABS, flags = 0, do_ecmd_cmd = 0x0, do_ecmd_lnum = 0, append = 0, usefilter = 0, amount = 0, regname = 0, force_bin = 0, read_edit = 0, force_ff = 0, force_enc = 0, bad_char = 0, useridx = 0, errmsg = 0x0, getline = 0x563780 <get_str_line>, cookie = 0x7ffdf3bb34f8, cstack = 0x7ffdf3bb2e50, verbose_save = -1, save_msg_silent = -1, did_esilent = 0, did_sandbox = false}
        save_msg_scroll = 1
        save_cmdmod = {split = 0, tab = 0, browse = false, confirm = false, hide = false, keepalt = false, keepjumps = false, keepmarks = false, keeppatterns = false, lockmarks = false, noswapfile = false, save_ei = 0x0, filter_regmatch = {regprog = 0x0, startp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, endp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, rm_ic = false}, filter_force = false}
        save_reg_executing = 0
        cmd = 0x142ce71 "+tabclose"
        ni = 0
#18 0x000000000056772e in do_cmdline (cmdline=0x0, fgetline=0x563780 <get_str_line>, cookie=0x7ffdf3bb34f8, flags=7) at ../src/nvim/ex_docmd.c:595
        recursive = 3
        call_depth = 3
        next_cmdline = 0x142ce70 " +tabclose"
        cmdline_copy = 0x142ce70 " +tabclose"
        used_getline = true
        msg_didout_before_start = false
        count = 2
        did_inc = 0
        retval = 1
        cstack = {cs_flags = {0 <repeats 50 times>}, cs_pending = '\000' <repeats 49 times>, cs_pend = {csp_rv = {0x0 <repeats 50 times>}, csp_ex = {0x0 <repeats 50 times>}}, cs_forinfo = {0x0 <repeats 50 times>}, cs_line = {0 <repeats 50 times>}, cs_idx = -1, cs_looplevel = 0, cs_trylevel = 0, cs_emsg_silent_list = 0x0, cs_lflags = 0}
        lines_ga = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 16, ga_growsize = 10, ga_data = 0x0}
        current_line = 0
        fname = 0x0
        breakpoint = 0x0
        dbg_tick = 0x0
        debug_saved = {trylevel = 0, force_abort = 0, caught_stack = 0x0, vv_exception = 0x0, vv_throwpoint = 0x0, did_emsg = 0, got_int = 0, need_rethrow = 0, check_cstack = 0, current_exception = 0x0}
        initial_trylevel = 1
        saved_msg_list = 0x7ffdf3bb3b40
        private_msg_list = 0x0
        cmd_getline = 0x563780 <get_str_line>
        cmd_cookie = 0x7ffdf3bb34f8
        cmd_loop_cookie = {lines_gap = 0x0, current_line = 0, repeating = 0, getline = 0x0, cookie = 0x0}
        real_cookie = 0x7ffdf3bb34f8
        getline_is_func = 0
#19 0x0000000000563711 in source_using_linegetter (cookie=0x7ffdf3bb34f8, fgetline=0x563780 <get_str_line>, traceback_name=0x8ca380 "nvim_exec()") at ../src/nvim/ex_cmds2.c:2764
        save_sourcing_name = 0x911c35 "command line"
        save_sourcing_lnum = 0
        sourcing_name_buf = "nvim_exec() called at command line:0\000\000\000\000\350\065\273\363\375\177\000\000\377\377\377\377\377\177\000\001\003\000\000\000\353\003\000\000\000\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377\000\000\000\000\000\000\000\000\n\000\000\000\062\000\000\000\000\000\000\000\000\000$@\000\000\000\000\000\000$@\000\000\000\000\000\000\000\000\000\001\000\000\062", '\000' <repeats 19 times>, "P\345\207\071\254\177\000\000\220\064\273\363\375\177\000\000\000dD\000\000\000\000\000c\353a\000\000\000\000\000\030\000\000\000\000\000\000\000p\320A\001\000\000\000\000\030\000\000\000\000\000\000\000"...
        save_current_sctx = {sc_sid = -3, sc_seq = 0, sc_lnum = 0}
        entry = {top_funccal = 0x0, next = 0x0}
        retval = 0
#20 0x00000000005635cf in do_source_str (cmd=0x141d070 "tabprevious | +tabclose", traceback_name=0x8ca380 "nvim_exec()") at ../src/nvim/ex_cmds2.c:2782
        cookie = {buf = 0x141d070 "tabprevious | +tabclose", offset = 24}
#21 0x000000000048c19b in nvim_exec (src=..., output=false, err=0x7ffdf3bb35e8) at ../src/nvim/api/vim.c:110
        save_msg_silent = 0
        save_capture_ga = 0x0
        capture_local = {ga_len = 23, ga_maxlen = 0, ga_itemsize = 21090416, ga_growsize = 0, ga_data = 0x17}
#22 0x000000000044cd48 in nlua_msgpack_nvim_exec (lstate=0x7fac3987e380) at src/nvim/auto/msgpack_lua_c_bindings.generated.c:1882
        err = {type = kErrorTypeNone, msg = 0x0}
        arg2 = false
        arg1 = {data = 0x141d070 "tabprevious | +tabclose", size = 23}
        ret = {data = 0x0, size = 0}
#23 0x000000000085c9bd in lj_BC_FUNCC ()
No symbol table info available.
#24 0x00000000008424a0 in lua_pcall (L=0x7fac3987e380, nargs=<optimized out>, nresults=<optimized out>, errfunc=<optimized out>) at lj_api.c:1169
        g = 0x7fac3987e3e0
        oldh = <optimized out>
        ef = 0
        status = <optimized out>
#25 0x00000000005e88fe in nlua_exec_file (path=0x13b7688 "./minimal.lua") at ../src/nvim/lua/executor.c:1420
        lstate = 0x7fac3987e380
#26 0x00000000005e8888 in ex_luafile (eap=0x7ffdf3bb3808) at ../src/nvim/lua/executor.c:1402
No locals.
#27 0x000000000056a9d8 in do_one_cmd (cmdlinep=0x7ffdf3bb3b98, flags=10, cstack=0x7ffdf3bb3ba0, fgetline=0x0, cookie=0x0) at ../src/nvim/ex_docmd.c:1964
        p = 0x13b7687 " ./minimal.lua"
        lnum = -1063752452066765312
        n = 0
        errormsg = 0x0
        after_modifier = 0x13b7680 "luafile ./minimal.lua"
        ea = {arg = 0x13b7688 "./minimal.lua", nextcmd = 0x0, cmd = 0x13b7680 "luafile ./minimal.lua", cmdlinep = 0x7ffdf3bb3b98, cmdidx = CMD_luafile, argt = 524445, skip = 0, forceit = 0, addr_count = 0, line1 = 1, line2 = 1, addr_type = ADDR_LINES, flags = 0, do_ecmd_cmd = 0x0, do_ecmd_lnum = 0, append = 0, usefilter = 0, amount = 0, regname = 0, force_bin = 0, read_edit = 0, force_ff = 0, force_enc = 0, bad_char = 0, useridx = 0, errmsg = 0x0, getline = 0x0, cookie = 0x0, cstack = 0x7ffdf3bb3ba0, verbose_save = -1, save_msg_silent = -1, did_esilent = 0, did_sandbox = false}
        save_msg_scroll = 1
        save_cmdmod = {split = 0, tab = 0, browse = false, confirm = false, hide = false, keepalt = false, keepjumps = false, keepmarks = false, keeppatterns = false, lockmarks = false, noswapfile = false, save_ei = 0x0, filter_regmatch = {regprog = 0x0, startp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, endp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, rm_ic = false}, filter_force = false}
        save_reg_executing = 0
        cmd = 0x13b7680 "luafile ./minimal.lua"
        ni = 0
#28 0x000000000056772e in do_cmdline (cmdline=0x7ffdf3bb4e6f "luafile ./minimal.lua", fgetline=0x0, cookie=0x0, flags=10) at ../src/nvim/ex_docmd.c:595
        recursive = 3
        call_depth = 3
        next_cmdline = 0x13b7680 "luafile ./minimal.lua"
        cmdline_copy = 0x13b7680 "luafile ./minimal.lua"
        used_getline = false
        msg_didout_before_start = false
        count = 1
        did_inc = 0
        retval = 1
        cstack = {cs_flags = {0 <repeats 50 times>}, cs_pending = '\000' <repeats 49 times>, cs_pend = {csp_rv = {0x0 <repeats 50 times>}, csp_ex = {0x0 <repeats 50 times>}}, cs_forinfo = {0x0 <repeats 50 times>}, cs_line = {0 <repeats 50 times>}, cs_idx = -1, cs_looplevel = 0, cs_trylevel = 0, cs_emsg_silent_list = 0x0, cs_lflags = 0}
        lines_ga = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 16, ga_growsize = 10, ga_data = 0x0}
        current_line = 0
        fname = 0x0
        breakpoint = 0x0
        dbg_tick = 0x0
        debug_saved = {trylevel = 0, force_abort = 0, caught_stack = 0x0, vv_exception = 0x0, vv_throwpoint = 0x0, did_emsg = 0, got_int = 0, need_rethrow = 0, check_cstack = 0, current_exception = 0x0}
        initial_trylevel = 0
        saved_msg_list = 0x0
        private_msg_list = 0x0
        cmd_getline = 0x0
        cmd_cookie = 0x0
        cmd_loop_cookie = {lines_gap = 0x0, current_line = 0, repeating = 0, getline = 0x0, cookie = 0x0}
        real_cookie = 0x0
        getline_is_func = 0
#29 0x0000000000568614 in do_cmdline_cmd (cmd=0x7ffdf3bb4e6f "luafile ./minimal.lua") at ../src/nvim/ex_docmd.c:284
No locals.
#30 0x00000000005f2af3 in exe_commands (parmp=0x7ffdf3bb41f0) at ../src/nvim/main.c:1730
        i = 0
#31 0x00000000005f003b in main (argc=5, argv=0x7ffdf3bb43f8) at ../src/nvim/main.c:508
        fname = 0x0
        params = {argc = 5, argv = 0x7ffdf3bb43f8, use_vimrc = 0x7ffdf3bb4e69 "NORC", clean = false, n_commands = 2, commands = {0x7ffdf3bb4e6f "luafile ./minimal.lua", 0x7ffdf3bb4e86 "quitall!", 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, cmds_tofree = "\000\000\000\000\000\000\000\000\000", n_pre_commands = 0, pre_commands = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, edit_type = 0, tagname = 0x0, use_ef = 0x0, input_isatty = true, output_isatty = true, err_isatty = true, input_neverscript = false, no_swap_file = 0, use_debug_break_level = -1, window_count = 1, window_layout = 0, diff_mode = 0, listen_addr = 0x0}
        cwd = 0x0
        use_remote_ui = false
        use_builtin_ui = true
```

</details>

### PR DESCRIPTION
**Pull request by notomo**
Fix #15313 

📝 test output before fix
```
[ RUN      ] API/win close does not make tabpage invalid even if close floating window from other tabpage: -- Tests exited non-zero: SIGPIPE
-- No output to stderr.
CMake Error at /home/notomo/workspace/neovim/cmake/RunTests.cmake:85 (message):
  functional tests failed with error: SIGPIPE
```

### CODE REVIEW

File: test/functional/api/window_spec.lua [hunk 1]
```diff
@@ -347,6 +347,19 @@ describe('API/win', function()
       eq(2, #meths.list_wins())
       eq('', funcs.getcmdwintype())
     end)
+
+    it('does not make tabpage invalid even if close floating window from other tabpage', function()
```
Comment (justinmk) [inline test/functional/api/window_spec.lua:351]:
```suggestion
    it('closing current (float) window of another tabpage #15313', function()
```

File: test/functional/api/window_spec.lua [hunk 2]
```diff
@@ -347,6 +347,19 @@ describe('API/win', function()
...
+      command('tabedit')
```
Comment (justinmk) [inline test/functional/api/window_spec.lua:352]:
```suggestion
      command('tabedit')
      eq(2, eval('tabpagenr()'))
```

File: test/functional/api/window_spec.lua [hunk 3]
```diff
@@ -347,6 +347,19 @@ describe('API/win', function()
...
+      local win = meths.open_win(0, true, {
+        relative='editor', row=10, col=10, width=50, height=10
+      })
+      local tabpage = eval('tabpagenr()')
+      command('tabprevious')
```
Comment (justinmk) [inline test/functional/api/window_spec.lua:357]:
```suggestion
      command('tabprevious')
      eq(1, eval('tabpagenr()'))
```

File: test/functional/api/window_spec.lua [hunk 4]
```diff
@@ -347,6 +347,19 @@ describe('API/win', function()
...
+      meths.win_close(win, false)
+
+      meths.tabpage_get_win(tabpage)
```
Comment (justinmk) [inline test/functional/api/window_spec.lua:360]:
```suggestion
      eq(1000, meths.tabpage_get_win(tabpage))
```

File: test/functional/api/window_spec.lua [hunk 5]
```diff
@@ -347,6 +347,21 @@ describe('API/win', function()
...
+      eq(2, eval('tabpagenr()'))
+      local win = meths.open_win(0, true, {
+        relative='editor', row=10, col=10, width=50, height=10
+      })
+      local tabpage = eval('tabpagenr()')
+      command('tabprevious')
+      eq(1, eval('tabpagenr()'))
+      meths.win_close(win, false)
+
+      eq(1000, meths.tabpage_get_win(tabpage))
```
Comment (justinmk) [inline test/functional/api/window_spec.lua:362]:
```suggestion
      eq({ 1001 }, meths.tabpage_get_win(tabpage))
```

Comment (justinmk) [inline test/functional/api/window_spec.lua:362]: this is failing, and the linux CI failures look like maybe a crash?

Comment (notomo) [reply test/functional/api/window_spec.lua]: Thanks!
I found failure from `linux asan (cc=clang-12)`'s `View raw logs` and fixed it.
But I'm not sure why `.id` is needed.

https://pipelines.actions.githubusercontent.com/OAGhSzOoyagEUMnWXOouBvclYp4jdxeDQMweYOrPWiuB3OOcSA/_apis/pipelines/1/runs/7579/signedlogcontent/5?urlExpires=2021-08-22T21%3A51%3A33.8371685Z&urlSigningMethod=HMACV1&urlSignature=uIAyclUybrHzLFZIMkxjsPEVmisdNxq%2BkMMgFG6BQKk%3D
```
2021-08-22T16:22:17.2166679Z [1m[31m[  ERROR   ][0m[0m [36mtest/functional/api/window_spec.lua[0m @ [36m351[0m: [1mAPI/win close closing current (float) window of another tabpage #15313[0m
2021-08-22T16:22:17.2167520Z test/helpers.lua:73: Expected objects to be the same.
2021-08-22T16:22:17.2167983Z Passed in:
2021-08-22T16:22:17.2168350Z (table: 0x7f1f19d414b8) {
2021-08-22T16:22:17.2168694Z   [id] = 1001 }
2021-08-22T16:22:17.2169004Z Expected:
2021-08-22T16:22:17.2169336Z (number) 1000
```

Comment (justinmk) [reply test/functional/api/window_spec.lua]: I think that error is indicating that the test framework thinks nvim_tabpage_get_win() is returning a list-like table.

    eq({ 1001 }, meths.tabpage_get_win(tabpage))
