### PR TITLE
fix(extmarks): fix signs

### LINKED ISSUE #17638: Virtual text + relativenumber rendering issues
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1203-gc3cc17f0e

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch linux

### Terminal name/version

Kitty 0.24.4

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

 `nvim -u init.lua`

```lua
-- init.lua
vim.wo.number = true
vim.wo.relativenumber = true

vim.cmd [[normal 20ohello]]
vim.cmd [[normal ithis is weird]]

vim.api.nvim_buf_set_extmark(
    0,
    vim.api.nvim_create_namespace("foo"),
    1,
    0,
    {virt_text = {{"hello", "String"}}, virt_text_pos = "overlay", hl_mode = "combine", virt_text_win_col = 20, priority = 1}
)
```

### Expected behavior

Virtual text is displayed normally.

### Actual behavior

The line with the virtual text has render artifacts from the line the cursor is on.

https://user-images.githubusercontent.com/12900252/157021012-f829d574-f2b3-427d-ae0e-3ae42bfe8a20.mp4

### PR DESCRIPTION
**Pull request by lewis6991**
Don't add sign extmarks to state->active. Instead when drawing signs,
    perform a full line scan for sign marks. This allows decor_redraw_line
    to be moved back inside the `!number_only` block in screen.c, which
    prevents decor scans when redrawing the number column when
    'relativenumber' is set.

Fixes: #17638

### CODE REVIEW

File: test/functional/ui/decorations_spec.lua [hunk 1]
```diff
@@ -1634,4 +1634,87 @@ l5
...
+      X Y Z W {3:a} {3:b} {3:c} {3:d} {3:e} {3:f} {3:g} {3:h}                 |
+      X Y Z W {3:a} {3:b} {3:c} {3:d} {3:e} {3:f} {3:g} {3:h}                 |
+      X Y Z W {3:a} {3:b} {3:c} {3:d} {3:e} {3:f} {3:g} {3:h}                 |
+      X Y Z W {3:a} {3:b} {3:c} {3:d} {3:e} {3:f} {3:g} {3:h}                 |
+      X Y Z W {3:a} {3:b} {3:c} {3:d} {3:e} {3:f} {3:g} {3:h}                 |
+      X Y Z W {3:a} {3:b} {3:c} {3:d} {3:e} {3:f} {3:g} {3:h}                 |
+      X Y Z W {3:a} {3:b} {3:c} {3:d} {3:e} {3:f} {3:g} {3:^h}                 |
+                                              |
+    ]], attr_ids={
+      [1] = {background = Screen.colors.Grey, foreground = Screen.colors.DarkBlue};
```
Comment (bfredl) [inline test/functional/ui/decorations_spec.lua:1668]: add to the ` screen:set_default_attr_ids` table in the describe block.

File: test/functional/ui/decorations_spec.lua [hunk 2]
```diff
@@ -1634,4 +1634,87 @@ l5
...
+    ]]
+
+    local ns = meths.create_namespace('test')
+
+    meths.buf_set_extmark(0, ns, 2, 0, {
+      virt_text = {{"hello", "String"}},
+      virt_text_win_col = 20,
+    })
+
+    -- Trigger a screen update
```
Comment (bfredl) [inline test/functional/ui/decorations_spec.lua:1698]: I'd suggest adding a `screen:expect` before this. and then just do `'j'` here so we test the effect of both a normal screen update and then of a "number only" update.

Comment (lewis6991) [reply test/functional/ui/decorations_spec.lua]: I did `kj`, so I could re-use the same grid.

File: test/functional/ui/decorations_spec.lua [hunk 3]
```diff
@@ -1634,4 +1635,90 @@ l5
...
+      {3:~                                                 }|
+      {3:~                                                 }|
+      {3:~                                                 }|
+                                                        |
+    ]]
+
+    screen:expect{grid=grid}
+
+    -- Trigger a screen update
+    feed('kj')
```
Comment (bfredl) [inline test/functional/ui/decorations_spec.lua:1719]: do we really need to get back to the same line? otherwise just `k` would be more robust.

Comment (lewis6991) [reply test/functional/ui/decorations_spec.lua]: We don't need to, I just thought re-using the grid was slightly better from a maintenance POV.

What makes it more robust? The fact we are only triggering 1 redraw?

If we want to be particular about it, couldn't we use something like `'redrawdebug'` to check specifically what cells are being redrawn? If so, do you know if we have any existing test that do this?

Comment (bfredl) [reply test/functional/ui/decorations_spec.lua]: Grids in tests doesn't "cost" anything, at least not to the extent that we should make tests weaker just so that we can play code golf with test code. Grids are trivial to make, and remake alike whenever there is an intended change of behavior.

As a concrete example the second test would trivially pass even if "number only" redraws nothing, with a change we at least see that it actually redraws numbers correctly on cursor move.

Comment (lewis6991) [reply test/functional/ui/decorations_spec.lua]: Ok sure. It just wasn't clear to me how it was weaker, but it is now, thanks. I already made the change regardless.
