### PR TITLE
[RDY] Fix some regressions

### LINKED ISSUE #3538: when neomake plugin is loaded neovim crashes on entering 04
reproduce:
put neomake in your init.vim. (i use vimplug, but that's not relevant, i think)
start nvim
enter 
```vim
04
```
wait a few seconds:
nvim: /build/neovim-H96Rof/neovim-0.0.0+git201510270507+1948+14~ubuntu14.04.1/src/nvim/os/input.c:87: create_cursorhold_event: Assertion `queue_empty(loop.events)' failed.
Aborted

### PR DESCRIPTION
**Pull request by tarruda**
Close #3538 #3547

### CODE REVIEW

File: src/nvim/os/input.c [hunk 1]
```diff
@@ -82,9 +82,11 @@ static void cursorhold_event(void **argv)
...
 static void create_cursorhold_event(void)
 {
-  // If the queue had any items, this function should not have been
-  // called(inbuf_poll would return kInputAvail)
-  assert(queue_empty(loop.events));
+  // If events are enabled and the queue has any items, this function should not
+  // have been called(inbuf_poll would return kInputAvail)
+  // TODO(tarruda): Cursorhold should be implemented as a timer set during the
+  // `state_check` callback for the states where it can be triggered.
+  assert(!events_enabled || queue_empty(loop.events));
```
Comment (oni-link) [inline src/nvim/os/input.c]: Do we still need this `assert()`? If events are enabled we already know that `loop.events` is empty. Or could the call `ui_flush()` in `state_enter()` fill the queue before `os_inchar()` is called?

Comment (tarruda) [inline src/nvim/os/input.c]: This assert is just to document the state of these variables. I added it because this is a confusing place to implement of cursorhold(But is required for now, cursorhold is still triggered when getting the count in `normal_execute` for example).

When [further refactoring](https://github.com/neovim/neovim/issues/3382#issuecomment-151290282) is performed, I will be able to move cursorhold triggering to the state_enter layer, possibly as a `VimState` flag that enables or disables a cursorhold timer before blocking for keys.
