### PR TITLE
fix(windows): treat powershell as not-Unix-like in Windows

### LINKED ISSUE #21045: Windows: exepath() misses extension in powershell & pwsh
### Neovim version (nvim -v)

0.8.0, gd367ed9b2

### Vim (not Nvim) behaves the same?

no, 9.0.868

### Operating system/version

Windows 11

#### Prepare
Go to a folder which is in PATH, create a file called `test` and one called `test.bat`.
`(Get-Command test).Path` test should return the path to `test.bat`

#### using nvim

nvim --clean
:set shell=powershell
:echo exepath("test")

### Expected behavior

Returns `<path_to_test>\test.bat`.

### Actual behavior

Returns `<path_to_test>\test`.

Further explanation:
Powershell prefers to use the bat file, which can be seen from using `(Get-Command test).Path`. When the shell option is not set to `pwsh` or `powershell` (rather set to `cmd`), exepath('test') outputs `test.bat` as expected. 
This behaviour is different to vim, as there the bat path is returned correctly with each shell.

Maybe, the PATHEXT variable has to be used for powershell / pwsh too?

I've found this issue https://github.com/vim/vim/pull/6115 before actually testing my issue on vim vs neovim. It might be related to the matter.

### PR DESCRIPTION
**Pull request by akriese**
Fixes #21045.

This takes part of vim patch [v8.2.3071](https://github.com/vim/vim/commit/127950241e84c822d3c50f46a00d42a70d2d5cb6) to make `pwsh` and `powershell` return the same `exepath()`s (including extensions) as `cmd.exe`.

### CODE REVIEW

**Comment by justinmk** [comment]
cc @3N4N

File: src/nvim/os/fs.c [hunk 1]
```diff
@@ -302,7 +302,9 @@ static bool is_executable(const char *name, char **abspath)
 static bool is_executable_ext(const char *name, char **abspath)
   FUNC_ATTR_NONNULL_ARG(1)
 {
-  const bool is_unix_shell = strstr((char *)path_tail(p_sh), "sh") != NULL;
+  const bool is_unix_shell = strstr((char *)path_tail(p_sh), "powershell") == NULL
+                             && strstr((char *)path_tail(p_sh), "pwsh") == NULL
+                             && strstr((char *)path_tail(p_sh), "sh") != NULL;
```
Comment (3N4N) [inline src/nvim/os/fs.c:307]: No need to cast into `char *` since `path_tail` already returns a char pointer.  In Vim's source, they needed to cast because `gettail`, Vim's equivalent of `path_tail`, returns a `char_u *`<sup>[1]</sup>.

```suggestion
  const bool is_unix_shell = strstr(path_tail(p_sh), "powershell") == NULL
                             && strstr(path_tail(p_sh), "pwsh") == NULL
                             && strstr(path_tail(p_sh), "sh") != NULL;
```

[1]: https://github.com/vim/vim/blob/4ae0057308c59a0dee2b452736366e49a5a98b3a/src/filepath.c#L2886-L2887

**Comment by 3N4N** [comment]
By the way, the Windows CI failure must've been a flake.  It passed fine on [my fork][1].

[1]: https://github.com/3N4N/neovim/actions/runs/3662892446/jobs/6192300808

**Comment by 3N4N** [comment]
Do we not want extensionless file to be found with `:h exepath()`?

After this patch, the binary files 'text.exe', 'test.bat', 'test.com' will be found, but the file 'test' (without any extension) will not be found.  But both `where` and `Get-Command` find the extensionless 'test' file.

But neovim with ':set shell=cmd', doesn't find 'test' either (without applying this patch), even though `where test` returns correct path in cmd.  So I don't know what should be the expected behavior.

**Comment by akriese** [comment]
So, as I understand it, if `exepath()` is supposed to only return executables and windows does not define extension-less files as executable, this would be the desired behavior, right? Even if the result diverges from `Get-Command`...

**Comment by 3N4N** [comment]
> this would be the desired behavior, right?

Right.  As it stands now, exepath in this PR behaves correctly.

**Comment by musjj** [comment]
Would it be a good idea if `bash.exe` (MSYS2, Git Bash, etc.) also receive the same kind of treatment?
My use-case is that I'm using `exepath` in order to find `*.bat`/`*.cmd` files, but with `shell` set to `bash.exe`, the correct path isn't returned.
Actually, why does `exepath` depend on your `shell` option in the first place? Why not just query the user's OS?

**Comment by justinmk** [comment]
> But with `shell` set to `bash.exe`, the correct path isn't returned.
> Actually, why does `exepath` depend on your `shell` option in the first place? Why not just query the user's OS?

in Git bash on windows, files without ".exe" suffix can be executable, right? 

> After this patch, the binary files 'text.exe', 'test.bat', 'test.com' will be found, but the file 'test' (without any extension) will not be found. But both `where` and `Get-Command` find the extensionless 'test' file.
> 
> But neovim with ':set shell=cmd', doesn't find 'test' either (without applying this patch), even though `where test` returns correct path in cmd. So I don't know what should be the expected behavior.
> 
> **Edit**: `where` is a program to find files in general, not just executable files. And `Get-Command` returning extensionless (and thus non-executable) file is puzzling even to Chris Dent, [the resident PowerShell expert](https://www.amazon.com/Mastering-PowerShell-Scripting-Automate-environment-ebook/dp/B0971MG88X) (I asked him on Discord). So I say `exepath()` should _not_ find extensionless files, even if it doesn't coincide with what `where` and `Get-Command` do.

Great info, thanks! So what is the 3-line conclusion here? Please include it in the commit message.

**Comment by musjj** [comment]
> In Git bash on windows, files without ".exe" suffix can be executable, right?

Not completely sure of the specs, but I think only script (bash, sh, etc.) executables can have no extension in Git Bash. Binary executables require `.exe` just like usual.

**Comment by 3N4N** [comment]
> > After this patch, the binary files 'text.exe', 'test.bat', 'test.com' will be found, but the file 'test' (without any extension) will not be found. But both `where` and `Get-Command` find the extensionless 'test' file.
> > But neovim with ':set shell=cmd', doesn't find 'test' either (without applying this patch), even though `where test` returns correct path in cmd. So I don't know what should be the expected behavior.
> > **Edit**: `where` is a program to find files in general, not just executable files. And `Get-Command` returning extensionless (and thus non-executable) file is puzzling even to Chris Dent, [the resident PowerShell expert](https://www.amazon.com/Mastering-PowerShell-Scripting-Automate-environment-ebook/dp/B0971MG88X) (I asked him on Discord). So I say `exepath()` should _not_ find extensionless files, even if it doesn't coincide with what `where` and `Get-Command` do.
> 
> Great info, thanks! So what is the 3-line conclusion here? Please include it in the commit message.

I'm not the author of this PR, but it should be something like this:
```
BREAKING!: exepath() does not return extentionless files in Windows with
PowerShell as shell.
```

**Comment by 3N4N** [comment]
@akriese sorry for the confusion but I didn't mean the full commit should be replaced by my suggestion.  It should've been appended, like the message of commit [`0405594`][1].

But don't change it again now.  I'm sure the maintainer will edit the commit message before merging if it needs editing.

[1]: https://github.com/neovim/neovim/commit/0405594399741babd6d935d581eac2584b289f92

File: src/nvim/os/fs.c [hunk 2]
```diff
@@ -302,7 +302,9 @@ static bool is_executable(const char *name, char **abspath)
 static bool is_executable_ext(const char *name, char **abspath)
   FUNC_ATTR_NONNULL_ARG(1)
 {
-  const bool is_unix_shell = strstr((char *)path_tail(p_sh), "sh") != NULL;
+  const bool is_unix_shell = strstr(path_tail(p_sh), "powershell") == NULL
+                             && strstr(path_tail(p_sh), "pwsh") == NULL
+                             && strstr(path_tail(p_sh), "sh") != NULL;
```
Comment (justinmk) [inline src/nvim/os/fs.c:307]: This also affects powershell in non-Windows system.

Comment (3N4N) [reply src/nvim/os/fs.c:307]: There is an `ifdef mswin` right above the function, though.

**Comment by justinmk** [comment]
ported vim-patch 8.2.3071 and related patches to avoid needing to revisit this in the future. 8.2.3071 is mostly N/A because all the magic special-case bullshit is not something we want.

**Comment by zeertzjq** [comment]
Some other related patches: #19313

**Comment by justinmk** [comment]
> We need a test case in `test/functional/vimscript/exepath_spec.lua` .

Merged to unblock, but it would still be helpful to have this test @akriese

**Comment by akriese** [comment]
I just created this test. First time writing a test for neovim, so forgive me, if I did something wrong. Unfortunately, I don't know how to run the test on Windows with `is_os('win')` evaluating to true. I am running with `mingw32-make functionaltest` and it fails because it thinks, that I am on a not-Windows machine.

**Comment by 3N4N** [comment]
> I am running with mingw32-make functionaltest and it fails because it thinks, that I am on a not-Windows machine.

I suggest using cmake for everything.  Neovim is a cmake project; the makefile provided with it is only for convenience, and I don't think it's catered too much to Windows devs.  What I do is use something like these:

```
PS> cmake -E env DEPS_BUILD_DIR=E:/projects/neovim/deps cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:/apps/nvim -DCMAKE_C_COMPILER=clang -DCMAKE_C_FLAGS=-w -B .\build\debug

PS> cmake --build .\build\debug

PS> cmake -E env TEST_FILE=.\test\functional\path\to\your\test\file.lua cmake --build .\build\debug functionaltest
```

I'm not gonna explain what's happening in the commands above.  You should be able to figure out with a little bit of time.

> Edit: Also, the test for set shell=pwsh.exe will probably fail, if that version of Powershell is not installed on the system (don't know if it is installed by default)

There is a helper function in the test suite called [`set_shell_powershell`][1].  Grep and see how it's used.

[1]: https://github.com/neovim/neovim/blob/8a4285d5637c146a0ae606918a8e77063c6a5f0d/test/functional/ex_cmds/make_spec.lua#L21

**Comment by 3N4N** [comment]
Also, @akriese you should do this in a new PR.

**Comment by justinmk** [comment]
> What I do is use something like these:
> 
> ```
> PS> cmake -E env DEPS_BUILD_DIR=E:/projects/neovim/deps cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:/apps/nvim -DCMAKE_C_COMPILER=clang -DCMAKE_C_FLAGS=-w -B .\build\debug
> 
> PS> cmake --build .\build\debug
> 
> PS> cmake -E env TEST_FILE=.\test\functional\path\to\your\test\file.lua cmake --build .\build\debug --target functionaltest
> ```

see also https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msvc-powershell (@3N4N any improvements to make there?)

**Comment by akriese** [comment]
> > What I do is use something like these:
> > ```
> > PS> cmake -E env DEPS_BUILD_DIR=E:/projects/neovim/deps cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:/apps/nvim -DCMAKE_C_COMPILER=clang -DCMAKE_C_FLAGS=-w -B .\build\debug
> > 
> > PS> cmake --build .\build\debug
> > 
> > PS> cmake -E env TEST_FILE=.\test\functional\path\to\your\test\file.lua cmake --build .\build\debug --target functionaltest
> > ```
> 
> see also https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msvc-powershell (@3N4N any improvements to make there?)

I used the instructions in the README aswell as @3N4N's commands. Didn't work out of the box, maybe my environment has some issue. It eventually worked out for me when explicitly passing the `LUAJIT_LIB` path to the cmake command ([my build script](https://github.com/akriese/dotfiles/blob/main/neovim_build.ps1))
