### PR TITLE
Fix test failures found in Debian builds

### LINKED ISSUE #7522: Test failures in 0.2.1 from Debian's builds
0.2.1 has been uploaded to Debian and there are various [build/test failures](https://buildd.debian.org/status/logs.php?pkg=neovim&ver=0.2.1-2&suite=sid).  As I have time, I'll perform triage on the available porterboxes I have access to, but don't let that stop you from offering ideas/fixes. :)

Here's a breakdown of what's happened for tracking purposes, along with potentially relevant information.

---
### [armel](https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=armel&ver=0.2.1-2&stamp=1510204415&raw=0)
* LuaJIT build
```
test/functional/api/highlight_spec.lua[0m @ [36m35[0m: [1mhighlight api nvim_get_hl_by_id[0m
...W7Xi/neovim-0.2.1/test/functional/api/highlight_spec.lua:46: Expected objects to be the same.
Passed in:
(string) 'Invalid highlight id: 7671724'
Expected:
(string) 'Invalid highlight id: 30000'

stack traceback:
	...W7Xi/neovim-0.2.1/test/functional/api/highlight_spec.lua:46: in function <...W7Xi/neovim-0.2.1/test/functional/api/highlight_spec.lua:35>
```

---
### [armhf](https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=armhf&ver=0.2.1-2&stamp=1510204523&raw=0)
* LuaJIT build
```
test/functional/api/highlight_spec.lua[0m @ [36m35[0m: [1mhighlight api nvim_get_hl_by_id[0m
...SLtd/neovim-0.2.1/test/functional/api/highlight_spec.lua:46: Expected objects to be the same.
Passed in:
(string) 'Invalid highlight id: 6389676'
Expected:
(string) 'Invalid highlight id: 30000'

stack traceback:
	...SLtd/neovim-0.2.1/test/functional/api/highlight_spec.lua:46: in function <...SLtd/neovim-0.2.1/test/functional/api/highlight_spec.lua:35>
```

---
### [mips](https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=mips&ver=0.2.1-2&stamp=1510204511&raw=0)
* LuaJIT build
```
test/functional/api/highlight_spec.lua[0m @ [36m35[0m: [1mhighlight api nvim_get_hl_by_id[0m
...GU7g/neovim-0.2.1/test/functional/api/highlight_spec.lua:46: Expected objects to be the same.
Passed in:
(string) 'Invalid highlight id: 53'
Expected:
(string) 'Invalid highlight id: 30000'

stack traceback:
	...GU7g/neovim-0.2.1/test/functional/api/highlight_spec.lua:46: in function <...GU7g/neovim-0.2.1/test/functional/api/highlight_spec.lua:35>
```

---
### [mips64el](https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=mips64el&ver=0.2.1-2&stamp=1510204554&raw=0)
* LuaJIT build
  * mips64el support is still pretty new for LuaJIT, so I may switch this build back to Lua and see if that helps

This caused _tons_ of test failures.  The example below is just the first one.  I'm ignoring other test failures in this build for now, since it's unclear if they're related to this issue.
```
/usr/share/lua/5.1/busted/block.lua:22: attempt to index field 'env' (a nil value)

stack traceback:
	/usr/bin/busted:3: in main chunk
```

---
### [mipsel](https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=mipsel&ver=0.2.1-2&stamp=1510205124&raw=0)
* LuaJIT build
```
test/functional/api/highlight_spec.lua[0m @ [36m35[0m: [1mhighlight api nvim_get_hl_by_id[0m
...uMp6/neovim-0.2.1/test/functional/api/highlight_spec.lua:46: Expected objects to be the same.
Passed in:
(string) 'Invalid highlight id: 53'
Expected:
(string) 'Invalid highlight id: 30000'

stack traceback:
	...uMp6/neovim-0.2.1/test/functional/api/highlight_spec.lua:46: in function <...uMp6/neovim-0.2.1/test/functional/api/highlight_spec.lua:35>
```

```
test/functional/terminal/cursor_spec.lua[0m @ [36m62[0m: [1mterminal cursor with number column is positioned correctly when focused[0m
./test/functional/ui/screen.lua:302: Row 2 did not match.
Expected:
  |{7:  1 }tty ready                                     |
  |*{7:  2 }{1: }                                             |
  |{7:  3 }                                              |
  |{7:  4 }                                              |
  |{7:  5 }                                              |
  |{7:  6 }                                              |
  |{3:-- TERMINAL --}                                    |
Actual:
  |{7:  1 }tty ready                                     |
  |*{7:  2 }rows: 6, cols: 46                             |
  |{7:  3 }{1: }                                             |
  |{7:  4 }                                              |
  |{7:  5 }                                              |
  |{7:  6 }                                              |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	./test/functional/ui/screen.lua:302: in function 'wait'
	./test/functional/ui/screen.lua:216: in function 'expect'
	...p6/neovim-0.2.1/test/functional/terminal/cursor_spec.lua:65: in function <...p6/neovim-0.2.1/test/functional/terminal/cursor_spec.lua:62>
```

```
test/functional/terminal/window_spec.lua[0m @ [36m16[0m: [1mterminal window with 'number' wraps text[0m
./test/functional/ui/screen.lua:302: Row 4 did not match.
Expected:
  |{7:       1 }tty ready                                |
  |{7:       2 }rows: 6, cols: 48                        |
  |{7:       3 }abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNO|
  |*{7:       4 }WXYZ abcdefghijklmnopqrstuvwxyzABCDEFGHIJ|
  |{7:       5 }KLMNOPQRSTUVWXYZrows: 6, cols: 41        |
  |{7:       6 }{1: }                                        |
  |{3:-- TERMINAL --}                                    |
Actual:
  |{7:       1 }tty ready                                |
  |{7:       2 }rows: 6, cols: 48                        |
  |{7:       3 }abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNO|
  |*{7:       4 }WXYZrows: 6, cols: 41                    |
  |{7:       5 } abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMN|
  |{7:       6 }OPQRSTUVWXYZ{1: }                            |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	./test/functional/ui/screen.lua:302: in function 'wait'
	./test/functional/ui/screen.lua:216: in function 'expect'
	...p6/neovim-0.2.1/test/functional/terminal/window_spec.lua:47: in function <...p6/neovim-0.2.1/test/functional/terminal/window_spec.lua:16>
```

---
### [ppc64el](https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=ppc64el&ver=0.2.1-2&stamp=1510203863&raw=0)
* Lua build
```
test/functional/terminal/tui_spec.lua[0m @ [36m408[0m: [1mtui 't_Co' (terminal colors) no TERM uses 8 colors[0m
...O/neovim-0.2.1/test/functional/terminal/tui_spec.lua:381: bad argument #2 to 'format' (string expected, got nil)

stack traceback:
	...O/neovim-0.2.1/test/functional/terminal/tui_spec.lua:381: in function 'assert_term_colors'
	...O/neovim-0.2.1/test/functional/terminal/tui_spec.lua:409: in function <...O/neovim-0.2.1/test/functional/terminal/tui_spec.lua:408>
```

---
### [alpha](https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=alpha&ver=0.2.1-2&stamp=1510205067&raw=0)
* Lua build
```
test/functional/terminal/cursor_spec.lua[0m @ [36m62[0m: [1mterminal cursor with number column is positioned correctly when focused[0m
./test/functional/ui/screen.lua:302: Row 2 did not match.
Expected:
  |{7:  1 }tty ready                                     |
  |*{7:  2 }{1: }                                             |
  |{7:  3 }                                              |
  |{7:  4 }                                              |
  |{7:  5 }                                              |
  |{7:  6 }                                              |
  |{3:-- TERMINAL --}                                    |
Actual:
  |{7:  1 }tty ready                                     |
  |*{7:  2 }rows: 6, cols: 46                             |
  |{7:  3 }{1: }                                             |
  |{7:  4 }                                              |
  |{7:  5 }                                              |
  |{7:  6 }                                              |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	./test/functional/ui/screen.lua:302: in function 'wait'
	./test/functional/ui/screen.lua:216: in function 'expect'
	...eovim-0.2.1/test/functional/terminal/cursor_spec.lua:65: in function <...eovim-0.2.1/test/functional/terminal/cursor_spec.lua:62>
```

```
test/functional/terminal/tui_spec.lua[0m @ [36m408[0m: [1mtui 't_Co' (terminal colors) no TERM uses 8 colors[0m
...j/neovim-0.2.1/test/functional/terminal/tui_spec.lua:381: bad argument #2 to 'format' (string expected, got nil)

stack traceback:
	...j/neovim-0.2.1/test/functional/terminal/tui_spec.lua:381: in function 'assert_term_colors'
	...j/neovim-0.2.1/test/functional/terminal/tui_spec.lua:409: in function <...j/neovim-0.2.1/test/functional/terminal/tui_spec.lua:408>
```

---
### [hppa](https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=hppa&ver=0.2.1-2&stamp=1510211184&raw=0)
* Lua build
```
test/functional/api/highlight_spec.lua[0m @ [36m35[0m: [1mhighlight api nvim_get_hl_by_id[0m
.../neovim-0.2.1/test/functional/api/highlight_spec.lua:46: Expected objects to be the same.
Passed in:
(string) 'Invalid highlight id: -120576164'
Expected:
(string) 'Invalid highlight id: 30000'

stack traceback:
	(tail call): ?
	.../neovim-0.2.1/test/functional/api/highlight_spec.lua:46: in function <.../neovim-0.2.1/test/functional/api/highlight_spec.lua:35>
```

```
test/functional/terminal/cursor_spec.lua[0m @ [36m62[0m: [1mterminal cursor with number column is positioned correctly when focused[0m
./test/functional/ui/screen.lua:302: Row 2 did not match.
Expected:
  |{7:  1 }tty ready                                     |
  |*{7:  2 }{1: }                                             |
  |{7:  3 }                                              |
  |{7:  4 }                                              |
  |{7:  5 }                                              |
  |{7:  6 }                                              |
  |{3:-- TERMINAL --}                                    |
Actual:
  |{7:  1 }tty ready                                     |
  |*{7:  2 }rows: 6, cols: 46                             |
  |{7:  3 }{1: }                                             |
  |{7:  4 }                                              |
  |{7:  5 }                                              |
  |{7:  6 }                                              |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	./test/functional/ui/screen.lua:302: in function 'wait'
	./test/functional/ui/screen.lua:216: in function 'expect'
	...eovim-0.2.1/test/functional/terminal/cursor_spec.lua:65: in function <...eovim-0.2.1/test/functional/terminal/cursor_spec.lua:62>
```

```
test/functional/terminal/tui_spec.lua[0m @ [36m408[0m: [1mtui 't_Co' (terminal colors) no TERM uses 8 colors[0m
...s/neovim-0.2.1/test/functional/terminal/tui_spec.lua:381: bad argument #2 to 'format' (string expected, got nil)

stack traceback:
	...s/neovim-0.2.1/test/functional/terminal/tui_spec.lua:381: in function 'assert_term_colors'
	...s/neovim-0.2.1/test/functional/terminal/tui_spec.lua:409: in function <...s/neovim-0.2.1/test/functional/terminal/tui_spec.lua:408>
```

```
test/functional/terminal/window_spec.lua[0m @ [36m16[0m: [1mterminal window with 'number' wraps text[0m
./test/functional/ui/screen.lua:302: Row 4 did not match.
Expected:
  |{7:       1 }tty ready                                |
  |{7:       2 }rows: 6, cols: 48                        |
  |{7:       3 }abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNO|
  |*{7:       4 }WXYZ abcdefghijklmnopqrstuvwxyzABCDEFGHIJ|
  |{7:       5 }KLMNOPQRSTUVWXYZrows: 6, cols: 41        |
  |{7:       6 }{1: }                                        |
  |{3:-- TERMINAL --}                                    |
Actual:
  |{7:       1 }tty ready                                |
  |{7:       2 }rows: 6, cols: 48                        |
  |{7:       3 }abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNO|
  |*{7:       4 }WXYZrows: 6, cols: 41                    |
  |{7:       5 } abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMN|
  |{7:       6 }OPQRSTUVWXYZ{1: }                            |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	./test/functional/ui/screen.lua:302: in function 'wait'
	./test/functional/ui/screen.lua:216: in function 'expect'
	...eovim-0.2.1/test/functional/terminal/window_spec.lua:47: in function <...eovim-0.2.1/test/functional/terminal/window_spec.lua:16>
```

---
### [powerpc](https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=powerpc&ver=0.2.1-2&stamp=1510204003&raw=0)
* LuaJIT build
```
test/functional/terminal/cursor_spec.lua[0m @ [36m62[0m: [1mterminal cursor with number column is positioned correctly when focused[0m
./test/functional/ui/screen.lua:302: Row 2 did not match.
Expected:
  |{7:  1 }tty ready                                     |
  |*{7:  2 }{1: }                                             |
  |{7:  3 }                                              |
  |{7:  4 }                                              |
  |{7:  5 }                                              |
  |{7:  6 }                                              |
  |{3:-- TERMINAL --}                                    |
Actual:
  |{7:  1 }tty ready                                     |
  |*{7:  2 }rows: 6, cols: 46                             |
  |{7:  3 }{1: }                                             |
  |{7:  4 }                                              |
  |{7:  5 }                                              |
  |{7:  6 }                                              |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	./test/functional/ui/screen.lua:302: in function 'wait'
	./test/functional/ui/screen.lua:216: in function 'expect'
	...xu/neovim-0.2.1/test/functional/terminal/cursor_spec.lua:65: in function <...xu/neovim-0.2.1/test/functional/terminal/cursor_spec.lua:62>
```

---
### [sparc64](https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=sparc64&ver=0.2.1-2&stamp=1510205989&raw=0)
* Lua build
```
test/functional/terminal/cursor_spec.lua[0m @ [36m62[0m: [1mterminal cursor with number column is positioned correctly when focused[0m
./test/functional/ui/screen.lua:302: Row 2 did not match.
Expected:
  |{7:  1 }tty ready                                     |
  |*{7:  2 }{1: }                                             |
  |{7:  3 }                                              |
  |{7:  4 }                                              |
  |{7:  5 }                                              |
  |{7:  6 }                                              |
  |{3:-- TERMINAL --}                                    |
Actual:
  |{7:  1 }tty ready                                     |
  |*{7:  2 }rows: 6, cols: 46                             |
  |{7:  3 }{1: }                                             |
  |{7:  4 }                                              |
  |{7:  5 }                                              |
  |{7:  6 }                                              |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	./test/functional/ui/screen.lua:302: in function 'wait'
	./test/functional/ui/screen.lua:216: in function 'expect'
	...eovim-0.2.1/test/functional/terminal/cursor_spec.lua:65: in function <...eovim-0.2.1/test/functional/terminal/cursor_spec.lua:62>
```

```
test/functional/terminal/tui_spec.lua[0m @ [36m408[0m: [1mtui 't_Co' (terminal colors) no TERM uses 8 colors[0m
...s/neovim-0.2.1/test/functional/terminal/tui_spec.lua:381: bad argument #2 to 'format' (string expected, got nil)

stack traceback:
	...s/neovim-0.2.1/test/functional/terminal/tui_spec.lua:381: in function 'assert_term_colors'
	...s/neovim-0.2.1/test/functional/terminal/tui_spec.lua:409: in function <...s/neovim-0.2.1/test/functional/terminal/tui_spec.lua:408>
```

```
test/functional/terminal/window_spec.lua[0m @ [36m16[0m: [1mterminal window with 'number' wraps text[0m
./test/functional/ui/screen.lua:302: Row 4 did not match.
Expected:
  |{7:       1 }tty ready                                |
  |{7:       2 }rows: 6, cols: 48                        |
  |{7:       3 }abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNO|
  |*{7:       4 }WXYZ abcdefghijklmnopqrstuvwxyzABCDEFGHIJ|
  |{7:       5 }KLMNOPQRSTUVWXYZrows: 6, cols: 41        |
  |{7:       6 }{1: }                                        |
  |{3:-- TERMINAL --}                                    |
Actual:
  |{7:       1 }tty ready                                |
  |{7:       2 }rows: 6, cols: 48                        |
  |{7:       3 }abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNO|
  |*{7:       4 }WXYZrows: 6, cols: 41                    |
  |{7:       5 } abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMN|
  |{7:       6 }OPQRSTUVWXYZ{1: }                            |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	./test/functional/ui/screen.lua:302: in function 'wait'
	./test/functional/ui/screen.lua:216: in function 'expect'
	...eovim-0.2.1/test/functional/terminal/window_spec.lua:47: in function <...eovim-0.2.1/test/functional/terminal/window_spec.lua:16>
```

### PR DESCRIPTION
**Pull request by jamessan**
Closes #7522

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

File: test/functional/terminal/tui_spec.lua [hunk 1]
```diff
@@ -380,7 +380,7 @@ describe("tui 't_Co' (terminal colors)", function()
     -- TODO: Revisit this after jobstart/termopen accept `env` dict.
     screen = thelpers.screen_setup(0, string.format(
       [=[['sh', '-c', 'LANG=C TERM=%s %s %s -u NONE -i NONE --cmd "silent set noswapfile noshowcmd noruler"']]=],
-      term,
+      term and term or "",
```
Comment (bfredl) [inline test/functional/terminal/tui_spec.lua]: Is this not just `term or ""` ?

**Comment by ZyX-I** [comment]
Most of project-local integers have defines like `PRIdNUMBER`, `PRIdSCID`, `PRIdLINENR`, …; new define should be created when needed in place of using PRId64, or number should be cast.
