### PR TITLE
vim-patch:9.1.1086: completion doesn't work with multi lines

### LINKED ISSUE #2505: Proposal: multiline completion support
Currently Vim allows only single line completions. This is quite limiting as there is also no way to determine beginning and end of the completed text so this leaves us in the limbo where we need to do some hackish things to achieve things like multiline snippets.

Most obvious way to do such thing would be to make (`:h complete-items`):

```viml
{ 'word': "aaa\nbbb" }
```

to insert 2 lines:

```
aaa
bbb
```

Currently it inserts

```
aaa^@bbb
```

Where `^@` is NUL character (`:h NL-used-for-NUL`).

The problems with multiline completion is that there will be open question how to handle indentation.

Alternatively we could allow `List` as `'word'` parameter where each line would be one item.

### PR DESCRIPTION
**Pull request by glepnir**
Problem:  completion doesn't work with multi lines
          (Łukasz Jan Niemier)
Solution: handle linebreaks in completion code as expected
          (glepnir)

fixes: vim/vim#2505
closes: vim/vim#15373

https://github.com/vim/vim/commit/76bdb82527a13b5b2baa8f7d7ce14b4d5dc05b82

### CODE REVIEW

File: src/nvim/insexpand.c [hunk 1]
```diff
@@ -963,20 +964,49 @@ static void ins_compl_insert_bytes(char *p, int len)
...
+    return attr;
   }
 
   return -1;
 }
 
+/*
+ * Returns TRUE if the current completion string contains newline characters,
+ * indicating it's a multi-line completion.
+ */
```
Comment (zeertzjq) [inline src/nvim/insexpand.c:992]:
```suggestion
/// Returns true if the current completion string contains newline characters,
/// indicating it's a multi-line completion.
```

File: src/nvim/insexpand.c [hunk 2]
```diff
@@ -963,20 +964,49 @@ static void ins_compl_insert_bytes(char *p, int len)
...
+static bool ins_compl_has_multiple(void)
+{
+  return vim_strchr(compl_shown_match->cp_str.data, '\n') != NULL;
+}
+/*
+ * Returns TRUE if the given line number falls within the range of a multi-line
+ * completion, i.e. between the starting line (compl_lnum) and current cursor
+ * line. Always returns FALSE for single-line completions.
+ */
```
Comment (zeertzjq) [inline src/nvim/insexpand.c:1001]:
```suggestion

/// Returns true if the given line number falls within the range of a multi-line
/// completion, i.e. between the starting line (compl_lnum) and current cursor
/// line. Always returns false for single-line completions.
```

File: src/nvim/insexpand.c [hunk 3]
```diff
@@ -3737,6 +3765,29 @@ void ins_compl_delete(bool new_leader)
...
   }
 
+  char *remaining = NULL;
+  if (curwin->w_cursor.lnum > compl_lnum) {
+    if (curwin->w_cursor.col < get_cursor_line_len()) {
+      char *line = get_cursor_line_ptr();
+      remaining = xstrdup(line + curwin->w_cursor.col);
+      if (remaining == NULL) {
+        return;
+      }
```
Comment (zeertzjq) [inline src/nvim/insexpand.c:3775]:
```suggestion
```

File: src/nvim/insexpand.c [hunk 4]
```diff
@@ -963,20 +964,46 @@ static void ins_compl_insert_bytes(char *p, int len)
...
+      || (lnum > compl_lnum && lnum < curwin->w_cursor.lnum)
+      || (lnum == curwin->w_cursor.lnum && col <= compl_ins_end_col)) {
+    return attr;
   }
 
   return -1;
 }
 
+// Returns TRUE if the current completion string contains newline characters,
+// indicating it's a multi-line completion.
```
Comment (zeertzjq) [inline src/nvim/insexpand.c:990]:
```suggestion
/// Returns true if the current completion string contains newline characters,
/// indicating it's a multi-line completion.
```

File: src/nvim/insexpand.c [hunk 5]
```diff
@@ -963,20 +964,46 @@ static void ins_compl_insert_bytes(char *p, int len)
...
+static bool ins_compl_has_multiple(void)
+{
+  return vim_strchr(compl_shown_match->cp_str.data, '\n') != NULL;
+}
+
+// Returns TRUE if the given line number falls within the range of a multi-line
+// completion, i.e. between the starting line (compl_lnum) and current cursor
+// line. Always returns FALSE for single-line completions.
```
Comment (zeertzjq) [inline src/nvim/insexpand.c:998]:
```suggestion
/// Returns true if the given line number falls within the range of a multi-line
/// completion, i.e. between the starting line (compl_lnum) and current cursor
/// line. Always returns false for single-line completions.
```

File: src/nvim/insexpand.c [hunk 6]
```diff
@@ -3745,13 +3797,48 @@ void ins_compl_delete(bool new_leader)
...
+
   // TODO(vim): is this sufficient for redrawing?  Redrawing everything
   // causes flicker, thus we can't do that.
   changed_cline_bef_curs(curwin);
   // clear v:completed_item
   set_vim_var_dict(VV_COMPLETED_ITEM, tv_dict_alloc_lock(VAR_FIXED));
 }
 
+// Insert a completion string that contains newlines.
+// The string is split and inserted line by line.
```
Comment (zeertzjq) [inline src/nvim/insexpand.c:3815]:
```suggestion
/// Insert a completion string that contains newlines.
/// The string is split and inserted line by line.
```

File: test/functional/ui/popupmenu_spec.lua [hunk 7]
```diff
@@ -5935,6 +5935,104 @@ describe('builtin popupmenu', function()
         ]])
         feed('<C-E><Esc>')
       end)
+
+      -- oldtest: Test_pum_complete_with_special_characters()
+      it('#expand multiple-line completion', function()
```
Comment (zeertzjq) [inline test/functional/ui/popupmenu_spec.lua:5940]:
```suggestion
      it('multi-line completion', function()
```

File: test/functional/ui/popupmenu_spec.lua [hunk 8]
```diff
@@ -5935,6 +5935,104 @@ describe('builtin popupmenu', function()
...
+          hello 你好                      |
+                                          |
+          我好^ hero                       |
+          {1:~  }{n: function ()    }{1:             }|
+          {1:~  }{n: foobar         }{1:             }|
+          {1:~  }{s: 你好^@  ^@我好 }{1:             }|
+          {1:~                               }|*13
+          {2:-- }{5:match 3 of 3}                 |
+        ]])
+        feed('<C-E><ESC>')
```
Comment (zeertzjq) [inline test/functional/ui/popupmenu_spec.lua:6007]: There are three `<C-N>`s in the old test, but here there are only two.

File: test/functional/ui/popupmenu_spec.lua [hunk 9]
```diff
@@ -5935,6 +5935,115 @@ describe('builtin popupmenu', function()
...
+        feed('<C-N>')
+        screen:expect([[
+          hello ^ hero                     |
+          {1:~    }{n: function ()    }{1:           }|
+          {1:~    }{n: foobar         }{1:           }|
+          {1:~    }{n: 你好^@  ^@我好 }{1:           }|
+          {1:~                               }|*15
+          {2:-- }{8:Back at original}             |
+        ]])
+        screen:snapshot_util()
```
Comment (zeertzjq) [inline test/functional/ui/popupmenu_spec.lua:6017]:
```suggestion
```

**Review by zeertzjq — APPROVED** [review]

File: src/nvim/insexpand.c [hunk 10]
```diff
@@ -963,20 +964,47 @@ static void ins_compl_insert_bytes(char *p, int len)
...
 }
 
+/// Returns true if the current completion string contains newline characters,
+/// indicating it's a multi-line completion.
+static bool ins_compl_has_multiple(void)
+{
+  return vim_strchr(compl_shown_match->cp_str.data, '\n') != NULL;
+}
+
+/// Returns ture if the given line number falls within the range of a multi-line
```
Comment (zeertzjq) [inline src/nvim/insexpand.c:997]:
```suggestion
/// Returns true if the given line number falls within the range of a multi-line
```

**Review by zeertzjq — APPROVED** [review]

**Comment by justinmk** [comment]
Thank you @zeertzjq and @glepnir !

File: test/functional/ui/popupmenu_spec.lua [hunk 11]
```diff
@@ -5935,6 +5935,114 @@ describe('builtin popupmenu', function()
...
+        ]])
+
+        feed('S<C-X><C-O>')
+        screen:expect([[
+          func ()                         |
+                                          |
+          end^                             |
+          {s:function ()    }{1:                 }|
+          {n:foobar         }{1:                 }|
+          {n:你好^@  ^@我好 }{1:                 }|
```
Comment (justinmk) [inline test/functional/ui/popupmenu_spec.lua:5958]: Why is it rendering as `^@` instead of linebreak? I thought the entire purpose of https://github.com/vim/vim/issues/2505 was to insert linebreaks.

Comment (zeertzjq) [reply test/functional/ui/popupmenu_spec.lua:5958]: What is "rendering as linebreak"?

Comment (justinmk) [reply test/functional/ui/popupmenu_spec.lua:5958]: Oh I see these tests are checking the menu representation, not the inserted text. I was expecting a test that verifies the inserted text has multiple lines instead of one line with `^@` chars.

Comment (zeertzjq) [reply test/functional/ui/popupmenu_spec.lua:5958]: Isn't it right here?

**Comment by justinmk** [comment]
coverity:

```
/src/nvim/insexpand.c: 3791 in ins_compl_delete()
3785         // move cursor to end of line
3786         curwin->w_cursor.col = get_cursor_line_len();
3787       }
3788     
3789       if ((int)curwin->w_cursor.col > col) {
3790         if (stop_arrow() == FAIL) {
>>>     CID 533635:  Resource leaks  (RESOURCE_LEAK)
>>>     Variable "remaining" going out of scope leaks the storage it points to.
3791           return;
3792         }
3793         backspace_until_column(col);
3794         compl_ins_end_col = curwin->w_cursor.col;
3795       }
```

**Comment by justinmk** [comment]
When 'autoindent' is set, the text is formatted badly. Doesn't look like the tests cover this case. When inserting the text, should it behave like 'paste' is set?

**Comment by glepnir** [comment]
already create a pr for this https://github.com/vim/vim/pull/16614
