### PR TITLE
fix(completion): reason="discard" when candidate text remains in buffer

### LINKED ISSUE #38160: `CompleteDone` reason = discard when accepting the only possible match
### Problem

With `completeopt=menu` (as opposed to `menuone`, and specifically without `noinsert`), if there's a single possible completion match, it gets inserted into the buffer automatically without opening the `ins-completion` menu. However, the `CompleteDone` event that fires will set `vim.v.event.reason = "discard"` rather than `"accept"`, even though `vim.v.completed_item` does correctly reflect the sole match that gets selected.

Previously, #32600 amended the `CompleteDone` event with the `discard` reason to distinguish it from `cancel`. But it appears to have missed this edge case where `accept` seems more appropriate (unless I'm missing something).

This has downstream implications for `vim.lsp.completion`, which only applies side-effects (additional edits, snippet expansion, etc) when `reason == "accept"`: https://github.com/neovim/neovim/blob/6beb1fe0cd686cd0fe8a2a5f72704f7d1bbd252c/runtime/lua/vim/lsp/completion.lua#L889-L892 That said, if I patch this locally to always call `on_complete_done()`, there does seem to be a separate issue downstream of *that* where additional LSP text edits that I'm expecting are prevented by the logic here: https://github.com/neovim/neovim/blob/6beb1fe0cd686cd0fe8a2a5f72704f7d1bbd252c/runtime/lua/vim/lsp/completion.lua#L795-L801 So it could be that the insertion of the only match is updating `changedtick` in a way that's not anticipated by LSP completion either. But that's a separate issue I haven't fully dug into.

### Steps to reproduce

repro.lua

```lua
vim.o.completeopt = "menu"

local group = vim.api.nvim_create_augroup("repro", { clear = true })

vim.api.nvim_create_autocmd("CompleteDone", {
  group = group,
  callback = function()
    vim.print({
      event = vim.v.event,
      completed_item = vim.v.completed_item,
    })
  end,
})

vim.api.nvim_create_autocmd("UIEnter", {
  group = group,
  callback = function()
    local keys = vim.api.nvim_replace_termcodes("itest<cr><c-n><esc>", true, false, true)
    vim.fn.feedkeys(keys, "nt")
  end,
})
```

```console
$ nvim --clean -u repro.lua
```

After some setup to ensure `completeopt=menu` and to add some debug printing around the `CompleteDone` event, this repro will add the word `test` to the buffer, then use `<c-n>` to trigger keyword completion. With `test` being the only keyword, that's what gets inserted. However, the data set for `CompleteDone` tells a different story:

```
{
  completed_item = {
    abbr = "",
    info = "",
    kind = "",
    menu = "",
    user_data = "",
    word = "test"
  },
  event = {
    complete_type = "keyword",
    complete_word = "",
    reason = "discard"
  }
}
```

### Expected behavior

I expected `event.reason` to be `"accept"`, as the acceptance of the first/only result is automatic in this configuration. I also would expect `event.complete_word` to be `"test"` rather than empty in this repro.

### Nvim version (nvim -v)

NVIM v0.11.6 Build type: Release LuaJIT 2.1.1767980792

### Vim (not Nvim) behaves the same?

no, vim doesn't include the `reason` key at all in `v:event` (AFAICT)

### Operating system/version

macOS 26.3

### Terminal name/version

WezTerm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

Homebrew

### PR DESCRIPTION
**Pull request by glepnir**
fix(completion): CompleteDone reason="discard" when candidate text remains in buffer

Problem: CompleteDone fires with reason="discard" even when the candidate
text was inserted and left in the buffer, because reason was determined
solely by the terminating keycode (Ctrl-Y).

Solution: Check compl_used_match to detect whether inserted
text remains in the buffer, and set reason="accept" accordingly. 

Fix #38160

### CODE REVIEW

File: test/functional/autocmd/completedone_spec.lua [hunk 1]
```diff
@@ -13,6 +13,7 @@ describe('CompleteDone', function()
 
   describe('sets v:event.reason', function()
     before_each(function()
+      command('set cot+=noinsert')
```
Comment (justinmk) [inline test/functional/autocmd/completedone_spec.lua]:
```suggestion
      command('set completeopt+=noinsert')
```

File: test/functional/autocmd/completedone_spec.lua [hunk 2]
```diff
@@ -23,6 +24,19 @@ describe('CompleteDone', function()
       eq('accept', eval('g:donereason'))
     end)
 
+    it('accept when candidate is inserted without noinsert #38160', function()
+      command('set completeopt=menu,menuone')
```
Comment (justinmk) [inline test/functional/autocmd/completedone_spec.lua]:
```suggestion
      command('set completeopt=menu,menuone') -- Omit "noinsert".
```

**Comment by gravndal** [comment]
I don't think this fixes the problem as described in https://github.com/neovim/neovim/issues/38160, as this both isn't gated behind the absence of either `completeopt=menuone` or `noinsert`, and also isn't triggered immediately.

This also breaks the behaviour of `CompleteDone` when you've selected a completion (but not yet accepted it) with `completeopt+=menuone`, which makes snippet completion combined with `set ac complete+=.` very painful.

Here's a simple reproducer with `nvim --clean` on `ce1154048b11cdc402d0e5da352a3adca19afb56`:

```lua
_G.pretend_snippet_plugin = function(findstart, base)
  if findstart == 1 then
    local line = vim.api.nvim_get_current_line()
    local cursor = vim.api.nvim_win_get_cursor(0)[2]
    local line_to_cursor = line:sub(0, cursor)
    return vim.fn.match(line_to_cursor, '\\k\\+$')
  end
  return vim.fn.matchfuzzy({{
    word = 'llength',
    user_data = { is_pretend = true }
  }}, base, { key = 'word' })
end

vim.api.nvim_create_autocmd('CompleteDone', {
  group = vim.api.nvim_create_augroup('hello', {}),
  callback = function()
    if vim.v.event.reason ~= 'accept' then return end
    local item = vim.v.completed_item
    if not (item and item.user_data and item.user_data.is_pretend) then return end
    local cursor = vim.api.nvim_win_get_cursor(0)
    vim.api.nvim_buf_set_text(0, cursor[1] - 1, cursor[2], cursor[1] - 1, cursor[2], { 'hello world' })
  end,
})
```

When setting

```vim
set completeopt=menu
set omnifunc=v:lua.pretend_snippet_plugin
```

Try doing
```
llen<C-o><Space>
llen<C-o><Esc>
```

Note that `CompleteDone` is triggered as if accepted after the `<Space>` and `<Esc>`.

And then when setting
```vim
set ac
set complete=Fv:lua.pretend_snippet_plugin,.
```

Try doing
```
llen<C-n><Space>
llen<C-n><Esc>
```

Note that just like when doing manual ins completion, `CompleteDone` is triggered with `reason == 'accept`' after the `<Space>` and `<Esc>`, but in this case it probably shouldn't have been triggered at all as you didn't actually accept the completion (even if the text in the buffer was changed), and:

 - it doing so makes it impossible to autocomplete words in a buffer that happen to match a unique snippet (edit: this also applies to `compl-keyword`)

 - it's also really surprising that doing `<Esc>` triggers `CompleteDone` with `reason == 'accept'`, and thus snippet expansion etc

 - accepting a completion being an intentional action, and having the ability to discard without cancelling by simply just continuing to type is genuinely useful (edit: this also applies to non-auto ins completion IMO)
