### PR TITLE
Fix popupmenu position issue

### LINKED ISSUE #13085: Has pumwidth been ported?
Could not find this anywhere, but has `pumwidth` already been ported? 

I'm trying to find away around the issue where, with long completions near the right edge of the nvim window, the completion results get truncated. Going by [this old thread](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=450481) I thought this had long been fixed by showing the popup to the left hand side of the cursor in those cases. But that doesn't appear to be the case.

What could help me out is setting a very large `pumwidth`. But my nvim (0.4.3) only recognizes `pumheight`.

### PR DESCRIPTION
**Pull request by erw7**
fixes https://github.com/neovim/neovim/issues/13085#issuecomment-707494940.

### CODE REVIEW

File: src/nvim/popupmnu.c [hunk 1]
```diff
@@ -301,49 +301,49 @@ void pum_display(pumitem_T *array, int size, int selected, bool array_changed,
         if (pum_width < p_pw) {
           pum_width = (int)p_pw;
         }
-      }
-    } else if (((cursor_col > p_pw || cursor_col > max_width) && !pum_rl)
```
Comment (janlazo) [inline src/nvim/popupmnu.c:305]: Good find. I added an extra `}` here when the patch 8.0.1491 didn't have it.

File: src/nvim/popupmnu.c [hunk 2]
```diff
@@ -301,49 +301,49 @@ void pum_display(pumitem_T *array, int size, int selected, bool array_changed,
...
+        if (pum_rl && W_ENDCOL(curwin) < max_width + pum_scrollbar + 1) {
+          pum_col = cursor_col + max_width + pum_scrollbar + 1;
+          if (pum_col >= Columns) {
+            pum_col = Columns - 1;
+          }
+        } else if (!pum_rl) {
+          if (curwin->w_wincol > Columns - max_width - pum_scrollbar
+              && max_width <= p_pw) {
+            // use full width to end of the screen
+            pum_col = Columns - max_width - pum_scrollbar;
```
Comment (janlazo) [inline src/nvim/popupmnu.c:317]: This is correct. Made a mistake when porting patch 8.0.1522.

**Review by janlazo — APPROVED** [review]

**Comment by janlazo** [comment]
I modified those tests to make them pass but it turns out that I got it wrong. Thank you for the fix.
