### PR TITLE
fix(lsp): simplify semantic tokens range request logic

### LINKED ISSUE #36928: LSP spam: "Cannot find request with id X whilst attempting to cancel" after recent commits (Windows + WSL)
### Problem

Summary

After updating to recent commits on master, Neovim’s LSP subsystem begins flooding the log with repeated messages such as:

Cannot find request with id 24 whilst attempting to cancel

This affects multiple language servers (lua_ls, powershell_es, others) and occurs even with a minimal config. The issue does not occur on older commits — the last known good commit is:

cdc6f85111 (2025-12-01)

The problem appears within the next ~123 commits after that.

Environment

OS: Windows 11 Pro (23H2) — also reproducible on WSL2 Ubuntu

Compiler: MSVC (Build Tools 2022)

Build system: Ninja + CMake

Neovim version where bug is present: any master commit after 2025-12-01

Neovim version where bug is NOT present: cdc6f85111

Actual behavior

The log is filled with repeated errors such as:

[LSP[lua_ls]] Cannot find request with id 18 whilst attempting to cancel
[LSP[lua_ls]] Cannot find request with id 87 whilst attempting to cancel
[LSP[powershell_es]] Cannot find request with id 14 whilst attempting to cancel

This can result in hundreds of lines within seconds.
The spam occurs even when Neovim is idle and across multiple LSP servers.

Additional notes

Rebuilding Neovim multiple times with fresh .deps confirmed it is not caused by stale dependencies.

Minimal configurations show the same behavior.

Regression window:

good: cdc6f85111 (2025-12-01)
bad:  HEAD (2025-12-11)
distance: 123 commits after cdc6f85111

This may be related to recent changes in:

LSP request lifecycle

async RPC scheduling

cancellation token logic

event loop timing

If additional testing (Windows/WSL logs, bisection, or custom builds) is helpful, I can assist.

Thanks!

### Steps to reproduce

Steps to reproduce

Build Neovim from any master commit after 2025-12-01.

Launch Neovim with a minimal configuration:

nvim --clean file.lua

Allow an LSP to start (lua_ls, powershell_es, or any server).

Interact briefly (move cursor, open/close buffers, trigger completion).

Open the LSP log:

:LspLog

### Expected behavior

Expected behavior

LSP cancellations should only target active requests.

Neovim should not attempt to cancel nonexistent or already-finished requests.

No error spam or runaway log growth.

### Nvim version (nvim -v)

NVIM v0.12.0-dev (any recent commit after Dec 1)

### Vim (not Nvim) behaves the same?

Not applicable — Vim does not include the built-in LSP client. This issue is specific to Neovim’s LSP subsystem.

### Operating system/version

Windows 11 Pro (23H2), build 22631

### Terminal name/version

WezTerm 20251201-075747-d3b0fdad

### $TERM environment variable

xterm-256color

### Installation

Build from source (MSVC + Ninja)

### PR DESCRIPTION
**Pull request by jdrouhard**
By simplifying the way range is supported, we can fix a couple issues as well as making it less complex and more efficient:

* For non-range LSP servers, don't send requests on WinScrolled. The semantic tokens module has been reworked to only send one active request at a time, as it was before range support was added. If range is not supported, then send_request() only fires if there's been a change to the buffer's document version.
* Cache the server's support of range and delta requests when attaching to a buffer to save the lookup on each request.
* Range requests always use the visible window, so just use that for the `range` param when sending requests when range is supported by the server. This reduces the API surface area of send_request().
* Debounce the WinScrolled autocmd requests in the same the way requests are debounced when the buffer contents are changing. Should allow scrolling via mouse wheel or holding down "j" or "k" work a bit smoother.

The previous iteration of range support allowed multiple active requests to be in progress simultaneously. However, a bug was preventing any but the most recent request to actually apply to the client's highlighting state so that complexity was unused. It was effectively only using one active request at a time but was just using range requests on WinScrolled events instead of a full (or delta) request when the document version changed.

Fixes #36928
Close #36942

### CODE REVIEW

File: runtime/lua/vim/lsp/semantic_tokens.lua [hunk 1]
```diff
@@ -266,63 +249,56 @@ function STHighlighter:send_request(range)
...
+        elseif supports_delta and current_result.result_id then
+          method = 'textDocument/semanticTokens/full/delta'
+          params.previousResultId = current_result.result_id
         end
 
         ---@param response? lsp.SemanticTokens|lsp.SemanticTokensDelta
         local success, request_id = client:request(method, params, function(err, response, ctx)
+          -- look client up again using ctx.client_id instead of using a captured
+          -- client object
+          local c = vim.lsp.get_client_by_id(ctx.client_id)
```
Comment (tris203) [inline runtime/lua/vim/lsp/semantic_tokens.lua]: I removed this in the original PR as it wasnt clear _why_ we relook up the client.
Can you explain why?

File: runtime/lua/vim/lsp/semantic_tokens.lua [hunk 2]
```diff
@@ -602,9 +556,13 @@ function STHighlighter:reset()
   for client_id, state in pairs(self.client_state) do
     api.nvim_buf_clear_namespace(self.bufnr, state.namespace, 0, -1)
     state.current_result = {}
-    local client = vim.lsp.get_client_by_id(client_id)
-    assert(client)
-    self:cancel_all_requests(client)
+    if state.active_request.request_id then
+      ---@type vim.lsp.Client|nil
```
Comment (tris203) [inline runtime/lua/vim/lsp/semantic_tokens.lua]: I dont think you need this it should be infered

File: runtime/lua/vim/lsp/semantic_tokens.lua [hunk 3]
```diff
@@ -626,9 +584,14 @@ function STHighlighter:mark_dirty(client_id)
   if state.current_result then
     state.current_result.version = nil
   end
-  local client = vim.lsp.get_client_by_id(client_id)
-  assert(client)
-  self:cancel_all_requests(client)
+
+  if state.active_request.request_id then
+    ---@type vim.lsp.Client|nil
```
Comment (tris203) [inline runtime/lua/vim/lsp/semantic_tokens.lua]: I think it should also be infered here

File: runtime/lua/vim/lsp/semantic_tokens.lua [hunk 4]
```diff
@@ -266,63 +249,56 @@ function STHighlighter:send_request(range)
...
     if client then
       local current_result = state.current_result
-      local active_requests = state.active_requests
-
-      local full_request_version = active_requests[FULL] and active_requests[FULL].version
+      local active_request = state.active_request
 
-      local new_version = current_result.version ~= version and full_request_version ~= version
+      local supports_range = client:supports_method('textDocument/semanticTokens/range', self.bufnr)
+      local supports_delta = client:supports_method('textDocument/semanticTokens/full/delta', self.bufnr)
```
Comment (tris203) [inline runtime/lua/vim/lsp/semantic_tokens.lua]: Minor perf, but if we inline these then we save time looking up the capability until its about to be used

File: runtime/lua/vim/lsp/semantic_tokens.lua (hunk 1 above)
Comment (jdrouhard) [reply runtime/lua/vim/lsp/semantic_tokens.lua]: If the client is destroyed while the request is outstanding, then having it captured here prevents garbage collection. If we do this instead, we allow the client to be destroyed (possibly) and then this response does nothing.

File: runtime/lua/vim/lsp/semantic_tokens.lua (hunk 2 above)
Comment (jdrouhard) [reply runtime/lua/vim/lsp/semantic_tokens.lua]: It was not inferred by lua_ls for me without this. /shrug

File: runtime/lua/vim/lsp/semantic_tokens.lua (hunk 4 above)
Comment (jdrouhard) [reply runtime/lua/vim/lsp/semantic_tokens.lua]: I don't think there's much of a perf cost here. The function itself is pretty fast and we use the range support one twice. For non-range clients, it's zero cost. Both are looked up in that case anyway.

As for pulling the delta one out, I think doing its lookup once per range request won't make a difference but it certainly cleans up the code to place the two method lookups next to each other like this.

Comment (jdrouhard) [reply runtime/lua/vim/lsp/semantic_tokens.lua]: I went ahead and did something to address this. Now, the `supports_range` and `supports_delta` are stored on the client state so it only has to be looked up once per LSP client/buffer. This is much better than per request, thanks for pointing it out!

File: runtime/lua/vim/lsp/semantic_tokens.lua [hunk 5]
```diff
@@ -23,19 +23,16 @@ local M = {}
 --- @field highlights? STTokenRange[] cache of highlight ranges for this document version
 --- @field tokens? integer[] raw token array as received by the server. used for calculating delta responses
 --- @field namespace_cleared? boolean whether the namespace was cleared for this result yet
-
+---
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/semantic_tokens.lua]: This new line seems to be messing up the doc generation.
```suggestion

```

File: runtime/lua/vim/lsp/semantic_tokens.lua [hunk 6]
```diff
@@ -23,19 +23,16 @@ local M = {}
...
 --- @class (private) STActiveRequest
 --- @field request_id? integer the LSP request ID of the most recent request sent to the server
 --- @field version? integer the document version associated with the most recent request
-
----@alias full_request 'FULL'
-
----@type full_request
-local FULL = 'FULL'
-
+---
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/semantic_tokens.lua]:
```suggestion

```

File: runtime/lua/vim/lsp/semantic_tokens.lua (hunk 2 above)
Comment (MariaSolOs) [reply runtime/lua/vim/lsp/semantic_tokens.lua]: Agreed, the type annotation is unnecessary.

File: runtime/lua/vim/lsp/semantic_tokens.lua [hunk 7]
```diff
@@ -197,34 +194,28 @@ function STHighlighter:new(bufnr)
...
-    if request.request_id then
-      client:cancel_request(request.request_id)
-      state.active_requests[idx] = nil
-    end
-  end
-end
-
 ---@package
 function STHighlighter:on_attach(client_id)
+  ---@type vim.lsp.Client|nil
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/semantic_tokens.lua]:
```suggestion
```

File: runtime/lua/vim/lsp/semantic_tokens.lua [hunk 8]
```diff
@@ -197,34 +194,28 @@ function STHighlighter:new(bufnr)
...
+  local client = vim.lsp.get_client_by_id(client_id)
   local state = self.client_state[client_id]
   if not state then
     state = {
       namespace = api.nvim_create_namespace('nvim.lsp.semantic_tokens:' .. client_id),
-      active_requests = {},
+      supports_range = client
+          and client:supports_method('textDocument/semanticTokens/range', self.bufnr)
+        or false,
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/semantic_tokens.lua:223]:
```suggestion,
```
`or false` is redundant.

File: runtime/lua/vim/lsp/semantic_tokens.lua [hunk 9]
```diff
@@ -197,34 +194,28 @@ function STHighlighter:new(bufnr)
...
+      supports_delta = client
+          and client:supports_method('textDocument/semanticTokens/full/delta', self.bufnr)
+        or false,
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/semantic_tokens.lua:226]:
```suggestion,
```

File: runtime/lua/vim/lsp/semantic_tokens.lua [hunk 10]
```diff
@@ -256,73 +247,65 @@ end
...
 ---@package
----@param range? lsp.Range
-function STHighlighter:send_request(range)
+function STHighlighter:send_request()
   local version = util.buf_versions[self.bufnr]
 
   self:reset_timer()
 
   for client_id, state in pairs(self.client_state) do
+    ---@type vim.lsp.Client|nil
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/semantic_tokens.lua]:
```suggestion
```

File: runtime/lua/vim/lsp/semantic_tokens.lua (hunk 2 above)
Comment (jdrouhard) [reply runtime/lua/vim/lsp/semantic_tokens.lua]: Weird, my lua ls definitely complains it can't infer the type here. Maybe my env is set up wrong. I'll remove for now.

File: runtime/lua/vim/lsp/semantic_tokens.lua (hunk 8 above)
Comment (jdrouhard) [reply runtime/lua/vim/lsp/semantic_tokens.lua:223]: ~~Wouldn't it be nil without it? I didn't want it to possibly be nil but rather always a valid boolean.~~

Edit: nope, I'm just hallucinating. I'll update.

Comment (MariaSolOs) [reply runtime/lua/vim/lsp/semantic_tokens.lua:223]: It's okay. Boolean expressions are tricky 😅

File: runtime/lua/vim/lsp/semantic_tokens.lua (hunk 5 above)
Comment (jdrouhard) [reply runtime/lua/vim/lsp/semantic_tokens.lua]: Didn't seem to make a difference. Removed them anyway, but docs didn't change.

File: runtime/lua/vim/lsp/semantic_tokens.lua (hunk 1 above)
Comment (jdrouhard) [reply runtime/lua/vim/lsp/semantic_tokens.lua]: Anyway, I went ahead and reverted this change back to what's in master. I'm not sure that any possible race condition here would ever actually happen. This pattern of capturing the client itself in the closure seems to occur elsewhere in the lsp code so there is precedent even if it's technically possible to process results for otherwise-destroyed clients.

File: runtime/lua/vim/lsp/semantic_tokens.lua (hunk 8 above)
Comment (jdrouhard) [reply runtime/lua/vim/lsp/semantic_tokens.lua:223]: Ah ha! I wasn't crazy! :joy: From the lint job after I took out `or false`:

```
 runtime/lua/vim/lsp/semantic_tokens.lua:211:7 [Warning] Cannot assign `boolean?` to `boolean`.
- Optional type cannot match `boolean`
- Type `nil` cannot match `boolean` (assign-type-mismatch)
          supports_range = client
          ^^^^^^^^^^^^^^
runtime/lua/vim/lsp/semantic_tokens.lua:213:7 [Warning] Cannot assign `boolean?` to `boolean`.
- Optional type cannot match `boolean`
- Type `nil` cannot match `boolean` (assign-type-mismatch)
          supports_delta = client
          ^^^^^^^^^^^^^^
```

File: runtime/lua/vim/lsp/semantic_tokens.lua [hunk 11]
```diff
@@ -266,43 +255,31 @@ function STHighlighter:send_request(range)
...
+        or (current_result.version ~= version and active_request.version ~= version)
+      then
+        -- cancel stale in-flight request
+        if active_request.request_id then
+          client:cancel_request(active_request.request_id)
+          active_request = {}
+          state.active_request = active_request
         end
 
+        ---@class lsp.SemanticTokensParams
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/semantic_tokens.lua]:
```suggestion
        ---@type lsp.SemanticTokensParams
```

Comment (MariaSolOs) [reply runtime/lua/vim/lsp/semantic_tokens.lua]: Using `class` here is causing this type to be doc-generated.

File: runtime/lua/vim/lsp/semantic_tokens.lua (hunk 8 above)
Comment (MariaSolOs) [reply runtime/lua/vim/lsp/semantic_tokens.lua:223]: Oh very interesting. Lua is a truly chaotic language. Thank you for trying!

File: runtime/lua/vim/lsp/semantic_tokens.lua [hunk 12]
```diff
@@ -602,9 +558,12 @@ function STHighlighter:reset()
   for client_id, state in pairs(self.client_state) do
     api.nvim_buf_clear_namespace(self.bufnr, state.namespace, 0, -1)
     state.current_result = {}
-    local client = vim.lsp.get_client_by_id(client_id)
-    assert(client)
-    self:cancel_all_requests(client)
+    if state.active_request.request_id then
+      local client = vim.lsp.get_client_by_id(client_id)
+      assert(client)
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/semantic_tokens.lua]: Nit:
```suggestion
      local client = assert(vim.lsp.get_client_by_id(client_id))
```

File: runtime/lua/vim/lsp/semantic_tokens.lua [hunk 13]
```diff
@@ -626,9 +585,13 @@ function STHighlighter:mark_dirty(client_id)
   if state.current_result then
     state.current_result.version = nil
   end
-  local client = vim.lsp.get_client_by_id(client_id)
-  assert(client)
-  self:cancel_all_requests(client)
+
+  if state.active_request.request_id then
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/semantic_tokens.lua]: It looks like it might be helpful to abstract this logic of canceling the active client request into a local function.

File: runtime/lua/vim/lsp/semantic_tokens.lua (hunk 11 above)
Comment (jdrouhard) [reply runtime/lua/vim/lsp/semantic_tokens.lua]: Fixed.

**Comment by justinmk** [comment]
Restarted CI. @MariaSolOs ok to merge?

**Comment by MariaSolOs** [comment]
> Restarted CI. @MariaSolOs ok to merge?

I defer to @tris203 on giving the final 👍 as they're more familiar with this implementation and I fully trust their judgement.
