### PR TITLE
fix(tui): don't set tty background if &bg was set before VimEnter

### LINKED ISSUE #22614: Background color is detected late
### Problem

The value of "background" doesn't get set properly until after startup

### Steps to reproduce

nvim --clean -c "set background?" # outputs background=dark
:set background? # outputs background=light

### Expected behavior

Both values to be the same. Ideally I would be able to use this value in my config to set the appropriate colour scheme.

### Neovim version (nvim -v)

v0.8.3

### Vim (not Nvim) behaves the same?

no, 9.0.1337

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

Arch Repository (community)

### PR DESCRIPTION
**Pull request by rewhile**
close #22614

### CODE REVIEW

File: src/nvim/option.c [hunk 1]
```diff
@@ -3336,8 +3336,8 @@ void set_tty_background(const char *value)
   if (starting) {
     // Wait until after startup, so OptionSet is triggered.
     do_cmdline_cmd((value[0] == 'l')
-                   ? "autocmd VimEnter * ++once ++nested set bg=light"
-                   : "autocmd VimEnter * ++once ++nested set bg=dark");
+                   ? "autocmd VimEnter * ++once ++nested if &bg == '' | set bg=light | endif"
```
Comment (bfredl) [inline src/nvim/option.c:3339]: I don't think this would work. need `!nvim_get_option_info2("bg", {}).was_set`

Comment (nullchilly) [reply src/nvim/option.c:3339]: I personally can't reproduce the original issue

Do you know how to write a test for this racing condition?

**Comment by fdelacruz** [comment]
This is still broken and only worked back in v0.9.0 Release.
