### PR TITLE
fix(lsp): show meaningful error on invalid completion response

### LINKED ISSUE #39400: LSP: Completion request cancelation errors when server returns `vim.NIL` in `result.items` as response
### Problem

When completion request returns:
```
{
  -- ...
  items = vim.NIL,
  -- ...
}
```
then request cancellation function errors:
```
vim.schedule callback: /usr/share/nvim/runtime/lua/vim/lsp/completion.lua:1006: attempt to get length of local 'result' (a userdata value)
stack traceback:
        /usr/share/nvim/runtime/lua/vim/lsp/completion.lua:1006: in function 'callback'
        /usr/share/nvim/runtime/lua/vim/lsp/completion.lua:591: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp/client.lua:742: in function ''
        vim/_core/editor.lua: in function <vim/_core/editor.lua:0>
```

due to line
```
      if result and #(result.items or result) > 0 then
```
not having a check for `vim.NIL`

### Steps to reproduce using "nvim --clean -u minimal_init.lua"

`minimal_init.lua`:
```
vim.cmd [[ edit a.c ]]
vim.fn.append(0, "int main() { r }")
vim.lsp.start({ name = 'clangd', cmd = { 'clangd' } })
vim.lsp.start({ name = 'ctags', cmd = { 'ctags-lsp' } })
vim.cmd [[ norm! kfr ]]
vim.cmd [[ startinsert ]]
```
After launching, trigger omnifunc

### Expected behavior

_No response_

### Nvim version (nvim -v)

* `v0.12.2`
* `v0.13.0-dev-321+gf83d0b9653`

### Language server name/version

ctags-lsp

### Operating system/version

Arch

### Log file

_No response_

### PR DESCRIPTION
**Pull request by glepnir**
Problem: vim.NIL is truthy in Lua, so `#(result.items or result)`
crashes on `#vim.NIL` when servers return null.

Solution: skip spec-allowed result=null silently, raise an error
on items=null with the server name.

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion

Fix #39400

### CODE REVIEW

File: runtime/lua/vim/lsp/completion.lua [hunk 1]
```diff
@@ -1004,7 +1004,14 @@ local function trigger(bufnr, clients, ctx)
       end
 
       local result = response.result
-      if result and #(result.items or result) > 0 then
+      if type(result) == 'table' and result.items == vim.NIL then
+        vim.notify_once(
+          ('%s: completion response has items=null, expected CompletionItem[]'):format(
```
Comment (justinmk) [inline runtime/lua/vim/lsp/completion.lua]: if https://github.com/neovim/neovim/issues/39400 is a server bug then this should be `assert` or `error`.

Comment (glepnir) [reply runtime/lua/vim/lsp/completion.lua]: This would interrupt the user's experience.  response error also thrown via notify.

File: runtime/lua/vim/lsp/completion.lua [hunk 2]
```diff
@@ -1004,7 +1004,14 @@ local function trigger(bufnr, clients, ctx)
...
+            client and client.name or 'UNKNOWN'
+          ),
+          vim.log.levels.ERROR
+        )
+      elseif result and result ~= vim.NIL and #(result.items or result) > 0 then
```
Comment (justinmk) [inline runtime/lua/vim/lsp/completion.lua:1013]: checking `result ~= vim.NIL` here is another change? is `result == vim.NIL` a spec violation or not? the PR description does not mention this.

File: runtime/lua/vim/lsp/completion.lua (hunk 1 above)
Comment (glepnir) [reply runtime/lua/vim/lsp/completion.lua]: https://github.com/neovim/neovim/blob/c822a2657c78e4b9d3798dfdf93e365460b5b885/runtime/lua/vim/lsp/completion.lua#L997-L1004

File: runtime/lua/vim/lsp/completion.lua (hunk 2 above)
Comment (glepnir) [reply runtime/lua/vim/lsp/completion.lua:1013]: result can be null so added a check here . updated commit msg

```
result: CompletionItem[] | [CompletionList] | null. 
If a CompletionItem[] is provided it is interpreted to be complete. 
So it is the same as { isIncomplete: false, items }
```

File: runtime/lua/vim/lsp/completion.lua (hunk 1 above)
Comment (justinmk) [reply runtime/lua/vim/lsp/completion.lua]: https://github.com/neovim/neovim/issues/39400 also interrupts the user's experience. The point of the discussion there was to show a more meaningful error message, since you said we shouldn't handle it. If we're not going to handle/support/allow it, then we use assert/error to show a more meaningful error. 

`vim.notify*` is a "soft" message and must not be used for errors.

Some existing lsp code uses `vim.notify` where it shouldn't. That's a separate topic...

Comment (glepnir) [reply runtime/lua/vim/lsp/completion.lua]: It’s a server-side issue, but using `assert/error` interrupts the user’s workflow. They can’t continue coding just because the server returned something invalid. Why should we break the user experience for a server error?

Wouldn’t it be better to surface a notification and simply skip the invalid response? In completion.lua, errors are  handled via notify, which avoids disrupting the user. 😮‍💨   If you strongly prefer using assert/error here, I don’t have any objections.

Comment (justinmk) [reply runtime/lua/vim/lsp/completion.lua]: > Wouldn’t it be better to surface a notification and simply skip the invalid response?

In https://github.com/neovim/neovim/issues/39400#issuecomment-4321696306 you said we shouldn't handle it. Skipping it is handling it, i.e. it accepts invalid server response...

> Why should we break the user experience for a server error?

It's already broken. We are improving things by showing a meaningful error.
