### PR TITLE
fix(vim.version): vim.VersionRange:has() with prerelease

### LINKED ISSUE #33316: vim.VersionRange:has() doesn't work correctly with Nvim nightly version
### Problem

See Steps to reproduce and Expected Behavior

### Steps to reproduce

1. nvim --clean
2. `:=vim.version.range('>=0.10'):has(vim.version())` => false
3. `:=vim.version.range('>=0.10'):has('0.12.0')` => true

### Expected behavior

Step 2 should returns true

Btw, It seems to me the culprit is here https://github.com/neovim/neovim/blob/a8edf6e4459d7422c1a96e4f33e350090902dc61/runtime/lua/vim/version.lua#L241

### Nvim version (nvim -v)

v0.12.0-dev-a8edf6e445

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Kubuntu 24.04.1

### Terminal name/version

Kubuntu

### $TERM environment variable

xterm-256color

### Installation

Built from source

### PR DESCRIPTION
**Pull request by brianhuster**
Problem:
fix https://github.com/neovim/neovim/issues/33316

Solution:
The `vim.VersionRange:has()` shouldn't have special handling for prereleases (Why would we need it when `__eq`, `__lt`, `__le` already handle prereleases?).

Also see comment https://github.com/neovim/neovim/pull/33324#issuecomment-2780210160

TODO
- [x] news.txt

Closes https://github.com/neovim/neovim/issues/33316

### CODE REVIEW

**Comment by zeertzjq** [comment]
This isn't correct. `vim.version.range('>=0.12.0'):has('0.12.0-dev')` should still return `false`.

**Comment by brianhuster** [comment]
> This isn't correct. vim.version.range('>=0.12.0'):has('0.12.0-dev') should still return false.

I know that, that's why I added more tests. The added test fails, which means there is something wrong with the logic to compare prerelease. I will check that

**Comment by brianhuster** [comment]
@zeertzjq @justinmk The bug is not in my added test but in an old one
```lua
assert(not vim.version.range('1.2.3-alpha'):has('1.2.3-beta'))
```
From what I test, `vim.version.range('1.2.3-alpha')` is same as `vim.version.range('1.2.3-alpha - 1.2.4-alpha')`, so `1.2.3-beta` is supposed to be inside that range, right? But the test expects the opposite

I think you want to make it be like `vim.version.range('1.2.3-alpha')` should only includes one and only version `1.2.3-alpha`, but since vim.VersionRange is end-exclusive, there is no way to accurately present such "range". Previously, the code just check if `prerelease` of version is different from `self.from` and will returns false, but that breaks other cases like #33316.

So I will propose that if a range only includes one version with major, minor and patch like `1.2.3`, it should be parse as `1.2.3 - 1.2.3` instead of `1.2.3 - 1.2.4`, because there is no version smaller than a patch and prerelease. Then the function `vim.VersionRange:has()` will check if `from` and `to` are the same, then `to` will be inclusive.

Anyway, build metadata doesn't make a version different, for example, I run
```vim
:=vim.version.parse '1.2.3+ubuntu' == vim.version.parse '1.2.3+win'
:=vim.version.parse '1.2.3' == vim.version.parse '1.2.3+win'
```
Both returns true. So I think my proposal is safe to use

**Comment by brianhuster** [comment]
Also I try the `semver` library from Node,
```javascript
const semver = require('semver')
console.log(semver.satisfies('1.2.4-dev', '1.2.3')) // false
```

**Comment by justinmk** [comment]
> `vim.version.range('1.2.3-alpha')` is same as `vim.version.range('1.2.3-alpha - 1.2.4-alpha')`, so `1.2.3-beta` is supposed to be inside that range, right?

All prereleases are considered "equal". `-alpha` and `-beta` are equal. Or maybe it's alphabetical...

**Comment by brianhuster** [comment]
> maybe it's alphabetical...

Yes, it is https://semver.org/#spec-item-11

**Comment by brianhuster** [comment]
Btw, is this considered a breaking change, since it makes that function doesn't exclude `[to]` when `[from] = [to]`?

**Comment by brianhuster** [comment]
Btw, is this considered a breaking change?

File: runtime/lua/vim/version.lua [hunk 1]
```diff
@@ -255,7 +255,8 @@ end
 --- }
 --- ```
 ---
---- `:has()` checks if a version is in the range (inclusive `from`, exclusive `to`).
+--- `:has()` checks if a version is in the range (inclusive `from`, exclusive
+--- `to`. If `from` and `to` are the same, then 'to' will be inclusive).
```
Comment (justinmk) [inline runtime/lua/vim/version.lua:259]:
```suggestion
--- `:has()` checks if a version is in the range (inclusive `from`, exclusive `to`).
```

File: runtime/doc/lua.txt [hunk 2]
```diff
@@ -3973,7 +3973,7 @@ vim.version.range({spec})                                *vim.version.range()*
 <
 
     `:has()` checks if a version is in the range (inclusive `from`, exclusive
-    `to`).
+    `to`. If `from` and `to` are the same, then 'to' will be inclusive).
```
Comment (justinmk) [inline runtime/doc/lua.txt:3976]:
```suggestion
    `to`).
```

File: test/functional/lua/version_spec.lua [hunk 3]
```diff
@@ -100,17 +100,31 @@ describe('version', function()
...
+          assert(range:has(range.to))
+        end
+      end)
     end
 
     it('handles prerelease', function()
-      assert(not vim.version.range('1.2.3'):has('1.2.3-alpha'))
-      assert(vim.version.range('1.2.3-alpha'):has('1.2.3-alpha'))
-      assert(not vim.version.range('1.2.3-alpha'):has('1.2.3-beta'))
+      assert(not vim.version.range('1.2.3'):has('1.2.3-alpha'), '1.2.3 should not have 1.2.3-alpha')
```
Comment (justinmk) [inline test/functional/lua/version_spec.lua:117]: don't need the extra messages. the code is already quite readable. though it was wrong before :)
```suggestion
      assert(not vim.version.range('1.2.3'):has('1.2.3-alpha'))
```

File: test/functional/lua/version_spec.lua [hunk 4]
```diff
@@ -100,17 +100,31 @@ describe('version', function()
...
+      assert(
+        vim.version.range('1.2.3-alpha'):has('1.2.3-alpha'),
+        '1.2.3-alpha should have 1.2.3-alpha'
+      )
+      assert(
```
Comment (justinmk) [inline test/functional/lua/version_spec.lua:122]: worth adding a note here

    -- Per semver spec, prereleases have alphabetical ordering.

**Review by justinmk — APPROVED** [review]
Nice catch. LGTM after comments

**Comment by justinmk** [comment]
> Btw, is this considered a breaking change?

No, but worth mentioning in news-changed.

**Comment by zeertzjq** [comment]
This is not compatible with Nvim's versioning scheme, right?

**Comment by brianhuster** [comment]
Sorry if I'm wrong, but I thought blackported commits aren't supposed to be mention in `news.txt`, right? (I guess that's why Github Actions fails to backport it)

**Comment by justinmk** [comment]
Not sure. Don't want to discourage news.txt when it's appropriate.

**Comment by clason** [comment]
Just means the bot failed and manual backporting is needed. The bot is for convenience, not for restricting what should and should not be backported -- there's a reason it gives instructions for manual backporting. Try following them!
