### PR TITLE
fix(api): preserve WinConfig style when converting float to split

### LINKED ISSUE #37067: window-local option changed when switch buffer
## Steps to reproduce

```lua
vim.o.number = true

local api = vim.api
local buf0 = api.nvim_create_buf(false, true)
api.nvim_buf_call(
  buf0,
  function()
    vim.fn.jobstart({ 'echo', '00000000000' }, {
      term = true,
    })
  end
)

local float_opts =
  { width = 10, height = 10, style = 'minimal', relative = 'editor', row = 5, col = 5 }
local split_opts = { style = 'minimal', split = 'below', win = -1 }

-- ok
-- local win = api.nvim_open_win(buf0, true, split_opts)

local win = api.nvim_open_win(buf0, true, float_opts)
api.nvim_win_set_config(win, split_opts)

local buf1 = api.nvim_create_buf(false, true)
api.nvim_buf_call(
  buf1,
  function() vim.fn.jobstart({ 'echo', '11111111111111111111' }, { term = true }) end
)
--
api.nvim_win_set_buf(win, buf1)
```

## Expected behavior
split window shouldn't enable `&number`.

EDIT: `vim._with({ wo = { number = vim.wo.number } }, function() api.nvim_win_set_buf(win, buf1) end)` fix the issue

## System info

- Nvim version (nvim -v): `v0.12.0-dev-1877 ge1aceb0068` neovim/neovim@e1aceb0068
- Vim (not Nvim) behaves the same?: ?
- Operating system/version: Linux 6.17.9-zen1-1-zen
- Terminal name/version: kitty
- $TERM environment variable: `xterm-kitty`
- Installation: ?

### PR DESCRIPTION
**Pull request by glepnir**
Fix #37067

### CODE REVIEW

File: src/nvim/window.c [hunk 1]
```diff
@@ -5043,6 +5047,11 @@ static void win_enter_ext(win_T *const wp, const int flags)
   // may have to copy the buffer options when 'cpo' contains 'S'
   if (wp->w_buffer != curbuf) {
     buf_copy_options(wp->w_buffer, BCO_ENTER | BCO_NOHELP);
+    // buf_copy_options may override window options with buffer-local or global defaults.
+    // For windows with minimal style, we need to re-apply style.
+    if (wp->w_config.style == kWinStyleMinimal) {
+      win_set_minimal_style(wp);
+    }
```
Comment (zeertzjq) [inline src/nvim/window.c]: Where does `buf_copy_options()` override window options? I don't see any place where it does that.

Comment (glepnir) [reply src/nvim/window.c]: oh you're right, `buf_copy_options` doesn't touch window options at all, my bad. the real issue is in `get_winopts`. when switch buffers, it restores window options from the buffer's saved wininfo , which has number=1.
normally get_winopts() has a check at the end to re-apply minimal style,  So, reassigning the value after the merge should work. What do you think? Can I add a test 🤔

File: src/nvim/window.c [hunk 2]
```diff
@@ -1313,6 +1311,8 @@ win_T *win_split_ins(int size, int flags, win_T *new_wp, int dir, frame_T *to_fl
     // make the contents of the new window the same as the current one
     win_init(wp, curwin, flags);
   } else if (wp->w_floating) {
+    // Save the style before clearing config so it can be re-applied later
+    WinStyle saved_style = wp->w_config.style;
```
Comment (justinmk) [inline src/nvim/window.c]:
```suggestion
    WinStyle saved_style = wp->w_config.style;
```

File: src/nvim/window.c [hunk 3]
```diff
@@ -1337,6 +1336,8 @@ win_T *win_split_ins(int size, int flags, win_T *new_wp, int dir, frame_T *to_fl
     // non-floating window doesn't store float config or have a border.
     merge_win_config(&wp->w_config, WIN_CONFIG_INIT);
     CLEAR_FIELD(wp->w_border_adj);
+    // Restore the style for later re-application
+    wp->w_config.style = saved_style;
```
Comment (justinmk) [inline src/nvim/window.c]:
```suggestion
    // Restore WinConfig style. #37067
    wp->w_config.style = saved_style;
```
