### PR TITLE
fix(messages): better formatting for :highlight with ext_messages

### LINKED ISSUE #31624: messages: ui_attach: sometimes whitespaces are not preserved in chunks
### Problem

Sometimes message chunks passed to `vim.ui_attach` callback have lost some whitespace characters compared to the built-in UI appearance. 

Image

### Steps to reproduce

`init.lua`:
```lua
local api = vim.api
local ns = api.nvim_create_namespace('messageRedirection')

local function log(msg)
  api.nvim_buf_set_lines(1, -1, -1, true, vim.split(msg, '\n'))
  vim.cmd.normal 'G'
end

local function detach()
  api.nvim__redraw({flush = true})
  vim.ui_detach(ns)
  api.nvim__redraw({flush = true})
end

api.nvim_create_autocmd('CmdlineEnter', {callback = detach})

local redirect = true

local function attach()
  if not redirect then
    return
  end
  api.nvim__redraw({flush = true})
  vim.ui_attach(ns, {ext_messages = true, ext_cmdline = false}, function (event, _, content, _)
    if event ~= 'msg_show' then
      return
    end

    vim.schedule(function ()
      log(vim.inspect(content))
      api.nvim__redraw({flush = true})
    end)
  end)
end

api.nvim_create_autocmd({'CmdlineLeave'}, {callback = attach})

api.nvim_create_autocmd({'UIEnter'}, {
  callback = attach
})

api.nvim_create_user_command('MsgRedirToggle', function ()
  redirect = not redirect
  if not redirect then
    detach()
  end
end, {nargs = 0})
```
- `nvim --clean -u init.lua`
- enter `:filter Search hi` command
- enter `:MsgRedirToggle`
- enter `:filter Search hi` command again and compare results, especially look at the chunk contents before `xxx`. I get

Image

Only the first line has any space before `xxx`.

### Expected behavior

Whitespace characters are preserved in ui_attach callback. 

### Nvim version (nvim -v)

v0.11.0-dev-1380+g7121983c45

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian Sid

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

from repo

### PR DESCRIPTION
**Pull request by luukvbaal**
Also avoid going down message callstack with empty message, and remove expected grid for some tests where it did not change, and we are just testing for expected messages.

Fix #31624

### CODE REVIEW

File: src/nvim/message.c [hunk 1]
```diff
@@ -2129,8 +2129,8 @@ void msg_puts_len(const char *const str, const ptrdiff_t len, int hl_id, bool hi
   // If redirection is on, also write to the redirection file.
   redir_write(str, len);
 
-  // Don't print anything when using ":silent cmd".
-  if (msg_silent != 0) {
+  // Don't print anything when using ":silent cmd" or empty message.
+  if (msg_silent != 0 || *str == NUL) {
```
Comment (luukvbaal) [inline src/nvim/message.c:2133]: Without this the change in `msg_puts_display()` resulted in strlen - 1 overflow; there is no need to try to put an empty message onto the screen, or emit it.

File: src/nvim/highlight_group.c [hunk 2]
```diff
@@ -1887,8 +1887,7 @@ bool syn_list_header(const bool did_header, const int outlen, const int id, bool
     if (got_int) {
       return true;
     }
-    msg_outtrans(hl_table[id - 1].sg_name, 0, false);
-    name_col = msg_col;
+    msg_col = name_col = msg_outtrans(hl_table[id - 1].sg_name, 0, false);
```
Comment (justinmk) [inline src/nvim/highlight_group.c:1890]: nit: I think we discourage this

**Review by justinmk — APPROVED** [review]
