### PR TITLE
[RFC] channel: avoid references to non-rooted vimL list with output

### LINKED ISSUE #7768: neovim randomly crashing with ALE
I'm trying neovim because it seems noticeably faster and smoother than vim with my current setup, however on random times it crashes, losing all the work done since the last save. given the error message printed before the crash I could say the culprit is the plugin raising the error, but I suppose nvim should just print the error without crashing, so I'm opening an issue here hoping to have the crash fixed

- `nvim --version`:

NVIM v0.2.3-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171224-58539-1xuae39/build/config -I/tmp/neovim-20171224-58539-1xuae39/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/tmp/neovim-20171224-58539-1xuae39/build/src/nvim/auto -I/tmp/neovim-20171224-58539-1xuae39/build/include
Compilato da matteo@mecbucpro.local

Features: +acl +iconv +jemalloc +tui

- Vim (version: HEAD ) behaves differently? never had a crash with vim
- Operating system/version: macOS 10.13.2
- Terminal name/version: iTerm2 3.1.5 + fish 2.7.1 + tmux 2.6
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

no idea how to reproduce it, it happens randomly

### Actual behaviour

schermata 2017-12-26 alle 15 48 14

### Expected behaviour

an error message without the crash

### PR DESCRIPTION
**Pull request by bfredl**
Likely fixes #7768 #7913. Though I have only been able to reproduce locally with `test_garbagecollect_now()` which is documentedly not safe inside callbacks even with "correct" code.

The vimL list created in `process_channel_event` is not rooted and can thus be freed before `on_channel_event` gets invoked. Simply moving the refcount doesn't work, gc ignores refcounts anyway to break cycles. Instead store the data in the internal `buffer` of the reader.

Additionally, if multiple internal stream callbacks were recieved before vimL callbacks got called (because it is somehow blocked), only invoke one vimL callback with all data.

### CODE REVIEW

File: src/nvim/channel.c [hunk 1]
```diff
@@ -634,10 +627,12 @@ static void on_channel_output(Stream *stream, Channel *chan, RBuffer *buf,
   }
 
   rbuffer_consumed(buf, count);
-  if (reader->buffered) {
-    ga_concat_len(&reader->buffer, ptr, count);
-  } else if (callback_reader_set(*reader)) {
-    process_channel_event(chan, &reader->cb, type, ptr, count, 0);
+  // if buffer wasn't consumed, a pending callback is stalled. Amalgate the
```
Comment (jamessan) [inline src/nvim/channel.c]: I think you were going for "amalgamate" instead of "amalgate" here, but "aggregate" is probably better.

File: test/functional/core/job_spec.lua [hunk 2]
```diff
@@ -433,9 +433,25 @@ describe('jobs', function()
...
-      call rpcnotify(g:channel, 'data', d.data)
     ]])
-    eq({'notification', 'data', {{{'1', ''}, {'2', ''}, {'3', ''}, {'4', ''}, {'5', ''}, {''}}}}, next_msg())
+
+    local expected = {'1', '2', '3', '4', '5', ''}
+    local chunks = eval('d.data')
+    local received = {''}
+    for i, chunk in ipairs(chunks) do
+      if i < #chunks then
+        -- if chunks got joined, a spurios [''] callback was not sent
```
Comment (justinmk) [inline test/functional/core/job_spec.lua]: Typo

**Review by justinmk — APPROVED** [review]

**Comment by bfredl** [comment]
QB failures look unrelated (inccommand, wrapped line syntax highlight).
