### PR TITLE
fix(vim.lsp.enable): shouldn't run LSP configs on startup

### LINKED ISSUE #33761: vim.lsp.enable() loads all config on startup which breaks jsonls with SchemaStore.nvim
### Problem

I will explain in repro step

### Steps to reproduce

1. `export NVIM_APPNAME=nvim_repro`
1. `git clone https://github.com/b0o/SchemaStore.nvim ~/.config/nvim_repro/pack/test/opt/SchemaStore.nvim`
1. Create ~/.config/nvim_repro with the following files
```lua
---@file ~/.config/nvim_repro/after/lsp/jsonls.lua
---@type vim.lsp.Config
return {
	cmd = { 'vscode-json-language-server', '--stdio' },
	filetypes = { 'json', 'jsonc' },
	init_options = {
		provideFormatter = true,
	},
	root_markers = { '.git' },
	settings = {
		json = {
			schemas = require('schemastore').json.schemas(),
			validate = { enable = true },
		},
	},
}
```
```lua
---@file ~/.config/nvim/init.lua
vim.lsp.enable 'jsonls'
```
```vim
" ~/.config/nvim_repro/plugin/plugins.vim
packadd! SchemaStore.nvim
```
1. Run `nvim .`
=> Error : module "schemastore" not found

This bug happens because vim.lsp.enable tries to load all config on startup, but it didn't in Nvim 0.11.1

This is caused by https://github.com/neovim/neovim/pull/33702

### Expected behavior

It shouldn't run all autocmd on startup

### Nvim version (nvim -v)

NVIM v0.12.0-dev-ce8b755a86

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

NA

### Terminal name/version

NA

### $TERM environment variable

NA

### Installation

build from source

### PR DESCRIPTION
**Pull request by brianhuster**
closes #33761

cc @MariaSolOs @mfussenegger @lewis6991 @jfly I'm not sure if https://github.com/neovim/neovim/pull/33702 is even a good idea, shouldn't starting/stopping LSP clients be the job of `vim.lsp.start/stop`? Maybe should extend them to support client name instead

If the name of `vim.lsp.enable` is confusing, maybe it's better to rename it to `activate/add/prepare/setup` instead?

### CODE REVIEW

File: runtime/lua/vim/lsp.lua [hunk 1]
```diff
@@ -623,7 +623,9 @@ function lsp.enable(name, enable)
 
   -- Ensure any pre-existing buffers start/stop their LSP clients.
   if enable ~= false then
-    vim.api.nvim_command('doautoall nvim.lsp.enable FileType')
+    if vim.v.vim_did_enter == 1 then
+      vim.api.nvim_command('doautoall nvim.lsp.enable FileType')
```
Comment (lewis6991) [inline runtime/lua/vim/lsp.lua:627]: I didn't see when this got added.


```suggestion
      vim.cmd.doautoall('nvim.lsp.enable FileType')
```

Comment (brianhuster) [reply runtime/lua/vim/lsp.lua:627]: I came from #33702. Yes, I would like you to review it as well

Comment (brianhuster) [reply runtime/lua/vim/lsp.lua:627]: > Actually if possible it would be better to use nvim_exec_autocmds.

Not sure if nvim_exec_autocmds even support `doautoall`, but that's not my priority. I just want to fix this bug because it is really annoying, it throws error just after I open Nvim.

Or you can revert that PR

**Comment by brianhuster** [comment]
Please add `ci-backport release-0.11` since #33702 has been merged to 0.11 branch
