### PR TITLE
fix(lsp): wait for exit_timeout on quit

### LINKED ISSUE #36752: lsp: `ClientConfig.flags.exit_timeout` is ignored
### Problem

When quitting neovim, the client will be forced stopped immediately, instead of after `ClientConfig.flags.exit_timeout` milliseconds.

I suspect `:stop()` is being called twice, which is escalating to immediate force stopping.

### Steps to reproduce

- Take an existing lsp and modify its source code so it ignores shutdown requests. I used the python-language-server for this. You'll know the modifications work correctly when `:stop()` fails to stop the server.
- Set `vim.lsp.config('*', { flags = { exit_timeout = 3000 } })`, or pick any other large number.
- `:qall`
- Vim will close in much less than 3000 milliseconds.

### Expected behavior

`exit_timeout` is respected.

### Nvim version (nvim -v)

NVIM v0.12.0-dev+1714-a950e8ea9

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Fedora 43

### Terminal name/version

kitty 0.43.1

### $TERM environment variable

xterm-kitty

### Installation

Fedora COPR

### PR DESCRIPTION
**Pull request by phanen**
## Problem

When quitting Nvim, LSP servers will not be force-stopped, even if `ClientConfig.exit_timeout` is an integer.

`pkill emmylua_ls; VIMRUNTIME=runtime/ nvim --clean -u repro.lua repro.lua ; waitpid $(pgrep emmylua_ls)`

```
vim.lsp.config('foo', { cmd = { 'emmylua_ls' }, exit_timeout = 1000 })
vim.lsp.enable('foo')
vim.defer_fn(vim.cmd.quit, 500)
```

## Solution

On VimLeavePre, wait up to `exit_timeout:integer` milliseconds for servers to exit. Do this with an explicit `vim.wait()`, because the actual force-stop is deferred, and won't be attempted if Nvim exits before then.

Fix https://github.com/neovim/neovim/issues/36752

### CODE REVIEW

**Comment by justinmk** [comment]
cc @superatomic

**Comment by zeertzjq** [comment]
Unfortunately this leads to memory leaks...

**Comment by superatomic** [comment]
See #36752 for prior discussion. I've thought about good solutions to this problem on and off for a while now, and all of them have tradeoffs that I'm unhappy with. Still unsure what the best way to solve this bug is.

The options are to block vim on exit, force quit the language server (what we do now), or detach the server on exit. All three of which are bad in their own ways.

**Comment by justinmk** [comment]
> The options are to block vim on exit, force quit the language server (what we do now), or detach the server on exit. All three of which are bad in their own ways.

If the user explicitly set `exit_timeout` then they have explicitly asked Nvim to wait on exit. That was the intended purpose of the field, right?

The [default of exit_timeout=false](https://github.com/neovim/neovim/issues/36752#issuecomment-3596017419) does _not_ wait, so by default Nvim will exit immediately.

Does this PR conform to the above? @phanen

**Comment by superatomic** [comment]
> If the user explicitly set exit_timeout then they have explicitly asked Nvim to wait on exit. That was the intended purpose of the field, right?

Correct. Back when it was an experimental `flags.exit_timeout`, that was its only purpose, although (afaik) it did not actually function and always behaved as if `exit_timeout=true` on exit.

**Comment by phanen** [comment]
> Does this PR conform to the above?

Yes. `exit_timeout=true/integer` sigterm lsp immediately or after a timeout when we cannot stop the server by "shutdown" request.
This pr force nvim to keep alive to execute possible pending sigterm.

I'm not sure why `exit_timeout` was invented (maybe to handle some buggy lsp? but why nvim won't kill all its chlidren automatically on quit), I use it to avoid some dangling lsp. `exit_timeout=false` we only emit "shutdown" request.
I'm not sure if this callback can always executed when it quit nvim.
https://github.com/neovim/neovim/blob/9278f792c374e32de4906dc23adfc9144812c285/runtime/lua/vim/lsp/client.lua#L900-L908

Even it's executed, sometime lsp don't succefully quit (like repro.lua I post above). So have to set `exit_timeout` to force it stop.

> although (afaik) it did not actually function and always behaved as if `exit_timeout=true` on exit.

I think it behave as `exit_timeout=false`, it sent "shutdown" request but it don't sigterm the lsp.

File: runtime/lua/vim/lsp.lua [hunk 1]
```diff
@@ -1155,6 +1155,12 @@ api.nvim_create_autocmd('VimLeavePre', {
     for _, client in pairs(active_clients) do
       client:stop(client.exit_timeout)
     end
+
+    vim.wait(math.huge, function()
+      return vim.iter(active_clients):all(function(client)
+        return client._shutdown_timer == nil
```
Comment (justinmk) [inline runtime/lua/vim/lsp.lua]: Waiting forever (`math.huge`) is not correct. It should wait until `exit_timeout` (if it's a number), that is the entire purpose of `exit_timeout` ?

**Comment by justinmk** [comment]
> but why nvim won't kill all its chlidren automatically on quit)

Waiting for children to exit takes time, X seconds or much longer, then users complain about it. 

> `exit_timeout=false` we only emit "shutdown" request.

Correct, and that should be enough to stop any non-buggy LS.

But if `exit_timeout>0` then Nvim should wait up to that timeout. Are we not doing that? The current approach in this PR doesn't look right. 

The correct behavior is that Nvim waits up to `exit_timeout` milliseconds. Are we doing that or not?

**Comment by superatomic** [comment]
> But if `exit_timeout>0` then Nvim should wait up to that timeout. Are we not doing that?

Currently, Nvim does not wait. That's the bug in #36752. I believe the logic is to prevent Nvim from seemingly "freezing" while it's waiting for a  language server to exit.

**Comment by superatomic** [comment]
cc @mfussenegger since you've been involved in this discussion in the past.

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (phanen) [reply runtime/lua/vim/lsp.lua]: ~change it to wait for max `exit_timeout` of all client. f17a3824d77be08fd2fedce2a747666f06b42a30~

No, this don't fix issue in repro.lua. Use `max_timeout + 1` can fix but not sure if can also work for other case.

**Comment by justinmk** [comment]
> Currently, Nvim does not wait. That's the bug in #36752. I believe the logic is to prevent Nvim from seemingly "freezing" while it's waiting for a language server to exit.

That is the reason for the `false` default. But if the user opts-in to a non-`false` `exit_timeout`, then they have explicitly requested to wait up to that maximum for LS to exit, on Nvim exit.

This PR looks ok but the CI failure is obviously a blocker.

File: runtime/lua/vim/lsp.lua [hunk 2]
```diff
@@ -1152,9 +1152,19 @@ api.nvim_create_autocmd('VimLeavePre', {
...
 
+    local max_timeout = 0
     for _, client in pairs(active_clients) do
       client:stop(client.exit_timeout)
+      if type(client.exit_timeout) == 'integer' then
+        max_timeout = math.max(max_timeout, client.exit_timeout)
+      end
     end
+
+    vim.wait(max_timeout + 1, function()
```
Comment (justinmk) [inline runtime/lua/vim/lsp.lua]: It is probably worth showing a message here.

```suggestion
    if max_timeout > 10 then
      vim.api.nvim_echo(...)
    end
    vim.wait(max_timeout + 1, function()
```

**Comment by superatomic** [comment]
> That is the reason for the `false` default. But if the user opts-in to a non-`false` `exit_timeout`, then they have explicitly requested to wait up to that maximum for LS to exit, on Nvim exit.

Makes sense. It's still unideal that `false` behaves as `true` during Nvim exit, but at least making things work as expected when `exit_timeout` is a number is a good start.

**Comment by justinmk** [comment]
> It's still unideal that `false` behaves as `true` during Nvim exit

~~Agh 🙈 :) It's somewhat defensible because it aligns with `stop(force:boolean)`.~~ But yes, we need to document `exit_timeout` to mention the "Nvim exit" behavior.

Edit: the "waits indefinitely" in the `exit_timeout` docs is misleading. It simply means that Nvim takes no action. And that is consistent with the behavior on VimExit (after this PR).

**Comment by superatomic** [comment]
@phanen you can add a "fix #36752" to this PR.

What's the status on getting this merged? Anything left to do?

**Comment by justinmk** [comment]
> What's the status on getting this merged?

need to fix the [memory leak](https://github.com/neovim/neovim/pull/37597#issuecomment-3810801181) which fails ASAN CI, or find a way to ignore it in CI.

**Comment by superatomic** [comment]
Understood. Unfortunately I don't know enough about that area to help with that myself.

**Comment by zeertzjq** [comment]
~It seems that the current `vim.wait()` interval behavior is wrong: #37836~
#37837 may fix the memory leaks.

**Comment by zeertzjq** [comment]
Needs a rebase

File: runtime/lua/vim/lsp.lua [hunk 3]
```diff
@@ -1132,9 +1132,28 @@ api.nvim_create_autocmd('VimLeavePre', {
...
     log.info('exit_handler', active_clients)
 
+    local max_timeout = 0
     for _, client in pairs(active_clients) do
-      client:stop(client.exit_timeout)
+      local timeout = client.exit_timeout
+      client:stop(timeout)
+      if type(timeout) == 'number' then
+        max_timeout = math.max(max_timeout, timeout)
+      end
```
Comment (justinmk) [inline runtime/lua/vim/lsp.lua]:
```suggestion
      max_timeout = math.max(max_timeout, tonumber(client.exit_timeout) or 0)
      client:stop(client.exit_timeout)
```

**Comment by justinmk** [comment]
I updated the PR description + commit message. There were some non-obvious details here, please try to make that clearer in the future.

I will update the docs in https://github.com/neovim/neovim/pull/37830
