### PR TITLE
fix(lsp): move augroup define to if statement

### LINKED ISSUE #19403: Signs and virtual texts for diagnostics are not shown
### Neovim version (nvim -v)

NVIM v0.8.0-dev-nightly-6-g8e2524500

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.4

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

 build from repo

### How to reproduce the issue

1. Open any file
2. Type something with wrong syntax and then back to NORMAL mode

The signs and virtual texts for the errors are not shown. **Confirmed that this issue was introduced by this commit** (https://github.com/neovim/neovim/commit/6b1a8f23d7da60aa2fe53cd66760176d2f589690). Thank you. 

### Expected behavior

After I type something with syntax error and then back to NORMAL, no signs and virtual texts are shown. 

See the demo below

https://user-images.githubusercontent.com/11582667/179384331-7828a262-e406-4a79-a3a3-a771953481d7.mov

### Actual behavior

The signs and virtual texts should be shown.

### PR DESCRIPTION
**Pull request by glepnir**
fix #19403

### CODE REVIEW

File: runtime/lua/vim/diagnostic.lua [hunk 1]
```diff
@@ -372,14 +372,15 @@ local function schedule_display(namespace, bufnr, args)
...
-  local group = vim.api.nvim_create_augroup(key, { clear = true })
   if not registered_autocmds[key] then
+    local group = vim.api.nvim_create_augroup(key, { clear = true })
     vim.api.nvim_create_autocmd(insert_leave_auto_cmds, {
       group = group,
       buffer = bufnr,
       callback = function()
         execute_scheduled_display(namespace, bufnr)
       end,
+      desc = 'Diagnostic ' .. table.concat(insert_leave_auto_cmds, ','),
```
Comment (ii14) [inline runtime/lua/vim/diagnostic.lua:383]: The information about what events the autocommand is attached is redundant. Maybe the description could be something like `vim.diagnostic: display diagnostics`?

Comment (glepnir) [reply runtime/lua/vim/diagnostic.lua]: done :)
