### PR TITLE
fix(events): make v:event readonly in more events

### LINKED ISSUE #18063: `v:event` should be readonly in `ChanInfo`, `ChanOpen`, `RecordingLeave` and `TermClose` events
### Feature already in Vim?

N/A

### Feature description

In `ChanInfo`, `ChanOpen`, `RecordingLeave` and `TermClose` events, `v:event` is not readonly, whereas in many other events `v:event` is. `v:event` should also be readonly in these four events for consistency.

### PR DESCRIPTION
**Pull request by zeertzjq**
Close #18063

This makes v:event readonly in these four events:
- ChanInfo
- ChanOpen
- RecordingLeave
- TermClose

### CODE REVIEW

File: test/functional/autocmd/channel_spec.lua [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+      {3:Error detected while processing ChanOpen Autocommands for "*":}                  |
+      {3:E46: Cannot change read-only variable "v:event.info"}                            |
+      {4:Press ENTER or type command to continue}^                                         |
+    ]])
+  end)
+
+  it('in ChanInfo event', function()
+    command('autocmd ChanInfo * let v:event.info.id = 0')
+    meths.set_client_info('foo', {}, 'remote', {}, {})
+    screen:expect([[
```
Comment (justinmk) [inline test/functional/autocmd/channel_spec.lua:41]: screen:expect() is a kinda verbose and inefficient way to test this, no?

i'd also consider putting these tests in `test/functional/autocmd/autocmd_spec.lua` since they are really just testing a property of `v:event` for many different cases.

File: src/nvim/channel.c [hunk 2]
```diff
@@ -836,6 +836,7 @@ static void set_info_event(void **argv)
   typval_T retval;
   (void)object_to_vim(DICTIONARY_OBJ(info), &retval, NULL);
   tv_dict_add_dict(dict, S_LEN("info"), retval.vval.v_dict);
+  tv_dict_set_keys_readonly(dict);
```
Comment (justinmk) [inline src/nvim/channel.c:839]: in the future we need an abstraction for this block of code so it doesn't need to be pasted everywhere (and avoids bugs like this)

File: test/functional/autocmd/channel_spec.lua (hunk 1 above)
Comment (zeertzjq) [reply test/functional/autocmd/channel_spec.lua:41]: I guess I can use a `<CR>` to suppress the hit-enter prompt, then evaluate `v:errmsg`.

Comment (zeertzjq) [reply test/functional/autocmd/channel_spec.lua:41]: Oh, I forgot that hit-enter prompt is skipped when there is no UI attached.

**Review by justinmk — APPROVED** [review]
