### PR TITLE
fix(lsp): use LSP textEdit range for completion start boundary

### LINKED ISSUE #37441: Native LSP snippet expansions fail when snippet text contains characters outside `iskeyword`
### Problem

Native LSP completion with snippets fails when the snippet’s trigger text
contains characters not included in `iskeyword`. Only part of the trigger is
replaced, producing hybrid or duplicated content.

---

**Examples:**

1. **Emmet abbreviation:**

Typing:

```
main.container>section.hero>h1+p+button
```

Results in:

```html
main.container>section.hero>h1+p+<main class="container">
  <section class="hero">
    <h1></h1>
    <p></p>
    <button></button>
  </section>
</main>
```

2. **HTML boilerplate snippet (`!`):**

Typing `!` produces:

```html
!<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
</body>
</html>
```

Notice how the initial trigger character (`!` or abbreviation) is duplicated.

### Steps to reproduce

Enable some language server that has snippets whose trigger text includes characters not in `iskeyword` and try expanding one of those snippets with `<C-x><C-o>` `<C-y>`. The above examples use `emmet_language_server`.

### Expected behavior

For the above examples I should have got these:

```html
<main class="container">
  <section class="hero">
    <h1></h1>
    <p></p>
    <button></button>
  </section>
</main>
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
</body>
</html>
```

Adding punctuation characters to 'iskeyword' (`setlocal iskeyword+=.,>,+,-`) fixes snippet insertion but breaks motions like ciw or cw.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-2038+g86c939ba91 

### Vim (not Nvim) behaves the same?

I think Vim doesn't have native support for LSPs or snippets

### Operating system/version

Arch Linux

### Terminal name/version

foot

### $TERM environment variable

xterm-256color

### Installation

tarball release

### PR DESCRIPTION
**Pull request by HarshK97**
Problem:
previously, adjust_start_col returned nil when completion items had different start position from lsp textEdit range
This caused the completion to fall back to `\k*$` which ignores the non-keyword characters

Solution:
- adjust_start_col: now returns the minimun start postion among all items instead of nil
- _lsp_to_complete_items: added logic to add the prefix to the items which start later than minimum, aliging all items

fixes: https://github.com/neovim/neovim/issues/37441

### CODE REVIEW

File: runtime/lua/vim/lsp/completion.lua [hunk 1]
```diff
@@ -457,6 +457,31 @@ function M._convert_results(
...
+        elseif item.textEdit.insert and item.textEdit.insert.start.line == lnum then
+          item_start_char = item.textEdit.insert.start.character
+        end
+
+        if item_start_char then
+          local item_start_byte = vim.str_byteindex(line, encoding, item_start_char, false)
+          if item_start_byte > server_start_boundary then
+            local missing_prefix = line:sub(server_start_boundary + 1, item_start_byte)
+            --- @type string
+            match.word = missing_prefix .. match.word
```
Comment (glepnir) [inline runtime/lua/vim/lsp/completion.lua]: I don't think it's a good idea to use another for loop to modify the word after generating `complete_item`...I have a startcol change PR on https://github.com/neovim/neovim/pull/32142 and I tried test case on it seems like output is correct 🤔

```lua
  it('#test', function ()
    create_server('dummy1', {
      isIncomplete = false,
      items = {
        {
          label = 'div.foo',
          insertTextFormat = 1,
          textEdit = {
            newText = '<div class="foo"></div>',
            range = { start = { line = 0, character = 0 }, ['end'] = { line = 0, character = 7 } },
          },
        },
      },
    })
    exec_lua(function()
      vim.o.completeopt = 'menu,menuone,noinsert'
    end)
    feed('Adiv.foo<C-x><C-O>')
    retry(nil, nil, function()
      eq(
        1,
        exec_lua(function()
          return vim.fn.pumvisible()
        end)
      )
    end)
    feed('<C-Y>')
    eq('<div class="foo"></div>', exec_lua([[return vim.api.nvim_get_current_line()]]))
    eq('div.foo', n.api.nvim_get_vvar('completed_item').abbr)
  end)
```

Comment (HarshK97) [reply runtime/lua/vim/lsp/completion.lua]: Thanks for the feedback! I took a look at #32142 and it's a larger refactor that's been put into milestone 12.0 and open for a year. My pr implements what @mfussenegger suggested, normalizing items relative to min start position.
> But one issue the current implementation does have is if a server were to provide several textEdits each with a different starting word boundary. `vim.fn.complete` needs the same starting point for all items. We could address that by normalizing (trimming or extending) the completion items relative to the left (or right?)-most starting point.
- https://github.com/neovim/neovim/pull/32142#issuecomment-3607107758
And yes, my implementation requires 2 iterations, but as @mfussenegger said, this is necessary to handle mixed start positions.
> But note that to fix that, we'd have to keep iterating twice, because you need to figure out the left/right most position to be able to normalize the other entries. That requires 2 iterations.
- https://github.com/neovim/neovim/pull/32142#issuecomment-3607107758
Happy to close this one if #32142 addresses this, or this could serve as a simpler stopgap fix for #37441

Comment (glepnir) [reply runtime/lua/vim/lsp/completion.lua]: My inference is that `adjust_startcol` doesn't need to be run every time. If `textEdit` is provided, the client doesn't need to infer word boundaries. 

Adjusting the word's prefix can also be done within `to_complete_items` instead of a separate for loop?  I remember I tried that in that PR before.   The number of matches is usually large. The extra for loop increases the time complexity. However, this is usually not a significant concern unless the number is exceptionally large.😮‍💨 ..I'm still confused about some of the implementations of current completions (I'm a little foolish）. but let's hear his thoughts cc @mfussenegger

Comment (mfussenegger) [inline runtime/lua/vim/lsp/completion.lua]: > And yes, my implementation requires 2 iterations, but as @mfussenegger said, this is necessary to handle mixed start positions.

Given the current `vim.fn.complete(start_col)` mechanism 2 iterations are the minimum we need: 1 full iteration to determine the min/max boundaries, a second iteration to do the conversion to matches.

But the implementation here currently has one extra iteration - it modifies `match.word` in a separate third iteration. @glepnir is right that adding the `missing_prefix` could be integrated into `to_complete_items` 

Otherwise the change here looks good to me - I like that the scope is narrower and limited to fixing the mixed textEdit start location issue.

File: test/functional/plugin/lsp/completion_spec.lua [hunk 2]
```diff
@@ -777,6 +777,37 @@ describe('vim.lsp.completion: item conversion', function()
...
   )
 
+  it('prepends prefix for items with different start positions', function()
+    local text = 'div.foo|'
+
+    local item_emmet = {
+      label = 'div.foo',
+      insertTextFormat = 1,
+      textEdit = {
+        newText = '<div class="foo"></div>',
```
Comment (glepnir) [inline test/functional/plugin/lsp/completion_spec.lua]: It would be best to include the expanded test results and cursor position (sould be in there right ? `...>|<..` 🤔) , as I provided above.

File: runtime/lua/vim/lsp/completion.lua [hunk 3]
```diff
@@ -282,9 +282,21 @@ end
 --- @param result vim.lsp.CompletionResult Result of `textDocument/completion`
 --- @param prefix string prefix to filter the completion items
 --- @param client_id integer? Client ID
+--- @param server_start_boundary integer? server start boundary
+--- @param line string? current line content
+--- @param lnum integer? 0-indexed line number
+--- @param encoding string? encoding
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/completion.lua:288]: In the `_convert_results` signature these aren't nullable and always provided. Can they be changed here?


```suggestion
--- @param line string current line content
--- @param lnum integer 0-indexed line number
--- @param encoding string encoding
```

Comment (HarshK97) [reply runtime/lua/vim/lsp/completion.lua:288]: @mfussenegger the lint test for luals failed for `runtime/lua/vim/lsp/handlers.lua`, but this gonna get **deprecated** anyway
```lua
--- @deprecated remove in 0.13
--- @see # https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion
RCS['textDocument/completion'] = function(_, result, _)
  if vim.tbl_isempty(result or {}) then
    return
  end
  local cursor = api.nvim_win_get_cursor(0)
  local row, col = cursor[1], cursor[2]
  local line = assert(api.nvim_buf_get_lines(0, row - 1, row, false)[1])
  local line_to_cursor = line:sub(col + 1)
  local textMatch = vim.fn.match(line_to_cursor, '\\k*$')
  local prefix = line_to_cursor:sub(textMatch + 1)

  local matches = completion._lsp_to_complete_items(result, prefix)
  vim.fn.complete(textMatch + 1, matches)
end
```

So I think we can ignore this, or I can make the params nullable, till then?

Comment (mfussenegger) [reply runtime/lua/vim/lsp/completion.lua:288]: Oh, I wasn't aware of that. In that case I'd make the params nullable until that handler is removed.

**Comment by justinmk** [comment]
Restarted CI. This looks like a good starting point that we can iterate on. Any other blockers?

**Review by mfussenegger — APPROVED** [review]
Tested this for a bit and didn't notice any issues, so lgtm

**Review by glepnir — APPROVED** [review]

**Comment by nickdowell** [comment]
This has broken omni completion for C++ code using unique_ptr and similar constructs - https://github.com/neovim/neovim/issues/39001
