### PR TITLE
fix(messages): make swapfile attention message part of prompt

### LINKED ISSUE #34088: `confirm()` during startup doesn't show message, only choices
### Problem

Calling `confirm()` during startup doesn't show confirm message, only choices.

### Steps to reproduce

1. Create the following 'init.vim':

    ```vim
    call confirm("Hello\nWorld", "&Yes\n&No")
    ```

2. `nvim --clean -u init.vim`
3. Only `[Y]es, (N)o: ` is shown, while there is no "Hello" and "World" lines.

### Expected behavior

Confirmation is shown in full during startup.

Notes:
- It does work as expected not during startup.
- Deferring a redraw doesn't fix the problem and shows that there is room in command line only for a single confirmation line.
- It works on 0.10.4 (without special highlighting), but not on 0.11.1 or Nightly.
- It works with `require('vim._extui')` on Nightly, i.e. with the following code before `confirm`:

    ```vim
    lua << EOF
      require('vim._extui').enable({ enable = true })
    EOF
    ```

- It (kind of) works in Vim in a sense that the whole confirmation message and choices are shown in the shell prior to drawing the Vim itself. @luukvbaal, I'd think this might be somehow related to the ongoing command line rework?

### Nvim version (nvim -v)

NVIM v0.12.0-dev-378+ge9fd6dc956-dirty

### Vim (not Nvim) behaves the same?

No (see "Expected behavior")

### Operating system/version

EndeavourOS Linux x86_64, 6.14.6-arch1-1

### Terminal name/version

Ghostty 1.1.3-arch1

### $TERM environment variable

xterm-ghostty

### Installation

From source and appimages

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  The swapfile attention message is not repeated after clearing
          the screen.
          After clearing the screen `msg_scrolled` is reset without
          clearing other related variables, causing an assert.
Solution: Make the attention message part of the confirm prompt.
          Call `msg_reset_scroll()`.

Fix #34088

### CODE REVIEW

**Comment by luukvbaal** [comment]
Tried but failed to trip the [assert](https://github.com/neovim/neovim/issues/34088#issuecomment-2956440003) in a test.

**Comment by echasnovski** [comment]
Thanks, @luukvbaal! It seems to have fixed the issue indeed (both simple repro and `vim.pack` use case).

**Review by justinmk — APPROVED** [review]

**Comment by gpanders** [comment]
Confirmed that this fixes the assertion I found in https://github.com/neovim/neovim/issues/34423

However, the swapfile dialog still disappears after only a second or two, which still seems like a bug. It is certainly not enough time for a user to read it.

**Demo**

[Screencast from 2025-06-10 13-56-04.webm](https://github.com/user-attachments/assets/3b9cc1cb-036f-4900-b393-d1d1e94527d7)

**Comment by luukvbaal** [comment]
Right, the attention message is not part of the confirm message for whatever reason...

**Review by justinmk — APPROVED** [review]
Great!

**Review by gpanders — APPROVED** [review]

File: src/nvim/memline.c [hunk 1]
```diff
@@ -3245,50 +3247,47 @@ char *get_file_in_dir(char *fname, char *dname)
...
 
-/// Print the ATTENTION message: info about an existing swapfile.
+/// Build the ATTENTION message: info about an existing swapfile.
 ///
 /// @param buf  buffer being edited
 /// @param fname  swapfile name
-static void attention_message(buf_T *buf, char *fname)
+/// @param fhname  swapfile name, home replaced
+/// @param msg  string buffer, emitted as either a regular or confirm message
+static void attention_message(buf_T *buf, char *fname, char *fhname, StringBuilder *msg)
```
Comment (zeertzjq) [inline src/nvim/memline.c:3256]: Rename this function to `build_attention_message()`?

File: src/nvim/memline.c [hunk 2]
```diff
@@ -3472,40 +3474,26 @@ static char *findswapname(buf_T *buf, char **dirp, char *old_fname, bool *found_
...
-              = do_dialog(VIM_WARNING,
-                          _("VIM - ATTENTION"),
-                          name,
-                          proc_running
-                          ? _("&Open Read-Only\n&Edit anyway\n&Recover\n&Quit\n&Abort")
-                          : _("&Open Read-Only\n&Edit anyway\n&Recover\n&Delete it\n&Quit\n&Abort"),
-                          1, NULL, false);
-
-            if (proc_running && dialog_result >= 4) {
+            if (swap_exists_action != SEA_NONE) {
```
Comment (zeertzjq) [inline src/nvim/memline.c:3478]: Why is the check for `choice == SEA_CHOICE_NONE` from `SwapExists` autocommand removed?

Comment (justinmk) [inline src/nvim/memline.c:3478]: coverity:

```
*** CID 554963:           (FORWARD_NULL)
/src/nvim/memline.c: 3484             in findswapname()
3478                 if (swap_exists_action != SEA_NONE) {
3479                   kv_printf(msg, _("Swap file \""));
3480                   kv_printf(msg, "%s", fhname);
3481                   kv_printf(msg, _("\" already exists!"));
3482                   char *run_but = _("&Open Read-Only\n&Edit anyway\n&Recover\n&Quit\n&Abort");
3483                   char *but = _("&Open Read-Only\n&Edit anyway\n&Recover\n&Delete it\n&Quit\n&Abort");
>>>     CID 554963:           (FORWARD_NULL)
>>>     Passing null pointer "msg.items" to "do_dialog", which dereferences it.
3484                   choice = (sea_choice_T)do_dialog(VIM_WARNING, _("VIM - ATTENTION"), msg.items,
3485                                                    proc_running ? run_but : but, 1, NULL, false);
3486     
3487                   // compensate for missing "Delete it" button
3488                   choice += proc_running && choice >= 4;
3489                   // pretend screen didn't scroll, need redraw anyway
/src/nvim/memline.c: 3492             in findswapname()
3486     
3487                   // compensate for missing "Delete it" button
3488                   choice += proc_running && choice >= 4;
3489                   // pretend screen didn't scroll, need redraw anyway
3490                   msg_reset_scroll();
3491                 } else {
>>>     CID 554963:           (FORWARD_NULL)
>>>     Passing null pointer "msg.items" to "msg_outtrans", which dereferences it.
3492                   msg_outtrans(msg.items, 0, false);
3493                 }
3494                 no_wait_return--;
3495                 kv_destroy(msg);
3496                 xfree(fhname);
3497               }
```

Comment (luukvbaal) [reply src/nvim/memline.c:3478]: Yeah I saw the report. Definitely a false positive but maybe this suppresses it?
```diff
diff --git a/src/nvim/memline.c b/src/nvim/memline.c
index 1054e40190..fb640e00d1 100644
--- a/src/nvim/memline.c
+++ b/src/nvim/memline.c
@@ -3258,6 +3258,7 @@ static void attention_message(buf_T *buf, char *fname, char *fhname, StringBuild
   assert(buf->b_fname != NULL);

   emsg(_("E325: ATTENTION"));
+  kv_resize(*msg, IOSIZE);
   kv_printf(*msg, _("Found a swap file by the name \""));
   kv_printf(*msg, "%s\"\n", fhname);
   const time_t swap_mtime = swapfile_info(fname, msg);
```
