### PR TITLE
[RFC] signal_init: Always unblock SIGCHLD.

### LINKED ISSUE #5230: man with MANPAGER "nvim -c 'set ft=man' -" hangs, while `man $PAGE | nvim -c 'set ft=man' -` doesn't
Hi guys! When I heard nvim now supported neat builtin highlighted and linked manpages (from neoman, I suppose?) I know I needed to try this out. Here goes:

- `nvim --version`: NVIM v0.1.5-771-gdfb6a51
- Operating system/version: Linux 3.16.0-77-generic
- Terminal name/version: rxvt-unicode-256color
- `$TERM`: rxvt-unicode

### Actual behaviour

```bash
$ export MANPAGER="nvim -c 'set ft=man' -"
$ man write
```

Never shows the nvim interface. The process list shows a zombie Python process and the its parent nvim process wainting in `epoll_wait`.

I've updated the Python plugin with the following:

```
pip2 install --upgrade --user neovim ; pip3 install --upgrade --user neovim
```

### Expected behaviour

I expect the behaviour of:

```bash
$ export MANPAGER="nvim -c 'set ft=man' -"
$ man write
```

And

```bash
man write | nvim -c 'set ft=man' -
```

To be the same.

However, the former hangs, while the latter doesn't.

I strace'd both the hanging and non-hanging variants and believe to have identified a crucial difference:

Good (`pid(man) = 31976 (not seen here)`, `pid(nvim) = 31977`, `pid(python2) = 32005`):

```
$ cat nvim.good.strace | grep -nP '^(31975|31977|32005).*(CHLD|exited.with)' | column -ts ':' 
...
333     31977 rt_sigaction(SIGCHLD, {SIG_DFL, [], SA_RESTORER|SA_RESTART, 0x7fc7493ffcb0},  <unfinished ...>
15087   31977 rt_sigaction(SIGCHLD, {0x655a80, ~[RTMIN RT_1], SA_RESTORER, 0x7f6c9f558330}, NULL, 8) = 0
15090   31977 clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6c9fb67a90) = 32005
15291   32005 rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
16306   32005 +++ exited with 0 +++
...
```

Bad:  (`pid(man) = 21502`, `pid(nvim) = 21512`, `pid(python2) = 21521`):

```
$ cat nvim.bad.strace | grep -nP '^(21502|21512|21521).*(CHLD|exited.with)' | column -ts ':'
...
13934  21512 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [CHLD], 8) = 0
13936  21512 rt_sigaction(SIGCHLD, {0x655a80, ~[RTMIN RT_1], SA_RESTORER, 0x7f0149c3e330}, NULL, 8) = 0
13938  21512 rt_sigprocmask(SIG_SETMASK, [CHLD], NULL, 8) = 0
13939  21512 clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f014a24da90) = 21521
14139  21521 rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
15143  21521 +++ exited with 0 +++
15157  21502 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=21512, si_uid=287026, si_status=SIGINT, si_utime=46, si_stime=4} ---
...
```

Said another way, in the "good" variant, nvim does not block `CHLD` signals. In the bad variant, it blocks them (before cloning, and doesn't unblock them). Therefore, it cannot receive the SIGCHLD from the python process exiting `*`. It just hangs there in `epoll_wait`.

Perhaps this is a libuv bug. I'm not sure what causes it to be so different.

**NOTE**: The process hierarchies are a bit different in the good/bad variants:

```
GOOD
- 31975 (sh)
  - 31977 (nvim)
    - 32005 (python2, exited)
  - 31976 (man)

BAD
- 21502 (man)
  - 21512 (nvim)
    - 32005 (python2, zombie)
```

It might be that when man spawns nvim, it sets up the signal mask a bit differently, and therefore libuv reacts differently to that. I'm also a bit weirded out that this works fine on OSX.

`*`: Note that this is just getting the version of the Python plugin, this is the invocation: `python2 -c import sys; sys.path.remove(""); sys.stdout.write(str(sys.version_info[0]) + "." + str(sys.version_info[1])); import pkgutil; exit(2*int(pkgutil.get_loader("neovim") is None))`.

### Steps to reproduce using `nvim -u NORC`

I'm afraid this works perfectly fine. Most likely because it doesn't try to start Python :).

### PR DESCRIPTION
**Pull request by justinmk**
Inherited signal mask may block SIGCHLD, which causes libuv to hang at
epoll_wait.

Closes #5230

### CODE REVIEW

**Comment by nhooyr** [comment]
Sorry, I'm confused, why does vim not need to do this?

**Comment by justinmk** [comment]
macos gcc failure is weird:
 
```
/Users/travis/build/neovim/neovim/src/nvim/os/signal.c: In function 'signal_init':
/Users/travis/build/neovim/neovim/src/nvim/os/signal.c:51:3: error: conversion to 'sigset_t' from 'int' may change the sign of the result [-Werror=sign-conversion]
   sigaddset(&mask, SIGCHLD);
   ^
```

File: src/nvim/os/signal.c [hunk 1]
```diff
@@ -45,6 +46,14 @@ void signal_init(void)
   signal_watcher_init(&main_loop, &spwr, NULL);
   signal_watcher_start(&spwr, on_signal, SIGPWR);
 #endif
+
+#ifdef SIGCHLD
```
Comment (aktau) [inline src/nvim/os/signal.c]: Not that it matters too much in this, but to indicate that this should be more like a "clean slate", it might be better to move this code to the top of the function.

**Comment by aktau** [comment]
LGTM

**Comment by justinmk** [comment]
The macos gcc error seems insane.

**Comment by jszakmeister** [comment]
I think I see where the OS X error is coming from:

from signal.h:

```c
int  sigaddset(sigset_t *, int);
#define     sigaddset(set, signo)   (*(set) |= __sigbits(signo), 0)
```

from sys/_types/_sigset.h:

```text
typedef __darwin_sigset_t            sigset_t;
```

and from sys/_types.h:

```text
typedef __uint32_t   __darwin_sigset_t;      /* [???] signal set */
```

So it seems, OS X said sigset_t is unsigned, but then ORs in an int, mixing the types.  So GCC seems correct here... sadly.

**Comment by aktau** [comment]
Something weird is definitely going on. OSX clang (the default compiler) with `-Weverything` doesn't warn for:

```c
#include <stdio.h>
#include <signal.h>

int main() {
  sigset_t s;
  sigemptyset(&s);
  sigaddset(&s, SIGCHLD);
  return 0;
}
```

But gcc (6) does.

```
-std=c11 -Wall -Wextra -Wsign-conversion sig.c -o sig.o |& sed 's/^/gcc-6: /' ; clang -std=c11 -Weverything -Wsign-conversion sig.c -o sig.o |& sed 's/^/clang: /'
gcc-6: sig.c: In function 'main':
gcc-6: sig.c:7:3: warning: conversion to 'sigset_t {aka unsigned int}' from 'int' may change the sign of the result [-Wsign-conversion]
gcc-6:    sigaddset(&s, SIGCHLD);
gcc-6:    ^~~~~~~~~
```

Perhaps it's using different `include` paths. I think I've seen something similar to this before, from way back when, when I was working on the automatic C header to Lua FFI cleaner.

**Comment by justinmk** [comment]
So the system header is broken. Is the `#pragma` approach in this PR the appropriate way to address that?

**Comment by aktau** [comment]
> So the system header is broken. Is the #pragma approach in this PR the appropriate way to address that?

I kinda want to know how Apple is avoiding those warnings. But I can't find it...

**Comment by aktau** [comment]
> I kinda want to know how Apple is avoiding those warnings. But I can't find it...
 Hide all checks

So, I really can't find any pragmas. But I encountered this in the GCC docs:

> -Wsystem-headers
>   Issue warnings for code in system headers. These are normally unhelpful in finding bugs in your own code, therefore suppressed. If you are responsible for the system library, you may want to see them. 
> https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html

And

> The header files declaring interfaces to the operating system and runtime libraries often cannot be written in strictly conforming C. Therefore, GCC gives code found in system headers special treatment. All warnings, other than those generated by ‘#warning’ (see Diagnostics), are suppressed while GCC is processing a system header. **Macros defined in a system header are immune to a few warnings wherever they are expanded. This immunity is granted on an ad-hoc basis, when we find that a warning generates lots of false positives because of code in macros defined in system headers.**
> https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html

Which implies that system headers are usually automatically warning-free. But the case is different for macro's. Macro's in system headers are not exempt from all warnings. Perhaps `-Wsign-conversion` is system-macro-exempt for Clang but not GCC?  I'm unsure where to find an exhaustive list of these things...

That would explain why this happens:

```
$ clang-3.8 -std=c11 -Weverything -Wsign-conversion sig.c -o sig.o
$ clang-3.8 -std=c11 -Weverything -Wsign-conversion $(clang-3.8 -E sig.c -o tmp.c && echo tmp.c) -o sig.o
sig.c:6:13: warning: implicit conversion changes signedness: 'int' to 'unsigned int' [-Wsign-conversion]
  (*(&s) |= __sigbits(20), 0);
         ~~ ^~~~~~~~~~~~~
1 warning generated.
```

...in the second case, the code is inlined, and no longer in a system header.

**Comment by aktau** [comment]
...and another reference from the Clang devs from 2012. Still no word on where to find exactly which warnings/macro's are considered: http://clang-developers.42468.n3.nabble.com/Warnings-from-macro-expansions-vs-system-headers-td4028109.html

**Comment by aktau** [comment]
Man, that pragma solution is unbelievably ugly, but it's starting to look like the only way. libuv doesn't have the same warning levels as us, AFAIK. Perhaps we should file a bug to the GCC devs to make an exception for this one. Or... a rdar:// bug for the Apple folks, but something tells me they'll be less than responsive.

**Comment by jszakmeister** [comment]
Given that we know how this is generated under OS X, we could maybe just cast the argument under OS X:

```c
sigaddset(&s, (sigset_t) SIGCHLD);
```

It's not great either, but less ugly than the pragma stuff and a decent comment would help future readers know why we're doing.

Just a thought.

@aktau I've filed several development related bugs in the past for similar, and they're very unresponsive to them. :-(

**Comment by justinmk** [comment]
@jszakmeister see the first smurf commit. That did not seem to work.

**Comment by aktau** [comment]
@jszakmeister as @justinmk mentioned, you cannot get around it with a cast. The problem is in the implementation of `sigaddset` itself. Clang tells us:

```
sig.c:9:13: warning: implicit conversion changes signedness: 'int' to 'unsigned int' [-Wsign-conversion]
  (*(&s) |= __sigbits((sigset_t) 20), 0);
         ~~ ^~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

Thre return value of `__sigbits` is `int`, not `sigset_t`.

NOTE: SIGCHLD = 20.

**Comment by jszakmeister** [comment]
I tried it with gcc-5 before making the suggestion, but it looks like I just missed the warning.  Sorry for the noise.  I also didn't see the __sigbits() in there to help screw up that trick.  Oh well.

> Thre return value of __sigbits is int, not sigset_t.

Right... I wasn't trying to say it was, I just missed __sigbits being in there.  It is, however, trying to OR an int and an unsigned int, and it was that which I was hoping to avoid. :-)

**Comment by jszakmeister** [comment]
You could go the other way... since it's the mask that it's being OR'd into, you could cast it instead.  That seems to get rid of the warning:

```c
sigaddset((int *) &mask, SIGCHLD);
```

**Comment by justinmk** [comment]
Ok, we still need to detect when this should be done. Because for systems that don't have such headers we could end up with the reverse problem....

**Comment by aktau** [comment]
> You could go the other way... since it's the mask that it's being OR'd into, you could cast it instead. That seems to get rid of the warning:

Very clever!

> Ok, we still need to detect when this should be done. Because for systems that don't have such headers we could end up with the reverse problem....

Exactly.

**Comment by justinmk** [comment]
> `sigaddset((int *) &mask, SIGCHLD);`

I would guess that will break if Apple fixes their headers. So I think disabling the warning for that single line is the least costly approach.

**Comment by justinmk** [comment]
Updated. Will merge after build.

**Comment by aktau** [comment]
> I would guess that will break if Apple fixes their headers. So I think disabling the warning for that single line is the least costly approach.

Indeed that would be the idea. At that point we'll know they fixed their headers and we can adjust the `#ifdef` to only apply to old Apple platforms, up until the point we decide not to support macOS with broken headers anymore.

File: src/nvim/os/signal.c [hunk 2]
```diff
@@ -29,6 +32,9 @@ static bool rejecting_deadly;
 
 void signal_init(void)
 {
+  // Ensure that SIGCHLD is unblocked, else libuv (epoll_wait) may hang.
```
Comment (aktau) [inline src/nvim/os/signal.c]: You could probably make a direct reference to the issue that caused it here.

File: src/nvim/os/signal.c [hunk 3]
```diff
@@ -151,3 +157,27 @@ static void on_signal(SignalWatcher *handle, int signum, void *data)
       break;
   }
 }
+
+static void signal_unblock_SIGCHLD(void)
```
Comment (aktau) [inline src/nvim/os/signal.c]: Why not get rid of the `_SIGCHILD` in the name and pass it as an argument?

**Comment by aktau** [comment]
Said another way. if we go with the current way (pragmas),  we might never know when Apple fixes this, and we might get stuck with technical debt forever. I believe this is how Vim reached its current state as well. Eternal manual vigilance vs automatic machine vigilance and a bit of fixer-upping. I know which one I'd chose.

**Comment by justinmk** [comment]
Agreed. I'm busy the next few days, maybe someone can send a PR.
