### PR TITLE
fix(grid): prevent overflows during extreme resize layouts

### LINKED ISSUE #33883: `assert((size_t)grid_line_maxcol <= linebuf_size);` fail when shrink screen width
### Problem

* `make distclean clean; make CMAKE_BUILD_TYPE=RelWithDebInfo`
* `VIMRUNTIME=runtime build/bin/nvim --clean +"let i=1 | while i <100 | wincmd v | endwhile"`
* then shrink screen width 

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x000070cbf6e52813 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:89
#2  0x000070cbf6df8dc0 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x000070cbf6de057a in __GI_abort () at abort.c:73
#4  0x000070cbf6de04e3 in __assert_fail_base (fmt=<optimized out>, assertion=0x62b14de61610 "(size_t)grid_line_maxcol <= linebuf_size", file=<optimized out>, 
    line=<optimized out>, function=<optimized out>) at assert.c:118
#5  0x000070cbf6df0ed0 in __assert_fail (assertion=<optimized out>, file=<optimized out>, line=<optimized out>, function=<optimized out>) at assert.c:127
#6  0x000062b14d9b19e0 in screengrid_line_start (grid=<optimized out>, row=<optimized out>, col=<optimized out>) at /home/phan/b/neovim/src/nvim/grid.c:385
#7  0x000062b14da4bb09 in grid_line_start (view=0x62b16685ba28, row=<optimized out>) at /home/phan/b/neovim/src/nvim/grid.c:368
#8  win_draw_end (wp=wp@entry=0x62b166859230, c1=126, draw_margin=draw_margin@entry=false, startrow=startrow@entry=1, endrow=45, hl=hl@entry=HLF_EOB)
    at /home/phan/b/neovim/src/nvim/drawscreen.c:2559
#9  0x000062b14da4cc58 in win_update (wp=<optimized out>) at /home/phan/b/neovim/src/nvim/drawscreen.c:2454
#10 0x000062b14da49aff in update_screen () at /home/phan/b/neovim/src/nvim/drawscreen.c:653
#11 0x000062b14da4a5fc in screen_resize (width=77, height=<optimized out>) at /home/phan/b/neovim/src/nvim/drawscreen.c:396
#12 screen_resize (width=<optimized out>, height=<optimized out>) at /home/phan/b/neovim/src/nvim/drawscreen.c:270
#13 0x000062b14dccbaf8 in ui_refresh () at /home/phan/b/neovim/src/nvim/ui.c:249
#14 0x000062b14d9dc4e9 in handle_nvim_ui_try_resize (channel_id=<optimized out>, args=..., arena=<optimized out>, error=<optimized out>)
    at /home/phan/b/neovim/build/src/nvim/auto/api/private/dispatch_wrappers.generated.h:6669
#15 0x000062b14dbb51cf in request_event (argv=<optimized out>) at /home/phan/b/neovim/src/nvim/msgpack_rpc/channel.c:366
#16 0x000062b14daac4ab in multiqueue_oneshot_event (argv=<optimized out>) at /home/phan/b/neovim/src/nvim/event/multiqueue.c:283
#17 0x000062b14dc898f6 in state_handle_k_event () at /home/phan/b/neovim/src/nvim/state.c:120
#18 0x000062b14dbc3e6e in nv_event (cap=<optimized out>) at /home/phan/b/neovim/src/nvim/normal.c:6647
#19 0x000062b14dbb8312 in normal_execute (state=0x7ffc83ab4370, key=<optimized out>) at /home/phan/b/neovim/src/nvim/normal.c:1246
#20 0x000062b14dc897d2 in state_enter (s=0x7ffc83ab4370) at /home/phan/b/neovim/src/nvim/state.c:102
#21 0x000062b14dbb5941 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /home/phan/b/neovim/src/nvim/normal.c:523
#22 0x000062b14d9b84ad in main (argc=<optimized out>, argv=<optimized out>) at /home/phan/b/neovim/src/nvim/main.c:654
```

### Steps to reproduce

.

### Expected behavior

No crash.

### Nvim version (nvim -v)

6dee1672ccc973f50e28e4adb7cbadd481db3f03

### Vim (not Nvim) behaves the same?

no

### Operating system/version

linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

built from source

### PR DESCRIPTION
**Pull request by LorenzoPiombini**
Fixes #33883.

### Root cause
---
when the view is completely full of windows (like in this extreme case), there simply aren’t enough columns left to redraw all the existing windows in the shrinking terminal window.

Neovim basically tries to draw outside the boundaries of the resized terminal, and the assert stops it, causing a crash.

## Problem
When the terminal shrinks, Neovim tries to recompute the layout and adjust every window so that the total width matches the new Columns.
But in this extreme scenario (tons of windows split horizontally), there is simply not enough space for all of them.
the frame width (topframe->fr_width) never reaches the new Columns value , the logic tries to redistribute this negative space across child frames, but it triggers the assert.

 as a solution I suggest to simply not draw the windows after the Column boundaries.

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks. The tests seem like they could fit in https://github.com/neovim/neovim/blob/64cf63a88110459d70d140f6074fa014adaef331/test/functional/ui/screen_basic_spec.lua#L565 , not a new test file. 

And they could be deduplicated. Verbosity is a real cost that adds up since we have 8000+ tests. 

And each test does not need its own `describe`, please always use the codebase conventions.

^ Please apply these guidelines to all PRs.

File: src/nvim/grid.c [hunk 1]
```diff
@@ -592,6 +600,16 @@ void grid_line_flush(void)
...
+  // In extreme layouts we may end up with grid_line_clear_to slightly past grid_line_maxcol,
+  // clamp it so we never try to clear beyond the available segment.
+  if (grid_line_clear_to > grid_line_maxcol) {
+    if (grid_line_maxcol < 0) {
+      grid_line_maxcol = 0;
+    }
+    grid_line_clear_to = grid_line_maxcol;
+  }
+
   assert(grid_line_clear_to <= grid_line_maxcol);
```
Comment (justinmk) [inline src/nvim/grid.c]: This `assert` is here because the situation your code works-around, presumably indicates a bug somewhere else. So adding this workaround (1) doesn't fix the actual problem, and (2) makes this assert redundant (except the `=` case, which strangely the new code does not workaround...)

File: src/nvim/grid.c [hunk 2]
```diff
@@ -375,7 +375,15 @@ void screengrid_line_start(ScreenGrid *grid, int row, int col)
...
   grid_line_coloff = col;
   grid_line_first = (int)linebuf_size;
-  grid_line_maxcol = MIN(grid_line_maxcol, grid->cols - grid_line_coloff);
+
+  // Compute available columns from this offset, but never let it go negative.
+  int avail = grid->cols - grid_line_coloff;
+  if (avail < 0) {
+    // Defensive clamp: nothing to draw if col is already past the last column.
+    avail = 0;
+  }
```
Comment (justinmk) [inline src/nvim/grid.c]: why not use MIN

**Comment by justinmk** [comment]
Using AI is fine, but please review the logic and text yourself before asking for review. There is way too much verbosity here. Clean up the explanation, and code, so that it is simple and meaningful. And after all the verbosity here, the actual approach in this PR is basically just a workaround/hack, and not even a good one. We need your help to narrow down AI output to more meaningful and less noisy results.

**Comment by LorenzoPiombini** [comment]
I will review your comments  tonight, and provide the fixes. I am at work right now.

**Comment by LorenzoPiombini** [comment]
> Using AI is fine, but please review the logic and text yourself before asking for review. There is way too much verbosity here. Clean up the explanation, and code, so that it is simple and meaningful. And after all the verbosity here, the actual approach in this PR is basically just a workaround/hack, and not even a good one. We need your help to narrow down AI output to more meaningful and less noisy results.

Yes this is a bandaid, to avoid the crash for the time being,I wanted to suggest a couple of better solutions, before touching in a  significant way this part of the code. I think to better fix this, we need to agree on a road and then move in that direction. The problem here is that there is no space, for the windows, and we need to put them in another buffer or tab, or we need to limit the maximum number of split available in a buffer so we do not encounter this problem, I just wanted to discuss it with you first, and if you think is a good idea I will implement it.

File: src/nvim/grid.c (hunk 1 above)
Comment (LorenzoPiombini) [reply src/nvim/grid.c]: i will dig deeper in to this one

Comment (LorenzoPiombini) [reply src/nvim/grid.c]: thanks for your feedback Justin!
I think i better understood the problem, and I have a proper fix now!

less code, and no workaround.

File: src/nvim/drawscreen.c [hunk 3]
```diff
@@ -1367,6 +1367,11 @@ static void draw_sep_connectors_win(win_T *wp)
 /// bot: from bot_start to last row (when scrolled up)
 static void win_update(win_T *wp)
 {
+  if (!wp->w_floating && wp->w_wincol >= Columns) {
```
Comment (zeertzjq) [inline src/nvim/drawscreen.c]:
```suggestion
  if (wp->w_grid.target == &default_grid && wp->w_wincol >= Columns) {
```

File: src/nvim/drawscreen.c [hunk 4]
```diff
@@ -1367,6 +1367,11 @@ static void draw_sep_connectors_win(win_T *wp)
 /// bot: from bot_start to last row (when scrolled up)
 static void win_update(win_T *wp)
 {
+  if (wp->w_grid.target == &default_grid && wp->w_wincol >= Columns) {
+    // No need to update/redraw from this windows forward
```
Comment (zeertzjq) [inline src/nvim/drawscreen.c]: "from this windows forward" doesn't seem to match the purpose of this `return` statement.

File: test/functional/ui/screen_basic_spec.lua [hunk 5]
```diff
@@ -646,6 +646,20 @@ local function screen_tests(linegrid)
       ]])
     end)
 
+    it('does not crash Neovim #33883', function()
```
Comment (zeertzjq) [inline test/functional/ui/screen_basic_spec.lua]:
```suggestion
    it('does not crash when windows fill the screen #33883', function()
```

**Review by zeertzjq — APPROVED** [review]
