### PR TITLE
[RDY] ex_getln.c: fix compute_cmdrow() not resetting lines_left

### LINKED ISSUE #8254: inccommand: very long substitution wraps (cmdline) incorrectly
- `nvim --version`: NVIM v0.2.3-969-g2ec94eb23
- Operating system/version: Linux 4.14.0-3-amd64 SMP Debian 4.14.17-1
- Terminal name/version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
:set inccommand=nosplit
:%s/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
```

### Actual behaviour
When the cursor reaches the last column of the terminal and you press 'a' again, the cursor will be on a second line. Press 'a' a few times more and the cursor will be brought back on the first line and the second line will be hidden.

### Expected behaviour
The second line should be visible.

Another bug which I feel has the same root cause can be reproduced like this:
Add the following to your command line and make sure it is at least two lines high:
```
%s/COLLECT_GCC_OPTIONS='-Wall' '-Wextra' '-Wlogical-op' '-Wjump-misses-init' '-Wshadow' '-Wduplicated-cond' '-Wduplicated-branches' '-Wnull-dereference' '-v' '-save-temps' '-mtune=generic' '-march=x86-64'/COLLECT_GCC_OPTIONS='-Wall' '-Wextra' '-Wlogical-op' '-Wjump-misses-init' '-Wshadow' '-Wduplicated-cond' '-Wduplicated-branches' '-Wnull-dereference' '-v' '-save-temps' '-mtune=generic' '-march=x86-64'
```
Then move back before the last `/` and try adding a few `/`. You should see the command line being duplicated multiple times and asking for a redraw with `<C-l>` doesn't change anything.

### PR DESCRIPTION
**Pull request by glacambre**
Before this commit, when `inccomand` was set to `nosplit`, multi-line
substitutions collapsed the command-line.

This happened because when ex_getln.c:cursorcmd() computed a msg_row, it
was given a cmdline_row one line too high. This happened because
message.c:msg_puts_display() was supposed to decrement cmdline_row but
didn't, because of the `msg_no_more && lines_left == 0` check placed
just before the decrementation part in msg_puts_display's while loop.

Every time msg_puts_display writes a line, it decreases `lines_left` (a
variable used to know how many lines are left for prompts). Since
redrawcommandline() did not reset lines_left between calls to
msg_puts_display, every time a character was pressed, `lines_left` was
decremented. This meant that once the user pressed COLUMNS+ROWS numbers
of characters, lines_left would reach 0 and prevent msg_row from being
decremented.

It makes sense to fix setting `lines_left` to `cmdline_row` in
`compute_cmdrow` ; after all, computing where the command line row
should be placed is equivalent to computing how many lines left of
output there are left.

Closes #8254.

Note: I tried to write a test but couldn't get it to fail. It was in inccommand_spec.lua and looked like this:
```lua
it('long :%s/ with inccomand does not collapse cmdline', function()
  local screen = Screen.new(10,5)
  clear()
  common_setup(screen)
  command('set inccommand=nosplit')
  feed(':%s/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')
  screen:expect([[
    {15:~                             }|
    {15:~                             }|
    :%s/AAAAAAAAAAAAAAAAAAAAAAAAAA|
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA|
    AAAAAAAA^                      |
  ]])
end)
```

### CODE REVIEW

**Comment by blueyed** [comment]
As for the test: maybe multiple `feed` calls could be used?

**Comment by glacambre** [comment]
@blueyed, yup, looks like that did the trick! Thanks :)

File: test/functional/ui/inccommand_spec.lua [hunk 1]
```diff
@@ -2634,3 +2634,38 @@ it(':substitute with inccommand, timer-induced :redraw #9777', function()
...
+  feed('A')
+  feed('A')
+  feed('A')
+  feed('A')
+  feed('A')
+  feed('A')
+  feed('A')
+  feed('A')
+  feed('A')
+  feed('A')
```
Comment (justinmk) [inline test/functional/ui/inccommand_spec.lua]: `feed()` actually takes multiple args and will call them as separate RPC requests. So this could be:

    feed('A', 'A', 'A', 'A', 'A', 'A', 'A', ...)

File: test/functional/ui/inccommand_spec.lua [hunk 2]
```diff
@@ -2634,3 +2634,19 @@ it(':substitute with inccommand, timer-induced :redraw #9777', function()
     :%s/foo/ZZZ^                   |
   ]])
 end)
+
+it('long :%s/ with inccomand does not collapse cmdline', function()
```
Comment (justinmk) [inline test/functional/ui/inccommand_spec.lua]:
```suggestion
it('long :%s/ with inccommand does not collapse cmdline', function()
```

**Review by blueyed — APPROVED** [review]

**Comment by blueyed** [comment]
Thank you!

**Comment by blueyed** [comment]
@glacambre 
btw: is your system clock off?
Your last commit (446f3affc) has: "Date:   Mon Aug 12 23:57:12 2019 +0200" (which is in the future still)

**Comment by glacambre** [comment]
Oh, yeah, I was fiddling with my system's clock before I commited this. I accidentally set it to the wrong day. Sorry.
