### PR TITLE
fix: set correct '[ mark when pasting chunks

### LINKED ISSUE #32960: paste sets wrong '[ mark (when pasting a big text stream)
### Problem

Pasting a big string (so that "streamed paste" is invoked with multiple chunks) sets the `'[` mark to the edit from the last chunk, instead of the start of the paste.

### Steps to reproduce

1. paste a big string
2. check the `'[` mark

### Expected behavior

pasting should set the `'[` mark where the paste started, not where the last chunk was inserted.

This patch is a starting point:

```diff
diff --git a/runtime/lua/vim/_editor.lua b/runtime/lua/vim/_editor.lua
index c9b8e68c10b0..3712c13960a3 100644
--- a/runtime/lua/vim/_editor.lua
+++ b/runtime/lua/vim/_editor.lua
@@ -213,7 +213,7 @@ end
 vim.inspect = vim.inspect
 
 do
-  local tdots, tick, got_line1, undo_started, trailing_nl = 0, 0, false, false, false
+  local startpos, tdots, tick, got_line1, undo_started, trailing_nl = nil, 0, 0, false, false, false
 
   --- Paste handler, invoked by |nvim_paste()|.
   ---
@@ -249,6 +249,7 @@ do
     local is_last_chunk = phase == -1 or phase == 3
     if is_first_chunk then -- Reset flags.
       tdots, tick, got_line1, undo_started, trailing_nl = now, 0, false, false, false
+      startpos = vim.fn.getpos('.')
     end
     if #lines == 0 then
       lines = { '' }
@@ -329,6 +330,7 @@ do
       vim.api.nvim_command(('echo "%s"'):format(dots))
     end
     if is_last_chunk then
+      vim.fn.setpos("'[", assert(startpos))
       vim.api.nvim_command('redraw' .. (tick > 1 and '|echo ""' or ''))
     end
     return true -- Paste will not continue if not returning `true`.
```

### Nvim version (nvim -v)

0.11

### PR DESCRIPTION
**Pull request by acehinnnqru**
Fix #32960

### CODE REVIEW

File: runtime/lua/vim/_editor.lua [hunk 1]
```diff
@@ -329,6 +330,7 @@ do
       vim.api.nvim_command(('echo "%s"'):format(dots))
     end
     if is_last_chunk then
+      vim.fn.setpos("'[", assert(startpos))
```
Comment (zeertzjq) [inline runtime/lua/vim/_editor.lua:333]: This is only correct when pasting in Insert mode or on an empty line, not correct when pasting in Normal or Visual mode on an non-empty line. And the mark should not be set at all when in Cmdline (or Terminal?) mode.

Comment (zeertzjq) [reply runtime/lua/vim/_editor.lua:333]: Instead, consider using `getpos("']")` after pasting the first chunk instead.

Comment (acehinnnqru) [reply runtime/lua/vim/_editor.lua:335]: I think the code in the function before has returned when in `cmdline` mode.

File: runtime/lua/vim/_editor.lua [hunk 2]
```diff
@@ -254,6 +254,7 @@ do
       lines = { '' }
     end
     if #lines == 1 and lines[1] == '' and not is_last_chunk then
+      startpos = vim.fn.getpos("'[")
```
Comment (zeertzjq) [inline runtime/lua/vim/_editor.lua:257]: - This isn't correct, as when the first chunk is empty the next non-empty chunk's `'[` mark should be used. In think it should be like this:
- Initialize `startpos` to `nil` and set it to `nil` again after pasting the last chunk
- After pasting a chunk, set `startpos` to `getpos("'[")` only if it previously is `nil`

Comment (acehinnnqru) [reply runtime/lua/vim/_editor.lua:257]: Yeah, sorry, I am working on this, I should change this pr into a draft pr

File: runtime/lua/vim/_editor.lua [hunk 3]
```diff
@@ -328,7 +328,12 @@ do
       -- message when there are zero dots.
       vim.api.nvim_command(('echo "%s"'):format(dots))
     end
+    startpos = startpos == nil and vim.fn.getpos("'[") or startpos
     if is_last_chunk then
+      if startpos then
+        vim.fn.setpos("'[", startpos)
+        startpos = nil
+      end
```
Comment (zeertzjq) [inline runtime/lua/vim/_editor.lua:336]: `startpos` can't be `nil` here, as the previous assignment has already set it to non-`nil`.

Comment (zeertzjq) [reply runtime/lua/vim/_editor.lua:336]: But actually there is another way: when there is only one chunk, don't call `getpos("'[")` or `setpos("'[")` at all, i.e., move the assignment to the `else` branch of the `if is_last_chunk`.

Comment (acehinnnqru) [reply runtime/lua/vim/_editor.lua:336]: > But actually there is another way: when there is only one chunk, don't call `getpos("'[")` or `setpos("'[")` at all, i.e., move the assignment to the `else` branch of the `if is_last_chunk`.

when the chunk is the only chunk, the `startpos` would be nil if we move the assignment into the `else` branch

Comment (zeertzjq) [reply runtime/lua/vim/_editor.lua:336]: Yes, in that case the `if startpos` is needed.

Comment (acehinnnqru) [reply runtime/lua/vim/_editor.lua]: > Yes, in that case the `if startpos` is needed.

So I don't move the assignment but use `assert` and remove the `if`

Comment (zeertzjq) [reply runtime/lua/vim/_editor.lua]: No, I prefer moving the assignment and keeping the `if`.

Comment (acehinnnqru) [reply runtime/lua/vim/_editor.lua]: yeah, I think that's more readable

File: runtime/lua/vim/_editor.lua [hunk 4]
```diff
@@ -328,7 +328,10 @@ do
       -- message when there are zero dots.
       vim.api.nvim_command(('echo "%s"'):format(dots))
     end
+    startpos = startpos == nil and vim.fn.getpos("'[") or startpos
     if is_last_chunk then
+      vim.fn.setpos("'[", assert(startpos))
+      startpos = nil
       vim.api.nvim_command('redraw' .. (tick > 1 and '|echo ""' or ''))
     end
```
Comment (zeertzjq) [inline runtime/lua/vim/_editor.lua:336]: This is what I meant:
```suggestion
    if is_last_chunk then
      if startpos then
        vim.fn.setpos("'[", assert(startpos))
        startpos = nil
      end
      vim.api.nvim_command('redraw' .. (tick > 1 and '|echo ""' or ''))
    else if startpos == nil then
      startpos = vim.fn.getpos("'[")
    end
```

File: runtime/lua/vim/_editor.lua [hunk 5]
```diff
@@ -329,7 +329,13 @@ do
       vim.api.nvim_command(('echo "%s"'):format(dots))
     end
     if is_last_chunk then
+      if startpos then
+        vim.fn.setpos("'[", startpos)
+        startpos = nil
+      end
       vim.api.nvim_command('redraw' .. (tick > 1 and '|echo ""' or ''))
+    else
+      startpos = startpos == nil and vim.fn.getpos("'[") or startpos
```
Comment (zeertzjq) [inline runtime/lua/vim/_editor.lua:338]:
```suggestion
    else if startpos == nil then
      startpos = vim.fn.getpos("'[")
```

File: test/functional/api/vim_spec.lua [hunk 6]
```diff
@@ -853,6 +853,61 @@ describe('API', function()
...
+          1/chunk 1 (start)
+          1/chunk 2
+          1/chunk 3 (end)
+          aaaaaabbbbbbccccccdddddd
+          ]]
+        expect(expected1)
+        -- Only pastes an empty line
+        api.nvim_paste('', true, -1)
+        eq({ 0, 5, 1, 0 }, fn.getpos("'["))
+        api.nvim_paste('', true, 3)
```
Comment (zeertzjq) [inline test/functional/api/vim_spec.lua:887]: This chunk has paste `3`, but it doesn't have a corresponding chunk with phase `1`.

File: test/functional/api/vim_spec.lua [hunk 7]
```diff
@@ -853,6 +853,61 @@ describe('API', function()
...
+        eq({ 0, 5, 1, 0 }, fn.getpos("'["))
+        -- Pastes some empty lines between non-empty line
```
Comment (zeertzjq) [inline test/functional/api/vim_spec.lua:889]:
```suggestion
        -- Pastes some empty chunks between non-empty chunks
```

File: test/functional/api/vim_spec.lua [hunk 8]
```diff
@@ -853,6 +853,59 @@ describe('API', function()
...
+        api.nvim_paste('dddddd\n', true, 3)
+        eq({ 0, 4, 7, 0 }, fn.getpos("'["))
+        expected1 = [[
+          1/chunk 1 (start)
+          1/chunk 2
+          1/chunk 3 (end)
+          aaaaaabbbbbbccccccdddddd
+          ]]
+        expect(expected1)
+        -- Only pastes an empty line
```
Comment (zeertzjq) [inline test/functional/api/vim_spec.lua:884]:
```suggestion
        -- Only pastes an empty chunk
```

**Review by zeertzjq — APPROVED** [review]

**Review by justinmk — APPROVED** [review]
Thank you so much! I'm glad we got this into 0.11 :D

File: test/functional/api/vim_spec.lua [hunk 9]
```diff
@@ -853,6 +853,59 @@ describe('API', function()
         feed('u') -- Undo.
         expect(expected1)
       end)
+      it('stream: multiple chunks sets the correct mark [', function()
```
Comment (justinmk) [inline test/functional/api/vim_spec.lua:856]:
```suggestion
      it("stream: multiple chunks sets correct '[ mark", function()
```

File: test/functional/api/vim_spec.lua [hunk 10]
```diff
@@ -853,6 +853,59 @@ describe('API', function()
...
+          1/chunk 3 (end)
+          ]]
+        expect(expected1)
+        eq({ 0, 1, 1, 0 }, fn.getpos("'["))
+        api.nvim_paste('aaaaaa', true, -1)
+        eq({ 0, 4, 1, 0 }, fn.getpos("'["))
+        api.nvim_paste('bbbbbb', true, 1)
+        eq({ 0, 4, 7, 0 }, fn.getpos("'["))
+        api.nvim_paste('cccccc', true, 2)
+        eq({ 0, 4, 13, 0 }, fn.getpos("'["))
```
Comment (justinmk) [inline test/functional/api/vim_spec.lua:874]: *During* a stream, I think the `'[` marks should be set to the "correct" position. It shouldn't be temporarily wrong. WDYT?

File: runtime/lua/vim/_editor.lua [hunk 11]
```diff
@@ -329,7 +329,13 @@ do
       vim.api.nvim_command(('echo "%s"'):format(dots))
     end
     if is_last_chunk then
+      if startpos then
+        vim.fn.setpos("'[", startpos)
+        startpos = nil
+      end
       vim.api.nvim_command('redraw' .. (tick > 1 and '|echo ""' or ''))
+    elseif startpos == nil then
```
Comment (justinmk) [inline runtime/lua/vim/_editor.lua:337]: Why check `startpos == nil` instead of `phase == 2 or phase == 3` ? 

We can call `setpos()` always during phase 2/3. That ensures the `'[` mark is always correct during a stream, instead of being temporarily wrong until the last chunk.

File: runtime/lua/vim/_editor.lua [hunk 12]
```diff
@@ -329,7 +329,13 @@ do
       vim.api.nvim_command(('echo "%s"'):format(dots))
     end
     if is_last_chunk then
+      if startpos then
+        vim.fn.setpos("'[", startpos)
+        startpos = nil
```
Comment (justinmk) [inline runtime/lua/vim/_editor.lua:334]: Why check `startpos` instead of `phase == 2 or phase == 3` ? 

We can call `setpos()` always during phase 2/3. That ensures the `'[` mark is always correct during a stream, instead of being temporarily wrong until the last chunk.

```suggestion
      if phase == 2 or phase == 3 then
        vim.fn.setpos("'[", assert(startpos))
        startpos = nil
```

File: runtime/lua/vim/_editor.lua [hunk 13]
```diff
@@ -329,7 +329,13 @@ do
...
+      end
       vim.api.nvim_command('redraw' .. (tick > 1 and '|echo ""' or ''))
+    elseif startpos == nil then
+      startpos = vim.fn.getpos("'[")
```
Comment (justinmk) [inline runtime/lua/vim/_editor.lua:338]:
```suggestion
    elseif startpos == 1 then
      startpos = vim.fn.getpos("'[")
```

File: test/functional/api/vim_spec.lua (hunk 10 above)
Comment (acehinnnqru) [reply test/functional/api/vim_spec.lua:874]: It should work. What I doing is trying not to break some correct behaviors, I think

File: runtime/lua/vim/_editor.lua [hunk 14]
```diff
@@ -328,7 +328,14 @@ do
       -- message when there are zero dots.
       vim.api.nvim_command(('echo "%s"'):format(dots))
     end
+    if startpos == nil then
+      startpos = vim.fn.getpos("'[")
+    end
+    if phase == 2 or phase == 3 then
```
Comment (zeertzjq) [inline runtime/lua/vim/_editor.lua:334]:
```suggestion
    if not is_first_chunk then
```

File: runtime/lua/vim/_editor.lua (hunk 13 above)
Comment (zeertzjq) [reply runtime/lua/vim/_editor.lua]: This will not work if the first chunk is empty

File: runtime/lua/vim/_editor.lua [hunk 15]
```diff
@@ -328,7 +328,14 @@ do
...
+      vim.fn.setpos("'[", assert(startpos))
```
Comment (zeertzjq) [inline runtime/lua/vim/_editor.lua:335]:
```suggestion
    else
      vim.fn.setpos("'[", startpos)
```

File: test/functional/api/vim_spec.lua [hunk 16]
```diff
@@ -853,6 +853,39 @@ describe('API', function()
...
+        eq({ 0, 5, 1, 0 }, fn.getpos("'["))
+        api.nvim_paste('bbbbbb', true, 1)
+        eq({ 0, 5, 7, 0 }, fn.getpos("'["))
+        api.nvim_paste('cccccc', true, 2)
+        eq({ 0, 5, 7, 0 }, fn.getpos("'["))
+        api.nvim_paste('dddddd\n', true, 3)
+        eq({ 0, 5, 7, 0 }, fn.getpos("'["))
+        -- Pastes some empty chunks between non-empty chunks
+        api.nvim_paste('', true, 1)
+        eq({ 0, 5, 7, 0 }, fn.getpos("'["))
```
Comment (zeertzjq) [inline test/functional/api/vim_spec.lua:881]: I think this line should be removed, as here nothing has been pasted yet and the first isn't at the start of the paste.

**Comment by acehinnnqru** [comment]
In summary,
1. If the `startpos` is nil, set `startpos` as `vim.fn.getpos("'[")` which means the first **non-empty** chunk has been pasted.
2. If the `startpos` isn't nil, set the `'[` mark as `startpos` which means we are pasting **not-first-chunk-and-non-empty** chunks.

Note,
1. `startpos == nil` is not equal to `phase == 1` because there may be empty chunk pasted which won't arrive here (**was returned at code before**)).

**Review by zeertzjq — APPROVED** [review]
