### PR TITLE
fix(statuscolumn): fix crashes and clang/PVS warnings

### LINKED ISSUE #21722: crash when evaluating statusline
### Describe the bug

after running the command neovim just quits without any errors displaying in the terminal
terminal is usable afterwards (unlike segfaults most times)

### Steps to reproduce

`nvim --clean`
`:lua vim.api.nvim_eval_statusline("%4(%l%):%2c", {})`

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	0x00007fff203faf50 _platform_strcmp + 80
1   nvim                          	0x0000000109f237e4 build_stl_str_hl + 6612
2   nvim                          	0x0000000109c37d96 nvim_eval_statusline + 1494
3   nvim                          	0x0000000109bffa2e nlua_api_nvim_eval_statusline + 510
4   nvim                          	0x0000000109b73d26 lj_BC_FUNCC + 68
```

### Expected behavior

no crash

### Neovim version (nvim -v)

NVIM v0.9.0-dev-647+g1df2db0bc

### Operating system/version

macOS 11.4

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Installation

nightly release

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #21722

### CODE REVIEW

**Review by lewis6991 — APPROVED** [review]

File: src/nvim/drawline.c [hunk 1]
```diff
@@ -472,14 +472,14 @@ static void get_statuscol_display_info(LineDrawState *draw_state, int *char_attr
 {
   *c_extrap = NUL;
   *c_finalp = NUL;
+  const char *const text_end = stcp->text + stcp->text_len;
```
Comment (luukvbaal) [inline src/nvim/drawline.c:475]: LGTM, add this to the `statuscol_t` structure and set in `get_statuscol_str()` instead?

Comment (zeertzjq) [reply src/nvim/drawline.c]: I'll remove `text_len` then. And set `textp` to `NULL` to indicate that 'statuscolumn' hasn't been evaluated.
