### PR TITLE
fix(log): unify error messages for vim.ui_attach/decor providers

### LINKED ISSUE #32917: mention the error that caused "Excessive errors in vim.ui_attach() callback"
### Problem

(partially moved from https://github.com/neovim/neovim/discussions/32916)

`ui_remove_cb()` in `src/nvim/ui.c` switches back to the built-in UI if a custom `vim.ui_attach()` callback errored 10 times. The user gets (almost) constant message `Excessive errors in vim.ui_attach() callback from ns: %d.` without details of the original error.

### Expected behavior

The original error details (with traceback?) are
- appended to the existing message, so it's immediately visible to the user,
- stored in the log file.

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Error messages that cause a vim.ui_attach() namespace to
          detach are not visible in the message history. Decoration
          provider and vim.ui_attach error messages are dissimilar.
Solution: Emit vim.ui_attach() errors as an actual message in addition
          to logging it. Adjust error message format.

Fix #32917

### CODE REVIEW

File: src/nvim/decoration_provider.c [hunk 1]
```diff
@@ -34,9 +34,9 @@ static kvec_t(DecorProvider) decor_providers = KV_INITIAL_VALUE;
 
 static void decor_provider_error(DecorProvider *provider, const char *name, const char *msg)
 {
-  const char *ns_name = describe_ns(provider->ns_id, "(UNKNOWN PLUGIN)");
-  ILOG("error in provider %s.%s: %s", ns_name, name, msg);
-  msg_schedule_semsg_multiline("Error in decoration provider %s.%s:\n%s", ns_name, name, msg);
+  const char *ns = describe_ns(provider->ns_id, "(UNKNOWN PLUGIN)");
+  ILOG("Error in decoration provider %s callback %s:\n%s", ns, name, msg);
+  msg_schedule_semsg_multiline("Error in decoration provider %s callback %s:\n%s", ns, name, msg);
```
Comment (justinmk) [inline src/nvim/decoration_provider.c:39]: let's choose either "provider" or "callback". redundant to say both.

```suggestion
  ILOG("Error in decoration provider \"%s\" (ns=%s):\n%s", name, ns, msg);
  msg_schedule_semsg_multiline("Error in decoration provider \"%s\" (ns=%s):\n%s", name, ns, msg);
```

File: src/nvim/ui.c [hunk 2]
```diff
@@ -712,6 +713,13 @@ void ui_grid_resize(handle_T grid_handle, int width, int height, Error *err)
   }
 }
 
+static void ui_attach_error(uint32_t ns_id, const char *name, const char *msg)
+{
+  const char *ns = describe_ns((NS)ns_id, "(UNKNOWN PLUGIN)");
+  ILOG("Error executing UI event %s callback in %s:\n%s", name, ns, msg);
+  msg_schedule_semsg_multiline("Error executing UI event %s callback in %s:\n%s", name, ns, msg);
```
Comment (justinmk) [inline src/nvim/ui.c:720]:
```suggestion
  ILOG("Error in UI event handler \"%s\" (ns=%s):\n%s", name, ns, msg);
  msg_schedule_semsg_multiline("Error in UI event handler \"%s\" (ns=%s):\n%s", name, ns, msg);
```

File: src/nvim/ui.c [hunk 3]
```diff
@@ -798,7 +806,8 @@ void ui_remove_cb(uint32_t ns_id, bool checkerr)
     ui_cb_update_ext();
     ui_refresh();
     if (checkerr) {
-      msg_schedule_semsg("Excessive errors in vim.ui_attach() callback from ns: %d.", ns_id);
+      const char *ns = describe_ns((NS)ns_id, "(UNKNOWN PLUGIN)");
+      msg_schedule_semsg("Excessive errors in vim.ui_attach() callback from %s.", ns);
```
Comment (justinmk) [inline src/nvim/ui.c:810]:
```suggestion
      msg_schedule_semsg("Excessive errors in vim.ui_attach() callback (ns=%s)", ns);
```

File: test/functional/ui/decorations_spec.lua [hunk 4]
```diff
@@ -767,16 +768,16 @@ describe('decorations providers', function()
     end
     ]]
 
-    screen:expect{grid=[[
-      {2:Error in decoration provider ns1.start:} |
```
Comment (justinmk) [inline test/functional/ui/decorations_spec.lua:771]: the `ns1.start` format seems kind of like a good idea?

**Comment by justinmk** [comment]
off-topic: all errors should probably be logged to NVIM_LOG_FILE by default. That would avoid the redundant ILOG calls in this case.

File: test/functional/ui/decorations_spec.lua (hunk 4 above)
Comment (luukvbaal) [inline test/functional/ui/decorations_spec.lua:771]: Replying to your deleted comment @justinmk. Yes maybe this is a reasonable field format actually, it looked like a typo to me in the source😅

**Comment by przepompownia** [comment]
Not sure if the same error should be reported 10 times, but it's definitely better than no details what's happened.

File: test/functional/ui/decorations_spec.lua (hunk 4 above)
Comment (justinmk) [reply test/functional/ui/decorations_spec.lua:771]: I kind of like it, but not sure if that pattern is understood by many. The `(ns=...)` is probably a more broadly useful pattern for now.

**Comment by luukvbaal** [comment]
I changed it from 10 to 3, matching decoration providers. Still not sure why CI fails, it passes locally.

**Review by justinmk — APPROVED** [review]

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
We may need to set a local NVIM_LOG_FILE in these tests (and use `assert_log()`), to avoid noise in the CI logs. https://github.com/neovim/neovim/actions/runs/13989818285/job/39171064521

```
 1 FAILED TEST
------------------------------------------------------------------------------
$NVIM_LOG_FILE: /Users/runner/work/neovim/neovim/build/.nvimlog
(last 100 lines)
ERR 2025-03-21T10:41:45.899 T3659.25283.0 ui_attach_error:719: Error in "msg_show" UI event handler (ns=(UNKNOWN PLUGIN)):
fast context failure
Error executing lua: [string "<nvim>"]:3: attempt to index global 'err' (a nil value)
stack traceback:
	[string "<nvim>"]:3: in function <[string "<nvim>"]:1>
ERR 2025-03-21T10:41:45.906 T3659.25283.0 ui_attach_error:719: Error in "msg_clear" UI event handler (ns=(UNKNOWN PLUGIN)):
```
