### PR TITLE
lsp: allow launching language servers with uv_spawn using cwd arg

### LINKED ISSUE #14072: Can't start LSP server outside of `$PATH`, even though `cmd_cwd` is provided.
**Problem in the code:** `extra_spawn_params.cwd` is not considered when determining whether `cmd` is executable. Thus the LSP server is not started even though the command is executable in this case.

https://github.com/neovim/neovim/blob/115488105d3ddec2d9251d3adbcdb78dfe3cc9bc/runtime/lua/vim/lsp/rpc.lua#L318-L320

**Background:** I install my language servers locally (outside of `$PATH`) and inject the install directory through `cmd_cwd` as described in the docs. https://github.com/neovim/neovim/blob/115488105d3ddec2d9251d3adbcdb78dfe3cc9bc/runtime/lua/vim/lsp.lua#L370-L374

By the way, this https://github.com/neovim/neovim/pull/11336#issue-336710654 also uses `cmd_cwd`, so this seems like a regression to me.

### PR DESCRIPTION
**Pull request by mjlbach**
Closes #14072

Minor downside in that this doesn't check the error when the executable *in* the new cwd is not valid, but those wouldn't even launch before so I don't consider it a regression :) It still yields an informative error message:

`E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:380: start `./laniserver.index.js` failed: ENOENT: no such file or directory`

You can test with:

```lua
LaunchPyright = function()
  local settings = {
    python = {
      analysis = {
        autoSearchPaths = true;
        useLibraryCodeForTypes = true;
      };
    };
  };
  local client_id = vim.lsp.start_client({
      cmd = {"./langserver.index.js", "--stdio"};
      cmd_cwd = "/usr/local/lib/node_modules/pyright";
      root_dir = vim.fn.getcwd();
      capabilities = vim.lsp.protocol.make_client_capabilities();
      settings = settings;
      on_init = function(client, _)
        client.notify('workspace/didChangeConfiguration', {
          settings = settings;
        })
      end
    })
  vim.lsp.buf_attach_client(0, client_id)
end

vim.cmd([[
  command! -range LaunchPyright  execute 'lua LaunchPyright()'
]])

```

### CODE REVIEW

**Comment by mjlbach** [comment]
@kabouzeid does this address your issue?

File: runtime/lua/vim/lsp/rpc.lua [hunk 1]
```diff
@@ -315,8 +315,11 @@ local function start(cmd, cmd_args, dispatchers, extra_spawn_params)
     dispatchers = { dispatchers, 't', true };
   }
 
-  if not (vim.fn.executable(cmd) == 1) then
-    error(string.format("The given command %q is not executable.", cmd))
+  if extra_spawn_params and extra_spawn_params.cwd then
+      assert(is_dir(extra_spawn_params.cwd), "cwd must be a directory")
+  else if not (vim.fn.executable(cmd) == 1) then
+      error(string.format("The given command %q is not executable.", cmd))
+    end
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/rpc.lua:322]:
```suggestion
  elseif not (vim.fn.executable(cmd) == 1) then
      error(string.format("The given command %q is not executable.", cmd))
```

**Review by mfussenegger — APPROVED** [review]

**Comment by kabouzeid** [comment]
Thank you for looking into this! It *should* fix my issue. Give me a few minutes to test it though :)

In the meantime I fixed this by checking for "./" or "../" in the executable cmd, and in this case prepending the local directory to obtain an absolute path (https://github.com/kabouzeid/nvim-lspinstall/blob/0c41ce5d28ab1f8fb1215693c40406a56c4f0e85/lua/lspinstall.lua#L106-L111). It works perfectly and I suppose we could also use this here to check whether the cmd is executable.

In case it is a concern, I don't think my approach will work on Windows.

**Comment by mjlbach** [comment]
> In case it is a concern, I don't think my approach will work on Windows.

That is *the* concern, and why I didn't throw an error haha

**Comment by kabouzeid** [comment]
I see 😄 

The PR doesn't seem to fix my issue, in fact it seems my code doesn't even reach this code path.
I'm getting this error: `cmd ["./efm-langserver"] is not executable.`.

**Comment by mjlbach** [comment]
Where are you defining cwd? passing cwd in via setup{} in lspconfig isn't supported for reference

**Comment by kabouzeid** [comment]
Yes I'm passing it via the config in lspconfig, why wouldn't this work?

**Comment by mjlbach** [comment]
because we do the same test here: https://github.com/mjlbach/nvim-lspconfig/blob/6a02c860f946f386e085d837674c360cbc8c54e2/lua/lspconfig/util.lua#L213-L216

**Comment by kabouzeid** [comment]
Ah yes. After commenting this out in lspconfig I can now confirm it works :)

File: runtime/lua/vim/lsp/rpc.lua [hunk 2]
```diff
@@ -315,8 +315,11 @@ local function start(cmd, cmd_args, dispatchers, extra_spawn_params)
     dispatchers = { dispatchers, 't', true };
   }
 
-  if not (vim.fn.executable(cmd) == 1) then
-    error(string.format("The given command %q is not executable.", cmd))
+  if extra_spawn_params and extra_spawn_params.cwd then
+      assert(is_dir(extra_spawn_params.cwd), "cwd must be a directory")
+  elseif not (vim.fn.executable(cmd) == 1) then
+      error(string.format("The given command %q is not executable.", cmd))
+    end
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/rpc.lua:322]: I think you forgot to remove the extra `end` after changing the `else if` to `elseif`

File: runtime/lua/vim/lsp/rpc.lua (hunk 1 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp/rpc.lua]: I did, thanks :)

File: runtime/lua/vim/lsp/rpc.lua (hunk 2 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp/rpc.lua]: Should be fixed now :)

**Comment by mjlbach** [comment]
Merged but please file an issue or PR on nvim-lspconfig
