### PR TITLE
fix(lsp): use line start/end for visual line selection

### LINKED ISSUE #22629: code_action makes unexpected ranges when it called form linewise-visual mode
### Problem

If I call `vim.lsp.buf.code_action()` from linewise-visual mode (`V`) without explicit range, it makes a range by `range_from_selection()`.
But it gives not a line-wise range but a characters-wise.

It may makes a buggy behavior like #21326 .

### Steps to reproduce using "nvim -u minimal_init.lua"

It requires a LSP supporting code_action with a range like `gopls`.
(I'm using `gopls` )
So I should prepare a dependencies with like Dockerfile to reproduce it.
I'll do it later.

note for me:

```
require("lspconfig").gopls.setup {}
vim.vim.lsp.set_log_level(vim.log.levels.TRACE)
vim.keymap.set("v", "<leader>lca", vim.lsp.buf.code_action)
```

### Expected behavior

It makes line-wise range.

### Neovim version (nvim -v)

v0.9.0-dev-286777c

### Language server name/version

gopls v0.11.0

### Operating system/version

Ubuntu 22

### Log file

https://gist.github.com/kyoh86/3cbeb80ff07bfee93a84503aedb25e42

### PR DESCRIPTION
**Pull request by mfussenegger**
Fixes https://github.com/neovim/neovim/issues/22629

### CODE REVIEW

**Comment by kyoh86** [comment]
I tried this one and confirm the issue is solved.

File: runtime/lua/vim/lsp/buf.lua [hunk 1]
```diff
@@ -129,6 +130,11 @@ local function range_from_selection()
   local start_col = start[3]
   local end_row = end_[2]
   local end_col = end_[3]
+  if mode == 'V' then
+    start_col = 1
+    local lines = api.nvim_buf_get_lines(0, end_row - 1, end_row, true)
+    end_col = #lines[1]
```
Comment (kyoh86) [inline runtime/lua/vim/lsp/buf.lua:136]: uh, `start_col` is not head line of the selection.
(it is "start" of the selection)
and also, `end_col` is not tail line of the selection.

If we select lines from row 4 to row 6, it works right.
But when we select lines form row 6 to row 4, it does not work.

Comment (kyoh86) [reply runtime/lua/vim/lsp/buf.lua:136]: it is considered in https://github.com/neovim/neovim/pull/22632/files#diff-ac41943ef406cefaa6a72f1e1b157d024e1977bb4ea52e3965318e181ea0effaR141-R151.
So maybe it should processed after them.
