### PR TITLE
fix(api): correctly pass f-args for nvim_create_user_command

### LINKED ISSUE #18095: nvim_create_user_command(): opts.fargs splits arguments differently from <f-args>
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1445-g4bef2f02e

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Solus 4.3 Fortitude

### Terminal name/version

Konsole 21.12.3

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

1. `nvim --clean`
2. Run this Lua code:
    ```vim
    :lua vim.api.nvim_create_user_command('Test1', 'call v:lua.vim.pretty_print([<f-args>])', { nargs = '*' })
    ```
3. Run this command:
    ```vim
    :Test1 this is    a\ test
    ```
4. The message area displays `{ "this", "is", "a test" }`
5. Run this Lua code:
    ```vim
    :lua vim.api.nvim_create_user_command('Test2', function(opts) vim.pretty_print(opts.fargs) end, { nargs = '*' })
    ```
6. Run this command:
    ```vim
    :Test2 this is    a\ test
    ```
7. The message area displays `{ "this", "is", " ", " a\\ test" }`

### Expected behavior

`opts.fargs` should get rid of extra spaces and backslashes, like `<f-args>` (unless this is the intended behavior, in which case I think the difference should be documented in `:help nvim_create_user_command()`)

### Actual behavior

`opts.fargs` keeps redundant spaces, and backslashes from escape sequences are included in the result

### PR DESCRIPTION
**Pull request by gpanders**
Skip runs of whitespace and do not include `\` characters in resulting
strings. This matches the behavior of <f-args> when used with
`:command`.

Closes #18095.

### CODE REVIEW

File: src/nvim/ex_docmd.c [hunk 1]
```diff
@@ -5774,26 +5774,36 @@ static void ex_delcommand(exarg_T *eap)
...
 ///
-/// @note  If no separator is found start = 0 and end = length - 1
-/// @param[in]  arg  String to split
-/// @param[in]  iter Iteration counter
-/// @param[out]  start Start of the split
-/// @param[out]  end End of the split
-/// @param[in]  length Length of the string
+/// @param[in]  arg String to split
+/// @param[in]  arglen Length of {arg}
+/// @param[inout] p Pointer to last character of previous iteration
```
Comment (zeertzjq) [inline src/nvim/ex_docmd.c:5779]:
```suggestion
/// @param[inout] p Index of last character of previous iteration
```

Comment (zeertzjq) [reply src/nvim/ex_docmd.c:5779]: Naming this `p` also looks a bit confusing.

File: test/functional/api/command_spec.lua [hunk 2]
```diff
@@ -124,12 +124,27 @@ describe('nvim_create_user_command', function()
...
+      fargs = {"this", "includes a", "backslash:", "\\"},
+      bang = false,
+      line1 = 1,
+      line2 = 1,
+      mods = "",
+      range = 0,
+      count = 2,
+      reg = "",
+    }, exec_lua [=[
+      vim.api.nvim_command([[CommandWithLuaCallback this   includes\ a backslash: \\]])
```
Comment (muniter) [inline test/functional/api/command_spec.lua:142]: Thanks for looking into this gp.

Just a sanity check: from the fargs docs:

> replaces every pair of backslashes (\\) with one backslash

I see the function does ir as the last `\\` is replaces to only one `\`. Right?

Comment (gpanders) [reply test/functional/api/command_spec.lua:142]: As far as I can tell this matches what you get when you use

```vim
func Foo(...)
  echom a:000
endfunc

command -nargs=* Foo call Foo(<f-args>)
```

Then run

```vim
:Foo this   includes\ a backslash: \\
```

and you get `['this', 'includes a', 'backslash:', '\']`.

Comment (gpanders) [reply test/functional/api/command_spec.lua:142]: Ah it's still not write, because

```vim
:Foo a\b
```

shows `['a\b']`. So the backslash is preserved in that case.

Comment (muniter) [reply test/functional/api/command_spec.lua:142]: Nice! This makes us match fargs now, although rules are quirky. But also if the command wants the full cmdline they can use the unmodified `args`. 👍
