### PR TITLE
fix(watch): ignore nonexistent paths (ENOENT)

### LINKED ISSUE #28058: runtime/lua/vim/_watch.lua:99: ENOENT: no such file or directory
### Problem

Set up lsp per instructions, open an Go file in a Go project on neovim HEAD, I see error message:

```
LSP[gopls]: Error SERVER_REQUEST_HANDLER_ERROR: "...eovim/HEAD-0c0be09/share/nvim/runtime/lua/vim/_watch.lua:100: ENOENT: no such file or directory"
```

### Steps to reproduce

1. install gopls: `go install golang.org/x/tools/gopls@latest`
    ```
    $ gopls version
    golang.org/x/tools/gopls v0.15.2
    ```
2. run the following:
    - `mkdir -p ~/tmp/test-nvim`
    - `cd ~/tmp/test-nvim`
    - `go mod init test-nvim`
    - `go work init`
3. create `test.lua` with content:
    ```lua
    vim.lsp.start({
	    name = "gopls",
	    cmd = { "gopls" },
	    root_dir = vim.fs.dirname(vim.fs.find({ "go.work", "go.mod" }, { upward = true })[1]),
    })
    ```
4. `nvim --clean -u ~/tmp/test-nvim/test.lua main.go`
5. Error shows:

```
LSP[gopls]: Error SERVER_REQUEST_HANDLER_ERROR: "...eovim/HEAD-0c0be09/share/nvim/runtime/lua/vim/_watch.lua:99: ENOENT: no such fil
e or directory"
```

I put a debug print statement in https://github.com/neovim/neovim/blob/master/runtime/lua/vim/_watch.lua#L99

```lua
  print(vim.inspect(path))
```

I see the following message:

```
11:09:45 msg_show "/Users/jackieli/tmp/test-nvim"
11:09:45 msg_show "/Users/jackieli/tmp/test-nvim/vendor"
11:09:45 msg_show LSP[gopls]: Error SERVER_REQUEST_HANDLER_ERROR: "...eovim/HEAD-0c0be09/share/nvim/runtime/lua/vim/_watch.lua:100: ENOENT: no such file or directory"
```

I believe the lsp handler is trying to add the folders to the file watch list but my project isn't using Go's 'vendor/' directory, it should skip or fail silently. But it shows the error instead.

This error only starts to show up recently. The LSP related functionality is not affected.

**Note** that this doesn't happen with 0.9.5. Tested with:

`/opt/homebrew/Cellar/neovim/0.9.5/bin/nvim --clean -u ~/tmp/test-nvim/test.lua main.go`

### Expected behavior

No error showing

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2702+g 0c0be09ea Homebrew

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 14.2.1

### Terminal name/version

kitty 0.33.1

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### PR DESCRIPTION
**Pull request by justinmk**
## Problem:
The `_watch.watch()` strategy may fail if the given path does not exist:

    …/vim/_watch.lua:101: ENOENT: no such file or directory
    stack traceback:
        [C]: in function 'assert'
        …/vim/_watch.lua:101: in function <…/vim/_watch.lua:61>
        [string "<nvim>"]:5: in main chunk

- `_watch.watch()` actively asserts any error returned by `handle:start()`.
- whereas `_watch.watchdirs()` just ignores the result of `root_handle:start()`.

Servers may send "client/registerCapability" with "workspace/didChangeWatchedFiles" item(s) (`baseUri`) which do not actually exist on the filesystem: https://github.com/neovim/neovim/issues/28058#issuecomment-2189929424

    {
      method = "client/registerCapability",
      params = {
        registrations = { {
            method = "workspace/didChangeWatchedFiles",
            registerOptions = {
              watchers = { {
                  globPattern = {
                    baseUri = "file:///Users/does/not/exist",
                    pattern = "**/*.{ts,js,mts,mjs,cjs,cts,json,svelte}"
                  }
                },
    ...
    }

## Solution:
- Remove the assert in `_watch.watch()`.
- Show a once-only message for both cases.
- More detailed logging is blocked until we have `nvim_log` / `vim.log`.

fix #28058

### CODE REVIEW

File: test/functional/lua/watch_spec.lua [hunk 1]
```diff
@@ -21,17 +21,44 @@ describe('vim._watch', function()
...
+        watchfunc_
+      )
+    end
+
+    it('ignores nonexistent paths (watchfunc=' .. watchfunc .. '())', function()
+      skip(watchfunc == 'inotify' and n.fn.executable('inotifywait') == 0, 'inotifywait not found')
+
+      do_watch('/i am /very/funny.go', watchfunc)
+
+      vim.uv.sleep(200)
```
Comment (justinmk) [inline test/functional/lua/watch_spec.lua:49]: 200ms per test 🙈

File: test/functional/lua/watch_spec.lua [hunk 2]
```diff
@@ -21,17 +21,44 @@ describe('vim._watch', function()
...
+
+      eq(0, exec_lua [[return #_G.events]])
```
Comment (justinmk) [inline test/functional/lua/watch_spec.lua:51]: fails correctly before patch

**Comment by justinmk** [comment]
`inotifywait` on bsd seems to expect an existing path? or somehow watch.inotify() is getting invokved on the bsd CI but `inotifywait` isn't found?

```
test/functional/testnvim.lua:126: Error executing lua: /tmp/cirrus-ci-build/runtime/lua/vim/_system.lua:244: ENOENT: no such file or directory
stack traceback:
	[C]: in function 'error'
	/tmp/cirrus-ci-build/runtime/lua/vim/_system.lua:244: in function 'spawn'
	/tmp/cirrus-ci-build/runtime/lua/vim/_system.lua:335: in function 'system'
	/tmp/cirrus-ci-build/runtime/lua/vim/_watch.lua:287: in function </tmp/cirrus-ci-build/runtime/lua/vim/_watch.lua:286>
	[string "<nvim>"]:5: in main chunk

stack traceback:
	test/functional/testnvim.lua:126: in function 'exec_lua'
	test/functional/lua/watch_spec.lua:42: in function 'do_watch'
	test/functional/lua/watch_spec.lua:118: in function <test/functional/lua/watch_spec.lua:77>
```

File: test/functional/lua/watch_spec.lua [hunk 3]
```diff
@@ -21,17 +21,67 @@ describe('vim._watch', function()
...
+
+      spy_notify_once()
+      do_watch('/i am /very/funny.go', watchfunc)
+
+      if watchfunc ~= 'inotify' then -- watch.inotify() doesn't (currently) call vim.notify_once.
+        t.retry(nil, 2000, function()
+          t.eq(msg, last_notify_once_msg())
+        end)
+      end
+      eq(0, exec_lua [[return #_G.events]])
```
Comment (justinmk) [inline test/functional/lua/watch_spec.lua:74]: fails correctly before patch

**Review by mfussenegger — APPROVED** [review]

File: test/functional/lua/watch_spec.lua [hunk 4]
```diff
@@ -21,30 +21,87 @@ describe('vim._watch', function()
...
+        skip(not is_ci() and n.fn.executable('inotifywait') == 0, 'inotifywait not found')
       end
 
+      -- Note: because this is not `elseif`, BSD is skipped for *all* cases...?
       if watchfunc == 'watch' then
         skip(is_os('mac'), 'flaky test on mac')
         skip(is_os('bsd'), 'Stopped working on bsd after 3ca967387c49c754561c3b11a574797504d40f38')
+      elseif watchfunc == 'watchdirs' and is_os('mac') then
+        -- Bump this (or fix the bug) if CI continues to fail in future versions of macos CI.
+        skip(is_ci() and vim.uv.os_uname().release == '23.6.0', 'weird failure for macOS arm 14 CI')
```
Comment (justinmk) [inline test/functional/lua/watch_spec.lua:95]: Very strange failure only in macos 14 CI (darwin 23.6.0). I can't see how the test changes would cause this (clear() is correctly invoked for each test, and there are no logical changes...).

```
FAILED   test/functional/lua/watch_spec.lua @ 82: vim._watch watchdirs() detects file changes
test/functional/lua/watch_spec.lua:149: Expected objects to be the same.
Passed in:
(table: 0x0116023758) {
 *[1] = {
    [change_type] = 3
   *[path] = '/Users/runner/work/neovim/neovim/build/Xtest_tmpdir/nvim_KFMvPbXk9a/nvim_KFMvPbXk9a' }
  [2] = {
    [change_type] = 3
    [path] = '/Users/runner/work/neovim/neovim/build/Xtest_tmpdir/nvim_KFMvPbXk9a/file' } }
Expected:
(table: 0x010d9d6548) {
 *[1] = {
    [change_type] = 1
   *[path] = '/Users/runner/work/neovim/neovim/build/Xtest_tmpdir/nvim_KFMvPbXk9a/file' }
  [2] = {
    [change_type] = 3
    [path] = '/Users/runner/work/neovim/neovim/build/Xtest_tmpdir/nvim_KFMvPbXk9a/file' } }

stack traceback:
	test/functional/lua/watch_spec.lua:149: in function <test/functional/lua/watch_spec.lua:82>
```
