### PR TITLE
fix(diagnostic): support function type of float in open_float()

### LINKED ISSUE #31573: `vim.diagnostic.config` does not apply options returned from functions
### Problem

`:h vim.diagnostic.Opts` says

```
    Each of the configuration options below accepts one of the following:
    • `false`: Disable this feature
    • `true`: Enable this feature, use default settings.
    • `table`: Enable this feature with overrides. Use an empty table to use
      default values.
    • `function`: Function with signature (namespace, bufnr) that returns any
      of the above.
...
      • {float}?             (`boolean|vim.diagnostic.Opts.Float|fun(namespace: integer, bufnr:integer): vim.diagnostic.Opts.Float`)
                             Options for floating windows. See
                             |vim.diagnostic.Opts.Float|.
```

but

```lua
vim.diagnostic.config({
  float = {
    border = 'rounded',
    header = '',
    scope = 'cursor',
  },
})
```

and

```lua
vim.diagnostic.config({
  float = function (namespace, bufnr)
    return {
      border = 'rounded',
      header = '',
      scope = 'cursor',
    }
  end,
})
```

have totally different behaviors; the function version doesn't seem to do anything at all.

### Steps to reproduce

Add

```lua
vim.diagnostic.config({
  float = function (namespace, bufnr)
    return {
      border = 'rounded',
      header = '',
      scope = 'cursor',
    }
  end,
})
```

to your config and open a diagnostic floating window `vim.diagnostic.show_float()`

### Expected behavior

Should look the same as 

```lua
vim.diagnostic.config({
  float = {
    border = 'rounded',
    header = '',
    scope = 'cursor',
  },
})
```

### Nvim version (nvim -v)

 v0.10.2 

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 15.2

### Terminal name/version

Terminal.app

### $TERM environment variable

xterm-256color

### Installation

brew

### PR DESCRIPTION
**Pull request by glepnir**
Problem: the float field of vim.diagnostic.config can be a function type but function was ignored in open_float function.

Solution: check global_diagnostic_options.float type before use for funciton type

Fix #31573

### CODE REVIEW

File: runtime/lua/vim/diagnostic.lua [hunk 1]
```diff
@@ -1824,8 +1824,13 @@ function M.open_float(opts, ...)
     -- does not have a dedicated table for configuration options; instead, the options are mixed in
     -- with its `opts` table which also includes "keyword" parameters. So we create a dedicated
     -- options table that inherits missing keys from the global configuration before resolving.
-    local t = global_diagnostic_options.float
-    local float_opts = vim.tbl_extend('keep', opts, type(t) == 'table' and t or {})
```
Comment (justinmk) [inline runtime/lua/vim/diagnostic.lua:1828]: can't we just change this to:

```lua
local float_opts = vim.tbl_extend('keep', opts, type(t) == 'table' and t or (
    type(t) == 'function' and global_diagnostic_options.float(0, bufnr) or {}
))

also, does the comment above need an small update?

```

File: runtime/lua/vim/diagnostic.lua [hunk 2]
```diff
@@ -1824,8 +1824,13 @@ function M.open_float(opts, ...)
     -- does not have a dedicated table for configuration options; instead, the options are mixed in
     -- with its `opts` table which also includes "keyword" parameters. So we create a dedicated
     -- options table that inherits missing keys from the global configuration before resolving.
-    local t = global_diagnostic_options.float
```
Comment (justinmk) [inline runtime/lua/vim/diagnostic.lua:1827]: can't we just change this to:

    local t = global_diagnostic_options.float or global_diagnostic_options.float(0, bufnr)

Comment (glepnir) [reply runtime/lua/vim/diagnostic.lua:1827]: yes i forget it use `if_nil` to set a default value always.

File: runtime/lua/vim/diagnostic.lua [hunk 3]
```diff
@@ -1822,10 +1822,11 @@ function M.open_float(opts, ...)
...
     -- Unlike the other decoration functions (e.g. set_virtual_text, set_signs, etc.) `open_float`
     -- does not have a dedicated table for configuration options; instead, the options are mixed in
-    -- with its `opts` table which also includes "keyword" parameters. So we create a dedicated
-    -- options table that inherits missing keys from the global configuration before resolving.
-    local t = global_diagnostic_options.float
-    local float_opts = vim.tbl_extend('keep', opts, type(t) == 'table' and t or {})
+    -- with its `opts` table. We create a dedicated options table (`float_opts`) that inherits
+    -- missing keys from the global configuration (`global_diagnostic_options.float`), which can
+    -- be a table or a function.
+    local t = global_diagnostic_options.float or global_diagnostic_options.float(0, bufnr)
```
Comment (justinmk) [inline runtime/lua/vim/diagnostic.lua:1828]: oh I may have made a mistake, should it be more like this?:

```suggestion
    local o = global_diagnostic_options
    local t = type(o.float) == 'table' and o.float or (type(o.float) == 'function' and o.float(0, bufnr) or {})
```

File: test/functional/lua/diagnostic_spec.lua [hunk 4]
```diff
@@ -1749,6 +1749,18 @@ describe('vim.diagnostic', function()
           return _G.count_extmarks(_G.diagnostic_bufnr, _G.diagnostic_ns)
         end)
       )
+
+      eq(
```
Comment (justinmk) [inline test/functional/lua/diagnostic_spec.lua:1753]: -- `float` option defined as a function.

File: test/functional/lua/diagnostic_spec.lua [hunk 5]
```diff
@@ -1749,6 +1749,18 @@ describe('vim.diagnostic', function()
...
+        true,
+        exec_lua(function()
+          vim.diagnostic.config({
+            float = function(_, _)
+              return { border = 'rounded' }
+            end,
+          })
+          return type(vim.diagnostic.config().float) == 'function'
```
Comment (justinmk) [inline test/functional/lua/diagnostic_spec.lua:1761]: instead of asserting this (which doesn't really test much), can we assert `eq('rounded', ...)` ?

And before this assertion, check that border is NOT 'rounded', to make sure we are actually testing something.

Comment (glepnir) [reply test/functional/lua/diagnostic_spec.lua:1761]: I have added in open_float

File: test/functional/lua/diagnostic_spec.lua [hunk 6]
```diff
@@ -2500,6 +2513,37 @@ describe('vim.diagnostic', function()
       )
     end)
 
+    it('', function()
```
Comment (justinmk) [inline test/functional/lua/diagnostic_spec.lua]: 👀

**Comment by justinmk** [comment]
rebase, and please double-check if an existing test can be updated instead (if it saves a lot of code)
