### PR TITLE
fix(health): emit `Progress` message

### LINKED ISSUE #36243: ui2: persistant healthcheck loading message
### Problem

When running `:checkhealth` while using `vim._extui`, "Running healthchecks..." will appear after the checks have finished running instead of while they are running.

### Steps to reproduce

- `nvim --clean`
- `:lua require('vim._extui').enable { enable = true, msg = { target = 'cmd', timeout = 4000 } }`
- `:checkhealth`

"Running healthchecks..." will not appear while the health checks are running, but after they are finished running, the text will appear in the command-line.

Image

### Expected behavior

Without enabling `vim._extui`:

Image

"Running healthchecks..." will appear while the health checks are running, and disappears afterwards.

### Nvim version (nvim -v)

NVIM v0.12.0-dev+1466-a04c73ca0

### Vim (not Nvim) behaves the same?

non-applicable

### Operating system/version

Fedora 42

### Terminal name/version

kitty 0.42.2

### $TERM environment variable

xterm-kitty

### Installation

https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/

### PR DESCRIPTION
**Pull request by yochem**
Problem:
The `"Running healthchecks..."` message doesn't inform the user much and
is a hack from before we got a way to emit actual progress messages.

Solution:
Use `nvim_echo` to emit progress messages showing the name of the report
that is currently running.

Closes #36243

### CODE REVIEW

**Comment by justinmk** [comment]
Good idea. Why per report instead of 1 progress for all reports?

**Comment by yochem** [comment]
Sorry the description is wrong. I meant it shows

```
checkhealth: 10% checking vim.treesitter...
checkhealth: 20% checking vim.lsp...
...
checkhealth: done
```

The previous message simply showed "running healthchecks..." Instead of _which_ healthcheck

**Comment by justinmk** [comment]
To fix the tests it looks like many of them just need `checkhealth: checks done` added.

File: runtime/lua/vim/health.lua [hunk 1]
```diff
@@ -371,6 +371,21 @@ local function get_summary()
...
+---Emit progress messages
+---@param len integer
+---@return fun(status: 'success'|'running', idx: integer, fmt: string, ...: any): nil
+local function progress_report(len)
+  local progress = { kind = 'progress', title = 'checkhealth' }
+
+  return function(status, idx, fmt, ...)
+    progress.status = status
+    progress.percent = status == 'success' and nil or math.floor(idx / len * 100)
+    -- percent=0 emits the reporting of percentage, so use 1% instead
```
Comment (eamonburns) [inline runtime/lua/vim/health.lua]: I think "emits" should be changed to "omits".

File: runtime/lua/vim/health.lua [hunk 2]
```diff
@@ -371,6 +371,24 @@ local function get_summary()
   return s
 end
 
+---Emit progress messages
+---@param len integer
+---@return fun(status: 'success'|'running', idx: integer, fmt: string, ...: any): nil
+local function progress_report(len)
```
Comment (justinmk) [inline runtime/lua/vim/health.lua:377]: We should probably put this in `_core/util.lua` , so we can start reusing it and getting a feel for what a public api might look like. And maybe it can be re-used from `pack.lua` which has a similar thing.

Comment (yochem) [reply runtime/lua/vim/health.lua]: Yeah I tailored the one from vim.pack to the needs here. Agree that a initial private implementation would be a good first step
