### PR TITLE
fix(lsp): set tagstack on jump via goto methods

### LINKED ISSUE #30926: LSP: `vim.lsp.buf.definition` does not set tagstack
### Problem

Since commit 0083e03d6, `vim.lsp.buf.definition` does not seem to set the tag stack. This results in things like `C-o` being completely broken and jumping back to random places.

Seems this is also a known issue as mentioned in #30877 as well. 

### Steps to reproduce

With an LSP server like `clangd` or `rust-analyzer`, jump to a function definition with `vim.lsp.buf.definition` and then press `C-o`. Cursor does not come back to the initial location from where `vim.lsp.buf.definition` was triggered.

### Expected behavior

Jumping with `vim.lsp.buf.definition` and then pressing `C-o` should jump back to the initial location.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1035+g50e63c817

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.14.0 (22a44757)

### $TERM environment variable

tmux-256color

### Installation

Build from repo

### PR DESCRIPTION
**Pull request by mfussenegger**
Follow up to https://github.com/neovim/neovim/pull/30877
Fixes https://github.com/neovim/neovim/issues/30926

### CODE REVIEW

**Comment by SanchayanMaity** [comment]
Tested this and works now!

File: runtime/lua/vim/lsp/buf.lua [hunk 1]
```diff
@@ -96,6 +99,13 @@ local function get_locations(method, opts)
       if #all_items == 1 then
         local item = all_items[1]
         local b = item.bufnr or vim.fn.bufadd(item.filename)
+
+        -- Save position in jumplist
+        vim.cmd("normal! m'")
+        -- Push a new item into tagstack
+        local tagstack = { { tagname = tagname, from = from } }
+        vim.fn.settagstack(vim.fn.win_getid(win), { items = tagstack }, 't')
+
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/buf.lua:108]: Note all this logic might be a candidate for vim.jump (https://github.com/neovim/neovim/issues/26782)
