### PR TITLE
fix(api): nvim_parse_cmd parses :map incorrectly

### LINKED ISSUE #21918: nvim_parse_cmd doas not have the ability to parse `:map` corectly
### Describe the bug

There is no way to parse `:map` with the second argument having multiple spaces with `nvim_parse_cmd`.
More specifically:
`nvim_parse_cmd` treats all spaces as delimiters thus making it impossible to parse commands like `:map` which may have arguments with multiple spaces.

### Steps to reproduce

```vim
nvim --clean
:lua cmd=vim.api.nvim_parse_cmd("map a b  c",{})  --two spaces between b  and c
:lua vim.cmd(cmd)
```

### Expected behavior

Creating a map `a` `b  c`

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

nvim_parse_cmd

### Terminal name/version

alacritty 0.11.0

### $TERM environment variable

alacritty

### Installation

system package manager

### PR DESCRIPTION
**Pull request by glepnir**
Problem: nvim_parse_cmd() incorrectly splits mapping commands like into three arguments instead of preserving whitespace in the RHS.

Solution: Add special handling for mapping commands to parse them as exactly two arguments - the LHS and the RHS with all whitespace preserved.

Fix #21918

### CODE REVIEW

File: src/nvim/ex_docmd.c [hunk 1]
```diff
@@ -8180,3 +8180,16 @@ uint32_t get_cmd_argt(cmdidx_T cmdidx)
...
+bool is_mapping_command(cmdidx_T cmdidx)
+{
+  if (IS_USER_CMDIDX(cmdidx)) {
+    return false;
+  }
+
+  const char *name = cmdnames[cmdidx].cmd_name;
+  size_t len = strlen(name);
+
+  return (len >= 3 && strcmp(name + len - 3, "map") == 0);
```
Comment (justinmk) [inline src/nvim/ex_docmd.c]: This seems fragile. We should probably just explicitly check for the command indexes.

File: src/nvim/api/command.c [hunk 2]
```diff
@@ -121,9 +122,36 @@ Dict(cmd) nvim_parse_cmd(String str, Dict(empty) *opts, Arena *arena, Error *err
   Array args = ARRAY_DICT_INIT;
   size_t length = strlen(ea.arg);
 
-  // For nargs = 1 or '?', pass the entire argument list as a single argument,
-  // otherwise split arguments by whitespace.
-  if (ea.argt & EX_NOSPC) {
+  // Check if this is a mapping command that needs special handling
+  bool is_mapping_cmd = is_mapping_command(ea.cmdidx);
+  if (is_mapping_cmd && *ea.arg != NUL) {
```
Comment (justinmk) [inline src/nvim/api/command.c]: What special handling? Show an example of the string form converted to pseudocode structure:

    // "..." => { args=..., ... }

File: src/nvim/api/command.c [hunk 3]
```diff
@@ -121,9 +122,36 @@ Dict(cmd) nvim_parse_cmd(String str, Dict(empty) *opts, Arena *arena, Error *err
   Array args = ARRAY_DICT_INIT;
   size_t length = strlen(ea.arg);
 
-  // For nargs = 1 or '?', pass the entire argument list as a single argument,
-  // otherwise split arguments by whitespace.
-  if (ea.argt & EX_NOSPC) {
+  // Check if this is a mapping command that needs special handling
```
Comment (justinmk) [inline src/nvim/api/command.c:150]: Factor this out into a function. I suspect similar logic exists elsewhere in the codebase, right?

File: test/functional/api/vim_spec.lua [hunk 4]
```diff
@@ -4636,6 +4636,45 @@ describe('API', function()
         },
       }, api.nvim_parse_cmd('argadd a.txt | argadd b.txt', {}))
     end)
+    it('works on rhs with space', function()
```
Comment (justinmk) [inline test/functional/api/vim_spec.lua]: isn't it specifically about :map commands ? 
```suggestion
    it('parses :map commands with space in RHS', function()
```

File: src/nvim/ex_docmd.c (hunk 1 above)
Comment (glepnir) [reply src/nvim/ex_docmd.c]: yes... I'm mainly trying to prevent it from turning out like this... because I feel like you wouldn't like it.

```C
static bool is_mapping_command(cmdidx_T cmdidx)
{
  switch (cmdidx) {
    // Map commands
    case CMD_map:
    case CMD_nmap:
    case CMD_vmap:
    case CMD_xmap:
    case CMD_smap:
    case CMD_omap:
    case CMD_imap:
    case CMD_lmap:
    case CMD_cmap:
    case CMD_tmap:
    // Noremap commands  
    case CMD_noremap:
    case CMD_nnoremap:
    case CMD_vnoremap:
    case CMD_xnoremap:
    case CMD_snoremap:
    case CMD_onoremap:
    case CMD_inoremap:
    case CMD_lnoremap:
    case CMD_cnoremap:
    case CMD_tnoremap:
    // Unmap commands
    case CMD_unmap:
    case CMD_nunmap:
    case CMD_vunmap:
    case CMD_xunmap:
    case CMD_sunmap:
    case CMD_ounmap:
    case CMD_iunmap:
    case CMD_lunmap:
    case CMD_cunmap:
    case CMD_tunmap:
    // Mapclear commands
    case CMD_mapclear:
    case CMD_nmapclear:
    case CMD_vmapclear:
    case CMD_xmapclear:
    case CMD_smapclear:
    case CMD_omapclear:
    case CMD_imapclear:
    case CMD_lmapclear:
    case CMD_cmapclear:
    case CMD_tmapclear:
      return true;
    default:
      return false;
  }
}
```

File: src/nvim/api/command.c [hunk 5]
```diff
@@ -121,9 +147,63 @@ Dict(cmd) nvim_parse_cmd(String str, Dict(empty) *opts, Arena *arena, Error *err
...
+  // like mapping commands need special argument parsing to preserve whitespace in RHS:
+  // "map a b  c" => { args=["a", "b  c"], ... }
+  bool is_mapping_cmd = false;
+  switch (ea.cmdidx) {
+  case CMD_map:
```
Comment (justinmk) [inline src/nvim/api/command.c]: this also should be in a function. presumably this handling is needed elsewhere, otherwise how does vim handle :map commands?

Comment (glepnir) [reply src/nvim/api/command.c]: do_exmap use `get_map_mode` which check first letter to detect map mode like 
```
  if (modec == 'i') {
    mode = MODE_INSERT;                                                  // :imap
```

Comment (zeertzjq) [reply src/nvim/api/command.c]: Then you can define a function in ex_docmd.c that checks the value of `cmdnames[ea.cmdidx].cmd_func`.

Comment (glepnir) [reply src/nvim/api/command.c]: make sense

File: src/nvim/ex_docmd.c [hunk 6]
```diff
@@ -8180,3 +8180,18 @@ uint32_t get_cmd_argt(cmdidx_T cmdidx)
 {
   return cmdnames[(int)cmdidx].cmd_argt;
 }
+
+/// Check if a command is a mapping/abbreviation command by examining its handler function
```
Comment (justinmk) [inline src/nvim/ex_docmd.c]:
```suggestion
/// Check if a command is a :map/:abbrev command.
```

File: src/nvim/ex_docmd.c [hunk 7]
```diff
@@ -8180,3 +8180,18 @@ uint32_t get_cmd_argt(cmdidx_T cmdidx)
...
+bool is_mapping_command(cmdidx_T cmdidx)
```
Comment (justinmk) [inline src/nvim/ex_docmd.c]: afaict "mapping" is not used in any C function names. either "map" or "keymap".

```suggestion
bool is_map_cmd(cmdidx_T cmdidx)
```

File: test/functional/api/vim_spec.lua [hunk 8]
```diff
@@ -4636,6 +4636,45 @@ describe('API', function()
         },
       }, api.nvim_parse_cmd('argadd a.txt | argadd b.txt', {}))
     end)
+    it('parses :map commands with space in RHS', function()
+      eq({
+        addr = 'none',
+        args = { 'a', 'b  c' },
```
Comment (justinmk) [inline test/functional/api/vim_spec.lua:4642]: This is a tricky case, nice bug fix 👍

File: src/nvim/api/command.c [hunk 9]
```diff
@@ -40,6 +41,31 @@
 # include "api/command.c.generated.h"
 #endif
 
+/// Parse arguments for mapping commands, preserving whitespace in RHS
```
Comment (justinmk) [inline src/nvim/api/command.c]:
```suggestion
/// Parse arguments for :map/:abbrev commands, preserving whitespace in RHS.
```

File: src/nvim/api/command.c [hunk 10]
```diff
@@ -121,9 +147,16 @@ Dict(cmd) nvim_parse_cmd(String str, Dict(empty) *opts, Arena *arena, Error *err
...
   size_t length = strlen(ea.arg);
 
-  // For nargs = 1 or '?', pass the entire argument list as a single argument,
-  // otherwise split arguments by whitespace.
-  if (ea.argt & EX_NOSPC) {
+  // Check if this is a mapping command that needs special handling
+  // like mapping commands need special argument parsing to preserve whitespace in RHS:
+  // "map a b  c" => { args=["a", "b  c"], ... }
+  bool is_mapping_cmd = is_mapping_command(ea.cmdidx);
+  if (is_mapping_cmd && *ea.arg != NUL) {
```
Comment (justinmk) [inline src/nvim/api/command.c]:
```suggestion
  if (is_mapping_command(ea.cmdidx) && *ea.arg != NUL) {
```

File: src/nvim/api/command.c [hunk 11]
```diff
@@ -40,6 +41,31 @@
 # include "api/command.c.generated.h"
 #endif
 
+/// Parse arguments for mapping commands, preserving whitespace in RHS
+/// @param arg_str  The argument string to parse
+/// @param arena    Arena allocator
+/// @return Array with at most 2 elements: [lhs, rhs]
+static Array parse_mapping_args(const char *arg_str, Arena *arena)
```
Comment (justinmk) [inline src/nvim/api/command.c]:
```suggestion
static Array parse_map_cmd(const char *arg_str, Arena *arena)
```

File: src/nvim/api/command.c [hunk 12]
```diff
@@ -40,6 +41,31 @@
...
+{
+  Array args = arena_array(arena, 2);  // Allocate for at most 2 arguments
```
Comment (justinmk) [inline src/nvim/api/command.c]: does MAXSIZE_TEMP_ARRAY work here ? 

```suggestion
  MAXSIZE_TEMP_ARRAY(args, 2);
```

Comment (zeertzjq) [reply src/nvim/api/command.c]: Didn't you see the `return` statement?

Comment (justinmk) [reply src/nvim/api/command.c]: in any case, the comment isn't needed since that is the express purpose of that arg

Comment (justinmk) [reply src/nvim/api/command.c]:
```suggestion
  Array args = arena_array(arena, 2);
```

File: src/nvim/api/command.c [hunk 13]
```diff
@@ -40,6 +41,31 @@
...
+
+  char *lhs_start = (char *)arg_str;
+  char *lhs_end = skiptowhite(lhs_start);
+  size_t lhs_len = (size_t)(lhs_end - lhs_start);
+
+  // Add the LHS (first argument)
+  ADD_C(args, STRING_OBJ(cstrn_as_string(lhs_start, lhs_len)));
```
Comment (zeertzjq) [inline src/nvim/api/command.c:57]: `cbuf_as_string` may be better?
