### PR TITLE
[RFC] Fix some bugs with clipboard=unnamed

### LINKED ISSUE #2105: incorrect kill+paste behavior with clipboard=unnamed
Killing a line and then pasting with `p` pastes text I killed two times ago instead of the most recent instance. Pasting with `]p`, however, works correctly and also causes a subsequent `p` to past the correct text.  With `clipboard=`, I am not seeing this behavior.

(version a4c3ac2799281b56c1c38d0fdc584e22ac1b3d2f).

### PR DESCRIPTION
**Pull request by bfredl**
`getreg(v:register)` and `dd""p` are both broken when `clipboard=unnamed`. This might fix #2105 and #1690 (or parts thereof). 

Should have some tests, too.

### CODE REVIEW

**Comment by bfredl** [comment]
updated with tests.

**Comment by aktau** [comment]
It seems like this would reinstate some lost compatibility with Vim indeed, running `:echo v:register` in Vim does indeed print `*` for me, while it prints `"` in current nvim master. So it seems to me that this change is better than the hacky quickfix I proposed in #1690.

**Comment by aktau** [comment]
So LGTM after tests pass (and comments are sorted out).

File: src/nvim/ops.c [hunk 1]
```diff
@@ -5310,6 +5312,12 @@ static void free_register(struct yankreg *reg)
   y_current = curr;
 }
 
+int get_unnamed_register_name(void) {
+    int name = 0;
+    adjust_clipboard_name(&name, true, false);
```
Comment (Pyrohh) [inline src/nvim/ops.c]: This function's style is off... we should probably use clang-format more as it's so much easier :smile:

Comment (Pyrohh) [inline src/nvim/ops.c]: (by the way, https://github.com/google/vim-codefmt is quite nice)

Comment (bfredl) [inline src/nvim/ops.c]: :+1: Right now I have a leader mapping to set all shifts to 2, but I should add an autocommand or something for all files under `~/dev/neovim`

**Comment by bfredl** [comment]
Updated to suggestions, thanks @aktau @pyrohh @splinterofchaos !

**Comment by splinterofchaos** [comment]
LGTM :+1:

**Comment by bfredl** [comment]
Also did some cleanup of `get_yank_register`.  `i = regname` didn't make sense as `i` is never `regname`

**Comment by bfredl** [comment]
Hmm, no way one could restart an individual quickbuild item like one can with travis?

**Comment by bfredl** [comment]
Updated to suggestions. Surely there is more cleanups to be done here, but I will merge after tests and do the bigger refactors in a separate PR.

**Comment by bfredl** [comment]
Note to self: github interprets "might fix #xxx" as "does fix #xxx"
