### PR TITLE
[RDY] ex_getln.c: fix <S-Tab> not triggering Pmenu when wildoptions=pum

### LINKED ISSUE #10042: Shift+Tab cannot trigger Pmenu when set wildoptions=pum
- `nvim --version`: v0.4.0-789-g8c842b39b
- Vim (version: ) behaves differently? `wildoptions=pum` cannot be set in vim
- Operating system/version: Arch Linux
- Terminal name/version: Tilix 1.9.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set wildoptions=pum
:set <S-Tab>
```

### Actual behaviour

Pmenu didn't trigger.

### Expected behaviour

Pmenu should be triggered the same as when I press Tab, except that the candidate is selected from the end.

### PR DESCRIPTION
**Pull request by glacambre**
Some of the logic that was present for `<Tab>` was missing from `<S-Tab>`.

Closes https://github.com/neovim/neovim/issues/10042.

### CODE REVIEW

**Comment by glacambre** [comment]
I don't know how codecov works, is there anything I can do to avoid worsening the coverage percentage?

**Comment by bfredl** [comment]
@glacambre It seems to be broken currently, I've got 0% on a recent PR. Don't worry about it.

File: src/nvim/ex_getln.c [hunk 1]
```diff
@@ -1022,9 +1022,12 @@ static int command_line_execute(VimState *state, int key)
 
   // <S-Tab> goes to last match, in a clumsy way
   if (s->c == K_S_TAB && KeyTyped) {
-    if (nextwild(&s->xpc, WILD_EXPAND_KEEP, 0, s->firstc != '@') == OK
-        && nextwild(&s->xpc, WILD_PREV, 0, s->firstc != '@') == OK
-        && nextwild(&s->xpc, WILD_PREV, 0, s->firstc != '@') == OK) {
+    if (nextwild(&s->xpc, WILD_EXPAND_KEEP, 0, s->firstc != '@') == OK) {
+      showmatches(&s->xpc, p_wmnu
+                  && ((wim_flags[s->wim_index] & WIM_LIST) == 0));
+      redrawcmd();
```
Comment (bfredl) [inline src/nvim/ex_getln.c]: Is this extra redraw needed? what happens otherwise?

Comment (glacambre) [reply src/nvim/ex_getln.c]: `<S-Tab>` seems to work without it but I decided to add it because the `<Tab>` path [also has one](https://github.com/neovim/neovim/blob/master/src/nvim/ex_getln.c#L990). It doesn't seem necessary either though (tests don't fail if I remove it). Should I amend my commit to remove both `redrawcmd()` calls?

**Comment by blueyed** [comment]
@glacambre 
From https://codecov.io/gh/neovim/neovim/compare/5cc45bb419892909f2ede9ec3f6fb12f9e0da82d...5b73715a467435b24c6217dc09eb5e6aa125d81b/diff (the "codecov/patch" status) it looks like only the true-case/branch is covered (with tests).

The total coverage ("codecov/project") is flaky unfortunately.

File: src/nvim/ex_getln.c (hunk 1 above)
Comment (bfredl) [reply src/nvim/ex_getln.c]: `wildoptions=pum` does not require any extra redraw compared to standand wildmenu, and this code seemingy worked before. The wildchar branch seems to be doing a lot of other stuff, I don't know if `redrawcmd()` can be elided there. But we shouldn't cargo-cult copy extra redraws unless we know they are needed in the new place also.

**Comment by bfredl** [comment]
LGTM, rebased.
