### PR TITLE
fix(lsp): check active_clients table length first

### LINKED ISSUE #21523: `vim.lsp.get_active_clients({bufnr = 0})` can error
### Neovim version (nvim -v)

v0.8.1

### Vim (not Nvim) behaves the same?

—

### Operating system/version

Linux

### Terminal name/version

Windows Terminal

### $TERM environment variable

tmux-256color

### Installation

Nix

### How to reproduce the issue

I've got an error when testing with mini.nvim. My goal is to wait for lsp to start with something like:

```lua
child.lua_get([[vim.wait(5000, function() return #vim.lsp.get_active_clients({name = "marksman", bufnr=0}) >= 1 end, 50)]])
```

In my case if I didn't guard it with pcall it's pretty much guaranteed to get an error:

```
Error executing lua: ...eovim-unwrapped-0.8.1/share/nvim/runtime/lua/vim/lsp.lua:1796: attempt to index local 'client' (a nil value)
  stack traceback:
        ...eovim-unwrapped-0.8.1/share/nvim/runtime/lua/vim/lsp.lua:1796: in function 'get_active_clients'
```

The code that triggers an error:

https://github.com/neovim/neovim/blob/b840eb694579f64697ed6248ce2884da3ecf7783/runtime/lua/vim/lsp.lua#L1790-L1800

What I think is happening here, is when I filter active clients with `{bufnr = 0}` there is a time frame when `all_buffer_active_clients` is populated with client ids, but `active_clients` not yet. `mini.test` run code via RPC in child neovim. Maybe it's able to execute something in between? Unfortunately I didn't manage to reproduce it with minimal `init.lua`, maybe it is possible with some async calls like vim.schedule.

I think a nil check should be enough, something like:

```lua
    if
      client
      and (filter.id == nil or client.id == filter.id)
      and (filter.name == nil or client.name == filter.name)
    then
```

### Expected behavior

`get_active_clients` shouldn't error, but return empty clients list.

### Actual behavior

```
Error executing lua: ...eovim-unwrapped-0.8.1/share/nvim/runtime/lua/vim/lsp.lua:1796: attempt to index local 'client' (a nil value)
  stack traceback:
        ...eovim-unwrapped-0.8.1/share/nvim/runtime/lua/vim/lsp.lua:1796: in function 'get_active_clients'
```

### PR DESCRIPTION
**Pull request by glepnir**
Fix #21523

### CODE REVIEW

File: runtime/lua/vim/lsp.lua [hunk 1]
```diff
@@ -1842,10 +1842,16 @@ function lsp.get_active_clients(filter)
 
   local t = filter.bufnr and (all_buffer_active_clients[resolve_bufnr(filter.bufnr)] or {})
     or active_clients
+
+  if #active_clients == 0 then
```
Comment (stasjok) [inline runtime/lua/vim/lsp.lua:1846]: `active_clients` are indexed by client id, right? So it can have holes. If client with id 1 is stopped, than this condition returns too early.

Comment (glepnir) [reply runtime/lua/vim/lsp.lua:1846]: active_clients is table the value is client id

File: runtime/lua/vim/lsp.lua [hunk 2]
```diff
@@ -1842,10 +1842,16 @@ function lsp.get_active_clients(filter)
...
+    return clients
+  end
+
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp.lua:1849]:
```suggestion
```

**Review by mfussenegger — COMMENTED** [review]
Could you also add a test-case?

**Comment by glepnir** [comment]
try to add a test case ,failed.  `lsp.start` run in before each block when into the `describe` block it already run complete .
