### PR TITLE
fix(float): don't unload 'hidden' float buffer with :close!

### LINKED ISSUE #39055: ui2: Invalid 'end_col': out of range on tab close
### Problem

I encountered another such bug when hiding a message window that survived closing the tab.

```
vim.schedule callback: ...rc-dev/share/nvim/runtime/lua/vim/_core/ui2/messages.lua:69: Invalid 'end_col': out of range
stack traceback:
	[C]: in function 'nvim_buf_set_text'
	...rc-dev/share/nvim/runtime/lua/vim/_core/ui2/messages.lua:69: in function ''
	vim/_core/editor.lua: in function <vim/_core/editor.lua:0>
```

### Steps to reproduce

```lua
require('vim._core.ui2').enable({msg = {target = 'msg', timeout = 1000}})
vim.api.nvim_open_tabpage(0, true, {})
print(1)
vim.defer_fn(function ()
  vim.cmd.normal('ZQ')
end, 900)
```

### Expected behavior

No such error.

### Nvim version (nvim -v)

v0.13.0-dev-185+g87b5062f94

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Debian Sid

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

from repo

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  When closing floating windows to close a tabpage, if the current
          buffer will unload, buffers contained in those floating windows
          will too (unexpectedly).
Solution: Don't pass along "free_buf" argument; check 'bufhidden' for
          the buffer in the to be closed float.

Fix #39055

### CODE REVIEW

**Comment by luukvbaal** [comment]
Ref https://github.com/neovim/neovim/issues/39055#issuecomment-4252512647

File: test/functional/ui/float_spec.lua [hunk 1]
```diff
@@ -1072,6 +1072,15 @@ describe('float window', function()
       command('close')
       assert_alive()
     end)
+
+    it("does not unload 'hidden' buffer", function()
```
Comment (zeertzjq) [inline test/functional/ui/float_spec.lua]:
```suggestion
    it('does not unload bufhidden=hide buffer', function()
```

**Comment by zeertzjq** [comment]
I think the same change is needed in `win_close_othertab()` as well.

File: test/functional/ui/float_spec.lua (hunk 1 above)
Comment (luukvbaal) [reply test/functional/ui/float_spec.lua]: Sure (I used this wording after coming across it in `:h quit`: "The buffer is unloaded, also when it has 'hidden' set.")

**Review by zeertzjq — APPROVED** [review]

**Comment by przepompownia** [comment]
The repro from #39055 does not explode here too.
