### PR TITLE
fix(windows): set console code page to UTF-8 for shell commands

### LINKED ISSUE #33480: nvim - issue with unicode / colored terminal stdout on Windows (question marks / ansi codes)
### Problem

I'm using Windows 11 and start neovim using `nvim`, so I assume it's using default Windows Terminal which can be confirmed by running `:!ver`.
```
:!ver
[No write since last change]
Microsoft Windows [Version 10.0.22635.5170] 
```
But terminal output in nvim seems to be inconsistent with the default windows terminal. 
Below are 2 examples. Can confirm that running both examples in Terminal works fine - unicode colors and color codes are displayed by default.

### Unicode characters.

Running commands below result in either unicode text replaced with question marks or error running Python script.

```
nvim --clean
:!echo тест
:!py -c "print('тест')"
```

Output:
```
???? 

Traceback (most recent call last):                                                                                        
File "<string>", line 1, in <module>                                                                                    
File "C:\software\Python311\Lib\encodings\cp1252.py", line 19, in encode
 return codecs.charmap_encode(input,self.errors,encoding_table)[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3: character maps to <undefined>    
```
----

### Colored output.
```
nvim --clean
!echo test > xxx
!echo new > yyy
!git diff --color xxx yyy
```

Output:
Image

### Steps to reproduce

.

### Expected behavior

 1. Output unicode characters without errors.
 2. Output colors.

### Nvim version (nvim -v)

NVIM v0.11.0

### Vim (not Nvim) behaves the same?

Prints without issues. VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan 26 2025 21:15:39)

### Operating system/version

Windows 11

### Terminal name/version

cmd, Microsoft Windows [Version 10.0.22635.5170]

### $TERM environment variable

.

### Installation

Github Releases

### PR DESCRIPTION
**Pull request by kx0101**
## Problem

On Windows, `:!echo тест` shows `????` because the console code page defaults to a legacy ANSI encoding (e.g. CP1252) instead of `UTF-8`

Closes #33480

## Solution

Call `SetConsoleOutputCP(CP_UTF8)` and `SetConsoleCP(CP_UTF8)` in `do_os_system()` before spawning child processes, and restore the original values after. It covers both `:!` and `system()` since they both go through `do_os_system()`

### CODE REVIEW

File: src/nvim/os/shell.c [hunk 1]
```diff
@@ -867,6 +867,11 @@ static int do_os_system(char **argv, const char *input, size_t len, char **outpu
   // environment variable $NoDefaultCurrentDirectoryInExePath
   char *oldval = os_getenv("NoDefaultCurrentDirectoryInExePath");
   os_setenv("NoDefaultCurrentDirectoryInExePath", "1", true);
+
+  UINT old_output_cp = GetConsoleOutputCP();
+  UINT old_input_cp = GetConsoleCP();
+  SetConsoleOutputCP(CP_UTF8);
```
Comment (justinmk) [inline src/nvim/os/shell.c:874]:
```suggestion
  // Force console codepage to UTF-8 before spawning child process. #33480
  SetConsoleOutputCP(CP_UTF8);
```

**Comment by justinmk** [comment]
Is this something needed for `jobstart()` also? https://github.com/neovim/neovim/blob/9705a1c13b04c20a6b8eb1f57d543f4d08240876/src/nvim/eval/funcs.c#L3479

(Not to mention `vim.system()` @lewis6991 )

File: test/functional/vimscript/system_spec.lua [hunk 2]
```diff
@@ -166,6 +166,11 @@ describe('system()', function()
         test_shell_unquoting()
       end)
 
+      it('cmd.exe with UTF-8', function()
```
Comment (justinmk) [inline test/functional/vimscript/system_spec.lua]:
```suggestion
      it('with shell=cmd.exe, spawns child process with UTF-8 codepage', function()
```

File: test/functional/vimscript/system_spec.lua [hunk 3]
```diff
@@ -166,6 +166,11 @@ describe('system()', function()
         test_shell_unquoting()
       end)
 
+      it('with shell=cmd.exe, spawns child process with UTF-8 codepage', function()
```
Comment (justinmk) [inline test/functional/vimscript/system_spec.lua]: actually, why does the test mention cmd.exe? that's used to test the functionality, but the functionality applies to all shells, right?
```suggestion
      it('spawns child process with UTF-8 codepage', function()
```

File: test/functional/vimscript/system_spec.lua [hunk 4]
```diff
@@ -166,6 +166,11 @@ describe('system()', function()
...
+        command('set shell=cmd.exe')
+        eq('тест\n', eval([[system('echo тест')]]))
```
Comment (justinmk) [inline test/functional/vimscript/system_spec.lua:171]: does this test definitely fail before the change you made? i thought we had tests like this already.

Comment (kx0101) [reply test/functional/vimscript/system_spec.lua:171]: yeah it did fail before:

```bash
FAILED   system() executes shell function with shell=cmd.exe, 
          spawns child process with UTF-8 codepage

 Expected: 'тест\n'
 Passed in: '????\n'
```

File: test/functional/vimscript/system_spec.lua (hunk 3 above)
Comment (kx0101) [reply test/functional/vimscript/system_spec.lua]: haha oh yeah lol

I was tunnel visioning on `cmd.exe` since that's what I used to reproduce it

Fixed!

**Comment by kx0101** [comment]
btw, I'm not really sure I can say for certain if we need to change anything on `jobstart()` 😞
