### PR TITLE
fix(ui): exclude hidden windows from tabline window count

### LINKED ISSUE #36759: vim._extui: Number of windows in tabpage is incorrect
### Problem

The default tabline shows the number of windows in a tabpage.

When `vim._extui` is enabled, a new tabpage is reported as having two windows while only one is present. Presumably the cmd window is included in the number? The issue is not present when `vim._extui` is disabled.

Duplicate of #34295?

Image

### Steps to reproduce

```
nvim --clean
:lua require('vim._extui').enable {}
:tabnew
```

### Expected behavior

The number of windows is one (and hence not shown).

Image

### Nvim version (nvim -v)

0.12.0-dev-1719+g03d6cf7aae

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Fedora Linux 43

### Terminal name/version

kitty 0.43.1

### $TERM environment variable

xterm-kitty

### Installation

AppImage

### PR DESCRIPTION
**Pull request by benarcher2691**
## Summary
- Fixes tabline showing incorrect window count when `vim._extui` is enabled
- The extui pager window has `focusable=true` but `hide=true` (hidden by default)
- Previously only non-focusable windows were excluded from the count
- Now hidden windows are also excluded from the tabline window count

## Changes
- `src/nvim/statusline.c`: Added `|| wp->w_config.hide` check to exclude hidden windows
- `test/functional/ui/cmdline2_spec.lua`: Updated test expectations to match correct behavior (tests previously expected the incorrect window count "2")

Fixes #36759

## Test plan
- [x] Manual test: `:lua require('vim._extui').enable {}` + `:tabnew` shows no window count
- [x] Manual test: `:split` in second tab correctly shows "2" window count
- [x] All 8607 functional tests pass

### CODE REVIEW

File: src/nvim/statusline.c [hunk 1]
```diff
@@ -710,7 +710,7 @@ void draw_tabline(void)
       bool modified = false;
 
       for (wincount = 0; wp != NULL; wp = wp->w_next, wincount++) {
-        if (!wp->w_config.focusable) {
+        if (!wp->w_config.focusable || (wp->w_floating && wp->w_config.hide)) {
```
Comment (luukvbaal) [inline src/nvim/statusline.c]:
```suggestion
        if (!wp->w_config.focusable || wp->w_config.hide) {
```

Please also change the `focusable` condition in `ex_docmd.c:ex_tabs()`, ref #27984.

**Review by luukvbaal — APPROVED** [review]

**Comment by benarcher2691** [comment]
Re-running CI to verify test results

**Comment by benarcher2691** [comment]
Having issues in the CI pipeline. Will continue faultfinding given time.

**Comment by luukvbaal** [comment]
Judging from the CI history the only fails have been unrelated flaky tests. One of the maintainers will usually re-run those for you.

This looks good to go to me, thanks!

**Comment by justinmk** [comment]
Side-note: similar to what we did for 'statusline', `draw_tabline` should always use `win_redr_custom` instead of this bespoke C code. I.e. the default 'tabline' should be a Lua function, not C code. 

But meanwhile, this PR is helpful, thanks!
