### PR TITLE
fix(float): reset pwd after win_set_buf in nvim_open_win

### LINKED ISSUE #15280: nvim_open_win with non-current buffer leads to wrong working directory with 'autochdir'
### Neovim Version

NVIM v0.5.0-dev+1115-gc1fbc2ddf

### Operating system/version:

WSL Ubuntu

### Terminal name/version:

mintty 3.4.5

### TERM environment variable

xterm-256color

### Installation

Built from source

### Steps to reproduce

vimrc:
```vim
set autochdir

autocmd CmdlineLeave * call Leave()

let s:buf = nvim_create_buf(0, 1)
call nvim_buf_set_name(s:buf, 'Foo')

function! Leave()
  let l:win = nvim_open_win(s:buf, 0, {
        \ 'relative': 'editor',
        \ 'height': 1,
        \ 'width': 1,
        \ 'row': 0,
        \ 'col': 0,
        \ })
  call nvim_win_close(l:win, 1)
endfunction
```

1. Open nvim: `nvim -u vimrc`.
2. Edit a file in a different directory: `:e ~/foo/bar.txt`
3. Check pwd: `pwd`

### Vim

No, Vim doesn't have floating windows

### Expected behavior

`pwd` should show `~/foo`.

### Actual behavior

`pwd` shows `~`.

### PR DESCRIPTION
**Pull request by glepnir**
Problem:  win_set_buf will make buffer as current and do_autochdir when p_acd is true
Solution:  temporarily disable 'autochdir' when using win_set_buf()

Fix #15280

### CODE REVIEW

**Comment by zeertzjq** [comment]
Another approach is to temporarily disable 'autochdir' when using `win_set_buf()` on non-current window. A similar one can be see in `aucmd_prepbuf()`.

**Comment by glepnir** [comment]
oh thanks do change now.

File: test/functional/api/window_spec.lua [hunk 1]
```diff
@@ -551,6 +551,33 @@ describe('API/win', function()
     end)
   end)
 
+  describe('reset dir', function()
+    it('reset dir in nvim_open_win', function()
```
Comment (justinmk) [inline test/functional/api/window_spec.lua:555]: should this test live in the nvim_open_win describe() block? : https://github.com/neovim/neovim/blob/57adf8c6e01d9395eb52fe03571c535571efdc4b/test/functional/api/window_spec.lua#L1164
