### PR TITLE
fix(float): "Not enough room" error for 1-line float

### LINKED ISSUE #19464: Set winbar throws not enough space error even when there's space.
### Neovim version (nvim -v)

0.8.0 commit 1f1863ed5

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch linux

### Terminal name/version

Kitty terminal

### $TERM environment variable

screen-256color

### Installation

build from repo

### Reproduction steps
```lua
-- file: minimal_reproduce.lua
local win = vim.api.nvim_get_current_win()
vim.wo[win].winbar = '%f'

local grp = vim.api.nvim_create_augroup('asdf', {clear=true})
vim.api.nvim_create_autocmd('WinEnter', {
  group = grp,
  pattern = '*',
  desc = 'winbar crash?',
  callback = function ()
    vim.wo[win].winbar = '%f'
  end
})

local buf = vim.api.nvim_create_buf(false, true)
vim.api.nvim_open_win(buf, true, {
  relative = "win",
  win = win,
  border = 'single',
  col = 1,
  row = 1,
  height = 1,
  width = 40,
})
```

```sh
nvim --clean minimal_reproduce.lua
:lua require('minimal_reproduce')
```

### Things to note
- A winbar on current win is already set.
- We are trying to set winbar of previous win while entering the float of height 1 in auto command context.

### Expected behavior

No error should be thrown as the original window has enough space in it to draw winbar.

### Actual behavior

It throws following error
```
Error detected while processing WinEnter Autocommands for "*":
Error executing lua callback: ./minimal_reproduce.lua:10: Vim:E36: Not enough room
stack traceback:
        [C]: in function '__newindex'
        ./minimal_reproduce.lua:10: in function <./minimal_reproduce.lua:9>
        [C]: in function 'nvim_open_win'
        ./minimal_reproduce.lua:15: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

### Speculations 
It seems nvim is trying to draw winbar on the float even though winbar option in that window is empty . This can actually be seen if you open the float with height 2 the float buffer starts after an empty line.

@famiu  any clue ?

### PR DESCRIPTION
**Pull request by glepnir**
When float height is 1 and before window has winbar set . reset it to empty on float win avoid trigger no room.

Fix #19464

### CODE REVIEW

File: src/nvim/window.c [hunk 1]
```diff
@@ -749,6 +749,11 @@ win_T *win_new_float(win_T *wp, bool last, FloatConfig fconfig, Error *err)
   if (wp == NULL) {
     wp = win_alloc(last ? lastwin : lastwin_nofloating(), false);
     win_init(wp, curwin, 0);
+    // After win init new wp copied the value from curwin
+    // if new win only have one line shouldn't set wbr value
```
Comment (justinmk) [inline src/nvim/window.c:753]: Try to make comments say what something _means_, not _how_ it's done (except for cases where "how" is not obvious).

```suggestion
    // Don't inherit 'winbar' for 1-line window. #19464
```

File: test/functional/ui/float_spec.lua [hunk 2]
```diff
@@ -10327,6 +10327,35 @@ describe('float window', function()
         ]]}
       end
     end)
+
+    it("does not set winbar when float only have one line #19464", function()
```
Comment (justinmk) [inline test/functional/ui/float_spec.lua:10331]:
```suggestion
    it("1-line float does not inherit'winbar' #19464", function()
```

File: test/functional/ui/float_spec.lua [hunk 3]
```diff
@@ -10327,6 +10327,35 @@ describe('float window', function()
...
+          win = win,
+          border = 'single',
+          col = 1,
+          row = 1,
+          height = 1,
+          width = 40,
+        })
+        return {vim.wo[win].winbar, vim.wo[float_winid].winbar}
+      ]])
+      eq({"%f", ""}, res)
```
Comment (justinmk) [inline test/functional/ui/float_spec.lua:10357]: This is a clear test, thanks.

**Comment by justinmk** [comment]
[This comment](https://github.com/neovim/neovim/issues/19464#issuecomment-1195824973) explains things well. Copied below with my edits:

> Floats with height 1 are a lot more common then splits with height 1. ... The current behavior makes it impossible handle because `nvim_open_win` will throw the "Not enough room" error before anything can clear that inherited 'winbar'.

That comment goes further and suggests floating windows should never inherit 'winbar'. Does that make sense?

**Review by justinmk — APPROVED** [review]
LGTM, thanks. 

This is a special case for 1-line floats. But should it be for all floats instead (i.e. never inherit 'winbar')?

**Comment by justinmk** [comment]
I guess we still need this. Mind rebasing? :)

**Comment by glepnir** [comment]
rebased

File: test/functional/ui/float_spec.lua [hunk 4]
```diff
@@ -9845,6 +9845,35 @@ describe('float window', function()
         })
       end
     end)
+
+    it("1-line float does not inherit'winbar' #19464", function()
```
Comment (justinmk) [inline test/functional/ui/float_spec.lua:9849]:
```suggestion
    it("1-line float does not inherit 'winbar' #19464", function()
```
