### PR TITLE
fix(fileio): use first available directory in backupdir for backupcopy

### LINKED ISSUE #11349: Setting backupdir with dirs that don't exist and linked files
- `nvim --version`:
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: 8.0) behaves differently? Yes. It writes the backup to `/var/tmp` for a symlinked file
- Operating system/version: OS X 10.14.6
- Terminal name/version: iTerm2 3.3.6
- `$TERM`: `xterm-256color`

--------------------------------

Relates (I think) to #10101 (since it's about backups for symlinks).

Having `backupdir` set to a list of dirs where (in order of appearance) the first one does not exist, writing backups for symlink files will fail with `E506`.

When setting the `backupdir` option, the help indicates that it will attempt to create the backup file in the
> first directory in the list where this is possible

If one has this vimrc (only setting the backupdir):

```
set backupdir=~/.this-does-not-exist-tmp/,/var/tmp/
```

and the following files:

```
drwxr-xr-x  4 wspurgin  staff   128B Nov  7 10:17 .
drwxr-xr-x  7 wspurgin  staff   224B Nov  7 10:14 ..
lrwxr-xr-x  1 wspurgin  staff     7B Nov  7 10:14 bar.txt -> foo.txt
-rw-r--r--  1 wspurgin  staff    12B Nov  7 10:17 foo.txt
```

Attempt to edit `bar.txt` and then `:w` the file after it is open

### Actual behaviour

A `E506 Can't write backup file` error occurs when attempting to write `bar.txt`. Note, that if you swap the order of the directory list in `backupdir` (where a directory that exists appears first), there's no `E506`.

### Expected behaviour

I expect it to write the backup file to `/var/tmp` and not `E506`.

### LINKED ISSUE #18659: backupdir seems broken for symlink
### Neovim version (nvim -v)

NVIM v0.7.0

### Vim (not Nvim) behaves the same?

no, vim 8.0 1-1763

### Operating system/version

Rocky 8.5

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-256color

### Installation

system package manager

### How to reproduce the issue

```vim
set backup
set backupdir=.backup/,~/.vim-backup/backup//,/tmp//
```

```console
$ cd tmp/; mkdir -p a b; touch a/foo; ln -fs ../a/foo b/foo
$ nvim a/foo # do some edit, write, edit, write
$ ls ~/.vim-backup/backup/
%home%jerome%tmp%a%foo~
$ nvim b/foo # do some edit, write
```

### Expected behavior

Write succeeds

Not sure about the behavior, but I would like something like

```console
$ ls ~/.vim-backup/backup/
%home%jerome%tmp%a%foo~
%home%jerome%tmp%b%foo~
```

vim 8.0 behavior is not an example, as it does not support complete path backup name with %

### Actual behavior

When I write in neovim, I get an error:

```
:w
E506: Can't write to backup file (add ! to override)
```

### PR DESCRIPTION
**Pull request by wspurgin**
Continuation from #11417 and #18704

Fixes #11349
Fixes #18659

Confirmed that on `master` this is still broken. I also think the previous bisection in #11349 is still accurate because I'm also running v0.7.2 and the same behavior is observed there too.

### CODE REVIEW

File: src/nvim/fileio.c [hunk 1]
```diff
@@ -2771,6 +2771,9 @@ int buf_write(buf_T *buf, char *fname, char *sfname, linenr_T start, linenr_T en
               != 0) {
             SET_ERRMSG(_("E506: Can't write to backup file "
                          "(add ! to override)"));
+            XFREE_CLEAR(backup);
+            backup = NULL;
+            continue;
```
Comment (wspurgin) [inline src/nvim/fileio.c:2776]: We were missing the `continue` here on failure, so we were only every trying to create the backup file in the first directory (because we `break` out of the loop over all the backupdir options on line 2788 without checking `dirp` & `backup`). Before #9709, that break only happened _after_ we [checked that the creation of the backup worked](https://github.com/neovim/neovim/pull/9709/files#diff-1b7a1b0f3dbb1d3f4c6520ab4207aeedbbf7e8cfa129d7c710a64e06db20ae9dL2878-L2886)

**Comment by wspurgin** [comment]
Fixed lint errors.

**Comment by wspurgin** [comment]
Can I get a rerun on windows? It looks like a crash that wasn't related to these changes (the [previous run on windows](https://github.com/neovim/neovim/actions/runs/3265613418/jobs/5368700356) before the linting fixes passed)

**Comment by wspurgin** [comment]
@zeertzjq can I get a rerun on CI / windows? It looks like an unrelated failure (random nvim process crash). The [previous run](https://github.com/neovim/neovim/actions/runs/3265613418/jobs/5368700356) before the lint fixes passed on windows.

**Comment by wspurgin** [comment]
@justinmk Hi again! Looks like this fix works with Windows now too 🚀 - can I request your review (as you had the most context on the original PRs/issues)?

**Comment by wspurgin** [comment]
@zeertzjq I think Justin might be occupied on other more important work than this teeny PR. I see that reviews aren't required for PRs to be merged, but is there some process or other support I should go through/provide to help get this fix merged?

I just wanna make sure I don't drop this PR again for another 3 years 😅

**Comment by correabuscar** [comment]
Thank you for this PR, it fixed my use case where my `backupdir=.,~/.local/state/nvim/backup//` and I couldn't `touch newfile` in current dir due to directory permissions (but the file I was editing was writable for me), so I used to get that `Can't write backup file` error and had to use `w!`, but with this PR it just works because it seems to have used the second dir (even though it didn't exist at first, it created it automatically)

(I didn't run the included (lua)test though)
