### PR TITLE
getdigits: introduce `strict`, `def` parameters

### LINKED ISSUE #5555: Segfault when going to very large line number using :LineNumber
- `nvim --version`:
```
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/build/config -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/src -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/build/src/nvim/auto -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/build/include
Compiled by acid@macbook

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences
```
- Vim (version: 7.4) behaves differently?  
In regular vim everything works as expected
- Operating system/version:  
macOS, Version 10.12.1
- Terminal name/version:   
iTerm2, Build 3.0.11
- `$TERM`:   
xterm-256color

### Actual behaviour
```
:99999999999999999999999999Assertion failed: (errno != ERANGE), function getdigits, file /tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/src/nvim/charset.c, line 1743.
[1]    21949 abort      nvim /tmp/newfile
```
### Expected behaviour

Go to the last line of file
### Steps to reproduce using `nvim -u NORC`

Open any file with vim
```
nvim -u NORC /tmp/newfile
```
Try to go to very far line:
```
:999999999999999999999999999
```

### PR DESCRIPTION
**Pull request by justinmk**
Problem:
During a refactor long ago, we changed the `getdigits_*` familiy of functions to abort on overflow.  But this is often wrong, because many of these codepaths are handling user input.

Solution:
Decide at each call-site whether to use "strict" mode.

fix #5555

### CODE REVIEW

File: src/nvim/charset.c [hunk 1]
```diff
@@ -176,7 +176,7 @@ int buf_init_chartab(buf_T *buf, int global)
         ++p;
 
         if (ascii_isdigit(*p)) {
-          c2 = getdigits_int((char_u **)&p);
+          c2 = getdigits_int((char_u **)&p, true, 0);
```
Comment (justinmk) [inline src/nvim/charset.c]: In some cases I'm not really sure we want strict-mode, but did it anyway since it's more conservative.  Can revisit later, or wait for a crash report.
