### PR TITLE
fix(fs.lua): normalize slash truncation

### LINKED ISSUE #23733: vim.fs.find, vim.fs.dir doesn't support X:/ path on windows
### Problem

`vim.fs.find` and `vim.fs.dir` doesn't support `X:/` path on windows.
After some debug, found that `vim.fs.dir` can not list files under path `X:`, which is resulted from that `vim.fs.normalize` will convert `X:/` into `X:`. Is it a bug?
(Currently I have to change `X:/` into `X:/.` before passed into `vim.fs.find` to work around)

### Steps to reproduce

```lua
for name, type in vim.fs.dir("E:/") do
    print(name, type) -- Got wrong files
end
for name, type in vim.fs.dir("E:/.") do
    print(name, type) -- Got correct files
end
```

### Expected behavior

`vim.fs.find` and `vim.fs.dir` work correctly for `X:/` path on windows.

### Neovim version (nvim -v)

0.9

### Vim (not Nvim) behaves the same?

no

### Operating system/version

windows 11

### Terminal name/version

xterm

### $TERM environment variable

xterm

### Installation

nvim.exe

### PR DESCRIPTION
**Pull request by mike325**
Preserve last slash in windows' root drive directories

fixes #23733

### CODE REVIEW

**Comment by zeertzjq** [comment]
Please squash the PR into one commit.

File: runtime/lua/vim/fs.lua [hunk 1]
```diff
@@ -348,7 +348,11 @@ function M.normalize(path, opts)
     path = path:gsub('%$([%w_]+)', vim.uv.os_getenv)
   end
 
-  return (path:gsub('\\', '/'):gsub('/+', '/'):gsub('(.)/$', '%1'))
+  path = path:gsub('\\', '/'):gsub('/+', '/')
+  if iswin and path:match('^%w:/$') then
+    return path
+  end
+  return (path:gsub('(.)/$', '%1'))
```
Comment (justinmk) [inline runtime/lua/vim/fs.lua:355]: Why don't we always preserve the last slash instead of only on Windows? Based on previous discussion https://github.com/neovim/neovim/pull/23937#discussion_r1219692472 it doesn't sound like there was strong opposition. And that would avoid this special-case. @gpanders @lewis6991 @clason

Comment (justinmk) [reply runtime/lua/vim/fs.lua:355]: I guess this was part of 0.9 so back-compat is a concern. But normalize() is much more useful if its result is very predictable.
