### PR TITLE
[RFC] vim-patch:8.0.1809,8.1.{34,219}

### LINKED ISSUE #3257: Gvim incorrectly processes the backtick ("`") symbol in filenames on Windows under certain circumstances
1. Put three files with the names `0.txt`, ``1`2.txt`` and `3.txt` and contents "text" in the same folder, run `gvim.exe -u NONE -N *` from there.
2. Execute `:lvimgrep /text/ ##`. Gvim outputs the message:
```
"1`2.txt 3.txt" [New File]
Cannot open file "1`2.txt 3.txt"
(1 of 1): text
```
and only finds "text" in `0.txt`.

OS: Windows 7,
Gvim: gvim_8.1.0204_x86.zip

### PR DESCRIPTION
**Pull request by janlazo**
**vim-patch:8.0.1809: various typos**

Problem:    Various typos.
Solution:   Correct the mistakes, change "cursur" to "cursor". (closes vim/vim#2887)
vim/vim@b946482

**vim-patch:8.1.0034: cursor not restored with ":edit #"**

Problem:    Cursor not restored with ":edit #".
Solution:   Don't assume autocommands moved the cursor when it was moved to
            the first non-blank.
https://github.com/vim/vim/commit/adb8fbec4f4059d214fe6acf2485ffd35e803450

**vim-patch:8.1.0219: expanding ## fails to escape backtick**

Problem:    Expanding ## fails to escape backtick.
Solution:   Escape a backtick in a file name. (closes vim/vim#3257)
vim/vim@2c8c681

### CODE REVIEW

File: src/nvim/ex_cmds.c [hunk 1]
```diff
@@ -2546,11 +2546,17 @@ int do_ecmd(
...
 
-    // If autocommands change the cursor position or topline, we should keep
-    // it.  Also when it moves within a line.
+    // If autocommands change the cursor position or topline, we should
+    // keep it.  Also when it moves within a line. But not when it moves
+    // to the first non-blank.
     if (!equalpos(curwin->w_cursor, orig_pos)) {
-      newlnum = curwin->w_cursor.lnum;
-      newcol = curwin->w_cursor.col;
+      const char_u *text = get_cursor_line_ptr();
```
Comment (justinmk) [inline src/nvim/ex_cmds.c]: We should not have renamed nor moved `ml_get_curline` and `ml_get_cursor`. The new name and location in cursor.c makes little sense.
