### PR TITLE
fix(man.lua): provide better error message when failing to execute man

### LINKED ISSUE #33265: :Man shows noisy "ENOENT: no such file or directory" error on Windows
### Problem

Hi! Some few days ago I installed the version 0.11.0 of neovim and all worked as expected but when I tried to use the `<S-k>` command, the notifier displays a quite similar error but instead of `_watch.lua`, throws this:

Error executing Lua callback: ...gram Files/Neovim/share/nvim/runtime/lua/vim/_system.lua:248: ENOENT: no such file or directory
stack traceback:
	[C]: in function 'error'
	...gram Files/Neovim/share/nvim/runtime/lua/vim/_system.lua:248: in function 'spawn'
	...gram Files/Neovim/share/nvim/runtime/lua/vim/_system.lua:353: in function 'system'
	C:/Program Files/Neovim/share/nvim/runtime/lua/man.lua:11: in function 'system'
	C:/Program Files/Neovim/share/nvim/runtime/lua/man.lua:243: in function 'get_path'
	C:/Program Files/Neovim/share/nvim/runtime/lua/man.lua:333: in function '_find_path'
	C:/Program Files/Neovim/share/nvim/runtime/lua/man.lua:694: in function 'open_page'
	C:/Program Files/Neovim/share/nvim/runtime/plugin/man.lua:11: in function <C:/Program Files/Neovim/share/nvim/runtime/plugin/man.lua:6>

It's look like the `man` plugin have some issues on windows platform maybe.

> [!Warning]
> I tested it in Rust and the behaviour was the expected
> The issue starts with other langs like TS, Astro, and others.

### Steps to reproduce

nvim
open a file
do `<S-k>`

### Expected behavior

Show the correct docs.

### Nvim version (nvim -v)

v0.12.0-dev-60+g8a40213eb3

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Windows 10

### Terminal name/version

Windwos Terminal Preview 1.23.10732.0

### $TERM environment variable

None

### Installation

Neovim Release pages

### PR DESCRIPTION
**Pull request by 11soda11**
Problem:  `:Man` shows inacurrate error message when `man`
	  can't be executed

Solution: throw error with better message when `vim.system` fails

Fixes: #33265

Before:
before - Copy

After:
afternew - Copy

### CODE REVIEW

File: runtime/plugin/man.lua [hunk 1]
```diff
@@ -20,7 +26,7 @@ end, {
   addr = 'other',
   nargs = '*',
   complete = function(...)
-    return require('man').man_complete(...)
+    return vim.F.npcall(require('man').man_complete, ...)
```
Comment (justinmk) [inline runtime/plugin/man.lua:29]: avoid vim.F

File: runtime/lua/man.lua [hunk 2]
```diff
@@ -8,7 +8,20 @@ local M = {}
...
 --- @return string
 local function system(cmd, silent, env)
-  local r = vim.system(cmd, { env = env, timeout = 10000 }):wait()
+  local ok, proc_or_err = pcall(vim.system, cmd, { env = env, timeout = 10000 })
+
+  if not ok then
+    local errmsg = tostring(proc_or_err)
+    if string.find(errmsg, 'ENOENT') then
+      error(string.format("can't find '%s'", cmd[1]), 0)
+    elseif string.find(errmsg, 'EACCES') then
```
Comment (justinmk) [inline runtime/lua/man.lua:17]: This is a bit clumsy. Maybe `vim.system()` should return a structured object or something, but meanwhile we can use `vim.fn.executable()` to do the check, without string-scraping error messages. Here's some untested sample code:

```lua
if vim.fn.executable(cmd[1]) == 0 then
  error(string.format('not executable (or does not exist): "%s"', cmd[1]), 0)
end
local r = vim.system(cmd, { env = env, timeout = 10000 }):wait()
```

File: runtime/plugin/man.lua [hunk 3]
```diff
@@ -8,9 +8,15 @@ vim.api.nvim_create_user_command('Man', function(params)
...
   else
-    local err = man.open_page(params.count, params.smods, params.fargs)
-    if err then
+    local ok, err = pcall(man.open_page, params.count, params.smods, params.fargs)
+    if
+      ok
+      or string.find(assert(err), "can't find '%a+'")
+      or string.find(assert(err), "can't access '%a+'")
+    then
       vim.notify('man.lua: ' .. err, vim.log.levels.ERROR)
```
Comment (justinmk) [inline runtime/plugin/man.lua:17]: Let's just do this for all errors. That avoids yet another string.find() on error messages.

File: runtime/plugin/man.lua (hunk 1 above)
Comment (Sodastream11) [reply runtime/plugin/man.lua]: I will, but why?

File: runtime/plugin/man.lua (hunk 3 above)
Comment (Sodastream11) [reply runtime/plugin/man.lua]: Done

File: runtime/plugin/man.lua [hunk 4]
```diff
@@ -8,7 +8,7 @@ vim.api.nvim_create_user_command('Man', function(params)
   if params.bang then
     man.init_pager()
   else
-    local err = man.open_page(params.count, params.smods, params.fargs)
+    local _, err = pcall(man.open_page, params.count, params.smods, params.fargs)
```
Comment (justinmk) [inline runtime/plugin/man.lua:11]: open_page may return a string error: https://github.com/neovim/neovim/blob/ad337025314a424f19f96decb69b6a9d36121efe/runtime/lua/man.lua#L685

but you have now assigned that to `_`.

File: runtime/plugin/man.lua [hunk 5]
```diff
@@ -20,7 +20,12 @@ end, {
   addr = 'other',
   nargs = '*',
   complete = function(...)
-    return require('man').man_complete(...)
+    local ok, ret = pcall(require('man').man_complete, ...)
+    if ok then
+      return ret
+    else
+      return nil
```
Comment (justinmk) [inline runtime/plugin/man.lua:27]: how is this helpful ? `man_complete` should make this decision in its own logic, if it's actually needed.

File: runtime/lua/man.lua [hunk 6]
```diff
@@ -8,6 +8,12 @@ local M = {}
 --- @param env? table<string,string|number>
 --- @return string
 local function system(cmd, silent, env)
+  if vim.fn.executable(cmd[1]) == 0 then
+    error(string.format("not found: '%s'", cmd[1]), 0)
+  elseif vim.uv.fs_access(cmd[1], 'X') then
+    error(string.format("no permission to execute: '%s'", cmd[1]), 0)
```
Comment (justinmk) [inline runtime/lua/man.lua:14]: the example code i gave intentionally used double quotes in the message.
```suggestion
    error(string.format('not found: "%s"', cmd[1]), 0)
  elseif vim.uv.fs_access(cmd[1], 'X') then
    error(string.format('not executable: "%s"', cmd[1]), 0)
```

File: runtime/plugin/man.lua (hunk 4 above)
Comment (justinmk) [reply runtime/plugin/man.lua:11]: d'oh

**Review by justinmk — APPROVED** [review]

File: runtime/plugin/man.lua (hunk 5 above)
Comment (Sodastream11) [reply runtime/plugin/man.lua:27]: I added this since, if on a Release build, nvim crashes without any error if the completion function returns an error. But i will move this into `man_complete`, unless this behaviour is intentional?

Comment (justinmk) [reply runtime/plugin/man.lua:27]: > nvim completely crashes without any error message if the completion function throws an error.

sounds bad... mind creating an issue?

File: runtime/plugin/man.lua [hunk 7]
```diff
@@ -20,7 +20,7 @@ end, {
   addr = 'other',
   nargs = '*',
   complete = function(...)
-    return require('man').man_complete(...)
+    require('man').man_complete(...)
```
Comment (justinmk) [inline runtime/plugin/man.lua:23]: why return the return ?

File: runtime/plugin/man.lua (hunk 5 above)
Comment (Sodastream11) [reply runtime/plugin/man.lua]: sure

File: runtime/plugin/man.lua (hunk 7 above)
Comment (Sodastream11) [reply runtime/plugin/man.lua]: accidental

**Comment by Sodastream11** [comment]
I just tested this on linux and realised the access check doesnt work since we're not passing the full path of the command and we're not nullifying. Also on linux `vim.fn.executable` also checks if the file is executable, which makes the error message `not found` misleading. How can we change this now? Should i open another pr?
