### PR TITLE
fix(diff): use mmfile_t in linematch

### LINKED ISSUE #30505: linematch.c crashes when processing strings with embedded `NUL` characters
### Problem

I noticed that expanding snippet can crash nvim in some cases. 
```cpp
#1  0x000055857a750dc3 in fastforward_buf_to_lnum (s=s@entry=0x7f325ebfd378, lnum=2) at .../src/nvim/linematch.c:149
#2  0x000055857a750f0f in try_possible_paths (df_iters=df_iters@entry=0x7f325ebfd7c0, paths=paths@entry=0x7f325ebfd570, npaths=npaths@entry=1, path_idx=path_idx@entry=1, choice=choice@entry=0x7f325ebfd56c,
    diffcmppath=diffcmppath@entry=0x7f324c006df0, diff_len=0x7f325ebfd838, ndiffs=2, diff_blk=0x7f325ebfd840, iwhite=false) at .../src/nvim/linematch.c:184
#3  0x000055857a750e79 in try_possible_paths (df_iters=df_iters@entry=0x7f325ebfd7c0, paths=paths@entry=0x7f325ebfd570, npaths=npaths@entry=1, path_idx=path_idx@entry=0, choice=choice@entry=0x7f325ebfd56c,
    diffcmppath=diffcmppath@entry=0x7f324c006df0, diff_len=0x7f325ebfd838, ndiffs=2, diff_blk=0x7f325ebfd840, iwhite=false) at .../src/nvim/linematch.c:209
#4  0x000055857a75110e in populate_tensor (df_iters=df_iters@entry=0x7f325ebfd7c0, ch_dim=ch_dim@entry=2, diffcmppath=diffcmppath@entry=0x7f324c006df0, diff_len=diff_len@entry=0x7f325ebfd838, ndiffs=ndiffs@entry=2,
    diff_blk=diff_blk@entry=0x7f325ebfd840, iwhite=false) at .../src/nvim/linematch.c:263
#5  0x000055857a75107c in populate_tensor (df_iters=df_iters@entry=0x7f325ebfd7c0, ch_dim=ch_dim@entry=1, diffcmppath=diffcmppath@entry=0x7f324c006df0, diff_len=diff_len@entry=0x7f325ebfd838, ndiffs=ndiffs@entry=2,
    diff_blk=diff_blk@entry=0x7f325ebfd840, iwhite=false) at .../src/nvim/linematch.c:270
#6  0x000055857a75107c in populate_tensor (df_iters=df_iters@entry=0x7f325ebfd7c0, ch_dim=ch_dim@entry=0, diffcmppath=diffcmppath@entry=0x7f324c006df0, diff_len=diff_len@entry=0x7f325ebfd838, ndiffs=ndiffs@entry=2,
    diff_blk=diff_blk@entry=0x7f325ebfd840, iwhite=false) at .../src/nvim/linematch.c:270
#7  0x000055857a7512df in linematch_nbuffers (diff_blk=0x7f325ebfd840, diff_len=0x7f325ebfd838, ndiffs=2, decisions=0x7f325ebfd830, iwhite=false) at .../src/nvim/linematch.c:356
#8  0x000055857a779e7c in get_linematch_results (lstate=0x7f325f780380, ma=<optimized out>, mb=<optimized out>, start_a=50, count_a=<optimized out>, start_b=51, count_b=15, iwhite=false)
    at .../src/nvim/lua/xdiff.c:77
#9  0x000055857a779f91 in hunk_locations_cb (start_a=<optimized out>, count_a=<optimized out>, start_b=<optimized out>, count_b=<optimized out>, cb_data=<optimized out>) at .../src/nvim/lua/xdiff.c:133
#10 0x000055857a8d1182 in xdl_call_hunk_func (xe=<optimized out>, xscr=<optimized out>, ecb=0x7f325ebfda80, xecfg=0x7f325ebfdaf0) at .../src/xdiff/xdiffi.c:993
#11 0x000055857a8d3dad in xdl_diff (mf1=<optimized out>, mf2=<optimized out>, xpp=0x7f325ebfdaa0, xecfg=0x7f325ebfdaf0, ecb=0x7f325ebfda80) at .../src/xdiff/xdiffi.c:1090
#12 0x000055857a77a44e in nlua_xdl_diff (lstate=0x7f325f780380) at .../src/nvim/lua/xdiff.c:341
#13 0x000055857a94cfe6 in lj_BC_FUNCC ()
#14 0x000055857a93889d in lua_pcall (L=L@entry=0x7f325f780380, nargs=nargs@entry=5, nresults=nresults@entry=-1, errfunc=errfunc@entry=0) at lj_api.c:1122
#15 0x000055857a76f1c0 in nlua_luv_thread_common_cfpcall (lstate=0x7f325f780380, nargs=5, nresult=-1, flags=1, is_callback=is_callback@entry=false) at .../src/nvim/lua/executor.c:264
#16 0x000055857a76f345 in nlua_luv_thread_cfpcall (lstate=<optimized out>, nargs=<optimized out>, nresult=<optimized out>, flags=<optimized out>) at .../src/nvim/lua/executor.c:245
#17 0x000055857a8e3b7c in luv_work_cb ()
#18 0x000055857a94cfe6 in lj_BC_FUNCC ()
#19 0x000055857a93889d in lua_pcall (L=L@entry=0x7f325f780380, nargs=nargs@entry=1, nresults=nresults@entry=0, errfunc=errfunc@entry=0) at lj_api.c:1122
#20 0x000055857a76f1c0 in nlua_luv_thread_common_cfpcall (lstate=lstate@entry=0x7f325f780380, nargs=nargs@entry=1, nresult=nresult@entry=0, flags=flags@entry=1, is_callback=is_callback@entry=false)
    at .../src/nvim/lua/executor.c:264
#21 0x000055857a76f345 in nlua_luv_thread_cfpcall (lstate=lstate@entry=0x7f325f780380, nargs=nargs@entry=1, nresult=nresult@entry=0, flags=flags@entry=1) at .../src/nvim/lua/executor.c:245
#22 0x000055857a76f37f in nlua_luv_thread_cfcpcall (lstate=0x7f325f780380, func=<optimized out>, ud=0x558595e71500, flags=1) at .../src/nvim/lua/executor.c:253
#23 0x000055857a8e39e4 in luv_work_cb_wrapper ()
#24 0x000055857a997735 in worker ()
#25 0x00007f3260ade732 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#26 0x00007f3260b592b8 in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

At the moment the following `init.lua` is as minimal as I can create. I have not analyzed what happens on the gitsigns side. 

cc: @lewis6991 @jwhite510 

### Steps to reproduce

- `git clone https://github.com/przepompownia/repro.nvim xdiff-linematch-error && cd xdiff-linematch-error`

- replace `init.lua` with:
```lua
local thisInitFile = debug.getinfo(1).source:match('@?(.*)')
local cwd = vim.fs.dirname(thisInitFile)
local appname = vim.env.NVIM_APPNAME or 'nvim'

vim.env.XDG_CONFIG_HOME = cwd
vim.env.XDG_DATA_HOME = vim.fs.joinpath(cwd, '.xdg', 'data')
vim.env.XDG_STATE_HOME = vim.fs.joinpath(cwd, '.xdg', 'state')
vim.env.XDG_CACHE_HOME = vim.fs.joinpath(cwd, '.xdg', 'cache')
vim.fn.mkdir(vim.fs.joinpath(vim.env.XDG_CACHE_HOME, appname), 'p')
local stdPathConfig = vim.fn.stdpath('config')

vim.opt.runtimepath:prepend(stdPathConfig)
vim.opt.packpath:prepend(stdPathConfig)

local function gitClone(url, installPath, branch)
  if vim.fn.isdirectory(installPath) ~= 0 then
    return
  end

  local command = {'git', 'clone', '--', url, installPath}
  if branch then
    table.insert(command, 3, '--branch')
    table.insert(command, 4, branch)
  end

  vim.notify(('Cloning %s dependency into %s...'):format(url, installPath), vim.log.levels.INFO, {})
  local sysObj = vim.system(command, {}):wait()
  if sysObj.code ~= 0 then
    error(sysObj.stderr)
  end
  vim.notify(sysObj.stdout)
  vim.notify(sysObj.stderr, vim.log.levels.WARN)
end

local pluginsPath = vim.fs.joinpath(cwd, 'nvim/pack/plugins/opt')
vim.fn.mkdir(pluginsPath, 'p')
pluginsPath = vim.uv.fs_realpath(pluginsPath)
--- @type table<string, {url:string, branch: string?}>
local plugins = {
  ['gitsigns'] = {url = 'https://github.com/lewis6991/gitsigns.nvim'},
}
for name, repo in pairs(plugins) do
  local installPath = vim.fs.joinpath(pluginsPath, name)
  gitClone(repo.url, installPath, repo.branch)
  vim.cmd.packadd({args = {name}, bang = true})
end

vim.o.swapfile = false -- convenient after crash here

require('gitsigns').setup({})

vim.api.nvim_create_autocmd('FileType', {
  pattern = {'lua'},
  group = vim.api.nvim_create_augroup('luals', {}),
  callback = function ()
    vim.lsp.start({
      name = 'luals',
      filetype = 'lua',
      cmd = {'lua-language-server'},
      root_dir = vim.uv.cwd(),
      settings = {
        Lua = {
          runtime = {
            path = {
              '?.lua',
              '?/init.lua',
            },
            version = 'LuaJIT',
            pathStrict = true,
          },
          workspace = {
            ignoreDir = {'lua'},
            checkThirdParty = false,
            library = {
              vim.fs.joinpath(vim.env.VIMRUNTIME, 'lua'),
              vim.fs.joinpath('${3rd}/luv/library', 'lua'),
            },
          },
          diagnostics = {
            globals = {'vim'},
          },
        },
      },
    })
  end,
})

vim.api.nvim_create_autocmd('LspAttach', {
  group = vim.api.nvim_create_augroup('arctgx.completion', {clear = true}),
  callback = function (args)
    vim.lsp.completion.enable(true, args.data.client_id, args.buf, {autotrigger = true})

    vim.keymap.set({'i'}, '<C-Space>', function ()
      vim.lsp.completion.trigger()
    end, {buffer = args.buf})
  end
})

-- vim.opt.diffopt:append('vertical') -- not necessary
vim.opt.diffopt:append('linematch:60')
```
- `nvim --clean -u init.lua init.lua`
- after loading luals type `Oif<C-Space>` then try to expand the snippet `if  then^@  ^@end`. For me nvim crashes before expansion. 

### Expected behavior

No crash

### Nvim version (nvim -v)

NVIM v0.11.0-dev-828+g052875b9d Build type: RelWithDebInfo LuaJIT 2.1.1724512491

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Debian Sid

### Terminal name/version

alacritty 0.14.0-dev (8dfd2e56), tmux 3.4

### $TERM environment variable

tmux-256color

### Installation

from repo

### PR DESCRIPTION
**Pull request by lewis6991**
Problem:

Linematch used to use strchr to navigate a string, however strchr does
not supoprt embedded NULs.

Solution:

Use `mmfile_t` instead of `char*` in linematch and introduce `strnchr()`.

Fixes: #30505

### CODE REVIEW

**Comment by lewis6991** [comment]
@jwhite510

File: src/nvim/linematch.c [hunk 1]
```diff
@@ -29,44 +31,48 @@ struct diffcmppath_S {
...
-    while (d + i < slen) {
-      char e = strsorig[k][i + d];
+    const mmfile_t *s = k == 0 ? s1 : s2;
+    int d = 0;
+    int i = 0;
+    strsproc[k] = (mmfile_t){
+      .ptr = xmalloc((size_t)(s->size + 1) * sizeof(char)),
+      .size = s->size
+    };
+    while (d + i < s->size) {
```
Comment (zeertzjq) [inline src/nvim/linematch.c:62]: I don't think using `s->size` here is correct. This is processing the whole file when `matching_chars()` only compares one line.

File: src/nvim/strings.c [hunk 2]
```diff
@@ -496,6 +496,20 @@ char *vim_strchr(const char *const string, const int c)
   }
 }
 
+// Sized version of strchr that can handle embedded NULs.
+// Adjusts n to the new size.
+char *strnchr(register const char *p, size_t *n, int c)
```
Comment (bfredl) [inline src/nvim/strings.c:501]: no need for `register` annotation on variables.

File: src/nvim/linematch.c [hunk 3]
```diff
@@ -143,15 +147,17 @@ static int count_n_matched_chars(const char **sp, const size_t n, bool iwhite)
...
-    *s = strchr(*s, '\n');
-    if (!*s) {
-      return;
+    s.ptr = strnchr(s.ptr, (size_t *)&s.size, '\n');
+    if (!s.ptr) {
+      break;
     }
-    (*s)++;
+    s.ptr++;
+    s.size++;
```
Comment (bfredl) [inline src/nvim/linematch.c:158]: wouldn't `s.ptr++` be matched by `s.size--` ? or am I missing something?

Comment (lewis6991) [reply src/nvim/linematch.c:158]: Yes. Good spot. Obviously the test suite isn't exercising this.

File: src/nvim/strings.c (hunk 2 above)
Comment (lewis6991) [reply src/nvim/strings.c:501]: How come? I copied this from GCC's `strchr` implementation, so if they think it's necessary, wouldn't it also be necessary here too?

Comment (bfredl) [reply src/nvim/strings.c:501]: yes, and when we copy in code into our codebase we adjust it to follow _our_ conventions (which is based on what compilers _we_ support, etc). We don't use `register` annotations in general (because we trust the optimizer with that), and I don't think this function needs to be marked that it came originally from a codebase which uses them.

Comment (lewis6991) [reply src/nvim/strings.c:501]: I compiled this with `gcc` and `clang`. `gcc` with `register` produces the least amount of code.

<details>
<summary>`gcc` (no `register`) - 28 instructions</summary>
```
d10083ff     	sub	sp, sp, #0x20
f9000fe0     	str	x0, [sp, #0x18]
f9000be1     	str	x1, [sp, #0x10]
b9000fe2     	str	w2, [sp, #0xc]
14000011     	b	0x54 <ltmp0+0x54>
f9400fe0     	ldr	x0, [sp, #0x18]
39c00000     	ldrsb	w0, [x0]
2a0003e1     	mov	w1, w0
b9400fe0     	ldr	w0, [sp, #0xc]
6b01001f     	cmp	w0, w1
54000061     	b.ne	0x34 <ltmp0+0x34>
f9400fe0     	ldr	x0, [sp, #0x18]
1400000e     	b	0x68 <ltmp0+0x68>
f9400fe0     	ldr	x0, [sp, #0x18]
91000400     	add	x0, x0, #0x1
f9000fe0     	str	x0, [sp, #0x18]
f9400be0     	ldr	x0, [sp, #0x10]
b9400000     	ldr	w0, [x0]
51000401     	sub	w1, w0, #0x1
f9400be0     	ldr	x0, [sp, #0x10]
b9000001     	str	w1, [x0]
f9400be0     	ldr	x0, [sp, #0x10]
b9400000     	ldr	w0, [x0]
7100001f     	cmp	w0, #0x0
54fffdac     	b.gt	0x14 <ltmp0+0x14>
d2800000     	mov	x0, #0x0                ; =0
910083ff     	add	sp, sp, #0x20
d65f03c0     	ret
```
</details>

<details>
<summary>`gcc` (with `register`) - 23 instructions</summary>
```
d10043ff     	sub	sp, sp, #0x10
f90007e1     	str	x1, [sp, #0x8]
b90007e2     	str	w2, [sp, #0x4]
1400000d     	b	0x40 <ltmp0+0x40>
39c00001     	ldrsb	w1, [x0]
2a0103e2     	mov	w2, w1
b94007e1     	ldr	w1, [sp, #0x4]
6b02003f     	cmp	w1, w2
54000041     	b.ne	0x28 <ltmp0+0x28>
1400000c     	b	0x54 <ltmp0+0x54>
91000400     	add	x0, x0, #0x1
f94007e1     	ldr	x1, [sp, #0x8]
b9400021     	ldr	w1, [x1]
51000422     	sub	w2, w1, #0x1
f94007e1     	ldr	x1, [sp, #0x8]
b9000022     	str	w2, [x1]
f94007e1     	ldr	x1, [sp, #0x8]
b9400021     	ldr	w1, [x1]
7100003f     	cmp	w1, #0x0
54fffe2c     	b.gt	0x10 <ltmp0+0x10>
d2800000     	mov	x0, #0x0                ; =0
910043ff     	add	sp, sp, #0x10
d65f03c0     	ret
```
</details>

<details>
<summary>`clang` (with and without `register`) - 34 instructions</summary>
```
d10083ff     	sub	sp, sp, #0x20
f9000be0     	str	x0, [sp, #0x10]
f90007e1     	str	x1, [sp, #0x8]
b90007e2     	str	w2, [sp, #0x4]
14000001     	b	0x14 <ltmp0+0x14>
f94007e8     	ldr	x8, [sp, #0x8]
b9400108     	ldr	w8, [x8]
71000108     	subs	w8, w8, #0x0
1a9fc7e8     	cset	w8, le
37000288     	tbnz	w8, #0x0, 0x74 <ltmp0+0x74>
14000001     	b	0x2c <ltmp0+0x2c>
f9400be8     	ldr	x8, [sp, #0x10]
39c00108     	ldrsb	w8, [x8]
b94007e9     	ldr	w9, [sp, #0x4]
6b090108     	subs	w8, w8, w9
1a9f07e8     	cset	w8, ne
370000a8     	tbnz	w8, #0x0, 0x54 <ltmp0+0x54>
14000001     	b	0x48 <ltmp0+0x48>
f9400be8     	ldr	x8, [sp, #0x10]
f9000fe8     	str	x8, [sp, #0x18]
1400000b     	b	0x7c <ltmp0+0x7c>
f9400be8     	ldr	x8, [sp, #0x10]
91000508     	add	x8, x8, #0x1
f9000be8     	str	x8, [sp, #0x10]
f94007e9     	ldr	x9, [sp, #0x8]
b9400128     	ldr	w8, [x9]
71000508     	subs	w8, w8, #0x1
b9000128     	str	w8, [x9]
17ffffe9     	b	0x14 <ltmp0+0x14>
f9000fff     	str	xzr, [sp, #0x18]
14000001     	b	0x7c <ltmp0+0x7c>
f9400fe0     	ldr	x0, [sp, #0x18]
910083ff     	add	sp, sp, #0x20
d65f03c0     	ret
```
</details>

**Comment by lewis6991** [comment]
https://github.com/neovim/neovim/pull/30591

File: src/nvim/linematch.c [hunk 4]
```diff
@@ -143,15 +147,17 @@ static int count_n_matched_chars(const char **sp, const size_t n, bool iwhite)
...
 }
 
-void fastforward_buf_to_lnum(const char **s, linenr_T lnum)
+mmfile_t fastforward_buf_to_lnum(mmfile_t s, linenr_T lnum)
 {
   for (int i = 0; i < lnum - 1; i++) {
-    *s = strchr(*s, '\n');
-    if (!*s) {
-      return;
+    s.ptr = strnchr(s.ptr, (size_t *)&s.size, '\n');
```
Comment (justinmk) [inline src/nvim/linematch.c:153]: coverity warning looks valid, worth an assert?

```
CID 510275:  Memory - illegal accesses  (INCOMPATIBLE_CAST)
/src/nvim/linematch.c: 153 in fastforward_buf_to_lnum()
147       return matched_chars;
148     }
149     
150     mmfile_t fastforward_buf_to_lnum(mmfile_t s, linenr_T lnum)
151     {
152       for (int i = 0; i < lnum - 1; i++) {
>>>     CID 510275:  Memory - illegal accesses  (INCOMPATIBLE_CAST)
>>>     Pointer "&s.size" points to an object whose effective type is "int" (32 bits, signed) but is dereferenced as a wider "unsigned long" (64 bits, unsigned). This may lead to memory corruption.
153         s.ptr = strnchr(s.ptr, (size_t *)&s.size, '\n');
154         if (!s.ptr) {
155           break;
156         }
157         s.ptr++;
158         s.size--;
```

File: src/nvim/strings.c [hunk 5]
```diff
@@ -496,6 +496,20 @@ char *vim_strchr(const char *const string, const int c)
...
+{
+  while (*n > 0) {
+    if (*p == c) {
+      return (char *)p;
+    }
+    p++;
+    (*n)--;
+  }
+  return NULL;
+}
```
Comment (zeertzjq) [inline src/nvim/strings.c:511]: Is this really needed? This seems mostly the same of `memchr()`, except that it takes a pointer to `n`.

Comment (lewis6991) [reply src/nvim/strings.c:511]: If you can replace with `memchr`, then go for it. I gave it a generic name, because it is a generic function.
