### PR TITLE
fix(build.zig): remove runtime dependency on Windows SDK

### LINKED ISSUE #36889: `zig build nvim` fails on Windows (nlua0 exit code 53)
### Problem

When running `zig build nvim` on Windows, the build fails due to the generated `nlua0.exe` exiting with a non-zero exit code.

### Steps to reproduce

```sh
git clone https://github.com/neovim/neovim
cd neovim
zig build nvim
```

### Expected behavior

Build should succeed.

### Nvim version (nvim -v)

0.12.0-dev commit bc0635a9fc9c15a2423d4eb35f627d127d00fa46

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows 11 25H2 (OS Build 26200.7171)

### Terminal name/version

Windows Terminal

### $TERM environment variable

N/A

### Installation

Build from repo

### PR DESCRIPTION
**Pull request by eamonburns**
## Problem

When building on Windows using the Zig build system, there is a runtime dependency on Windows SDK (specifically `ucrtbased.dll`) introduced by libuv.

## Solution

Since the dependency is only required when libuv is built in Debug mode, never build libuv in Debug mode on Windows.

This follows optimization mode tweaks done to other dependencies in build.zig already.

Closes #36889

### CODE REVIEW

File: build.zig [hunk 1]
```diff
@@ -102,9 +102,12 @@ pub fn build(b: *std.Build) !void {
...
     }
     if (!system_integration_options.uv) {
-        if (b.lazyDependency("libuv", .{ .target = target, .optimize = optimize })) |dep| {
+        // NOTE: libuv on Windows depends on Windows SDK when compiled with .Debug mode
+        // https://github.com/neovim/neovim/issues/36889
+        const optimize_uv = if (optimize == .Debug and target.result.os.tag == .windows) .ReleaseSafe else optimize;
+        if (b.lazyDependency("libuv", .{ .target = target, .optimize = optimize_uv })) |dep| {
             libuv = dep.artifact("uv");
-            libluv = try build_lua.build_libluv(b, target, optimize, lua, libuv.?, use_luajit);
+            libluv = try build_lua.build_libluv(b, target, optimize_uv, lua, libuv.?, use_luajit);
```
Comment (ntdiary) [inline build.zig]: Seems this is compiling `libluv`. I'm not sure whether `optimize` should match what `libuv` uses.

**Review by ntdiary — COMMENTED** [review]
```shell
-Doptimize=[enum]  Prioritize performance, safety, or binary size
                     Supported Values:
                       Debug
                       ReleaseSafe
                       ReleaseFast
                       ReleaseSmall

```
Honestly, this is my first time working with Zig. While I can identify the root cause, I'm not sure which of `small/fast/safe` is the most appropriate—or if it even matters. :D

**Comment by eamonburns** [comment]
> Honestly, this is my first time working with Zig. While I can identify the root cause, I'm not sure which of `small/fast/safe` is the most appropriate—or if it even matters. :D

I opted for ReleaseSafe because it has safety checks. The alternative only applies if it was originally compiled in Debug mode, so the user likely doesn't care about speed or binary size.

File: build.zig (hunk 1 above)
Comment (eamonburns) [reply build.zig]: Good point. I'll look into it

**Comment by clason** [comment]
AFAIR from discussions in Ghostty, there's a huge performance difference between `ReleaseSafe` and `ReleaseFast`, where you absolutely want to use the latter for end-user builds. (`ReleaseSafe` is basically Zig's "we have ASAN at home".)

**Comment by eamonburns** [comment]
> AFAIR from discussions in Ghostty, there's a huge performance difference between `ReleaseSafe` and `ReleaseFast`, where you absolutely want to use the latter for end-user builds. (`ReleaseSafe` is basically Zig's "we have ASAN at home".)

End-user builds would have an explicit `-Doptimize=Release...`, in which case libuv would be built using that optimize mode.

| -Doptimize      | libuv optimize |
| --------------- | -------------- |
| omitted (Debug) | ReleaseSafe    |
| Debug           | ReleaseSafe    |
| ReleaseSafe     | ReleaseSafe    |
| ReleaseSmall    | ReleaseSmall   |
| ReleaseFast     | ReleaseFast    |

File: build.zig (hunk 1 above)
Comment (eamonburns) [reply build.zig]: I reverted it in https://github.com/eamonburns/neovim/commit/b34cd44ae663d3b191b44a6a1f0171250b3dd821

**Review by bfredl — APPROVED** [review]
