### PR TITLE
fix(lsp): rewrite incremental sync

### LINKED ISSUE #14542: lsp: incremental sync breaks with certain multibyte character operations
- `nvim --version`:
```
NVIM v0.5.0-dev+1318-g61aefaf29
Build type: RelWithDebInfo
LuaJIT 2.0.5
```
- language server name/version: rust-analyzer 9a431c26f 2021-05-12 dev
- Operating system/version: Linux coorie 5.10.34-1-MANJARO #1 SMP Sun May 2 11:29:56 UTC 2021 x86_64 GNU/Linux

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>

```vim
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 1
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: tmux-256color

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: pyls: configuration checked.
  - INFO: texlab: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: clangd: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - INFO: tsserver: configuration checked.
```

</details>

<details>
<summary>lsp.log</summary>

before blank file
after attached lsp.log
[lsp.log](https://github.com/neovim/neovim/files/6466465/lsp.log)

</details>

### Steps to reproduce using nvim -u minimal_init.lua

<details>
<summary>minimal_init.vim</summary>

```
set runtimepath+=~/.config/nvim/dein/repos/github.com/neovim/nvim-lspconfig
lua require'lspconfig'.rust_analyzer.setup {}

lua vim.lsp.set_log_level('debug')

let g:signature = ''

function! s:fetch_cursor_signature_and_store() abort
  " Request without blocking and use the response next time.
  lua <<EOF
  do
    local cur = vim.lsp.util.make_position_params()
    vim.lsp.buf_request(0, "textDocument/signatureHelp", cur,
      function(err, _method, result, _client_id, _bufnr, _config)
        if type(result) ~= "table" or type(result.signatures) ~= "table" then
          return
        end
        local signature = result.signatures[1]
        if not signature then return end
        -- Discard signature.parameters
        vim.g['signature'] = signature.label
      end)
  end
EOF
endfunction

function! s:on_event() abort
  call s:fetch_cursor_signature_and_store()
  " use g:signature
endfunction

autocmd CursorMovedI * call s:on_event()

lua print(vim.lsp.get_log_path())
```

lspconfig HEAD is
```
*   commit 0a921bf2be74d293c8a8d6dd70122c1d01151a30 (HEAD -> master, origin/master, origin/HEAD): e808cea 7a3e0d1
| | Author: Michael Lingelbach <m.j.lbach@gmail.com>
| | Date:   Fri May 7 15:19:53 2021 -0700
```

</details>

1. Open file
```sh
cargo new hello
cd hello
sed 's/"Hello, world!"/"Hello, world! に対応"/' -i src/main.rs
nvim -u ../minimal_init.vim src/main.rs
```
2. Move cursor on 'に' \u306b
3. Type xcl to remove two chars and insert mode
4. IME On
5. Type "対応" \u5bfe\u5fdc. The line has string "Hello, World! 対応応".
6. I got the client-sided serialization error and was blocked with "Press ENTER or type command to continue"
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:394: Vim:E474: String "<af><be><e5>" contains byte that does not start any UTF-8 character
続けるにはENTERを押すかコマンドを入力してください
```
7. Enter
8. IME Off
9. Esc
10. :q

### Actual behaviour
When sending a signature request, the client tries to notify `textDocument/didChange` just before it. Then the error occurs asynchronously in json_encode and blocks the user interface.

### Expected behaviour
The file you are in the middle of editing is not necessarily valid utf-8. LSP can only send utf-8, but it is not desirable to block the user interface when an error occurs asynchronously and there is no way to catch it.

### PR DESCRIPTION
**Pull request by mjlbach**
closes https://github.com/neovim/neovim/issues/14542, https://github.com/neovim/neovim/issues/15128

on_bytes is blocked, this is a rewrite using on_lines with some performance optimizations, unicode fixes, and support for multiple different line endings (mac, dos, and unix file format).

### CODE REVIEW

**Comment by mjlbach** [comment]
Noticed debugging https://github.com/neovim/neovim/issues/15128 that this still fails:

Pre:
```
module Scratch where

data Foo = FooConstructor String String

--bar :: [Foo]
--bar =
--  (FooConstructor <$> ["hello, neovim!"] <* ["⊕" :: String])
--    <*> ["goodbye, neovim!"]

baz :: String
baz = "this should stay as is"

```
Post:
```
module Scratch where

data Foo = FooConstructor String String

bar :: [Foo]
bar =
  (FooConstructor <$> ["hello, neovim!"] <* ["⊕" :: String])
    <*> ["goodbye, neovim!"]

baz :: String
baz = "this should stay as is"
```


```
[DEBUG][2021-11-05 21:38:38] .../vim/lsp/rpc.lua:339	"rpc.send"	{
  jsonrpc = "2.0",
  method = "textDocument/didChange",
  params = {
    contentChanges = { {
        range = {
          end = {
            character = 2,
            line = 7
          },
          start = {
            character = 0,
            line = 4
          }
        },
        rangeLength = 112,
        text = 'bar :: [Foo]\nbar =\n  (FooConstructor <$> ["hello, neovim!"] <* ["⊕" :: String])\n'
      } },
    textDocument = {
      uri = "file:///home/michael/Repositories/neovim_development/neovim-worktree/neovim/test_hs/main.hs",
      version = 4
    }
  }
}
````

**Comment by dmitmel** [comment]
Found a bug:

1. type `аб`
2. delete `а`
3. undo

(In other words, `iаб<Esc>hxu`)

Crashes with the following error message:

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:399: Vim:E474: String "<d0>" contains byte that does not start any UTF-8 character
```

**Comment by mjlbach** [comment]
I can't reproduce. What server did you use? with a utf-16 server (at least):

```
[DEBUG][2021-11-06 08:34:45] .../vim/lsp/rpc.lua:339	"rpc.send"	{
  jsonrpc = "2.0",
  method = "textDocument/didChange",
  params = {
    contentChanges = { {
        range = {
          end = {
            character = 0,
            line = 0
          },
          start = {
            character = 0,
            line = 0
          }
        },
        rangeLength = 0,
        text = "a"
      } },
    textDocument = {
      uri = "file:///home/michael/Repositories/neovim_development/neovim-worktree/lsp-on-lines/test.lua",
      version = 4
    }
  }
}
[DEBUG][2021-11-06 08:34:46] .../vim/lsp/rpc.lua:339	"rpc.send"	{
  jsonrpc = "2.0",
  method = "textDocument/didChange",
  params = {
    contentChanges = { {
        range = {
          end = {
            character = 1,
            line = 0
          },
          start = {
            character = 1,
            line = 0
          }
        },
        rangeLength = 0,
        text = "6"
      } },
    textDocument = {
      uri = "file:///home/michael/Repositories/neovim_development/neovim-worktree/lsp-on-lines/test.lua",
      version = 5
    }
  }
}

[DEBUG][2021-11-06 08:34:48] .../vim/lsp/rpc.lua:339	"rpc.send"	{
  jsonrpc = "2.0",
  method = "textDocument/didChange",
  params = {
    contentChanges = { {
        range = {
          end = {
            character = 1,
            line = 0
          },
          start = {
            character = 0,
            line = 0
          }
        },
        rangeLength = 1,
        text = ""
      } },
    textDocument = {
      uri = "file:///home/michael/Repositories/neovim_development/neovim-worktree/lsp-on-lines/test.lua",
      version = 6
    }
  }
}
[DEBUG][2021-11-06 08:34:48] .../vim/lsp/rpc.lua:339	"rpc.send"	{
  jsonrpc = "2.0",
  method = "textDocument/didChange",
  params = {
    contentChanges = { {
        range = {
          end = {
            character = 0,
            line = 0
          },
          start = {
            character = 0,
            line = 0
          }
        },
        rangeLength = 0,
        text = "a"
      } },
    textDocument = {
      uri = "file:///home/michael/Repositories/neovim_development/neovim-worktree/lsp-on-lines/test.lua",
      version = 7
    }
  }
}
```

**Comment by dmitmel** [comment]
> What server did you use?

sumneko_lua

>. Did you make distclean before make installing (I added a new file to the runtime, sync.lua)?

I rebuilt everything from scratch. The `'vim.lsp.sync` module is available.

---

To eliminate the possibility of Language Servers affecting reproduction of the bug, I can give you the parameters and returned values of the underlying `compute_diff` calls. This doesn't look right to me:

```lua
print(vim.inspect(
  require('vim.lsp.sync').compute_diff(
    { "б" },  -- prev_lines
    { "аб" }, -- curr_lines
    0,        -- firstline
    1,        -- lastline
    1,        -- new_lastline
    "utf-16", -- offset_encoding
    "\n"      -- line_ending
  )
))
--[[
{
  range = {
    end = {
      character = 0,
      line = 0
    },
    start = {
      character = 0,
      line = 0
    }
  },
  rangeLength = 0,
  text = "а<d0>"
}
--]]
```

---

Also, I have found that deleting multiple lines at a time from a buffer can cause crashes with the error message `Error executing lua callback: /usr/share/nvim/runtime/lua/vim/lsp/sync.lua:51: index out of range`. For example, with sumneko_lua attached to a buffer with the following contents:

```
a
a

a
```

`gg4dd` causes the crash. But so does `ggj3dd`. The underlying compute_diff invocations are:

```lua
compute_diff({ "a", "a", "", "a" }, { "" }, 0, 4, 0, "utf-16", "\n")       -- full file deletion
compute_diff({ { "a", "a", "", "a" }, { "a" }, 1, 4, 1, "utf-16", "\n" })  -- last three lines
```

**Comment by dmitmel** [comment]
Granted, I may have messed up somewhere while backporting this PR, #16124 and #16129 to 0.5.1, so please run the snippets with compute_diff I posted above and tell me if you get the same results or not.

**Comment by mjlbach** [comment]
The issue was in rangeLength, wasn't accounting for empty lines. Try again?

**Comment by dmitmel** [comment]
The cases with line deletion no longer cause a crash.

**Comment by dmitmel** [comment]
The test case with `аб` now works fine

File: runtime/lua/vim/lsp/sync.lua [hunk 1]
```diff
@@ -0,0 +1,363 @@
...
+      if offset > 0 then
+        char = M.byte_to_utf(line, byte, offset_encoding) + 1
+        byte = byte + offset
+      else
+        char = M.byte_to_utf(line, byte, offset_encoding)
+        byte = byte + offset
+      end
+    else
+      assert(false, '`align` must be start or end.')
+    end
```
Comment (dmitmel) [inline runtime/lua/vim/lsp/sync.lua:99]:
```lua
error('`align` must be start or end.')
```

File: runtime/lua/vim/lsp/sync.lua [hunk 2]
```diff
@@ -0,0 +1,363 @@
...
+
+  -- Iterate across previous and current line containing first change
+  -- to find the first different byte.
+  -- Note: *about -> a*about will register the second a as the first
+  -- difference, regardless of edit since we do not receive the first
+  -- column of the edit from on_lines.
+  local start_byte_idx = 1
+  for idx = 1, #prev_line + 1 do
+    start_byte_idx = idx
+    if string.byte(prev_line, idx) ~= string.byte(curr_line, idx) then
```
Comment (dmitmel) [inline runtime/lua/vim/lsp/sync.lua:136]: By the way, I am not sure about it, but using `string.byte` from a global namespace may not undergo JIT compilation (because the global has to be queried every time), even though `string.byte` itself is definitely compiled. I would localize it (i.e. put `local string_byte = string.byte` outside of the loop or at the start of the file) just to be safe.

File: runtime/lua/vim/lsp/sync.lua [hunk 3]
```diff
@@ -0,0 +1,363 @@
...
+    if start_line_idx == prev_line_idx then
+      -- Search until beginning of difference
+      max_length = math.min(prev_line_length - start_range.byte_idx, curr_line_length - start_range.byte_idx) + 1
+    else
+      max_length = math.min(prev_line_length, curr_line_length) + 1
+    end
+    for idx = 0, max_length do
+      byte_offset = idx
+      if
+        string.byte(prev_line, prev_line_length - byte_offset) ~= string.byte(curr_line, curr_line_length - byte_offset)
```
Comment (dmitmel) [inline runtime/lua/vim/lsp/sync.lua:203]: Same comment as in `compute_start_range`.

**Comment by mjlbach** [comment]
I think this is mostly correct now, but I'm marking this as a draft as I've decided to add 20 or so tests, I added the first one as a proof of concept getting the testing infra setup but this will be great as the way I've set it up, it can basically be copy/pasted when we switch to on_bytes.

**Comment by mjlbach** [comment]
I'm inclined to just hardcode in the workaround for #16259. Anyways again would be great for concerned parties to daily drive this for awhile and report any issues :)

File: runtime/lua/vim/lsp/sync.lua [hunk 4]
```diff
@@ -0,0 +1,384 @@
...
+local math = math
+
+---@private
+-- Given a line, byte idx, and offset_encoding convert to the
+-- utf-8, utf-16, or utf-32 index.
+---@param line string the line to index into
+---@param byte integer the byte idx
+---@param offset_encoding string utf-8|utf-16|utf-32|nil (default: utf-8)
+--@returns integer the utf idx for the given encoding
+function M.byte_to_utf(line, byte, offset_encoding)
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/sync.lua:56]: Can we somehow merge this with `get_line_byte_from_position` in `vim.lsp.util` ?

File: runtime/lua/vim/lsp/sync.lua [hunk 5]
```diff
@@ -0,0 +1,384 @@
...
+--  test 2 -> test 2 -> test *4 -> *4     -> *4      ->
+--  test 3    test 3
+--  test *4   test 4
+
+local M = {}
+
+-- local string.byte, unclear if this is necessary for JIT compilation
+local str_byte = string.byte
+local vim = vim
+local math = math
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/sync.lua:47]: Does this make a difference?

File: runtime/lua/vim/lsp/sync.lua [hunk 6]
```diff
@@ -0,0 +1,384 @@
...
+-- Given a line, byte idx, alignment, and offset_encoding convert to the aligned
+-- utf-8 index and either the utf-16, or utf-32 index.
+---@param line string the line to index into
+---@param byte integer the byte idx
+---@param align string when dealing with multibyte characters,
+--        to choose the start of the current character or the beginning of the next.
+--        Used for incremental sync for start/end range respectively
+---@param offset_encoding string utf-8|utf-16|utf-32|nil (default: utf-8)
+---@returns table<string, int> byte_idx and char_idx of first change position
+function M.align_position(line, byte, align, offset_encoding)
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/sync.lua:85]: Only `compute_diff` is used by the other modules. Should we keep the other functions local? (Or rename `sync` to `_sync` to indicate that it's private?)

File: runtime/lua/vim/lsp/sync.lua [hunk 7]
```diff
@@ -0,0 +1,384 @@
...
+  local prev_line_length = #prev_line
+  local curr_line_length = #curr_line
+
+  local byte_offset = 0
+  -- Buffer has increased in line count
+  -- if new_lastline > lastline then
+  -- -- Buffer has decreased in line count
+  -- elseif new_lastline < lastline then
+  -- elseif
+  -- end
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/sync.lua:202]: This looks a bit as if it is a leftover from iterating on the code. I guess it can be removed?

File: runtime/lua/vim/lsp/sync.lua [hunk 8]
```diff
@@ -0,0 +1,384 @@
...
+    if not lines[start_range.line_idx] then
+      return ""
+    end
+  -- Trivial case: start and end range are the same line, directly grab changed text
+  if start_range.line_idx == end_range.line_idx then
+    -- string.sub is inclusive, end_range is not
+    return string.sub(lines[start_range.line_idx], start_range.byte_idx, end_range.byte_idx - 1)
+
+  else
+    -- Handle deletion cas
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/sync.lua:257]:
```suggestion
    -- Handle deletion case
```

File: runtime/lua/vim/lsp/sync.lua (hunk 5 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp/sync.lua:47]: I believe making the tables local avoid a global lookup in each access, I'm not 100% positive on this though.

File: runtime/lua/vim/lsp/sync.lua (hunk 6 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp/sync.lua:85]: Yes, I'll make everything private. Originally I kept these public because I was going to write tests foreach one, but I ended up writing end to end tests.

File: runtime/lua/vim/lsp/sync.lua (hunk 4 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp/sync.lua]: I think it would require a rewrite of functions that call vim.lsp.util and promoting byte_to_utf to utils, which IMO is out of scope for this PR

File: runtime/lua/vim/lsp/sync.lua (hunk 5 above)
Comment (muniter) [reply runtime/lua/vim/lsp/sync.lua:47]: It does, according to Mike (bullet point 7) http://wiki.luajit.org/Numerical-Computing-Performance-Guide

Comment (mjlbach) [reply runtime/lua/vim/lsp/sync.lua:47]: Should I cache math.min as math_min instead?

Comment (mjlbach) [reply runtime/lua/vim/lsp/sync.lua]: Added some more aggresive local caching https://github.com/neovim/neovim/pull/16252/commits/72f27ab529764a2ae65d2eea654fc687b9fb99a4

Comment (mfussenegger) [reply runtime/lua/vim/lsp/sync.lua]: > It does, according to Mike (bullet point 7) http://wiki.luajit.org/Numerical-Computing-Performance-Guide

Afaik that's a bit different than the `local vim = vim` case here - It assigns something within a table to the local to avoid the table lookups. 

> Added some more aggresive local caching 72f27ab

:+1:

Comment (mjlbach) [reply runtime/lua/vim/lsp/sync.lua]: I think my final update is in line with the performance guide though right? (no table lookup)

Comment (mfussenegger) [reply runtime/lua/vim/lsp/sync.lua]: As far as I understand - yes.

**Comment by mfussenegger** [comment]
I gave this a trial run for a day and didn't notice any sync bugs

**Review by mfussenegger — APPROVED** [review]
