### PR TITLE
fix(eval): fixups for winnrs of unfocusable/hidden windows

### LINKED ISSUE #35453: Fugitive diff exits diffmode when notification window is destroyed
### Problem

This is a recent issue I have that is hard to describe minimally. There's a conflict, sort of, between vim-fugitive and mini.notify. If I open my `packages.lua` file (which is basically my lazy.nvim plugin spec), then do `:Gdiffsplit`, I observe the following:

1. The diffsplit is opened as expected
2. mini.notify is showing lsp updates in a floating window
    Image
4. when the notifications stop and the floating window is removed, fugitive exits diffmode
    Image

I've traced the problem and have the following observations:

* The problem happens in Neovim nightly.
* The problem does not happen in Neovim v0.11.3.
* The autocommand here is what is triggering the diffmode exit: https://github.com/tpope/vim-fugitive/blob/61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4/autoload/fugitive.vim#L6548-L6551
  * For some reason, `s:can_diffoff(+expand('<abuf>'))` returns true.

### Steps to reproduce

I'm sorry to say that it is hard to create a minimal reproducible setup for this. I can look into it later if it is strictly necessary.

### Expected behavior

The expected behaviour is that exiting a floating window from the notifications does not also exit diffmode.

Image

### Nvim version (nvim -v)

NVIM v0.12.0-dev-1067+g0b8a9bde0e

### Vim (not Nvim) behaves the same?

Not relevant

### Operating system/version

Arch Linux

### Terminal name/version

wezterm 20250730-195751-6a493f88

### $TERM environment variable

xterm-256color

### Installation

AUR

### PR DESCRIPTION
**Pull request by seandewar**
Problem: various functions may return incorrect window numbers for unfocusable or hidden windows.

Solution: fix the checks. Make sure current windows in non-current tabpages have a window number.

Fixes #35453

Surprisingly fiddly to get this right, so hopefully I didn't screw anything up. :innocent:

### CODE REVIEW

File: test/functional/ui/float_spec.lua [hunk 1]
```diff
@@ -899,14 +900,53 @@ describe('float window', function()
...
+    command('tabfirst')
+    eq({ 2, 3 }, fn.win_id2tabwin(win))
+    eq(3, fn.getwininfo(win)[1].winnr)
+    eq(win, fn.win_getid(3, 2))
+    eq(3, fn.tabpagewinnr(2, '$'))
+    eq(3, fn.tabpagewinnr(2))
+
+    -- ...but not if it's non-current in that tabpage.
+    api.nvim_tabpage_set_win(tp, split_win)
+    eq({ 0, 0 }, fn.win_id2tabwin(win))
```
Comment (seandewar) [inline test/functional/ui/float_spec.lua:946]: Maybe this should return `[tp, 0]` instead, but that might be odd (and it'd have to be documented).

(Eh, I guess `getwininfo` does that now anyway, so maybe it should...)

Comment (seandewar) [reply test/functional/ui/float_spec.lua:946]: Looking at Vim for inspiration, I think this is fine.
  
They also return `[0, 0]` and can return `#{winnr: 0, tabnr: <non-zero>}` for their popup windows from `win_id2tabwin` and `getwininfo` respectively. (Actually it looks like due to a bug, Vim always gives `tabnr: 0`... vim/vim#18111)

Comment (seandewar) [reply test/functional/ui/float_spec.lua:946]: Vim bug fixed in [v9.1.1696](https://github.com/vim/vim/commit/7d6be2cead4e58356387b52ab9587c079a167775) :+1:
