### PR TITLE
fix(treesitter): validate language alias for injections

### LINKED ISSUE #27078: nightly: Error in decoration provider treesitter/highlighter.win
The problem is reproducible on nightly. The problem is not reproducible on nvim v0.9.5 from archlinux repos.

I posted the issue on nvim-treesitter https://github.com/nvim-treesitter/nvim-treesitter/issues/5917 and @clason recommended to post here, so I am doing it.

### Problem

When editing a `.sh` file the following error comes up:

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:751: Vim:E219: Brak {.                                   
stack traceback:                                                                                                                          
        [C]: in function 'nvim_get_runtime_file'                                                                                          
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:751: in function 'fn'                                                 
        ...vim/install/share/nvim/runtime/lua/vim/func/_memoize.lua:54: in function 'has_parser'                                          
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:760: in function 'resolve_lang'                                       
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:799: in function '_get_injection'                                     
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:844: in function 'f'                                                  
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:192: in function 'tcall'                                              
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:383: in function '_add_injections'                                    
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:446: in function 'parse'                                              
        ...ll/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:350: in function <...ll/share/nv     
```

### Steps to reproduce

1. Create the following file:

```
#!/bin/bash
      config {
        args = [<<-EOF
          exec sleep 60
          ${var.script}
        EOF
        ]
      }
    }
  }
}
```

2. Save it as testfile.sh

3. Open with neovim __nightly__

4. The error just happens on startup and I think happens in a loop. Editor is unusable.

obraz

### Expected behavior

The editor should be usable.

### Output of `:checkhealth nvim-treesitter`

```markdown
1                                                                                                                                   
        1 ──────────────────────────────────────────────────────────────────────────────
        2 nvim-treesitter: require("nvim-treesitter.health").check()
        3 
        4 Installation
        5 - WARNING tree-sitter executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :                   TSInstall)
        6 - OK node found v21.5.0 (only needed for :TSInstallFromGrammar)
        7 - OK git executable found.
        8 - OK cc executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
        9   Version: cc (GCC) 13.2.1 20230801
       10 - OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
       11 
       12 OS Info:
       13 {
       14   machine = "x86_64",
       15   release = "6.7.0-zen3-1-zen",
       16   sysname = "Linux",
       17   version = "#1 ZEN SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:36:54 +0000"
       18 } 
       19 
       20 Parser/Features         H L F I J
       21   - bash                ✓ ✓ ✓ . ✓
       22   - c                   ✓ ✓ ✓ ✓ ✓
       23   - cpp                 ✓ ✓ ✓ ✓ ✓
       24   - lua                 ✓ ✓ ✓ ✓ ✓
       25   - markdown            ✓ . ✓ ✓ ✓
       26   - markdown_inline     ✓ . . . ✓
       27   - python              ✓ ✓ ✓ ✓ ✓
       28   - query               ✓ ✓ ✓ ✓ ✓
       29   - vim                 ✓ ✓ ✓ . ✓
       30   - vimdoc              ✓ . . . ✓
       31 
       32   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
       33          +) multiple parsers found, only one will be used
       34          x) errors found in the query, try to run :TSUpdate {lang}
       35 


also:

```
$ git -C .vim/plugged/nvim-treesitter/ log -1
commit 503d0ccdee762bb4b2758c391288768fafe39861 (HEAD -> master, origin/update-readme-pr, origin/master, origin/HEAD)
Author: GitHub <noreply@github.com>
Date:   Thu Jan 18 06:37:49 2024 +0000
```

### Output of `nvim --version`

```text
$ nvim -V1 -v
NVIM v0.10.0-dev-2121+g06aebfa99
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
Compilation: /usr/bin/cc -O2 -g -Og -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always  -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/kamil/.cache/,nvim/neovim/.deps/usr/include/luajit-2.1 -I/home/kamil/.cache/,nvim/neovim/.deps/usr/include -I/home/kamil/.cache/,nvim/neovim/build/src/nvim/auto -I/home/kamil/.cache/,nvim/neovim/build/include -I/home/kamil/.cache/,nvim/neovim/build/cmake.config -I/home/kamil/.cache/,nvim/neovim/src -I/usr/include 

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/kamil/.cache/,nvim/install/share/nvim"

Run :checkhealth for more info
```

### Additional context

Thanks! Just a heads up that there may be problems with nvim-nightly. I do not know if report here or upstream to neovim. Disabling nvim-treesitter from vim-plug makes the issue dissapear. Thanks!

### Neovim version (nvim -v)

v0.10.0-dev-2121+g06aebfa99

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ArchLinux

### Terminal name/version

KDE konsole

### $TERM environment variable

xterm-256color

### Installation

git clone https://github.com/neovim/neovim.git && cd neovim && git checkout tags/nightly && make CMAKE_BUILD_TYPE=RealWithDebInfo VERBOSE=1 CMAKE_INSTALL_PREFIX=mydir cmake nvim install

### PR DESCRIPTION
**Pull request by clason**
Problem: Parsed language annotations can be random garbage so
`nvim_get_runtime_file` throws an error.

Solution: Validate that `alias` is a valid language name before trying
to find a parser for it.

Uses the same strategy as in `vim.language.add`.

Fixes #27078

### CODE REVIEW

File: runtime/lua/vim/treesitter/languagetree.lua [hunk 1]
```diff
@@ -757,6 +757,11 @@ end)
 ---@param alias string language or filetype name
 ---@return string? # resolved parser name
 local function resolve_lang(alias)
+  -- validate that `alias` is a legal language
+  if not (alias and alias:match('[%w_]+') == alias) then
```
Comment (lewis6991) [inline runtime/lua/vim/treesitter/languagetree.lua:761]: Personally, I find dropping the parens makes the logic marginally better to follow.

```suggestion
  if not alias or alias:match('[%w_]+') ~= alias then
```

but feel free to ignore

**Review by lewis6991 — APPROVED** [review]

File: runtime/lua/vim/treesitter/languagetree.lua (hunk 1 above)
Comment (lewis6991) [reply runtime/lua/vim/treesitter/languagetree.lua:761]: I wouldn't worry then.
