### PR TITLE
fix(mark): set mark fnum from buffer

### LINKED ISSUE #19173: " mark jumps to last buffer ("E92: Buffer 0 not found")
### Neovim version (nvim -v)

NVIM v0.8.0-dev+528-g3b1423bfa

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

Source

### How to reproduce the issue

Start nvim with `nvim --clean`.

Edit a new file `foo` and put in some contents:

```
:e foo
iHello<CR>world<Esc>
:w
```

Without closing nvim, edit a second file `bar` and put in some contents:

```
:e bar
iGoodbye<Esc>
:w
```

Close `nvim`, then reopen `bar`:

```
nvim --clean bar
```

Now edit `foo` again and use `'"` to move your cursor to the last known position:

```
:e foo
'"
```

### Expected behavior

The cursor should move to the end of the second line, which is the last cursor position in that buffer.

### Actual behavior

The buffer changes back to `bar`.

Bisected to 565f72b9689e0c440ff72c712a090224aaf7631b.

Another (simpler) way to replicate this is to simply open any file and press `'"` in normal mode. The cursor should move to the last position in that file, but instead it shows an error: `E92: Buffer 0 not found`.

I discovered this because it breaks the common pattern of using an autocommand to automatically restore the cursor position when opening a buffer as documented in `:h restore-cursor`.

### PR DESCRIPTION
**Pull request by gpanders**
Closes #19173.

### CODE REVIEW

File: src/nvim/mark.c [hunk 1]
```diff
@@ -430,6 +430,8 @@ fmark_T *mark_get_local(buf_T *buf, win_T *win, int name)
     mark = mark_get_motion(buf, win, name);
   }
 
+  mark->fnum = buf->b_fnum;
```
Comment (muniter) [inline src/nvim/mark.c:433]: Thanks gp. Need a null check on `mark`

**Review by muniter — APPROVED** [review]
I'm working on a fix that makes sure marks are not set with incorrect fnum and some tests. But would like this PR merged since I might take a little longer with mine, and want to stop the breakage.
