### PR TITLE
fix(man): support MacOS 13

### LINKED ISSUE #20579: `:Man` broken on macOS 13
### Neovim version (nvim -v)

v0.9.0-dev-66-g121f052d1

### Vim (not Nvim) behaves the same?

no, 9.0.270

### Operating system/version

macOS 13.0 beta

### Terminal name/version

kitty 0.26.3

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue
```
nvim --clean
:Man g| (here | is the cursor)
and then press `tab` here
```
### Expected behavior

Like vim, a sound feedback to indicate that vim has no completion available.

### Actual behavior

```
E5108: Error executing Lua function: /usr/local/share/nvim/runtime/lua/man.lua:502: /usr/local/share/nvim/runtime
/lua/man.lua:11: man.lua: "command error 'man -w': What manual page do you want?\n"
stack traceback:
        [C]: in function 'error'
        /usr/local/share/nvim/runtime/lua/man.lua:502: in function 'get_paths'
        /usr/local/share/nvim/runtime/lua/man.lua:514: in function </usr/local/share/nvim/runtime/lua/man.lua:513>
```

### PR DESCRIPTION
**Pull request by lewis6991**
MacOS 13 has changed its version of `man` to an version that doesn't
properly support `man -w` (without arguments). In order to workaround
this we simply fallback to $MANPATH.

Fixes #20579

### CODE REVIEW

File: runtime/lua/man.lua [hunk 1]
```diff
@@ -480,38 +482,30 @@ local function format_candidate(path, psect)
...
+  end, list)
+  return { elem, unpack(list1) }
+end
 
-    -- Fallback to a single path, with the page we're trying to find.
-    ok, ret = pcall(verify_exists, sect, name)
+local function get_paths(sect, name)
+  -- must pcall as some `man` implementations don't support FIND_ARG without arguments (e.g. macOS 13)
+  local mandirs_raw = vim.F.npcall(man_system, { FIND_ARG }) or vim.env.MANPATH
+  local mandirs table.concat(vim.split(mandirs_raw, '[:\n]', { trimempty = true }), ',')
```
Comment (mathjiajia) [inline runtime/lua/man.lua:495]: missed an equal sign here?
