### PR TITLE
fix(treesitter): TSNode:id() with NUL byte causes unreliable select()

### LINKED ISSUE #39126: unreliable test: `select_spec.lua: treesitter incremental-selection repeat`
seen in https://github.com/neovim/neovim/actions/runs/24513313811/job/71650139559

```
FAILED   ...im/neovim/test/functional/treesitter/select_spec.lua @ 69: treesitter incremental-selection repeat
Expected values to be equal.
Expected:
"4"
Actual:
"2"
stack traceback:
	...im/neovim/test/functional/treesitter/select_spec.lua:82: in function <...im/neovim/test/functional/treesitter/select_spec.lua:69>
```

@altermo

### PR DESCRIPTION
**Pull request by altermo**
fix https://github.com/neovim/neovim/issues/39126

I misdiagnosed this issue (in https://github.com/neovim/neovim/pull/38391) as a race condition, while it actually was that adding extra code made the memory arrangement change perfectly for the bug to not happen.

The bug: TSNode:id() returns the underlying c pointer as a string, which may include null bytes; and these null bytes are not handled by string.format in PUC-lua. This resulted in two different nodes being able to have the same id..

And what I mean by not handled is that PUC-lua `('%s'):format('\0a\0')` returns `''` and not `'\0a\0'` (e.g. treats the string as a c-string(string which ends in null-byte)).

### CODE REVIEW

File: runtime/lua/vim/treesitter/_select.lua [hunk 1]
```diff
@@ -36,7 +36,7 @@ local M = {}
 --- @param node vim.treesitter.select.node
 --- @return string
 local function node_id(node)
-  return ('%s:%s'):format(table.concat({ unpack(node.top.region) }, ':'), node.node:id())
+  return table.concat({ unpack(node.top.region) }, ':') .. ':' .. node.node:id()
```
Comment (justinmk) [inline runtime/lua/vim/treesitter/_select.lua:39]: could still use format() ?

```suggestion
  ('%s:%s'):format(table.concat({ unpack(node.top.region) }, ':'), tostring(node.node:id()))
```

**Comment by justinmk** [comment]
> TSNode:id() returns the underlying c pointer as a string, which may include null bytes

That seems like a more lower-level bug that we might want to track?

But thanks for fixing the select code meanwhile 👍

File: runtime/lua/vim/treesitter/_select.lua (hunk 1 above)
Comment (altermo) [reply runtime/lua/vim/treesitter/_select.lua:39]: No, in puc lua `('%s'):format('\0a\0')` returns `''` and not `'\0a\0'`, thats the problem...
