### PR TITLE
fix(terminal): fix pointer comparison after free

### LINKED ISSUE #16941: Flaky `curwin` pointer comparisons
### Neovim version (nvim -v)

0.6.1, v0.7.0-dev+835-gf65b0d423

### Vim (not Nvim) behaves the same?

no (but repro case is different)

### Operating system/version

Linux / glibc 2.33

### Terminal name/version

alacritty 0.9.0

### $TERM environment variable

alacritty

### Installation

package (0.6.1) and built from source (0.7.0-dev)

### How to reproduce the issue

1. Install `fzf` on the system
2. Assuming `fzf` is installed in `/usr` (adjust the `source` setting otherwise):
```console
% mkdir /tmp/test
% cd /tmp/test
% cat <<EOF > init.vim
source /usr/share/vim/vimfiles/plugin/fzf.vim
nnoremap <C-p> :FZF<CR>
set cursorline
set cursorcolumn
set number
EOF
% nvim --clean -u init.vim
```
3. press `C-p` and `C-t` repeatedly

### Expected behavior

The only file present in the directory (`init.vim` here) should open in a new tab, preserving the current window configuration.

### Actual behavior

Sometimes, the new window doesn't inherit properly all the settings (`cursorline` and `cursorcolumn` go away):

https://user-images.githubusercontent.com/34467/148231181-9fd480e5-dd75-442b-a75d-b190800764cd.mp4

---

I did some investigation, and the cause of the issue is the following: neovim is doing `curwin` comparison between pointers, but sometimes malloc returns the same pointer after being free'd.

Given the following debug-diff:
```diff
diff --git a/src/nvim/terminal.c b/src/nvim/terminal.c
index 70a5c7aa0..126a8a262 100644
--- a/src/nvim/terminal.c
+++ b/src/nvim/terminal.c
@@ -416,7 +416,15 @@ void terminal_enter(void)

   s->state.execute = terminal_execute;
   s->state.check = terminal_check;
+
+  smsg(">>> state enter / curwin unchanged:%s [saved:%p (h:%d) curwin:%p (h:%d)])",
+       save_curwin == curwin ? "yes": "no",
+       (void*)save_curwin, save_curwin->handle, (void*)curwin, curwin->handle);
+
   state_enter(&s->state);
+  smsg("<<< state exit  / curwin unchanged:%s [saved:%p (h:%d) curwin:%p (h:%d)])",
+       save_curwin == curwin ? "yes" : "no",
+       (void*)save_curwin, save_curwin->handle, (void*)curwin, curwin->handle);

   restart_edit = 0;
   State = save_state;
diff --git a/src/nvim/window.c b/src/nvim/window.c
index 1e747a67e..c17a08c7c 100644
--- a/src/nvim/window.c
+++ b/src/nvim/window.c
@@ -3690,6 +3690,7 @@ void win_alloc_aucmd_win(void)
 static int win_alloc_firstwin(win_T *oldwin)
 {
   curwin = win_alloc(NULL, false);
+  smsg("win_alloc_firstwin() -> %p", (void*)curwin);
   if (oldwin == NULL) {
     // Very first window, need to create an empty buffer for it and
     // initialize from scratch.
@@ -4800,6 +4801,7 @@ static void win_free(win_T *wp, tabpage_T *tp)
   int i;
   wininfo_T *wip;

+  smsg("win_free(%p)", (void*)wp);
   pmap_del(handle_T)(&window_handles, wp->handle);
   clearFolding(wp);
```

Here is a sequence of what typically happens:

```
win_free(0x5587ef127310)
win_alloc_firstwin() -> 0x5587ef126b10
<<< state exit  / curwin unchanged:no [saved:0x5587ef127310 (h:0) curwin:0x5587ef126b10 (h:1004)])
>>> state enter / curwin unchanged:yes [saved:0x5587ef12fbb0 (h:1005) curwin:0x5587ef12fbb0 (h:1005)])
win_free(0x5587ef12fbb0)
win_alloc_firstwin() -> 0x5587ef12cb80
<<< state exit  / curwin unchanged:no [saved:0x5587ef12fbb0 (h:0) curwin:0x5587ef12cb80 (h:1006)])
>>> state enter / curwin unchanged:yes [saved:0x5587ef1370d0 (h:1007) curwin:0x5587ef1370d0 (h:1007)])
win_free(0x5587ef1370d0)
win_alloc_firstwin() -> 0x5587ef19b8c0
<<< state exit  / curwin unchanged:no [saved:0x5587ef1370d0 (h:1007) curwin:0x5587ef19b8c0 (h:1008)])
>>> state enter / curwin unchanged:yes [saved:0x5587ef13c390 (h:1009) curwin:0x5587ef13c390 (h:1009)])
win_free(0x5587ef13c390)
win_alloc_firstwin() -> 0x5587ef13c390
<<< state exit  / curwin unchanged:yes [saved:0x5587ef13c390 (h:1010) curwin:0x5587ef13c390 (h:1010)])
```

The last `win_free()`/`win_alloc_firstwin()` pair has matching pointers, which messes up a lot of comparison, typically in `terminal.c` the following (but not the only place):

```c
  if (save_curwin == curwin) {  // save_curwin may be invalid (window closed)!
```

I'm not sure how to fix that, in particular because I see a lot of other `curwin` pointer comparison. I would say that having the `free` happening *after* the allocation of the new window would be the safest, but I'm not sure how to achieve that (I'm not familiar with the codebase at all).

This bugs is expressed relatively harmlessly in this case (pretty annoying though), but I believe very bad things could happen messing with pointers like this.

Also note that `cursorcolumn` and `cursorline` are reset because the floating window uses a minimal style which resets those, but for some reason the line numbering is not affected.

### PR DESCRIPTION
**Pull request by ubitux**
At the moment of comparison, the pointer save_curwin can be invalid (as
suggested by the comment) because it has been free'd. Worst, the new
curwin could have been re-allocated to that same pointer, altering the
execution flow unpredictably.

While there are many other potential similar cases to fix in the
codebase, the presented scenario is not hypothetical and does happen in
practice (while spawning new windows from fzf for instance).

There are numerous other instances of curwin comparisons in the
codebase, and they may need further investigation.

closes #16941

### CODE REVIEW

**Comment by jamessan** [comment]
LGTM.  @bfredl?

File: src/nvim/terminal.c [hunk 1]
```diff
@@ -404,7 +404,7 @@ void terminal_enter(void)
 
   // Disable these options in terminal-mode. They are nonsense because cursor is
   // placed at end of buffer to "follow" output. #11072
-  win_T *save_curwin = curwin;
+  handle_T save_handle = curwin->handle;
```
Comment (justinmk) [inline src/nvim/terminal.c:407]: nit: I'd leave the name as it was, it's a bit more semantically descriptive

**Review by justinmk — APPROVED** [review]
This makes sense, and yes it's a pattern we should follow everywhere.

File: src/nvim/terminal.c (hunk 1 above)
Comment (ubitux) [reply src/nvim/terminal.c]: Rebased & done

Comment (ubitux) [reply src/nvim/terminal.c]: Note that there is a `win_T *save_curwin = curwin` in the same file later on, so it might get confusing. That's why I renamed it in the first place.

File: src/nvim/terminal.c [hunk 2]
```diff
@@ -442,7 +442,7 @@ void terminal_enter(void)
   RedrawingDisabled = s->save_rd;
   apply_autocmds(EVENT_TERMLEAVE, NULL, NULL, false, curbuf);
 
-  if (save_curwin == curwin) {  // save_curwin may be invalid (window closed)!
+  if (save_curwin == curwin->handle) {
```
Comment (justinmk) [inline src/nvim/terminal.c:445]: the comment is still relevant: the reason we are checking this is because we don't want to enter this block if the window was closed.
```suggestion
  if (save_curwin == curwin->handle) {  // Else: window was closed.
```
