### PR TITLE
vim-patch:8.2.3394: filler lines are wrong when changing text in diff mode

### LINKED ISSUE #8809: Unexpected scrolling while editing with diff mode enabled
# Describe the bug
In diff mode, editing in and leaving the insert mode scrolls the window unexpectedly (presumably to align the diff?).
Specifically, this happens when
(1) typing a character for the first time after entering insert mode;
(2) typing a non-`<CR>` character for the first time after typing `<CR>` in the insert mode;
(3) typing `<CR>` after typing a non-`<CR>` character in insert mode;
(4) leaving the insert mode and the window was affected by any of (1)-(3) during this insert mode session.

# To Reproduce
1. Prepare two files

<details><summary>left</summary>
<pre>
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
</pre>
</details>
<details><summary>right</summary>
<pre>
11
12
13
14
15
16
17
18
19
20
</pre>
</details>

2. Run `vim --clean -d left right` (or `gvim --clean ...`,)
3. Move the cursor to the last line of the right window, unfold the folds if any, and hit `<C-e>` several times so that the left window's DiffAdd area is "cut" by the top of the window. See the image below. 
4. Run the cases (1)-(4) described above. For example, `Aa<CR>a<ESC>`. The window will vigorously scroll up and down at each key (except the first `A`). a-1 cr a-2 esc

# Expected behavior
The window should not scroll.

# Environment
- OS: Ubuntu 21.04
- GNOME Terminal and GVim.

# Relevant commits
* At 8.1.0363, only (1) is present. I haven't checked when this behavior is first introduced.
* 8.1.0394 introduced (4).
    ```
    commit e3521d9cbb786806eaff106707851d37d2c0ecef
    Author: Bram Moolenaar <Bram@vim.org>
    Date:   Sun Sep 16 14:10:31 2018 +0200

        patch 8.1.0394: diffs are not always updated correctly

        Problem:    Diffs are not always updated correctly.
        Solution:   When using internal diff update for any changes properly.

     src/diff.c         | 20 +++++++++++++++-----
     src/main.c         |  9 +++++++++
     src/misc1.c        |  7 ++++++-
     src/proto/diff.pro |  1 +
     src/structs.h      |  3 ++-
     src/version.c      |  2 ++
     6 files changed, 35 insertions(+), 7 deletions(-)
    ```
* 8.1.1922 introduced (2) and (3)
    ```
    commit 4f57eefe1e84b5a90e08474092ea6fc8825ad5c9
    Author: Bram Moolenaar <Bram@vim.org>
    Date:   Sat Aug 24 20:54:19 2019 +0200

        patch 8.1.1922: in diff mode global operations can be very slow

        Problem:    In diff mode global operations can be very slow.
        Solution:   Do not call diff_redraw() many times, call it once when redrawing.
                    And also don't update folds multiple times.

     src/diff.c         | 7 ++++---
     src/fold.c         | 5 +++++
     src/globals.h      | 3 +++
     src/proto/diff.pro | 1 +
     src/screen.c       | 6 ++++++
     src/version.c      | 2 ++
     6 files changed, 21 insertions(+), 3 deletions(-)
    ```

### PR DESCRIPTION
**Pull request by tomtomjhj**
Problem:    Filler lines are wrong when changing text in diff mode.
Solution:   Don't change the filler lines on every change.  Check
            scrollbinding when updating the filler lines. (closes vim/vim#8809)
https://github.com/vim/vim/commit/04626c243c47af91c2580eaf23e12286180e0e81

### CODE REVIEW

File: src/nvim/diff.c [hunk 1]
```diff
@@ -639,12 +639,18 @@ static int diff_check_sanity(tabpage_T *tp, diff_T *dp)
 /// @param dofold Also recompute the folds
 void diff_redraw(bool dofold)
 {
+  win_T *wp_other = NULL;
+  int used_max_fill = false;
```
Comment (seandewar) [inline src/nvim/diff.c:643]:
```suggestion
  bool used_max_fill = false;
```

**Review by bfredl — APPROVED** [review]
Did a quick check whether it would conflict with #15351  in any way, and it looks fine :)

**Review by janlazo — APPROVED** [review]

**Comment by tomtomjhj** [comment]
Can someone merge this?

File: src/nvim/testdir/test_diffmode.vim [hunk 2]
```diff
@@ -965,6 +965,30 @@ func Test_diff_screen()
   call delete('XdiffSetup')
 endfunc
 
+func Test_diff_with_scroll_and_change()
+  CheckScreendump
```
Comment (justinmk) [inline src/nvim/testdir/test_diffmode.vim:969]: this test will be skipped because Nvim does not use Vim screen tests. we need a lua screen test that mimics this one. It is pretty easy, see https://github.com/neovim/neovim/blob/9edd17509fca597b847656adc8fc20fc1cc44ce5/test/functional/example_spec.lua

Comment (tomtomjhj) [reply src/nvim/testdir/test_diffmode.vim:969]: Thanks for the tip. Ported this test to diff_spec.lua.
