### PR TITLE
fix: add bold border size to vim.lsp.buf.hover

### LINKED ISSUE #33382: bold border with lsp.buf.hover
### Problem

https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/util.lua#L20
not define the bold border size

### Steps to reproduce

invoke lsp.buf.hover with border = "bold" opts

### Expected behavior

open lsp.buf.hover float window with bold border

### Nvim version (nvim -v)

NVIM v0.12.0-dev-105+g8af9f8ab5e

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 15.4

### Terminal name/version

wezterm 20250103-121535-8e9cf912

### $TERM environment variable

xterm-256color

### Installation

appimage

### PR DESCRIPTION
**Pull request by siddhantdev**
Problem: vim.lsp.buf.hover allows a bold border size which hasn't been defined

Solution: Define the bold border size for vim.lsp.buf.hover

Fixes: https://github.com/neovim/neovim/issues/33382

### CODE REVIEW

**Review by MariaSolOs — APPROVED** [review]

**Comment by MariaSolOs** [comment]
@glepnir could you also please check that this looks correct? :)

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -24,6 +24,7 @@ local border_size = {
   rounded = { 2, 2 },
   solid = { 2, 2 },
   shadow = { 1, 1 },
+  bold = { 3, 3 },
```
Comment (zeertzjq) [inline runtime/lua/vim/lsp/util.lua:27]: How can border size be 3? The are only two borders in each direction.
```suggestion
  bold = { 2, 2 },
```

**Review by zeertzjq — DISMISSED** [review]

**Review by glepnir — APPROVED** [review]
