### PR TITLE
fix(screen): redraw the ruler for a current floating window

### LINKED ISSUE #22664: Ruler is not shown when cursor is inside floating window
### Problem

When cursor is placed inside floating window, ruler is not shown. This seems to be a side effect of #22590. 

### Steps to reproduce

1. `nvim -u NONE`
2. `:lua vim.api.nvim_open_win(0, true, {relative = 'editor', row = 1, col = 1, width = 10, height = 10})`
3. Look at cursor position and ruler in bottom right. Previously it showed  `0,0-1  All` but it does not on latest appimage release.

### Expected behavior

Ruler behavior does not depend on whether cursor in inside regular or floating window.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1223+g3e8955094

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.2.2-arch2-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

### PR DESCRIPTION
**Pull request by bfredl**
Semi-regression. The "ruler" behavior for a floating window was never really specified but in practice followed the users cursor movements in normal mode in a focused float, which seems like a reasonable behavior to now specify.

### CODE REVIEW

File: test/functional/ui/float_spec.lua [hunk 1]
```diff
@@ -2184,6 +2184,98 @@ describe('float window', function()
       end
     end)
 
+    it('with border show popupmenu', function()
```
Comment (zeertzjq) [inline test/functional/ui/float_spec.lua:2187]: This description is wrong.
