### PR TITLE
vim-patch:8.2.{4594,4603,4607,4647,4974}

### LINKED ISSUE #28481: `:finish` can no longer be used in `exrc` files since v0.9.0
### Problem

Since v0.9.0, I started getting

```
Error detected while processing .exrc:
E168: :finish used outside of a sourced file
```

...due to `finish`es in my `.exrc`.

I suspect this is related to the `vim.secure.read()` + exrc changes.

### Steps to reproduce

1. Enable `exrc`
2. Create a `.exrc` file like (This is how/why I use `finish` in `exrc`s. To reproduce the issue itself, a simple `finish` anywhere should do.)
    ```vim
    if index(['git', 'gh'], trim(split(system('ps -o comm= ' .. luaeval('vim.loop.os_getppid()')), '/')[-1])) >= 0
          \ || stridx(trim(split(system('ps -o command= ' .. luaeval('vim.loop.os_getpid()')), '/')[-1]), '+Man!') >= 0
      finish
    endif
    
    " lots of settings
    ```
3. Start Neovim (In my case, use Neovim as Git editor and `git commit`, or use Neovim as Manual pager then `man ...`)

### Expected behavior

`:finish` still works in `exrc`s.

### Neovim version (nvim -v)

v0.9.5

### Vim (not Nvim) behaves the same?

No, 9.1 (2024 Jan 02, compiled Apr 18 2024 20:05:12)

### Operating system/version

macOS 14.4.1

### Terminal name/version

Kitty 0.34.1

### $TERM environment variable

tmux-256color

### Installation

Homebrew

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #28481

#### vim-patch:8.2.4594: need to write script to a file to be able to source them

Problem:    Need to write script to a file to be able to source them.
Solution:   Make ":source" use lines from the current buffer. (Yegappan
            Lakshmanan et al., closes vim/vim#9967)

https://github.com/vim/vim/commit/36a5b6867bb6c0bd69c8da7d788000ab8a0b0ab0

Most code and test changes are reverted or modified again in patch
8.2.4603, so only port parts that are untouched in patch 8.2.4603.

Co-authored-by: Yegappan Lakshmanan <yegappan@yahoo.com>

#### vim-patch:8.2.4603: sourcing buffer lines is too complicated

Problem:    Sourcing buffer lines is too complicated.
Solution:   Simplify the code. Make it possible to source Vim9 script lines.
            (Yegappan Lakshmanan, closes vim/vim#9974)

https://github.com/vim/vim/commit/85b43c6cb7d56919e245622f4e42db6d8bee4194

This commit changes the behavior of sourcing buffer lines to always have
a script ID, although sourcing the same buffer always produces the same
script ID.

vim-patch:9.1.0372: Calling CLEAR_FIELD() on the same struct twice

Problem:  Calling CLEAR_FIELD() on the same struct twice.
Solution: Remove the second CLEAR_FIELD().  Move the assignment of
          cookie.sourceing_lnum (zeertzjq).

closes: vim/vim#14627

https://github.com/vim/vim/commit/f68517c1671dfedcc1555da50bc0b3de6d2842f6

Co-authored-by: Yegappan Lakshmanan <yegappan@yahoo.com>

#### vim-patch:8.2.4607: sourcing buffer lines may lead to errors for conflicts

Problem:    Sourcing buffer lines may lead to errors for conflicts.
Solution:   Add the ++clear argument. (Yegappan Lakshmanan, closes vim/vim#9991)

https://github.com/vim/vim/commit/35dc17634dd6da5b90bd1b0160c4ed9e394f4b87

Documentation changes only. Vim9script is N/A.
Cherry-pick another documentation change for :source from latest Vim.

Co-authored-by: Yegappan Lakshmanan <yegappan@yahoo.com>

#### vim-patch:8.2.4647: "source" can read past end of copied line

Problem:    "source" can read past end of copied line.
Solution:   Add a terminating NUL.

https://github.com/vim/vim/commit/2bdad6126778f907c0b98002bfebf0e611a3f5db

Co-authored-by: Bram Moolenaar <Bram@vim.org>

#### vim-patch:8.2.4974: ":so" command may read after end of buffer

Problem:    ":so" command may read after end of buffer.
Solution:   Compute length of text properly.

https://github.com/vim/vim/commit/4748c4bd64610cf943a431d215bb1aad51f8d0b4

Co-authored-by: Bram Moolenaar <Bram@vim.org>

### CODE REVIEW

File: src/nvim/runtime.c [hunk 1]
```diff
@@ -2177,28 +2144,32 @@ int do_source(char *fname, int check_other, int is_vimrc, int *ret_sid)
...
     si = new_script_item(fname_exp, &sid);
     fname_exp = xstrdup(si->sn_name);  // used for autocmd
     if (ret_sid != NULL) {
       *ret_sid = sid;
     }
   }
-  current_sctx.sc_sid = sid;
+  if (!cookie.source_str_from_lua) {
+    current_sctx.sc_sid = sid;
+  }
```
Comment (zeertzjq) [inline src/nvim/runtime.c:2167]: Probably better to make `nvim_exec2` behavior the same in Vimscript and Lua (and not allocated a script ID unless using `:s`), while always allocating a new script ID when sourcing buffer lines.
