### PR TITLE
vim-patch:9.1.{0954,0956}

### LINKED ISSUE #16284: popupmenu.c:539 occurs SEGV and heap-buffer-overflow after v9.1.0954
### Steps to reproduce

 - Show completion candidates.
 - Scroll backward continuously by ^P
 - Killed by SEGV

### Expected behaviour

Scroll smoothly and no SEGV

### Version of Vim

9.1.0954

### Environment

OS: Arch Linux (WSL2) and Arch Linux
terminal: Alacritty (Windows 11) and Alacritty (Arch Linux)
TERM: xterm-256color
shell: GNU bash, version 5.2.37(1)-release

### Logs and stack traces

```shell
=================================================================
==43145==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x51a00006f078 at pc 0x55b44b94ff70 bp 0x7fff6b232510 sp 0x7fff6b232500
READ of size 4 at 0x51a00006f078 thread T0
    #0 0x55b44b94ff6f in pum_user_attr_combine /home/ray/projects/vim/vim/src/popupmenu.c:539
    #1 0x55b44b951324 in pum_redraw /home/ray/projects/vim/vim/src/popupmenu.c:650
    #2 0x55b44b94e5fa in pum_display /home/ray/projects/vim/vim/src/popupmenu.c:363
    #3 0x55b44b6c2f24 in ins_compl_show_pum /home/ray/projects/vim/vim/src/insexpand.c:1453
    #4 0x55b44b6ddb83 in show_pum /home/ray/projects/vim/vim/src/insexpand.c:5556
    #5 0x55b44b6dd9a5 in ins_complete /home/ray/projects/vim/vim/src/insexpand.c:5532
    #6 0x55b44b3c30ac in edit /home/ray/projects/vim/vim/src/edit.c:1304
    #7 0x55b44b870cdd in invoke_edit /home/ray/projects/vim/vim/src/normal.c:7125
    #8 0x55b44b870863 in nv_edit /home/ray/projects/vim/vim/src/normal.c:7091
    #9 0x55b44b829669 in normal_cmd /home/ray/projects/vim/vim/src/normal.c:952
    #10 0x55b44c14e7aa in main_loop /home/ray/projects/vim/vim/src/main.c:1562
    #11 0x55b44c14c9c5 in vim_main2 /home/ray/projects/vim/vim/src/main.c:895
    #12 0x55b44c14b958 in main /home/ray/projects/vim/vim/src/main.c:441
    #13 0x7fb393634e07  (/usr/lib/libc.so.6+0x25e07) (BuildId: 98b3d8e0b8c534c769cb871c438b4f8f3a8e4bf3)
    #14 0x7fb393634ecb in __libc_start_main (/usr/lib/libc.so.6+0x25ecb) (BuildId: 98b3d8e0b8c534c769cb871c438b4f8f3a8e4bf3)
    #15 0x55b44b1f80f4 in _start (/usr/local/bin/vim+0x14580f4) (BuildId: 93bcdca96b07efac2a946bb1a9b7ecf9aec64a44)

0x51a00006f078 is located 8 bytes before 1200-byte region [0x51a00006f080,0x51a00006f530)
allocated by thread T0 here:
    #0 0x7fb394cfd891 in malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x55b44b1f85a0 in lalloc /home/ray/projects/vim/vim/src/alloc.c:246
    #2 0x55b44b1f8413 in alloc_clear /home/ray/projects/vim/vim/src/alloc.c:177
    #3 0x55b44b6c1d5f in ins_compl_build_pum /home/ray/projects/vim/vim/src/insexpand.c:1364
    #4 0x55b44b6c2ae0 in ins_compl_show_pum /home/ray/projects/vim/vim/src/insexpand.c:1421
    #5 0x55b44b6ddb83 in show_pum /home/ray/projects/vim/vim/src/insexpand.c:5556
    #6 0x55b44b6dd9a5 in ins_complete /home/ray/projects/vim/vim/src/insexpand.c:5532
    #7 0x55b44b3c30ac in edit /home/ray/projects/vim/vim/src/edit.c:1304
    #8 0x55b44b870cdd in invoke_edit /home/ray/projects/vim/vim/src/normal.c:7125
    #9 0x55b44b870863 in nv_edit /home/ray/projects/vim/vim/src/normal.c:7091
    #10 0x55b44b829669 in normal_cmd /home/ray/projects/vim/vim/src/normal.c:952
    #11 0x55b44c14e7aa in main_loop /home/ray/projects/vim/vim/src/main.c:1562
    #12 0x55b44c14c9c5 in vim_main2 /home/ray/projects/vim/vim/src/main.c:895
    #13 0x55b44c14b958 in main /home/ray/projects/vim/vim/src/main.c:441
    #14 0x7fb393634e07  (/usr/lib/libc.so.6+0x25e07) (BuildId: 98b3d8e0b8c534c769cb871c438b4f8f3a8e4bf3)
    #15 0x7fb393634ecb in __libc_start_main (/usr/lib/libc.so.6+0x25ecb) (BuildId: 98b3d8e0b8c534c769cb871c438b4f8f3a8e4bf3)
    #16 0x55b44b1f80f4 in _start (/usr/local/bin/vim+0x14580f4) (BuildId: 93bcdca96b07efac2a946bb1a9b7ecf9aec64a44)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/ray/projects/vim/vim/src/popupmenu.c:539 in pum_user_attr_combine
Shadow bytes around the buggy address:
  0x51a00006ed80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51a00006ee00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51a00006ee80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51a00006ef00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51a00006ef80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x51a00006f000: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x51a00006f080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51a00006f100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51a00006f180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51a00006f200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51a00006f280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==43145==ABORTING
```

### PR DESCRIPTION
**Pull request by glepnir**
vim-patch:9.1.0954: popupmenu.c can be improved

Problem:  popupmenu.c can be improved
Solution: slightly refactor the logic
          (glepnir)

closes: https://github.com/vim/vim/pull/16271

Replace some if blocks and combine user attr abstract to an inline
function.

https://github.com/vim/vim/commit/89a107efd141d5a1fed850af80a74900077666cf

vim-patch:9.1.0956: completion may crash, completion highlight wrong
… with preview window

Problem:  completion may crash, completion highlight wrong with preview
          window (after v9.1.0954)
Solution: correctly calculate scroll offset, check for preview window
          when adding extra highlighting
          (glepnir)

when there have a preview window prepare_tagpreview
will change curwin to preview window and this may cause
ComplMatchIns check condition not correct. check wp is curwin
and also the type of wp is not a preview or poup info

fixes: https://github.com/vim/vim/issues/16284
closes: https://github.com/vim/vim/pull/16283

https://github.com/vim/vim/commit/8d0bb6dc9f2e5d94ebb59671d592c1b7fa325ca6

### CODE REVIEW

File: src/nvim/popupmenu.c [hunk 1]
```diff
@@ -633,13 +640,8 @@ void pum_redraw(void)
...
       attr = hl_combine_attr(win_hl_attr(curwin, HLF_PNI), attr);
       orig_attr = attr;
-      int user_abbr_hlattr = pum_array[idx].pum_user_abbr_hlattr;
-      int user_kind_hlattr = pum_array[idx].pum_user_kind_hlattr;
-      if (item_type == CPT_ABBR && user_abbr_hlattr > 0) {
-        attr = hl_combine_attr(attr, user_abbr_hlattr);
-      }
-      if (item_type == CPT_KIND && user_kind_hlattr > 0) {
-        attr = hl_combine_attr(attr, user_kind_hlattr);
+      if (item_type < 2) {
```
Comment (zeertzjq) [inline src/nvim/popupmenu.c:643]: Missing comment

File: test/old/testdir/test_popup.vim [hunk 2]
```diff
@@ -1809,7 +1813,22 @@ func Test_pum_matchins_highlight_combine()
   call VerifyScreenDump(buf, 'Test_pum_matchins_combine_06', {})
   call term_sendkeys(buf, "\<Esc>")
 
+  call term_sendkeys(buf, ":let g:change=1\<CR>S\<C-X>\<C-O>")
+  call VerifyScreenDump(buf, 'Test_pum_matchins_11', {})
+  call term_sendkeys(buf, "\<Esc>")
+
```
Comment (zeertzjq) [inline test/old/testdir/test_popup.vim:1819]: Wrong function

File: src/nvim/insexpand.c [hunk 3]
```diff
@@ -1722,6 +1722,12 @@ bool ins_compl_active(void)
   return compl_started;
 }
 
+/// Return True when wp is the actual completion window
+bool ins_compl_win_active(win_T *wp)
+{
+  return ins_compl_active() && !(wp->w_p_pvw || (wp->w_floating && wp->w_float_is_info));
```
Comment (zeertzjq) [inline src/nvim/insexpand.c:1728]: Is the `w_floating` check needed? It's not checked in the condition in `pum_set_selected`.

File: src/nvim/insexpand.c [hunk 4]
```diff
@@ -1722,6 +1722,12 @@ bool ins_compl_active(void)
   return compl_started;
 }
 
+/// Return True when wp is the actual completion window
```
Comment (zeertzjq) [inline src/nvim/insexpand.c:1725]:
```suggestion
/// Return true when wp is the actual completion window
```

File: test/functional/ui/popupmenu_spec.lua [hunk 5]
```diff
@@ -5668,11 +5668,15 @@ describe('builtin popupmenu', function()
       -- oldtest: Test_pum_matchins_highlight_combine()
       it('with ComplMatchIns, Normal and CursorLine highlights', function()
         exec([[
+          let g:change = 0
```
Comment (zeertzjq) [inline test/functional/ui/popupmenu_spec.lua:5671]: Code added to wrong function

Comment (glepnir) [reply test/functional/ui/popupmenu_spec.lua]: sry.. thanks for carefully review

File: test/functional/ui/popupmenu_spec.lua [hunk 6]
```diff
@@ -5663,6 +5667,20 @@ describe('builtin popupmenu', function()
           {2:-- INSERT --}                    |
         ]])
         feed('<Esc>')
```
Comment (zeertzjq) [inline test/functional/ui/popupmenu_spec.lua:5669]:
```suggestion
        feed('<Esc>')

```

File: test/old/testdir/test_popup.vim [hunk 7]
```diff
@@ -1767,17 +1767,25 @@ func Test_pum_matchins_highlight()
...
+    let g:change = 0
     func Omni_test(findstart, base)
       if a:findstart
         return col(".")
       endif
-      return [#{word: "foo"}, #{word: "bar"}, #{word: "你好"}]
+      if g:change == 0
+        return [#{word: "foo"}, #{word: "bar"}, #{word: "你好"}]
+      endif
+      return [#{word: "foo", info:"info"}, #{word: "bar"}, #{word: "你好"}]
```
Comment (zeertzjq) [inline test/old/testdir/test_popup.vim:1788]: Code added to wrong function
