### PR TITLE
fix(api): single-line visual block insert triggers extra on_lines

### LINKED ISSUE #22009: nvim_buf_attach: on_lines handler reports wrong value for Visual Block
### Describe the bug

Create a buffer with some lines. Register an event handler with

```
local function on_lines(_, bufnr, changedtick, first, last, last_updated, _, _, _)
  print(bufnr .. ' ' .. changedtick .. ' ' .. first .. ' ' .. last .. ' ' .. last_updated)
end

vim.api.nvim_buf_attach(0, false, {
  on_lines = on_lines
})
```
Go to the beginning of line 1. Go into Visual Block (C-V), insert a space (Shift + I, then space, then Escape). I get `<bufnr> <changedtick> 1 1 1`. Deleting the space with with `x` results in `<bufnr> <changedtick> 0 1 1` which is the correct result according to https://neovim.io/doc/user/api.html#nvim_buf_attach() (first value zero-indexed, rest probably not)

`<bufnr> <changedtick> 1 1 1` is wrong and should be `<bufnr> <changedtick> 0 1 1` (zero-based 1st line edited and was the only line edited, line number after edit is still 1.

### Steps to reproduce

See description.

### Expected behavior

See description.

### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

no, neovim specifics

### Operating system/version

Ubuntu 20.04

### Terminal name/version

Neovim-qt

### $TERM environment variable

n/a

### Installation

Self-compiled

### PR DESCRIPTION
**Pull request by glepnir**
Problem: Visual block insert on a single line incorrectly triggers two on_lines callbacks - one for the correct line (0-indexed) and another for a non-existent additional line.

Solution: Only call changed_lines() in block_insert() when additional lines beyond the first were actually modified (start.lnum < end.lnum).

fix #22009

### CODE REVIEW

File: test/functional/lua/buffer_updates_spec.lua [hunk 1]
```diff
@@ -449,6 +449,19 @@ describe('lua buffer event callbacks: on_lines', function()
     eq({ 'bytes', 2, 5, 0, 0, 0, 4, 0, 40, 0, 10, 10 }, api.nvim_get_var('qf_on_bytes'))
     eq({ 'lines', 2, 6, 0, 5, 1, 42 }, api.nvim_get_var('qf_on_lines'))
   end)
+
+  it('single-line visual block insert should not trigger extra on_lines #22009', function()
```
Comment (justinmk) [inline test/functional/lua/buffer_updates_spec.lua:453]: should this test be in `test/functional/api/buffer_updates_spec.lua` ? 

this test file is only for the lua-only parts of buffer updates.

Comment (glepnir) [reply test/functional/lua/buffer_updates_spec.lua:453]: I guess no .. see describe `describe('lua buffer event callbacks: on_lines', function()` the on_lines cb test case all in this block.

Comment (justinmk) [reply test/functional/lua/buffer_updates_spec.lua:453]: `on_lines` is just the lua variant of buffer update "lines" events...

**Comment by justinmk** [comment]
@glepnir mind backporting this?
