### PR TITLE
fix(lua): vim.region on linewise selection

### LINKED ISSUE #18155: `vim.region` doesn't account for linewise regtype
### Neovim version (nvim -v)

NVIM v0.7.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10 20H2 19044.1645

### Terminal name/version

Windows Terminal 1.12.10732.0

### $TERM environment variable

empty

### Installation

chocolatey

### How to reproduce the issue

```
nvim --clean
```

Edit the buffer so that it contains the two lines "abc" and "def"

```
:lua =vim.region(0, {0, 1}, {1, 1}, 'V', true)
```

### Expected behavior

The output `{{0, 3}, [0] = {0, -1}}` (the 3 is 3 rather than 2 because we passed in `true` for `inclusive`)

### Actual behavior

The output `{{0, 2}, [0] = {1, -1}}`

It seems like if we pass in the linewise regtype, `vim.region` should properly return every column for each line. This would be useful when implementing operators.

For example, I made a custom operator that marks a range of text to be swapped the first time you use it, then actually does the swap the second time. I'm been trying to use `vim.highlight.range` to leave a lasting highlight on the marked range, but linewise text objects like `ip` put the final `]` mark on the first rather than the last column of the last line. Similarly, linewise visual mode puts the final mark on the column the cursor ended on.

I was trying to figure out how `vim.highlight.on_yank` has the correct behavior even though it calls into `vim.highlight.range`, and it seems like that's because `op_yank_reg` in `ops.c` has special handling for `yank_type == kMTLineWise` before the `TextYankPost` autocmd is dispatched.

### PR DESCRIPTION
**Pull request by aayushoj**
This PR should close #18155

### CODE REVIEW

**Comment by clason** [comment]
Thanks, but please drop the binary files, and use conventional commit messages (`fix(lua): ...`).

File: runtime/lua/vim/_editor.lua [hunk 1]
```diff
@@ -548,6 +548,9 @@ function vim.region(bufnr, pos1, pos2, regtype, inclusive)
       else
         c2 = #bufline + 1
       end
+    elseif regtype:byte() == 86 then -- linewise selection, always return whole line
```
Comment (zeertzjq) [inline runtime/lua/vim/_editor.lua:551]:
```suggestion
    elseif regtype == 'V' then -- linewise selection, always return whole line
```

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/25132 is related but doesn't block this. If this is merged I'll revisit https://github.com/neovim/neovim/pull/25132 based on this.
