### PR TITLE
convert non-string errors using tostring()

### LINKED ISSUE #12045: non-string Lua errors in vim.loop callbacks cause segfault
- `nvim --version`: NVIM v0.4.3
- Operating system/version: Linux 5.5.10

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -c 'lua vim.loop.new_idle():start(function() error() end)'
```

Using `new_idle` to get a function to run in loop callback but also happens in other kinds of callbacks like pipe reads.

### Actual behaviour
Neovim terminated by SIGSEGV.

### Expected behaviour
Error logged as an error message?

### PR DESCRIPTION
**Pull request by bfredl**
fixes #12045

### CODE REVIEW

**Comment by clason** [comment]
@bfredl what is the status here? can this be salvaged for 0.11?

**Comment by bfredl** [comment]
Likely, unless this has already been covered by other PR since then

**Comment by bfredl** [comment]
it is no longer crashing since long, but it still would make sense to use `__tostring` consistently .

File: src/nvim/lua/executor.c [hunk 1]
```diff
@@ -125,30 +125,37 @@ lua_State *get_global_lstate(void)
...
-/// Convert lua error into a Vim error message
+/// get error on top of stack as a string
 ///
-/// @param  lstate  Lua interpreter state.
-/// @param[in]  msg  Message base, must contain one `%.*s`.
-void nlua_error(lua_State *const lstate, const char *const msg)
-  FUNC_ATTR_NONNULL_ALL
+/// Might alter the top value on stack in place (but doesn't change stack height)
+///
+/// "error" points to memory on the lua stack, use
```
Comment (justinmk) [inline src/nvim/lua/executor.c:132]: is "error" referring to the result of this function?
