### PR TITLE
fix(lsp): check if client is stopping before reusing

### LINKED ISSUE #33616: LSP: vim.lsp.start() can return shutting down client
### Problem

Stopping a language server and then calling `vim.lsp.start()` with the same name/root will return the old language server that's in the middle of shutting down. `vim.lsp.start()` won't return a new server until the old process has terminated.

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
local start_opts = { cmd = { 'npx', '-y', 'typescript-language-server', '--stdio' }, name = 'start-stop-test' }
local client1 = vim.lsp.start(start_opts)
vim.lsp.stop_client(client1)
local client2 = vim.lsp.start(start_opts)
print('these should be different', client1, client2)
```

### Expected behavior

I expect a new client with a new id. The old client is unusable even if the process is still technically still running.

### Nvim version (nvim -v)

0.11.0

### Language server name/version

any

### Operating system/version

any

### Log file

_No response_

### PR DESCRIPTION
**Pull request by moguls753**
Problem:
Stopping a language server and then calling `vim.lsp.start()` with the same name/root will return the old language server that's in the middle of shutting down. `vim.lsp.start()` won't return a new server until the old process has terminated.

Solution:
Introducing a client.is_stopping field that tracks the shutdown phase, preventing the client from being reused.

fixes https://github.com/neovim/neovim/issues/33616

### CODE REVIEW

File: runtime/lua/vim/lsp.lua [hunk 1]
```diff
@@ -727,7 +727,7 @@ function lsp.start(config, opts)
   end
 
   for _, client in pairs(all_clients) do
-    if reuse_client(client, config) then
+    if not client.is_stopping and reuse_client(client, config) then
```
Comment (justinmk) [inline runtime/lua/vim/lsp.lua:730]: does checking `client:is_stopped()` work instead? https://github.com/neovim/neovim/blob/03d378fda68fc5942660707cdd2314c0e12fb0a0/runtime/lua/vim/lsp/client.lua#L938-L939

if not, then `Client:is_stopped()` will need to be updated to check `is_stopping`, assuming that new field is actually needed.

Comment (justinmk) [reply runtime/lua/vim/lsp.lua:730]:
```suggestion
    if not client:is_stopped() and reuse_client(client, config) then
```

**Comment by justinmk** [comment]
thanks for looking at this, but at least 50% of the work is to add a test. https://github.com/neovim/neovim/issues/33616 gives a small set of steps that should be straightforward to add to a (correctly failing) test.

File: runtime/lua/vim/lsp/client.lua [hunk 2]
```diff
@@ -804,6 +804,7 @@ end
 ---
 --- @param force? boolean
 function Client:stop(force)
+  self.is_stopping = true
```
Comment (justinmk) [inline runtime/lua/vim/lsp/client.lua:807]: also, if this new field is added, surly this method should check it before continuing?

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (MariaSolOs) [inline runtime/lua/vim/lsp.lua:730]: Nit: It makes more sense to me to move the `client:is_stopped()` check inside `reuse_client`.

Comment (moguls753) [reply runtime/lua/vim/lsp.lua:730]: I added `is_stopping` because `client:is_stopped()` remains false until the Language Server actually closes—stop_client() only sends shutdown/exit and doesn’t shut down immediately. I’m pretty sure this is causing the issue.

Maybe its an idea to wrap it into the is_stopped function for clarity

```lua
function Client:is_stopped() 
   return self.rpc.is_closing() or client.is_stopping
```

**Comment by moguls753** [comment]
> thanks for looking at this, but at least 50% of the work is to add a test. #33616 gives a small set of steps that should be straightforward to add to a (correctly failing) test.

Thanks for the review and the help! This is only my second complexity:low PR, so I really appreciate the guidance. I’ll add a test  tomorrow—it’s getting late here.

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (justinmk) [reply runtime/lua/vim/lsp.lua:730]: > Maybe its an idea to wrap it into the is_stopped function for clarity

yes, review my comment above. We surely don't want a `client:is_stopped()` method that is missing this new field, that would be quite bad.

Comment (moguls753) [reply runtime/lua/vim/lsp.lua:730]: I’m not sure how to do that, since reuse_client can be passed in via opts.

```lua
function lsp.start(config, opts)
  opts = opts or {}
  local reuse_client = opts.reuse_client or reuse_client_default
```

Or am I missing something?

File: runtime/lua/vim/lsp/client.lua (hunk 2 above)
Comment (moguls753) [reply runtime/lua/vim/lsp/client.lua:807]: Right, maybe double stopping would not hurt, but its better for sure.

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (moguls753) [reply runtime/lua/vim/lsp.lua:730]: Ah yes, no I got you.

Comment (MariaSolOs) [reply runtime/lua/vim/lsp.lua:730]: `reuse_client` takes the client as the argument, so I would change the default implementation to something like:
```lua
local function reuse_client_default(client, config)
  if client:is_stopped() then return false end
  ...
end
```

Comment (moguls753) [reply runtime/lua/vim/lsp.lua:730]: Thanks for the suggestion! I see your point, but if someone provides their own `reuse_client()` callback via opts, this won’t work—`opts.reuse_client` would be called instead. I believe the cleanest approach is to stick with

```lua
if not client:is_stopped() and reuse_client(client, config) then
  ...
end
```

Comment (MariaSolOs) [reply runtime/lua/vim/lsp.lua]: If someone provides their own `reuse_client` then they can decide to use clients that are stopping. And so yes, your fix would only be included in the default implementation but I believe that the check should be there as it truly determines whether a client is reused.

File: runtime/lua/vim/lsp/client.lua [hunk 3]
```diff
@@ -387,6 +387,7 @@ function Client.create(config)
     capabilities = config.capabilities,
     workspace_folders = lsp._get_workspace_folders(config.workspace_folders or config.root_dir),
     root_dir = config.root_dir,
+    is_stopping = false,
```
Comment (justinmk) [inline runtime/lua/vim/lsp/client.lua:390]: `is_stopped()` is already a public method, don't need another public field. Ideally we wouldn't need this field at all, but I'm assuming there is no other way.
```suggestion
    _is_stopping = false,
```

File: runtime/lua/vim/lsp/client.lua [hunk 4]
```diff
@@ -387,6 +387,7 @@ function Client.create(config)
...
     _before_init_cb = config.before_init,
```
Comment (justinmk) [inline runtime/lua/vim/lsp/client.lua:391]: `is_stopped()` is already a public method, don't need another public field. Ideally we wouldn't need this field at all, but I'm assuming there is no other way.

also let's put it after `_before_init_cb` so that at least this part of the fields is sorted... 

```suggestion
    _is_stopping = false,
    _before_init_cb = config.before_init,
```

File: runtime/lua/vim/lsp/client.lua (hunk 3 above)
Comment (justinmk) [inline runtime/lua/vim/lsp/client.lua:390]: `is_stopped()` is already a public method, don't need another public field. Ideally we wouldn't need this field at all, but I'm assuming there is no other way.
```suggestion
    _is_stopping = false,
```

Comment (moguls753) [reply runtime/lua/vim/lsp/client.lua]: yes, makes sense thx.

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (moguls753) [reply runtime/lua/vim/lsp.lua]: Good point, I'll change that. Thank you!

File: runtime/lua/vim/lsp.lua [hunk 5]
```diff
@@ -148,6 +148,10 @@ end
 --- @param config vim.lsp.ClientConfig
 --- @return boolean
 local function reuse_client_default(client, config)
+  if client:is_stopped() then
+    return false
+  end
+
   if client.name ~= config.name then
```
Comment (justinmk) [inline runtime/lua/vim/lsp.lua:155]:
```suggestion
  if client.name ~= config.name or client:is_stopped() then
```

File: runtime/lua/vim/lsp/client.lua [hunk 6]
```diff
@@ -804,6 +805,11 @@ end
...
 --- @param force? boolean
 function Client:stop(force)
+  if self.is_stopping then
+    return
+  end
+  self.is_stopping = true
+
   local rpc = self.rpc
 
   if rpc.is_closing() then
```
Comment (justinmk) [inline runtime/lua/vim/lsp/client.lua:815]:
```suggestion
  if self.is_stopped() then
    ...
  end
  self.is_stopping = true
  local rpc = self.rpc
```

File: runtime/lua/vim/lsp/client.lua [hunk 7]
```diff
@@ -804,6 +805,10 @@ end
 ---
 --- @param force? boolean
 function Client:stop(force)
+  if self.is_stopped() then
+    return
+  end
+  self.is_stopping = true
   local rpc = self.rpc
 
   if rpc.is_closing() then
```
Comment (justinmk) [inline runtime/lua/vim/lsp/client.lua:814]: since is_stopped() checks both, we can simplify this code.

```suggestion
  if self.is_stopped() then
    return
  end
  
  self.is_stopping = true
  local rpc = self.rpc
```

Comment (moguls753) [reply runtime/lua/vim/lsp/client.lua]: Of course, thanks for the hints.

File: runtime/lua/vim/lsp/client.lua [hunk 8]
```diff
@@ -804,12 +805,13 @@ end
 ---
 --- @param force? boolean
 function Client:stop(force)
-  local rpc = self.rpc
-
-  if rpc.is_closing() then
+  if self:is_stopped() then
     return
   end
```
Comment (zeertzjq) [inline runtime/lua/vim/lsp/client.lua:810]: This condition doesn't look right. It contradicts the description above:
```
    By default, it will just request the server to shutdown without force. If
    you request to stop a client which has previously been requested to
    shutdown, it will automatically escalate and force shutdown.
```
