### PR TITLE
lsp: invoke vim.notify when client exits with code or signal other than 0

### LINKED ISSUE #12610: LSP: notify the user when the language server has crashed
- `nvim --version`: NVIM v0.5.0-583-g7b529e791 / LuaJIT 2.1.0-beta3
- language server name/version: efm-langserver (https://github.com/mattn/efm-langserver/commit/0b64dd8f71a63599c7ac0267c0c31d1c8497cc2c)
- Operating system/version: Linux Debian (Buster)

LSP log: https://gist.github.com/aktau/1c1ef881c0afb41d9808a821263ea1d7

### Steps to reproduce using `nvim -u NORC`

This basically applies to any language server that can crash. In my case it's due to https://github.com/mattn/efm-langserver/issues/57. A few times now when trying to resolve other issues with nvim-lsp I was confused because the language server had just crashed.

### Actual behaviour

When the language server crashes I get no notification that it happened, and am left to wonder why I get no diagnostics or anything else anymore.

### Expected behaviour

Either:

  1. A notification that the language server has crashed. Or,
  2. A notification that the language server has crashed (to allow filing bugs for the language server owner) followed by an automatic restart of the language server. (In my case, this would be preferable, but I'm not sure if this is the case for every language server. It could be a configurable option.)

It would be helpful (but not required), to add a note to the notification such that the user can file a better bug report (with logs) to the langserver.

### PR DESCRIPTION
**Pull request by mjlbach**
closes: #12610

@tjdevries you had assigned yourself but I wanted to do this since it came up when I was debugging a rust-analyzer crash. Should we notify on any exit? I just did non-zero exit codes for now.

### CODE REVIEW

**Comment by mjlbach** [comment]
This is weird, this occasionally prints the error code to stdout... I guess it has to do with timing of exit? 

```
❯ /usr/local/bin/nvim -u init.lua test.hbs
Client 1 crashed with exit code 15%
```

File: runtime/lua/vim/lsp.lua [hunk 1]
```diff
@@ -542,6 +542,12 @@ function lsp.start_client(config)
       client_ids[client_id] = nil
     end
 
+    if signal ~= 0 then
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp.lua:545]: Isn't this mixing up signal and exit code?

File: runtime/lua/vim/lsp.lua [hunk 2]
```diff
@@ -542,6 +542,12 @@ function lsp.start_client(config)
...
+      vim.schedule(function()
+        vim.notify(string.format("Client %s crashed with exit code %s", client_id, signal))
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp.lua:547]: Do you think it would make sense to set the log level to warn or even error ?

Comment (mjlbach) [reply runtime/lua/vim/lsp.lua]: I did now, but currently the behavior of anything but error is to print to :messages

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp.lua]: Is this better? I think it's good to inform on both signal and exit code (in case someone kills their server and wants to verify?)

Comment (mjlbach) [reply runtime/lua/vim/lsp.lua]: The exit code is 0 if you send sigterm to the language server

Comment (mjlbach) [reply runtime/lua/vim/lsp.lua]: image

Comment (mfussenegger) [reply runtime/lua/vim/lsp.lua]: Yes sorry, I  should've been more verbose.

I think the normal graceful exit case is signal 15 (sigterm) with exit code 0.
Currently the `or signal ~= 0` condition would lead to a notification in that scenario as well.  I don't think that's what a user wants.

Comment (mjlbach) [reply runtime/lua/vim/lsp.lua]: That makes sense. When you say normal graceful exit case, what are you referring to? When we send stop client, we don't use sigterm, we send a stop request to the server, so I believe in most cases  the signal should be 0 unless a user sends sigterm/kill from console

Comment (mfussenegger) [reply runtime/lua/vim/lsp.lua]: Okay. I was confused by the `0` and didn't know that it's the value returned by luv if the process exits by itself.

Otherwise `0` is kind of a ping signal. From the [kill manual](https://man.archlinux.org/man/kill.2)

> If sig is 0, then no signal is sent, but existence and permission checks are still performed


I'd still think of `15` / `SIGTERM` as a clean intended shutdown, but no strong opposition anymore :)

**Review by mfussenegger — APPROVED** [review]

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp.lua]: I think I agree-ish with your point, I'm inclined to merge as is because it's just a warning (I removed the language that your server crashed, changed it to quit) because it's still informative if the server didn't exit when we send the shutdown command. We can always change the behavior if people complain

Comment (mfussenegger) [reply runtime/lua/vim/lsp.lua]: > because it's still informative if the server didn't exit when we send the shutdown command

Agreed

> I removed the language that your server crashed, changed it to quit

Nice :+1:
