### PR TITLE
fix(statuscolumn): make %l/%r respect 'number'/'relativenumber'

### LINKED ISSUE #21745: statuscolumn respects `signcolumn` but not `number`/`nonumber`
### Describe the bug

The new `statuscolumn` feature respects the `signcolumn` option, and will omit signs if they are turned off even if `%s` is present in the format string.  However, it does not respect the `number`/`nonumber` option, so `%l` always renders the line number.  The behavior should be consistent one way or the other.

### Steps to reproduce

```vim
set statuscolumn=%l%s
set signcolumn=no
set nonumber
```

Result: Line numbers are displayed, but no signs
Expected: Neither are displayed

### Expected behavior

Line numbers should not be displayed with `nonumber`, just as signs are not displayed with `signcolumn=no`.  Alternatively, `statuscolumn` should consistently override/ignore both options.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-656+g93d99aefd

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux/Fedora 37

### Terminal name/version

Alacritty/master

### $TERM environment variable

alacritty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by luukvbaal**
Resolve https://github.com/neovim/neovim/issues/21745.

### CODE REVIEW

**Comment by lewis6991** [comment]
I think we should have a test for this.

**Review by lewis6991 — APPROVED** [review]

**Comment by luukvbaal** [comment]
Tests added.

File: test/functional/ui/statuscolumn_spec.lua [hunk 1]
```diff
@@ -111,6 +117,9 @@ describe('statuscolumn', function()
       16 12│aaaaa                                          |
                                                            |
     ]])
+    command([[set stc=%l%=%{&rnu?'\ ':''}%r│]])
+    screen:expect_unchanged()
+    command([[set stc=%{&nu?v:lnum:''}%=%{&rnu?'\ '.v:relnum:''}│]])
```
Comment (justinmk) [inline test/functional/ui/statuscolumn_spec.lua:122]: Thank you for looking for relevant existing tests to update. It's often counterproductive to add entirely new tests that differ very little from existing tests, especially if the tests are verbose.
