### PR TITLE
fix(highlight): let winhighlight use cursor

### LINKED ISSUE #18399: Cannot use `Cursor` with `'winhighlight'`
### Neovim version (nvim -v)

a1542b091dd7b919fa8524c1c909ef897dde9299

### Vim (not Nvim) behaves the same?

N/A, Neovim-only setting

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

From source

### How to reproduce the issue

`:set winhighlight=Cursor:Cursor`

### Expected behavior

You can use `Cursor` in `winhighlight`, since it is listed in `highlight-groups`:

image

image

### Actual behavior

image

NB: This is because `"Cursor"` does not appear as a value of `hlf_names` in `highlights_def.h`.

### PR DESCRIPTION
**Pull request by zbirenbaum**
Closes #18399 

Pretty simple fix, just added a highlight definition for Cursor  and `:set winhighlight=Cursor:Cursor` no longer shows an error

### CODE REVIEW

**Comment by zbirenbaum** [comment]
I'm a bit confused as to why so many build tests are failing. I checked a couple of them and it looks like the build fails outright, but I deleted my build folder and recompiled completely before I PR'd this with no errors

**Comment by clason** [comment]
No, it's actually a `functionaltest` that's failing: https://github.com/neovim/neovim/runs/6745692422?check_suite_focus=true#step:13:6960

(The CI output is confusing, unfortunately.)

**Comment by zbirenbaum** [comment]
> No, it's actually a functionaltest that's failing

Thank you! That clears things up a bit, I'll look into it and amend a fix

**Comment by bfredl** [comment]
I'd try add  HLF_CU at the end of the table (but before HLF_COUNT which is the sentinel), perhaps it will disturb the magic numbers in the test less.

**Comment by zbirenbaum** [comment]
> I'd try add HLF_CU at the end of the table (but before HLF_COUNT which is the sentinel), perhaps it will disturb the magic numbers in the test less.

That was my first thought as well, but it only goes up to 60 so the case still fails with 60!=64 when I put it at the very end.

**Comment by zeertzjq** [comment]
You probably messed up a rebase.

**Comment by zbirenbaum** [comment]
> You probably messed up a rebase.

Yeah I did, sorry about that

File: src/nvim/highlight_defs.h [hunk 1]
```diff
@@ -114,6 +114,7 @@ typedef enum {
   HLF_WBR,        // Window bars
   HLF_WBRNC,      // Window bars of not-current windows
   HLF_COUNT,      // MUST be the last one
```
Comment (zeertzjq) [inline src/nvim/highlight_defs.h:116]: Well, look at the comment

Comment (zbirenbaum) [reply src/nvim/highlight_defs.h:116]: Sorry, all I'm not sure I see the comment you are talking about.

Comment (zeertzjq) [reply src/nvim/highlight_defs.h:116]: `MUST be the last one`

Comment (zbirenbaum) [reply src/nvim/highlight_defs.h:116]: Sorry, I'm so dumb,  after messing up the rebase I just made the change manually quickly and forgot to make it second to last.

**Comment by zbirenbaum** [comment]
Ok, so the reason for that whole debacle was that it went from:
passing locally with no test case change -> passing locally with test case changed -> failing when rebased and pushed with the value that was expected before the change being passed in, then I messed up the 2nd rebase trying to revert and amend my testcase change lmao.

Anyways, looks like another commit I didn't have before fixed the issue somehow, so hopefully this should work now.

**Comment by zbirenbaum** [comment]
I don't believe the remaining failing cases are related to me, as they are in parser_spec and extmark_spec so this is probably good to be merged.
