### PR TITLE
fix(api): fix crash in command preview with %

### LINKED ISSUE #28851: SIGSEGV when adding a `%` to user-commands with `preview` and `complete = "file"` options.
### Problem

When the character `%` is added to the Ex command-line, and the command in the prompt is defined with the options `preview` and `complete = "file"` (via `nvim_create_user_command`), Neovim crashes with a memory error.

The crash happens only if the current buffer has a file. If `expand("%")` is empty it seems to work.

Sometimes it crashes with a `SIGSEGV` (with no error messages), and some other times it prints `E41: Out of memory!` and dies.

I found the issue with `complete = "file"`, but it also fails with `"dir"`. Other completions (like, `"help"`, `"syntax"`, or `"file_in_path"`) have no problems.

I tested multiple Neovim versions (Linux x86_64, from Nix and from the prebuilt packages in <https://github.com/neovim/neovim/releases>), and it seems that it is broken since 0.8 (when `preview` was added).

### Steps to reproduce

1. Create a user-command with `complete = "file"` and `preview`. The function for `preview` can be empty.

    ```lua
    local function callback()
    end

    local function preview()
        return 0
    end

    vim.api.nvim_create_user_command("TestCommand", callback, {
        nargs = "?",        -- or "*"
        complete = "file",  -- or "dir"
        preview = preview,
    })
    ```

1. Ensure that the current buffer has a file (so `expand("%")` is not empty).

    ```vim
    :e /tmp/testfile
    ```

1. Open the command-line and type the command with any argument without a `%`.

    The completion will work as expected.

    ```vim
    :TestCommand /tmp/<Tab>
    ```

1. Now, write a `%` in the command-line. Neovim crashes immediately.

    ```vim
    :TestCommand /tmp/%
    ```

The steps can be automated:

1. A Lua script to create the user-command, open a file, and simulate the `:TestCommand %` input:

    ```lua
    local function callback()
    end

    local function preview()
        return 0
    end

    vim.api.nvim_create_user_command("TestCommand", callback, {
        nargs = "?",        -- or "*"
        complete = "file",  -- or "dir"
        preview = preview,
    })



    vim.defer_fn(
        function()
            -- Open any file.
            vim.cmd.edit("/tmp/test" .. os.time())

            -- Type the command with a `%`.
            vim.api.nvim_feedkeys(":TestCommand %", "n", false)
        end,
        200
    )
    ```

2. Then, open Neovim with it:

    ```console
    $ nvim --clean -c 'so test-sigsegv.lua'
    ```

### Expected behavior

No crashes.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

This is exclusive to Neovim

### Operating system/version

Debian 12

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

Prebuilt packages and nixpkgs

### PR DESCRIPTION
**Pull request by glepnir**
Problem: parse_cmdline() sets eap->cmdlinep to address of local parameter, causing invalid memory access when expand_filename() tries to modify it. This leads to crashes when typing '%' in user commands with preview=true and complete=file.

Solution: Change parse_cmdline() signature to accept char **cmdline, allowing cmdlinep to point to caller's variable for safe reallocation.

Fix #28851

### CODE REVIEW

File: test/functional/api/command_spec.lua [hunk 1]
```diff
@@ -789,6 +789,25 @@ describe('nvim_create_user_command', function()
     ]])
     eq('hello 12', n.exec_capture('1,2Test2'))
   end)
+
+  it('does not crash with % in user command having preview and file completion #28851', function()
```
Comment (justinmk) [inline test/functional/api/command_spec.lua]: the user-defined preview tests live here: https://github.com/neovim/neovim/blob/67fede0fc94bff89bb266b649b8d0a57858622d1/test/functional/ui/inccommand_user_spec.lua#L236

Comment (justinmk) [inline test/functional/api/command_spec.lua]:
```suggestion
  it('no crash with % + preview + file completion #28851', function()
```

**Review by justinmk — APPROVED** [review]
Fix LGTM, nice catch. The test should be moved to `inccommand_user_spec.lua` though

File: test/functional/ui/inccommand_user_spec.lua [hunk 2]
```diff
@@ -664,4 +664,23 @@ describe("'inccommand' with multiple buffers", function()
       :Replace foo bar                        |
     ]])
   end)
+
+  it('no crash with % + preview + file completion #28851', function()
```
Comment (zeertzjq) [inline test/functional/ui/inccommand_user_spec.lua]: still wrong `describe()` block
