### PR TITLE
fix(lsp): don't treat MarkedString[] with language id as empty

### LINKED ISSUE #35516: #35423 treats all jdtls hover responses as "Empty hover response"
### Problem

On neovim 0.11.3 with eclpise java language server (jdtls), the hover ("K") works, but in the master branch, all hover requests result in `vim.notify("Empty hover response")` happening.

If I revert #35423 then hover works again. This change causes all jdtls hover responses to be treated as empty.

### Steps to reproduce

Create standalone `Example.java` using jdtls:
```java
/** doc comment */
public class Example {}
```

Press K on "Example".

The LSP requests and responses are the same for both versions, but all `jdtls` responses are now treated as empty:

```
neovim 0.11.3: (works)

[DEBUG][2025-08-27 16:41:30] ...m/lsp/client.lua:674	"LSP[jdtls]"	"client.request"	2	"textDocument/hover"	{ position = { character = 14, line = 1 }, textDocument = { uri = "file:///home/rmuir/hover_repro/Example.java" } }	<function 1>	1
[DEBUG][2025-08-27 16:41:30] .../vim/lsp/rpc.lua:277	"rpc.send"	{ id = 23, jsonrpc = "2.0", method = "textDocument/hover", params = { position = { character = 14, line = 1 }, textDocument = { uri = "file:///home/rmuir/hover_repro/Example.java" } } }
[DEBUG][2025-08-27 16:41:30] .../vim/lsp/rpc.lua:391	"rpc.receive"	{ id = 23, jsonrpc = "2.0", result = { contents = { { language = "java", value = "Example" }, "doc comment" } } }

neovim 0.12: "Empty hover response"

[DEBUG][2025-08-27 16:43:38] /usr/local/share/nvim/runtime/lua/vim/lsp/log.lua:151	"LSP[jdtls]"	"client.request"	2	"textDocument/hover"	{ position = { character = 14, line = 1 }, textDocument = { uri = "file:///home/rmuir/hover_repro/Example.java" } }	<function 1>	1
[DEBUG][2025-08-27 16:43:38] /usr/local/share/nvim/runtime/lua/vim/lsp/log.lua:151	"rpc.send"	{ id = 14, jsonrpc = "2.0", method = "textDocument/hover", params = { position = { character = 14, line = 1 }, textDocument = { uri = "file:///home/rmuir/hover_repro/Example.java" } } }
[DEBUG][2025-08-27 16:43:39] /usr/local/share/nvim/runtime/lua/vim/lsp/log.lua:151	"rpc.receive"	{ id = 14, jsonrpc = "2.0", result = { contents = { { language = "java", value = "Example" }, "doc comment" } } }
```

This reproducer could be substantially improved, but I'm hoping this problematic response is easier to turn into a test case than to instruct how to wrestle jdtls:
```lua
{ 
  id = 14, 
  jsonrpc = "2.0",
  result = { 
    contents = {
      { 
        language = "java", 
        value = "Example"
      },
      "doc comment"
    }
  }
}
```

### Expected behavior

Hover works again :)

### Nvim version (nvim -v)

v0.12.0-dev-1100+gc1e7ce9d79

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux 6.16.3

### Terminal name/version

ghostty

### $TERM environment variable

xterm-ghostty

### Installation

make

### PR DESCRIPTION
**Pull request by rmuir**
Problem:
Hover response of MarkedString[] where the first element contains a language identifier treated as empty.

Solution:
Fix empty check to handle case of MarkedString[] where the first element is a pair of a language and value.

Closes #35516

### CODE REVIEW

File: runtime/lua/vim/lsp/buf.lua [hunk 1]
```diff
@@ -72,7 +72,13 @@ function M.hover(config)
         if
           (
             type(result.contents) == 'table'
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/buf.lua:80]: This if condition is quite hard to follow at this point. Could we split it up into smaller/more readable blocks, or at least add a comment explaining each case that this condition checks for?

Comment (rmuir) [reply runtime/lua/vim/lsp/buf.lua:80]: I agree. I will give it a try, not a native lua speaker, went for the most conservative fix.

Comment (rmuir) [reply runtime/lua/vim/lsp/buf.lua:80]: Added comments to explain the 5 different datastructures at play here...

File: runtime/lua/vim/lsp/buf.lua [hunk 2]
```diff
@@ -69,11 +69,26 @@ function M.hover(config)
         lsp.log.error(err.code, err.message)
       elseif result and result.contents then
         -- Make sure the response is not empty
+        -- Five response shapes:
+        -- - MarkupContent: { kind="markdown", value="doc" }
+        -- - MarkedString-string: "doc"
+        -- - MarkedString-pair: { language="c", value="doc" }
+        -- - MarkedString[]-string: { "doc1", ... }
+        -- - MarkedString[]-pair: { { language="c", value="doc1" }, ... }
```
Comment (justinmk) [inline runtime/lua/vim/lsp/buf.lua:77]: This is a great comment!
