### PR TITLE
Revert "tui: improve support for tmux, GNU Screen"

### LINKED ISSUE #14298: starting neovim inside tmux 'types' the background string, seems related to PR #14094
- `nvim --version`: NVIM v0.5.0-dev+2c4e9c524
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: macOS Big Sur 11.2.3
- Terminal name/version: Kitty 0.19.3
- `$TERM`: tmux-256color
- tmux: 3.1c

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour

In my tmux `M-]` is bound to next window. If another window is open then it jumps to that window and the text `11;rgb:1b1b/2b2b/3333\` appears.

If another tmux window isn't open it will execute the text as neovim commands, like it was typed.

It looks like it has to do with PR #14094 . It's a tmux change and has to do with background colors. It also contains the string `"\x1b]11;?\x07"` which looks very similar to what happens. My current background color is `#1b2b33` which is also part of the text that is visible in the next window.

No problems when neovim is started in a shell without tmux running.

### Expected behaviour

Start neovim without anything happening.

### PR DESCRIPTION
**Pull request by ericonr**
This reverts commit c266c2f36ea56220268d2b19364e28815e338c2f.

This commit broke neovim under tmux, where it "types" the background
string as input to the terminal. Fixing this with neovim as-is requires
changing tmux keybindings or TERM settings, which has to be done by
every single user, therefore a fix should happen on neovim's side.

Fixes #14298

@erw7 if you can think of a solution that keeps the changes from that commit, that'd be awesome, but until then, IMHO it would be better to have neovim working for all users.

### CODE REVIEW

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -55,11 +55,7 @@
 #define STARTS_WITH(str, prefix) (strlen(str) >= (sizeof(prefix) - 1) \
     && 0 == memcmp((str), (prefix), sizeof(prefix) - 1))
 #define TMUX_WRAP(is_tmux, seq) ((is_tmux) \
-                                 ? DCS_STR "tmux;\x1b" seq STERM_STR : seq)
-#define SCREEN_TMUX_WRAP(is_screen, is_tmux, seq) \
-    ((is_screen) \
-     ? DCS_STR seq STERM_STR : (is_tmux) \
-     ? DCS_STR "tmux;\x1b" seq STERM_STR : seq)
+    ? "\x1bPtmux;\x1b" seq "\x1b\\" : seq)
```
Comment (janlazo) [inline src/nvim/tui/tui.c:58]:
```
  src/nvim/tui/tui.c:58:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 57  [whitespace/alignment] [2]
```

**Review by janlazo — CHANGES_REQUESTED** [review]
need separate commit for lint fix.
CI lint job mustn't fail.

File: src/nvim/tui/tui.c (hunk 1 above)
Comment (ericonr) [reply src/nvim/tui/tui.c]: I think it's fixed now? Can't find the CI result.

File: src/nvim/tui/tui.c [hunk 2]
```diff
@@ -54,12 +54,8 @@
 #define TOO_MANY_EVENTS 1000000
 #define STARTS_WITH(str, prefix) (strlen(str) >= (sizeof(prefix) - 1) \
     && 0 == memcmp((str), (prefix), sizeof(prefix) - 1))
```
Comment (janlazo) [inline src/nvim/tui/tui.c:56]:
```
  src/nvim/tui/tui.c:56:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 55  [whitespace/alignment] [2]
```

Comment (ericonr) [reply src/nvim/tui/tui.c]: Done.

File: src/nvim/tui/tui.c [hunk 3]
```diff
@@ -53,16 +53,16 @@
 
 #define TOO_MANY_EVENTS 1000000
 #define STARTS_WITH(str, prefix) (strlen(str) >= (sizeof(prefix) - 1) \
-    && 0 == memcmp((str), (prefix), sizeof(prefix) - 1))
-#define TMUX_WRAP(is_tmux, seq) ((is_tmux) \
-    ? "\x1bPtmux;\x1b" seq "\x1b\\" : seq)
+                    && 0 == memcmp((str), (prefix), sizeof(prefix) - 1))
```
Comment (janlazo) [inline src/nvim/tui/tui.c:56]: Should have `(strlen` to this line because moving `&&` in this column doesn't make sense. `src/clint.py` does not work well with macros.

Comment (ericonr) [reply src/nvim/tui/tui.c]: I kept the macro definition in two lines because otherwise it would be too long.

**Comment by janlazo** [comment]
@ericonr Thanks for entertaining my lint comments. Reverting a commit shouldn't require these fixes.
