### PR TITLE
fix(messages): proper multiline Lua print() messages

### LINKED ISSUE #21044: `print` should only send one `msg_show` event with `ext_messages`
### Feature already in Vim?

_No response_

### Feature description

Right now if you do something like the below, a separate `msg_show` event will be created for every line in the `print` output.

It would be better to get all the content in one `msg_show` event. This is already the case for most commands like `:ls`.

```lua
print(vim.inspect({a=1, b=2}))
```

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Separate message emitted for each newline present in Lua
          print() arguments.
Solution: Make msg_multiline() handle NUL bytes. Refactor print() to use
          msg_multiline(). Refactor vim.print() to use print().

Fix #21044

### CODE REVIEW

File: src/nvim/message.c [hunk 1]
```diff
@@ -249,35 +249,37 @@ bool msg(const char *s, const int hl_id)
   return msg_hl_keep(s, hl_id, false, false);
 }
 
-/// Similar to msg_outtrans, but support newlines and tabs.
-void msg_multiline(const char *s, int hl_id, bool check_int, bool hist, bool *need_clear)
+/// Similar to msg_outtrans_len, but support newlines and tabs.
+void msg_multiline(const char *str, int hl_id, bool check_int, bool hist, bool *need_clear, int len)
```
Comment (bfredl) [inline src/nvim/message.c:253]: Could change it to `String str`. Callers with unknown length can use `cstr_as_string`  (works without copy)

**Comment by przepompownia** [comment]
With this change I can remove the workaround used to reassemble multi-line output split into separate events - one per line.

**Review by justinmk — APPROVED** [review]
Beautiful
