### PR TITLE
fix(lsp): set_loclist should target current win

### LINKED ISSUE #14639: vim.lsp.util.set_loclist may store location entries for the wrong window
The function `vim.lsp.util.set_loclist` is currently implemented as follows:

https://github.com/neovim/neovim/blob/a282a177d3320db25fa8f854cbcdbe0bc6abde7f/runtime/lua/vim/lsp/util.lua#L1453-L1458

This implementation has a problem: it uses window ID `0` to set the location list for the current window. This can create issues when the location list was supposed to be populated for window A, but the current window is changed to window B.

To illustrate: imagine a whole bunch of diagnostics are published for buffer B1 in window W1. We're talking about maybe hundreds of diagnostics that take a few seconds to produce. What I've been seeing is that if you switch to e.g. buffer B2 in window W2, the location list would be set for that window; not W1.

In addition, if you already have the location list open, sometimes the location list ends up being empty. I suspect this is because NeoVim will open the location list for the location list, but you can't see that in NeoVim itself (as `:lope` doesn't do anything as you already have a location list open). This happens less often and is harder to reproduce, but I've run into it a few times at least.

To work around this, you have to use `bufwinnr()` or a similar function to get the window ID of the buffer, _before_ setting the location list. This way the location list should always be opened for the correct window. This means `set_loclist()` probably needs a window number as its argument, which the callers then derive from a buffer number.

Here's a little recording that shows what happens when you rely on window ID 0:

[asciicast](https://asciinema.org/a/4TGvRg6ihPUWEdn2h6YOEzBPK)

### PR DESCRIPTION
**Pull request by mjlbach**
Currently, for large number of diagnostics, the delay in populating loclist may be sufficient for a user to switch to another window, resulting in the loclist being populated on the wrong window.

Closes: #14639

@YorickPeterse please confirm this fixes your issue, I haven't tested.

### CODE REVIEW

File: runtime/lua/vim/lsp/diagnostic.lua [hunk 1]
```diff
@@ -1202,6 +1202,8 @@ function M.set_loclist(opts)
 
   local open_loclist = if_nil(opts.open_loclist, true)
 
+  local win_id = vim.api.nvim_get_current_win()
+
   local bufnr = vim.api.nvim_get_current_buf()
```
Comment (YorickPeterse) [inline runtime/lua/vim/lsp/diagnostic.lua:1207]: I think you can still have a race condition here, if somebody manages to switch windows between these two lines; assuming that's even possible.

Comment (mjlbach) [reply runtime/lua/vim/lsp/diagnostic.lua:1207]: Between what two lines? I don't see any race condition here.

Comment (YorickPeterse) [reply runtime/lua/vim/lsp/diagnostic.lua:1207]: @mjlbach Between these two:

```lua
local win_id = vim.api.nvim_get_current_win()

local bufnr = vim.api.nvim_get_current_buf()
```

I'm not sure if the user can actually do anything between running these two lines, but if they can (i.e. this runs in the background), the following could happen:

1. `local win_id = vim.api.nvim_get_current_win()` runs, produces window ID 1
2. The user switches to window 2
3. `local bufnr = vim.api.nvim_get_current_buf()` runs, producing the buffer ID for window 2; not window 1

The rest of the PR looks fine and works as far as I'm able to test.

Comment (mjlbach) [reply runtime/lua/vim/lsp/diagnostic.lua:1207]: This isn't handled in a callback, this is user-invoked so it will be fine. Thanks for the review.
