### PR TITLE
[RDY] api/buffer: introduce get/set_lines with more flexible out-of-bounds handling

### LINKED ISSUE #155: VIm incompatibility: Appending at last line of buffer fails in neovim
Beginning with a empty buffer, trying to add a new line under the first(empty) line, like this

    1| 
    2| test

by running

    :py import vim; vim.current.buffer.append("test", 1)

results in a "NvimError: Index out of bounds" in Neovim and has to be circumvented by calling

    :py import vim; vim.current.buffer.append("test")

This scenario works in just fine in regular Vim.

The workaround is to detect if you're appending at the last line of the buffer, however, that requires an additional msgrpc call to check the current buffer size, introducing a performance penalty.

### PR DESCRIPTION
**Pull request by bfredl**
Step one was to make things consistent with the vim python interface, so fixes neovim/python-client#155 and #4058 . Though that is probably too narrow an aim. We might to add a flag to toggle bound checking of the slice functions, to also accommodate languages with stricter range semantics.

The index handling is a confusing mixture of offset and element based indexing, with implementation arbitararily split between `[gs]et_slice` and two helper functions (not anyone's fault in particular, just a result of our fix-a-bug-at-a-time approach.) But it was not messier than the missing corner case could be inferred like so:

```
  include_start = include_start && (start < buf->b_ml.ml_line_count); // added
  start = normalize_index(buf, start) + (include_start ? 0 : 1);
  include_end = include_end || (end >= buf->b_ml.ml_line_count);
  end = normalize_index(buf, end) + (include_end ? 1 : 0);
```

Next step might be to try to simplify the implementation, or even so the API.  Do we really need to support both offset (0-based) and element (1-based) indexing at the API-level, as controlled by the include_start and include_end parameters ? This multiplies the different cases to support, and test, as highlighted by this missing corner case. The only limitation to use pure offset indexing (python-style) is that there is no numerical value for the index-past-the-end. Either we could have a magic value, like INT32_MAX to designate this index (leaks a implementation limit to the API, so a bit unclean) or we could use a slightly modified scheme, where -1 is the index-past-the-end and -2 is the last element etc (but this would make us different than anyone else, so still not 100% happy). IMHO even having a dedicated flag just for this position is cleaner than  `include_start`, but that is debatable.

Thoughts? Ideas?

### CODE REVIEW

**Comment by bfredl** [comment]
FWIW I implemented the "magic number" straw-man proposal [here](https://github.com/neovim/neovim/compare/master...bfredl:oobrange), including back-wards compatibility to see how the old representation maps to the new.

**Comment by bfredl** [comment]
I broke out the simplification (hopefully) of the implementation from the change of the API. Still you need to add an `strict_indexing` flag to the slice function to do this. Either we need `_ex` functions or we accept this breaking change for now (but if we're breaking, we could simplify the API anyway).

**Comment by justinmk** [comment]
Does this revert the changes in https://github.com/neovim/neovim/pull/2846 or just fix an edge case it missed?

In particular note the discussion here: https://github.com/neovim/neovim/pull/2846#discussion_r34417350

I haven't reviewed those PRs nor this one, but I'll mention that the general conclusion in the previous 2 times this has come up is:

- the neovim API does not _directly_ need to be Vim-compatible
- the `if_py` compat layer of course _does_ need to be Vim-compatible
- some previous users preferred "pythonic" behavior in the python client (_not_ the `if_py` compat layer)

How does this PR fit in with those concerns? cc @nhynes

**Comment by bfredl** [comment]
@justinmk As I said, I'm actually making this configurable with a strict_indexing flag to toggle between coercion (clamping to nearest valid index) or rasing an error. If we only intent to keep `buffer_[gs]et_range` as you suggested, the python client will set this flag to true or false as appropriate for each python-level operation, so no pythonisms in the generic API.

FTM I changed `buffer_get_line` to to be strict, as IMO that is the reasonable behaviour anyway, but that can be "reverted" just by changing this flag back to `false` in the wrapper.

**Comment by bfredl** [comment]
@justinmk And if you agree removing include_start/include_end is the way forward, what do you think of the "magic value" approach (latest commit), does it hurt too bad? (note that `next_index` is stateless and so can be done client-side, so no extra roundtrips here)

**Comment by bfredl** [comment]
Actually I start to like the second alternative (shift negative indicies) more. Viml already use this convention but only for end indicies (in `arr[start:end]`). It would be more convenient to support languages with an explicit `end` indexing mode like in julia: `buffer[a:end-b]` . Here the `end` operator could be implemented to just return `-1`.

File: src/nvim/api/buffer.c [hunk 1]
```diff
@@ -170,20 +192,34 @@ void buffer_set_line_slice(Buffer buffer,
                       ArrayOf(String) replacement,
                       Error *err)
 {
```
Comment (justinmk) [inline src/nvim/api/buffer.c]: This and the other functions that take `include_start`/`include_end` should be marked as deprecated. I guess doxygen has a marker for that, but also gcc/clang have an attribute... http://stackoverflow.com/a/12839666/152142

File: test/functional/api/buffer_spec.lua [hunk 2]
```diff
@@ -68,14 +69,16 @@ describe('buffer_* functions', function()
...
       eq({'a', 'b', 'c'}, curbuf('get_line_slice', 0, 2, true, true)) --sanity
 
       eq({'c'}, curbuf('get_line_slice', -1, 4, true, true))
       eq({'a', 'b', 'c'}, curbuf('get_line_slice', 0, 5, true, true))
-      eq(false, pcall(curbuf, 'set_line_slice', 4, 5, true, true, {'d'}))
-      eq(false, pcall(curbuf, 'set_line_slice', -4, -5, true, true, {'d'}))
+      curbuf('set_line_slice', 4, 5, true, true, {'d'})
+      eq({'a', 'b', 'c', 'd'}, curbuf('get_line_slice', 0, 5, true, true))
+      curbuf('set_line_slice', -4, -5, true, true, {'e'})
+      eq({'e', 'a', 'b', 'c', 'd'}, curbuf('get_line_slice', 0, 5, true, true))
```
Comment (justinmk) [inline test/functional/api/buffer_spec.lua]: Is there a test for strict indexing?

File: src/nvim/api/buffer.c [hunk 3]
```diff
@@ -170,20 +192,34 @@ void buffer_set_line_slice(Buffer buffer,
...
+  if (start < 0) start -= 1;
+  if (end < 0) end -= 1;
```
Comment (justinmk) [inline src/nvim/api/buffer.c]: This and the other cases should use `normalize_index` or a new similar private function.

**Comment by justinmk** [comment]
Normally I would try to avoid the `strict_indexing` flag, but in this case it allows us to move forward without having to answer many unknown questions correctly once and forever, so it's more than welcome a this point.

> Do we really need to support both offset (0-based) and element (1-based) indexing at the API-level, as controlled by the include_start and include_end parameters ? 

No we don't. Let's pick one (I would say zero-index).

> The only limitation to use pure offset indexing (python-style) is that there is no numerical value for the index-past-the-end. Either we could have a magic value, like INT32_MAX 

How about INT64_MAX.

File: src/nvim/api/buffer.c (hunk 1 above)
Comment (bfredl) [inline src/nvim/api/buffer.c]: doxygen would be better because it is the docs that an external client/plugin writer would read.

File: src/nvim/api/buffer.c (hunk 3 above)
Comment (bfredl) [inline src/nvim/api/buffer.c]: True that, this is just "demonstrate the possibility" commit.

File: test/functional/api/buffer_spec.lua (hunk 2 above)
Comment (bfredl) [inline test/functional/api/buffer_spec.lua]: No. Docs are also missing. Let's decide the API first :)

**Comment by bfredl** [comment]
True, as that is the largest value `Integer` allows, it's slightly less magic.

**Comment by justinmk** [comment]
@bfredl Are all your questions answered here or are you blocked by anything else?

**Comment by bfredl** [comment]
No it's fine. If you don't mind I will go for alternative 2 as it makes it easier for languages with explicit `end` indexing and at the same time it is not more complex for python-style languages (some special casing is needed in python for both alternatives).

**Comment by justinmk** [comment]
:+1: 

I think we should continue to explicitly mention "lines" in the function names. So, `buffer_set_lines` or `buffer_set_line_range` instead of `buffer_set_range`.

**Comment by bfredl** [comment]
Updated. I will add tests tomorrow.

**Comment by bfredl** [comment]
Copy converted the `{gs}et_line[_slice]` tests to tests for the new functions.

**Comment by bfredl** [comment]
Added deprecation notes, though those for `{gs}et_line_slice` might be more confusing than helpful. It is probably better to think "what was it I wanted to do, anyway?" and implement that using `{gs}et_lines`, or look at a concrete example (I will port python-client to use the new functions)

**Comment by bfredl** [comment]
See neovim/python-client#190

**Comment by bfredl** [comment]
Let's merge this. It is fully backwards compatible for now, but the following functions could be deprecated in the next release and  _eventually_ be removed:

```
buffer_get_line
buffer_set_line
buffer_del_line
buffer_insert
buffer_get_line_slice
buffer_set_line_slice
```

Yes I think we should deprecate the single line functions as @justinmk suggested (to nugde clients to use multi line operations whenever possible, rather than doing single line in a loop).

Removing them should probably wait a release or two, or until all actively developed/used rpc clients have upgraded.
See neovim/python-client#190 for an example of migrating.
