### PR TITLE
fix(treesitter): make foldexpr work without highlighting

### LINKED ISSUE #24150: treesitter fold not updated if treesitter hightlight is not active
### Problem

Treesitter folds are not updated correctly if `vim.treesitter.start()` is not used. This is because without activating treesitter highlight, nvim won't call `LanguageTree:parse()` on each update (as in https://github.com/neovim/neovim/blob/5ceb2238d3685255cd517ca87fd7edae9ed88811/runtime/lua/vim/treesitter/highlighter.lua#L317). 

Therefore, the foldexpr itself should call `LanguageTree:parse()` where appropriate if highlighting is not active. Another option would be to make a separate function for activating treesitter highlight, and to change `vim.treesitter.start` to do the minimal jobs required for treesitter-based functionalities to work correctly.

### Steps to reproduce

The following example demonstrates the necessity of `parse()` for foldepxr. Run nvim as follows:
```
nvim --clean -S <(tee << 'EOF'
    set fdc=1 fdm=expr fde=v:lua.vim.treesitter.foldexpr()
    setf lua
    call setline(1, ['function asdf()', '  return', 'end'])
    lua vim.treesitter.get_parser()
EOF
)
```
Despite that the buffer has a parser, folds are not updated:
image

### Expected behavior

If I manually run `parse()`, folds are updated correctly:
```
nvim --clean -S <(tee << 'EOF'
    set fdc=1 fdm=expr fde=v:lua.vim.treesitter.foldexpr()
    setf lua
    call setline(1, ['function asdf()', '  return', 'end'])
    lua vim.treesitter.get_parser():parse()
EOF
)
```
image

### Neovim version (nvim -v)

8182384205d3c222e999ea9a78276cbf685f50fd

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

ubuntu 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

tmux-256color

### Installation

built from the repository

### PR DESCRIPTION
**Pull request by tomtomjhj**
Fixes #24150

Problem: Treesitter fold is not updated if treesitter hightlight is not active. More precisely, updating folds requires `LanguageTree:parse()`.

Solution: Call `parse()` before computing folds. This won't introduce much additional cost, because
* if highlighting is active, it's likely that `TSHighlighter._on_buf` already ran `parse()`; and
* `on_bytes` calls `get_folds_levels()` only if new lines are added.

### CODE REVIEW

**Review by lewis6991 — APPROVED** [review]

**Comment by lewis6991** [comment]
Is it possible to add a test?

**Comment by tomtomjhj** [comment]
Updated the test not to run `parse()` manually, and modified `on_bytes` to trigger fold recomputation when lines are removed.

File: runtime/lua/vim/treesitter/_fold.lua [hunk 1]
```diff
@@ -283,10 +281,12 @@ local function on_bytes(bufnr, foldinfo, start_row, old_row, new_row)
...
-    foldinfo:add_range(start_row, end_row_new)
+  if new_row ~= old_row then
+    if new_row < old_row then
+      foldinfo:remove_range(end_row_new, end_row_old)
+    else
+      foldinfo:add_range(start_row, end_row_new)
+    end
     schedule_if_loaded(bufnr, function()
       get_folds_levels(bufnr, foldinfo, start_row, end_row_new)
       recompute_folds()
```
Comment (lewis6991) [inline runtime/lua/vim/treesitter/_fold.lua:292]: We still need to recompute folds when any edit is made.

**Review by lewis6991 — APPROVED** [review]

**Review by justinmk — APPROVED** [review]
Nicely done

**Comment by tomtomjhj** [comment]
https://github.com/neovim/neovim/actions/runs/5392035239/jobs/9789791486?pr=24167#step:12:8130
The CI failure looks irrelevant to this patch.
