### PR TITLE
fix(treesitter): consistent highlighting of multiline combined injection

### LINKED ISSUE #31777: Combined injections not entirely highlighted
### Problem

The treesitter highlighter fails to consider all text of a combined injection, even when it is visible on screen. Sometimes it will draw it correctly but the highlights go back to being incorrect on the next redraw(?)

### Steps to reproduce

minimal.lua:

```lua
vim.treesitter.query.set(
  'lua',
  'injections',
  [[((comment_content) @injection.content (#set! injection.self) (#set! injection.combined))]]
)

vim.api.nvim_buf_set_lines(0, 0, -1, false, {
  '-- print([[some',
  '-- text',
  '-- here]])',
})
vim.bo.ft = 'lua'
```

```sh
nvim --clean -u minimal.lua
```

Observe:
Image

Weird redrawing:
https://github.com/user-attachments/assets/8e845f91-29fe-46ae-a3bd-617e2d8387cd

### Expected behavior

In the above example, `here]]` should also have a string highlight, and the final closing parenthesis should have a bracket highlight. Instead they are not parsed as injections.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1422+g35247b00a4-dirty Build type: Debug LuaJIT 2.1.1734355927

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Linux 6.12.5 @ NixOS

### Terminal name/version

kitty 0.37.0

### $TERM environment variable

xterm-kitty

### Installation

Build from source

### PR DESCRIPTION
**Pull request by vanaigr**
See https://github.com/neovim/neovim/pull/32569#issuecomment-2677695941

The idea is to reapply previous (relevant) highlights of a highlight layer when drawing that layer on a new line.This way highlights from later layers will always appear in front of highlights from previous layers with the same priority.

The highlights are split on line boundaries so that the same multiline highlight is not added multiple times on each line. 

fix https://github.com/neovim/neovim/issues/31777

### CODE REVIEW

File: runtime/lua/vim/treesitter/highlighter.lua [hunk 1]
```diff
@@ -306,6 +310,33 @@ local function get_spell(capture_name)
...
+  local cur_begin_l = m.begin_line
+  local cur_begin_c = m.begin_col
+  if cur_begin_l < line then
+    cur_begin_l = line
+    cur_begin_c = 0
+  end
+
+  local cur_opts = m.opts
+  if cur_opts.end_line >= line + 1 then
+    cur_opts = vim.tbl_extend('error', {}, cur_opts)
```
Comment (MariaSolOs) [inline runtime/lua/vim/treesitter/highlighter.lua:327]: What exactly is this line for? Are you creating a copy of `cur_opts`?

Comment (vanaigr) [reply runtime/lua/vim/treesitter/highlighter.lua:327]: Yes. End position is clampled on the copy, but we may need to insert the original coordinates for clamping them to other lines.

Comment (MariaSolOs) [reply runtime/lua/vim/treesitter/highlighter.lua:327]: In that case could we use `vim.deepcopy`? It would make the code's intentions clearer.

**Comment by vanaigr** [comment]
The tests failed probably because of this PR: https://github.com/neovim/neovim/pull/32601

File: runtime/lua/vim/treesitter/highlighter.lua [hunk 2]
```diff
@@ -370,7 +407,9 @@ local function on_line_impl(self, buf, line, on_spell, on_conceal)
             conceal = conceal,
             spell = spell,
             url = url,
-          })
+          }
+          local mark = { begin_line = start_row, begin_col = start_col, opts = opts }
```
Comment (justinmk) [inline runtime/lua/vim/treesitter/highlighter.lua:411]: start/end are the normal convention in the codebase

```suggestion
          local mark = { start_line = start_row, start_col = start_col, opts = opts }
```

File: runtime/lua/vim/treesitter/highlighter.lua [hunk 3]
```diff
@@ -306,6 +310,33 @@ local function get_spell(capture_name)
   return nil, 0
 end
 
+---@param m MarkInfo
+---@param buf integer
+---@param line integer
+---@param next_marks MarkInfo[]
+local function add_mark(m, buf, line, next_marks)
```
Comment (justinmk) [inline runtime/lua/vim/treesitter/highlighter.lua:317]: is there a 1-line docstring that can give insight into what this does? E.g. "Sets a mark unless..."

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
I think we were ready to merge this, mind rebasing ?

**Comment by vanaigr** [comment]
rebased

**Comment by ribru17** [comment]
It looks like `prev_marks` keeps getting appended to without ever being cleared, is that the case? I think they should be cleared at some point, probably in `on_win` I guess?

Then I think this will be good to go, though it does seem hacky and ideally this would not be needed in the future

**Comment by ribru17** [comment]
(Ignore that, I think it's fine; they should only be created when preparing highlight states)

File: test/functional/treesitter/highlight_spec.lua [hunk 4]
```diff
@@ -550,24 +550,13 @@ describe('treesitter highlighting (C)', function()
...
-      {18:-- text}                                                          |
-      {18:-- here]])}                                                       |
+      {18:--}{26: random}                                                        |
+      {18:--}{26: text}                                                          |
+      {18:--}{26: here]]}{16:)}                                                       |
       ^                                                                 |
       {1:~                                                                }|*11
                                                                        |
     ]=])
-    -- NOTE: Once #31777 is fixed, this test case should be updated to the following:
```
Comment (justinmk) [inline test/functional/treesitter/highlight_spec.lua:560]: does this pr fix #31777 ? or is this no longer relevant ?

Comment (ribru17) [reply test/functional/treesitter/highlight_spec.lua:560]: It does fix it (I think)
