### PR TITLE
fix(extui): send FileType event after default extui options are set

### LINKED ISSUE #36314: vim._extui: some options are not set on FileType event
### Problem

I previously requested to expose a way to configure options for the extui filetypes in #33871. Between then and now there has been a regression. No option listed below set in `ftplugin/{cmd,dialog,msg,pager}.lua` for their respective buffers will take effect.

```lua
-- runtime/lua/vim/_extui/shared.lua:73
api.nvim_set_option_value('filetype', ft, { scope = 'local' })
local ignore = 'all' .. (type == 'pager' and ',-TextYankPost' or '')
api.nvim_set_option_value('eventignorewin', ignore, { scope = 'local' })
api.nvim_set_option_value('wrap', true, { scope = 'local' })
api.nvim_set_option_value('linebreak', false, { scope = 'local' })
api.nvim_set_option_value('smoothscroll', true, { scope = 'local' })
api.nvim_set_option_value('swapfile', false, { scope = 'local' })
api.nvim_set_option_value('modifiable', true, { scope = 'local' })
api.nvim_set_option_value('bufhidden', 'hide', { scope = 'local' })
api.nvim_set_option_value('buftype', 'nofile', { scope = 'local' })
if type ~= 'msg' then
  -- Use MsgArea and hide search highlighting in the cmdline window.
  local hl = 'Normal:MsgArea'
  hl = hl .. (type == 'cmd' and ',Search:MsgArea,CurSearch:MsgArea,IncSearch:MsgArea' or '')
  api.nvim_set_option_value('winhighlight', hl, { scope = 'local' })
end
```

Will bisect later.

### Steps to reproduce

`nvim --clean -c "lua require('vim._extui').enable({ enable = true })"`

With

```lua
-- ftplugin/{cmd,dialog,msg,pager}.lua
vim.cmd([[
    set linebreak
    set nosmoothscroll
    set nowrap
]])
```

### Expected behavior

Options set for extui are not overwritten.

### Nvim version (nvim -v)

v0.12.0-dev-095b9f98

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Debian 13 x86_64

### Terminal name/version

kitty 0.41.1

### $TERM environment variable

xterm-kitty

### Installation

bob-nvim

### PR DESCRIPTION
**Pull request by yilisharcs**
Problem: Setting a filetype before configuring default options for extui buffers prevents users from setting their own options.

Solution: Call nvim_set_option_value after defaults are set.

Closes #36314

### CODE REVIEW

**Comment by luukvbaal** [comment]
Thanks. This regressed with a commit intending to avoid firing OptionSet, which didn't even work work since that is not ignored by 'eventignorewin'.

File: test/functional/ui/messages2_spec.lua [hunk 1]
```diff
@@ -418,4 +419,23 @@ describe('messages2', function()
...
+    ]])
+    screen:expect([[
+                                                           |
+      {1:~                                                    }|*9
+      {3:─────────────────────────────────────────────────────}|
+      ^foofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofo|
+      {1:                                                     }|
+                                                           |
+    ]])
+    t.eq(n.eval('g:optionset'), 4) -- still fires for 'filetype'
```
Comment (justinmk) [inline test/functional/ui/messages2_spec.lua]:
```suggestion
    t.eq(4, n.eval('g:optionset')) -- still fires for 'filetype'
```

File: test/functional/ui/messages2_spec.lua [hunk 2]
```diff
@@ -418,4 +419,23 @@ describe('messages2', function()
                                                            |
     ]])
   end)
+
+  it('FileType is fired after default options are set', function()
+    n.exec([[
+      let g:optionset = 0
+      au FileType pager set nowrap
+      au OptionSet * let g:optionset += 1
```
Comment (justinmk) [inline test/functional/ui/messages2_spec.lua]: for extra visibility is it worth tracking the option name? kind of curious which (4...) options are being set. 

```suggestion
      let g:optionset = ''
      au FileType pager set nowrap
      au OptionSet * let g:optionset ..= expand('<amatch>') .. ','
```

File: test/functional/ui/messages2_spec.lua [hunk 3]
```diff
@@ -418,4 +419,23 @@ describe('messages2', function()
                                                            |
     ]])
   end)
+
+  it('FileType is fired after default options are set', function()
+    n.exec([[
+      let g:optionset = 0
+      au FileType pager set nowrap
```
Comment (justinmk) [inline test/functional/ui/messages2_spec.lua:426]: this does not have `++nested` so the `set nowrap` itself will not trigger OptionSet, right? a bit confusing given the test context.

Comment (luukvbaal) [reply test/functional/ui/messages2_spec.lua:426]: That's right. This here simulates a user config which may or may not fire it, indeed depending on `++nested`. Not sure that matters; we're trying to prevent extui from firing `OptionSet`, it just so happens to fire for the `FileType` autocommand.

File: test/functional/ui/messages2_spec.lua (hunk 2 above)
Comment (luukvbaal) [reply test/functional/ui/messages2_spec.lua]: It fires for 'filetype', like the comment below mentions.

File: test/functional/ui/messages2_spec.lua (hunk 3 above)
Comment (justinmk) [reply test/functional/ui/messages2_spec.lua:426]: I know, but still all of this is not obvious and I'm thinking about future people that look at this test.
