### PR TITLE
fix(lsp): check filetype registry in health

### LINKED ISSUE #38082: checkhealth vim.lsp: false warnings for filetypes from vim.filetype.add
## Problem

`checkhealth vim.lsp` warns about "Unknown filetype" for filetypes that Neovim can detect and assign, including built-in ones from `filetype.lua`.

## Steps to reproduce

```console
nvim --clean --noplugin +'lua vim.filetype.add({extension={mdx="mdx"}}) vim.lsp.config("test",{cmd={"true"},filetypes={"mdx"}}) vim.lsp.enable("test")' +'checkhealth vim.lsp'
```

Output:

`⚠️ WARNING Unknown filetype 'mdx'`

## Expected behavior

The healthcheck should recognize filetypes from the Lua filetype registry.

Could depend on #38081 (exposing registered filetypes via a public API), which would give the healthcheck the correct data source and extingu9ish the warning.

I'm also happy to open a PR for this if y'all deem this a legitimate issue.

### PR DESCRIPTION
**Pull request by barrettruth**
## Problem

Improve handling of the bothersome `Unknown filetype` healthcheck warnings most commonly seen on slightly unusual filetypes registered by valid LSP configs, built-in registry-only filetypes like `beancount` and user-defined entries added with `vim.filetype.add()`.

Limitations discussed in #38082 and #38081 (namely this *not* fixing the lack of a single exhaustive filetype list), and enabled by #38831.

Fixes #38082.

## Solution

Combine the following two sources available here:

- `getcompletion('', 'filetype')` (keep the original approach)
- `vim.filetype.inspect()` (also include these filetype names)

I also added two tests:

1. no warning for the built-in registry-only filetype `beancount`
2. no warning for a custom `mdx` filetype added via `vim.filetype.add()`

For example, the filetype `hbs` still warns, so extension names are not treated as valid filetypes.

### CODE REVIEW

File: test/functional/plugin/health_spec.lua [hunk 1]
```diff
@@ -107,6 +107,43 @@ describe(':checkhealth', function()
     command('checkhealth vim.provider')
     eq(nil, string.match(curbuf_contents(), 'WRONG!!!'))
   end)
+
+  it('vim.lsp does not warn for filetypes from the filetype registry', function()
```
Comment (justinmk) [inline test/functional/plugin/health_spec.lua]: nit: could combine the tests
```suggestion
  it('vim.lsp warns about unknown filetypes', function()
```

**Review by justinmk — APPROVED** [review]
Nice, thanks @barrettruth ! LGTM after lint fix.

File: test/functional/plugin/health_spec.lua (hunk 1 above)
Comment (barrettruth) [reply test/functional/plugin/health_spec.lua]: combined and test renamed
