### PR TITLE
vim-patch:8.2.3677: after a put the '] mark is on the last byte

### LINKED ISSUE #9047: Different values assigned to '] and '> marks when performing the same operations on multibyte text
### Steps to reproduce

Run this from command line:

`vim --clean --cmd "1 s/^/тест/" --cmd ":norm diwp" --cmd ":norm viwdp" --cmd ":marks"`.

Here is the output:

Снимок экрана 2021-10-26 в 17 51 24

Marks `']` and `'>` are pointing to the different positions (Mark `']` points to byte 7, mark `'>` points to byte 6).

This does not happens when Latin text is used. For example (both pointing to column 3): 

`nvim --clean  --cmd "1 s/^/test/" --cmd ":norm diwp" --cmd ":norm viwdp" --cmd ":marks"`:

Снимок экрана 2021-10-26 в 17 54 29

### Expected behaviour

Marks `']` and `'>` should point to the same position.

### Operating system

macOS Monterey

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct  1 2021 22:47:36)

### Logs and stack traces

_No response_

### LINKED ISSUE #16148: Different values assigned to '] and '> marks when performing the same operations on multibyte text
### Neovim version (nvim -v)

NVIM v0.6.0-dev+498-gd0f10a7ad

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

macOS 11.6

### Terminal name/version

iTerm2 

### $TERM environment variable

xterm-256colors

### Installation

homebrew

### How to reproduce the issue

`nvim --clean --cmd "set termguicolors" --cmd "1 s/^/тест/" --cmd ":norm diwp" --cmd ":norm viwdp" --cmd ":marks"`

### Expected behavior

Marks `']` and `'>` should point to the same position.

### Actual behavior

Mark `']` points to byte 7, mark `'>` points to byte 6:

Снимок экрана 2021-10-26 в 00 21 16

This does not happen if you are editing Latin text. For example (both pointing to column 3): 
`nvim --clean --cmd "set termguicolors" --cmd "1 s/^/test/" --cmd ":norm diwp" --cmd ":norm viwdp" --cmd ":marks"`

Снимок экрана 2021-10-26 в 00 21 47

### PR DESCRIPTION
**Pull request by clason**
Problem:    After a put the '] mark is on the last byte of a multi-byte
            character.
Solution:   Move it to the first byte. (closes vim/vim#9047)
https://github.com/vim/vim/commit/4d07253a485819b3a9fd923d263e722ea2109c12

closes #16148

### CODE REVIEW

**Comment by clason** [comment]
The two new `']` tests are failing (`[x,x,9,x]` instead of expected `[x,x,7,x]`); probably needs earlier patches so I'm shelving this for now. (Although suggestions welcome.)

**Comment by zeertzjq** [comment]
The test seems to pass if `mb_head_off` is changed to `utf_head_off`.

File: src/nvim/ops.c [hunk 1]
```diff
@@ -3386,6 +3387,10 @@ void do_put(int regname, yankreg_T *reg, int dir, long count, int flags)
           }
           STRMOVE(ptr, oldp + col);
           ml_replace(lnum, newp, false);
+
+          // compute the byte offset for the last character
+          first_byte_off = mb_head_off(newp, ptr - 1);
```
Comment (zeertzjq) [inline src/nvim/ops.c:3392]:
```suggestion
          first_byte_off = utf_head_off(newp, ptr - 1);
```

File: src/nvim/ops.c [hunk 2]
```diff
@@ -3520,12 +3530,13 @@ void do_put(int regname, yankreg_T *reg, int dir, long count, int flags)
...
 
-      // put '] mark at last inserted character
+      // Put the '] mark on the first byte of the last inserted character.
+      // Correct the length for change in indent.
       curbuf->b_op_end.lnum = lnum;
-      // correct length for change in indent
       col = (colnr_T)STRLEN(y_array[y_size - 1]) - lendiff;
       if (col > 1) {
-        curbuf->b_op_end.col = col - 1;
+        curbuf->b_op_end.col = col - 1 - mb_head_off(y_array[y_size - 1],
```
Comment (zeertzjq) [inline src/nvim/ops.c:3538]:
```suggestion
        curbuf->b_op_end.col = col - 1 - utf_head_off(y_array[y_size - 1],
```

**Review by zeertzjq — COMMENTED** [review]
Nvim also has a `mb_head_off`, but it is only used in Lua and was only introduced recently in <https://github.com/neovim/neovim/commit/2230b578d1d36728d156f82fb0e1a44c1f810b8c>, and it returns a negative number.

File: src/nvim/ops.c (hunk 1 above)
Comment (clason) [reply src/nvim/ops.c]: Thank you! I've had trouble with commit suggestions in PRs generated via `vim-patch.sh`, so I made those changes manually.

**Review by zeertzjq — APPROVED** [review]

**Comment by zeertzjq** [comment]
@clason I didn't notice the indent in the test was wrong until today. I opened #16802 to fix this.
