### PR TITLE
fix(lsp): avoid attaching to unloaded buffers

### LINKED ISSUE #16249: lsp: rust analyzer panicks with "bad range" if syntax enable explicitly set
### Description

Seems like extending a source file beyond its original length causes rust_analyzer to panic when trying to get completion

### Neovim version

```
NVIM v0.6.0-dev+557-g5ce35abae
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -march=native -mtune=native -O2 -pipe -fcommon -U_FORTIFY_SOURCE -fno-semantic-interposition -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-git/src/build/config -I/build/neovim-git/src/neovim-git/src -I/usr/include -I/build/neovim-git/src/build/src/nvim/auto -I/build/neovim-git/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Nvim-lspconfig version

6224c54a9945a52bf43a8bc1a42a112084590c0b

### Affected language servers

rust_analyzer

### Steps to reproduce

1. Create a rust file
2. Add content to it
3. Attempt completion at a position beyond its original length

### Actual behavior

rust_analyzer panics.

Comparing the behavior a minimal config had and my config had, for some reason when using my config, no `didChange` notification is sent to the server.

### Expected behavior

_No response_

### Minimal config

I was unable to reproduce this on a minimal config.

### Health check

lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: ccls: configuration checked.
  - INFO: rust_analyzer: configuration checked.

### LSP log

https://gist.github.com/yshui/02b430e836889182d01529e3c9ea1b83

### LINKED ISSUE #16297: LSP `contentChanged` updates not sent if `filetypedetect` triggered during before loading buffer
### Neovim version (nvim -v)

0.5.1

### Language server name/version

all

### Operating system/version

Arch Linux

### :checkhealth

_No response_

### Steps to reproduce using "nvim -u minimal_init.lua"

I prepared a [testcase](https://github.com/Isopod/nvim-lsp-testcase) just for this issue. Detailed instructions are in the README.

#### init.vim
```
packadd nvim-lspconfig
lua require'lspconfig'.dummy.setup{}
syntax on
```

You can use any language server of your choice (substitute `dummy` accordingly). Feel free to use the minimal [`dummyls.py`](https://github.com/Isopod/nvim-lsp-testcase/blob/master/dummyls.py) from my repository.

#### Actions
- Open a file supported by the language server and modify the buffer. 
- Observe the messages sent by Neovim. (You can do this either by checking `lsp.log`, or, if you use my dummy language server, check the output of `transcript.txt` in the current directory.)
- Notice that no updates are being sent (but initialization, shutdown and other messages *are* sent)

#### Observations
- The critical line is `syntax on` in `init.vim`. If it is *not* present, then updates work.
- The issue *cannot* be reproduced if there is a mode line in the file specifying the type, e.g. `# vim:et ft=dummy`
- I bisected and discovered that the bug started with commit 519848f64eda3aacb6d2ceac63c3b52c9ff0c59b.

I hope this is clear. I'm sorry if it is a bit messy, I reduced it as best I could. It took me several days to find out the exact circumstances under which it could be reproduced.

### Expected behavior

When the buffer content is changed, `contentChanged` updates should be sent to the language server.

### Actual behavior

`contentChanged` updates are not sent. As a result, features like code completion do not work.

### Log file

_No response_

### LINKED ISSUE #16562: Client handlers break when loading and immediately attaching to buffer
### Neovim version (nvim -v)

NVIM v0.7.0-dev+683-gafaad8b54

### Language server name/version

pylsp v1.3.2 (but not relevant to issue)

### Operating system/version

macOS 12.0.1

### :checkhealth

```markdown
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: sumneko_lua: configuration checked.
  - INFO: denols: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: pylsp: configuration checked.
```

### Steps to reproduce using "nvim -u minimal_init.lua"

All that's needed is the following config:

```lua
-- minimal_init.lua
vim.lsp.set_log_level("trace")

-- cmd should correspond to an installed server but is otherwise irrelevant
local client_id = vim.lsp.start_client({ cmd = { "pylsp" } }) 
vim.lsp.buf_attach_client(vim.api.nvim_get_current_buf(), client_id)
```

Then, open Neovim with `nvim --clean -u minimal_init.lua test.py` (the filename is irrelevant).

### Expected behavior

The client sends notifications on buffer events (e.g. `textDocument/didChange` on change). 

### Actual behavior

The client sends a `textDocument/didOpen` notification but does not send any further notifications on events. 

I think the issue is that the buffer is not yet loaded when `vim.lsp.buf_attach_client` is called, so [`vim.api.nvim_buf_attach`](https://github.com/neovim/neovim/blob/9b65a7e06438c3b407ad7136a30c0a5281f2174f/runtime/lua/vim/lsp.lua#L1173) fails and returns `false`. However, that return value isn't checked, so the attach process fails silently (which can affect subsequent servers, too, since the client is under the impression that the buffer is already attached). 

There's a couple of simple solutions on the user / plugin side, like using an autocommand that fires after the buffer is loaded or deferring `vim.lsp.buf_attach_client`, but I wonder if there's a way to at least indicate that the process failed in this case (and ideally avoid breaking other servers). 

### Log file

https://gist.github.com/jose-elias-alvarez/0c2e46f2db52a3dee2afca3ccceca7d8

### PR DESCRIPTION
**Pull request by mjlbach**
Closes neovim#16562 
Closes neovim#16249 
Closes neovim#16297

* buf_attach_client can be called on an unloaded buffer
* on_attach will prematurely fail, while the language server client
  tracks this buffer as attached
* The language server client will track this buffer as attached despite
  textDocument/didChange notifications not being sent to the server
* Instead, check if the buffer is loaded and return early, warning via
  the lsp logger that buf_attach_client was called on an invalid buffer

### CODE REVIEW

File: runtime/lua/vim/lsp.lua [hunk 1]
```diff
@@ -1156,6 +1156,12 @@ function lsp.buf_attach_client(bufnr, client_id)
     client_id = {client_id, 'n'};
   }
   bufnr = resolve_bufnr(bufnr)
+  if not vim.api.nvim_buf_is_loaded(bufnr) then
+    local _ = log.warn() and log.warn(
+      string.format("buf_attach_client called on unloaded buffer (id: %d): ", bufnr)
+    )
+    return
```
Comment (gpanders) [inline runtime/lua/vim/lsp.lua:1163]: Since the function returns `true` on success do you want to make this return `false` on failure to keep the return type consistent?

**Review by gpanders — APPROVED** [review]

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp.lua:1163]: I thought about it but I think conventionally we return nil on failure (although this is a loose convention). Most people shouldn't be explicitly checking false anyways?

**Comment by evanrittenhouse** [comment]
Hi - I'm still getting this issue using @mfussenegger's `nvim-jdtls` plugin. The logs mention attaching to an unloaded buffer, which is then solved by using `vim.lsp_buf_attach_client(1, 1)`.  I can provide configuration as needed - my company has a variety of internal tools, so I'm using custom logic to determine the `root_dir`, among other things, but I wait to call the `attach` until after that's calculated. If this is better suited as an issue in the `nvim-jdtls` repo, please let me know.

Thanks!
