### PR TITLE
fix(folds): cursorline highlight is not always applied on closed folds

### LINKED ISSUE #22232: CursorLineNr highlight disappears when moving up through folds
### Describe the bug

When using a the statuscolumn option and moving up the buffer line by line over folded text, the CursorLineNr highlight disappears. See the GIF below for an example.

statuscol_fold

### Steps to reproduce

I can reproduce this with `o.statuscolumn = "%{v:relnum? v:relnum:v:lnum}"`.

### Expected behavior

The expected behavior is that the CursorLineNr highlight would not disappear when moving across folded text.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-934+g9668c166e, 

### Vim (not Nvim) behaves the same?

No, statuscolumn is not a vim feature

### Operating system/version

Linux 6.1.9-arch1-2

### Terminal name/version

xterm 378

### $TERM environment variable

xterm-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:    The cursorline highlight logic checks for `w_cursor.lnum`
            which may be different from the line number passed to
            `win_line()` even when the cursor is actually on that line.
Solution:   Update cursor line highlight logic to check for the line
            number of the start of a closed fold if necessary.

Fix https://github.com/neovim/neovim/issues/22232

### CODE REVIEW

**Comment by luukvbaal** [comment]
I'm not sure if this should be submitted to vim first. Vim doesn't have the `CursorLineFold` highlight group and as such, the `Folded` highlight group takes precedence over `CursorLine` there. Hence the problem described in https://github.com/neovim/neovim/issues/22232 does not apply to vim. `w_cursor.lnum` is still technically incorrect in vim as well though.

**Comment by luukvbaal** [comment]
The problem described in https://github.com/neovim/neovim/issues/22232#issuecomment-1427049553 is different and unfixed by this PR (as of yet). I suppose it would be fixed by calling `foldAdjustCursor()` in the function that closes a fold. What is the strategy here? Is `w_cursor.lnum` intentionally left outdated/inaccurate since it doesn't really matter in most cases? It turns out it does matter for `'cursorline'`, does it make sense to solve this and similar problems(idk if there are any others)?

**Comment by luukvbaal** [comment]
Am I missing something or is the existing `CursorLineFold` test not actually testing for it properly? https://github.com/neovim/neovim/blob/5d3769ea2343a30c60963011bef85346320bd97c/test/functional/ui/fold_spec.lua#L92-L118

There are no folded lines in the screen test because the the <kbd>zf3j</kbd> is done with the cursor already at botline. This would fix the test I think?
```diff
@@ -93,7 +93,7 @@ describe("folded lines", function()
       command("set cursorline foldcolumn=2 foldmethod=marker")
       command("hi link CursorLineFold Search")
       insert(content1)
-      feed("zf3j")
+      feed("ggzf3j")
       if multigrid then
         screen:expect([[
         ## grid 1
```

**Comment by luukvbaal** [comment]
Updated to fix([I think](https://github.com/neovim/neovim/pull/22242#issuecomment-1427171058)) and reuse the existing cursorline fold test, as well as fixing the issue described in https://github.com/neovim/neovim/pull/22242#issuecomment-1427163734.

**Comment by luukvbaal** [comment]
> Is w_cursor.lnum intentionally left outdated/inaccurate since it doesn't really matter in most cases?

OK so RE the above and the failings oldtests they could be fixed by testing for 2 instead of 4 and that would still confirm that what it is testing for works as expected. 

However I suppose that by adding a `foldAdjustCursor()` to `setManualFoldWin()`, we do lose the hysteresis nature of a closed fold. I.e. closing and opening a fold without further moving the cursor currently keeps the cursor on the same line when the fold is opened again. 

That would no longer be the case with this change, instead placing the cursor on the first line of the fold. Is that an acceptable change in behavior for accurately applying the cursorline highlight?

**Comment by luukvbaal** [comment]
Updated logic to check for the start of a closed fold if necessary without actually changing `w_cursor.lnum`, and added more tests.

**Comment by luukvbaal** [comment]
@gpanders do you want to review the test change? Seems like you [added](https://github.com/neovim/neovim/commit/ed35e20640ca1d5412550a2df5930b090acee57c) it but I think it was [erroneous](https://github.com/neovim/neovim/pull/22242#issuecomment-1427171058).

**Comment by gpanders** [comment]
Looks good to me at a quick glance. Good catch.

File: src/nvim/buffer_defs.h [hunk 1]
```diff
@@ -1126,6 +1126,9 @@ struct window_S {
                                     // time through cursupdate() to the
                                     // current virtual column
 
+  linenr_T w_cursorline;            ///< Where 'cursorline' should be drawn,
+                                    ///  can be different from w_cursor.lnum
+                                    ///  for closed folds.
```
Comment (zeertzjq) [inline src/nvim/buffer_defs.h:1131]:
```suggestion
                                    ///< can be different from w_cursor.lnum
                                    ///< for closed folds.
```
There was also a mistake in the code above:
```diff
diff --git a/src/nvim/buffer_defs.h b/src/nvim/buffer_defs.h
index 3601dc706..6669e2303 100644
--- a/src/nvim/buffer_defs.h
+++ b/src/nvim/buffer_defs.h
@@ -1112,7 +1112,7 @@ struct window_S {
   win_T *w_prev;              ///< link to previous window
   win_T *w_next;              ///< link to next window
   bool w_closing;                   ///< window is being closed, don't let
-                                    ///  autocommands close it too.
+                                    ///< autocommands close it too.
 
   frame_T *w_frame;             ///< frame containing this window
 
```

File: src/nvim/drawscreen.c [hunk 2]
```diff
@@ -1849,9 +1854,9 @@ static void win_update(win_T *wp, DecorProviders *providers)
 
   // Now that the window has been redrawn with the old and new cursor line,
   // update w_last_cursorline.
-  wp->w_last_cursorline = cursorline_standout ? wp->w_cursor.lnum : 0;
+  wp->w_last_cursorline = cursorline_standout ? wp->w_cursorline : 0;
 
-  wp->w_last_cursor_lnum_rnu = wp->w_p_rnu ? wp->w_cursor.lnum : 0;
+  wp->w_last_cursor_lnum_rnu = wp->w_p_rnu ? wp->w_cursorline : 0;
```
Comment (zeertzjq) [inline src/nvim/drawscreen.c:1859]: I think this change is also needed above:
```diff
diff --git a/src/nvim/drawscreen.c b/src/nvim/drawscreen.c
index 814d44303..c96c0ee9c 100644
--- a/src/nvim/drawscreen.c
+++ b/src/nvim/drawscreen.c
@@ -1815,7 +1815,7 @@ static void win_update(win_T *wp, DecorProviders *providers)
       idx++;
       lnum += foldinfo.fi_lines + 1;
     } else {
-      if (wp->w_p_rnu && wp->w_last_cursor_lnum_rnu != wp->w_cursor.lnum) {
+      if (wp->w_p_rnu && wp->w_last_cursor_lnum_rnu != wp->w_cursorline) {
         // 'relativenumber' set and cursor moved vertically: The
         // text doesn't need to be drawn, but the number column does.
         foldinfo_T info = fold_info(wp, lnum);
```

File: src/nvim/drawscreen.c [hunk 3]
```diff
@@ -1549,6 +1549,11 @@ static void win_update(win_T *wp, DecorProviders *providers)
   }
 
   bool cursorline_standout = win_cursorline_standout(wp);
+  // Make sure that the cursorline on a closed fold is redrawn
+  if (cursorline_standout) {
```
Comment (zeertzjq) [inline src/nvim/drawscreen.c:1553]: This calculation is only needed for cursorline, not for conceal.
```suggestion
  if (wp->w_p_cul) {
```

File: src/nvim/drawscreen.c (hunk 2 above)
Comment (zeertzjq) [inline src/nvim/drawscreen.c:1859]: I don't think this change is correct. If 'cursorline' has been enabled and then disabled, `w_cursorline` will be an incorrect value.

Comment (luukvbaal) [reply src/nvim/drawscreen.c:1859]: It fixed an issue for which I thought I added a test but it doesn't currently fail. This diff does make it fail:
```diff
+++ b/test/functional/ui/fold_spec.lua
@@ -208,7 +208,7 @@ describe("folded lines", function()
         ]])
       end
       command("set relativenumber cursorlineopt=number")
-      feed("jk")
+      feed("jgk")
       if multigrid then
         screen:expect([[
         ## grid 1
```

Comment (luukvbaal) [reply src/nvim/drawscreen.c:1859]: It seems the updated test still fails regardless of this change, I thought I had this working before, but I guess it still requires a fix.

Comment (luukvbaal) [reply src/nvim/drawscreen.c]: Swapping around the relativenumber and cursorline if blocks in `get_line_number_attr()` fixes this case. I wonder if it makes anything else fail, I wouldn't expect it to...

Comment (luukvbaal) [reply src/nvim/drawscreen.c]: This would also fix it, any preference? I guess this is more in line with the other changes already made:
```diff
 static int get_line_number_attr(win_T *wp, linenr_T lnum, int row, int startrow, int
filler_lines)
 {
   if (wp->w_p_rnu) {
-    if (lnum < wp->w_cursor.lnum) {
+    if (lnum < wp->w_cursorline) {
       // Use LineNrAbove
       return win_hl_attr(wp, HLF_LNA);
     }
-    if (lnum > wp->w_cursor.lnum) {
+    if (lnum > wp->w_cursorline) {
       // Use LineNrBelow
       return win_hl_attr(wp, HLF_LNB);
     }
```

Comment (zeertzjq) [reply src/nvim/drawscreen.c]: There may be another bug here.

Comment (luukvbaal) [reply src/nvim/drawscreen.c]: > This would also fix it, any preference? I guess this is more in line with the other changes already made:

This one is actually incorrect when 'cursorline' is not set, reverted to the previous version.

File: src/nvim/drawline.c [hunk 4]
```diff
@@ -960,7 +960,7 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool nochange,
   filler_todo = filler_lines;
 
   // Cursor line highlighting for 'cursorline' in the current window.
-  if (lnum == wp->w_cursor.lnum) {
+  if (lnum == wp->w_cursorline) {
     // Do not show the cursor line in the text when Visual mode is active,
     // because it's not clear what is selected then.
     if (wp->w_p_cul && !(wp == curwin && VIsual_active)
```
Comment (zeertzjq) [inline src/nvim/drawline.c:966]: Now checking for `w_p_cul` first makes more sense here (and is the same as Vim) because `w_cursorline` is not set if `w_p_cul` is false.
```suggestion
  if (wp->w_p_cul && lnum == wp->w_cursorline) {
    // Do not show the cursor line in the text when Visual mode is active,
    // because it's not clear what is selected then.
    if (!(wp == curwin && VIsual_active)
```

Comment (luukvbaal) [reply src/nvim/drawline.c:966]: Should it just be a single if block, i.e. reduce the nesting level?

Comment (zeertzjq) [reply src/nvim/drawline.c:966]: I guess yet.

Comment (luukvbaal) [reply src/nvim/drawline.c:966]:
```diff
+++ b/src/nvim/drawline.c
@@ -960,20 +960,17 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool nochange,
   filler_todo = filler_lines;

   // Cursor line highlighting for 'cursorline' in the current window.
-  if (lnum == wp->w_cursorline) {
-    // Do not show the cursor line in the text when Visual mode is active,
-    // because it's not clear what is selected then.
-    if (wp->w_p_cul && !(wp == curwin && VIsual_active)
-        && wp->w_p_culopt_flags != CULOPT_NBR) {
-      cul_screenline = (wp->w_p_wrap
-                        && (wp->w_p_culopt_flags & CULOPT_SCRLINE));
-      if (!cul_screenline) {
-        apply_cursorline_highlight(wp, lnum, &line_attr, &cul_attr, &line_attr_lowprio);
-      } else {
-        margin_columns_win(wp, &left_curline_col, &right_curline_col);
-      }
-      area_highlighting = true;
+  // Do not show the cursor line in the text when Visual mode is active,
+  // because it's not clear what is selected then.
+  if (wp->w_p_cul && wp->w_p_culopt_flags != CULOPT_NBR
+      && lnum == wp->w_cursorline && !(wp == curwin && VIsual_active) ) {
+    cul_screenline = (wp->w_p_wrap && (wp->w_p_culopt_flags & CULOPT_SCRLINE));
+    if (!cul_screenline) {
+      apply_cursorline_highlight(wp, lnum, &line_attr, &cul_attr, &line_attr_lowprio);
+    } else {
+      margin_columns_win(wp, &left_curline_col, &right_curline_col);
     }
+    area_highlighting = true;
   }

   SignTextAttrs sattrs[SIGN_SHOW_MAX];  // sign attributes for the sign column
```

Comment (zeertzjq) [reply src/nvim/drawline.c:966]: I guess yet. So
```diff
diff --git a/src/nvim/drawline.c b/src/nvim/drawline.c
index a4b9e552a..25db3c7d1 100644
--- a/src/nvim/drawline.c
+++ b/src/nvim/drawline.c
@@ -960,20 +960,18 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool nochange,
   filler_todo = filler_lines;
 
   // Cursor line highlighting for 'cursorline' in the current window.
-  if (lnum == wp->w_cursorline) {
-    // Do not show the cursor line in the text when Visual mode is active,
-    // because it's not clear what is selected then.
-    if (wp->w_p_cul && !(wp == curwin && VIsual_active)
-        && wp->w_p_culopt_flags != CULOPT_NBR) {
-      cul_screenline = (wp->w_p_wrap
-                        && (wp->w_p_culopt_flags & CULOPT_SCRLINE));
-      if (!cul_screenline) {
-        apply_cursorline_highlight(wp, lnum, &line_attr, &cul_attr, &line_attr_lowprio);
-      } else {
-        margin_columns_win(wp, &left_curline_col, &right_curline_col);
-      }
-      area_highlighting = true;
+  if (wp->w_p_cul && lnum == wp->w_cursor.lnum
+      // Do not show the cursor line in the text when Visual mode is active,
+      // because it's not clear what is selected then.
+      && !(wp == curwin && VIsual_active)
+      && wp->w_p_culopt_flags != CULOPT_NBR) {
+    cul_screenline = (wp->w_p_wrap && (wp->w_p_culopt_flags & CULOPT_SCRLINE));
+    if (!cul_screenline) {
+      apply_cursorline_highlight(wp, lnum, &line_attr, &cul_attr, &line_attr_lowprio);
+    } else {
+      margin_columns_win(wp, &left_curline_col, &right_curline_col);
     }
+    area_highlighting = true;
   }
 
   SignTextAttrs sattrs[SIGN_SHOW_MAX];  // sign attributes for the sign column
```

Comment (zeertzjq) [reply src/nvim/drawline.c]: I guess yes, so
```diff
diff --git a/src/nvim/drawline.c b/src/nvim/drawline.c
index a4b9e552a..b7ebd157b 100644
--- a/src/nvim/drawline.c
+++ b/src/nvim/drawline.c
@@ -960,20 +960,17 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool nochange,
   filler_todo = filler_lines;
 
   // Cursor line highlighting for 'cursorline' in the current window.
-  if (lnum == wp->w_cursorline) {
-    // Do not show the cursor line in the text when Visual mode is active,
-    // because it's not clear what is selected then.
-    if (wp->w_p_cul && !(wp == curwin && VIsual_active)
-        && wp->w_p_culopt_flags != CULOPT_NBR) {
-      cul_screenline = (wp->w_p_wrap
-                        && (wp->w_p_culopt_flags & CULOPT_SCRLINE));
-      if (!cul_screenline) {
-        apply_cursorline_highlight(wp, lnum, &line_attr, &cul_attr, &line_attr_lowprio);
-      } else {
-        margin_columns_win(wp, &left_curline_col, &right_curline_col);
-      }
-      area_highlighting = true;
+  if (wp->w_p_cul && wp->w_p_culopt_flags != CULOPT_NBR && lnum == wp->w_cursorline
+      // Do not show the cursor line in the text when Visual mode is active,
+      // because it's not clear what is selected then.
+      && !(wp == curwin && VIsual_active)) {
+    cul_screenline = (wp->w_p_wrap && (wp->w_p_culopt_flags & CULOPT_SCRLINE));
+    if (!cul_screenline) {
+      apply_cursorline_highlight(wp, lnum, &line_attr, &cul_attr, &line_attr_lowprio);
+    } else {
+      margin_columns_win(wp, &left_curline_col, &right_curline_col);
     }
+    area_highlighting = true;
   }
 
   SignTextAttrs sattrs[SIGN_SHOW_MAX];  // sign attributes for the sign column
```

File: test/functional/ui/fold_spec.lua [hunk 5]
```diff
@@ -176,26 +185,63 @@ describe("folded lines", function()
...
+          {1:~                                            }|
+          {1:~                                            }|
+          {1:~                                            }|
+          {1:~                                            }|
+                                                       |
+        ]])
+      end
+      command("set relativenumber cursorlineopt=number")
+      feed("jgk")
+      poke_eventloop()
```
Comment (luukvbaal) [inline test/functional/ui/fold_spec.lua:212]: Still getting:

```
warning: Screen changes were received after the expected state. This indicates
indeterminism in the test. Try adding screen:expect(...) (or poke_eventloop())
between asynchronous (feed(), nvim_input()) and synchronous API calls.
```

Do we care/anything to be done about it?

Comment (zeertzjq) [reply test/functional/ui/fold_spec.lua:212]: Do you mean this happens with `poke_eventloop()`?

Comment (luukvbaal) [reply test/functional/ui/fold_spec.lua:212]: Yes, specifically this test still gives this warning with `poke_eventloop()`, but not always.

File: test/functional/ui/fold_spec.lua [hunk 6]
```diff
@@ -176,26 +185,63 @@ describe("folded lines", function()
...
+          {7:  }{8:  6 }                                       |
+          {1:~                                            }|
+          {1:~                                            }|
+          {1:~                                            }|
+          {1:~                                            }|
+                                                       |
+        ]])
+      end
+      command("set relativenumber cursorlineopt=number")
+      feed("jgk")
```
Comment (zeertzjq) [inline test/functional/ui/fold_spec.lua:211]: I think using `zo4Gzc` here is better. It is not clear if the current behavior of `jgk` is intended (#15490).

File: test/functional/ui/fold_spec.lua [hunk 7]
```diff
@@ -176,26 +185,63 @@ describe("folded lines", function()
...
+          {1:~                                            }|
+          {1:~                                            }|
+          {1:~                                            }|
+          {1:~                                            }|
+                                                       |
+        ]])
+      end
+      command("set relativenumber cursorlineopt=number")
+      feed("zo4Gzc")
+      poke_eventloop()
```
Comment (zeertzjq) [inline test/functional/ui/fold_spec.lua:212]: Actually this can be removed. This fixes the warning and still fails without the change in `get_line_number_attr()`.
```suggestion
```

**Comment by zeertzjq** [comment]
This introduces an extra call to `fold_info()` on each redraw when `cursorline_standout` is true. Not sure if it's possible to avoid this extra call.

**Comment by luukvbaal** [comment]
`fold_info()` is called again for each line in the main loop in `win_update()`. The additional work here could be avoided by storing the cursorline `foldinfo_T` and passing it to `win_line()` in place of the new `fold_info()` when `lnum == wp->w_cursorline`.

**Comment by luukvbaal** [comment]
The added tests keep passing without these two changes, I guess we should omit them? I think it is more correct. Turns out the changes to `w_cursorline` in `drawline.c` were what was necessary here.
```diff
@@ -1604,7 +1609,7 @@ static void win_update(win_T *wp, DecorProviders *providers)
                         // if lines were inserted or deleted
                         || (wp->w_match_head != NULL
                             && buf->b_mod_xlines != 0)))))
-        || (cursorline_standout && lnum == wp->w_cursor.lnum)
+        || (cursorline_standout && lnum == wp->w_cursorline)
         || lnum == wp->w_last_cursorline) {
       if (lnum == mod_top) {
         top_to_mod = false;
@@ -1849,7 +1854,7 @@ static void win_update(win_T *wp, DecorProviders *providers)

   // Now that the window has been redrawn with the old and new cursor line,
   // update w_last_cursorline.
-  wp->w_last_cursorline = cursorline_standout ? wp->w_cursor.lnum : 0;
+  wp->w_last_cursorline = cursorline_standout ? wp->w_cursorline : 0;

   wp->w_last_cursor_lnum_rnu = wp->w_p_rnu ? wp->w_cursor.lnum : 0;

```

**Comment by zeertzjq** [comment]
I've tried this change on this PR but it didn't work.

**Comment by luukvbaal** [comment]
I included that and other micro-optimizations in latest commit if we care.

> I've tried this change on this PR previously but it didn't work. Now I tried again and it works, so maybe I made a mistake previously.

Perhaps you checked for `w_cursorline` instead of `w_cursor.lnum` there? It's confusing me as well😅 I almost reverted these two because I thought the original was more correct and the added tests didn't fail without them but it does break some behavior. I'll try to add a test for it, I would have thought the current tests would fail with the behavior I observed...
```diff
+++ b/src/nvim/drawscreen.c
@@ -1609,7 +1609,7 @@ static void win_update(win_T *wp, DecorProviders *providers)
                         // if lines were inserted or deleted
                         || (wp->w_match_head != NULL
                             && buf->b_mod_xlines != 0)))))
-        || (cursorline_standout && lnum == wp->w_cursorline)
+        || (cursorline_standout && lnum == wp->w_cursor.lnum)
         || lnum == wp->w_last_cursorline) {
       if (lnum == mod_top) {
         top_to_mod = false;
@@ -1854,7 +1854,7 @@ static void win_update(win_T *wp, DecorProviders *providers)

   // Now that the window has been redrawn with the old and new cursor line,
   // update w_last_cursorline.
-  wp->w_last_cursorline = cursorline_standout ? wp->w_cursorline : 0;
+  wp->w_last_cursorline = cursorline_standout ? wp->w_cursor.lnum : 0;

   wp->w_last_cursor_lnum_rnu = wp->w_p_rnu ? wp->w_cursor.lnum : 0;
```

**Review by zeertzjq — APPROVED** [review]
