### PR TITLE
logs: make XDG_CACHE_HOME/nvim if it doesn't exist

### LINKED ISSUE #13753: .nvimlog in every directory I work in
- `nvim --version`: NVIM v0.5.0-dev+1023-gea8756f85 
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
open a file, edit it, close the file
```

### Actual behaviour
`.nvimlog` is placed in the local directory
### Expected behaviour
`.nvimlog` is not placed in the local directory

A result of #13739 presumably.  

If I create the directory `~/.cache/nvim` myself then neovim uses it.  Shouldn't neovim have created that directory?

### PR DESCRIPTION
**Pull request by mjlbach**
Closes #13753

@teto

### CODE REVIEW

File: src/nvim/log.c [hunk 1]
```diff
@@ -69,6 +69,12 @@ static bool log_path_init(void)
       || log_file_path[0] == '\0'
       || os_isdir((char_u *)log_file_path)
       || !log_try_create(log_file_path)) {
+    // Make kXDGCacheHome if it does not exist.
+    char *cachehome = get_xdg_home(kXDGCacheHome);
+    if (!os_isdir((char_u *)cachehome)) {
+      os_mkdir((char *)cachehome, 0700);
```
Comment (jamessan) [inline src/nvim/log.c:75]: This should probably be `os_mkdir_recurse()`, since we don't know how much (if any) of XDG_CACHE_HOME will already exist.

Comment (mjlbach) [reply src/nvim/log.c:75]: I thought about that, I'll go ahead and change it then

**Comment by mjlbach** [comment]
I looked through the C style guide and I think this is ok? Let me know if I need to clean it up?

File: src/nvim/log.c [hunk 2]
```diff
@@ -69,6 +70,19 @@ static bool log_path_init(void)
       || log_file_path[0] == '\0'
       || os_isdir((char_u *)log_file_path)
       || !log_try_create(log_file_path)) {
+    // Make kXDGCacheHome if it does not exist.
+    char *cachehome = get_xdg_home(kXDGCacheHome);
+    char *failed_dir = NULL;
+    if (!os_isdir((char_u *)cachehome)) {
+        int ret;
+        if ((ret = os_mkdir_recurse(cachehome, 0700, &failed_dir)) != 0) {
+          EMSG3(_(SERR "Failed to create directory %s "
```
Comment (jamessan) [inline src/nvim/log.c:79]: `SERR` (and E886) are specific to the shada code.  It looks like every "Failed to create directory" scenario currently has its own error code, so I guess we need a new one for this.

It needs to be in the 5xxx range since it's Neovim specific.  It looks like we already have some different groups of error numbers in the 5000+ range, but I don't know what the reasoning behind them is.  The error code should also be a tag in the help file at the same location as `:help NVIM_LOG_FILE`.

I think `:help NVIM_LOG_FILE` should specifically mention `$XDG_CACHE_HOME` so it's clear we honor that, rather than coincidentally choosing the same path.

Comment (mjlbach) [reply src/nvim/log.c]: Updated the error code and docs. The test that is failing now is

```
[  ERROR   ] test/functional/options/defaults_spec.lua @ 236: startup defaults $NVIM_LOG_FILE defaults to .nvimlog if stdpath("cache") is invalid
```

Which makes sense, since now we are explicitly making stdpath cache, so I guess I need to figure out how to make an unwriteable stdpath cache in the test?

Comment (mjlbach) [reply src/nvim/log.c]: Also will change the error code based on feedback as to what it should be, I just picked a free number.

Comment (mjlbach) [reply src/nvim/log.c]: @bfredl has revealed the reasoning behind error codes is RNG

File: runtime/doc/starting.txt [hunk 3]
```diff
@@ -1338,12 +1338,12 @@ DATA DIRECTORY (DEFAULT) ~
...
 "~/.config" is understood to mean "$XDG_CONFIG_HOME or ~/.config".
 
-LOG FILE					*$NVIM_LOG_FILE*
+LOG FILE					*$NVIM_LOG_FILE* *E5010*
 Besides 'debug' and 'verbose', Nvim keeps a general log file for internal
 debugging, plugins and RPC clients. >
 	:echo $NVIM_LOG_FILE
-Usually the file is ~/.cache/nvim/log unless that path is inaccessible
-or if $NVIM_LOG_FILE was set before |startup|.
+By default, the file is located at $XDG_CACHE_HOME/nvim/log unless that path
```
Comment (teto) [inline runtime/doc/starting.txt:1345]: this is valid only on linux, may be best to refer to it as stdpath('cache')

File: src/nvim/log.c [hunk 4]
```diff
@@ -69,6 +70,19 @@ static bool log_path_init(void)
...
+    if (!os_isdir((char_u *)cachehome)) {
+        int ret;
+        if ((ret = os_mkdir_recurse(cachehome, 0700, &failed_dir)) != 0) {
+          EMSG3(_(LOGERR "Failed to create directory %s "
+                  "for writing logs: %s"),
+                failed_dir, os_strerror(ret));
+        }
+    }
+    xfree(failed_dir);
+    xfree(cachehome);
```
Comment (teto) [inline src/nvim/log.c:85]: we recommand XFREE_CLEAR

File: runtime/doc/starting.txt (hunk 3 above)
Comment (mjlbach) [reply runtime/doc/starting.txt]: Done

Comment (mjlbach) [reply runtime/doc/starting.txt]: Also added a note that logs are stored at the standard location now (along with data)

File: src/nvim/log.c (hunk 4 above)
Comment (mjlbach) [reply src/nvim/log.c]: Done

**Comment by ZacharyRizer** [comment]
I am still having the issue discussed here [#13753](https://github.com/neovim/neovim/issues/13753) that this merge is shown to fix. Is there something I'm missing? .nvimlog still appears in every project repo. 

nvim --version = NVIM v0.5.0-dev+1028-g702208daa

the nvimlog's are empty, I don't see any error messages.

**Comment by jamessan** [comment]
> .nvimlog still appears in every project repo.

_Appears_ or are left over from before the problem was fixed?  I would suggest deleting them so you can confirm one way or the other.

**Comment by ZacharyRizer** [comment]
Appears. I can delete them, exit nvim, then open nvim in the project root and .nvimlog is right back where I it was before.

**Comment by jamessan** [comment]
What does `env | grep -e XDG -e HOME` show in your shell?

**Comment by ZacharyRizer** [comment]
It shows my home directory:

HOME=/Users/(myUserName)

**Comment by mjlbach** [comment]
Just moving my comment from the other thread here:

You need to use a debug build now for the error message to show up.

    Install the build dependencies if you haven't.
    Clone the git repo
    run make
    If .nvimlog is still present there should be an error message as why

**Comment by ZacharyRizer** [comment]
@mjlbach I saw your message in the other thread, sorry I meant to respond. I did install from the cloned repo with make. But still no logs. Let me uninstall, and make sure all dependencies are there, then reinstall.

**Comment by mjlbach** [comment]
FWIW I'm on mac, and I don't see this issue

**Comment by mjlbach** [comment]
Make sure you use `./build/bin/nvim`

**Comment by ZacharyRizer** [comment]
Ok, so I think I finally got the debug version installed. This is what it shows in the log file right after it is created, i.e. on nvim startup. 

INFO  2021-01-18T14:21:57.227 25246 set_init_2:754: startup runtimepath/packpath value: /Users/proton/.config/nvim,/etc/xdg/nvim,/Users/proton/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/local/share/nvim/runtime,/usr/local/lib/nvim,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/Users/proton/.local/share/nvim/site/after,/etc/xdg/nvim/after,/Users/proton/.config/nvim/after
INFO  2021-01-18T14:21:57.277 25246 channel_create_event:204: new channel 3 (function coc#rpc#start_server[17]..<SNR>16_start:55) : {"id": 3, "client": {}, "mode": "rpc", "stream": "job"}
INFO  2021-01-18T14:21:57.338 25246 main:559: starting main loop

**Comment by mjlbach** [comment]
If you can hop into gdb/lldb and put a break on log_path_init, this is the only place that could be failing:

https://github.com/mjlbach/neovim/blob/abbfaf286f26989b18377d4238f3cea9dc281149/src/nvim/log.c#L91

**Comment by mjlbach** [comment]
For reference:

1. `lldb ./build/bin/nvim`
2. `breakpoint set --file log.c --line 75`
3.  run
4. `n` until line 85, see why the conditional fails.

**Comment by ZacharyRizer** [comment]
Thanks for the step through, definitely a bit out of my pay grade here. I'm not sure exactly what I'm looking for, but I didn't see anything jump out at me in the debugger. 
Screen Shot 2021-01-18 at 3 06 40 PM

**Comment by mjlbach** [comment]
1. Goto line 85
2. `p len`
3. `p size`
4.  `p log_try_create(log_file_path)`
5.  `p log_file_path`
And paste all of those values here

**Comment by ZacharyRizer** [comment]
(lldb) p len
(size_t) $0 = 29
(lldb) p size
(size_t) $1 = 4097
(lldb) p log_try_create(log_file_path)
(bool) $2 = false
(lldb) p log_file_path
(char [4097]) $3 = "/Users/proton/.cache/nvim/log"

**Comment by mjlbach** [comment]
We are so close!

Go to line 85
1. `s` instead of `n`
2. `n` (and paste the trace like you did before, that was helpful)
3. `p log_file` on line 45, I'm guessing fopen is failing for some reason.

**Comment by ZacharyRizer** [comment]
Screen Shot 2021-01-18 at 3 23 09 PM

**Comment by mjlbach** [comment]
Can you just check the file perms on 
1.`ls -ld /Users/proton/.cache`
2. `ls -ld /Users/proton/.cache/nvim`
3. `ls -l /Users/proton/.cache/nvim/log`

4. Also, go back to line 45, hit `n` until you are on the `return false` statement, then `p errno` and `p *errno`

**Comment by mjlbach** [comment]
Basically fopen is returning NULL which indicates the file can't be opened, but the directory exists so it's likely a permissions error.

**Comment by ZacharyRizer** [comment]
Screen Shot 2021-01-18 at 3 38 55 PM
Screen Shot 2021-01-18 at 3 40 28 PM

Thank you for all the guidance on this!

**Comment by mjlbach** [comment]
`sudo rm ~/.cache/nvim/log`

The problem should be gone. I'm not quite sure how that got there, as running as root shouldn't respect your local XDG_CACHE_DIR (I think?)

**Comment by ZacharyRizer** [comment]
Bravo! Thank you so much for taking the time to walk me through this. Also learned a lot about that particular debugging tool!

File: test/functional/options/defaults_spec.lua [hunk 5]
```diff
@@ -233,13 +233,6 @@ describe('startup defaults', function()
       }})
       eq(xdgcachedir..'/log', string.gsub(eval('$NVIM_LOG_FILE'), '\\', '/'))
     end)
-    it('defaults to .nvimlog if stdpath("cache") is invalid', function()
```
Comment (justinmk) [inline test/functional/options/defaults_spec.lua:236]: still need this test for permissions cases , no?
