### PR TITLE
fix(terminal): skip setting `string_initial` to false on no-op

### LINKED ISSUE #34028: crash when cat big file inside terminal of nvim
### Problem

testing with 0.10.4/0.11.1

open terminal inside nvim by :terminal 

cat a big patch file (which contains some binary diff by accident)

nvim crash with following stacktrace:

```
#0  0x00007f6ed32969fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f6ed32969fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f6ed3242476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f6ed32287f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f6ed3289677 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f6ed32a0cfc in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007f6ed32a4c7c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007f6ed32a5909 in realloc () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x000055766ce7a5cf in xrealloc (ptr=0x5576926913c0, size=0) at /home/xwang/project/neovim/src/nvim/memory.c:178
#8  0x000055766cfc9e2e in term_settermprop (prop=VTERM_PROP_TITLE, val=0x7fff21498120, data=0x55769260c270) at /home/xwang/project/neovim/src/nvim/terminal.c:1309
#9  0x000055766d034105 in settermprop (prop=VTERM_PROP_TITLE, val=0x7fff21498120, user=0x55769267c040) at /home/xwang/project/neovim/src/nvim/vterm/screen.c:439
#10 0x000055766d0367c2 in vterm_state_set_termprop (state=0x557692f520d0, prop=VTERM_PROP_TITLE, val=0x7fff21498120) at /home/xwang/project/neovim/src/nvim/vterm/state.c:2375
#11 0x000055766d03d3dc in settermprop_string (state=0x557692f520d0, prop=VTERM_PROP_TITLE, frag=...) at /home/xwang/project/neovim/src/nvim/vterm/state.c:545
#12 0x000055766d03b141 in on_osc (command=0, frag=..., user=0x557692f520d0) at /home/xwang/project/neovim/src/nvim/vterm/state.c:1950
#13 0x000055766d0306b7 in string_fragment (vt=0x557692ad7e70, str=0x55769445f9d7 "", len=0, final=false) at /home/xwang/project/neovim/src/nvim/vterm/parser.c:89
#14 0x000055766d02fc4d in vterm_input_write (vt=0x557692ad7e70, bytes=0x55769445f240 "", len=4095) at /home/xwang/project/neovim/src/nvim/vterm/parser.c:165
#15 0x000055766cfc7814 in terminal_receive (term=0x55769260c270, data=0x55769445f240 "", len=4095) at /home/xwang/project/neovim/src/nvim/terminal.c:1114
#16 0x000055766ccc369e in on_channel_output (stream=0x55769266f418, chan=0x55769266f230, buf=0x55769445f240 "", count=4095, eof=false, reader=0x55769266f918) at /home/xwang/project/neovim/src/nvim/channel.c:681
#17 0x000055766ccc2e21 in on_channel_data (stream=0x55769266f418, buf=0x55769445f240 "", count=4095, data=0x55769266f230, eof=false) at /home/xwang/project/neovim/src/nvim/channel.c:653
#18 0x000055766cd797bf in read_event (argv=0x7fff21498468) at /home/xwang/project/neovim/src/nvim/event/rstream.c:180
#19 0x000055766cd79715 in invoke_read_cb (stream=0x55769266f418, eof=false) at /home/xwang/project/neovim/src/nvim/event/rstream.c:233
#20 0x000055766cd79173 in read_cb (uvstream=0x55769266f420, cnt=4095, buf=0x7fff21498570) at /home/xwang/project/neovim/src/nvim/event/rstream.c:135
#21 0x000055766d13f22c in uv.read ()
#22 0x000055766d13fb78 in uv.stream_io ()
#23 0x000055766d148551 in uv.io_poll ()
#24 0x000055766d1342af in uv_run ()
#25 0x000055766cd765a2 in loop_uv_run (loop=0x55766d2ea358 <main_loop>, ms=0) at /home/xwang/project/neovim/src/nvim/event/loop.c:61
#26 0x000055766cd764dd in loop_poll_events (loop=0x55766d2ea358 <main_loop>, ms=0) at /home/xwang/project/neovim/src/nvim/event/loop.c:82
#27 0x000055766ceeace9 in os_breakcheck () at /home/xwang/project/neovim/src/nvim/os/input.c:207
#28 0x000055766cf9d9bf in state_handle_k_event () at /home/xwang/project/neovim/src/nvim/state.c:131
#29 0x000055766cfc8568 in terminal_execute (state=0x7fff2149c730, key=-26365) at /home/xwang/project/neovim/src/nvim/terminal.c:894
#30 0x000055766cf9d919 in state_enter (s=0x7fff2149c730) at /home/xwang/project/neovim/src/nvim/state.c:102
#31 0x000055766cfc7ea4 in terminal_enter () at /home/xwang/project/neovim/src/nvim/terminal.c:740
#32 0x000055766ccfff23 in edit (cmdchar=105, startln=false, count=1) at /home/xwang/project/neovim/src/nvim/edit.c:1284
#33 0x000055766ceaddfa in invoke_edit (cap=0x7fff2149c970, repl=0, cmd=105, startln=0) at /home/xwang/project/neovim/src/nvim/normal.c:6282
#34 0x000055766cea8617 in nv_edit (cap=0x7fff2149c970) at /home/xwang/project/neovim/src/nvim/normal.c:6254
#35 0x000055766cea5b84 in normal_execute (state=0x7fff2149c900, key=105) at /home/xwang/project/neovim/src/nvim/normal.c:1244
#36 0x000055766cf9d919 in state_enter (s=0x7fff2149c900) at /home/xwang/project/neovim/src/nvim/state.c:102
#37 0x000055766cea0fc4 in normal_enter (cmdwin=false, noexmode=false) at /home/xwang/project/neovim/src/nvim/normal.c:523
#38 0x000055766ce3c8a9 in main (argc=2, argv=0x7fff2149cd58) at /home/xwang/project/neovim/src/nvim/main.c:651
```

### Steps to reproduce

cat use following big patch, I got it 100 % reproducible 

[out.tar.xz.log](https://github.com/user-attachments/files/20220558/out.tar.xz.log)

(note: unpack as tar.xz because github doesn't allow tar.xz attachment)

### Expected behavior

not crash

### Nvim version (nvim -v)

0.11.1/0.10.4

### Vim (not Nvim) behaves the same?

not tried

### Operating system/version

ubuntu 22.04

### Terminal name/version

kitty/neovide remote

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by The-Briel-Deal**
Problem:

Currently undefined behavior can occur when `string_fragment()` is called with `OSC_COMMAND`. This is because when the state changes to `OSC_COMMAND`, `string_initial` is set to true. Then in some cases, directly after this `string_initial` will be set back to false before the on_osc callback is called, this leads to `term_settermprop()` never initializing the title.

Solution:

In all of the no-op cases in `string_fragment()` currently, we continue to the end of the function where `vt->parser.string_initial` is set to false. This change makes it so that the function returns in the no-op cases instead.

Note:

This change also adds a test with a byte sequence from the file in #34028 that caused nvim to crash. This byte sequences is the shortest sequence I could trim down from that file that still would trigger the crash. There are also two other tests I added which validate that setting the title with OSC-0 and OSC-2 still works.

Fixes: #34028

### CODE REVIEW

**Comment by The-Briel-Deal** [comment]
I addressed the unrelated reason the lint check is failing here https://github.com/neovim/neovim/pull/34180.

**Review by gpanders — DISMISSED** [review]

File: test/functional/terminal/parser_spec.lua [hunk 1]
```diff
@@ -12,4 +16,36 @@ describe(':terminal', function()
...
+  end)
+
+  it('handles control character following OSC prefix #34028', function()
+    local chan = api.nvim_open_term(0, {})
+    local input = OSC_PREFIX .. NUL .. '0;aaaaaaaaaaaaaaaaaaaaaaaaaaa\r\n'
+    --                          ^ Having a ctrl char following the OSC_PREFIX causes
+    --                            `string_fragment()` to be called while in OSC_COMMAND mode.
+    api.nvim_chan_send(chan, input)
+    assert_alive()
+  end)
```
Comment (gpanders) [inline test/functional/terminal/parser_spec.lua:50]: All three of these tests pass on master without your change, so I don't think these reproduce the issue you're describing.

**Comment by The-Briel-Deal** [comment]
Hey @gpanders! I just wanted to follow up on this patch. I extended the test case with a second portion which pushes a longer string if the first one succeeds to make sure the test case reproduces the issue on MacOS as well. Let me know if you have any more questions on this!

I'm pretty sure the reason you weren't able to reproduce this the first time is because the test triggered the crash on all platforms except for MacOS ([see this CI run where I verified this](https://github.com/The-Briel-Deal/neovim/actions/runs/15258010280)).

File: test/functional/terminal/parser_spec.lua (hunk 1 above)
Comment (gpanders) [reply test/functional/terminal/parser_spec.lua]: > So i'm wondering if you are on an apple silicon mac?

Indeed I am. Thanks for looking into this.

**Review by gpanders — APPROVED** [review]
