### PR TITLE
fix(highlight): preserve inherited colors when update=true breaks links

### LINKED ISSUE #38743: Linked group is lost from `:hi` after another hlgroup update with `update = true`
### Problem

I was experimenting with the new `update` option in `vim.api.nvim_set_hl` and tried updating a hlgroup that was previously linked. It worked, but `:hi` shows incomplete info.

### Steps to reproduce

`nvim --clean`

1. `50o<Esc>`
2. `set nu`
3. `:lua vim.api.nvim_set_hl(0, "RedBG", { bg = "red" })`
4. `:lua vim.api.nvim_set_hl(0, "LineNr", { link = "RedBG" })`
5. `lua vim.api.nvim_set_hl(0, "LineNr", { fg = "green", update = true })`

Before the last step:

Image

After the last step:

Image

### Expected behavior

Line numbers are updated, but the information about where the red bg is from is lost, I would expect either `links to RedGB` or `guibg=red` in the output.

### Nvim version (nvim -v)

v0.13.0-dev-65+gb346b87fb2-Homebrew

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 26.3.1

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

wezterm

### Installation

homebrew

### PR DESCRIPTION
**Pull request by glepnir**
Problem: Breaking a link with update=true loses colors inherited from the linked group.

Solution: Copy color indices from the linked group so inherited colors remain visible in :hi output.

Fix #38743

### CODE REVIEW

File: src/nvim/highlight_group.c [hunk 1]
```diff
@@ -965,6 +966,12 @@ void set_hl_group(int id, HlAttrs attrs, Dict(highlight) *dict, int link_id)
       }
     } else if (!update) {
       *cattrs[j].dest = kColorIdxNone;
+    } else if (old_link > 0 && cattrs[j].val >= 0) {
+      HlGroup *linked = &hl_table[old_link - 1];
```
Comment (justinmk) [inline src/nvim/highlight_group.c:971]: 1-line comments that explain what's going on are always worth having for these changes. It's not at all obvious what's going on here. It's really not a fun puzzle to have to figure out this kind of code everywhere. 

```suggestion
      // Copy color indices from the linked group so inherited colors remain visible in :hi output.
      HlGroup *linked = &hl_table[old_link - 1];
```
