### PR TITLE
fix(menu): check Visual mode before Insert in execute_menu

### LINKED ISSUE #19473: Mouse popup showing menu in insert-visual mode while it reports no menu
### Neovim version (nvim -v)

0.8.0-dev+519-g6f6286e4f9

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

linux 5.15.19-1-MANJARO

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

AUR

### How to reproduce the issue

```
nvim --clean
:set mouse=a
isome text <C-o>V
```
right click visually selected area.
left click on `cut`

### Expected behavior

Either:
Text being cut
Or:
There being no popup menu

### Actual behavior

An error is raised:
`E335: Menu not defined for Insert mode`

### PR DESCRIPTION
**Pull request by glepnir**
Problem: Right-click menu fails with E335 when using <C-o>V in Insert mode. The mode detection checks restart_edit before VIsual_active, incorrectly selecting Insert mode binding even when Visual mode is active.

Solution: Check Visual mode before Insert mode to match get_menu_mode() priority order.

Fix #19473

### CODE REVIEW

File: src/nvim/menu.c [hunk 1]
```diff
@@ -1438,18 +1438,18 @@ void execute_menu(const exarg_T *eap, vimmenu_T *menu, int mode_idx)
...
-    } else if (State & MODE_TERMINAL) {
+    if (State & MODE_TERMINAL) {
       idx = MENU_INDEX_TERMINAL;
     } else if (get_real_state() & MODE_VISUAL) {
       // Detect real visual mode -- if we are really in visual mode we
       // don't need to do any guesswork to figure out what the selection
       // is. Just execute the visual binding for the menu.
       idx = MENU_INDEX_VISUAL;
+    } else if (State & MODE_CMDLINE) {
+      idx = MENU_INDEX_CMDLINE;
```
Comment (zeertzjq) [inline src/nvim/menu.c]: Cmdline mode should have higher priority than Visual mode.
