### PR TITLE
fix(lsp): sort items when completeopt include fuzzy

### LINKED ISSUE #33610: Incorrect completion sorting with `completeopt+=fuzzy`
### Problem

Incorrect completions items returned after typing non `iskeyword` like `-` or `\`

### Steps to reproduce

init.lua
```lua
for name, url in pairs({
	"https://github.com/neovim/nvim-lspconfig",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

vim.api.nvim_create_autocmd("LspAttach", {
	group = vim.api.nvim_create_augroup("UserLspConfig", {}),
	callback = function(args)
		local client = vim.lsp.get_client_by_id(args.data.client_id)
		if client == nil then
			return
		end
		vim.lsp.completion.enable(true, client.id, args.buf, { autotrigger = true })
	end,
})

vim.lsp.enable("svelte")
vim.lsp.enable("tailwindcss")

vim.opt.completeopt = "menuone,popup,noselect,fuzzy"
```

1. initialize a sveltekit project and enable tailwindcss
2. open `src/routes/+layout.svelte` and enter `w-` for header's class
3. irrelevant completion items to width are returned

relevant `mini.completion` issue: https://github.com/echasnovski/mini.nvim/issues/530  

### Expected behavior

expected to items like `w-{number}` to be returned

### Nvim version (nvim -v)

NVIM v0.11.0

### Vim (not Nvim) behaves the same?

vim not support this feature

### Operating system/version

Linux

### Terminal name/version

st/tmux

### $TERM environment variable

tmux-256color

### Installation

official arch package

### PR DESCRIPTION
**Pull request by glepnir**
Problem: When fuzzy is enabled and the prefix is not empty, items are not sorted by fuzzy score before calling fn.complete.

Solution: Use matchfuzzypos to get the scores and sort the items by fuzzy score before calling fn.complete.

Fix #33610

### CODE REVIEW

File: runtime/lua/vim/lsp/completion.lua [hunk 1]
```diff
@@ -352,6 +357,13 @@ function M._lsp_to_complete_items(result, prefix, client_id)
   if not user_cmp then
     ---@diagnostic disable-next-line: no-unknown
     table.sort(candidates, function(a, b)
+      if use_fuzzy and prefix ~= '' then
+        local score_a = a._fuzzy_score or 0
+        local score_b = b._fuzzy_score or 0
+        if score_a ~= score_b then
+          return score_a > score_b
+        end
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/completion.lua]: Isn't this strictly speaking going against the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion)?

> to achieve consistency across languages and to honor different clients usually the client is responsible for filtering and sorting. This has also the advantage that client can experiment with different filter and sorting models. However servers can enforce different behavior by setting a filterText / sortText

> Completion Item with text edits: in this mode the server tells the client that it actually knows what it is doing. If you create a completion item with a text edit at the current cursor position no word guessing takes place and no automatic filtering (like with an insertText) should happen. This mode can be combined with a sort text and filter text to customize two things. If the text edit is a replace edit then the range denotes the word used for filtering. If the replace changes the text it most likely makes sense to specify a filter text to be used.

Based on that I'd think it should use  `sortText -> score -> label`. But judging from your test cases the server actually provides a `textEdit` and `sortText` - which seems like the server is drunk and provides a bad ordering?

No strong opinion. But maybe worth double checking if the server isn't doing something wrong.

Otherwise - if you extend it to also honor the `nosort` `completeopt` it should be good, given that we'd then have an opt-out and users could configure either behavior.
And maybe worth pulling the `if ...` out of the inner sort loop and create a different `compare_fn` depending on `use_fuzzy` & `prefix`.

Comment (glepnir) [reply runtime/lua/vim/lsp/completion.lua]: Yes, I overlooked the fact that when isIncomplete is set, the prefix can also be non-empty. This breaks sortText ordering on some servers. I’ve adjusted the condition here: fuzzy-score sorting is now only applied when the prefix is inferred before the completion popup is created for the first time, and when there are no subsequent completion requests. also added nosort.

**Review by mfussenegger — APPROVED** [review]
