### PR TITLE
fix(trust): hash unchanged empty buffers as empty files

### LINKED ISSUE #39017: cannot `:trust` empty file
### Problem

Empty files (actual empty ones, without any eol chars) cannot be properly trusted at the moment, nvim asks for trust infinitely even if it's already `:trust`ed.

Possibly related: #31241

### Steps to reproduce

- `touch empty`
- `:=vim.secure.read("empty")`
- choose to view file and `:trust` in the new window
-  `:=vim.secure.read("empty")` and see the trust prompt again

### Expected behavior

It should be possible to `:trust` empty files.

### Nvim version (nvim -v)

0.12.1

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Linux 6.18; Android 14

### Terminal name/version

WezTerm; Termux

### $TERM environment variable

xterm-256color

### Installation

nixpkgs; termux-packages

### PR DESCRIPTION
**Pull request by barrettruth**
## Problem

related #39017 (SHOULD NOT be closed)

`vim.secure.trust({ bufnr = ... })` hashes an unchanged empty buffer as a newline, so trusting an empty file by buffer does not match the empty bytes hashed by `vim.secure.read(path)`.

## Solution

Handle the unchanged empty-buffer case explicitly and hash it as `''` so buffer-based trust matches the on-disk empty file in that workflow.

***NOTE***: NeoVim's modified-empty vs unmodified-empty is (and has been for a while) WIP (see #34272), so this is intentionally scoped to only unchanged, empty files which are handled unambiguously. For example, modifying an empty, untrusted file (which is allowed) will STILL run into the linked issue..

### CODE REVIEW

**Comment by justinmk** [comment]
> Handle the unchanged empty-buffer case explicitly and hash it as `''`

Yes, this is fine 👍

**Comment by barrettruth** [comment]
I think this partially resolves the issue and takes a most conservative position. For this reason I think it is in no part *incorrect* so I have marked it ready.

File: test/functional/ex_cmds/trust_spec.lua [hunk 1]
```diff
@@ -54,6 +57,16 @@ describe(':trust', function()
     eq(string.format(''), vim.trim(trust))
   end)
 
+  it('trust an empty file using current buffer', function()
+    local cwd = fn.getcwd()
+    local hash = fn.sha256(assert(t.read_file(empty_file)))
+
+    command('edit ' .. empty_file)
+    matches('^Allowed in trust database%: ".*' .. empty_file .. '"$', exec_capture('trust'))
+    local trust = t.read_file(fn.stdpath('state') .. pathsep .. 'trust')
```
Comment (justinmk) [inline test/functional/ex_cmds/trust_spec.lua:66]: i guess this is following the other existing test, but just for reference, we could use `vim.fs.joinpath()` to make this more readable.

**Review by justinmk — APPROVED** [review]
