### PR TITLE
fix: make `nvim_cmd` not suppress errors inside key mapping

### LINKED ISSUE #18632: nvim_cmd in key mapping suppresses errors
### Neovim version (nvim -v)

NVIM v0.8.0-dev+243-g03a8269e3

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.X

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

Source

### How to reproduce the issue

test.lua:
```lua
vim.keymap.set("n", "[l", function() vim.api.nvim_cmd({cmd = "lprev"}) end)
```

Then:

```
nvim --clean -u test.lua
```

Press `[l` in Normal mode.

### Expected behavior

The mapping should throw an error because there is no location list.

### Actual behavior

No error is thrown.

Using `vim.api.nvim_command("lprev")` in the mapping *does* throw an error as expected.

### PR DESCRIPTION
**Pull request by famiu**
Fixes `nvim_cmd` not showing errors when it's used inside a key mapping. Also has an additional fix to make `nvim_cmd` properly undo the `:sandbox` modifier

Closes #18632

### CODE REVIEW

File: test/functional/api/vim_spec.lua [hunk 1]
```diff
@@ -3636,5 +3636,13 @@ describe('API', function()
       meths.cmd({ cmd = "update" }, {})
       meths.cmd({ cmd = "buffer", count = 0 }, {})
     end)
+    it('doesn\'t suppress errors when used in keymapping', function()
+      meths.exec_lua([[
+        vim.keymap.set("n", "[l",
+                       function() vim.api.nvim_cmd({ cmd = "echo", args = {"foo"} }, {}) end)
+      ]], {})
+      feed("[l")
+      neq(nil, string.find(eval("v:errmsg"), "E5108"))
```
Comment (zeertzjq) [inline test/functional/api/vim_spec.lua:3645]:
```suggestion
      neq(nil, string.find(eval("v:errmsg"), "E5108:"))
```

**Comment by gpanders** [comment]
Can confirm that this fixes #18632.

**Review by gpanders — APPROVED** [review]
