### PR TITLE
NVIM_APPNAME supports relative paths

### LINKED ISSUE #23056: tempname() fails when NVIM_APPNAME is set to subdirectory
### Problem

When `NVIM_APPNAME` contains a subdirectory, tempname() fails to return anything. For example, I store all of my nvim configs in `$HOME/nvim-profiles` and use an alias to run nvim with the the `NVIM_APPNAME` variable set. However, any plugins that rely on `tempname()` to generate a temporary directory are not able to run properly. 

Before `NVIM_APPNAME`, I just set the various `XDG_HOME` variables using the following shell script, and everything worked fine:
<details>
<summary>Shell Script</summary>

```shell
#!/bin/sh
NVIM_PROFILE_NAME=""
NVIM_COMMAND="nvim"

exec env XDG_CONFIG_HOME="$HOME/.config/nvim-profiles/${NVIM_PROFILE_NAME}" \
         XDG_DATA_HOME="$HOME/.local/share/nvim-profiles/${NVIM_PROFILE_NAME}" \
         XDG_STATE_HOME="$HOME/.local/state/nvim-profiles/${NVIM_PROFILE_NAME}" \
         XDG_CACHE_HOME="$HOME/.cache/nvim-profiles/${NVIM_PROFILE_NAME}" \
         ${NVIM_COMMAND} \
         "$@"
```

</details>

### Steps to reproduce
1. Run the following commands in terminal
```shell
cd $HOME
NVIM_APPNAME="some_directory/TestVim" nvim
```
2. execute "echo tempname()" in neovim
3. Nothing gets returned
4. Run `NVIM_APPNAME="TestVim" nvim`
5. `tempname()` returns a temporary directory path

### Expected behavior

I would expect `tempname()` to return the path to a temporary directory:

Screen Recording 2023-04-12 at 1 50 51 PM

Interestingly enough, calling the alias in the `~/.local/state` directory allows tempname() to return a directory. No clue why this happens.

Screen_Recording_2023-04-12_at_12 39 51_PM

### Neovim version (nvim -v)

NVIM v0.10.0-dev-46+ge23c6ebed

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.3

### Terminal name/version

Kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

bob

### LINKED ISSUE #24966: NVIM_APPNAME disallows paths
### Discussed in https://github.com/neovim/neovim/discussions/24954

<div type='discussions-op-text'>

<sup>Originally posted by **doctorfree** August 31, 2023</sup>
Neovim 0.9 introduced `NVIM_APPNAME` as a way to specify the location of the configuration folder, rather than always using `~/.config/nvim`. I maintain a project that installs, initializes, and manages multiple Neovim configurations using this feature.

In version 0.9 it is possible to specify a path like `neovim/my-cool-config` as the `NVIM_APPNAME` environment variable value. This is especially nice if you have a lot of Neovim configurations to manage, put them all in a subdirectory of `~/.config`.

However, nightly Neovim has removed this capability. With nightly if you use a path for `NVIM_APPNAME` then you get an error message and nvim exits. The issue where this was decided indicates that `NVIM_APPNAME` was never intended to support paths, simply and strictly the name of a subdirectory in `~/.config`.

I do not know what the history or reasoning or intent was with implementation of this feature. But it was working pretty nicely and now it's not. What reasons do people have for disallowing support of a path in `NVIM_APPNAME`?</div>

### PR DESCRIPTION
**Pull request by RoryNesbitt**
This is a minimum viable product to allow paths in `NVIM_APPNAME`. It is enough to fix #23056 and close #24966

The current implementation means a user with multiple configs will end up with a lot of messy directories that may not be clear they relate to neovim (depending on what the appname they used once and then forgot about was).

Allowing the appname to include sub-directories would mean that they can choose to group all these together,
e.g.
```
NVIM_APPNAME="neovim-configs/first-config" nvim
NVIM_APPNAME="neovim-configs/second-config" nvim
```
It would also allow the user to clone someones dotfiles repo and then reach the config without moving it from the repo (this is a key part to how [dotfyle-cli](https://github.com/rorynesbitt/dotfyle-cli) works),
e.g.
```
git clone git@github.com:user/dotfiles ~/.config/user/dotfiles
NVIM_APPNAME="user/dotfiles/.config/nvim" nvim
```

I am looking for feedback about what else would need to be included in this for it to be merged.
I don't know c but I'm willing to do what I can if pointed in the right direction

From the relevant issue:
- ~updated stdpath logic in various places~
- [x] update to the docs
- [x] block the inclusion of `../` in the appname

### CODE REVIEW

**Comment by RoryNesbitt** [comment]
The new appname check looks for the equivalent of`/../`, `^../`, or `/..$`     (or `\\`)
This means that if someone for whatever reason has .. in the middle of a valid filename then that will still work, it will only get blocked when it is being used to mean parent directory.

This should mean that `XDG_xx` variables are still correctly made use of, but still allow for subdirectories. In which case are the other two changes still required?

**Comment by justinmk** [comment]
Please always say clearly what problem is being solved, and give an example. 

The first obvious question is, if `NVIM_APPNAME=$HOME/t` then what are `stdpath('config')` and `stdpath('cache')` expected to return? 

> In which case are the other two changes still required?

re "updated stdpath logic in various places": for example, `stdpath('config')` and `stdpath('cache')` are currently assumed (correctly) to be separate directories. But if `NVIM_APPNAME` can be set to an absolute path then that falls apart. Neither Nvim nor plugins can reason about "the cache directory" if it's the same directory as "the config directory". 

### Other notes:

- > The new appname check looks for the equivalent of`/../`, 
    - Instead of checking for ".." literally, can the path be resolved to an unambiguous, absolute path--which is then compared with the umabiguous, absolute form of CWD or its parent? That should be more robust. Though I don't remember if we have a robust "normalize" function internally, yet.
- If this PR ends up being viable then it would need tests, e.g. the [discussion](https://github.com/neovim/neovim/discussions/24954#discussioncomment-6870419) mentions `tempname()`.

**Comment by RoryNesbitt** [comment]
> Please always say clearly what problem is being solved, and give an example.

I've updated the original comment

> The first obvious question is, if `NVIM_APPNAME=$HOME/t` then what are `stdpath('config')` and `stdpath('cache')` expected to return?

This is an interesting question and not something I was planning to support here. The idea behind checking for `..` is that it has to remain a subdirectory of the normal `stdpath('config')` and `stdpath('cache')` etc
I suppose the extension of this logic is to also make sure the appname doesn't start with a path separator, `$HOME/t` would become `/home/user/t` and therefore the initial `/` would throw the error.

> re "updated stdpath logic in various places": for example, `stdpath('config')` and `stdpath('cache')` are currently assumed (correctly) to be separate directories. But if `NVIM_APPNAME` can be set to an absolute path then that falls apart. Neither Nvim nor plugins can reason about "the cache directory" if it's the same directory as "the config directory".

Again, this is not the intention of this pr


>  * Instead of checking for ".." literally, can the path be resolved to an unambiguous, absolute path (which is then compared with the umabiguous, absolute form of CWD or its parent)? That should be more robust. Though I don't remember if we have a robust "normalize" function internally, yet.

It was suggested to me that I make use of realpath to check the actual location of the directory. Although this would mean symlinks to strange places would not work and my personal opinion on that is if the user is symlinking they probably have a reason for it (like gnu stow). So my check deliberately stuck to the idea of "what does the string look like" not "where does the resulting directory rest".
I am of course open to differing opinions from the more wise

> * If this PR ends up being viable then it would need tests, e.g. the [discussion](https://github.com/neovim/neovim/discussions/24954#discussioncomment-6870419) mentions `tempname()`.

I shall make sure to add tests. `tempname()` should be the only thing really effected,,I think

**Comment by RoryNesbitt** [comment]
> The first obvious question is, if NVIM_APPNAME=$HOME/t then what are stdpath('config') and stdpath('cache') expected to return?

After some testing I don't think this is actually a problem (although I would still block it because it could cause confusion).

When I set the appname to this I don't get anything put in `/home/rory/t` I get `/home/rory/.local/state/home/rory/t` etc.
I am inferring from this that an absolute path is never actually possible and since linux treats `//` like `/` it will "just work". But I would not expect it to just work on windows, in fact I don't even know if the check I added would work on windows

**Comment by RoryNesbitt** [comment]
I'm not entirely sure if that's the best way to do the tests, I based them on the one that was already there.
Also the old test suggests that `\\` should be read as a `PATHSEP` but I'm assuming that would only be windows? in which case maybe I should seperate the tests with `if is_os('win') then` and test for both `/` and `\\` options

**Comment by RoryNesbitt** [comment]
Hey @justinmk , I think I've addressed all your issues, would appreciate another look when you get the time.

Things I'm anticipating, but I'm not sure about:
- Move the updated test that makes sure incorrect appnames are ignored to a separate test, rather than the one it was in before when it was a simpler check? If so where would you want it?
- rebase the commits to be shorter, or would you squash them all together? Maybe something like 
- - fix(tempname): substitute PATHSEP for '_' in directory name
- - feat(NVIM_APPNAME): allow relative paths
- - test(options/defaults_spec): add tests for NVIM_APPNAME as a path

File: src/nvim/os/stdpaths.c [hunk 1]
```diff
@@ -69,13 +69,19 @@ const char *get_appname(void)
...
 
-/// Ensure that APPNAME is valid. In particular, it cannot contain directory separators.
+// Ensure that APPNAME is valid. In particular, it cannot contain .. surrounded
+// by path separators, the start of the string, or the end of the string.
 bool appname_is_valid(void)
 {
   const char *appname = get_appname();
   const size_t appname_len = strlen(appname);
+  if (appname[0] == PATHSEP) {
+    return false;
```
Comment (justinmk) [inline src/nvim/os/stdpaths.c:79]: `path_is_absolute`

File: src/nvim/os/stdpaths.c [hunk 2]
```diff
@@ -69,13 +69,19 @@ const char *get_appname(void)
...
+  }
   for (size_t i = 0; i < appname_len; i++) {
```
Comment (justinmk) [inline src/nvim/os/stdpaths.c:81]: is the for-loop still needed?

File: test/functional/options/defaults_spec.lua [hunk 3]
```diff
@@ -616,10 +616,25 @@ describe('stdpath()', function()
 
     -- Check that Nvim rejects invalid APPNAMEs
     -- Call jobstart() and jobwait() in the same RPC request to reduce flakiness.
-    eq(1, exec_lua([[
-      local child = vim.fn.jobstart({ vim.v.progpath }, { env = { NVIM_APPNAME = 'a/b\\c' } })
-      return vim.fn.jobwait({ child }, 3000)[1]
-    ]]))
+    local function runAppnameTest(testAppname, expectedExitCode)
```
Comment (justinmk) [inline test/functional/options/defaults_spec.lua:619]:
```suggestion
    local function test_appname(testAppname, expectedExitCode)
```

**Comment by justinmk** [comment]
> as per the ci checks, would you want something about this in news?

yes. also `:help NVIM_APPNAME` will need to say "must be a name or relative path"

> local waitTime = (expectedExitCode == -1) and 100 or 3000 This works, but do we actually care about wasting time in tests?

test time matters very much, we'll need to find a better approach

File: src/nvim/os/stdpaths.c (hunk 2 above)
Comment (RoryNesbitt) [reply src/nvim/os/stdpaths.c:81]: The for loop is specifically for `..` as although absolute paths can't be used you can do the equivalent by setting appname to `../../../../../effectively/absolute/path`

File: src/nvim/os/stdpaths.c (hunk 1 above)
Comment (RoryNesbitt) [reply src/nvim/os/stdpaths.c:79]: I'm not sure what you're meaning here, do you want me to set that variable instead of the early return?

**Comment by RoryNesbitt** [comment]
> yes. also `:help NVIM_APPNAME` will need to say "must be a name or relative path"

Added both these things

> test time matters very much, we'll need to find a better approach

The idea behind that line of code was that if we expect nvim to error with that appname set then it would happen very quickly anyway, and 3000 was the timeout used on the previous check incase it didn't. However, if we expect nvim to accept the appname then we will always be waiting for the timeout to occur, so I made it much shorter. 
I fear to say "it works on my machine" but an alternative option is to keep the timeout always at 100. My tests still get the correct results with that set

File: src/nvim/os/stdpaths.c (hunk 1 above)
Comment (justinmk) [reply src/nvim/os/stdpaths.c:79]: i'm saying `path_is_absolute` should be used instead of checking `appname[0] == PATHSEP`

Comment (RoryNesbitt) [reply src/nvim/os/stdpaths.c:79]: I did not know that was an option, that would have saved such a headache yesterday.
Thanks for the info :smile: updated it

File: src/nvim/os/stdpaths.c (hunk 2 above)
Comment (RoryNesbitt) [reply src/nvim/os/stdpaths.c:81]: I double checked just in case, the new test will fail if the for loop is taken out

**Comment by RoryNesbitt** [comment]
I done the rebase to appease the commit linter. Hope that's chill :smile:

File: runtime/doc/news.txt [hunk 4]
```diff
@@ -169,6 +169,8 @@ The following new APIs and features were added.
 • |vim.lsp.util.locations_to_items()| sets the `user_data` of each item to the
   original LSP `Location` or `LocationLink`.
 
+• |$NVIM_APPNAME| environment variable now supports being set to a relative path
```
Comment (justinmk) [inline runtime/doc/news.txt:172]:
```suggestion
• |$NVIM_APPNAME| can be set to a relative path instead of only a name.
```

File: src/nvim/fileio.c [hunk 5]
```diff
@@ -3309,7 +3309,13 @@ static void vim_mktempdir(void)
     // "/tmp/" exists, now try to create "/tmp/nvim.<user>/".
     add_pathsep(tmp);
 
-    const char *appname = get_appname();
+    // Make a copy of the appname to avoid modifying it
+    char appname[40] = { 0 };
+    xstrlcpy(appname, get_appname(), sizeof(appname));
+    // Substitute slashes in appname with underscores
+    memchrsub(appname, '/', '_', sizeof(appname));
+    memchrsub(appname, '\\', '_', sizeof(appname));
```
Comment (justinmk) [inline src/nvim/fileio.c:3317]: Should we use `%` since that is what is used for other things like undofiles ? Could also reduce the chances of accidental conflicts.

```suggestion
    memchrsub(appname, '/', '%', sizeof(appname));
    memchrsub(appname, '\\', '%', sizeof(appname));
```

File: src/nvim/fileio.c [hunk 6]
```diff
@@ -3309,7 +3309,13 @@ static void vim_mktempdir(void)
     // "/tmp/" exists, now try to create "/tmp/nvim.<user>/".
     add_pathsep(tmp);
 
-    const char *appname = get_appname();
+    // Make a copy of the appname to avoid modifying it
+    char appname[40] = { 0 };
```
Comment (justinmk) [inline src/nvim/fileio.c:3313]: where is 40 coming from?

File: src/nvim/os/stdpaths.c [hunk 7]
```diff
@@ -69,13 +69,19 @@ const char *get_appname(void)
   return env_val;
 }
 
-/// Ensure that APPNAME is valid. In particular, it cannot contain directory separators.
+// Ensure that APPNAME is valid. In particular, it cannot contain .. surrounded
+// by path separators, the start of the string, or the end of the string.
```
Comment (justinmk) [inline src/nvim/os/stdpaths.c:73]: No reason to allow ".." at all. That simplifies both the documentation and the logic.

```suggestion
// Ensure that APPNAME is valid. Must be a name or relative path.
```

File: src/nvim/os/stdpaths.c [hunk 8]
```diff
@@ -69,13 +69,19 @@ const char *get_appname(void)
...
   const size_t appname_len = strlen(appname);
+  if (path_is_absolute(appname)) {
+    return false;
+  }
   for (size_t i = 0; i < appname_len; i++) {
-    if (appname[i] == PATHSEP) {
+    if (appname[i] == '.' && appname[i + 1] == '.'
+        && (i == 0 || appname[i - 1] == PATHSEP)
+        && (appname[i + 2] == '\0' || appname[i + 2] == PATHSEP)) {
       return false;
```
Comment (justinmk) [inline src/nvim/os/stdpaths.c:85]: Can we get rid of the for-loop, and just return false if `..` is found anywhere in the string?

File: src/nvim/fileio.c (hunk 5 above)
Comment (RoryNesbitt) [reply src/nvim/fileio.c:3317]: That makes sense, it's currently `_` because that's the same change that's made to [name, just above](https://github.com/neovim/neovim/blob/master/src/nvim/fileio.c#L3294-L3297).
If we were to change this here I would suggest changing both

File: test/functional/options/defaults_spec.lua [hunk 9]
```diff
@@ -914,3 +929,14 @@ describe('stdpath()', function()
     end)
   end)
 end)
+
+describe('tempname()', function()
+  describe('returns a string', function()
```
Comment (justinmk) [inline test/functional/options/defaults_spec.lua:934]: don't need a new describe() for this, it should be sibling to the other test above

File: src/nvim/fileio.c (hunk 6 above)
Comment (RoryNesbitt) [reply src/nvim/fileio.c:3313]: Similar to the above comment, I heavily referenced the way name worked when writing this 
[Seen here](https://github.com/neovim/neovim/blob/master/src/nvim/fileio.c#L3292)

File: src/nvim/os/stdpaths.c (hunk 7 above)
Comment (RoryNesbitt) [reply src/nvim/os/stdpaths.c:73]: What if a user has a directory name like `nvim..configs`? It's weird, I don't like it, but it's a valid dir name

File: src/nvim/os/stdpaths.c (hunk 8 above)
Comment (RoryNesbitt) [reply src/nvim/os/stdpaths.c:84]: This makes sense but would fail for instances of `..dir` or `dir..`. Although these must be very niche cases so I'd be comfortable overlooking them

Comment (RoryNesbitt) [reply src/nvim/os/stdpaths.c:84]: To cover those I could check for 
```
/../
^../
/..$
^..$
```
This is pretty much what the for loop checks for but would be clearer

Comment (justinmk) [reply src/nvim/os/stdpaths.c:84]: NVIM_APPNAME is a completely controllable value, there's no reason we need to support weird cases. Better for the logic to be simpler where possible.

File: test/functional/options/defaults_spec.lua (hunk 9 above)
Comment (RoryNesbitt) [reply test/functional/options/defaults_spec.lua]: I'm not sure how to word the check but I've moved it into place

Comment (RoryNesbitt) [reply test/functional/options/defaults_spec.lua]: Took me way too long to realise I could use `PATHSEPSTR` to make this just work.

I also added a check for `APPNAME == "."` I feel that would break things

File: src/nvim/os/stdpaths.c (hunk 8 above)
Comment (RoryNesbitt) [reply src/nvim/os/stdpaths.c]: Took me way too long to realise I could use PATHSEPSTR to make this just work.

I also added a check for APPNAME == "." I feel that would break things

File: src/nvim/fileio.c [hunk 10]
```diff
@@ -3309,7 +3309,13 @@ static void vim_mktempdir(void)
...
+    xstrlcpy(appname, get_appname(), sizeof(appname));
+    // Substitute slashes in appname with underscores
```
Comment (justinmk) [inline src/nvim/fileio.c:3315]:
```suggestion
    // Replace slashes, in case appname is a relative path.
```

File: src/nvim/os/stdpaths.c [hunk 11]
```diff
@@ -69,15 +69,16 @@ const char *get_appname(void)
   return env_val;
 }
 
-/// Ensure that APPNAME is valid. In particular, it cannot contain directory separators.
+// Ensure that APPNAME is valid. Must be a name or relative path.
```
Comment (justinmk) [inline src/nvim/os/stdpaths.c:72]:
```suggestion
/// Ensure that APPNAME is valid. Must be a name or relative path.
```

File: src/nvim/os/stdpaths.c [hunk 12]
```diff
@@ -69,15 +69,16 @@ const char *get_appname(void)
...
 {
   const char *appname = get_appname();
-  const size_t appname_len = strlen(appname);
-  for (size_t i = 0; i < appname_len; i++) {
-    if (appname[i] == PATHSEP) {
-      return false;
-    }
+  if (path_is_absolute(appname)
+      || strcmp(appname, ".") == 0
+      || strcmp(appname, "..") == 0
```
Comment (justinmk) [inline src/nvim/os/stdpaths.c:78]:
```suggestion
      || strequal(appname, ".")
      || strequal(appname, "..")
```

File: src/nvim/os/stdpaths.c [hunk 13]
```diff
@@ -69,15 +69,16 @@ const char *get_appname(void)
...
+      || strstr(appname, PATHSEPSTR"..") != NULL
+      || strstr(appname, ".."PATHSEPSTR) != NULL) {
```
Comment (justinmk) [inline src/nvim/os/stdpaths.c:80]: unfortunately this fails on windows bc of the way PATHSEPSTR is defined: https://github.com/neovim/neovim/blob/5ea5812714bcbeb6a5438c80d410984ad4fbb922/src/nvim/ascii.h#L81

let's just do this for now (both "/" and "\\" need to be checked on Windows, unless we "normalize" appname before this code is reached):

```suggestion
#ifdef BACKSLASH_IN_FILENAME
      || strstr(appname, "\\..") != NULL
      || strstr(appname, "..\\") != NULL)
#endif
      || strstr(appname, "/..") != NULL
      || strstr(appname, "/..") != NULL) {
```

File: test/functional/options/defaults_spec.lua [hunk 14]
```diff
@@ -616,10 +616,33 @@ describe('stdpath()', function()
...
+    -- APPNAMEs that should be accepted
+    test_appname('a/b', -1)
+    test_appname('a/b/c', -1)
+  end)
+
+  it('tempname() succeeds when $NVIM_APPNAME is a path', function()
+      clear({env={
+        NVIM_APPNAME=alter_slashes('a/b'),
+      }})
+      funcs.tempname() -- should not crash
```
Comment (justinmk) [inline test/functional/options/defaults_spec.lua:645]: use `assert_alive()` after this, or ideally check for the actual value (the above test already has an approach to do that)

Comment (RoryNesbitt) [reply test/functional/options/defaults_spec.lua:645]: The thing that's throwing me with this is that my test gives it `/home/rory/Documents/projects/neovim/build/Xtest_tmpdir/a%b.rory/J4qGVP/0`
Is there a variable for `Xtest_tmpdir` that I just can't find?

Comment (RoryNesbitt) [reply test/functional/options/defaults_spec.lua]: Okay so I fixed that by setting `TMPDIR`, but setting `USER` did nothing, I for sure thought `USER` was the obvious one
I'll try fix it in a bit

File: test/functional/core/fileio_spec.lua
Comment (RoryNesbitt) [inline test/functional/core/fileio_spec.lua:1]: This test works better than the previous, but I have to be honest I don't know if it's the best option, It's based on the surrounding tests

Comment (RoryNesbitt) [reply test/functional/core/fileio_spec.lua:1]: I somehow put it in the wrong place when I rebased but the comment still remains

**Comment by RoryNesbitt** [comment]
Hey @justinmk , hope you had a good weekend 😊 

I think, if you're happy with the new test, that this is ready to merge, would appreciate your opinion on that.

I've also made the substitution change further up on a different branch (`_` to `%` for the username) and run the tests, all of which came back successful.
I don't think there's a need in PRing that one, though, since it's literally changing 2 characters only, unless you want another test added to cover that too

**Comment by justinmk** [comment]
Pushed an update.

**Comment by RoryNesbitt** [comment]
Had a look through your changes, it all makes sense and the `matches` check is more like what I wanted but didn't know what to use :)
The review about hard coding 3000 is not something I have a strong opinion on one way or the other, just thought it should be noted.

With that all being said I am happy with the PR when you are

**Comment by justinmk** [comment]
CI failures are unrelated. asan failure is https://github.com/neovim/neovim/issues/23762

File: src/nvim/os/stdpaths.c [hunk 15]
```diff
@@ -69,15 +69,23 @@ const char *get_appname(void)
...
   const char *appname = get_appname();
-  const size_t appname_len = strlen(appname);
-  for (size_t i = 0; i < appname_len; i++) {
-    if (appname[i] == PATHSEP) {
-      return false;
-    }
+  if (path_is_absolute(appname)
+      // TODO(justinmk): on Windows, path_is_absolute says "/" is NOT absolute. Should it?
+      || strequal(appname, "/")
+      || strequal(appname, "\\")
```
Comment (justinmk) [inline src/nvim/os/stdpaths.c:79]: `path_is_absolute` should possibly be changed to consider "/" absolute on Windows, but not sure what the blast radius is so not fixing it in this PR.

**Comment by dundargoc** [comment]
let's goooo!

**Comment by RoryNesbitt** [comment]
Thanks for the help justin. Really happy to see this feature officially supported now :smile:
