### PR TITLE
[RFC] memline: fix segfaults

### LINKED ISSUE #1836: Segfault after loading swap file with Recover.vim
Recover.vim is https://github.com/chrisbra/Recover.vim

This looks like it might be very specific to my setup, not sure, i'm just going to dump the details of how it happens right now and try to narrow it down later.

```
[dx@bolsa test/bitlbee/bitlbee]$ vim protocols/account.c
```

This results in no apparent response, it looks like it's dead. Pressing enter does nothing. Pressing ctrl-c gets the usual swap recovery screen:

Pressing enter or ctrl-c makes it segfault:

If i press two ctrl-c fast enough, the contents of the file are shown for roughly half a second and then it segfaults.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fc0781c39ae in realloc () from /usr/lib/libc.so.6
(gdb)
(gdb) bt
#0  0x00007fc0781c39ae in realloc () from /usr/lib/libc.so.6
#1  0x00000000004e6175 in xrealloc (ptr=0x7fff00000000, size=<optimized out>) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/memory.c:129
#2  0x000000000056e3ab in dynamic_buffer_ensure (buf=buf@entry=0x7fff9b772f50, desired=<optimized out>) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/shell.c:276
#3  0x000000000056e579 in system_data_cb (rstream=0x16ef480, data=<optimized out>, eof=<optimized out>) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/shell.c:286
#4  0x000000000056ba8f in read_cb (rstream=<optimized out>, data=0x16f3f70, eof=<optimized out>) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/job.c:442
#5  0x000000000056d79d in read_cb (stream=0x16f42d0, cnt=3, buf=<optimized out>) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/rstream.c:364
#6  0x00007fc078c24b94 in ?? () from /usr/lib/libuv.so.1
#7  0x00007fc078c254dc in ?? () from /usr/lib/libuv.so.1
#8  0x00007fc078c29cda in uv.io_poll () from /usr/lib/libuv.so.1
#9  0x00007fc078c1d3f7 in uv_run () from /usr/lib/libuv.so.1
#10 0x000000000056c9e0 in loop (run_mode=UV_RUN_ONCE) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/event.c:196
#11 0x000000000056ccc4 in event_poll (ms=ms@entry=3569) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/event.c:122
#12 0x000000000056db11 in input_poll (ms=ms@entry=4000) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/input.c:301
#13 0x000000000056db87 in inbuf_poll (ms=4000) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/input.c:317
#14 0x000000000056debb in os_inchar (buf=buf@entry=0x7f9d41 <typebuf_init+1> "", maxlen=maxlen@entry=87, ms=ms@entry=-1, tb_change_cnt=tb_change_cnt@entry=2) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/input.c:100
#15 0x00000000004a6888 in inchar (buf=0x7f9d41 <typebuf_init+1> "", maxlen=263, wait_time=-1, tb_change_cnt=2) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/getchar.c:2497
#16 0x00000000004a8680 in vgetorpeek (advance=advance@entry=1) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/getchar.c:2317
#17 0x00000000004a888b in vgetc () at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/getchar.c:1396
#18 0x00000000004a8c6f in safe_vgetc () at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/getchar.c:1516
#19 0x000000000051a6f5 in normal_cmd (oap=oap@entry=0x7fff9b7754d0, toplevel=toplevel@entry=true) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/normal.c:491
#20 0x000000000050e49c in main_loop (cmdwin=cmdwin@entry=0, noexmode=noexmode@entry=0) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/main.c:748
#21 0x000000000051052d in main (argc=<optimized out>, argv=<optimized out>) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/main.c:534
```

The [valgrind output](http://dump.dequis.org/wUU3W.txt) seems uninteresting but running it under valgrind stops it from crashing. Still gets the black screen but doesn't crash afterwards.

Backtrace when attaching gdb to neovim at the point where i need to press ctrl-c:

```
(gdb) bt
#0  0x00007f2cc86540d9 in syscall () from /usr/lib/libc.so.6
#1  0x00007f2cc90545ea in uv.epoll_wait () from /usr/lib/libuv.so.1
#2  0x00007f2cc9052e4a in uv.io_poll () from /usr/lib/libuv.so.1
#3  0x00007f2cc90463f7 in uv_run () from /usr/lib/libuv.so.1
#4  0x000000000056c9e0 in loop (run_mode=UV_RUN_ONCE) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/event.c:196
#5  0x000000000056ccc4 in event_poll (ms=ms@entry=-1) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/event.c:122
#6  0x000000000056c1f3 in job_wait (job=job@entry=0x2371ca0, ms=ms@entry=-1) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/job.c:305
#7  0x000000000056e9dc in shell (cmd=0x236d520 "TERM=vt100 LC_ALL=C vim -u NONE -es -V  'protocols/account.c'", extra_args=extra_args@entry=0x0, input=input@entry=0x0, len=0, output=output@entry=0x7fff27c58348,
    nread=nread@entry=0x7fff27c58350, silent=true, forward_output=false) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/shell.c:242
#8  0x000000000056ebd5 in os_system (cmd=<optimized out>, input=input@entry=0x0, len=<optimized out>, output=output@entry=0x7fff27c58348, nread=nread@entry=0x7fff27c58350)
    at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/os/shell.c:176
#9  0x0000000000454131 in get_system_output_as_rettv (argvars=0x7fff27c58470, rettv=0x7fff27c58ab0, retlist=retlist@entry=false) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:14641
#10 0x0000000000454203 in f_system (argvars=<optimized out>, rettv=<optimized out>) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:14689
#11 0x0000000000459faf in call_func (funcname=funcname@entry=0x237695b "system(cmd)", len=len@entry=6, rettv=rettv@entry=0x7fff27c58ab0, argcount=argcount@entry=1, argvars=argvars@entry=0x7fff27c58470, firstline=firstline@entry=1,
    lastline=1, doesrange=0x7fff27c58654, evaluate=1, selfdict=0x0) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:6945
#12 0x000000000045d2a5 in get_func_tv (name=0x237695b "system(cmd)", len=6, rettv=rettv@entry=0x7fff27c58ab0, arg=arg@entry=0x7fff27c58a58, firstline=1, lastline=1, doesrange=0x7fff27c58654, evaluate=1, selfdict=0x0)
    at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:6779
#13 0x000000000045b9b1 in eval7 (arg=arg@entry=0x7fff27c58a58, rettv=rettv@entry=0x7fff27c58ab0, evaluate=evaluate@entry=1, want_string=want_string@entry=0) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:4123
#14 0x000000000045bbb7 in eval6 (arg=arg@entry=0x7fff27c58a58, rettv=rettv@entry=0x7fff27c58ab0, evaluate=evaluate@entry=1, want_string=want_string@entry=0) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:3833
#15 0x000000000045be3d in eval5 (arg=arg@entry=0x7fff27c58a58, rettv=rettv@entry=0x7fff27c58ab0, evaluate=evaluate@entry=1) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:3685
#16 0x000000000045c13c in eval4 (arg=arg@entry=0x7fff27c58a58, rettv=rettv@entry=0x7fff27c58ab0, evaluate=evaluate@entry=1) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:3429
#17 0x000000000045c9d2 in eval3 (arg=arg@entry=0x7fff27c58a58, rettv=rettv@entry=0x7fff27c58ab0, evaluate=evaluate@entry=1) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:3349
#18 0x000000000045caed in eval2 (arg=arg@entry=0x7fff27c58a58, rettv=rettv@entry=0x7fff27c58ab0, evaluate=evaluate@entry=1) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:3286
#19 0x000000000045cc05 in eval1 (arg=arg@entry=0x7fff27c58a58, rettv=rettv@entry=0x7fff27c58ab0, evaluate=evaluate@entry=1) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:3219
#20 0x000000000045d7ef in eval0 (arg=0x237695b "system(cmd)", rettv=rettv@entry=0x7fff27c58ab0, nextcmd=nextcmd@entry=0x7fff27c58b48, evaluate=1) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:3181
#21 0x00000000004622e6 in ex_let (eap=0x7fff27c58b40) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:1370
#22 0x00000000004f00a2 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7fff27c591c8, sourcing=sourcing@entry=1, cstack=cstack@entry=0x7fff27c58d20, fgetline=fgetline@entry=0x462e22 <get_func_line>, cookie=cookie@entry=0x2371470)
    at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/ex_docmd.c:1919
#23 0x00000000004f0a16 in do_cmdline (cmdline=<optimized out>, cmdline@entry=0x0, fgetline=fgetline@entry=0x462e22 <get_func_line>, cookie=cookie@entry=0x2371470, flags=flags@entry=7)
    at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/ex_docmd.c:621
#24 0x00000000004598b9 in call_user_func (fp=fp@entry=0x2374230, argcount=argcount@entry=0, argvars=argvars@entry=0x7fff27c595c0, rettv=rettv@entry=0x7fff27c597a0, firstline=firstline@entry=1, lastline=lastline@entry=1, selfdict=0x0)
    at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:18731
#25 0x0000000000459efa in call_func (funcname=funcname@entry=0x2376c60 "recover#ConfirmSwapDiff", len=len@entry=23, rettv=rettv@entry=0x7fff27c597a0, argcount=argcount@entry=0, argvars=argvars@entry=0x7fff27c595c0,
    firstline=firstline@entry=1, lastline=1, doesrange=0x7fff27c5979c, evaluate=1, selfdict=0x0) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:6920
#26 0x000000000045d2a5 in get_func_tv (name=name@entry=0x2376c60 "recover#ConfirmSwapDiff", len=23, rettv=rettv@entry=0x7fff27c597a0, arg=arg@entry=0x7fff27c597b8, firstline=1, lastline=1, doesrange=0x7fff27c5979c, evaluate=1,
    selfdict=0x0) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:6779
#27 0x0000000000460b3d in ex_call (eap=0x7fff27c59850) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/eval.c:2694
#28 0x00000000004f00a2 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7fff27c59ed8, sourcing=sourcing@entry=1, cstack=cstack@entry=0x7fff27c59a30, fgetline=fgetline@entry=0x48cf57 <getnextac>, cookie=cookie@entry=0x7fff27c59f80)
    at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/ex_docmd.c:1919
#29 0x00000000004f0a16 in do_cmdline (cmdline=<optimized out>, cmdline@entry=0x0, fgetline=fgetline@entry=0x48cf57 <getnextac>, cookie=cookie@entry=0x7fff27c59f80, flags=flags@entry=7)
    at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/ex_docmd.c:621
#30 0x000000000048c520 in apply_autocmds_group (event=event@entry=EVENT_SWAPEXISTS, fname=0x2333f20 "/home/dx/test/bitlbee/bitlbee/protocols/account.c", fname_io=fname_io@entry=0x0, force=force@entry=0, group=group@entry=-3,
    buf=buf@entry=0x0, eap=0x0) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/fileio.c:6740
#31 0x000000000048c8a9 in apply_autocmds (event=event@entry=EVENT_SWAPEXISTS, fname=<optimized out>, fname_io=fname_io@entry=0x0, force=force@entry=0, buf=buf@entry=0x0)
    at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/fileio.c:6356
#32 0x0000000000484c3f in do_swapexists (buf=buf@entry=0x205cf30, fname=fname@entry=0x2333f80 "/home/dx/.vim/tmp/account.c.swp") at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/memline.c:3232
#33 0x00000000004893a8 in findswapname (buf=buf@entry=0x205cf30, dirp=dirp@entry=0x7fff27c5a538, old_fname=old_fname@entry=0x0) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/memline.c:3382
#34 0x000000000048975c in ml_open_file (buf=0x205cf30) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/memline.c:512
#35 0x0000000000489875 in check_need_swap (newfile=newfile@entry=1) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/memline.c:556
#36 0x000000000048e662 in readfile (fname=0x205f290 "protocols/account.c", sfname=<optimized out>, from=from@entry=0, lines_to_skip=lines_to_skip@entry=0, lines_to_read=lines_to_read@entry=2147483647, eap=eap@entry=0x0, flags=1)
    at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/fileio.c:621
#37 0x00000000004b28e7 in open_buffer (read_stdin=read_stdin@entry=0, eap=eap@entry=0x0, flags=flags@entry=0) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/buffer.c:153
#38 0x000000000050e946 in create_windows (parmp=parmp@entry=0x7fff27c5a8f0) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/main.c:1701
#39 0x0000000000510316 in main (argc=<optimized out>, argv=<optimized out>) at /home/dx/test/asd/bezel/neovim-git/src/neovim-git/src/nvim/main.c:446
```
Frame `#25` suggests blaming [Recover.vim](https://github.com/chrisbra/Recover.vim)

Distro: Arch linux
[.nvimrc](http://dump.dequis.org/uyZOf.txt)
[neovim-git PKGBUILD modified for debug symbols](http://dump.dequis.org/UuHhK.txt)
[/home/dx/test/bitlbee/bitlbee/protocols/account.c](http://dump.dequis.org/IwHfo.c)
[/home/dx/.vim/tmp/account.c.swp](http://dump.dequis.org/PwUxO.swp)

### PR DESCRIPTION
**Pull request by justinmk**
- regression by 42f1bd9
- closes #1836
- fixed another segfault from  00f18e2e09af35494d0b94ae76a9dbc3e0319d89
- ported legacy test  78, which is related to swapfile/recovery

todo:
- [x] delete old test78
- [ ] another (no. 3) segfault: https://github.com/neovim/neovim/issues/2019#issuecomment-75370337
- [ ] E309: https://github.com/neovim/neovim/pull/1805#issuecomment-91271069

### CODE REVIEW

**Comment by aktau** [comment]
LGTM, nice catch :). It clearly looks like those two lines after the `else` belong(ed) together and possibly got mixed up by some automatic tool. Strange.

File: src/nvim/memline.c [hunk 1]
```diff
@@ -1571,16 +1552,10 @@ static time_t swapfile_info(char_u *fname)
 
 static int recov_file_names(char_u **names, char_u *path, int prepend_dot)
 {
```
Comment (oni-link) [inline src/nvim/memline.c]: We could add `FUNC_ATTR_NONNULL_ALL`.

Comment (justinmk) [inline src/nvim/memline.c]: :+1:

**Comment by jszakmeister** [comment]
*nudge*  Is there anything left to do here?  Just the `FUNC_ATTR_NONNULL_ALL` bit?

**Comment by Pyrohh** [comment]
Is the core of this change just the missing braces? If the other commits aren't needed or ready (given the `WIP` in one of the names). Then perhaps just that braces change could be commited.

**Comment by philix** [comment]
@aktau if the preprocessor test didn't succeed (almost never the case) the two lines inside a brace were just a normal block that didn't belong to an `else`.

I probably removed them thinking they were a leftover of some of my refactorings that simply removed the `if (out of memory)` text leaving the `{` block untouched.

It turns out that leaving orphan blocks was a safer strategy, but I started removing them after some negative review feedback. Removed too much though :)

@justinmk that's an incredible catch. Thanks for fixing and sorry for introducing it.

**Comment by philix** [comment]
Illustration for my comment above:
screen shot 2015-03-31 at 12 50 53 am

File: src/nvim/memline.c [hunk 2]
```diff
@@ -1253,8 +1253,10 @@ void ml_recover(void)
       mf_put(mfp, hp, false, false);
     mf_close(mfp, false);           /* will also free(mfp->mf_fname) */
   }
-  free(buf->b_ml.ml_stack);
-  free(buf);
+  if (buf != NULL) { //may be NULL if swap file not found.
```
Comment (justinmk) [inline src/nvim/memline.c]: Segfault occurs because fname_used may be null on line 836, then `buf` is never initialized.

File: src/nvim/memline.c [hunk 3]
```diff
@@ -1330,53 +1332,35 @@ recover_names (
...
 
-    // check for out-of-memory
-    for (int i = 0; i < num_names; ++i) {
-      if (names[i] == NULL) {
-        for (int j = 0; j < num_names; ++j)
-          free(names[j]);
-        num_names = 0;
-        break;
-      }
-    }
```
Comment (justinmk) [inline src/nvim/memline.c]: Also removing this OOM check.

**Comment by justinmk** [comment]
Reason this PR was held up is because I was trying to write a test, and decided to port test 78 since it is related, and ran into another segfault, plus some unrelated issues.

**Comment by justinmk** [comment]
You can reproduce the other segfault like this:

    :recover foo

Since foo isn't an existing swapfile, it will crash. Reason this wasn't caught by the tests is that the tests always work with actually existing swapfiles.

**Comment by justinmk** [comment]
This is ready for review if anyone wants to comment. I'm going to add one more test, then merge.

File: src/nvim/memline.c (hunk 2 above)
Comment (Pyrohh) [inline src/nvim/memline.c]: Should be two spaces after `{`.

I think it might be a good idea to clean up files so we can take them off of `clint-ignored-files.txt`, but of course later.

File: test/functional/helpers.lua [hunk 4]
```diff
@@ -49,6 +53,10 @@ end
 
 local session, loop_running, loop_stopped, last_error
 
+local function set_session(s)
+  session = s
+end
```
Comment (justinmk) [inline test/functional/helpers.lua]: @bfredl @tarruda This is a temporary hack to allow multiple spawned sessions in a single test. After this PR I plan to refactor helpers.lua into a module with a `new()` constructore so that a test can control multiple sessions. Does that sound ok?

Another thing that would be useful (for testing swapfiles) is ability to `kill -9` the session. Any nice way to do that? I see that `loop.c` in the lua client [does not send signals](https://github.com/neovim/lua-client/blob/master/nvim/loop.c#L58).

File: test/functional/ex_cmds/recover_spec.lua [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+    feed('isometext<esc>')
+    execute('preserve')
+    source('redir => g:swapname | swapname | redir END')
+
+    local swappath1 = eval('g:swapname')
+
+    --TODO(justinmk): this is an ugly hack to force `helpers` to support
+    --multiple sessions.
+    local nvim2 = helpers.spawn({helpers.nvim_prog, '-u', 'NONE', '--embed'})
+    helpers.set_session(nvim2)
```
Comment (justinmk) [inline test/functional/ex_cmds/recover_spec.lua]: To control a session session in the same test, use the `set_session()` function. All the calls to helper functions in the rest of this test refer to that second session. This is pretty ugly, so I plan to refactor helpers.lua shortly.

File: test/functional/helpers.lua (hunk 4 above)
Comment (tarruda) [inline test/functional/helpers.lua]: > After this PR I plan to refactor helpers.lua into a module with a new() constructor so that a test can control multiple sessions. Does that sound ok?

:+1: 

> Another thing that would be useful (for testing swapfiles) is ability to kill -9 the session. Any nice way to do that? I see that loop.c in the lua client does not send signals.

I added session:exit() to accept arguments for sending SIGTERM/SIGKILL: https://github.com/neovim/lua-client/blob/master/nvim/loop.c#L154-L156, but forgot to forward parameters from the session layer to the loop layer: https://github.com/neovim/lua-client/blob/master/nvim/session.lua#L127-L129 . It should be very simple to enable this functionality, could you send a PR to lua client?

File: test/functional/ex_cmds/recover_spec.lua (hunk 5 above)
Comment (tarruda) [inline test/functional/ex_cmds/recover_spec.lua]: It's my fault, I should have wrapped session methods into another class for the tests :disappointed:

File: test/functional/helpers.lua (hunk 4 above)
Comment (justinmk) [inline test/functional/helpers.lua]: Sure, I wasn't sure if it was intentional.
