### PR TITLE
fix(lsp): check for `vim.NIL` where needed

### LINKED ISSUE #39224: LSP: Error message when querying document symbols using python-lsp-server
### Problem

Hi there!

An error message shows when trying to look at document symbols using python-lsp-server:
```
vim.schedule callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1955: attempt to concatenate field 'containerName' (a userdata value)
stack traceback:
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1955: in function 'map_result'
        /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:294: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:180: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp/client.lua:742: in function ''
        vim/_core/editor.lua: in function <vim/_core/editor.lua:0>
```

This does not happen with any other LSP I've used recently.

The error is thrown in `vim.lsp.util.symbols_to_items()` when `symbol.containerName` is `vim.NIL`:
https://github.com/neovim/neovim/blob/43398547ec72c99ab0b90837c02de4a0add77b04/runtime/lua/vim/lsp/util.lua#L1972

Probably related to this change in 0.12:
https://github.com/neovim/neovim/blob/43398547ec72c99ab0b90837c02de4a0add77b04/runtime/doc/news.txt#L54-L55

I guess the fix is to check explicitly for `vim.NIL` instead of using the ternary operator. I don't have the time right now to familiarise myself with how to contribute that change myself but I hope this helps!

### Steps to reproduce using "nvim --clean -u minimal_init.lua"

```lua
-- minimal_init.lua
local pattern = "python"
local cmd = { "pylsp" }
local root_markers = { ".git", ".editorconfig" }
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd("FileType", {
	pattern = pattern,
	callback = function(args)
		local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
		local root_dir = match and vim.fn.fnamemodify(match, ":p:h") or nil
		vim.lsp.start({
			name = "pylsp",
			cmd = cmd,
			root_dir = root_dir,
			settings = settings,
		})
	end,
})

vim.lsp.set_log_level("debug")
```

1. Open Neovim `nvim --clean -u minimal_init.lua`.
2. Open an empty python file `:e test.py`.
3. Query document symbols `gO`.
4. Observe "No document symbols found".
5. Add code to the python file `import os`.
6. Query document symbols `gO`.
7. Observe the error message as above.

### Expected behavior

It should display the symbols as expected.

### Nvim version (nvim -v)

v0.12.1

### Language server name/version

python-lsp-server 1.14.0-2

### Operating system/version

arch linux

### Log file

https://gist.github.com/mariusz-tang/78d362b2d7a2372469db6de9c1b32303

### LINKED ISSUE #39400: LSP: Completion request cancelation errors when server returns `vim.NIL` in `result.items` as response
### Problem

When completion request returns:
```
{
  -- ...
  items = vim.NIL,
  -- ...
}
```
then request cancellation function errors:
```
vim.schedule callback: /usr/share/nvim/runtime/lua/vim/lsp/completion.lua:1006: attempt to get length of local 'result' (a userdata value)
stack traceback:
        /usr/share/nvim/runtime/lua/vim/lsp/completion.lua:1006: in function 'callback'
        /usr/share/nvim/runtime/lua/vim/lsp/completion.lua:591: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp/client.lua:742: in function ''
        vim/_core/editor.lua: in function <vim/_core/editor.lua:0>
```

due to line
```
      if result and #(result.items or result) > 0 then
```
not having a check for `vim.NIL`

### Steps to reproduce using "nvim --clean -u minimal_init.lua"

`minimal_init.lua`:
```
vim.cmd [[ edit a.c ]]
vim.fn.append(0, "int main() { r }")
vim.lsp.start({ name = 'clangd', cmd = { 'clangd' } })
vim.lsp.start({ name = 'ctags', cmd = { 'ctags-lsp' } })
vim.cmd [[ norm! kfr ]]
vim.cmd [[ startinsert ]]
```
After launching, trigger omnifunc

### Expected behavior

_No response_

### Nvim version (nvim -v)

* `v0.12.2`
* `v0.13.0-dev-321+gf83d0b9653`

### Language server name/version

ctags-lsp

### Operating system/version

Arch

### Log file

_No response_

### PR DESCRIPTION
**Pull request by superatomic**
Fixes #39224.
Fixes #39400.

Out of scope for this PR but I think we'll want to update the type annotations to include the possibility of these values being `vim.NIL`.

### CODE REVIEW

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -1964,13 +1965,13 @@ function M.symbols_to_items(symbols, bufnr, position_encoding)
       local end_lnum = range['end'].line + 1
       local end_col = get_line_byte_from_position(bufnr, range['end'], position_encoding) + 1
 
-      local is_deprecated = symbol.deprecated
-        or (symbol.tags and vim.tbl_contains(symbol.tags, protocol.SymbolTag.Deprecated))
+      local is_deprecated = not_nil(symbol.deprecated or nil)
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/util.lua:1968]: I don't think that treating `nil` as equivalent to `vim.NIL` is correct here. The former is meant to represent `symbol.deprecated = nil` while the latter means that `symbol` doesn't have a `deprecated` property. Those are treated differently in LSP and we should handle them differently here as well. This was why we went through the hassle of https://github.com/neovim/neovim/pull/34849.

`symbol` here is of type `lsp.DocumentSymbol|lsp.SymbolInformation|lsp.WorkspaceSymbol`. The first 2 variants support `deprecated?: boolean`, while `lsp.WorkspaceSymbol` doesn't have a `deprecated` field at all. In the case of `symbol.tags`, the field is either missing or set to an array. The current code would incorrectly accept servers setting `symbol.tags = nil`.

So I would write this as:
```lua
      local is_deprecated = (symbol.deprecated ~= vim.NIL and symbol.deprecated)
        or (symbol.tags ~= vim.NIL and vim.tbl_contains(symbol.tags, protocol.SymbolTag.Deprecated))
```

File: runtime/lua/vim/lsp/util.lua [hunk 2]
```diff
@@ -1964,13 +1965,13 @@ function M.symbols_to_items(symbols, bufnr, position_encoding)
...
+        or (not_nil(symbol.tags) and vim.tbl_contains(symbol.tags, protocol.SymbolTag.Deprecated))
       local text = string.format(
         '[%s] %s%s%s',
         kind,
         symbol.name,
-        symbol.containerName and ' in ' .. symbol.containerName or '',
+        not_nil(symbol.containerName) and ' in ' .. symbol.containerName or '',
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/util.lua:1974]:
```suggestion
        symbol.containerName ~= vim.NIL and ' in ' .. symbol.containerName or '',
```

File: runtime/lua/vim/lsp/util.lua (hunk 1 above)
Comment (superatomic) [reply runtime/lua/vim/lsp/util.lua:1968]: `not_nil(symbol.deprecated or nil)` is just checking that it's not `nil`, `vim.NIL`, or `false` (hence the `or nil`).

It already accepted servers setting `symbol.tabs == nil` (and `false`). Are you staying that was a bug?

File: runtime/lua/vim/lsp/util.lua (hunk 2 above)
Comment (superatomic) [reply runtime/lua/vim/lsp/util.lua:1974]: This doesn't work. It needs to check both `nil` and `vim.NIL`. For example, lua_ls, with just `symbol.containerName ~= vim.NIL`:

```
vim.schedule callback: /home/liv/src/neovim//runtime/lua/vim/lsp/util.lua:1974: attempt to concatenate field 'containerName' (a nil value)
stack traceback:
	/home/liv/src/neovim//runtime/lua/vim/lsp/util.lua:1974: in function 'map_result'
	/home/liv/src/neovim//runtime/lua/vim/lsp/handlers.lua:294: in function 'handler'
	/home/liv/src/neovim//runtime/lua/vim/lsp/buf.lua:208: in function 'handler'
	/home/liv/src/neovim//runtime/lua/vim/lsp/client.lua:757: in function 'fn'
	/home/liv/src/neovim//runtime/lua/vim/_core/editor.lua:273: in function </home/liv/src/neovim//runtime/lua/vim/_core/editor.lua:272>
```

File: runtime/lua/vim/lsp/util.lua (hunk 1 above)
Comment (MariaSolOs) [reply runtime/lua/vim/lsp/util.lua:1968]: > It already accepted servers setting `symbol.tabs == nil` (and `false`). Are you staying that was a bug?

Yes

File: runtime/lua/vim/lsp/util.lua (hunk 2 above)
Comment (MariaSolOs) [reply runtime/lua/vim/lsp/util.lua:1974]: What server sets `containerName` to `nil`?

Comment (superatomic) [reply runtime/lua/vim/lsp/util.lua:1974]: That was `lua-language-server`.

From personally testing the LSPs I have installed, this also applies to:
- `rust-analyzer`
- `json-lsp`
- `fish-lsp`
- `bash-language-server`
- `clangd`

The only language server I have installed that sets `containerName` to `vim.NIL` is `python-lsp-server`.

Comment (MariaSolOs) [reply runtime/lua/vim/lsp/util.lua:1974]: Oh right, if `symbol` isn't a `WorkspaceSymbol` then `symbol.containerName` will be `nil`.

File: runtime/lua/vim/lsp/util.lua (hunk 1 above)
Comment (superatomic) [reply runtime/lua/vim/lsp/util.lua:1968]: > So I would write this as:
> 
> ```lua
>       local is_deprecated = (symbol.deprecated ~= vim.NIL and symbol.deprecated)
>         or (symbol.tags ~= vim.NIL and vim.tbl_contains(symbol.tags, protocol.SymbolTag.Deprecated))
> ```

Yeah, so this doesn't work either:

```
vim.schedule callback: /home/liv/src/neovim//runtime/lua/vim/_core/shared.lua:336: t: expected table, got nil
stack traceback:
	[C]: in function 'error'
	/home/liv/src/neovim//runtime/lua/vim/_core/shared.lua:1315: in function 'validate'
	/home/liv/src/neovim//runtime/lua/vim/_core/shared.lua:336: in function 'tbl_contains'
	/home/liv/src/neovim//runtime/lua/vim/lsp/util.lua:1971: in function 'map_result'
	/home/liv/src/neovim//runtime/lua/vim/lsp/handlers.lua:294: in function 'handler'
	/home/liv/src/neovim//runtime/lua/vim/lsp/buf.lua:208: in function 'handler'
	/home/liv/src/neovim//runtime/lua/vim/lsp/client.lua:757: in function 'fn'
	/home/liv/src/neovim//runtime/lua/vim/_core/editor.lua:273: in function </home/liv/src/neovim//runtime/lua/vim/_core/editor.lua:272>
```

Comment (MariaSolOs) [reply runtime/lua/vim/lsp/util.lua:1968]: I see. My main point is:

> I don't think that treating `nil` as equivalent to `vim.NIL` is correct here. The former is meant to represent `symbol.deprecated = nil` while the latter means that `symbol` doesn't have a `deprecated` property. Those are treated differently in LSP and we should handle them differently here as well. This was why we went through the hassle of #34849.

Depending on the possible types of `symbol` here, we should check if it's `nil` or `vim.NIL`. The current code would incorrectly accept invalid server responses.

Comment (superatomic) [reply runtime/lua/vim/lsp/util.lua:1968]: > The current code would incorrectly accept invalid server responses.

This functionally just casts `vim.NIL`s to `nil`s for both of these checks, which I believe should be handled the same in this specific case. I understand that #34849 was very important and allowed for logic which distinguishes between the two, but I'm not sure we want to handle these cases any differently here.

File: runtime/lua/vim/_core/util.lua [hunk 3]
```diff
@@ -129,4 +129,11 @@ function M.term_exitcode()
   return ''
 end
 
+--- Returns false if value is `nil` or `vim.NIL`
+---
+--- @return boolean
+function M.not_nil(value)
```
Comment (justinmk) [inline runtime/lua/vim/_core/util.lua]: nit/nonblocker: ~~would isnil be more readable?~~

note that this has some overlap with `F.if_nil` (which needs to be renamed...), but that doesn't currently support `vim.NIL`. so perhaps we should make this a similar thing that also supports `vim.NIL`.

File: runtime/lua/vim/lsp/util.lua (hunk 1 above)
Comment (justinmk) [reply runtime/lua/vim/lsp/util.lua]: > The current code would incorrectly accept invalid server responses.

As a compromise, we could at least show a better error message since we've already done the work here.

Otherwise, is there a blocker remaining?

Comment (superatomic) [reply runtime/lua/vim/lsp/util.lua]: > As a compromise, we could at least show a better error message since we've already done the work here.

I'm not sure we can do this. Even if passing `nil` (nothing) is incorrect behavior for servers and they should be passing `vim.NIL` (`null`), many of them send `nil`. A nicer error message would be great, but I think it's probably better to let this behavior slide.

I also haven't looked at the spec so I don't know if this field is optional or not.

> Otherwise, is there a blocker remaining?

Not for me, no.

**Comment by ofseed** [comment]
> Out of scope for this PR but I think we'll want to update the type annotations to include the possibility of these values being `vim.NIL`.

This is related to the JSON-RPC layer; currently, we have only manually annotated some of the JSON-RPC types. In #38525, I added the complete JSON-RPC types, including this `vim.NIL`.

**Comment by justinmk** [comment]
This fixes 2 bugs, let's unblock it. If there is a followup needed we can do that but I don't see a major risk here.

**Comment by glepnir** [comment]
#39400 it's  not a bug and it shouldn't be treated as one.

**Comment by justinmk** [comment]
oops, I forgot that this also address https://github.com/neovim/neovim/issues/39400 

@superatomic this needs a rebase

File: runtime/lua/vim/_core/util.lua (hunk 3 above)
Comment (justinmk) [reply runtime/lua/vim/_core/util.lua]: I think it probably does make sense to change this to `isnil`, otherwise we end up with things like `not not_nil()`. Right?

That also aligns with `isarray`, `islist`, and prepares this for adding to public stdlib.

Comment (superatomic) [reply runtime/lua/vim/_core/util.lua]: Can do! I liked `not_nil()` because a lot of use cases will involve writing `not isnil()` anyway. But consistency with `isarray` and `islist` is a good idea, and `not not_nil()` is really ugly.

After I make this change, should I open a PR to add this to the stdlib?

Comment (justinmk) [reply runtime/lua/vim/_core/util.lua]: > After I make this change, should I open a PR to add this to the stdlib?

maybe, but i think we should wrap that up with renaming / deprecated `F.lua` ... 😓

Comment (superatomic) [reply runtime/lua/vim/_core/util.lua]: I can work on deprecating `vim.F` if you want.

Comment (superatomic) [reply runtime/lua/vim/_core/util.lua]: I'm working on deprecating `vim.F` right now. Are there any functions that you think should be migrated out of the `vim.F` namespace (`vim.F.npcall()` being the most useful looking one, which can be moved to `vim.npcall()`), or should they just all be deprecated with no replacement?
