### PR TITLE
fix(treesitter): avoid computing foldlevels for reloaded buffer

### LINKED ISSUE #32210: SwapExists error breaks treesitter highlighting
### Problem

When `foldexpr` is set to `v:lua.vim.treesitter.foldexpr()`, and the default SwapExists autocmd is disabled, `:edit`ing a file already open in another nvim instance multiple times causes treesitter highlighting to break.

### Steps to reproduce

1. Save the below config script as `minimal.lua`
2. Run `nvim --clean -u minimal.lua minimal.lua`
3. Open a second terminal window, without closing the first one
4. Run `nvim --clean -u minimal.lua minimal.lua` again in the second terminal window
5. Press `e` to Edit anyway
6. Run `:e` and press `e` to Edit anyway
7. Repeat 6 until the syntax highlighting in the file breaks, this usually happens on the second time for me. At this point, running `:lua vim.treesitter.stop()` brings back regex syntax highlighting and `:lua vim.treesitter.start()` disables it, but the treesitter-based highlighting is not enabled again.

```lua
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"

vim.api.nvim_del_augroup_by_name("nvim.swapfile")

```

### Expected behavior

Treesitter highlighting should keep working.

### Nvim version (nvim -v)

v0.11.0-dev-1636+ge3e1c1e765

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

AUR

### PR DESCRIPTION
**Pull request by luukvbaal**
Fix #32210

### CODE REVIEW

**Comment by luukvbaal** [comment]
Despite despite best efforts, I was unable to write a regression test that fails, or find out how this actually breaks the highlighter.

I did find that since #31821, foldlevels aren't actually computed until the first re-edit. The first `foldexpr()` evaluation happens before `filetype` is set, so `foldinfo[bufnr].parser == nil`.

File: runtime/lua/vim/treesitter/_fold.lua [hunk 1]
```diff
@@ -261,10 +261,9 @@ end
 ---@param fn function
 local function schedule_if_loaded(bufnr, fn)
   vim.schedule(function()
-    if not api.nvim_buf_is_loaded(bufnr) then
-      return
+    if foldinfos[bufnr] and api.nvim_buf_is_loaded(bufnr) then
```
Comment (lewis6991) [inline runtime/lua/vim/treesitter/_fold.lua:264]: Conceptually I think this should be done inside of `fn()`, so at the call sites to `schedule_if_loaded`.

Comment (luukvbaal) [reply runtime/lua/vim/treesitter/_fold.lua:264]: Both checks or just the newly added one?

Comment (lewis6991) [reply runtime/lua/vim/treesitter/_fold.lua:264]: Just the new one. Otherwise this function isn't needed at all.

Comment (luukvbaal) [reply runtime/lua/vim/treesitter/_fold.lua:264]: Both checks are quite similar though, `foldinfos[bufnr]` is only `nil` _because_ the buffer was unloaded (but reloaded before `foldexpr()` is evaluated again). Doesn't it make sense to keep them together?

Comment (lewis6991) [reply runtime/lua/vim/treesitter/_fold.lua:264]: Wrapping vim.schedule with a guard to check the buffer is loaded/valid is a common idiom I've used in a few plugins, so I'd imagine as we do more async this could eventually be generalized. `foldinfo` is state specific to this module, so IMO it makes sense to try and decouple that from this kind of logic. Not a big deal though.

**Review by lewis6991 — APPROVED** [review]

**Comment by ribru17** [comment]
> I did find that since #31821, foldlevels aren't actually computed until the first re-edit. The first `foldexpr()` evaluation happens before `filetype` is set (if `'foldexpr'` is set in init.lua), so `foldinfo[bufnr].parser == nil`. Doesn't seem easy to avoid without regressing #27422, was this considered @ribru17?

Interesting... I had not seen this sadly so I never considered it. Maybe the solution here is to go back to always calling get_parser(), and memoize get_parser() now that we can clear certain cache values?
