### PR TITLE
[RDY] Fix for missing output (#4569, ...)

### LINKED ISSUE #4569: Part of the asynchronous job output is cut off
- Neovim version: NVIM 0.1.4-dev
- [x] Vim behaves differently? Yes, issue does not exist
    - Vim version: 7.4.712

- Operating system/version: Xubuntu 15.10
- Terminal name/version: terminator, xterm, xfce4-terminal
- `$TERM`: `xterm`

### Actual behaviour
When using neomake plugin (https://github.com/benekastah/neomake) I'm experiencing the problem that when the linter report is long, the results are shown only for the part of a file. Neomake && Vim run without this issue. It seems that in my case this is caused by the asynchronous job output being cut to 64KB. So, when the linter output is 100KB, 36KB is cut off. When it's, say, 150KB, in my case 128KB will be OK with 22KB cut off, so it works okay up to multiplicands of 64KB as it seems.

I've tested it with some simple text file and simple vim script and it confirms that the output is cut. Just part of the file (which corresponds to 64KB) is shown. I don't know if that's intended for some reason or if there is some fix / workaround. I don't know Vim / Neovim source code and maybe I'm missing something obvious. If so - I'm sorry (and thanks for pointing out my possible mistake / misconfiguration).

### Expected behaviour

The output is not cut off. All the job output can be processed.

### Steps to reproduce using `nvim -u NONE`

1. `nvim -u NONE -S ./vimtest.vim`

I attach two files zipped: vimtest.vim and file.txt - example text file to be processed.
[nvim_test.zip](https://github.com/neovim/neovim/files/217609/nvim_test.zip)

### PR DESCRIPTION
**Pull request by oni-link**
process.c: Process termination closes streams too early 
 shell.c: Fix missing output 

Some tests fail for me, but so do the tests for upstream. Not sure what is wrong. Testing with Travis CI.

Fixes #4569

### CODE REVIEW

**Comment by oni-link** [comment]
Only test that fails/hangs is `test/functional/legacy/command_count_spec.lua`, but it also hangs on upstream.

**Comment by justinmk** [comment]
Still WIP?

**Comment by oni-link** [comment]
@justinmk, I wanted to remove the teardown check [here](https://github.com/neovim/neovim/pull/4646/files#diff-89f96344a6610f20b684b4d71368eaabR373), but without it, the event loop could be called recursively. So with the check in place, perhaps there could be some data loss when nvim exits and does not check the open streams.

I also have a local commit that wraps around long lines for `:!cmd` output, but this could wait for another PR.

Otherwise it is ready for RFC (and feedback how it works on different systems).

**Comment by oni-link** [comment]
`tempfile_spec.lua` fix removed and some commits squashed.

**Comment by justinmk** [comment]
@oni-link Any chance you could write a test for this? This fix is valuable, and we really don't want to regress it.

File: src/nvim/event/process.c [hunk 1]
```diff
@@ -333,9 +333,47 @@ static void process_close(Process *proc)
...
+    }
+  }
+}
+
 static void process_close_handles(void **argv)
 {
   Process *proc = argv[0];
+
+  // Did our process forked a child that keeps the output streams open?
+  if (!process_is_tearing_down) {
```
Comment (justinmk) [inline src/nvim/event/process.c]: How about a TODO here mentioning "there could be some data loss when nvim exits and does not check the open streams."

**Comment by oni-link** [comment]
> @oni-link Any chance you could write a test for this? This fix is valuable, and we really don't want to regress it.

I tried, but I did not get very far (screen test problems). My manuel tests were

`:!cat file.txt` " in upstream second half of output is lost
`:so vimtest.vim` " in upstream second half of output is lost
`:call system('xclip -i -selection clipboard','data')` " check that changes can handle child process that keeps the streams open after parent terminated


I used `file.txt` from [#4569](https://github.com/neovim/neovim/files/217609/nvim_test.zip) and modified script  `vimtest.vim`
```vim
function! s:JobHandler(job_id, data, event)
  echo a:job_id .", ".string(a:data) .", " .a:event
  endfunction

let s:callbacks = {
    \ 'on_stdout': function('s:JobHandler'),
    \ 'on_stderr': function('s:JobHandler'),
    \ 'on_exit': function('s:JobHandler')
    \ }

let job1 = jobstart(['bash', '-c', 'cat file.txt'], s:callbacks)

```

File: src/nvim/event/process.c (hunk 1 above)
Comment (oni-link) [inline src/nvim/event/process.c]: After commit fixup2 there should only be data loss for a child process that keeps the streams open.  Otherwise something like this
`:!./a.out` with `a.out` from
```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main(int argc, char *argv[])
{
  pid_t cpid = fork();

  if (cpid == -1) {
    perror("fork");
    exit(EXIT_FAILURE);
  }

  if (cpid == 0) {
    char* arg[]={"/usr/bin/yes",NULL};
    execv("/usr/bin/yes",arg);

    _exit(EXIT_SUCCESS);

  } else { 
    sleep(3);
    exit(EXIT_SUCCESS);
  }
}

```
would block forever and nvim could not exit (without data loss).

**Comment by justinmk** [comment]
@oni-link I also noticed that wrapping the last line in `jobwait()` avoids the issue:

    let job1 = jobwait([jobstart(['bash', '-c', 'cat file.txt'], s:callbacks)], 3000)

However, I finally found a way to repro the issue in a test, by spawning a child nvim in a `:terminal` buffer. Working on a PR.

File: src/nvim/rbuffer.c [hunk 2]
```diff
@@ -15,7 +15,7 @@ RBuffer *rbuffer_new(size_t capacity)
   FUNC_ATTR_WARN_UNUSED_RESULT FUNC_ATTR_NONNULL_RET
 {
   if (!capacity) {
-    capacity = 0xffff;
+    capacity = 0x10000;
```
Comment (justinmk) [inline src/nvim/rbuffer.c]: @oni-link Can you explain this change?

Comment (oni-link) [inline src/nvim/rbuffer.c]: Suggested buffer size by libuv and linux pipe capacity (also a multiple of the atomic pipe buffer size (4096)).

**Comment by justinmk** [comment]
Though https://github.com/neovim/neovim/pull/4950 didn't help on CI, it fails reliably on my machine (before your PR). 

Is this PR ready?

**Comment by oni-link** [comment]
I cannot reproduce any fails when running `TEST_FILE="./test/functional/terminal/job_spec.lua"  make functionaltest` when using #4950 (without this PR).

**Comment by justinmk** [comment]
> I cannot reproduce any fails when running TEST_FILE="./test/functional/terminal/job_spec.lua" make functionaltest when using #4950 (without this PR).

Neither can travis, or quickbuild. It only seems to fail on a single machine I've tried. I'll take another look at it later.
