### PR TITLE
fix(exceptions): restore `did_throw`

### LINKED ISSUE #13490: Memory leak & no error reported from uncaught exception in autocmd
- `nvim --version`: **Latest (NVIM v0.5.0-dev+918-g4383c0f95)**
- `vim -u DEFAULTS` behaves differently? **Yes (Vim behaves correctly)**
- Operating system/version: **WSL running Ubuntu 20.04.1 LTS**
- Terminal name/version: **Windows Terminal 1.4.3243.0 / tmux 3.0a**
- `$TERM`: **`xterm-256color` / `tmux-256color`**

### Steps to reproduce using `nvim -u NORC`
Source this:
```vim
au BufWinEnter * throw 'not today'
" the try/endtry is used to also trigger the leak
try
  new
endtry
```
Alternatively, run `nvim --clean -c "au BufWinEnter * th 0" -c "try|new|endt|qa!"` with LSAN to get a quick report.

### Actual behaviour
No exception reported, plus a memory leak (unless the `try`/`endtry` is omitted).

I haven't had much time to check, but my suspicion is that PR #7881 might be the culprit.
A recursive call to `do_cmdline()` sets `current_exception` to `NULL` (`ex_docmd.c:408`),
potentially before it's handled and freed within the block starting at `ex_docmd.c:815` inside
another recursive call deeper in the stack. Commands such as `:new`, `:edit`, etc. can trigger this.

From LSAN:
```
=================================================================
==29553==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x4d558d in malloc (/home/sean/projects/3rdparty/neovim/build/bin/nvim+0x4d558d)
    #1 0x115f982 in try_malloc /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:71:15
    #2 0x115fb5c in xmalloc /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:105:15
    #3 0xd04838 in throw_exception /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_eval.c:466:10
    #4 0xd172f9 in ex_throw /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_eval.c:1153:9
    #5 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #6 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #7 0x708ffe in apply_autocmds_group /home/sean/projects/3rdparty/neovim/build/../src/nvim/autocmd.c:1611:5
    #8 0x70f317 in apply_autocmds_retval /home/sean/projects/3rdparty/neovim/build/../src/nvim/autocmd.c:1311:18
    #9 0x71b199 in open_buffer /home/sean/projects/3rdparty/neovim/build/../src/nvim/buffer.c:336:5
    #10 0xbc1794 in do_ecmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds.c:2588:24
    #11 0xcaccc9 in do_exedit /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:7232:11
    #12 0xcab964 in ex_splitview /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:6967:5
    #13 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #14 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #15 0xc3d6e1 in do_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2877:3
    #16 0xc38024 in cmd_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2547:14
    #17 0xc38735 in ex_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2528:3
    #18 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #19 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #20 0xc5a283 in do_cmdline_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:287:10
    #21 0xfd8b9b in exe_commands /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:1698:5
    #22 0xfc654a in main /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:500:5
    #23 0x7f04190010b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 33 byte(s) in 1 object(s) allocated from:
    #0 0x4d558d in malloc (/home/sean/projects/3rdparty/neovim/build/bin/nvim+0x4d558d)
    #1 0x115f982 in try_malloc /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:71:15
    #2 0x115fb5c in xmalloc /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:105:15
    #3 0x1160111 in xmallocz /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:182:15
    #4 0x116027e in xmemdupz /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:200:17
    #5 0x116180e in xstrdup /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:419:10
    #6 0x1949ade in vim_strsave /home/sean/projects/3rdparty/neovim/build/../src/nvim/strings.c:58:20
    #7 0xd04d11 in throw_exception /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_eval.c:478:22
    #8 0xd172f9 in ex_throw /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_eval.c:1153:9
    #9 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #10 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #11 0x708ffe in apply_autocmds_group /home/sean/projects/3rdparty/neovim/build/../src/nvim/autocmd.c:1611:5
    #12 0x70f317 in apply_autocmds_retval /home/sean/projects/3rdparty/neovim/build/../src/nvim/autocmd.c:1311:18
    #13 0x71b199 in open_buffer /home/sean/projects/3rdparty/neovim/build/../src/nvim/buffer.c:336:5
    #14 0xbc1794 in do_ecmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds.c:2588:24
    #15 0xcaccc9 in do_exedit /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:7232:11
    #16 0xcab964 in ex_splitview /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:6967:5
    #17 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #18 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #19 0xc3d6e1 in do_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2877:3
    #20 0xc38024 in cmd_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2547:14
    #21 0xc38735 in ex_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2528:3
    #22 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #23 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #24 0xc5a283 in do_cmdline_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:287:10
    #25 0xfd8b9b in exe_commands /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:1698:5
    #26 0xfc654a in main /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:500:5
    #27 0x7f04190010b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x4d558d in malloc (/home/sean/projects/3rdparty/neovim/build/bin/nvim+0x4d558d)
    #1 0x115f982 in try_malloc /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:71:15
    #2 0x115fb5c in xmalloc /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:105:15
    #3 0x1160111 in xmallocz /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:182:15
    #4 0x116027e in xmemdupz /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:200:17
    #5 0x116180e in xstrdup /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:419:10
    #6 0x8f7055 in eval_to_string_skip /home/sean/projects/3rdparty/neovim/build/../src/nvim/eval.c:811:14
    #7 0xd171bf in ex_throw /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_eval.c:1143:13
    #8 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #9 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #10 0x708ffe in apply_autocmds_group /home/sean/projects/3rdparty/neovim/build/../src/nvim/autocmd.c:1611:5
    #11 0x70f317 in apply_autocmds_retval /home/sean/projects/3rdparty/neovim/build/../src/nvim/autocmd.c:1311:18
    #12 0x71b199 in open_buffer /home/sean/projects/3rdparty/neovim/build/../src/nvim/buffer.c:336:5
    #13 0xbc1794 in do_ecmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds.c:2588:24
    #14 0xcaccc9 in do_exedit /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:7232:11
    #15 0xcab964 in ex_splitview /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:6967:5
    #16 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #17 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #18 0xc3d6e1 in do_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2877:3
    #19 0xc38024 in cmd_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2547:14
    #20 0xc38735 in ex_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2528:3
    #21 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #22 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #23 0xc5a283 in do_cmdline_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:287:10
    #24 0xfd8b9b in exe_commands /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:1698:5
    #25 0xfc654a in main /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:500:5
    #26 0x7f04190010b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: 91 byte(s) leaked in 3 allocation(s).
```

### Expected behaviour
This message, courtesy of Vim:
```
Error detected while processing BufWinEnter Autocommands for "*":
E605: Exception not caught: not today
```

### LINKED ISSUE #13711: Errors in BufEnter autocmd swallowed when triggered by vim.cmd("buffer ...")
- `nvim --version`: NVIM v0.5.0-dev+1012-gfe1ebea33
- `vim -u DEFAULTS` (version: ) behaves differently? Vim doesn't have `vim.cmd` or `vim.api`.
- Operating system/version: N/A
- Terminal name/version: N/A
- `$TERM`: N/A

### Steps to reproduce using `nvim -u NORC`

Create the following `bug.lua` file.
```lua
function setup_bug()
  vim.cmd [[autocmd BufEnter * lua print(0); error("error swallowed"); print(1)]]
  -- vim.cmd [[autocmd BufEnter * throw 'error swallowed']]
end
function show_bug()
  local buf = vim.api.nvim_create_buf(true, false)
  vim.api.nvim_buf_set_lines(buf, 0, -1, true, {"some text"})
  vim.cmd("buffer " .. buf)
  -- vim.cmd("doautocmd BufEnter")
end
```

Then run this command.
```
nvim -u NORC -c 'luafile bug.lua' -c 'lua setup_bug(); show_bug()'
```

### Actual behaviour

A new unnamed buffer is created with the text "some text", 0 is printed, and then the new buffer is switched to.

If you comment out line 8 and uncomment line 9 (i.e. replace `buffer` with `doautocmd`), then the error is correctly displayed. `lua error("error swallowed")` and `throw 'error swallowed'` as the autocmd both have the same behavior.

### Expected behaviour

A new unnamed buffer is created with the text "some text" and the following is printed (or similar)

```
0
Error detected while processing command line:
E5108: Error executing lua bug.lua:8: Vim(lua):E5108: Error executing lua [string ":lua"]:1: error swallowed
```

### LINKED ISSUE #18842: Exceptions are silently dropped by runtime! command used inside try/catch
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

No, 8.2.4975

### Operating system/version

CentOS 7.9

### Terminal name/version

xfce4-terminal 0.8.7.4

### $TERM environment variable

tmux-256color

### Installation

Downloaded release tarball from Github

### How to reproduce the issue

Create a temporary directory, and inside it create these 3 files:

**init.vim**
```
execute 'set runtimepath +='.expand('<sfile>:p:h')
try
  runtime! throw*.vim
  echomsg "No errors!"
catch
  throw v:exception
endtry
```

**throw1.vim**
```
echomsg "Sourcing throw1"
throw "Exception!"
```

**throw2.vim**
```
echomsg "Sourcing throw2"
```

Now run `nvim -u /path/to/init.vim` (and compare the output against `vim -N --clean -u /path/to/init.vim`)

### Expected behavior

It should print
```
Sourcing throw1
Sourcing throw2
Error detected while processing /path/to/init.vim:
line    6:
E605: Exception not caught: Exception!
```

### Actual behavior

It prints:

```
Sourcing throw1
Sourcing throw2
No errors!
```

### PR DESCRIPTION
**Pull request by seandewar**
Closes #13490
Closes #13711
Closes #18842
Also doesn't seem to regress #7876... 

`!did_throw` doesn't exactly imply `!current_exception`, as `did_throw = false`
is sometimes used to defer exception handling for later (without forgetting the
exception). E.g: uncaught exception handling in `do_cmdline()` may be deferred
to a different call (e.g: when `try_level > 0`).

In #7881, `current_exception = NULL` in `do_cmdline()` is used as an analogue of
`did_throw = false`, but also causes the pending exception to be lost, which
also leaks as `discard_exception()` wasn't used.

It may be possible to fix this by saving/restoring `current_exception`, but
handling all of `did_throw`'s edge cases seems messier. Maybe not worth
diverging over.

This fix also uncovers a `man_spec.lua` bug on Windows: exceptions are thrown
due to Windows missing `man`, but they're lost; skip these tests if `man` isn't
executable.

### CODE REVIEW

**Review by seandewar — COMMENTED** [review]
```c
assert(current_exception == NULL);
```
I don't think it will, but it _might_ be possible for this assertion to fail in `try_leave()` again, but presumably that would've regressed #7876...

**Comment by bfredl** [comment]
Pr/Issue 20000 
image

File: test/functional/plugin/man_spec.lua [hunk 1]
```diff
@@ -6,6 +6,12 @@ local funcs = helpers.funcs
 local nvim_prog = helpers.nvim_prog
 local matches = helpers.matches
 
+clear()
+if funcs.executable('man') == 0 then
+  pending('missing "man" command', function() end)
+  return
+end
+
```
Comment (zeertzjq) [inline test/functional/plugin/man_spec.lua:14]: The tests actually still work even if `man` is missing. This check can probably removed with #19912.

File: src/nvim/eval.c [hunk 2]
```diff
@@ -5985,7 +5985,7 @@ void timer_due_cb(TimeWatcher *tw, void *data)
   // Handle error message
   if (called_emsg > called_emsg_before && did_emsg) {
     timer->emsg_count++;
-    if (current_exception != NULL) {
+    if (did_throw) {
```
Comment (zeertzjq) [inline src/nvim/eval.c:5988]: This is probably not what the code here is intended to do. The corresponding code in Vim (<https://github.com/vim/vim/commit/c577d813b7978345dec4310b2d8f5d5624a681f6>) saves `did_throw` and doesn't discard exception if `did_throw` is previously set. Not sure if this can happen in Nvim though, as Nvim processes timers on the main loop.

Comment (zeertzjq) [reply src/nvim/eval.c:5988]: Oh, timers can be processed from `getchar()`. I'll try to check what should be done there.

Comment (zeertzjq) [reply src/nvim/eval.c:5988]: I still cannot find a place where `did_throw` can be `true` when `timer_due_cb()` is called.

**Review by zeertzjq — APPROVED** [review]
It is very hard to find a case where the assertion will fail. This fix can unblock several Vim patches.
