### PR TITLE
vim-patch:8.1.2073: when editing a buffer 'colorcolumn' may not work

### LINKED ISSUE #12918: Colorcolumn disappears after switching buffer
- `nvim --version`: NVIM v0.4.4
- `vim -u DEFAULTS` (version: 8.1) behaves differently? yes
- Operating system/version: macOS 10.15.5
- Terminal name/version: alacritty 0.5.0 (a6681e3)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. open a test file: `nvim -u NONE test1`
2. set colorcolumn for the current buffer: `:setlocal cc=80`
3. open a new test file: `:e test2`
4. go back to the previous buffer: `:b test1`

### Actual behaviour

The colorcolumn is no longer visible, but `:setlocal cc?` still returns `colorcolumn=80`.

### Expected behaviour

The colocolumn is still visible when switching back to `test1`.

### PR DESCRIPTION
**Pull request by zeertzjq**
#### vim-patch:8.1.2073: when editing a buffer 'colorcolumn' may not work

Problem:    When editing a buffer 'colorcolumn' may not work.
Solution:   Set the buffer before copying option values. Call
            check_colorcolumn() after copying window options.
https://github.com/vim/vim/commit/010ee9657acf1a9f799079d718998c94e50ccadc

Fix #12918

### CODE REVIEW

**Comment by zeertzjq** [comment]
The test I added fails on `master`:
```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] test/functional/ui/highlight_spec.lua @ 1203: ColorColumn highlight when entering a buffer vim-patch:8.1.2073
test/functional/ui/highlight_spec.lua:1214: Row 8 did not match.
Expected:
  |{4:  1 }11{1:1}11111{1:1}1                          |
  |{3:  2 }22{1:2}22222{1:2}22                         |
  |{3:  3 }33{1:3}33333{1:3}3                          |
  |{5:~                                       }|
  |{5:~                                       }|
  |{5:~                                       }|
  |{7:X                                       }|
  |*{4:  1 }^11{1:1}11111{1:1}1                          |
  |*{3:  2 }22{1:2}22222{1:2}22                         |
  |*{3:  3 }33{1:3}33333{1:3}3                          |
  |{5:~                                       }|
  |{5:~                                       }|
  |{5:~                                       }|
  |{6:X                                       }|
  |                                        |
Actual:
  |{4:  1 }11{1:1}11111{1:1}1                          |
  |{3:  2 }22{1:2}22222{1:2}22                         |
  |{3:  3 }33{1:3}33333{1:3}3                          |
  |{5:~                                       }|
  |{5:~                                       }|
  |{5:~                                       }|
  |{7:X                                       }|
  |*{4:  1 }^1111111111                          |
  |*{3:  2 }22222222222                         |
  |*{3:  3 }3333333333                          |
  |{5:~                                       }|
  |{5:~                                       }|
  |{5:~                                       }|
  |{6:X                                       }|
  |                                        |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	test/functional/ui/screen.lua:595: in function '_wait'
	test/functional/ui/screen.lua:362: in function 'expect'
	test/functional/ui/highlight_spec.lua:1214: in function <test/functional/ui/highlight_spec.lua:1203>


 1 FAILED TEST
```

File: src/nvim/option.c [hunk 1]
```diff
@@ -6136,6 +6135,7 @@ void win_copy_options(win_T *wp_from, win_T *wp_to)
 {
   copy_winopt(&wp_from->w_onebuf_opt, &wp_to->w_onebuf_opt);
   copy_winopt(&wp_from->w_allbuf_opt, &wp_to->w_allbuf_opt);
+  didset_window_options(wp_to);
```
Comment (seandewar) [inline src/nvim/option.c:6138]: Nvim already does this in win_init.

Comment (zeertzjq) [reply src/nvim/option.c:6176]: Thanks!

**Review by seandewar — APPROVED** [review]
