### PR TITLE
vim-patch:8.1.{35,42,64},8.2.{1781,1783,1976,2014,3671}

### LINKED ISSUE #13715: Weird prompt buffer behavior in neovim but not in vim
- `nvim --version`: 
NVIM v0.5.0-dev+1012-gfe1ebea33-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/rishabh/git/neovim/build/config -I/home/rishabh/git/neovim/src -I/home/rishabh/git/neovim/.deps/usr/include -I/usr/include -I/home/rishabh/git/neovim/build/src/nvim/auto -I/home/rishabh/git/neovim/build/include
Compiled by root@acid-burn

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
- `vim -u DEFAULTS` (version: ) behaves differently?
Yes
- Operating system/version: Arch Linux
- Terminal name/version: ST
- `$TERM`: st-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set buftype=prompt<CR>
ihello<ESC>a<BS><BS>
<ESC>Iab

```

### Actual behaviour
3rd line gives `hello` and `l` and `o` are not deleted by backspace in the buffer
4th line gives ^bahello (^ represents the position of the cursor)

### Expected behaviour
3rd line gives `hel`
4th line gives ab^hello (^ represents position of cursor)

### In terms of functional tests
```lua
  it('Insert at start using I', function()
    screen:expect([[
      ^                         |
      ~                        |
      ~                        |
      ~                        |
      [Prompt]                 |
      other buffer             |
      ~                        |
      ~                        |
      ~                        |
                               |
    ]])
    feed("i")
    feed("hello<BS><BS>")
    screen:expect([[
      % hel^                    |
      ~                        |
      ~                        |
      ~                        |
      [Prompt] [+]             |
      other buffer             |
      ~                        |
      ~                        |
      ~                        |
                               |
    ]])
    feed("<Esc>I")
    feed("ab")
    screen:expect([[
      % ab^hel                  |
      ~                        |
      ~                        |
      ~                        |
      [Prompt] [+]             |
      other buffer             |
      ~                        |
      ~                        |
      ~                        |
                               |
    ]])
  end)

end)
```

If if we put these tests in `test/functional/prompt_buffer_spec.lua`, these tests fail. However, these should not fail intuitively.

Even the actual behavior of the second test is different from what we would get in practice:
```
Expected:
  |*% ab^hel                  |
  |~                        |
  |~                        |
  |~                        |
  |[Prompt] [+]             |
  |other buffer             |
  |~                        |
  |~                        |
  |~                        |
  |                         |
Actual:
  |*% ^abhel                  |
  |~                        |
  |~                        |
  |~                        |
  |[Prompt] [+]             |
  |other buffer             |
  |~                        |
  |~                        |
  |~                        |
  |                         |
```

The actual behavior we get is `^bahel`

This is not there in case of vim.

### PR DESCRIPTION
**Pull request by seandewar**
Like #15881, aims to fix prompt buffer input issues with telescope & whatever, but by porting missing patches instead.
There's been some failed porting attempts in the past, ~~so this may also end in a fiery inferno.~~

Good news so far is that the things these patches fix seem to work properly?
~~But there's a new problem with telescope seemingly introduced by this logic in `leaving_window`~~ _Fixed; was a Vim bug._

Closes #13715; should address telescope issues like https://github.com/nvim-telescope/telescope.nvim/issues/261.
Supersedes #15881.

### CODE REVIEW

**Comment by seandewar** [comment]
https://github.com/vim/vim/commit/34c20ff85b87be587ea5d0398812441b502ee6a5

File: test/functional/legacy/prompt_buffer_spec.lua [hunk 1]
```diff
@@ -150,4 +153,13 @@ describe('prompt buffer', function()
     ]])
   end)
 
+  it('keeps insert mode after aucmd_restbuf in callback', function()
+    source [[
+      let s:buf = nvim_create_buf(1, 1)
+      call timer_start(0, {-> nvim_buf_set_lines(s:buf, -1, -1, 0, ['walrus'])})
```
Comment (Maverun) [inline test/functional/legacy/prompt_buffer_spec.lua:222]: image

**Review by janlazo — APPROVED** [review]
LGTM. Fix the merge conflict and I'll merge.
