### PR TITLE
win_redr_status(): skip if wildmenu is showing

### LINKED ISSUE #2255: wildmenu causes the statusline to appear temporarily
When a terminal window is open, `wildmenu` is on, and the statusbar isn’t visible (either `laststatus=0` or `laststatus=1` and no other window is open), tapping `wildchar` (usually `<Tab>`) causes the statusbar to appear _instead of_ the wildmenu. Tapping `wildchar` again returns everything to normal, with the second wildmenu entry selected.
## Tested on:

a6e53a3 Merge PR #2076 'Builtin terminal emulation'
## Steps to reproduce:

From a shell, run `nvim -u NONE +'set wildmenu laststatus=0' term://sh`
Then, inside nvim, type `:<Tab>`
## Expected results:

The wildmenu appears, with the first entry (`!`) selected.
## Actual results:

A statusline appears, with the text `term://.//19967:sh`. The wildmenu doesn’t appear. A `!` is correctly inserted in the command-line, but isn’t drawn until another key is presed (e.g. `<C-L>`).

### LINKED ISSUE #7108: :redrawstatus erases ex-mode completions
I was using an async timer in the background to unnecessarily redraw the status line (I'm still not sure why the status line updates constantly without it), but in doing so I discovered that an async `:redraws` command would wipe out the completions for ex mode.

Here's an example:

```vim
let s:spinner_index = 0
let s:spinner_states = ['.', 'o', 'O', '°', 'O', 'o', '.'] 
function! StartSpinner()
    let s:spinner_timer = timer_start(250, 'SpinSpinner', {'repeat': -1})
endfunction
function! SpinSpinner(timer)
    let s:spinner_index = float2nr(fmod(s:spinner_index + 1, len(s:spinner_states)))
    :redraws
endfunction
function! SpinnerStatus()
    return s:spinner_states[s:spinner_index]
endfunction
```

If you `:call StartSpinner()` and then enter ex mode and type in, say `:h<TAB>` the completions for `h` will pop up above the prompt, but at the next 250ms interval when `:redraws` is called, the completions will disappear.

```
NVIM v0.2.1-612-g3b45f676c
Build type: Release
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/Users/mqudsi/Random/neovim/build/config -I/Users/mqudsi/Random/neovim/src -I/Users/mqudsi/Random/neovim/.deps/usr/include -I/Users/mqudsi/Random/neovim/.deps/usr/include -I/Users/mqudsi/Random/neovim/.deps/usr/include -I/Users/mqudsi/Random/neovim/.deps/usr/include -I/Users/mqudsi/Random/neovim/.deps/usr/include -I/Users/mqudsi/Random/neovim/.deps/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/usr/include -I/Users/mqudsi/Random/neovim/build/src/nvim/auto -I/Users/mqudsi/Random/neovim/build/include
Compiled by mqudsi@QBook.lan

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

### PR DESCRIPTION
**Pull request by justinmk**
This might be too coarse, but it passes all tests ...

A more nuanced approach might be: only skip the windows whose
statuslines are overwritten by the wildmenu.

Closes #2255
Closes #7108

- [x] mark `vim-path:8.0.0710` N/A

### CODE REVIEW

File: test/functional/ui/wildmode_spec.lua [hunk 1]
```diff
@@ -52,6 +54,59 @@ describe("'wildmode'", function()
...
+        if helpers.pending_win32(pending) then return end
+        -- set_shell_powershell()
+        -- feed([[:terminal 1,2,3,4,5 | foreach-object -process {echo $_; sleep 0.1}]])
+      else
+        feed([[:terminal for i in $(seq 1 5000); do printf 'foo\nfoo\nfoo\n'; sleep 0.1; done<cr>]])
+      end
+      screen:sleep(50)        -- Allow some output.
+      feed([[<C-\><C-N>gg]])
+      feed([[:sign <Tab>]])   -- Invoke wildmenu.
+      screen:sleep(50)        -- Allow some output.
```
Comment (justinmk) [inline test/functional/ui/wildmode_spec.lua]: The `screen:sleep()` here and in the next test are necessary to make sure some activity was allowed. But it also causes `screen:expect()` to wait until the full timeout. @bfredl I applied https://github.com/neovim/neovim/pull/6930 and found that it fixed that issue for both of these cases.

Comment (bfredl) [inline test/functional/ui/wildmode_spec.lua]: Hmm, but the "trivial success" detection logic in #6830 might flag it as a false positive. Rather we should allow to pass the min_timeout also.

File: test/functional/ui/wildmode_spec.lua [hunk 2]
```diff
@@ -52,6 +57,59 @@ describe("'wildmode'", function()
...
+                                 |
+        ~                        |
+        ~                        |
+        define  jump  list  >    |
+        :sign define^             |
+      ]])
+    end)
+
+    it('with laststatus=0, :vsplit, :term #2255', function()
+      command('set laststatus=0 shell=sh')
```
Comment (jamessan) [inline test/functional/ui/wildmode_spec.lua]: This should either be pending on Windows or have a Windows implementation, right (due to `shell=sh`)?
