### PR TITLE
lsp reuse_win priorizies windows/tabs currently displayed

### LINKED ISSUE #36483: [LSP] reuse window always jump to the first opened window even if the buffer is already opened on the current window/tab
### Problem

LSP reuse window does not behave as good as `tab drop`, and there is no easy way for users to customize the document jumping behaviour other than directly modifying the runtime lua code.

### Steps to reproduce

Case 1:
Edit a file in split view. Call LSP jump to definition in the second window where the definition is located in the same buffer.
Expected result: scroll to the definition in the second window.
Actual result: the first window got focus and scrolled to the definition instead.

Case 2:
Edit a file and open a copy of the file in a second tab. Split the tab and open another buffer (e.g. the header file). Call LSP jump to definition in the second buffer where the definition is located in the first buffer.
Expected result: scroll to the definition in the first window of the second tab.
Actual result: the first tab got focus and scrolled to the definition instead.

### Note

Cause:
`vim/lsp/buf.lua:get_locations:on_response` implemented `reuse_win` as `w = vim.fn.win_findbuf(b)[1] or w` which forces it to always pick the first window if the buffer is opened.

Potential fix:
Replace with `tab drop` instead.
```lua
if opts.reuse_win then
  vim.cmd("tab drop " .. item.filename)
  w = vim.fn.win_getid()
end
```

### Nvim version (nvim -v)

v0.12.0-dev-1575+gded5786252

### PR DESCRIPTION
**Pull request by otomn**
Fixes: #36483

### CODE REVIEW

File: runtime/lua/vim/lsp/buf.lua [hunk 1]
```diff
@@ -243,11 +243,15 @@ local function get_locations(method, opts)
 
       vim.bo[b].buflisted = true
       local w = win
-      if opts.reuse_win then
+      if opts.reuse_win and vim.api.nvim_win_get_buf(w) ~= b then
         w = vim.fn.win_findbuf(b)[1] or w
-        if w ~= win then
-          api.nvim_set_current_win(w)
+        for _, tw in ipairs(vim.api.nvim_tabpage_list_wins(0)) do
+          if vim.api.nvim_win_get_buf(tw) == b then
```
Comment (justinmk) [inline runtime/lua/vim/lsp/buf.lua]: Can `vim.fn.bufwinid()` or some function like that be used to avoid some of this code?

Comment (otomn) [reply runtime/lua/vim/lsp/buf.lua]: Thanks for the tip. Code simplified.
