### PR TITLE
viml/profile: fix missing fixes when merging vim-patch:8.1.0130

### LINKED ISSUE #12255: Crash during profiling
- `nvim --version`: NVIM v0.5.0-d2766b0
- `vim -u DEFAULTS` (version: ) behaves differently? Does not crash.
- Operating system/version: Arch Linux

### Steps to reproduce using `nvim -u NORC`

**UPDATE 2:** In one file: [The malicious script.](https://gist.github.com/zsugabubus/60f354fa9a3ee5ae8f9435fa8388ebb8) [Repo.](https://github.com/zsugabubus/nvim-crash)

---

* `nvim -u NORC`
* Open your ‘init.vim’ (or some Vim file).
* [`packadd vim-white`](https://github.com/zsugabubus/vim-white) (will start profiling into ‘white.log’).
* [`packadd vim-commentr`](https://github.com/zsugabubus/vim-commentr).
* Press <kbd>K</kbd> on some function (maybe relevant).
* Hit <kbd>Enter</kbd> until all red goes away (`vim-white` generates a bunch of error messages, so will not call `profile stop`).
* Go back to your opened Vim file.
* <kbd>Leader</kbd><kbd>c</kbd><kbd>c</kbd>.
* Crash.

Sorry, for the little self-promotion but really this is the way it crashes. `packadd` was easy to me, but probably works as “expected” using `source` too.

**UPDATE:** commentr no longer needed. You can enjoy the never ending fun using `--cmd 'source happy.vim'`. (white still required to generate errors.)
```vim
" happy.vim
nnoremap X :call X()<CR>
fun X()
	new
	set ft=vim
endfun
```

So the one-liner:
```sh
nvim -u NORC +'h nextnonblank' --cmd 'packadd vim-white' --cmd 'source happy.vim' '+normal X'
```

---

```
 9461          for (int i = 0; i < fp->uf_lines.ga_len; ++i) {
 9462            if (FUNCLINE(fp, i) == NULL)
 9463              continue;
 9464  >>>>      prof_func_line(fd, fp->uf_tml_count[i],
 9465                &fp->uf_tml_total[i], &fp->uf_tml_self[i], TRUE);
 9466            fprintf(fd, "%s\n", FUNCLINE(fp, i));
 9467          }

[0] from 0x00005555557b14da in func_dump_profile+351 at ../src/nvim/eval.c:9464
[1] from 0x0000555555777c7d in profile_dump+49 at ../src/nvim/ex_cmds2.c:1002
[2] from 0x00005555557786c6 in ex_profile+313 at ../src/nvim/ex_cmds2.c:870
[3] from 0x0000555555770036 in do_one_cmd+5140 at ../src/nvim/ex_docmd.c:2251
[4] from 0x0000555555771db1 in do_cmdline+2681 at ../src/nvim/ex_docmd.c:615
[5] from 0x0000555555742f45 in apply_autocmds_group+1585 at ../src/nvim/fileio.c:6993
[6] from 0x0000555555743223 in apply_autocmds+23 at ../src/nvim/fileio.c:6623
[7] from 0x00005555556cafd9 in did_set_string_option+12440 at ../src/nvim/option.c:3411
[8] from 0x00005555556ce964 in do_set+5475 at ../src/nvim/option.c:1885
[9] from 0x00005555557630c1 in ex_set+34 at ../src/nvim/ex_docmd.c:9224

[2] id 50026 name nvim from 0x00007ffff7d33536
[1] id 50022 name nvim from 0x00005555557b14da in func_dump_profile+351 at ../src/nvim/eval.c:9464

i = 0
*fp = {
  uf_varargs = 0,
  uf_flags = 1,
  uf_calls = 1,
  uf_cleared = false,
  uf_args = {
    ga_len = 1,
    ga_maxlen = 3,
    ga_itemsize = 8,
    ga_growsize = 3,
    ga_data = 0x5555560785f0
  },
  uf_lines = {
    ga_len = 3,
    ga_maxlen = 3,
    ga_itemsize = 8,
    ga_growsize = 3,
    ga_data = 0x555556078630
  },
  uf_profiling = 0,
  uf_prof_initialized = 1,
  uf_tm_count = 0,
  uf_tm_total = 0,
  uf_tm_self = 0,
  uf_tm_children = 0,
  uf_tml_count = 0x0,   (<<< SIGSEGV)
  uf_tml_total = 0x0,
  uf_tml_self = 0x0,
  uf_tml_start = 0,
  uf_tml_children = 0,
  uf_tml_wait = 0,
  uf_tml_idx = -1,
  uf_tml_execed = 0,
  uf_script_ctx = {
    sc_sid = 62,
    sc_seq = 79,
    sc_lnum = 602
  },
  uf_refcount = 2,
  uf_scoped = 0x0,
  uf_name = 0x5555560787a0 "commentr#OpComment"
}
$_siginfo = {
  si_signo = 11,
  si_errno = 0,
  si_code = 1,
  _sifields = {
    _sigfault = {
      si_addr = 0x0,
      _addr_lsb = 0,
      _addr_bnd = {
        _lower = 0x0,
        _upper = 0x0
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by erw7**
fixes #12255.

This should be fine, but I couldn't figure out what path to follow to cause `SIGSEGV` by looking at `call_use_func()`.

Added: This will also fix the following problems.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:function Test()
:endfunction
:profile start log1
:profile func Test
:call Test()
:profile stop
:profile start log2
:profile func Test
:call Test()
:profile stop
```

#### log1
```
FUNCTION Test()
Called 1 times
...
```

#### log2
```
FUNCTION Test()
Called 2 times
...
```

#### log1
```
FUNCTION Test()
Called 1 times
...
```

#### log2
```
FUNCTION Test()
Called 1 times
...
```

### CODE REVIEW

File: src/nvim/ex_cmds2.c [hunk 1]
```diff
@@ -1045,9 +1045,10 @@ static void profile_reset(void)
         uf->uf_tm_self      = profile_zero();
         uf->uf_tm_children  = profile_zero();
 
-        XFREE_CLEAR(uf->uf_tml_count);
-        XFREE_CLEAR(uf->uf_tml_total);
-        XFREE_CLEAR(uf->uf_tml_self);
+        for (int i = 0; i < uf->uf_lines.ga_len; i++) {
+          uf->uf_tml_count[i] = 0;
+          uf->uf_tml_total[i] = uf->uf_tml_self[i] = 0;
+        }
```
Comment (justinmk) [inline src/nvim/ex_cmds2.c:1051]: Hmm. is this avoiding the root problem by not freeing the pointer? In https://github.com/neovim/neovim/issues/12255 it looks like `fp->uf_tml_count[i]` is NULL. So if we don't free it here, then we avoid the crash... but the profile results will be wrong?

Comment (erw7) [reply src/nvim/ex_cmds2.c:1051]: The change by vim-patch:8.1.0130 (https://github.com/neovim/neovim/commit/7823b357812b06da7348a5b4f5a66afae8f1f71c) needs to be changed to clear the memory at zero instead of freeing it. We missed it. Therefore, this change does not result in the wrong profile result.

There were other things that seemed to need fixing, so I fixed that too. I also added a test because I think the reason we missed this was that the test was incomplete.

File: test/functional/ex_cmds/profile_spec.lua [hunk 2]
```diff
@@ -23,6 +25,19 @@ local function assert_file_exists_not(filepath)
   eq(nil, lfs.attributes(filepath, 'uid'))
 end
 
+local function read_file(filepath)
```
Comment (justinmk) [inline test/functional/ex_cmds/profile_spec.lua:28]: looks similar to `test/helpers.lua`. Perhaps that one could be changed to return `msg`, then we don't need this one?

Comment (erw7) [reply test/functional/ex_cmds/profile_spec.lua]: I had overlooked that.
