### PR TITLE
fix(extmarks): make right_align and win_col work on wrapped line

### LINKED ISSUE #16634: Position virtual text at both eol and right align
### Feature already in Vim?

No.

### Feature description

`nvim_buf_set_extmark` allows virtual text to be positioned `right_aligned`. It ends up overlaying the normal text if a single line spans multiple rows, as shown like this:

``` neovim
┌───────────────────────────────────────────────────────────────────────┐
│line_too_looooooooooooooooooooooooooooooooooooooooooooooo[virtual_text]│
│ooooooooooog                                                           │
│                                                                       │
│                                                                       │
│                                                                       │
│                                                                       │
└───────────────────────────────────────────────────────────────────────┘
```

What I'm expecting is the virtual text automatically being shifted to the eol row. Just like below:

``` neovim
┌───────────────────────────────────────────────────────────────────────┐
│line_too_looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo│
│ooooooooooog                                             [virtual_text]|
│                                                                       │
│                                                                       │
│                                                                       │
│                                                                       │
└───────────────────────────────────────────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #16634

### CODE REVIEW

File: src/nvim/decoration.h [hunk 1]
```diff
@@ -82,7 +82,11 @@ typedef struct {
   Decoration decor;
   int attr_id;  // cached lookup of decor.hl_id
   bool virt_text_owned;
-  int win_col;
+  /// Screen column to draw the virtual text.
+  /// When -1, the virtual text may be drawn after deciding where.
+  /// When < -1, the virtual text shouldn't currently be drawn.
```
Comment (bfredl) [inline src/nvim/decoration.h:87]: "not currently" is not very specific. I assume it means "on a later screenline". Perhaps this could be mentioned in the comment.
