### PR TITLE
fix(ui): only internal messages are unsafe

### LINKED ISSUE #36490: `vim._extui` does not play well with some vim plugins
### Problem

`vim._extui` does not play well with some vim plugins that uses the cmdline, e.g. [vim-easyalign](https://github.com/junegunn/vim-easy-align).

When using vim-easyalign with `vim._extui` enabled, the ":EasyAlign (_)" prompt will not be shown in the message area.

### Steps to reproduce

1. Create the following `minimal.lua` file:
    ```lua
    vim
      .system({
        'git',
        'clone',
        '--depth=1',
        '--filter=blob:none',
        'https://github.com/junegunn/vim-easy-align.git',
      })
      :wait()

    require('vim._extui').enable({})

    vim.opt.rtp:append('vim-easy-align')
    vim.keymap.set(
      { 'n', 'x' },
      'gl',
      '<Plug>(EasyAlign)',
      { noremap = false, desc = 'Align text' }
    )
    ```
2. Run nvim with `nvim --clean -u minimal.lua`
3. Open a random non-empty file
4. Select a paragraph with >2 lines and hit `gl` to trigger align

### Expected behavior

":EasyAlign (_)" prompt should appear in the message area.

Without extui enabled the ":EasyAlign (_)" prompt is shown normally, but with extui the prompt is not shown in the message area.

Without extui:

Image

With extui:

Image

### Nvim version (nvim -v)

v0.12.0-dev-1574+g8d6963a6a0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

6.17.7-arch1-1

### Terminal name/version

alacritty 0.16.1 (42f49eeb) + tmux 3.5a

### $TERM environment variable

tmux-256color

### Installation

AUR

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Fast context for msg_show event inhibits vim.ui_attach from
          displaying a stream of messages from a single command.
Solution: Remove fast context from msg_show events emitted as a result
          of explicit API/command calls. The fast context was originally
          introduced to prevent issues with internal messages.

Fix #36490
Fix #36604
Close #36745

### CODE REVIEW

**Comment by luukvbaal** [comment]
This strives to maintain backwards compatibility with the way plugins show a message stream to the user. Getting it to work properly without regressing elsewhere has been a bit of a struggle😮‍💨

This originally got on my radar in #33952, which "streams" as expected with this PR:
[asciicast](https://asciinema.org/a/AwtsRFKDhEWaW31w)

Also manifested in #36243, which has since been [resolved](https://github.com/neovim/neovim/pull/37123) by @yochem with a vim.wait() which I removed again here.

#36745 and #36490 also appear to be fixed/superceded here.

File: runtime/lua/vim/health.lua [hunk 1]
```diff
@@ -383,10 +383,6 @@ local function progress_report(len)
     -- percent=0 omits the reporting of percentage, so use 1% instead
     -- progress.percent = progress.percent == 0 and 1 or progress.percent
     progress.id = vim.api.nvim_echo({ { fmt:format(...) } }, false, progress)
-    -- extui/ui2 shows all messages at once after the healthchecks are finished.
-    -- This 1ms wait ensures the messages are shown separately
-    vim.wait(1)
-    vim.cmd.redraw()
```
Comment (superatomic) [inline runtime/lua/vim/health.lua:389]: When this PR was rebased, this line (which was added in #37567) was accidentally removed.
