### PR TITLE
fix(incsearch): support `c_CTRL-{G,T}` with an offset

### LINKED ISSUE #22228: incsearch does not support {offset}
### Problem

The fact that incsearch allows ctrl-g and ctrl-t to cycle through different instances of the matched string before accepting the complete motion is awesome, particularly when used in operator-pending mode.  Say we have the following line and our cursor is at the beginning in normal mode:
`blah blah blah`
We can use `c/blah<ctrl-g><ctrl-g><enter>` to change everything up to the third "blah" (exclusive).  But what if I wanted to include the third "blah" in the change?  It seems like I should be able to make use of the {offset} (:help /) to do `c/blah/e<ctrl-g><ctrl-g><enter>` ; however ctrl-g and ctrl-t do nothing as soon as you add the second slash to specify the offset.

### Expected behavior

Desired behavior would be for ctrl-g and ctrl-t to still cycle through potential matches and once enter is pressed, any {offset} specified would be respected.  In the example above, our change would include the third "blah" (we would be in insert mode with nothing on the current line).

### PR DESCRIPTION
**Pull request by barrettruth**
## Problem

`c_CTRL-{G,T}` stop cycling once an `'incsearch'` command includes an offset such as `/blah/e`.

`do_search()` already parses the pattern and offset separately but `may_do_command_line_next_incsearch()` cycles on the raw cmdline text instead.

Partially fixes&nbsp;#22228.

## Solution

Refactor pattern/offset parsing from `do_search()` to be used in the command-line incsearch path so `c_CTRL-{G,T}` keep selecting matches.

***NOTE***: this does not fully resolve&nbsp;#22228 (see my comment).

### CODE REVIEW

File: test/functional/ui/searchhl_spec.lua [hunk 1]
```diff
@@ -576,6 +576,21 @@ describe('search highlighting', function()
...
   end)
 
+  it('works with incsearch offset and c_CTRL-G/c_CTRL-T', function()
+    feed_command('set hlsearch')
+    feed_command('set incsearch')
+    insert('blah blah blah')
+
+    feed('gg0/blah/e<C-g><cr>')
+    eq({ 0, 1, 9, 0 }, fn.getpos('.'))
+
```
Comment (barrettruth) [inline test/functional/ui/searchhl_spec.lua:581]: tested these three cases for caution but fine to remove the first/second as well

File: src/nvim/search.c [hunk 2]
```diff
@@ -1024,6 +1024,77 @@ static int first_submatch(regmmatch_T *rp)
...
+
+  int cmdlen = 0;
+  char *p;
+  char *ps = *strcopy;
+
+  *searchstr = *pat;
+  *searchstrlen = *patlen;
+  *dircp = NULL;
+
+  // Find end of regular expression.
```
Comment (barrettruth) [inline src/nvim/search.c:1043]: original impl and comments preserved exactly here

**Comment by justinmk** [comment]
Probably should this upstream to Vim too

**Review by justinmk — APPROVED** [review]

**Comment by barrettruth** [comment]
I was wondering that.

The PR should be good to merge, but perhaps we ought to wait for how vim addresses this first (I am making an issue in vim)?

**Comment by barrettruth** [comment]
I begrudgingly fixed an issue spotted by GitHub copilot on the upstream vim pr. Had devin port it over here. 

The entire PR is marked ai-assisted even though ~3 lines of code are ai-assisted and i wrote the vim fix upstream, so technically the label is accurate but i removed it from the commit msg

**Comment by justinmk** [comment]
i think we should drop the ai-assisted label, it's a nag

guess what, i used a computer to produce this text!!!11

**Comment by barrettruth** [comment]
this is ready now and i added all tests chris added to vim as well

**Review by zeertzjq — APPROVED** [review]

**Comment by barrettruth** [comment]
thanks
