### PR TITLE
Fix flaky test: "scrollback_spec: 'scrollback' option deletes lines (only) if necessary"

### LINKED ISSUE #10723: flaky test: 'scrollback' option deletes lines (only) if necessary
```
[ RUN      ] 'scrollback' option deletes lines (only) if necessary: FAIL
  test/functional\terminal\scrollback_spec.lua:458: Expected objects to be the same.
  Passed in:
  (string) 'line35'
  Expected:
  (string) 'line36'
  
  stack traceback:
  	test/functional\terminal\scrollback_spec.lua:458: in function <test/functional\terminal\scrollback_spec.lua:417>
```

Seen on AppVeyor (MSVC_32): https://ci.appveyor.com/project/neovim/neovim/builds/26530249/job/y5t74nmtujopu5ka#L6135

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/neovim/neovim/issues/10723.

### CODE REVIEW

**Comment by blueyed** [comment]
Using `screen:expect` with the complete grid appears to fix its
flakiness.

File: test/functional/terminal/scrollback_spec.lua [hunk 1]
```diff
@@ -438,13 +438,38 @@ describe("'scrollback' option", function()
...
-    eq((iswin() and '36: line' or '35: line'), eval("getline(line('w0') - 1)"))
-    eq((iswin() and '27: line' or '26: line'), eval("getline(line('w0') - 10)"))
-
+    if iswin() then
+      eq('36: line', eval("getline(line('w0') - 1)"))
+      eq('27: line', eval("getline(line('w0') - 10)"))
+    else
+      eq('35: line', eval("getline(line('w0') - 1)"))
+      eq('26: line', eval("getline(line('w0') - 10)"))
+    end
```
[the remark this answers is not in the document]
Comment (blueyed) [reply test/functional/terminal/scrollback_spec.lua]: Reverted.

File: test/functional/terminal/scrollback_spec.lua [hunk 2]
```diff
@@ -438,13 +438,38 @@ describe("'scrollback' option", function()
...
+      screen:expect{grid=[[
+        36: line                      |
+        37: line                      |
+        38: line                      |
+        39: line                      |
+        40: line                      |
+        {IGNORE}|
+        {3:-- TERMINAL --}                |
+      ]]}
+    end
```
[the remark this answers is not in the document]
Comment (blueyed) [reply test/functional/terminal/scrollback_spec.lua]: It also appears to fix the flakiness.
Probably checking for `any='{3:-- TERMINAL --}'` might also do it, but I think it's good to see it in total.

File: test/functional/terminal/scrollback_spec.lua [hunk 3]
```diff
@@ -438,9 +438,29 @@ describe("'scrollback' option", function()
...
+        {3:-- TERMINAL --}                |
+      ]]}
+    else
+      screen:expect{grid=[[
+        36: line                      |
+        37: line                      |
+        38: line                      |
+        39: line                      |
+        40: line                      |
+        {IGNORE}|
```
Comment (justinmk) [inline test/functional/terminal/scrollback_spec.lua]: is IGNORE still needed? I would think `shell-test` is predictable.

Comment (blueyed) [reply test/functional/terminal/scrollback_spec.lua]: It uses "sh" as the outer shell.
I've seen "sh-5…" so figured it might depend on the version.
No idea why there is no prompt on Windows though.

Comment (blueyed) [reply test/functional/terminal/scrollback_spec.lua]: With https://github.com/neovim/neovim/pull/11004 we could have it more explicit of course - but might still look different then when "sh" is some other shell on user systems.
So I think this is fine.
