### PR TITLE
fix(shada): update deleted marks

### LINKED ISSUE #4295: shada: "delmark" is not persisted in shada
- Neovim version:NVIM v0.1.3-133-g12938b8
- Operating system:linux
- Terminal emulator:xfce4-terminal
### Actual behaviour

if marks are deleted vim updates the .viminfo so that after reopening a file the deleted marks are NOT present anymore.
Neovim behaves different so that these marks are still present after reopening.
### Expected behaviour

Removing a marker should be updated in the main.shada on file close so that the marker is not present anymore after reopening the file. Otherwise it will remain forever in the file. You can only get rid of it if you use :wshada!.
If you use :wshada! to store the actual markers a complete new main.shada is written so you loose all the information of the other files.  
### Steps to reproduce

nvim -u NONE testfile
hack hack hack
set marker b on e.g. line 10 in command mode with:
10ggmb
close file and reopen
show marks with:
:marks
delete marker b with:
delmark b
close file and reopen
show marks again with:
:marks

### PR DESCRIPTION
**Pull request by MariaSolOs**
I'm recycling the fix from #16067 and I'll try to handle the missing bits.

Hopefully this will finally close #4295.

### CODE REVIEW

**Comment by MariaSolOs** [comment]
@ii14 I've addressed the comments you had left in the original PR. Could I please get a look here again? :)

**Comment by MariaSolOs** [comment]
Also HUGE DISCLAIMER: I'm very rusty in my C and totally unfamiliar with the logic behind this fix. Because of this I ask for a detailed review of this PR (pinging @justinmk since I see that you participated in previous discussions about this problem).

File: src/nvim/shada.c [hunk 1]
```diff
@@ -2200,8 +2207,22 @@ static inline ShaDaWriteResult shada_read_when_writing(ShaDaReadDef *const sd_re
               }
               shada_free_shada_entry(&wms_entry->data);
             }
+          } else {
+            FOR_ALL_BUFFERS(buf) {
+              if (buf->b_ffname != NULL && path_fnamecmp(entry.data.filemark.fname, buf->b_ffname) == 0) {
```
Comment (zeertzjq) [inline src/nvim/shada.c:2212]: Lint failure because this line is too long
```suggestion
              if (buf->b_ffname != NULL
                  && path_fnamecmp(entry.data.filemark.fname, buf->b_ffname) == 0) {
```

Comment (MariaSolOs) [reply src/nvim/shada.c]: Oops my bad. Thanks!
