### PR TITLE
vim-patch:9.1.{0285,0294}

### LINKED ISSUE #28250: <C-u>zz does not work on the last line, when the last line is centered, and `scrollof` set to value >0
### Problem

When the cursor is on the last line of the buffer, and the line is centered (with `zz`), `<c-u>zz` does not work - the cursor gets stuck on the last line. Preview (for a couple of seconds while the cursor is at line `87` I'm pressing `<c-u>` and nothing happens, only when I move the cursor one line up with `k` it works):

https://github.com/neovim/neovim/assets/100767853/b0809d25-d82d-475d-84fb-2f4cd13d3ecd

**Note:** I'm aware that there were some bugs and some fixes lately regarding `<c-u>` and `<c-d>` (#28160), so I guess that this issue is related.

### Steps to reproduce

minimal.lua:
```lua
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "Scroll down half screen" })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "Scroll up half screen" })
vim.opt.scrolloff = 8 -- or any value larger than 0
```
run: `nvim --clean file.txt -u minimal.lua`

### Expected behavior

Half-page jump.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2840+gc695caa7e

### Vim (not Nvim) behaves the same?

no, vim 8.2.3995 (installed using apt)

### Operating system/version

Ubuntu 22.04.4 LTS

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

wezterm

### Installation

bob (https://github.com/MordechaiHadad/bob)

### LINKED ISSUE #28251: C-d and C-u don't move the cursor half the page when viewport collides with the start/end of the file
### Problem

When the start/end of the file is a couple of lines away from the viewport, scrolling to it with C-u or C-d does appropriately scroll the view, but doesn't fully move the cursor.

https://github.com/neovim/neovim/assets/39461169/9b32ea4c-c133-4f64-ae95-9d7af4c428e8

### Steps to reproduce

nvim -u NORC

### Expected behavior

normal half page cursor move/scroll

### Neovim version (nvim -v)

v0.10.0-dev-4946489e2

### Vim (not Nvim) behaves the same?

no, vim 9.0.1544

### Operating system/version

macOS 14

### Terminal name/version

kitty 0.33.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by luukvbaal**
**vim-patch:9.1.0285: Still problems with cursor position for CTRL-D/U**

Problem:  Problems with cursor position when scrolling half a page.
Solution: Rework the cursor logic. (Luuk van Baal)

https://github.com/vim/vim/commit/78c51500f1bb16501521d721d52cb0982f5e70b6

**vim-patch:9.1.0294: Text height function does not respect it's argument**

Problem:  plines_m_win() does not take into account it's "limit_winheight"
          argument for filler lines below the last line of the buffer.
          (after v9.1.0280)
Solution: Check window height when "limit_winheight" is TRUE.
          (Luuk van Baal)

https://github.com/vim/vim/commit/08b0f632c125514fe0ea188c36ac048d7d7929d4

Fix #28250
Fix #28251

### CODE REVIEW

File: src/nvim/plines.c [hunk 1]
```diff
@@ -880,14 +880,17 @@ int plines_m_win(win_T *wp, linenr_T first, linenr_T last, bool limit_winheight)
...
     linenr_T next = first;
-    count += plines_win_full(wp, first, &next, NULL, false, limit_winheight);
+    count += plines_win_full(wp, first, &next, NULL, false, false);
     first = next + 1;
   }
   if (first == wp->w_buffer->b_ml.ml_line_count + 1) {
     count += win_get_fill(wp, first);
   }
+  if (limit_winheight && count > wp->w_height) {
+    return wp->w_height;
```
Comment (zeertzjq) [inline src/nvim/plines.c:892]:
```suggestion
  if (limit_winheight && count > wp->w_height_inner) {
    return wp->w_height_inner;
```

**Review by zeertzjq — APPROVED** [review]
