### PR TITLE
fix(startup): support .exrc or .nvimrc with init.lua

### LINKED ISSUE #13501: init.lua doesn't load "exrc" files (.nvimrc, .exrc)
- `nvim --version`: NVIM v0.5.0-dev+926-g99007bcc1
- `vim -u DEFAULTS` (version: ) behaves differently? - same
- Operating system/version: Manjaro Linux
- Terminal name/version: kitty 0.19.1
- `$TERM`: xterm-kitty

### Steps to reproduce:
```lua
--mininit.lua
vim.o.exrc = true
```

```vim
" .nvimrc in cwd
let g:test_from_nvimrc = 1
```

1. Open vim with minimal init.lua `nvim -u mininit.lua`
2. try `:echo g:test_from_nvimrc`

### Actual behaviour
Variable is undefined because `.nvimrc` is not loaded. I tried `.exrc` also, same thing.

### Expected behaviour
To print `1` in cmdline.

Edit: 
When sourcing the lua file from init.vim works.
```vim
" mininit.vim
lua require'mininit.lua'
```

```
nvim -u mininit.vim
:echo g:test_from_nvimrc
Prints 1
```

### PR DESCRIPTION
**Pull request by kristijanhusak**
Original PR: https://github.com/neovim/neovim/pull/13503
Closes #13501

Created a new PR because the old one was very outdated.

### CODE REVIEW

File: test/functional/core/startup_spec.lua [hunk 1]
```diff
@@ -576,6 +577,26 @@ describe('user config init', function()
...
+        ]])
+    end)
+
+    after_each(function()
+      os.remove(exrc_path)
+    end)
+
+    it('loads .exrc', function()
+      clear{ args_rm={'-u'}, env={ XDG_CONFIG_HOME=xconfig }}
+      feed('a') -- accept secure read prompt
```
Comment (kristijanhusak) [inline test/functional/core/startup_spec.lua:595]: This is not working, unfortunately. Does anyone know how could I accept the prompt?
I noticed that there's no exrc test at all, which might be for a reason.

Comment (zeertzjq) [reply test/functional/core/startup_spec.lua:595]: You need to attach a UI, otherwise the prompt is skipped.

Comment (zeertzjq) [reply test/functional/core/startup_spec.lua:613]: Hmm, exrc isn't enabled here, and it seems a bit tricky to enable it.

Comment (kristijanhusak) [reply test/functional/core/startup_spec.lua:613]: It should be since it's using `init_lua_path`, which has `vim.opt.exrc = true` set. Unless I'm missing something.

Comment (zeertzjq) [reply test/functional/core/startup_spec.lua:613]: Oh wait, I think here the prompt shows up and is skipped before the UI is attached. I guess the `.exrc` cannot be in the directory where `nvim` is startup in this test then. `:cd` into another directory with `.exrc` may work, but I cannot seem to get it to work either.

Comment (zeertzjq) [reply test/functional/core/startup_spec.lua:613]: Oh wait, maybe the prompt is skipped before the UI is attached. This is a bit tricky. I guess this test needs to run `nvim` in `:terminal` instead?

Comment (kristijanhusak) [reply test/functional/core/startup_spec.lua]: `:terminal` worked out, thanks!

File: test/functional/core/startup_spec.lua [hunk 2]
```diff
@@ -576,6 +577,48 @@ describe('user config init', function()
...
+      command('terminal nvim')
+      local screen = Screen.new(80, 8)
+      screen:attach()
+      screen:expect{grid=string.format([[
+        ^                                                                                |
+                                                                                        |
+                                                                                        |
+                                                                                        |
+                                                                                        |
+        %s.exrc is not trusted.                             |
```
Comment (zeertzjq) [inline test/functional/core/startup_spec.lua:609]: This depends on the path and can easily fail. If the path is too long it may also take multiple lines. You can use `any = ` and `helpers.pesc` in `screen:expect()` instead. There is an example in `test/functional/ex_cmds/swapfile_preserve_recover_spec.lua`.

Comment (kristijanhusak) [reply test/functional/core/startup_spec.lua:609]: Sure, I'll replace that. There's another issue that CI shows that I'm not sure how to tackle:

https://github.com/neovim/neovim/actions/runs/3548796299/jobs/5960439467#step:13:6990

Comment (zeertzjq) [reply test/functional/core/startup_spec.lua:609]: Use `helpers.nvim_prog` and pass arguments to it instead. Maybe `termopen()` can also be used instead of `:terminal`.

Comment (kristijanhusak) [reply test/functional/core/startup_spec.lua]: I replaced it to use `nvim_prog`. `:terminal` seems to be working fine. Do you still want me to replace it with `termopen()` ?
