### PR TITLE
test(pack): use `n.rmdir()` to delete directories

### LINKED ISSUE #39042: unreliable test: pack_spec after_each
Sometimes the vim.pack tests fail on Windows ci:

```
ERROR    test/functional/plugin/pack_spec.lua @ 415: vim.pack after_each
vim/fs.lua:735: EBUSY: resource busy or locked: D:/a/neovim/neovim/build/Xtest_xdg_plugin/share/nvim-data/site/pack/core/opt/plugindirs

stack traceback:
	vim/fs.lua:735: in function 'rm'
	vim/fs.lua:722: in function 'rm'
	vim/fs.lua:764: in function 'rm'
	test/functional/plugin\pack_spec.lua:416: in function <test/functional/plugin\pack_spec.lua:415>
```

This can happen because Windows doesn't allow file/dir deletion if the process has a handle to it.

Workaround is to use `n.rmdir()` : https://github.com/neovim/neovim/blob/53038d2c381e79fcb2ba9c7c5b2e637e3db76f6a/test/functional/testnvim.lua#L842

### PR DESCRIPTION
**Pull request by echasnovski**
Problem: using `vim.fs.rm(dir_path, { force = true, recursive = true })` can result in an error on Windows if the process has a handle to it.

Solution: Use `n.rmdir()` helper in cases when its possible side effects (like changing working directory) does not matter.

---

Resolve #39042.

### CODE REVIEW

File: test/functional/plugin/pack_spec.lua [hunk 1]
```diff
@@ -478,7 +478,7 @@ describe('vim.pack', function()
       eq(true, pack_exists('basic'))
       eq('table', type(get_lock_tbl().plugins.basic))
 
-      vim.fs.rm(pack_get_dir(), { force = true, recursive = true })
+      n.rmdir(pack_get_dir())
```
Comment (justinmk) [inline test/functional/plugin/pack_spec.lua:481]: `n.rmdir()` might have unwanted behavior in the middle of a test, because it will `cd` to try to "release" the directory handle: https://github.com/neovim/neovim/blob/e70cb6b1d88bb9b7aaa8e6e188cabb303c1905bc/test/functional/testnvim.lua#L842-L851

however, maybe we could fix this by doing a save-and-restore of CWD.

Comment (echasnovski) [reply test/functional/plugin/pack_spec.lua:481]: In most cases it is done before `n.clear()`, so should not matter. I'll revert others.

Comment (justinmk) [reply test/functional/plugin/pack_spec.lua:481]: ok, i'll see if i can improve `n.rmdir()` in a followup pr #39048
