### PR TITLE
fix(defaults): omit extraneous info from unimpaired mapping errors

### LINKED ISSUE #30625: Improve error handling for new unimpaired mappings
Pressing `]q` at the end of the quickfix list shows:

```
E5108: Error executing lua: vim/_defaults.lua:0: Vim:E553: No more items
stack traceback:
        [C]: in function 'cnext'
        vim/_defaults.lua: in function <vim/_defaults.lua:0>
```

when it should simply show

```
E553: No more items
```

just as if the user had used `:cnext` directly.

### PR DESCRIPTION
**Pull request by gpanders**
Resolves https://github.com/neovim/neovim/issues/30625.

### CODE REVIEW

File: test/functional/editor/defaults_spec.lua [hunk 1]
```diff
@@ -95,6 +95,60 @@ describe('default', function()
     end)
   end)
 
-  -- describe('key mappings', function()
-  -- end)
+  describe('key mappings', function()
+    describe('unimpaired-style mappings', function()
+      it('do not show a full stack trace #30625', function()
+        n.clear({ args_rm = { '--cmd', 'comclear | mapclear | mapclear!' } })
```
Comment (zeertzjq) [inline test/functional/editor/defaults_spec.lua:101]:
```suggestion
        n.clear({ args_rm = { '--cmd' } })
```

File: runtime/lua/vim/_defaults.lua [hunk 2]
```diff
@@ -219,132 +219,150 @@ do
...
-    local function create_unimpaired_mapping(lhs, rhs, desc)
-      vim.keymap.set('n', lhs, function()
-        local _, err = pcall(rhs) ---@type any, string
-        if err then
-          vim.api.nvim_err_writeln(err)
-        end
-      end, { desc = desc })
+    --- Execute a command and print errors without a stacktrace.
+    --- @param opts table Arguments to |nvim_cmd()|
+    local function cmd(opts)
```
Comment (justinmk) [inline runtime/lua/vim/_defaults.lua:224]: This might be an example of the kind of thing to put in an internal-only `_util.lua` module, where useful stuff can live and potentially (but not always) graduate later to a public interface. (This particular thing might "graduate" to a flag on the existing `vim.cmd`.)

File: test/functional/editor/defaults_spec.lua (hunk 1 above)
Comment (gpanders) [reply test/functional/editor/defaults_spec.lua:101]: Why? Won't that remove all `--cmd` arguments? I only want to remove the `:mapclear` ones.
