### PR TITLE
fix(input): use click number of last click for mouse drag

### LINKED ISSUE #4754: mouse double-click and drag should select word by word
- Neovim version: 0.4.x ece19b459c082eae05b5c480f6ee91181f002c02
- Vim behaves differently? Vim version: VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Nov  6 2014 14:32:04)
- Operating system/version: OS X 10.10.2
- Terminal name/version: iTerm 2
- `$TERM`: `xterm-256color`
### Actual behaviour

Double click, then drag to select word by word. In NeoVim, the selection starts with a word (if double clicked inside a word) but as soon as dragging starts then it selects character by character instead of word by word.
### Expected behaviour

While dragging, selection should continue to select word by word like in Vim.
### Steps to reproduce using `nvim -u NORC` and `vim -u NONE`

Run this before testing the mouse actions: 

``` viml
set mouse=a
```

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #4754

### CODE REVIEW

File: src/nvim/os/input.c [hunk 1]
```diff
@@ -306,37 +306,35 @@ static uint8_t check_multiclick(int code, int grid, int row, int col)
...
 
-  if (code == KE_LEFTRELEASE
-      || code == KE_RIGHTRELEASE
-      || code == KE_MIDDLERELEASE
-      || code == KE_MOUSEDOWN
-      || code == KE_MOUSEUP
-      || code == KE_MOUSELEFT
-      || code == KE_MOUSERIGHT
-      || code == KE_MOUSEMOVE) {
+  if ((code >= KE_MOUSEDOWN && code <= KE_MOUSERIGHT) || code == KE_MOUSEMOVE) {
```
Comment (zeertzjq) [inline src/nvim/os/input.c:309]: Vim also keeps the number of clicks for mouse release events, so using the number of clicks below instead of returning 0 here matches Vim's behavior better.

**Review by justinmk — APPROVED** [review]
Very happy to have this fixed, thank you!
