### PR TITLE
Fix newly detected implicit fallthrough issues

### LINKED ISSUE #12509: address implicit fallthrough warnings
Compiling with clang10, I have many implicit-falltrough warnings.
Firefox addresses it via defining MOZ_FALLTHROUGH (compiler-dependant). I think we could use a similar NVIM_FALLTRHOUGH in auto/config.h.in

cc @jamessan since you 've already added this part
https://github.com/neovim/neovim/commit/b43a3dbff8c615fec152e3fb2157961f3d90b705

### PR DESCRIPTION
**Pull request by jamessan**
* Disable -Wimplicit-fallthrough for a) gperf-generated code and b) vendored tree_sitter directory
* Add missing "goto endFAIL" when spellfile can't be read

Closes #12509

### CODE REVIEW

File: src/nvim/macros.h [hunk 1]
```diff
@@ -203,16 +205,31 @@
 # define PRAGMA_DIAG_PUSH_IGNORE_MISSING_PROTOTYPES \
   _Pragma("clang diagnostic push") \
   _Pragma("clang diagnostic ignored \"-Wmissing-prototypes\"")
+# ifdef HAVE_WIMPLICIT_FALLTHROUGH_FLAG
+#  define PRAGMA_DIAG_PUSH_IGNORE_IMPLICIT_FALLTHROUGH \
+    _Pragma("clang diagnostic push") \
+    _Pragma("clang diagnostic ignored \"-Wimplicit-fallthrough\"")
+# else
```
Comment (teto) [inline src/nvim/macros.h:212]: any reason why we dont define PRAGMA_DIAG_PUSH_IGNORE_IMPLICIT_FALLTHROUGH via a `#cmakedefine` instead of preproc ? this could get rid of HAVE_WIMPLICIT_FALLTHROUGH_FLAG

**Review by teto — COMMENTED** [review]
thanks for addressing. Minor comments.

with this PR, clang10 still had this comment (without giving more info on location)
```
[100%] Building C object src/nvim/CMakeFiles/nvim.dir/tui/input.c.o
warning: fallthrough annotation in unreachable code [-Wimplicit-fallthrough]
[100%] Building C object src/nvim/CMakeFiles/nvim.dir/tui/terminfo.c.o
```

File: src/nvim/CMakeLists.txt [hunk 2]
```diff
@@ -189,7 +189,11 @@ if(NOT MSVC)
   endif()
 
   # tree-sitter: inlined external project, we don't maintain it. #10124
-  set_source_files_properties(${TREESITTER_SOURCES} PROPERTIES COMPILE_FLAGS "${COMPILE_FLAGS} -Wno-conversion -Wno-pedantic -Wno-shadow -Wno-missing-prototypes -Wno-unused-variable")
+  if(HAVE_WIMPLICIT_FALLTHROUGH_FLAG)
+    set_source_files_properties(${TREESITTER_SOURCES} PROPERTIES COMPILE_FLAGS "${COMPILE_FLAGS} -Wno-conversion -Wno-pedantic -Wno-shadow -Wno-missing-prototypes -Wno-unused-variable -Wno-implicit-fallthrough")
+  else()
```
[the remark this answers is not in the document]
Comment (jamessan) [reply src/nvim/CMakeLists.txt]: > can we make the compile_flags a variable ?

Done.

File: src/nvim/macros.h (hunk 1 above)
Comment (jamessan) [reply src/nvim/macros.h:212]: > any reason why we dont define PRAGMA_DIAG_PUSH_IGNORE_IMPLICIT_FALLTHROUGH via a `#cmakedefine` instead of preproc ?

I tried that and it's more complicated than it's worth.  `HAVE_WIMPLICIT_FALLTHROUGH_FLAG` does the job.
