### PR TITLE
runtime: propagate lua parsing errors while using "require"

### LINKED ISSUE #13477: runtime: requiring lua module with syntax error gives wrong error message
### Neovim Version

```
NVIM v0.5.0-dev+917-g85bce4d13
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/my_user/tools/neovim/build/config -I/home/my_user/tools/neovim/src -I/usr/include -I/home/my_user/tools/neovim/build/src/nvim/auto -I/home/my_user/tools/neovim/build/include
Compiled by my_user@my-host

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
   fall-back for $VIM: "/usr/local/share/nvim"

```

### Problem

`XDG_CONFIG_HOME/nvim/lua` should be in `LUA_PATH` in order to require user create Lua files.

Ex. in an `init.lua`

```lua
vim.o.exrc = true
vim.o.secure = true

require('some-other-file')
```

### What happens 

Unable to require files found in `XDG_CONFIG_HOME/nvim/lua` as one normally would.

Requiring any lua file that might be found in `XDG_CONFIG_HOME/nvim/lua` throws an error of `module '[x]' not found:`

### Steps to reproduce

Build Neovim from source using

```
make CMAKE_BUILD_TYPE=RelDebWithInfo USE_BUNDLED=OFF
sudo make install USE_BUNDLED=OFF
```

Create a `lua` folder in `XDG_CONFIG_HOME/nvim`

Create a file calling `settings.lua` with the contents of

```
vim.o.exrc = true
vim.o.secure = true
```

Create a `init.lua` or `init.vim` with either

```
require('settings')
```

or

```
lua require('settings')
```

Or different named `.lua` or `.vim` file that you tell Neovim to load using `nvim -u [that file name]`.

Neovim will say that `module 'settings' not found:`

### Other useful info

What `nvim -c "lua print(package.path)"` returns:

`./?.lua;/usr/share/luajit-2.1.0-beta3/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua`

I have tried building Neovim [the harder way](https://github.com/neovim/neovim/wiki/Building-Neovim) as well.

Allowing the build process to install bundled dependencies does not change this.

Attempting to manually modify the `runtimepath` variable does not effect this error either.

### PR DESCRIPTION
**Pull request by dm1try**
errors returned by `loadfile` in `vim._load_package` are hidden atm.
it can be interpreted as some problem with a loading path because the default error contains "module not found" message provided by other loaders.

fixes #13477

this fix relies on [the default interface](https://pgl.yoyo.org/luai/i/package.loaders) where the error can be returned by the "seacher" function. though I do not like how the message formatted :) at least it's better than nothing

Screen Shot 2020-12-08 at 01 56 45

EDIT, extra links
https://www.gammon.com.au/scripts/doc.php?lua=loadfile
https://www.gammon.com.au/scripts/doc.php?lua=package.loadlib

### CODE REVIEW

File: src/nvim/lua/vim.lua [hunk 1]
```diff
@@ -115,15 +115,17 @@ function vim._load_package(name)
   for _,path in ipairs(paths) do
     local found = vim.api.nvim_get_runtime_file(path, false)
     if #found > 0 then
-      return loadfile(found[1])
+      local f, err = loadfile(found[1])
+      return f or err
```
Comment (bfredl) [inline src/nvim/lua/vim.lua:119]: `return f or error(err)` might work to override message.

Comment (dm1try) [reply src/nvim/lua/vim.lua:119]: yeah, it looks better
Screen Shot 2020-12-08 at 02 11 55

**Comment by bfredl** [comment]
@dm1try would you mind adding a test? you could add a file to `fixtures/lua` with known syntax error and use `set rtp+=test/functional/fixtures` just like `core/startup_spec.lua`. If the syntax error differs among luajit and puc lua maybe matching "syntax error" is enough.

**Comment by tjdevries** [comment]
Can probably just use `error("Failed to load")` or similar, right? It doesn't even have to have a syntax error? Or is the behavior different for both? I don't remember. (maybe test for both?)

**Comment by dm1try** [comment]
updated, added a test.

File: test/functional/lua/vim_spec.lua [hunk 2]
```diff
@@ -1453,3 +1453,25 @@ describe('lua stdlib', function()
...
+
+describe('vim._load_package', function()
+  describe('with a script that contains a syntax error', function()
+
+    before_each(function()
+      command('set rtp+=test/functional/fixtures')
+    end)
+
+    after_each(function()
+      command('set rtp-=test/functional/fixtures')
```
Comment (bfredl) [inline test/functional/lua/vim_spec.lua:1465]: use `clear()`  it `before_each` instead.

File: test/functional/lua/vim_spec.lua [hunk 3]
```diff
@@ -1453,3 +1453,25 @@ describe('lua stdlib', function()
...
+    end)
+
+    it('raises an error', function()
+      local syntax_error_msg = exec_lua [[
+        _, err = pcall(vim._load_package, "syntax_error")
```
Comment (bfredl) [inline test/functional/lua/vim_spec.lua:1470]: call `require` directly, `vim._load_package` is an implementation detail.

**Comment by bfredl** [comment]
> Can probably just use `error("Failed to load")` or similar, right? It doesn't even have to have a syntax error? Or is the behavior different for both? I don't remember. (maybe test for both?)

Not sure what you mean @tjdevries . This path is only for syntax errors more or less, runtime load errors are handled separately (and correctly already).

File: test/functional/lua/vim_spec.lua [hunk 4]
```diff
@@ -1453,3 +1453,18 @@ describe('lua stdlib', function()
     end)
   end)
 end)
+
+describe('lua: require("mod") from packages', function()
+  before_each(function()
+    command('set rtp+=test/functional/fixtures')
+  end)
```
Comment (dm1try) [inline test/functional/lua/vim_spec.lua:1460]: 👎

File: test/functional/lua/vim_spec.lua (hunk 3 above)
Comment (dm1try) [reply test/functional/lua/vim_spec.lua]: in that case `vim_spec` is a wrong place for testing this behavior.

File: test/functional/lua/vim_spec.lua (hunk 4 above)
Comment (bfredl) [reply test/functional/lua/vim_spec.lua:1460]: there is a clear in the `before_each` for the entire file.

Comment (dm1try) [reply test/functional/lua/vim_spec.lua:1460]: sorry, I need to clarify

the previous description and the nested context for the specific error case was clearer than the current version:
 - the nested context described how we build it(why we need `before_each`)
 - it could be easier extended with other scenarios(like a "happy-path" cases)
 - it was consistent with other test cases in this spec

moreover, the current description is kinda "verbose":
 - "lua": looks like unnecessary prefix here
-  "require from packages"? could it be different `require`?

File: test/functional/lua/vim_spec.lua (hunk 3 above)
Comment (dm1try) [reply test/functional/lua/vim_spec.lua]: > vim._load_package is an implementation detail.

I disagree. `vim._load_package` is  "searcher function". there are clear [public requirements](https://pgl.yoyo.org/luai/i/package.loaders) for it:
 - take a package name
 - return a loaded package or error or `nil`
it was tested in isolation.

though, I agree that it makes sense to test it in the integration with `package` module (at least we can sure that the result error message is properly formatted :) )

btw, the function can be named`vim.package.load` after all(instead of using `_` to show its speciality)

Comment (dm1try) [reply test/functional/lua/vim_spec.lua]: though I don't think it's that important atm :)

Comment (bfredl) [reply test/functional/lua/vim_spec.lua]: > I disagree. vim._load_package is "searcher function". there are clear public requirements for it:

This is completely missing the context. "searcher function" is a public interface of __liblua__. The actual public interface that __neovim__ expects its plugins/users to use is `require`, alternatively `vim.api.nvim_get_runtime_file` to bypass the package system (needed to load non-`.lua` files, like fennel). ` vim._load_package` is an implementation detail as it could be changed/removed from `0.5` to `0.6` and plugins should not depend on it, which is that the `vim._` prefix indicates.

Comment (dm1try) [reply test/functional/lua/vim_spec.lua]: > This is completely missing the context. "searcher function" is a public interface of liblua. The actual public interface that neovim expects its plugins/users to use is require, alternatively vim.api.nvim_get_runtime_file to bypass the package system (needed to load non-.lua files, like fennel). vim._load_package is an implementation detail as it could be changed/removed from 0.5 to 0.6 and plugins should not depend on it, which is that the vim._ prefix indicates.

there is no "actual" public interface(does the "actual" mean the thing that **you** want to test here?), there are just public interfaces from different components in the stack. the test suite can contain tests for the any component(its public interface) in the stack. A part of test suite can cover client requirements for neovim plugin users but it does not mean that each test should do it.

Comment (bfredl) [reply test/functional/lua/vim_spec.lua]: > there is no "actual" public interface(does the "actual" mean the thing that you want to test here?), there are just public interfaces from different components in the stack.

Maybe my wording was sub-optimal but the distinction I mention does make *actual* sense once you consider stability over multiple versions. Plugins are of course perfectly free to exploit any interface of any level of the implementation stack, but there **must** be a distinction of what interfaces it becomes **neovim's** problem if we break them in the future, as opposed to the plugins (or a dependency fucking up, though from the users POV that is also neovim's problem to deal with). In this case: we say `require` is a recommended interface we want to continue to work even given potential heavy further refactors in the future (same with the runtime API functions), but `vim._load_package` is a implementation detail that can change or be removed at any given moment.  Now you can of course unit test it but the primary focus of functional tests should be user/plugin observable behaviour that neovim considers itself responsible to preserve (within reasonable effort).

Comment (dm1try) [reply test/functional/lua/vim_spec.lua]: The client of "search function" interface is not the plugin developer, but the application itself(it means the Neovim uses 
`lualib` capability to provide the custom search function for finding packages). There are no any claims that this is part of public plugin API. So I do not see any problem in its future change/removing. Moreover this case is more like an "edge-case" so the reasonable effort should be directed for "happy-path" testing of functional requirements  described in the documentation.
