### PR TITLE
startup: Remove special case of TUI initialization

### LINKED ISSUE #7967: Windows/TUI: Printing to stdout during initialization prevents starting normally
- `nvim --version`: NVIM v0.2.2 (also with very recent 0.2.3-580-gec62f925a)
- Vim (version: ) behaves differently? No
- Operating system/version: Windows 10 Pro 1709
- Terminal name/version: cmd.exe
- `$TERM`: empty, cygwin (when running cmd.exe under cmder)

### Steps to reproduce

```
nvim -u init.test.vim
```

with `init.test.vim` being:

```
echom "Test echom"
```

### Actual behaviour

The following gets printed to the terminal:

```
Test echom
Press ENTER or type command to continue
```

And nothing else happens no matter what keys you press. Only `ctrl-c` gets you out to the terminal, and then everything you typed gets printed.

This seems to happen when anything prints messages during initialization.

I am able to start normally even with a complex init file only if no messages get printed.

### Expected behaviour

Display the message and start normally.

### PR DESCRIPTION
**Pull request by erw7**
fixes #7967

Implemented according to https://github.com/neovim/neovim/pull/9825#issuecomment-478868745.

- [x] Move `ui_builtin_start()` to the same position as embedded_mode `remote_ui_wait_for_attch()`.
- [x] If stdin is redirected, save the original `stdin` and replace fd 0 with tty before calling `ui_builtin_start()`.
- [x] ~Remove unnecessary code such as `start_input()`, `stop_input()` etc.~
- [x] Fix the problem that the display of `nvim -u NORC -c "echo 'Hello'"` is cleared.
- [x] ~Examine the behavior of `exmode_active` and correct if necessary.~
- [x] ~Write a test.~

### CODE REVIEW

**Comment by erw7** [comment]
This method has problems for the following reasons when `stdin` is redirected. `stdin` is changed from a `pipe` to a `tty(console)` in a [`readfile()`](https://github.com/neovim/neovim/blob/7c38994ff2397772234bd89faf8b372fa9fecfbd/src/nvim/fileio.c#L1737) called from [`read_stdin()`](https://github.com/neovim/neovim/blob/35362495c965554f45634bcde3c4ce6d5eca52aa/src/nvim/main.c#L468
). Therefore, if we call `ui_builtin_start()` before calling `read_stdin()`, the input of tui will be a pipe.

This problem occurs because we can not pass a tty handle to `uv_pipe_init()` on Windows. I think that it is good to solve by #9825.

**Comment by justinmk** [comment]
> The easiest way to solve this problem is #9825, but does this make sense to implement it as it may reduce code?

stream.c change in https://github.com/neovim/neovim/pull/9825/commits/10f703dc0784cee4aa97d54c916c7192ec4874f5 seems separate from #9825. Maybe we should merge that sooner than the rest.

See https://github.com/neovim/neovim/pull/9825/files#r273467992.
Another idea: on Windows, we could simply cancel any/all prompts if the UI is not ready, as a workaround for #7967.

**Comment by erw7** [comment]
Is there any possibility that the following code will be executed?

https://github.com/neovim/neovim/blob/21b108fe445452e6e35621184fc77623dc64f9a3/src/nvim/tui/input.c#L445-L460

**Comment by erw7** [comment]
> stream.c change in 10f703d seems separate from #9825. Maybe we should merge that sooner than the rest.

@justinmk  Does that mean that it separates 10f703d into another pull request? I will ask you one more point. "Hello" displayed by `nvim-qt--u NORC -c "echo 'Hello'"` disappears immediately after startup. This seems to be the cause of the failure of the https://github.com/neovim/neovim/pull/9829#issuecomment-478730632 test, but is it better to create an issue?

**Comment by justinmk** [comment]
> @justinmk Does that mean that it separates [10f703d](https://github.com/neovim/neovim/commit/10f703dc0784cee4aa97d54c916c7192ec4874f5) into another pull request?

I think so.

> "Hello" displayed by `nvim-qt--u NORC -c "echo 'Hello'"` disappears immediately after startup. This seems to be the cause of the failure of the [#9829 (comment)](https://github.com/neovim/neovim/pull/9829#issuecomment-478730632) test, 

By "disappears", do you mean it displayed in the shell, _not_ the GUI?
That shouldn't happen if nvim-qt is using `--embed` without `--headless`, [with [Nvim 0.3.4](https://github.com/neovim/neovim/wiki/Following-HEAD#20181118). Because Nvim waits for the UI. 

For all cases except `--headless`/`-es`/`-Es`, we should not attempt to display a message until we have a UI. That simplifies the system.

> but is it better to create an issue?

Let's try to deal with it here, since it is related.

**Comment by erw7** [comment]
> I think that's only relevant for -es/-Es. It happens when the stdin stream is closed.

In the case of `-es/-Es`, the following code is not executed because silent_mode is true. I think that TUI will not execute and the corresponding code will not.

https://github.com/neovim/neovim/blob/b358054694765b595ff3ef64a5b0bba98628c218/src/nvim/main.c#L479-L482

If the code in question is not executed, I can use to the handle of TTY instead of `stdin` on `tinput_init()` when redirecting `stdin`, so I would like to know that.

**Comment by erw7** [comment]
>> @justinmk Does that mean that it separates 10f703d into another pull request?
>
> I think so.

@justinmk I created a separate pull request #9884.

**Comment by erw7** [comment]
> By "disappears", do you mean it displayed in the shell, not the GUI?

No. It looks like the GUI is cleared after launching.

After `remote_ui_wait_for_attach()` is called in [main.c:370](https://github.com/neovim/neovim/blob/b358054694765b595ff3ef64a5b0bba98628c218/src/nvim/main.c#L370), `exe_pre_commands()` and `exe_commands()` are called in [main.c:381](https://github.com/neovim/neovim/blob/b358054694765b595ff3ef64a5b0bba98628c218/src/nvim/main.c#L381) and [main.c:548](https://github.com/neovim/neovim/blob/b358054694765b595ff3ef64a5b0bba98628c218/src/nvim/main.c#L548). Therefore, is not what displayed by `--cmd/-c` is displayed in the GUI?

**Comment by bfredl** [comment]
> Therefore, is not what displayed by --cmd/-c is displayed in the GUI?

It is displayed in `--embed` GUI but not TUI, but it could be a worthwhile change to make TUI also start early. Though it could have some effects like making env vars set in `init.vim` not take effect in TUI initialization.

**Comment by justinmk** [comment]
> In the case of `-es/-Es`, the following code is not executed because silent_mode is true. I think that TUI will not execute and the corresponding code will not.

My mistake, I was thinking of this: https://github.com/neovim/neovim/blob/9daa7d9978ac0249b61e823808cabbcbc997d5c7/src/nvim/os/input.c#L111-L114


> Though it could have some effects like making env vars set in `init.vim` not take effect in TUI initialization.

Good point, let's just document that. init.vim should not be munging TUI-related env vars.

**Comment by erw7** [comment]
> Good point, let's just document that. init.vim should not be munging TUI-related env vars.

Create `tinit.vim` to munging TUI-related  env vars, and do we use it like `ginit.vim` in GUI?

**Comment by erw7** [comment]
Comment said "Don't clear the screen", but `CLEAR` is assigned to `must_redraw`. Is the following code correct?

https://github.com/neovim/neovim/blob/d08692a8246039b938b5645a6c01b4ff7f51671e/src/nvim/main.c#L486-L489

**Comment by justinmk** [comment]
> Create `tinit.vim` to munging TUI-related env vars, and do we use it like `ginit.vim` in GUI?

Neither is needed. We will introduce a `UIAttach` event in a separate PR.

**Comment by bfredl** [comment]
@erw7 Yes. The point is we can't clear right now, but the clear should then be done next time an ordinary redraw is done.

File: src/nvim/main.c [hunk 1]
```diff
@@ -468,25 +461,12 @@ int main(int argc, char **argv)
...
-    ui_builtin_start();
-  }
-
   setmouse();  // may start using the mouse
 
   if (exmode_active || early_ui) {
     // Don't clear the screen when starting in Ex mode, or when an
     // embedding UI might have displayed messages
-    must_redraw = CLEAR;
+    must_redraw = VALID;
```
Comment (justinmk) [inline src/nvim/main.c]: @bfredl tests pass with this change. Any objection?

**Comment by justinmk** [comment]
This looks really good so far!

File: src/nvim/main.c (hunk 1 above)
Comment (bfredl) [reply src/nvim/main.c]: Let's change it. If there is startup redraw issues, we can change it back later...

Comment (bfredl) [reply src/nvim/main.c]: though it would be better then to have `redraw_later(VALID)` here in case something before this wants to redraw more than `VALID`.

**Comment by erw7** [comment]
@bfredl The position where "Hello" displayed by `nvim -u NORC -c "echo 'Hello'"` is at the center of the column, but could you give me some hints to fix it?

**Comment by bfredl** [comment]
@erw7 cannot reproduce, does this happen only on windows?

**Comment by erw7** [comment]
@bfredl I have now confirmed on Linux. It seems like a problem that occurs only with Windows.

**Comment by erw7** [comment]
@bfredl I understand the cause of https://github.com/neovim/neovim/pull/9829#issuecomment-482961048. It seems that the `msg_col` changed by the call of `scriptnames()` by `execute()` of the following code is not restored. This problem seems to be solved by #9338.

https://github.com/neovim/neovim/blob/773bdd41ec19c9909e979c4580cf098d71d168d7/runtime/plugin/rplugin.vim#L29

**Comment by erw7** [comment]
I read `:h --headless`, the https://github.com/neovim/neovim/pull/9829#issuecomment-484034791  change is not desirable. Therefore, do not use headless mode with oldtest, or in the case of the headless mode, the `:echo` output needs to be changed to the screen and stderr.

**Comment by justinmk** [comment]
#9338 is merged now, would you mind rebasing this?

**Comment by erw7** [comment]
> #9338 is merged now, would you mind rebasing this?

@justinmk I rebased this.

File: src/nvim/tui/input.c [hunk 2]
```diff
@@ -48,6 +48,21 @@ void tinput_init(TermInput *input, Loop *loop)
 
   int curflags = termkey_get_canonflags(input->tk);
   termkey_set_canonflags(input->tk, curflags | TERMKEY_CANON_DELBS);
+#ifdef WIN32
+  if (!os_isatty(0)) {
+      const HANDLE conin_handle = CreateFile("CONIN$",
+                                             GENERIC_READ | GENERIC_WRITE,
+                                             FILE_SHARE_READ | FILE_SHARE_WRITE,
+                                             (LPSECURITY_ATTRIBUTES)NULL,
+                                             OPEN_EXISTING, 0, (HANDLE)NULL);
```
Comment (justinmk) [inline src/nvim/tui/input.c]: is `FILE_SHARE_WRITE` needed? We do not specify it in https://github.com/neovim/neovim/blob/16b1e8f9c070ad853c6c63b43591e297bf512662/src/nvim/main.c#L1136

File: src/nvim/main.c [hunk 3]
```diff
@@ -469,25 +462,12 @@ int main(int argc, char **argv)
...
   setmouse();  // may start using the mouse
 
   if (exmode_active || early_ui) {
     // Don't clear the screen when starting in Ex mode, or when an
     // embedding UI might have displayed messages
-    must_redraw = CLEAR;
+    redraw_later(VALID);
   } else {
     screenclear();  // clear screen
     TIME_MSG("clearing screen");
```
Comment (justinmk) [inline src/nvim/main.c]: I guess we pretty much never hit this case, now :)
