### PR TITLE
fix(tui): grow termkey's internal buffer for large escape sequences

### LINKED ISSUE #26099: Neovim assert fails when osc52 is enabled with copy to clipboard
### Problem

I'm using tmux-3.2 for in my dev environment, connected through windows terminal. When I do a copy and paste on a considerably large code section, neovim terminates with the following assert failure.

```
nvim: neovim/src/nvim/tui/input.c:673: handle_raw_buffer: Assertion `consumed <= rbuffer_size(input->read_stream.buffer)' failed.
```

### Steps to reproduce

1. Run tmux with following in `.tmux.conf`, to enable osc-52 on tmux as per [this](https://github.com/tmux/tmux/wiki/Clipboard#quick-summary) link

```tmux
set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',screen-256color:Tc'
set -s set-clipboard on
set -as terminal-features ',screen-256color:clipboard'
```

2. Open nvim with following minimum reproducible config
```lua
vim.opt.clipboard = vim.opt.clipboard + 'unnamedplus'
local ok, osc52 = pcall(require, "vim.clipboard.osc52")

if not ok then
    return
end

vim.g.clipboard = {
    name = 'OSC 52',
    copy = {
    ['+'] = osc52.copy,
    ['*'] = osc52.copy,
    },
    paste = {
    ['+'] = osc52.paste,
    ['*'] = osc52.paste,
    },
}
```

3. Open the file that has the following code segment:

```lua
    require("clangd_extensions").setup({
        inlay_hints = {
            inline = vim.fn.has("nvim-0.10") == 1,
            -- Options other than `highlight' and `priority' only work
            -- if `inline' is disabled
            -- Only show inlay hints for the current line
            only_current_line = false,
            -- Event which triggers a refresh of the inlay hints.
            -- You can make this { "CursorMoved" } or { "CursorMoved,CursorMovedI" } but
            -- not that this may cause  higher CPU usage.
            -- This option is only respected when only_current_line and
            -- autoSetHints both are true.
            only_current_line_autocmd = { "CursorHold" },
            -- whether to show parameter hints with the inlay hints or not
            show_parameter_hints = true,
            -- prefix for parameter hints
            parameter_hints_prefix = "<- ",
            -- prefix for all the other hints (type, chaining)
            other_hints_prefix = "=> ",
            -- whether to align to the length of the longest line in the file
            max_len_align = false,
            -- padding from the left if max_len_align is true
            max_len_align_padding = 1,
            -- whether to align to the extreme right or not
            right_align = false,
            -- padding from the right if right_align is true
            right_align_padding = 7,
            -- The color of the hints
            highlight = "Comment",
            -- The highlight group priority for extmark
            priority = 100,
        },
        ast = {
            -- These are unicode, should be available in any font
            role_icons = {
                type = "🄣",
                declaration = "🄓",
                expression = "🄔",
                statement = ";",
                specifier = "🄢",
                ["template argument"] = "🆃",
            },
            kind_icons = {
                Compound = "🄲",
                Recovery = "🅁",
                TranslationUnit = "🅄",
                PackExpansion = "🄿",
                TemplateTypeParm = "🅃",
                TemplateTemplateParm = "🅃",
                TemplateParamObject = "🅃",
            },
            --[[ These require codicons (https://github.com/microsoft/vscode-codicons)
                role_icons = {
                    type = "",
                    declaration = "",
                    expression = "",
                    specifier = "",
                    statement = "",
                    ["template argument"] = "",
                },

                kind_icons = {
                    Compound = "",
                    Recovery = "",
                    TranslationUnit = "",
                    PackExpansion = "",
                    TemplateTypeParm = "",
                    TemplateTemplateParm = "",
                    TemplateParamObject = "",
                }, ]]

            highlights = {
                detail = "Comment",
            },
        },
        memory_usage = {
            border = "none",
        },
        symbol_info = {
            border = "none",
        },
    })
    require'lspconfig'.clangd.setup{}

```

4. Copy above code segment (`yG`) 
5. Open another file in a different buffer (`:vnew`)
6. Paste the copied segment (`p`)

nvim crash with assert failure on debug build. On release build the process will hang

### Expected behavior

Copied section should be pasted on the new buffer

### Neovim version (nvim -v)

NVIM v0.10.0-dev (commit : 4972c80 )

### Vim (not Nvim) behaves the same?

No applicable

### Operating system/version

CentOS 7.9

### Terminal name/version

Windows Terminal 1.20.3131.0

### $TERM environment variable

screen-256color

### Installation

built from source on main branch

### PR DESCRIPTION
**Pull request by gpanders**
Some escape sequences (in particular, OSC 52 paste responses) can be very large, even unbounded in length. These can easily overflow termkey's internal buffer. In order to process these long sequences, dynamically grow termkey's internal buffer.

Fixes: https://github.com/neovim/neovim/issues/26099

### CODE REVIEW

File: src/nvim/tui/input.c [hunk 1]
```diff
@@ -692,10 +691,19 @@ static void handle_raw_buffer(TermInput *input, bool force)
...
-      // termkey_push_bytes can return (size_t)-1, so it is possible that
-      // `consumed > rbuffer_size(input->read_stream.buffer)`, but since tk_getkeys is
-      // called soon, it shouldn't happen.
+      size_t size = MIN(count, len);
+      if (size > termkey_get_buffer_remaining(input->tk)) {
+        // We are processing a very long escape sequence. Increase termkey's
+        // internal buffer size. We don't handle out of memory situations so
+        // assert the result
+        const size_t bufsize = termkey_get_buffer_size(input->tk);
+        assert(termkey_set_buffer_size(input->tk, 2 * bufsize));
```
Comment (gpanders) [inline src/nvim/tui/input.c:700]: Doubling the buffer size is just a heuristic. If the input is very large we will have to reallocate multiple times. But this should not happen very often (the _only_ case we ever see this is for large OSC 52 pastes, which are infrequent).

**Comment by gpanders** [comment]
Is it worth it to shrink the termkey buffer back to a smaller size when the large escape sequence has been processed?

If we leave it as-is then we don't have to reallocate again if the user pastes another large block of text. But we are also leaving a (potentially large-ish) block of memory unused if someone pastes a large block of text once and then never does it again.

File: src/nvim/tui/input.c (hunk 1 above)
Comment (zeertzjq) [inline src/nvim/tui/input.c:700]:
```suggestion
        if (!termkey_set_buffer_size(input->tk, 2 * bufsize)) {
          abort();
        }
```

**Comment by justinmk** [comment]
> Is it worth it to shrink the termkey buffer back to a smaller size when the large escape sequence has been processed?

Seems worth it. It's a small amount of extra code.

**Comment by gpanders** [comment]
@clason I [noticed the same thing](https://github.com/neovim/neovim/pull/26309#discussion_r1410722663). We can refactor that specific change unless @zeertzjq has a different suggestion (as he was the one who proposed it originally).
