### PR TITLE
[RDY] treesitter: filter updates on <CR>

### LINKED ISSUE #12817: treesitter: highlighting is wrong when hitting `o`
- `nvim --version`: `NVIM v0.5.0-649-gc42fdc036`
- `vim -u DEFAULTS` (version: ) behaves differently? Not applicable
- Operating system/version: Void linux
- Terminal name/version: st
- `$TERM`: `st-256color`

### Steps to reproduce using `nvim -u NORC`

Setup treesitter highlighting for C.
`set formatoptions+=ro`
Go to a comment and hit `A<Enter>` or `o`.

### Actual behaviour

The highlighting is wrong, that is : the freshly added comment is not highlighted, and the word below is highlighted.

### Expected behaviour

Everything should be fine.

@bfredl I think this is related to the byte interface too

### PR DESCRIPTION
**Pull request by vigoux**
This fixes an error when fo=ro, when hitting <CR> to insert a new
comment line.

Fixes #12817.

### CODE REVIEW

File: test/functional/lua/buffer_updates_spec.lua [hunk 1]
```diff
@@ -256,9 +256,10 @@ describe('lua: nvim_buf_attach on_bytes', function()
   -- assert the wrong thing), but masks errors with unflushed lines (as
   -- nvim_buf_get_offset forces a flush of the memline). To be safe run the
   -- test both ways.
-  local function setup_eventcheck(verify)
-    meths.buf_set_lines(0, 0, -1, true, origlines)
-    local shadow = deepcopy(origlines)
+  local function setup_eventcheck(verify, start_text)
+    local start_txt = start_text or origlines
```
Comment (teto) [inline test/functional/lua/buffer_updates_spec.lua:260]: I find this needlessly tricky, you can rewrite other tests to pass origlines instead.

File: test/functional/lua/buffer_updates_spec.lua [hunk 2]
```diff
@@ -256,9 +256,9 @@ describe('lua: nvim_buf_attach on_bytes', function()
   -- assert the wrong thing), but masks errors with unflushed lines (as
   -- nvim_buf_get_offset forces a flush of the memline). To be safe run the
   -- test both ways.
-  local function setup_eventcheck(verify)
-    meths.buf_set_lines(0, 0, -1, true, origlines)
-    local shadow = deepcopy(origlines)
+  local function setup_eventcheck(verify, start_txt)
```
Comment (bfredl) [inline test/functional/lua/buffer_updates_spec.lua:259]: note to self: we can allow start_txt as a multiline string and split it on `\n` automatically

File: src/nvim/change.c [hunk 3]
```diff
@@ -1677,9 +1677,14 @@ int open_line(
         truncate_spaces(saved_line);
       }
       ml_replace(curwin->w_cursor.lnum, saved_line, false);
-      extmark_splice_cols(
-          curbuf, (int)curwin->w_cursor.lnum,
-          0, curwin->w_cursor.col, (int)STRLEN(saved_line), kExtmarkUndo);
+
+      int new_len = (int)STRLEN(saved_line);
+
+      if (new_len != curwin->w_cursor.col) {
```
Comment (bfredl) [inline src/nvim/change.c:1683]: Hmm is it obvious when `curwin->w_cursor.col == new_len` then the bytes is the same? And when they are different, we don't know if there is a shared prefix/suffix?

Comment (vigoux) [reply src/nvim/change.c:1683]: Good question. The new content should be the old content with striped trailing whitespace, thus we have a shared prefix.

Comment (bfredl) [reply src/nvim/change.c:1683]: is this true even with exandtab and such? sometimes vim will change tabs to spaces and back automagically.

Comment (bfredl) [reply src/nvim/change.c:1683]: BTW, if you don't want to look into this right now, just put a `TODO` here.

**Comment by vigoux** [comment]
AppVeyor fail does not seem related, rerunning...
