### PR TITLE
fix(lsp): jump to the target win when opts.reuse_win is true

### LINKED ISSUE #33458: [LSP]: reuse_win does not jump cursor
### Problem

`vim.lsp.buf.[implementation|definition|...]({ reuse_win = true })` does not jump cursor to existing window if buffer is already open.

### Steps to reproduce

1. `nvim repro.lua`
2. Insert anything that lsp can read to open the library definition/implementation, e.g., `vim.keymap.set`
3. open `repro.lua` buffer and the library buffer side by side.
4. type `gd` over `set` to jump to the library definition.

The open buffer is scrolled to the target line, but cursor does not jump.

### Expected behavior

Cursor should jump to the open buffer.

### Nvim version (nvim -v)

0.11

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Windows 10/Ubuntu

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

appimage

### PR DESCRIPTION
**Pull request by acehinnnqru**
Fixes: #33458

### CODE REVIEW

**Comment by acehinnnqru** [comment]
I can't determine which is better,
```lua
local w = opts.reuse_win and vim.fn.win_findbuf(b)[1] or win
if opts.reuse_win and w ~= win then
  api.nvim_set_current_win(w)
end
```
or 
```lua
local w = win
if opts.reuse_win then
  w = vim.fn.win_findbuf(b)[1] or w
  if w ~= win then
    api.nvim_set_current_win(w)
  end
end
```

File: runtime/lua/vim/lsp/buf.lua [hunk 1]
```diff
@@ -215,7 +215,13 @@ local function get_locations(method, opts)
         vim.fn.settagstack(vim.fn.win_getid(win), { items = tagstack }, 't')
 
         vim.bo[b].buflisted = true
-        local w = opts.reuse_win and vim.fn.win_findbuf(b)[1] or win
+        local w = win
+        if opts.reuse_win then
+          w = vim.fn.win_findbuf(b)[1] or w
+          if w ~= win then
+            api.nvim_set_current_win(w)
+          end
```
Comment (glepnir) [inline runtime/lua/vim/lsp/buf.lua:223]:
```suggestion
          w ~= win and api.nvim_set_current_win(w)
```

**Review by glepnir — COMMENTED** [review]
add a case in `test/functional/plugin/lsp_spec.lua`

File: runtime/lua/vim/lsp/buf.lua (hunk 1 above)
Comment (acehinnnqru) [reply runtime/lua/vim/lsp/buf.lua:223]: `w ~= win and api.nvim_set_current_win(w)` would failed when compiling;

or `local _ = w ~= win and api.nvim_set_current_win(w)`

Comment (glepnir) [reply runtime/lua/vim/lsp/buf.lua:223]: aha just keep if then

**Comment by justinmk** [comment]
A new test probably isn't needed, but just update the existing one?: https://github.com/neovim/neovim/blob/2f8fb4f28ab92d62e07d1d64a6dd89e0b6eb7253/test/functional/plugin/lsp_spec.lua#L3400

**Comment by acehinnnqru** [comment]
> A new test probably isn't needed, but just update the existing one?:
> 
> https://github.com/neovim/neovim/blob/2f8fb4f28ab92d62e07d1d64a6dd89e0b6eb7253/test/functional/plugin/lsp_spec.lua#L3400

This unit test aims to test the function `vim.lsp.util.show_document`

**Comment by justinmk** [comment]
is there any way to make the test smaller? i was really hoping to avoid a gigantic, complicated test for this minor feature.

**Comment by acehinnnqru** [comment]
> is there any way to make the test smaller? i was really hoping to avoid a gigantic, complicated test for this minor feature. 

The change is in a local function which cannot be tested directly and it's only used in definition, implementation and declaration.
maybe I could try to find a better way to test it.
