### PR TITLE
fix(lsp): apply_text_edits causes unwanted BufDelete events

### LINKED ISSUE #37832: vim.lsp.util.apply_text_edits forces given buffer to be listed (buflisted=true)
I have a question about this line of code in the function `apply_text_edit`:

https://github.com/neovim/neovim/blob/8a0cbf04d6a60f91c69c707789b18986a6921f8f/runtime/lua/vim/lsp/util.lua#L315

I am aware this code is mentioned in this issue:
https://github.com/neovim/neovim/issues/25272

I was wondering why does this function change the current buffer to a listed one.
Is this critically needed?
It seems to be a bug to me.

Even trying to load the buffer (just above) seems strange.
Why would you make edits to a buffer that is not even loaded.

But I don't know much about the inner workings of vim/neovim so I may be wrong.

## Why I'm asking

I was experiencing very strange crashes in one of my custom plugins.

It was caused by me handling the BufDelete event, which I thought `only me™` could possibly trigger.

But it turns out, the BufDelete was also emitted by a [nvim-cmp] completion confirmation.
Because it calls `apply_text_edit` during this procedure.
And it will also remember the buflisted value before the call, and then reapply the old buflisted value after the call.

https://github.com/hrsh7th/nvim-cmp/blob/da88697d7f45d16852c6b2769dc52387d1ddc45f/lua/cmp/utils/api.lua#L74-L79

This will cause neovim (I think) to emit a BufDelete event.
(because the buffer becomes unlisted?)

The problem is, the buffer is not deleted, it is still there.
So it might even be a bug in neovim, I don't know.

<details>
<summary>I have a snippet to reproduce the issue if it helps:</summary>

If you just change the buffer from listed to unlisted (even though the buffer is not destroyed, the event is still fired):

`nvim -u <filename> --noplugins`
```lua
-- Setup textEdit payload for demonstration
local textEdit = {
	newText = "",
	range = {
		["end"] = { character = 0, line = 1 },
		start = { character = 0, line = 1 },
	},
}

-- Create an unlisted, scratch buffer (the problem only happens in an unlisted buffer, scratch or not)
local the_buffer = vim.api.nvim_create_buf(false, true)

-- Setup a listener to see the problem occur
vim.api.nvim_create_autocmd("BufDelete", {
	group = vim.api.nvim_create_augroup("ReproGroup", { clear = true }),
	callback = function()
		vim.api.nvim_buf_set_lines(the_buffer, -1, -1, false, { "A BufDelete event was triggered!!" })
	end,
})

-- Just a quick setup with some guidance (no impact on the issue)
vim.cmd.buffer(the_buffer)

local function append(lines) vim.api.nvim_buf_set_lines(0, -1, -1, false, lines) end
local function buflisted() return vim.bo[the_buffer].buflisted and "✅ listed" or "❌ unlisted" end

--- This is cmp.utils.api.apply_text_edits with added debug statements
local function apply_text_edits(text_edits, bufnr, position_encoding)
	-- preserve 'buflisted' state because vim.lsp.util.apply_text_edits forces it to true
	local prev_buflisted = vim.bo[bufnr].buflisted                         append({ "Memorize buflisted                    "..buflisted() })
	vim.lsp.util.apply_text_edits(text_edits, bufnr, position_encoding)    append({ "vim.lsp.util.apply_text_edits(...)    "..buflisted() })
	vim.bo[bufnr].buflisted = prev_buflisted                               append({ "Restore buflisted                     "..buflisted() })
end

append({ "", "Call vim.lsp.util.apply_text_edits:", "" })

apply_text_edits({ textEdit }, the_buffer, "utf-8")

append({ "", "Modifying buflisted (same effect):", "" })

vim.bo[the_buffer].buflisted = true                                        append({ "set buflisted to true                 "..buflisted() })
vim.bo[the_buffer].buflisted = false                                       append({ "set buflisted to false                "..buflisted() })
```

If you happen to use a completion in an unlisted buffer:

`nvim -u <filename>`
```lua
-- Minimal plugin configuration
local cmp_spec = {
	"hrsh7th/nvim-cmp",
	dependencies = { "hrsh7th/cmp-path" },
	config = function()
		local cmp = require("cmp")
		cmp.setup({
			mapping = cmp.mapping.preset.insert({
				["<Enter>"] = cmp.mapping.confirm({ select = true }),
				["<C-Space>"] = cmp.mapping.complete(),
			}),
			sources = cmp.config.sources({
				{ name = "path" }, -- The problem also happens with other kinds of sources (snippy for example)
			}),
		})
	end,
}

-- Using lazy to install the plugin, you may do differently
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
require("lazy.minit").repro({ spec = { cmp_spec } })

-- Create an unlisted, scratch buffer (the problem only happens in an unlisted buffer, scratch or not)
local the_buffer = vim.api.nvim_create_buf(false, true)

-- Setup a listener to see the problem occur
vim.api.nvim_create_autocmd("BufDelete", {
	group = vim.api.nvim_create_augroup("ReproGroup", { clear = true }),
	callback = function()
		vim.api.nvim_buf_set_lines(the_buffer, -1, -1, false, { "A BufDelete event was triggered!!" })
	end,
})

-- Enter the buffer
vim.cmd.buffer(the_buffer)

-- Basic setup for easier repro
vim.api.nvim_buf_set_lines(the_buffer, 0, -1, false, {
	"1. Start typing '/' to trigger cmp-path's autocomplete",
	"2. Select any entry and hit <CR> (confirm)",
	"",
})
vim.fn.feedkeys("GA")
```
</details>

[nvim-cmp]: https://github.com/hrsh7th/nvim-cmp

### PR DESCRIPTION
**Pull request by glepnir**
Problem:
Since 2f6d1d3c887a87d9402137425b418dd12a904aac, `apply_text_edits`
unconditionally sets `buflisted=true`, causing spurious BufDelete events
if plugins restore the original 'buflisted' state on unlisted buffers:
https://github.com/neovim/neovim/blob/65ef6cec1cb766334c59d3255595dfe523b11020/src/nvim/option.c#L2159-L2169

Solution:
- Don't set 'buflisted' in `apply_text_edits`. Set it more narrowly, in
  `apply_workspace_edit` where the semantics requires affected buffers
  to be visible to the user.
- Also skip setting 'buflisted' if it would not be changed, to avoid
  redundant `OptionSet` events.

Fix #37832

### CODE REVIEW

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -710,7 +709,11 @@ function M.apply_workspace_edit(workspace_edit, position_encoding)
       elseif change.kind then --- @diagnostic disable-line:undefined-field
         error(string.format('Unsupported change: %q', vim.inspect(change)))
       else
+        local bufnr = vim.uri_to_bufnr(change.textDocument.uri)
         M.apply_text_document_edit(change, idx, position_encoding, workspace_edit.changeAnnotations)
+        if not vim.bo[bufnr].buflisted then
+          vim.bo[bufnr].buflisted = true
```
Comment (justinmk) [inline runtime/lua/vim/lsp/util.lua]: why check `vim.bo[bufnr].buflisted` before setting it? if it's not changed I would expect that to be a no-op. does it trigger an event(s), even if the value is unchanged? if so, that sure is worth mentioning in a 1-line comment...

**Comment by justinmk** [comment]
if this is a bug from https://github.com/neovim/neovim/commit/2f6d1d3c887a87d9402137425b418dd12a904aac then the commit message should mention that

**Comment by justinmk** [comment]
Why is BufDelete mentioned here? From the linked issue it sounds like it was just something that a third-party plugin was doing. Please explain.

**Comment by glepnir** [comment]
When apply_text_edits is called on a buffer where buflisted is false, it triggers this condition when the values are not equal.

https://github.com/neovim/neovim/blob/65ef6cec1cb766334c59d3255595dfe523b11020/src/nvim/option.c#L2159-L2169

File: runtime/lua/vim/lsp/util.lua [hunk 2]
```diff
@@ -710,7 +709,12 @@ function M.apply_workspace_edit(workspace_edit, position_encoding)
       elseif change.kind then --- @diagnostic disable-line:undefined-field
         error(string.format('Unsupported change: %q', vim.inspect(change)))
       else
+        local bufnr = vim.uri_to_bufnr(change.textDocument.uri)
         M.apply_text_document_edit(change, idx, position_encoding, workspace_edit.changeAnnotations)
+        -- avoid triggering OptionSet
+        if not vim.bo[bufnr].buflisted then
```
Comment (justinmk) [inline runtime/lua/vim/lsp/util.lua:715]: ~~shouldn't this mention BufDelete?~~

oh, this `if not` condition is only for `OptionSet`, which is unrelated to the main point of this PR which is to avoid `BufDelete` (which does *not* trigger if 'buflisted' is *unchanged*).

this was confusing to figure out, which slows down review...
