### PR TITLE
`vim.version` improvements

### LINKED ISSUE #34708: `vim.version.range('<=a.b.c')` is not precise about its upper bound
### Problem

Version ranges like '<=a.b.c' in `vim.version.range()` include more versions than it should (which is "less or equal to 'a.b.c'"). Examples:
- `vim.version.range('<=1.2.3')` includes pre-releases of 1.2.4.
- `vim.version.range('<=1.2.3-alpha')` includes 1.2.3.
- `vim.version.range('<=1.2.3-beta')` includes 1.2.4-alpha.

This is because version ranges are right-side-exclusive and '<=a.b.c' ranges are implemented by increase patch number by 1.

### Steps to reproduce

1. `nvim --clean`
2. All of the following should return `false`, but they return `true`:
    - `:=vim.version.range('<=1.2.3'):has('1.2.4-alpha')`
    - `:=vim.version.range('<=1.2.3-alpha'):has('1.2.3')`
    - `:=vim.version.range('<=1.2.3-beta'):has('1.2.4-alpha')`

### Expected behavior

Version range '<=a.b.c' is treated as "less or equal to 'a.b.c'" and never includes versions that are strictly greater than 'a.b.c'.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-690+gc752016976

### Vim (not Nvim) behaves the same?

No, doesn't have this functionality

### Operating system/version

EndeavourOS Linux x86_64

### Terminal name/version

Ghostty 1.1.3-arch1

### $TERM environment variable

xterm-ghostty

### Installation

From source

### PR DESCRIPTION
**Pull request by echasnovski**
This PR makes several improvements to `vim.version`. Mostly for things that might/will be useful for #34009 follow-up work. In particular:
- Document `vim.VersionRange` class separately. Its structure is already documented, so having a dedicated class documentation with tag is something that is used in other places. Didn't do this for `vim.Version`, because its fields were not documented.
- Make `tostring()` on version range return human-readable range representation, in a way that `vim.version.range(tostring(r)) == r` for any version range `r`. This is useful to serialize version ranges to be stored in a (lock)file.
- Fix #34708. The solution is slightly hacky which should work for most common situations, as the proper solution (allow manually set inclusiveness of range edges) is too intrusive.
- Add `vim.version.intersect()` to compute intersection of two ranges. This is useful when computing allowed range from several semver constraints.

One other thing that would be useful outside of `vim.version` is to have a dedicated way to check if an object is a version and if it is a version range. But I am not sure if there is an established pattern to check if an object is an instance of a certain class.

### CODE REVIEW

File: runtime/lua/vim/version.lua [hunk 1]
```diff
@@ -341,7 +353,24 @@ function M.range(spec) -- Adapted from https://github.com/folke/lazy.nvim
       end
     end
     ---@diagnostic enable: need-check-nil
-    return setmetatable({ from = from, to = to }, { __index = VersionRange })
+    return setmetatable({ from = from, to = to }, range_mt)
+  end
+end
+
+--- Compute common range
```
Comment (justinmk) [inline runtime/lua/vim/version.lua]: missing `@since`

```suggestion
--- Computes the common range shared by the given ranges.
```

File: runtime/lua/vim/version.lua [hunk 2]
```diff
@@ -341,7 +353,24 @@ function M.range(spec) -- Adapted from https://github.com/folke/lazy.nvim
...
+---
+--- @param r1 vim.VersionRange First range to intersect.
+--- @param r2 vim.VersionRange Second range to intersect.
+--- @return vim.VersionRange? Biggest range that is present inside both `r1` and `r2`.
```
Comment (justinmk) [inline runtime/lua/vim/version.lua]:
```suggestion
--- @return vim.VersionRange? Maximal range that is present inside both `r1` and `r2`.
```

**Review by justinmk — APPROVED** [review]
Nice choices

File: runtime/lua/vim/version.lua (hunk 1 above)
Comment (echasnovski) [reply runtime/lua/vim/version.lua]: > missing `@since`

Didn't add it since it results in the "WARNING: This feature is experimental/unstable." in documentation. So I thought it is planned to somehow be added during the release. And there is no `@since 14` in the code base yet, although there were new functions (#33703).

So just to double-check: should it still be added now?

Comment (echasnovski) [reply runtime/lua/vim/version.lua]: I've found [the recommendation](https://github.com/neovim/neovim/blob/d6d1bfd20da05e8bd40441ecdc0ac75af66f77eb/runtime/doc/develop.txt#L250-L253), so it is probably intended. My bad, didn't know about this. Added `@since 14`.

File: test/functional/lua/version_spec.lua [hunk 3]
```diff
@@ -58,10 +58,10 @@ describe('version', function()
       ['1.2.3'] = { from = { 1, 2, 3 }, to = { 1, 2, 3 } },
       ['1.2'] = { from = { 1, 2, 0 }, to = { 1, 3, 0 } },
       ['=1.2.3'] = { from = { 1, 2, 3 }, to = { 1, 2, 3 } },
-      ['>1.2.3'] = { from = { 1, 2, 4 } },
+      ['>1.2.3'] = { from = '1.2.4-alpha' },
```
Comment (brianhuster) [inline test/functional/lua/version_spec.lua:61]: Does semver spec specify that the first prerelease version is "alpha"?

Comment (brianhuster) [inline test/functional/lua/version_spec.lua]:
```suggestion
      ['>1.2.3'] = { from = '1.2.4-0' },
```

File: runtime/lua/vim/version.lua [hunk 4]
```diff
@@ -314,9 +316,19 @@ function M.range(spec) -- Adapted from https://github.com/folke/lazy.nvim
...
     elseif mods == '<=' then
       from = M._version({})
-      to.patch = to.patch + 1
+      -- HACK: construct the smallest reasonable version bigger than `to`
+      -- to simulate `<=` while using exclusive right hand side
+      if to.prerelease then
+        to.prerelease = to.prerelease .. 'a'
+      else
+        to.patch = to.patch + 1
+        to.prerelease = 'alpha'
```
Comment (brianhuster) [inline runtime/lua/vim/version.lua]: From https://semver.org/#spec-item-9.
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.--.

```suggestion
        to.prerelease = '0'
```

Comment (echasnovski) [reply runtime/lua/vim/version.lua]: Yeah, indeed, this looks better. Thanks!

File: runtime/lua/vim/version.lua [hunk 5]
```diff
@@ -314,9 +316,19 @@ function M.range(spec) -- Adapted from https://github.com/folke/lazy.nvim
...
+      end
     elseif mods == '>' then
       from.patch = from.patch + 1
+      -- HACK: construct the smallest reasonable version bigger than `from`
+      -- to simulate `>` while using inclusive left hand side
+      from.prerelease = 'alpha'
```
Comment (brianhuster) [inline runtime/lua/vim/version.lua]:
```suggestion
      from.prerelease = '0'
```

File: runtime/lua/vim/version.lua (hunk 4 above)
Comment (echasnovski) [reply runtime/lua/vim/version.lua]: > From https://semver.org/#spec-item-9.

Yes, I've seen this. I missed the other part:

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows:
> 
> 1. Identifiers consisting of only digits are compared numerically.
> 2. Identifiers with letters or hyphens are compared lexically in ASCII sort order.
> 3. **Numeric identifiers always have lower precedence than non-numeric identifiers.**
> 4. A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal.

I am a bit torn on using `-0` suffix as is due to `Numeric identifiers MUST NOT include leading zeroes.`. But I guess `0` by itself is not a leading zero. Even if it is, later changing to `-1` is trivial.

Comment (brianhuster) [reply runtime/lua/vim/version.lua]: Yes, I think "0" is leading zeroes in things like "01", "02", "0a", etc

**Comment by echasnovski** [comment]
@justinmk, should `vim.version.intersect()` also accept string range specification as input?
Now it requires something like `vim.version.intersect(vim.version.range('>=1.2.3'), vim.version.range('<1.3.0'))`, which is enough (both for 'vim.pack' and in general), but it might be nicer to allow `vim.version.intersect('>=1.2.3', '<1.3.0')`

**Comment by justinmk** [comment]
> should `vim.version.intersect()` also accept string range specification as input?

i'd say no, but cmp/gt/etc support it so... sigh. either way is fine w/ me

**Comment by echasnovski** [comment]
> > should `vim.version.intersect()` also accept string range specification as input?
> 
> i'd say no, but cmp/gt/etc support it so... sigh. either way is fine w/ me

Let's just keep it as is then. Can always be added later if needed for some reason.

I think it is ready to merge.
