### PR TITLE
fix(vim.pack): skip checkout on bad `version`

### LINKED ISSUE #36037: vim.pack.add checkouts the repository's default branch when the commit specified in the `version` field is not available
### Problem

 `vim.pack` install plugins in two steps :

1. First, it clones the remote repository.
2. Then it checkouts the correct revision

If this process gets interrupted, the local clone of the plugin is left at revision pointed by the remote repository's `HEAD` instead of the revision specified by the `version` field.

This is a security issue, because this behavior could be exploited by a malicious user.

### Steps to reproduce

Requirements :

- An account on a public Git hosting service
- Ability to create and delete public Git repositories, and push commits

1. Create a public repository with an empty plugin :

   ```bash
   mkdir -p some-plugin/lua
   cat << "EOF" > some-plugin/lua/some-plugin.lua
   local M = {}

   function M.setup()
     vim.notify("This is a Neovim plugin")
   end

   return M
   EOF
   pushd some-plugin
   git init
   git add .
   git commit --no-edit -m 'add a plugin'
   git branch -M main
   git remote add origin git@example.org:some-plugin.git
   git push -u origin main
   ```

   In this example :

   - The public URL of the plugin's Git repository is <https://example.org/some-plugin.git>
   - The hash of the latest commit is `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

2. Adds the following lines to `init.lua` and restart Neovim :

   ```lua

   -- Installs the plugin
   vim.pack.add({
     {
         src = "https://example.org/some-plugin.git",
         version = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
     }
   })

   -- Initialize the plugin
   require('some-plugin').setup()
   ```

    At this stage, executing the command `:messages` displays the message :

    ```text
    This is a Neovim plugin
    ```

3. Amend the latest commit on the plugin's Git repository :

   ```bash
   sed -i 's/Neovim/malicious &/' lua/some-plugin.lua
   git commit --all --amend --reset-author --no-edit
   ```

   After executing those commands, the file `lua/some-plugin.lua` contains :

   ```lua
   local M = {}

   function M.setup()
     vim.notify("This is a malicious Neovim plugin")
   end

   return M
   ```

4. Delete the public Git repository, and recreate a new one with the same public URL

5. Push the amended commit :

   ```
   git push --force origin main
   ```

6. Delete the local copy of the plugin's repository, in order to force `vim.pack` to reinstall it :

   ```bash
   rm -rf ~/.local/share/nvim/site/pack/core/opt/some-plugin/
   ```

7. Restart Neovim

After those steps, the following error message appears :

```text
Error in /home/user/.config/nvim/init.lua:
E5113: Lua chunk: ...er/.local/lib/neovim/share/nvim/runtime/lua/vim/pack.lua:729: vim.pack:             
                                                                                                         
`some-plugin`:                                                                                           
...er/.local/lib/neovim/share/nvim/runtime/lua/vim/pack.lua:485: `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` is not a branch/tag/commit. Available:                                                                
Tags:                                                                                                    
Branches: main                                                                                           
stack traceback:                                                                                         
        [C]: in function 'error'                                                                         
        ...er/.local/lib/neovim/share/nvim/runtime/lua/vim/pack.lua:729: in function 'add'               
        /home/user/.config/nvim/lua/user/plugins.lua:1: in main chunk                                 
        [C]: in function 'require'                                                                       
        /home/user/./config/nvim/init.lua:28: in main chunk 
```

If Neovim is restarted a second time, executing the command `:messages` will display the message `This is a malicious Neovim plugin`.

If a lua module from the plugin is dynamically loaded (for instance, in a key mapping) the malicious code will get executed without restarting Neovim.

This is a security issue, because:

- Steps 3 to 5 could be done by a malicious user  (someone who would have stolen the credentials of a plugin's author)
- Steps 6 and 7 force `vim.pack` to reinstall the plugin. This could also happen if a user copy theirs Neovim configuration from one machine to another

### Expected behavior

If the revision specified by the `version` is not found, installation should fail without leaving the local clone of the repository in an inconsistent state.

### Nvim version (nvim -v)

v0.12.0-dev-1359+g94bd212d

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Fedora Linux 42.20251004.0 (Kinoite)

### Terminal name/version

foot 1.24.0

### $TERM environment variable

foot

### Installation

build from repo

### PR DESCRIPTION
**Pull request by m-r-r**
Close #36037

### CODE REVIEW

File: test/functional/plugin/pack_spec.lua [hunk 1]
```diff
@@ -432,6 +432,27 @@ describe('vim.pack', function()
...
+      eq(
+        'number',
+        type(err:find('`deadbeefdeadbeefdeadbeefdeadbeefdeadbeef` is not a branch/tag/commit'))
+      )
+
+      local plug_path = pack_get_plug_path('basic')
+      local entries = vim.iter(vim.fs.dir(plug_path)):totable()
+
+      eq(true, vim.deep_equal(entries, { { '.git', 'directory' } }))
+    end)
```
Comment (echasnovski) [inline test/functional/plugin/pack_spec.lua]:
```suggestion
    it('does not checkout on bad `version`', function()
      local err = pcall_err(exec_lua, function()
        vim.pack.add({ { src = repos_src.basic, version = 'not-exist' } })
      end)
      matches('`not%-exist` is not a branch/tag/commit', err)

      local plug_path = pack_get_plug_path('basic')
      local entries = vim.iter(vim.fs.dir(plug_path)):totable()
      eq({ { '.git', 'directory' } }, entries)
    end)
```

**Review by echasnovski — CHANGES_REQUESTED** [review]
Thanks for the PR!

Looks reasonable and simple enough. The test can be a bit more compact, though.

File: test/functional/plugin/pack_spec.lua (hunk 1 above)
Comment (m-r-r) [reply test/functional/plugin/pack_spec.lua]: Thanks for your input ! It is indeed easier to read.

**Review by echasnovski — APPROVED** [review]
Looks good to me. Thanks!
