### PR TITLE
fix(paste): improve repeating of pasted text

### LINKED ISSUE #28561: bracketed paste not stored in macro recording
### Problem

When I use Neovim in a terminal and copy paste some text in insert mode, I expect the effect to be more or less as if I wrote that text with the keyboard instead of pasting it. When recording a macro, that's not the case: if I record a macro and paste some text (for example to add a line of text) during the recording, then that text is not added when executing the macro.

### Steps to reproduce

- Copy some text to the clipboard
- Start a terminal that supports bracketed paste mode (I tested with gnome-terminal and wezterm)
- Start Neovim (nvim --clean)
- Start a macro: [q][q]
- Start insert mode: [i]
- Paste the text in the terminal with [Ctrl-Shift-V]
- Exit insert mode and stop the macro: [Esc], [q]
- Replay the macro: [@][q]

Result: the text is not added again.

### Expected behavior

The macro should add the text that was copy-pasted during the recording.

### Neovim version (nvim -v)

v0.9.6-dev-18+g0ef27180e

### Vim (not Nvim) behaves the same?

No (Vim 9.1)

### Operating system/version

Debian testing

### Terminal name/version

gnome-terminal 3.50.1

### $TERM environment variable

xterm-256color

### Installation

Build from repo (0.9 branch)

### PR DESCRIPTION
**Pull request by zeertzjq**
- Fixes 'autoindent' being applied during redo.
- Makes redoing a large paste significantly faster.
- Stores pasted text in the register being recorded.

Fix #28561

### CODE REVIEW

**Comment by zeertzjq** [comment]
This PR makes redoing a large paste significantly faster. With the same build type and a 15MB log file:
- Before this PR, pasting the file takes several seconds, while redoing the paste takes over a minute.
- After this PR, both pasting the file and redoing the paste takes several seconds.

File: src/nvim/getchar.c [hunk 1]
```diff
@@ -3182,3 +3189,121 @@ bool map_execute_lua(bool may_repeat)
...
 }
+
+/// Appends pasted text to redo buffer and/or record buffer if needed.
+/// Escapes all K_SPECIAL and NUL bytes in the content.
+///
+/// @param state  kFalse for the start of a paste
+///               kTrue for the end of a paste
+///               kNone for the content of a paste
+/// @param str    the content of the paste (only used when state is kNone)
+void store_pasted_text(const TriState state, const String str, const bool crlf)
```
Comment (justinmk) [inline src/nvim/getchar.c:3200]: is it worth using a common prefix?
```suggestion
void paste_store(const TriState state, const String str, const bool crlf)
```

File: src/nvim/getchar.c [hunk 2]
```diff
@@ -3182,3 +3189,121 @@ bool map_execute_lua(bool may_repeat)
...
+      }
+      if (need_record) {
+        add_byte_buff(&recordbuff, c);
+      }
+    }
+  }
+}
+
+/// Gets a paste stored by store_pasted_text() from typeahead and repeats it.
+void repeat_pasted_text(int count)
```
Comment (justinmk) [inline src/nvim/getchar.c:3265]:
```suggestion
void paste_repeat(int count)
```

File: src/nvim/getchar.c (hunk 1 above)
Comment (zeertzjq) [reply src/nvim/getchar.c]: Yes

File: src/nvim/api/vim.c [hunk 3]
```diff
@@ -1259,30 +1259,19 @@ Boolean nvim_paste(String data, Boolean crlf, Integer phase, Arena *arena, Error
...
-      // readfile()-style: "\n" is indicated by presence of N+1 item.
-      if (i + 1 < lines.size) {
-        AppendCharToRedobuff(NL);
-      }
-    }
-  }
-  if (!(State & (MODE_CMDLINE | MODE_INSERT)) && (phase == -1 || phase == 3)) {
-    AppendCharToRedobuff(ESC);  // Dot-repeat.
+  if (!cancel) {
+    paste_store(kNone, data, crlf);
```
Comment (justinmk) [inline src/nvim/api/vim.c:1269]: the `AppendCharToRedobuff` hacks were already attempting to "fixup" the input buffer, so arguably `paste_store` is just formalizing that. 👍

File: src/nvim/getchar.c [hunk 4]
```diff
@@ -3182,3 +3189,121 @@ bool map_execute_lua(bool may_repeat)
...
+
+  got_int = false;
+  while (!aborted) {
+    ga_grow(&ga, 32);
+    uint8_t c1 = (uint8_t)vgetorpeek(true);
+    if (c1 == K_SPECIAL) {
+      c1 = (uint8_t)vgetorpeek(true);
+      uint8_t c2 = (uint8_t)vgetorpeek(true);
+      int c = TO_SPECIAL(c1, c2);
+      if (c == K_PE) {
```
Comment (justinmk) [inline src/nvim/getchar.c:3280]:
```suggestion
      if (c == K_PE) {  // <PasteEnd>
```

File: src/nvim/getchar.c [hunk 5]
```diff
@@ -3182,3 +3189,121 @@ bool map_execute_lua(bool may_repeat)
   ga_clear(&line_ga);
   return true;
 }
+
+/// Appends pasted text to redo buffer and/or record buffer if needed.
```
Comment (justinmk) [inline src/nvim/getchar.c:3193]:
```suggestion
/// Wraps pasted text stream with <PasteStart> and <PasteEnd> and appends to redo buffer and/or record buffer if needed.
```

File: src/nvim/normal.c [hunk 6]
```diff
@@ -6593,6 +6594,11 @@ static void nv_open(cmdarg_T *cap)
   }
 }
 
+static void nv_paste(cmdarg_T *cap)
```
Comment (justinmk) [inline src/nvim/normal.c:6597]: can we give a hint that mentions `<PasteStart>`. 

```suggestion
/// Handles <PasteStart>, repeats pasted text.
static void nv_paste(cmdarg_T *cap)
```

File: src/nvim/keycodes.c [hunk 7]
```diff
@@ -184,6 +184,9 @@ static const struct key_name_entry {
   { K_KRIGHT,          "kRight" },
   { K_KRIGHT,          "KP6" },
 
+  { K_PS,              "PasteStart" },
```
Comment (justinmk) [inline src/nvim/keycodes.c:187]: can we leave a hint about the intention of these keycodes, to emphasize that they are internal-only and not to be sent directly by UIs
```suggestion
  // Delimits pasted text (input from nvim_paste). Internal-only, not directly sent by UIs.
  { K_PS,              "PasteStart" },
```

**Review by justinmk — COMMENTED** [review]
Is there a way we can add a guardrail to prevent `<pastestart>` from being sent (perhaps accidentally) by `nvim_input` / feedkeys? E.g. show an error.

File: src/nvim/keycodes.c (hunk 7 above)
Comment (zeertzjq) [reply src/nvim/keycodes.c:187]: I can just remove these notations.

File: src/nvim/getchar.c [hunk 8]
```diff
@@ -3182,3 +3189,121 @@ bool map_execute_lua(bool may_repeat)
...
+
+  const bool need_redo = !block_redo;
+  const bool need_record = reg_recording != 0 && reg_executing == 0;
+
+  if (!need_redo && !need_record) {
+    return;
+  }
+
+  if (state != kNone) {
+    const int c = state == kFalse ? K_PS : K_PE;
```
[the remark this answers is not in the document]
Comment (zeertzjq) [reply src/nvim/getchar.c:3215]: I've removes these two notations. Maybe I should remove rename them `K_PASTE_START` and `K_PASTE_END`?

**Comment by justinmk** [comment]
I added this to news.txt in https://github.com/neovim/neovim/pull/30494 because this is a very nice improvement, even if it's technically a "bug fix".
