### PR TITLE
fix(pack): add more detailed suggestion for fixing out-of-sync lockfile

### LINKED ISSUE #38929: Lockfile desync if `vim.pack.update` succeeds `git checkout` but fails to write lockfile
## Problem

If `vim.pack.update()` succeeds to do `git checkout ${rev}` but fails to write the lockfile, the state between the lockfile and actual repositories desyncs. And doing `vim.pack.update()` afterwards reports "Same" and "nothing to update". The lock file won't be updated.

This desync is less noticable.

## Workaround

Remove lockfile and try to update again?

### Steps to reproduce

```bash
cd $(mktemp -d)
mkdir config data
export XDG_CONFIG_HOME=$(pwd)/config
export XDG_DATA_HOME=$(pwd)/data
nvim --clean
:lua vim.pack.add({{src="https://github.com/neovim/nvim-lspconfig",version=vim.version.range '2.6.0'}})
:qa
# mocking fail write
cd ./data/nvim/site/pack/core/opt/nvim-lspconfig/
# 2.7.0
git checkout 0203a9608d63eda57679b01e69f33a7b4c34b0d1
cd -
nvim --clean ./config/nvim/nvim-pack-lock.json
# modify version field from "2.6.0 - 2.6.0" -> ">=0.0.0"
:w
:qa
nvim --clean
:lua vim.pack.update()
```

`vim.pack.update()`  confirmation buffer shows up. But It reports "Same".
It leaves lockfile unchanged.

### Expected behavior

The lockfile upated.

### Nvim version (nvim -v)

NVIM v0.13.0-dev-133+g6d43869aa0

### Vim (not Nvim) behaves the same?

no, vim does not have vim.pack API

### Operating system/version

6.6.87.2-microsoft-standard-WSL2

### Terminal name/version

weztern

### $TERM environment variable

xterm-256color

### Installation

Built from source

### PR DESCRIPTION
**Pull request by echasnovski**
Problem: If the lockfile points to the revision that is not on disk, the `:checkhealth vim.pack` suggests to run `vim.pack.update()`. Although usually it should resolve the problem, it is not always the case: like if the state on disk is already the latest available.

Solution: Add an extra suggestion with a more drastic measure by manually removing `rev` field from the lockfile for it to be repaired after the `:restart`.

---

Resolve #38929

### CODE REVIEW

File: runtime/lua/vim/pack/health.lua [hunk 1]
```diff
@@ -128,7 +128,9 @@ local function check_plugin_lock_data(plug_name, lock_data)
       ('Plugin %s is not at expected revision\n'):format(name_str)
         .. ('Expected: %s\nActual:   %s\n'):format(lock_data.rev, head)
         .. 'To synchronize, restart Nvim and run '
-        .. ('`vim.pack.update({ %s }, { offline = true })`'):format(name_str)
+        .. ('`vim.pack.update({ %s }, { offline = true })`\n'):format(name_str)
+        .. 'If there are no updates, delete `rev` lockfile entry (do not create trailing comma) '
+        .. 'and restart Nvim to regenerate lockfile data'
```
Comment (justinmk) [inline runtime/lua/vim/pack/health.lua]: should we mention something about `This can happen if XDG_CONFIG_HOME is read-only.` ? https://github.com/neovim/neovim/issues/38929#issuecomment-4224168874

Comment (echasnovski) [reply runtime/lua/vim/pack/health.lua]: I don't really know how much detailed the suggestion are welcome in `:checkhealth` output. The current text is the one that I think is enough. If you want to, I can add it, of course. Should I?

Comment (justinmk) [reply runtime/lua/vim/pack/health.lua]: hints about common situations are always welcome in checkhealth :)

Comment (echasnovski) [reply runtime/lua/vim/pack/health.lua]: Pushed the change with that note. Here is how it looks now:

screenshot_2026-04-10_17:05:01
