### PR TITLE
floatwin: show error if window is closed immediately

### LINKED ISSUE #11383: Reproducible floating window crash when used with wincmd
Version 0.4.2 to current master

```lua
local api = vim.api
local should_crash = true
local function crashes(contents)
  local floating_bufnr = api.nvim_create_buf(false, true)
  local floating_winnr = api.nvim_open_win(floating_bufnr, true, {
    relative = 'cursor';
    style = should_crash and 'minimal' or nil;
		row = 0; col = 0;
    height = #contents;
    width = 10;
  })
  api.nvim_buf_set_lines(floating_bufnr, 0, -1, true, contents)
  local floating_win = api.nvim_call_function('win_id2win', {floating_winnr})
  api.nvim_command("wincmd p")
  api.nvim_command("autocmd CursorMoved * ++once "..floating_win.."wincmd c")
  return floating_bufnr, floating_winnr
end
crashes{"foo"}
crashes{"bar"}
```

`nvim -u NORC +"luafile buggy.lua"` will cause a crash.

Discovered from old LSP code. The style affects this for some reason, so if you change `should_crash` to false, it stops crashing.

Every piece here is essential to the conditions for crashing: 

- Removing `...CursorMoved...` will not cause a crash
- Removing `wincmd p` will not cause a crash
- Not entering with (i.e. `enter=false` for  `nvim_open_win(..., enter`) will not cause a crash

This leads me to suspect that the issue is due to `wincmd` for a closed window, but I'm not certain. @bfredl

### PR DESCRIPTION
**Pull request by justinmk**
Autocmds may close window while it is being entered, then win_set_minimal_style(wp) operates on an invalid pointer.

We could silently ignore this instead, but it is unlikely to be intentional, so it is more useful to show an error.

fix #11383

### CODE REVIEW

File: test/functional/ui/float_spec.lua [hunk 1]
```diff
@@ -56,6 +58,31 @@ describe('floating windows', function()
     eq(1000, funcs.win_getid())
   end)
 
+  it('closed immediately by autocmd #11383', function()
+    eq('Error executing lua: [string "<nvim>"]:4: Window was closed immediately',
```
Comment (blueyed) [inline test/functional/ui/float_spec.lua]: nit (and for another PR anyway): shouldn't that be s/lua/Lua?  (IIRC Lua people really care about it)

**Review by blueyed — APPROVED** [review]

File: test/functional/ui/float_spec.lua (hunk 1 above)
Comment (justinmk) [reply test/functional/ui/float_spec.lua]: Yes. I've tried to title-case Lua everywhere in our docs/messages, because that's more readable (`l` looks like capital `i`), and because that's how the project is named (similar to "Vim", "Nvim").

Comment (bfredl) [reply test/functional/ui/float_spec.lua]: Though I would say "Lua" is "Lua the language" or "Lua the Project" while it is perfectly fine to refer to "some lua code"  as "lua" (which this error message is about), just as we invoke it as `v:lua`, `luaeval()` etc. We don't capitalize other feature or language names in error messages.

**Review by bfredl — APPROVED** [review]

File: test/functional/ui/float_spec.lua (hunk 1 above)
Comment (blueyed) [reply test/functional/ui/float_spec.lua]: I (and "they") would say "some Lua code" - I'd also say "Python code".
While quickly looking at the source, there's also "Vim(lua):E5107: Error loading lua" though, where the first one is ok to be lowercase since that's the command.

The one above/here is also about the command though, isn't it?

**Comment by blueyed** [comment]
Re-submitted the freebsd build, but will not show up in the status apparently (in my namespace): https://builds.sr.ht/~blueyed/job/115918

File: test/functional/ui/float_spec.lua (hunk 1 above)
Comment (bfredl) [reply test/functional/ui/float_spec.lua]: > While quickly looking at the source, there's also "Vim(lua):E5107: Error loading lua" though, where the first one is ok to be lowercase since that's the command. The one above/here is also about the command though, isn't it?

Well, that's just my point: we are currently using lower-case lua everywhere in error messages (except for beginning of sentence). I don't think there is anything particularly wrong with the current status-quo to need to change, though if someone wants goes through every error message and every test and changes it consistently, they can do so of course :]

Comment (blueyed) [reply test/functional/ui/float_spec.lua]: Yeah, wouldn't be too bad probably, but it is also not clear if the above refers to the `:lua` command, or "Lua code" - it just reads like the latter, but comes from/via the first probably.
