### PR TITLE
fix(ui-ext): log and clear error in ui_comp_event

### LINKED ISSUE #20789: vim.ui_attach: memory leak with error in callback
### Neovim version (nvim -v)

v0.9.0-dev-155+g771824128

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.26.4

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Run `nvim --clean`
2. Source the following Lua file:
```lua
local ns = vim.api.nvim_create_namespace('foo')

vim.ui_attach(ns, { ext_popupmenu = true }, function(event)
  if event == 'popupmenu_show' then
    error('foo')
  end
end)

vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('i<C-X><C-V>', false, true, true), 'tnix', false)

vim.ui_detach(ns)
```

### Expected behavior

No memory leak

### Actual behavior

Memory leak:
```
=================================================================
==273991==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 195 byte(s) in 1 object(s) allocated from:
    #0 0x557c6adbac69 in malloc (**/build/bin/nvim+0xcecc69) (BuildId: 4006f3fe6d4562c26665844be88dfbbc6c9eb236)
    #1 0x557c6bb47372 in try_malloc **/src/nvim/memory.c:80:15
    #2 0x557c6bb4753c in xmalloc **/src/nvim/memory.c:114:15
    #3 0x557c6afd88d8 in api_set_error **/src/nvim/api/private/helpers.c:816:14
    #4 0x557c6b933599 in nlua_call_ref **/src/nvim/lua/executor.c:1523:7
    #5 0x557c6c462ded in ui_comp_event **/src/nvim/ui_compositor.c:708:3
    #6 0x557c6c416fe3 in ui_call_event **/build/src/nvim/auto/ui_events_call.generated.h:245:3
    #7 0x557c6c4276cf in ui_call_popupmenu_show **/build/src/nvim/auto/ui_events_call.generated.h:343:3
    #8 0x557c6be528a3 in pum_display **/src/nvim/popupmenu.c:168:9
    #9 0x557c6b8c27cc in ins_compl_show_pum **/src/nvim/insexpand.c:1264:3
    #10 0x557c6b8d23a5 in show_pum **/src/nvim/insexpand.c:4292:3
    #11 0x557c6b8cf92a in ins_complete **/src/nvim/insexpand.c:4270:5
    #12 0x557c6b2c793d in insert_do_complete **/src/nvim/edit.c:1180:7
    #13 0x557c6b2a3ef4 in insert_execute **/src/nvim/edit.c:615:5
    #14 0x557c6c2832e7 in state_enter **/src/nvim/state.c:88:26
    #15 0x557c6b2aca0c in insert_enter **/src/nvim/edit.c:331:5
    #16 0x557c6b2a16fe in edit **/src/nvim/edit.c:1256:3
    #17 0x557c6bcad66e in invoke_edit **/src/nvim/normal.c:7054:7
    #18 0x557c6bc83af7 in nv_edit **/src/nvim/normal.c:7031:5
    #19 0x557c6bc6dbf5 in normal_execute **/src/nvim/normal.c:1173:3
    #20 0x557c6bc668bf in normal_cmd **/src/nvim/normal.c:7413:9
    #21 0x557c6b641118 in exec_normal **/src/nvim/ex_docmd.c:6446:5
    #22 0x557c6b019448 in nvim_feedkeys **/src/nvim/api/vim.c:299:5
    #23 0x557c6ae220f0 in nlua_api_nvim_feedkeys **/build/src/nvim/auto/lua_api_c_bindings.generated.c:3272:3
    #24 0x557c6c7ccf95 in lj_BC_FUNCC (**/build/bin/nvim+0x26fef95) (BuildId: 4006f3fe6d4562c26665844be88dfbbc6c9eb236)

SUMMARY: AddressSanitizer: 195 byte(s) leaked in 1 allocation(s).
```

### PR DESCRIPTION
**Pull request by andrewwillette**
Fix #20789

Fix for memory leak in ui_comp_event. See [issue 20789 for more context](https://github.com/neovim/neovim/issues/20789).

I've verified that `make unittest` passes. I've had issues prior to this change, on `master`, where `make functionaltest` fails(with a timeout) on `timer_spec.lua`. Unfortunately it's still the case, and I cannot verify that they pass. I'm hoping the CI pipeline will handle the valid testing for me.

Thanks for your time.

### CODE REVIEW

**Comment by andrewwillette** [comment]
@zeertzjq , thrilled to see you kicked off the build!

I'm uncertain why the windows stage failed. I've looked to other pull requests to see if it could be an issue elsewhere, I haven't seen anything to make me believe so. Have you seen the intermittent failures on the Windows stage before?

**Comment by zeertzjq** [comment]
Yes. This failure has happened intermittently.

File: src/nvim/ui_compositor.c [hunk 1]
```diff
@@ -716,6 +716,11 @@ static void ui_comp_event(UI *ui, char *name, Array args)
       handled = true;
     }
   })
+  if (err.type != kErrorTypeNone) {
```
Comment (bfredl) [inline src/nvim/ui_compositor.c:719]: we should do this inside of the loop. multiple `event_cb->cb` could error out. also `api_clear_error()` should not be in an else branch.

Comment (andrewwillette) [reply src/nvim/ui_compositor.c]: @bfredl, thanks for reviewing the PR.

I saw the iteration issue when I first made the change, and tried the below:

```C
map_foreach_value(&ui_event_cbs, event_cb, {
  Error err = ERROR_INIT;
  Object res = nlua_call_ref(event_cb->cb, name, args, false, &err);
  if (res.type == kObjectTypeBoolean && res.data.boolean == true) {
    handled = true;
  }
  if (err.type != kErrorTypeNone) {
    ELOG("Error while executing ui_comp_event callback: %s", err.msg);
  }
  api_clear_error(&err);
})
```

but I was getting the compiler error of `too many arguments provided to function-like macro invocation`. I'm a C novice and wasn't sure how to approach it. With your review, I've made an attempt at handling the error for each iteration. Please let me know if there's a better way to do it.

Thank you for your time, I appreciate it.

**Comment by andrewwillette** [comment]
@bfredl, the build failed with commit linter issue : commit not having colon. I've force pushed to handle this.

File: src/nvim/ui_compositor.c [hunk 2]
```diff
@@ -711,11 +711,17 @@ static void ui_comp_event(UI *ui, char *name, Array args)
   bool handled = false;
 
   map_foreach_value(&ui_event_cbs, event_cb, {
+    err.type = kErrorTypeNone;
+    err.msg = NULL;
```
Comment (zeertzjq) [inline src/nvim/ui_compositor.c:715]: It seems that `Error err = ERROR_INIT` declation and `api_clear_error(&err)` should both be moved inside this loop.

Comment (andrewwillette) [reply src/nvim/ui_compositor.c:715]: Sorry for delayed response, Thanksgiving, travelling, learning C macros.

I made an attempt at this and discussed the issue [in the above comment on the PR](https://github.com/neovim/neovim/pull/21147#discussion_r1029735065).

I've made more attempts to get it to work, learning more about C macros along the way. I believe the reason for the `too many arguments provided to function-like macro invocation` compiler error is because the `ERROR_INIT` macro includes a comma:

```C
#define ERROR_INIT { .type = kErrorTypeNone, .msg = NULL }
```

The C preprocessor sees any comma as an argument separator. I could be wrong about this, I gained the insight [from this SO post](https://stackoverflow.com/a/38030161/9168060).

FWIW, defining `ERROR_INIT` with just the `.type`, such as below:

```C
#define ERROR_INIT { .type = kErrorTypeNone }
```

does not trigger a compiler error. Leads me to believe the comma is the issue. I made some attempts at workaround, but couldn't find a solution. I'm curious your opinion.

Comment (zeertzjq) [reply src/nvim/ui_compositor.c:715]: Oh, didn't read that carefully. I guess assigning another variable to `ERROR_INIT` and the assigning `err` to that variable inside the loop should work then.

Comment (andrewwillette) [reply src/nvim/ui_compositor.c]: Thank you for the advice! I've followed it, it works.

File: src/nvim/ui_compositor.c [hunk 3]
```diff
@@ -706,16 +706,21 @@ static void ui_comp_grid_resize(UI *ui, Integer grid, Integer width, Integer hei
 
 static void ui_comp_event(UI *ui, char *name, Array args)
 {
-  Error err = ERROR_INIT;
   UIEventCallback *event_cb;
   bool handled = false;
-
+  Error initerr = ERROR_INIT;
```
Comment (zeertzjq) [inline src/nvim/ui_compositor.c:711]:
```suggestion
  const Error initerr = ERROR_INIT;
```

File: src/nvim/ui_compositor.c [hunk 4]
```diff
@@ -706,16 +706,21 @@ static void ui_comp_grid_resize(UI *ui, Integer grid, Integer width, Integer hei
...
     Object res = nlua_call_ref(event_cb->cb, name, args, false, &err);
     if (res.type == kObjectTypeBoolean && res.data.boolean == true) {
       handled = true;
     }
+    if (err.type != kErrorTypeNone) {
+      ELOG("Error while executing ui_comp_event callback: %s", err.msg);
+    }
+    api_clear_error(&err);
   })
+  api_clear_error(&initerr);
```
Comment (zeertzjq) [inline src/nvim/ui_compositor.c:723]: `initerr.type` is always `kErrorTypeNone` so this is not needed.
```suggestion
```

Comment (andrewwillette) [reply src/nvim/ui_compositor.c]: Thanks, made the update.

Interesting to me that that is how it works. The [NULL declaration for](https://github.com/andrewwillette/neovim-willette/blob/2dd8befde1ace73d84edae95c25d807bec0e2d86/src/nvim/api/private/defs.h#L15) `.msg` makes sense that it wouldn't take up any memory, but I'd think `-1` for `kErrorTypeNone` ([link](https://github.com/andrewwillette/neovim-willette/blob/2dd8befde1ace73d84edae95c25d807bec0e2d86/src/nvim/api/private/defs.h#L28)) would. I trust you, you know more than I do here.

File: src/nvim/ui_compositor.c [hunk 5]
```diff
@@ -706,15 +706,19 @@ static void ui_comp_grid_resize(UI *ui, Integer grid, Integer width, Integer hei
...
   bool handled = false;
-
+  const Error initerr = ERROR_INIT;
   map_foreach_value(&ui_event_cbs, event_cb, {
+    Error err = initerr;
     Object res = nlua_call_ref(event_cb->cb, name, args, false, &err);
     if (res.type == kObjectTypeBoolean && res.data.boolean == true) {
       handled = true;
     }
+    if (err.type != kErrorTypeNone) {
```
Comment (zeertzjq) [inline src/nvim/ui_compositor.c:718]:
```suggestion
    if (ERROR_SET(&err)) {
```

File: src/nvim/ui_compositor.c (hunk 4 above)
Comment (zeertzjq) [reply src/nvim/ui_compositor.c]: `type` is stored on the stack and does not need to be freed.

File: src/nvim/ui_compositor.c (hunk 5 above)
Comment (andrewwillette) [reply src/nvim/ui_compositor.c]: Thanks, updated.

File: src/nvim/ui_compositor.c (hunk 4 above)
Comment (andrewwillette) [reply src/nvim/ui_compositor.c]: Thank you. I understand.

**Comment by andrewwillette** [comment]
@zeertzjq, sorry to bother, any chance you could retrigger the CI build? The Windows phase timed out.

File: src/nvim/ui_compositor.c [hunk 6]
```diff
@@ -706,15 +706,19 @@ static void ui_comp_grid_resize(UI *ui, Integer grid, Integer width, Integer hei
 
 static void ui_comp_event(UI *ui, char *name, Array args)
 {
-  Error err = ERROR_INIT;
   UIEventCallback *event_cb;
   bool handled = false;
-
+  const Error initerr = ERROR_INIT;
   map_foreach_value(&ui_event_cbs, event_cb, {
+    Error err = initerr;
```
Comment (bfredl) [inline src/nvim/ui_compositor.c:713]: you could write `(Error)ERROR_INIT` here and get rid of the extra definition

Comment (zeertzjq) [reply src/nvim/ui_compositor.c:713]: That doesn't compile.

Comment (andrewwillette) [reply src/nvim/ui_compositor.c:713]: I tried the below:
```C
  map_foreach_value(&ui_event_cbs, event_cb, {
    Error err = (Error)ERROR_INIT;
    Object res = nlua_call_ref(event_cb->cb, name, args, false, &err);
    if (res.type == kObjectTypeBoolean && res.data.boolean == true) {
      handled = true;
    }
    if (ERROR_SET(&err)) {
      ELOG("Error while executing ui_comp_event callback: %s", err.msg);
    }
    api_clear_error(&err);
  })
```
but the compiler throws the error of : `Too many arguments provided to function-like macro invocation`. I believe it's because the preprocessor sees any comma as an arg separator to a macro, and the `ERROR_INIT` macro [has a comma in its value](https://github.com/andrewwillette/neovim-willette/blob/0ab8fa1371b59ef8d864b6ce8661fbfc4bb04fe7/src/nvim/api/private/defs.h#L15).

Comment (bfredl) [reply src/nvim/ui_compositor.c:713]: This works in multiple already existing code paths in our code base. not sure what causes the preprocessor to throw a childish tantrum in this particular case.

Comment (andrewwillette) [reply src/nvim/ui_compositor.c:713]: I don't see any examples of `map_foreach_value` with a macro with of value `{...,...}` in the repository.

There is [an example](https://github.com/andrewwillette/neovim-willette/blob/0ab8fa1371b59ef8d864b6ce8661fbfc4bb04fe7/src/nvim/channel.c#L940) where the `ADD` macro([link](https://github.com/andrewwillette/neovim-willette/blob/0ab8fa1371b59ef8d864b6ce8661fbfc4bb04fe7/src/nvim/api/private/helpers.h#L77-L78)) is called in the `map_foreach_value`, but I believe this is still valid because the comma exists inside parenthesis. The preprocessor understands values inside parens are separate function args.

The `ERROR_INIT` macro has a comma [inside brackets](https://github.com/andrewwillette/neovim-willette/blob/0ab8fa1371b59ef8d864b6ce8661fbfc4bb04fe7/src/nvim/api/private/defs.h#L15).

I could be wrong, but it is my understanding of the issue.

Comment (andrewwillette) [reply src/nvim/ui_compositor.c]: So I found a solution in line with surrounding the macro in parens! I saw that `STRING_OBJECT` ([link](https://github.com/andrewwillette/neovim-willette/blob/a17b0c947ad128edb9d9c5c54a610107a71e7f0a/src/nvim/api/private/helpers.h#L33-L35)) was used inside other macros, for example `PUT` ([link](https://github.com/andrewwillette/neovim-willette/blob/a17b0c947ad128edb9d9c5c54a610107a71e7f0a/src/nvim/api/autocmd.c#L298)). I followed `STRING_OBJECT`'s pattern (of what looks to be like an anonymous function in C?) to get it to work.

@bfredl / @zeertzjq please let me know if you think the prior implementation is preferable. Thank you for your time.  I really want to get this merged.

Comment (bfredl) [reply src/nvim/ui_compositor.c]: yes, that is the preferred pattern.

Comment (andrewwillette) [reply src/nvim/ui_compositor.c]: @bfredl sorry, I'm not sure I understand. Are you saying I should revert the `ERROR_INIT` [parens update](https://github.com/neovim/neovim/pull/21147/commits/a17b0c947ad128edb9d9c5c54a610107a71e7f0a#diff-5b8e70a02d059fb67689dcdf1385f39c7a6916c2e2e486459301ec9c65da041fR15) or not? If not, can you retrigger the CI pipeline?

**Comment by andrewwillette** [comment]
@bfredl / @zeertzjq can this be merged?
