### PR TITLE
fix(options): repair stale UI state after `set all&`

### LINKED ISSUE #6477: guicursor doesn't take affect after set all&
Starting nvim with `build/bin/nvim -u NONE` in an `xterm`. Then run

```
set guicursor?
set all&
set guicursor?
```
You can see the value has changed, but the affect doesn't change.

Running
```
set guicursor&
```
changes the affect, but it doesn't change the value observed with `set guicursor?`

### PR DESCRIPTION
**Pull request by barrettruth**
## Problem

`set all&` resets option values directly but leaves UI-derived state stale. In #6477 this shows up in `guicursor`; the same bulk-reset path can also leave `laststatus` / `showtabline` out of sync with the visible UI (see comment on #6477).

## Solution

Repair *some* of this stale UI state instead of replaying full per-option setter semantics. This includes reparsing `guicursor`, refreshing statusline state, and recomputing tabline/window rows.

Of course, this does not fix the entire `set all&` path, only these confirmed sub-cases.

fix #6477

### CODE REVIEW

File: src/nvim/option.c [hunk 1]
```diff
@@ -483,6 +483,16 @@ static void change_option_default(const OptIndex opt_idx, OptVal value)
   options[opt_idx].def_val = value;
 }
 
+static void didset_options_all(void)
```
Comment (justinmk) [inline src/nvim/option.c]: should this live below `didset_options2` ?

docstring should give a hint about what this is intended to do. does this look right:

```
/// Repair UI state after `:set all&`.
///
/// `set_options_default` resets option values directly (via `set_option_direct`) without invoking
/// per-option `did_set` callbacks, so UI-derived state (cursor shape, statusline, tabline) can get
/// out of sync. This function patches the known cases.
///
/// Note: We intentionally do not replay all `did_set` callbacks (opt_did_set_cb) because they have
/// order-dependent side effects and old→new transition logic that does not hold when values are
/// already reset.
```

Comment (barrettruth) [reply src/nvim/option.c]: doneski
