### PR TITLE
fixed hang issue with --headless and -r option specified

### LINKED ISSUE #11386: `nvim -r` hangs if the output is "too long"
- `nvim --version`: 0.4.3
- Operating system/version: CentOS 7.3
- Terminal name/version: tmux 1.8 (inside putty)
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

#11181 helped in that we can actually _see_ the swapfile information, but if there are more than a couple entries, we hang.

1. Cause there to be more than 3 swapfiles in `'directory'`
2. Run `nvim -u NORC -r`

### Actual behaviour
nvim displays 2.5 entries of swap information and then hangs.

```
Swap files found:
   In directory ~/.local/share/nvim/swap//:
1.    %home%user%path%to%fileA.swp
          owned by: user   dated: Wed Sep 25 14:35:05 2019
         file name: ~user/path/to/fileA
          modified: no
         user name: user   host name: myhost
        process ID: 26124
2.    %home%user%path%to%fileB.swp
          owned by: user   dated: Fri Oct 25 17:37:54 2019
         file name: ~user/path/to/fileB
          modified: YES
         user name: user   host name: myhost
        process ID: 16402
3.    %home%user%path%to%fileC.swp
          owned by: user   dated: Fri Oct 25 14:46:11 2019
         file name: ~user/path/to/fileC
          modified: 
```

I have to use Ctrl-c to kill nvim.

### Expected behaviour
All swapfile entries are displayed and nvim exits cleanly.

### PR DESCRIPTION
**Pull request by Code-Hex**
fixed https://github.com/neovim/neovim/issues/11386 issues.

Calling the do_more_prompt function in headless mode will freeze neovim because it is eventally in the input-accepting state (the same as waiting for --more--).

I have tried

- `nvim -u NORC -c 'for i in range(0, 1000) | echo i | endfor | quit' --headless`
- `nvim -u NORC -r`

### CODE REVIEW

**Comment by Code-Hex** [comment]
By the way, I think this "Press ENTER or type command to continue" message shouldn't be output in headless mode spec, is my understanding correct?

```
$ nvim -u NORC -c 'ls' --headless

  1 %a   "[No Name]"                    line 0
Press ENTER or type command to continue
```

**Comment by glacambre** [comment]
>By the way, I think this "Press ENTER or type command to continue" message shouldn't be output in headless mode spec, is my understanding correct?

Yes, there's even an issue for this: https://github.com/neovim/neovim/issues/9358 :).

**Comment by Code-Hex** [comment]
A lot of tests have failed...
I think it's due to a lot of tests relying on headless mode. I think we need to work on replacing "Expected" and "Actual", but I can't judge if it's really correct... 😢 

How should I do this?

**Comment by justinmk** [comment]
thanks for tracking this down!



> think we need to work on replacing "Expected" and "Actual", but I can't judge if it's really correct..

where? on travis I only see this:

```
[32m[2m[ RUN      ][0m[0m startup defaults :filetype late `:filetype â€¦ off` stays OFF: -- Tests exited non-zero: SIGPIPE
-- No output to stderr.
CMake Error at /home/travis/build/neovim/neovim/cmake/RunTests.cmake:85 (message):
  functional tests failed with error: SIGPIPE
```

File: src/nvim/main.c [hunk 1]
```diff
@@ -513,6 +513,14 @@ int main(int argc, char **argv)
...
   if (params.n_commands > 0) {
     exe_commands(&params);
+    // If in headless mode, we need to exit at this point.
+    // If we continue, we will enter the normal mode and the
+    // message "Press ENTER or type command to continue" will be
+    // displayed and we will be in the input waiting state.
+    if (headless_mode) {
+      msg_putchar('\n');
+      return 0;
+    }
```
Comment (justinmk) [inline src/nvim/main.c:523]: this probably isn't the right approach. maybe leave this for a separate PR

Comment (Code-Hex) [reply src/nvim/main.c:523]: Thanks.

I understand. I quit to touch this issue (I will focus only for “more”)

**Comment by Code-Hex** [comment]
@justinmk  I think it was difficult.  I will try to fix it

**Comment by Code-Hex** [comment]
@justinmk The main issue has been fixed. Re-review, please!

File: test/functional/core/startup_spec.lua [hunk 2]
```diff
@@ -277,6 +277,24 @@ describe('startup', function()
...
+    end
+    expected = expected .. period
+    eq(
+      expected,
+      -- FIXME(codehex): We should really set a timeout for the system function.
+      -- If this test fails, there will be a waiting input state.
+      funcs.system({nvim_prog, '-u', 'NONE', '-c',
+        'for i in range(1, 100) | echo i | endfor | quit',
+        '--headless'
+      })
```
Comment (Code-Hex) [inline test/functional/core/startup_spec.lua:295]: I'm sorry, I didn't think an idea...

**Comment by Code-Hex** [comment]
Probably, travis CI has been broken
https://travis-ci.org/github/neovim/neovim/jobs/683712510

**Review by tjdevries — APPROVED** [review]
I ran this PR on my local machine and it fixed the exact problem I was having w/ headless mode pausing when I had "a lot" of output.

@justinmk I don't merge C code though as a rule ;) So it's up to you. I have no idea if this is the right fix or not given other  factors.

**Comment by glacambre** [comment]
This PR also closes #12299, that's pretty cool!

**Comment by Code-Hex** [comment]
CI has been passed. (I tried force-push to rerun CI)

**Comment by tjdevries** [comment]
OK, I'll merge tomorrow if I don't hear any complaints. It looks good to me and is a very small change and tests pass. So seems fine to merge

**Comment by Code-Hex** [comment]
@tjdevries merge? 🙏

**Comment by tjdevries** [comment]
@Code-Hex Thanks for fixing and thanks for the ping. I actually need this for a plugin I'm working on anyway, so I can't deny some selfish motives to checking out the PR myself and running the tests ;)
