### PR TITLE
paste: support replace mode

### LINKED ISSUE #11921: paste: support replace mode
- `nvim --version`: 
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- `vim -u DEFAULTS` (version: ) behaves differently? 
Unknown, vim not installed.
vi does not have this issue through.
- Operating system/version: 
Arch-linux
- Terminal name/version:
None, ssh only machine, no GUI
- `$TERM`:
screen-256color

### Steps to reproduce using `nvim -u NORC`

```
copy 'helloworld.' text to clipboard

nvim -u NORC

i -> paste from clipboard (ctrl+shift+insert) -> Esc

0 (to start of line) -> R (replace mode) -> paste same content from clipboard (ctrl+shift+insert) -> Esc

final result: 'helloworld.helloworld.'

```

### Actual behaviour

In replace mode clipboard content being pasted is inserted at cursor instead of replacing at cursor.

### Expected behaviour

Pasting clipboard contents in Replace mode replaces content at cursor.

### PR DESCRIPTION
**Pull request by Jesse-Bakker**
Fixes #11921 

Implementation matches vim behaviour

### CODE REVIEW

File: src/nvim/lua/vim.lua [hunk 1]
```diff
@@ -212,6 +212,19 @@ do
...
         -- XXX: Normal-mode: workaround bad cursor-placement after first chunk.
         vim.api.nvim_command('normal! a')
+      elseif phase < 2 and mode == 'R' then
+        local nchars = 0
+        for _, line in ipairs(lines) do
+            nchars = nchars + line:len()
+        end
+        local pos = vim.api.nvim_win_get_cursor(0)
+        local row, col = pos[1], pos[2]
+        local line = vim.api.nvim_buf_get_lines(0, row-1, row, true)[1]
```
Comment (bfredl) [inline src/nvim/lua/vim.lua]: This is the best we can do for now but we should use `nvim_buf_set_text` #11833 later when it is available

File: test/functional/api/vim_spec.lua [hunk 2]
```diff
@@ -571,6 +571,28 @@ describe('API', function()
...
       eq(false, nvim('get_option', 'paste'))
     end)
+    it('Replace-mode', function()
+      -- Within single line
+      nvim('put', {'line 1', 'line 2', 'line 3'}, "c", true, false)
+      command('normal 2l')
+      command('startreplace')
+      nvim('paste', 'new', true, -1)
+      expect([[
+      linew1
```
Comment (bfredl) [inline test/functional/api/vim_spec.lua]: This example is a bit degenerate as two out of three chars are the same, maybe use `normal l` instead of `2l`.

File: src/nvim/lua/vim.lua (hunk 1 above)
Comment (Jesse-Bakker) [reply src/nvim/lua/vim.lua]: I agree. I think there are lots of places where that API can simplify code, so some grepping and refactoring when it is ready would probably be a good idea.

File: test/functional/api/vim_spec.lua (hunk 2 above)
Comment (Jesse-Bakker) [reply test/functional/api/vim_spec.lua]: Agreed. Will update the test soon™

File: src/nvim/lua/vim.lua (hunk 1 above)
Comment (bfredl) [inline src/nvim/lua/vim.lua]: `line` and `lines` is maybe a bit confusing. could call this `bufline` maybe to indicate it is from the buffer.

File: src/nvim/lua/vim.lua [hunk 3]
```diff
@@ -212,6 +212,19 @@ do
         vim.api.nvim_put(lines, 'c', true, true)
         -- XXX: Normal-mode: workaround bad cursor-placement after first chunk.
         vim.api.nvim_command('normal! a')
+      elseif phase < 2 and mode == 'R' then
+        local nchars = 0
+        for _, line in ipairs(lines) do
+            nchars = nchars + line:len()
+        end
+        local pos = vim.api.nvim_win_get_cursor(0)
+        local row, col = pos[1], pos[2]
```
Comment (bfredl) [inline src/nvim/lua/vim.lua]: `local row, col = unpack(vim.api.nvim_win_get_cursor(0))`

**Comment by bfredl** [comment]
LGTM otherwise. Maybe @justinmk wants to take a look also?

**Comment by teto** [comment]
cool stuff. Thanks
