### PR TITLE
fix(highlight): winhl receive wrong argument

### LINKED ISSUE #24586: Invalid winhighlight accepted
### Problem

Invalid `winhighlight` accepted.

### Steps to reproduce

```
nvim --clean
```

```vim
:set winhighlight='Normal:Visual'
:set winhighlight?
```

(outputs `winhighlight='Normal:Visual'`)

### Expected behavior

Since the `winhighlight` is surrounded by quotes, I expected the value to not be accepted, as the following error is produced.
```
E5248: Invalid character in group name
```

Under the actual behavior, the invalid `winhighlight` is set. This eventually becomes a problem (e.g., when splitting the window).

For other options like `textwidth` and `spelloptions`, setting an invalid option results in an error, and the the invalid option is not set.

### Neovim version (nvim -v)

v0.9.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Kubuntu 23.04

### Terminal name/version

Konsole 22.12.3

### $TERM environment variable

xterm-256color

### Installation

appimage

### PR DESCRIPTION
**Pull request by glepnir**
Problem: winhl receive and set the wrong format value even if nvim through an error

Solution: validate winhl value.

Fix #24586

### CODE REVIEW

File: src/nvim/option.c [hunk 1]
```diff
@@ -1140,6 +1140,13 @@ static void do_set_option_string(int opt_idx, int opt_flags, char **argp, int ne
 
   // Get the new value for the option
   char *newval = stropt_get_newval(nextchar, opt_idx, argp, varp, origval, &op, flags);
+  // Validate winhl new value around by single quote
+  if (striequal(opt->shortname, "winhl")
```
Comment (bfredl) [inline src/nvim/option.c:1144]: I don't think this is needed. when `parse_winhl_opt` returns false, the old value is already restored

Comment (glepnir) [reply src/nvim/option.c:1144]: this can avoid screen redraw. keep highlight not changed.

Comment (zeertzjq) [reply src/nvim/option.c:1144]: I don't think this block makes any sense. It only check for one specific case of invalid value.

Comment (glepnir) [reply src/nvim/option.c:1144]: right. but how can i keep screen not redraw highlight ? even `parse_winhl_opt` return false the screen highlight changed.

Comment (glepnir) [reply src/nvim/option.c:1144]: oh I know why redraw.. if `errmsg != NULL` and value restored. Is it must still run to `check_redraw_for` ? can return directly ? some option need this maybe ?

Comment (glepnir) [reply src/nvim/option.c]: seems that this optimization is not needed. removed it then.
