### PR TITLE
fix: checkhealth warning even if init.lua exists

### LINKED ISSUE #25291: `Missing user config file: $XDG_CONFIG_HOME/nvim/init.lua` in health check even though it's right there
### Problem

1. When running `:healthcheck nvim`, section `Configuration` complains that the user config file is missing:

    ```checkhealth
    ==============================================================================
    nvim: require("nvim.health").check()
    
    Configuration ~
    - WARNING Missing user config file: $XDG_CONFIG_HOME/nvim/init.lua
      - ADVICE:
        - :help |init.vim|
    ```
    
    ...while it lies right there:
    ```
    $ file $XDG_CONFIG_HOME/nvim/init.lua
    /Users/futar/.config/nvim/init.lua: ASCII text
    ```

2. By contrast, the warning *always* goes away when an `init.vim` was present, **even with** `init.lua` showing up at the same time:
    ```
    $ ls $XDG_CONFIG_HOME/nvim
    init.lua init.vim
    ```
    
    ```checkhealth
    ==============================================================================
    nvim: require("nvim.health").check()
    
    Configuration ~
    - OK no issues found
    ```
    As mentioned in the manual (E5422): `...It can be either Vimscript ("init.vim") or Lua ("init.lua"), but not both.`, I don't think "no issues found" should be expected.

### Steps to reproduce

1. Back up `$XDG_CONFIG_HOME/nvim` to somewhere else
2. `touch $XDG_CONFIG_HOME/nvim/init.lua` (shouldn't matter if empty or not)
3. `nvim --cmd 'checkhealth nvim'`
---
4. `touch $XDG_CONFIG_HOME/nvim/init.vim`
5. `nvim --cmd 'checkhealth nvim'`

### Expected behavior

1. No warnings should be raised 
2. A warning should be raised explaining referencing E5422

### Neovim version (nvim -v)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.2/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 13.0.1

### Terminal name/version

iTerm2 3.4.20

### $TERM environment variable

xterm-256color

### Installation

homebrew

### PR DESCRIPTION
**Pull request by tjmblake**
First PR - hoping to fix https://github.com/neovim/neovim/issues/25291

### CODE REVIEW

File: runtime/lua/nvim/health.lua [hunk 1]
```diff
@@ -54,9 +54,16 @@ local function check_config()
   health.start('Configuration')
   local ok = true
 
-  local vimrc = (
-    empty(vim.env.MYVIMRC) and vim.fn.stdpath('config') .. '/init.vim' or vim.env.MYVIMRC
-  )
+  local init_lua_path = vim.fn.stdpath('config') .. '/init.lua'
+  local init_vim_path = vim.fn.stdpath('config') .. '/init.vim'
+  if filereadable(init_lua_path) and filereadable(init_vim_path) then
+    health.warn('You can have either Vimscript ("init.vim") or Lua ("init.lua"), but not both.')
```
Comment (justinmk) [inline runtime/lua/nvim/health.lua:60]: Are you sure this is needed? There's already a builtin check which shows at startup: https://github.com/neovim/neovim/blob/5ea5812714bcbeb6a5438c80d410984ad4fbb922/src/nvim/main.c#L2006

File: runtime/lua/nvim/health.lua [hunk 2]
```diff
@@ -54,9 +54,16 @@ local function check_config()
...
+  end
+
+  local init_path = filereadable(init_lua_path) and init_lua_path or init_vim_path
+
+  local vimrc = (empty(vim.env.MYVIMRC) and init_path or vim.env.MYVIMRC)
```
Comment (justinmk) [inline runtime/lua/nvim/health.lua:65]: should probably default to init.lua rather than init.vim, for messaging.
```suggestion
  local vimrc = (empty(vim.env.MYVIMRC) and init_lua_path or vim.env.MYVIMRC)
```

File: runtime/lua/nvim/health.lua (hunk 1 above)
Comment (tjmblake) [reply runtime/lua/nvim/health.lua]: It is not needed, have removed

File: runtime/lua/nvim/health.lua [hunk 3]
```diff
@@ -54,15 +54,16 @@ local function check_config()
   health.start('Configuration')
   local ok = true
 
-  local vimrc = (
-    empty(vim.env.MYVIMRC) and vim.fn.stdpath('config') .. '/init.vim' or vim.env.MYVIMRC
-  )
+  local init_lua_path = vim.fn.stdpath('config') .. '/init.lua'
+
+  local vimrc = (empty(vim.env.MYVIMRC) and init_lua_path or vim.env.MYVIMRC)
```
Comment (MariaSolOs) [inline runtime/lua/nvim/health.lua:59]: Now that this is in a single line I would remove the outer parentheses.

File: runtime/lua/nvim/health.lua [hunk 4]
```diff
@@ -54,15 +54,16 @@ local function check_config()
...
+
+  local vimrc = empty(vim.env.MYVIMRC) and init_lua_path or vim.env.MYVIMRC
+
   if not filereadable(vimrc) then
     ok = false
     local has_vim = filereadable(vim.fn.expand('~/.vimrc'))
     health.warn(
       (-1 == vim.fn.getfsize(vimrc) and 'Missing' or 'Unreadable') .. ' user config file: ' .. vimrc,
-      { has_vim and ':help nvim-from-vim' or ':help init.vim' }
+      { has_vim and ':help nvim-from-vim' or ':help init.lua' }
```
Comment (justinmk) [inline runtime/lua/nvim/health.lua:66]:
```suggestion
      { has_vim and ':help nvim-from-vim' or ':help config' }
```

**Comment by justinmk** [comment]
Previous commit flipped the problem of #25291 . I pushed a fix

**Comment by justinmk** [comment]
Lots of tui_spec failures, can't see how that is related.

```
ERROR    test/functional/terminal/tui_spec.lua @ 75: TUI rapid resize #7572 #7628
test/functional/ui/screen.lua:178: EOF was received from Nvim. Likely the Nvim process crashed.
```

**Comment by tjmblake** [comment]
> Lots of tui_spec failures, can't see how that is related.
> 
> ```
> ERROR    test/functional/terminal/tui_spec.lua @ 75: TUI rapid resize #7572 #7628
> test/functional/ui/screen.lua:178: EOF was received from Nvim. Likely the Nvim process crashed.
> ```
> 
> I see that failure in other PRs, so not related.

Thank you for helping. 
Not sure if I'll be useful, but I'll have a look at those unrelated tests.

**Comment by GaetanLepage** [comment]
Thank you for fixing this !
The wrong behavior is still present in 0.9.5.
Are there any plan to backport this change to the stable release ?

**Comment by dundargoc** [comment]
Only because you asked so nicely: https://github.com/neovim/neovim/pull/26871
