### PR TITLE
fix(gen_vimvim): correctly add aliases to vimAutoEvent

### LINKED ISSUE #23424: Aliased events are missed in generated vim syntax
### Problem

The aliased events, i.e.

- `BufCreate`
- `BufRead`
- `BufWrite`
- `FileEncoding`

are missed in `$VIM/runtime/syntax/vim/generated.vim`.

https://github.com/neovim/neovim/blob/26cc946226d96bf6b474d850b961e1060346c96f/src/nvim/auevents.lua#L130-L147

### Steps to reproduce

```console
$ grep -E -o '\b(BufCreate|BufRead|BufWrite|FileEncoding)\b' $VIM/runtime/syntax/vim/generated.vim
```

The 24th line of the file is:

```vim
syn keyword vimAutoEvent contained  InsertLeavePre MenuPopup ModeChanged OptionSet QuickFixCmdPost QuickFixCmdPre QuitPre RemoteReply SearchWrapped SessionLoadPost ShellCmdPost ShellFilterPost SourceCmd SourcePost SourcePre SpellFileMissing StdinReadPost StdinReadPre SwapExists Syntax TabClosed TabEnter TabLeave TabNew TermChanged TermEnter TermLeave TermResponse TextChanged TextChangedI TextChangedP TextChangedT TextYankPost User VimEnter VimLeave VimLeavePre VimResized VimResume VimSuspend WinClosed WinEnter WinLeave WinNew WinResized WinScrolled 1 2 3 4
```

Here, indices `1 2 3 4` are wrongly added; consequently, e.g. `BufRead` is not highlighted:

```console
$ echo 'au BufRead *.vim setf vim' | nvim --clean -c 'setf vim' -
```

### Expected behavior

The aliased events are added in the generated vim syntax file.

The issue is fixed by a patch like below:

```diff
--- a/src/nvim/generators/gen_vimvim.lua
+++ b/src/nvim/generators/gen_vimvim.lua
@@ -117,7 +117,7 @@ for au, _ in pairs(auevents.aliases) do
     if lld.line_length > 850 then
       w('\n' .. vimau_start)
     end
-    w(' ' .. au)
+    w(' ' .. _[1])
   end
 end
 
```

### Neovim version (nvim -v)

v0.10.0-dev-241+g26cc94622

### Vim (not Nvim) behaves the same?

No, 9.0.1420

### Operating system/version

EndeavourOS

### Terminal name/version

GNOME Terminal 3.46.8 using VTE 0.72.1 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by e-kwsm**
close #23424

Feel free to rename the variable.

### CODE REVIEW

File: src/nvim/generators/gen_vimvim.lua [hunk 1]
```diff
@@ -112,12 +112,13 @@ for _, au in ipairs(auevents.events) do
     w(' ' .. au)
   end
 end
-for au, _ in pairs(auevents.aliases) do
+for au, alias in pairs(auevents.aliases) do
   if not auevents.nvim_specific[au] then
```
Comment (zeertzjq) [inline src/nvim/generators/gen_vimvim.lua:116]: I think this condition should also be removed as it doesn't do anything, and the `au` variable above can be changed to `_`.

Comment (e-kwsm) [reply src/nvim/generators/gen_vimvim.lua]: done

**Review by zeertzjq — APPROVED** [review]
