### PR TITLE
fix(Windows): restore console title at exit

### LINKED ISSUE #21404: Title not restored after exiting from nvim opened with stdin
### Neovim version (nvim -v)

v0.9.0-dev-506+g090048bec9f8

### Vim (not Nvim) behaves the same?

no, vim 9.0.815

### Operating system/version

Windows 11 22H2

### Terminal name/version

Windows Terminal, Conhost

### $TERM environment variable

nil, xterm-256color

### Installation

Built from source

### How to reproduce the issue

```
$ set TERM='xterm-256color' # without setting $TERM, ':h title' doesn't take effect in either cmd or powershell
$ echo foo | nvim --clean --cmd 'set title' -
:q
```

### Expected behavior

The terminal title should be restored to what it was before opening neovim.

### Actual behavior

The terminal title remains what it was set to by neovim.

### PR DESCRIPTION
**Pull request by 3N4N**
Fixes #21404

### CODE REVIEW

**Comment by 3N4N** [comment]
@justinmk This is a fairly tiny change, can be lumped together with the code added in #20607.  That is to say, I'm thinking this one should be easy to greenlight.

File: src/nvim/os/os_win_console.c [hunk 1]
```diff
@@ -10,6 +10,7 @@
 # include "os/os_win_console.c.generated.h"
 #endif
 
+char origTitle[256] = { 0 };
```
Comment (theHamsta) [inline src/nvim/os/os_win_console.c:13]: `static`?
