### PR TITLE
vim-patch:8.2.1947: crash when using "zj" without folds

### LINKED ISSUE #7245: Using zj after foldmethod is changed may crash Vim
**Describe the bug**
Using `zj` to jump to the next fold below the cursor can cause a read access violation after changing `foldmethod`. (`zk` does not seem to be affected; unsure about other commands)

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Attempt to create a fold (with `:fold`, `zfG`, etc.)
3. Execute `:set foldmethod=expr`
4. Use `zj` in normal mode
5. Vim crashes

Or run Vim using:
`vim --clean -c "fold | setl fdm=expr | norm zj"`

Do note that for step 2 the buffer can be empty; a fold doesn't actually have to be successfully created, just trying to create one is enough to trigger the crash.

**Expected behavior**
Vim shouldn't crash and `zj` should do nothing.

**Environment:**
- Vim version: 8.2.1941 huge
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov  1 2020 23:02:04)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1941
Compiled by appveyor@APPVYR-WIN
Huge version with GUI.  Features included (+) or not (-):
+acl                +clientserver       +diff               +float              +langmap            +multi_byte_ime/dyn +printer            +spell              +textobjects        +viminfo
+arabic             +clipboard          +digraphs           +folding            +libcall            +multi_lang         +profile            +startuptime        +textprop           +vreplace
+autocmd            +cmdline_compl      +directx            -footer             +linebreak          +mzscheme/dyn       +python/dyn         +statusline         -tgetent            -vtp
+autochdir          +cmdline_hist       -dnd                +gettext/dyn        +lispindent         +netbeans_intg      +python3/dyn        -sun_workshop       +timers             +wildignore
+autoservername     +cmdline_info       -ebcdic             -hangul_input       +listcmds           +num64              +quickfix           +syntax             +title              +wildmenu
+balloon_eval       +comments           +emacs_tags         +iconv/dyn          +localmap           +ole                +reltime            +tag_binary         +toolbar            +windows
-balloon_eval_term  +conceal            +eval               +insert_expand      +lua/dyn            +packages           +rightleft          -tag_old_static     +user_commands      +writebackup
+browse             +cryptv             +ex_extra           +ipv6               +menu               +path_extra         +ruby/dyn           -tag_any_white      +vartabs            -xfontset
++builtin_terms     +cscope             +extra_search       +job                +mksession          +perl/dyn           +scrollbind         +tcl/dyn            +vertsplit          -xim
+byte_offset        +cursorbind         -farsi              +jumplist           +modify_fname       +persistent_undo    +signs              -termguicolors      +virtualedit        +xpm_w32
+channel            +cursorshape        +file_in_path       +keymap             +mouse              +popupwin           +smartindent        +terminal           +visual             -xterm_save
+cindent            +dialog_con_gui     +find_in_path       +lambda             +mouseshape         -postscript         +sound              -termresponse       +visualextra        
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_IPV6   -DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python38.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DRUBY_VERSION=24 -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib netapi32.lib  /machine:AMD64  libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python38.lib   "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.lib Ws2_32.lib xpm\x64\lib-vc14\libXpm.lib /PDB:gvim.pdb -debug
```
 - OS: Windows 10 Build 19041
 - Terminal: GUI (and presumably happens with all terminals)

**Additional context**
[The access violation occurs in `foldMoveTo()` in `fold.c`, line 954](https://github.com/vim/vim/blob/36113e46b4a7e8c33aa1ed1c9cfa6591c952183d/src/fold.c#L954).

From what I can see, clearing folds usually results in `curwin->w_folds->ga_data` being set to `NULL`.

However, executing `set foldmethod=expr` leaves `curwin->w_folds->ga_data` with a non-`NULL` value, which seems to eventually cause the read access violation in `foldMoveTo()` (although `curwin->w_folds->ga_len` is 0 in both cases as expected).

### PR DESCRIPTION
**Pull request by seandewar**
Problem:    Crash when using "zj" without folds. (Sean Dewar)
Solution:   Check for at least one fold. (closes vim/vim#7245)
https://github.com/vim/vim/commit/c136a3528b7ebb825c3863d701af44f023381181

### CODE REVIEW

File: src/nvim/fold.c [hunk 1]
```diff
@@ -886,8 +886,12 @@ int foldMoveTo(
   for (long n = 0; n < count; n++) {
     // Find nested folds.  Stop when a fold is closed.  The deepest fold
     // that moves the cursor is used.
-    linenr_T lnum_off = 0;
     garray_T *gap = &curwin->w_folds;
+    if (gap->ga_len == 0) {
+      break;
+    }
+
+    linenr_T lnum_off = 0;
```
Comment (janlazo) [inline src/nvim/fold.c:894]: Did you have to move it?

File: src/nvim/fold.c [hunk 2]
```diff
@@ -886,8 +886,12 @@ int foldMoveTo(
   for (long n = 0; n < count; n++) {
     // Find nested folds.  Stop when a fold is closed.  The deepest fold
     // that moves the cursor is used.
-    linenr_T lnum_off = 0;
     garray_T *gap = &curwin->w_folds;
+    if (gap->ga_len == 0) {
+      break;
+    }
+
```
Comment (janlazo) [inline src/nvim/fold.c:893]: The patch did not add a newline.

**Review by janlazo — APPROVED** [review]
It's fine except for the extra changes.

File: src/nvim/testdir/test_fold.vim [hunk 3]
```diff
@@ -795,3 +795,12 @@ func Test_fold_delete_first_line()
...
 endfunc
+
+" this was crashing
+func Test_move_no_folds()
+  new
+  fold
+  setlocal fdm=expr
+  normal zj
+  bwipe!
+endfunc
```
Comment (janlazo) [inline src/nvim/testdir/test_fold.vim:806]: Add the modeline even though it came from an earlier patch.

**Review by janlazo — APPROVED** [review]
Waiting for CI to double-check before merging.
