### PR TITLE
[RDY] win: Fix reading content from stdin

### LINKED ISSUE #6890: Windows: nvim exits when called with piped stdin
- `nvim --version`: 0.2.1-343-g58b51c60
- Vim (version: ) behaves differently? 8.0/yes
- Operating system/version: Windows
- Terminal name/version: Conemu/cmd.exe

### Actual behaviour

```
echo fudge | nvim -
Vim: finished.?les...?, exiting...??Vi
~
~
~
(...)
```

- The `?` are actually a question mark inside a square (not  a diamond)
- It prints the full screen before terminating. The behaviour is slightly different in the windows terminal vs connemu. In the windows terminal it seems to wait for input before exiting.

### Expected behaviour

Should open a buffer with the piped contents, like Vim.

### Steps to reproduce using `nvim -u NORC`

```
echo fudge | nvim -u NORC -
```

### PR DESCRIPTION
**Pull request by b-r-o-c-k**
Fixes #6890

### CODE REVIEW

**Comment by justinmk** [comment]
Wonderful, this should allow us to nudge https://github.com/neovim/neovim/pull/6299

**Comment by janlazo** [comment]
@b-r-o-c-k I needed this https://github.com/neovim/neovim/pull/8160/commits/bc43d2559f33aa6334d70834b389f0bc59dadcbf for my PR since your workaround for lastexitcode didn't work for MINGW (or something else is happening). Does it need stderr redirected to stdout?

File: src/nvim/fileio.c [hunk 1]
```diff
@@ -1737,9 +1737,17 @@ readfile (
   xfree(buffer);
 
   if (read_stdin) {
-    /* Use stderr for stdin, makes shell commands work. */
     close(0);
+#ifndef WIN32
+    // On Unix, use stderr for stdin, makes shell commands work.
     ignored = dup(2);
```
Comment (justinmk) [inline src/nvim/fileio.c]: In Vim this is guarded by `HAVE_DUP`, which is defined for Windows (`src/os_dos.h` in Vim's source).

https://github.com/vim/vim/blob/e7499ddc33508d3d341e96f84a0e7b95b2d6927c/src/fileio.c#L2397-L2398

I wonder why it doesn't work in Nvim.

File: src/nvim/tui/input.c [hunk 2]
```diff
@@ -47,7 +47,13 @@ void term_input_init(TermInput *input, Loop *loop)
...
   // setup input handle
 #ifdef WIN32
-  uv_tty_init(&loop->uv, &input->tty_in, 0, 1);
+  // On Windows, always read from the console input buffer instead of stdin.
+  // This avoids problems when stdin was previously used for other input.
+  const HANDLE conin_handle = CreateFile("CONIN$", GENERIC_READ | GENERIC_WRITE,
+                            FILE_SHARE_READ, (LPSECURITY_ATTRIBUTES)NULL,
+                            OPEN_EXISTING, 0, (HANDLE)NULL);
+  const int conin_fd = _open_osfhandle(conin_handle, _O_RDONLY);
+  uv_tty_init(loop, &input->tty_in, conin_fd, true);
```
Comment (b-r-o-c-k) [inline src/nvim/tui/input.c]: I think it's a better idea to move this patch to here because it's going to be less redundant. The patch won't need to be duplicated in #6299 if it's moved to here.

Comment (justinmk) [reply src/nvim/tui/input.c]: @b-r-o-c-k seems reasonable, but then it won't work for `--headless` (TUI is not started then). So some duplication or refactoring might still be needed.

**Comment by justinmk** [comment]
can you include your explanation from https://github.com/neovim/neovim/pull/8267#discussion_r181260964 in the commit message?

File: src/nvim/tui/input.c (hunk 2 above)
Comment (b-r-o-c-k) [reply src/nvim/tui/input.c]: You're right, this doesn't work for headless mode and I'm not sure if there's a good way to avoid the duplication so I'll just change it back to the way it was.
