### PR TITLE
fix(treesitter): use proper query syntax for inspector

### LINKED ISSUE #25958: InspectTree: wrong file type or output?
### Problem

When I execute `:InspectTree` on a buffer I get a new buffer with a text representation of the document tree. The file type is set to `query`, but the text is not an actual Tree-sitter query syntax. If the file type was actually correct we would get integration with file-type specific settings and plugins.

### Steps to reproduce

Let's take the following piece of Lua code:

```lua
if not success then return end
```

If I execute `:InspectTree` I get the following output:

```
(if_statement) ; [1:1 - 31:0]
 condition: (unary_expression) ; [1:4 - 15:0]
  operand: (identifier) ; [1:8 - 15:0]
 consequence: (block) ; [1:21 - 27:0]
  (return_statement) ; [1:21 - 27:0]
```

### Expected behavior

I would expect either the file type to be set to something else, or this output:

```
(if_statement ; [3:1 - 31:2]
 "if" ; [3:1 - 2]
 condition: (unary_expression ; [3:4 - 15:2]
  "not" ; [3:4 - 7:2]
  operand: (identifier)) ; [3:8 - 15:2]
 "then" ; [3:16 - 20:2]
 consequence: (block ; [3:21 - 27:2]
  (return_statement ; [3:21 - 27:2]
   "return")) ; [3:21 - 27:2]
 "end") ; [3:28 - 31:2]
```

### Neovim version (nvim -v)

0.10, 0.9

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

GNU/Linux

### Terminal name/version

alacritty 0.12.3

### $TERM environment variable

alacritty

### Installation

XBPS (Void package manager)

### PR DESCRIPTION
**Pull request by gpanders**
Use actual Tree-sitter query syntax for the inspector window. This makes parsing with the query parser work correctly and more reliably.

In particular this means that nested nodes are grouped within parentheses (like all lisps).

### CODE REVIEW

**Comment by gpanders** [comment]
Another nice feature of this is that it enables jumping to the end of a node using the standard `%` key to jump between open and closing parens.

**Comment by clason** [comment]
Hmm, one significant(?) advantage is that you can now copy&paste from the Treeview to the Query Editor.

**Comment by Danielkonge** [comment]
> Sample to see what it looks like:

How does it look if you show the anonymous nodes?

**Comment by gpanders** [comment]
Hmm it's not quite 100% correct yet -- moving to draft.

File: runtime/lua/vim/treesitter/dev.lua [hunk 1]
```diff
@@ -76,6 +76,9 @@ local function traverse(node, depth, lang, injections, tree)
     })
 
     traverse(child, depth + 1, lang, injections, tree)
+
+    -- Add closing parens to final child
+    tree[#tree].text = string.format('%s)', tree[#tree].text)
```
Comment (Danielkonge) [inline runtime/lua/vim/treesitter/dev.lua]: If you want to simplify this for the anonymous nodes, you could put the end parenthesis on a new line. If you don't like that kind of formatting, I think it makes sense to put it like this when there is no anonymous nodes at the end, and put it after the last anonymous node otherwise.

**Comment by gpanders** [comment]
In my opinion both are equally readable (or unreadable, if you have a Lisp allergy). So the benefits of this change are:

1. Being able to more easily jump between start and end node positions with `%`
2. Being able to copy text into the query editor
3. Using the `query` filetype and `query` TS parser

**Comment by gpanders** [comment]
> I think this will only be noticeable with deep nesting -- where this probably _does_ make a difference; with 20 indents or so, doubling adds up (hah!)

We can leave it at 1 space indents if people prefer that. I don't feel strongly about it.

**Comment by Danielkonge** [comment]
> ```lisp
> local_declaration: (variable_declaration ; [1:1 - 24]
>   "local" ; [1:1 - 5]
>   (assignment_statement ; [1:7 - 24]
>     (variable_list ; [1:7 - 7]
>       name: (identifier)) ; [1:7 - 7]
>     "=" ; [1:9 - 9]
>     (expression_list ; [1:11 - 24]
>       value: (table_constructor ; [1:11 - 24]
>         "{" ; [1:11 - 11]
>         (field ; [1:12 - 16]
>           name: (identifier) ; [1:12 - 12]
>           "=" ; [1:14 - 14]
>           value: (number)) ; [1:16 - 16]
>         "," ; [1:17 - 17]
>         (field ; [1:19 - 23]
>           name: (identifier) ; [1:19 - 19]
>           "=" ; [1:21 - 21]
>           value: (number)) ; [1:23 - 23]
>         "}")))) ; [1:24 - 24]
> (function_call ; [3:1 - 12]
>   name: (identifier) ; [3:1 - 5]
>   arguments: (arguments ; [3:6 - 12]
>     "(" ; [3:6 - 6]
>     (bracket_index_expression ; [3:7 - 11]
>       table: (identifier) ; [3:7 - 7]
>       "[" ; [3:8 - 8]
>       field: (unary_expression ; [3:9 - 10]
>         "#" ; [3:9 - 9]
>         operand: (identifier)) ; [3:10 - 10]
>       "]") ; [3:11 - 11]
>     ")")) ; [3:12 - 12]
> ```

That looks good to me. As a less important side question: Is there something we could set to make it easy to identify whether the `query` file I am highlighting is `InspectTree` or a normal `query` file? Or is there already something I could easily catch that I missed?

**Comment by clason** [comment]
> Or is there already something I could easily catch that I missed?

Are the line annotations not obvious enough?

**Comment by gpanders** [comment]
>As a less important side question: Is there something we could set to make it easy to identify whether the query file I am highlighting is InspectTree or a normal query file?

Do you mean programmatically? The inspector sets the `b:dev_base` buffer variable, though that's not documented or part of the API so use with caution.

**Comment by Danielkonge** [comment]
> Are the line annotations not obvious enough?

I am not sure if I understand exactly what you mean?

I meant something along the lines of a buffer option. Currently I assume I am looking at the `InspectTree` if `vim.bo.buftype == 'nofile'` and a normal `query` file otherwise. But this doesn't work perfectly (e.g. the query editor in the "playground" is also 'nofile'). I could specify more of the buffer options for the `InspectTree`, but I was wondering if there was an easier way that I am missing? And if not, if there was an easy thing to add to simplify this?

Note: This is not very important, and I don't think it needs to be part of this pull request.

**Comment by clason** [comment]
What is the actual problem here? Maybe better to describe this in a followup issue.

**Comment by Danielkonge** [comment]
> What is the actual problem here? Maybe better to describe this in a followup issue.

I think @gpanders comment on using `vim.b.dev_base` solves my problem, so we don't need to change anything. At most we could add a comment to the docs that you can use `vim.b.dev_base` to detect whether you are in `InspectTree`.

**Comment by clason** [comment]
But, again, why would you want to do that?

**Comment by Danielkonge** [comment]
> But, again, why would you want to do that?

I don't think this is a general issue, so it is not important at all. But for a large tree like you often see in `InspectTree` I might want to color more stuff to make it clearer what indentation level I am on, but I don't usually prefer it that way when writing queries.

E.g. (before the update) `InspectTree` like this:

Screenshot 2023-11-28 at 18 44 47


and queries like this:

Screenshot 2023-11-28 at 18 45 34

instead of:

Screenshot 2023-11-28 at 18 46 08

**Comment by clason** [comment]
> > I think this will only be noticeable with deep nesting -- where this probably _does_ make a difference; with 20 indents or so, doubling adds up (hah!)
> 
> We can leave it at 1 space indents if people prefer that. I don't feel strongly about it.

I looked at a few trees for Neovim source files, and 2 space should still be fine, so I don't mind switching.

Long-term, upstream (tree-sitter) is working to include a query formatter which hopefully is opinionated enough that we can just follow whatever they are doing. So whatever we do here is not set in stone.

**Review by lewis6991 — APPROVED** [review]

**Comment by clason** [comment]
I noticed an issue with this: If you are moving through the source window, the highlight in the treeview is off:

Screenshot 2023-11-29 at 16 43 05

**Comment by gpanders** [comment]
> I noticed an issue with this: If you are moving through the source window, the highlight in the treeview is off:

https://github.com/neovim/neovim/pull/26302

**Comment by Danielkonge** [comment]
I noticed another issue with parentheses. If a named note ends with an anonymous node, then the end parenthesis is put there, so if we are hiding the anonymous nodes, then the end parenthesis is not included in the tree. 

E.g. this is missing two ')':
Screenshot 2023-11-29 at 17 10 24

If I show the anonymous nodes, then it is fine:
Screenshot 2023-11-29 at 17 11 05

What is causing the problem here is the parentheses at the end of line 6 and 13 in the second picture. They are missing in the first picture.

**Comment by gpanders** [comment]
Yea, doing this correctly will be a bit trickier. We need to separate how the nodes are displayed (in `:draw()`) from how the nodes are discovered (in `traverse()`). Right now the two are coupled. When we are traversing the tree we find all nodes, including anonymous nodes, regardless of whether or not those nodes will be displayed. So we can't manage open/closing parens in `traverse()`, we would need to do it in `:draw()` instead.

**Comment by gpanders** [comment]
https://github.com/neovim/neovim/pull/26304
