### PR TITLE
fix(tabpage): check if ROWS_AVAIL changed for resize

### LINKED ISSUE #19591: `laststatus=3` not working when specific tab commands are used
### Neovim version (nvim -v)

v0.7.2

### Vim (not Nvim) behaves the same?

not applicable, 'laststatus=3' only in neovim

### Operating system/version

Arch Linux

### Terminal name/version

konsole

### $TERM environment variable

xterm-256color

### Installation

Arch community repo

### How to reproduce the issue
Run these commands:
```
tabnew
tabprev
set laststatus=3
tabnext
echo 'this wont be printed'
```

### Expected behavior

Statusline and command-line area should be displayed normally

### Actual behavior

- when terminal window is focused, the statusline disappears
- command-line does not seem to be updating, e.g. `:echo 'hi'` doesn't do anything
- the terminal buffer seems to have one more line than it should when it is set to full height

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #19591

### CODE REVIEW

File: test/functional/editor/tabpage_spec.lua [hunk 1]
```diff
@@ -53,6 +54,46 @@ describe('tabpage', function()
     neq(999, eval('g:win_closed'))
   end)
 
+  it('no glitch when switching tabpage after setting laststatus=3 #19591', function()
```
Comment (justinmk) [inline test/functional/editor/tabpage_spec.lua:57]: "no glitch", "correct", "works" all are redundant in tests.

```suggestion
  it('switching tabpage after setting laststatus=3 #19591', function()
```

**Review by justinmk — APPROVED** [review]
