### PR TITLE
eval: save_tv_as_string: Correctly handle an empty string

### LINKED ISSUE #6554: system() doesn't work when {input} is ''
- `nvim --version`: ``NVIM v0.2.0-1413-g3a606ee58``
- Vim (version: ) behaves differently? **yes**, ``VIM - Vi IMproved 8.0``
- Operating system/version: ``Linux 4.10.5-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux``
- Terminal name/version: ``rxvt-unicode``
- `$TERM`: ``rxvt-unicode-256color``

### Actual behaviour

Returns no output.

### Expected behaviour

Should return expected output:
```
test

```

### Steps to reproduce using `nvim -u NORC`

Run as EX command:

``:echo system('echo test', '')``

### PR DESCRIPTION
**Pull request by jamessan**
When tv_get_string_chk returns a non-NULL value, we have a valid string.
Propagating an error state (*len = -1, NULL return) for an empty string
is invalid.

Closes #6554

### CODE REVIEW

**Comment by jamessan** [comment]
@ZyX-I Any idea why the test is sometimes failing in Travis like this:

```
[ RUN      ] system() passing input works with an empty string: ERR
./test/functional/helpers.lua:93: Failed to evaluate expression
stack traceback:
	./test/functional/helpers.lua:93: in function 'eval'
	...build/neovim/neovim/test/functional/eval/system_spec.lua:258: in function <...build/neovim/neovim/test/functional/eval/system_spec.lua:257>
```

I've been running `system_spec.lua` in a loop on my VM here and haven't had any issues so far.  In my previous version of the PR, I tested cherry-picking the commit onto code before the big typval refactor and it seemed to work fine there.

**Comment by jamessan** [comment]
Hmm, after clearing Travis' cache, everything ran fine except for the flaky timers tests.

**Comment by justinmk** [comment]
Let's re-run it a few times...

**Comment by jamessan** [comment]
Ok, it happened again in the coverage build.

There was also this stderr output reported at the end of the run:

```
-- Output to stderr:
2017/04/28 16:34:19 ERROR 10786/open_log_file:127: Couldn't open USR_LOG_FILE, logging to stderr! This may be caused by attempting to LOG() before initialization functions are called (e.g. init_homedir()).
2017/04/28 16:34:19 ERROR 10786/call_set_error:723: RPC: ch 1 was closed by the client
2017/04/28 16:34:41 ERROR 11266/open_log_file:127: Couldn't open USR_LOG_FILE, logging to stderr! This may be caused by attempting to LOG() before initialization functions are called (e.g. init_homedir()).
2017/04/28 16:34:41 ERROR 11266/call_set_error:723: RPC: ch 1 was closed by the client
```

File: src/nvim/eval.c [hunk 1]
```diff
@@ -17409,7 +17409,8 @@ static char *save_tv_as_string(typval_T *tv, ptrdiff_t *const len, bool endnl)
   // print an error.
   if (tv->v_type != VAR_LIST) {
     const char *ret = tv_get_string_chk(tv);
-    if (ret && (*len = strlen(ret))) {
+    if (ret) {
+      *len = strlen(ret);
```
Comment (justinmk) [inline src/nvim/eval.c]: Might be worth temporarily reverting this change to see if the problem still occurs with the new test. To avoid having to look at a bunch of failed builds, change the expect result to what happens on master.

```lua
eq("", eval('system("echo test", "")'))
```

File: test/functional/eval/system_spec.lua [hunk 2]
```diff
@@ -255,7 +255,7 @@ describe('system()', function()
       eq(2, eval("1+1"))  -- Still alive?
```
Comment (justinmk) [inline test/functional/eval/system_spec.lua]: off topic, just noticed the test on lin 250 should be:

    feed_command('call system("cat - &", "input")')

File: src/nvim/eval.c (hunk 1 above)
Comment (jamessan) [inline src/nvim/eval.c]: No lua tracebacks yet with the code reverted...

**Comment by jamessan** [comment]
I've run the Travis builds a few times now and none of them have failed.  Looking better now.

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
Hmm, saw this in https://github.com/neovim/neovim/pull/7924 :

```
system() passing input works with an empty string: [1m[31mERR[0m[0m
test/functional/helpers.lua:93: Failed to evaluate expression

stack traceback:
	test/functional/helpers.lua:93: in function 'eval'
	...build/neovim/neovim/test/functional/eval/system_spec.lua:262: in function <...build/neovim/neovim/test/functional/eval/system_spec.lua:261>
```

**Comment by justinmk** [comment]
I can repro it locally, will investigate.
