### PR TITLE
[RDY] Allow nil in list when decoding lsp responses

### LINKED ISSUE #13829: LSP completion: "Error executing vim.schedule lua callback: error converting argument 2", probably due to `vim.NIL` conversion logic
- `nvim --version`:
```
NVIM v0.5.0-dev+1050-g78f0f00cd
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/akear/.cache/yay/neovim-git/src/build/config -I/home/akear/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/akear/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/akear/.cache/yay/neovim-git/src/build/include
Compiled by akear@nocsik-fixe

Features: +acl +iconv +tui
```
- `vim -u DEFAULTS` (version: ) behaves differently? 
- Operating system/version: Archlinux, kernel 5.10.9-zen1-1-zen
- Terminal name/version: Kitty 0.19.3
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

Not really possible with `-u NORC`, it requires `nvim-lua/completion-nvim` and `neovim/nvim-lspconfig` plugins.

LSP configuration:
```lua
local on_attach = function(_, _)
  require'completion'.on_attach()
end

nvim_lsp.purescriptls.setup{
  on_attach=on_attach;
}
```

It also requires setting up a Purescript server and opening a `.purs` file:
```bash
npm install -g spago purescript purescript-language-server
# In a new folder
spago init
nvim src/Main.purs
```

Then go to the line that says `  log "🍝"`, delete the line, and start typing `log` again. The bug should manifest itself.

### Actual behaviour

We get the following error at each keypress when trying to complete the current word, and no completion menu shows up:
```
E5100: Cannot convert given lua table: table should either have a sequence of positive integer keys or contain only string keys
Error executing vim.schedule lua callback: error converting argument 2
```

### Expected behaviour

Completion should behave normally.

### Additional informations

I've tried to debug it and traced it back to the following response from the server:

<details>
<summary>Log from log.lsp</summary>

`[ DEBUG ] 2021-01-26T18:26:55+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]  "decoded"       {  id = 4,  jsonrpc = "2.0",  result = {    isIncomplete = false,    items = { {        additionalTextEdits = vim.NIL,        command = {          arguments = { "log", "Effect.Class.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          command = "purescript.addCompletionImport",          title = "Add completion import"        },        detail = "∀ m. MonadEffect m ⇒ String → m Unit",        documentation = {          kind = "markdown",          value = "\n*From: Effect.Class.Console*"        },        filterText = vim.NIL,        insertText = "log",        kind = 3,        label = "log",        sortText = "Z.log",        textEdit = {          newText = "log",          range = {            end = {              character = 4,              line = 9            },            start = {              character = 2,              line = 9            }          }        }      }, {        additionalTextEdits = vim.NIL,        command = {          arguments = { "logShow", "Effect.Class.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          command = "purescript.addCompletionImport",          title = "Add completion import"        },        detail = "∀ m a. MonadEffect m ⇒ Show a ⇒ a → m Unit",        documentation = {          kind = "markdown",          value = "\n*From: Effect.Class.Console*"        },        filterText = vim.NIL,        insertText = "logShow",        kind = 3,        label = "logShow",        sortText = "Z.logShow",        textEdit = {          newText = "logShow",          range = {            end = {              character = 4,              line = 9            },            start = {              character = 2,              line = 9            }          }        }      }, {        additionalTextEdits = vim.NIL,        command = {          arguments = { "log", "Effect.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          command = "purescript.addCompletionImport",          title = "Add completion import"        },        detail = "String → Effect Unit",        documentation = {          kind = "markdown",          value = "\n*From: Effect.Console*"        },        filterText = vim.NIL,        insertText = "log",        kind = 3,        label = "log",        sortText = "Z.log",        textEdit = {          newText = "log",          range = {            end = {              character = 4,              line = 9            },            start = {              character = 2,              line = 9            }          }        }      }, {        additionalTextEdits = vim.NIL,        command = {          arguments = { "logShow", "Effect.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          command = "purescript.addCompletionImport",          title = "Add completion import"        },        detail = "∀ a. Show a ⇒ a → Effect Unit",        documentation = {          kind = "markdown",          value = "\n*From: Effect.Console*"        },        filterText = vim.NIL,        insertText = "logShow",        kind = 3,        label = "logShow",        sortText = "Z.logShow",        textEdit = {          newText = "logShow",          range = {            end = {              character = 4,              line = 9            },            start = {              character = 2,              line = 9            }          }        }      } }  }}
`

which once formatted gets us the following structure:
```
{  
  id = 4,  
  jsonrpc = "2.0",  
  result = {    
    isIncomplete = false,    
    items = { 
      {        
        additionalTextEdits = vim.NIL,        
        command = {          
          arguments = { "log", "Effect.Class.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          
          command = "purescript.addCompletionImport",          
          title = "Add completion import"        
        },        
        detail = "∀ m. MonadEffect m ⇒ String → m Unit",        
        documentation = {          
          kind = "markdown",          
          value = "\n*From: Effect.Class.Console*"        
        },        
        filterText = vim.NIL,        
        insertText = "log",        
        kind = 3,        
        label = "log",        
        sortText = "Z.log",        
        textEdit = {          
          newText = "log",          
          range = {            
            end = {              
              character = 4,              
              line = 9            
            },            
            start = {              
              character = 2,              
              line = 9            
            }          
          }        
        }      
      }, {        
        additionalTextEdits = vim.NIL,        
        command = {          
          arguments = { "logShow", "Effect.Class.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          
          command = "purescript.addCompletionImport",          
          title = "Add completion import"        
        },        
        detail = "∀ m a. MonadEffect m ⇒ Show a ⇒ a → m Unit",        
        documentation = {          
          kind = "markdown",          
          value = "\n*From: Effect.Class.Console*"        
        },        
        filterText = vim.NIL,        
        insertText = "logShow",        
        kind = 3,        
        label = "logShow",        
        sortText = "Z.logShow",        
        textEdit = {          
          newText = "logShow",          
          range = {            
            end = {              
              character = 4,              
              line = 9            
            },            
            start = {              
              character = 2,              
              line = 9            
            }          
          }        
        }      
      }, {        
        additionalTextEdits = vim.NIL,        
        command = {          
          arguments = { "log", "Effect.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          
          command = "purescript.addCompletionImport",          
          title = "Add completion import"        
        },        
        detail = "String → Effect Unit",        
        documentation = {          
          kind = "markdown",          
          value = "\n*From: Effect.Console*"        
        },        
        filterText = vim.NIL,        
        insertText = "log",        
        kind = 3,        
        label = "log",        
        sortText = "Z.log",        
        textEdit = {          
          newText = "log",          
          range = {            
            end = {              
              character = 4,              
              line = 9            
            },            
            start = {              
              character = 2,              
              line = 9            
            }          
          }        
        }      
      }, {        
        additionalTextEdits = vim.NIL,        
        command = {          
          arguments = { "logShow", "Effect.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          
          command = "purescript.addCompletionImport",          
          title = "Add completion import"        
        },        
        detail = "∀ a. Show a ⇒ a → Effect Unit",        
        documentation = {          
          kind = "markdown",          
          value = "\n*From: Effect.Console*"        
        },        
        filterText = vim.NIL,        
        insertText = "logShow",        
        kind = 3,        
        label = "logShow",        
        sortText = "Z.logShow",        
        textEdit = {          
          newText = "logShow",          
          range = {            
            end = {              
              character = 4,              
              line = 9            
            },            
            start = {              
              character = 2,              
              line = 9            
            }          
          }        
        }      
      } 
    }  
  }}

```

</details>

In the response, `result.items[i].command.arguments[3]` contains a `vim.NIL` which will be converted to a Lua `nil` in `handle_body` from `rpc.lua` (line 522). I suspect this is the issue because:
- Commenting line 522 `decoded.result = convert_NIL(decoded.result)` fixes the issue (but you get an other one down the line, so not a proper fix obviously).
- Inserting line 556 the following piece of code (before the `try_call`), which replaces the `vim.NIL` values by empty strings, fixes the issue:
```lua
if decoded.result and decoded.result.items then
  for i, table in ipairs(decoded.result.items) 
    if decoded.result.items[i] ~= nil then
      decoded.result.items[i].command.arguments[3] = ""
    end
  end
end
```

I'm not sure if the problem comes from `purescript-language-server` returning a `null` value in the middle of an array, or from the `vim.NIL` conversion logic.

Let me know if you need more information.

### PR DESCRIPTION
**Pull request by akinsho**
This PR is based on the discussion in #13829, where `nil` is being dropped whilst decoding the lsp server responses (and requests?). It simply uses `vim.tbl_islist` as suggested there. One question I still have is if we have to check that the list doesn't contain any tables that might need to have nil values converted. I'm not very familiar with the lsp implementation here so not sure if that's necessary.

It does however resolve the issue in #14564 and so will hopefully also fix #13829

@mjlbach was this what you had in mind regarding a fix for #13829

#### Todo
- [x] Check that this hasn't broken anything...

### CODE REVIEW

**Comment by mjlbach** [comment]
Would be good to have a test :)

**Comment by akinsho** [comment]
@mjlbach any chance you can point me towards where this test should go? I've read through the testing part of the README, still not entirely sure where this file is being tested, there's no `rpc_spec` or anything

**Comment by mjlbach** [comment]
prob just lsp_spec.lua

File: test/functional/plugin/lsp_spec.lua [hunk 1]
```diff
@@ -926,6 +926,49 @@ describe('LSP', function()
         end;
       }
     end)
+
+    it('should handle return nil when decoding a list', function()
```
Comment (akinsho) [inline test/functional/plugin/lsp_spec.lua:930]: @mjlbach sorry to be a bother but in the interest of time/trying to get this in for 0.5 I wonder if you could help. The testing helpers for the lsp presume a much better understanding of neovim's client than I have and I'd like to avoid losing too much time trying to wrangling with it.

I'm essentially just trying to send a request back and forth from the fake server and assert that `vim.NIL` is kept if the params contains a list but my test keeps failing because the expected callbacks are in the wrong order 🤔 . There's kind of a lot going on across the various test helpers

Is this the kind of test you had in mind, should it be something simpler that just checks the behaviour of `handle_body`?

Comment (mjlbach) [reply test/functional/plugin/lsp_spec.lua:930]: I can help debug any tests this weekend. I would try to match the callbacks expected by other tests, there shouldn't be anything unique about this other than the fact that you're using code-actions which has 2 round trips

Comment (akinsho) [reply test/functional/plugin/lsp_spec.lua:930]: @mjlbach I've spent more time plugging away at this now and I'm not really sure how specifically to test this based on the examples in `lsp_spec.lua`. It doesn't have any docs so it's mostly been trial and error/reading through some of the helper implementations.

What should the flow be within my test case be? I tried basing it on the issue I saw i.e. I've tried triggering and responding to a code action which should trigger an `executeCommand` if this command contained a list with a `nil` value then if this change was working we'd expect it to get through to the test in `fake_lsp_server.lua` with the `vim.NIL` intact?

Trying to trigger the `vim.lsp.buf.code_action()` doesn't seem to do anything i.e. the `textDocument/codeAction` isn't sent to the fake lsp server and none of the subsequent commands are executed, I also can't tell whether it getting through would correctly validate that `NIL` was no longer being filtered out. Just passing notifications through using `client.notify` doesn't seems to make a difference whether I comment out my changes or not.

**Comment by akinsho** [comment]
@mjlbach apologies for all the pings. I *think* I finally got a handle on the test setup and have updated my test although it doesn't really seem to matter whether or not my change is included or not the tests seem to pass regardless i.e. I send a request from the client with a list containing `vim.NIL` and whether or not I have my changes in or not the test passes.

The tests all seem to rebuild nvim every time so I'm guessing nothing is cached and looking at `client.request` it seems as though it would flow through the code path I changed but it doesn't seem to make a difference in either case. Any ideas?

File: runtime/lua/vim/lsp/rpc.lua [hunk 2]
```diff
@@ -50,9 +50,11 @@ recursive_convert_NIL = function(v, tbl_processed)
     return nil
   elseif not tbl_processed[v] and type(v) == 'table' then
     tbl_processed[v] = true
-    return vim.tbl_map(function(x)
-      return recursive_convert_NIL(x, tbl_processed)
-    end, v)
+    if not vim.tbl_islist(v) then
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/rpc.lua:53]: This will also mean that dictionaries within tables will no longer be recursively processed. Maybe we should acount for that and only keep `vim.NIL` in lists, but still recurse into dictionary-style-tables ?

Comment (akinsho) [reply runtime/lua/vim/lsp/rpc.lua]: Just pushed a changed which should allow trimming `vim.NIL` in dictionaries but spare lists 👍🏾

**Comment by mjlbach** [comment]
@akinsho the PR LGTM but the test included seems to not fail even without this PR. The fix should check that a table terminating with `nil` has the correct number of arguments when sent from the server to the client.

**Comment by akinsho** [comment]
@mjlbach I've tweaked the test and verified that it now fails without this PR's change. I think this is done on my end. Let me know if there's anything missing.

**Comment by mjlbach** [comment]
@mfussenegger this LGTM now, WDYT?

@akinsho thanks for driving this. Can you squash your commits and use conventional commit style on the message? Otherwise I'll squash/merge when tests are green

**Review by mjlbach — APPROVED** [review]

**Comment by akinsho** [comment]
@mjlbach I've already squashed them down and am using the conventional commit syntax

**Comment by mjlbach** [comment]
I thrink a more accurate commit message is `fix(lsp): do not convert vim.NIL to nil in lists`

**Comment by akinsho** [comment]
I've rebased the branch off master and updated the test. I think the reference to callbacks in the lsp spec changed at some point and I needed to update this PR. Not sure if that was why it was failing, but it seems to pass all functional tests on my machine now
