### PR TITLE
fix(shada): preserve marks after delete across sessions

### LINKED ISSUE #35770: :bdelete erases marks on closing
### Problem

Using `:bdelete` on any currently open files with global or local marks deletes
their marks upon closing neovim. Tested `:bufdo bd` with all globally marked
files open, with disastrous results. This can be avoided if the user re-opens
the marked files before closing neovim.

I tried to find the commit that caused the issue with git bisect. I believe
this to be the culprit: 6bee2f686fcfd190e7017fc08115de247ac9afe9 .

### Steps to reproduce

```md
# Marks are deleted

1. nvim -u NONE
2. :edit foo
3. :mark X (or mX)
4. :marks               // "foo" is listed
5. :bdelete
6. :marks               // "foo" is still listed
7. :q
8. nvim -u NONE
9. :marks               // "foo" is gone

# Marks persist

1. nvim -u NONE
2. :edit foo
3. :mark X (or mX)
4. :edit bar
5. :mark Y (or mY)
6. :marks               // "foo" and "bar" are listed
7. :bufdo bdelete
8. :marks               // "foo" and "bar" are still listed
9. :edit foo            // Reloading "foo" prevents the bug
10. :q
11. nvim -u NONE
12. :marks              // "foo" is listed, but "bar" is gone
```

### Expected behavior

Marks are not deleted by `:bdelete`, as that concerns `:bwipeout`.

### Nvim version (nvim -v)

v0.12.0-dev-1264d11

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Debian 13

### Terminal name/version

kitty 0.41.1

### $TERM environment variable

xterm-kitty

### Installation

bob-nvim

### PR DESCRIPTION
**Pull request by glepnir**
Problem: marks are lost after `:bdelete` because `ignore_buf()` filters out unlisted buffers during shada mark processing.

Solution: revert to original buffer checks for mark operations, avoiding 
`!buf->b_p_bl` condition that incorrectly ignores deleted buffers.

Fix #35770

### CODE REVIEW

**Comment by justinmk** [comment]
> Solution: removing `!buf->b_p_bl` condition that incorrectly ignores deleted buffers.

is that outdated? does not seem to match the approach taken here.

**Comment by zeertzjq** [comment]
```c
static inline bool ignore_buf(const buf_T *const buf, Set(ptr_t) *const removable_bufs)
  FUNC_ATTR_PURE FUNC_ATTR_WARN_UNUSED_RESULT FUNC_ATTR_ALWAYS_INLINE
{
  return (buf == NULL || buf->b_ffname == NULL || !buf->b_p_bl || bt_quickfix(buf) \
          || bt_terminal(buf) || set_has(ptr_t, removable_bufs, (ptr_t)buf));
}
```

**Comment by zeertzjq** [comment]
Isn't this just reverting part of #34373

**Comment by justinmk** [comment]
Also interested in the answer to that. Though it passes tests...

This is a painful bug so would like to see it fixed.

**Comment by glepnir** [comment]
shouldn’t ignore b_p_bl here, otherwise marks for files that were once opened won’t be written.   #34373 replaced some branches with ignore_buf. however, this one shouldn’t have been replaced.

File: test/functional/shada/marks_spec.lua [hunk 1]
```diff
@@ -418,4 +418,30 @@ describe('ShaDa support code', function()
     -- Make sure that uppercase marks aren't deleted.
     nvim_command('normal! `A')
   end)
+
+  it('preserves marks after bdelete #35770', function()
```
Comment (zeertzjq) [inline test/functional/shada/marks_spec.lua]:
```suggestion
  it('preserves marks after :bdelete #35770', function()
```
