### PR TITLE
fix(startup): keep empty file arg w/ stdin

### LINKED ISSUE #35269: `echo foo bar | xargs nvim` does not open foo unless it is nonempty
### Problem

`echo foo bar | xargs nvim` is supposed to run `nvim foo bar`, but the buffer 1 is gone unless the first argument, `foo`, is an existing nonempty file.
`echo foo | xargs nvim` works as expected.

nvim v0.8.0 (appimages) opens foo and bar as buffers 2 and 3, resp, while v0.9.0 does not.

A workaround is to supply `--open-tty` (non POSIX) to xargs, which reopens stdin for nvim.

related? #8561

### Steps to reproduce

It does not matter whether the second argument, bar, exists or not.

#### 1. foo does not exist

```sh
rm -f foo
echo foo | xargs nvim --clean +ls
#  1 %a   "foo"                          line 0
echo foo bar | xargs nvim --clean +ls
#  2 %a   "bar"                          line 0
```

#### 2. foo is empty

```sh
echo > foo
echo foo | xargs nvim --clean +ls
#  1 %a   "foo"                          line 0
echo foo bar | xargs nvim --clean +ls
#  2 %a   "bar"                          line 0
```

#### 3. foo is not empty (works as expected)

```sh
echo 1 > foo
echo foo | xargs nvim --clean +ls
#  1 %a   "foo"                          line 0
echo foo bar | xargs nvim --clean +ls
#  1 %a   "foo"                          line 0
#  2      "bar"                          line 0
```

### Expected behavior

nvim, invoked by xargs, opens the first argument, foo, that does not exist or is empty.

### Nvim version (nvim -v)

v0.12.0-dev-0fa8157

### Vim (not Nvim) behaves the same?

no, vim 9.1.1552

### Operating system/version

EndeavourOS

### Terminal name/version

ghostty 1.1.3

### $TERM environment variable

xterm-ghostty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by cameronr**
Problem:

Running `echo dummy | nvim file1 file2` closes the buffer for file1 if file1 doesn't exist.

Solution:

It looks the timing or order of when the buffer for stdin was created changed in 43e8ec9 such that the stdin buffer may now be created after the file arguments. This change handles that case.

Fixes: #35269

### CODE REVIEW

**Comment by cameronr** [comment]
I'm new to the neovim codebase so I wasn't sure if there was a way to read the stdin buffer without making it `curbuf`. If there's a better way, please let me know!

File: test/functional/core/startup_spec.lua [hunk 1]
```diff
@@ -534,6 +534,26 @@ describe('startup', function()
     )
   end)
 
+  it('if stdin and file arguments, keep first file even if empty #35269', function()
```
Comment (justinmk) [inline test/functional/core/startup_spec.lua]: er... doesn't this conflict with the test just above (which references https://github.com/neovim/neovim/issues/8561)? 

    if stdin is empty: selects buffer 2, deletes buffer 1 #8561

or is it different because in this case, buffer 1 is an actual file-on-disk?

File: src/nvim/main.c [hunk 2]
```diff
@@ -1623,15 +1623,37 @@ static void read_stdin(void)
   swap_exists_action = SEA_DIALOG;
   no_wait_return = true;
   bool save_msg_didany = msg_didany;
+  buf_T *prev_buf = NULL;
+
+  if (curbuf->b_ffname) {
+    // curbuf is already opened for a file, create a new buffer for stdin #35269
+    buf_T *newbuf = buflist_new(NULL, NULL, 0, 0);
+    if (newbuf == NULL) {
+      ELOG("Unable to allocate buffer for stdin");
```
Comment (justinmk) [inline src/nvim/main.c]: based on other parts of main.c it looks like we can use `semsg` here, which helps avoids confused users. though this should "never" happen in practice.
```suggestion
      semsg("Failed to create buffer for stdin");
```

File: src/nvim/main.c [hunk 3]
```diff
@@ -1623,15 +1623,37 @@ static void read_stdin(void)
   swap_exists_action = SEA_DIALOG;
   no_wait_return = true;
   bool save_msg_didany = msg_didany;
+  buf_T *prev_buf = NULL;
+
+  if (curbuf->b_ffname) {
+    // curbuf is already opened for a file, create a new buffer for stdin #35269
```
Comment (justinmk) [inline src/nvim/main.c]:
```suggestion
    // curbuf is already opened for a file, create a new buffer for stdin. #35269
```

File: src/nvim/main.c [hunk 4]
```diff
@@ -1623,15 +1623,37 @@ static void read_stdin(void)
...
   // Create memfile and read from stdin.
   open_buffer(true, NULL, 0);
-  if (buf_is_empty(curbuf) && curbuf->b_next != NULL) {
-    // stdin was empty, go to buffer 2 (e.g. "echo file1 | xargs nvim"). #8561
-    do_cmdline_cmd("silent! bnext");
-    // Delete the empty stdin buffer.
-    do_cmdline_cmd("bwipeout 1");
+  if (buf_is_empty(curbuf)) {
+    // stdin was empty so we should wipe it (e.g. "echo file1 | xargs nvim"). #8561
+    // stdin buffer may be first or last #35269
```
Comment (justinmk) [inline src/nvim/main.c]:
```suggestion
    // stdin buffer may be first or last ("echo foo | nvim file1 -"). #35269
```

File: src/nvim/main.c [hunk 5]
```diff
@@ -1623,15 +1623,37 @@ static void read_stdin(void)
...
+      ELOG("Unable to allocate buffer for stdin");
+      return;
+    }
+
+    // remember the current buffer so we can go back to it
+    prev_buf = curbuf;
+    set_curbuf(newbuf, 0, false);
+  }
+
   set_buflisted(true);
```
Comment (justinmk) [inline src/nvim/main.c:1641]: was this intended to apply to the stdin buffer? does this need to be moved?

File: test/functional/core/startup_spec.lua (hunk 1 above)
Comment (justinmk) [inline test/functional/core/startup_spec.lua]:
```suggestion
  it('file args + empty stdin #35269', function()
```

**Review by justinmk — APPROVED** [review]
LGTM, thanks! Ideally `prev_buf` could be eliminated somehow, or maybe that whole block of logic could be simplified.

File: test/functional/core/startup_spec.lua (hunk 1 above)
Comment (cameronr) [reply test/functional/core/startup_spec.lua]: Sorry, I should've called it out more. Difference between those two tests is where the `-` is in the argument list. In the test for #8561 it's first, in the test I added it's last. That's why the unit tests still passed even when it was failing when using non-headless mode from the shell (since stdin ends up being read last in that case). I'll update the name of the test.

File: src/nvim/main.c (hunk 5 above)
Comment (cameronr) [reply src/nvim/main.c:1641]: The two cases are:

1. stdin buffer is first and so it's already `curbuf` (this is the case that worked before)

2. stdin buffer is last and `curbuf` is pointing to the first file argument. that case, we need to set `curbuf` to the stdin buffer while we work with it (and remember the old `curbuf` so we can restore it when we're done). So I don't think it needs to be moved (unless I've misunderstood the question)

File: test/functional/core/startup_spec.lua (hunk 1 above)
Comment (cameronr) [reply test/functional/core/startup_spec.lua]: My proposal for this one is:

if stdin is empty and - is last: selects buffer 1, deletes buffer 3 #35269

**Comment by cameronr** [comment]
> Ideally `prev_buf` could be eliminated somehow, or maybe that whole block of logic could be simplified.

I know, I wish I knew a cleaner way to do it.

**Comment by e-kwsm** [comment]
@cameronr thank you for your work!

**Comment by glepnir** [comment]
ASAN failed.

File: src/nvim/main.c [hunk 6]
```diff
@@ -1623,15 +1623,37 @@ static void read_stdin(void)
...
-  if (buf_is_empty(curbuf) && curbuf->b_next != NULL) {
-    // stdin was empty, go to buffer 2 (e.g. "echo file1 | xargs nvim"). #8561
-    do_cmdline_cmd("silent! bnext");
-    // Delete the empty stdin buffer.
-    do_cmdline_cmd("bwipeout 1");
+  if (buf_is_empty(curbuf)) {
+    // stdin was empty so we should wipe it (e.g. "echo file1 | xargs nvim"). #8561
+    // stdin buffer may be first or last ("echo foo | nvim file1 -"). #35269
+    if ((curbuf->b_next != NULL) || (curbuf->b_prev != NULL)) {
+      do_bufdel(DOBUF_WIPE, NULL, 0, 0, 0, 1);
```
Comment (justinmk) [inline src/nvim/main.c:1648]: asan failure. this is one reason why the old code was using `do_cmdline_cmd`

```
= ==13649==ERROR: LeakSanitizer: detected memory leaks
= 
= Direct leak of 176 byte(s) in 1 object(s) allocated from:
=     #0 0x564318bc0da3 in malloc (/home/runner/work/neovim/neovim/build/bin/nvim+0xd1eda3) (BuildId: 94f2d704be41a838937af8c98dba131aa568a09b)
=     #1 0x564319852584 in try_malloc /home/runner/work/neovim/neovim/src/nvim/memory.c:113:15
=     #2 0x5643198527e4 in xmalloc /home/runner/work/neovim/neovim/src/nvim/memory.c:147:15
=     #3 0x564319800ac2 in mf_open /home/runner/work/neovim/neovim/src/nvim/memfile.c:89:20
=     #4 0x56431980c253 in ml_open /home/runner/work/neovim/neovim/src/nvim/memline.c:310:20
=     #5 0x564318e24d70 in open_buffer /home/runner/work/neovim/neovim/src/nvim/buffer.c:230:7
=     #6 0x564318e2cb84 in enter_buffer /home/runner/work/neovim/neovim/src/nvim/buffer.c:1741:5
=     #7 0x564318e428e2 in set_curbuf /home/runner/work/neovim/neovim/src/nvim/buffer.c:1676:5
=     #8 0x5643196bc78f in read_stdin /home/runner/work/neovim/neovim/src/nvim/main.c:1638:5
=     #9 0x5643196ac8dc in main /home/runner/work/neovim/neovim/src/nvim/main.c:529:5
=     #10 0x7f67e2c2a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
=     #11 0x7f67e2c2a28a in __libc_start_main csu/../csu/libc-start.c:360:3
=     #12 0x564318b20f74 in _start (/home/runner/work/neovim/neovim/build/bin/nvim+0xc7ef74) (BuildId: 94f2d704be41a838937af8c98dba131aa568a09b)
```

Comment (cameronr) [reply src/nvim/main.c:1648]: Ok, I'll take a look. Is there a way to run the leak detection locally?

Comment (justinmk) [reply src/nvim/main.c:1648]: thanks, already addressed by https://github.com/neovim/neovim/pull/35413
