### PR TITLE
fix(marks): wrong display after inserting/deleting lines

### LINKED ISSUE #27369: Virtual text with left gravity shown on two lines after pasting above
### Problem

Virtual text with left gravity shown on two lines after pasting above:

https://github.com/neovim/neovim/assets/35768171/a734b112-b4f5-43dc-901e-b4a50f7509ab

### Steps to reproduce

1. Run `nvim --clean`
2. Source the following file:
```vim
call setline(1, ['aaa', 'bbb', 'ccc', 'ddd'])
let ns = nvim_create_namespace('')
call nvim_buf_set_extmark(0, ns, 1, 0, #{virt_text: [['foo']], right_gravity: v:false})
```
3. Press `yyp`
4. Virtual text is shown on both line 2 and line 3

### Expected behavior

Virtual text is only shown on one line. After pressing `<C-L>` it is shown on line 2, which may or may not be the expected behavior.

### Neovim version (nvim -v)

v0.10.0-dev-2294+gc0b99bb1de 

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### LINKED ISSUE #27370: Wrong display when deleting line with inline virtual text causes another line to wrap
### Problem

Wrong display when deleting line with inline virtual text causes another line to wrap:

https://github.com/neovim/neovim/assets/35768171/44818e37-325c-41d4-afc3-69a102b0a9bc

### Steps to reproduce

1. Run `nvim --clean`
2. Source the following file:
```vim
call setline(1, ['aaa', 'bbb', 'ccc', 'ddd', 'eee'])
call setline(3, repeat('c', winwidth(0) - 1))
let ns = nvim_create_namespace('')
call nvim_buf_set_extmark(0, ns, 1, 0, #{virt_text: [['!!!']], virt_text_pos: 'inline'})
```
3. Press `j`
4. Press `dd`
5. The last two lines are both displayed as `eee`

### Expected behavior

The last two lines are displayed as `ddd` and `eee`

### Neovim version (nvim -v)

v0.10.0-dev-2294+gc0b99bb1de   

### Vim (not Nvim) behaves the same?

N/A (deletes text property with line)

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Lines to/from which virt_lines or inline virt_text may have
          moved are left valid. Similarly the modified region may be
          too small to account for moved decorations after inserting
          or deleting lines. `redrawOneLine()` can be replaced with
          a call to `changed_lines_redraw_buf()`.
Solution: Invalidate the line after a change if there is virt_lines, or
          inline virt_text in the buffer with 'wrap' enabled. Extend the
          modified region for inserted or deleted lines if there may be
          decorations in the buffer. Remove `redrawOneLine()`.
          Simplify the logic for `changed_lines_invalidate_win()`.

Fix #27369
Fix #27370

### CODE REVIEW

**Comment by luukvbaal** [comment]
This resolves https://github.com/neovim/neovim/pull/33361#issuecomment-2781689543. I.e. with this patch applied but cf59631f reverted, there is no apparent problem when trying to reproduce #33358.

File: src/nvim/change.c [hunk 1]
```diff
@@ -523,6 +503,13 @@ void deleted_lines_mark(linenr_T lnum, int count)
 /// @param xtra number of extra lines (negative when deleting)
 void changed_lines_redraw_buf(buf_T *buf, linenr_T lnum, linenr_T lnume, linenr_T xtra)
 {
+  // When lines are deleted "lnume" needs to be adjusted to ensure it
+  // is set to the last line below the change.
+  lnume += (xtra < 0);
```
Comment (zeertzjq) [inline src/nvim/change.c:508]: This doesn't look correct. `lnume` is already the line below last change line as mentioned in the doc comment above.

Comment (luukvbaal) [reply src/nvim/change.c:508]: It didn't look right to me either but "it" in the comment should be `buf->b_mod_bot`. You'll find that when you delete a line 1, currently both `buf->b_mod_top` _and_ `buf->b_mod_bot` are set to 1. That is wrong according to
https://github.com/neovim/neovim/blob/c73a827564083b4dadb3a70468466306fb416d08/src/nvim/drawscreen.c#L1574

Commenting out this line results in a failure `decorations_spec.lua`.

Comment (zeertzjq) [reply src/nvim/change.c]: How is that wrong? The lines that need changes have been deleted, so no lines need changes.

Comment (luukvbaal) [reply src/nvim/change.c]: It's wrong because it results in missing lines. Maybe `mod_top` shouldn't be set either then?

Comment (luukvbaal) [reply src/nvim/change.c]: The lines that are deleted by the scroll logic in #33358.

Comment (luukvbaal) [reply src/nvim/change.c]: But yeah I missed, or forgot about #27453. If the accuracy of that approach is preferred and you intend to pick that back up we can close this or reduce it to just the refactor part.

File: src/nvim/change.c [hunk 2]
```diff
@@ -186,6 +186,15 @@ static void changed_lines_invalidate_win(win_T *wp, linenr_T lnum, colnr_T col,
     approximate_botline_win(wp);
   }
 
+  // If lines haven been inserted/deleted and the buffer has virt_lines, or
+  // inline virtual text with 'wrap' is enabled, invalidate the line after the
+  // changed lines as some virt_lines may now be drawn above a different line,
+  // or cause another line to wrap.
```
Comment (zeertzjq) [inline src/nvim/change.c:192]:
```suggestion
  // and inline virtual text may cause another line to wrap.
```

File: src/nvim/change.c [hunk 3]
```diff
@@ -523,6 +508,14 @@ void deleted_lines_mark(linenr_T lnum, int count)
 /// @param xtra number of extra lines (negative when deleting)
 void changed_lines_redraw_buf(buf_T *buf, linenr_T lnum, linenr_T lnume, linenr_T xtra)
 {
+  // If lines haven been deleted and there are virtual lines in the buffer,
+  // ensure win_update() calculates the new height of the line to which
+  // virtual lines may have moved to, which could be the line below the
+  // last changed line, so buf->b_mod_bot must be set two lines below.
+  if (xtra < 0 && (buf_meta_total(buf, kMTMetaLines))) {
+    lnume += 2;
+  }
```
Comment (zeertzjq) [inline src/nvim/change.c:517]: When `xtra > 1 && buf_meta_total(buf, kMTMetaLines)`, also need to increase `lnume` by `1`.

Comment (zeertzjq) [reply src/nvim/change.c:517]: With negative `xtra` extmarks in the deleted lines may move to a different line. With positive `xtra` this doesn't happen.

File: src/nvim/change.c (hunk 1 above)
Comment (luukvbaal) [reply src/nvim/change.c]: > so the condition here should be related to extmarks

But since left gravity marks can move from the line beyond the change as you found in #27369, I think this is basically needed for any kind of decoration. The most restrictive condition we have available for that right now would be something like `buf->b_marktree->n_keys > 0`.

File: test/functional/ui/decorations_spec.lua [hunk 4]
```diff
@@ -3033,6 +3033,21 @@ describe('extmark decorations', function()
     feed('<C-E><C-Y>')
     eq(5, n.fn.line('w0'))
   end)
+
+  it('redraws the line from which a right_gravity mark has moved #27369', function()
```
Comment (zeertzjq) [inline test/functional/ui/decorations_spec.lua:3037]:
```suggestion
  it('redraws the line from which a left gravity mark has moved #27369', function()
```

**Review by zeertzjq — APPROVED** [review]
