### PR TITLE
jumplist: avoid extra jumplist tail entry

### LINKED ISSUE #9775: :drop on unopen file adds extra jump to jumplist
- `nvim --version`:
> NVIM v0.3.4
> Build type: Release
> LuaJIT 2.0.5
> Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
> Compiled by builduser
> 
> Features: +acl +iconv +jemalloc +tui 
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> 
> Run :checkhealth for more info

- Operating system/version:
> 4.20.11-arch2-1-ARCH <span>#</span>1 SMP PREEMPT Fri Feb 22 13:09:33 UTC 2019

- Terminal name/version:
> <span>#</span> GNOME Terminal 3.30.2 using VTE 0.54.3 +GNUTLS
- `$TERM`: xterm-256color

### Issue

When a file is not open in a window and is to be edited in the current window, `:drop` adds an extra jump, which is a duplicate of the current position, at the tail of the jumplist.
This makes it necessary to press `<CTRL-O>` twice to go back to the previous cursor position.

### Steps to reproduce using `nvim -u NORC`

Given the following two files:
```
#file1
file1 contents

#file2
file2 contents
```

The following does not work as expected:

```
nvim -u NORC file1
:drop file2
<CTRL-O>
```

### Actual behaviour

```
nvim -u NORC file1
:clearjumps
:drop file2
:jumps

 jump line  col file/text
   2     1    0 file1
   1     1    0 file2 contents
>
```

### Expected behaviour

```
nvim -u NORC file1
:clearjumps
:drop file2
:jumps

 jump line  col file/text
   1     1    0 file1
>
```

### PR DESCRIPTION
**Pull request by abdelhakeem**
setpcmark() should not add pcmark to jumplist if jumplist tail is the same.

fixes #9775

### CODE REVIEW

File: src/nvim/mark.c [hunk 1]
```diff
@@ -163,6 +163,15 @@ int setmark_pos(int c, pos_T *pos, int fnum)
...
  */
 void setpcmark(void)
+{
+  setpcmark_jl(true);
+}
+
+/*
+ * Set the previous context mark to the current position and add it to the
+ * jump list if "jumplist" is true.
+ */
```
Comment (mhinz) [inline src/nvim/mark.c]: This should use Doxygen style:

```c

/// Set the previous context mark to the current position.
///
/// @param jumplist Add current position to jumplist, if true.
void setpcmark......
```

**Comment by justinmk** [comment]
Thank you @abdelhakeem , I'm quite interested in this feature myself. Can you add a basic test? I would create a new test file `test/functional/normal/jump_spec.lua`. 

See `test/functional/example_spec.lua` to get started.

**Comment by justinmk** [comment]
If we change it to _always_ avoid adding a duplicate consecutive jumplist item, does that avoid the `setpcmark_ext` extra function?

**Comment by abdelhakeem** [comment]
> If we change it to _always_ avoid adding a duplicate consecutive jumplist item, does that avoid the `setpcmark_ext` extra function?

Actually I misunderstood the issue at first, hence my wording led to misunderstanding...
The issue we're having here is not about duplicate consecutive jumplist items (that might be another issue though), it's the call to `setpcmark` that is not followed by a jump. `setpcmark`adds the current position to the jumplist by default (_not_ duplicated), with the assumption that anyone would call it before an actual jump, so it pushes the current position. `do_argfile` just wants to update the current position mark when it calls `setmark('\'')`, it shouldn't update the jumplist in this case then.

Remember the jumplist in the `:drop` issue looks like this:
`
 jump line  col file/text
   2     1    0 file1
   1     1    0 file2 contents
>
`
No duplicate entries, just that after adding `1     1    0 file2 contents` we don't jump as assumed by `setpcmark`.

**Comment by abdelhakeem** [comment]
Related: https://github.com/neovim/neovim/issues/9775#issuecomment-478259421

File: test/functional/normal/jump_spec.lua [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+describe("Jumplist", function()
+  local fname1  = "Xtest-functional-normal-jump"
+  local fname2 = fname1 .. "2"
+
+  setup(function()
+    write_file(fname1,  "first file contents");
+    write_file(fname2, "second file contents");
+  end)
+
+  teardown(function()
```
Comment (justinmk) [inline test/functional/normal/jump_spec.lua]: generally it's better to use before_each and after_each, otherwise these files exist while other `it()` cases (if any are added in the future) are running in this `describe()`. It's harmless to `os.remove()` a non-existing file.

File: test/functional/normal/jump_spec.lua [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+local feed = helpers.feed
+local write_file = helpers.write_file
+
+describe("Jumplist", function()
+  local fname1  = "Xtest-functional-normal-jump"
+  local fname2 = fname1 .. "2"
+
+  setup(function()
+    write_file(fname1,  "first file contents");
+    write_file(fname2, "second file contents");
```
Comment (justinmk) [inline test/functional/normal/jump_spec.lua]: do this at the start of the `it()` block unless these files are useful for other `it()` cases.

File: test/functional/normal/jump_spec.lua [hunk 4]
```diff
@@ -0,0 +1,50 @@
+local helpers = require('test.functional.helpers')(after_each)
+
+local clear = helpers.clear
+local command = helpers.command
+local eq = helpers.eq
+local funcs = helpers.funcs
+local feed = helpers.feed
+local write_file = helpers.write_file
+
+describe("Jumplist", function()
```
Comment (justinmk) [inline test/functional/normal/jump_spec.lua]: we don't title-case test names.

**Comment by justinmk** [comment]
@abdelhakeem Thanks, this is clear now! Do you want to also fix main.c in this PR, as mentioned in https://github.com/neovim/neovim/issues/9775#issuecomment-478259421 ?

**Comment by abdelhakeem** [comment]
The fix in `main` "breaks" two tests which expect the buggy behavior:

```
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] .../abdelhakeem/neovim/test/functional/shada/marks_spec.lua @ 143: ShaDa support code is able to dump and restore jump list
.../abdelhakeem/neovim/test/functional/shada/marks_spec.lua:155: Expected objects to be the same.
Passed in:
(string) '
 jump line  col file/text
   4     2    0 Xtestfile-functional-shada-marks-2
   3     1    0 Xtestfile-functional-shada-marks-2
   2     2    0 Xtestfile-functional-shada-marks
   1     1    0 Xtestfile-functional-shada-marks
>'
Expected:
(string) '
 jump line  col file/text
   5     2    0 Xtestfile-functional-shada-marks-2
   4     1    0 Xtestfile-functional-shada-marks-2
   3     2    0 Xtestfile-functional-shada-marks
   2     1    0 Xtestfile-functional-shada-marks
   1     1    0 
>'

stack traceback:
	.../abdelhakeem/neovim/test/functional/shada/marks_spec.lua:155: in function <.../abdelhakeem/neovim/test/functional/shada/marks_spec.lua:143>

[  FAILED  ] ...bdelhakeem/neovim/test/functional/shada/merging_spec.lua @ 903: ShaDa jumps support code merges jumps when reading
...bdelhakeem/neovim/test/functional/shada/merging_spec.lua:913: Expected objects to be the same.
Passed in:
(string) '
 jump line  col file/text
   5     2    0 /a/b/c
   4     2    0 /a/b/d
   3     3    0 /a/b/d
   2     2    0 /a/b/e
   1     2    0 /a/b/f
>'
Expected:
(string) '
 jump line  col file/text
   6     2    0 /a/b/c
   5     2    0 /a/b/d
   4     3    0 /a/b/d
   3     2    0 /a/b/e
   2     2    0 /a/b/f
   1     1    0 
>'
```

**Comment by justinmk** [comment]
> The fix in main "breaks" two tests which expect the buggy behavior:

@abdelhakeem that's ok, those tests merely assert that we match Vim behavior. We are intentionally deviating now, so the tests can just be updated.

**Comment by abdelhakeem** [comment]
@justinmk 
It keeps popping up in different places as expected, this `setpcmark_ext` approach isn't reliable.
I found out that jumplist navigation commands call `cleanup_jumplist` (in `movemark`) before changing position, which already removes duplicates but it does _not_ remove this redundant entry at the tail, so I added the following to `cleanup_jumplist` instead of the original fix:

```diff
--- a/src/nvim/mark.c
+++ b/src/nvim/mark.c
@@ -1191,6 +1191,18 @@ void cleanup_jumplist(void)
   if (curwin->w_jumplistidx == curwin->w_jumplistlen)
     curwin->w_jumplistidx = to;
   curwin->w_jumplistlen = to;
+
+  if (curwin->w_jumplistlen
+      && curwin->w_jumplistidx == curwin->w_jumplistlen) {
+    // When pointer is below last jump, remove it if it
+    // matches current position.
+    const xfmark_T *fm_last = &curwin->w_jumplist[curwin->w_jumplistlen - 1];
+    if (fm_last->fmark.fnum == curbuf->b_fnum
+        && equalpos(fm_last->fmark.mark, curwin->w_cursor)) {
+      curwin->w_jumplistlen--;
+      curwin->w_jumplistidx--;
+    }
+  }
 }
```

It (hopefully) solved all instances of the problem, but the tests are weirdly always hanging here with this change though:

```
[----------] Running tests from /home/abdelhakeem/neovim/test/functional/core/fileio_spec.lua
[ RUN      ] fileio fsync() codepaths #8304: 767.11 ms OK
█
```

Any ideas?

File: test/functional/normal/jump_spec.lua [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+    eq(buf2, funcs.bufnr("%"))
+    feed("<C-O>")
+    eq(buf1, funcs.bufnr("%"))
+
+    command("drop " .. fname2)
+    feed("<C-O>")
+    eq(buf1, funcs.bufnr("%"))
+
+    os.remove(fname1)
+    os.remove(fname2)
```
Comment (justinmk) [inline test/functional/normal/jump_spec.lua]: This would go in `after_each()` to avoid stale files if the test has an error that prevents it from completing.

In contrast, `write_file` stuff can stay at the start of the test, it does not need to go in `before_each()`.

Comment (justinmk) [reply test/functional/normal/jump_spec.lua]: I'll fix it in the merge.

**Comment by justinmk** [comment]
@abdelhakeem so far as I've tested it, this is a really nice change that fixes a very old Vim issue. Nice work!

**Comment by groves** [comment]
This change means if `getjumplist` is called during `BufHidden` or `BufLeave` autocmds, the buffer being left isn't added to the jumplist.

I'm writing a plugin that uses the jumplist to show recently edited buffers in windows and added autocommands that were checking the jumplist as the user went between buffers. Was really confused as to why my jumplist stopped updating when I was editing new files.

I can't see a straightforward way to fix that bug while keeping this behavior. It seems like it'd be nice to only cleanup the jumplist on updating it rather than when reading it, but that seems like a challenging thing to do. Thought I'd toss this in here in case anyone else could think of a more straightforward fix.

**Comment by abdelhakeem** [comment]
> This change means if `getjumplist` is called during `BufHidden` or `BufLeave` autocmds, the buffer being left isn't added to the jumplist.
> 
> I'm writing a plugin that uses the jumplist to show recently edited buffers in windows and added autocommands that were checking the jumplist as the user went between buffers. Was really confused as to why my jumplist stopped updating when I was editing new files.
> 
> I can't see a straightforward way to fix that bug while keeping this behavior. It seems like it'd be nice to only cleanup the jumplist on updating it rather than when reading it, but that seems like a challenging thing to do. Thought I'd toss this in here in case anyone else could think of a more straightforward fix.

A hacky workaround could be to prevent `getjumplist()` from cleaning up the jumplist in autocmd context as it would be cleaned up later when read or used anyway:

https://github.com/neovim/neovim/blob/a973fa5b4397933e94d888d06e435a986fc4a218/src/nvim/eval/funcs.c#L3514

```c
 cleanup_jumplist(wp, !autocmd_busy); 
```

I'm not sure if this would introduce another unexpected behavior though.
