### PR TITLE
[RDY] Fix xfree of static value from vim_getenv() refactor

### LINKED ISSUE #2487: Dead lock after tab to autocomple `!./li`
I attached LLDB to a running nvim instance and tried to autocomplete `!./li`. This was enough to freeze the editor.

```c
$ lldb
(lldb) process attach --pid 38813
Process 38813 stopped
* thread #1: tid = 0x5feae6, 0x00007fff97d0821a libsystem_kernel.dylib`kevent + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007fff97d0821a libsystem_kernel.dylib`kevent + 10
libsystem_kernel.dylib`kevent:
->  0x7fff97d0821a <+10>: jae    0x7fff97d08224            ; <+20>
    0x7fff97d0821c <+12>: movq   %rax, %rdi
    0x7fff97d0821f <+15>: jmp    0x7fff97d02c53            ; cerror_nocancel
    0x7fff97d08224 <+20>: retq

Executable module set to "/Users/felipe/src/neovim/./build/bin/nvim".
Architecture set to: x86_64h-apple-macosx.
(lldb) continue
Process 38813 resuming
Process 38813 stopped
* thread #1: tid = 0x5feae6, 0x00007fff948c7fcf libsystem_platform.dylib`OSSpinLockLock + 7, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x00007fff948c7fcf libsystem_platform.dylib`OSSpinLockLock + 7
libsystem_platform.dylib`OSSpinLockLock:
->  0x7fff948c7fcf <+7>:  lock
    0x7fff948c7fd0 <+8>:  cmpxchgl %ecx, (%rdi)
    0x7fff948c7fd3 <+11>: testl  %eax, %eax
    0x7fff948c7fd5 <+13>: je     0x7fff948c7fdc            ; <+20>
(lldb) thread backtrace
* thread #1: tid = 0x5feae6, 0x00007fff948c7fcf libsystem_platform.dylib`OSSpinLockLock + 7, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x00007fff948c7fcf libsystem_platform.dylib`OSSpinLockLock + 7
    frame #1: 0x000000010a5ab994 nvim`je_arena_dalloc_large [inlined] je_malloc_mutex_lock + 36 at mutex.h:75
    frame #2: 0x000000010a5ab987 nvim`je_arena_dalloc_large(arena=0x04b881f8458b48ff, chunk=0x000000010a400000, ptr=0x000000010a5d3654) + 23 at arena.c:1978
    frame #3: 0x000000010a59c0c2 nvim`ifree + 1298 at arena.h:1056
    frame #4: 0x000000010a59be70 nvim`ifree + 423 at jemalloc_internal.h:898
    frame #5: 0x000000010a59bcc9 nvim`ifree + 23 at jemalloc_internal.h:917
    frame #6: 0x000000010a59bcb2 nvim`ifree [inlined] je_iqalloc at jemalloc_internal.h:924
    frame #7: 0x000000010a59bcb2 nvim`ifree(ptr=<unavailable>) + 258 at jemalloc.c:1233
    frame #8: 0x000000010a420515 nvim`xfree(ptr=0x000000010a5d3654) + 21 at memory.c:106
    frame #9: 0x000000010a3b7f6f nvim`expand_shellcmd(filepat=0x000000000ad68278, num_file=0x00007fff558fefa4, file=0x00007fff558fefa8, flagsarg=41) + 1167 at ex_getln.c:3902
    frame #10: 0x000000010a3b3ebe nvim`ExpandFromContext(xp=0x00007fff558fef78, pat=0x000000000ad68278, num_file=0x00007fff558fefa4, file=0x00007fff558fefa8, options=218) + 1294 at ex_getln.c:3632
    frame #11: 0x000000010a3af9a8 nvim`ExpandOne(xp=0x00007fff558fef78, str=0x000000000ad68278, orig=0x000000000ab8da60, options=218, mode=3) + 664 at ex_getln.c:2774
    frame #12: 0x000000010a3b1a4b nvim`nextwild(xp=0x00007fff558fef78, type=3, options=8, escape=1) + 443 at ex_getln.c:2616
    frame #13: 0x000000010a3ac17e nvim`getcmdline(firstc=58, count=1, indent=0) + 6190 at ex_getln.c:695
    frame #14: 0x000000010a3b2cef nvim`getexline(c=58, cookie=0x0000000000000000, indent=0) + 79 at ex_getln.c:1679
    frame #15: 0x000000010a38e497 nvim`do_cmdline(cmdline=0x0000000000000000, fgetline=0x000000010a3b2ca0, cookie=0x0000000000000000, flags=0) + 2135 at ex_docmd.c:539
    frame #16: 0x000000010a44b2db nvim`nv_colon(cap=0x00007fff558ff898) + 267 at normal.c:4049
    frame #17: 0x000000010a4414c0 nvim`normal_cmd(oap=0x00007fff558ff958, toplevel=true) + 6512 at normal.c:907
    frame #18: 0x000000010a400ea1 nvim`main_loop(cmdwin=0, noexmode=0) + 2001 at main.c:708
    frame #19: 0x000000010a3fdcd6 nvim`main(argc=1, argv=0x00007fff558ffb70) + 2614 at main.c:495
    frame #20: 0x00007fff8fb2a5c9 libdyld.dylib`start + 1
```

### PR DESCRIPTION
**Pull request by mbainter**
Fixes #2487.

The refactoring of vim_getenv() to remove the mustfree arg
included reworking calling functions.  expand_shellcmd was
also using that to track its usage of the variable within
the function, resulting in #2487. This change addresses
that scenario and cleans up some of the function for style.

### CODE REVIEW

**Comment by elmart** [comment]
Thanks for fixing this so quick.
Couple of things:
- Please take as a habit separating style-only changes and meaningful changes. In this case, you can make a "Cleanup" commit with all style changes, and a "Fix" commit with the real fix.
- It would be nice if you reviewed your last merged PR, so that we make sure there are no other cases like this. I mean, review calling places where `mustfree` was removed, to make sure we don't have more static strings incorrectly freed. I think to remember there weren't many places, and it's strange that error passed reviewers filter (my fault), but just to be sure. If there's some more case, please include it in this PR too.

**Comment by elmart** [comment]
BTW, we use [WIP] (work in progress) for what you have used [InProgress]. Convention is [WIP] --> [RFC] --> [RDY]. Bot automatically assigns tags if you follow it, and it's clearer for everyone else.

**Comment by mbainter** [comment]
No problem.  I marked it as in progress as I want to go through the rest just to be sure I didn't miss that anywhere else.  When I made the change I was looking for that, but somehow I missed it here.  I want to be sure I didn't anywhere else before you merge this.  I wanted to get the fix out here right away though.

Good point on the style vs fix, I should know better than that.  I will make sure I separate them going forward.

File: src/nvim/ex_getln.c [hunk 1]
```diff
@@ -3832,49 +3832,56 @@ static void expand_shellcmd(char_u *filepat, int *num_file, char_u ***file,
...
-  /* For an absolute name we don't use $PATH. */
-  if (path_is_absolute_path(pat))
+  bool mustfree = false;  // Track memory allocation for *path.
+  // For an absolute name we don't use $PATH.
+  if (path_is_absolute_path(pat)) {
     path = (char_u *)" ";
-  else if ((pat[0] == '.' && (vim_ispathsep(pat[1])
-                              || (pat[1] == '.' && vim_ispathsep(pat[2])))))
+  } else if ((pat[0] == '.' && (vim_ispathsep(pat[1]) 
+        || (pat[1] == '.' && vim_ispathsep(pat[2]))))) {
```
Comment (elmart) [inline src/nvim/ex_getln.c]: This doesn't follow styleguide. `||` should be columned below `vim_ispathsep`, as before.

File: src/nvim/ex_getln.c [hunk 2]
```diff
@@ -3882,24 +3889,28 @@ static void expand_shellcmd(char_u *filepat, int *num_file, char_u ***file,
...
       ++e;
+    }
   }
   *file = ga.ga_data;
   *num_file = ga.ga_len;
 
   xfree(buf);
   xfree(pat);
-  xfree(path);
+  if(mustfree) {
```
Comment (elmart) [inline src/nvim/ex_getln.c]: Space needed after `if`.

**Comment by mbainter** [comment]
Okay, I went through everywhere vim_getenv() is called in the codebase, and reviewed the use of the variable it returns.  There was only one other place that variable is reused in that way, and it already had a mustfree variable wrapped around  that use.  I think this PR is ready.

(I addressed the issues raised above as well)

**Comment by elmart** [comment]
LGTM.

**Comment by elmart** [comment]
Ok, some more new contributor training:   ;-)
- I added "Fixes #2787." to your first comment.  That way, when this gets merged, issue is automatically closed. Please do so in future when fixing an open issue.
- You should not mark RDY before all your reviewers have given their LGTM. RDY is there for PR's that can just be merged without further thinking if maintainer sees one.

Waiting for build to pass and then I'll merge. Thanks!

File: src/nvim/ex_getln.c [hunk 3]
```diff
@@ -3841,6 +3841,7 @@ static void expand_shellcmd(char_u *filepat, int *num_file, char_u ***file,
 
   flags |= EW_FILE | EW_EXEC;
 
+  bool mustfree = false;  // Track memory allocation for *path.
```
Comment (oni-link) [inline src/nvim/ex_getln.c]: Why use`*` in the comment?

Comment (elmart) [inline src/nvim/ex_getln.c]: Ooops, sorry, I just saw your comment right after merging.
No big deal, though.
