### PR TITLE
Make SHM_ALL to a variable instead of a compound literal #define

### LINKED ISSUE #9855: SHM_ALL only contains 'x' when built with RelWithDebInfo
- `nvim --version`: 0.3.4
- Vim (version: 8.1) behaves differently? Yes.
- Operating system/version: Fedora 30
- Terminal name/version: Tilix 1.9.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Any character from `SHM_ALL` except `x` will do:
```
nvim -u NORC
:set shortmess=c
```

Attaching gdb and looking at `p` after https://github.com/neovim/neovim/blob/c5e8924f4e72f46679cff52ac075e3eb023883d5/src/nvim/option.c#L3239 yields only `x`, so my guess is that GCC 9 is being more aggressive with optimizations. There is already a hack for a similar problem: https://github.com/neovim/neovim/blob/c5e8924f4e72f46679cff52ac075e3eb023883d5/src/nvim/option.c#L2492

### Actual behaviour
`E539: Illegal character <c>: shortmess=c`

### Expected behaviour
No error.

### PR DESCRIPTION
**Pull request by jamessan**
gcc-9 has [improved compliance] with the C spec for lifetime of compound
literals, tying their lifetime to block scope instead of function scope.
This makes the behavior comparable to all other automatic variables.

Using the SHM_ALL #define instantiated a compound literal local to an if
clause and assigned the address to a "char_u *".  Since the pointer was
then being used outside of the if clause, it was using an invalid
address.

[improved compliance]: https://gcc.gnu.org/gcc-9/porting_to.html#complit

Closes #9855

### CODE REVIEW

File: src/nvim/option.c [hunk 1]
```diff
@@ -2486,11 +2495,6 @@ static bool valid_filetype(char_u *val)
   return true;
 }
 
-#ifdef _MSC_VER
-// MSVC optimizations are disabled for this function because it
-// incorrectly generates an empty string for SHM_ALL.
-#pragma optimize("", off)
-#endif
```
Comment (justinmk) [inline src/nvim/option.c]: Also should delete the counterpart

**Review by justinmk — APPROVED** [review]
