### PR TITLE
fix(highlight): accept NONE as a color name

### LINKED ISSUE #17478: 'NONE' is not a valid color
### Neovim version (nvim -v)

0.7.0 commit g6a3acccd8

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch 5.15.24-1-lts

### Terminal name/version

Alacritty 0.8.0-dev

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

```
nvim --clean
:lua vim.api.nvim_set_hl(0, "Normal", {bg="NONE"})
```

### Expected behavior

Transparent `Normal` background.

### Actual behavior

```
E5108: Error executing lua [string ":lua"]:1: 'NONE' is not a valid color
stack traceback:
        [C]: in function 'nvim_set_hl'
        [string ":lua"]:1: in main chunk```

### PR DESCRIPTION
**Pull request by lewis6991**
For when ns=0

Fixes #17478

### CODE REVIEW

File: src/nvim/highlight.c [hunk 1]
```diff
@@ -927,10 +927,11 @@ int object_to_color(Object val, char *key, bool rgb, Error *err)
   } else if (val.type == kObjectTypeString) {
     String str = val.data.string;
     // TODO(bfredl): be more fancy with "bg", "fg" etc
+    if (!str.size || STRCMP(str.data, "NONE") == 0) {
```
Comment (gpanders) [inline src/nvim/highlight.c:930]: Should we use `STRICMP` so that it's case insensitive? At least with `:highlight`, `NONE`, `none`, and `NoNe` all work.

File: src/nvim/highlight.c [hunk 2]
```diff
@@ -927,10 +927,11 @@ int object_to_color(Object val, char *key, bool rgb, Error *err)
   } else if (val.type == kObjectTypeString) {
     String str = val.data.string;
     // TODO(bfredl): be more fancy with "bg", "fg" etc
+    if (!str.size || STRICMP(str.data, "NONE") == 0) {
```
Comment (gpanders) [inline src/nvim/highlight.c:930]: This also clears the hl group for an empty string (`""`), so let's capture that in a test case too

**Review by gpanders — APPROVED** [review]
