### PR TITLE
fix(Man): completion on Mac

### LINKED ISSUE #31512: `:Man <tab>` does not complete
### Problem

`:Man` autocomplete doesn't work and shows outdated bash page. Demo [here](https://youtu.be/DsW_Vtwva5A)

References #30873

### Steps to reproduce

nvim --clean
:Man <tab>
:Man b<tab>

### Expected behavior

nvim --clean
:Man <tab> " Should show autocomplete suggestions
:Man b<tab> " Should show autocomplete suggestions

### Nvim version (nvim -v)

gab9cfc4dc3

### Vim (not Nvim) behaves the same?

No. 9.1

### Operating system/version

MacOS

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

Homebrew --head

### PR DESCRIPTION
**Pull request by lewis6991**
Problem:
`man -w` does not work on recent versions of MacOs.

Solution:
Make it so an empty result is interpreted as an error unless silent=true

closes: https://github.com/neovim/neovim/issues/31512

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
hmm, macos CI:

```
FAILED   test/functional/plugin/man_spec.lua @ 267: :Man can complete
test/functional/plugin/man_spec.lua:268: Expected objects to be the same.
Passed in:
(boolean) false
Expected:
(boolean) true

stack traceback:
	test/functional/plugin/man_spec.lua:268: in function <test/functional/plugin/man_spec.lua:267>
```

**Comment by justinmk** [comment]
It passes consistently on my intel mac. 

To unblock this, we could skip the test on intel macos. Previously we had zero test coverage so this is much better :)

File: test/functional/plugin/man_spec.lua [hunk 1]
```diff
@@ -263,4 +263,14 @@ describe(':Man', function()
       { '1', 'other_man' },
     }, get_search_history('other_man(1)'))
   end)
+
+  it('can complete', function()
+    t.skip(t.is_os('mac') and t.is_arch('x86_64'), 'not supported on intel ma')
```
Comment (justinmk) [inline test/functional/plugin/man_spec.lua:268]:
```suggestion
    t.skip(t.is_os('mac') and t.is_arch('x86_64'), 'not supported on intel mac')
```

File: test/functional/plugin/man_spec.lua [hunk 2]
```diff
@@ -263,4 +263,14 @@ describe(':Man', function()
...
+    eq(
+      true,
+      exec_lua(function()
+        return #require('man').man_complete('g', 'Man g') > 0
```
Comment (justinmk) [inline test/functional/plugin/man_spec.lua:272]: `:Man g` gets about 10x more results than `:Man f`. Just a guess, but maybe `:Man f` in this test will avoid potential timing-related issues.

Comment (lewis6991) [reply test/functional/plugin/man_spec.lua:272]: I can try, but this code is synchronous. I'm pretty sure the issue is the version of MacOS because one version updated all the coreutils and this is when `man -w` broke.

Comment (lewis6991) [reply test/functional/plugin/man_spec.lua]: Dam, I forgot to stage the change with the skip line commented out. Oh well.
