### PR TITLE
api: fix use-after-free in nvim_chan_send

### LINKED ISSUE #14198: Getting some pointer errors when using nvim_chan_send
- `nvim --version`:
```NVIM v0.5.0-dev+1174-g9f5c8226b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/iainearl/src/neovim/build/config -I/Users/iainearl/src/neovim/src -I/Users/iainearl/src/neovim/.deps/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/iainearl/src/neovim/build/src/nvim/auto -I/Users/iainearl/src/neovim/build/include
Compiled by iainearl@HOSTNAME

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/iainearl/.local/share/nvim"
```
- `vim -u DEFAULTS` (version: ) behaves differently?
It's lua related so I can't test it in vanilla vim

- Operating system/version: `macOS 11.2.2`
- Terminal name/version: `alacritty 0.7.2 (5ac8060)`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

1. Create `/tmp/bug.lua` with the following content:
```lua
local winh = nil
local bufh = nil
local chan = nil

vim.cmd("vsplit")
winh = vim.api.nvim_get_current_win()
bufh = vim.api.nvim_create_buf(true, true)
vim.api.nvim_win_set_buf(winh, bufh)
vim.api.nvim_set_current_win(winh)
vim.cmd("term")
for _, c in ipairs(vim.api.nvim_list_chans()) do
    if c.buffer == bufh then
        print("setting chan to " .. c.id)
        chan = c
    end
end
vim.api.nvim_chan_send(chan.id, "ls\n")

```
2. Open the file
```
nvim -u NORC /tmp/bug.lua
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```
3. Run the Ex command `:luafile %`

### Actual behaviour
neovim exits with some pointer errors:
```
nvim(17127,0x10d27fe00) malloc: *** error for object 0x7fb7673ef6c0: pointer being freed was not allocated
nvim(17127,0x10d27fe00) malloc: *** set a breakpoint in malloc_error_break to debug
fish: Job 1, 'nvim $argv' terminated by signal SIGABRT (Abort)
```

### Expected behaviour
I would expect it to successfully send the ls command to the terminal buffer? Unless I'm doing it horribly wrong.

### PR DESCRIPTION
**Pull request by bfredl**
fixes #14198 . curious that existing tests did not trigger this, but maybe msgpack-rpc freeing happens too late to notice.

### CODE REVIEW

File: test/functional/core/job_spec.lua [hunk 1]
```diff
@@ -979,6 +981,7 @@ describe('jobs', function()
       nvim('command', 'let g:job_opts.pty = 1')
       nvim('command', 'let exec = [expand("<cfile>:p")]')
       nvim('command', "let j = jobstart(exec, g:job_opts)")
+      j = eval'j'
```
Comment (mhinz) [inline test/functional/core/job_spec.lua:984]: It's really just a smaaaall nitpick, but I think we should use explicit parentheses here. :>

Comment (bfredl) [reply test/functional/core/job_spec.lua:984]: one day even you will learn to appreciate the full power of free form lua syntax.
