### PR TITLE
[RFC] highlighting refactor + implement termguicolors purely on TUI side

### LINKED ISSUE #7929: TUI: Switching termguicolors at runtime in tmux breaks colors until resized
- `nvim --version`: NVIM v0.2.3-527-g499c9a155
- Vim (version: 8.0.688) does not exhibit the behavior
- Operating system/version: SLES 11.3, Ubuntu 16.04, Windows
- Terminal name/version: GNOME Terminal 3.18.3, also occurs in MinTTY
- `$TERM`: screen-256color

### Steps to reproduce
1. Open a tmux (or screen) session and ensure `$TERM` is `screen-256color`.
1. Create a simple rc file with the following:
```vim
set termguicolors
colorscheme desert
```
2. Open it with `nvim -u bug-vimrc --noplugin`
3. Try to disable termguicolors with `:set notermguicolors` and notice that colors are wrong.
4. Resize the window, colors immediately get redrawn correctly.

This issue does not occur in vim, nor does it seem to occur in nvim when in a normal `xterm-256color` terminal.

Support for changing `termguicolors` at runtime was completed in #7520

### PR DESCRIPTION
**Pull request by bfredl**
Having both HlAttrs and attrentry_T seems superfluous: the later is one dword larger, so we could just as well use it in the ui abstraction and avoid the conversion. HlAttrs were only stored in bulk in `ugrid.c`, correcting the size of the largest composed char from 37 down to 29 offsets the cost...

This enables us to implement termguicolors entirely on the TUI side, no screen.c redraw needed. However to support termguicolors in a attached TUI we would need to add a third color mode in remote UI, which transmits both colors.

@johnmiked15 does this fix #7929 for you?

### CODE REVIEW

File: src/nvim/highlight_defs.h [hunk 1]
```diff
@@ -7,6 +7,37 @@
 
 typedef int32_t RgbValue;
 
+/// Terminal highlighting attribute bits.
```
Comment (justinmk) [inline src/nvim/highlight_defs.h]: not only for "terminal"

File: src/nvim/highlight_defs.h [hunk 2]
```diff
@@ -7,6 +7,36 @@
 
 typedef int32_t RgbValue;
 
+/// Highlighting attribute bits.
+/// \addtogroup HL_ATTRIBUTES
+/// @{
+#define HL_NORMAL      0x00
```
Comment (jamessan) [inline src/nvim/highlight_defs.h]: Is it worth turning this into an enum to ease inspection when debugging?

**Comment by johnmiked15** [comment]
Just tried your branch and I can confirm that it does fix #7929 for me. I can switch `termguicolors` at runtime without the `:mode` workaround and colors all look correct. Thanks for getting to this so quickly!

File: src/nvim/api/ui_events.in.h [hunk 3]
```diff
@@ -47,19 +47,22 @@ void visual_bell(void)
...
-  FUNC_API_SINCE(3);
+  FUNC_API_SINCE(3) FUNC_API_BRIDGE_IMPL;
 void update_bg(Integer bg)
-  FUNC_API_SINCE(3);
+  FUNC_API_SINCE(3) FUNC_API_BRIDGE_IMPL;
 void update_sp(Integer sp)
-  FUNC_API_SINCE(3);
+  FUNC_API_SINCE(3) FUNC_API_BRIDGE_IMPL;
+void default_colors_set(Integer rgb_fg, Integer rgb_bg, Integer rgb_sp,
+                        Integer cterm_fg, Integer cterm_bg)
```
Comment (justinmk) [inline src/nvim/api/ui_events.in.h]: Maybe it's worth adding a stub for `cterm_sp` now (IIUC it's needed for https://github.com/neovim/neovim/issues/7479 )

File: src/nvim/screen.c [hunk 4]
```diff
@@ -5847,30 +5840,16 @@ next_search_hl_pos(
...
 
-static void screen_start_highlight(int attr)
-{
-  screen_attr = attr;
-  ui_start_highlight(attr);
-}
-
-static void screen_stop_highlight(void)
-{
-  ui_stop_highlight();
```
Comment (justinmk) [inline src/nvim/screen.c]: I would vote to keep at least the `ui_` "start"/"stop" pair (`ui_start_highlight`, `ui_stop_highlight`). It gives a semantic hint, and leaves clues when comparing Vim code, at a negligible cost.

File: src/nvim/api/ui.c [hunk 5]
```diff
@@ -86,6 +86,7 @@ void nvim_ui_attach(uint64_t channel_id, Integer width, Integer height,
   ui->put = remote_ui_put;
   ui->bell = remote_ui_bell;
   ui->visual_bell = remote_ui_visual_bell;
+  ui->default_colors_set = remote_ui_default_colors_set;
```
Comment (justinmk) [inline src/nvim/api/ui.c]: maybe just `colors_set` ?

File: src/nvim/tui/tui.c [hunk 6]
```diff
@@ -410,36 +407,57 @@ static void sigwinch_cb(SignalWatcher *watcher, int signum, void *data)
...
+  }
+
+  int bg = ui->rgb ? attrs.rgb_bg_color : (attrs.cterm_bg_color - 1);
+  if (bg == -1) {
+    bg = ui->rgb ? grid->clear_attrs.rgb_bg_color
+                 : (grid->clear_attrs.cterm_bg_color - 1);
+  }
+
+  int attr = ui->rgb ? attrs.rgb_ae_attr : attrs.cterm_ae_attr;
+  bool bold = attr & HL_BOLD, italic = attr & HL_ITALIC;
```
Comment (justinmk) [inline src/nvim/tui/tui.c]: `italic` should go on its own line.

File: src/nvim/ui.c [hunk 7]
```diff
@@ -174,84 +178,57 @@ void ui_event(char *name, Array args)
...
-  if (attrs.background != -1) {
-    PUT(hl, "background", INTEGER_OBJ(attrs.background));
-  }
+  if (use_rgb) {
+    if (aep->rgb_fg_color != -1) {
+      PUT(hl, "foreground", INTEGER_OBJ(aep->rgb_fg_color));
+    }
+
+    if (aep->rgb_bg_color != -1) {
+    PUT(hl, "background", INTEGER_OBJ(aep->rgb_bg_color));
```
Comment (justinmk) [inline src/nvim/ui.c]: indent

File: src/nvim/screen.c (hunk 4 above)
Comment (bfredl) [reply src/nvim/screen.c]: But the semantics are not "start" and "stop", the nvim UI layer can directly _set_ the highlight from whatever value to whatever other value. The old names made sense in vim where screen.c directly wrote to the terminal, and clear highlight probably was a prerequisite for some term.c operations. But in nvim tui.c does its own housekeeping when explictly `^[...m` needs to be sent or not, so it makes no sense: highlights only needs to be _set_ before explicitly grid modifying operations. 

We can have `ui_clear_highlight() { ui_set_highlight(0) }` (which rhymes nicely with that they are used for clear operations) and eliminate the ad-hoc constant, but we shouldn't be afraid to rename functions when semantics in fact are different from vim.

File: src/nvim/api/ui.c (hunk 5 above)
Comment (bfredl) [reply src/nvim/api/ui.c]: Wouldn't that be too similar to `set_highlight`? I would like some qualifier like "default" or "global" to make the distinction more clear.

File: src/nvim/api/ui_events.in.h (hunk 3 above)
Comment (bfredl) [reply src/nvim/api/ui_events.in.h]: I would expect any terminal that supports sp would also support truecolors, and would be used in this mode when sp is wanted. (not to mention, vim doesn't have `ctermsp=` at all) The relevant change for #7479 would rather be to store `rgb_sp` on the tui.c side.

File: src/nvim/screen.c (hunk 4 above)
Comment (justinmk) [reply src/nvim/screen.c]: Definitely. If the semantics changed then that was just my misunderstanding.

File: src/nvim/syntax.c [hunk 8]
```diff
@@ -64,7 +64,7 @@ struct hl_group {
   int sg_cterm_bold;            ///< bold attr was set for light color
   // for RGB UIs
   int sg_gui;                   ///< "gui=" highlighting attributes
-                                ///< (combination of \ref HL_ATTRIBUTES)
+                                ///< (combination of HlAttrFlags)
```
Comment (teto) [inline src/nvim/syntax.c]: Is the HlAttrFlags picked up  automatically maybe ?

Comment (bfredl) [reply src/nvim/syntax.c]: I don't know, guess I have to check the output.

File: src/nvim/api/ui.c (hunk 5 above)
Comment (justinmk) [reply src/nvim/api/ui.c]: how about `colors_init` then. It seems weird to start putting "default" in API function/event names.

Comment (justinmk) [reply src/nvim/api/ui.c]: Or `colors_configure` -- that might be a good convention for cases where the client is expected to manage state.

**Comment by justinmk** [comment]
LGTM. Very nice cleanup.

File: src/nvim/api/ui.c (hunk 5 above)
Comment (bfredl) [reply src/nvim/api/ui.c]: Not sure I like it, all highlights are "configured". And it is not only initialization, these values is continously used and can be changed. How about calling them what they are called elsewhere, `normal_colors_set` ?

**Comment by bfredl** [comment]
I'm glad you appreciate my yak shaving.

File: src/nvim/api/ui.c (hunk 5 above)
Comment (justinmk) [reply src/nvim/api/ui.c]: default_colors_set is more intuitive than normal_colors_set, let's stick with that.
