### PR TITLE
[RDY] term: use an argument vector for termopen().

### LINKED ISSUE #2354: Tests failing with "Process does not own terminal"
Here's the [log for `make test`](https://gist.github.com/Pyrohh/733e8a80e173e887e550). I'm not quite sure what to make of it, but it looks related to [this function](https://github.com/neovim/neovim/blob/master/test/functional/job/tty-test.c#L19-22) (which was previously a no-op). I'm running Arch Linux if that makes a difference (something about systemd's process supervision mechanisms maybe?).

### PR DESCRIPTION
**Pull request by splinterofchaos**
Old behaviour: termopen('cmd') would run `&shell &shcf "cmd"`, which
caused the functional tests to fail on some systems due to the process
not "owning" the terminal. Also, it is inconsistent with jobstart().

Modify termopen() so that &shell is not invoked, but maintain the old
behaviour with :terminal. Factor the common code for building the
argument vector from jobstart() and modify the functional tests to call
termopen() instead of :terminal (fixes #2354).

---

Still [WIP] because I have yet to implement a correct naming scheme for the buffer (https://github.com/neovim/neovim/issues/2354#issuecomment-92532588), though I'm considering an alternative: add a `'name'` field to the options dictionary and set it to `{cmd}` from `ex_terminal`. Could be useful in general.

Also, I added a few tests for `:terminal`, since its behaviour now differs from `termopen()`, but I couldn't avoid using the Unix-specific `sh` without rewriting `tty-test.c` to not propagate the problem from #2354, or make another test shell. 

Will work on this more tomorrow.

### CODE REVIEW

File: src/nvim/eval.c [hunk 1]
```diff
@@ -10779,47 +10779,62 @@ static void f_jobresize(typval_T *argvars, typval_T *rettv)
   rettv->vval.v_number = 1;
 }
 
-// "jobstart()" function
-static void f_jobstart(typval_T *argvars, typval_T *rettv)
+static char** list_to_argv(list_T *args)
```
Comment (Pyrohh) [inline src/nvim/eval.c]: pointer alignment (I like the way you're doing it, but it's not project style)

**Comment by ZyX-I** [comment]
> Modify termopen() so that &shell is not invoked, but maintain the old
> behaviour with :terminal. Factor the common code for building the
> argument vector from jobstart() and modify the functional tests to call
> termopen() instead of :terminal (fixes #2354).

Why not just use `&shell` if `termopen` receives a string and new code when it receives a list? And, if possible, make the code that process this first argument reusable by `system` and `systemlist`.

**Comment by splinterofchaos** [comment]
> Why not just use &shell if termopen receives a string and new code when it receives a list?

Wouldn't be difficult, but what's the motivation, backwards compatibility? If anything, I think it'd be more consistent to make `termopen("do a cmd")` equivalent to `termopen(['do', 'a', 'cmd'])` and maybe add an option to `{opts}` (either a boolean like `'use_shell'`, or `'shell'` and `'shellcmdflag'`).

> And, if possible, make the code that process this first argument reusable by system and systemlist

I do like that idea.

**Comment by ZyX-I** [comment]
> Wouldn't be difficult, but what's the motivation, backwards compatibility?

It and consistency: you can’t remove `system(string)` due to backwards compatibility. And `termopen` also accepts shell command.

Also sometimes you *do* want to make command be processed by a shell (e.g. `call termopen('vim *.py')`) or do not have any special characters expect for space and raw string is more convenient to type.

// Side note: once we have a linter for VimL with these and changes to `system*` `termopen(string)`, `system(string)` and `systemlist(string)` should yield a warning.

**Comment by bfredl** [comment]
I also think keeping `termopen(string)` as convenient alias, and then I think it should be supported for `jobopen(string, ...)` as well, as these function already have similar api (and purpose) it would be confusing to support it in one but not the other (also they could share `val_to_argv` similar to `list_to_argv` already in this PR, and perhaps even with `system` as @ZyX-I  noted).

**Comment by splinterofchaos** [comment]
I'm starting to like these ideas, but right now I'm just working on removing the dependence of `sh` for running the tests. Maybe it's not a big deal until we get nvim on windows working, but if we get it out of the way right now it'll be less work later.

Also, the goal is to resolve #2354 so @Pyrohh, I, and whoever else can run functional tests without hacking into `test/functional/tty-test.c`, so I want to delay any new features that could delay the merging of this PR. Though, if we determine that `termopen()` is too widely used to *temporarily not* have backwards compatibility, then I'll have to fix that immediately anyway.

**Comment by bfredl** [comment]
Sounds reasonable, no need to do it all in this PR. (Unless for the `termopen()` part, I don't know if it is relied upon)

File: src/nvim/eval.c (hunk 1 above)
Comment (splinterofchaos) [inline src/nvim/eval.c]: :+1:

**Comment by splinterofchaos** [comment]
Silly me: spending all day writing a very simple shell to execute programs through libuv, just for testing `:terminal`, when all I had to so was print a prompt, the command, and exit.

Marking RFC.

**Comment by splinterofchaos** [comment]
I've implemented the suggested change, but as I said, I don't want to delay merging this because of them. While reviewing, please let me know if the commits, minus the last, look good so that if I need to work on it more, but everything else is fine, I can remove the commit, merge, and create a new PR.

File: runtime/doc/eval.txt [hunk 2]
```diff
@@ -6140,7 +6143,9 @@ synstack({lnum}, {col})					*synstack()*
 		valid positions.
 
 system({expr} [, {input}])				*system()* *E677*
-		Get the output of the shell command {expr} as a string.  See
+		Get the output of the shell command {expr} as a string. If
+		{expr} is a string, 'shell' and 'shellcmdflag' will be used,
+		if {expr} is a string, it will be run directly.  See
```
Comment (ZyX-I) [inline runtime/doc/eval.txt]: Here should be “`if {expr} is a |List|`”, not “if `{expr}` is a string”.

File: runtime/doc/eval.txt [hunk 3]
```diff
@@ -6287,15 +6289,19 @@ tempname()					*tempname()* *temp-file-name*
...
-		if the current buffer is modified (all buffer contents are
-		destroyed).  The {opts} dict is similar to the one passed to
-		|jobstart()|, but the `pty`, `width`, `height`, and `TERM` fields are
-		ignored: `height`/`width` are taken from the current window and
-		$TERM is set to "xterm-256color".  Returns the same values as
-		|jobstart()|.
+termopen({cmd}[, {opts}])			{Nvim} *termopen()*
+		Spawns {cmd} in a new pseudo-terminal session connected
+		to the current buffer. If {cmd} is a string, it will be
+		executed as "'shell' 'shellcmdflag' {cmd}".  This function
```
Comment (ZyX-I) [inline runtime/doc/eval.txt]: Missing “if {cmd} is a |List|” case.

File: src/nvim/eval.c [hunk 4]
```diff
@@ -10779,47 +10779,71 @@ static void f_jobresize(typval_T *argvars, typval_T *rettv)
...
-    return;
+  if (cmd->v_type == VAR_STRING) {
+    return shell_build_argv((char *)get_tv_string(cmd), NULL);
   }
 
-  if (argvars[0].v_type != VAR_LIST
-      || (argvars[1].v_type != VAR_DICT && argvars[1].v_type != VAR_UNKNOWN)) {
-    // Wrong argument types
+  if (cmd->v_type != VAR_LIST) {
     EMSG(_(e_invarg));
```
Comment (ZyX-I) [inline src/nvim/eval.c]: I would highly suggest to *never* use `e_invarg`. It is not telling the user what is the error: should be something `Exxx: Expected List or String`.

File: src/nvim/eval.c [hunk 5]
```diff
@@ -10779,47 +10779,71 @@ static void f_jobresize(typval_T *argvars, typval_T *rettv)
...
-    return;
+    return NULL;
   }
 
-  list_T *args = argvars[0].vval.v_list;
-  // Assert that all list items are strings
+  list_T *args = cmd->vval.v_list;
   for (listitem_T *arg = args->lv_first; arg != NULL; arg = arg->li_next) {
     if (arg->li_tv.v_type != VAR_STRING) {
       EMSG(_(e_invarg));
```
Comment (ZyX-I) [inline src/nvim/eval.c]: Same.

File: src/nvim/eval.c [hunk 6]
```diff
@@ -10779,47 +10779,71 @@ static void f_jobresize(typval_T *argvars, typval_T *rettv)
...
+  rettv->v_type = VAR_NUMBER;
+  rettv->vval.v_number = 0;
+
+  if (check_restricted() || check_secure()) {
     return;
   }
 
+  if (argvars[1].v_type != VAR_DICT && argvars[1].v_type != VAR_UNKNOWN) {
+    // Wrong argument types
+    EMSG(_(e_invarg));
```
Comment (ZyX-I) [inline src/nvim/eval.c]: Same.

File: test/functional/terminal/cursor_spec.lua [hunk 7]
```diff
@@ -144,7 +144,7 @@ describe('cursor with customized highlighting', function()
       [6] = {foreground = 130},
     })
     screen:attach(false)
-    execute('term "' ..nvim_dir.. '/tty-test"')
+    execute('call termopen(["' ..nvim_dir.. '/tty-test"]) | startinsert')
```
Comment (ZyX-I) [inline test/functional/terminal/cursor_spec.lua]: It is rather strange that `..nvim_dir..` is surrounded by spaces, but there are no spaces between both `..` and `nvim_dir`.

Comment (ZyX-I) [inline test/functional/terminal/cursor_spec.lua]: And same thing in other tests. Is this intentional?

File: runtime/doc/eval.txt (hunk 2 above)
Comment (splinterofchaos) [inline runtime/doc/eval.txt]: :+1:

File: runtime/doc/eval.txt (hunk 3 above)
Comment (splinterofchaos) [inline runtime/doc/eval.txt]: :+1:

File: src/nvim/eval.c (hunk 4 above)
Comment (splinterofchaos) [inline src/nvim/eval.c]: I moved the error checking down so that this gets caught by `get_tv_string`.

File: src/nvim/eval.c (hunk 5 above)
Comment (splinterofchaos) [inline src/nvim/eval.c]: :+1:

File: src/nvim/eval.c (hunk 6 above)
Comment (splinterofchaos) [inline src/nvim/eval.c]: Now:     EMSG(_(e_invarg2), "expected dictionary");`

File: test/functional/terminal/cursor_spec.lua (hunk 7 above)
Comment (splinterofchaos) [inline test/functional/terminal/cursor_spec.lua]: Thanks; a copy and paste error.

**Comment by splinterofchaos** [comment]
@jszakmeister, Is there a timeout on QuickBuild? I think this one's stuck in an infinite loop. Been running for over two hours. http://neovim-qb.szakmeister.net/build/564/overview

**Comment by splinterofchaos** [comment]
Rebased and squashed related commits together.

File: src/nvim/os/shell.c [hunk 8]
```diff
@@ -166,17 +168,16 @@ int os_call_shell(char_u *cmd, ShellOpts opts, char_u *extra_args)
...
               char **output,
               size_t *nread) FUNC_ATTR_NONNULL_ARG(1)
 {
-  return shell(cmd, NULL, input, len, output, nread, true, false);
+  return shell(argv, input, len, output, nread, true, false);
 }
 
-static int shell(const char *cmd,
-                 const char *extra_args,
+static int shell(char **argv,
```
Comment (bfredl) [inline src/nvim/os/shell.c]: I don't think this function should be called `shell` as it doesn't necessarily use the shell anymore. perhaps `call_argv` or `call_system` or something like that.

Comment (splinterofchaos) [inline src/nvim/os/shell.c]: :+1: -- I vote for `do_os_system()`.

**Comment by splinterofchaos** [comment]
Odd failure locally:
> ./test/functional/helpers.lua:135: attempt to perform arithmetic on local 'written' (a nil value)

From `request()` returning `nil` in `nvim_feed()`:
```lua
local function nvim_feed(input)
  while #input > 0 do
    local written = request('vim_input', input)
    input = input:sub(written + 1)
  end
end
```
Not sure why this would happen, but curious if travis will show the same.

**Comment by splinterofchaos** [comment]
OK, a memory error caused it. `do_os_system()` (was `shell()`) now copies `argv[0]` to a temporary buffer for error reporting. Inefficient, but nothing compared to spawning a new program.

File: runtime/doc/eval.txt [hunk 9]
```diff
@@ -4031,9 +4031,11 @@ jobsend({job}, {data})					{Nvim} *jobsend()*
 			:call jobsend(j, ["abc", "123\n456", ""])
 < 		will send "abc<NL>123<NUL>456<NL>".
 
-jobstart({argv}[, {opts}])			{Nvim} *jobstart()*
-		Spawns {argv}(list) as a job. If passed, {opts} must be a
-		dictionary with any of the following keys:
+jobstart({cmd}[, {opts}])				{Nvim} *jobstart()*
+		Spawns {cmd} as a job.  If {cmd} is a |String|, it will be ran
+		via "'shell' 'shellcmdflag' {cmd}", or directly if a |List|.
```
Comment (bfredl) [inline runtime/doc/eval.txt]: Perhaps remove the outer quotes here, it could be interpreted as we're concatenating a string here, but we're really building up an argument list.

File: runtime/doc/eval.txt [hunk 10]
```diff
@@ -6299,15 +6301,20 @@ tempname()					*tempname()* *temp-file-name*
...
-		if the current buffer is modified (all buffer contents are
-		destroyed).  The {opts} dict is similar to the one passed to
-		|jobstart()|, but the `pty`, `width`, `height`, and `TERM` fields are
-		ignored: `height`/`width` are taken from the current window and
-		$TERM is set to "xterm-256color".  Returns the same values as
-		|jobstart()|.
+termopen({cmd}[, {opts}])			{Nvim} *termopen()*
+		Spawns {cmd} in a new pseudo-terminal session connected
+		to the current buffer. If {cmd} is a |String|, it will be
+		executed as "'shell' 'shellcmdflag' {cmd}", otherwise if {cmd}
```
Comment (bfredl) [inline runtime/doc/eval.txt]: similarly here. Perhaps explicitly say something like "{cmd} is interpreted exactly like in |jobstart| " ?

File: runtime/doc/eval.txt [hunk 11]
```diff
@@ -6152,7 +6155,9 @@ synstack({lnum}, {col})					*synstack()*
 		valid positions.
 
 system({expr} [, {input}])				*system()* *E677*
```
Comment (bfredl) [inline runtime/doc/eval.txt]: perhaps should change first argument to `{cmd}` as it works the same as the `{cmd}` in `jobstart`. Even if the explanation is repeated, I think it also should point out that it works the same as `jobstart`. This way, it is easier to reason if it is a "safe" refactor to change between the functions.

File: src/nvim/os/shell.c [hunk 12]
```diff
@@ -119,14 +119,14 @@ int os_call_shell(char_u *cmd, ShellOpts opts, char_u *extra_args)
...
-  int status = shell((const char *)cmd,
-                     (const char *)extra_args,
-                     input.data,
-                     input.len,
-                     output_ptr,
-                     &nread,
-                     emsg_silent,
-                     forward_output);
+
+  int status = do_os_system(shell_build_argv((char *)cmd, (char *)extra_args),
```
Comment (bfredl) [inline src/nvim/os/shell.c]: Not really related to this PR, but if I haven't missed something it looks like `extra_args` is only ever used in `mch_expand_wildcards`. Perhaps this function could be refactored  to manipulate the argv list directly, instead of complicating the entire `call_shell` `os_call_shell` `shell_build_argv` chain. (later, no need to do it in this PR).

**Comment by bfredl** [comment]
LGTM, just some comments on the documentation.

A further change could be to bring `rpcstart` into the fold, I see no point why it should have a different `rpcstart(arg0, [arg1, ...])` form.

File: runtime/doc/eval.txt (hunk 9 above)
Comment (splinterofchaos) [inline runtime/doc/eval.txt]: :+1:

File: runtime/doc/eval.txt (hunk 10 above)
Comment (splinterofchaos) [inline runtime/doc/eval.txt]: :+1:

File: runtime/doc/eval.txt (hunk 11 above)
Comment (splinterofchaos) [inline runtime/doc/eval.txt]: :+1: -- forgot about `system()`'s docs.

**Comment by splinterofchaos** [comment]
I opened issue #2463 to discuss whether `rpcstart`'s interface can change.

**Comment by bfredl** [comment]
Great work @splinterofchaos ! Perhaps this PR should be merged as-is as it currently has no backward-incompatible changes (right?) and already is very useful, and then a PR for #2463 (if no objections to that)

**Comment by tarruda** [comment]
LGTM, great work @splinterofchaos

File: src/nvim/eval.c [hunk 13]
```diff
@@ -10787,47 +10787,74 @@ static void f_jobresize(typval_T *argvars, typval_T *rettv)
...
-    if (arg->li_tv.v_type != VAR_STRING) {
-      EMSG(_(e_invarg));
-      return;
+    char *a = (char *)get_tv_string_chk(&arg->li_tv);
+    if (a == NULL) {
+      // Did emsg in get_tv_string; just deallocate argv.
+      while (i-- > 0) {
+        xfree(argv[i]);
+      }
+      return NULL;
```
Comment (oni-link) [inline src/nvim/eval.c]: `argv` is not freed.

File: runtime/doc/eval.txt [hunk 14]
```diff
@@ -4031,9 +4031,12 @@ jobsend({job}, {data})					{Nvim} *jobsend()*
 			:call jobsend(j, ["abc", "123\n456", ""])
 < 		will send "abc<NL>123<NUL>456<NL>".
 
-jobstart({argv}[, {opts}])			{Nvim} *jobstart()*
-		Spawns {argv}(list) as a job. If passed, {opts} must be a
-		dictionary with any of the following keys:
+jobstart({cmd}[, {opts}])				{Nvim} *jobstart()*
+		Spawns {cmd} as a job.  If {cmd} is a |List|, it will be run
+		director. If {cmd} is a |String|, it will be equivalent to >
```
Comment (oni-link) [inline runtime/doc/eval.txt]: What does `it will be run director` mean?

Comment (tarruda) [inline runtime/doc/eval.txt]: `it will be run directly`(passed to the operating system process spawning function)

File: src/nvim/eval.c [hunk 15]
```diff
@@ -10787,47 +10787,74 @@ static void f_jobresize(typval_T *argvars, typval_T *rettv)
...
-  if (!os_can_exe(exe, NULL)) {
-    // String is not executable
-    EMSG2(e_jobexe, exe);
+  if (argvars[1].v_type != VAR_DICT && argvars[1].v_type != VAR_UNKNOWN) {
+    // Wrong argument types
+    EMSG2(_(e_invarg2), "expected dictionary");
     return;
   }
 
+  char **argv = tv_to_argv(&argvars[0]);
```
Comment (oni-link) [inline src/nvim/eval.c]: Just wondering, don't we check arguments in order, so that the first error message we see is for the first wrong argument?

Comment (tarruda) [inline src/nvim/eval.c]: Maybe refactor `tv_to_argv` so it receives a `char **` out parameter with the command name?

File: src/nvim/eval.c [hunk 16]
```diff
@@ -15195,10 +15222,18 @@ static void f_termopen(typval_T *argvars, typval_T *rettv)
     cwd = (char *)argvars[1].vval.v_string;
   }
   int pid = job_pid(job);
+
+  // Get the desired name of the buffer.
+  char *name = job_opts ?
+    (char *)get_dict_string(job_opts, (char_u *)"name", false) : NULL;
+  if (!name) {
+    typval_T *name_tv = (argvars[0].v_type == VAR_LIST) ?
```
Comment (oni-link) [inline src/nvim/eval.c]: Can't we use `argv` to get the name?

File: runtime/doc/eval.txt (hunk 14 above)
Comment (splinterofchaos) [inline runtime/doc/eval.txt]: :+1:  -- typo

File: src/nvim/eval.c (hunk 13 above)
Comment (splinterofchaos) [inline src/nvim/eval.c]: :+1:

File: src/nvim/eval.c (hunk 15 above)
Comment (splinterofchaos) [inline src/nvim/eval.c]: That simplified `termopen()`, but did you have something in mind for `jobstart()`?

File: src/nvim/eval.c [hunk 17]
```diff
@@ -10787,44 +10787,79 @@ static void f_jobresize(typval_T *argvars, typval_T *rettv)
...
+  }
+  
+  // Build the argument vector
+  int i = 0;
+  char **argv = xcalloc(argc + 1, sizeof(char *));
+  for (listitem_T *arg = argl->lv_first; arg != NULL; arg = arg->li_next) {
+    char *a = (char *)get_tv_string_chk(&arg->li_tv);
+    if (a == NULL) {
+      // Did emsg in get_tv_string; just deallocate argv.
+      argv[i] = NULL;
```
Comment (oni-link) [inline src/nvim/eval.c]: All entries in `argv` started to be `NULL`, so this could be removed.

Comment (splinterofchaos) [inline src/nvim/eval.c]: :+1:

File: runtime/doc/eval.txt [hunk 18]
```diff
@@ -4052,7 +4055,8 @@ jobstart({argv}[, {opts}])			{Nvim} *jobstart()*
 		  - The job ID on success, which is used by |jobsend()| and
 		    |jobstop()|
 		  - 0 when the job table is full or on invalid arguments
-		  - -1 when {argv}[0] is not executable
+		  - -1 when {cmd}[0] is not executable. (Will never fail if
+		    {cmd} is a string unless 'shell' is not executable.)
```
Comment (Pyrohh) [inline runtime/doc/eval.txt]: It seems odd to have a sentence inside parentheses, maybe remove the parens? also there should be two spaces after period.

File: runtime/doc/eval.txt [hunk 19]
```diff
@@ -6151,9 +6155,10 @@ synstack({lnum}, {col})					*synstack()*
 		character in a line and the first column in an empty line are
 		valid positions.
 
-system({expr} [, {input}])				*system()* *E677*
-		Get the output of the shell command {expr} as a string.  See
-		|systemlist()| to get the output as a List.
+system({cmd} [, {input}])				*system()* *E677*
+		Get the output of the shell command {cmd} as a string.  {cmd}
+		will be run the same as in |jobstart()|.  See |systemlist()|
+		to get the output as a List.
```
Comment (Pyrohh) [inline runtime/doc/eval.txt]: Maybe `List` should be `|List|`, like `|String|` above.

File: runtime/doc/eval.txt [hunk 20]
```diff
@@ -6182,11 +6187,8 @@ system({expr} [, {input}])				*system()* *E677*
 		To avoid the string being truncated at a NUL, all NUL
 		characters are replaced with SOH (0x01).
 
-		The command executed is constructed using several options:
-	'shell' 'shellcmdflag' 'shellxquote' {expr} 'shellredir' {tmp} 'shellxquote'
-		({tmp} is an automatically generated file name).
-		For Unix braces are put around {expr} to allow for
-		concatenated commands.
+		The command executed is constructed using several options when
+		{expr} is a string: 'shell' 'shellcmdflag' {expr}
```
Comment (Pyrohh) [inline runtime/doc/eval.txt]: should be `{cmd}`

Comment (Pyrohh) [inline runtime/doc/eval.txt]: same with line 6175

File: runtime/doc/eval.txt [hunk 21]
```diff
@@ -6299,15 +6301,18 @@ tempname()					*tempname()* *temp-file-name*
...
-		session connected to the current buffer.  This function fails
-		if the current buffer is modified (all buffer contents are
-		destroyed).  The {opts} dict is similar to the one passed to
-		|jobstart()|, but the `pty`, `width`, `height`, and `TERM` fields are
-		ignored: `height`/`width` are taken from the current window and
-		$TERM is set to "xterm-256color".  Returns the same values as
-		|jobstart()|.
+termopen({cmd}[, {opts}])			{Nvim} *termopen()*
+		Spawns {cmd} in a new pseudo-terminal session connected
+		to the current buffer. {cmd} is the same as the one passed to
```
Comment (Pyrohh) [inline runtime/doc/eval.txt]: two spaces after period

File: runtime/doc/eval.txt [hunk 22]
```diff
@@ -6299,15 +6301,18 @@ tempname()					*tempname()* *temp-file-name*
...
+		|jobstart()|.  This function fails if the current buffer is
+		modified (all buffer contents are destroyed).
+
+		The {opts} dict is similar to the one passed to |jobstart()|,
+		but the `pty`, `width`, `height`, and `TERM` fields are
+		ignored: `height`/`width` are taken from the current window
+		and `$TERM` is set to "xterm-256color".  An additional option,
+		`name`, can be used to give the terminal a specific name.
```
Comment (Pyrohh) [inline runtime/doc/eval.txt]: Maybe ```... "xterm-256color". If `name` is specified, the teminal's name is set to `name`.```

File: runtime/doc/various.txt [hunk 23]
```diff
@@ -226,10 +226,17 @@ g8			Print the hex values of the bytes used in the
...
+                        equivalent to: >
 
-			      :enew | call termopen('{cmd}') | startinsert
+			      :enew
+			      :call termopen([&sh, &shcf, '{cmd}'],
+                                              \{'name':'{cmd}'})
+			      :startinsert
 <
+                        If no {command} is given, 'shellcmdflag' will not be
+                        sent to |termopen()|.
```
Comment (Pyrohh) [inline runtime/doc/various.txt]: should be tabs, not spaces

File: runtime/doc/various.txt [hunk 24]
```diff
@@ -226,10 +226,17 @@ g8			Print the hex values of the bytes used in the
 
 						  *:term* *:terminal*
 :term[inal][!] {cmd}	Spawns {command} using the current value of 'shell'
-			in a new terminal buffer.  This is equivalent to: >
+                        and 'shellcmdflag' in a new terminal buffer.  This is
+                        equivalent to: >
```
Comment (Pyrohh) [inline runtime/doc/various.txt]: should be tabs, not spaces

File: runtime/doc/eval.txt [hunk 25]
```diff
@@ -4031,9 +4031,12 @@ jobsend({job}, {data})					{Nvim} *jobsend()*
 			:call jobsend(j, ["abc", "123\n456", ""])
 < 		will send "abc<NL>123<NUL>456<NL>".
 
-jobstart({argv}[, {opts}])			{Nvim} *jobstart()*
-		Spawns {argv}(list) as a job. If passed, {opts} must be a
-		dictionary with any of the following keys:
+jobstart({cmd}[, {opts}])				{Nvim} *jobstart()*
+		Spawns {cmd} as a job.  If {cmd} is a |List|, it will be run
+		directly.  If {cmd} is a |String|, it will be equivalent to >
```
Comment (Pyrohh) [inline runtime/doc/eval.txt]: The actual help option is `|string|`, so this should either be changed to that, or `*string*` in `eval.txt` should have `*String*` added next to it for consistency with `*List*` and `*list*`.

File: src/nvim/eval.c [hunk 26]
```diff
@@ -10778,44 +10778,78 @@ static void f_jobresize(typval_T *argvars, typval_T *rettv)
...
 
-// "jobstart()" function
-static void f_jobstart(typval_T *argvars, typval_T *rettv)
+static char **tv_to_argv(typval_T *cmd_tv, char **cmd)
 {
-  rettv->v_type = VAR_NUMBER;
-  rettv->vval.v_number = 0;
+  if (cmd_tv->v_type == VAR_STRING) {
+    char *cmd_str = (char *)get_tv_string(cmd_tv);
+    if (cmd) {
```
Comment (Pyrohh) [inline src/nvim/eval.c]: Explicit comparisons with null are used below, so it's probably a good idea to be consistent about it.

File: src/nvim/eval.c [hunk 27]
```diff
@@ -10778,44 +10778,78 @@ static void f_jobresize(typval_T *argvars, typval_T *rettv)
...
   }
 
-  if (argvars[0].v_type != VAR_LIST
-      || (argvars[1].v_type != VAR_DICT && argvars[1].v_type != VAR_UNKNOWN)) {
-    // Wrong argument types
-    EMSG(_(e_invarg));
-    return;
+  list_T *argl = cmd_tv->vval.v_list;
+  int argc = argl->lv_len;
+  if (!argc) {
```
Comment (Pyrohh) [inline src/nvim/eval.c]: See above comment.

File: runtime/doc/eval.txt (hunk 22 above)
Comment (splinterofchaos) [inline runtime/doc/eval.txt]: I feel that `'name'` must be noted as being unique to `termopen()`, I changed it to:
> "xterm-256color", and it may have a
		`name` field.  `name`, if present, sets the buffer's name to
		"term://{cwd}/{pid}:{name}".
		Returns the same values as |jobstart()|.

File: src/nvim/eval.c (hunk 26 above)
Comment (splinterofchaos) [inline src/nvim/eval.c]: :+1: -- This function has many `NULL` comparisons. I decided to just change the explicit tests to implicite.

File: src/nvim/eval.c (hunk 27 above)
Comment (splinterofchaos) [inline src/nvim/eval.c]: :+1:

File: runtime/doc/eval.txt (hunk 18 above)
Comment (splinterofchaos) [inline runtime/doc/eval.txt]: :+1:

File: runtime/doc/eval.txt (hunk 19 above)
Comment (splinterofchaos) [inline runtime/doc/eval.txt]: :+1:

File: runtime/doc/eval.txt (hunk 20 above)
Comment (splinterofchaos) [inline runtime/doc/eval.txt]: :+1:

File: runtime/doc/eval.txt (hunk 21 above)
Comment (splinterofchaos) [inline runtime/doc/eval.txt]: :+1:

File: runtime/doc/various.txt (hunk 23 above)
Comment (splinterofchaos) [inline runtime/doc/various.txt]: :+1:

File: runtime/doc/various.txt (hunk 24 above)
Comment (splinterofchaos) [inline runtime/doc/various.txt]: :+1:

**Comment by splinterofchaos** [comment]
Rebased and made the code a little more consistent. Thanks @Pyrohh.

**Comment by Pyrohh** [comment]
Thanks @splinterofchaos. Given @tarruda and @bfredl both said LGTM already, I'd imagine this can be merged (assuming you think so as well).

File: runtime/doc/eval.txt [hunk 28]
```diff
@@ -6299,15 +6301,19 @@ tempname()					*tempname()* *temp-file-name*
...
-		destroyed).  The {opts} dict is similar to the one passed to
-		|jobstart()|, but the `pty`, `width`, `height`, and `TERM` fields are
-		ignored: `height`/`width` are taken from the current window and
-		$TERM is set to "xterm-256color".  Returns the same values as
-		|jobstart()|.
+termopen({cmd}[, {opts}])			{Nvim} *termopen()*
+		Spawns {cmd} in a new pseudo-terminal session connected
+		to the current buffer.  {cmd} is the same as the one passed to
+		|jobstart()|.  This function fails if the current buffer is
+		modified (all buffer contents are destroyed).
```
Comment (justinmk) [inline runtime/doc/eval.txt]: This comment is bizarre. Are the buffer contents replaced, or in fact a new buffer is created, which *may* causes loss of unsaved changes in the case of `set nohidden`?

Comment (justinmk) [inline runtime/doc/eval.txt]: Oh, actually it's the function behavior that's bizarre. Why do we replace the current buffer with a `term:` buffer instead of creating a *new* buffer?

File: runtime/doc/eval.txt [hunk 29]
```diff
@@ -6299,15 +6301,19 @@ tempname()					*tempname()* *temp-file-name*
...
+
+		The {opts} dict is similar to the one passed to |jobstart()|,
+		but the `pty`, `width`, `height`, and `TERM` fields are
+		ignored: `height`/`width` are taken from the current window
```
Comment (justinmk) [inline runtime/doc/eval.txt]: Why are ``pty`, `width`, `height`, and `TERM`` ignored?

File: runtime/doc/various.txt [hunk 30]
```diff
@@ -224,10 +224,17 @@ g8			Print the hex values of the bytes used in the
 
 						  *:term* *:terminal*
 :term[inal][!] {cmd}	Spawns {command} using the current value of 'shell'
```
Comment (justinmk) [inline runtime/doc/various.txt]: This should be `{cmd}`

File: runtime/doc/various.txt [hunk 31]
```diff
@@ -224,10 +224,17 @@ g8			Print the hex values of the bytes used in the
...
+			and 'shellcmdflag' in a new terminal buffer.  This is
+			equivalent to: >
 
-			      :enew | call termopen('{cmd}') | startinsert
+			      :enew
+			      :call termopen([&sh, &shcf, '{cmd}'],
+			                    \{'name':'{cmd}'})
+			      :startinsert
 <
+			If no {command} is given, 'shellcmdflag' will not be
```
Comment (justinmk) [inline runtime/doc/various.txt]: {command} => {cmd}

File: runtime/doc/eval.txt (hunk 28 above)
Comment (splinterofchaos) [inline runtime/doc/eval.txt]: At least the first part of that relates #2368. `f_termopen()` has
```c
  if (curbuf->b_changed) {
    EMSG(_("Can only call this function in an unmodified buffer"));
    return;
  }
```
to protect against destroying modified buffers, but doesn't hide it. Also, some reading of code using `b_changed` suggested to me that this check might be insufficient. This causes #2408 because of a static variable in `syntax.c` not getting updated.

`termopen` definitely still needs some work, but I want to save that for another PR so I can get this merged.

**Comment by splinterofchaos** [comment]
I'll mark this RDY, but will wait until tomorrow in case anyone has a last minute comment.

File: runtime/doc/eval.txt (hunk 29 above)
Comment (splinterofchaos) [inline runtime/doc/eval.txt]: I can't think of a use case for setting a custom `'height'`, but perhaps `'width'` could be set to the maximum of the buffer's width and the given number so that long commands/output get linewrapped. I seem to remember someone opening an issue about this, but I can't find it.

I'd like to save that for another PR, though. I haven't modified that code.

File: src/nvim/eval.c [hunk 32]
```diff
@@ -10779,44 +10779,78 @@ static void f_jobresize(typval_T *argvars, typval_T *rettv)
...
-      return;
+  assert(argl->lv_first);
+
+  const char_u *exe = get_tv_string_chk(&argl->lv_first->li_tv);
+  if (!exe || !os_can_exe(exe, NULL)) {
+    // String is not executable
+    if (exe) {
+      EMSG2(e_jobexe, exe);
     }
+    return NULL;
```
Comment (justinmk) [inline src/nvim/eval.c]: if `!exe`, we return NULL without an error message.

File: runtime/doc/various.txt (hunk 31 above)
Comment (splinterofchaos) [inline runtime/doc/various.txt]: This happens when `{cmd}` is not specified, so it's equivalent to
```vim
enew
call termopen(&shell, {'name' : &shell)
startinsert
```
but after looking `ex_terminal` over, it doesn't look like I correctly do that.  Now fixed.

File: runtime/doc/various.txt (hunk 30 above)
Comment (splinterofchaos) [inline runtime/doc/various.txt]: :+1:

File: src/nvim/ex_docmd.c [hunk 33]
```diff
@@ -9409,9 +9409,20 @@ static void ex_folddo(exarg_T *eap)
 
 static void ex_terminal(exarg_T *eap)
 {
-  char cmd[512];
-  snprintf(cmd, sizeof(cmd), ":enew%s | call termopen('%s') | startinsert",
-      eap->forceit==TRUE ? "!" : "",
-      strcmp((char *)eap->arg, "") ? (char *)eap->arg : (char *)p_sh);
-  do_cmdline_cmd((uint8_t *)cmd);
+  // We will call `termopen()` will `[&shell]` if given a {cmd}.
```
Comment (justinmk) [inline src/nvim/ex_docmd.c]: will => with

Comment (splinterofchaos) [inline src/nvim/ex_docmd.c]: The brackets denote that we send it as a list, but using `'shell'` instead of `&shell` does seem to make sense.

**Comment by splinterofchaos** [comment]
@justinmk, have I satisfied your concerns?

**Comment by justinmk** [comment]
LGTM
