### PR TITLE
fix(api): do not update grid position in nvim_win_set_cursor

### LINKED ISSUE #28023: Cursor is blinking when using `nvim_win_set_cursor` in another window
### Problem

I'm implementing autoscroll feature for Test Explorer which updates very often. Scrolling this window causes blinking of the cursor:

https://github.com/neovim/neovim/assets/3128467/6b7997cd-c79f-4771-a5c7-ce920eeca183

### Steps to reproduce

```
---Autoscrolls the cursor to the provided row.
---@param row number|nil
local function autoscroll_cursor(row)
  local winnr = M.bufnr and vim.fn.win_findbuf(M.bufnr)[1]

  if winnr and config.cursor_follows_tests and row and last_set_cursor_row ~= row then
    -- V1
    -- vim.api.nvim_win_call(winnr, function()
    --   vim.cmd(tostring(row))
    --   last_set_cursor_row = row
    -- end)

    -- V2
    vim.api.nvim_win_set_cursor(winnr, { row, 0 })
    last_set_cursor_row = row
  end
end
```

I tried both approaches `V1` and `V2` and it happens for both.

### Expected behavior

Cursor should not blink

### Neovim version (nvim -v)

v0.9.5 and v0.10.0

### Vim (not Nvim) behaves the same?

-

### Operating system/version

macOS 14.4

### Terminal name/version

iTerm 2

### $TERM environment variable

xterm-256

### Installation

Homebrew/source code

### PR DESCRIPTION
**Pull request by luukvbaal**
Revert commit c971f538ab87b537ae4c97bd44167661c5691a2d.
Forcing grid cursor position will need a new API like originally proposed in #27858.

### CODE REVIEW

File: test/functional/api/window_spec.lua [hunk 1]
```diff
@@ -220,8 +220,22 @@ describe('API/win', function()
       -- curwin didn't change back
       neq(win, curwin())
 
-      -- shows updated position after getchar() #20793
+      -- does not show updated position after getchar() in non-current window
```
Comment (zeertzjq) [inline test/functional/api/window_spec.lua:223]: What does "getchar() in non-current window" mean?

Comment (luukvbaal) [reply test/functional/api/window_spec.lua:223]: Wrong word ordering. It's the cursor that's set in a non-current window(after a getchar()).

**Comment by echasnovski** [comment]
I can confirm that it fixes [this issue](https://github.com/neovim/neovim/pull/27858#issuecomment-2043317842) (at least for 'mini.clue').
