### PR TITLE
fix(lsp): delete b:lsp_floating_preview buf var after win close

### LINKED ISSUE #31289: LSP: `b:lsp_floating_preview` should be unset after closing the associated floating window
### Problem

I was trying to create a command that changes its behavior based on whether hover information is already displayed in a floating window.

I tried to check if such a floating window exists by verifying whether the buffer-local variable `lsp_floating_preview` is defined, but it didn't work. This is because this variable is not unset after the floating window is closed. It works the first time, but on the second and subsequent attempts, it doesn't work because the variable exists even when a floating window is not present.

I ran into this problem when dealing with `textDocument/hover`, but all functions that use `vim.lsp.util.open_floating_preview(...)` (which declares `lsp_floating_preview`) should have the same problem.

### Steps to reproduce using "nvim -u minimal_init.lua"

minimal_init.lua:

```lua
local pattern = "rust"
local cmd = { "rust-analyzer" }
local root_markers = { "Cargo.toml" }
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd(
    "FileType", {
        pattern = pattern,
        callback = function(args)
            local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
            local root_dir = match and vim.fn.fnamemodify(match, ":p:h") or nil
            vim.lsp.start {
                name = "rust-analyzer",
                cmd = cmd,
                root_dir = root_dir,
                settings = settings,
            }
        end,
    }
)
```

src/main.rs:

```rust
fn main() {
    println!("Hello, world!");
}
```

1. Create a new rust project: `cargo new sample; cd sample`
    This will create `src/main.rs` shown above.
    I used a Rust project, but it should be reproducible with a project in another programming language as long as it has an LSP server that supports `textDocument/hover`.
2. Start a Neovim session: `nvim -u <path to minimal_init.lua> src/main.rs`
3. Run `:lua vim.lsp.buf.hover()`.
    The cursor can be located anywhere that has hover information. 
    I didn't move the cursor at all in my case.
4. Wait until indexing is complete and a floating window appears.
5. Run `:only` to close the floating window.
6. Check if `b:lsp_floating_preview` exists: `:echo b:lsp_floating_preview`
    - expected: `Undefined variable: b:lsp_floating_preview`
    - actual: `1002`

### Expected behavior

`b:lsp_floating_preview` should be unset after the window created by `vim.lsp.util.open_floating_preview()` is closed.

### Nvim version (nvim -v)

v0.10.2

### Language server name/version

rust-analyzer 1.82.0

### Operating system/version

Ubuntu 22.04

### Log file

_No response_

### PR DESCRIPTION
**Pull request by glepnir**
Problem: After floating preview window closed the buf var still exist

Solution: delete  after floating window closed.

Fix #31289

### CODE REVIEW

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -1344,6 +1344,10 @@ local function close_preview_window(winnr, bufnrs)
 
     local augroup = 'preview_window_' .. winnr
     pcall(api.nvim_del_augroup_by_name, augroup)
+    local ok, buf = pcall(api.nvim_win_get_var, winnr, 'buf_hold_win')
```
Comment (lewis6991) [inline runtime/lua/vim/lsp/util.lua:1347]: Prefer using `vim.w` and `vim.b`.

```suggestion
    local buf = vim.w[winnr].buf_hold_win
    if buf then
      vim.b[buf].lsp_floating_window = nil
    end
```

File: runtime/lua/vim/lsp/util.lua [hunk 2]
```diff
@@ -1609,6 +1613,7 @@ function M.open_floating_preview(contents, syntax, opts)
       { silent = true, noremap = true, nowait = true }
     )
     close_preview_autocmd(opts.close_events, floating_winnr, { floating_bufnr, bufnr })
+    api.nvim_win_set_var(floating_winnr, 'buf_hold_win', bufnr)
```
Comment (lewis6991) [inline runtime/lua/vim/lsp/util.lua:1616]:
```suggestion
    vim.w[floating_winnr].buf_hold_win = bufnr
```

**Review by lewis6991 — APPROVED** [review]

File: runtime/lua/vim/lsp/util.lua [hunk 3]
```diff
@@ -1344,6 +1344,13 @@ local function close_preview_window(winnr, bufnrs)
 
     local augroup = 'preview_window_' .. winnr
     pcall(api.nvim_del_augroup_by_name, augroup)
+    local buf = vim.w[winnr].buf_hold_win
+    if buf then
+      vim.b[buf].lsp_floating_window = nil
+    end
+    if ok then
+      api.nvim_buf_del_var(buf, 'lsp_floating_preview')
+    end
```
[the remark this answers is not in the document]
Comment (glepnir) [reply runtime/lua/vim/lsp/util.lua:1353]: another thing is need check buf is valid because there is run into next event loop
