### PR TITLE
[RFC] terminal: Handle loss of focus in event loop.

### LINKED ISSUE #2301: [terminal-emulation] Segfault while in t-mode
*Steps to reproduce:* After executing `:terminal` (do not leave terminal-insert-mode), connect using python-client and execute `vs {file}` using rpc, then leave t-mode (using `<C-\><C-n>`) and bang!

*Use case:* open files in the current nvim session from a terminal running inside it.
`~/open.py` file:
```
#!/bin/python2

import os
def main(nvim_listen_addr, *files):
    from neovim import attach
    nvim = attach('socket', path=nvim_listen_addr)
    for f in files:
        nvim.command('vs ' + os.path.abspath(f))

if __name__ == '__main__':
    import sys
    main(os.environ['NVIM_LISTEN_ADDRESS'], *sys.argv[1:])
```

From nvim, execute `:terminal`, then `~/open.py {file}`
The window splits fine but when you leave t-mode, it segfaults.

*Note:* If you use `'badd '` instead of `'vs '`, there won't be a problem...

*PS:* Awesome features, you guys! I'm speechless!

### PR DESCRIPTION
**Pull request by splinterofchaos**
While in a terminal and insert mode, if an aucmd or event caused loss of focus, nvim would stay in the terminal event loop causing an inconsistent view of internal state and/or segfault.

Remove the "term" argument from terminal_enter() as it only makes sense to call it with curbuf->terminal. Terminate the loop either when focus is lost or the terminal closes.

~~Implement redraw() in terms of the pointer...~~

fixes #2301

@tarruda, for `terminal_enter()`, I notice that it has only one call site, and that `process_deferred` is unconditionally true. Do or will we need this to be called with `process_deferred=false` at any point, or can we simplify this?

### CODE REVIEW

**Comment by splinterofchaos** [comment]
Running `build/bin/tty-test` shows that my logic is a little off, so moving this back to WIP. Also, some of the output I got through the travis test is a little nonsensical.

File: test/functional/terminal/buffer_spec.lua [hunk 1]
```diff
@@ -155,5 +157,42 @@ describe('terminal buffer', function()
...
+    -- We should be in a new buffer now.
+    screen:expect([[
+      ^                                                  |
+      ~                                                 |
+      +++                                               |
+      rows: 2, cols: 50++                               |
+      {2: }                                                 |
+      {1:+++                                               }|
+                                                        |
+    ]])
```
Comment (splinterofchaos) [inline test/functional/terminal/buffer_spec.lua]: One outstanding issue: event when I put `execute('set noruler')`, that `rows: 2, cols: 50` shows up, and if the `statusline` is longer than one character, all but the first get appended after the `cols: 50`.

Otherwise, this is basically the output I expect.

**Comment by splinterofchaos** [comment]
Failed on the quick-build tests, but I'm afraid I don't understand how to see the error.

**Comment by splinterofchaos** [comment]
Marking RFC because I got the tests working,

Also, I noticed that if the user typed `<C-\>` and then either a mouse click or lost focus, the mouse click would be sent as a keyboard press, so I added a commit that lets us keep listening for `<C-\><C-n>`, but allows mouse presses and `K_EVENT`s as well.

**Comment by splinterofchaos** [comment]
Added a commit for #2317 (miscalculated terminal width), though I'm not quite sure how to test it except manually.

File: src/nvim/terminal.c [hunk 2]
```diff
@@ -353,8 +353,14 @@ void terminal_resize(Terminal *term, uint16_t width, uint16_t height)
   invalidate_terminal(term, -1, -1);
 }
 
-void terminal_enter(Terminal *term, bool process_deferred)
+void terminal_enter(bool process_deferred)
 {
+  Terminal *term = curbuf->terminal;
+  assert(term && "should only be called when curbuf has a terminal");
```
Comment (philix) [inline src/nvim/terminal.c]: What if you pass the buffer to `terminal_enter` instead of relying on the `curbuf` global? You can move the `assert` up on the call chain and handle the error (or totally avoid it) in a better way.

I see that the terminal also has a reference to the buffer. Maybe this is a sign that most the function should actually take the buffer as argument. @tarruda may have his reasons.

File: src/nvim/terminal.c [hunk 3]
```diff
@@ -413,12 +413,22 @@ void terminal_enter(Terminal *term, bool process_deferred)
         event_process();
         break;
 
+      case Ctrl_N:
+        if (got_bs) {
+          goto end;
```
Comment (tarruda) [inline src/nvim/terminal.c]: Won't this result in `<c-n><c-\><c-n>` exiting terminal focus?

File: src/nvim/terminal.c (hunk 2 above)
Comment (tarruda) [inline src/nvim/terminal.c]: > I see that the terminal also has a reference to the buffer. Maybe this is a sign that most the function should actually take the buffer as argument.

Yes, a `Terminal` is always tied to a `buf_T`. And since `buf_T->terminal` is used to distinguish normal buffers from terminal buffers, I guess it makes sense to refactor most functions in this module to receive buffers, thus avoiding the need for cyclic references(In another PR, of course)

Comment (splinterofchaos) [inline src/nvim/terminal.c]: I did it like this because, if I understand the event loop correctly, we have to exit when `curbuf->terminal != term` or `term->buf != curbuf`, so even if `terminal_enter()` takes a `buf_T` argument, we'd have to assert `buf == curbuf && buf->terminal`.

Comment (tarruda) [inline src/nvim/terminal.c]: > I did it like this because, if I understand the event loop correctly, we have to exit when curbuf->terminal != term or term->buf != curbuf, so even if terminal_enter() takes a buf_T argument, we'd have to assert buf == curbuf && buf->terminal.

:+1: for `terminal_enter` this makes sense(little gain in keeping the parameter since we still depend on the global)

**Comment by splinterofchaos** [comment]
I don't think I'll be adding anything more to this right now. The last commit, "term: ensure term->buf is valid", I don't think is a good permanent solution (see the TODO), but it at least prevents memory errors when the terminal's buffer is unexpectedly deleted, or the other way around.

**Comment by philix** [comment]
LGTM although I'm not familiar with the terminal code.

**Comment by tarruda** [comment]
:+1: LGTM. Great work @splinterofchaos, and thanks for taking some of the terminal bugs off my back :smile:

**Comment by Pyrohh** [comment]
@splinterofchaos It's probably not a big deal, but next time you merge could you do it locally? Since these commits weren't very recently rebased, the merge commit is shown as the most recent commit, but you have to scroll down a bunch to see the rest of the commits. @justinmk presumably still uses these two shell functions to automate the process:

https://github.com/justinmk/config/blob/master/.bashrc#L222

**Comment by splinterofchaos** [comment]
Sorry, yes I should have rebased. I'll make sure to do so in the future. Thanks.
