### PR TITLE
fix(diagnostic): virtual_lines should anchor at end_lnum, not lnum

### LINKED ISSUE #38685: lnum rather than end_lnum not used for virtual_lines
### Problem

I'm using diagnostics to highlight github review comments.  GitHub review comments span from a range of lines (sometimes).  I'm then rendering those using virtual_lines.  I was surprised that the lines rendered under the first line of the diagnostic, and not under the end_lnum.

### Steps to reproduce

```
-- init.lua
vim.opt.number = true
vim.diagnostic.config({
  virtual_lines = true,
  underline = true,
  signs = true,
})
```

```
-- setdiag.lua
local ns = vim.api.nvim_create_namespace('repro')
vim.diagnostic.set(ns, 0, {{
  lnum = 3,      -- 0-indexed: line 4 (range start)
  end_lnum = 9,  -- 0-indexed: line 10 (range end)
  col = 0,
  message = "This comment is about lines 4-10, but renders at line 4",
  severity = vim.diagnostic.severity.WARN,
  source = 'review',
}})
```

```
line 1
line 2
line 3
line 4 -- range starts here
line 5
line 6
line 7
line 8
line 9
line 10 -- range ends here, comment should anchor here
line 11
line 12
```

then run: `nvim '+source setdiag.lua' -u init.lua example.txt`

### Expected behavior

I was expecting to see the virtual lines _after_ end_lnum

### Nvim version (nvim -v)

NVIM v0.12.0

### Vim (not Nvim) behaves the same?

I assume vim doesn't have diagnostics?

### Operating system/version

macOS 26.4 

### Terminal name/version

kitty 0.43.1 created by Kovid Goyal

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### PR DESCRIPTION
**Pull request by glepnir**
Problem: Multi-line diagnostics always render virtual lines below lnum.

Solution: Use end_lnum when placing the virt_lines extmark.

Fix #38685

### CODE REVIEW

File: test/functional/lua/diagnostic_spec.lua [hunk 1]
```diff
@@ -2578,6 +2578,35 @@ describe('vim.diagnostic', function()
       end)
       eq({ 'c', 'b', 'a' }, result)
     end)
+
+    it('anchors virtual lines at end_lnum for multi-line diagnostics #38685', function()
```
Comment (justinmk) [inline test/functional/lua/diagnostic_spec.lua]: why is a new test needed? this bug seems like something that should have been caught by an existing test, i.e. can we modify the existing test to have multiline diagnostics?
