### PR TITLE
Make mode() return correct value in ex mode

### LINKED ISSUE #16981: Under nvim -e, mode(1) returns incorrect value
### Neovim version (nvim -v)

v0.6.1

### Vim (not Nvim) behaves the same?

no, Vim 8.2.3995

### Operating system/version

Debian unstable/amd64

### Terminal name/version

tmux 3.2a on mate-terminal

### $TERM environment variable

tmux-direct

### Installation

Debian repositories

### How to reproduce the issue

nvim -e
:echo mode(1)

### Expected behavior

The result should be `cv` (documented behavior) or `ce` (Vim's behavior).  In such a case, my configuration should disable loading the colorscheme, since a TTY might be missing.

### Actual behavior

The value is `n` (normal mode), but I am not in normal mode.  As a result, my colorscheme is loaded.

### PR DESCRIPTION
**Pull request by bk2204**
When the user is in ex mode, a call to `mode(1)` is documented to return "cv".  However, it does not currently do so, because the check which checks for ex mode is nested inside a conditional which is never reached in ex mode.  Vim uses an explicit check for `exmode_active`, so let's do the same thing here.  Add some tests for this case both with a TTY and in silent mode.

Fixes #16981

### CODE REVIEW

**Comment by zeertzjq** [comment]
Look like this fixes a regression from #14311

**Comment by zeertzjq** [comment]
@bfredl previously stated that this is redundant logic, but this is actually not.

File: test/functional/core/startup_spec.lua [hunk 1]
```diff
@@ -224,6 +224,23 @@ describe('startup', function()
...
+    local screen = Screen.new(25, 3)
+    clear('-e')
+    screen:attach()
+    -- Verify we set the proper mode both before and after :vi.
+    feed("put =mode(1)<CR>vi<CR>:put =mode(1)<CR>")
+    screen:expect{[[
+      cv                       |
+      ^n                        |
+      :put =mode(1)            |
+    ]]}
```
Comment (zeertzjq) [inline test/functional/core/startup_spec.lua:237]:
```suggestion
    screen:expect([[
      cv                       |
      ^n                        |
      :put =mode(1)            |
    ]])
```

Comment (bk2204) [reply test/functional/core/startup_spec.lua]: Thanks.  I've squashed that into the commit.

**Comment by zeertzjq** [comment]
I think the reason why the `|| exmode_active` is not redundant is that like `State` does not contain `CMDLINE` when printing messages.

**Review by bfredl — APPROVED** [review]
yes, looks like ex mode commands execute in "normal" State, so this should be changed back.
