### PR TITLE
[RFC] cmdline: always use save_cmdline before command_line_enter

### LINKED ISSUE #8857: Press ':' right at startup breaks neovim
- `nvim --version`:
```
NVIM v0.3.2-261-gf767cee10
Build type: Debug
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -I/home/void/neovim/build/config -I/home/void/neovim/src -I/usr/include -I/home/void/neovim/build/src/nvim/auto -I/home/void/neovim/build/include
Compiled by void@node-a0

Features: +acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Terminal name/version:
alacritty v0.1.0

### Steps to reproduce
* Start nvim
* Press ':' really quickly
* In the command buffer, the cursor is moved to the right by several character, no ':' is shown
* Press any other key
* Crash

### Stack trace
```
(gdb) bt
#0  0x0000564936b57a27 in ptr2cells (p=0x0) at /home/void/neovim/src/nvim/charset.c:699
#1  0x0000564936bfe971 in cmdline_charsize (idx=0)
    at /home/void/neovim/src/nvim/ex_getln.c:2109
#2  0x0000564936bfd4f3 in command_line_handle_key (s=0x7ffe9f7222c0)
    at /home/void/neovim/src/nvim/ex_getln.c:1498
#3  0x0000564936bfbf69 in command_line_execute (state=0x7ffe9f7222c0, key=-11517)
    at /home/void/neovim/src/nvim/ex_getln.c:1027
#4  0x0000564936d5a137 in state_enter (s=0x7ffe9f7222c0)
    at /home/void/neovim/src/nvim/state.c:67
#5  0x0000564936bfa2d8 in command_line_enter (firstc=58, count=1, indent=0)
    at /home/void/neovim/src/nvim/ex_getln.c:396
#6  0x0000564936bfe72d in getcmdline (firstc=58, count=1, indent=0)
    at /home/void/neovim/src/nvim/ex_getln.c:1999
#7  0x0000564936bfeb32 in getexline (c=58, cookie=0x0, indent=0)
    at /home/void/neovim/src/nvim/ex_getln.c:2179
#8  0x0000564936be01d9 in do_cmdline (cmdline=0x0, fgetline=0x564936bfeaf5 <getexline>,
    cookie=0x0, flags=0) at /home/void/neovim/src/nvim/ex_docmd.c:511
#9  0x0000564936c94aa9 in nv_colon (cap=0x7ffe9f722cf0)
    at /home/void/neovim/src/nvim/normal.c:4565
#10 0x0000564936c8cea2 in normal_execute (state=0x7ffe9f722c50, key=58)
    at /home/void/neovim/src/nvim/normal.c:1137
#11 0x0000564936d5a137 in state_enter (s=0x7ffe9f722c50)
    at /home/void/neovim/src/nvim/state.c:67
#12 0x0000564936c8b147 in normal_enter (cmdwin=false, noexmode=false)
    at /home/void/neovim/src/nvim/normal.c:467
#13 0x0000564936c4ee02 in main (argc=2, argv=0x7ffe9f722fa8)
    at /home/void/neovim/src/nvim/main.c:566

```

### PR DESCRIPTION
**Pull request by bfredl**
`:norm! :` might be invoked in various ways, so its safest to always allow recursive invocation of cmdline mode. Fixes #8857 .

Simple reproduction without events: `cnoremap <f3> <cmd>norm! :foo<cr>` (might not crash immediately, press another key after `<f3>` )

### CODE REVIEW

File: src/nvim/ex_getln.c [hunk 1]
```diff
@@ -1996,7 +1991,16 @@ getcmdline (
     int indent               // indent for inside conditionals
 )
 {
-  return command_line_enter(firstc, count, indent);
+  // Be prepared for situations where cmdline can be invoked recursively.
+  // That includes cmd mappings, event handlers, as well as update_screen(), as
+  // custom status line may invoke ":normal".
```
Comment (justinmk) [inline src/nvim/ex_getln.c]: should it be `":normal :..."` ?

**Review by justinmk — APPROVED** [review]

**Comment by euank** [comment]
This fixes #6023 (segfaults that happen in the wild due to a few plugins using `exec "norm! ...."`).

The  repro I posted there behaves fine if I apply this patch, but reliably segfaults on previous commits.

Thanks @bfredl!

**Comment by bfredl** [comment]
Added a test which fails on master.
