### PR TITLE
fix(lsp): fix applying the multiple out-of-range TextEdits

### LINKED ISSUE #16842: Extra blank lines when formatting final lines of a file with efm language server
### Neovim version (nvim -v)

NVIM v0.7.0-dev+793-g991e872d8

### Language server name/version

efm-langserver 0.0.38 (rev: HEAD/devel go1.18-6178d25f Wed Dec 29 20:20:32 2021 +0000)

### Operating system/version

Darwin _ 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

### :checkhealth

```markdown
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: efm: configuration checked.

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /Users/fsouza/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: screen-256color
```

### Steps to reproduce using "nvim -u minimal_init.lua"

Modified minimal_init.lua: https://gist.github.com/fsouza/a21bc749af74046b2a90be67d77da2b3

```
$ nvim -u minimal_init.lua sample.yaml
```

Write the following yaml:

```yaml
things:
- name: whatever
```

Format the code with `:lua vim.lsp.buf.formatting()`

(I included ocaml as a config option to ensure it's not a problem with prettierd itself, if you want to reproduce with ocaml, write some poorly formatted code as the last lines of a file and invoke `vim.lsp.buf.formatting()`.

### Expected behavior

Code should be formatted to:

```yaml
things:
  - name: whatever
```

### Actual behavior

Code gets formatted to:

```yaml
things:

  - name: whatever
```

The issue happens with all of the last lines, not just the last one, meaning if I have:

```yaml
things:
- name: thing-1
- name: thing-2
- name: thing-3
- name: thing-4
```

Formatting takes me to:

```yaml
things:

  - name: thing-1

  - name: thing-2

  - name: thing-3

  - name: thing-4
```

And the issue only happens when formatting the last lines of the file. If you try the steps above with this code:

```yaml
things:
- name: whatever
other: thing
```

Then it gets correctly formatted to:

```yaml
things:
  - name: whatever
other: thing
```

Can't repro with other servers, so I assume it's something efm is doing wrong when getting the output from the process and turning into LSP commands, but I'm kinda lost on what exactly is going on.

Couple of recordings:

1. Formatting the last line in a file

https://user-images.githubusercontent.com/108725/147802999-47f4ce64-b318-476a-9563-a16f54d51661.mov

Logs (also included in the field below): https://gist.github.com/fsouza/cd967ebe4b324fafcc3e5ef62288c675

2. Formatting a line that's not the last one

https://user-images.githubusercontent.com/108725/147803062-a912ba5d-9156-4416-9d0e-d21b85fb8678.mov

Logs: https://gist.github.com/fsouza/ee6b6fdf5bd97ef3d6d0fc10b76f85e1

Looking at the responses for `textDocument/formatting`, they're equal, but maybe I'm missing something. I plan to dig into it over the next day or two, but figured I could open this issue just in case it's something obvious.

I can also reproduce it in neovim 0.5.1 and 0.6.0. And I imagine I would have noticed this before? 🙈 Which leads me to think something changed in the efm-langserver, idk. I'll look into that later.

### Log file

First recording, unexpected behavior: https://gist.github.com/fsouza/cd967ebe4b324fafcc3e5ef62288c675

Second recording, behaving as expected: https://gist.github.com/fsouza/ee6b6fdf5bd97ef3d6d0fc10b76f85e1

### PR DESCRIPTION
**Pull request by hrsh7th**
Fixes https://github.com/neovim/neovim/issues/16842

In the previous implementation, the out-of-range TextEdits will be fixed at the preparation phase.
However, The out-of-range TextEdit can't detect correctly at that time because another TextEdit can create a new ending line to the buffer.

So the new implementation will fix the out-of-range TextEdit at the run-time.

### CODE REVIEW

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -440,7 +422,24 @@ function M.apply_text_edits(text_edits, bufnr, offset_encoding)
...
   local is_cursor_fixed = false
+  local has_eol_text_edit = false
   for _, text_edit in ipairs(text_edits) do
+    -- Some LSP servers may return +1 range of the buffer content but nvim_buf_set_text can't accept it so we should fix it here.
+    local max = vim.api.nvim_buf_line_count(bufnr)
+    local len = _str_utfindex_enc(vim.api.nvim_buf_get_lines(bufnr, -2, -1, false)[1] or '', nil, offset_encoding)
+    if max <= text_edit.range.start.line then
+      text_edit.range.start.line = max - 1
+      text_edit.range.start.character = len
+      text_edit.newText = '\n' .. text_edit.newText
```
Comment (mjlbach) [inline runtime/lua/vim/lsp/util.lua:433]: Should we use the system specific newline specifier?

Comment (hrsh7th) [reply runtime/lua/vim/lsp/util.lua:433]: I think it's depending on the `nvim_buf_set_text` behavior.
This `\n` will be used only for the neovim side. So I don't think it's a problem maybe.

In my knowledge, the system-specific newline specifier is needed only when sending it to the language server.

Comment (mjlbach) [reply runtime/lua/vim/lsp/util.lua:433]: Ah, sorry, you're just splitting on newline. Nevermind.

File: runtime/lua/vim/lsp/util.lua [hunk 2]
```diff
@@ -440,7 +422,24 @@ function M.apply_text_edits(text_edits, bufnr, offset_encoding)
 
   -- Apply text edits.
   local is_cursor_fixed = false
+  local has_eol_text_edit = false
   for _, text_edit in ipairs(text_edits) do
+    -- Some LSP servers may return +1 range of the buffer content but nvim_buf_set_text can't accept it so we should fix it here.
+    local max = vim.api.nvim_buf_line_count(bufnr)
+    local len = _str_utfindex_enc(vim.api.nvim_buf_get_lines(bufnr, -2, -1, false)[1] or '', nil, offset_encoding)
```
Comment (mjlbach) [inline runtime/lua/vim/lsp/util.lua:429]: Can we first convert the text edit character to bytes, and then re-use that on line 446 and 448?

File: runtime/lua/vim/lsp/util.lua [hunk 3]
```diff
@@ -440,7 +422,24 @@ function M.apply_text_edits(text_edits, bufnr, offset_encoding)
...
+    if max <= text_edit.range['end'].line then
+      text_edit.range['end'].line = max - 1
+      text_edit.range['end'].character = len
+      has_eol_text_edit = true
+    end
+
+    -- Apply text edit via nvim_buf_set_text
     local e = {
       start_row = text_edit.range.start.line,
       start_col = get_line_byte_from_position(bufnr, text_edit.range.start),
```
Comment (mjlbach) [inline runtime/lua/vim/lsp/util.lua:445]: This should take offset encoding into account, there's another PR that does this but it can just be fixed here.

**Comment by hrsh7th** [comment]
@mjlbach I've fixed your reviewed points.

**Comment by mjlbach** [comment]
Thanks! I'll merge when tests are green.

**Comment by hrsh7th** [comment]
Hm. The tests seems failed. But I can't understand it...

File: runtime/lua/vim/lsp/util.lua [hunk 4]
```diff
@@ -440,16 +421,35 @@ function M.apply_text_edits(text_edits, bufnr, offset_encoding)
...
+      start_col = get_line_byte_from_position(bufnr, text_edit.range.start, offset_encoding),
       end_row = text_edit.range['end'].line,
-      end_col  = get_line_byte_from_position(bufnr, text_edit.range['end']),
+      end_col  = get_line_byte_from_position(bufnr, text_edit.range['end'], offset_encoding),
       text = vim.split(text_edit.newText, '\n', true),
     }
+
+    -- Some LSP servers may return +1 range of the buffer content but nvim_buf_set_text can't accept it so we should fix it here.
+    local max = vim.api.nvim_buf_line_count(bufnr)
+    local len = #(vim.api.nvim_buf_get_lines(bufnr, -2, -1, false)[1] or '')
```
Comment (mjlbach) [inline runtime/lua/vim/lsp/util.lua:437]: should we use get_line here instead? Also this could be guarded under the conditional 
`if max <= e.start_row or max <= e.end_row then` to avoid querying the buf.

**Review by mjlbach — APPROVED** [review]
