### PR TITLE
fix(loader): randomized AppImage path pollutes luac cache #31165

### LINKED ISSUE #31165: .cache/nvim/luac/ contains ~250,000 files when using nvim.appimage
### Problem

Nvim started freezing almost every session for me. Eventually I found that my `~/.cache/nvim/luac` directory has more than 250,000 files in it.

These appear to be cache files generated and named according to the path of the original lua file.

The problem is the `nvim.appimage` release mounts nvim at a different temporary path each time it is invoked. The naming scheme of these cache files changes, then on every invocation, making the cache pointless and creating N additional files on every launch of nvim. For me, that led to a directory that currently has 246,768 files in it.

Here is an example of 2 identical files in the the `./luac/` directory that are named differently only because the temporary mounting paths generated by appimage are different:

`%2ftmp%2f.mount_nvim.a65Rja0%2fusr%2fshare%2fnvim%2fruntime%2flua%2fvim%2ftreesitter.luac`
`%2ftmp%2f.mount_nvim.aNpxXgo%2fusr%2fshare%2fnvim%2fruntime%2flua%2fvim%2ftreesitter.luac`

I originally encountered this with the 0.9.5 appimage on RHEL7, but have confirmed the v0.11.0-dev-1129+gadbffff5d0 pre-release still behaves the same way.

### Steps to reproduce

To reproduce:

1) install `nvim.appimage`
2) `mv ~/.cache/nvim/luac ~/.cache/nvim/luac.backup`
3) `nvim`
4) Observe contents of `~/.cache/nvim/luac/`
5) Close nvim and run `nvim` again
6) Observe contents of `~/.cache/nvim/luac/` and see that new identical files have been added with a different mount prefix

Every time `nvim` is launched, more files are added.

### Expected behavior

Expected behavior is not to allow unbounded growth of the number of files in `~/.cache/nvim/luac/`.

When using `nvim.appimage`, the cache is effectively rendered moot between launches of nvim. A simple workaround to address the problem I'm experiencing would be to either not cache or remove cached luac files on close when appimage is used.

A more ideal solution would allow the cached files to be used and probably involves some sort of translation of appimage mount paths to a common filename in the cache directory that can be shared among multiple instances of nvim that are compatible (same version?)

### Nvim version (nvim -v)

v0.11.0-dev-1129+gadbffff5d0 all the way back to v0.9.5

### Vim (not Nvim) behaves the same?

unlikely since these are lua cache files? Not sure how to even check this.

### Operating system/version

RHEL9.3, RHEL7, and RHEL8

### Terminal name/version

zsh 5.8

### $TERM environment variable

screen

### Installation

appimage

### PR DESCRIPTION
**Pull request by shmerl**
Fixes infinite growth of number of *.luac files in the cache and actual cache file misses caused by randomness of filenames when using AppImage with loader enabled.

fix #31165

### CODE REVIEW

**Comment by shmerl** [comment]
Hm, it fails some checks like this:

```
runtime/lua/vim/loader.lua:122:11 [Warning] Can not infer type. (no-unknown)
        local idx = name:find('/usr/', 1, true)
              ^^^
```

I'm not exactly sure what it doesn't like. Any suggestion how to prevent that? The `idx` should be a number of `nil`.

File: runtime/lua/vim/loader.lua [hunk 1]
```diff
@@ -116,6 +116,13 @@ end
 --- @param name string can be a module name, or a file name
 --- @return string file_name
 local function cache_filename(name)
+  -- Simplify the name of AppImage mounted file, to prevent
+  -- random part in it from creating cache misses.
+  if os.getenv('APPIMAGE') ~= nil then
+    local idx = name:find('/usr/', 1, true) --- @type integer?
```
Comment (justinmk) [inline runtime/lua/vim/loader.lua:122]: look at examples in the codebase, if in doubt
```suggestion
    local idx = name:find('/usr/', 1, true) ---@type integer?
```

File: runtime/lua/vim/loader.lua [hunk 2]
```diff
@@ -116,6 +116,13 @@ end
...
+    name = idx and name:sub(idx) or name
```
Comment (justinmk) [inline runtime/lua/vim/loader.lua]: 1. this can be simplified using match()
2. always show an input/output example, it communicates so much in a very concise way.

```suggestion
    -- Avoid cache pollution caused by AppImage randomizing the program root. #31165
    -- "/tmp/.mount_nvimAmpHPH/usr/share/nvim/runtime" => "/usr/share/nvim/runtime"
    name = name:match("(/usr/.*)") or name
```

File: runtime/lua/vim/loader.lua [hunk 3]
```diff
@@ -116,6 +116,14 @@ end
 --- @param name string can be a module name, or a file name
 --- @return string file_name
 local function cache_filename(name)
+  -- Simplify the name of AppImage mounted file, to prevent
+  -- random part in it from creating cache misses.
```
Comment (justinmk) [inline runtime/lua/vim/loader.lua]:
```suggestion
```

**Comment by justinmk** [comment]
I pushed a change, can you confirm it works so we can wrap this up

File: runtime/lua/vim/loader.lua [hunk 4]
```diff
@@ -116,6 +116,12 @@ end
 --- @param name string can be a module name, or a file name
 --- @return string file_name
 local function cache_filename(name)
```
Comment (justinmk) [inline runtime/lua/vim/loader.lua:127]: Why did you modify this function? `normalize` is defined in this module and is used through this module to resolve the path. Seems like `normalize` is where the workaround should live.

**Comment by shmerl** [comment]
> I pushed a change, can you confirm it works so we can wrap this up

Never did it before, how can I build an appimage from my branch?

**Comment by shmerl** [comment]
OK, I managed to repack things using appimage-tool using the patched file. Checking.

**Comment by shmerl** [comment]
Weird, even with fixed file I still see this accumulation:

```
Only in luac: %2ftmp%2f.mount_NeovimHiB7yR%2fusr%2fshare%2fnvim%2fruntime%2ffiletype.luac
Only in luac: %2ftmp%2f.mount_NeovimHiB7yR%2fusr%2fshare%2fnvim%2fruntime%2flua%2fvim%2ftermcap.luac
Only in luac: %2ftmp%2f.mount_NeovimHiB7yR%2fusr%2fshare%2fnvim%2fruntime%2fplugin%2feditorconfig.luac
Only in luac: %2ftmp%2f.mount_NeovimHiB7yR%2fusr%2fshare%2fnvim%2fruntime%2fplugin%2fman.luac
Only in luac: %2ftmp%2f.mount_NeovimHiB7yR%2fusr%2fshare%2fnvim%2fruntime%2fplugin%2fosc52.luac
Only in luac: %2ftmp%2f.mount_NeovimHiB7yR%2fusr%2fshare%2fnvim%2fruntime%2fplugin%2ftohtml.luac
```

FYI, the way I tested it. Extracted existing appimage release:

```
nvim --appimage-extract
```

Replaced `loader.lua` and then repacked things back with

```
wcurl https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage

./appimagetool-x86_64.AppImage --no-appstream squashfs-root 
```

Really not sure why it's not helping though. Could be something else is going on? I can try replacing things in the function you suggested for a test.

**Comment by shmerl** [comment]
Nope, we are missing something here. Even moving that fix to the normalize function doesn't help.

**Comment by justinmk** [comment]
Try removing the `os.getenv('APPIMAGE')` check

**Comment by shmerl** [comment]
Nope, that's not it. It's still using that cursed path in filenames:

```
%2ftmp%2f.mount_NeovimygI0ZN%2fusr%2fshare%2...
```
I think something else is happening besides loader may be? Also, I can confirm that the variable is set if I read this from inside neovim itself

```
:= os.getenv('APPIMAGE')
```

Returns binary path.

**Comment by justinmk** [comment]
To double check that the appimage "repack" is actually working, can you try throwing an error in the loader somewhere and confirm that the error is thrown after repack :)

**Comment by shmerl** [comment]
Weird, adding `error('foo')` to that `cache_filename` function does nothing. Even adding it on top level of loader.lua has no effect. Something is off here.

Also, I see my changes in loader.lua that's mounted to /tmp with appimage when neovim is opened.

**Comment by justinmk** [comment]
Just a guess, but confirm that `enable=true` here https://github.com/neovim/neovim/blob/2f78ff816b03661b5f74d0624e973eaca0d64ef1/runtime/lua/vim/loader.lua#L424

else you are hitting the "standard" path in that if-else, which does not use the custom loader.

**Comment by shmerl** [comment]
I added something like this in `runtime/lua/vim/loader.lua`:

```
function M.enable(enable)
  error("enable = " .. enable)
...
```

But I don't see any exception thrown. I don't get it, is this module even used at all?

**Comment by nenahp** [comment]
i would guess u need to use make to compile as loader.lua may be preload as bytecode

**Comment by shmerl** [comment]
> loader.lua may be preload as bytecode

Where would it come from though? I don't see any luac files in the appimage tree.

**Comment by justinmk** [comment]
how are you starting `nvim`? try `--luamod-dev`  and make sure you point to the VIMRUNTIME that has your changes:

    VIMRUNTIME=$HOME/dev/neovim/runtime/ nvim --luamod-dev

**Comment by shmerl** [comment]
I was actually starting re-packed appimage since that should trigger the env variable check. I can try using the above method.

**Comment by shmerl** [comment]
@justinmk: Just got to testing it using your method with providing the modified runtime with the fix. It works!

I.e. I unpacked the appimage to `$HOME/tmp/neovim_debug`, applied the change to loader.lua and tried this (using same appimage nvim binary I unpacked things from):

```
VIMRUNTIME=$HOME/tmp/neovim_debug/squashfs-root/usr/share/nvim/runtime nvim --luamod-dev
```

Now those previously problematic files are created without the bad prefix like this:

```
%2fusr%2fshare%2fnvim%2fruntime%2ffiletype.luac
```

So I can confirm that the fix helps.

**Comment by justinmk** [comment]
Nice! Did you try moving the logic to `normalize()` instead of `cache_filename` ? That seems more complete.

To write a test for this, just add a new `it()` case to `test/functional/lua/loader_spec.lua` and (try AI for this):

1. in the `clear{env={...}}` have it set the APPIMAGE env var, and set VIMRUNTIME to something like `./Xtest/tmpbogus/usr/...`
2. it should `require()` some module that lives in the test directory `./Xtest/tmpbogus/usr/nvim/runtime/lua/foo.lua`
3. have it call the `loader._profile` function: https://github.com/neovim/neovim/blob/c947b8da106c8a9448bb6fa1cc2aba82e51eb8e0/runtime/lua/vim/loader.lua#L477
4. have it call `loader._inspect()`: https://github.com/neovim/neovim/blob/c947b8da106c8a9448bb6fa1cc2aba82e51eb8e0/runtime/lua/vim/loader.lua#L498
    - it looks like the `stats` don't mention filenames, but that can be easily changed. That makes it easy to check the cached filenames.
5. assert that the cached name is `/usr/nvim/runtime/lua/foo.lua`

**Comment by shmerl** [comment]
That's a bit over my head now, I'll have to take a closer look how to make a new test. Do you suggest to add it to some existing unit test file or make a new one?

**Comment by shmerl** [comment]
On doing it in normalize, it does work. I tried this:

```lua
local function normalize(path)
  path = fs.normalize(path, { expand_env = false, _fast = true })

  if os.getenv('APPIMAGE') ~= nil then
    -- Avoid cache pollution caused by AppImage randomizing the program root. #31165
    -- "/tmp/.mount_nvimAmpHPH/usr/share/nvim/runtime" => "/usr/share/nvim/runtime"
    path = path:match("(/usr/.*)") or path
  end

  return path
end
```

**Comment by justinmk** [comment]
> That's a bit over my head now,

try an AI to get something started. You can [run the test](https://github.com/neovim/neovim/blob/master/test/README.md#filter-by-file) like this:

    TEST_FILE=test/functional/lua/loader_spec.lua make functionaltest


> I'll have to take a closer look how to make a new test. Do you suggest to add it to some existing unit test file or make a new one?

`test/functional/lua/loader_spec.lua`

File: runtime/lua/vim/loader.lua [hunk 5]
```diff
@@ -78,7 +78,15 @@ local function fs_stat_cached(path)
 end
 
 local function normalize(path)
-  return fs.normalize(path, { expand_env = false, _fast = true })
+  path = fs.normalize(path, { expand_env = false, _fast = true })
+
+  if os.getenv('APPIMAGE') ~= nil then
```
Comment (justinmk) [inline runtime/lua/vim/loader.lua]: since loader is very perf-sensitive, let's cache this in a `local is_appimage` near the top of the module (line 10).

File: runtime/lua/vim/loader.lua [hunk 6]
```diff
@@ -78,7 +79,11 @@ local function fs_stat_cached(path)
 end
 
 local function normalize(path)
-  return fs.normalize(path, { expand_env = false, _fast = true })
+  path = fs.normalize(path, { expand_env = false, _fast = true })
+
+  -- Avoid cache pollution caused by AppImage randomizing the program root. #31165
+  -- "/tmp/.mount_nvimAmpHPH/usr/share/nvim/runtime" => "/usr/share/nvim/runtime"
+  return is_appimage and path:match('(/usr/.*)') or path
```
Comment (justinmk) [inline runtime/lua/vim/loader.lua]: although i'm normally in favor of ternaries, i think in this case it's better to keep it separated in a `if` block, because this is a special case that is mostly unrelated to the rest of this module, and furthermore, the comment above this line is now less clear because it annotates both branches

**Comment by shmerl** [comment]
I'll look into the test a bit later.

**Comment by justinmk** [comment]
rebase?

**Comment by shmerl** [comment]
I'll refersh it soon, but I didn't have a chance to look into unit tests. I'll have some time for that later in the month.

**Comment by justinmk** [comment]
We can just merge this for now. Meanwhile, the value of `vim.loader` is in question: https://github.com/neovim/neovim/discussions/36905
