### PR TITLE
[RDY] unittest: Allow multiple indirect includes

### LINKED ISSUE #5857: Unit Tests under test/unit/eval fail in a certain order
- `nvim --version`: commit c5f4b92ff93a40ec4e77b78d0576903e7a60eefd
- Vim (version: ) behaves differently? nvim-specific
- Operating system/version: Mageia Linux x86-64 v6 ; Debian x86-64 Stretch
- Terminal name/version: konsole of plasma 5.8.x
- `$TERM`: screen

### Actual behaviour

Tests fail with this output:

```
./test/unit/helpers.lua:119: attempt to redefine 'partial_S'

stack traceback:
	./test/unit/helpers.lua:119: in function 'cimport'
	./test/unit/eval/helpers.lua:8: in main chunk

-- Output to stderr:
E474: No container to close: ]
E474: Closing list with curly bracket: }
E474: Closing dictionary with square bracket: ]
E474: Trailing comma: ]
E474: Expected value after colon: }
E474: Expected value: }
E474: Comma not inside container: ,
E474: Duplicate comma: ,1]
E474: Comma after colon: ,}
E474: Using comma in place of colon: ,}
E474: Leading comma: ,}
E474: Leading comma: ,]
E474: Colon not inside container: :
E474: Using colon not in dictionary: :]
E474: Unexpected colon: :}
E474: Duplicate colon: :1}
E474: Expected null: n
E474: Expected true: t
E474: Expected false: f
E474: Unfinished escape sequence: "\
E474: Unfinished unicode escape sequence: "\u"
E474: Expected four hex digits after \u: \uXXXX"
E474: Unknown escape sequence: \?"
E474: ASCII control characters cannot be present inside string: ^I"
E474: Only UTF-8 strings allowed: <c2>"
E474: Only UTF-8 code points up to U+10FFFF are allowed to appear unescaped: ü"
E474: Expected string end: "
E474: Failed to convert string "ê¯" from UTF-8
E474: Missing number after minus sign: -
E474: Missing number after decimal dot: -1.
E474: Missing exponent: -1.0e
E474: Unidentified byte: ?
E474: Trailing characters: ?
E474: Unexpected end of input: [1
E474: Missing number after minus sign: -

CMake Error at /home/shlomif/Download/unpack/file/vim/neovim/cmake/RunTests.cmake:46 (message):
  Running unit tests failed with error: 1.


FAILED: cd /home/shlomif/Download/unpack/file/vim/neovim/build && /usr/bin/cmake -DBUSTED_PRG=/home/shlomif/Download/unpack/file/vim/neovim/.deps/usr/bin/busted -DLUA_PRG=/home/shlomif/Download/unpack/file/vim/neovim/.deps/usr/bin/luajit -DWORKING_DIR=/home/shlomif/Download/unpack/file/vim/neovim -DBUSTED_OUTPUT_TYPE=utfTerminal -DTEST_DIR=/home/shlomif/Download/unpack/file/vim/neovim/test -DBUILD_DIR=/home/shlomif/Download/unpack/file/vim/neovim/build -DTEST_TYPE=unit -DSYSTEM_NAME=Linux -P /home/shlomif/Download/unpack/file/vim/neovim/cmake/RunTests.cmake
ninja: build stopped: subcommand failed.
Makefile:104: recipe for target 'unittest' failed
make: *** [unittest] Error 1


```

### Expected behaviour

Tests should succeed.

### Steps to reproduce using `nvim -u NORC`

The following script:

```bash
LC_ALL=C TEST_FILE="test/unit/eval/tricks_spec.lua test/unit/eval/encode_spec.lua test/unit/eval/decode_spec.lua  test/unit/eval/helpers.lua  " make unittest

```

which does the same thing here as:

```bash
LC_ALL=C TEST_FILE=test/unit/eval/ make unittest

```

produces the failure  here. It is ran as part of the grand "LC_ALL=C make unittest", causing it to fail under certain conditions. Please look into it.

### PR DESCRIPTION
**Pull request by ZyX-I**
Works by saving all preprocessor defines and reusing them on each run. This also 
saves NVIM_HEADER_H defines. Saving other defines is needed for defines like 
`Map(foo, bar)` which are sometimes used to declare types or functions. Saving 
types or function declarations is not needed because they are recorded as luajit 
state.

Fixes #5857

### CODE REVIEW

File: test/unit/helpers.lua [hunk 1]
```diff
@@ -68,14 +68,12 @@ local function cimport(...)
...
-    local stream = Preprocess.preprocess_stream(unpack(paths))
-    body = stream:read("*a")
-    stream:close()
+    body = Preprocess.preprocess(unpack(paths))
     if body ~= nil then break end
   end
 
   if body == nil then
-    print("ERROR: helpers.lua: Preprocess.preprocess_stream():read() returned empty")
+    print("ERROR: helpers.lua: Preprocess.preprocess() returned empty")
```
Comment (justinmk) [inline test/unit/helpers.lua]: This sanity check was for the `:read()` call. Because of a lua or lfs bug it sometimes returns empty, and catching it here saves debugging later. Not sure if it's still needed, but if so it so check `ret == nil` after line 182 in `test/unit/preprocess.lua`.

File: test/unit/preprocess.lua [hunk 2]
```diff
@@ -145,21 +149,40 @@ end
...
+  pseudoheader_file:flush()
+  pseudoheader_file:close()
   local defines = table.concat(self.preprocessor_extra_flags, ' ')
   local cmd = ("echo $hdr | " ..
                tostring(self.path) ..
                " " ..
                tostring(defines) ..
-               " -std=c99 -P -E -"):gsub('$hdr', shell_quote(pseudoheader))
+               " -std=c99 -P -E " .. shell_quote(pseudoheader_fname))
+  local def_cmd = ("echo $hdr | " ..
```
Comment (justinmk) [inline test/unit/preprocess.lua]: Does `$hdr` get replaced now? Before `:gsub('$hdr', ...)` did so.

File: test/unit/preprocess.lua [hunk 3]
```diff
@@ -145,21 +149,40 @@ end
...
   local pseudoheader = headerize({...}, false)
+  local pseudoheader_fname = 'tmp_pseudoheader.h'
+  local pseudoheader_file = io.open(pseudoheader_fname, 'w')
+  pseudoheader_file:write(self.added_header_defines)
+  pseudoheader_file:write("\n")
+  pseudoheader_file:write(pseudoheader)
+  pseudoheader_file:flush()
+  pseudoheader_file:close()
   local defines = table.concat(self.preprocessor_extra_flags, ' ')
   local cmd = ("echo $hdr | " ..
```
Comment (justinmk) [inline test/unit/preprocess.lua]: Would be slightly easier to follow if this were defined next to `io.popen(cmd)` below.

File: test/unit/preprocess.lua (hunk 2 above)
Comment (ZyX-I) [inline test/unit/preprocess.lua]: `echo $hdr | … -` was replaced with actual file name. Just forgot to remove the command.

Comment (ZyX-I) [inline test/unit/preprocess.lua]: Currently it works because any input is ignored.

File: test/unit/preprocess.lua [hunk 4]
```diff
@@ -61,12 +65,12 @@ end
...
 -- all the passed in headers. I.e.:
 --
--- headerize({"stdio.h", "math.h", true}
+-- headerize({"stdio.h", "math.h"}, true}
 -- produces:
 -- #include <stdio.h>
 -- #include <math.h>
 --
--- headerize({"vim.h", "memory.h", false}
+-- headerize({"vim.h", "memory.h"}, false}
```
Comment (justinmk) [inline test/unit/preprocess.lua]: Should the final `}` be a `)` ?

**Review by justinmk — APPROVED** [review]

**Comment by ZyX-I** [comment]
This is also ready, quickbuild failure seems to be one of the unrelated random failures:

```
07:48:57,849 INFO  - not ok 107 - TermClose event works as expected
07:48:57,849 INFO  - # test/functional/autocmd/termclose_spec.lua @ 20
07:48:57,849 INFO  - # Failure message: ./test/functional/ui/screen.lua:318: Row 4 did not match.
07:48:57,849 INFO  - # Expected:
07:48:57,849 INFO  - # |ready $ |
07:48:57,849 INFO  - # |[Process exited 0] |
07:48:57,849 INFO  - # |^ |
07:48:57,849 INFO  - # |*TermClose works! |
07:48:57,849 INFO  - # Actual:
07:48:57,849 INFO  - # |ready $ |
07:48:58,079 INFO  - # |[Process exited 0] |
07:48:58,080 INFO  - # |^ |
07:48:58,080 INFO  - # |* |
07:48:58,080 INFO  - #
07:48:58,080 INFO  - # To print the expect() call that would assert the current screen state, use
07:48:58,080 INFO  - # screen:snaphot_util(). In case of non-deterministic failures, use
07:48:58,080 INFO  - # screen:redraw_debug() to show all intermediate screen states.
07:48:58,080 INFO  - # stack traceback:
07:48:58,080 INFO  - #     ./test/functional/ui/screen.lua:318: in function 'wait'
07:48:58,080 INFO  - #     ./test/functional/ui/screen.lua:229: in function 'expect'
07:48:58,080 INFO  - #     test/functional/autocmd/termclose_spec.lua:24: in function <test/functional/autocmd/termclose_spec.lua:20>
07:48:58,080 INFO  - #
07:48:58,080 INFO  - # test/functional/autocmd/termclose_spec.lua @ 32: TermClose event reports the correct <abuf>
```
