### PR TITLE
fix(treesitter): make InspectTree correctly handle nested injections

### LINKED ISSUE #26084: `:InspectTree` incorrectly handles nested injections
### Problem

When inspect a piece of code that has nested injections, `:InspectTree` overrides the first node with the last, and also never tries to handle child's injections

This piece of code below for a file named `test.html` is an example, while using with nvim-treesitter, 
```html
<html>
<body>
<script>
const x = html`<foo></foo>`
</script>
</body>
</html>
```

### Steps to reproduce

- repro.lua
```lua
for name, url in pairs{
  nvim_treesitter = 'https://github.com/nvim-treesitter/nvim-treesitter'
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require("nvim-treesitter.configs").setup({
  ensure_installed = { "html", "javascript" },
})
```

- `nvim -u repro.lua test.html`
- `:InspectTree`

### Expected behavior

It should correctly handle nested injections

### Neovim version (nvim -v)

0.10.0-dev commit 86c2213b5e451b0c80c2d7adc356c7cebe4bb7f8

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux 6.6.1

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

Build from source

### PR DESCRIPTION
**Pull request by lucario387**
**Problem**: `:InspectTree` doesn't correctly handle nested injections

Using nvim-treesitter, we can have a codeblock of
```html
<script> 
const x = html`<ge></ge>`
</script>
```
that will be rendered as the image: image

This was because of the codeblock below https://github.com/neovim/neovim/blob/315c711700a87fe3fa546906ab39557ebba19baf/runtime/lua/vim/treesitter/dev.lua#L104-L115

When we check for an injection, we only consider it to be a child of the root tree, and didn't check whether it was a child of another injection tree.

**Solution**: During initial creation of `TSTreeView`, Iterate over all root trees to get their injections, not just the root tree. For each overlapping tree of a parent tree, Keep the injection tree with the biggest range as the child.

Potential issues:
- The old nvim-treesitter-playground implementation has all injections for a range shown, should this be followed?
- How exactly can we find the tree with the biggest range? I used to try `child:trees()[1]:root()`, but this sometimes break while messing with a large enough file. Because of that, I opted for iterating every injected tree of a child, which is sometimes unnecessary.

fixes #26084 

| Before | After |
| - | - |
| image | image |

### CODE REVIEW

File: runtime/lua/vim/treesitter/dev.lua [hunk 1]
```diff
@@ -99,22 +99,44 @@ function TSTreeView:new(bufnr, lang)
...
+    return end_byte - start_byte
   end
+  parser:for_each_tree(function(root_tree, root_ltree)
+    local root = root_tree:root()
+    for _, child in pairs(root_ltree:children()) do
+      child:for_each_tree(function(tree, ltree)
+        local r = tree:root()
+        local node = root:named_descendant_for_range(r:range())
+        if node then
+          if injections[node:id()] then
```
Comment (lucario387) [inline runtime/lua/vim/treesitter/dev.lua:119]: I don't know if the inner injected trees are parsed before or after the outer ones. If the order are outer -> inner, then I will remove the if accordingly

File: runtime/lua/vim/treesitter/dev.lua [hunk 2]
```diff
@@ -100,19 +100,39 @@ function TSTreeView:new(bufnr, lang)
...
+  ---@return number
+  local function node_length(node)
+    local _, _, start_byte = node:start()
+    local _, _, end_byte = node:end_()
+    return end_byte - start_byte
+  end
+  parser:for_each_tree(function(parent_tree, parent_ltree)
+    local parent = parent_tree:root()
+    for _, child in pairs(parent_ltree:children()) do
+      local r = child:trees()[1]:root()
```
Comment (lucario387) [inline runtime/lua/vim/treesitter/dev.lua:115]: This seems unsafe but I don't know. I'm just expecting the first tree to be what I expected

Comment (lucario387) [reply runtime/lua/vim/treesitter/dev.lua]: It breaks, so I attempted it a different way

**Comment by Danielkonge** [comment]
Thank you for fixing this, I have also run into this problem with nested injected languages. 

Have you tried something more complicated like the following in a markdown file? (remove the `;` before ```, I just added them so it shows up nicely in GitHub)

```markdown
Markdown
;```markdown
Injected markdown.
~~~lua
print 'Injected Lua'
print({{{{}}}})
vim.cmd[[echo str([])]]
vim.cmd[[
echo 'Injected vim in injected Lua'
echo str([])
]]
~~~
More injected markdown.
;```
```

Also, did you double check that the languages are as you expected when you press `I` in the `InspectTree` window to have the language of each line listed?

**Comment by lucario387** [comment]
> Have you tried something more complicated like the following in a markdown file? (remove the ; before ```, I just added them so it shows up nicely in GitHub)

It's not more complicated than my example. It's still just nested injections.

Fwiw, here's the result of your code. 
image

**Comment by Danielkonge** [comment]
> It's not more complicated than my example. It's still just nested injections.

It is still just nested injections, yes. What I meant with more complicated was really just deeper nesting + multiple injections of the same language at the same nesting level. In particular, I have run into a problem with multiple injections of the same language at the same nesting level before, so I thought it would be worth testing.  

> Fwiw, here's the result of your code. 

Thank you. That looks like I would expect for that part.

File: runtime/lua/vim/treesitter/dev.lua [hunk 3]
```diff
@@ -100,19 +100,41 @@ function TSTreeView:new(bufnr, lang)
...
+    return end_byte - start_byte
   end
+  parser:for_each_tree(function(parent_tree, parent_ltree)
+    local parent = parent_tree:root()
+    for _, child in pairs(parent_ltree:children()) do
+      child:for_each_tree(function(tree, ltree)
+        local r = tree:root()
+        local node = parent:named_descendant_for_range(r:range())
+        if node then
+          if injections[node:id()] then
```
[the remark this answers is not in the document]
Comment (lucario387) [reply runtime/lua/vim/treesitter/dev.lua:119]: I don't know the exact order of child tree iteration, so I opted to compare the node length

As `for_each_tree` uses `pairs()`, the order of the trees is not guaranteed to be outermost->innermost. If I understand this incorrectly then I will change to your example

[the remark this answers is not in the document]
Comment (gpanders) [reply runtime/lua/vim/treesitter/dev.lua:119]: Ok, I think you're right that it's safer not to assume the iteration order.

I don't like this `node_length` function, I'd prefer to have it as a method on TSNode or in the Range module instead, but we can do that in a follow up. Two changes I want to make here in this PR:

1. Store the size of the current injection in the `injections` table to make it easier/cheaper to compare in each iteration
2. `assert` that `named_descendant_for_range` is non-nil (it won't ever be nil)

```diff
-        local node = parent:named_descendant_for_range(r:range())
-        if node then
-          if injections[node:id()] then
-            local old_r = injections[node:id()].root
-            -- Keep the outermost tree, as this is most likely the parent's tree
-            if node_length(r) >= node_length(old_r) then
-              injections[node:id()] = {
-                lang = ltree:lang(),
-                root = r,
-              }
-            end
-          else
-            injections[node:id()] = {
-              lang = ltree:lang(),
-              root = r,
-            }
-          end
+        local node = assert(parent:named_descendant_for_range(r:range()))
+        local id = node:id()
+        local size = node_length(r)
+        if not injections[id] or size > injections[id].size then
+          injections[id] = {
+            lang = ltree:lang(),
+            root = r,
+            size = size,
+          }
```

**Comment by lucario387** [comment]
> I have run into a problem with multiple injections of the same language at the same nesting level before, so I thought it would be worth testing.

If this still happens for nvim-treesitter, make sure to send a PR :D. We tried very aggressively to not have a node be injected with two languages (bar comment nodes).

**Comment by gpanders** [comment]
Thanks @lucario387!

**Comment by Danielkonge** [comment]
> If this still happens for nvim-treesitter, make sure to send a PR :D. We tried very aggressively to not have a node be injected with two languages (bar comment nodes).

I think my explanation was unclear. I have run into this issue before in a plugin, I haven't noticed an issue like that in the neovim core. Also, with two languages at the same level I meant something like this:
~~~markdown
Markdown
```lua
-- one lua block
local a = 1
```
more markdown
```lua
-- second lua block at "same nesting level"
local b = 2
```
~~~
But if I notice any issue with treesitter (I have been doing a lot of stuff with treesitter recently) in neovim, I will try to make a pull request. :)
