### PR TITLE
[RDY] floating-window.c: fix crash when using inccommand

### LINKED ISSUE #9739: Segfault when using inccommand together with floating window
- `nvim --version`: `NVIM v0.4.0-dev` built from `907b4803500e3321b0996807d75d85646a6720e2`
- Operating system/version: `MacOS High Sierra 10.13.6`
- Terminal name/version: `iTerm2 3.2.5`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
set inccommand=nosplit

let s:buf = nvim_create_buf(v:false, v:true)
let s:win = nvim_open_win(s:buf, 0, 10, 10, {
      \ 'relative': 'cursor',
      \ 'row': 0,
      \ 'col': 0,
      \ })
```

Type `:s/`

### Expected behaviour
No crash

### Actual behaviour
Neovim crashes with `Segmentation fault: 11`

Also occurs with `NVIM v0.4.0-386-gced980ff1` on Windows 10 WSL Ubuntu.

### PR DESCRIPTION
**Pull request by gelguy**
Fixes #9739.

It seems that code prior to floating window assumed that `wp->w_frame` always exists, i.e. a window will always be associated with a frame.

### CODE REVIEW

File: test/functional/ui/float_spec.lua [hunk 1]
```diff
@@ -1105,6 +1107,191 @@ describe('floating windows', function()
       end
     end)
 
+    it('does not crash with inccommand #9379', function()
+      screen:try_resize(30,15)
```
Comment (mhinz) [inline test/functional/ui/float_spec.lua]: Is there any particular reason for this? It would be more readable if the test would use the default of 40 columns and 7 lines.

File: test/functional/ui/float_spec.lua [hunk 2]
```diff
@@ -1105,6 +1107,191 @@ describe('floating windows', function()
...
+      command("set inccommand=split")
+      command("set laststatus=2")
+
+      local buf = meths.create_buf(false,false)
+      meths.open_win(buf, true, {relative='editor', width=30, height=3, row=2, col=0})
+
+      insert([[
+  foo
+  bar
+]])
```
Comment (mhinz) [inline test/functional/ui/float_spec.lua]: The above 3 lines can all be on the same level as `insert(`.

File: test/functional/ui/float_spec.lua (hunk 1 above)
Comment (gelguy) [reply test/functional/ui/float_spec.lua]: I believe I got `30,15` from one of the tests in `inccommand_spec`.

Updated to use `40,7`.

File: src/nvim/window.c [hunk 3]
```diff
@@ -4656,7 +4656,11 @@ void win_size_restore(garray_T *gap)
     {
       int i = 0;
       FOR_ALL_WINDOWS_IN_TAB(wp, curtab) {
-        frame_setwidth(wp->w_frame, ((int *)gap->ga_data)[i++]);
+        if (wp->w_floating) {
+          win_setwidth_win(((int *)gap->ga_data)[i++], wp);
```
Comment (bfredl) [inline src/nvim/window.c]: This is to save/restore state of split layout when opening temporary split. So we don't need to do anything at all for floats here.

**Review by mhinz — APPROVED** [review]

**Comment by bfredl** [comment]
Nice, thanks!
