### PR TITLE
Check for bash version in vim-patch.sh

### LINKED ISSUE #12069: `./scripts/vim-patch.sh -l` does not work on MacOS default bash.
- `nvim --version`: NVIM v0.5.0-423-g4139678f9
- Operating system/version: Mac OS X 10.15.3
- Terminal name/version: iTerm2 Build 3.3.9
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```sh
$ git clone https://github.com/neovim/neovim.git
$ cd neovim
$ ./scripts/vim-patch.sh -l
```

### Actual behaviour

```sh
$ ./scripts/vim-patch.sh -l
./scripts/vim-patch.sh: line 400: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

### Expected behaviour

```sh
$ ./scripts/vim-patch.sh -l
Updating Vim sources: ...
```

This behavior is due to the version of default bash on MacOS.

```sh
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```

Why not add some Notes about bash prerequisites on [Wiki](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim) or somewhere?

### PR DESCRIPTION
**Pull request by xylix**
Because of licensing reasons apple is not going to upgrade their installed bash version anytime soon. Checking for an unsupported version and informing the user about the need to update their bash is probably the easiest workaround we can do. Could also compromise and make the script be compatible with antique bash, but that doesn't sound necessary.

I'd gladly also add this warning to any other scripts / to a wrapper script if there's other places in the neovim build / contribution chain where a bash version check could be useful. Any pointers about this?

Fixes  #12069

### CODE REVIEW

**Review by Wordof-worf — APPROVED** [review]
навигации между коммитами в запросе на включение.

**Comment by justinmk** [comment]
why not check `$BASH_VERSION` ? if the first char is less than 4 then it's too old

File: scripts/vim-patch.sh [hunk 1]
```diff
@@ -5,6 +5,12 @@ set -u
 # Use privileged mode, which e.g. skips using CDPATH.
 set -p
 
+# Ensure that the user has a bash that supports -A
+if ! declare -A ; then
```
Comment (justinmk) [inline scripts/vim-patch.sh:9]: doesn't this echo a bunch of noise?

**Comment by xylix** [comment]
I didn't know how to do it in bash, but figured it out now. Now it looks in the $BASH_VERSION.

File: scripts/vim-patch.sh [hunk 2]
```diff
@@ -5,6 +5,12 @@ set -u
 # Use privileged mode, which e.g. skips using CDPATH.
 set -p
 
+# Ensure that the user has a bash that supports -A
+if [ "${BASH_VERSION::1}" -lt 4  ]; then
```
Comment (blueyed) [inline scripts/vim-patch.sh:9]: Should use `BASH_VERSINFO[0]` ("The major version number (the release).", see `bash(1)`).
Otherwise it fails for bash 10 in some years.
Have not checked when `BASH_VERSINFO` was added though..

Comment (xylix) [reply scripts/vim-patch.sh]: https://github.com/bminor/bash/blob/master/CHANGES#L9370
Versinfo was added in bash 2.0, so 1996. Fixed now.

File: scripts/vim-patch.sh [hunk 3]
```diff
@@ -5,6 +5,12 @@ set -u
 # Use privileged mode, which e.g. skips using CDPATH.
 set -p
 
+# Ensure that the user has a bash that supports -A
+if [ "${BASH_VERSINFO[0]}" -lt 4  ]; then
```
Comment (blueyed) [inline scripts/vim-patch.sh:9]:
```suggestion
if [[ "${BASH_VERSINFO[0]}" -lt 4  ]]; then
```

File: scripts/vim-patch.sh [hunk 4]
```diff
@@ -5,6 +5,12 @@ set -u
...
+  echo "Update your bash version to one that supports -A syntax (>3)"
```
Comment (blueyed) [inline scripts/vim-patch.sh:10]:
```suggestion
  echo "This script requires bash version 3 or later (you have ${BASH_VERSION})." >&2
```

**Review by blueyed — COMMENTED** [review]
LGTM in general, but I think the message can be improved, especially with regard to writing to stderr.

**Comment by xylix** [comment]
Applied feedback changes

**Review by blueyed — APPROVED** [review]
Thanks!

File: scripts/vim-patch.sh [hunk 5]
```diff
@@ -5,6 +5,12 @@ set -u
 # Use privileged mode, which e.g. skips using CDPATH.
 set -p
 
+# Ensure that the user has a bash that supports -A
+if [[ "${BASH_VERSINFO[0]}" -lt 4  ]]; then
+  echo "This script requires bash version 3 or later (you have ${BASH_VERSION})." >&2
```
Comment (justinmk) [inline scripts/vim-patch.sh:10]: should be "requires bash 4+". version 3 is too old
