### PR TITLE
fix(fold): dont highlight search results on folded lines

### LINKED ISSUE #13507: Fold + search results in wrong highlighting
- `nvim --version`: v0.5.0-dev+925-g00f60c2ce
- `vim -u DEFAULTS` (version: (8.0 - 2016 Sep 12, compiled Oct 13 2020) behaves differently? Yes
- Operating system/version: linux
- Terminal name/version: kitty 0.18.3
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Run `nvim -u NORC -i NONE -c 'set foldmethod=indent' /tmp/tmp.py` and paste the following:
```python
if A:
    pass
else:
    if B:
        pass
    else:
        pass
```

Search for `if B:` with `/`

### Actual behaviour
The `!A` branch is folded. The fold has the following text: `+-- 4 lines: if B:...`. ` 4 li` is highlighted.

### Expected behaviour
` 4 li` is not highlighted.

### PR DESCRIPTION
**Pull request by teto**
Behavior may change in future but for now stick to legacy behavior.
Fixes https://github.com/neovim/neovim/issues/13507

cc @glacambre

### CODE REVIEW

**Review by vigoux — APPROVED** [review]

**Comment by cvlmtg** [comment]
Hi, I just updated neovim with `brew install --build-from-source --HEAD neovim` and there's an issue with search highlight. Not sure how to describe it so I made a little movie. As you can see some words are highlighted but some are no longer highlighted. I suppose it depends on the highlight group, but have no clues on why...

Before the update it worked correctly obviously. My OS is macOS Catalina


https://user-images.githubusercontent.com/6401008/103346746-3aae0e00-4a95-11eb-9c17-3ff3db5321bf.mov

File: src/nvim/screen.c [hunk 1]
```diff
@@ -2196,7 +2197,7 @@ static int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow,
     }
 
     if (wp->w_p_spell
-        && foldinfo.fi_lines == 0
+        && !has_fold
```
Comment (teto) [inline src/nvim/screen.c:2200]: this must be the culprit

**Comment by teto** [comment]
seems like I've broken something indeed. Sad that tests havent' caught it, it's a well covered area. Will look into it.

**Comment by teto** [comment]
I guess the `foldinfo.fi_lines >= 0` should be `> `, in your clip, is the `const` in a fold ?

**Comment by akinsho** [comment]
Hmm 🤔 I've also noticed that my [indentLine](https://github.com/Yggdroot/indentLine) plugin is no longer showing indents lines on *certain* lines and I have folds enabled I hadn't thought to check if it was related to whether it was only in folds but that would make sense since it primarily was affecting indented lines which would likely be in folds. I reverted my build but can rebuild master and confirm if it only happens within folds

**Comment by akinsho** [comment]
Here's a screen grab. I've enabled foldcolumn and it appears to happen within the folds. Just above where the fold starts the indent lines are visible but not within it
image

**Comment by teto** [comment]
this was a silly mistake of mine. Should be fixed in https://github.com/neovim/neovim/pull/13643 . I've tested and it looks ok. If that's ok for you too, I will update the test to prevent such a regression.

**Comment by rafikdraoui** [comment]
One way to easily trigger this is with `set foldmethod=indent`. For example, with the text:

```
aaaa
  bbbbb
  ccccc
```

searching for `b` doesn't highlight the matches.


I can confirm that #13643 fixes this for me.

**Comment by cvlmtg** [comment]
> I guess the `foldinfo.fi_lines >= 0` should be `> `, in your clip, is the `const` in a fold ?

yes, it is in a fold (foldmethod is set to syntax and the word is inside a function, hence a fold)

anyway I tried to write a `const` outside the function and this happens:

https://user-images.githubusercontent.com/6401008/103357084-9dfa6900-4ab2-11eb-96ab-2fb8d3a343c7.mov

as for your PR I'm not sure if I can do some tests today, will try as soon as I can though

**Comment by akinsho** [comment]
I've just rebuilt from master and I'm seeing normal highlighting again on my end 👍🏿 , thanks for the quick fix.
