### PR TITLE
fix(tui): don't wait for DA1 response when stdin is closed

### LINKED ISSUE #35744: When terminal closes, neovim closes later
### Problem

When the terminal is closed which neovim is in, neovim will not close instantly, but linger for around 1-2 seconds and then close.

Tested it on Hyprland with terminals: kitty, xterm, alacritty

### Steps to reproduce

`nvim --clean`
Close the terminal window (or `:lua vim.uv.kill(vim.api.nvim_get_proc(vim.uv.os_getppid()).ppid,1)`)

### Expected behavior

Neovim closing as soon as the terminal window closes.

### Nvim version (nvim -v)

v0.12.0-dev-f89e1eb

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Linux 6.16.6-arch1-1

### Terminal name/version

kitty 0.42.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #35744

### CODE REVIEW

**Review by gpanders — APPROVED** [review]

File: test/functional/terminal/tui_spec.lua [hunk 1]
```diff
@@ -2382,6 +2382,16 @@ describe('TUI', function()
     screen:expect({ any = vim.pesc('[Process exited 1]') })
   end)
 
+  it('exits immediately when stdin is closed #35744', function()
+    local chan = api.nvim_get_option_value('channel', { buf = 0 })
+    local pid = fn.jobpid(chan)
+    fn.chanclose(chan)
+    retry(nil, 50, function()
```
Comment (justinmk) [inline test/functional/terminal/tui_spec.lua:2389]: is 50ms intentional? this fails sometimes. https://github.com/neovim/neovim/pull/41365

Comment (zeertzjq) [reply test/functional/terminal/tui_spec.lua:2389]: It's "immediately"
