### PR TITLE
[RFC] Bugfixes

### LINKED ISSUE #3188: Reference count of job callbacks not respected after `:so`
When I run the script `job.vim` in a loop, `:while 1|so job.vim|endw`, ASAN catches a problem.
`job.vim`:
```vim
function! s:JobHandler(job_id, data, event)
endfunction

let s:callbacks = {
\ 'on_stdout': function('s:JobHandler'),
\ 'on_stderr': function('s:JobHandler'),
\ 'on_exit': function('s:JobHandler')
\ }
let job = jobstart('echo', s:callbacks)
```

Problem seems to be, that every job uses the same callback function reference, but with every new `so job.vim` the reference count for the reference is set back.  So after starting a lot of jobs,  we don't have enough references to "free", because the reference count is too low.

```c
==29236==ERROR: AddressSanitizer: heap-use-after-free on address 0x6100000415dc at pc 0x000000d623dc bp 0x7ffddd5a7e30 sp 0x7ffddd5a7e28
READ of size 4 at 0x6100000415dc thread T0
    #0 0xd623db in user_func_unref /home/oni-link/git/neovim/src/nvim/eval.c:19759:7
    #1 0xe43686 in free_term_job_data_event /home/oni-link/git/neovim/src/nvim/eval.c:21120:5
    #2 0x1610062 in queue_process_events /home/oni-link/git/neovim/src/nvim/event/queue.c:144:7
    #3 0xecb5f1 in normal_cmd /home/oni-link/git/neovim/src/nvim/normal.c:496:5
    #4 0xea9fb5 in main_loop /home/oni-link/git/neovim/src/nvim/main.c:747:7
    #5 0xe95b68 in main /home/oni-link/git/neovim/src/nvim/main.c:534:3
    #6 0x7f81f44edf9f in __libc_start_main (/lib64/libc.so.6+0x1ff9f)
    #7 0x442165 in _start (/home/oni-link/git/neovim/build/bin/nvim+0x442165)

0x6100000415dc is located 156 bytes inside of 185-byte region [0x610000041540,0x6100000415f9)
freed by thread T0 here:
    #0 0x4d80a0 in __interceptor_cfree.localalias.1 /home/oni-link/git/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:35
    #1 0xac6434 in xfree /home/oni-link/git/neovim/src/nvim/memory.c:108:3
    #2 0xd5df41 in func_free /home/oni-link/git/neovim/src/nvim/eval.c:19736:3
    #3 0xd6257e in user_func_unref /home/oni-link/git/neovim/src/nvim/eval.c:19763:7
    #4 0xe434c2 in free_term_job_data_event /home/oni-link/git/neovim/src/nvim/eval.c:21117:5
    #5 0x1610062 in queue_process_events /home/oni-link/git/neovim/src/nvim/event/queue.c:144:7
    #6 0xecb5f1 in normal_cmd /home/oni-link/git/neovim/src/nvim/normal.c:496:5
    #7 0xea9fb5 in main_loop /home/oni-link/git/neovim/src/nvim/main.c:747:7
    #8 0xe95b68 in main /home/oni-link/git/neovim/src/nvim/main.c:534:3
    #9 0x7f81f44edf9f in __libc_start_main (/lib64/libc.so.6+0x1ff9f)

previously allocated by thread T0 here:
    #0 0x4d8228 in malloc /home/oni-link/git/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:40
    #1 0xac6114 in try_malloc /home/oni-link/git/neovim/src/nvim/memory.c:62:15
    #2 0xac6354 in xmalloc /home/oni-link/git/neovim/src/nvim/memory.c:96:15
    #3 0xd5a06b in ex_function /home/oni-link/git/neovim/src/nvim/eval.c:19000:10
    #4 0x123a294 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2195:5
    #5 0x121905e in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:621:20
    #6 0x5d7595 in do_source /home/oni-link/git/neovim/src/nvim/ex_cmds2.c:2523:3
    #7 0x5d3a54 in cmd_source /home/oni-link/git/neovim/src/nvim/ex_cmds2.c:2234:12
    #8 0x5d3b70 in ex_source /home/oni-link/git/neovim/src/nvim/ex_cmds2.c:2212:3
    #9 0x123a294 in do_one_cmd /home/oni-link/git/neovim/src/nvim/ex_docmd.c:2195:5
    #10 0x121905e in do_cmdline /home/oni-link/git/neovim/src/nvim/ex_docmd.c:621:20
    #11 0xf32b6b in nv_colon /home/oni-link/git/neovim/src/nvim/normal.c:4080:18
    #12 0xed7487 in normal_cmd /home/oni-link/git/neovim/src/nvim/normal.c:912:3
    #13 0xea9fb5 in main_loop /home/oni-link/git/neovim/src/nvim/main.c:747:7
    #14 0xe95b68 in main /home/oni-link/git/neovim/src/nvim/main.c:534:3
    #15 0x7f81f44edf9f in __libc_start_main (/lib64/libc.so.6+0x1ff9f)

SUMMARY: AddressSanitizer: heap-use-after-free /home/oni-link/git/neovim/src/nvim/eval.c:19759:7 in user_func_unref
```

### PR DESCRIPTION
**Pull request by tarruda**
Fix #3188 #2322 #3197

### CODE REVIEW

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -140,6 +140,7 @@ UI *tui_start(void)
 
   // listen for SIGWINCH
   signal_watcher_init(&loop, &data->winch_handle, ui);
+  data->winch_handle.events = queue_new_child(loop.events);
```
Comment (oni-link) [inline src/nvim/tui/tui.c]: That queue is never freed (when calling tui_stop()).

Comment (tarruda) [inline src/nvim/tui/tui.c]: :+1:

**Comment by justinmk** [comment]
Can these be tested? I may have repro for the job callback issue, when I get back to a computer later.

**Comment by tarruda** [comment]
> Can these be tested? I may have repro for the job callback issue, when I get back to a computer later.

I've added a test for the job callback change. As for the others:

- The signal watcher change only happens in certain terminals and is not applicable to the lua UI, so can't automate the test
- I couldn't find a way to deterministically reproduce the `remote_ui_attach` issue
- The `event_init` change is possible to test, but might require some adapting to our test infrastructure(we need a way to pass specific command-line flags to individual tests)
- The terminal change I was only able to reproduce with FZF

File: test/functional/job/job_spec.lua [hunk 2]
```diff
@@ -188,6 +189,41 @@ describe('jobs', function()
...
+    local script = [[
+      function! g:JobHandler(job_id, data, event)
+      endfunction
+
+      let g:callbacks = {
+      \ 'on_stdout': function('g:JobHandler'),
+      \ 'on_stderr': function('g:JobHandler'),
+      \ 'on_exit': function('g:JobHandler')
+      \ }
+      let job = jobstart('cat -', g:callbacks)
```
Comment (justinmk) [inline test/functional/job/job_spec.lua]: on windows, `pause` might be a good substitue for `cat -`.

Comment (tarruda) [inline test/functional/job/job_spec.lua]: When we run tests on windows, it might be a good a idea to use msys to provide a minimal set of unix command line tools
