### PR TITLE
fix(eval): fixup for empty modifier in fnamemodify

### LINKED ISSUE #16367: fnamemodify with empty modifiers always returns empty string
### Neovim version (nvim -v)

NVIM v0.6.0-dev+600-gf71be1f87

### Vim (not Nvim) behaves the same?

no, vim 8.2.3623

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.9.0 (fed349aa)

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

nvim --clean
:echo fnamemodify('/bin/bash', '')

### Expected behavior

Display `/bin/bash`.

### Actual behavior

Won't display anything.

### PR DESCRIPTION
**Pull request by clason**
https://github.com/neovim/neovim/commit/1dbbaf89bf5d3bcd1edac3af9938c2e2dd18f816 erroneously removed a check for empty modifier and a PVS fix. Restore that check and fix.

Fixes #16367

### CODE REVIEW

File: src/nvim/eval/funcs.c [hunk 1]
```diff
@@ -2663,7 +2663,7 @@ static void f_fnamemodify(typval_T *argvars, typval_T *rettv, FunPtr fptr)
   char buf[NUMBUFLEN];
   const char *fname = tv_get_string_chk(&argvars[0]);
   const char *const mods = tv_get_string_buf_chk(&argvars[1], buf);
-  if (fname == NULL) {
+  if (mods == NULL || fname == NULL) {
     fname = NULL;
   } else if (mods != NULL && *mods != NUL) {
```
Comment (zeertzjq) [inline src/nvim/eval/funcs.c:2668]: This line and the `*mods != NUL` line below should also need change, otherwise `len` is still zero when `*mods` is NULL.

Comment (clason) [reply src/nvim/eval/funcs.c]: Thanks, I missed that change -- and now #16367 is _actually_ fixed :)

File: src/nvim/eval/funcs.c [hunk 2]
```diff
@@ -2665,12 +2665,14 @@ static void f_fnamemodify(typval_T *argvars, typval_T *rettv, FunPtr fptr)
...
   if (mods == NULL || fname == NULL) {
     fname = NULL;
-  } else if (mods != NULL && *mods != NUL) {
+  } else {
     len = strlen(fname);
-    size_t usedlen = 0;
-    if (*mods != NUL) {
-      (void)modify_fname((char_u *)mods, false, &usedlen,
-                         (char_u **)&fname, &fbuf, &len);
+    if (mods != NULL && *mods != NUL) {
```
Comment (zeertzjq) [inline src/nvim/eval/funcs.c:2670]: The `mods != NULL` is redundant because if `mods == NULL`, control flow will never reach here. See also <https://github.com/neovim/neovim/commit/607d1cc80dc8c559684822ba2d35bb71f634aafa> (PVS/V560).

Comment (clason) [reply src/nvim/eval/funcs.c]: That was in the code before my change, so something must have reverted that PVS fix. It's back in.

File: src/nvim/eval/funcs.c [hunk 3]
```diff
@@ -2663,14 +2663,16 @@ static void f_fnamemodify(typval_T *argvars, typval_T *rettv, FunPtr fptr)
...
     len = strlen(fname);
-    size_t usedlen = 0;
     if (*mods != NUL) {
-      (void)modify_fname((char_u *)mods, false, &usedlen,
-                         (char_u **)&fname, &fbuf, &len);
+      size_t usedlen = 0;
+      if (*mods != NUL) {
+        (void)modify_fname((char_u *)mods, false, &usedlen,
+                           (char_u **)&fname, &fbuf, &len);
+      }
```
Comment (zeertzjq) [inline src/nvim/eval/funcs.c:2675]: This `*mods != NUL` already been checked
```suggestion
      (void)modify_fname((char_u *)mods, false, &usedlen,
                         (char_u **)&fname, &fbuf, &len);
```

**Review by zeertzjq — APPROVED** [review]

**Comment by clason** [comment]
TSAN failure looks unrelated.
