### PR TITLE
fix(messages): avoid spurious newline in headless mode with cmdheight=0

### LINKED ISSUE #38490: messages: cmdheight=0 prepends extra line to headless output
### Problem

```
 $ nvim --clean --cmd 'set cmdheight=0' --headless -c 'echo 1 | q'

1 
```

### Steps to reproduce

`nvim --clean --cmd 'set cmdheight=0' --headless -c 'echo 1 | q'`

### Expected behavior

No extra line

### Nvim version (nvim -v)

v0.12.0-dev-2707+gc9e961994b

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Debian Sid

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

from repo

### PR DESCRIPTION
**Pull request by Linykq**
## Problem
When running nvim in headless mode with `cmdheight=0`, an extra newline is prepended to output (eg. `nvim --clean --cmd 'set cmdheight=0' --headless -c 'echo 1 | q' ` prints `\n1` instead of `1`), because `!ui_has(kUIMessages)` is always true in headless mode, causing `p_ch == 0` in `msg_start()` to unconditionally trigger `msg_putchar('\n')` which  writes a newline to stdout.

## Solution
When in headless printf mode with `p_ch == 0` and no prior output on the current line, call `msg_puts_display("\n", ...)` directly instead of `msg_putchar('\n')`, so the grid is still updated for correct screen positioning but no newline is written to stdout.

fix #38490

### CODE REVIEW

**Comment by przepompownia** [comment]
Out of curiosity: were the description and solution generated by some LLM?

Regardless, it seems to fix the issue.

**Comment by justinmk** [comment]
please add a test here: https://github.com/neovim/neovim/blob/ae2829ee35c1fb8649f9d4046c5af48987193d03/test/functional/ui/cmdline_spec.lua#L1275

 You can [run the test](https://neovim.io/doc/user/dev_test.html#dev-filter-test) like this:

    make functionaltest TEST_FILE=test/functional/ui/cmdline_spec.lua

File: test/functional/ui/cmdline_spec.lua [hunk 1]
```diff
@@ -1700,4 +1700,21 @@ describe('cmdheight=0', function()
...
+      'NONE',
+      '-i',
+      'NONE',
+      '--headless',
+      '--cmd',
+      'set cmdheight=0',
+      '-c',
+      'echo 1',
+      '+q',
+    })
```
Comment (justinmk) [inline test/functional/ui/cmdline_spec.lua]: can spawn_wait be used https://github.com/neovim/neovim/blob/ae2829ee35c1fb8649f9d4046c5af48987193d03/test/functional/core/main_spec.lua#L82

Comment (Linykq) [reply test/functional/ui/cmdline_spec.lua]: I think so. I will modify it.

**Comment by przepompownia** [comment]
Thanks!
