### PR TITLE
fix(extui): clear cmdline buffer for first message

### LINKED ISSUE #21150: vim.ui_attach: document the effect of return value of callback
In the current implementation, if `vim.ui_attach()` callback returns `true`, the event is not passed to UI, otherwise it is still passed to UI. For `ext_popupmenu` this difference is unnoticeable in TUI because TUI doesn't not support `ext_popupmenu`, but it is noticeable in a UI that supports `ext_popupmenu`. Anyway, this behavior is neither documented nor tested.

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Cmdline buffer is not cleared for a new message (since c973c7ae),
          resulting in an incorrect spill indicator. When the cmdline
          buffer is cleared, "msg_row" is not invalidated, resulting in
          an error. The extui module is untested.
          Return value of `vim.ui_attach()->callback` is undocumented.
Solution: Clear the cmdline buffer for the first message in an event
          loop iteration. Ensure msg_row passed as end_row does not
          exceed buffer length.
          Add `messages_spec2.lua` to test the extui module, keeping in
          mind that test coverage will greatly increase if this UI is made
          the default. As such, only tests for specific extui functionality
          unlikely to be covered by tests leveraging the current message grid.
          Document the return value of `vim.ui_attach()->callback`, it seems
          to make sense, and is also used to suppress remote UI events in
          `messages_spec2.lua`.

Fix #21150

### CODE REVIEW

File: test/functional/ui/extui_spec.lua [hunk 1]
```diff
@@ -0,0 +1,48 @@
+local n = require('test.functional.testnvim')()
```
Comment (justinmk) [inline test/functional/ui/extui_spec.lua]: let's name this file `messages_spec2.lua` , to start migrating away from the "extui" nonce

File: test/functional/ui/extui_spec.lua [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+local Screen = require('test.functional.ui.screen')
+
+local clear, command, feed, exec_lua = n.clear, n.command, n.feed, n.exec_lua
+
+describe('extui', function()
```
Comment (justinmk) [inline test/functional/ui/extui_spec.lua]:
```suggestion
describe('messages/pager', function()
```

File: test/functional/ui/extui_spec.lua (hunk 1 above)
Comment (justinmk) [reply test/functional/ui/extui_spec.lua]:
```suggestion
-- Tests for the buitin Lua UI provider for messages, pager, dialog.

local n = require('test.functional.testnvim')()
```

Comment (luukvbaal) [reply test/functional/ui/extui_spec.lua]: Would coining it the "event UI" make sense maybe? And thus name this `event_ui_spec.lua`

File: runtime/lua/vim/_meta/builtin.lua [hunk 3]
```diff
@@ -267,6 +267,8 @@ function vim.wait(time, callback, interval, fast_only) end
 ---             - {set_cmdheight}? (`boolean`) If false, avoid setting
 ---               'cmdheight' to 0 when `ext_messages` is enabled.
 --- @param callback fun(event: string, ...) Function called for each UI event
+--- @return boolean A truthy value indicates `callback` handled the event.
+---                 Nvim will not send the event to remote UIs.
```
Comment (justinmk) [inline runtime/lua/vim/_meta/builtin.lua]: if the callback returns truthy, is it fair to say the callback canceled (or silenced) the event?

```suggestion
--- @return boolean Truthy if `callback` canceled the event (Nvim will not send the event to remote UIs).
```

Comment (luukvbaal) [reply runtime/lua/vim/_meta/builtin.lua]: It only makes sense to return a truthy value if the callback did something to display the information contained in the event. Then remote UIs don't need to process the event themselves, but rather just show the new Nvim state (which they will at the next "flush" event). Cancelling doesn't seem the right word for that.

At least that's how I interpret this interaction. @bfredl might know better.

File: test/functional/ui/extui_spec.lua (hunk 1 above)
Comment (justinmk) [reply test/functional/ui/extui_spec.lua]: "Event UI" implies it's some special variant. But it's not, it's just a UI implemented in the way Nvim UIs should be implemented :)

This will apply to other things in the future too, that's why it's useful to avoid quirky names sooner than later.

File: runtime/lua/vim/_meta/builtin.lua (hunk 3 above)
Comment (justinmk) [reply runtime/lua/vim/_meta/builtin.lua]: > Cancelling doesn't seem the right word for that.

Agreed. "consumed" (or "handled" as you indeed had it)

```suggestion
--- @return boolean Truthy if `callback` handled the event, thus Nvim should not propagate it further.
```

Comment (luukvbaal) [reply runtime/lua/vim/_meta/builtin.lua]: It's not the return value of this function actually so this annotation is incorrect (maybe that caused some confusion, and the lint failure?). It's a possible return value for `callback` that Nvim handles as such.

**Comment by luukvbaal** [comment]
Why is luacheck failing😡

**Comment by clason** [comment]
Because it doesn't follow the standard `foo_spec.lua` pattern?

File: runtime/doc/lua.txt [hunk 4]
```diff
@@ -1076,8 +1076,10 @@ vim.ui_attach({ns}, {opts}, {callback})                      *vim.ui_attach()*
                       enable events for the respective UI element.
                     • {set_cmdheight}? (`boolean`) If false, avoid setting
                       'cmdheight' to 0 when `ext_messages` is enabled.
-      • {callback}  (`fun(event: string, ...)`) Function called for each UI
-                    event
+      • {callback}  (`fun(event: string, ...): any`) Function called for each
+                    UI event. A truthy return value signals to Nvim that the
+                    event is handled, in which case it is not propagated to
+                    remote UIs.
```
Comment (justinmk) [inline runtime/doc/lua.txt:1082]: I would frame this as "other UIs", not "remote UIs". UIs are just UIs, doesn't matter where they come from. For example, there could be multiple in-process Lua UIs, right?

File: test/functional/messages2_spec.lua [hunk 5]
```diff
@@ -0,0 +1,73 @@
+local n = require('test.functional.testnvim')()
```
Comment (justinmk) [inline test/functional/messages2_spec.lua:1]: should this file live in functional/ui/ rather than the top-level of functional/ ?

File: runtime/doc/lua.txt (hunk 4 above)
Comment (luukvbaal) [reply runtime/doc/lua.txt:1082]: > there could be multiple in-process Lua UIs, right?

Yes and the way it's currently implemented is that those in-process Lua "UIs" still receive the event even after a truthy value has been returned, hence the distinction.

This difference in behavior could be questioned but a possibly valid reason for it is that `vim.ui_attach()` is a more likely extension point for event listeners that don't want to be an actual UI, e.g. just implementing some sort of logging.
