### PR TITLE
fix(autocmds): prevent autocmds with once=true from calling itself

### LINKED ISSUE #25526: autocmds with `once=true` can execute more than once
### Problem

The code below will execute the autocmd recursively.
This is of course a simplified repro. The one I encountered in the wild was not so obvious.

```lua
vim.api.nvim_create_autocmd("User", {
  once = true,
  pattern = "test",
  group = vim.api.nvim_create_augroup("test", { clear = true }),
  callback = function()
    vim.api.nvim_exec_autocmds("User", { pattern = "test" })
  end,
})
vim.api.nvim_exec_autocmds("User", { pattern = "test" })
```

### Steps to reproduce

run the repro with `nvim -u bug.lua`

### Expected behavior

the autocmd should only be ran once

### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

na

### Operating system/version

linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-256-kitty

### Installation

bob

### PR DESCRIPTION
**Pull request by Vinschers**
Fix #25526.

Problem:
Autocmd with `once=true` that calls itself would enter a recursion loop since callback runs before aucmd's deletion.
The suggested fix does not work because deletion of autocmd breaks the reference needed in the callback function.

Solution:
Modify the aucmd's variable to have a NULL pattern. This makes it impossible to enter a recursion with once=true.
After callback, restore the original variable and continue to the regular deletion.

### CODE REVIEW

File: src/nvim/autocmd.c [hunk 1]
```diff
@@ -2104,12 +2104,20 @@ char *getnextac(int c, void *cookie, int indent, bool do_concat)
...
+    }
+
     // Can potentially reallocate kvec_t data and invalidate the ac pointer
-    if (call_autocmd_callback(ac, apc)) {
+    if (call_autocmd_callback(&ac_copy, apc)) {
       // If an autocommand callback returns true, delete the autocommand
       oneshot = true;
     }
 
+    ac->pat = ac_copy.pat; // Restore aucmd reference
```
Comment (ii14) [inline src/nvim/autocmd.c:2119]: `ac` can be invalidated by the callback at this point, access through `kv_A(*acs, apc->auidx)`.

**Review by ii14 — CHANGES_REQUESTED** [review]

**Review by ii14 — APPROVED** [review]

**Comment by ii14** [comment]
Code has to be formatted though, run `make format`. I think it's just that there has to be two spaces between source code and inline comment.

**Comment by lewis6991** [comment]
Meaningful test failure:

```lua
 test/functional/lua/snippet_spec.lua @ 243: vim.snippet correctly indents with newlines
test/functional/testnvim.lua:127: EOF was received from Nvim. Likely the Nvim process crashed.

stack traceback:
	test/functional/testnvim.lua:127: in function 'exec_lua'
	test/functional/lua/snippet_spec.lua:35: in function 'test_expand_success'
	test/functional/lua/snippet_spec.lua:254: in function <test/functional/lua/snippet_spec.lua:243>
```

**Comment by justinmk** [comment]
Looks reasonable, can you fix the test failure (seems like Nvim is crashing).

Please rebase to get updated CI.

**Comment by justinmk** [comment]
Pushed a fixup.

File: test/functional/autocmd/autocmd_spec.lua [hunk 2]
```diff
@@ -250,6 +250,23 @@ describe('autocmd', function()
...
+        once = true,
+        pattern = nil,
+        callback = function()
+          vim.g.count = vim.g.count + 1
+          vim.api.nvim_exec_autocmds('User', { pattern = nil })
+        end,
+      })
+      vim.api.nvim_exec_autocmds('User', { pattern = nil })
+    ]]
+    eq(1, eval('g:count')) -- Added autocommands should not be executed
```
Comment (zeertzjq) [inline test/functional/autocmd/autocmd_spec.lua:269]: What is "Added autocommands"?

Comment (justinmk) [reply test/functional/autocmd/autocmd_spec.lua:269]: that's a copy paste. i'll cleanup this test.

File: test/functional/autocmd/autocmd_spec.lua [hunk 3]
```diff
@@ -250,6 +250,25 @@ describe('autocmd', function()
...
       fn.execute('autocmd Tabnew')
     )
+
+    --
+    -- :autocmd does not recursively call ++once Lua handlers.
+    --
+    exec_lua [[vim.g.count = 0]]
+    eq(0, eval('g:count'))
+    exec_lua [[
+      vim.g.count = 0
```
Comment (zeertzjq) [inline test/functional/autocmd/autocmd_spec.lua:260]: Why is `vim.g.count = 0` run twice?
