### PR TITLE
[RFC] Fix appimage problem

### LINKED ISSUE #9341: nvim.appimage: certain `system` calls show neovim version instead of command output
- `nvim --version`: v0.3.2-980-g857a7312d
- Operating system/version: 
    - Debian testing (buster)
    - `Linux 4.18.0-1-amd64 #1 SMP Debian 4.18.6-1 (2018-09-06) x86_64 GNU/Linux`
- Terminal name/version: `zsh 5.6.2 (x86_64-debian-linux-gnu)`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:echo system('rustfmt --version')
```

### Actual behaviour

Produces the `nvim --version` output in the resulting buffer, instead:

```
NVIM v0.3.2-980-g857a7312d                                                                                                                                                  
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=
gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I
/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/us
r/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-cbc055ff-e87a-4ba2-90c0-93f3831ec630

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info

Press ENTER or type command to continue
```

### Expected behaviour

the result of `rustfmt --version`, which is (on my local machine as of writing this issue):

```
rustfmt 0.99.4-stable (1c40881 2018-08-27)
```

I have gotten this to work by extracting the appimage and symlinking it to `/usr/bin/nvim`, but I am curious if there's a way around this that doesn't involve extraction of the image. I can check version for other things easily within the appimage variant, e.g. `:echo system('ghc --version')` gives in the un-extracted appimage:

```
The Glorious Glasgow Haskell Compilation System, version 8.2.2                                                                                                              

Press ENTER or type command to continue
```

### PR DESCRIPTION
**Pull request by erw7**
fixes #9341 
[ci skip]

### CODE REVIEW

File: scripts/genappimage.sh [hunk 1]
```diff
@@ -62,8 +62,17 @@ delete_blacklisted
...
-ln -s usr/bin/nvim AppRun
+# Appimage set the ARGV0 environment variable. This causes problems in zsh.
+# To prevent this, we use wrapper script to unset ARGV0 as AppRun.
+# See https://github.com/AppImage/AppImageKit/issues/852
+#
+cat << 'EOF' > AppRun
+#!/bin/bash
+
+unset ARGV0
+exec "$(dirname "$(readlink  -f "${0}")")/usr/bin/nvim" ${@+"$@"}
```
Comment (justinmk) [inline scripts/genappimage.sh]: is `${@+"$@"}`  correct?  Looking at https://mywiki.wooledge.org/BashGuide/Parameters , I only see `${x:+y}`, not `${x+y}`. 

What is `${@+"$@"}` supposed to do?
