### PR TITLE
fix(treesitter): allow optional directive captures

### LINKED ISSUE #23100: treesitter optional captures causes error
### Problem

I have a injection like this:
```query
(call_expression
  arguments: (argument_list
    (interpreted_string_literal)? @sql (#offset! @sql 0 1 0 -1)
    (raw_string_literal)?         @sql (#offset! @sql 0 1 0 -1)
  )
)
```

This captues both of

```go
db.Where("THIS STRING IS WHAT IT CAPTURE")
db.Where(`THIS ALSO BE CAPTURED`)
```

What causes error:
```go
db.Where()
// Error detected while processing BufReadPost Autocommands for "*":
// Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:21: Error executing lua: /usr/share/nvim/runtime/filetype.lua:22: BufReadPost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:429: attempt to index a nil value
// stack traceback:
// /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:429: in function 'handler'
// /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:586: in function 'apply_directives'
// /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:710: in function '(for generator)'
// /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:663: in function 'f'
// /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:123: in function 'tcall'
// /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:262: in function 'parse'
// /usr/share/nvim/runtime/lua/vim/treesitter.lua:89: in function '_create_parser'
// /usr/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
// /usr/share/nvim/runtime/lua/vim/treesitter.lua:469: in function 'start'
// .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
// ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
// ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
// ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function // <...er/start/nvimtreesitter/lua/nvimtreesitter/configs.lua:132>
```
https://github.com/neovim/neovim/blob/1ca77c222b00215657bae416eba5d280a1d9dc29/runtime/lua/vim/treesitter/query.lua#L429
where `match[capture_id]` is nil.

### Steps to reproduce

use this injection and write some `go` code like `db.Where()`.
```query
;; queries/go/injections.scm
(call_expression
  function: (selector_expression
    operand: (_)
    field: (field_identifier) @_function_name (#match? @_function_name "(Select|Where|Delete|Joins|Order|Expr)")
  )
  arguments: (argument_list
    (interpreted_string_literal)? @sql (#offset! @sql 0 1 0 -1)
    (raw_string_literal)? @sql (#offset! @sql 0 1 0 -1)
  )
)
```

### Expected behavior

no node is captured

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Arch Linux(WSL)

### Terminal name/version

Windows Terminal

### $TERM environment variable

tmux-256color

### Installation

pacman official

### PR DESCRIPTION
**Pull request by ribru17**
Problem: optional Tree-sitter captures lead to nil access by directives

Solution: just return if the captured node doesn't exist

Fixes #23100

### CODE REVIEW

**Comment by wookayin** [comment]
It would be nice if we can add test cases for this.

File: test/functional/treesitter/parser_spec.lua [hunk 1]
```diff
@@ -547,6 +547,36 @@ int x = INT_MAX;
...
   end)
 
+  describe('when setting the node for an injection', function()
+    before_each(function()
+      insert([[
+print()
+      ]])
+    end)
+
+    it('should not error when encountering optional captures', function()
```
Comment (gpanders) [inline test/functional/treesitter/parser_spec.lua:557]:
```suggestion
    it('should not error when encountering optional captures #23100', function()
```

**Review by gpanders — APPROVED** [review]

File: test/functional/treesitter/parser_spec.lua [hunk 2]
```diff
@@ -547,6 +547,36 @@ int x = INT_MAX;
...
   end)
 
+  describe('when setting the node for an injection', function()
+    before_each(function()
+      insert([[
+print()
+      ]])
+    end)
+
+    it('should not error when encountering optional captures #23100', function()
```
Comment (justinmk) [inline test/functional/treesitter/parser_spec.lua:557]:
```suggestion
    it('handles optional captures #23100', function()
```

or "supports". this test name will already be absurdly long because of all the nesting
