### PR TITLE
fix(highlight): avoid red underline in floating window with blend

### LINKED ISSUE #14453: underline has a wrong colour if the text is overlayed by a transparent floating window
- `nvim --version`: NVIM v0.5.0-dev+1281-gecf075eb2
- `vim -u DEFAULTS` (version: ) behaves differently? does not have `nvim_open_win` and `winblend`
- Operating system/version: Archlinux
- Terminal name/version: kitty 0.20.2
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

use this [file.lua](https://paste.sh/ZRdQEKs1#K5jFWBNQi-NUcuT-yaCc3xsC) and observe the underline.

```
nvim -u NORC file.lua
```

The first line is overlayed by a transparent floating window, the second one is not. 

### Actual behaviour

image

### Expected behaviour

image

--- 

Maybe it's because `xterm-kitty` has the ability to use a different underline colour so it changed to red, while `xterm-256color` does not, the underline has the same colour as the text regardless of the setting.
This only happens when the text is below a floating window with `winblend=100`.

One of the solutions is changing the `guisp` manually to a colour I want but that doesn't seem good, ideally it should not change to red when it's overlayed by a floating window. 
The other solution is changing my `$TERM` to `xterm-256color` but I'd lose the capability of changing the underline colour which is useful for LSP diagnostics.

Thanks in advance!

### PR DESCRIPTION
**Pull request by glepnir**
Problem: When a floating window with high winblend uses a highlight group
         with underline (but without guisp), the underline appears red.

Solution: Only blend the special color (for underline/undercurl) if the
          foreground highlight actually has underline or undercurl set.
          Otherwise, ignore the special color.

Fix #14453

### CODE REVIEW

File: test/functional/ui/float_spec.lua [hunk 1]
```diff
@@ -8824,6 +8827,56 @@ describe('float window', function()
                                                             |
         ]])
       end
+      -- issue: #14453
```
Comment (justinmk) [inline test/functional/ui/float_spec.lua]: I see that nvim_open_win() is doing something unusual, so I guess this test can't be combined with one of the existing tests above.

A brief description will help (and a blank line for navigation):

```suggestion

      -- winblend highlight with underline (but without guisp) in a floatwin. #14453
```

File: test/functional/ui/float_spec.lua [hunk 2]
```diff
@@ -8473,6 +8475,7 @@ describe('float window', function()
         occaecat cupidatat non proident, sunt in culpa
         qui officia deserunt mollit anim id est
         laborum.]])
+      curbuf = api.nvim_get_current_buf()
```
Comment (justinmk) [inline test/functional/ui/float_spec.lua]: in the rest of this file, curbuf is a function, so reassigning it to a different type is confusing.
```suggestion
      local curbufnr = curbuf()
```
