### PR TITLE
[RFC] Fix some keys not working in ext_popupmenu

### LINKED ISSUE #10471: When using ext_popupmenu, it is not possible to operate the keys according to the manual
- `nvim --version`: NVIM v0.4.0-1256-g564d415d2
- `gvim -u DEFAULTS` (version: ) behaves differently? Yes(8.1.1640)
- Operating system/version: N/A
- Terminal name/version: N/A
- `$TERM`: N/A

### Steps to reproduce using `nvim -u NORC`

```
nvim-qt -- -u NORC
i
/usr/include/<C-x><C-f><PageDown><PageUP>
```

### Actual behaviour
Nothing happens.

### Expected behaviour
&lt;PageUp&gt;	  Select a match several entries back, but don't insert it.
&lt;PageDown&gt;	  Select a match several entries further, but don't insert it.

I confirmed that `popupmenu_select` event for the item currently selected by `<PageUp>` or  `<PageDown>` is always generated. Since `nvim` has no way of knowing the number of items displayed in the popupmenu of the UI, I do not know how to fix this.

### PR DESCRIPTION
**Pull request by erw7**
fixes #10471.

### CODE REVIEW

File: src/nvim/popupmnu.c [hunk 1]
```diff
@@ -136,7 +136,10 @@ void pum_display(pumitem_T *array, int size, int selected, bool array_changed,
       } else {
         ui_call_popupmenu_select(selected);
       }
-      return;
+      pum_height = ui_pum_height();
```
Comment (bfredl) [inline src/nvim/popupmnu.c]: Only gathering the height here is too restrictive. We should allow the UI to set the height after receiving the items, which might change the height it needs.

Comment (bfredl) [reply src/nvim/popupmnu.c]: I e `pum_get_height()` should always use the most recent value set by the UI.

Comment (erw7) [reply src/nvim/popupmnu.c]: @bfredl For now, I changed `pum_get_height()` to call `ui_pum_get_height()`. I think that there is a problem if `<PageUp>` etc. call `pum_get_height()` before the UI calls `nvim_ui_pum_set_height()`. How do I synchronize? Can you give me some implementation hint? Should I call `LOOP_PROCESS_EVENTS_UNTIL(& main_loop, NULL, -1, is_pum_set_height_done())` with `pum_get_height()`? A deadlock occurred when trying to synchronize using the above method immediately after `ui_call_popupmenu_show()`.

Comment (bfredl) [reply src/nvim/popupmnu.c]: There should be no need to synchronize anything. As long as the UI sends the `nvim_ui_pum_set_height()`  before `nvim_input('<PageUp>')` it should be processed before. If an indirect mapping or something uses a slightly outdated value, it is not a catastrophe. Let's not make it more complicated than needed.

Comment (bfredl) [reply src/nvim/popupmnu.c]: Though you could mark nvim_ui_pum_set_height() as `NVIM_API_FAST`, so the events cannot get reordered internally, in case nvim was CPU-blocked by an unrelated timer, or something.

File: src/nvim/popupmnu.c [hunk 2]
```diff
@@ -136,7 +136,6 @@ void pum_display(pumitem_T *array, int size, int selected, bool array_changed,
       } else {
         ui_call_popupmenu_select(selected);
       }
-      return;
```
Comment (bfredl) [inline src/nvim/popupmnu.c]: why remove this `return` ?

File: src/nvim/popupmnu.c [hunk 3]
```diff
@@ -852,7 +855,8 @@ void pum_recompose(void)
 /// Only valid when pum_visible() returns TRUE!
 int pum_get_height(void)
 {
-  return pum_height;
+  int ui_pum_height = ui_pum_get_height();
+  return ui_pum_height ? ui_pum_height : pum_height;
```
Comment (bfredl) [inline src/nvim/popupmnu.c]: use `pum_external && ui_pum_height` as the condition.

File: src/nvim/popupmnu.c [hunk 4]
```diff
@@ -237,6 +236,10 @@ void pum_display(pumitem_T *array, int size, int selected, bool array_changed,
         pum_height = row - above_row;
       }
     }
+    if (pum_external) {
```
Comment (bfredl) [inline src/nvim/popupmnu.c]: this seems quite ad-hoc. vim already carries 1-2 items between pages it seems. I don't think we should do any extra adjustment for `pum_external` only.

File: CMakeLists.txt [hunk 5]
```diff
@@ -118,7 +118,7 @@ set(NVIM_VERSION_PATCH 0)
 set(NVIM_VERSION_PRERELEASE "-dev") # for package maintainers
 
 # API level
-set(NVIM_API_LEVEL 6)         # Bump this after any API change.
+set(NVIM_API_LEVEL 7)         # Bump this after any API change.
```
Comment (bfredl) [inline CMakeLists.txt]: no need to bump it, PRERELEASE is already true.

File: src/nvim/popupmnu.c (hunk 2 above)
Comment (erw7) [reply src/nvim/popupmnu.c]: I removed this `return;` so that `pum_height` does not become 0 when UI does not call `nvim_pum_set_height()`. For now, I moved `return;` right after `ui_call_popupmenu_select()`.

If the UI does not call `nvim_pum_set_height()`, the value calculated from the line of the cursor and the number of lines on the screen is used as `pum_height`. I think this is better than 0 or a fixed value of 10.

Comment (bfredl) [reply src/nvim/popupmnu.c]: Sure, makes sense.

File: runtime/doc/api.txt [hunk 6]
```diff
@@ -1892,4 +1892,13 @@ nvim_ui_try_resize_grid({grid}, {width}, {height})
                     {width}   The new requested width.
                     {height}  The new requested height.
 
+                                                    *nvim_ui_pum_set_height()*
+nvim_ui_pum_set_height({height})
```
Comment (bfredl) [inline runtime/doc/api.txt]: This will be autogenerated from the docstring at the method in  `api/ui.c`, so you need to update the text there.

File: src/nvim/popupmnu.c (hunk 3 above)
Comment (erw7) [reply src/nvim/popupmnu.c]: Please tell me the reason to change the condition so. The reasons I think are:

1. When a `UI` that does not support `ext_popupmenu` uses `nvim_pum_set_height()`, it does not use its `pum_height`.
1.  To avoid unnecessary calls to `ui_pum_get_height()`.
1. To clarify the meaning of the code when others see this code in the future.

If it is 1, check that `ui->ui_ext[kUIpopupmenu]` is true in `nvim_set_pum_height()`.

In case of 2, change as follows:

```Diff
--- a/src/nvim/popupmnu.c
+++ b/src/nvim/popupmnu.c
@@ -855,8 +855,8 @@ void pum_recompose(void)
 /// Only valid when pum_visible() returns TRUE!
 int pum_get_height(void)
 {
-  int ui_pum_height = ui_pum_get_height();
-  return pum_external && ui_pum_height ? ui_pum_height : pum_height;
+  int ui_pum_height = pum_extara ? ui_pum_get_height() : 0;
+  return ui_pum_height ? ui_pum_height : pum_height;
 }

 void pum_set_boundings(dict_T *dict)
```

In the case of 3, write an appropriate comment. I think the above is more appropriate than changing the conditions.

Comment (bfredl) [reply src/nvim/popupmnu.c]: Well, the point is just what the code says: whenever `pum_external` is false external popupmenu is disabled, so `pum_height` should be used (which I guess implies all of the above). Though I agree just substituting it into the ternary doesn't look very good.  Could rewrite it like so:

```
int pum_get_height(void)
{
  if (pum_external) {
    int ui_pum_height = ui_pum_get_height();
    if (ui_pum_height) {
      return ui_pum_height;
    }
  }
  return pum_height;
}
```

**Comment by justinmk** [comment]
could you please rebase?

**Comment by erw7** [comment]
> could you please rebase?

I Rebased.

**Comment by bfredl** [comment]
Thanks, merged!

File: test/functional/ui/popupmenu_spec.lua [hunk 7]
```diff
@@ -368,6 +370,125 @@ describe('ui/ext_popupmenu', function()
...
+    end)
+
+    it('an error occurs when ext_popupmenu is false', function()
+      local ok, err, _
+      ok, _ = pcall(meths.ui_pum_set_height, 1)
+      eq(ok, true)
+      screen:set_option('ext_popupmenu', false)
+      ok, err = pcall(meths.ui_pum_set_height, 1)
+      eq(ok, false)
+      matches('.*: It must support the ext_popupmenu option', err)
```
Comment (justinmk) [inline test/functional/ui/popupmenu_spec.lua]: Could use `pcall_err` next time.
