### PR TITLE
fix(terminal): free terminal if close_buffer() closes a closed terminal

### LINKED ISSUE #16257: `termopen` leaks memory if `on_exit` runs `bdelete` (fzf)
### Neovim version (nvim -v)

v0.6.0-dev+563-gb74916cfd

### Vim (not Nvim) behaves the same?

N/A? In Vim 8.2.3582, memory usage grows much slowly when spamming fzf.

### Operating system/version

Ubuntu 21.04

### Terminal name/version

GNOME Terminal 3.38.1 using VTE 0.62.3 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

tmux-256color

### Installation

built from the repository

### How to reproduce the issue

Minimal reproducer extracted from this part of fzf vim integration:
https://github.com/junegunn/fzf/blob/e4c3ecc57e99f4037199f11b384a7f8758d1a0ff/plugin/fzf.vim#L845-L856
```vim
" leak.vim
" this leaks memory
nnoremap x :call termopen('echo 1', opts)<CR>
let opts = {}
function! opts.on_exit(...)
  bdelete
endfunction

" this does not leak memory
nnoremap o :call termopen('echo 1')<CR>i<CR>
```
Run `nvim --clean -u leak.vim` and hold down `x` key. Check the memory usage with tools like htop or run memory profilers like heaptrack. Roughly 200kb is leaked for each invocation.

Screenshot of heaptrack profile result:
image

### Expected behavior

Should not leak memory. Specifically, `terminal_destroy` should be called. 

### Actual behavior

`terminal_destroy` is not called if `on_exit` runs `bdelete`, resulting in memory leak.

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #16257

IDK if this can be tested. `valgrind` showed the leaked memory as described in #16257 as `still reachable`, and ASAN cannot detect them.

### CODE REVIEW

**Comment by zeertzjq** [comment]
I find it a bit hard to deal with the case where the channel's multiqueue has already been freed. Closing.

**Comment by gpanders** [comment]
Hmm I wonder if we can just do

```
if (term->closed) {
  if (status == -1 && !term->refcount) {
    terminal_destroy(term);
  }
}
```

I think this is okay, because status is only ever `-1` from `close_buffer`, and if we're calling `terminal_close` from `close_buffer` when `term->closed` is `true` that means the channel has already exited.

What do you think?

**Comment by zeertzjq** [comment]
Can the call to `channel_decref` be omitted?

**Comment by gpanders** [comment]
I think so because the terminal does not own the channel, but vice versa, so the terminal object isn't responsible for managing the channel's ref count.

**Comment by zeertzjq** [comment]
Oops, I deleted the message. It was "can the call to `channel_decref()` be omitted?".

**Comment by gpanders** [comment]
Let's try [this](https://github.com/neovim/neovim/pull/16264#issuecomment-963744353) and see if it breaks any tests (and how many). Do you want to revive this PR, or shall I make a new one?

**Comment by zeertzjq** [comment]
The FreeBSD error is a bit hard to understand.

**Comment by zeertzjq** [comment]
Maybe `channel_decref` is still needed.
```
2 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!1 lua references were leaked!
```

**Comment by jamessan** [comment]
Also in ASAN:

```
2021-11-09T02:33:02.7145356Z [ RUN      ] :terminal prints more lines than the screen height and exits will push extra lines to scrollback: 118.05 ms OK
2021-11-09T02:33:02.7806044Z ==================== File /home/runner/work/neovim/neovim/build/log/ubsan.38736 ====================
2021-11-09T02:33:02.7807272Z = =================================================================
2021-11-09T02:33:02.7809346Z = ==38736==ERROR: AddressSanitizer: heap-use-after-free on address 0x625000020154 at pc 0x00000199608d bp 0x7ffdd44e03b0 sp 0x7ffdd44e03a8
2021-11-09T02:33:02.7810763Z = READ of size 4 at 0x625000020154 thread T0
2021-11-09T02:33:02.7811569Z ====================================================================================================
2021-11-09T02:33:02.7813462Z nan ms test/helpers.lua:257: Found runtime errors in logfile(s): /home/runner/work/neovim/neovim/build/log/ubsan.38736
2021-11-09T02:33:02.7814542Z 
2021-11-09T02:33:02.7815266Z stack traceback:
2021-11-09T02:33:02.7816449Z 	test/helpers.lua:257: in function 'check_logs'
2021-11-09T02:33:02.7817639Z 	test/functional/helpers.lua:892: in function <test/functional/helpers.lua:888>
2021-11-09T02:33:02.7818467Z 
```

Might get some more details running it locally.

**Comment by zeertzjq** [comment]
Maybe something is need to indicated whether `close_cb` has been called or not. It is possible that `close_cb` has already been called and has put `term_delayed_free` into event loop, but `terminal_destroy()` hasn't been called yet, so the buffer is still referencing the terminal.

**Comment by gpanders** [comment]
The owning channel should probably be incrementing `term->refcount` to indicate that it still owns the terminal...

**Comment by zeertzjq** [comment]
Right now `term->refcount` is only changed when processing `K_EVENT`.

**Comment by gpanders** [comment]
0855e0e seems to fix at least one of the ASAN leaks for me locally, let's see what this does.

**Comment by zeertzjq** [comment]
Well, I think this will cause even more memory leak?

**Comment by gpanders** [comment]
> Well, I think this will cause even more memory leak?

Why do you think so? The channel increments the ref count on creation and decrements it when it's done with the terminal, so the behavior in most cases shouldn't change. This does prevent `terminal_close` from inadvertently destroying the terminal before the channel is done with it, however (which was causing the UAF in the last ASAN failure).

**Comment by zeertzjq** [comment]
`term_delayed_free` is put in event loop by `close_cb`, which is only called in `terminal_close` or when the user presses a key in a closed terminal.

**Comment by gpanders** [comment]
There are only 3 ways a terminal can be destroyed:

1. The job is terminated prematurely (`:bdelete!`). This calls `close_cb` because `status` is `-1` and `term->closed` is `false`.
2. The job ends normally and a user presses a key on the "Process exited" screen. This also calls `close_cb` from `terminal_enter`.
3. The job ends normally and a user calls `:bdelete` without pressing a key. This does not call `close_cb` since `term->closed` is true, but it will check the `refcount` and, if it is 0, call `terminal_destroy`.

Scenario 3 is the one we are dealing with here. So you're right that this still leaks memory, because now `term->refcount` is non-zero so `terminal_destroy` is not being called. Maybe instead of `terminal_destroy` we need to call `close_cb`? That will ensure the channel is cleaned up as well.

**Comment by zeertzjq** [comment]
> I find it a bit hard to deal with the case where the ~channel~ main loop's multiqueue has already been freed.

Back to this problem.

**Comment by gpanders** [comment]
I edited my comment right before you posted:

---

I think I was wrong when I said this btw:

    I think so because the terminal does not own the channel, but vice versa, so the terminal object isn't responsible for managing the channel's ref count.

Shouldn't `close_cb` be safe to call, since the terminal object is the one maintaining a reference to the channel. That reference is dropped in `term_delayed_free`, so as long as the terminal exists the channel should exist.

**Comment by zeertzjq** [comment]
I'm think about calling `channel_decref` earlier. Not really sure.

**Comment by zeertzjq** [comment]
`term->destroy` is unused. I'm try to find more information about it.

**Comment by gpanders** [comment]
I think we're closing in. This is almost good to go, but `term_delayed_free` is still being called twice which is causing a UAF (and an ASAN failure). This is happening because `terminal_enter` executes `:bwipeout` after calling `close_cb`, which then of course calls `terminal_close` and `close_cb` again. So we just need a way to indicate that `close_cb` has already been called (which of course you already said [2 hours ago](https://github.com/neovim/neovim/pull/16264#issuecomment-963773845). I just needed to catch up :) ).

**Comment by zeertzjq** [comment]
`term->destroy` has ever been used. It wasn't used when it was first destroyed. <https://github.com/neovim/neovim/commit/cdedd89d228a016a4e433968702e9e3ce5165e7d>

**Comment by zeertzjq** [comment]
I'm looking into some `exiting`-related stuff. If it is always true that channel has been freed when exiting, we can just call `terminal_destroy` instead.

**Comment by zeertzjq** [comment]
I think the only case where `close_buffer()` is called while `exiting` is `true` is in `free_all_mem()`. Or am I missing something?

**Comment by zeertzjq** [comment]
The `nvim_open_term` case may be different from the channel case.

**Comment by zeertzjq** [comment]
The only case where `close_buffer()` is called while `exiting` is `true` is inside `free_all_mem()`, where the event loop has already been freed (and so has the channels). Calling `terminal_destroy` should be fine here.

**Review by gpanders — APPROVED** [review]

**Comment by gpanders** [comment]
I'll let this marinate for a bit in case anyone else wants to review.

File: src/nvim/terminal.c [hunk 1]
```diff
@@ -278,15 +293,16 @@ void terminal_close(Terminal *term, int status)
   term->closed = true;
 
   if (status == -1 || exiting) {
-    // If status is -1, this was called by close_buffer(buffer.c).  Or if
-    // exiting, we must inform the buffer the terminal no longer exists so that
-    // close_buffer() doesn't call this again.
+    // If status is -1 so this was called by close_buffer(), or if inside
+    // process_teardown(), we must inform the buffer the terminal no longer
+    // exists so that close_buffer() doesn't call this again.
```
Comment (jamessan) [inline src/nvim/terminal.c:298]:
```suggestion
    // If status is -1, this was called by close_buffer() or inside
    // process_teardown().  We must inform the buffer the terminal no longer
    // exists so that close_buffer() doesn't call this again.
```

**Review by jamessan — APPROVED** [review]
Small comment rewording, but otherwise looks good after squash.  This sounds like the true fix for the issue I was trying to fix in https://github.com/neovim/neovim/pull/6195 :)

File: src/nvim/terminal.c (hunk 1 above)
Comment (zeertzjq) [reply src/nvim/terminal.c:298]: Well, this is not what I wanted to mean.

**Review by jamessan — APPROVED** [review]

**Comment by zeertzjq** [comment]
When handling `K_EVENT`, `term->refcount` is non-zero, so maybe this can still be a problem. However it is hard to find a way to properly test this.

**Comment by zeertzjq** [comment]
Wait, memory is still leaking when using `:enew`.

**Comment by zeertzjq** [comment]
> When handling `K_EVENT`, `term->refcount` is non-zero, so maybe this can still be a problem. However it is hard to find a way to properly test this.

Oh, memory is still leaking if I run `:lua vim.api.nvim_command('terminal echo'); vim.defer_fn(function() vim.api.nvim_input('A'); vim.defer_fn(function() vim.api.nvim_command('bdelete') end, 100) end, 100);`.

**Comment by zeertzjq** [comment]
> > When handling `K_EVENT`, `term->refcount` is non-zero, so maybe this can still be a problem. However it is hard to find a way to properly test this.
> 
> Oh, memory is still leaking if I run `:lua vim.api.nvim_command('terminal echo'); vim.defer_fn(function() vim.api.nvim_input('A'); vim.defer_fn(function() vim.api.nvim_command('bdelete') end, 100) end, 100);`.

Setting `buf_handle` to `0` should fix that.

**Comment by zeertzjq** [comment]
I just found out that channels closed with `nvim_open_term()` are never freed because `channel_close()` never calls `channel_decref()` on a channel whose type if `kChannelStreamInternal`.

**Review by gpanders — APPROVED** [review]
