### PR TITLE
fix(float): don't relative float win itself

### LINKED ISSUE #24129: after nvim_win_set_config, the floatwin moves as the cursor moves
### Problem

it seems after called nvim_win_config to a floatwin, the floatwin's relative target became to itself. so on every cursor movement, it moves itself too.

### Steps to reproduce

* nvim --clean +'so test.lua'
* jkjk

test.lua
```
local api = vim.api

local bufnr = api.nvim_create_buf(false, true)
api.nvim_buf_set_lines(bufnr, 0, -1, false, { "a", "b", "c", "d" })

local winid = vim.api.nvim_open_win(bufnr, true, { relative = "win", row = 3, col = 3, width = 12, height = 3 })

api.nvim_win_set_config(winid, { relative = "win", row = 3, col = 3, width = 12, height = 3 })
```

### Expected behavior

the floatwin still anchors to the window/cursor when it's been created.

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

st-256color

### Installation

pacman

### PR DESCRIPTION
**Pull request by glepnir**
Problem: when reconfig current float win without win key in `nvim_win_set_config` will cause float win position changed when move.

Solution: don't relative itself.

Fix #24129

### CODE REVIEW

File: src/nvim/api/win_config.c [hunk 1]
```diff
@@ -730,7 +730,16 @@ static bool parse_float_config(Dict(float_config) *config, FloatConfig *fconfig,
   }
 
   if (relative_is_win) {
-    fconfig->window = curwin->handle;
+    if (reconf) {
+      win_T *wp = handle_get_window(config->win);
```
Comment (willothy) [inline src/nvim/api/win_config.c:734]: I may be wrong but couldn't you just check that `config->win != curwin->handle` instead of fetching and comparing the pointers? That way this could still be a single statement like below and no checks for the actual window need to be done in `parse_float_config`, since validation is done in `nvim_open_win` and `nvim_win_set_config`.

```lua
if (!reconf || config->win != curwin->handle) {
  fconfig->window = curwin=>handle;
}
```

Comment (willothy) [reply src/nvim/api/win_config.c:734]: You may also need to account for `config->win = 0` (I don't think `handle_get_window` does this?)

Comment (glepnir) [reply src/nvim/api/win_config.c:734]: emm i guess we can do it early .

File: src/nvim/api/win_config.c [hunk 2]
```diff
@@ -240,6 +240,14 @@ void nvim_win_set_config(Window window, Dict(float_config) *config, Error *err)
   // reuse old values, if not overridden
   FloatConfig fconfig = new_float ? FLOAT_CONFIG_INIT : win->w_float_config;
 
+  if (!new_float && HAS_KEY(config, float_config, relative) && striequal(config->relative.data,
```
Comment (bfredl) [inline src/nvim/api/win_config.c:243]: it's a bit weird to replicate already existing parsing logic. I'd do this check on the parsed value in `fconfig` after the call to `!parse_float_config` (or even inside it, passing in win is fine)

File: src/nvim/api/win_config.c [hunk 3]
```diff
@@ -938,8 +938,8 @@ static void parse_border_style(Object style, FloatConfig *fconfig, Error *err)
   }
 }
 
-static bool parse_float_config(Dict(float_config) *config, FloatConfig *fconfig, bool reconf,
-                               bool new_win, Error *err)
+static bool parse_float_config(win_T *wp, Dict(float_config) *config, FloatConfig *fconfig,
+                               bool reconf, bool new_win, Error *err)
```
Comment (zeertzjq) [inline src/nvim/api/win_config.c:942]: It seems that `new_win` is no longer needed as it can be replaced by `wp == NULL`.

File: src/nvim/api/win_config.c [hunk 4]
```diff
@@ -958,6 +958,12 @@ static bool parse_float_config(Dict(float_config) *config, FloatConfig *fconfig,
     has_relative = true;
     fconfig->external = false;
     if (fconfig->relative == kFloatRelativeWindow) {
+      if (reconf) {
+        win_T *target_win = find_window_by_handle(config->win, err);
+        if (!target_win || target_win == wp) {
+          return false;
```
Comment (zeertzjq) [inline src/nvim/api/win_config.c:964]: I don't think this `return` is correct. This causes the other keys in the config to be silently ignored.

Comment (glepnir) [reply src/nvim/api/win_config.c:964]: when win no target win or target is itself the other keys still need parse ? this set should execute  right ?

Comment (zeertzjq) [reply src/nvim/api/win_config.c:964]: That will not solve the usage mentioned in #24129

File: src/nvim/api/win_config.c [hunk 5]
```diff
@@ -1141,6 +1141,16 @@ static bool parse_float_config(Dict(win_config) *config, WinConfig *fconfig, boo
...
 
   if (relative_is_win || is_split) {
+    if (reconf && relative_is_win) {
+      win_T *target_win = find_window_by_handle(config->win, err);
+      if (!target_win) {
+        return false;
+      }
+
+      if (target_win == wp && curwin == wp) {
+        api_set_error(err, kErrorTypeException, "floating can not relative itself");
```
[the remark this answers is not in the document]
Comment (glepnir) [reply src/nvim/api/win_config.c:1151]: oh. yup..a mistake

File: src/nvim/api/win_config.c [hunk 6]
```diff
@@ -1141,6 +1141,17 @@ static bool parse_float_config(Dict(win_config) *config, WinConfig *fconfig, boo
...
 
   if (relative_is_win || is_split) {
+    if (reconf && relative_is_win) {
+      win_T *target_win = find_window_by_handle(config->win, err);
+      if (!target_win) {
+        return false;
+      }
+
+      if (target_win == wp) {
+        api_set_error(err, kErrorTypeException, "floating can not relative itself");
```
Comment (zeertzjq) [inline src/nvim/api/win_config.c:1151]:
```suggestion
        api_set_error(err, kErrorTypeException, "floating window cannot be relative to itself");
```

File: test/functional/ui/float_spec.lua [hunk 7]
```diff
@@ -9227,6 +9227,14 @@ describe('float window', function()
       eq(restcmd, fn.winrestcmd())
       eq(config, api.nvim_win_get_config(0))
     end)
+
+    it("through an error when relative itself", function()
```
Comment (zeertzjq) [inline test/functional/ui/float_spec.lua:9231]:
```suggestion
    it("error when relative to itself", function()
```
