### PR TITLE
fix(float): prevent truncation of title that fits exactly

### LINKED ISSUE #36872: Floating window title might get truncated even if it fits
### Problem

After #28387 title might be truncated even when it fits in the width.

### Steps to reproduce

1. Create the following 'init-float-title.lua' file:

    ```lua
    local title = 'abcde'
    local config = {
      relative = 'editor',
      row = 1,
      col = 1,
      height = 3,
      width = vim.fn.strchars(title),
      border = 'single',
      title = title,
    }
    vim.api.nvim_open_win(vim.api.nvim_create_buf(false, true), false, config)
    ```

2. `nvim --clean -u init-float-title.lua`. Observe that the title is `<bcde`, although `abcde` fits.

This root cause is probably #28387.

### Expected behavior

Floating window title is not truncated if it can fit full into available width.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-1783+ged9abb1851

### Vim (not Nvim) behaves the same?

No, doesn't have this exact functnionality

### Operating system/version

EndeavourOS Linux x86_64, 6.17.9-arch1-1

### Terminal name/version

Ghostty 1.2.3-arch2

### $TERM environment variable

xterm-ghostty

### Installation

Appimage

### PR DESCRIPTION
**Pull request by arkriny**
Problem:
The `over_flow` parameter in `grid_draw_bordertext` always added 1 for the '<' character. As a result, titles that fit exactly were still truncated with an unnecessary '<'.

Solution:
Adjust `over_flow` only when the actual overflow is greater than 0.

Fix #36872

### CODE REVIEW

File: test/functional/ui/float_spec.lua [hunk 1]
```diff
@@ -2104,6 +2104,67 @@ describe('float window', function()
       assert_alive()
     end)
 
+    it('does not truncate title when it exactly fits window width #36872', function()
```
Comment (justinmk) [inline test/functional/ui/float_spec.lua]: can this test be combined with the above test, by adding a 2nd floatwin? that avoids quite a lot of new test code. the screen test can just test both at the same time.

Comment (arkriny) [reply test/functional/ui/float_spec.lua]: I used the footer since they share logic. With two windows, it becomes even harder to track what affects what.

These float tests feel largely boilerplate for multigrid cases. I think there's room to improve them, making it easier to add new tests instead of modifying existing ones just to avoid a +200 diff.
