### PR TITLE
fix(api): convert title_pos string in nvim_win_get_config

### LINKED ISSUE #21695: title_pos == 1 when you get win config with vim.api.nvim_win_get_config
### Describe the bug

title_pos == 1 when you get win config with vim.api.nvim_win_get_config

### Steps to reproduce

vim.api.nvim_set_keymap("n", "<Leader>l", "", {
  callback = function()
    local conf_ = {
      width = 10,
      relative = "editor",
      anchor = "NW",
      style = "minimal",
      border = "rounded",
      title = "Hoge",
      title_pos = "center",
    }
    local conf = vim.fn.extend(conf_, {
        height = 10,
        row = 10,
        col = 10,
      })
    local buf = vim.api.nvim_create_buf(false, true)
    local win =  vim.api.nvim_open_win(buf, true, conf)
    print(vim.inspect(vim.api.nvim_win_get_config(win)))

  end,
  noremap = true,
  silent = true,
  desc = "title_pos == 1",
  nowait = true,
})

### Expected behavior

{
  anchor = "NW",
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  col = {
    [false] = 10,
    [true] = 3
  },
  external = false,
  focusable = true,
  height = 10,
  relative = "editor",
  row = {
    [false] = 10,
    [true] = 3
  },
  title = { { "Hoge", "FloatTitle" } },
  title_pos = 1,
  width = 10,
  zindex = 50
}

### Neovim version (nvim -v)

v0.9.0-dev-633+g904c13e6b-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

13.1

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

brew install --HEAD neovim

### PR DESCRIPTION
**Pull request by glepnir**
use `left center right` instead of `0,1,2` in `nvim_win_get_config`.

Fix #21695

### CODE REVIEW

**Comment by Cassin01** [comment]
Thank you

File: src/nvim/api/win_config.c [hunk 1]
```diff
@@ -299,7 +299,15 @@ Dictionary nvim_win_get_config(Window window, Error *err)
           ADD(titles, ARRAY_OBJ(tuple));
         }
         PUT(rv, "title", ARRAY_OBJ(titles));
-        PUT(rv, "title_pos", INTEGER_OBJ(config->title_pos));
+        char *title_pos;
+        if (config->title_pos == 0) {
```
Comment (bfredl) [inline src/nvim/api/win_config.c:303]: could use the defined constants like `kAlignLeft` etc
