### PR TITLE
fix(fs): prevent duplicate path separator (#21497)

### LINKED ISSUE #21497: vim.fs.find prepends an extra slash when match is in the root directory (`/`)
### Neovim version (nvim -v)

NVIM v0.8.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux 5.15.81-1-lts

### Terminal name/version

alacritty 0.11.0 (8dbaa0bb)

### $TERM environment variable

not set

### Installation

pacman -S neovim

### How to reproduce the issue

```
:lua print(vim.inspect(vim.fs.find('usr', { path = '/usr/lib/bash', upward = true, type = 'directory' })))
```

### Expected behavior

Output would be `{ "/usr" }`

### Actual behavior

Output is `{ "//usr" }`

It's fine in any directory one level deep, e.g. if changing the above to:
```
:lua print(vim.inspect(vim.fs.find('lib', { path = '/usr/lib/bash', upward = true, type = 'directory' })))
```
Output is `{ "/usr/lib" }`

### PR DESCRIPTION
**Pull request by ehaynes99**
Fixes #21497

### CODE REVIEW

File: runtime/lua/vim/fs.lua [hunk 1]
```diff
@@ -74,7 +74,11 @@ end
 
 ---@private
 local function join_paths(...)
-  return table.concat({ ... }, '/')
+  local path_elements = vim.tbl_map(function(element)
+    return element:gsub('/$', '')
+  end, { ... })
+
+  return table.concat(path_elements, '/')
```
Comment (ii14) [inline runtime/lua/vim/fs.lua:81]: How about just this? It will remove all empty segments from the path.
```suggestion
  return (table.concat({ ... }, '/'):gsub('//+', '/'))
```

Comment (ehaynes99) [reply runtime/lua/vim/fs.lua:81]: I thought about that, but in general I try to avoid masking errors in input. E.g. it'll just magically work for:

```lua
vim.inspect(vim.fs.find('something', {
  path = 'broken////////////////input',
  upward = true,
  type = 'directory',
}))
```

But if you prefer the simplicity, I don't feel too strongly about it.

Comment (ii14) [reply runtime/lua/vim/fs.lua:81]: This path is still valid though, at least on Linux.

Comment (lewis6991) [reply runtime/lua/vim/fs.lua]: I think the main concern is performance. This function could be used in hot loops.
