### PR TITLE
fix(tui): don't crash when nvim__screenshot() is called with bad path

### LINKED ISSUE #34593: `vim.api.nvim__screenshot()` in home dir causes crash.
### Problem

Currently if you call `vim.api.nvim__screenshot('~/foo.txt')` neovim immediately crashes.

### Steps to reproduce

nvim --clean
:lua vim.api.nvim__screenshot('~/foo.txt')

Produces: 
```
fish: Job 1, 'nvim $argv' terminated by signal SIGSEGV (Address boundary error)
```

### Expected behavior

This should either display an error message if nvim can't interpret `~` as home, or it should produce a screenshot in the home directory without crashing.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-519+gbf1d4e9793 Build type: Debug LuaJIT 2.1.1744317938 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

vim does not have `vim.api.nvim__screenshot()`

### Operating system/version

Arch Linux x86_64 - Kernel 6.14.6-arch1-1

### Terminal name/version

kitty 0.42.0

### $TERM environment variable

xterm-kitty

### Installation

Build from source

### PR DESCRIPTION
**Pull request by The-Briel-Deal**
Problem: Currently vim.api.nvim__screenshot crashes when called with an invalid path. This is because we don't check if `fopen()` returns a null pointer.

Solution: If `fopen()` return a null pointer, print a message and return.

Fixes: https://github.com/neovim/neovim/issues/34593

### CODE REVIEW

**Review by zeertzjq — CHANGES_REQUESTED** [review]
The TUI process isn't supposed to print messages.

**Comment by The-Briel-Deal** [comment]
> The TUI process isn't supposed to print messages.

I gotcha, thats good to know, i'm guessing this same check can be done on the server process before this request is sent? Either way I think we should probably return if fopen() returns NULL. I'll do that for now and I'll see if I can figure out how to do this log on the serverside before the request is sent.

**Comment by The-Briel-Deal** [comment]
> The TUI process isn't supposed to print messages.

Alright, well I dropped the error message logging and we just return now if the path isn't valid. I don't see a good way to check if a call to `fopen()` will be able to create a file before calling it. Also we can't reliably perform the path check on the server since the UI (the process which writes the screenshot) could be on a different machine.

Regardless, I feel like returning instead of crashing is still better behavior here, even if we don't log.

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -1657,6 +1657,9 @@ void tui_screenshot(TUIData *tui, String path)
   grid->col = 0;
 
   FILE *f = fopen(path.data, "w");
+  if (f == NULL) {
+    return;
+  }
```
Comment (zeertzjq) [inline src/nvim/tui/tui.c]: Perhaps this block should be moved to the top of the function? The cursor movement shouldn't be done if the screenshot fails.

**Review by zeertzjq — APPROVED** [review]
