### PR TITLE
Fix colors in terminal by maintaining COLORTERM

### LINKED ISSUE #10836: set COLORTERM='truecolor' in :terminal when using truecolor GUI/TUI
See https://gist.github.com/XVilka/8346728#true-color-detection for what this does.

Current behavior is to unset COLORTERM.

### PR DESCRIPTION
**Pull request by ThomasFeher**
There are multiple issues with colors not working as expected in Neovim's
terminal (e.g., #10836, https://github.com/junegunn/fzf.vim/issues/1065,
https://github.com/nvim-telescope/telescope.nvim/issues/228). The reason is that
`COLORTERM` is not set, or better actively unset by Neovim.
I don't know why it is done, it is there since the file _pty_process_unix.c_ was
added, maybe a workaround at that time, because Truecolor wasn't supported?

Removing the removal of `COLORTERM` does fix the issue for my environment
(Linux, Alacritty, Tmux, `termguicolor` enabled) when using `bat` in Neovim
terminal as well as in Fzf.vim and Telescope.nvim.

Fixes https://github.com/neovim/neovim/issues/10836

### CODE REVIEW

File: src/nvim/os/pty_process_unix.c [hunk 1]
```diff
@@ -160,7 +160,6 @@ static void init_child(PtyProcess *ptyproc)
   os_unsetenv("COLUMNS");
   os_unsetenv("LINES");
   os_unsetenv("TERMCAP");
-  os_unsetenv("COLORTERM");
```
Comment (bfredl) [inline src/nvim/os/pty_process_unix.c:163]: hmm we should not just passively pass trough COLORTERM, but maybe it should be set to `truecolor` if 'termguicolors' is true and '256' otherwise.

Comment (ThomasFeher) [reply src/nvim/os/pty_process_unix.c:163]: Done.

**Comment by ThomasFeher** [comment]
CI seems to get stuck. I rebased onto master but it got stuck again. Any idea if
this is related to the actual changes or is that some general problem?

**Comment by jamessan** [comment]
> Any idea if
> this is related to the actual changes or is that some general problem?

That particular failure has been sporadically happening.  It's not related to your changes.

Can you squash the two commits?  Then it should be good to merge.

**Comment by ThomasFeher** [comment]
Squashed.
