### PR TITLE
vim-patch:8.2.3943: compiler warning from gcc for uninitialized variable

### LINKED ISSUE #9429: Warning when compiling diff.c
### Steps to reproduce

Start make, CONF_OPT_FEAT = --with-features=normal

### Expected behaviour

No warnings from the compiler

### Version of Vim

8.2.3941

### Environment

Debian, gcc 11.2.0

### Logs and stack traces

```shell
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -fno-strength-reduce -Wall -Wno-deprecated-declarations -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/diff.o diff.c
diff.c: In function ‘diff_try_update’:
diff.c:3284:26: warning: ‘hunk’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 3284 |         hunk->count_orig = oldcount;
      |         ~~~~~~~~~~~~~~~~~^~~~~~~~~~
diff.c:1639:18: note: ‘hunk’ was declared here
 1639 |     diffhunk_T  *hunk;
      |                  ^~~~
```

### PR DESCRIPTION
**Pull request by dundargoc**
Problem:    Compiler warning from gcc for uninitialized variable.
Solution:   Initialize variable. (closes vim/vim#9429)
https://github.com/vim/vim/commit/491669701c72578f273db53e579d8a03a9deac0c

### CODE REVIEW

**Comment by dundargoc** [comment]
PVS warns about the same thing which is why I ported it.

**Review by lewis6991 — APPROVED** [review]

File: src/nvim/diff.c [hunk 1]
```diff
@@ -1536,7 +1536,7 @@ static void diff_read(int idx_orig, int idx_new, diffio_T *dio)
   long off;
   int i;
   int notset = true;  // block "*dp" not set yet
-  diffhunk_T *hunk;
+  diffhunk_T *hunk = NULL;
```
Comment (zeertzjq) [inline src/nvim/diff.c:1539]: Missing comment

**Review by zeertzjq — APPROVED** [review]
