### PR TITLE
fix(diagnostic): nvim_echo takes three args

### LINKED ISSUE #15686: [LSP] diagnostic.lua:634: Expected 3 arguments
### Neovim version (nvim -v)

v0.6.0-dev+284-gc2a65921d

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macos

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

source code build

### How to reproduce the issue

E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/diagnostic.lua:634: Expected 3 arguments  
```
634:    vim.api.nvim_echo({"No more valid diagnostics to move to", "WarningMsg"})
```

### Expected behavior

shoudl output `No more valid diagnostics to move to`

### Actual behavior

Shows E5108

### PR DESCRIPTION
**Pull request by clason**
Fixup for https://github.com/neovim/neovim/pull/15585
Closes https://github.com/neovim/neovim/issues/15686

### CODE REVIEW

File: runtime/lua/vim/diagnostic.lua [hunk 1]
```diff
@@ -631,7 +631,7 @@ local function diagnostic_move_pos(opts, pos)
   local win_id = opts.win_id or vim.api.nvim_get_current_win()
 
   if not pos then
-    vim.api.nvim_echo({"No more valid diagnostics to move to", "WarningMsg"})
+    vim.api.nvim_echo({"No more valid diagnostics to move to", "WarningMsg"}, true, {})
```
Comment (ray-x) [inline runtime/lua/vim/diagnostic.lua:634]: try this:

 vim.api.nvim_echo({{"No more valid diagnostics to move to", "WarningMsg"}}, true, {})
Write

Comment (clason) [reply runtime/lua/vim/diagnostic.lua]: Ah, I was missing the outer braces -- thanks! (I've not finished my morning coffee yet...)
