### PR TITLE
fix(treesitter): use capture metadata range if exists

### LINKED ISSUE #4181: offset directive does not work for conceal
### Describe the bug

offset directive does not modify capture range for conceal
it works for textobjects i can do something like `vis` to visual select the inner part of a string (without quotation marks)
but for conceal it causes `"hello world"` to be concealed to `...` instead of `"..."`

### To Reproduce

`highlights.scm`
```
;extends

(((string) @string (#offset! @string 0 1 0 -1)) (#set! conceal ""))
```
<br>

`textobjects.scm`
```
;extends

(string) @string.outer
((string) @string.inner (#offset! @string.inner 0 1 0 -1))
```

### Expected behavior

`"hello world"` should be concealed to `"..."`

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v17.0.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 12.2.1 20230111
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.1.6-arch1-3",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Mon, 16 Jan 2023 12:51:23 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - regex               ✓ . . . .
  - diff                ✓ . . . .
  - markdown_inline     ✓ . . . ✓
  - help                ✓ . . . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ . ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - c                   ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-588+g99cf11128
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/msia/repos/neovim/build/cmake.config -I/home/msia/repos/neovim/src -I/home/msia/repos/neovim/.deps/usr/include -I/usr/include -I/home/msia/repos/neovim/build/src/nvim/auto -I/home/msia/repos/neovim/build/include
Compiled by root

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by danilax999**
Fixes nvim-treesitter/nvim-treesitter#4181

### CODE REVIEW

File: runtime/lua/vim/treesitter/highlighter.lua [hunk 1]
```diff
@@ -236,7 +236,8 @@ local function on_line_impl(self, buf, line, is_spell_nav)
         break
       end
 
-      local start_row, start_col, end_row, end_col = node:range()
+      local range = metadata[capture] and metadata[capture].range or { node:range() }
+      local start_row, start_col, end_row, end_col = unpack(range)
```
Comment (lewis6991) [inline runtime/lua/vim/treesitter/highlighter.lua:240]: Better to use `vim.treesitter.get_range(node, bufnr, metadata)`
