### PR TITLE
cmdheight=0: fix bugs part2

### LINKED ISSUE #19184: cmdheight=0:  whichkey floating window opened whilst in commandline don't redraw
### Neovim version (nvim -v)

NVIM v0.8.0-dev+1988-g8f5bcfb0e

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.4

### Terminal name/version

Kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### How to reproduce the issue

Apologies, but I don't know how to easily recreate the sequence of events that leads to this bug without using the [whichkey.nvim](https://github.com/folke/which-key.nvim) plugin, but I thought it was better to report it than leave it, as someone might recognize what might be happening better than I do.

https://user-images.githubusercontent.com/22454918/176856986-f2874d72-bdef-4413-9eab-954bb333c733.mov

As the video above shows, if a user uses a plugin like which key that tries to open a sequence of floating window whilst using something I guess like `getchar` the floating windows do not properly get cleared when the next one is triggered.

Reproduction steps:
1. Install whichkey.nvim
2. Add a nested mapping e.g. `<leader>fg` where `g` triggers some action
3. Type `<leader>f` which will open the first floating window
4. Type `g` to trigger the next window, notice the first is not cleared
5. Press `<esc>` which should clear the second window. Note that the remnant of the first window remains

### Expected behavior

Each subsequent window opened should clear the screen of the one that was drawn before it. No half drawn floating windows should appear.

### Actual behavior

As the video shows parts of the window remain visible

### LINKED ISSUE #19193: cmdheight=0: show recording indicator for macros
### Feature description

With the new _cmdheight=0_ feature (#1004) the `recording @*` indicator for macros is not visible anymore.
This makes recording macros less intuitive and possibly leads to confusion when _q_ is hit by accident.

I think a good solution would be to expand the command line as long as the macro is being recorded and close it again afterwards.

### PR DESCRIPTION
**Pull request by Shougo**
Continue of https://github.com/neovim/neovim/pull/16251 https://github.com/neovim/neovim/pull/18961

Fix #19184
Fix #19193

Note:  I don't recommend for you to use `rhysd/accelerated-jk` plugin with `cmdheight=0` because of https://github.com/neovim/neovim/issues/18953

Note: It is the feature that `If you enter the cmdline while the cursor is in the lower half of the window, the entire buffer content will shift one line up while the cmdline is open`.  Because of https://github.com/neovim/neovim/issues/19112

### CODE REVIEW

**Comment by Shougo** [comment]
I have added `ui_has_messages()` to simplify the code.

File: src/nvim/ops.c [hunk 1]
```diff
@@ -687,7 +687,8 @@ void op_reindent(oparg_T *oap, Indenter how)
     redraw_curbuf_later(INVERTED);
   }
 
-  if (oap->line_count > p_report) {
+  // TODO(Shougo): Use ext_messages instead
+  if (oap->line_count > p_report && ui_has_messages()) {
     i = oap->line_count - (i + 1);
     smsg(NGETTEXT("%" PRId64 " line indented ",
                   "%" PRId64 " lines indented ", i),
```
Comment (justinmk) [inline src/nvim/ops.c:694]: Display of most messages, especially messages that go through `smsg()` (and similar message functions), should be decided in messages.c, not at every call site.

Here for example, there is already `p_report` (which might also be changed by 'shortmess', idk). If users don't want that message they set that option. `cmdheight=0` should just show the message without hit-enter. And the hit-enter should be avoided in messages.c, `wait_return`, or whatever central place decides whether hit-enter is done.

File: src/nvim/normal.c [hunk 2]
```diff
@@ -2790,7 +2790,7 @@ void pop_showcmd(void)
 
 static void display_showcmd(void)
 {
-  if (p_ch < 1 && !ui_has(kUIMessages)) {
+  if (!ui_has_messages()) {
```
Comment (justinmk) [inline src/nvim/normal.c:2793]: showcmd and ruler definitely wouldn't be shown with cmdheight=0, so this kind of guard is correct.

File: src/nvim/ops.c [hunk 3]
```diff
@@ -2791,7 +2792,8 @@ static void op_yank_reg(oparg_T *oap, bool message, yankreg_T *reg, bool append)
     xfree(reg->y_array);
   }
 
-  if (message && (p_ch > 0 || ui_has(kUIMessages))) {  // Display message about yank?
+  // TODO(Shougo): Use ext_messages instead
+  if (message && ui_has_messages()) {  // Display message about yank?
```
Comment (justinmk) [inline src/nvim/ops.c:2796]: This is another `smsg()` case. Should not need to special-case this here. Should be handled in messages.c, and display of the message is controlled by the user via 'shortmess' etc.

**Comment by xiyaowong** [comment]
@Shougo issue #19184 still exists.

- nvim -v
```
NVIM v0.8.0-dev+439-g434ce1f5c
Build type: Release
LuaJIT 2.1.0-beta3
```

- mini.vim
```vim
set runtimepath^=~/.local/share/nvim/site/pack/packer/opt/which-key.nvim

lua require('which-key').setup()

set cmdheight=0
```

- `nvim -u mini.vim --noplugin`
- type `gg`

**Comment by akinsho** [comment]
@xiyaowong are you sure you built nvim and are on the correct branch? I tested my original issue and it's resolved. I also just tried `gg` and that is also fine

**Comment by xiyaowong** [comment]
> 



> @xiyaowong are you sure you built nvim and are on the correct branch? I tested my original issue and it's resolved. I also just tried `gg` and that is also fine.
> 
> Although `gg` never resulted in the same issue as even without this PR I find it works fine

yes 

```NVIM v0.8.0-dev+537-gffbed8d6c``

**Comment by jemag** [comment]
I think they might be different issues. I tested it and the issue about floating windows does not happen.

However, the issues involving `g` as mentioned here: https://github.com/folke/which-key.nvim/issues/301 do still happen in this PR. I am not sure however if it's a problem with which-key or neovim itself.

**Comment by akinsho** [comment]
@xiyaowong @jemag can conversation be moved to the issue and not the PR, so it doesn't make the review more confusing, please. The issue I specifically am reporting is to do with the behaviour of the floating windows and redrawing. Nothing to do with the press enter prompt (at least not directly). If there's another issue, either of you will need to create a specific issue for that one.

Apologies to the maintainers/contributors

**Comment by Shougo** [comment]
@xiyaowong OK.  I have reproduced.

It seems `which-key.nvim` implementation problem because of https://github.com/folke/which-key.nvim/blob/535703cd4f08623e12458b5522be1f4ec2a878e7/lua/which-key/view.lua#L123

`wchich-key.nvim` has dummy output.  It is not needed for `cmdheight=0`.

File: src/nvim/normal.c (hunk 2 above)
Comment (Shougo) [reply src/nvim/normal.c:2793]: What is the problem?

File: src/nvim/ops.c (hunk 1 above)
Comment (Shougo) [reply src/nvim/ops.c:694]: All `smsg()` should be disabled if `cmdheight=0`?
Well, I think it should be printed by `ext_messages()`.

File: src/nvim/normal.c (hunk 2 above)
Comment (zeertzjq) [reply src/nvim/normal.c:2793]: This is correct. There is no problem here.

Comment (Shougo) [reply src/nvim/normal.c:2793]: If I remove the guard, it is failed by `grid.c:335: grid_puts_line_flush: Assertion `put_dirty_row != -1' failed.`.

File: src/nvim/ops.c (hunk 1 above)
Comment (Shougo) [reply src/nvim/ops.c]: I have removed the check.  It is not `hit-enter` problem.  It just overwrites the bottom of buffer.

Comment (Shougo) [reply src/nvim/ops.c]: スクリーンショット_2022-07-03_11-37-27

Please see the bottom line.  It is overwritten.
I should disable all of `smsg()`?

**Comment by justinmk** [comment]
> Please see the bottom line. It is overwritten.
> I should disable all of smsg()?

Bottom line _should_ be overwritten (clear to end-of-screen). Except when handled by ext_messages.

**Comment by Shougo** [comment]
> Bottom line should be overwritten (clear to end-of-screen). Except when handled by ext_messages.

The clear does not work....
I have fixed the problem by `semsg()` instead.

**Comment by Shougo** [comment]
Hi.  I have added the change.

https://github.com/neovim/neovim/pull/19185/commits/ada1767ccba489312c77c0aaebc7b931de805ee8

What do you think?

I think command line space is already added in `min_rows()`.

**Comment by Shougo** [comment]
Thank you for the merge.

**Comment by justinmk** [comment]
Thanks @Shougo . Is there not a few more tests that can cover the cases here, e.g. I see a change to `win_setminheight` which suggests that a test for 1-line windows could be useful.

**Comment by Shougo** [comment]
Some tests are added in Vim 9.0.0114, Vim 9.0.0118 and  they are already ported now.
