### PR TITLE
fix(vim.ui.input): return empty string when inputs nothing

### LINKED ISSUE #18144: Make `ui.input()` handle `<C-c>`, `<Esc>`, and empty string input
### Feature already in Vim?

No

### Feature description

At the moment, `vim.ui.input()` has to following behavior:
- When typing `<C-c>` during any time of input, it gives `E5108: Error executing lua Keyboard interrupt`.
- When typing `<Esc>` during any time of input, it stops user query and executes `on_confirm(nil)`.
- When typing `<CR>` as first key of input implying an empty string as input, it behaves exactly like `<Esc>`.

This is mainly because `vim.ui.input()` is basically a wrapper around `vim.fn.input()`, which behaves exactly like this: throws error on `<C-c>` and returns empty string on cancel. Technically, by setting `cancelreturn` field in `opts`, it can return specific string on cancel, but then it can't distinguish between `<Esc>` and that string as input.

My suggestion is for `vim.ui.input()` to have this behavior:
- On `<C-c>` execute `on_confirm(nil)`.
- On `<Esc>` execute `on_confirm(nil)`.
- On `<CR>` as first key execute `on_confirm('')`.

Allowing `<C-c>` seems to be an easy fix by using `pcall(vim.fn.input, ...)`, distinguish between `<Esc>` and empty string is not straightforward. I suggest using temporary key listener with `vim.on_key`.

So the [entire `vim.ui.input()`](https://github.com/neovim/neovim/blob/6e6f5a783333d1bf9d6c719c896e72ac82e1ae54/runtime/lua/vim/ui.lua#L85-L97) will become something like this (also fixing the #18143 issue here):
```lua
local input_ns_id = vim.api.nvim_create_namespace('')

function _G.input(opts, on_confirm)
  vim.validate {
    opts = { opts, 'table', true },
    on_confirm = { on_confirm, 'function', false },
  }

  -- Use temporary listener to distinguish between `<Esc>` and empty string
  local was_cancelled = false
  vim.on_key(function(key)
    if key == vim.api.nvim_replace_termcodes('<Esc>', true, true, true) then
      was_cancelled = true
    end
  end, input_ns_id)

  if opts == nil or vim.tbl_isempty(opts) then
    opts = vim.empty_dict()
  end
  -- Use `pcall` to allow cancelling with `<C-c>`
  local ok, input = pcall(vim.fn.input, opts)

  -- Stop listener
  vim.on_key(nil, input_ns_id)

  if not ok or was_cancelled then
    on_confirm(nil)
  else
    on_confirm(input)
  end
end
```

Happy to do PR if this feature is useful.

### PR DESCRIPTION
**Pull request by wookayin**
The previous behavior of `vim.ui.input()` when typing <CR> with no text
input (with an intention of having the empty string as input)
was to execute `on_confirm(nil)`.

Inputting an empty string now should correctly execute `on_confirm('')`.
This should be clearly distinguished from cancelling or aborting the
input UI, in which case `on_confirm(nil)` is executed as before.

Fixes #18144.

### CODE REVIEW

**Comment by wookayin** [comment]
This PR is based on #18144 but has been slightly modified due to #18143 being already fixed.

I have added a few more missing test cases:

- 1. Input nothing + `<CR>` => returns `""`
- 2. Press `<Esc>` to abort => returns `nil`  (actually `opts.cancelreturn`)
- 3. Press `<Ctrl-C>` to abort => `on_confirm` does not executed (interrupted)

with and without `cancelreturn`. Although `vim.ui.input` does not document the use of `cancelreturn` (actually it is meant to be used in `vim.fn.input`), but I did not want to change the behavior.

The case (i) and (ii) are obvious but the scenario (iii) is bit confusing for me. Actually the behavior was previously undefined. I believe not calling `on_confirm` would be the most reasonable behavior, but happy to discuss if there's any objections.

/cc @zeertzjq @echasnovski (author of #18144) @bfredl

**Comment by wookayin** [comment]
Another note: actually the last test case is a bit strange, I feel the code works fine in actual neovim but in the test case emulated with `feedkeys` and `exec_lua("return result")` do not work the same as a real neovim when `KeyboardInterrupt` happens.

```diff
    it('does not call on_confirm when interrupted with cancelreturn opt #18144', function()
      feed(':lua result = "on_confirm not called"<cr>')
-      eq('on_confirm not called', exec_lua('return result'))
      feed(':lua vim.ui.input({ cancelreturn = "CANCEL" }, function(input) result = input end)<cr>')
      feed('Inputted Text<c-c>')
      -- Ctrl-C would make vim.ui.input() throw, so `result = input` won't be executed
      -- Note that the control flow logic is slightly different from the behavior with ESC
      eq('on_confirm not called', exec_lua('return result'))
    end)
```
Removing the highlighted line would make the test fail, somehow `result` becomes `nil` in the last line.

File: runtime/lua/vim/ui.lua [hunk 1]
```diff
@@ -88,11 +88,15 @@ function M.input(opts, on_confirm)
   })
 
   opts = (opts and not vim.tbl_isempty(opts)) and opts or vim.empty_dict()
+  opts = vim.tbl_extend('keep', opts, { cancelreturn = vim.NIL })
+
   local input = vim.fn.input(opts)
-  if #input > 0 then
+  if input == vim.NIL then
+    on_confirm(opts.cancelreturn) -- canceled
+  elseif #input >= 0 then
```
Comment (zeertzjq) [inline runtime/lua/vim/ui.lua:96]: This seems always true.

**Comment by zeertzjq** [comment]
Looking at the code it seems that `on_confirm` is called with `vim.NIL` on cancel, not `nil`.

File: runtime/lua/vim/ui.lua (hunk 1 above)
Comment (wookayin) [reply runtime/lua/vim/ui.lua:96]: Hmm you are right. I think I no longer need the else statement below. A corner case is that if a user specifies `cancelreturn = nil`, it will throw an error. Let me fix this.

Comment (zeertzjq) [reply runtime/lua/vim/ui.lua:96]: Oh wait. This will throw an error whenever something that does not have a length and is not `nil` or `vim.NIL` as `cancelreturn`.

**Comment by wookayin** [comment]
> Looking at the code it seems that on_confirm is called with vim.NIL on cancel, not nil.

You were right, my bad. Thanks for the catch. In the test helpers `nil` and `vim.NIL` are not clearly distinguished; somehow `exec_lua('return nil')` gives `vim.NIL` (`mpack.NIL`).

In the updated version I see `on_confirm(nil)` is called correctly. To ensure `on_confirm(vim.NIL)` is NOT called, we should avoid calling `eq` with `helpers.NIL` but instead do an inline evaluation like: `eq(true, exec_lua('return (nil == vim.NIL)'))`

File: runtime/lua/vim/ui.lua (hunk 1 above)
Comment (wookayin) [reply runtime/lua/vim/ui.lua]: Fixed in fd54b82 and made test cases more precise.

**Comment by wookayin** [comment]
A minor note:

Although not documented, `vim.ui.input({ cancelreturn = ... }, on_confirm)` will respond with `on_confirm(cancelreturn)` as before, with the exception when `cancelreturn == vim.NIL` in which case it will invoke `on_confirm(vim.NIL)`.

I believe this change of behavior should be fine, because the previous behavior of `vim.ui.input({cancelreturn = vim.NIL}, on_confirm)` was to raise an error `attempt to get length of local 'input' (a userdata value)`.

File: test/functional/lua/ui_spec.lua [hunk 2]
```diff
@@ -83,5 +83,61 @@ describe('vim.ui', function()
...
+
+    it('does not call on_confirm when interrupted with cancelreturn opt #18144', function()
+      feed(':lua result = "on_confirm not called"<cr>')
+      eq('on_confirm not called', exec_lua('return result'))
+      feed(':lua vim.ui.input({ cancelreturn = "CANCEL" }, function(input) result = input end)<cr>')
+      feed('Inputted Text<c-c>')
+      -- Ctrl-C would make vim.ui.input() throw, so `result = input` won't be executed
+      -- Note that the control flow logic is slightly different from the behavior with ESC
+      eq('on_confirm not called', exec_lua('return result'))
+    end)
```
Comment (zeertzjq) [inline test/functional/lua/ui_spec.lua:131]: This test seem unnecessary.

**Comment by zeertzjq** [comment]
TBH I don't think one should be using `cancelreturn` as if `vim.ui.input()` is overridden by a custom handler it may not work.

File: test/functional/lua/ui_spec.lua (hunk 2 above)
Comment (zeertzjq) [reply test/functional/lua/ui_spec.lua:131]:
```suggestion
```
