### PR TITLE
fix(lsp): check for lens range in `vim.lsp.codelens.run()`

### LINKED ISSUE #31258: feature: vim.lsp.codelens.run() could select code lenses from the narrowest enclosing scope
### Problem

Some code lenses (e.g. ruby-lsp's `rubyLsp.runTest`) span multiple lines, that is, their `range.start.line` and `range.end.line` may be different.

When I am working on a test and ready to run it again, I have to navigate up to its first line before I can invoke `vim.lsp.codelens.run()`, which adds a little friction.

I have [code in my `init.lua`](https://github.com/matthewtodd/dotfiles/blob/7c6a7b0b2652e084bfcf8b21d58e93854fb81032/etc/nvim/init.lua#L59-L82) to detect enclosing code lenses for the current line and navigate up to the first line of the narrowest one, but I'm wondering if solving this for everyone would be interesting.

### Expected behavior

I would love to have a way to run the narrowest enclosing codelens without having to navigate.

Maybe this is making `vim.lsp.codelens.run()` magic, or maybe it's offering a new magic `vim.lsp.codelens.runEnclosing()` function, or maybe it's just having `vim.lsp.codelens.run()` accept an optional line number, falling back to the current cursor line.

Happy to work up a PR for any of this, but figured I'd start the conversation first!

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes https://github.com/neovim/neovim/issues/31258.

### CODE REVIEW

**Comment by MariaSolOs** [comment]
@matthewtodd it would be great if you can test this with the Ruby LSP :)

File: runtime/lua/vim/lsp/codelens.lua [hunk 1]
```diff
@@ -70,16 +70,20 @@ function M.get(bufnr)
...
   local bufnr = api.nvim_get_current_buf()
   local options = {} --- @type {client: integer, lens: lsp.CodeLens}[]
   local lenses_by_client = lens_cache_by_buf[bufnr] or {}
   for client, lenses in pairs(lenses_by_client) do
     for _, lens in pairs(lenses) do
-      if lens.range.start.line == (line - 1) and lens.command and lens.command.command ~= '' then
+      if
+        lens.range.start.line <= line
+        and lens.range['end'].line >= line
+        and lens.command
```
Comment (ribru17) [inline runtime/lua/vim/lsp/codelens.lua]: Nit: maybe the `and lens.command` should be first, to short circuit several range property accesses/compares? Super micro optimization though...

**Review by ribru17 — APPROVED** [review]

File: runtime/lua/vim/lsp/codelens.lua (hunk 1 above)
Comment (MariaSolOs) [reply runtime/lua/vim/lsp/codelens.lua]: Sure :)

**Comment by matthewtodd** [comment]
Oh, wow, thanks, @MariaSolOs! I just tested, and it works great!

I was surprised at first to see all enclosing codelenses listed (they can be nested, e.g. one to run all tests and one to run the current test), but on reflection I think that's the right call. ~~I'll need look into some way to disambiguate them in my telescope picker.~~ Only [the lens's title](https://github.com/MariaSolOs/neovim/blob/a2f8ed4230f32b53c483133d3a7757aeabba5b53/runtime/lua/vim/lsp/codelens.lua#L97-L107) is passed to `vim.ui.select`, which makes it a little hard to pick, so maybe we want some configurability there?

Screenshot 2025-08-13 at 4 45 45 PM

**Comment by MariaSolOs** [comment]
> Only [the lens's title](https://github.com/MariaSolOs/neovim/blob/a2f8ed4230f32b53c483133d3a7757aeabba5b53/runtime/lua/vim/lsp/codelens.lua#L97-L107) is passed to `vim.ui.select`, which makes it a little hard to pick, so maybe we want some configurability there?

You can always use a plugin with a fancier `vim.ui.select` implementation (which from the picture it seems like you're already doing that) and use the `kind` value to provide a different label in the dropdown menu.

`fzf-lua` allows this in https://github.com/ibhagwan/fzf-lua/blob/2f9e1af8cbff922543c2f259040d518517b8e294/lua/fzf-lua/providers/ui_select.lua#L89, you can possibly explore GitHub history to find some examples.

**Comment by matthewtodd** [comment]
> You can always use a plugin with a fancier `vim.ui.select` implementation

Ah, yes, of course! I saw [the `format_item` parameter](https://github.com/MariaSolOs/neovim/blob/a2f8ed4230f32b53c483133d3a7757aeabba5b53/runtime/lua/vim/lsp/codelens.lua#L97-L107) and thought I'd just be receiving the resulting string, but since `vim.ui.select` is replaceable, I can just ignore that and do whatever I want with the raw list of `options`.

Thank you!

(As a note to other readers, current `telescope-ui-select` [isn't extensible](https://github.com/nvim-telescope/telescope-ui-select.nvim/blob/6e51d7da30bd139a6950adf2a47fda6df9fa06d2/lua/telescope/_extensions/ui-select.lua#L89-L91) in the way `fzf-lua`, linked above, is. I'll be wrapping its `vim.ui.select` implementation to force my own `format_item` once it's been registered.)
