### PR TITLE
fix(api): nvim_parse_cmd raises error message in pcall()

### LINKED ISSUE #20339: `nvim_parse_cmd` throw error, even through it has been surrounded by `pcall` already
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1159-g8317b9199

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ArchLinux

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

build from repo

### How to reproduce the issue

`cat mini.lua`
```lua
vim.api.nvim_create_autocmd('CmdlineChanged', {
    pattern = ':',
    callback = function ()
        local ok, parsed = pcall(vim.api.nvim_parse_cmd, vim.fn.getcmdline(), {})
    end
})
```
1. nvim --clean +'so mini.lua' mini.lua
2. Type `V:n`

### Expected behavior

No error

### Actual behavior

image

### PR DESCRIPTION
**Pull request by ateoi**
# Problem:
nvim_parse_cmd() in pcall() may show an error message (side-effect): https://github.com/neovim/neovim/issues/20339 

    :lua pcall(vim.api.nvim_parse_cmd, vim.fn.getcmdline(), {})
    E16: Invalid range

# Solution:
Avoid emsg() in the nvim_parse_cmd() codepath.

~~Borrow solution from cmdpreview_may_show:~~

https://github.com/neovim/neovim/blob/664f2749e688e2aa2b322d2296111e1246a860ee/src/nvim/ex_getln.c#L2427-L2432

Fix #20339

### CODE REVIEW

**Comment by bfredl** [comment]
`parse_cmdline()` is supposed to return any message in `errormsg` out param. having it also throw is a design error. 

Looking at it, it is caused by `get_cmd_address` having an error return, but it calls `get_address()` which has no such return and thus uses `emsg()` internally (trivial wrapper `addr_error()`) .

 I would suggest refactor `get_address()` to also have an errormsg out param and then change its callsites to use emsg() instead. Then we can remove the usage of `emsg_off++` workarounds instead of adding more.

**Comment by ateoi** [comment]
> Doesn't this prevent `nvim_parse_cmd` from throwing an error even when it's not in a pcall?

No, because `parse_cmdline()` still returns `false` on error and then `api_set_error()` is called. But I agree with @bfredl , refactor `get_address()` is a better solution.

**Comment by ateoi** [comment]
Maybe it's possible to include in this refactor the removal of the `emsg_off` workaround from `do_incsearch_highlighting()`, as both `parse_command_modifiers()` and `parse_cmd_address()` do not call `emsg()` anymore.

https://github.com/neovim/neovim/blob/bab4bcdefbdad7f175f7f31c230de3d066963542/src/nvim/ex_getln.c#L262

File: src/nvim/ex_docmd.c [hunk 1]
```diff
@@ -1284,8 +1284,8 @@ void set_cmd_dflall_range(exarg_T *eap)
   case ADDR_NONE:
   case ADDR_UNSIGNED:
   case ADDR_QUICKFIX:
-    iemsg(_("INTERNAL: Cannot use EX_DFLALL "
-            "with ADDR_NONE, ADDR_UNSIGNED or ADDR_QUICKFIX"));
+    *errormsg = _("INTERNAL: Cannot use EX_DFLALL "
+                  "with ADDR_NONE, ADDR_UNSIGNED or ADDR_QUICKFIX");
```
Comment (zeertzjq) [inline src/nvim/ex_docmd.c:1288]: Don't pass along internal error message. Just keep this `iemsg()`.

File: src/nvim/ex_docmd.c [hunk 2]
```diff
@@ -3219,12 +3222,12 @@ char *skip_range(const char *cmd, int *ctx)
   return (char *)cmd;
 }
 
-static void addr_error(cmd_addr_T addr_type)
+static void addr_error(cmd_addr_T addr_type, char **errormsg)
```
Comment (lewis6991) [inline src/nvim/ex_docmd.c:3225]: I think it would be better to return an error instead?

```suggestion
static const char *addr_error(cmd_addr_T addr_type)
```

**Comment by ateoi** [comment]
These are the functions called by `get_address()`:

```
nvim_parse_cmd() -> parse_cmdline() -> parse_cmd_address() -> get_address()
    skipwhite()
    addr_error()
    qf_get_cur_idx()
    qf_get_cur_valid_idx()
    qf_get_size()
    qf_get_valid_size()
    mark_get()
    mark_check()
    assert()
    skip_regexp()
    magic_isset()
>   do_search()
>   searchit()
    ascii_isdigit()
    getdigits()
    getdigits_int32()
    compute_buffer_local_count()
    hasFolding()
```

From these functions, I've identified at least two additional ones that call emsg directly (`do_search()` and `searchit()`).

`do_search()` seems to be simple to refactor, but `searchit()` will be more challenging because it may generate multiple error messages, which can't be handled by the current error message out parameter. For example, it makes multiple calls to `vim_regexec_multi()` in a loop that possibly generate error messages, and later `searchit()` itself may generate an additional one:

https://github.com/neovim/neovim/blob/c194acbfc479d8e5839fa629363f93f6550d035c/src/nvim/search.c#L631-L647

https://github.com/neovim/neovim/blob/c194acbfc479d8e5839fa629363f93f6550d035c/src/nvim/search.c#L939-L954

Any suggestions to handle this multiple error messages scenario?

**Comment by justinmk** [comment]
> I've identified at least two additional ones that call emsg directly (`do_search()` and `searchit()`).

Do those actually need to be fixed here or can we leave them as a TODO?

It looks like this PR will fix _many_ cases except those two. So we could track those remaining cases in an issue and think about them in a followup PR. @ateoi

**Comment by ateoi** [comment]
> Do those actually need to be fixed here or can we leave them as a TODO?
> 

From my tests, this PR fixes the original issue, so I guess we can leave the remaining cases as TODO.

But as a suggestion, I think nvim could have a more flexible messaging/logging infrastructure. It would be nice to have something similar to the diagnostics framework to handle the system messages.

**Comment by justinmk** [comment]
> nvim could have a more flexible messaging/logging infrastructure.

it's planned

**Comment by justinmk** [comment]
@ateoi do you plan to write tests for this? Would help get it merged faster.

**Comment by justinmk** [comment]
Rebased and added a test, to move this forward. Parsing a cmdline in an event is a pretty important/common use-case, and handlers need a way to skip invalid cmdlines without showing user-facing errors.

Remaining work is tracked in https://github.com/neovim/neovim/issues/24220
