### PR TITLE
fix(unhide): close floating windows first

### LINKED ISSUE #17797: hang with floating window and `:unhide 1`
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1292-ge9b53f3fb

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.24.4

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Run `nvim --clean`
2. Type `:call nvim_open_win(0, v:false, #{ width: 10, height: 10, relative: "editor", row: 10, col: 10 })` and press Enter
3. Type `:unhide 1` and press Enter

### Expected behavior

No crash or hang

### Actual behavior

`:unhide 1` leads to a hang with `E444: Cannot close last window` spammed in messages.

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #17797
Close #25314

### CODE REVIEW

File: src/nvim/buffer.c [hunk 1]
```diff
@@ -3616,8 +3616,11 @@ void ex_buffer_all(exarg_T *eap)
   }
   while (true) {
     tpnext = curtab->tp_next;
-    for (wp = firstwin; wp != NULL; wp = wpnext) {
-      wpnext = wp->w_next;
+    // Try to close floating windows firest
```
Comment (glepnir) [inline src/nvim/buffer.c:3619]:
```suggestion
    // Try to close floating windows first
```
