### PR TITLE
paste: fix paste in terminal mode

### LINKED ISSUE #10992: TUI paste in :terminal mode gives error (but works)
- `nvim --version`: NVIM v0.4.0-2042-g7bb858c39
- Terminal name/version: kitty
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Copy some text with cmd-c, then try to paste into a terminal buffer (in insert mode) with cmd-v.

### Actual behaviour

The error `paste: Error executing lua: vim.lua:198: Vim(normal):Can't re-enter normal mode from terminal mode` flashes.

### Expected behaviour

No error msg.

### PR DESCRIPTION
**Pull request by bfredl**
fixes #10992

### CODE REVIEW

File: src/nvim/lua/vim.lua [hunk 1]
```diff
@@ -196,7 +196,9 @@ paste = (function()
       if phase < 2 and mode ~= 'i' and mode ~= 'R' then
         vim.api.nvim_put(lines, 'c', true, true)
         -- XXX: Normal-mode: workaround bad cursor-placement after first chunk.
-        vim.api.nvim_command('normal! a')
+        if mode ~= 't' then
```
Comment (justinmk) [inline src/nvim/lua/vim.lua]: could go on line 196. did so in the merge-commit.

File: src/nvim/lua/vim.lua [hunk 2]
```diff
@@ -196,7 +196,9 @@ paste = (function()
...
+          vim.api.nvim_command('normal! a')
```
Comment (justinmk) [inline src/nvim/lua/vim.lua]: This hack isn't really working in any case, so will need to revisit it again :(
