### PR TITLE
fix(autocmd): Heap UAF with :bwipe in Syntax autocmd

### LINKED ISSUE #37425: heap-use-after-free with :bwipe in Syntax autocmd
### Problem

```
=================================================================
==2296975==ERROR: AddressSanitizer: heap-use-after-free on address 0x7e3cf65f198c at pc 0x56222dda25be bp 0x7ffc8681eb60 sp 0x7ffc8681eb58
READ of size 4 at 0x7e3cf65f198c thread T0
    #0 0x56222dda25bd in do_syntax_autocmd **/src/nvim/option.c:2722:16
    #1 0x56222dd9ec25 in did_set_option **/src/nvim/option.c:3544:5
    #2 0x56222dd5bbca in set_option **/src/nvim/option.c:3721:12
    #3 0x56222dd51056 in do_one_set_option **/src/nvim/option.c:1337:13
    #4 0x56222dd4c362 in do_set **/src/nvim/option.c:1386:9
    #5 0x56222dd4bb4d in ex_set **/src/nvim/option.c:734:3
    #6 0x56222d6a09df in execute_cmd0 **/src/nvim/ex_docmd.c:1762:7
    #7 0x56222d6837b5 in do_one_cmd **/src/nvim/ex_docmd.c:2392:7
    #8 0x56222d678d76 in do_cmdline **/src/nvim/ex_docmd.c:679:20
    #9 0x56222dfecdfb in do_source_ext **/src/nvim/runtime.c:2319:5
    #10 0x56222dfee6b0 in do_source **/src/nvim/runtime.c:2395:10
    #11 0x56222dfe886e in cmd_source **/src/nvim/runtime.c:1866:14
    #12 0x56222dfe8229 in ex_source **/src/nvim/runtime.c:1874:3
    #13 0x56222d6a09df in execute_cmd0 **/src/nvim/ex_docmd.c:1762:7
    #14 0x56222d6837b5 in do_one_cmd **/src/nvim/ex_docmd.c:2392:7
    #15 0x56222d678d76 in do_cmdline **/src/nvim/ex_docmd.c:679:20
    #16 0x56222dc9dd74 in nv_colon **/src/nvim/normal.c:3198:18
    #17 0x56222dc8b15c in normal_execute **/src/nvim/normal.c:1254:3
    #18 0x56222e1a6953 in state_enter **/src/nvim/state.c:100:26
    #19 0x56222dc6dee4 in normal_enter **/src/nvim/normal.c:523:3
    #20 0x56222d9ecfff in main **/src/nvim/main.c:660:3
    #21 0x7fccf7227634 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #22 0x7fccf72276e8 in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #23 0x56222ce08004 in _start (**/build/bin/nvim+0xca3004) (BuildId: 92bbb25ee0cdd581d947f027882c8d4840bd3931)

0x7e3cf65f198c is located 140 bytes inside of 12752-byte region [0x7e3cf65f1900,0x7e3cf65f4ad0)
freed by thread T0 here:
    #0 0x56222cf0ab9d in free.part.0 asan_malloc_linux.cpp.o
    #1 0x56222db8b830 in xfree **/src/nvim/memory.c:159:3
    #2 0x56222d1614c2 in apply_autocmds_group **/src/nvim/autocmd.c:1997:7
    #3 0x56222d169ace in apply_autocmds **/src/nvim/autocmd.c:1573:10
    #4 0x56222dda2525 in do_syntax_autocmd **/src/nvim/option.c:2720:3
    #5 0x56222dd9ec25 in did_set_option **/src/nvim/option.c:3544:5
    #6 0x56222dd5bbca in set_option **/src/nvim/option.c:3721:12
    #7 0x56222dd51056 in do_one_set_option **/src/nvim/option.c:1337:13
    #8 0x56222dd4c362 in do_set **/src/nvim/option.c:1386:9
    #9 0x56222dd4bb4d in ex_set **/src/nvim/option.c:734:3
    #10 0x56222d6a09df in execute_cmd0 **/src/nvim/ex_docmd.c:1762:7
    #11 0x56222d6837b5 in do_one_cmd **/src/nvim/ex_docmd.c:2392:7
    #12 0x56222d678d76 in do_cmdline **/src/nvim/ex_docmd.c:679:20
    #13 0x56222dfecdfb in do_source_ext **/src/nvim/runtime.c:2319:5
    #14 0x56222dfee6b0 in do_source **/src/nvim/runtime.c:2395:10
    #15 0x56222dfe886e in cmd_source **/src/nvim/runtime.c:1866:14
    #16 0x56222dfe8229 in ex_source **/src/nvim/runtime.c:1874:3
    #17 0x56222d6a09df in execute_cmd0 **/src/nvim/ex_docmd.c:1762:7
    #18 0x56222d6837b5 in do_one_cmd **/src/nvim/ex_docmd.c:2392:7
    #19 0x56222d678d76 in do_cmdline **/src/nvim/ex_docmd.c:679:20
    #20 0x56222dc9dd74 in nv_colon **/src/nvim/normal.c:3198:18
    #21 0x56222dc8b15c in normal_execute **/src/nvim/normal.c:1254:3
    #22 0x56222e1a6953 in state_enter **/src/nvim/state.c:100:26
    #23 0x56222dc6dee4 in normal_enter **/src/nvim/normal.c:523:3
    #24 0x56222d9ecfff in main **/src/nvim/main.c:660:3
    #25 0x7fccf7227634 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #26 0x7fccf72276e8 in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #27 0x56222ce08004 in _start (**/build/bin/nvim+0xca3004) (BuildId: 92bbb25ee0cdd581d947f027882c8d4840bd3931)

previously allocated by thread T0 here:
    #0 0x56222cf0be9d in calloc (**/build/bin/nvim+0xda6e9d) (BuildId: 92bbb25ee0cdd581d947f027882c8d4840bd3931)
    #1 0x56222db8b8f6 in xcalloc **/src/nvim/memory.c:173:15
    #2 0x56222d18ee12 in buflist_new **/src/nvim/buffer.c:1974:11
    #3 0x56222d642e12 in do_ecmd **/src/nvim/ex_cmds.c:2482:13
    #4 0x56222d6c270f in do_exedit **/src/nvim/ex_docmd.c:5930:5
    #5 0x56222d6c11b8 in ex_splitview **/src/nvim/ex_docmd.c:5588:5
    #6 0x56222d6a09df in execute_cmd0 **/src/nvim/ex_docmd.c:1762:7
    #7 0x56222d6837b5 in do_one_cmd **/src/nvim/ex_docmd.c:2392:7
    #8 0x56222d678d76 in do_cmdline **/src/nvim/ex_docmd.c:679:20
    #9 0x56222dfecdfb in do_source_ext **/src/nvim/runtime.c:2319:5
    #10 0x56222dfee6b0 in do_source **/src/nvim/runtime.c:2395:10
    #11 0x56222dfe886e in cmd_source **/src/nvim/runtime.c:1866:14
    #12 0x56222dfe8229 in ex_source **/src/nvim/runtime.c:1874:3
    #13 0x56222d6a09df in execute_cmd0 **/src/nvim/ex_docmd.c:1762:7
    #14 0x56222d6837b5 in do_one_cmd **/src/nvim/ex_docmd.c:2392:7
    #15 0x56222d678d76 in do_cmdline **/src/nvim/ex_docmd.c:679:20
    #16 0x56222dc9dd74 in nv_colon **/src/nvim/normal.c:3198:18
    #17 0x56222dc8b15c in normal_execute **/src/nvim/normal.c:1254:3
    #18 0x56222e1a6953 in state_enter **/src/nvim/state.c:100:26
    #19 0x56222dc6dee4 in normal_enter **/src/nvim/normal.c:523:3
    #20 0x56222d9ecfff in main **/src/nvim/main.c:660:3
    #21 0x7fccf7227634 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #22 0x7fccf72276e8 in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #23 0x56222ce08004 in _start (**/build/bin/nvim+0xca3004) (BuildId: 92bbb25ee0cdd581d947f027882c8d4840bd3931)

SUMMARY: AddressSanitizer: heap-use-after-free **/src/nvim/option.c:2722:16 in do_syntax_autocmd
Shadow bytes around the buggy address:
  0x7e3cf65f1700: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7e3cf65f1780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7e3cf65f1800: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7e3cf65f1880: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7e3cf65f1900: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x7e3cf65f1980: fd[fd]fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x7e3cf65f1a00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x7e3cf65f1a80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x7e3cf65f1b00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x7e3cf65f1b80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x7e3cf65f1c00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==2296975==ABORTING
```
Most likely a regression from https://github.com/neovim/neovim/commit/3fbc5f9860c28d026fcd2864cf955e8899e0d589

### Steps to reproduce

1. Run `nvim --clean`
2. Source the following file:
```vim
new
autocmd Syntax * ++once bwipe!
setlocal syntax=vim
```
3. ASAN reports a heap-use-after-free

### Expected behavior

No heap-use-after-free

### Nvim version (nvim -v)

v0.12.0-dev-2049+gdde914f926

### Vim (not Nvim) behaves the same?

No, Vim 9.1.2086

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.45.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by 11soda11**
Problem:
Creating an autocommand which executes `:bwipe` on the Syntax event causes a heap-use-after-free.

Solution: set BF_SYN_SET flag before applying autocommands

Fixes: #37425

### CODE REVIEW

File: src/nvim/option.c [hunk 1]
```diff
@@ -2715,11 +2715,11 @@ static void do_syntax_autocmd(buf_T *buf, bool value_changed)
   static int syn_recursive = 0;
 
   syn_recursive++;
+  curbuf->b_flags |= BF_SYN_SET;
```
Comment (seandewar) [inline src/nvim/option.c]:
```suggestion
  buf->b_flags |= BF_SYN_SET;
```

Comment (11soda11) [reply src/nvim/option.c]: thx
