### PR TITLE
compositor: handle invalid screen positions after resize gracefully

### LINKED ISSUE #9989: hit assert at ui_compositor.c:421
- `nvim --version`:
```
NVIM v0.4.0-731-g400ee5924
Build type: Debug
LuaJIT 2.0.5
Compilation: /usr/bin/cc -fsanitize=address -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src -I/usr/include -I/tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/build/include
Compiled by wangxinyu@archlinux

Features: +acl +iconv +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

- Vim (version: ) behaves differently?
not tried

- Operating system/version:
archlinux 64
- Terminal name/version:
run from nvim-qt

### Steps to reproduce using `nvim -u NORC`

not tried

### Actual behaviour

during window resize(or switch active grid ? I'm not sure). nvim crash 
backtrace shows
```
#0  0x00007f1e5ab73d7f in raise () from /usr/lib/libc.so.6
#1  0x00007f1e5ab5e672 in abort () from /usr/lib/libc.so.6
#2  0x00007f1e5ab5e548 in __assert_fail_base.cold.0 () from /usr/lib/libc.so.6
#3  0x00007f1e5ab6c396 in __assert_fail () from /usr/lib/libc.so.6
#4  0x000055e011f0e539 in ui_comp_raw_line (ui=0x6120000007c0, grid=1, row=0, startcol=2, endcol=72, clearcol=72, clearattr=0, 
    flags=0, chunk=0x63400010083a, attrs=0x625000b2e904)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/ui_compositor.c:421
#5  0x000055e011efb73f in ui_call_raw_line (grid=1, row=0, startcol=2, endcol=72, clearcol=72, clearattr=0, flags=0, 
    chunk=0x63400010083a, attrs=0x625000b2e904)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/build/src/nvim/auto/ui_events_call.generated.h:225
#6  0x000055e011f0263d in ui_line (grid=0x55e0121f7860 <default_grid>, row=0, startcol=2, endcol=72, clearcol=72, clearattr=0, 
    wrap=false) at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/ui.c:328
#7  0x000055e011dd4b4d in grid_put_linebuf (grid=0x55e0121f7860 <default_grid>, row=0, coloff=2, endcol=80, clear_width=80, 
    rlflag=0, wp=0x62500be3c100, bg_attr=0, wrap=false)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/screen.c:4471
#8  0x000055e011dd1a20 in win_line (wp=0x62500be3c100, lnum=27, startrow=0, endrow=28, nochange=true, number_only=false)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/screen.c:3977
#9  0x000055e011dbedb0 in win_update (wp=0x62500be3c100)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/screen.c:1368
#10 0x000055e011db851b in update_screen (type=40) at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/screen.c:473
#11 0x000055e011de7e73 in screen_resize (width=70, height=58)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/screen.c:7187
#12 0x000055e011f019e3 in ui_refresh () at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/ui.c:200
#13 0x000055e0118ff956 in nvim_ui_try_resize (channel_id=1, width=70, height=58, err=0x7ffe7c4e13b0)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/api/ui.c:219
#14 0x000055e0118c86c0 in handle_nvim_ui_try_resize (channel_id=1, args=..., error=0x7ffe7c4e13b0)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/build/src/nvim/auto/api/private/dispatch_wrappers.generated.h:2002
#15 0x000055e011c77aeb in request_event (argv=0x7ffe7c4e14f8)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/msgpack_rpc/channel.c:371
#16 0x000055e011a6f1e2 in multiqueue_process_events (this=0x604000000650)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/event/multiqueue.c:150
#17 0x000055e011ed95c3 in terminal_execute (state=0x7ffe7c4e1650, key=-26365)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/terminal.c:472
#18 0x000055e011e8f4c5 in state_enter (s=0x7ffe7c4e1650)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/state.c:73
#19 0x000055e011ed8e4e in terminal_enter () at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/terminal.c:408
#20 0x000055e0119810e8 in edit (cmdchar=105, startln=false, count=1)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/edit.c:1349
#21 0x000055e011cc012d in invoke_edit (cap=0x7ffe7c4e1978, repl=0, cmd=105, startln=0)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/normal.c:7628
#22 0x000055e011cc002a in nv_edit (cap=0x7ffe7c4e1978)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/normal.c:7600
#23 0x000055e011c8d5cd in normal_execute (state=0x7ffe7c4e18f0, key=105)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/normal.c:1128
#24 0x000055e011e8f4c5 in state_enter (s=0x7ffe7c4e18f0)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/state.c:73
#25 0x000055e011c86916 in normal_enter (cmdwin=false, noexmode=false)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/normal.c:462
#26 0x000055e011bdac6d in main (argc=6, argv=0x7ffe7c4e1d58)
    at /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/main.c:597

```

### PR DESCRIPTION
**Pull request by bfredl**
The screen resize logic needs to be refactored to be simpler and more deterministic. Until then, we need to handle attempts to draw outside of the screen size gracefully, just like the old vim code did.

fixes #9989

### CODE REVIEW

File: src/nvim/ui_compositor.c [hunk 1]
```diff
@@ -480,8 +480,25 @@ static void ui_comp_raw_line(UI *ui, Integer grid, Integer row,
...
+
+  // TODO(bfredl): this should not really be necessary. But on some condition
+  // when resizing nvim, a window will be attempted to be drawn on the older
+  // and possibly larger global screen size.
+  if (row >= default_grid.Rows) {
+    DLOG("compositor: invalid row %ld on grid %ld", row, grid);
+    return;
+  }
+  if (clearcol > default_grid.Columns) {
+    DLOG("compositor: invalid last column %ld on grid %ld", clearcol, grid);
```
Comment (justinmk) [inline src/nvim/ui_compositor.c]: `PRId64` instead of `%ld` ?
