### PR TITLE
[RFC] vim-patch:7.4.2069,7.4.2101,7.4.2222,7.4.2223

### LINKED ISSUE #728: Character À eats up the next two characters when in scriptin in :source! <scriptin>
Problem: character `À` (Hex `00C0`) eats up the next two characters
when inside a script used as `<scriptin>` in `:source! <scriptin>`

**Steps to reproduce**
- Script file `script.vim`

```
:%s/à nossa/--à nossa--/g
:%s/À nossa/--À nossa--/g
```
- Sample file `text`

```
Assim mesmo, a complexidade dos estudos efetuados ainda não demonstrou
convincentemente que vai participar na mudança do levantamento das variáveis
envolvidas. Todas estas questões, devidamente ponderadas, levantam dúvidas
sobre se a constante divulgação das À nossa foo à nossa informações afeta
positivamente a correta previsão das diretrizes de desenvolvimento para o
futuro. Desta maneira, o entendimento das metas propostas nos obriga à análise
do sistema de participação geral. Podemos já vislumbrar o modo pelo qual a
futuro. Desta maneira, o entendimento das metas propostas nos obriga à análise
sobre se a constante divulgação das À nossa foo à nossa informações afeta
estrutura atual da organização é uma das consequências do impacto na agilidade
decisória.
```
- Vim invocation `$ vim -N -u NONE text`
- Command (a) `:source script.vim`
- Command (b) `:source! script.vim`

**Results:**

Using (a) everything works as expected.

Using (b) the second substitute command is read as
(which can be seen in the command history)

`:%s/Àossa/--Àossa/g`

resulting in the error

`E486: Pattern not found: Àossa`

while the first substitute works as expected.

Both files are uft-8. Others characters, like `Ò`, seems to work fine.

### PR DESCRIPTION
**Pull request by jamessan**
#### vim-patch:7.4.2069

Problem:    spell.c is too big.
Solution:   Split it in spell file handling and spell checking.

https://github.com/vim/vim/commit/9ccfebddc3ff2a3c2853cf706fd4c26f639bf381

#### vim-patch:7.4.2101

Problem:    Looping over windows, buffers and tab pages is inconsistant.
Solution:   Use FOR_ALL_ macros everywhere. (Yegappan Lakshmanan)

https://github.com/vim/vim/commit/2932359000b2f918d5fade79ea4d124d5943cd07

#### vim-patch:7.4.2222

Problem:    Sourcing a script where a character has 0x80 as a second byte does
            not work. (Filipe L B Correia)
Solution:   Turn 0x80 into K_SPECIAL KS_SPECIAL KE_FILLER. (Christian
            Brabandt, closes vim/vim#728)  Add a test case.

https://github.com/vim/vim/commit/6bff02eb530aa29aafa2cb5627399837be7a5dd5

#### vim-patch:7.4.2223

Problem:    Buffer overflow when using latin1 character with feedkeys().
Solution:   Check for an illegal character.  Add a test.

https://github.com/vim/vim/commit/d3c907b5d2b352482b580a0cf687cbbea4c19ea1

### CODE REVIEW

**Comment by justinmk** [comment]
I cringe to mention this, with 2932359000b2f918d5fade79ea4d124d5943cd07 I noticed that the order of arguments is swapped compared to ours. Not sure if you noticed that, but wanted to mention it.

**Comment by jamessan** [comment]
> I noticed awhile ago that the order of arguments in one of the macros is swapped compared to ours.

Yeah, our order makes sense. :)

**Comment by jamessan** [comment]
The lint failures in spellfile.c are expected.  They were pre-existing in spell.c and are just flagged as new due to the new file.

**Comment by justinmk** [comment]
No problem.

File: src/nvim/getchar.c [hunk 1]
```diff
@@ -2494,7 +2489,6 @@ fix_input_buffer (
   for (i = len; --i >= 0; ++p) {
     if (p[0] == NUL
         || (p[0] == K_SPECIAL
-          && !script
           && (i < 2 || p[1] != KS_EXTRA))) {
```
Comment (justinmk) [inline src/nvim/getchar.c]: Also in the original patch this comment on line 2493/2488 was removed:

    // Don't replace K_SPECIAL when reading a script file.

File: src/nvim/getchar.c [hunk 2]
```diff
@@ -2494,8 +2489,7 @@ fix_input_buffer (
   for (i = len; --i >= 0; ++p) {
```
Comment (justinmk) [inline src/nvim/getchar.c]: In the original patch this comment  was removed:

    // Don't replace K_SPECIAL when reading a script file.

Comment (jamessan) [inline src/nvim/getchar.c]: Fixed, thanks.

File: src/nvim/globals.h [hunk 3]
```diff
@@ -556,7 +556,6 @@ EXTERN win_T    *prevwin INIT(= NULL);  /* previous window */
   FOR_ALL_TABS(tp) \
     FOR_ALL_WINDOWS_IN_TAB(wp, tp)
 
-# define FOR_ALL_WINDOWS(wp) for (wp = firstwin; wp != NULL; wp = wp->w_next)
```
Comment (blueyed) [inline src/nvim/globals.h]: Why was `FOR_ALL_WINDOWS` removed here, `and `FOR_ALL_WINDOWS_IN_TAB(wp, curtab)` used instead?
It causes unnecessary differences, and appears to be the root of warnings with gcc-9:
```
../src/nvim/window.c: In function ‘do_window’:
../src/nvim/window.c:183:33: error: self-comparison always evaluates to true [-Werror=tautological-compare]
  183 |     FOR_ALL_WINDOWS_IN_TAB(wp2, curtab) {
      |                                 ^~
```
(since it compares curtab to curtab then)

Comment (jamessan) [reply src/nvim/globals.h]: It's been over two years since I did this.  I don't remember the reasoning.  My guess would be that it seemed like unnecessary duplication.  `FOR_ALL_WINDOWS_IN_TAB` covers all cases that `FOR_ALL_WINDOWS` does.

The only "problem" is that the compiler warns about the comparison, since it doesn't know about the macro.
