### PR TITLE
fix(gen_lsp.lua): improve type name, and fix wrong type inheritance

### LINKED ISSUE #26617: Wrong type annotation
### Problem

https://github.com/neovim/neovim/blob/5a2536de0c4beae4eba50a0d2868983c1690ecc7/runtime/lua/vim/lsp/_meta/protocol.lua#L3098-L3104

https://github.com/neovim/neovim/blob/5a2536de0c4beae4eba50a0d2868983c1690ecc7/runtime/lua/vim/lsp/_meta/protocol.lua#L4160-L4161

`completionItem` is not anonym26. anonym26 corresponds to `completionItem.insertTextModeSupport`.

<details><summary>Specification</summary>

```
export interface [CompletionClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionClientCapabilities) {
	/**
	 * Whether completion supports dynamic registration.
	 */
	dynamicRegistration?: boolean;

	/**
	 * The client supports the following `CompletionItem` specific
	 * capabilities.
	 */
	completionItem?: {
		/**
		 * Client supports snippets as insert text.
		 *
		 * A snippet can define tab stops and placeholders with `$1`, `$2`
		 * and `${3:foo}`. `$0` defines the final tab stop, it defaults to
		 * the end of the snippet. Placeholders with equal identifiers are
		 * linked, that is typing in one will update others too.
		 */
		snippetSupport?: boolean;

		/**
		 * Client supports commit characters on a completion item.
		 */
		commitCharactersSupport?: boolean;

		/**
		 * Client supports the follow content formats for the documentation
		 * property. The order describes the preferred format of the client.
		 */
		documentationFormat?: [MarkupKind](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#markupContent)[];

		/**
		 * Client supports the deprecated property on a completion item.
		 */
		deprecatedSupport?: boolean;

		/**
		 * Client supports the preselect property on a completion item.
		 */
		preselectSupport?: boolean;

		/**
		 * Client supports the tag property on a completion item. Clients
		 * supporting tags have to handle unknown tags gracefully. Clients
		 * especially need to preserve unknown tags when sending a completion
		 * item back to the server in a resolve call.
		 *
		 * @since 3.15.0
		 */
		tagSupport?: {
			/**
			 * The tags supported by the client.
			 */
			valueSet: [CompletionItemTag](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItemTag)[];
		};

		/**
		 * Client supports insert replace edit to control different behavior if
		 * a completion item is inserted in the text or should replace text.
		 *
		 * @since 3.16.0
		 */
		insertReplaceSupport?: boolean;

		/**
		 * Indicates which properties a client can resolve lazily on a
		 * completion item. Before version 3.16.0 only the predefined properties
		 * `documentation` and `detail` could be resolved lazily.
		 *
		 * @since 3.16.0
		 */
		resolveSupport?: {
			/**
			 * The properties that a client can resolve lazily.
			 */
			properties: string[];
		};

		/**
		 * The client supports the `insertTextMode` property on
		 * a completion item to override the whitespace handling mode
		 * as defined by the client (see `insertTextMode`).
		 *
		 * @since 3.16.0
		 */
		insertTextModeSupport?: {
			valueSet: [InsertTextMode](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#insertTextMode)[];
		};

		/**
		 * The client has support for completion item label
		 * details (see also `CompletionItemLabelDetails`).
		 *
		 * @since 3.17.0
		 */
		labelDetailsSupport?: boolean;
	};

	completionItemKind?: {
		/**
		 * The completion item kind values the client supports. When this
		 * property exists the client also guarantees that it will
		 * handle values outside its set gracefully and falls back
		 * to a default value when unknown.
		 *
		 * If this property is not present the client only supports
		 * the completion items kinds from `Text` to `Reference` as defined in
		 * the initial version of the protocol.
		 */
		valueSet?: [CompletionItemKind](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItemKind)[];
	};

	/**
	 * The client supports to send additional context information for a
	 * `textDocument/completion` request.
	 */
	contextSupport?: boolean;

	/**
	 * The client's default when the completion item doesn't provide a
	 * `insertTextMode` property.
	 *
	 * @since 3.17.0
	 */
	insertTextMode?: [InsertTextMode](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#insertTextMode);

	/**
	 * The client supports the following `CompletionList` specific
	 * capabilities.
	 *
	 * @since 3.17.0
	 */
	completionList?: {
		/**
		 * The client supports the following itemDefaults on
		 * a completion list.
		 *
		 * The value lists the supported property names of the
		 * `CompletionList.itemDefaults` object. If omitted
		 * no properties are supported.
		 *
		 * @since 3.17.0
		 */
		itemDefaults?: string[];
	}
}
```

</details>

### Steps to reproduce using "nvim -u minimal_init.lua"

any

### Expected behavior

_No response_

### Neovim version (nvim -v)

NVIM v0.10.0-dev-5a2536d

### Language server name/version

any

### Operating system/version

any

### Log file

_No response_

### PR DESCRIPTION
**Pull request by wookayin**
Note: this PR consists of several commits, which were made in order to make diff atomic and PR easier to read/review, orthogonal to the upstream LSP model changes.

Follow-up after #23750.
Fixes #26617.

### Style improvements:

1. Anonymous classes derived from `StructureLiteralType` should have a
   better name. The class name can be also nested. Examples:

```diff
----@field serverInfo? anonym1
+---@field serverInfo? lsp._anonym1.serverInfo
```
```diff
----@field insertTextModeSupport? anonym26
+---@field insertTextModeSupport? lsp._anonym26.completionItem.insertTextModeSupport
```

2. Add one separate empty line before each `@field` definition. Without
   these, empty lines the doc can look confusing because descriptions
   also may contain empty lines. See `lsp.CompletionItem` for example:

```lua
---The kind of this completion item. Based of the kind
---an icon is chosen by the editor.
---@field kind? lsp.CompletionItemKind
---Tags for this completion item.
---
---@since 3.15.0
---@field tags? lsp.CompletionItemTag[]
```

   It might feel like "Tags for this completion item" belongs to `kind`,
   not `tags` due to the lack of separator blank lines. The following
   (after this commit) should look much better:

```diff
 ---The kind of this completion item. Based of the kind
 ---an icon is chosen by the editor.
 ---@field kind? lsp.CompletionItemKind
+---
 ---Tags for this completion item.
 ---
 ---@since 3.15.0
 ---@field tags? lsp.CompletionItemTag[]
```

3. Escape some LSP-specific annotations that can't be recognized by
   lua-ls. It'd be better to make them visible in LSP hover doc windows.

   Example: `@sample ...`.

### Fixes:

1. A type may extend from more than one base types (as well as mixin
   types). Previously only the first base class was being considered,
   resulting incomplete base classes for `@class` definitions.

   Example: `InlayHintOptions` (should have both of `resolveProvider`
   and `workDoneProgress`, the latter is from `WorkDoneProgressOptions`)

```diff
----@class lsp.InlayHintOptions
+---@class lsp.InlayHintOptions: lsp.WorkDoneProgressOptions
```

2. Remove `<200b>` (zero-width space) unicode characters.

3. Add the missing newline at EOF.

### CODE REVIEW

File: scripts/gen_lsp.lua [hunk 1]
```diff
@@ -154,95 +193,177 @@ function M.gen(opt)
...
+
+    -- StructureLiteralType
     elseif type.kind == 'literal' then
       -- can I use ---@param disabled? {reason: string}
       -- use | to continue the inline class to be able to add docs
       -- https://github.com/LuaLS/lua-language-server/issues/2128
       anonymous_num = anonymous_num + 1
-      local anonym = { '---@class anonym' .. anonymous_num }
-      for _, field in ipairs(type.value.properties) do
+      local anonymous_classname = 'lsp._anonym' .. anonymous_num
```
Comment (mfussenegger) [inline scripts/gen_lsp.lua:255]: Would it cause unintended conflicts without the `_anonym`+number part?

I see there's:

```
@class lsp._anonym50.TextDocumentFilter
@class lsp._anonym49.TextDocumentFilter
```

I suspect if we've functions that deal with these properties it might be more useful if they were actually the same type - given that they are the same thing.

**Review by mfussenegger — COMMENTED** [review]
Nice improvement :+1:

File: scripts/gen_lsp.lua (hunk 1 above)
Comment (wookayin) [reply scripts/gen_lsp.lua:255]: That's a great point I also noticed; I was planning to have a further improvement, but possibly as a separate PR (it's going to be a complicated one).

Eventually, we should remove the "anonym" thing; in this particular case the class can be named as something like `lsp.TextDocumentFilter`.

In most of such cases where several structured literal types (with the same filed name) are involved, they only differ in whether a field is optional or not. For example:

```diff
 ---@class lsp._anonym49.TextDocumentFilter
+---@field language string
 ---@field scheme? string
 ---@field pattern? string

 ---@class lsp._anonym50.TextDocumentFilter
 ---@field language? string
+---@field scheme string
 ---@field pattern? string

 ---@class lsp._anonym51.TextDocumentFilter
 ---@field language? string
 ---@field scheme? string
+---@field pattern string
```

The semantic here is either `language`, `scheme`, or `pattern` is given (but at least only one). This could be consolidated into one class:

```
---@class lsp.TextDocumentFilter
---@field language? string
---@field scheme? string
---@field pattern? string
```

since the "exclusive or" semantic here is not very important for us. In principle we can do some sort of type unification and merge types if applicable.
