### PR TITLE
fix(cmd): make :update work on new unmodified buffers

### LINKED ISSUE #35145: `:update` does not write new, empty buffer
### Problem

```
:edit foo/bar/baz.tx
:update ++p
```

Buffer is not written and the `foo/bar/` directory is not created.

### Expected behavior

`:update` should work on a new, empty buffer, without having to make edits to the buffer to convince `:update` to write it.

Maybe `bufIsChanged` should return true for new, empty buffers?

https://github.com/neovim/neovim/blob/78f4994627b7d9c3b85f30028fe55ff38024a39d/src/nvim/undo.c#L3106-L3109

### PR DESCRIPTION
**Pull request by glepnir**
Problem: update command does not write new buffers that have
filenames but no corresponding file on disk, even when using ++p flag.

Solution: allow update to write when buffer has filename but file
doesn't exist.

Fix #35145

### CODE REVIEW

File: test/functional/ex_cmds/write_spec.lua [hunk 1]
```diff
@@ -164,3 +164,98 @@ describe(':write', function()
...
+    local filename = 'test_dir/existing.txt'
+    local fd = io.open(filename, 'w')
+    fd:write('content')
+    fd:close()
+    local mtime_before = fn.getftime(filename)
+    command('edit ' .. filename)
+    command('update')
+    eq(mtime_before, fn.getftime(filename))
+  end)
+  --
```
Comment (zeertzjq) [inline test/functional/ex_cmds/write_spec.lua]: ?

File: src/nvim/ex_cmds.c [hunk 2]
```diff
@@ -1772,7 +1772,7 @@ void ex_file(exarg_T *eap)
 /// ":update".
 void ex_update(exarg_T *eap)
 {
-  if (curbufIsChanged()) {
+  if (curbufIsChanged() || (curbuf->b_ffname != NULL && !os_path_exists(curbuf->b_ffname))) {
```
Comment (seandewar) [inline src/nvim/ex_cmds.c:1775]: Depending on `&buftype`, `curbuf->b_ffname` may not represent the "real" file path. That may mean `:update` now `:write`s in cases where nothing changed, but the buffer isn't "new".

E.g: an `acwrite` buffer with a `BufWriteCmd` that writes over a network; such a buffer may even have a name like `foo://bar` that doesn't map to a "real" file, in which case `:update` will now always attempt to `:write` when the buffer wasn't changed...

Maybe check `bt_nofilename`?
Also, we're missing mentions of this change in `:h :update` and `vim-diff.txt`?

Comment (glepnir) [reply src/nvim/ex_cmds.c:1775]: 👍 thanks and followup https://github.com/neovim/neovim/pull/35939
