### PR TITLE
fix: also splice extmarks in preview buffers

### LINKED ISSUE #12967: Treesitter: inccommand nosplit causes virtual text error messages
- `nvim --version`:
```
NVIM v0.5.0-706-g42d13b90f                                                     
Build type: RelWithDebInfo                                                     
LuaJIT 2.1.0-beta3                                                             
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -W
all -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wsh
adow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-pro
tector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLAR
ATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN
_LOG_LEVEL=3 -I/build/nvim/parts/nvim/build/build/config -I/build/nvim/parts/nv
im/build/src -I/build/nvim/parts/nvim/build/.deps/usr/include -I/usr/include -I
/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build
/build/include                                                                 
Compiled by root@lcy01-amd64-026                                               
                                                                               
Features: +acl +iconv +tui                                                     
See ":help feature-compile"                                                    
                                                                               
   system vimrc file: "$VIM/sysinit.vim"                                       
  fall-back for $VIM: "/usr/share/nvim"   
```

- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Ubuntu 20.04/ MacOS 10
- Terminal name/version: kitty 0.18.3
- `$TERM`: xterm-kitty

#### Minimal init.vim
```vim
call plug#begin(stdpath('data') . '/plugged')
Plug 'nvim-treesitter/nvim-treesitter'
call plug#end()

lua << EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = 'all',
  highlight = {
    enable = true,
  },
}
EOF
```
1. open nvim with minimal vimrc above
```
nvim -u <path-to-minimal-vimrc-above>
```
2. open any filetype `nvim-treesitter` supports
3. set `inccommand=nosplit`
4. start substituting a word in the buffer until is about to be completely replaced

nvim-treesitter-inccommand

### Actual behaviour
As the image below show when using `inccommand=nosplit` with treesitter when a word is "collapsed" during substitution it causes, error messages to be inserted into the buffer as virtual text. These are cleared once you run `:e`.

treesitter-invalid-start

### Expected behaviour
No virtual text error messages and consistent highlighting

Side note: This also seems to happen when switching git branches whilst in nvim but I haven't nailed down the exact repro for that so will submit another issue once I have.

### PR DESCRIPTION
**Pull request by vigoux**
We indeed need to adjust extmarks in preview windows.

Should I add a test for that ?

Fixes #12967

### CODE REVIEW

File: src/nvim/buffer_updates.c [hunk 1]
```diff
@@ -237,7 +237,7 @@ void buf_updates_send_changes(buf_T *buf,
   for (size_t i = 0; i < kv_size(buf->update_callbacks); i++) {
     BufUpdateCallbacks cb = kv_A(buf->update_callbacks, i);
     bool keep = true;
-    if (cb.on_lines != LUA_NOREF) {
+    if (cb.on_lines != LUA_NOREF && (cb.preview || !(State & CMDPREVIEW))) {
```
Comment (vigoux) [inline src/nvim/buffer_updates.c:240]: Not sure about this version, but that avoided a whole bunch of changes, by passing arguments and so on

File: src/nvim/api/buffer.c [hunk 2]
```diff
@@ -121,6 +121,7 @@ Integer nvim_buf_line_count(Buffer buffer, Error *err)
 ///               - buffer handle
 ///             - utf_sizes: include UTF-32 and UTF-16 size of the replaced
 ///               region, as args to `on_lines`.
+///             - preview: also attach to command preview events
```
Comment (bfredl) [inline src/nvim/api/buffer.c:124]: add `'inccommand'` as a reference

File: test/functional/lua/buffer_updates_spec.lua [hunk 3]
```diff
@@ -493,6 +493,23 @@ describe('lua: nvim_buf_attach on_bytes', function()
       }
 
     end)
+
+    it('inccomand=nosplit and substitute', function()
+      if verify then pending("Verification can't be done when previewing") end
```
Comment (bfredl) [inline test/functional/lua/buffer_updates_spec.lua:498]: I would like this to work but I can do it in a follow up PR  :)
