### PR TITLE
Fix relative float positioning

### LINKED ISSUE #13403: nvim_win_get_position not work after nvim_open_win
- `nvim --version`: v0.5.0-822-g4e6f00dd2
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: MacOS
- Terminal name/version: iTerm2

### Steps to reproduce using `nvim -u NORC`

Source vim code: 

``` vim
let buf = nvim_create_buf(1,1)
call nvim_buf_set_lines(s:buf, 0, -1, v:false, ['a', 'b'])
let win = nvim_open_win(s:buf, v:false, {
      \ 'height':2,
      \ 'width': 10,
      \ 'col': 10,
      \ 'row': 10,
      \ 'relative': 'editor',
      \ 'style': 'minimal',
      \})
let pos = nvim_win_get_position(win)
echo pos
```

### Actual behaviour

Returned position is `[0, 0]`.

### Expected behaviour

Return window position.

I can use `redraw` to make `nvim_win_get_position` return correct window position, but seems that `redraw` should not be needed.

### PR DESCRIPTION
**Pull request by andrew-pa**
A fix for issue #13403, where `nvim_win_get_position` returns `[0,0]` instead of the actual position before the first redraw after a window is created, and also for #14735 where "nvim_open_win with relative=win doesn't work if win is a float", i.e. nested relative floats don't have the correct position.

### CODE REVIEW

**Comment by rmagatti** [comment]
Hey 👋 I'm pretty interested in #14735 getting fixed. Tried this branch out but still seeing unexpected positions using [goto-preview](https://github.com/rmagatti/goto-preview). And fwiw, this also seems to "break" Goneovim's floating window position implementation somehow.

I admittedly do not understand enough to know if this PR should have the effects I was hoping for but thought it might be worth sharing my attempts either way.

Thanks for working on this!

**Comment by andrew-pa** [comment]
Hi! Thanks for trying it out, it is definitely related and should have the desired effect. It looks like maybe I forgot to handle the borders, or is it more than that? I also tried Goneovim out and in my very limited testing I'm not sure what's exactly broken, do you mind uploading a screenshot? It looks like the borders are also off, and also killing a intermediate float messes up the children which might be a deeper problem. I will admit I'm new to this so I'm not entirely sure what's going on

**Comment by rmagatti** [comment]
@andrew-pa 
So this is me on the latest commit with the TUI in Kitty.


And this is the latest commit in Goneovim.


And this would be the desired positioning (gif in the goto-preview repo) which only happens with Goneovim (and other GUIs like Uivonim) but not with the TUI.
https://github.com/rmagatti/goto-preview

**Comment by andrew-pa** [comment]
@rmagatti 
Ok let me see if I can get your plugin installed so I can reproduce that exactly. I suspect something to do with text positions/scrolling. Thanks!

File: src/nvim/window.c [hunk 1]
```diff
@@ -782,26 +826,8 @@ void ui_ext_win_position(win_T *wp)
   FloatConfig c = wp->w_float_config;
   if (!c.external) {
     ScreenGrid *grid = &default_grid;
-    float row = c.row, col = c.col;
```
Comment (bfredl) [inline src/nvim/window.c:785]: Hmm this is not really correct for multigrid. Does it work to use `comp_row += grid->comp_row`  just below `int comp_row = (int)row - (south ? wp->w_height : 0);` ? This will also reuse the nested bufpos calculation already done for the parent float.

Comment (andrew-pa) [reply src/nvim/window.c:785]: Yes this is much better! I've updated the branch to reflect this. Is there something simular that can be done for computing the position of windows initially for #13403?

**Comment by andrew-pa** [comment]
@rmagatti does this work for you now? It seems to be working for me.
I've noticed that the window position code automatically positions windows one line below the line of text they are supposed to be relative to when you set `bufpos`, I'm assuming that was that the intended behavior?

File: src/nvim/window.c [hunk 2]
```diff
@@ -737,6 +737,44 @@ void win_config_float(win_T *wp, FloatConfig fconfig)
     redraw_later(wp, NOT_VALID);
   }
 
+  // compute initial position
+  if (wp->w_float_config.relative == kFloatRelativeWindow) {
+    int row = 0;
+    int col = 0;
+    Error dummy = ERROR_INIT;
+    win_T *win = wp;
+    while (win) {
```
Comment (bfredl) [inline src/nvim/window.c:746]: is the loop here really needed? Can't we just use `wp->w_winrow` of the parent?

Comment (andrew-pa) [reply src/nvim/window.c]: Yeah that works, I didn't realize. I've made the change in the latest commit.

**Comment by rmagatti** [comment]
Hey @andrew-pa this does work perfectly for me actually. Nice work! 🎉

**Comment by andrew-pa** [comment]
Alright fantastic, that's good to know! Thanks for testing stuff out.

**Comment by XVilka** [comment]
Shouldn't be this one marked for 0.5.0 milestone as well, as solving one of the issues from the milestone?

**Comment by mjlbach** [comment]
We're releasing tomorrow so my guess is this will end up in the first patch release

**Comment by andrew-pa** [comment]
Alright that's cool. Is there something remaining to be done that is blocking this from being merged? I've just been kinda waiting, and it's cool if it's just in backlog that makes sense.

**Comment by clason** [comment]
If this is ready, could you squash your commits and use a [conventional commit message](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#commit-messages)? Also, in general please don't merge `master` into your PR -- if needed, you should instead `rebase` your PR on `master` to keep the history clean, and help with bisecting.

**Comment by andrew-pa** [comment]
Is there anything left blocking this from being merged?

**Review by vigoux — APPROVED** [review]
Everything seems _sane_ in this PR, though I am not sure about the actual functionallity, so I'd wait for @bfredl on this

**Comment by andrew-pa** [comment]
@bfredl Are we waiting on anything else to get this merged?

File: src/nvim/window.c (hunk 1 above)
Comment (bfredl) [reply src/nvim/window.c:785]: this change still needs to be reverted.

**Comment by bfredl** [comment]
Only my review comment that wasn't fixed yet.

**Comment by andrew-pa** [comment]
> Only my review comment that wasn't fixed yet.

Alright sorry I totally missed what that was getting at, should be fixed now.

**Comment by bfredl** [comment]
merged, sorry for the wait :sweat_smile:
