### PR TITLE
fix(vim.iter): use correct cmp function when truncating tail in `take`

### LINKED ISSUE #27997: vim.iter doesn't respect `take(n)` when called after `rev()`
### Problem

Calling `take` on a reversed iterator (`vim.iter`) is not respected. If `take` is called before `rev`, then it will be respected. If the iterator is unreversed (`iter:rev():rev()`) then `take` will also again be respected.

### Steps to reproduce

```lua
vim.iter({ 1, 2, 3 }):take(2)
-- GOOD: Produces { 1, 2 }

vim.iter({ 1, 2, 3 }):rev():rev():take(2)
-- GOOD: Produces { 1, 2 }

vim.iter({ 1, 2, 3 }):take(2):rev()
-- GOOD: Produces { 3, 2 }

vim.iter({ 1, 2, 3 }):rev():take(2)
-- PROBLEM: Produces { 3, 2, 1 }
```

### Expected behavior

```lua
vim.iter({ 1, 2, 3 }):rev():take(2)
-- EXPECTED: { 3, 2 }
```

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2671+gdc110cba3

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

bob

### PR DESCRIPTION
**Pull request by cbochs**
Fixes https://github.com/neovim/neovim/issues/27997

### CODE REVIEW

File: test/functional/lua/iter_spec.lua [hunk 1]
```diff
@@ -139,6 +139,8 @@ describe('vim.iter', function()
 
   it('rev()', function()
     eq({ 3, 2, 1 }, vim.iter({ 1, 2, 3 }):rev():totable())
+    eq({ 3, 2 }, vim.iter({ 1, 2, 3 }):rev():take(2):totable())
```
Comment (gpanders) [inline test/functional/lua/iter_spec.lua:142]: Thank you for adding a test case! I think these cases belong in the `take()` test block rather than `rev()` though.

Comment (cbochs) [reply test/functional/lua/iter_spec.lua]: Moved!

**Review by gpanders — APPROVED** [review]
