### PR TITLE
fix(shada): prevent use-after-free when mapping file marks

### LINKED ISSUE #34440: shada: heap-use-after-free
### Problem

When running Nvim with ASAN and `UBSAN_OPTIONS=print_stacktrace=1 ASAN_OPTIONS=abort_on_error=1:log_path=/tmp/nvim_asan`, ASAN detects a heap-use-after-free on exit:
```
=================================================================
==808198==ERROR: AddressSanitizer: heap-use-after-free on address 0x7b9b606b0b90 at pc 0x55ff71a5400d bp 0x7fff9e5ebf80 sp 0x7fff9e5eb740
READ of size 1 at 0x7b9b606b0b90 thread T0
    #0 0x55ff71a5400c in strcmp.part.0 asan_interceptors.cpp.o
    #1 0x55ff726d2963 in strequal **/src/nvim/memory.c:550:49
    #2 0x55ff72558278 in mh_find_bucket_cstr_t **/src/nvim/map_key_impl.c.h:35:16
    #3 0x55ff725596f0 in mh_put_cstr_t **/src/nvim/map_key_impl.c.h:101:18
    #4 0x55ff7255bcbc in map_put_ref_cstr_tptr_t **/src/nvim/map_value_impl.c.h:32:16
    #5 0x55ff72beb180 in shada_read_when_writing **/src/nvim/shada.c:1909:20
    #6 0x55ff72bc6da6 in shada_write **/src/nvim/shada.c:2589:39
    #7 0x55ff72bbf567 in shada_write_file **/src/nvim/shada.c:2848:35
    #8 0x55ff72547d0f in getout **/src/nvim/main.c:781:5
    #9 0x55ff7224cb83 in ex_quit **/src/nvim/ex_docmd.c:4788:7
    #10 0x55ff72217cdb in execute_cmd0 **/src/nvim/ex_docmd.c:1724:7
    #11 0x55ff721f7b0f in do_one_cmd **/src/nvim/ex_docmd.c:2368:7
    #12 0x55ff721ecb25 in do_cmdline **/src/nvim/ex_docmd.c:675:20
    #13 0x55ff721f0c68 in do_cmdline_cmd **/src/nvim/ex_docmd.c:378:10
    #14 0x55ff730d0ade in do_window **/src/nvim/window.c:295:5
    #15 0x55ff727d3559 in nv_window **/src/nvim/normal.c:5142:5
    #16 0x55ff727cb49a in normal_execute **/src/nvim/normal.c:1246:3
    #17 0x55ff72cf54b5 in state_enter **/src/nvim/state.c:102:26
    #18 0x55ff727ae081 in normal_enter **/src/nvim/normal.c:523:3
    #19 0x55ff725352d9 in main **/src/nvim/main.c:655:3
    #20 0x7f5b614356b4 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #21 0x7f5b61435768 in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #22 0x55ff7198c004 in _start (**/build/bin/nvim+0xc67004) (BuildId: 5ace9cfa12a6e27c64b78423dedd3ac098aa9137)

0x7b9b606b0b90 is located 0 bytes inside of 36-byte region [0x7b9b606b0b90,0x7b9b606b0bb4)
freed by thread T0 here:
    #0 0x55ff71a8c28d in free.part.0 asan_malloc_linux.cpp.o
    #1 0x55ff726d0e10 in xfree **/src/nvim/memory.c:161:3
    #2 0x55ff72bee560 in shada_free_shada_entry **/src/nvim/shada.c:2961:5
    #3 0x55ff72bec495 in shada_read_when_writing **/src/nvim/shada.c:1947:19
    #4 0x55ff72bc6da6 in shada_write **/src/nvim/shada.c:2589:39
    #5 0x55ff72bbf567 in shada_write_file **/src/nvim/shada.c:2848:35
    #6 0x55ff72547d0f in getout **/src/nvim/main.c:781:5
    #7 0x55ff7224cb83 in ex_quit **/src/nvim/ex_docmd.c:4788:7
    #8 0x55ff72217cdb in execute_cmd0 **/src/nvim/ex_docmd.c:1724:7
    #9 0x55ff721f7b0f in do_one_cmd **/src/nvim/ex_docmd.c:2368:7
    #10 0x55ff721ecb25 in do_cmdline **/src/nvim/ex_docmd.c:675:20
    #11 0x55ff721f0c68 in do_cmdline_cmd **/src/nvim/ex_docmd.c:378:10
    #12 0x55ff730d0ade in do_window **/src/nvim/window.c:295:5
    #13 0x55ff727d3559 in nv_window **/src/nvim/normal.c:5142:5
    #14 0x55ff727cb49a in normal_execute **/src/nvim/normal.c:1246:3
    #15 0x55ff72cf54b5 in state_enter **/src/nvim/state.c:102:26
    #16 0x55ff727ae081 in normal_enter **/src/nvim/normal.c:523:3
    #17 0x55ff725352d9 in main **/src/nvim/main.c:655:3
    #18 0x7f5b614356b4 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #19 0x7f5b61435768 in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #20 0x55ff7198c004 in _start (**/build/bin/nvim+0xc67004) (BuildId: 5ace9cfa12a6e27c64b78423dedd3ac098aa9137)

previously allocated by thread T0 here:
    #0 0x55ff71a8d1f5 in malloc (**/build/bin/nvim+0xd681f5) (BuildId: 5ace9cfa12a6e27c64b78423dedd3ac098aa9137)
    #1 0x55ff726d0ae4 in try_malloc **/src/nvim/memory.c:115:15
    #2 0x55ff726d0d44 in xmalloc **/src/nvim/memory.c:149:15
    #3 0x55ff726d115a in xmallocz **/src/nvim/memory.c:221:15
    #4 0x55ff726d1283 in xmemdupz **/src/nvim/memory.c:239:17
    #5 0x55ff72bf2b52 in shada_read_next_item **/src/nvim/shada.c:3319:36
    #6 0x55ff72be6e9c in shada_read_when_writing **/src/nvim/shada.c:1777:22
    #7 0x55ff72bc6da6 in shada_write **/src/nvim/shada.c:2589:39
    #8 0x55ff72bbf567 in shada_write_file **/src/nvim/shada.c:2848:35
    #9 0x55ff72547d0f in getout **/src/nvim/main.c:781:5
    #10 0x55ff7224cb83 in ex_quit **/src/nvim/ex_docmd.c:4788:7
    #11 0x55ff72217cdb in execute_cmd0 **/src/nvim/ex_docmd.c:1724:7
    #12 0x55ff721f7b0f in do_one_cmd **/src/nvim/ex_docmd.c:2368:7
    #13 0x55ff721ecb25 in do_cmdline **/src/nvim/ex_docmd.c:675:20
    #14 0x55ff721f0c68 in do_cmdline_cmd **/src/nvim/ex_docmd.c:378:10
    #15 0x55ff730d0ade in do_window **/src/nvim/window.c:295:5
    #16 0x55ff727d3559 in nv_window **/src/nvim/normal.c:5142:5
    #17 0x55ff727cb49a in normal_execute **/src/nvim/normal.c:1246:3
    #18 0x55ff72cf54b5 in state_enter **/src/nvim/state.c:102:26
    #19 0x55ff727ae081 in normal_enter **/src/nvim/normal.c:523:3
    #20 0x55ff725352d9 in main **/src/nvim/main.c:655:3
    #21 0x7f5b614356b4 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #22 0x7f5b61435768 in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #23 0x55ff7198c004 in _start (**/build/bin/nvim+0xc67004) (BuildId: 5ace9cfa12a6e27c64b78423dedd3ac098aa9137)

SUMMARY: AddressSanitizer: heap-use-after-free asan_interceptors.cpp.o in strcmp.part.0
Shadow bytes around the buggy address:
  0x7b9b606b0900: fa fa fd fd fd fd fd fd fa fa fd fd fd fd fd fd
  0x7b9b606b0980: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x7b9b606b0a00: fa fa fd fd fd fd fd fd fa fa fd fd fd fd fd fd
  0x7b9b606b0a80: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fd
  0x7b9b606b0b00: fa fa fd fd fd fd fd fd fa fa fd fd fd fd fd fd
=>0x7b9b606b0b80: fa fa[fd]fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x7b9b606b0c00: fa fa 00 00 00 00 00 07 fa fa 00 00 00 00 00 07
  0x7b9b606b0c80: fa fa 00 00 00 00 00 07 fa fa 00 00 00 00 00 07
  0x7b9b606b0d00: fa fa 00 00 00 00 00 07 fa fa 00 00 00 00 00 07
  0x7b9b606b0d80: fa fa 00 00 00 00 00 07 fa fa 00 00 00 00 00 07
  0x7b9b606b0e00: fa fa 00 00 00 00 00 07 fa fa 00 00 00 00 00 07
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==808198==ABORTING
```

This is bisected to <https://github.com/neovim/neovim/commit/b98eefd8030c398735f4069ddc05b3e5b7a511a5> (#34373).

Note that the `abort_on_error=1` is required for bisecting, otherwise the ASAN log somehow isn't written before <https://github.com/neovim/neovim/commit/2dba5abcb2ee8d568b8f0181223930b598ea3c90>, and the heap-use-after-free is not observable.

### Steps to reproduce

Not available

### Expected behavior

No heap-use-after-free

### Nvim version (nvim -v)

v0.12.0-dev-565+gfb7a234f01

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.42.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by glepnir**
Problem: When ignore_buf skips buffers during initialization, shada_read_when_writing uses entry.data.filemark.fname directly as map key, but later frees the entry, leaving dangling pointers.

Solution: Always create independent copies of filenames as map keys using xstrdup() for new items, and free all keys during cleanup.

Fix #34440

### CODE REVIEW

File: src/nvim/shada.c [hunk 1]
```diff
@@ -2714,6 +2723,10 @@ static ShaDaWriteResult shada_write(FileDescriptor *const sd_writer,
   map_foreach_value(&wms->file_marks, val, {
     xfree(val);
   })
+  const char *stored_key = NULL;
+  map_foreach_key(&wms->file_marks, stored_key, {
+    xfree((char *)stored_key);
```
Comment (justinmk) [inline src/nvim/shada.c:2725]: how is this different than the `map_foreach_value(&wms->file_marks, val` loop just above this?

Comment (zeertzjq) [reply src/nvim/shada.c:2725]: Combine them into a single `map_foreach()`?

Comment (justinmk) [reply src/nvim/shada.c:2725]: oops I did not see that `map_foreach_value` and `map_foreach_key` are different names, I was focused on `&wms->file_marks`.

using `map_foreach` might be a bit more readable.

File: src/nvim/shada.c [hunk 2]
```diff
@@ -2714,6 +2723,10 @@ static ShaDaWriteResult shada_write(FileDescriptor *const sd_writer,
...
+  })
```
Comment (zeertzjq) [inline src/nvim/shada.c]:
```suggestion
  const char *stored_key = NULL;
  map_foreach(&wms->file_marks, stored_key, val, {
    xfree((char *)stored_key);
    xfree(val);
  })
```
