### PR TITLE
fix(lua): clear got_int when calling vim.on_key() callback

### LINKED ISSUE #17273: `<c-c>` causes `vim.on_key` to raise an error when calling `vim.fn` functions
### Neovim version (nvim -v)

NVIM v0.7.0-dev+894-g561df3098

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 12.1

### Terminal name/version

kitty 0.21.0

### $TERM environment variable

xterm-kitty

### Installation

brew install --HEAD neovim

### How to reproduce the issue

`foo.lua`:
```lua
vim.on_key(function(key)
    -- vim.api.* functions don't cause an error
    print(vim.fn.mode())
end, nil)
```

```bash
nvim --clean foo.lua
:so %
:startinsert
`<c-c>`
```

### Expected behavior

```
Error executing  vim.on_key Lua callback: vim.lua:0: Error executing 'on_key' with ns_ids '2'                                                            
    Messages: Keyboard interrupt
stack traceback:
        [C]: in function 'error'
        vim.lua: in function <vim.lua:0>
```

### Actual behavior

I would expect no error to show. Should I be wrapping calls to `vim.fn` in `vim.schedule_wrap`?

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #17273

### CODE REVIEW

File: src/nvim/getchar.c [hunk 1]
```diff
@@ -1644,7 +1644,10 @@ int vgetc(void)
   may_garbage_collect = false;
 
   // Execute Lua on_key callbacks.
+  int save_got_int = got_int;
+  got_int = false;
   nlua_execute_on_key(c);
+  got_int = save_got_int;
```
Comment (justinmk) [inline src/nvim/getchar.c:1650]: can this stuff live in `nlua_execute_on_key` ?

Comment (zeertzjq) [reply src/nvim/getchar.c]: Yes.

**Comment by zeertzjq** [comment]
The Windows test failure may be related:
```
  [  ERROR   ] test/functional\vimscript\let_spec.lua @ 27: :let :unlet self-referencing node in a List graph #6070
  test\functional\helpers.lua:106: EOF was received from Nvim. Likely the Nvim process crashed.
  stack traceback:
  	test\functional\helpers.lua:106: in function 'exec'
  	test\functional\helpers.lua:505: in function 'source'
  	test/functional\vimscript\let_spec.lua:30: in function <test/functional\vimscript\let_spec.lua:27>
```

But I don't think `got_int` is involved in that test.

**Review by justinmk — APPROVED** [review]
