### PR TITLE
fix(windows): don't set window icon on SIGHUP

### LINKED ISSUE #34171: SIGHUP causes slow shutdown on windows
### Problem

Closing nvim by closing conhost window causes error and freezes nvim window. I think the specific issue is that SIGHUP causes slow shutdown.

https://github.com/user-attachments/assets/4bc7d4ac-dabf-4a1d-938e-3728e6bda4f9

### Steps to reproduce

1. Open conhost
2. Run nvim.exe --clean
3. Close conhost window

### Expected behavior

Nvim closes instantly without a message like `:!qa`. This is how vim works.

### Nvim version (nvim -v)

v0.11.1

### Vim (not Nvim) behaves the same?

No, vim 9.1.1335

### Operating system/version

Windows 11 24H2

### Terminal name/version

conhsot (latest pre-installed)

### $TERM environment variable

N/A (windows)

### Installation

winget install neovim

### PR DESCRIPTION
**Pull request by 11soda11**
Problem:
When using conhost and pressing the 'x' button
to close it while nvim is open, nvim hangs up
while trying to reset the window icon, causing a big delay before the terminal actually closes.

Solution:
Set the window handle to NULL after receiving SIGHUP so that nvim will not try resetting the icon.

Fixes: #34171

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

File: src/nvim/os/os_win_console.c
Comment (11soda11) [inline src/nvim/os/os_win_console.c:1]: This doesn't have to do with the issue, but in `os_icon_init` the calls to `SendMessage` with `WM_GETICON` and then `os_icon_set` could be replaced by one `WM_SETICON` message, since it returns the original icon. This would also make `os_icon_set` unnecessary, because the only other place its called is on exit to reset the icon, so it could just be replaced by a simpler function only for resetting to original. Is this change appropriate/wanted here? or at all? Would be open to making another pr or including it here.

Comment (justinmk) [reply src/nvim/os/os_win_console.c:1]: definitely welcome in another pr. that code was added in a rather "hope this works" fashion, so improvements like this are welcome.

**Comment by justinmk** [comment]
@Sodastream11 does reverting 4dabeff30822 also fix this issue? Will be useful to know the blast-radius of that change. Oh, https://github.com/neovim/neovim/issues/34171 says the issue applies to 0.11.x, so I guess 4dabeff30822 isn't related.

File: src/nvim/os/os_win_console.c
Comment (11soda11) [reply src/nvim/os/os_win_console.c:1]: I see. Will open another pr soon.

File: src/nvim/os/os_win_console.c [hunk 1]
```diff
@@ -29,6 +29,11 @@ int os_open_conin_fd(void)
   return conin_fd;
 }
 
+void os_clear_hwnd(void) 
+{
+    hWnd = NULL;
```
Comment (zeertzjq) [inline src/nvim/os/os_win_console.c:34]: This line has wrong indent

Comment (11soda11) [reply src/nvim/os/os_win_console.c:34]: will fix in next pr
