### PR TITLE
fix(tui): set cursor color parameter as string when required

### LINKED ISSUE #20628: ":highlight Cursor" can't work.
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Archlinux x86_64

### Terminal name/version

alacritty (0.10.1)

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

":highlight Cursor guibg=red" can't work when you are in a night color scheme.

This command is available in version 0.7.2 but not in version 0.8.0.

### Expected behavior

expect

### Actual behavior

bug

### PR DESCRIPTION
**Pull request by tomcur**
See #20628. Terminals supporting cursor color changing usually set the "user-defined" `Cs` terminfo capability. Most terminals expect the parameter to the capability to be a string (in hex format like `#0099ff` or like `rgb:00/99/ff`), others may expect a number.

Neovim currently can't handle string parameters, causing terminals to receive a bogus command.

Unfortunately, as the `Cs` capability is "user-defined", there's no strict format. The parameter it takes isn't really standardized. It seems most terminals in use follow xterm; iTerm appears to be an exception.

This PR makes using the `Cs` capability more reliable by following terminfo and sending the color in hex format, at the cost of using unibilium string vars. Alternatively, https://github.com/neovim/neovim/commit/34d41baf8a8e4ab8c006b7f29a8106e60e311aa2 could be reverted and the specific format required by terminals to be hardcoded, instead of reading from terminfo.

Fixes #20628, #19607.

### CODE REVIEW

**Comment by tomcur** [comment]
Need to take a look at the CI failures.

**Comment by tomcur** [comment]
Took some time to look into terminfo/tic/unibilium. The CI failure was due to the failing platforms' tests including terminfo files with explicitly cancelled `Cs` capabilities. Apparently cancelled terminal capabilities remain as string capabilities, with the string a null pointer.

This means some of the capability checking in tui is subtly wrong, but there's probably no situation in which it matters.

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -2148,10 +2169,20 @@ static void augment_terminfo(TUIData *data, const char *term, long vte_version,
...
       data->unibi_ext.set_cursor_color = (int)unibi_add_ext_str(ut, "ext.set_cursor_color",
-                                                                "\033]12;#%p1%06x\007");
+                                                                "\033]12;%p1%s\007");
     }
   }
   if (-1 != data->unibi_ext.set_cursor_color) {
+    /// Some terminals supporting cursor color changing specify their Cs
+    /// capability to take a string parameter. Others take a numeric parameter.
+    /// If and only if the format string contains `%s` we assume a string
+    /// parameter. #20628
```
Comment (zeertzjq) [inline src/nvim/tui/tui.c:2179]:
```suggestion
    // Some terminals supporting cursor color changing specify their Cs
    // capability to take a string parameter. Others take a numeric parameter.
    // If and only if the format string contains `%s` we assume a string
    // parameter. #20628
```

**Comment by tomcur** [comment]
Windows CI failure is unrelated.

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
@kraftwerk28

**Comment by justinmk** [comment]
Thank you @tomcur for the careful work here and the references. (Please include the info in the commit message in the future :)

Thanks @erw7  for bisecting!
