### PR TITLE
win: locale independent argv

### LINKED ISSUE #7060: Failed to open multibyte filename on Windows passed by command argument
- `nvim --version`: master 4bcc70b2b5b02e3a6048b55a4390739570db3524
- Vim (version: 8.0) behaves differently? Yes
- Operating system/version: Windows 10 (**Japanese locale**)
- Terminal name/version: powershell.exe (ConEmu)
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`
1. Create text file as multibyte filename (ex. 日本語.txt)
2. Open 日本語.txt with vim `vim -u NORC .\日本語.txt`
3. `:echo bufname('%')` returns `.\日本語.txt`
3. Write something and save
2. Open 日本語.txt with nvim `nvim -u NORC .\日本語.txt`
1. Nothing shown in the buffer
1. `:echo bufname('%')` returns `.\<93><fa><96>{<8c><ea>.txt`

### Actual behavior
[https://gyazo.com/4b74d937fc39f3afcbdb60f2b43eb739](https://gyazo.com/4b74d937fc39f3afcbdb60f2b43eb739)

### Expected behavior
vim screenshot (`encoding` not set correctly)
[https://gyazo.com/f260d3873dd7a0af259a908465d4d73f](https://gyazo.com/f260d3873dd7a0af259a908465d4d73f)

### PR DESCRIPTION
**Pull request by yuntan**
fix #7060

What should I do when `malloc()` fails? (https://github.com/neovim/neovim/commit/8926d6c684c5afc66a9d842effb544d810356e09#diff-21cf87db76bbcab0a3b5054f99b4ef85R245)

### CODE REVIEW

File: src/nvim/main.c [hunk 1]
```diff
@@ -217,10 +222,31 @@ void early_init(void)
...
 int main(int argc, char **argv)
 #endif
 {
+#ifdef WIN32
+  char *argv[argc];
+
+  for(size_t i = 0; i < (size_t)argc; i++) {
+    // get required buffer size
+    size_t dest_size = (size_t)WideCharToMultiByte(CP_UTF8, 0, argv_w[i], -1, NULL, 0, NULL, NULL);
+    char *buf = (char *)malloc(dest_size + 1);
```
Comment (oni-link) [inline src/nvim/main.c]: We use the memory allocation functions in `memory.c`, so in this case we could use `xmalloc()`. With this function the program would exit, if not enough memory can be allocated.

Comment (jamessan) [inline src/nvim/main.c]: This can be changed to

```c
char *buf = xmallocz(dest_size);
```

It will either allocate the required memory or exit.  `xmallocz` also ensures the last byte is `NUL`.

**Comment by jamessan** [comment]
Lint issues:

```
src/nvim/main.c:233:  Missing space before ( in for(  [whitespace/parens] [5]
src/nvim/main.c:235:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/nvim/main.c:236:  Use xmalloc(...) instead of malloc(...).  [runtime/memory_fn] [2]
src/nvim/main.c:239:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
Total errors found: 4
```

File: src/nvim/main.c [hunk 2]
```diff
@@ -215,10 +220,28 @@ void early_init(void)
 
 #ifdef MAKE_LIB
 int nvim_main(int argc, char **argv)
+#elif defined WIN32
+// don't use codepage encoded arguments. see #7060
+int wmain(int argc, wchar_t **argv_w)
```
Comment (justinmk) [inline src/nvim/main.c]: should also be done for `MAKE_LIB` case, no?

Comment (justinmk) [inline src/nvim/main.c]: oh, probably not. We simply expect the caller to have encoded the arguments correctly when it calls `nvim_main()`.

**Comment by justinmk** [comment]
LGTM. Nice solution

**Comment by justinmk** [comment]
Revisited in https://github.com/neovim/neovim/pull/31193
