### PR TITLE
fix(tui): don't overwrite an assertion faliure message on exit

### LINKED ISSUE #21608: TUI: cannot see server stderr when Nvim server process crashes
### Neovim version (nvim -v)

NVIM v0.9.0-dev-590+g6ba34e21f

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Run `nvim --clean`
2. Try to trigger an assert failure (for example the one in #7889)

### Expected behavior

The assert failure can be seen

### Actual behavior

The assert failure cannot be seen

### PR DESCRIPTION
**Pull request by bfredl**
Fix #21608

If nvim exited with nonzero status this is for one of the two reasons:
- `:cquit` was invoked. This is used by users and plugins to communicate a result, like a nonzero status will fail a `git commit` operation
- There was an internal error or deadly signal. in this case an error message was likely written to stderr or to the screen.

In the latter case, the error message was often hidden by the TUI exiting altscreen mode, which erases all visible terminal text.

This change prevents this in the latter case, while still cleaning up the terminal properly when `:cquit` was deliberatily invoked. Other cleanup like exiting mouse mode and raw mode is still done.

### CODE REVIEW

File: src/nvim/event/process.c [hunk 1]
```diff
@@ -423,6 +423,7 @@ static void exit_event(void **argv)
 
   if (!exiting) {
     if (ui_client_channel_id) {
+      ui_client_exit_status = status;
       os_exit(status);
```
Comment (justinmk) [inline src/nvim/event/process.c:427]: Off-topic: `os_exit` doesn't [set v:exiting](https://github.com/neovim/neovim/blob/a293e2794dcf65a35eda6eeea6ea480bfef9dc73/src/nvim/main.c#L697) , wonder if we can all `getout` here instead.

File: src/nvim/tui/tui.c [hunk 2]
```diff
@@ -384,8 +386,13 @@ static void terminfo_stop(TUIData *tui)
   unibi_out_ext(tui, tui->unibi_ext.disable_extended_keys);
   // May restore old title before exiting alternate screen.
   tui_set_title(tui, (String)STRING_INIT);
-  // Exit alternate screen.
-  unibi_out(tui, unibi_exit_ca_mode);
+  // if nvim exited with nonzero status, without indicated this was an
+  // intentional exit (like `:1cquit`), it likely was an internal failure.
+  // Don't clobber the stderr error message in this case.
+  if (ui_client_exit_status == tui->seen_error_exit) {
```
Comment (justinmk) [inline src/nvim/tui/tui.c:392]: Can we use [v:exiting](https://github.com/neovim/neovim/blob/a293e2794dcf65a35eda6eeea6ea480bfef9dc73/src/nvim/main.c#L697) instead of adding `ui_client_exit_status`? Could init `seen_error_exit = INT_MAX`, then condition could be `if (tui->seen_error_exit != INT_MAX)`

File: src/nvim/api/ui_events.in.h [hunk 3]
```diff
@@ -167,4 +167,7 @@ void msg_history_show(Array entries)
   FUNC_API_SINCE(6) FUNC_API_REMOTE_ONLY;
 void msg_history_clear(void)
   FUNC_API_SINCE(10) FUNC_API_REMOTE_ONLY;
+
+void error_exit(Integer status)
```
Comment (justinmk) [inline src/nvim/api/ui_events.in.h:171]: Any reason not to make this a more general "exit" event? The status signals whether it's an error or not.

File: src/nvim/event/process.c (hunk 1 above)
Comment (bfredl) [reply src/nvim/event/process.c:427]: This code runs in the TUI process, `v:exiting` and the stuff which happens in `getout()` is not relevant for it (it might work by accident, but I think using `os_exit()` directly expresses the intent).

File: src/nvim/api/ui_events.in.h (hunk 3 above)
Comment (bfredl) [reply src/nvim/api/ui_events.in.h:171]: sure, could be done as a follow-up.
