### PR TITLE
fix(api): nvim_cmd{cmd="win_getid"} parsed as :winsize

### LINKED ISSUE #20681: nvim_cmd: vim.cmd.win_getid(...) invokes :winsize (resizes the editor)
### Steps to reproduce the issue

    :lua vim.cmd.win_getid(30,10)

API equivalent:

    :lua vim.api.nvim_cmd({cmd='win_getid', args={30,10}}, {})

### Expected behavior

Call `win_getid()` vimscript function.

### Actual behavior

The editors resizes. Resizing the terminal restores the correct size.

### LINKED ISSUE #24127: `nvim_cmd` does not fail when arguments are passed improperly
### Problem

When `nvim_cmd` is used incorrectly by having an argument be passed in the `cmd` string, it returns the empty string instead of failing.

### Steps to reproduce

```lua
vim.api.nvim_cmd({ cmd = "echo", args={"'hi'"} }, { output = true }) -- succeeds and returns "hi"
vim.api.nvim_cmd({ cmd = "echo 'hi'" }, { output = true }) -- succeeds and returns the empty string
vim.api.nvim_cmd({ cmd = "echoz 'hi'" }, { output = true }) -- fails because echoz is not defined
```

### Expected behavior

Improper usage should fail.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

N/A

### PR DESCRIPTION
**Pull request by justinmk**
Problem:
`:lua vim.cmd.win_getid(30,10)` is interpreted as `:win[size] 30 10`. User intention was to call `vim.fn.win_getid(30,10)`.

Solution:
Check that the `cmd` actually matches the resolved command.

fix #24127 
fix #20681

### CODE REVIEW

File: src/nvim/api/command.c [hunk 1]
```diff
@@ -393,6 +394,13 @@ String nvim_cmd(uint64_t channel_id, Dict(cmd) *cmd, Dict(cmd_opts) *opts, Error
   VALIDATE(!is_cmd_ni(ea.cmdidx), "Command not implemented: %s", cmdname, {
     goto end;
   });
+  const char *fullname = IS_USER_CMDIDX(ea.cmdidx)
+    ? get_user_command_name(ea.useridx, ea.cmdidx)
+    : get_command_name(NULL, ea.cmdidx);
+  VALIDATE(strstr(fullname, cmdname), "Invalid command: \"%s\"", cmdname, {
```
Comment (zeertzjq) [inline src/nvim/api/command.c:400]: I think one of these makes more sense: 
```suggestion
  VALIDATE(strncmp(fullname, cmdname, strlen(cmdname)), "Invalid command: \"%s\"", cmdname, {
```
or
```suggestion
  VALIDATE(strstr(fullname, cmdname) == fullname, "Invalid command: \"%s\"", cmdname, {
```

File: src/nvim/api/command.c [hunk 2]
```diff
@@ -373,7 +373,8 @@ String nvim_cmd(uint64_t channel_id, Dict(cmd) *cmd, Dict(cmd_opts) *opts, Error
   cmdname = string_to_cstr(cmd->cmd.data.string);
   ea.cmd = cmdname;
 
-  char *p = find_ex_command(&ea, NULL);
+  int is_fullname;
+  char *p = find_ex_command(&ea, &is_fullname);
```
Comment (famiu) [inline src/nvim/api/command.c:377]: I don't see `is_fullname` being used anywhere
