### PR TITLE
fix(treesitter): check that buf is loaded in autocommands

### LINKED ISSUE #25673: InspectTree: check if source buffer exists
### Problem

The Treesitter playground window does not check if the source buffer exists when executes autocommands (`CursorMoved`, `BufLeave`).

```
Error detected while processing CursorMoved Autocommands for "<buffer=62>":                                                                                                                                                              
Error executing lua callback: ...m-from-src/share/nvim/runtime/lua/vim/treesitter/dev.lua:369: Invalid buffer id: 61
stack traceback:
        [C]: in function 'nvim_buf_clear_namespace'
        ...m-from-src/share/nvim/runtime/lua/vim/treesitter/dev.lua:369: in function <...m-from-src/share/nvim/runtime/lua/vim/treesitter/dev.lua:368>
```
```
Error detected while processing BufLeave Autocommands for "<buffer=62>":                                                                                                                                                                 
Error executing lua callback: ...m-from-src/share/nvim/runtime/lua/vim/treesitter/dev.lua:441: Invalid buffer id: 61
stack traceback:
        [C]: in function 'nvim_buf_clear_namespace'
        ...m-from-src/share/nvim/runtime/lua/vim/treesitter/dev.lua:441: in function <...m-from-src/share/nvim/runtime/lua/vim/treesitter/dev.lua:440>
```

### Steps to reproduce

- Go to Neovim project
- prepare `init.lua` with
```lua
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'lua',
  callback = function(args)
    vim.treesitter.start(args.buf, 'lua')
    vim.lsp.start({
      name = 'lua-ls',
      cmd = { 'lua-language-server' }, -- ensure that `lua-language-server` is in `$PATH`
      root_dir = vim.fs.dirname(vim.fs.find({ '.git' }, { upward = true })[1]),
    })
  end,
})
```
- run `nvim --clean -u init.lua runtime/lua/vim/treesitter/dev.lua`
- jump to e.g. `nvim_buf_clear_namespace`
- after attaching lua-ls to the buffer run `:lua vim.lsp.buf.signature_help()` there
- jump to the help window (`<C-w>w`)
- type `:InspectTree`
- Notice that the source window has been closed
- try to close the playground window or jump between windows. 

### Expected behavior

Check if buffer is valid before clearing its namespace.

### Neovim version (nvim -v)

2eecb1b85dbb0e02ec40e95d28d3cc4720040f01

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Debian Sid

### Terminal name/version

kitty

### $TERM environment variable

tmux-256color

### Installation

from source

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #25673

Not sure if we should even be opening the inspector in floating windows though.

### CODE REVIEW

File: runtime/lua/vim/treesitter/dev.lua [hunk 1]
```diff
@@ -391,7 +395,7 @@ function M.inspect_tree(opts)
     buffer = buf,
     callback = function()
       if not api.nvim_buf_is_loaded(b) then
-        return true
+        return
```
Comment (gpanders) [inline runtime/lua/vim/treesitter/dev.lua:398]: Why change this? `return true` will cause the autocommand to be removed, which sounds like what we want in this case?

File: runtime/lua/vim/treesitter/dev.lua [hunk 2]
```diff
@@ -438,19 +442,19 @@ function M.inspect_tree(opts)
...
     group = group,
     buffer = buf,
     callback = function()
-      if not api.nvim_buf_is_loaded(b) then
-        return true
+      if api.nvim_buf_is_loaded(b) then
+        api.nvim_buf_clear_namespace(b, pg.ns, 0, -1)
       end
-
-      api.nvim_buf_clear_namespace(b, pg.ns, 0, -1)
```
Comment (gpanders) [inline runtime/lua/vim/treesitter/dev.lua:453]: Similar comment as above. We should keep the `return true` so that the autocommand will delete itself.

File: runtime/lua/vim/treesitter/dev.lua [hunk 3]
```diff
@@ -366,6 +366,10 @@ function M.inspect_tree(opts)
     group = group,
     buffer = b,
     callback = function()
+      if not api.nvim_buf_is_loaded(buf) then
+        return
```
Comment (gpanders) [inline runtime/lua/vim/treesitter/dev.lua:370]:
```suggestion
        return true
```

File: runtime/lua/vim/treesitter/dev.lua (hunk 1 above)
Comment (MariaSolOs) [reply runtime/lua/vim/treesitter/dev.lua:398]: My bad. I had no idea that the return value of an autocommand's callback had that meaning (doesn't seem to be [documented](https://neovim.io/doc/user/lua-guide.html#lua-guide-autocommands)) and I thought they were mistakes. I'll undo the changes.

Comment (gpanders) [reply runtime/lua/vim/treesitter/dev.lua:398]: It's documented in `nvim_create_autocmd`:

```
                 • callback (function|string) optional: Lua function (or
                   Vimscript function name, if string) called when the
                   event(s) is triggered. Lua callback can return true to
                   delete the autocommand, and receives a table argument with
                   these keys:
```

But I do admit it's not the most obvious or discoverable feature.

Comment (gpanders) [reply runtime/lua/vim/treesitter/dev.lua:398]: The `return true` pattern was chosen to mimic `nvim_buf_attach`, which similarly lets callbacks use `return true` to detach.

Comment (MariaSolOs) [reply runtime/lua/vim/treesitter/dev.lua:398]: Oh I cannot read then. Thanks for the tip!

**Review by gpanders — APPROVED** [review]
