### PR TITLE
vim.pack: more control over "load" and "install" behavior

### LINKED ISSUE #34770: Make `vim.pack.add()` more flexible
In #34009 there were several suggestions about making `vim.pack.add()` more flexible. Either by introducing/updating fields in `opts` or plugin specification (`spec`). This issue is meant to discuss the best way to approach them. Here are suggestions:

1. Allow skipping `:packadd` (even `:packadd!`) to only ensure that all plugins are installed in favor of manually loading them later. One way to do it is to allow `opts.load` as function that accepts a single resolved plugin spec and be responsible for loading into current session. Such plugins will still have `active=true` in `vim.pack.get()` output.

2. Allow skipping installation confirmation. This can be done by adding `opts.confirm`. It can be only boolean or maybe also a function to perform confirm (if `load` is allowed to be function).

3. Allow skipping automated installation of not presently installed plugins in favor of doing that manually later. Not sure about the best way to do that.

4. More straightforward plugin freeze/pin/lock. There are several ways to do it:

    - One way to do it is to allow `version = false` to mean "use current state". This works if plugin is already installed, but behavior during install is not (yet) really clear. To be fully specified requires lockfile support to have data about which commit to checkout during install. See [this comment](https://github.com/neovim/neovim/pull/34009#discussion_r2096143432) for details.

    - Add boolean `spec.freeze` (or `spec.pin`) that will freeze/pin plugin from updates while still using `spec.version` during install.

    - Do nothing and recommend specifying commit hash directly as `version`.

My suggestions:

1. Allow callable `opts.load` with default "`:packadd` + execute 'after/plugin/' files".
2. Allow `opts.confirm` that can be both boolean and callable (should block and return whether permission was granted).
3. I like the current approach of "block and install" because it allows the code after it to assume that plugin is installed.
4. Do nothing and suggest specifying commit hash. Can be seen in confirmation buffer or in future lockfile.

### LINKED ISSUE #35192: vim.pack should use `packadd!` by default (or at least if it is executed on startup)
### Problem

When users put `vim.pack.add( 'some-plugin' )` in their `init.lua`, the `plugin/` directory of that plugin will be loaded right away, even though `init.lua` may hasn't finished loading. This makes it different from the initializing process documented in `:h startup`, and also make `--noplugin` not work.

And it seems to me Vim already recommends using `:packadd!` in config files. Here is the document of `:h packadd`
```help
			When the optional "!" is given, no plugin/ files or
			ftdetect/ scripts are loaded, only the matching
			directories are added to 'runtimepath'.  This is
			useful in your |init.vim|.
```
The help doc of `pack-add` says
```help
You can also load an optional plugin at startup, by putting this command in
your |config|: >
    :packadd! foodebug
```
The help doc of `termdebug-starting` says:
```help
When loading the plugin from the |vimrc| file, add the "!" attribute: >vim
	packadd! termdebug
```

Some other problems of current behavior (as mentioned in later comments):
- Cannot use plugins that require users to call `setup()` before `plugin/` script is loaded
- Can make each `plugin/` script sourced twice

### Expected behavior

`vim.pack.add` should has option `load` set to `false` (at least if it is executed during startup time)

### PR DESCRIPTION
**Pull request by echasnovski**
close https://github.com/neovim/neovim/issues/35192
close https://github.com/neovim/neovim/issues/34770

This PR fixes #35192 and addresses most (if not all) ideas of #34770:
- Make default `opts.load` be `false` during startup to avoid sourcing 'plugin/' twice and make it work with `--noplugin`. After startup the default value is still `true` (to work with lazy loading).
- Allow `opts.load` to be a function to have full control over how plugin is loaded.
- Add `opts.confirm` to allow skipping install confirmation. Although requiring confirmation is good default design, it might be not necessary for most users. Since there should have been some action that lead to the plugin installation (usually adjusting `vim.pack.add()` in the 'init.lua').

---

My opinion is that the non-addressed ideas of #34770 might be a bit too much for `vim.pack.add` and hence this PR should also resolve it.

> Allow skipping automated installation of not presently installed plugins in favor of doing that manually later.

I like the current "block and install" because it allows the code after it to assume that plugin is installed and loaded.

> More straightforward plugin freeze/pin/lock.

The current suggestion of specifying commit hash or tag directly as `version` works as a freeze. Maybe the only downside would be that full changelog from target branch won't be shown in confirmation buffer after each update. To counter that, there are suggested newer version tags that can be used to track new releases. Plus #34919 might introduce an alternative to freezing via manual targeted "skip updating this plugin".

> Introduce something like `opts.convert_spec` ... a function that can be used to auto-transform plugin spec.

This can be achieved with a `vim.pack.add()` wrapper.

> Add `PackLoad[Pre]` events for easier config hooks

This can be achieved with function `opts.load`. Having a separate event would allow plugins to act on when other plugins are loaded, but I currently can not think of a use case where this would be the most appropriate solution.

### CODE REVIEW

**Comment by besserwisser** [comment]
Hey, just wanted to mention that this commit might break some configurations. At least for me it did. I had to add `{ load = true }` to all my `vim.pack.add()` calls. I have organised my plugins in `nvim/plugin/[plugin-name]` files, e.g.: 

```lua
-- copilot.lua
vim.pack.add({
	"https://github.com/nvim-lua/plenary.nvim",
	"https://github.com/zbirenbaum/copilot.lua",
	"https://github.com/zbirenbaum/copilot-cmp",
	"https://github.com/CopilotC-Nvim/CopilotChat.nvim",
}, { load = true })

require("copilot").setup({
	suggestion = {
		enabled = false,
	},
	panel = {
		enabled = false,
	},
})

require("copilot_cmp").setup()

require("CopilotChat").setup({
	-- Uses visual selection or falls back to buffer
	selection = function(source)
		local select = require("CopilotChat.select")
		return select.visual(source) or select.buffer(source)
	end,
})

vim.keymap.set({ "n", "v" }, "<leader>aa", "<cmd>CopilotChatOpen<cr>", { desc = "CopilotChatOpen" })
vim.keymap.set({ "n", "v" }, "<leader>ap", "<cmd>CopilotChatPrompts<cr>", { desc = "CopilotChatPrompts" })
```

**Comment by brianhuster** [comment]
0Huh, I can't see why it would break your config. What behavior change exactly?

Oh, I see, that's because you put them in `plugin/` directory. But AFAIK, neither Vim nor Nvim have ever recommended to put user config in `plugin` directory.

**Comment by echasnovski** [comment]
> I have organised my plugins in `nvim/plugin/[plugin-name]` files, e.g.:

Do you mean '~/.config/nvim/plugin/[plugin-name].lua'?

And what exactly broke? I assume that if adding `{ load = true }` fixed it, then 'plugin/' files of installed plugins are not loaded. This seems to be a limitation of loading process (described in `:h load-plugins`) itself: when loading 'plugin/' directories it seems to be using a "fixed" version of 'runtimepath' that was active at the start of loading. I.e. if those 'plugin/' directories modify 'runtimepath' itself, those new entries *will not* get their 'plugin/' directories sourced (during startup).

Here is an example:

- In file '~/.config/nvim/pack/bundle/opt/other-plug/plugin/other.lua' put `_G.other_loaded = true`.
- In file '~/.config/nvim/plugin/myplug.lua' put `vim.cmd('packadd! other-plugin')`.

Now after startup the `_G.other_loaded` is `nil`. Although the 'runtimepath' includes `~/.config/nvim/pack/bundle/opt/other-plug` *after* the currently traversed config directory. If command is changed to `packadd` (i.e. force 'plugin/' source), then it is `true`. I'll create an issue to discuss and document if this is feasible to change.

But at its worst, I guess it can be considered as a fairly low-cost known limitation to have to force `load = true` in case `vim.pack.add()` is called within 'plugin/' directories.

**Comment by besserwisser** [comment]
@echasnovski , yes I mean for example ''~/.config/nvim/plugin/copilot.lua''

In my example above `Copilot` command doesn't exist (e.g. `:Copilot status`) with the error message `E464: Ambiguous use of user-defined command`. When changing it to `load = true`, it works. It is not just this file. Others broke as well.

I agree that it is fine to add `load = true`. I just wanted to have it documented here, in case someone else is looking for it. Because a update to latest nightly breaks it, some might be surprised (but it is a nightly, so whatever). 

The alternative would be to put all the vim.pack.add into the `init.lua` and only the configuration into `~/.config/nvim/plugin/copilot.lua`, if I understand correctly?

**Comment by echasnovski** [comment]
> I just wanted to have it documented here, in case someone else is looking for it. Because a update to latest nightly breaks it, some might be surprised (but it is a nightly, so whatever).

Yes, that was helpful. Thanks!

> The alternative would be to put all the vim.pack.add into the `init.lua` and only the configuration into `~/.config/nvim/plugin/copilot.lua`, if I understand correctly?

Correct, that would work without `{ load = true }`.

**Comment by besserwisser** [comment]
Thank you for answering my questions and for your work

**Comment by BirdeeHub** [comment]
Summary as far as my comments on the previous PR/issues were concerned, `load = function() end` to disable `packadd!` entirely if desired. Good enough. Thank you! I have docs to update now!

**Comment by justinmk** [comment]
@echasnovski in order to opt-in to "on-demand" `:packadd` behavior for specific plugins, should we also let `load` be a field on the ~~opts~~ spec parameter? 

```lua
vim.pack.add({
  { src = 'https://github.com/mbbill/undotree', load = function() end},
})
```

It's pretty awkward for the user to have to do something like this:

```lua
vim.pack.add({
  { src = 'https://github.com/mbbill/undotree' },
  ...
}, {
 load = function(o)
   if o.spec ~= 'undotree' then
     vim.cmd.packadd(o.spec.name)
   end
 end,
})
```

**Comment by echasnovski** [comment]
> @echasnovski in order to opt-in to "on-demand" `:packadd` behavior for specific plugins, should we also let `load` be a field on the `opts` parameter?

Do you mean a part of plugin specification? I'd think it is a bit too much and not quite needed. It should be pretty normal to have several `vim.pack.add()` calls. So for the case of lazy loading 'mbbill/undotree' there are at least two suggestions:

- Just use `vim.pack.add` whenever you plan to have a manual `vim.cmd.packadd`. Yes, currently this means it will not be installed on clean machine until it is meant to be first loaded (which I'd consider at least a not bad behavior). And yes, currently it means that it will not be updated when `vim.pack.update()` is called without arguments (this will change after there is persistent spec storage, i.e. some kind of lockfile).
- Have all "eagerrly load" plugins in one `vim.pack.add()` and register all "lazy loaded" plugins in a second call. So something like this:

    ```lua
    -- Eagerly load
    vim.pack.add({
      { src = 'https://github.com/neovim/nvim-lspconfig' },
      -- ...
    })

    -- Lazy load
    vim.pack.add({
      { src = 'https://github.com/mbbill/undotree' },
      -- ...
    }, { load = function() end })
    ```

I'd personally suggest using the first variant, but the second one is also fine (as it provides some structure to the config, at least).

**Comment by justinmk** [comment]
> Do you mean a part of plugin specification?

yes

> currently it means that it will not be updated when `vim.pack.update()`

er... 

> Have all "eagerrly load" plugins in one `vim.pack.add()` and register all "lazy loaded" plugins in a second call.

yeah, that's fine. but if it doesn't update when `update()` is called, it's rather pointless.

**Comment by echasnovski** [comment]
> > currently it means that it will not be updated when `vim.pack.update()`
> 
> er...
> 
> > Have all "eagerrly load" plugins in one `vim.pack.add()` and register all "lazy loaded" plugins in a second call.
> 
> yeah, that's fine. but if it doesn't update when `update()` is called, it's rather pointless.

Here is the full quote:

> ... currently it means that it will not be updated when `vim.pack.update()` is called **without arguments (this will change after there is persistent spec storage, i.e. some kind of lockfile)**.

It still can be updated if it is actually loaded later,. Or with `vim.pack.update({ 'undotree' })` if it is tracking default branch (which is usually the case). Or with `vim.pack.update(vim.tbl_map(function(x) return x.spec.name end, vim.pack.get()))`.

I do have plans to start working on local plugins and lockfile support next week. Both will require discussions, though.

**Comment by mikejmcguirk** [comment]
> Yes, currently this means it will not be installed on clean machine until it is meant to be first loaded (which I'd consider at least a not bad behavior)

For me, this is a blocker to running deferred plugin loading through vim.pack.add(). If I have a plugin I want to load on InsertEnter, I don't want it downloading on a clean install when I enter insert mode. 

My current solution is to save the names/paths to a table in my load function, then manually packadd/source later.   This works, but it's not the most ergonomic and there's the (admittedly small) cost of setting up the table.

Something related to this in a broader sense is - One of the reasons I switched to vim.pack was to be able to centralize spec in one file/table. Spreading out spec into multiple files would work against what to me is a core feature.

My personal ideal solution would be to be able to call vim.pack.add([name: string], { load = [boolean}). The add function would be able to recognize if the spec is already present and perform the default load behavior (returning an error otherwise). But I can also see why advertising this as intended usage creates footguns by being vulnerable to typos or mis-understandings of how the load process works.

**Comment by BirdeeHub** [comment]
Hey! Question: can we make it so that the spec passed to the load function can have extra values placed into it?

If I put extra values in my spec, they are not being provided to the load function as it is currently and that in my opinion would further increase flexibility for very little cost?

Is there a reason why this cant be done? Or other concerns? It looks like this could be done just by editing the normalization function?

This would solve most requests for more values in the spec beyond URL schema, build steps, or luarocks stuff (which is taken care of before the load function is called) but everything else people seem to be asking for is load related.

for example, it would be nice to be able to include our own little flag for our load function to identify what is loaded when. Simplest example would be something like this

```lua
  vim.pack.add({
      "https://github.com/BirdeeHub/lze",
      { src = "https://github.com/Wansmer/treesj", opt = true },
  }, {
    load = function(p)
      print(vim.inspect(p)) -- print for demonstration purposes to show what we are recieving, output shown below
      if not p.spec.opt then -- currently this opt flag would not be included in spec
        vim.cmd.packadd(p.spec.name)
      end
    end,
    confirm = true,
  })
```
  the above print will currently result in the following, with the opt not included (also I edited the path output and added a comment)
```lua
{
  path = "$XDG_DATA_HOME/nvim/site/pack/core/opt/lze",
  spec = {
    name = "lze",
    src = "https://github.com/BirdeeHub/lze"
  }
}
{
  path = "$XDG_DATA_HOME/nvim/site/pack/core/opt/treesj",
  spec = {
    name = "treesj",
    src = "https://github.com/Wansmer/treesj"
    -- opt = true -- isn't here?
  }
}
```
  
  But obviously you could do a lot more than just that. You could make it so that the load function provides the spec straight to the lze.load function for example and use the full spec in the same list you provide your download specs in, or any number of other things to that effect.
  
Is this something that you would accept a PR for?
  
Currently I have been managing my lazy loading with lze, which you could use like this

```lua  
  vim.pack.add({
    "https://github.com/BirdeeHub/lze", -- https://github.com/nvim-neorocks/lz.n also works for this purpose
    "https://github.com/Wansmer/treesj",
    { src = "https://github.com/nvim-telescope/telescope.nvim" },
    { src = "https://github.com/NTBBloodBatch/sweetie.nvim", name = "sweetie" }
}, {
  -- prevent packadd! or packadd like this to allow on_require handler to load plugin spec (if you desire to use that handler, otherwise false is fine and you can remove the packadd for lze below)
  load = function() end,
  -- choose your preference for install confirmation
  confirm = true,
})
vim.cmd.packadd("lze")

require("lze").load {
    {
        "telescope.nvim",
        cmd = "Telescope",
        on_require = { "telescope" },
    },
    {
        "sweetie", -- note the name change above
        colorscheme = "sweetie",
    },
    {
        "treesj",
        cmd = { "TSJToggle" },
        keys = { { "<leader>Tt", ":TSJToggle<CR>", mode = { "n" }, desc = "treesj split/join" }, },
        after = function(spec)
            require("treesj").setup({})
        end,
    }
}
```

but with just that 1 change, you would be able to move all of the lze spec into the spec for the vim.pack.add specs. and just pass the specs straight to lze.load in the load function for vim.pack.add

```lua
vim.pack.add({ "https://github.com/BirdeeHub/lze" }, { confirm = false --[[or true idk]] })
vim.pack.add({
  {
    src = "https://github.com/nvim-telescope/telescope.nvim",
    cmd = "Telescope",
    on_require = { "telescope" },
  },
  {
    src = "https://github.com/Wansmer/treesj"
    cmd = { "TSJToggle" },
    keys = { { "<leader>Tt", ":TSJToggle<CR>", mode = { "n" }, desc = "treesj split/join" }, },
    after = function(spec)
      require('treesj').setup({})
    end,
  },
  {
    src = "https://github.com/NTBBloodBatch/sweetie.nvim",
    colorscheme = "sweetie",
  }
}, {
  load = function(p)
    require('lze').load(p.spec)
  end,
  -- choose your preference for install confirmation
  confirm = true,
})
```

TL;DR

If all values in the spec were passed on to the load function, it would solve people's issues with managing lazy loading while using vim.pack.add for very little maintenance effort.

It would not solve build steps, but I think that was to be handled via some sort of rockspec mechanism? But that would be a separate problem, not hindered by this change.

I can work on and submit a PR for that, but I would like to know if that would be accepted first

File: runtime/lua/vim/pack.lua [hunk 1]
```diff
@@ -651,6 +654,11 @@ local function pack_add(plug, load)
   n_active_plugins = n_active_plugins + 1
   active_plugins[plug.path] = { plug = plug, id = n_active_plugins }
 
+  if vim.is_callable(load) then
+    load({ spec = vim.deepcopy(plug.spec), path = plug.path })
```
Comment (BirdeeHub) [inline runtime/lua/vim/pack.lua:658]: this doesnt match the docs

`load({ spec = vim.deepcopy(plug.spec), path = plug.path })`

but the docs say

`load(vim.deepcopy(plug.spec), plug.path)`

Comment (BirdeeHub) [reply runtime/lua/vim/pack.lua:658]: Should the docs change, or should the implementation?

**Comment by justinmk** [comment]
> with just that 1 change, you would be able to move all of the lze spec into the spec for the vim.pack.add specs.

If we can make small changes that enable big extensibility opportunities that sounds attractive. I have not carefully studied the examples given here though. `on_require` seems a bit strange, the semantics of what it means to "require a plugin" are not well documented.

**Comment by BirdeeHub** [comment]
well, that on_require thing is from lze. You can specify a top level module and if requiring any submodule of it fails, it runs the lze spec. You can check out the source for it [here](https://github.com/BirdeeHub/lze/blob/master/lua/lze/h/on_require.lua) if you want but it isnt particularly relevant to the change I was suggesting.

Technically the plugin lze doesnt relate to this change at all, theres other things you could use the change for as well. And it would also help with [lz.n](https://github.com/nvim-neorocks/lz.n) as well, which doesn't have a built in "on_require" handler but is similar

The small change is just, when you put extra values in the spec in add, the load function can recieve all the things you put in there rather than just the ones strictly conforming to the type.

The change would be this, not 100% sure I did the new type annotation correctly though

https://github.com/neovim/neovim/compare/master...BirdeeHub:neovim:pack_add_spec_passthru

**Comment by justinmk** [comment]
> The small change is just, when you put extra values in the spec in add, the load function can recieve all the things you put in there rather than just the ones strictly conforming to the type.

That idea is typically very useful, similar to [what we did](https://github.com/neovim/neovim/pull/34550) with `cmd(..., config)`.

**Comment by BirdeeHub** [comment]
> That idea is typically very useful, similar to [what we did](https://github.com/neovim/neovim/pull/34550) with `cmd(..., config)`.

I agree for a number of reasons, however echasnovski would prefer if we put all extra fields into a new `.data` field rather than just accepting extras because he feels it is clearer.

I feel that is extra indirection for little gain and may have more drawbacks surrounding if the data field is present at all or not due to the extra indexing and needing to check or add it in normalization unnecessarily.

We need a deciding vote on the PR as to if it stays as the PR is now, accepting extra values, or if it is changed and only a single new field `.data` of type table is added.

If extra values is the choice, it is ready to go though.

**Comment by justinmk** [comment]
> put all extra fields into a new `.data` field rather than just accepting extras because he feels it is clearer.

That is pretty much equivalent. If we don't do it that way, then any time we add a new Spec field in the future, we risk clobbering existing extensions in the wild...

**Comment by BirdeeHub** [comment]
> > put all extra fields into a new `.data` field rather than just accepting extras because he feels it is clearer.
> 
> That is pretty much equivalent. If we don't do it that way, then any time we add a new Spec field in the future, we risk clobbering existing extensions in the wild...

It would be incorrect to optimize for the thing that happens only hypothetically in the future and will only happen a few times, when there is something that EVERY user will hit.

Every user will forget to check if data exists or not at least one time, and it adds a significant amount of verbosity to have to make the data table in the specs and check for its existence in load.

VERY few would ever hit such a collision you mentioned, and eventually there will be no more fields to add. And no one will ever hit it again.

I feel that reasoning is optimizing for the wrong thing. It adds like 10 lines or so per pack.add call, and a chance for mistake each time. In exchange for making something easier that would only happen very occasionally and then eventually stop altogether

The more I think about it the more I become convinced that `.data` is not only annoying but actually just bad.

**Comment by justinmk** [comment]
> the thing that happens only hypothetically in the future and will only happen a few times,

It's not hypothetical, it's something that there is copious empirical (historical) evidence for, and has very wide "blast radius" (affects many users) which only increases as we gain users.

> Every user will forget to check if data exists or not at least one time

"Every" user that is extending vim.pack, which is the uncommon case.

> It adds like 10 lines or so per pack.add call,

? Show an example of the 10 lines (not entire pages, just a very concise example), and the difference vs with/without `.data`.

**Comment by BirdeeHub** [comment]
> > It adds like 10 lines or so per pack.add call,
> 
> ? Show an example of the 10 lines (not entire pages, just a very concise example), and the difference vs with/without `.data`.

https://github.com/neovim/neovim/pull/35360#issuecomment-3194267381

This one is 8 lines and it's only 3 specs. If you have 4 specs in the load call, it's 10 extra lines.

**Comment by justinmk** [comment]
Oh, you are talking about the `data = { ... \n}` lines. That is just not an important thing. If you have 1 property you can do `data = { foo = bar }`. If you have >1 property then the enclosing `{ ... }` is a vanishing percentage of the total lines.
