### PR TITLE
fix(lua): use empty_dict when no opts given in vim.ui.input

### LINKED ISSUE #18143: `vim.ui.input({}, ...)` and `vim.ui.input(nil, ...)` throw an error
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

No, Vim doesn't have `input({opts})` interface

### Operating system/version

Xubuntu 20.04

### Terminal name/version

xfce4-terminal 0.8.9.1 (Xfce 4.14)

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

1. `nvim --clean`
2. `:lua vim.ui.input({}, function() end)` or `:lua vim.ui.input(nil, function() end)`.

### Expected behavior

Same as `:call input({})`.

### Actual behavior

Error `E5108: Error executing lua Vim:E730: using List as a String`.

The reason seems to be that [`vim.ui.input()` uses `{}` in both cases](https://github.com/neovim/neovim/blob/6e6f5a783333d1bf9d6c719c896e72ac82e1ae54/runtime/lua/vim/ui.lua#L90) as argument for `vim.fn.input()` (instead of `vim.empty_dict()`).

Happy to do PR to fix this.

### PR DESCRIPTION
**Pull request by tzx**
I'm pretty sure `{}` makes an empty list which is not you want to put as input to `vim.fn.input`. Therefore, this change makes it so that when opts are `nil` or `{}`, an empty_dict is passed as the argument for `vim.fn.input`. 

I also removed the doc about `Defaults to Input:`, because by default it's `""` for `input()`.

Edit: looks like an issue was already made for this. Resolves #18143.

### CODE REVIEW

File: runtime/lua/vim/ui.lua [hunk 1]
```diff
@@ -87,7 +87,9 @@ function M.input(opts, on_confirm)
     on_confirm = { on_confirm, 'function', false },
   })
 
-  opts = opts or {}
+  if not opts or vim.tbl_isempty(opts) then
+    opts = vim.empty_dict()
+  end
```
Comment (justinmk) [inline runtime/lua/vim/ui.lua:92]: Ternaries can help readability because they avoid nesting and helps the reader see that an assignment is being done to the current scope. 
```suggestion
  opts = (opts and not vim.tbl_isempty(opts)) and opts or vim.empty_dict()
```

Wonder why tbl_isempty doesn't accept nil ...

**Comment by justinmk** [comment]
Nice, thanks! Should be easy enough to add a 1-line test to test/functional/lua/ui_spec.lua ?

File: runtime/lua/vim/ui.lua (hunk 1 above)
Comment (tzx) [reply runtime/lua/vim/ui.lua]: oh nice! I was trying to do this but I didn't have the `and opts`

**Comment by tzx** [comment]
> Nice, thanks! Should be easy enough to add a 1-line test to test/functional/lua/ui_spec.lua ?

How would one do this? The other test just unit tests by replacing `vim.fn.input` so it doesn't wait for input. If I test by calling `vim.ui.input`, it would call `vim.fn.input`, which is what I want (otherwise I can't test the error from before) but it has to wait for user input.

File: test/functional/lua/ui_spec.lua [hunk 2]
```diff
@@ -67,5 +69,15 @@ describe('vim.ui', function()
       eq('Inputted text', result[1])
       eq('Input: ', result[2])
     end)
+
+    it('does not cause error on nil opt', function()
+      feed(':lua vim.ui.input(nil, function() end)<cr>')
+      eq('', eval('v:errmsg'))
```
Comment (justinmk) [inline test/functional/lua/ui_spec.lua:75]: This could be a false negative so let's go a bit further and actually feed input into the prompt, then check the result.

Like this (not tested):

```suggestion
      feed(':lua test_result=vim.ui.input(nil, function() end)<cr>')
      feed('x')
      eq('x', exec_lua('return test_result'))
```

Comment (tzx) [reply test/functional/lua/ui_spec.lua]: `vim.ui.input` doesn't return anything, so I made the callback set the variable.
