### PR TITLE
fix(lsp): handle multiline signature help labels

### LINKED ISSUE #30428: LSP: current parameter in signature help not highlighted if the label spans multiple lines
### Problem

calling signature help in a function whos signature is on more than 1 line, the current parameter is not highlighted. im using zig/zls as an example, im not sure what other servers support signature help
image
image

### Steps to reproduce

```sh
cat >test.zig <<EOF
pub fn main() void {
    foo({}, );
    bar({}, );
}
fn foo(_: void, _: void) void {}
fn bar(
    _: void,
    _: void,
) void {}
EOF
cat >repro.vim <<EOF
autocmd FileType zig lua vim.lsp.start({cmd = {'zls'}})
EOF
nvim --clean -u repro.vim test.zig
```
move to the call sites and run `:lua vim.lsp.buf.signature_help()`

### Expected behavior

i expect the parameters to be highlighted in all cases

### Neovim version (nvim -v)

v0.11.0-dev-794+gf01c764cc

### Vim (not Nvim) behaves the same?

n/a (?)

### Operating system/version

alpine linux kernel 6.11.0

### Terminal name/version

ghostty

### $TERM environment variable

xterm-ghostty

### Installation

built from source

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #30428

For reference, this is how it looks on `master`:
image

Versus with this PR:
image

### CODE REVIEW

**Comment by MariaSolOs** [comment]
Hmm, I guess I can use `highlight.range` here...

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -768,34 +768,42 @@ function M.convert_input_to_markdown_lines(input, contents)
   return contents
 end
 
+---@param offset integer
+---@param contents string[]
+---@return Range2
+local function get_line_and_col_from_offset(offset, contents)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/util.lua:774]:
```suggestion
local function get_pos_from_offset(offset, contents)
```

p.s.: another case for https://github.com/neovim/neovim/issues/25509 , probably

File: runtime/lua/vim/lsp/util.lua [hunk 2]
```diff
@@ -843,36 +853,47 @@ function M.convert_signature_help_to_markdown_lines(signature_help, ft, triggers
         documentation?: string | MarkupContent;
       }
       --]=]
```
Comment (justinmk) [inline runtime/lua/vim/lsp/util.lua:855]: would the above comment benefit from a "before => after" example to show what's going on here?

**Review by justinmk — APPROVED** [review]

**Comment by mfussenegger** [comment]
Would it be possible to add a test case for this?

File: runtime/lua/vim/lsp/util.lua (hunk 2 above)
Comment (MariaSolOs) [reply runtime/lua/vim/lsp/util.lua:870]: I'm not sure I understand. What exactly would you like me to clarify further?

File: runtime/lua/vim/lsp/util.lua [hunk 3]
```diff
@@ -781,34 +781,44 @@ function M.convert_input_to_markdown_lines(input, contents)
...
+end
+
 --- Converts `textDocument/signatureHelp` response to markdown lines.
 ---
 ---@param signature_help lsp.SignatureHelp Response of `textDocument/SignatureHelp`
 ---@param ft string|nil filetype that will be use as the `lang` for the label markdown code block
 ---@param triggers table|nil list of trigger characters from the lsp server. used to better determine parameter offsets
 ---@return string[]|nil table list of lines of converted markdown.
----@return number[]|nil table of active hl
+---@return Range4|nil table of active hl
```
Comment (wookayin) [inline runtime/lua/vim/lsp/util.lua:806]: is this correct? `active_hl` and `get_pos_from_offset` appear to have two numbers (actually not a Range2), not Range4.

Comment (MariaSolOs) [reply runtime/lua/vim/lsp/util.lua:806]: It is correct. Notice how `active_hl` is extended twice with 2 `Range2`s here:
https://github.com/neovim/neovim/blob/6e01e0f7b60f5afe802c6feb52b7f7d5fb15cde7/runtime/lua/vim/lsp/util.lua#L908-L912

Comment (wookayin) [reply runtime/lua/vim/lsp/util.lua:806]: I see, now I get how it contains four elements. It looked like `active_hl` is `Range4[]` at a glance. Though I believe making it explicit (e.g. `row_start, col_start`, `row_end, `col_end`) would make the code a bit easier to read.

File: runtime/lua/vim/lsp/util.lua [hunk 4]
```diff
@@ -781,34 +781,44 @@ function M.convert_input_to_markdown_lines(input, contents)
   return contents
 end
 
+--- Returns the line/column-based position in `contents` at the given offset.
+---
+---@param offset integer
+---@param contents string[]
+---@return Range2
```
Comment (wookayin) [inline runtime/lua/vim/lsp/util.lua:788]: Coming from https://github.com/neovim/neovim/pull/30460#discussion_r1798438892, this seems to be fixed:

```suggestion
---@return Range2
+++@return {[1]: integer, [2]: integer} row, col
```

Because Range2 means (start row, start end), not a position.

note: since this is just a local helper function, we can also simply return two integers rather than a table.

File: runtime/lua/vim/lsp/util.lua (hunk 3 above)
Comment (MariaSolOs) [reply runtime/lua/vim/lsp/util.lua:806]: I agree that it would make the code easier to read when not inside an editor, but what you described is exactly the definition of `Range4`:
```lua
---@class Range4
---@inlinedoc
---@field [1] integer start row
---@field [2] integer start column
---@field [3] integer end row
---@field [4] integer end column
```

I prefer to use the existing type here, and either way we do want to consolidate the many position/range abstractions we have (see https://github.com/neovim/neovim/issues/25509).

File: runtime/lua/vim/lsp/util.lua (hunk 4 above)
Comment (MariaSolOs) [reply runtime/lua/vim/lsp/util.lua:788]: I'll keep the table so that I can still just use `list_extend` without introducing extra variables at the call sites.

File: runtime/lua/vim/lsp/util.lua (hunk 3 above)
Comment (wookayin) [reply runtime/lua/vim/lsp/util.lua:806]: Yes, I agree. Just wanted to be clear, I meant using local variables while constructing a table (rather than using list_extend which is not type friendly).

Comment (MariaSolOs) [reply runtime/lua/vim/lsp/util.lua:806]: I don't get any type errors with the current approach...

File: runtime/lua/vim/lsp/handlers.lua [hunk 5]
```diff
@@ -462,6 +462,8 @@ M[ms.textDocument_typeDefinition] = location_handler
 --- @see # https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_implementation
 M[ms.textDocument_implementation] = location_handler
 
+local sig_help_ns = api.nvim_create_namespace('lsp_signature_help')
```
Comment (justinmk) [inline runtime/lua/vim/lsp/handlers.lua:465]: nit/non-blocker: do we usually prefix our namespaces with `nvim_` ? 

also wondering if we should use dot "." as the separator for namesapces, e.g. `nvim.lsp.foo`.

Comment (MariaSolOs) [reply runtime/lua/vim/lsp/handlers.lua:465]: I don't think we have a convention regarding namespace names. E.g. we use [`'vim/snippet'`](https://github.com/neovim/neovim/blob/36890824c7edb7bc5458062c14efbfa0b1d280b5/runtime/lua/vim/snippet.lua#L3) in `vim.snippet`, [`'ts.dev'`](https://github.com/neovim/neovim/blob/36890824c7edb7bc5458062c14efbfa0b1d280b5/runtime/lua/vim/treesitter/dev.lua#L138) in the TS inspector, etc.

We do seem to prefix these with `vim_` in the LSP namespaces though, so I'll stick to that.

**Comment by MariaSolOs** [comment]
@justinmk @mfussenegger I think this is ready to go :)

File: runtime/lua/vim/lsp/util.lua [hunk 6]
```diff
@@ -781,34 +781,44 @@ function M.convert_input_to_markdown_lines(input, contents)
...
-  if not signature_help.signatures then
-    return
-  end
   --The active signature. If omitted or the value lies outside the range of
   --`signatures` the value defaults to zero or is ignored if `signatures.length == 0`.
   --Whenever possible implementors should make an active decision about
   --the active signature and shouldn't rely on a default value.
   local contents = {}
-  local active_hl
+  local active_offset ---@type [number, number]|nil
```
Comment (wookayin) [inline runtime/lua/vim/lsp/util.lua:814]: nit:
```suggestion
  local active_offset ---@type [integer, integer]|nil
```

File: test/functional/plugin/lsp_spec.lua [hunk 7]
```diff
@@ -3519,6 +3519,27 @@ describe('LSP', function()
       local expected = { '```cs', 'TestEntity.TestEntity()', '```', 'some doc' }
       eq(expected, result)
     end)
+
+    it('higlights active parameters in multiline signature labels', function()
```
Comment (wookayin) [inline test/functional/plugin/lsp_spec.lua:3523]:
```suggestion
    it('highlights active parameters in multiline signature labels', function()
```

File: test/functional/plugin/lsp_spec.lua [hunk 8]
```diff
@@ -3519,6 +3519,27 @@ describe('LSP', function()
...
+              parameters = {
+                { label = '_: void' },
+                { label = '_: void' },
+              },
+            },
+          },
+        }
+        return vim.lsp.util.convert_signature_help_to_markdown_lines(signature_help, 'zig', { '(' })
+      end)
+      local expected = { 3, 4, 3, 11 }
```
Comment (wookayin) [inline test/functional/plugin/lsp_spec.lua:3540]: If I understood correctly, this refers to the second parameter (`activeParameter = 1` with zero-based index) => `_: void`; in line 3 (Row 2, with zero-based index). I was confused why it's not `{ 2, 4, 2, 11 }` -- Could you please clarify which index is exactly being used and document it if it would make it easier to understand?

It looks like we're using 1-based index here for line (ro~) or 0-based index for column (with end-exclusive), but `vim.highlight.range` seems to accept 0-based index for line/col (Range4 also implies 0-based row/col).

Comment (wookayin) [reply test/functional/plugin/lsp_spec.lua:3540]: Hmm, maybe I got it; looks like it's because of the additional line introduced as the code is wrapped with a codeblock: "```...```". So it *is* 0-index.

File: runtime/lua/vim/lsp/util.lua (hunk 3 above)
Comment (MariaSolOs) [reply runtime/lua/vim/lsp/util.lua:806]: @wookayin Yep! I left a short comment here:
https://github.com/neovim/neovim/blob/21911f2cc556e6b05ad58a92cc7d4539e6a939ae/runtime/lua/vim/lsp/util.lua#L900-L906

But I'll make sure to clarify this in the test too.

File: test/functional/plugin/lsp_spec.lua (hunk 8 above)
Comment (MariaSolOs) [reply test/functional/plugin/lsp_spec.lua:3543]: @wookayin exactly! I actually left a small comment about that here:
https://github.com/neovim/neovim/blob/21911f2cc556e6b05ad58a92cc7d4539e6a939ae/runtime/lua/vim/lsp/util.lua#L900-L906

But I'll make sure to clarify this in the test too.

Comment (MariaSolOs) [reply test/functional/plugin/lsp_spec.lua:3543]: And thank you for the review @wookayin <3!
