### PR TITLE
Fix #9687.

### LINKED ISSUE #9687: Segfault in tui_tk_ti_getstr when -1 is passed as value
- `nvim --version`: v0.3.4
- Vim (version: ) behaves differently?
I don't know, most probably yes, as it does not have such a function.
- Operating system/version: Guix System, 3499638
- Terminal name/version: ssh login, through Ubuntu host
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
Segmentation fault on startup
### Expected behaviour
Actually starts

I debugged this segfault, and it came from a tigetstr call, parameter was key_dc, return value was
(char*)-1, which is a valid return value as per the documentation of that method, and directly passed on to the tui_tk_ti_getstr hook function as value. (This is located in src/nvim/tui/tui.c)

I tend to believe this is not a problem in ncurses, as the return value is acceptable, according to the documentation, and I also believe that it is not a libtermkey problem, as it should leave the option open to the hook to handle the case when -1 is passed.

According to a short talk on the IRC channel it would be reasonable to handle this analogously to the case when NULL is returned. I will file a pull request in this spirit.

### PR DESCRIPTION
**Pull request by Boskovits**
Fixes #9687

### CODE REVIEW

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -2000,7 +2000,7 @@ static const char *tui_tk_ti_getstr(const char *name, const char *value,
   } else if (strequal(name, "key_dc")) {
     DLOG("libtermkey:kdch1=%s", value);
     // Vim: "If <BS> and <DEL> are now the same, redefine <DEL>."
-    if (value != NULL && strequal(stty_erase, value)) {
+    if (value != NULL && value != (char *)-1 && strequal(stty_erase, value)) {
```
Comment (justinmk) [inline src/nvim/tui/tui.c]: This looks weird. Is `-1` really passed as a pointer? Or should it be `*value != (char)-1` ?

Comment (Boskovits) [reply src/nvim/tui/tui.c]: Hello!

Yes, the -1 is really passed as a pointer. It is documented in man 3 tigetstr.
Here is a link:
https://linux.die.net/man/3/tigetstr

the relevant part is:
The tigetstr routine returns the value (char *)-1 if capname is not a string capability, or 0 if it is canceled or absent from the terminal description. 

Also, it seems that in this situation NULL should be returned, but in practice -1 is returned somehow.

Most probably there is another problem in curses, but handling this, otherwise acceptable return value would make sense.

If not this way, then by signaling an error.
