### PR TITLE
fix(vim.fs): dirname() returns "." on mingw/msys2

### LINKED ISSUE #30212: vim.fs.dirname() returns "." on MSYS2
### Problem

```
=vim.fs.dirname(vim.fn.stdpath('config'))
.
```

### Steps to reproduce

/

### Expected behavior

```
C:\User\XXX\AppData\Local
```

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

windows terminal

### $TERM environment variable

xterm-256color

### Installation

Msys2

### PR DESCRIPTION
**Pull request by justinmk**
Problem:
`vim.fs.dirname([[C:\User\XXX\AppData\Local]])` returns "." on mingw/msys2.

Solution:
- Check for "mingw" when deciding `iswin`.
- Use `has("win32")` where possible, it works in "fast" contexts since  b02eeb6a7281df0561a021d7ae595c84be9a01be.

fix #30212

### CODE REVIEW

File: test/testutil.lua [hunk 1]
```diff
@@ -392,7 +392,7 @@ function M.check_logs()
   )
 end
 
-function M.sysname()
+local function sysname()
   return uv.os_uname().sysname:lower()
```
Comment (justinmk) [inline test/testutil.lua:396]: not used in any existing tests, and they should not really be using this directly.

File: runtime/lua/vim/fs.lua [hunk 2]
```diff
@@ -2,6 +2,7 @@ local uv = vim.uv
 
 local M = {}
 
+-- Can't use `has('win32')` because the `nvim -ll` test runner doesn't support `vim.fn` yet.
 local iswin = uv.os_uname().sysname == 'Windows_NT'
```
Comment (zeertzjq) [inline runtime/lua/vim/fs.lua:6]: Also check for MinGW to fix #30212?

File: runtime/lua/vim/fs.lua [hunk 3]
```diff
@@ -2,7 +2,9 @@ local uv = vim.uv
 
 local M = {}
 
-local iswin = uv.os_uname().sysname == 'Windows_NT'
+-- Can't use `has('win32')` because the `nvim -ll` test runner doesn't support `vim.fn` yet.
+local sysname = uv.os_uname().sysname:lower()
+local iswin = sysname:find('windows') or sysname:find('mingw')
```
Comment (justinmk) [inline runtime/lua/vim/fs.lua:7]: We should be using has() here, but can't yet because `fs_spec.lua` runs its (many) tests in the `nvim -ll` test runner, which doesn't support `vim.fn` yet.

**Comment by clason** [comment]
Can this be backported? Sounds like a valuable fix.
