### PR TITLE
Fix problem with uv_write being called despite no output

### LINKED ISSUE #11653: crash with statusline + coc.nvim
- `nvim --version`:

```
NVIM v0.5.0-275-g34a59242a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-c551267c-89c8-4c0f-9e98-47bd2ce1b3e8

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
```

- Operating system/version:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

- Terminal name/version:

```
GNOME Shell 3.18.5
```

- `$TERM`:

```
xterm-256color
```

### Steps to reproduce using minimal config

- Install COC: https://github.com/neoclide/coc.nvim

- Create file `mini.vim` with:

```vim
set nocompatible                                                                                                                                                                                                                                              
set runtimepath^=~/.local/share/nvim/plugged/coc.nvim    
filetype plugin indent on                                                                                                                                                                                                                                   
syntax on                                                                                                                                                                                                                                                   
set hidden                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                           
function! Foobar()                                                                                                                                                                                                                                          
   let foo = system("bar")    
endfunction           
                     
set statusline+=%{Foobar()} 
set termguicolors
```

- Start neovim with command:

```
nvim -u mini.vim
```

- Type `:CocAction` or `:CocList`.

### Actual behaviour

Nvim 0.5.0 crashes :

> nvim: /home/travis/build/neovim/bot-ci/build/neovim/.deps/build/src/libuv/src/unix/stream.c:1400: uv_write2: Assertion `nbufs > 0' failed.

Doesn't happen with 0.4.3.

### PR DESCRIPTION
**Pull request by erw7**
fixes #11653, #11990

### CODE REVIEW

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -1973,7 +1973,23 @@ static void flush_buf(UI *ui)
...
+  //       | !want_invisible |     N/A      |    invis
+  // ------+-----------------+--------------+---------------
+  // !busy | want_invisible  |     N/A      |    invis
+  //       | !want_invisible |     norm     | invis + norm
+  // ------+-----------------+--------------+---------------
+  //
+  if (data->bufpos <= 0
+      && ((data->busy && data->is_invisible)
+          || (data->is_invisible && !data->busy && data->want_invisible)
+          || (!data->is_invisible && !data->busy && !data->want_invisible))) {
```
Comment (teto) [inline src/nvim/tui/tui.c:1992]: if I nitpick I would keep the order consistent between the different condition, and ideally with the table:
(data->busy / is_invisible / want_invisible

**Review by teto — COMMENTED** [review]
Thanks for the very nice PR/explanation. This important fix will help many coc users.
If you could arrange the order  that would be perfect.

File: src/nvim/tui/tui.c (hunk 1 above)
Comment (erw7) [reply src/nvim/tui/tui.c:1992]: It is corrected to the processing order ( is_invisible / data->busy / want_invisible. I think `busy` and  `want_invisible` are so closely related that it's better to have them next to each other. The table has not been modified because the number of columns exceeds 80 characters. Sure, it's a little hard to see, but if you read it vertically, it's not hard to read, so how about this?

**Comment by teto** [comment]
Could you prefix the commit with `tui`, for instance:
```
tui: don't call uv_write without output 

Fixes  #11653, #11990
...
```

**Comment by teto** [comment]
thank you !
