### PR TITLE
fix(messages): exclude search hit bottom msg from history

### LINKED ISSUE #13484: How to avoid searches from being written to messages?
Searches and jumps w/ `n`, `N` are written to the message log. I'm guessing (though am not sure) that `echomsg` is used to display the search information. Is there a setting I can toggle to use `echo` instead, so the search info still appears on the bottom but does not appear when I run `:messages`?

Example (in case this description isn't clear):
If in a new buffer I type `this is a test this is a test`, then `*`, then `n` a bunch of times, and then open up messages I see:
```
search hit BOTTOM, continuing at TOP
/\<test\>                                                        [1/2] W
/\<test\>                                                          [2/2]
search hit BOTTOM, continuing at TOP
/\<test\>                                                        [1/2] W
/\<test\>                                                          [2/2]
search hit BOTTOM, continuing at TOP
/\<test\>                                                        [1/2] W
/\<test\>                                                          [2/2]
search hit BOTTOM, continuing at TOP
/\<test\>                                                        [1/2] W
/\<test\>                                                          [2/2]
```
I want these messages displayed at the time of searching/jumping, but not in the log.

### PR DESCRIPTION
**Pull request by def3r**
## Problem:
`:messages` history include the "search hit BOTTOM, continuing at TOP" message.

## Solution:
Set `msg_hist_off` before giving the warning and reset it after warning.

Closes #13484

### CODE REVIEW

File: src/nvim/search.c [hunk 1]
```diff
@@ -954,7 +954,9 @@ int searchit(win_T *win, buf_T *buf, pos_T *pos, pos_T *end_pos, Direction dir,
       if (!shortmess(SHM_SEARCH)
           && shortmess(SHM_SEARCHCOUNT)
           && (options & SEARCH_MSG)) {
+        msg_hist_off = true;
         give_warning(_(dir == BACKWARD ? top_bot_msg : bot_top_msg), true);
+        msg_hist_off = false;
```
Comment (justinmk) [inline src/nvim/search.c]: Looks like it would make sense to add a `bool hist` param to `give_warning`.

File: src/nvim/message.c [hunk 2]
```diff
@@ -3554,6 +3556,7 @@ void give_warning(const char *message, bool hl)
   msg_col = 0;
 
   no_wait_return--;
+  msg_hist_off = false;
```
Comment (justinmk) [inline src/nvim/message.c]: Just to be safe let's do the usual `save_x` dance? Although, other things are set indiscriminately in here so maybe doesn't matter.

```suggestion
  msg_hist_off = save_msg_hist_off;
```

**Review by justinmk — APPROVED** [review]
LGTM, why still in draft?

**Comment by def3r** [comment]
> LGTM, why still in draft?

Couldn't look into tests earlier.
