### PR TITLE
fix(rpc): "grid_line" event parsing crashes

### LINKED ISSUE #25184: assertion failure at unpacker.c:466
### Problem

This assertion fails occasionally while editing code:

https://github.com/neovim/neovim/blob/f67517bba30b6233bea85e1f6a8505171142d4ca/src/nvim/msgpack_rpc/unpacker.c#L467

I can force it to fail by scrolling very quickly.

### Steps to reproduce

`repro.lua`:
```lua
function Repro()
  vim.defer_fn(function()
    local move_direction = math.random(2)
    if move_direction == 1 then
      for i=1,10 do
        vim.api.nvim_feedkeys("5k", "n", false)
      end
    else
      for i=1,10 do
        vim.api.nvim_feedkeys("5j", "n", false)
      end
    end
    Repro()
  end, 0.05)
end
```

```sh
nvim --noplugin --clean -u repro.lua src/nvim/msgpack_rpc/unpacker.c
```

It should crash within 30 seconds. If you get bored you can drag the corner of the terminal around while spamming `<C-c>` to try and mess with it more. Also having plugins (IDK if it matters which ones) seems to make it happen faster / more reliably.

### Expected behavior

No crash.

### Neovim version (nvim -v)

be10d65bf (0.10 nightly)

### Vim (not Nvim) behaves the same?

no

### Operating system/version

MacOS 13.4.1

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by llllvvuu**
refactor: use a more idiomatic loop to iterate over the cells
fixes: #25184

There are two cases in which the following assertion would fail:

https://github.com/neovim/neovim/blob/f67517bba30b6233bea85e1f6a8505171142d4ca/src/nvim/msgpack_rpc/unpacker.c#L467

1. If `g->ncells = 0`. Update this to be legal.
2. If an EOF is reached while parsing `wrap`. In this case, the unpacker attempts to resume from `cells`, which is a bug. Create a new state for parsing `wrap`.

Reference: https://neovim.io/doc/user/ui.html#ui-event-grid_line

### CODE REVIEW

**Comment by llllvvuu** [comment]
I just realized the issue still occurs. I added some more asserts to the code, and it seems to be some kind of concurrency issue as the only assert that actually hits is `assert(g->icell <= prev + 1)`:

```diff
diff --git a/src/nvim/msgpack_rpc/unpacker.c b/src/nvim/msgpack_rpc/unpacker.c
index 3aa1ba122..6afb6e4a7 100644
--- a/src/nvim/msgpack_rpc/unpacker.c
+++ b/src/nvim/msgpack_rpc/unpacker.c
@@ -458,13 +458,18 @@ bool unpacker_parse_redraw(Unpacker *p)
     p->read_size = size;
     p->state = 15;
 
+    assert(tok.length >= 0);
     if ((int)tok.length == 0) {
       return true;
     }
     FALLTHROUGH;
 
   case 15:
+    assert(g->ncells > 0);
+    int prev = -1;
     while (true) {
+      assert(g->icell <= prev + 1);
+      prev = g->icell;
       assert(g->icell < g->ncells);
 
       NEXT_TYPE(tok, MPACK_TOKEN_ARRAY);
```

It usually doesn't happen, but I can consistently trigger it by mouse scrolling as fast as possible (trackpad is especially easy to get the desired velocity). It seems some plugins are required as well, I will bisect and report back.

Is this variable not thread local?

**Comment by llllvvuu** [comment]
OK, both issues are fixed now and have a test for each which fail on master

File: test/unit/unpacker_spec.lua
Comment (justinmk) [inline test/unit/unpacker_spec.lua:1]: Naming this `msgpack_spec.lua` would be helpful imo.

**Review by justinmk — APPROVED** [review]
Need @bfredl to sanity-check this

File: test/unit/unpacker_spec.lua
Comment (llllvvuu) [reply test/unit/unpacker_spec.lua:1]: Funnily enough I'd actually waffled back and forth on that a bit yesterday. So happy to do it of course

File: test/unit/msgpack_spec.lua [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+
+--- @param unpacker Unpacker*
+--- @return boolean
+local function unpacker_advance(unpacker)
+  return lib.unpacker_advance(unpacker)
+end
+
+describe('msgpack', function()
+  describe('unpacker', function()
+    itp('does not crash when paused between `cells` and `wrap` params of `grid_line` (#25184)', function()
```
Comment (justinmk) [inline test/unit/msgpack_spec.lua:39]: parens are unnecessary, there's no risk of ambiguity when a `#123` is at the end of a line.

```suggestion
    itp('does not crash when paused between `cells` and `wrap` params of `grid_line` #25184', function()
```

File: test/unit/msgpack_spec.lua [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+      unpacker_goto(unpacker, payload, payload:len() - 1)
+      local finished = unpacker_advance(unpacker)
+      eq(finished, false)
+
+      unpacker[0].read_size = unpacker[0].read_size + 1
+      finished = unpacker_advance(unpacker)
+      eq(finished, true)
+    end)
+
+    itp('does not crash when parsing grid_line event with 0 `cells` (#25184)', function()
```
Comment (justinmk) [inline test/unit/msgpack_spec.lua:60]:
```suggestion
    itp('does not crash when parsing grid_line event with 0 `cells` #25184', function()
```

File: test/unit/msgpack_spec.lua (hunk 1 above)
Comment (llllvvuu) [reply test/unit/msgpack_spec.lua]: thanks!

File: src/nvim/msgpack_rpc/unpacker.c [hunk 3]
```diff
@@ -461,63 +460,61 @@ bool unpacker_parse_redraw(Unpacker *p)
...
   case 15:
-    assert(g->icell < g->ncells);
-
-    NEXT_TYPE(tok, MPACK_TOKEN_ARRAY);
-    int cellarrsize = (int)tok.length;
-    if (cellarrsize < 1 || cellarrsize > 3) {
-      p->state = -1;
-      return false;
-    }
+    for (; g->icell != g->ncells; g->icell++, p->read_ptr = data, p->read_size = size) {
```
Comment (bfredl) [inline src/nvim/msgpack_rpc/unpacker.c:463]: lumping in the `p->read_ptr = data, p->read_size = size` here is not really readable. Just keep them at the end of the loop.

File: src/nvim/msgpack_rpc/unpacker.c [hunk 4]
```diff
@@ -461,63 +460,61 @@ bool unpacker_parse_redraw(Unpacker *p)
...
+            return false;
+          }
+          grid_line_buf_char[g->coloff] = sc;
+          grid_line_buf_attr[g->coloff++] = g->cur_attr;
         }
-        grid_line_buf_char[g->coloff] = sc;
-        grid_line_buf_attr[g->coloff++] = g->cur_attr;
       }
     }
+    p->state = 16;
```
Comment (bfredl) [inline src/nvim/msgpack_rpc/unpacker.c:509]: also update the comment line above (the one with ` <0>[2, "redraw", <10>[{11}["grid_line", <14>[g, r, c, [<15>[cell], <15>[cell], ...]], ...], <11>[...], ...]]` ) to mention the new state 16.

**Review by bfredl — APPROVED** [review]
otherwise LGTM, thanks for the fix!

**Comment by llllvvuu** [comment]
Sorry for the delay, didn't have Wi-fi for a while. Just made the requested changes
