### PR TITLE
fix(api): don't use 'winborder' when reconfiguring float

### LINKED ISSUE #32974: `nvim_win_set_config` sets `border` from `winborder` even if it was explicitly set before
### Problem

`nvim_win_set_config` changes `border` value to `winborder` value if not empty.

After #31074

### Steps to reproduce

```init.lua
vim.o.winborder = 'single'
local winId = vim.api.nvim_open_win(vim.api.nvim_create_buf(false, true), false, {
  relative = 'laststatus',
  col = 0,
  row = 2,
  width = 10,
  height = 1,
  border = 'none',
}) -- here is OK
vim.api.nvim_win_set_config(winId, {
  relative = 'laststatus',
  col = 0,
  row = 2,
  width = 10,
  height = 1,
})
```
- `nvim --clean -u init.lua`

### Expected behavior

The border value should be left intact by `nvim_win_set_config`.

### Nvim version (nvim -v)

v0.11.0-dev-2041+g62d9fab9af

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Debian Sid

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

from repo

### PR DESCRIPTION
**Pull request by glepnir**
Problem: reconfig-ing a floatwin applies the global 'winborder'.

Solution:
- ignore 'winborder' when reconfig-ing a floatwin.
- apply 'winborder' when converting a "split" win to a "float" win.

Fix #32974

### CODE REVIEW

**Comment by zeertzjq** [comment]
Again,
> should `'winborder'` apply to floating windows converted from split windows by `nvim_win_set_config`?

It may make sense to do this, since converting a floating window to a split also erases border config.

File: test/functional/api/window_spec.lua [hunk 1]
```diff
@@ -1833,6 +1833,22 @@ describe('API/win', function()
       eq('', api.nvim_win_get_config(new_win).relative)
     end)
 
+    it('can use winborder when converting a split window to a floating window', function()
```
Comment (justinmk) [inline test/functional/api/window_spec.lua:1836]:
```suggestion
    it("uses 'winborder' when converting a split to a floating window", function()
```

**Comment by przepompownia** [comment]
It fixes at least the bug reported in #32974 I haven't checked behavior related to splitting. Thank you all!

File: test/functional/api/window_spec.lua [hunk 2]
```diff
@@ -1833,6 +1833,38 @@ describe('API/win', function()
...
+        row = 2,
+        col = 2,
+        width = 10,
+        height = 5,
+      })
+      local config = api.nvim_win_get_config(winid)
+      eq('┌', config.border[1])
+    end)
+
+    it("erases 'winborder' of a floating window when converting to split window", function()
```
Comment (zeertzjq) [inline test/functional/api/window_spec.lua:1852]:
```suggestion
    it("erases border of a floating window when converting to split window", function()
```

File: test/functional/api/window_spec.lua [hunk 3]
```diff
@@ -1833,6 +1833,38 @@ describe('API/win', function()
...
+        width = 10,
+        height = 5,
+      })
+      local config = api.nvim_win_get_config(winid)
+      eq('┌', config.border[1])
+      api.nvim_win_set_config(winid, { split = 'right', win = 0 })
+      config = api.nvim_win_get_config(winid)
+      eq(nil, config.border)
+    end)
+
```
Comment (zeertzjq) [inline test/functional/api/window_spec.lua:1867]: Wrong place. This is inside with `open_win` `describe()` block. They should be in the `set_config` `describe()` block

Comment (glepnir) [reply test/functional/api/window_spec.lua]: moved.

File: test/functional/ui/float_spec.lua [hunk 4]
```diff
@@ -10152,7 +10152,75 @@ describe('float window', function()
...
+          ^                                        |
+          {0:~                                       }|
+          {0:~ }{1:none}{0:                                  }|
+          {0:~ }{1: bor}{0:                                  }|
+          {0:~ }{1:der }{0:                                  }|
+          {0:~ }{2:~   }{0:                                  }|
+                                                  |
+        ]])
+      end
+      command('fclose!')
```
Comment (zeertzjq) [inline test/functional/ui/float_spec.lua:10223]: This is way too much duplicate screen state. Can't you just use the previous floating window with `screen:expect_unchanged()`? (You need to assign the result of the previous `api.nvim_open_win` to `winid`)
```suggestion
      -- don't use winborder when reconfig a floating window
      config.border = nil
      api.nvim_win_set_config(winid, config)
      screen:expect_unchanged()
      command('fclose!')
```

Comment (glepnir) [reply test/functional/ui/float_spec.lua]: make sense

**Review by zeertzjq — APPROVED** [review]

**Review by justinmk — APPROVED** [review]
