### PR TITLE
fix(lua): inspect_pos respect bufnr when get syntax info

### LINKED ISSUE #23096: `vim.inspect_pos(buffnr).syntax` does not respect the passed buffer number
### Problem

Calling `vim.inspect_pos(buffnr)` returns the syntax highlighting information for the current buffer regardless of the passed `buffnr`, as https://github.com/folke/neovim/blob/master/runtime/lua/vim/_inspector.lua#L78-L82 does not depend on the passed buffer number.

### Steps to reproduce

```
nvim --clean
i"test"<esc>
:set filetype=python
:enew
i# test<esc>
:set filetype=python
:lua print(vim.inspect(vim.inspect_pos(1, 0, 0)))
:buffer 1
:lua print(vim.inspect(vim.inspect_pos(1, 0, 0)))
```

### Expected behavior

It should return the syntax information from the referenced buffer, not the current buffer

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

not applicable, `vim` does not support `vim.inspect_pos`

### Operating system/version

Linux 6.2.10-arch1-1, ArchLinux

### Terminal name/version

alacritty 0.12.0 (5a728195)

### $TERM environment variable

alacritty

### Installation

pacman (so system package manager)

### PR DESCRIPTION
**Pull request by glepnir**
Problem: `synstack` get the syntax in current window this will ignore the `bufnr` param.
Solution: wrap `synstack` in `nvim_buf_call` to inspect `bufnr` .  
Chore: use set value to index instead invoke `table.insert` . in luajit  this is fast than `insert`.

Fix #23096

### CODE REVIEW

File: runtime/lua/vim/_inspector.lua [hunk 1]
```diff
@@ -70,15 +70,17 @@ function vim.inspect_pos(bufnr, row, col, filter)
   if filter.treesitter then
     for _, capture in pairs(vim.treesitter.get_captures_at_pos(bufnr, row, col)) do
       capture.hl_group = '@' .. capture.capture .. '.' .. capture.lang
-      table.insert(results.treesitter, resolve_hl(capture))
+      results.tressiter[#results.treesitter + 1] = resolve_hl(capture)
```
Comment (zeertzjq) [inline runtime/lua/vim/_inspector.lua:73]:
```suggestion
      results.treesitter[#results.treesitter + 1] = resolve_hl(capture)
```

File: runtime/lua/vim/_inspector.lua [hunk 2]
```diff
@@ -70,15 +70,17 @@ function vim.inspect_pos(bufnr, row, col, filter)
   if filter.treesitter then
     for _, capture in pairs(vim.treesitter.get_captures_at_pos(bufnr, row, col)) do
       capture.hl_group = '@' .. capture.capture .. '.' .. capture.lang
-      table.insert(results.treesitter, resolve_hl(capture))
+      results.treesiter[#results.treesitter + 1] = resolve_hl(capture)
```
Comment (zeertzjq) [inline runtime/lua/vim/_inspector.lua:73]:
```suggestion
      results.treesitter[#results.treesitter + 1] = resolve_hl(capture)
```

**Comment by glepnir** [comment]
@zeertzjq   LGTY?
