### PR TITLE
[LSP] Fix separator drawing on hover (fixes #13006, #12998)

### LINKED ISSUE #12998: [LSP Hover Style] Header divider line should not wrap
Hello Neovim LSP team,

An LSP Hover style issue best explained with this screenshot:

Neovim_LSP_Hover_Line_Wrap

Whenever there is multiline documentation in hover floating window, native Neovim LSP adds in a header divider line.

The divider line itself is fine.
However, it should never wrap.
Notice in the image above the wrapping below the `Axios` function.

It appears that the length of the divider line is taken from the API function it sits beneath.
Instead it would be much better if the length of the divider line is simply the width of the floating window.

This is an ideal example here:

Neovim_LSP_Hover_No_Wrap

Flutter + Dart has fat APIs which causes the header divider line to wrap in non-pleasing ways.

Best regards.

### LINKED ISSUE #13006: vim.lsp.util.fancy_floating_markdown always draw separator
- `nvim --version`: NVIM v0.5.0-709-g4f8d98e58, LuaJIT 2.1.0-beta3
- language server name/version: clangd version 10.0.1

### Steps to reproduce

The code below is customized version from official `textDocument/hover` callback function. Whatever `separator` option is the separator always drawn.

```lua
local hover_float_callback = function(_, method, result)
    util.focusable_float(method, function()
        -- ...
        local bufnr, winnr = util.fancy_floating_markdown(markdown_lines, {
            pad_left = 3; pad_right = 3; pad_top = 1; pad_bottom = 1; separator = false;  --> modified here
        })
        vim.api.nvim_win_set_option(winnr, 'conceallevel', 3)
        util.close_preview_autocmd({"CursorMoved", "BufHidden", "InsertCharPre"}, winnr)
        return bufnr, winnr
    end)
end
```
image

The `separator` option check code in the function `fancy_floating_markdown` on the file `lua/vim/lsp/util.lua` has a bug.

```lua
local insert_separator = opts.separator or true   --> Even opts.separator was false insert_separator always true.
if insert_separator then
    for i, h in ipairs(highlights) do
        h.start = h.start + i - 1
        h.finish = h.finish + i - 1
        if h.finish + 1 <= #stripped then
            table.insert(stripped, h.finish + 1, string.rep("─", width))
            height = height + 1
        end
    end
end

```

### PR DESCRIPTION
**Pull request by clason**
* The previous conditional for inserting a separator in `lsp.util.fancy_floating_markdown` did not work if `opts.separator` was set to `false`; the default option `true` for an empty option is now set explicitly.
Fixes #13006 

* If the method signature was longer than than the window width and `max_width` was not set, then the separator was calculated based on the full width and wrapped as well. Now it is always terminated at `wrap_at` (which might be less than `max_width`).
Fixes #12998

### CODE REVIEW

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -800,13 +800,15 @@ function M.fancy_floating_markdown(contents, opts)
   local width, height = M._make_floating_popup_size(stripped, opts)
 
   -- Insert blank line separator after code block
-  local insert_separator = opts.separator or true
+  local insert_separator = opts.separator
```
Comment (teto) [inline runtime/lua/vim/lsp/util.lua:803]: doesn't that always enable the separator ? maybe we should set insert_separator to the char to insert (eg "─" by default) and if null don't print a line.

Comment (clason) [reply runtime/lua/vim/lsp/util.lua:803]: that's exactly what the next line is for :)

Comment (teto) [reply runtime/lua/vim/lsp/util.lua:803]: I thing I get it, it should be disabled only if opts.separator is false ? (was thinking setting it to nil was a valid way to disable as well which confused me).

Comment (clason) [reply runtime/lua/vim/lsp/util.lua:803]: Exactly, but `nil` means that the option isn't set, and the default (true) should be used. But the disjunction of course always returned `true` (since nil is false-y).

File: runtime/lua/vim/lsp/util.lua [hunk 2]
```diff
@@ -800,13 +800,15 @@ function M.fancy_floating_markdown(contents, opts)
...
+  if insert_separator == nil then insert_separator = true end
+  local separator_width = math.min(width, opts.wrap_at)
```
Comment (teto) [inline runtime/lua/vim/lsp/util.lua:805]: move the separator_width inside the if, no need to compute it if we dont use it
