### PR TITLE
fix(treesitter): run FileType autocmds in the context of `<abuf>`

### LINKED ISSUE #35390: Treesitter: deleting buffer changes syntax highlighting of another buffer
### Problem

Treesitter: deleting buffer changes syntax highlighting of another buffer.

This is bisected to 285c04e2d0e3adc2a05d6fd8d0fdcee313ec1b08.

### Steps to reproduce

1. Run `nvim --clean`
2. Run `:edit $VIMRUNTIME/indent.vim`, which uses `vim` syntax highlighting
3. Run `:vsplit $VIMRUNTIME/filetype.lua`, which uses treesitter highlighting
4. Run `:bdelete`
5. The syntax highlighting in `indent.vim` (shown by `:set syntax?`) has changed from `vim` to `lua`

### Expected behavior

The syntax highlighting in `indent.vim` shouldn't change

### Nvim version (nvim -v)

v0.12.0-dev-1038+g1e20f31aa3

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.42.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by seandewar**
Problem: many FileType autocommands assume `curbuf == <abuf>`; this can cause `&syntax` to be restored for the wrong buffer in some cases when `TSHighlighter:destroy` is called.

Solution: run `nvim_exec_autocmds` in the context of the target buffer via `nvim_buf_call`.

Fixes #35390

### CODE REVIEW

File: runtime/lua/vim/treesitter/highlighter.lua [hunk 1]
```diff
@@ -191,10 +191,13 @@ function TSHighlighter:destroy()
...
     if vim.g.syntax_on == 1 then
-      api.nvim_exec_autocmds(
-        'FileType',
-        { group = 'syntaxset', buffer = self.bufnr, modeline = false }
-      )
+      -- FileType autocmds commonly assume curbuf is the target buffer, so nvim_buf_call.
+      api.nvim_buf_call(self.bufnr, function()
+        api.nvim_exec_autocmds(
+          'FileType',
+          { group = 'syntaxset', buffer = self.bufnr, modeline = false }
```
Comment (justinmk) [inline runtime/lua/vim/treesitter/highlighter.lua:198]: not a blocker for this pr, but `nvim_exec_autocmds` should just do this implicitly. it's completely silly that it needs to be wrapped when the user already passed `buffer=bufnr`.

**Review by justinmk — APPROVED** [review]

File: runtime/lua/vim/treesitter/highlighter.lua (hunk 1 above)
Comment (seandewar) [reply runtime/lua/vim/treesitter/highlighter.lua:198]: I would go as far to say I wish _all_ autocmds worked like that :smiling_face_with_tear:

Comment (tomtomjhj) [reply runtime/lua/vim/treesitter/highlighter.lua:198]: The fix in that direction is simple, so maybe it's fine do it in this pr
```diff
diff --git a/src/nvim/api/autocmd.c b/src/nvim/api/autocmd.c
index 2d480e94b7..ad47c6fcb3 100644
--- a/src/nvim/api/autocmd.c
+++ b/src/nvim/api/autocmd.c
@@ -750,6 +750,9 @@ void nvim_exec_autocmds(Object event, Dict(exec_autocmds) *opts, Arena *arena, E

   modeline = GET_BOOL_OR_TRUE(opts, exec_autocmds, modeline);

+  aco_save_T aco;
+  aucmd_prepbuf(&aco, buf);
+
   bool did_aucmd = false;
   FOREACH_ITEM(event_array, event_str, {
     GET_ONE_EVENT(event_nr, event_str, return )
@@ -763,6 +766,8 @@ void nvim_exec_autocmds(Object event, Dict(exec_autocmds) *opts, Arena *arena, E
   if (did_aucmd && modeline) {
     do_modelines(0);
   }
+
+  aucmd_restbuf(&aco);
 }

 static Array unpack_string_or_array(Object v, char *k, bool required, Arena *arena, Error *err)
```

Comment (seandewar) [reply runtime/lua/vim/treesitter/highlighter.lua:198]: Dunno if it's better to change the behaviour now or wait until 0.12. (Also dunno if we should `prepbuf` for each pattern or just once before calling `apply_autocmds_group`)

**Comment by seandewar** [comment]
Gonna merge now, leaving possible changes to `nvim_exec_autocmds` for later. :saluting_face:
