### PR TITLE
fix(startup): Wait for bg detection before processing user scripts

### LINKED ISSUE #28667: 0.10 colorscheme flickering
### Problem

There are a few conditions when colorscheme flickers when launching neovim. By flickering I mean that it between changin background from terminal background to neovim background, there is a period of time when the background is black.

I think it is somewhat related to #19362 . These only reproduce on nightly, 0.9.5 is fine.

### Steps to reproduce

For any of this, run `nvim --clean -u minimal.lua` with the contents of `minimal.lua` described below.

#### termguicolors

After setting `termguicolor`, background switches to black before switching to the user-defined one. Run with `sleep` to pause on black background, or with some synchronous code to see flickering.

I know that `termguicolors` is enabled automatically in 0.10, however this causes 0.9 configs to flicker and people waste time debugging. Also, I don't know how this works under the hood, but automatic setting of `termguicolors` seems to happen after `init.lua` is loaded, because `vim.o.termguicolors` returns `false` if printed inside user config (when not set manually).

```lua
vim.opt.termguicolors = true
-- vim.cmd.sleep(1)
vim.fn.system("notify-send loading")

vim.cmd.colorscheme("blue")
```

#### VimEnter

If you have a VimEnter autocommand with any synchronous action, the same thing happens. There are 3 cases. 

If you run (1) - you will see the same effect as with `termguicolors` - background switches to black. 
If you run (2) - you may see very subtle flickering of the screen. I choose `fn.system` as a generic synchronous side-effect. The same happens with `system():wait`.
If you run (3) - no flickering. The same is described in https://github.com/neovim/neovim/issues/19362#issuecomment-1924993842

```lua
vim.api.nvim_create_autocmd("VimEnter", {
	callback = function()
		--[[ (1) ]] vim.cmd.sleep(1)
		--[[ (2) ]] vim.fn.system("notify-send vimenter")
		--[[ (3) ]] vim.print("asdf")
	end,
})
vim.cmd.colorscheme("blue")
```

#### unnamedplus

Same flickering, however you cannot pause on it by running `sleep`, maybe it happens at different point in time. But, if you run synchronous commands, then you can see the flickering.

```lua
vim.opt.clipboard = "unnamedplus"
vim.fn.system("notify-send loading")
vim.cmd.colorscheme("blue")
```

### Expected behavior

No flickering like on 0.9.5. 

### Neovim version (nvim -v)

0.10.0-dev-3097+g064f3e42e

### Operating system/version

Linux/X11

### Terminal name/version

Tested on: kitty + tmux; kitty; wezterm; alacritty

### $TERM environment variable

Respectively^: tmux-256color; xterm-kitty; xterm-256color; alacritty

### Installation

Build from repo

### LINKED ISSUE #32109: 'background' detection occurs too late, causing colorscheme to load twice
### Problem

Neovim automatically sets `'background'` based on whether the terminal is in light or dark mode, both on startup and (on nightly) when the terminal's appearance changes. In the former case, at least on my machine, the automatic setting of the option occurs too late when the terminal is in light mode, meaning:
- Start up Nvim in a light mode terminal with a configured colorscheme
- The `'bg'` option is initially `"dark"` even though the terminal and OS are in light mode
- The configured colorscheme is applied while `'bg'` is still set to `"dark"`. Depending on the implementation of the colorscheme this could mean that it applies designated colors for its dark version.
- The automatic `'bg'` detection kicks in and sets the option to `"light"`.
- Because of the change the colorscheme is reloaded, this time with a `'bg'` value of `"light"` (which again may cause it to apply specific – in this case the correct – colors).

This is obviously bad because it's expensive and unnecessary, but particularly annoying with themes that adapt to the background because it means that there is a flash of dark before the correct colors are loaded.

### Steps to reproduce

1. Create a minimal configuration using `NVIM_APPNAME` (couldn't figure out how to do what needs to be done with just the issue template), with this structure:
   ```
   .
   ├── colors
   │   └── mycolors.lua
   └── init.lua
   ```
   Contents of `mycolors.lua`:
   ```lua
   -- a very simple mock colorscheme that follows the background

   local bg = vim.o.background

   if bg == "dark" then
       print("the value of 'bg' is: 'dark', thus applying the dark colors")
       vim.api.nvim_set_hl(0, "Normal", {bg = "#000000", fg = "#ffffff"})
   elseif bg == "light" then
       print("the value of 'bg' is: 'light', thus applying the light colors")
       vim.api.nvim_set_hl(0, "Normal", {bg = "#ffffff", fg = "#000000"})
   end

   vim.g.colors_name = "mycolors"
   ```
   Contents of `init.lua`:
   ```lua
   -- this part is optional:

   --vim.api.nvim_create_autocmd("ColorScheme", { callback = function(data)
   --    print(vim.inspect(data))
   --end})

   --vim.api.nvim_create_autocmd("OptionSet", { pattern = "background", callback = function(data)
   --    print(vim.inspect(data))
   --end})

   vim.cmd.colorscheme("mycolors")

   ```
2. Run `NVIM_APPNAME=<your name> nvim` in a light mode terminal (can reproduce in Kitty and Ghostty). A black flicker will be visible before the background becomes bright white as expected (Because nvim is so fast, this is barely noticable, but with a heavy config full of plugins, it is very noticable).
3. Check `:messages`. The order of the messages will be:
   - `the value of 'bg' is: 'dark', thus applying the dark colors`
   - `the value of 'bg' is: 'light', thus applying the light colors`

### Expected behavior

The value of `'background'` is determined and set as early as possible so that it does not trigger reloading of the colorscheme.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-6696ea7

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 15.2

### Terminal name/version

Ghostty 1.0.1, kitty 0.39.0

### $TERM environment variable

xterm-ghostty

### Installation

build from repo

### LINKED ISSUE #36211: Light terminal background can affect legacy syntax highlighting after startup
### Problem

The background kind of terminal emulator can affect the result of a startup. In particular, it can lead to legacy syntax highlight groups being cleared after startup if terminal background is light. This results into no visible highlight until the explicit `:edit`.

### Steps to reproduce

1. Create the 'init-cs.lua' lua with the single line `vim.cmd('colorscheme default')`. It seems to be reproducible with any color scheme which has `:hi clear` at the beginning.
2. Create a test 'nginx.conf' file with a single line `user  www www;`.
3. Have terminal background be light and execute `nvim --clean -u init-cs.lua -- nginx.conf`. The word `user` is not highlighted. The output of `:Inspect` is `ngxDirective` (i.e. seems to be cleared). It becomes highlighted after `:edit`.
    3.a Have terminal background be dark and execute `nvim --clean -u init-cs.lua -- nginx.conf`. The word `user` is highlighted. The output of `:Inspect` is `ngxDirective links to Function`.

This seems to be a combination of the following aspects:
1. [Guessing and setting the 'background'](https://github.com/neovim/neovim/blob/b459bf5961fd6bbd7c887d9c3751ff5dbbdcf55d/runtime/lua/vim/_defaults.lua#L720) during startup. Light background leads to setting `vim.o.background = 'light'`, which resources the color scheme, which leads to `:hi clear`. I.e. *it seems* that the effect of this guessing occurs *after* legacy syntax is applied.
2. The syntax for 'nginx' defines highlight groups [via pure linking](https://github.com/neovim/neovim/blob/b459bf5961fd6bbd7c887d9c3751ff5dbbdcf55d/runtime/syntax/nginx.vim#L2310-L2342), i.e. not `hi def link`. As highlight groups are not default, they are not restored after `:hi clear`. Although using `hi def link` in legacy syntax is more common, there are non trivial amount of cases where `hi link` is used.

My guess would be that the 2. is the "main" culprit. Changing `hi link` to `hi def link` fixes the issue.

But some aspect of 1. can still be at play here. Maybe somehow postponing legacy syntax effect until after 'background' is guessed is possible? Or maybe on top of [setting 'background'](https://github.com/neovim/neovim/blob/b459bf5961fd6bbd7c887d9c3751ff5dbbdcf55d/runtime/lua/vim/_defaults.lua#L816) there can be some sort of syntax update (maybe `:syntax reset`, not sure).

### Expected behavior

Background color of terminal emulator should not affect whether some highlight groups are defined or not.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-1459+g0791594101

### Vim (not Nvim) behaves the same?

No

### Operating system/version

EndeavourOS Linux x86_64, 6.17.1-arch1-1

### Terminal name/version

Ghostty 1.2.0-arch1

### $TERM environment variable

xterm-ghostty

### Installation

Appimage

### LINKED ISSUE #36416: Highlight set in user init file is not applied with default colorscheme
### Problem

Possibly related: https://github.com/neovim/neovim/issues/36211

Setting a highlight like `vim.api.nvim_set_hl(0, 'NonText', { fg = 'NvimLightGrey2' })` seems to be overridden by something happening in `_defaults.lua` related to TermResponse autocmd (timing related?).

### Steps to reproduce

Use a terminal emulator with a light background.

create `test.lua` with:

```lua
vim.api.nvim_set_hl(0, 'NonText', { fg = 'NvimLightGrey2' })
```

`nvim -V9log --clean -u test.lua`

Check `:verbose hi` and see it is last set from `_defaults.lua` file. Checking `:scriptnames` shows that `test.lua` is sourced after that file, and so the value of `:hi NonText` should have been changed changed, but it's set to `guifg=NvimLightGrey4` which is the default.

Log (`:scriptnames` output at the end)
[v9log.txt](https://github.com/user-attachments/files/23269382/v9log.txt)

### Expected behavior

Highlights set in user init file apply and are not overruled by the `_defaults.lua` file.

Is it some kind of timing-related bug with TermResponse? How can I prevent nvim from checking at all?

### Nvim version (nvim -v)

0.12.0-dev-1379+ga4006360f1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows 10

### Terminal name/version

Terminal Canary

### $TERM environment variable

`:echo $TERM` is empty, `-V9` log shows `&term=vtpcon`

### Installation

winget

### PR DESCRIPTION
**Pull request by kylesower**
Problem:
Automatic background detection sets the background option too late, which loads colorschemes twice and causes problems when the user's terminal background doesn't match the default (#32109, #36211, #36416).

Solution:
Use a DA1 query to determine whether the TTY supports OSC 11. Wait for background detection and setting to complete before processing user config.

Note:
I maintained the existing behavior as much as possible by triggering OptionSet manually on VimEnter (since it won't trigger automatically if we set the bg during startup). However, I'm unsure if this behavior is truly desired given that the documentation says OptionSet is triggered "After setting an option (except during |startup|)."

These changes also fix the flickering issue described in #28667. To check for the flickering, you can run `nvim --clean --cmd "set termguicolors" --cmd "echo \"foo\"" --cmd "sleep 10"`. On master, this gives me a black screen for 10 seconds, but on this branch, the background is dark or light depending on the terminal background (since the option is now set during startup rather than after VimEnter).

fix #28667
fix #32109
fix #36211
fix #36416

### CODE REVIEW

File: runtime/lua/vim/_defaults.lua [hunk 1]
```diff
@@ -805,31 +805,50 @@ do
...
           local resp = args.data.sequence ---@type string
+
+          -- DA1 response that should come after the OSC 11 response if the
+          -- terminal supports it.
+          if string.match(resp, '^\x1b%[%?.-c$') then
+            bg_detection_complete = true
+            if not bg_response_received then
+              return true
+            end
+            return false
```
Comment (justinmk) [inline runtime/lua/vim/_defaults.lua]:
```suggestion
            return not bg_response_received
```

File: runtime/lua/vim/_defaults.lua [hunk 2]
```diff
@@ -841,13 +860,25 @@ do
         nested = true,
         once = true,
         callback = function()
-          if vim.api.nvim_get_option_info2('background', {}).was_set then
-            vim.api.nvim_del_autocmd(id)
+          local optinfo = vim.api.nvim_get_option_info2('background', {})
+          local cmdline_sid = -3
+          if optinfo.last_set_sid > 0 or optinfo.last_set_sid == cmdline_sid then
+            pcall(function()
+              vim.api.nvim_del_autocmd(id)
```
Comment (justinmk) [inline runtime/lua/vim/_defaults.lua]: `pcall` is a red flag, can a condition be checked instead?

File: runtime/lua/vim/_defaults.lua [hunk 3]
```diff
@@ -805,31 +805,50 @@ do
       -- an OSC 11 response from the terminal emulator. If the user has set
       -- 'background' explicitly then we will delete this autocommand,
       -- effectively disabling automatic background setting.
-      local force = false
+      local bg_response_received = false
+      local bg_detection_complete = false
```
Comment (justinmk) [inline runtime/lua/vim/_defaults.lua]:
```
did_bg_response
did_bg_detection
```

**Review by justinmk — APPROVED** [review]
This looks thoughtful 🚀 
I assume @gpanders may want to review

File: runtime/lua/vim/_defaults.lua [hunk 4]
```diff
@@ -805,31 +805,50 @@ do
...
+          -- DA1 response that should come after the OSC 11 response if the
+          -- terminal supports it.
+          if string.match(resp, '^\x1b%[%?.-c$') then
+            bg_detection_complete = true
+            if not bg_response_received then
+              return true
+            end
+            return false
+          end
+
```
Comment (gpanders) [inline runtime/lua/vim/_defaults.lua]: We intentionally don't delete this autocommand today because we want to handle other OSC 11 responses that are triggered from theme change notifications. This PR would regress that feature (I guess we don't have a test for that or else the test should have failed).

**EDIT:** Ah I see, but if we receive the DA1 response without ever having received an OSC 11 response then we know the terminal doesn't support it, in which case removing the autocommand is ok. So this is fine actually.

**Review by gpanders — CHANGES_REQUESTED** [review]

File: runtime/lua/vim/_defaults.lua [hunk 5]
```diff
@@ -841,13 +860,25 @@ do
...
+              vim.api.nvim_del_autocmd(id)
+            end)
           end
         end,
       })
 
-      vim.api.nvim_ui_send('\027]11;?\007')
+      -- Send OSC 11 query along with DA1 request to determine whether terminal
+      -- supports the query. #32109
+      vim.api.nvim_ui_send('\027]11;?\007\027[c')
```
Comment (gpanders) [inline runtime/lua/vim/_defaults.lua]: Should probably also update `tui_query_bg_color` in `tui.c` to also emit DA1.

**Review by gpanders — APPROVED** [review]

File: runtime/lua/vim/_defaults.lua (hunk 4 above)
Comment (kylesower) [reply runtime/lua/vim/_defaults.lua]: But if we receive the DA1 response before the OSC 11 response, doesn't that mean the terminal doesn't support the OSC 11 query (or processes out of order)? The theme change notifications may still trigger the bg query, but those would still (presumably) receive no response, right?

EDIT: saw your edit.

File: runtime/lua/vim/_defaults.lua (hunk 5 above)
Comment (kylesower) [reply runtime/lua/vim/_defaults.lua]: I'm not sure whether we need it for all the subsequent queries because the DA1 is intended to detect the feature support in the first place. By detecting feature support during startup, we can wait for the background response before proceeding with user scripts. I don't see how it helps in queries that are triggered by theme changes (where, if there is no support, the autocommand shouldn't trigger at all), but there could easily be something I'm missing.

File: runtime/lua/vim/_defaults.lua (hunk 2 above)
Comment (kylesower) [reply runtime/lua/vim/_defaults.lua]: Just updated it to check if we got a response to the background query instead. I also changed the condition on the SID because I realized there were other SIDs that should trigger deletion (namely `SID_CMDARG`).

File: runtime/lua/vim/_defaults.lua (hunk 5 above)
Comment (gpanders) [reply runtime/lua/vim/_defaults.lua]: It's not strictly necessary, but it keeps things consistent and removes potential for confusion caused by differences in implementation ("why does this query emit DA1 but this one does not?")

**Comment by kylesower** [comment]
I'm not sure why the Windows and FreeBSD builds have some failing tests. Also not sure if you want me to add some tests for this, but I'm happy to do so. Will just take me some more time to figure out how it all works.

P.S. I'm not sure how useful the test is for the flickering, given that the behavior still seemed to be present on master.

EDIT: Who am I kidding? Of course I should add some tests. I'm working on that now.

File: runtime/lua/vim/_defaults.lua [hunk 6]
```diff
@@ -841,13 +859,23 @@ do
         nested = true,
         once = true,
         callback = function()
-          if vim.api.nvim_get_option_info2('background', {}).was_set then
+          local optinfo = vim.api.nvim_get_option_info2('background', {})
+          local sid_lua = -8
+          if not did_del_autocmd and optinfo.was_set and optinfo.last_set_sid ~= sid_lua then
             vim.api.nvim_del_autocmd(id)
```
Comment (justinmk) [inline runtime/lua/vim/_defaults.lua]: `did_del_autocmd` seems to confuse things. We already have an autocmd `id` so we know whether than `id` was deleted. But then `did_del_autocmd` implies that some other aucmd id might be present that we don't want to delete?

**Comment by justinmk** [comment]
As long as this change doesn't regress things, or fail existing (correct) tests, it is low risk. So I would suggest maybe only 1 test that tests the most important aspect(s), and only if it is reliable. Adding new tests that are unreliable and not super important is a poor tradeoff.

File: runtime/lua/vim/_defaults.lua (hunk 6 above)
Comment (kylesower) [reply runtime/lua/vim/_defaults.lua]: Yeah, I did overcomplicate that. I think I was led astray by one of the errors I saw on the Windows tests and thought that it would throw an error if it tried to delete the same autocmd more than once. That appears not to be the case, so I should be able to remove that condition entirely.

**Comment by kylesower** [comment]
> As long as this change doesn't regress things, or fail existing (correct) tests, it is low risk. So I would suggest maybe only 1 test that tests the most important aspect(s), and only if it is reliable. Adding new tests that are unreliable and not super important is a poor tradeoff.

@justinmk Okay, I'll cut it down to one, and then axe that if it doesn't seem reliable. I was mostly struggling with a couple existing tests (on Windows and FreeBSD). The `terminal/cursor_spec.lua` tests such as `buffer cursor position is correct in terminal with number column in a line with double-cell multibyte chars and no trailing spaces` became flaky on Windows with these changes. Somehow it occasionally messes up the line numbers:
```
 ERROR    test/functional/terminal/cursor_spec.lua @ 1110: buffer cursor position is correct in terminal with number column in a line with double-cell multibyte chars and no trailing spaces, before_each
test/functional\terminal\cursor_spec.lua:848: Row 1 did not match.
Expected:
  |*{121:  1 }                                                                  |
  |*{121:  2 }                                                                  |
  |*{121:  3 }                                                                  |
  |*{121:  4 }                                                                  |
  |*{121:  5 }Entering Ex mode.  Type "visual" to go to Normal mode.            |
  |*{121:  6 }:^                                                                 |
  |{5:-- TERMINAL --}                                                        |
Actual:
  |*{121:  2 }                                                                  |
  |*{121:  3 }                                                                  |
  |*{121:  4 }                                                                  |
  |*{121:  5 }                                                                  |
  |*{121:  6 }Entering Ex mode.  Type "visual" to go to Normal mode.            |
  |*{121:  7 }:^                                                                 |
  |{5:-- TERMINAL --}                                                        |
  ```
I know very little about the internals, so I'm struggling to figure out what's going wrong there. I've been troubleshooting that on another branch.

The FreeBSD build is also failing on an existing test, but I haven't had time to look at that yet:
```
�[1m�[35mFAILED  �[0m�[0m �[36mtest/functional/terminal/tui_spec.lua�[0m @ �[36m3910�[0m: �[1mTUI bg color is properly set in a nested Nvim instance when background=light�[0m
test/functional/terminal/tui_spec.lua:3925: retry() attempts: 464
test/functional/terminal/tui_spec.lua:3926: Expected objects to be the same.
Passed in:
(table: 0x017a330cd738) {
  [1] = true
 *[2] = 'dark' }
Expected:
(table: 0x017a330cd6d8) {
  [1] = true
 *[2] = 'light' }
 ```

**Comment by kylesower** [comment]
@justinmk Alright, I initially cut it down to one test, but that one was still mildly flaky on [Ubuntu arm](https://github.com/kylesower/neovim/actions/runs/20509907994/job/58929645062) when I ran it 100 times, so I cut that one too.

File: runtime/lua/vim/_defaults.lua (hunk 6 above)
Comment (kylesower) [reply runtime/lua/vim/_defaults.lua]: Okay, apparently my logic not to delete the autocmd was there for good reason. If the autocmd deletes itself by returning true, then subsequent calls to `nvim_del_autocmd` will throw. Perhaps that's a separate bug; I don't know if that behavior is intended. I'll check the autocmd's existence more directly using `nvim_get_autocmds` to avoid the confusing logic.

File: test/functional/terminal/cursor_spec.lua [hunk 7]
```diff
@@ -845,20 +845,26 @@ describe('buffer cursor position is correct in terminal with number column', fun
...
+      {121:  5 }                                                                  |
       {121:  6 }:^                                                                 |
       {5:-- TERMINAL --}                                                        |
     ]])
   end
 
   before_each(function()
     clear()
-    command('au TermOpen * set number')
   end)
```
Comment (kylesower) [inline test/functional/terminal/cursor_spec.lua]: On Windows only, this autocmd was causing some problems. As far as I could determine, it was setting `number` on the parent nvim while the child nvim was loading Ex mode and updating the colors. These simultaneous conditions caused the numbers to sometimes update to start at 2 rather than 1. That seems to me like a minor bug when it comes to computing the numbers, but it also seems to be wholly unrelated to the purpose of this test. As such, I updated the test to be slightly more deterministic in its timing by getting rid of the `TermOpen` autocmd and manually calling `set number`. This also gets rid of the "Entering Ex Mode" prompt.

Given that the set of conditions that was causing the failure seems unrealistic (because you'd have to open the terminal and start Ex mode simultaneously with that specific autocmd), I think it's okay to update the test like this. I couldn't think of a better way. The only alternative I could come up with is disabling the `vim.wait` for the bg detection in Ex mode, but updating the logic there just to make a test work felt counterproductive.

**Comment by kylesower** [comment]
@justinmk @gpanders There's a minor amount of flakiness in the current solution caused by `tui_query_kitty_keyboard` in `src/nvim/tui/tui.c`. 
```c
static void tui_query_kitty_keyboard(TUIData *tui)
  FUNC_ATTR_NONNULL_ALL
{
  // Set the key encoding whenever the Device Attributes (DA1) response is received.
  tui->input.callbacks.primary_device_attr = tui_set_key_encoding;
  out(tui, S_LEN("\x1b[?u\x1b[c"));
}
```
Since it's also making use of DA1 as a sentinel, there's a race condition with the TermResponse autocmd. If the kitty DA1 response comes after the TermResponse autocommand is created, then it gets handled by the autocmd and the `vim.wait()` completes before we actually get a response for the BG query. That's the reason for the FreeBSD failure that's still there.

I can think of two solutions at present. The first solution is to send two DA1 requests with the BG query, then wait until we receive two DA1 responses. If we receive two, then there are two possibilities: one is from the kitty query and one is from the BG query, or both are from the BG query. The latter is what occurs in most cases since the TermResponse autocmd is typically created after the kitty DA1 response is already received/handled. I don't think we'll have the reverse problem where the DA1 response from the BG query comes before the kitty query response since the kitty query should be flushed during client initialization, so the kitty keyboard detection should still work with this solution. `runtime/plugin/osc52.lua` does use another DA1, but there it's actually using the DA1 response, so it shouldn't be an issue if it receives a leftover response from the BG query.

The second solution is to use a different sentinel query. I was thinking of a DSR `\x1b[5n`, which should have a `\x1b[0n` response. Currently, this is not sent as a TermResponse, but that's pretty easy to add in `src/nvim/tui/input.c`.

I've tried both solutions, and both seem to work. What are your thoughts?

EDIT: just to add, I think the only test where there's some remaining flakiness is the black flicker test: `has no black flicker when clearing regions during startup with termguicolors`. However, I'm not sure that there's much value in the test since the flicker still seemed to be present on master when I checked. Since I updated the code not to delete the autocmd, if we detect the kitty DA1 response first, it just means that the `vim.wait()` will finish before setting the bg, and the behavior is then similar to how it used to be, though perhaps less predictable when the bg is set.

**Comment by barrettruth** [comment]
@kylesower don't want to necropost here but this is an issue that has caught my eye.

It seems like a) you've perfectly got this down yourself and b) have done almost everything you can to get this PR ready - just waiting for further review.

Could you re-ping a maintainer or push this issue forward?

Apologies for the semi-necro-post and thanks for the contributions.

**Comment by justinmk** [comment]
> The second solution is to use a different sentinel query. I was thinking of a DSR `\x1b[5n`, which should have a `\x1b[0n` response. Currently, this is not sent as a TermResponse, but that's pretty easy to add in `src/nvim/tui/input.c`.

This sounds better to me. But both approaches are reversible decisions so we don't need to deliberate on it. The main priority is : 

- a reliable test that can check for regressions so we can try other approaches later if necessary
    - side note:  we *already* have an existing bg-detection test(s), so just update them don't add new ones. (current PR achieves this ✅)
- avoid convoluated, spread-out code. (current PR achieves this ✅)

**Comment by kylesower** [comment]
@barrettruth Thanks for the reminder. I've made the necessary changes on another branch, but need to fix yet another issue with the Windows tests.

**Comment by barrettruth** [comment]
@kylesower out of curiosity, does this pr make `nvim -c checkhealth`, for example, immediately yield the appropriate background color in the ui? currently the background waits until `:checkhealth` finishes before it is set.

File: runtime/lua/vim/_core/defaults.lua [hunk 8]
```diff
@@ -850,13 +867,32 @@ do
...
+      -- and we don't have to keep waiting for a bg color response.
+      -- #32109
+      local osc11 = '\027]11;?\007'
+      local dsr = '\027[5n'
+      vim.api.nvim_ui_send(osc11 .. dsr)
+
+      -- Wait until detection of OSC 11 capabilities is complete to
+      -- ensure background is automatically set before user config.
+      vim.wait(100, function()
+        return did_dsr_response
```
Comment (justinmk) [inline runtime/lua/vim/_core/defaults.lua]: Should we show a warning if we never get the response?

File: src/nvim/tui/input.c [hunk 9]
```diff
@@ -726,7 +726,23 @@ static void handle_unknown_csi(TermInput *input, const TermKeyKey *key)
...
+      ADD_C(args, STATIC_CSTR_AS_OBJ("termresponse"));
+
+      StringBuilder response = KV_INITIAL_VALUE;
+      kv_printf(response, "\x1b[%dn", arg);
+      ADD_C(args, STRING_OBJ(cbuf_as_string(response.items, response.size)));
+
+      rpc_send_event(ui_client_channel_id, "nvim_ui_term_event", args);
+      kv_destroy(response);
+    } else if (nparams == 2) {
       int args[2];
```
Comment (justinmk) [inline src/nvim/tui/input.c:754]: in the nparams=1 case you noted `ECMA-48 DSR`. is there a note we can add for the nparams=2 case?

File: test/functional/terminal/tui_spec.lua [hunk 10]
```diff
@@ -2903,6 +2908,7 @@ describe('TUI', function()
         'sleep 10',
       }, {
         term = true,
+        env = { VIMRUNTIME = os.getenv('VIMRUNTIME') },
```
Comment (justinmk) [inline test/functional/terminal/tui_spec.lua:2911]: this gets VIMRUNTIME from the test runner, it probably is more intended to get it from the test Nvim, right?
```suggestion
        env = { VIMRUNTIME = fn.getenv('VIMRUNTIME') },
```

**Review by justinmk — APPROVED** [review]
LGTM after comments, then we can merge and get some bake-time before 0.12 release.

File: test/functional/terminal/tui_spec.lua (hunk 10 above)
Comment (zeertzjq) [reply test/functional/terminal/tui_spec.lua:2911]: Why is one "more intended" than the other?

File: runtime/lua/vim/_core/defaults.lua (hunk 8 above)
Comment (kylesower) [reply runtime/lua/vim/_core/defaults.lua]: I think we should. That will help us see if any problems arise (e.g. people noticing slow startup times) and adjust accordingly.

**Comment by kylesower** [comment]
> @kylesower out of curiosity, does this pr make `nvim -c checkhealth`, for example, immediately yield the appropriate background color in the ui? currently the background waits until `:checkhealth` finishes before it is set.

@barrettruth I think what you're observing may be a separate issue. I tried running `nvim --clean -c checkhealth`, and I see it swap from my terminal colors to the default color scheme after the healthcheck completes. That makes it seem like it's transitioning from `notermguicolors` -> `termguicolors`. However, what I can say is that `nlua_init_defaults()` runs before `exe_commands()` in `main.c`, so I believe the background variable should at least be set correctly before the healthcheck starts.

File: test/functional/terminal/tui_spec.lua (hunk 10 above)
Comment (kylesower) [reply test/functional/terminal/tui_spec.lua:2911]: I honestly don't know; I was resolving a bizarre issue where Windows was putting a path starting in `C:\Program Files (x86)\` at the start of the runtime path, causing an error. I don't see how my changes could have caused that problem, and I don't have a Windows system to test on. I also still don't understand much of the testing structure, but I see we have 2 instances of `fn.getenv` in the tests and far more of `os.getenv`; I just took what was used in the file already.

File: runtime/lua/vim/_core/defaults.lua (hunk 8 above)
Comment (kylesower) [reply runtime/lua/vim/_core/defaults.lua]: Updated: [728485b](https://github.com/neovim/neovim/pull/37075/changes/728485bd9551e7e7de75d5179627174a96d239f4)

File: src/nvim/tui/input.c (hunk 9 above)
Comment (kylesower) [reply src/nvim/tui/input.c:754]: Updated: [728485b](https://github.com/neovim/neovim/pull/37075/changes/728485bd9551e7e7de75d5179627174a96d239f4)

File: runtime/lua/vim/_core/defaults.lua [hunk 11]
```diff
@@ -830,15 +842,20 @@ do
...
+              vim.api.nvim_set_option_value('background', bg, {})
+
+              -- Ensure OptionSet still triggers when we set the background during startup
+              if vim.v.vim_did_enter == 0 then
+                vim.api.nvim_create_autocmd('VimEnter', {
+                  group = group,
+                  once = true,
+                  nested = true,
+                  callback = function()
+                    vim.api.nvim_exec_autocmds('OptionSet', {
```
Comment (justinmk) [inline runtime/lua/vim/_core/defaults.lua:854]: > Note: To preserve the existing behavior ... this triggers OptionSet manually on VimEnter ... However, I'm unsure if this behavior is truly desired given that the documentation says OptionSet is triggered "After setting an option (except during |startup|)."

Thanks for noting that. It's probably safe to drop this, as a followup PR. *Before* your fix (this PR), it was needed as a workaround since user config may not see the "correct" 'background' during startup. After your fix, that's no longer necessary.

Also, this `nvim_exec_autocmds('OptionSet')` doesn't set `v:option_new` etc so it's not really a full replacement anyway. (We have a backlog item to enhance `nvim_exec_autocmds` so that it can set event-args.)
