### PR TITLE
fix(lsp): schedule removal of client object

### LINKED ISSUE #20125: 'vim.lsp.get_client_by_id()' doesn't work inside on LspDetach
### Neovim version (nvim -v)

0.8.0 ead524656dc1664622f80509a983519a190ca48a

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Ubuntu 20.04

### Terminal name/version

st 0.8.5

### $TERM environment variable

st-256color

### Installation

Neovim PPA unstable

### How to reproduce the issue

cd /var/tmp/lsp_detach_issue
nvim --clean -u lsp_detach_issue.lua get_current_time.py
:PyrightStop

### Expected behavior

The message "LspDetach: LSP client is pyright." is printed.

### Actual behavior

The message "LspDetach: LSP client is nil." is printed.

### PR DESCRIPTION
**Pull request by gpanders**
The execution of the LspDetach autocommands in the LSP client's on_exit
function are scheduled on the event loop to avoid making API calls in a
fast context; however, this means that by the time the LspDetach
autocommands finally run the client object has already been deleted.

To address this, we also schedule the deletion of the client on the
event loop so that it is guaranteed to occur after all of the LspDetach
autocommands have fired.

Closes #20125.

### CODE REVIEW

**Review by mfussenegger — APPROVED** [review]

File: runtime/lua/vim/lsp.lua [hunk 1]
```diff
@@ -1147,20 +1147,23 @@ function lsp.start_client(config)
...
     end
-    local client = active_clients[client_id] and active_clients[client_id]
-      or uninitialized_clients[client_id]
-    active_clients[client_id] = nil
-    uninitialized_clients[client_id] = nil
+
+    -- Schedule the deletion of the client object so that it exists in the execution of LspDetach
+    -- autocommands
+    vim.schedule(function()
+      local client = active_clients[client_id] and active_clients[client_id]
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp.lua:1162]: The client is used outside the schedule.  Is this correct?

Comment (gpanders) [reply runtime/lua/vim/lsp.lua:1162]: Yes, good catch. I'll move the block below into the schedule as well.

**Review by glepnir — APPROVED** [review]
