### PR TITLE
fix(lsp): account for initializing servers in vim.lsp.start

### LINKED ISSUE #19326: lsp: vim.lsp.start() should take starting clients into account
### Neovim version (nvim -v)

0.8.0-pre 95c65a6b221fe6e1cf91e8322e7d7571dc511a71

### Vim (not Nvim) behaves the same?

No, Vim does not have LSP builtin

### Operating system/version

Debian testing

### Terminal name/version

hterm

### $TERM environment variable

hterm-256color

### Installation

Build from HEAD

### How to reproduce the issue

Given that the problem is easy to understand from the source, I'm not giving a full reproduction with an LSP config et al. If this is still required/helpful, please say so.

Assumption: one has a config where an LSP server is started on `autocmd FileType` using `vim.lsp.start()`.

```
$ nvim -O file1.py file2.py
```

### Expected behavior

I want only a single LSP process for both files, given that they (in my configuration) have the same client name and root_dir.

### Actual behavior

Two LSP processes get started, despite the root_dir and server name for the two files being the same.

The reason this happens is due to `vim.lsp.start` using `vim.lsp.get_active_clients()`

https://github.com/neovim/neovim/blob/5c3bbb67e7c59b2fa18e37fdd9845a0e7e3381db/runtime/lua/vim/lsp.lua#L742

Which only gets updated once the LSP server is fully up and running: 

https://github.com/neovim/neovim/blob/5c3bbb67e7c59b2fa18e37fdd9845a0e7e3381db/runtime/lua/vim/lsp.lua#L1184,L1185

This behaviour of `vim.lsp_get_active_clients()` appears to be on purpose. So perhaps `vim.lsp.start` should use something else.

### PR DESCRIPTION
**Pull request by aktau**
Fixes #19326 (see that issue for more context).

I've tested locally that this fixes the issue, in that `nvim -O ...` with N files that could reuse LSP clients no longer spawns N LSP processes.

### CODE REVIEW

**Comment by aktau** [comment]
(Please also see https://github.com/neovim/neovim/pull/19328 to solve my other problem with the `vim.lsp.start()` API. I have no idea why no review gets requested on that one.)

File: runtime/lua/vim/lsp.lua [hunk 1]
```diff
@@ -739,10 +739,12 @@ function lsp.start(config, opts)
     end
   config.name = config.name or (config.cmd[1] and vim.fs.basename(config.cmd[1])) or nil
   local bufnr = api.nvim_get_current_buf()
-  for _, client in pairs(lsp.get_active_clients()) do
-    if reuse_client(client, config) then
-      lsp.buf_attach_client(bufnr, client.id)
-      return client.id
+  for _, clients in ipairs({uninitialized_clients, lsp.get_active_clients()}) do
```
Comment (smjonas) [inline runtime/lua/vim/lsp.lua:742]: This creates a list with two entries, I think you need to use `unwrap` or something equivalent here. Also, `pairs` seemed correct.

Comment (aktau) [reply runtime/lua/vim/lsp.lua:742]: I intended it to be a list with two entries.

I'm not sure how unwrap would help the logic. Could you clarify?

Comment (smjonas) [reply runtime/lua/vim/lsp.lua]: Never mind, it makes total sense now :D

**Review by gpanders — APPROVED** [review]
