### PR TITLE
fix(mswin): UI may hang on exit

### LINKED ISSUE #33019: Windows Terminal "crash" (hang/freeze) on exit after using Neovim for a few minutes
continued from #8587 as requested by @justinmk ...

# Problem

hang/delay on exit (on Windows), bisected to https://github.com/neovim/neovim/commit/b360c0608556232c8ddb7ecc9cd26e68584bee76

<details>
<summary>old details</summary>

Here are the original comments for context:

> FYI I am on newest nightly (as of this morning) and over the last couple weeks I have noticed new "bad behavior" on exit of neovim ~~that is related to this shada issue (but I cannot surely tie it to shada, unlike above comments)~~.
> 
> Primarily it happens when I have a few buffers open and after 10 minutes+ of neovim usage (does not seem to happen if opening and closing neovim "quickly"). I typically use `:qa` to close neovim so this is when it is happening.
> 
> I am getting similar behavior as the Windows shada issues above except for it completely freezes/"crashes" my terminal on exit, unlike the shada issue above where it creates tmp shada file and keeps my terminal "painted" with whatever the last "screen" was in Neovim and I have to do a "clear" in my terminal to clear it... this "new" issue I am experiencing seems like a straight crash because the last neovim screen is still painted as above, but my terminal hangs/freezes so I cannot do "clear" or anything and have to close my terminal tab and re-open.
>
> I do not know the exact Nightly build that this started happening as I do not update nightly every day (every week or two maybe) but I do know this behavior started in the last month or so. 

 _Originally posted by @GitMurf in [#8587](https://github.com/neovim/neovim/issues/8587#issuecomment-2701340959)_

> RE: https://github.com/neovim/neovim/issues/8587#issuecomment-2701340959 (above a couple comments)
> 
> @justinmk I have done a fairly extensive attempt at a git bisect of building Neovim-nightly (not easy as this requires using Neovim a bit to cause the hang on exit) and I have determined that the issue described above seems to start at this commit: 4c2d14a
> 
> I have confirmed several times that going to the commit just before it (ae2fd91) does not encounter this issue... and when I again flip back to 4c2d14a I experience the issue again. Have tried this cycle several times.
> 
> To add to my more detailed description above (https://github.com/neovim/neovim/issues/8587#issuecomment-2701340959), it seems that it does not necessarily "fully" freeze/crash every time on exit, but depending on the scenario/situation, if you leave the terminal open for long enough, it often eventually fully exits and gives you back control of your terminal (clears the nvim painted last screen). I have watched it for 15 minutes and still had it "froze", but then left it over night and by the morning it had properly exited and the terminal screen "re-painted" outside of nvim.
> 
> I am less confident now that this relates to the same Shada issues as above (similar symptoms but I do not think this is necessarily related to Shada anymore), but it is very similar.

 _Originally posted by @GitMurf in [#8587](https://github.com/neovim/neovim/issues/8587#issuecomment-2742671422)_

> Let's discuss that in a new issue, with repro steps. Can't see how a treesitter bump relates to this issue. 

 _Originally posted by @justinmk in [#8587](https://github.com/neovim/neovim/issues/8587#issuecomment-2742814417)_

</details>

### PR DESCRIPTION
**Pull request by justinmk**
Problem:
On Windows, since b360c0608556, UI may hang on exit. #33019

Solution:
Restore the hack in `on_proc_exit`, until we can figure out why `rpc_close` is not called in the UI client when the server closes the channel.

fix #33019

### CODE REVIEW

File: src/nvim/event/proc.c [hunk 1]
```diff
@@ -437,6 +437,17 @@ static void on_proc_exit(Proc *proc)
   Loop *loop = proc->loop;
   ILOG("child exited: pid=%d status=%d" PRIu64, proc->pid, proc->status);
 
+#ifdef MSWIN
+  // XXX: This assumes the TUI never spawns any other processes...?
+  // TODO(justinmk): figure out why rpc_close sometimes(??) isn't called, then remove this jank.
+  // Theories:
+  // - EOF not received in receive_msgpack, then doesn't call chan_close_on_err().
+  // - proc_close_handles not tickled by ui_client.c's LOOP_PROCESS_EVENTS?
```
Comment (justinmk) [inline src/nvim/event/proc.c:445]: For reference: https://github.com/neovim/neovim/issues/33019#issuecomment-2749523625 confirmed that the `nvim --embed` server terminates, only the UI process hangs.
