### PR TITLE
[RFC] tui: fix resize and use BCE more often

### LINKED ISSUE #7861: TUI: corrupt display after resize + termguicolors, sign column, colorscheme
- `nvim --version`: NVIM v0.2.3-448-gc06995b34
- Vim (version: 8.0) does not appear to have this problem.
- Operating system/version: Arch Linux
- Terminal name/version: Gnome terminal 3.26.2 (also occurs on termite and urxvt)
- `$TERM`: xterm-256color

### Steps to reproduce:

To summarize, I believe this only occurs when all four of these conditions are met:

* Truecolor is enabled
* A colorscheme is set
* The sign column is showing (sample vimrc shows a dummy one, I also reproduced with gitgutter and ale)
* Commands are loaded from file (won't work if entered in command mode manually)
* Window resized

In detail:

1) Write this to a separate vimrc named `bug-vimrc` or something:

```vim
set termguicolors
colorscheme desert
sign define dummy
execute 'sign place 9999 line=1 name=dummy buffer=' . bufnr('')
```

2) Open it with `nvim -u bug-vimrc --noplugin`
3) Enter the following into the buffer:

```
short line

loooooooooong line
```

4) Place your cursor on the middle line
5) Shrink the size of the terminal horizontally (perhaps by opening a window on the right if you use a tiling WM)
6) Watch the first line in the buffer become corrupted

### Expected behaviour
First line stays the same.

### PR DESCRIPTION
**Pull request by bfredl**
Fixes #7861, but currently only on BCE terminals. Also resizing the terminal is _a lot_ smoother, as we don't literally need to fill the screen with space chars one at a time.

Problem is nvim very aggressively disables BCE, even if the terminal supports it. Though you can set `XTERM_VERSION=xx` to say "trust me, I use a non-broken terminal emulator" and it works with at least pangoterm (libvterm) and gnome-terminal (libvte).

What are these terminals that claim to be xterm but doesn't actually support BCE? I tried to navigate the tangle of interlinked issues but have a hard time to extract a list of terminals that were broken, and more importantly remain broken _today_. The most common complaints seem to be about conhost/WSL, and they claim to have fixed their stuff: https://github.com/Microsoft/WSL/issues/1706. Could we switch from (ridiculously narrow) whitelist to blacklist?

- [x] clear the screen correctly on BCE terminal 
- [x]  clear the screen correctly on non-BCE terminal
- [ ] detect BCE more reasonably

### CODE REVIEW

**Comment by bfredl** [comment]
Added a quickfix for invalid first line in non-BCE terminal, so this now actually fixes #7861. This case could be optimized more as I noted before https://github.com/neovim/neovim/issues/7861#issuecomment-409314118, but before spending a lot of time on this it would be good to know the true distribution of BCE vs non-BCE capable terminals.

**Comment by justinmk** [comment]
> Could we switch from (ridiculously narrow) whitelist to blacklist?

The problem is ssh/screen/tmux. For example [kitty won't support BCE](https://github.com/kovidgoyal/kitty/issues/160#issuecomment-346330445). If the user doesn't have kitty's terminfo on the remote system, the remote terminfo often claims BCE support, then Nvim looks broken.

See also https://github.com/neovim/neovim/pull/7624  (though it sounds like you reviewed it already).

> it would be good to know the true distribution of BCE vs non-BCE capable terminals.

The problem is how to detect them. We were depending on terminfo and getting lies.

**Comment by bfredl** [comment]
But kitty calls itself `xterm-kitty`, we can easily detect that. And `screen`/`tmux` calls itself `screen` and not `xterm`. I know termcap is a bunch of lies, but I would expect a terminal that calls itself `xterm-256color` and nothing else to behave like an xterm, termcap doesn't need to enter that equation at all.

**Comment by justinmk** [comment]
So we won't ever use BCE for screen/tmux (except for `XTERM_VERSION`), correct?

No objection to use TERM to detect kitty, though I would suggest that the decision be reflected by `nvim -V3`.

**Comment by justinmk** [comment]
> So we won't ever use BCE for screen/tmux (except for XTERM_VERSION)

Or if we implement termresponse detection https://github.com/neovim/neovim/issues/7490

**Comment by justinmk** [comment]
[This comment](https://github.com/kovidgoyal/kitty/issues/160#issuecomment-346470545) implies that tmux/screen don't support BCE. See also https://github.com/tmux/tmux/issues/109#issuecomment-140371375

**Comment by bfredl** [comment]
Then tmux is no problem: when TERM is `screen-*`, we don't support bce just like now. The change we should do is just: if a terminal calls itelf xterm (and provides no extra info like VTEVERSION or similar, where we can blacklist if needed), we should expect it to behave like an xterm.

**Comment by bfredl** [comment]
Allowing BCE also for "false" xterm is the conservative change. But beyond that, what are the terminals for which terminfo is actually lying? (not supporting BCE is fine as long the terminal is honest about it...) Is the terminfo for `screen` incorrect? If not, what is?

Also, in my empirical experiments, kitty actually seems to support BCE for full-screen clear, but not for scrolled-in area. But maybe it is not worth a special-case?

**Comment by bfredl** [comment]
> For this item, are you thinking about term response / DECRQSS or something else?

I don't know about DECRQSS and how reliable it is, but if it works it can of course be used. I think I would start with: basically trust terminfo again, but add exceptions for known terminals (starting with kitty). If this becomes unmanagable we can switch strategy.

**Comment by justinmk** [comment]
Let's do it.

**Comment by bfredl** [comment]
Ok, I added screen, tmux and kitty exceptions, should cover the most cases of broken terminfo or tmux-over-ssh (though it works on my computer without any extra check :P).

**Review by justinmk — APPROVED** [review]

**Comment by kovidgoyal** [comment]
FYI: for kitty you can use DECCARA https://sw.kovidgoyal.net/kitty/protocol-extensions.html#setting-text-styles-colors-in-arbitrary-regions-of-the-screen much more powerful than bce allows you to set arbitrary text attributes in arbitrary regions of the screen with single escape code.

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -1437,8 +1450,8 @@ static void patch_terminfo_bugs(TUIData *data, const char *term,
     }
   }
 
-  if (!true_xterm) {
-    // Cannot trust terminfo; safer to disable BCE. #7624
+  if (tmux || screen || kitty) {
+    // Disable BCE in some cases we know it is not working. #8806
     unibi_set_bool(ut, unibi_back_color_erase, false);
```
Comment (justinmk) [inline src/nvim/tui/tui.c]: 👍  Since this drives the `TUIData.bce` value,   `nvim -V3` should correctly reflect whether BCE is in effect.
