### PR TITLE
fix(diagnostics): separate pull/push namespaces 

### LINKED ISSUE #37936: lsp: push and pull diagnostics override each other
### Problem

Pull diagnostics (from `textDocument/diagnostic`) and push diagnostics (from `textDocument/publishDiagnostics`) use the same namespace, which is a problem when using language servers that publish two different sets of diagnostics on push vs pull, like rust-analyzer (see https://github.com/rust-lang/rust-analyzer/issues/18709#issuecomment-2551394047).

A `git bisect` pointed to https://github.com/neovim/neovim/pull/37221 as the first offending commit.

### Steps to reproduce

- `cargo new --lib repro && cd repro`
- create this `repro.lua`:

```lua
vim.lsp.config("rust_analyzer", {
  cmd = { "rust-analyzer" },
  root_markers = { "Cargo.toml", ".git" },
})

vim.lsp.enable("rust_analyzer")
```
- `printf 'fn foo() {}\n' > ./src/lib.rs`
- `nvim -u repro.lua ./src/lib.rs`
- ‼️ the diagnostic is shown, then immediately removed:

https://github.com/user-attachments/assets/3a4bc8ab-05c1-4df9-8351-aa144620420e

### Expected behavior

The diagnostic is not removed.

### Nvim version (nvim -v)

NVIM v0.12.0-nightly+29a46a1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 10.15

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

Nix flake

### PR DESCRIPTION
**Pull request by noib3**
Problem: https://github.com/neovim/neovim/issues/37936

Solution: see PR title

Closes https://github.com/neovim/neovim/issues/37936.

### CODE REVIEW

File: runtime/lua/vim/lsp/diagnostic.lua [hunk 1]
```diff
@@ -193,8 +193,14 @@ function M.get_namespace(client_id, is_pull)
 
   local client = lsp.get_client_by_id(client_id)
   if is_pull then
-    local key = ('%d'):format(client_id)
-    local name = ('nvim.lsp.%s.%d'):format(client and client.name or 'unknown', client_id)
+    local server_id =
+      vim.tbl_get((client or {}).server_capabilities or {}, 'diagnosticProvider', 'identifier')
```
Comment (tris203) [inline runtime/lua/vim/lsp/diagnostic.lua]: We shouldn't do this because of dynamic registrations

Comment (noib3) [reply runtime/lua/vim/lsp/diagnostic.lua]: Right. Should be fixed by 9b7ea85fc1f3 where I'm using a caller-provided pull request ID.

**Review by MariaSolOs — APPROVED** [review]

**Comment by MariaSolOs** [comment]
@noib3 you need to run `make doc` to update documentation.

File: runtime/lua/vim/lsp/diagnostic.lua [hunk 2]
```diff
@@ -188,13 +188,19 @@ local client_pull_namespaces = {}
...
-function M.get_namespace(client_id, is_pull)
+---@param pull_id string? Pull diagnostics provider identifier
+function M.get_namespace(client_id, is_pull, pull_id)
   vim.validate('client_id', client_id, 'number')
 
   local client = lsp.get_client_by_id(client_id)
   if is_pull then
-    local key = ('%d'):format(client_id)
-    local name = ('nvim.lsp.%s.%d'):format(client and client.name or 'unknown', client_id)
+    local provider_id = type(pull_id) == 'string' and pull_id or 'nil'
```
Comment (tris203) [inline runtime/lua/vim/lsp/diagnostic.lua:202]: I think this would be clearer with a vim.validate call and then can just be
local provider_id = pull_id or 'nil'

Comment (noib3) [reply runtime/lua/vim/lsp/diagnostic.lua:202]: done

File: runtime/doc/lsp.txt [hunk 3]
```diff
@@ -2074,14 +2074,15 @@ from({diagnostics})                                *vim.lsp.diagnostic.from()*
...
-get_namespace({client_id}, {is_pull})
+get_namespace({client_id}, {is_pull}, {pull_id})
     Get the diagnostic namespace associated with an LSP client
     |vim.diagnostic| for diagnostics
 
     Parameters: ~
       • {client_id}  (`integer`) The id of the LSP client
       • {is_pull}    (`boolean?`) Whether the namespace is for a pull or push
                      client. Defaults to push
+      • {pull_id}    (`string?`) Pull diagnostics provider identifier
```
Comment (justinmk) [inline runtime/doc/lsp.txt]: if we add this field can we drop `is_pull`? and for back-compat, declare `is_pull` like this (it's safe to rename it):

    pull_id: boolean?|string?

File: test/functional/plugin/lsp/diagnostic_spec.lua [hunk 4]
```diff
@@ -351,6 +351,89 @@ describe('vim.lsp.diagnostic', function()
...
+          pull_ns
+      end)
+
+      eq(1, push_ns_count)
+      eq(0, pull_ns_count)
+      eq(1, all_diags_count)
+      neq(push_ns, pull_ns)
+    end)
+
+    it('uses pull request identifier to isolate pull diagnostic namespaces', function()
```
Comment (justinmk) [inline test/functional/plugin/lsp/diagnostic_spec.lua]: using the same "nonce" helps discovery

```suggestion
    it('uses pull_id to isolate pull diagnostic namespaces', function()
```

**Review by justinmk — APPROVED** [review]

File: runtime/doc/lsp.txt (hunk 3 above)
Comment (noib3) [reply runtime/doc/lsp.txt]: We can currently end up with `is_pull=true` and `pull_id=nil`. How would that work if we collapsed them into a single field? Would the caller be expected to pass `'nil'` in that case?

Comment (justinmk) [reply runtime/doc/lsp.txt]: Is `is_pull=true + pull_id=nil` actually useful or just legacy? Legacy callers will pass `pull_id=true` and we can simply handle that for back-compat.

Comment (noib3) [reply runtime/doc/lsp.txt]: Addressed this in 88a6c29cf05f (I'll squash the PR back into a single commit if necessary).

File: runtime/lua/vim/lsp/diagnostic.lua [hunk 5]
```diff
@@ -187,14 +187,20 @@ local client_pull_namespaces = {}
 --- Get the diagnostic namespace associated with an LSP client |vim.diagnostic| for diagnostics
 ---
 ---@param client_id integer The id of the LSP client
----@param is_pull boolean? Whether the namespace is for a pull or push client. Defaults to push
-function M.get_namespace(client_id, is_pull)
+---@param pull_id (boolean|string)? Pull diagnostics provider identifier
+function M.get_namespace(client_id, pull_id)
   vim.validate('client_id', client_id, 'number')
+  vim.validate('pull_id', pull_id, { 'boolean', 'string' }, true)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/diagnostic.lua:195]: let's give ourselves a reminder to update the type decl later. 

note: using version=0.14 avoids bothering people until after 0.12 is released.

```lua
if type(pull_id) == 'boolean' then
  vim.deprecate(
    'get_namespace(pull_id:boolean)',
    'get_namespace(pull_id:string)',
    '0.14'
  )
end
```

File: runtime/lua/vim/lsp/diagnostic.lua [hunk 6]
```diff
@@ -187,14 +187,20 @@ local client_pull_namespaces = {}
 --- Get the diagnostic namespace associated with an LSP client |vim.diagnostic| for diagnostics
 ---
 ---@param client_id integer The id of the LSP client
----@param is_pull boolean? Whether the namespace is for a pull or push client. Defaults to push
-function M.get_namespace(client_id, is_pull)
+---@param pull_id (boolean|string)? Pull diagnostics provider identifier
```
Comment (justinmk) [inline runtime/lua/vim/lsp/diagnostic.lua]:
```suggestion
---@param pull_id (boolean|string)? (default: nil) Pull diagnostics provider id
---               (indicates "pull" client), or `nil` for a "push" client.
```

File: test/functional/plugin/lsp/diagnostic_spec.lua [hunk 7]
```diff
@@ -351,6 +351,89 @@ describe('vim.lsp.diagnostic', function()
       eq('Pull Diagnostic', diags[1].message)
     end)
 
+    it('does not clear push diagnostics when pull diagnostics are empty', function()
```
Comment (justinmk) [inline test/functional/plugin/lsp/diagnostic_spec.lua]:
```suggestion
    it('preserves push diagnostics when pull diagnostics are empty', function()
```

**Review by justinmk — APPROVED** [review]

File: test/functional/plugin/lsp/diagnostic_spec.lua (hunk 7 above)
Comment (noib3) [reply test/functional/plugin/lsp/diagnostic_spec.lua]: 256fe431f454964b62f71106b698e73a733741f1

File: runtime/lua/vim/lsp/diagnostic.lua (hunk 6 above)
Comment (noib3) [reply runtime/lua/vim/lsp/diagnostic.lua]: 256fe431f454964b62f71106b698e73a733741f1

File: runtime/lua/vim/lsp/diagnostic.lua (hunk 5 above)
Comment (noib3) [reply runtime/lua/vim/lsp/diagnostic.lua:195]: 256fe431f454964b62f71106b698e73a733741f1

**Comment by tris203** [comment]
I think this looks good to me too
