### PR TITLE
screen.c: fix display of signcolumn=auto in diffs

### LINKED ISSUE #13555: signcolumn > 1 creates a gap in diffmode with deleted lines
with 5ce328df401bc5cafd66caeb265835b939028b7f

### Steps to reproduce using `nvim -u NORC`

Create test1.txt and test2.txt a copy of test1.txt with a deleted line in the middle.
```
bin/nvim -u NORC  --cmd "setglobal signcolumn=yes:4" --cmd "set diffopt+=foldcolumn:0" -d ../test1.txt ../test2.txt
```

CC @shougo as I suspect it's linked to get_sign_display_info.

### Expected behaviour

20201219_03h07m47s_grim

### PR DESCRIPTION
**Pull request by teto**
sign_id was not reset when filler lines were involved, thus causing a
bad alignment between columns.

fixes https://github.com/neovim/neovim/issues/13555

### CODE REVIEW

**Review by vigoux — APPROVED** [review]

File: src/nvim/screen.c [hunk 1]
```diff
@@ -4347,6 +4347,10 @@ void screen_adjust_grid(ScreenGrid **grid, int *row_off, int *col_off)
 // Get information needed to display the sign in line 'lnum' in window 'wp'.
 // If 'nrcol' is TRUE, the sign is going to be displayed in the number column.
 // Otherwise the sign is going to be displayed in the sign column.
+//
+// @param count max number of signs
+// @param[out] n_extrap number of characters from pp_extra to display
+// @param[out] sign_idxp Index of the displayed sign
```
Comment (teto) [inline src/nvim/screen.c:4353]: it's `in` too

Comment (vigoux) [reply src/nvim/screen.c:4353]: Oh yes, missed that one
