### PR TITLE
[RFC] Trigger TabNew before TabEnter

### LINKED ISSUE #4333: TabNew triggered after TabEnter
- Neovim version: NVIM v0.1.3-211-g47b529
- Operating system: Ubuntu 14.04.3 LTS
- Terminal emulator: Gnome-terminal

### Actual behaviour
TabNew is triggered after TabEnter

### Expected behaviour
According to the documentation, TabNew should be triggered before TabEnter. It also makes more sense so you can do initialisation work in TabNew?

### Steps to reproduce
:au TabEnter * echom "TabEnter"
:au TabNew * echom "TabNew"
:tabnew

#### Output:
TabEnter
TabNew

#### Expected output:
TabNew
TabEnter

### PR DESCRIPTION
**Pull request by mhinz**
This is supposed to fix https://github.com/neovim/neovim/issues/4333

CC @fmoralesc

### CODE REVIEW

**Comment by mhinz** [comment]
Putting `TabNew` into `win_new_tabpage()` requires adding an argument to it, but is much better than the alternative: Getting `TabEnter` out of `win_new_tabpage()` and adding it to multiple places (complicated by the fact that `win_new_tabpage()` is often used in `if` or `return` statements.)

File: src/nvim/window.c [hunk 1]
```diff
@@ -2973,6 +2973,7 @@ int win_new_tabpage(int after)
     return FAIL;
   }
   curtab = newtp;
+  apply_autocmds(EVENT_TABNEW, arg, arg, false, curbuf);
 
   /* Create a new empty window. */
   if (win_alloc_firstwin(tp->tp_curwin) == OK) {
```
Comment (fmoralesc) [inline src/nvim/window.c]: So TabNew will trigger even if we fail to allocate a new window?

Comment (fmoralesc) [inline src/nvim/window.c]: Yes, that seems better to me. After all, the success condition of `win_new_tabpage` only happens within that branch, it would be weird to trigger the event when the function fails (not sure how likely that is though).

Comment (mhinz) [inline src/nvim/window.c]: If I move it into the block, I can move it down to the bottom right way. Should we simply make it like this:

```vim
    apply_autocmds(EVENT_TABNEW, filename, filename, false, curbuf);
    apply_autocmds(EVENT_TABENTER, NULL, NULL, FALSE, curbuf);
    apply_autocmds(EVENT_WINENTER, NULL, NULL, FALSE, curbuf);
```
?

Comment (fmoralesc) [inline src/nvim/window.c]: I think so :+1:

Comment (mhinz) [inline src/nvim/window.c]: (Note that I also switched `TabEnter` and `WinEnter` above. That order makes more sense to me.)

Comment (fmoralesc) [inline src/nvim/window.c]: Yes, that makes sense to me too.

Comment (mhinz) [inline src/nvim/window.c]: Uhm, okay. Switching `TabEnter` and `WinEnter` is worth an own PR.. `:h TabEnter` explicitly mentions that `TabEnter` comes after `WinEnter` and it breaks a test, too. I leave it away for now.

**Comment by justinmk** [comment]
> Switching TabEnter and WinEnter is worth an own PR.. :h TabEnter explicitly mentions that TabEnter comes after WinEnter and it breaks a test, too.

We can't change that, it would break Vim-compat.

**Comment by mhinz** [comment]
> We can't change that, it would break Vim-compat.

Oh, of course. Thanks for reminding.

Update: Now I also extended an existing test to take `TabNew` into account.

**Comment by fmoralesc** [comment]
:+1:

**Comment by mhinz** [comment]
Thanks for your comments. :)

File: test/functional/legacy/062_tab_pages_spec.lua [hunk 2]
```diff
@@ -139,6 +139,7 @@ describe('tab pages', function()
 	  autocmd TabLeave * :call add(g:r, 'TabLeave')
 	  autocmd WinLeave * :call add(g:r, 'WinLeave')
 	  autocmd BufLeave * :call add(g:r, 'BufLeave')
+	  autocmd TabNew   * :call add(g:r, 'TabNew')
```
Comment (justinmk) [inline test/functional/legacy/062_tab_pages_spec.lua]: We have `test/functional/autocmd/tabnew_spec.lua` and TabNew is not part of legacy Vim, so it should really be tested there.

Comment (mhinz) [inline test/functional/legacy/062_tab_pages_spec.lua]: Hmpf, right. I'll take this as an excuse to clean up `tabnew_spec.lua`.
