### PR TITLE
fix(channel): closing socket with pending writes leaks memory

### LINKED ISSUE #36392: Memory leak on SIGHUP with remote client attached
### Problem

Memory leak on SIGHUP with remote client attached.

The following change is need to find the actual position of the leak:
```diff
diff --git a/src/nvim/memory.c b/src/nvim/memory.c
index 0623834fe4..b025036145 100644
--- a/src/nvim/memory.c
+++ b/src/nvim/memory.c
@@ -674,7 +674,7 @@ void *mergesort_list(void *head, MergeSortGetFunc get_next, MergeSortSetFunc set
   return head;
 }
 
-#define REUSE_MAX 4
+#define REUSE_MAX 0
 
 static struct consumed_blk *arena_reuse_blk;
 static size_t arena_reuse_blk_count = 0;
```

ASAN log after applying the change above:
```

=================================================================
==2089849==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4096 byte(s) in 1 object(s) allocated from:
    #0 0x5567b58d2b05 in malloc (**/build/bin/nvim+0xd95b05) (BuildId: 81a1dbb637804ae755a5f6298ff4cf1ae5401cd5)
    #1 0x5567b65418c4 in try_malloc **/src/nvim/memory.c:113:15
    #2 0x5567b6541b24 in xmalloc **/src/nvim/memory.c:147:15
    #3 0x5567b65445cd in alloc_block **/src/nvim/memory.c:717:12
    #4 0x5567b5fcfbf3 in rstream_init **/src/nvim/event/rstream.c:37:20
    #5 0x5567b5bc89c0 in channel_from_connection **/src/nvim/channel.c:508:3
    #6 0x5567b6610590 in connection_cb **/src/nvim/msgpack_rpc/server.c:280:3
    #7 0x5567b5fd88fb in connection_event **/src/nvim/event/socket.c:172:3
    #8 0x5567b5fd6c4e in connection_cb **/src/nvim/event/socket.c:178:3
    #9 0x5567b7137375 in uv__server_io **/.deps/build/src/libuv/src/unix/stream.c:528:3
    #10 0x5567b7141cac in uv__io_poll **/.deps/build/src/libuv/src/unix/linux.c:1565:11
    #11 0x5567b7125d07 in uv_run **/.deps/build/src/libuv/src/unix/core.c:460:5
    #12 0x5567b5fbf0e7 in loop_uv_run **/src/nvim/event/loop.c:59:3
    #13 0x5567b5fbed64 in loop_poll_events **/src/nvim/event/loop.c:80:26
    #14 0x5567b678ff31 in inbuf_poll **/src/nvim/os/input.c:515:3
    #15 0x5567b678f962 in input_get **/src/nvim/os/input.c:154:18
    #16 0x5567b6b59b08 in state_enter **/src/nvim/state.c:79:7
    #17 0x5567b66234f4 in normal_enter **/src/nvim/normal.c:523:3
    #18 0x5567b63a3e50 in main **/src/nvim/main.c:656:3
    #19 0x7f64cd227674 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #20 0x7f64cd227728 in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #21 0x5567b57cf004 in _start (**/build/bin/nvim+0xc92004) (BuildId: 81a1dbb637804ae755a5f6298ff4cf1ae5401cd5)

SUMMARY: AddressSanitizer: 4096 byte(s) leaked in 1 allocation(s).
```

### Steps to reproduce

1. Build Nvim with ASAN and run `nvim --clean`.
2. In another terminal, start a remote TUI client and attach to the server.
3. Close the terminal containing the server.
4. Memory leak in the server.

### Expected behavior

No memory leak.

### Nvim version (nvim -v)

v0.12.0-dev-1546+ge87f2d1cf9

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.43.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by zeertzjq**
Problem:  Closing socket with pending writes leaks memory.
Analysis: When calling rstream_may_close() on an RStream with pending
          writes, it waits for write_cb() to call stream_close_handle(),
          which closes it as if it's a WStream and doesn't free the
          RStream's buffer.
Solution: Ensure that an RStream's buffer is freed when it's closed.

Fix #36392

### CODE REVIEW

**Comment by zeertzjq** [comment]
I removed `wstream_may_close()`, as it now has the same signature as `stream_may_close()` (unlike `rstream_may_close()` which has a different signature), and there is nothing enforcing the use of `wstream_may_close()` vs. `stream_may_close()` (e.g. `stream_may_close()` is already used in os/shell.c).

**Comment by zeertzjq** [comment]
Oops, wrong commit message again.

File: test/functional/api/server_requests_spec.lua [hunk 1]
```diff
@@ -305,6 +305,16 @@ describe('server -> client', function()
       eq(clientpid, fn.getpid())
       eq('howdy!', api.nvim_get_current_line())
 
+      -- sending notification and then closing channel immediately still works
```
Comment (ntdiary) [inline test/functional/api/server_requests_spec.lua:308]: Hi, @zeertzjq, it seems this behavior is unstable in `ubuntu release gcc functionaltest`.
If `EOF` is handled immediately after `nvim_set_current_line `, the latter is ignored due to the channel being closed, which cause this test to fail:
```
DBG 2025-11-16T07:46:01.086 T1.61591.0 receive_msgpack:208: ch 3: parsing 31 bytes from msgpack Stream: 0x55f87e230f70
DBG 2025-11-16T07:46:01.086 T1.61591.0 RPC: <- 3: [notify]    nvim_set_current_line
DBG 2025-11-16T07:46:01.086 T1.61591.0 handle_request:345: RPC: scheduled nvim_set_current_line
DBG 2025-11-16T07:46:01.086 T1.61591.0 read_cb:122: closing Stream (0x55f87e230f70): EOF (end of file)
DBG 2025-11-16T07:46:01.086 T1.61591.0 receive_msgpack:208: ch 3: parsing 0 bytes from msgpack Stream: 0x55f87e230f70
DBG 2025-11-16T07:46:01.086 T1.61591.0 stream_may_close:105: closing Stream: 0x55f87e230f70
INF 2025-11-16T07:46:01.086 T1.61591.0 chan_close_on_err:540: RPC: ch 3 was closed by the peer
DBG 2025-11-16T07:46:01.086 T1.61591.0 state_enter:99: input: K_EVENT
INF 2025-11-16T07:46:01.086 T1.61591.0 request_event:359: handler is nvim_set_current_line, channel->rpc.closed is true
``` 
https://github.com/neovim/neovim/blob/39e27d64ad69ac4a33c1c34915110991405af337/src/nvim/msgpack_rpc/channel.c#L359-L362

Comment (zeertzjq) [reply test/functional/api/server_requests_spec.lua:308]: Hmm right. I'll change it to `nvim_input` then. #36570
