### PR TITLE
TUI: don't use BCE with "reverse" attribute

### LINKED ISSUE #9346: TUI: statusline "middle" is blank on Terminal.app
- `nvim --version`: xterm-256color
- Vim (version: ) behaves differently? Yes
- Operating system/version: macOS 10.13
- Terminal name/version: Terminal.app
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

### Actual behaviour

statusline middle area is blank. This is similar to https://github.com/neovim/neovim/issues/9282 , but in that case it required CTRL-L, and I was running inside tmux. In this case, running in Terminal.app outside of tmux, the behavior is consistent, and CTRL-L doesn't change anything. (I didn't notice this before because I normally am always inside tmux.)

nvim-blank-statusline

### Expected behaviour

statusline should paint with the StatusLine background color.

cc @bfredl

### PR DESCRIPTION
**Pull request by bfredl**
fixes #9346. The implementation of BCE in libvterm is "too good", it enables to set any attribute when clearing. But not all terminals support this, so don't rely on it.

### CODE REVIEW

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -754,11 +755,11 @@ static void clear_region(UI *ui, int top, int bot, int left, int right,
   update_attrs(ui, attr_id);
 
   // non-BCE terminals can't clear with non-default background color
-  bool can_clear = data->bce || !data->has_bg;
```
Comment (justinmk) [inline src/nvim/tui/tui.c]: should the comment move to line 584?

Comment (bfredl) [reply src/nvim/tui/tui.c]: I updated it also.

**Review by justinmk — APPROVED** [review]
