### PR TITLE
Fix terminal session save that is restored even if a option is disabled

### LINKED ISSUE #13078: Saving a session with sessionoptions without 'terminal' still saves/ restores terminal buffers
- `nvim --version`: v0.5.0-741-gca6815115
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour

By default, `sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize` which doesn't have a 'terminal' included in it. So terminal buffers should not be saved off and restored. However, these terminal buffers are restored in NVIM when the session saved file is loaded whereas they are not saved and restored in vanilla VIM.

### Expected behaviour

NVIM should obey leaving out 'terminal' in sessionoptions.

### PR DESCRIPTION
**Pull request by GustavoKatel**
This is a continuation of https://github.com/neovim/neovim/pull/14797

This patch fixes https://github.com/neovim/neovim/issues/13078

Thanks to @yutkat for starting this out!

### CODE REVIEW

File: test/functional/ex_cmds/mksession_spec.lua [hunk 1]
```diff
@@ -37,22 +37,107 @@ describe(':mksession', function()
...
+
+      -- no terminal should be set. As a side effect we end up with a blank buffer
+      eq(2, #meths.list_bufs())
+      eq('', meths.buf_get_option(meths.list_bufs()[1], 'buftype'))
+      eq('', meths.buf_get_option(meths.list_bufs()[2], 'buftype'))
+    end
+  )
+
+  it('do not restore :terminal if not set in sessionoptions, terminal hidden #13078', function()
+    command('set sessionoptions-=terminal')
```
Comment (justinmk) [inline test/functional/ex_cmds/mksession_spec.lua:89]: how much is different between these tests? any way to have a shared function to avoid lots of duplicate code?

Comment (GustavoKatel) [reply test/functional/ex_cmds/mksession_spec.lua:89]: ah good point!

I guess I can do some cleanup. Do we have any code style that mentions nested `describe` in test files? I can also create a helper in `test/functional/helpers.lua` if that's better.

Comment (justinmk) [reply test/functional/ex_cmds/mksession_spec.lua:89]: nested describe should be avoided. Simple solution would be just to create a `local function test_foo()` that is called by the three new tests added here.

Comment (GustavoKatel) [reply test/functional/ex_cmds/mksession_spec.lua:89]: cool thanks! I will do this later today, I will also fix the CI errors

Comment (GustavoKatel) [reply test/functional/ex_cmds/mksession_spec.lua]: done in 5ef0ce342e05094c2b0c0db0edd7abbc78e57172 lmk if you have any suggestions for more cleanups. thanks

**Comment by zeertzjq** [comment]
Should `terminal` be included in `'sessionoptions'` by default? Vim has it by default.

**Comment by GustavoKatel** [comment]
> Should `terminal` be included in `'sessionoptions'` by default? Vim has it by default.

I guess that will make the transition smoother after this change for people that rely on the current behavior. I'm fine either way

**Comment by GustavoKatel** [comment]
not sure how to handle the failed CI checks. Any ideas?

**Comment by zeertzjq** [comment]
A rebase should fix them. And, by the way, I do think it's better to include `terminal` in `'sessionoptions'` by default.

**Comment by GustavoKatel** [comment]
> A rebase should fix them. And, by the way, I do think it's better to include `terminal` in `'sessionoptions'` by default.

done in c8ccf97bf8c49c05e1a89eb1730f7fb6d32bc590
