### PR TITLE
fix(float): trigger winnew event when float window create

### LINKED ISSUE #11673: `WinNew` event not triggered for float windows
Hi,

`WinNew` is not triggered when creating a new window and not entering it (eg: `nvim_open_win(_, false, _)`). This is the case for Lsp hover window for example.

I tried to set an autocommand to change winhighlight for this kind of windows but was not able to use `WinNew`

Thanks
A

### PR DESCRIPTION
**Pull request by glepnir**
Problem: `WinNew` autocmd not trigger when float window create by using `nvim_open_win`

Solution: trigger WinNew when `noautocmd` is false

Fix #11673

### CODE REVIEW

File: src/nvim/api/win_config.c [hunk 1]
```diff
@@ -191,6 +191,9 @@ Window nvim_open_win(Buffer buffer, Boolean enter, Dict(float_config) *config, E
   // autocmds in win_enter or win_set_buf below may close the window
   if (win_valid(wp) && buffer > 0) {
     win_set_buf(wp, buf, fconfig.noautocmd, err);
+    if (!fconfig.noautocmd) {
+      apply_autocmds(EVENT_WINNEW, NULL, NULL, false, buf);
```
Comment (justinmk) [inline src/nvim/api/win_config.c:195]: Low-level steps should rarely be done directly in the API function body. Shouldn't this be done in `win_set_buf`? also why doesn't `win_set_buf` already trigger this somehow, e.g. via `win_enter` ?

Comment (glepnir) [reply src/nvim/api/win_config.c:195]: `win_enter` need a flag to trigger `WINNEW` but in `win_new_float` we just check `sync` not set flag `WEE_TRIGGER_NEW_AUTOCMDS` in `win_enter`. let me do some change then..

File: src/nvim/api/win_config.c [hunk 2]
```diff
@@ -185,9 +185,7 @@ Window nvim_open_win(Buffer buffer, Boolean enter, Dict(float_config) *config, E
   if (!wp) {
     return 0;
   }
-  if (enter) {
-    win_enter(wp, false);
-  }
+  new_win_ext(wp, enter, false, buf);
```
Comment (justinmk) [inline src/nvim/api/win_config.c:188]: This doesn't save any code, it only adds redirection. My general question is whether some part of the `win_enter` codepath should already trigger WinNew. That requires looking at existing callers to `win_enter`
