### PR TITLE
fix(lsp): add assertion for explicit bufnr in apply_text_edits

### LINKED ISSUE #27613: LSP formatexpr does not properly save and restore marks
### Problem

Use the following mapping to reformat the entire buffer while keeping the cursor's position:

```vim
nnoremap gq<CR> mzgggq`z
```

Using this with `set formatexpr=v:lua.vim.lsp.formatexpr()` shows an error `E20: Mark not set` and does not correctly restore the cursor position.

### Steps to reproduce using "nvim -u minimal_init.lua"

local pattern = 'lua'
local cmd = {'lua-language-server'}
-- Add files/folders here that indicate the root of a project
local root_markers = {'.git', '.editorconfig', '.luarc.json'}
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'lua-language-server',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})

vim.keymap.set('n', 'gq<CR>', 'mzgggq`z')

### Expected behavior

The cursor position does not move after formatting using the mapping above.

### Neovim version (nvim -v)

71384129f75462f14344df236cf0a22b83da4f4c

### Language server name/version

N/A

### Operating system/version

N/A

### Log file

_No response_

### PR DESCRIPTION
**Pull request by gpanders**
Assert that the buffer number passed to apply_text_edits is fully
resolved (not 0 or null). Pass the known buffer number to
apply_text_edits from lsp.formatexpr().

Fixes: https://github.com/neovim/neovim/issues/27613

### CODE REVIEW

File: runtime/lua/vim/lsp.lua [hunk 1]
```diff
@@ -1280,7 +1280,7 @@ function lsp.formatexpr(opts)
       local response =
         client.request_sync(ms.textDocument_rangeFormatting, params, timeout_ms, bufnr)
       if response and response.result then
-        lsp.util.apply_text_edits(response.result, 0, client.offset_encoding)
+        lsp.util.apply_text_edits(response.result, bufnr, client.offset_encoding)
```
Comment (gpanders) [inline runtime/lua/vim/lsp.lua:1283]: This is a bit of a redundant fix and is not strictly necessary since `apply_text_edits` will resolve a `0` buffer number, but since we already have the buffer number available anyway we might as well use it.

File: test/functional/plugin/lsp_spec.lua [hunk 2]
```diff
@@ -1808,7 +1808,7 @@ describe('LSP', function()
         make_edit(4, 0, 5, 0, 'barfoo'),
       }
       eq(true, exec_lua('return vim.api.nvim_buf_set_mark(1, "a", 2, 1, {})'))
-      exec_lua('vim.lsp.util.apply_text_edits(...)', edits, 1, 'utf-16')
+      exec_lua('vim.lsp.util.apply_text_edits(...)', edits, 0, 'utf-16')
```
Comment (gpanders) [inline test/functional/plugin/lsp_spec.lua:1811]: This change is sufficient to demonstrate the fix. With `0` this test fails on master.

File: runtime/lua/vim/lsp/util.lua [hunk 3]
```diff
@@ -419,6 +419,11 @@ function M.apply_text_edits(text_edits, bufnr, offset_encoding)
   if not next(text_edits) then
     return
   end
+
+  if not bufnr or bufnr == 0 then
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/util.lua:423]: The method here is intended to be called with a result from a language server for a specific document/ buffer, so I think at this point this should be a concrete buffer number already. Because of that I'd tend to turn this into an error with an assert.

(Also the type annotation doesn't imply nil)

**Review by MariaSolOs — APPROVED** [review]

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (mfussenegger) [reply runtime/lua/vim/lsp.lua:1283]: +1 for the change. See my comment below I think this is actually the right fix

**Review by mfussenegger — APPROVED** [review]
