### PR TITLE
fix(Man.lua): trigger completion even without arguments

### LINKED ISSUE #31512: `:Man <tab>` does not complete
### Problem

`:Man` autocomplete doesn't work and shows outdated bash page. Demo [here](https://youtu.be/DsW_Vtwva5A)

References #30873

### Steps to reproduce

nvim --clean
:Man <tab>
:Man b<tab>

### Expected behavior

nvim --clean
:Man <tab> " Should show autocomplete suggestions
:Man b<tab> " Should show autocomplete suggestions

### Nvim version (nvim -v)

gab9cfc4dc3

### Vim (not Nvim) behaves the same?

No. 9.1

### Operating system/version

MacOS

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

Homebrew --head

### PR DESCRIPTION
**Pull request by saccarosium**
closes: #31512

It is slow to return all the manual entries but it is something that the user expects.

### CODE REVIEW

File: runtime/lua/man.lua [hunk 1]
```diff
@@ -576,9 +576,8 @@ function M.man_complete(arg_lead, cmd_line, _)
   end
 
   if #args == 1 then
-    -- returning full completion is laggy. Require some arg_lead to complete
-    -- return complete('', '', '')
-    return {}
+    -- returning full completion is laggy. But it is something that users espect (#31512)
+    return complete('', '', '')
```
Comment (justinmk) [inline runtime/lua/man.lua:580]: @lewis6991 do you foresee any problems with this? completion is currently broken.

File: runtime/lua/man.lua [hunk 2]
```diff
@@ -576,9 +576,8 @@ function M.man_complete(arg_lead, cmd_line, _)
   end
 
   if #args == 1 then
-    -- returning full completion is laggy. Require some arg_lead to complete
-    -- return complete('', '', '')
-    return {}
+    -- returning full completion is laggy. But it is something that users espect (#31512)
```
Comment (justinmk) [inline runtime/lua/man.lua:579]:
```suggestion
    -- Note: Returning full completion is laggy.
```

File: runtime/lua/man.lua (hunk 1 above)
Comment (lewis6991) [reply runtime/lua/man.lua:580]: Yes, it was very slow.

Comment (saccarosium) [reply runtime/lua/man.lua:580]: It is slow but not horribly slow, at least on my machine. 

On vim completion with `Man` can lock the UI in this version it is much faster...

Comment (lewis6991) [reply runtime/lua/man.lua:580]: Depends on your machine. It must have been too slow when I write this.

Comment (justinmk) [reply runtime/lua/man.lua:580]: But it's opt-in via `<tab>`, so it's better that it does something than nothing.

Comment (lewis6991) [reply runtime/lua/man.lua:580]: Not if you use command line completion from nvim-cmp.

Comment (justinmk) [reply runtime/lua/man.lua:580]: > Not if you use command line completion from nvim-cmp.

Then they need to deal with that, rather than expect a regression in Nvim core.

Comment (justinmk) [reply runtime/lua/man.lua:580]: The problem reported in https://github.com/neovim/neovim/issues/31512 (which also reproduces for me) is not only for the "everything" case. `:Man f<tab>` does not work. Or with any other char.

Comment (lewis6991) [reply runtime/lua/man.lua:580]: This PR does not fix that. Why would it?

This [PR](https://github.com/neovim/neovim/pull/31571) will probably fix it.
