### PR TITLE
ui: fix problem with the popupmenu when rightleft is set

### LINKED ISSUE #12032: segfault with rightleft, keymap=hebrew & coc.nvim completion
With [coc.nvim](https://github.com/neoclide/coc.nvim), and nothing else installed, Almost always I get a crash when `rightleft` and `keymap=hebrew` are set. I've taken the effort to build Neovim with debug info and not strip the executables, see the backtrace at the end.

- `nvim --version`:
```
NVIM v0.5.0-dev
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/cxglgpiww68zj4qn82x3dgln8nk6zb4c-neovim-beta-unwrapped-0.5.0/share/nvim
"

Run :checkhealth for more info
"
```

To be specific, this is the nightly as of today - https://github.com/neovim/neovim/commit/87d892afa0475644e91d9c8a57b7c35491c4dc32 .

- `vim -u DEFAULTS` (version: ) behaves differently? 
  I tested Vim just a little bit and it hadn't crashed for me yet. I'll update if I'll find out it does crash.
- Operating system/version: NixOS
- Terminal name/version: Urxvt with / without tmux (EDITED)
- `$TERM`:

Crashes with both `tmux-256color` & `rxvt-unicode-256color` (EDITED)

### Steps to reproduce using a clean `nvim/` directory in `$XDG_CONFIG_HOME`.

```
git clone https://github.com/doronbehar/nvim-config-test nvim -b neovim-beta-crash
cat nvim/init.vim # for your own reference
env XDG_CONFIG_HOME=$PWD nvim nvim/crashes.txt
```

Start type letters that trigger completion, it's probably hard without a Hebrew keyboard but I promise you that if you'll try hard enough you'll hit a crash.

~~According to my tests, it might be crucial to use rxvt-unicode + tmux with this in `~/.tmux.conf`:~~

<details><summary>(EDIT) not correct anymore, I've tested this with and without the following in `~/.tmux.conf`:</summary>

```
# Taken from https://github.com/neovim/neovim/wiki/FAQ#cursor-shape-doesnt-change-in-tmux
if-shell '[[ $TERM =~ "rxvt" ]]' 'set -g -a terminal-overrides '"'"',*:Ss=\E[%p1%d q:Se=\E[2 q'"'"
```

</details>

### Actual behaviour

Crash when hitting the enter key when completion is suggested. Here's the backtrace from `coredumpctl debug`:

```
#0  0x00007faa59d7115a in raise () from /nix/store/9rabxvqbv0vgjmydiv59wkz768b5fmbc-glibc-2.30/lib/libc.so.6
#1  0x00007faa59d5b548 in abort () from /nix/store/9rabxvqbv0vgjmydiv59wkz768b5fmbc-glibc-2.30/lib/libc.so.6
#2  0x00007faa59d5b42f in __assert_fail_base.cold.0 () from /nix/store/9rabxvqbv0vgjmydiv59wkz768b5fmbc-glibc-2.30/lib/libc.so.6
#3  0x00007faa59d69ad2 in __assert_fail () from /nix/store/9rabxvqbv0vgjmydiv59wkz768b5fmbc-glibc-2.30/lib/libc.so.6
#4  0x00000000006f7054 in compose_line (row=3, startcol=-1, endcol=15, flags=2) at /build/source/src/nvim/ui_compositor.c:350
#5  0x00000000006f7a8c in compose_area (startrow=3, endrow=7, startcol=-1, endcol=14) at /build/source/src/nvim/ui_compositor.c:485
#6  0x00000000006f7af6 in ui_comp_compose_grid (grid=0x829280 <pum_grid>) at /build/source/src/nvim/ui_compositor.c:496
#7  0x00000000006f6a13 in ui_comp_remove_grid (grid=0x829280 <pum_grid>) at /build/source/src/nvim/ui_compositor.c:224
#8  0x0000000000633efa in pum_check_clear () at /build/source/src/nvim/popupmnu.c:850
#9  0x00000000004ab877 in ins_redraw (ready=1) at /build/source/src/nvim/edit.c:1498
#10 0x00000000004a9ab4 in insert_check (state=0x7ffed8166c40) at /build/source/src/nvim/edit.c:618
#11 0x00000000006c34a2 in state_enter (s=0x7ffed8166c40) at /build/source/src/nvim/state.c:28
#12 0x00000000004a962f in insert_enter (s=0x7ffed8166c40) at /build/source/src/nvim/edit.c:483
#13 0x00000000004ab3d6 in edit (cmdchar=97, startln=false, count=1) at /build/source/src/nvim/edit.c:1412
#14 0x00000000005fce43 in invoke_edit (cap=0x7ffed8166e28, repl=0, cmd=97, startln=0) at /build/source/src/nvim/normal.c:7639
#15 0x00000000005fcdd3 in nv_edit (cap=0x7ffed8166e28) at /build/source/src/nvim/normal.c:7611
#16 0x00000000005ed40b in normal_execute (state=0x7ffed8166da0, key=97) at /build/source/src/nvim/normal.c:1133
#17 0x00000000006c358e in state_enter (s=0x7ffed8166da0) at /build/source/src/nvim/state.c:69
#18 0x00000000005eb500 in normal_enter (cmdwin=false, noexmode=false) at /build/source/src/nvim/normal.c:463
#19 0x00000000005a6488 in main (argc=10, argv=0x7ffed8167128) at /build/source/src/nvim/main.c:569
```

### Expected behaviour

No crash.

### More info

Somewhat similar to https://github.com/neovim/neovim/issues/11925 (cc @Kozova1), but I hope here the issue is illustrated better. I _think_ it happens only with already opened files which contain Hebrew text, meaning you might have to open, change something, and reopen in order to trigger the crash and hence reproduce.

### PR DESCRIPTION
**Pull request by erw7**
fixes #12032

### CODE REVIEW

**Comment by doronbehar** [comment]
It works and I am thrilled!

I can confirm the issue shows up with the non patched `nvim` when I reach the end of the line, and I tested exactly this.

I've also managed to apply the patch upon the stable release (excluding the patch to the test file, as it won't apply on stable), and the bug seems to be fixed there as well :smile: .

It's amazing what a single line can do. You made my day @erw7, thank you so much :green_heart: .

File: src/nvim/ui_compositor.c [hunk 1]
```diff
@@ -311,6 +311,9 @@ ScreenGrid *ui_comp_mouse_focus(int row, int col)
 static void compose_line(Integer row, Integer startcol, Integer endcol,
                          LineFlags flags)
 {
+  // If rightleft is set, startcol may be -1. In such cases, the assertions
+  // will fail because no overlap is found. Adjust startcol to prevent it.
+  startcol = MAX(startcol, 0);
```
Comment (bfredl) [inline src/nvim/ui_compositor.c:316]: Note to self: we probably want a `kLineFlagRightLeft` for cases like this.
