### PR TITLE
fix(api): nvim_parse_cmd handle nextcmd for commands without EX_TRLBAR

### LINKED ISSUE #36029: nvim_parse_cmd on multiple bar-separated Ex commands
### Problem

`nvim_parse_cmd` returns nonsense on some bar-separated Ex commands:

```
vim.api.nvim_parse_cmd('exe "ls"|edit foo',{})

{
  cmd = "execute",
  args = { '"ls"|edit', "foo" },
}
```

However, it seems to work with this case:

```
vim.api.nvim_parse_cmd('split|ls|term',{})

{
  cmd = "split",
  nextcmd = "ls|term"
}
```

### Steps to reproduce

```
vim.api.nvim_parse_cmd('exe "ls"|edit foo',{})
```

### Expected behavior

Set `nextcmd` correctly.

```
{
  cmd = "execute",
  args = { '"ls"' },
  nextcmd = 'edit foo'
}
```

### Nvim version (nvim -v)

ea124068f246

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macos

### Terminal name/version

ghostty

### $TERM environment variable

n/a

### Installation

source

### PR DESCRIPTION
**Pull request by glepnir**
Problem: nvim_parse_cmd('exe "ls"|edit foo', {}) fails to separate nextcmd, returning args as { '"ls"|edit', 'foo' } instead of { '"ls"' } with nextcmd='edit foo'.

Solution: Skip expressions before checking for '|' separator.

Fix #36029

### CODE REVIEW

File: src/nvim/ex_docmd.c [hunk 1]
```diff
@@ -1596,6 +1596,22 @@ bool parse_cmdline(char **cmdline, exarg_T *eap, CmdParseInfo *cmdinfo, const ch
   // Don't do this for ":read !cmd" and ":write !cmd".
   if ((eap->argt & EX_TRLBAR)) {
     separate_nextcmd(eap);
+  } else {
```
Comment (zeertzjq) [inline src/nvim/ex_docmd.c]: This isn't correct if the command doesn't expect an expression (e.g. `:terminal` and `:lua` which take `|` as part of argument, or `:syntax` which has a different rule for each subcommand)

Comment (glepnir) [reply src/nvim/ex_docmd.c]: make sense.. how about list some cmds in there 🤔

Comment (zeertzjq) [reply src/nvim/ex_docmd.c]: Ideally you can just set `eap->skip` and call `execute_cmd0()` if `skip_cmd(eap)` is false, but there may be bugs in some commands' handling of `eap->skip`...

Comment (glepnir) [reply src/nvim/ex_docmd.c]: emm but parse_cmdline() should only perform static parsing and should not execute any command code, right?

Comment (zeertzjq) [reply src/nvim/ex_docmd.c]: I said "ideally". Ideally commands for which `skip_cmd(eap)` return false should not execute anything (and only set `eap->nextcmd`) if `eap->skip` is set.

Comment (glepnir) [reply src/nvim/ex_docmd.c]: aha okkkay :) i tried this seems like a few cases and new case failed

```
    eap->skip = true;
    if (!skip_cmd(eap)) {
      int retv;
      execute_cmd0(&retv, eap, errormsg, false);
    }
    eap->skip = false;
```

File: test/functional/api/vim_spec.lua [hunk 2]
```diff
@@ -4849,6 +4849,12 @@ describe('API', function()
       result = api.nvim_parse_cmd('copen 5', {})
       eq(5, result.count)
     end)
+    it('correctly parses nextcmd for commands #36029', function()
```
Comment (justinmk) [inline test/functional/api/vim_spec.lua]: all tests are assumed to check for correctness.

```suggestion
    it('parses nextcmd for commands #36029', function()
```

File: src/nvim/ex_docmd.c [hunk 3]
```diff
@@ -1596,6 +1596,25 @@ bool parse_cmdline(char **cmdline, exarg_T *eap, CmdParseInfo *cmdinfo, const ch
...
   if ((eap->argt & EX_TRLBAR)) {
     separate_nextcmd(eap);
+  } else if (eap->cmdidx == CMD_execute
+             || eap->cmdidx == CMD_echo
+             || eap->cmdidx == CMD_echomsg
+             || eap->cmdidx == CMD_echoerr) {
+    // For commands without EX_TRLBAR, check for '|' separator
+    // by skipping over expressions (including string literals)
+    char *arg = eap->arg;
+    while (*arg != NUL && *arg != '|' && *arg != '\n') {
```
Comment (justinmk) [inline src/nvim/ex_docmd.c]: this feels rather hacky. if `parse_cmdline` or `nvim_parse_cmd` were used as the central codepath (https://github.com/neovim/neovim/issues/34398) then at least the "hacks" would be in one place. but that isn't currently the case.

Comment (justinmk) [reply src/nvim/ex_docmd.c]: here is another place that is checking for the same kinds of commands: https://github.com/neovim/neovim/blob/c2a196f19be1a7a625e47eaf15a295a0ac6e356d/src/nvim/eval.c#L1998-L2004

is this code that can be factored out into a common function? please look for this kind of thing when proposing patches.

Comment (glepnir) [reply src/nvim/ex_docmd.c]: Isn't this completely different.. Besides `parse_cmdline` was specifically designed for `nvim_parse_command` as a side-effect-free function. `do_one_cmd` has additional logic and ordering. I once tried using `parse_cmdline` inside `do_one_cmd`, but some buffer-related commands failed. However, that should be unrelated here — the hacky part only applies here.

Comment (justinmk) [reply src/nvim/ex_docmd.c]: At minimum I'm suggesting that we keep the `CMD_execute || CMD_echo || ...` decision in one place. It looks like that decision is important and relevant in multiple places.
