### PR TITLE
[RFC] Make vim_fgets() return the same values as in Vim

### LINKED ISSUE #8227: Neovim hangs on [I in Python file with `import sys`
- `nvim --version`:

```
NVIM v0.2.3-776-ge8c39f72f
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion
-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32
-DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic
-Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla
-fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS
-I/tmp/neovim-20180404-59056-10htpq2/build/config
-I/tmp/neovim-20180404-59056-10htpq2/src -I/usr/local/include
-I/usr/local/opt/gettext/include -I/usr/include
-I/tmp/neovim-20180404-59056-10htpq2/build/src/nvim/auto
-I/tmp/neovim-20180404-59056-10htpq2/build/include
Compiled by user@localhost.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-e8c39f7_1/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently? Yes, this works fine in Vim 8.0.1650 and 8.0.642.
- Operating system/version: `macOS High Sierra 10.13.3`
- Terminal name/version: `iTerm2 Build 3.2.20180404-nightly`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```python
# hang.py
import sys
sys.path
```

```bash
$ nvim -u NORC hang.py
```

Move the cursor to the word "sys" and then press `[I` to list all lines containing the word under the cursor. 

### Actual behaviour

Hangs indefinitely.

### Expected behaviour

Show list of lines matching word under cursor.

### Other observations

- By changing the import to for example `random` instead of `sys`, it works. So it's _something_ with `sys` (and possibly others?) that breaks `[I`.
- It works fine using `nvim -u NONE` instead of `NORC`.
- If I use `-u NONE` and then manually set `filetype plugin indent on` and then `:e` to re-read the file, it breaks again. So I suspect it's _something_ with the Python filetype.

### PR DESCRIPTION
**Pull request by mhinz**
The implementation of vim_fgets() differs between Neovim and Vim.

Vim says that it only returns `true` for EOF. But it always returns `true` when
fgets() returns NULL. This happens for EOF _or_ errors.

That probably misguided the author of Neovim's vim_fgets(), which does NOT
return `true` for errors.

Since all the callers of vim_fgets() probably expect it to work as it does in
Vim (and not as it says), it now returns the same values as the Vim
implementation.

Fixes #8227

### CODE REVIEW

**Comment by jamessan** [comment]
It's probably still worth adding the checks below so the `fgets()` loops are continued/stopped when appropriate.

```diff
diff --git a/src/nvim/fileio.c b/src/nvim/fileio.c
index 52686f665..623becb62 100644
--- a/src/nvim/fileio.c
+++ b/src/nvim/fileio.c
@@ -4451,7 +4451,7 @@ bool vim_fgets(char_u *buf, int size, FILE *fp) FUNC_ATTR_NONNULL_ALL
   do {
     errno = 0;
     retval = fgets((char *)buf, size, fp);
-  } while (retval == NULL && errno == EINTR);
+  } while (retval == NULL && ferror(fp) && errno == EINTR);
 
   if (buf[size - 2] != NUL && buf[size - 2] != '\n') {
     char tbuf[200];
@@ -4463,12 +4463,12 @@ bool vim_fgets(char_u *buf, int size, FILE *fp) FUNC_ATTR_NONNULL_ALL
       tbuf[sizeof(tbuf) - 2] = NUL;
       errno = 0;
       retval = fgets((char *)tbuf, sizeof(tbuf), fp);
-      if (retval == NULL && errno != EINTR) {
+      if (retval == NULL && (feof(fp) || errno != EINTR)) {
         break;
       }
     } while (tbuf[sizeof(tbuf) - 2] != NUL && tbuf[sizeof(tbuf) - 2] != '\n');
   }
-  return retval ? false : feof(fp);
+  return retval == NULL;
 }
 
 /// Read 2 bytes from "fd" and turn them into an int, MSB first.
```

File: src/nvim/fileio.c [hunk 1]
```diff
@@ -4475,12 +4475,12 @@ bool vim_fgets(char_u *buf, int size, FILE *fp) FUNC_ATTR_NONNULL_ALL
       tbuf[sizeof(tbuf) - 2] = NUL;
       errno = 0;
       retval = fgets((char *)tbuf, sizeof(tbuf), fp);
-      if (retval == NULL && errno != EINTR) {
+      if (retval == NULL && (errno != EINTR || feof(fp))) {
```
Comment (jamessan) [inline src/nvim/fileio.c]: Nitpick, but I would check `feof()` first since there's no reason to assume `errno` is valid unless an error happened.

Comment (mhinz) [reply src/nvim/fileio.c]: I did it that way because last time Justin argued that one shouldn't have to think about whether `feof()` could change `errno` again or not. :>

**Review by jamessan — APPROVED** [review]
