### PR TITLE
fix(api): handle count parameter correctly in nvim_parse_cmd and nvim_cmd

### LINKED ISSUE #21313: inconsistent behavior for nvim_cmd to run parsed "copen"
### Neovim version (nvim -v)

NVIM v0.8.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

archlinux

### Terminal name/version

st 0.8.5

### $TERM environment variable

tmux-256color

### Installation

system package manager

### How to reproduce the issue

* `nvim --clean`
* case 1 `:lua vim.api.nvim_cmd(vim.api.nvim_parse_cmd('copen', {}), {})`
* case 2 `copen`
* case 3 `:lua vim.api.nvim_cmd({cmd = "copen"}, {})`
* case 4 `:lua vim.api.nvim_cmd({cmd = "copen", args = {10}}, {})`

### Expected behavior

case 1, 2, 3 will open the quickfix window with height 10.
for the case 4, i would expect it worked just like `:copen 10`

### Actual behavior

case 1 opens quickfix window with height `1`;
case 4 failed to run;

### LINKED ISSUE #23121: vim.cmd.foo(2) does not behave like vim.cmd.foo{count=2}
### Problem

The ex-command `:undo {N}` accepts a count to jump to the change after the sequence number `{N}`. However, `vim.cmd.undo` only works with zero arguments and shows an error like
```
E5108: Error executing lua [string ":lua"]:1: Wrong number of arguments                                                                                               
stack traceback:
        [C]: in function 'undo'
        [string ":lua"]:1: in main chunk
```
  when called with an argument. 

A workaround is to use `vim.cmd("undo " .. sequence_number)`.

### Steps to reproduce

- `nvim --clean`
- `:lua vim.cmd.undo(1)`

### Expected behavior

`vim.cmd.undo` should accept a count argument

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2650+g8c6f97bef

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Linux Mint 20.2

### Terminal name/version

Kitty 0.15

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by glepnir**
Problem:
- nvim_parse_cmd('copen', {}) returns count: 0, causing nvim_cmd to override default behavior
- nvim_cmd({cmd = 'copen', args = {10}}, {}) fails with "Wrong number of arguments"

Solution:
- Only include count field in parse result when explicitly provided or non-zero
- Interpret single numeric argument as count for count-only commands like copen

Fix #21313
Fix #23121

### CODE REVIEW

File: src/nvim/api/command.c [hunk 1]
```diff
@@ -377,68 +382,96 @@ String nvim_cmd(uint64_t channel_id, Dict(cmd) *cmd, Dict(cmd_opts) *opts, Arena
     ea.argt = get_cmd_argt(ea.cmdidx);
   }
 
+  bool count_from_first_arg = false;
```
Comment (justinmk) [inline src/nvim/api/command.c:386]: a hint comment will be helpful here to show an example of what this means
```suggestion
  bool count_from_first_arg = false;  // "..."
```

File: src/nvim/api/command.c [hunk 2]
```diff
@@ -377,68 +382,96 @@ String nvim_cmd(uint64_t channel_id, Dict(cmd) *cmd, Dict(cmd_opts) *opts, Arena
...
+      bool is_numeric = false;
+      int64_t count_value = 0;
+
+      if (first_arg.type == kObjectTypeInteger) {
+        is_numeric = true;
+        count_value = first_arg.data.integer;
+      } else if (first_arg.type == kObjectTypeString) {
+        char *endptr;
+        long val = strtol(first_arg.data.string.data, &endptr, 10);
+        if (*endptr == '\0' && first_arg.data.string.size > 0) {
```
Comment (justinmk) [inline src/nvim/api/command.c:404]: need a hint comment that shows an example for each of these cases
```suggestion
        if (*endptr == '\0' && first_arg.data.string.size > 0) {
        // "..."
```

**Review by justinmk — APPROVED** [review]
LGTM. As a future refactor, we really should use `nvim_parse_cmd` as the source of truth in `do_cmdline`. We have duplicated the logic in both places, and it is very complex. https://github.com/neovim/neovim/issues/34398

File: src/nvim/api/command.c [hunk 3]
```diff
@@ -377,68 +382,102 @@ String nvim_cmd(uint64_t channel_id, Dict(cmd) *cmd, Dict(cmd_opts) *opts, Arena
...
+    if (cmd->args.size == 1 && (ea.argt & EX_COUNT) && !(ea.argt & EX_EXTRA)) {
+      Object first_arg = cmd->args.items[0];
+      bool is_numeric = false;
+      int64_t count_value = 0;
+
+      if (first_arg.type == kObjectTypeInteger) {
+        is_numeric = true;
+        count_value = first_arg.data.integer;
+      } else if (first_arg.type == kObjectTypeString) {
+        // Try to parse string as a number
```
Comment (justinmk) [inline src/nvim/api/command.c]: in many of these cases, an example will help a lot more than a description.

```suggestion
        // Try to parse string as a number. Example: "..."
```

File: src/nvim/api/command.c [hunk 4]
```diff
@@ -377,68 +382,102 @@ String nvim_cmd(uint64_t channel_id, Dict(cmd) *cmd, Dict(cmd_opts) *opts, Arena
...
+        long val = strtol(first_arg.data.string.data, &endptr, 10);
+        // Check if entire string was consumed (valid number) and string is not empty
+        if (*endptr == '\0' && first_arg.data.string.size > 0) {
+          is_numeric = true;
+          count_value = val;
+        }
+      }
+
+      if (is_numeric && count_value >= 0) {
+        // Interpret the argument as count
```
Comment (justinmk) [inline src/nvim/api/command.c:411]:
```suggestion
        // Interpret the argument as count. Example: "..."
```

File: test/functional/api/vim_spec.lua [hunk 5]
```diff
@@ -5396,6 +5404,57 @@ describe('API', function()
...
+      command('cclose')
+      eq(5, height2)
+
+      -- should reject both count and numeric arg
+      eq(
+        "Cannot specify both 'count' and numeric argument",
+        pcall_err(api.nvim_cmd, { cmd = 'copen', args = { 5 }, count = 10 }, {})
+      )
+    end)
+    it('handles string numeric arguments correctly', function()
```
Comment (glepnir) [inline test/functional/api/vim_spec.lua:5427]: @justinmk  I added a test that handles converting a string to  number. This is what we need ?

**Comment by gpanders** [comment]
Does this fix https://github.com/neovim/neovim/issues/30641?

**Comment by glepnir** [comment]
Not sure. I haven't seen  it yet. I'll look into it.
