### PR TITLE
[RFC] shada: Make sure that code does not attempt to read too long items

### LINKED ISSUE #6957: Broken shada files can cause assertion error
- `nvim --version`:
```
NVIM v0.2.0-303-gb674fd2c
Build type: Debug
Compilation: /usr/bin/afl-gcc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/languitar/src/neovim/build/config -I/home/languitar/src/neovim/src -I/home/languitar/src/neovim/.deps/usr/include -I/home/languitar/src/neovim/.deps/usr/include -I/home/languitar/src/neovim/.deps/usr/include -I/home/languitar/src/neovim/.deps/usr/include -I/home/languitar/src/neovim/.deps/usr/include -I/home/languitar/src/neovim/.deps/usr/include -I/usr/include -I/home/languitar/src/neovim/build/src/nvim/auto -I/home/languitar/src/neovim/build/include
Compiled by languitar@jaco

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim
```
- Operating system/version: archlinux 64
- Terminal name/version: termite
- `$TERM`:  xterm-termite

### Actual behaviour

I have fuzzed neovim for issues regarding the shada files. One thing that I have found is that an assertion error can be triggered with a broken file. I would expect that a usual warning is raised instead of an assertion error (which might be skipped for release builds).

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -i ./fuzzer02/crashes/id:000005,sig:06,src:000503+000235,op:splice,rep:16 -Z -R
```

This file (with broken extension due to github) is attached.
[id:000005,sig:06,src:000503+000235,op:splice,rep:16.txt](https://github.com/neovim/neovim/files/1121917/id.000005.sig.06.src.000503.000235.op.splice.rep.16.txt)

Will result in:

```
/home/languitar/src/neovim/src/nvim/shada.c:738: sd_reader_skip_read: Assertion `skip_bytes < (ptrdiff_t)offset' failed.
fish: “~/src/neovim/build/bin/nvim -u…” terminated by signal SIGABRT (Abort)
```

```
#0  0x00007ffff6d10670 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff6d11d00 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff6d0945a in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007ffff6d094d2 in __assert_fail () from /usr/lib/libc.so.6
#4  0x0000000000d82c85 in sd_reader_skip_read (sd_reader=0x7fffffffdd10, offset=14920435247833816829) at /home/languitar/src/neovim/src/nvim/shada.c:738
#5  0x0000000000d8a9e2 in sd_reader_skip (offset=14920435247833816829, sd_reader=0x7fffffffdd10) at /home/languitar/src/neovim/src/nvim/shada.c:762
#6  shada_read_next_item (sd_reader=sd_reader@entry=0x7fffffffdd10, entry=entry@entry=0x7fffffffd8f0, flags=flags@entry=3580, max_kbyte=max_kbyte@entry=0) at /home/languitar/src/neovim/src/nvim/shada.c:3536
#7  0x0000000000d924b0 in shada_read (sd_reader=sd_reader@entry=0x7fffffffdd10, flags=flags@entry=11) at /home/languitar/src/neovim/src/nvim/shada.c:1226
#8  0x0000000000db4436 in shada_read_file (flags=<optimized out>, file=0x0) at /home/languitar/src/neovim/src/nvim/shada.c:904
#9  shada_read_everything (fname=fname@entry=0x0, forceit=forceit@entry=false, missing_ok=missing_ok@entry=true) at /home/languitar/src/neovim/src/nvim/shada.c:3098
#10 0x000000000043d0de in main (argc=<optimized out>, argv=<optimized out>) at /home/languitar/src/neovim/src/nvim/main.c:387
```

### PR DESCRIPTION
**Pull request by ZyX-I**
Fixes #6957

### CODE REVIEW

**Comment by ZyX-I** [comment]
AppVeyor failure is usual

```
[  FAILED  ] C:/projects/neovim/test/functional\core\job_spec.lua @ 267: jobs can pass user data to the callback
C:/projects/neovim/test/functional\core\job_spec.lua:271: Expected objects to be the same.
Passed in:
(table) {
  [1] = 'notification'
  [2] = 'stdout'
 *[3] = {
    [1] = {
      [l] = { ... more }
      [n] = 5
      [s] = 'str' }
   *[2] = {
      [1] = 'foo' } } }
Expected:
(table) {
  [1] = 'notification'
  [2] = 'stdout'
 *[3] = {
    [1] = {
      [l] = { ... more }
      [n] = 5
      [s] = 'str' }
   *[2] = {
      [1] = 'foo'
     *[2] = '' } } }
stack traceback:
	C:/projects/neovim/test/functional\core\job_spec.lua:271: in function <C:/projects/neovim/test/functional\core\job_spec.lua:267>
```

QB only failed to compile due to kbtree.

Travis hang on check-single-includes, restarting.

**Comment by ZyX-I** [comment]
After restart lint stage succeeded, PR should be ready now.

File: src/nvim/shada.c [hunk 1]
```diff
@@ -3413,8 +3413,16 @@ static ShaDaReadResult shada_read_next_item(ShaDaReadDef *const sd_reader,
     return mru_ret;
   }
 
-  const size_t length = (size_t) length_u64;
-  entry->timestamp = (Timestamp) timestamp_u64;
+  if (length_u64 > PTRDIFF_MAX) {
+    emsgf(_(RCERR "Error while reading ShaDa file: "
+            "there is an item at position %" PRIu64 " "
+            "that is stated to be too long"),
```
Comment (justinmk) [inline src/nvim/shada.c]: Why "is stated to be" instead of just "is"? Could be abbreviated without ambiguity:

```c
emsgf(_(RCERR "Error while reading ShaDa file: "
        "item at position %" PRIu64 " is too long"),

Comment (ZyX-I) [inline src/nvim/shada.c]: @justinmk Because it is “stated to be”, you can’t generate such long entry under normal circumstances so most likely the number is wrong for one reason or another (starting from fuzzing output like in the original issue and ending with corrupted FS).

Comment (justinmk) [inline src/nvim/shada.c]: Ok. Could be reworded, but not worth it if this should never happen.
