### PR TITLE
fix(api): support get autocmds by id in api

### LINKED ISSUE #31531: nvim_get_autocmds: allow get by id
### Problem

Currently `nvim_get_autocmds` does not allow filter by id returned by `nvim_create_autocmd`. 

### Expected behavior

`id` option allows to do it without workarounds.

### PR DESCRIPTION
**Pull request by glepnir**
Close #31531

Problem: Can not use id as filter condition to get autocmds.

Solution: add id which support integer or array to filter get autocmds

PS: test and doc later

### CODE REVIEW

File: src/nvim/api/autocmd.c [hunk 1]
```diff
@@ -74,6 +74,7 @@ static int64_t next_autocmd_id = 1;
 ///             Cannot be used with {buffer}
 ///             - buffer: Buffer number or list of buffer numbers for buffer local autocommands
 ///             |autocmd-buflocal|. Cannot be used with {pattern}
+///             - id: (integer|array) autocmd ids
```
Comment (justinmk) [inline src/nvim/api/autocmd.c:77]: Is there a strong need to support array? If someone has an id they usually just want 1 result.

Comment (justinmk) [reply src/nvim/api/autocmd.c:77]: keeping the code simple (no array support) is probably worth it for now

Comment (glepnir) [reply src/nvim/api/autocmd.c:77]: okay 👍

File: src/nvim/api/autocmd.c [hunk 2]
```diff
@@ -72,8 +72,9 @@ static int64_t next_autocmd_id = 1;
 ///             - event (string|array): event or events to match against |autocmd-events|.
 ///             - pattern (string|array): pattern or patterns to match against |autocmd-pattern|.
 ///             Cannot be used with {buffer}
-///             - buffer: Buffer number or list of buffer numbers for buffer local autocommands
+///             - buffer number: Buffer number or list of buffer numbers for buffer local autocommands
 ///             |autocmd-buflocal|. Cannot be used with {pattern}
+///             - id number: Autocommand ID to match.
```
Comment (justinmk) [inline src/nvim/api/autocmd.c:77]: while we're here, sort these key names? they are in random order.

File: src/nvim/api/autocmd.c [hunk 3]
```diff
@@ -127,6 +128,11 @@ Array nvim_get_autocmds(Dict(get_autocmds) *opts, Arena *arena, Error *err)
     });
   }
 
+  int filter_id = -1;
```
Comment (justinmk) [inline src/nvim/api/autocmd.c:131]:
```suggestion
  int id = -1;
```

File: src/nvim/api/autocmd.c [hunk 4]
```diff
@@ -127,6 +128,11 @@ Array nvim_get_autocmds(Dict(get_autocmds) *opts, Arena *arena, Error *err)
...
+  if (HAS_KEY(opts, get_autocmds, id)) {
+    filter_id = (int)opts->id;
```
Comment (justinmk) [inline src/nvim/api/autocmd.c:133]: ternary?

File: test/functional/api/autocmd_spec.lua [hunk 5]
```diff
@@ -881,6 +881,93 @@ describe('autocmd api', function()
...
+      local _id, _id1
+      after_each(function()
+        api.nvim_del_autocmd(_id)
+        if _id1 then
+          api.nvim_del_autocmd(_id1)
+          _id1 = nil
+        end
+      end)
+
+      it('retrieves events using an ID', function()
```
Comment (justinmk) [inline test/functional/api/autocmd_spec.lua:895]: "retrieves" is an overly verbose word
```suggestion
      it('gets events by ID', function()
```

File: src/nvim/api/autocmd.c [hunk 6]
```diff
@@ -127,6 +128,11 @@ Array nvim_get_autocmds(Dict(get_autocmds) *opts, Arena *arena, Error *err)
     });
```
Comment (justinmk) [inline src/nvim/api/autocmd.c:128]: there is a TODO on line 96 that can be deleted now

File: test/functional/api/autocmd_spec.lua [hunk 7]
```diff
@@ -881,6 +881,93 @@ describe('autocmd api', function()
...
       end)
     end)
+
+    describe('id', function()
+      local _id, _id1
+      after_each(function()
+        api.nvim_del_autocmd(_id)
+        if _id1 then
+          api.nvim_del_autocmd(_id1)
+          _id1 = nil
```
Comment (justinmk) [inline test/functional/api/autocmd_spec.lua:891]: why is this needed? is clear() not called for each test?

Comment (glepnir) [reply test/functional/api/autocmd_spec.lua:891]: Aha thanks.

File: src/nvim/api/autocmd.c (hunk 2 above)
Comment (zeertzjq) [reply src/nvim/api/autocmd.c:74]: Having the type immediately after the field name without any separation is strange. It's better to put the type in parentheses. For example, the docstring from `nvim_get_hl` `opts` looks like this:
```c
/// @param opts  Options dict:
///                 - name: (string) Get a highlight definition by name.
///                 - id: (integer) Get a highlight definition by id.
///                 - link: (boolean, default true) Show linked group name instead of effective definition |:hi-link|.
///                 - create: (boolean, default true) When highlight group doesn't exist create it.
```

Comment (glepnir) [reply src/nvim/api/autocmd.c:74]: make sense.

Comment (glepnir) [reply src/nvim/api/autocmd.c]: also update the type  use integer and table instead of number array.

**Comment by przepompownia** [comment]
Works for me :)

File: test/functional/api/autocmd_spec.lua [hunk 8]
```diff
@@ -899,6 +899,89 @@ describe('autocmd api', function()
...
+            command = 'echo "hello"',
+            event = 'BufEnter',
+            id = id,
+            once = false,
+            pattern = '*',
+          },
+        }, api.nvim_get_autocmds({ id = id }))
+      end)
+
+      it('gets events by ID and group', function()
```
Comment (justinmk) [inline test/functional/api/autocmd_spec.lua:920]: let's just have 1 test for the "with other filters" case. we don't need to test every permutation. you can merge some of the filters from the below tests into this test, if possible, then drop the tests below.

```suggestion
      it('gets events by ID and other filters', function()
```

**Comment by justinmk** [comment]
LGTM after condensing the tests. Why in draft?

**Review by justinmk — APPROVED** [review]
