### PR TITLE
fix(lsp): decode 'null' in server responses as vim.NIL 

### LINKED ISSUE #31368: LSP: data properties will be removed if null
### Problem

Neovim provides `dataSupprt` for codeActions and publishDiagnostics

```
	/**
	 * Whether code action supports the `data` property which is
	 * preserved between a `textDocument/codeAction` and a
	 * `codeAction/resolve` request.
	 *
	 * @since 3.16.0
	 */
	dataSupport?: boolean;
```

```
/**
	 * A data entry field that is preserved on a code action between
	 * a `textDocument/codeAction` and a `codeAction/resolve` request.
	 *
	 * @since 3.16.0
	 */
	data?: [LSPAny](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#lspAny);
}
```

In the example notice that `REALLY_IMPORTANT_PARAM` is missing from the resolve request.

Because we serialise converting null to lua nils, when we decode and re-encode we lose properties in the data object

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
local requests = {
  ['initialize'] = function(_)
    return {
      --- @type lsp.ServerCapabilities
      capabilities = {
        codeActionProvider = {
          resolveProvider = true,
          codeActionKinds = { 'source' },
        },
      },
    }
  end,
  ['shutdown'] = function(_) end,
  ['textDocument/codeAction'] = function(_)
    ---@type lsp.CodeAction[]
    local action = {
      {
        title = 'Example Action',
        kind = 'source',
        data = {
          something = 'this',
          REALLY_IMPORTANT_PARAM = vim.NIL,
          something_else = 'that',
        },
      },
    }
    --- NOTE: Force serde as in memory lsp doesnt go through rpc
    local encoded = vim.json.encode(action)
    local decoded = vim.json.decode(encoded, { luanil = { object = true } })
    return decoded
  end,
  ['codeAction/resolve'] = function(params)
    print(vim.inspect(params))
	return {}
retu
  end,
}

local noops = {
  ['initialized'] = true,
}

local function server()
  local srv = {}
  local closing = false

  function srv.request(method, params, handler)
    coroutine.wrap(function()
      if requests[method] then
        local response = requests[method](params)
        handler(nil, response)
      elseif method == 'exit' then
        closing = true
      else
        vim.notify('Unhandled request: ' .. method)
      end
    end)()
  end

  function srv.notify(method, _params)
    coroutine.wrap(function()
      if method == 'exit' then
        closing = true
      elseif not noops[method] then
        vim.notify('Unhandled notification: ' .. method)
      end
    end)()
  end

  function srv.is_closing()
    return closing
  end

  function srv.terminate()
    closing = true
  end

  return srv
end

vim.lsp.start({
  name = 'serde_nil',
  cmd = server,
})
```

Perform a code action and see that the param is missing

### Expected behavior

Data properties to be preserved as null is a valid LSPAny value

```
/**
 * The LSP any type
 *
 * @since 3.17.0
 */
export type LSPAny = LSPObject | LSPArray | string | integer | uinteger |
	decimal | boolean | null;

```

### Nvim version (nvim -v)

0.11

### Language server name/version

Any

### Operating system/version

N/A

### Log file

_No response_

### PR DESCRIPTION
**Pull request by arkriny**
The current LSP parser treats absent fields and explicitly `null` fields the same, collapsing both into nil.

One possible solution would be to remove the 'object' flag and do explicit presence checks in all LSP handlers. But this would introduce a lot of unnecessary boilerplate in places where it doesn't matter, since the distinction between `null` and missing only matters for a few specific LSP types.

The fix I currently have in a draft state is to track `?|null` paths in a static tree, which is (ideally) generated from the spec. This allows handling of certain key paths explicitly and emit `vim.NIL` for `null`, keeping nil reserved for missing fields. This approach works and fixes #31368 and unblocks #34838.

However, it comes with some drawbacks: the parser doesn't know the actual expected type when encountering a key path like "result.data"; this path could appear in multiple methods, not just CodeAction responses.

What would be ideal is to make the parser type-aware. That is:

- Parse the top-level response object.

- Use the "id" to find the method name that was originally sent.

- With that context, parse the "result" or "error" field according to the expected schema for that method.

This is how it typically works in statically typed languages: the response handler already knows the expected structure, since it needs to allocate a concrete struct. In Lua, we don’t have static typing, and as far as I know, there’s no native way to enforce such schemas during deserialization.

A type-aware parser would not only solve the `null` vs `undefined` distinction cleanly, but also allow validating responses and reporting errors early if the server breaks the spec contract. It would give us fully type-safe LSP handlers.

At this point, I’m not sure in which direction I should continue. Should I explore building a proper type-aware parser, or focus on improving the current approach by generating the path tree from the spec and documenting it better?

I feel like I might be missing something, so I'd really appreciate any feedback, guidance, or alternative ideas.

### CODE REVIEW

**Comment by arkriny** [comment]
CC @justinmk @MariaSolOs

File: runtime/lua/vim/_meta/json.lua [hunk 1]
```diff
@@ -30,6 +30,10 @@ vim.json = {}
 ---                                   to Lua `nil` instead of |vim.NIL|.
 ---                                 - array: (boolean) When true, converts `null` in JSON arrays
 ---                                   to Lua `nil` instead of |vim.NIL|.
+---                                 - lsp: (boolean) Similar to `object`, but applies
```
Comment (MariaSolOs) [inline runtime/lua/vim/_meta/json.lua]: Should this behavior be specific to LSP? I can see it being helpful in other scenarios.

Comment (arkriny) [reply runtime/lua/vim/_meta/json.lua]: It could be unified, but then there should be a way to use alternative trees. I can also imagine passing the tree dynamically from Lua instead of defining it statically. However, as I mentioned earlier, I'm not sure how suitable this approach really is, since keys can collide between different types.

**Comment by arkriny** [comment]
Another idea I have is to add the ability to pass a list of keys to `decode()` that should not be decoded - leaving the corresponding nodes as-is in the final object (like json.RawMessage in Go). It would also make it possible to ignore decoding for fields like "data". For types with nullable fields, this would let us handle them specifically, since the expected type is already known. It’s a middle ground between the current parser and a fully type-aware parser that traverses the full expected schema tree.

File: runtime/lua/vim/_meta/json.lua (hunk 1 above)
Comment (mfussenegger) [reply runtime/lua/vim/_meta/json.lua]: I'd prefer keeping cjson decoupled from LSP.
It would be okayish to extend the luanil support to allow to parametrize concerte paths instead of a general true/false but overall I wonder if we instead shouldn't bite the bullet and deserialize null as vim.NIL for the LSP RPC and then handle vim.NIL everywhere as needed

Comment (arkriny) [reply runtime/lua/vim/_meta/json.lua]: > I wonder if we instead shouldn't bite the bullet and deserialize null as vim.NIL for the LSP RPC and then handle vim.NIL everywhere as needed

That seems like the right approach, and it might not require too many changes - after all, it's a server responsibility to follow the spec and do not return null for a `?` field.

But I'm concerned that we don't know how many servers actually rely on this client behavior. I can't imagine every server adapting quickly after users start seeing error messages on every LSP request after Neovim update - especially when VSC*de is completely fine with this kind of spec non-compliance.

Comment (mfussenegger) [reply runtime/lua/vim/_meta/json.lua]: > But I'm concerned that we don't know how many servers actually rely on this client behavior. I can't imagine every server adapting quickly after users start seeing error messages on every LSP request after Neovim update

We can use the dev cycle to learn that. Worst case we revert the commit before release if it would leave too many non-compliant servers broken

**Comment by arkriny** [comment]
test failing for some reason.. cant reproduce locally. No idea why typval.c is affected

**Comment by justinmk** [comment]
LGTM but would like approval from @MariaSolOs @lewis6991 @mfussenegger 

In the commit message, please include a brief Problem/Solution that explains the approach taken. Ideally mentioning the insight from https://github.com/neovim/neovim/issues/31368#issuecomment-2505732919

**Review by mfussenegger — COMMENTED** [review]
Does `documentSelector` need some additional vim.NIL handling, or are all current nil checks fine?

Other than that lgtm, although I think a news.txt entry would be justified as this affects all plugins using any of the properties that are defined with `|null`

**Comment by arkriny** [comment]
I fixed some `documentSelector` checks; other nullable fields don't appear to be affected.

I’m unsure how this should be reflected in news.txt. Should I try to collect an exhaustive list of all vim.lsp.* functions affected, or is a note about the change to the `lsp.null` alias sufficient? The type-level documentation already reflects the change.

As far as I can tell, only `vim.lsp.util.apply_text_document_edit()` and `vim.lsp.util.convert_signature_help_to_markdown_lines()` are affected.

File: runtime/doc/news.txt [hunk 2]
```diff
@@ -28,6 +28,7 @@ EXPERIMENTS
 
 LSP
 
+• Absence of values in LSP messages is now represented as |vim.NIL| instead of nil.
```
Comment (ribru17) [inline runtime/doc/news.txt]: I could be wrong, but I think this belongs in the regular breaking changes section, rather than breaking changes in head.

**Comment by arkriny** [comment]
Rebased on master and fixed result handling. The code appears stable in daily use and looks complete for this PR. Let me know if I should adjust documentation, commit message, news.txt, or testcases.

Also there seems to be an issue with oldtest checks (which you are likely already aware of).

**Comment by justinmk** [comment]
rebasing will fix the oldtest ci

**Comment by justinmk** [comment]
Thanks to reviewers, and thanks @skewb1k for digging into this.

**Comment by arkriny** [comment]
Appreciate all the help and guidance on this! Excited to be contributing to the project - you're all incredible.

**Comment by hrsh7th** [comment]
I have one question.

Now that this PR has been merged, should I consider it necessary to explicitly handle `vim.NIL` in LSP-related plugins?

`if response.items then ... end`
↓
`if response.items and response.items ~= vim.NIL then ... end`

**Comment by arkriny** [comment]
> Now that this PR has been merged, should I consider it necessary to explicitly handle `vim.NIL` in LSP-related plugins?     

Basically yes - if a field is defined as nullable in the spec, you should now handle `vim.NIL`.

> `if response.items then ... end` ↓ `if response.items and response.items ~= vim.NIL then ... end`

If items is both nullable and optional, then yes. But it's likely just one of the two. If a server confuses these properties, it's not spec-compliant and shouldn't need to be handled.

**Comment by hrsh7th** [comment]
The example code is written with backward compatibility in mind. If the plugin author wanted to make it work with both neovim stable and neovim nightly, an if statement like this would be necessary.

I will prepare a utility within the plugin to make the determination. Thank you for your reply.
