### PR TITLE
Vim insert setline undo fixes

### LINKED ISSUE #14: Undo not working properly in Vim8 and Neovim
I just installed this plugin; I'm using Vim 8.0 on macOS with patches: 1-1650 included. I'm seeing some odd behaviour when I undo. Let's say I have the following text in the buffer:

```clojure
(defn f
  [x]
  x)

(defn g
  [y]
  y)
```

I go to line 4, press `O` followed by `Enter` and insert another function so that my buffer looks like this:

```clojure
(defn f
  [x]
  x)

(defn h
  [z]
  z)

(defn g
  [y]
  y)
```

Now when I press `u` to undo, I get:

```clojure
(defn f
  [x]
  x
  []
  z)

(defn g
  [y]
  y)
```

whereas I would have expected something like the buffer in the first example above. Pressing `u` more times doesn't help - it keeps going through what appears to be a very long changelist but with no change being made to the buffer.

### PR DESCRIPTION
**Pull request by eraserhd**
These two patches from Vim fixed eraserhd/parinfer-rust#14 .

The first prevents corruption of undo history when setline() is called from a TextChangeI handler.  The second merges undo in insert mode to behave more like the user expects.

### CODE REVIEW

File: src/nvim/edit.c [hunk 1]
```diff
@@ -6117,6 +6125,7 @@ void free_last_insert(void)
 }
 
 #endif
+static int ins_apply_autocmds(event_T event);
```
Comment (justinmk) [inline src/nvim/edit.c]: forward declarations aren't needed, it's done automatically.

File: src/nvim/edit.c [hunk 2]
```diff
@@ -8673,6 +8682,24 @@ static char_u *do_insert_char_pre(int c)
   return res;
 }
 
+/*
+ * Trigger "event" and take care of fixing undo.
+ */
```
Comment (justinmk) [inline src/nvim/edit.c]: /// Trigger "event" and take care of fixing undo.

File: src/nvim/edit.c [hunk 3]
```diff
@@ -8673,6 +8682,24 @@ static char_u *do_insert_char_pre(int c)
...
+{
+  varnumber_T tick = buf_get_changedtick(curbuf);
+  int r;
+
+  r = apply_autocmds(event, NULL, NULL, FALSE, curbuf);
+
+  // If u_savesub() was called then we are not prepared to start
+  // a new line.  Call u_save() with no contents to fix that.
+  if (tick != buf_get_changedtick(curbuf))
+    u_save(curwin->w_cursor.lnum, (linenr_T)(curwin->w_cursor.lnum + 1));
```
Comment (justinmk) [inline src/nvim/edit.c]: lint will want braces : 

```
if (..) {
  ..
}
```

**Comment by janlazo** [comment]
Do any these 8.1.x patches depend on earlier 8.0.x patches?

**Comment by eraserhd** [comment]
@janlazo Nope.

I can demonstrate the issue is fixed with manual testing (the test case doesn't work because of missing `test_override()`).  I didn't bring any other code in, and it looked like the only surrounding changes were there from Neovim prior (e.g. `buf_get_changedtick(curbuf)` instead of `CHANGEDTICK(curbuf)` and formatting).

**Comment by eraserhd** [comment]
Ugh... OK, I tested a simple case, but this might not be working yet.  DO NOT MERGE.

**Comment by janlazo** [comment]
Did you check the blame for each file modified in the patch?
You're missing 8.1.0057.

**Comment by eraserhd** [comment]
@janlazo Oh, thanks.  I actually notice that I missed parts of the merge.  Maybe they weren't in the `.rej` files?  I'll check that, too.

**Comment by eraserhd** [comment]
OK, this necessarily deviates slightly from Vim:  Text from the relevant commit:

This deviates from Vim in the handling of the CursorHoldI event.  In
Vim, any buffer changes are merged into the insert.  In Neovim,
CursorHoldI is handled via the multiqueue, and the point at which
the cursor hold is implemented (in input.c) doesn't know enough about it.
Making all queued events merge into the insert seems more wronger since
changes by other asynchronous events really should be separately
undoable.

**Comment by eraserhd** [comment]
@janlazo @justinmk I think this looks good now.  See the comment above.  The Travis CI failure looks like a fluke, and everything else passes.

**Comment by janlazo** [comment]
@eraserhd Can you separate the changes from patch 8.1.0256 and your proposed deviation? It makes it easier to bisect and review. nvim is behind on autocmd and undo patches.

**Comment by eraserhd** [comment]
My current deviation is just omitting a patch segment that won't apply
(around EVENT_CURSORHOLDI Which no longer exists in Neovim), so there's
nothing to separate out.

(Doing something different would require adding code in input.c or edit.c)

**Comment by eraserhd** [comment]
*bump* Anything I can do to move this along?

**Comment by janlazo** [comment]
Wait for @justinmk or someone else to review again or add another vim-patch related to your changes (ie. undo) to test on current master.

**Comment by justinmk** [comment]
@eraserhd good choices, and thanks for including the explanation in the commit message.
