### PR TITLE
fix(lsp): filter code_action diagnostics to the cursor

### LINKED ISSUE #21985: vim.lsp.buf.code_action should get diagnostics at cursor, not line
### Describe the bug

Use `typescript-language-server` and  `vim.lsp.buf.code_action` returns wrong code actions 
I think`vim.lsp.buf.code_action` parameter diagnostics should be filtered by col. 
The related code is：
https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/buf.lua#L765

### Steps to reproduce

1. add a ts file like  that
```typescript
function a(x/**cursor here**/) {
  console.log(x)
}
export const b = 1
```
2. put the cursor at parameter x
3. execute vim.lsp.buf.code_action
4. the code action list has item ` Remove unused declaration for: 'x'`

### Expected behavior

the code action list has not ` Remove unused declaration for: 'x'`

### Neovim version (nvim -v)

NVIM v0.9.0-dev-7ef5e363d-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

windows wsl2

### Terminal name/version

window terminal 1.15

### $TERM environment variable

xterm-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by barrettruth**
:backlog:

Fixes #21985.

## Problem

`vim.lsp.buf.code_action()` sends every diagnostic on the current line rather than just those under the cursor.

The desired behavior seems to have been settled in the thread.

## Solution

Filter same-line diagnostics down to the cursor position for cursor-position requests. Of course, leave explicit/visual ranges unchanged.

### CODE REVIEW

File: test/functional/plugin/lsp_spec.lua [hunk 1]
```diff
@@ -4811,6 +4811,109 @@ describe('LSP', function()
       }
     end)
 
+    it('uses diagnostics at cursor position', function()
```
Comment (barrettruth) [inline test/functional/plugin/lsp_spec.lua:4814]: test is pretty long - couldn't find any helpers to make it more succinct.

Comment (barrettruth) [reply test/functional/plugin/lsp_spec.lua:4814]: could be combined with another test that tests both code action response + cursor pos filtering... but tbh don't know which approach is better

File: runtime/lua/vim/lsp/buf.lua [hunk 2]
```diff
@@ -1296,6 +1296,24 @@ local function on_code_action_results(results, opts)
...
 
+---@param diagnostic vim.Diagnostic
+---@param bufnr integer
+---@param lnum integer
+---@param col integer
+---@return boolean
+local function diagnostic_contains_cursor(diagnostic, bufnr, lnum, col)
+  local start = vim.pos(bufnr, diagnostic.lnum, diagnostic.col)
+  local finish =
+    vim.pos(bufnr, diagnostic.end_lnum or diagnostic.lnum, diagnostic.end_col or diagnostic.col)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/buf.lua:1320]: nice to see use of `vim.pos`. would `vim.range.has()` be useful here?

File: runtime/lua/vim/lsp/buf.lua [hunk 3]
```diff
@@ -1317,6 +1335,13 @@ function M.code_action(opts)
   local mode = api.nvim_get_mode().mode
   local bufnr = api.nvim_get_current_buf()
   local win = api.nvim_get_current_win()
+  local range = opts.range
+  local cursor = api.nvim_win_get_cursor(win)
+  local lnum = cursor[1] - 1
+  local col = cursor[2]
+  if range == nil and (mode == 'v' or mode == 'V') then
+    range = range_from_selection(bufnr, mode)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/buf.lua:1353]: nit: could move this near the range assignment on line 1338

File: test/functional/plugin/lsp_spec.lua (hunk 1 above)
Comment (justinmk) [reply test/functional/plugin/lsp_spec.lua]: shoudl this test live in `test/functional/plugin/lsp/diagnostic_spec.lua` ?

Comment (barrettruth) [reply test/functional/plugin/lsp_spec.lua]: there was a conflict so after rebase it got moved back next to the other vim lsp buf code action tests where it makes more sense to be imo

File: runtime/lua/vim/lsp/buf.lua (hunk 2 above)
Comment (barrettruth) [reply runtime/lua/vim/lsp/buf.lua:1320]: i considered it but `vim.range.has()`'s pos path is end-inclusive, but LSP diagnostic ranges are end-exclusive so the logic wouldn't match up or offsetting by one would be more confusing

File: runtime/lua/vim/lsp/buf.lua (hunk 3 above)
Comment (barrettruth) [reply runtime/lua/vim/lsp/buf.lua:1353]: done

File: runtime/lua/vim/lsp/buf.lua (hunk 2 above)
Comment (justinmk) [reply runtime/lua/vim/lsp/buf.lua:1320]: ok, do we need to add a feature/parameter to `vim.range.has()` ? please consider raising an issue to track that
