### PR TITLE
fix(statuscolumn): foldcolumn buffer is too small

### LINKED ISSUE #21759: Display problem with new statuscolumn and fold-related fill characters
### Describe the bug

When using a multibyte character for one of the fold-related fillchars, the gutter displaying the folds gets messed up (see screenshot)

This happens only when having multiple nested folds and foldcolumn at 4 or higher. It's reproducible with a --clean config with minimal settings and multiple terminal emulators (alacritty, konsole, kitty) and $TERM settings. **Only tested on Linux**

I'm using a nerd font, maybe that's of importance.

Setting the foldsep fill character to │ (0x2502) (or possible any other multibyte character) triggers the problem. Using a single-byte character like | or ¦ works normally.

foldbug

After setting foldcolumn=3 the gutter looks normal again

foldbug1

When using the pipe character as foldsep, it also displays normally.

foldbug2

### Steps to reproduce

nvim --clean -u ./minimal.vim

minimal config required:
* set foldcolumn=4 (or higher)
* vim.o.fillchars = [[eob: ,fold: ,foldopen:-,foldsep:│,foldclose:+]]
* set statuscolumn=%@SignCb@%=%s%=%T%#NumCb#%l\ %C%#Normal#│\ 

* create at least 4 nested folds and open them. Closed folds display normally.

### Expected behavior

properly displayed folding guides in the gutter.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-658+g80a02d1ce

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Linux warpcore 6.0.18-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 7 17:10:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Terminal name/version

alacritty 0.11.0

### $TERM environment variable

alacritty

### Installation

built from source

### PR DESCRIPTION
**Pull request by luukvbaal**
Resolve https://github.com/neovim/neovim/issues/21759.

### CODE REVIEW

File: src/nvim/buffer_defs.h [hunk 1]
```diff
@@ -1426,7 +1426,7 @@ struct statuscol {
   int sign_attr[SIGN_SHOW_MAX + 1];    ///< attributes used for signs
   int truncate;                        ///< truncated width
   bool draw;                           ///< draw statuscolumn or not
-  char fold_text[10];                  ///< text in fold column (%C)
+  char fold_text[9 * 4 + 1];           ///< text in fold column (%C)
```
Comment (lewis6991) [inline src/nvim/buffer_defs.h:1429]: These numbers are a big magic. Why 9, 4 and 1?

Comment (max397574) [reply src/nvim/buffer_defs.h:1429]: foldcolumn can be 1-9 (according to docs)
unicode characters take up to 4 bytes
not sure about the +1

Comment (lewis6991) [reply src/nvim/buffer_defs.h:1429]: I would those as defines similar to `SIGN_SHOW_MAX`.
