### PR TITLE
fix(decor): revise marktree metadata for invalid marks

### LINKED ISSUE #30197: crash with extmarks "invalidate" flag, using plugin grug-far.nvim ":GrugFar astgrep"
### Problem

When using the plugin [grug-far.nvim](https://github.com/MagicDuck/grug-far.nvim) on Neovim nightly, Neovim crashes. The problem does not occur on Neovim stable 0.10.1. 

It seems to be connected with `statuscolumn`. When `vim.opt.statuscolumn = ""` (empty string the default value) then the problem does not occur. But when you set `vim.opt.statuscolumn = " "` (just an empty space although I've also tried `vim.opt.statuscolumn = "%s %C"` after the plugin's maintainer's suggestion) then Neovim crashes with 
```shell
nvim: /home/runner/work/neovim/neovim/src/nvim/decoration.c:849: buf_signcols_count_range: Assertion `buf->b_signcols.count[prevwidth - 1] >= 0' failed
```

Relevant [issue at `grug-far` repo](https://github.com/MagicDuck/grug-far.nvim/issues/234).
### Steps to reproduce

`nvim --clean -u minimal.lua`
```lua
-- minimal.lua
-- Run this file as `nvim --clean -u minimal.lua`

for name, url in pairs({
	-- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
	-- some_plugin = 'https://github.com/author/plugin.nvim'
	grug_far = "https://github.com/MagicDuck/grug-far.nvim",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS _NECESSARY_ FOR REPRODUCING THE ISSUE
vim.opt.statuscolumn = " " -- (just an empty space here)

require("grug-far").setup({})
```
After Neovim opens run `GrugFar astgrep` and in the `Search` field type the following
```
if $A then
$B
end
```
Some times it crashes right when you type in the `Search` field, other times when you complete the `Search` field and move on to the `Replace` field.

Here is the backtrace after running `nvim --clean -u minimal.lua` and run `sudo gdb -p $pid` (after getting the pid with `echo getpid()`) in a different terminal instance.
```shell
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140415420049216) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140415420049216) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140415420049216, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fb503406476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fb5033ec7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fb5033ec71b in __assert_fail_base (fmt=0x7fb5035a1130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x563258861dc8 "buf->b_signcols.count[prevwidth - 1] >= 0", 
    file=0x563258861c10 "/home/runner/work/neovim/neovim/src/nvim/decoration.c", line=849, function=<optimized out>)
    at ./assert/assert.c:92
#6  0x00007fb5033fde96 in __GI___assert_fail (
    assertion=assertion@entry=0x563258861dc8 "buf->b_signcols.count[prevwidth - 1] >= 0", 
    file=file@entry=0x563258861c10 "/home/runner/work/neovim/neovim/src/nvim/decoration.c", line=line@entry=849, 
    function=function@entry=0x563258861fb0 <__PRETTY_FUNCTION__.1.lto_priv.4> "buf_signcols_count_range")
    at ./assert/assert.c:101
#7  0x000056325853c02f in buf_signcols_count_range (buf=buf@entry=0x56325a3c18e0, row1=row1@entry=7, row2=row2@entry=8, 
    add=add@entry=-1, clear=clear@entry=kFalse) at /home/runner/work/neovim/neovim/src/nvim/decoration.c:849
#8  0x000056325853c1ce in buf_remove_decor_sh (buf=buf@entry=0x56325a3c18e0, row1=row1@entry=7, row2=row2@entry=8, 
    sh=sh@entry=0x56325a4df5a0) at /home/runner/work/neovim/neovim/src/nvim/decoration.c:233
#9  0x000056325853c263 in buf_decor_remove (buf=0x56325a3c18e0, row1=7, row2=8, col1=<optimized out>, decor=..., 
    free=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/decoration.c:219
#10 0x00005632585c7256 in extmark_del (buf=buf@entry=0x56325a3c18e0, itr=itr@entry=0x7ffd7c03adc0, key=..., 
    restore=restore@entry=true) at /home/runner/work/neovim/neovim/src/nvim/extmark.c:187
#11 0x00005632585c7e21 in extmark_clear (buf=0x56325a3c18e0, ns_id=4, l_row=<optimized out>, l_col=<optimized out>, 
    u_row=2147483646, u_col=2147483647) at /home/runner/work/neovim/neovim/src/nvim/extmark.c:229
#12 0x00005632584e9d23 in nvim_buf_clear_namespace (buffer=<optimized out>, ns_id=4, line_start=0, line_end=2147483647, 
    err=0x7ffd7c03af10) at /home/runner/work/neovim/neovim/src/nvim/api/extmark.c:980
#13 0x00005632586038e8 in nlua_api_nvim_buf_clear_namespace (lstate=0x7fb502dd6380)
    at /home/runner/work/neovim/neovim/build/src/nvim/auto/lua_api_c_bindings.generated.h:3299
#14 0x00005632587e5346 in lj_BC_FUNCC ()
--Type <RET> for more, q to quit, c to continue without paging--c
#15 0x00005632587d1576 in lua_pcall (L=L@entry=0x7fb502dd6380, nargs=nargs@entry=0, nresults=nresults@entry=0, errfunc=errfunc@entry=-2) at lj_api.c:1122
#16 0x000056325861017d in nlua_pcall (lstate=lstate@entry=0x7fb502dd6380, nargs=nargs@entry=0, nresults=nresults@entry=0) at /home/runner/work/neovim/neovim/src/nvim/lua/executor.c:174
#17 0x00005632586176e9 in nlua_schedule_event (argv=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/lua/executor.c:372
#18 0x0000563258708b3b in state_handle_k_event () at /home/runner/work/neovim/neovim/src/nvim/state.c:119
#19 0x000056325855958c in insert_handle_key (s=s@entry=0x7ffd7c03b190) at /home/runner/work/neovim/neovim/src/nvim/edit.c:902
#20 0x0000563258559ef1 in insert_execute (state=0x7ffd7c03b190, key=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/edit.c:693
#21 0x00005632587089c1 in state_enter (s=0x7ffd7c03b190) at /home/runner/work/neovim/neovim/src/nvim/state.c:101
#22 0x00005632585564a4 in insert_enter (s=s@entry=0x7ffd7c03b190) at /home/runner/work/neovim/neovim/src/nvim/edit.c:342
#23 0x00005632585567f7 in edit (cmdchar=97, startln=<optimized out>, count=1) at /home/runner/work/neovim/neovim/src/nvim/edit.c:1292
#24 0x000056325866513c in normal_finish_command (s=s@entry=0x7ffd7c03b280) at /home/runner/work/neovim/neovim/src/nvim/normal.c:1042
#25 0x00005632586656e3 in normal_execute (state=0x7ffd7c03b280, key=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/normal.c:1234
#26 0x00005632587089c1 in state_enter (s=0x7ffd7c03b280) at /home/runner/work/neovim/neovim/src/nvim/state.c:101
#27 0x00005632586640db in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/normal.c:520
#28 0x00005632586237fe in main (argc=5, argv=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/main.c:661
```

### Expected behavior

Neovim nightly should not crash just like Neovim stable 0.10.1 doesn't crash.

### Neovim version (nvim -v)

NVIM v0.11.0-dev-680+g4353996d0

### Vim (not Nvim) behaves the same?

I've not tried.

### Operating system/version

Linux Mint 21.3

### Terminal name/version

kitty 0.36.1

### $TERM environment variable

xterm-kitty

### Installation

I used [bob](https://github.com/MordechaiHadad/bob) to install Neovim (both stable and latest nightly).

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Marktree meta count still includes invalidated marks, making
          guards that check the meta total ineffective.
Solution: Revise marktree metadata when in/revalidating a mark.

Fix #30197

### CODE REVIEW

File: src/nvim/extmark.c [hunk 1]
```diff
@@ -394,6 +414,7 @@ void extmark_splice_delete(buf_T *buf, int l_row, colnr_T l_col, int u_row, coln
         } else {
           invalidated = true;
           mt_itr_rawkey(itr).flags |= MT_FLAG_INVALID;
+          mt_meta_invalid(buf->b_marktree, mark, true);
```
Comment (bfredl) [inline src/nvim/extmark.c:417]: Hmm, instead of keeping an extra ` meta_invalid` counter we should actually remove the count from `meta_root` and also any other parent node (and add them back on undo, if re-ravidated). as invalid nodes are not rendered it is safe to skip them when actually using the meta counts to filter nodes at render time.

Comment (luukvbaal) [reply src/nvim/extmark.c:417]: Yeah that's what I started implementing at first but when I realized that those counters probably propagate throughout the child/parent nodes I wasn't sure the added complexity would be worth it (if I even managed to figure out how to implement it in marktree.c). I could take another look if that's what we want to do.

Comment (bfredl) [reply src/nvim/extmark.c:417]: I think we should be able to reuse `marktree_revise_flags` which already does this. `meta_describe_key` needs an extra condition to exclude invalid nodes, just like we already exclude end nodes.

**Comment by bfredl** [comment]
nice cleanup, thanks!
