### PR TITLE
fix(treesitter): select with node ending with unicode char

### LINKED ISSUE #38548: treesitter: incremental selection doesn't extend if last char is multibyte
### Problem

Incremental selection doesn't extend if last char is multibyte.

### Steps to reproduce

1. Run `nvim --clean test.lua` with the following `test.lua`:
```lua
local s = 'abc…'
```
2. Type `fbvan`, `abc…` is selected.
3. Continue typing `an`, the selection doesn't extend.

### Expected behavior

The selection extends at steps 3.

### Nvim version (nvim -v)

v0.12.0-dev-2722+g5a7df03b42

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.46.2

### $TERM environment variable

xterm-kitty

### Installation

AUR neovim-git

### PR DESCRIPTION
**Pull request by altermo**
fix https://github.com/neovim/neovim/issues/38548

The reason to not use `getregionpos` for the whole thing is because it handles eol differently.

### CODE REVIEW

File: runtime/lua/vim/treesitter/_select.lua [hunk 1]
```diff
@@ -381,14 +381,17 @@ local function get_selection()
...
 
-  if range[4] == #vim.fn.getline(range[3] + 1) + 1 then
-    range[3] = range[3] + 1
-    range[4] = 0
+  if pos2[3] == #vim.fn.getline(pos2[2]) + 1 then
+    pos2[2] = pos2[2] + 1
+    pos2[3] = 0
+  else
+    -- set {pos2} to pos of last byte of character under {pos2} (rather than first)
+    local r = vim.fn.getregionpos(pos2, pos2)
```
Comment (zeertzjq) [inline runtime/lua/vim/treesitter/_select.lua]:
```suggestion
    local r = vim.fn.getregionpos(pos2, pos2, { exclusive = false })
```
