### PR TITLE
fix(lsp): highlight active parameter in signature help

### LINKED ISSUE #25662: bug(lsp): active parameter not highlighted in signature help
### Problem

The active parameter is no longer highlighted in the floating window for signature help:
image

This seems to have been a regression from #25073

### Steps to reproduce

1. Using a language server that supports signature help (like LuaLS), invoke `vim.lsp.buf.signature_help` in insert mode and while filing up the parameters of a function call (e.g. `vim.keymap.set`).
2. Notice how the active parameter in the respective floating window doesn't have the highlights from `hl-LspSignatureActiveParameter`.

### Expected behavior

For the active parameter to be highlighted as specified by `hl-LspSignatureActiveParameter`.

### Neovim version (nvim -v)

v0.10.0-dev-1351+g28ef4a449

### Vim (not Nvim) behaves the same?

No

### Operating system/version

macOS Sonoma 14.0

### Terminal name/version

kitty 0.30.1

### $TERM environment variable

xterm-kitty

### Installation

From source

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #25662

### CODE REVIEW

File: runtime/lua/vim/lsp/handlers.lua [hunk 1]
```diff
@@ -476,15 +476,17 @@ function M.signature_help(_, result, ctx, config)
     vim.tbl_get(client.server_capabilities, 'signatureHelpProvider', 'triggerCharacters')
   local ft = vim.bo[ctx.bufnr].filetype
   local lines, hl = util.convert_signature_help_to_markdown_lines(result, ft, triggers)
-  if vim.tbl_isempty(lines) then
+  if not lines or vim.tbl_isempty(lines) then
```
Comment (bew) [inline runtime/lua/vim/lsp/handlers.lua:479]: Wouldn't it be better to normalize the markdown lines in `convert_signature_help_to_markdown_lines` ?

Comment (MariaSolOs) [reply runtime/lua/vim/lsp/handlers.lua:479]: Not sure I understand what you mean by "normalize".

Comment (bew) [reply runtime/lua/vim/lsp/handlers.lua:479]: I mean: make the return of `convert_signature_help_to_markdown_lines` always return the signature in the first line, without ```` ``` ````s.
That function naming looks like a good candidate for that behavior

(note that I'm an outsider here, I don't have much knowledge on this part of the code, I'm just curious why you made a check after a conversion function instead of changing the conversion function to always return the same format of output)

Comment (MariaSolOs) [reply runtime/lua/vim/lsp/handlers.lua:479]: `convert_signature_help_to_markdown_lines` converts the input text to Markdown content. Given that we want to display the signature with the Treesitter highlights of the respective language and we use the Markdown parser for these floating windows, the code block is necessary.

Comment (MariaSolOs) [reply runtime/lua/vim/lsp/handlers.lua:479]: The reason why this is conditional is because LSP Markdown content could also be `plaintext`, and in such case we don't add any Markdown decorations and display the content as is.

Comment (bew) [reply runtime/lua/vim/lsp/handlers.lua:479]: Make sense, thanks 👍
(can mark this discussion as resolved)

Comment (MariaSolOs) [reply runtime/lua/vim/lsp/handlers.lua:479]: It's okay! I appreciate your input and please ask all the questions you want :)

**Review by justinmk — APPROVED** [review]
is this ready to merge?
