### PR TITLE
fix(prompt): ignore 'modified' flag

### LINKED ISSUE #14116: prompt buffer: ignore 'modified' state
[nvim-dap](https://github.com/mfussenegger/nvim-dap) uses `buftype=prompt` for the debug REPL.

It looks as if by default any input to a prompt buffer sets the `modified` flag. This is a bit annoying for the REPL case, because users usually don't care whether the REPL is modified or not and they shouldn't get a "Did not save [dap-repl]" message. So I added something like this:

```
api.nvim_buf_attach(buf, false, {
  on_lines = function(b)
    api.nvim_buf_set_option(b, 'modified', false)
  end;
  on_changedtick = function(b)
    api.nvim_buf_set_option(b, 'modified', false)
  end;
  ...
```

But this workaround had the side effect of [breaking the backspace key](https://github.com/mfussenegger/nvim-dap/issues/119) in that after you type something you can no longer remove the characters with backspace.

Is there any other good way to that would allow to treat a prompt buffer like a terminal or `nofile` where modifications don't matter?

### PR DESCRIPTION
**Pull request by Willaaaaaaa**
## Problem

In aec3d7915c55fc0b7dc73f6186cf0ae45d416d33 Vim changed prompt-buffers to respect 'modified' so the termdebug plugin can "control closing the window".

But for most use-cases of prompt-buffers (such as REPLs, shells, AI "chat", …), the 'modified' flag is irrelevant because:

- prompt-buffers are in practice always "modified", and no way to "save" them, so *implicitly* setting 'modified' is noisy and annoying.

 

## Solution

Don't implicitly set 'modified' when a prompt-buffer is updated. (Plugins/users can still explicitly set 'modified' (`:set modified`)).

~~Update `termdebug.vim` to define a `QuitPre` handler instead of depending on 'modified'.~~

~~Prompt buffers always ignore modified checks, so setting 'modified' does not block closing the prompt window.~~

Resolve: #14116

### CODE REVIEW

**Comment by Willaaaaaaa** [comment]
```log
 FAILED   1 test, listed below:
FAILED   test/functional/legacy/prompt_buffer_spec.lua @ 567: prompt buffer o/O can create new lines
test/functional/legacy/prompt_buffer_spec.lua:653: Row 1 did not match.
Expected:
  |*line 4                   |
  |*after prompt             |
  |line 5"                  |
  |cmd: ^                    |
  |{3:[Prompt]                 }|
  |other buffer             |
  |{1:~                        }|
  |{1:~                        }|
  |{1:~                        }|
  |{5:-- INSERT --}             |
Actual:
  |*after                    |
  |*line 3"                  |
  |line 5"                  |
  |cmd: ^                    |
  |{3:[Prompt]                 }|
  |other buffer             |
  |{1:~                        }|
  |{1:~                        }|
  |{1:~                        }|
  |{5:-- INSERT --}             |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.

Snapshot:
screen:expect([[
  after                    |
  line 3"                  |
  line 5"                  |
  cmd: ^                    |
  {3:[Prompt]                 }|
  other buffer             |
  {1:~                        }|*3
  {5:-- INSERT --}             |
]])

stack traceback:
	test/functional/ui/screen.lua:909: in function '_wait'
	test/functional/ui/screen.lua:537: in function 'expect'
	test/functional/legacy/prompt_buffer_spec.lua:653: in function <test/functional/legacy/prompt_buffer_spec.lua:567>
```

Strange... I can't reproduce the ci failure above by neither running `TEST_FILE=test/functional/legacy/prompt_buffer_spec.lua make functionaltest` nor using nvim manually.

my try:
```
$ TEST_FILE=test/functional/legacy/prompt_buffer_spec.lua make functionaltest
mkdir -p ".deps"
/usr/bin/cmake -S /home/willaaaaaaa/dev/neovim//cmake.deps -B ".deps" -G "Ninja" 
-- Found GNU Make at /usr/bin/gmake
-- CMAKE_BUILD_TYPE=Release
-- Configuring done (0.8s)
-- Generating done (0.0s)
-- Build files have been written to: /home/willaaaaaaa/dev/neovim/.deps
mkdir -p build
touch "build/.ran-deps-cmake"
/usr/bin/cmake --build ".deps"
ninja: no work to do.
/usr/bin/cmake --build build --target functionaltest
[0/2] Re-checking globbed directories...
[2/3] cd /home/willaaaaaaa/dev/neovim/build/test && /usr/bin/cmake -D TEST_TYPE=fu...=/home/willaaaaaaa/dev/neovim -P /home/willaaaaaaa/dev/neovim/cmake/RunTests.cmake
-------- Global test environment setup.
-------- Running tests from test/functional/legacy/prompt_buffer_spec.lua
RUN      T1 prompt buffer works: 42.00 ms OK
RUN      T2 prompt buffer editing: 37.00 ms OK
RUN      T3 prompt buffer switch windows: 20.00 ms OK
RUN      T4 prompt buffer keeps insert mode after aucmd_restbuf in callback: 8.00 ms OK
RUN      T5 prompt buffer accessing hidden prompt buffer does not start insert mode: 3.00 ms OK
RUN      T6 prompt buffer modifying hidden buffer does not prevent prompt buffer mode change: 2.00 ms OK
RUN      T7 prompt buffer can insert multiline text: 72.00 ms OK
RUN      T8 prompt buffer can put (p) multiline text: 31.00 ms OK
RUN      T9 prompt buffer can put multiline text with nvim_paste: 13.00 ms OK
RUN      T10 prompt buffer can undo current prompt: 73.00 ms OK
RUN      T11 prompt buffer o/O can create new lines: 44.00 ms OK
RUN      T12 prompt buffer deleting prompt adds it back on insert: 22.00 ms OK
RUN      T13 prompt buffer sets the ': mark: 3.00 ms OK
RUN      T14 prompt buffer don't block closing when modified: 1.00 ms OK
RUN      T15 prompt buffer prompt_getinput returns current prompts text: 1.00 ms OK
RUN      T16 prompt buffer programmatic (non-user) edits: 21.00 ms OK
RUN      T17 prompt buffer works correctly with empty string as prompt: 15.00 ms OK
RUN      T18 prompt buffer prompt can be changed without interrupting user input: 66.00 ms OK
-------- 18 tests from test/functional/legacy/prompt_buffer_spec.lua (1363.00 ms total)

-------- Global test environment teardown.

======== 18 tests from 1 test file of test/functional/legacy/prompt_buffer_spec.lua ran. (1364.00 ms total)
PASSED   18 tests.
```

**Comment by Willaaaaaaa** [comment]
The test case in question: `prompt buffer o/O can create new lines`
This time it passed on **freebsd** but still failed on all other ci jobs. Maybe it's a timing issue? Any possible workaround to make the test stable? I’m happy to adjust it.

**Comment by glepnir** [comment]
emm not a timing issue🤔 can't we do it like this, I don't test it but I guess it can works.

```diff
diff --git a/src/nvim/buffer.c b/src/nvim/buffer.c
index 829d4d2392..62f70dbc29 100644
--- a/src/nvim/buffer.c
+++ b/src/nvim/buffer.c
@@ -4046,7 +4046,7 @@ bool bt_dontwrite_msg(const buf_T *const buf)

 /// @return  true if the buffer should be hidden, according to 'hidden', ":hide"
 ///          and 'bufhidden'.
-bool buf_hide(const buf_T *const buf)
+bool buf_hide(buf_T* const buf)
   FUNC_ATTR_PURE
 {
   // 'bufhidden' overrules 'hidden' and ":hide", check it first
@@ -4058,6 +4058,10 @@ bool buf_hide(const buf_T *const buf)
   case 'h':
     return true;            // "hide"
   }
+  // prompt buffer can always be abandoned even when modified
+  if (bt_prompt(buf)) {
+    return true;
+  }
   return p_hid || (cmdmod.cmod_flags & CMOD_HIDE);
 }
```

You also forgot to update the  `help modified`.

**Comment by Willaaaaaaa** [comment]
@glepnir Thanks for your quick and kind suggestion. I think your implementation only bypasses the "can't close when prompt buffer when modified" situation, and meanwhile, the buffer is still marked as 'modified'. But consider this, if we ignore modified for prompt buffers, why should it be marked as 'modified' in the first place?
And I quite agree with @justinmk , "[editing a prompt marks the buffer as 'modified', this is usually just unwanted and annoying](https://github.com/neovim/neovim/issues/34561#issue-3156808206)"

**Comment by glepnir** [comment]
emm `bufIsChanged` is called in multiple places, and it also affects the flag shown in the statusline. the prompt buffer is still `modifiable` see `help modifiable`. I tried using this diff patch, The test case you added also passes when using diff patch. However, the case that fails in CI also fails locally for me — but if I use diff, it passes. I’m not very familiar with the prompt buffer other opinions on this.

Edit:
We are only ignoring the modified flag when closing the buffer. We should not remove the modifiable or modified indicator from the statusline. If the buffer has been modified, it is correct and expected for the statusline to show it as modified.

**Comment by Willaaaaaaa** [comment]
Thank you again for your further explanation. 

I understand your concern that the changes to `bufIsChanged` will affect a lot, but that's exactly what my PR is trying to address.

And, what I'm doing is somewhat like modifying semantics. I believe the prompt buffer is mainly for interaction purposes, **not persistent content**, and saving such contents is an extremely rare need in my opinion. So, simply fixing the "blocking close" issue is only one aspect, semantic modification for `prompt buffer` is also necessary (well, at least to me).

And if I manage to fix the ci failure (I still can't reproduce it somehow.... I'll try to figure it out), should this be a good/acceptable solution?

**Comment by glepnir** [comment]
For me, after using PR code, this test also failed on my local machine. 

 `TEST_FILTER=create TEST_FILE=test/functional/legacy/prompt_buffer_spec.lua make test`

**Comment by Willaaaaaaa** [comment]
> For me, after using PR code, this test also failed on my local machine.
> 
> `TEST_FILTER=create TEST_FILE=test/functional/legacy/prompt_buffer_spec.lua make test`

Finally reproduced it by making my cpu busy. Otherwise, I can't reproduce it.
Still think it's a timing issue.... trying to figure it out~~

File: src/nvim/options.lua [hunk 1]
```diff
@@ -5933,8 +5924,8 @@ local options = {
         result of a BufNewFile, BufRead/BufReadPost, BufWritePost,
         FileAppendPost or VimLeave autocommand event.  See |gzip-example| for
         an explanation.
-        When 'buftype' is "nowrite" or "nofile" this option may be set, but
-        will be ignored.
+        When 'buftype' is "nowrite", "nofile" or "prompt", this option may be
+        set, but will be ignored and will not block closing the window.
```
Comment (glepnir) [inline src/nvim/options.lua]:
```suggestion
        set, but it will be ignored and will not block closing the window.
```

**Comment by Willaaaaaaa** [comment]
@glepnir A gentle ping~~ Is there anything I can do to help move this forward, or any remaining concerns that still block approval? And if it would be helpful to get another maintainer’s take, I’m totally happy to wait.

File: test/functional/legacy/prompt_buffer_spec.lua [hunk 2]
```diff
@@ -760,6 +768,19 @@ describe('prompt buffer', function()
     eq({ 13, 6 }, api.nvim_buf_get_mark(0, ':'))
   end)
 
+  it("don't block closing when modified", function()
+    command('new')
+    command('set buftype=prompt')
+    command('set modified')
+    command('startinsert')
+
+    feed('abc<BS><BS>')
```
Comment (glepnir) [inline test/functional/legacy/prompt_buffer_spec.lua]:
```suggestion
    command('set buftype=prompt modified')

    feed('iabc<BS><BS>')
```

File: src/nvim/undo.c [hunk 3]
```diff
@@ -3097,9 +3097,9 @@ static char *u_save_line_buf(buf_T *buf, linenr_T lnum)
 bool bufIsChanged(buf_T *buf)
   FUNC_ATTR_NONNULL_ALL FUNC_ATTR_WARN_UNUSED_RESULT
 {
-  // In a "prompt" buffer we do respect 'modified', so that we can control
-  // closing the window by setting or resetting that option.
-  return (!bt_dontwrite(buf) || bt_prompt(buf))
+  // A "prompt" buffer ignores the 'modified' flag, so it won't block closing
+  // when modified.
```
Comment (justinmk) [inline src/nvim/undo.c]: The old comment is a hint that maybe the behavior was intentional. Looking at the git history shows https://github.com/neovim/neovim/commit/aec3d7915c55fc0b7dc73f6186cf0ae45d416d33 . So now we need to decide the tradeoffs.

File: test/functional/legacy/prompt_buffer_spec.lua [hunk 4]
```diff
@@ -760,6 +768,17 @@ describe('prompt buffer', function()
...
   end)
 
+  it("don't block closing when modified", function()
+    command('new')
+    command('set buftype=prompt modified')
+
+    feed('iabc<BS><BS>')
+    eq('a', fn('prompt_getinput', fn('bufnr')))
+
+    command('quit')
```
Comment (justinmk) [inline test/functional/legacy/prompt_buffer_spec.lua]: can we just add this to the existing "works" test on line 73

**Review by justinmk — APPROVED** [review]
Edit: blocked waiting for confirmation of https://github.com/neovim/neovim/issues/14116#issuecomment-4012962948

---

This essentially reverts https://github.com/neovim/neovim/commit/aec3d7915c55fc0b7dc73f6186cf0ae45d416d33 , but it's low risk and easy to re-revert so let's try it. Not clear how urgent that use-case was.

Future note: if we need to revert this, let's try to find a compromise, e.g. only certain kinds of input set 'modified' ? Or maybe plugins can opt-in to this behavior somehow.

File: src/nvim/undo.c (hunk 3 above)
Comment (Willaaaaaaa) [reply src/nvim/undo.c]: Yes. As a matter of fact, the origin "prompt buffer respects modified" behavior looks like that it's intentionally designed for `Termdebug`. However, I think it is ~quite hacking~ and seems only in windows can it open as a `prompt buffer`, and in non-win, it still uses `terminal buffer`, which means **no** "it's not easy to close" effect achieved under non-win whatsoever.

So as far as I can see, we should make prompt buffer ignore `modified` by default, and if the plugin _truly_ wants to achieve "it's not easy to close" effect, it should forbid `:q` via `QuitPre` and `:q!` can do the job.

**Comment by Willaaaaaaa** [comment]
Thank you for the very careful and rigorous review. I must admit that my approach was indeed somewhat breaking, but I believe it won’t do much harm. This mainly affects:
- Termdebug (prompt mode) no longer “hard to close.” (I update the relevant logic in the latest commit)
- Any plugin that used prompt buffers and relied on `modified` semantics.

> only certain kinds of input set 'modified' 

I think this might be complicated in practice, I can't think of a good approach at least.

> Or maybe plugins can opt-in to this behavior somehow

Sounds like a better compromise! Make prompt buffers ignore modified by default, and provide a plugin‑level opt‑in so plugin can explicitly make a prompt buffer “hard to close”? Nevertheless, I think the current state is acceptable, and we can add the opt‑in if you guys think we should. I’m totally happy to add it if you prefer~~

---

~Edit: The ci is strange. I haven't rebased the git history. Why suddenly pop up a lint error when I haven't changed the mentioned file?~

**Comment by seandewar** [comment]
> Edit: The ci is strange

stylua 2.4.0 came out and changed how some Lua files are formatting.  
#38195 fixed them, so a rebase should fix the lint.

**Comment by brianhuster** [comment]
> Or maybe plugins can opt-in to this behavior somehow.

I think if the buffer has a `BufWriteCmd` autocmd, then it could make sense that the buffer warns if the user quit without saving

**Comment by Willaaaaaaa** [comment]
> > Or maybe plugins can opt-in to this behavior somehow.
> 
> I think if the buffer has a `BufWriteCmd` autocmd, then it could make sense that the buffer warns if the user quit without saving

Sorry for the late response. If have to find a compromise, I prefer an explicit opt-in than a autocmd. The latter one is not that straightforward to me. For one thing, it seems that you cannot easily define a `BufWriteCmd` autocmd **specifically** for **prompt** buffers.

**Comment by justinmk** [comment]
> > Or maybe plugins can opt-in to this behavior somehow.
> 
> I think if the buffer has a `BufWriteCmd` autocmd, then it could make sense that the buffer warns if the user quit without saving

@brianhuster +1 I assume you mean that as a general core behavior similar to how 'buftype' is checked. That sounds worth considering, let's track it in an issue.

File: src/nvim/undo.c (hunk 3 above)
Comment (justinmk) [reply src/nvim/undo.c]: Removing this special-case from `bufIsChanged` makes sense, however, it also makes sense to check 'modified' if a plugin/user has *explicitly* set it.

So, 'modified' shouldn't be *implicitly* set when the user does input (because... that is "almost always" the case, and there is no way to "save" a prompt-buffer, thus 'modified' is not telling us anything useful if it is implicitly set).

**Comment by justinmk** [comment]
Actually, can we change this so that 'modified' is not *automatically* set in a prompt-buffer, but if a plugin/user *explicitly* sets it, then the "No write since last change" warning is shown?

IIUC, the main pain-point from #14116 is that 'modified' is *implicitly* set whenever the user or a plugin modifies the prompt-buffer, which is of course silly because they are always modifying the prompt-buffer (and there's no way to "save" it anyway...).

(btw, I thought about this while writing the Problem/Solution description (which I have updated the PR description with). In the future, please be sure to clearly present a Problem/Solution, because that clarifies the discussion for us now and when referencing previous changes.)

File: test/functional/legacy/prompt_buffer_spec.lua [hunk 5]
```diff
@@ -89,6 +83,13 @@ describe('prompt buffer', function()
       {1:~                        }|*8
                                |
     ]])
+
+    command('new')
+    command('set buftype=prompt modified')
+    feed('iabc<BS><BS>')
+    eq('a', fn('prompt_getinput', fn('bufnr')))
+    command('quit')
+    eq(1, #api.nvim_list_wins())
```
Comment (justinmk) [inline test/functional/legacy/prompt_buffer_spec.lua]: Since 'modified' was *explicitly* set (line 88), I don't see any reason not to show the "unsaved changes" warning. 

All other changes in this test-file LGTM. We shouldn't *automatically* set 'modified'. But if a plugin or user sets it manually, then we should respect it.

Comment (Willaaaaaaa) [reply test/functional/legacy/prompt_buffer_spec.lua]: Agreed. I updated the test so that implicit prompt-buffer edits do not block `:quit`, while an explicit `:set modified` is still respected and triggers E37 warning.

**Comment by Willaaaaaaa** [comment]
@justinmk Thanks for your patience and kind guidance. My initial thought was indeed "**always** ignore `modified` for prompt buffers", but your solution takes more consideration, we should respect "modified" when it is explicitly set.

Now it's: implicit prompt-buffer edits should not set `modified`, while an explicit `:set modified` should still be respected. Hopefully, this version is correct and all situations are considered.

> In the future, please be sure to clearly present a Problem/Solution, because that clarifies the discussion for us now and when referencing previous changes.

Apologies for the misleading/inconvenience caused. It's my first time to contribute to such a big project, and I didn’t do a good enough job of describing the Problem/Solution upfront. I'll be careful about this in the future. Really learned a lot from you guys' rigorous and conscientious attitude❤

File: src/nvim/undo.c [hunk 6]
```diff
@@ -3090,17 +3090,18 @@ static char *u_save_line_buf(buf_T *buf, linenr_T lnum)
...
 bool bufIsChanged(buf_T *buf)
   FUNC_ATTR_NONNULL_ALL FUNC_ATTR_WARN_UNUSED_RESULT
 {
-  // In a "prompt" buffer we do respect 'modified', so that we can control
-  // closing the window by setting or resetting that option.
-  return (!bt_dontwrite(buf) || bt_prompt(buf))
-         && (buf->b_changed || file_ff_differs(buf, true));
+  return bt_prompt(buf)
+         ? buf->b_modified_was_set
+         : (!bt_dontwrite(buf) && (buf->b_changed || file_ff_differs(buf, true)));
```
Comment (justinmk) [inline src/nvim/undo.c:3105]: It's lucky/convenient that `b_modified_was_set` exists, but I would have expected the implementation to look more like: don't set `b_changed` except if 'modified' was explicitly set. https://github.com/neovim/neovim/blob/f168d215cfa2372c71e231f457b62b255f00a6e2/src/nvim/buffer_defs.h#L401

That might be higher-risk though, so I guess we can try this first.

File: src/nvim/undo.c [hunk 7]
```diff
@@ -3090,17 +3090,18 @@ static char *u_save_line_buf(buf_T *buf, linenr_T lnum)
...
 ///
 /// @return true if the buffer has changed
 bool bufIsChanged(buf_T *buf)
   FUNC_ATTR_NONNULL_ALL FUNC_ATTR_WARN_UNUSED_RESULT
 {
-  // In a "prompt" buffer we do respect 'modified', so that we can control
-  // closing the window by setting or resetting that option.
-  return (!bt_dontwrite(buf) || bt_prompt(buf))
-         && (buf->b_changed || file_ff_differs(buf, true));
+  return bt_prompt(buf)
```
Comment (justinmk) [inline src/nvim/undo.c:3103]:
```suggestion
  // In a "prompt" buffer we respect 'modified' if the user or a plugin explicitly set it.
  return bt_prompt(buf)
```
