### PR TITLE
fix(api): `substitute` calls `on_bytes` after modifying buffer

### LINKED ISSUE #36370: `on_bytes` is called before buffer is modified when doing search-and-replace
### Problem

When editing a buffer via search-and-replace, the `on_bytes` callback given to `nvim_buf_attach` seems to be called with the old buffer contents, making it impossible to get the new text.

### Steps to reproduce

- create this `minimal.lua`:

```lua
vim.api.nvim_buf_set_lines(0, 0, -1, false, { "Hello" })

local buffer_lines = {}

vim.api.nvim_buf_attach(0, false, {
  on_bytes = function()
    buffer_lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
  end
})

vim.cmd("s/llo/y")

-- 💥 buffer_lines is { "Hello" }.
assert(
  vim.deep_equal(buffer_lines, { "Hey" }),
  ("buffer_lines: %s"):format(vim.inspect(buffer_lines))
)
```

- run `nvim --clean -u minimal.lua`

### Expected behavior

When called in `on_bytes`, `vim.api.nvim_buf_get_{text|lines}` returns the new contents  .

### Nvim version (nvim -v)

NVIM v0.12.0-nightly+a04c73c

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 15.7

### Terminal name/version

Ghostty

### $TERM environment variable

ghostty

### Installation

Nix flake

### PR DESCRIPTION
**Pull request by noib3**
Problem: `extmark_splice()` was being called before `ml_replace()`, which caused the on_bytes callback to be invoked with the old buffer text instead of the new text.

Solution: store metadata for each match in a kvec, call `ml_replace()` once to update the buffer, then call `extmark_splice()` once per match.

Closes https://github.com/neovim/neovim/issues/36370.

### CODE REVIEW

File: src/nvim/ex_cmds.c [hunk 1]
```diff
@@ -3771,6 +3772,25 @@ static int do_sub(exarg_T *eap, const proftime_T timeout, const int cmdpreview_n
...
+        lpos_T end;            // Match end position in original text
+        int matchcols;         // Columns deleted from original text
+        bcount_t matchbytes;   // Bytes deleted from original text
+        int subcols;           // Columns in replacement text
+        bcount_t subbytes;     // Bytes in replacement text
+        linenr_T lnum_before;  // Line number before this substitution
+        linenr_T lnum_after;   // Line number after this substitution
+      } MatchExtmarkData;
+
+      garray_T match_extmarks = GA_EMPTY_INIT_VALUE;
```
Comment (glepnir) [inline src/nvim/ex_cmds.c]: prefer `kvec`

Comment (noib3) [reply src/nvim/ex_cmds.c]: Done.

File: test/functional/lua/buffer_updates_spec.lua [hunk 2]
```diff
@@ -1250,6 +1250,224 @@ describe('lua: nvim_buf_attach on_bytes', function()
       }
     end)
 
+    it('on_bytes sees modified buffer during substitute', function()
```
Comment (justinmk) [inline test/functional/lua/buffer_updates_spec.lua]: ?? Why should this be supported? We should not be emitting buffer updates during the "live preview". Only after the substitute is confirmed. The "live preview" is NOT an edit of any kind, it is just a preview.

If a plugin wants to do stuff during the preview it should implement an 'inccommand' preview handler (`:help :command-preview`).

I don't see anything like that in these tests so I assume that is not the case here.

File: src/nvim/ex_cmds.c [hunk 3]
```diff
@@ -3771,6 +3771,24 @@ static int do_sub(exarg_T *eap, const proftime_T timeout, const int cmdpreview_n
...
+        int start_col;         // Position in new text where replacement goes
+        lpos_T start;          // Match start position in original text
+        lpos_T end;            // Match end position in original text
+        int matchcols;         // Columns deleted from original text
+        bcount_t matchbytes;   // Bytes deleted from original text
+        int subcols;           // Columns in replacement text
+        bcount_t subbytes;     // Bytes in replacement text
+        linenr_T lnum_before;  // Line number before this substitution
+        linenr_T lnum_after;   // Line number after this substitution
+      } MatchExtmarkData;
```
Comment (justinmk) [inline src/nvim/ex_cmds.c]: this is not really extmark related, it's just line data? that happens to be sent to extmark_splice later?


```suggestion
      } LineData;
```

File: src/nvim/ex_cmds.c [hunk 4]
```diff
@@ -3771,6 +3771,24 @@ static int do_sub(exarg_T *eap, const proftime_T timeout, const int cmdpreview_n
       bool skip_match = false;
       linenr_T sub_firstlnum;           // nr of first sub line
 
+      // Track where substitutions started (set once per line).
+      linenr_T lnum_start = 0;
+
+      // Track extmark_splice data for each match in the line.
```
Comment (justinmk) [inline src/nvim/ex_cmds.c]:
```suggestion
      // Track per-line data for each match.
      // Will be sent as a batch to `extmark_splice` after the substitution is done.
```

File: test/functional/lua/buffer_updates_spec.lua (hunk 2 above)
Comment (justinmk) [inline test/functional/lua/buffer_updates_spec.lua]: The word "during" is raising questions for me. Is this PR intended to fix buffer updates emitted *after a substitution is confirmed*? Or *during an 'inccommand' preview*?

We should not send *any* buffer updates *during* a substitution (like during an 'inccommand' preview). The 'inccommand' preview is intentionally NOT an "edit" semantically or technically, and should not emit buffer updates. If it is emitting buffer updates before the user "confirms" the substitution, then that should be fixed (it should NOT emit updates).

**Comment by justinmk** [comment]
~~The tests should explicitly disable 'inccommand', to make it clear that these tests are not testing anything emitting *during* 'inccommand' preview.~~

~~And also should add a small test that confirms that buffer updates are *not emitted* during 'inccommand' preview.~~

Edit: see https://github.com/neovim/neovim/pull/36487#discussion_r2534874323

File: test/functional/lua/buffer_updates_spec.lua (hunk 2 above)
Comment (zeertzjq) [reply test/functional/lua/buffer_updates_spec.lua]: Doesn't the preview happen before the substitution, not during it?

Comment (justinmk) [reply test/functional/lua/buffer_updates_spec.lua]: Preview is performed by calling `do_sub` (which this PR modifies) and then undoing it later (after the user "confirms" the substitute).

It looks like `extmark_splice` (buffer updates) is already called during 'inccommand' preview. I suppose this could be useful for API clients like vscode-neovim which need to "sync" buffers, but I don't think it makes sense to support...

I guess it's orthogonal to the change in this PR.

Comment (justinmk) [reply test/functional/lua/buffer_updates_spec.lua]: Oh I just noticed this in `:help api-buffer-updates` so I guess it's intentional:

```
    When {changedtick} is |v:null| this means the screen lines (display)
    changed but not the buffer contents. {linedata} contains the changed
    screen lines. This happens when 'inccommand' shows a buffer preview.
```

**Comment by noib3** [comment]
Renamed `MatchExtmarkData` to `LineData`, renamed first test from `on_bytes sees modified buffer during substitute` to `on_bytes sees modified buffer after substitute` to address https://github.com/neovim/neovim/pull/36487#discussion_r2532441448, and added a [new test](https://github.com/neovim/neovim/pull/36487/files#diff-cc8ef97bacb1e75406844f69dc5b2cb115b357ea0218e0953ab7ed5d3fe6e9e1R1471-R1497) to make sure no buffer update event is emitted while the substitution patterns are being typed out.

**Comment by justinmk** [comment]
Thanks again for looking into this. Will be in the 0.11.6 release
