### PR TITLE
fix(vim.system): unclear non-executable message

### LINKED ISSUE #33445: _system.lua 'spawn' works incorrectly on windows
### Problem

````lua
local function spawn(cmd, opts, on_exit, on_error)
  if is_win then
    local cmd1 = vim.fn.exepath(cmd)
    if cmd1 ~= '' then
      cmd = cmd1
    end
  end

  local handle, pid_or_err = uv.spawn(cmd, opts, on_exit)
  if not handle then
    on_error()
    error(pid_or_err)
  end
  return handle, pid_or_err --[[@as integer]]
end
````
when called (for example with <K>) returns:
> "Files\Neovim\share\nvim\runtime/lua/vim/_system.lua:248: ENOENT: no such file or directory"

I hacked it by specifying the path to cmd.exe statically instead of relying on the dynamic approach

### Steps to reproduce

```
nvim --clean
:lua vim.api.nvim_create_autocmd('LspAttach', { callback = function(ev) local client = vim.lsp.get_client_by_id(ev.data.client_id); if client.supports_method('textDocument/completion') then vim.lsp.completion.enable(true, client.id, ev.buf, { autotrigger = true }) end end })
press <K> on a word

```
### Expected behavior

I'm not sure

### Nvim version (nvim -v)

0.11

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

windows 11

### Terminal name/version

powershell

### $TERM environment variable

ms-terminal

### Installation

winget

### PR DESCRIPTION
**Pull request by justinmk**
Problem:
When a command is not found or not executable, the error message gives no indication about what command was actually tried.

Solution:
Append the command name to ENOENT and EACCES messages.

TODO:
- maybe we can do this for all errors?
- can we check the error code instead of using `pid_or_err:match()`?

BEFORE:

    E5108: Error executing lua …/_system.lua:248: ENOENT: no such file or directory

AFTER:

    E5108: Error executing lua …/_system.lua:249: ENOENT: no such file or directory: "foo"

fix #33445

### CODE REVIEW

File: runtime/lua/vim/_system.lua [hunk 1]
```diff
@@ -245,6 +245,10 @@ local function spawn(cmd, opts, on_exit, on_error)
   local handle, pid_or_err = uv.spawn(cmd, opts, on_exit)
   if not handle then
     on_error()
+    if type(pid_or_err) == 'string' and (pid_or_err:match('ENOENT') or pid_or_err:match('EACCES')) then
```
Comment (MariaSolOs) [inline runtime/lua/vim/_system.lua:248]: Nit:
```suggestion
    if string.match(pid_or_err, 'ENOENT') or string.match(pid_or_err, 'EACCES') then
```

`string.match` will return `nil` if `pid_or_err` isn't a string.

File: runtime/lua/vim/_system.lua [hunk 2]
```diff
@@ -245,6 +245,10 @@ local function spawn(cmd, opts, on_exit, on_error)
   local handle, pid_or_err = uv.spawn(cmd, opts, on_exit)
```
Comment (MariaSolOs) [inline runtime/lua/vim/_system.lua:245]: Should we change the return type of `uv.spawn` to indicate that the 2nd return value can be a string?

File: runtime/lua/vim/_system.lua (hunk 1 above)
Comment (justinmk) [reply runtime/lua/vim/_system.lua:248]: that works for a number, but not boolean/table. but this check is also for LuaLS

File: runtime/lua/vim/_system.lua (hunk 2 above)
Comment (justinmk) [reply runtime/lua/vim/_system.lua:245]: yeah but I think that's waiting for https://github.com/luvit/luv/pull/762 to update the (rather outdated) type annotations?

**Review by lewis6991 — APPROVED** [review]
