### PR TITLE
[RFC] vim-patch:8.1.1378: delete() can not handle a file name that looks li…

### LINKED ISSUE #696: delete() from patch 7.4.1119/7.4.1120 does not work for filenames with brackets
The newly added `delete()` functionality seems to be broken for some filenames containing e.g. brackets:

```
host ~ » touch rc  
host ~ » mkdir -p test/\[a-1\]
host ~ » ls test
[a-1]
host ~ » vim -u rc --cmd ':call delete("./test", "rf")' 
Error detected while processing pre-vimrc command line:
E16: Invalid range
E16: Invalid range
Press ENTER or type command to continue
```

I tried with `zsh` and `bash` as shell.
`vim` version is

```
Included patches: 1-1530
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +title
+cindent         -hangul_input    +netbeans_intg   -toolbar
-clientserver    +iconv           +packages        +user_commands
-clipboard       +insert_expand   +path_extra      +vertsplit
+cmdline_compl   +job             +perl            +virtualedit
+cmdline_hist    +jumplist        +persistent_undo +visual
+cmdline_info    +keymap          +postscript      +visualextra
+comments        +langmap         +printer         +viminfo
+conceal         +libcall         +profile         +vreplace
+cryptv          +linebreak       +python          +wildignore
+cscope          +lispindent      -python3         +wildmenu
+cursorbind      +listcmds        +quickfix        +windows
+cursorshape     +localmap        +reltime         +writebackup
+dialog_con      +lua             +rightleft       -X11
+diff            +menu            -ruby            -xfontset
+digraphs        +mksession       +scrollbind      -xim
-dnd             +modify_fname    +signs           -xsmp
-ebcdic          +mouse           +smartindent     -xterm_clipboard
+emacs_tags      -mouseshape      +startuptime     -xterm_save
+eval            +mouse_dec       +statusline      -xpm
+ex_extra        +mouse_gpm       -sun_workshop    
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lncurses -lelf -lnsl   -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc -L/usr/lib64/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic 
```

### PR DESCRIPTION
**Pull request by Shougo**
Problem:    Delete() can not handle a file name that looks like a pattern.
Solution:   Use readdir() instead of appending "/*" and expanding wildcards.
            (Ken Takata, closes vim/vim#4424, closes vim/vim#696)
https://github.com/vim/vim/commit/701ff0a3e53d253d7300c385e582659bbff7860d

### CODE REVIEW

**Comment by Shougo** [comment]
Thanks.  But if I use typedef, the typedef is not included in generated header file.
I will try another method.

**Comment by Shougo** [comment]
I have fixed the warnings.

**Comment by Shougo** [comment]
```
[RUN      ] packadd command line completion works: 10525.51 ms FAIL

test/functional/legacy/packadd_spec.lua:412: Row 4 did not match.

Expected:

  |                              |

  |{0:~                             }|

  |{0:~                             }|

  |*{1:pluginA}{2:  pluginB  pluginC     }|

  |*:packadd pluginA^              |

Actual:

  |                              |

  |{0:~                             }|

  |{0:~                             }|

  |*{1:bar}{2:  pluginA  pluginB  >      }|

  |*:packadd bar^                  |

To print the expect() call that would assert the current screen state, use

screen:snapshot_util(). In case of non-deterministic failures, use

screen:redraw_debug() to show all intermediate screen states.  

stack traceback:

	test/functional/ui/screen.lua:583: in function '_wait'

	test/functional/ui/screen.lua:362: in function 'expect'

	test/functional/legacy/packadd_spec.lua:412: in function <test/functional/legacy/packadd_spec.lua:410>
```

I think the fail is not affected with the patch.

**Comment by justinmk** [comment]
`test/functional/legacy/packadd_spec.lua` uses `delete(s:topdir, 'rf')`. Somehow the redraw behavior changed, though I don't see what could have done so...

**Comment by Shougo** [comment]
> test/functional/legacy/packadd_spec.lua uses delete(s:topdir, 'rf'). Somehow the redraw behavior changed, though I don't see what could have done so...

Oh

**Comment by Shougo** [comment]
> OTOH I think packadd_spec is telling us that bar was not deleted, because it's now showing up in the <tab> results. Seems like delete(...,'rm') is behaving differently now.

I have tested `delete('rf')`, but it seems works for me.

**Comment by Shougo** [comment]
The failure seems changed.

```
Failures: 
	From test_arglist.vim:
	Found errors in Test_argadd():
	function RunTheTest[37]..Test_argadd[13]..Assert_argc line 4: Expected 'a' but got 'a/'
	function RunTheTest[37]..Test_argadd[18]..Assert_argc line 4: Expected 'a' but got 'a/'
	function RunTheTest[37]..Test_argadd[23]..Assert_argc line 4: Expected 'a' but got 'a/'
	function RunTheTest[37]..Test_argadd[28]..Assert_argc line 4: Expected 'a' but got 'a/'
	function RunTheTest[37]..Test_argadd[34]..Assert_argc line 4: Expected 'a' but got 'a/'
	Found errors in Test_argdelete():
	function RunTheTest[37]..Test_argdelete[16]..Assert_argc line 4: Expected 'a' but got 'a/'
	Found errors in Test_argedit():
	function RunTheTest[37]..Test_argedit line 3: Expected ['a'] but got ['a/']
	function RunTheTest[37]..Test_argedit line 4: Expected 'a' but got ''
	function RunTheTest[37]..Test_argedit line 6: Expected ['a', 'b'] but got ['a/', 'b']
	function RunTheTest[37]..Test_argedit line 9: Expected ['a', 'b', 'a'] but got ['a/', 'b', 'a/']
	function RunTheTest[37]..Test_argedit line 10: Expected 'a' but got ''
	function RunTheTest[37]..Test_argedit line 15: Expected ['a', 'b', 'a', 'C', 'D'] but got ['a/', 'b', 'a/', 'C', 'D']
	function RunTheTest[37]..Test_argedit line 18: Expected ['a', 'b', 'a', 'C', 'c', 'D'] but got ['a/', 'b', 'a/', 'C', 'c', 'D']
	function RunTheTest[37]..Test_argedit line 24: Expected ['x', 'a', 'b', 'a', 'C', 'c', 'D'] but got ['x', 'a/', 'b', 'a/', 'C', 'c', 'D']
	function RunTheTest[37]..Test_argedit line 32: Expected ['x', 'y', 'y', 'a', 'b', 'a', 'C', 'c', 'D'] but got ['x', 'y', 'y', 'a/', 'b', 'a/', 'C', 'c', 'D']
	Found errors in Test_argument():
	function RunTheTest[37]..Test_argument line 23: Expected ['d', 'c', 'b', 'a', 'c'] but got ['d', 'c', 'b', '', 'c']
	function RunTheTest[37]..Test_argument line 25: Expected '\na   b   [c] d   ' but got '\na/  b   [c] d   '
	function RunTheTest[37]..Test_argument line 28: Expected ['a', 'b', 'd'] but got ['a/', 'b', 'd']
	function RunTheTest[37]..Test_argument line 31: Expected ['a', 'd'] but got ['a/', 'd']
	function RunTheTest[37]..Test_argument line 34: Expected ['a'] but got ['a/']
	function RunTheTest[37]..Test_argument line 40: Expected ['a', 'b', 'c', 'x'] but got ['a/', 'b', 'c', 'x']
	function RunTheTest[37]..Test_argument line 43: Expected ['y', 'a', 'b', 'c', 'x'] but got ['y', 'a/', 'b', 'c', 'x']
	function RunTheTest[37]..Test_argument line 50: Expected ['a', 'f'] but got ['a/', 'f']
	Found errors in Test_argv():
	function RunTheTest[37]..Test_argv line 22: Expected ['a', 'b', 'c', 'd'] but got ['a/', 'b', 'c', 'd']
	function RunTheTest[37]..Test_argv line 34: Expected ['a', 'b', 'c', 'd'] but got ['a/', 'b', 'c', 'd']
	function RunTheTest[37]..Test_argv line 39: Expected ['a', 'b', 'c', 'd'] but got ['a/', 'b', 'c', 'd']
	Found errors in Test_zero_argadd():
	function RunTheTest[37]..Test_zero_argadd line 7: Expected ['added', 'a', 'b', 'c', 'd'] but got ['added', 'a/', 'b', 'c', 'd']
	function RunTheTest[37]..Test_zero_argadd line 11: Expected ['added', 'a', 'third', 'b', 'c', 'd'] but got ['added', 'a/', 'third', 'b', 'c', 'd']
	function RunTheTest[37]..Test_zero_argadd line 17: Expected ['edited', 'a', 'b', 'c', 'd'] but got ['edited', 'a/', 'b', 'c', 'd']
	function RunTheTest[37]..Test_zero_argadd line 21: Expected ['edited', 'a', 'third', 'b', 'c', 'd'] but got ['edited', 'a/', 'third', 'b', 'c', 'd']
	function RunTheTest[37]..Test_zero_argadd line 25: Expected ['edited', 'a', 'file with spaces', 'another', 'file', 'third', 'b', 'c', 'd'] but got ['edited', 'a/', 'file with spaces', 'another', 'file', 'third', 'b', 'c', 'd']
	From test_command_count.vim:
	Found errors in Test_command_count_2():
	function RunTheTest[37]..Test_command_count_2 line 9: Expected 'a' but got ''
	From test_registers.vim:
	Found errors in Test_display_registers():
	function RunTheTest[37]..Test_display_registers line 12: Expected '\n--- Registers ---\n""   a\n"0   ba\n"1   b\n"a   b\n"q   ^Jfunction Test_ve_blockpaste()^Jfunction Test_aaa_empty_reg_test()^Jfunct\n"-   a\n"*   OTOH I think packadd_spec is telling us that bar was not deleted, because \n"+   OTOH I think packadd_spec is telling us that bar was not deleted, because \n".   8\n":   ls\n"%   file2\n"#   file1\n"/   bar\n"=   2*4' but got '\n--- Registers ---\n""   a\n"0   ba\n"1   b\n"a   b\n"q   ^Jfunction Test_ve_blockpaste()^Jfunction Test_aaa_empty_reg_test()^Jfunct\n"-   a\nclipboard: error: Error: target STRING not available\n"+   OTOH I think packadd_spec is telling us that bar was not deleted, because \n".   8\n":   ls\n"%   file2\n"#   file1\n"/   bar\n"=   2*4'
```

**Comment by Shougo** [comment]
```
Failures:
	From test_arglist.vim:
	Found errors in Test_argadd():
	function RunTheTest[37]..Test_argadd[13]..Assert_argc line 4: Expected 'a' but got 'a/'
	function RunTheTest[37]..Test_argadd[18]..Assert_argc line 4: Expected 'a' but got 'a/'
	function RunTheTest[37]..Test_argadd[23]..Assert_argc line 4: Expected 'a' but got 'a/'
	function RunTheTest[37]..Test_argadd[28]..Assert_argc line 4: Expected 'a' but got 'a/'
	function RunTheTest[37]..Test_argadd[34]..Assert_argc line 4: Expected 'a' but got 'a/'
	Found errors in Test_argdelete():
	function RunTheTest[37]..Test_argdelete[16]..Assert_argc line 4: Expected 'a' but got 'a/'
	Found errors in Test_argedit():
	function RunTheTest[37]..Test_argedit line 3: Expected ['a'] but got ['a/']
	function RunTheTest[37]..Test_argedit line 4: Expected 'a' but got ''
	function RunTheTest[37]..Test_argedit line 6: Expected ['a', 'b'] but got ['a/', 'b']
	function RunTheTest[37]..Test_argedit line 9: Expected ['a', 'b', 'a'] but got ['a/', 'b', 'a/']
	function RunTheTest[37]..Test_argedit line 10: Expected 'a' but got ''
	function RunTheTest[37]..Test_argedit line 15: Expected ['a', 'b', 'a', 'C', 'D'] but got ['a/', 'b', 'a/', 'C', 'D']
	function RunTheTest[37]..Test_argedit line 18: Expected ['a', 'b', 'a', 'C', 'c', 'D'] but got ['a/', 'b', 'a/', 'C', 'c', 'D']
	function RunTheTest[37]..Test_argedit line 24: Expected ['x', 'a', 'b', 'a', 'C', 'c', 'D'] but got ['x', 'a/', 'b', 'a/', 'C', 'c', 'D']
	function RunTheTest[37]..Test_argedit line 32: Expected ['x', 'y', 'y', 'a', 'b', 'a', 'C', 'c', 'D'] but got ['x', 'y', 'y', 'a/', 'b', 'a/', 'C', 'c', 'D']
	Found errors in Test_argument():
	function RunTheTest[37]..Test_argument line 23: Expected ['d', 'c', 'b', 'a', 'c'] but got ['d', 'c', 'b', '', 'c']
	function RunTheTest[37]..Test_argument line 25: Expected '\na   b   [c] d   ' but got '\na/  b   [c] d   '
	function RunTheTest[37]..Test_argument line 28: Expected ['a', 'b', 'd'] but got ['a/', 'b', 'd']
	function RunTheTest[37]..Test_argument line 31: Expected ['a', 'd'] but got ['a/', 'd']
	function RunTheTest[37]..Test_argument line 34: Expected ['a'] but got ['a/']
	function RunTheTest[37]..Test_argument line 40: Expected ['a', 'b', 'c', 'x'] but got ['a/', 'b', 'c', 'x']
	function RunTheTest[37]..Test_argument line 43: Expected ['y', 'a', 'b', 'c', 'x'] but got ['y', 'a/', 'b', 'c', 'x']
	function RunTheTest[37]..Test_argument line 50: Expected ['a', 'f'] but got ['a/', 'f']
	Found errors in Test_argv():
	function RunTheTest[37]..Test_argv line 22: Expected ['a', 'b', 'c', 'd'] but got ['a/', 'b', 'c', 'd']
	function RunTheTest[37]..Test_argv line 34: Expected ['a', 'b', 'c', 'd'] but got ['a/', 'b', 'c', 'd']
	function RunTheTest[37]..Test_argv line 39: Expected ['a', 'b', 'c', 'd'] but got ['a/', 'b', 'c', 'd']
	Found errors in Test_zero_argadd():
	function RunTheTest[37]..Test_zero_argadd line 7: Expected ['added', 'a', 'b', 'c', 'd'] but got ['added', 'a/', 'b', 'c', 'd']
	function RunTheTest[37]..Test_zero_argadd line 11: Expected ['added', 'a', 'third', 'b', 'c', 'd'] but got ['added', 'a/', 'third', 'b', 'c', 'd']
	function RunTheTest[37]..Test_zero_argadd line 17: Expected ['edited', 'a', 'b', 'c', 'd'] but got ['edited', 'a/', 'b', 'c', 'd']
	function RunTheTest[37]..Test_zero_argadd line 21: Expected ['edited', 'a', 'third', 'b', 'c', 'd'] but got ['edited', 'a/', 'third', 'b', 'c', 'd']
	function RunTheTest[37]..Test_zero_argadd line 25: Expected ['edited', 'a', 'file with spaces', 'another', 'file', 'third', 'b', 'c', 'd'] but got ['edited', 'a/', 'file with spaces', 'another', 'file', 'third', 'b', 'c', 'd']
	From test_quickfix.vim:
	Found errors in Test_efm_dirstack():
	Caught exception in Test_efm_dirstack(): Vim(call):E739: Cannot create directory dir1: file already exists @ function RunTheTest[37]..Test_efm_dirstack, line 2
	From test_registers.vim:
	Found errors in Test_display_registers():
	function RunTheTest[37]..Test_display_registers line 12: Expected '\n--- Registers ---\n""   a\n"0   ba\n"1   b\n"a   b\n"q   ^Jfunction Test_ve_blockpaste()^Jfunction Test_aaa_empty_reg_test()^Jfunct\n"-   a\n"*   ^J\nclipboard: error: Error: target STRING not available\n".   8\n":   ls\n"%   file2\n"#   file1\n"/   bar\n"=   2*4' but got '\n--- Registers ---\n""   a\n"0   ba\n"1   b\n"a   b\n"q   ^Jfunction Test_ve_blockpaste()^Jfunction Test_aaa_empty_reg_test()^Jfunct\n"-   a\n".   8\n":   ls\n"%   file2\n"#   file1\n"/   bar\n"=   2*4'
```

It is master's result.

**Comment by Shougo** [comment]
I have tested `TEST_FILE=test/functional/packadd.lua make functionaltest` on master.
It is also failed...

**Comment by Shougo** [comment]
Why it is not failed?
https://travis-ci.org/github/neovim/neovim/builds/722556673

**Comment by Shougo** [comment]
@justinmk 

```diff
diff --git a/test/functional/legacy/packadd_spec.lua b/test/functional/legacy/packadd_spec.lua
index 609f82517..50fac51f7 100644
--- a/test/functional/legacy/packadd_spec.lua
+++ b/test/functional/legacy/packadd_spec.lua
@@ -334,6 +334,8 @@ describe('packadd', function()
         let g:sequence = ''
         runtime! ALL extra/bar.vim
         call assert_equal('runstartopt', g:sequence)
+
+        call delete(s:topdir, 'rf')
       endfunc
     ]=])
     call('SetUp')
```

The patch fixes `packadd_spec.lua` fail.
I don't know why...

**Comment by Shougo** [comment]
And I have found `$GZIP` environment is deprecated in `011_autocommands_spec.lua`.

```
[  ERROR   ] 1 error, listed below:
[  ERROR   ] test/functional/legacy/011_autocommands_spec.lua @ 68: file reading, writing and bufnew and filter autocommands FileReadPost (using gzip)
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(string) '
gzip: warning: GZIP environment variable is deprecated; use an alias or script
start of testfile
line 2	Abcdefghijklmnopqrstuvwxyz
line 3	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
line 4	Abcdefghijklmnopqrstuvwxyz
line 5	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
line 6	Abcdefghijklmnopqrstuvwxyz
line 7	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
line 8	Abcdefghijklmnopqrstuvwxyz
line 9	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
line 10 Abcdefghijklmnopqrstuvwxyz
end of testfile'
Expected:
(string) '
start of testfile
line 2	Abcdefghijklmnopqrstuvwxyz
line 3	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
line 4	Abcdefghijklmnopqrstuvwxyz
line 5	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
line 6	Abcdefghijklmnopqrstuvwxyz
line 7	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
line 8	Abcdefghijklmnopqrstuvwxyz
line 9	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
line 10 Abcdefghijklmnopqrstuvwxyz
end of testfile'
------------------------------------------------------------------------------
```

It should be fixed.

**Comment by Shougo** [comment]
I have fixed some test errors.

**Comment by Shougo** [comment]
```
-------------------------------
Executed:  1623 Tests
 Skipped:    77 Tests
  FAILED:     2 Tests


Failures:
	From test_command_count.vim:
	Found errors in Test_command_count_2():
	function RunTheTest[37]..Test_command_count_2 line 9: Expected 'a' but got ''
	From test_registers.vim:
	Found errors in Test_display_registers():
	function RunTheTest[37]..Test_display_registers line 12: Expected '\n--- Registers ---\n""   a\n"0   ba\n"1   b\n"a   b\n"q   ^Jfunction Test_ve_blockpaste()^Jfunction Test_aaa_empty_reg_test()^Jfunct\n"-   a\n"*   let $GZIP = ""\n"+   --quiet \n".   8\n":   ls\n"%   file2\n"#   file1\n"/   bar\n"=   2*4' but got '\n--- Registers ---\n""   a\n"0   ba\n"1   b\n"a   b\n"q   ^Jfunction Test_ve_blockpaste()^Jfunction Test_aaa_empty_reg_test()^Jfunct\n"-   a\nclipboard: error: Error: target STRING not available\n"+   --quiet \n".   8\n":   ls\n"%   file2\n"#   file1\n"/   bar\n"=   2*4'

TEST FAILURE
```

I think the errors are not affected the change.

**Comment by Shougo** [comment]
Fixed.

**Comment by Shougo** [comment]
The tests are passed!

**Comment by Shougo** [comment]
@justinmk I have fixed the tests.  Can you check it again?

**Comment by Shougo** [comment]
Wow.  It is not merged yet.  Can you merge it?

**Comment by Shougo** [comment]
I have fixed the conflict.

**Comment by Shougo** [comment]
Why the CI tests are failed?
I will investigate it.

**Comment by Shougo** [comment]
I get it.  I need to remove the marker in the test file.

**Comment by Shougo** [comment]
OK.  The test are passed.

File: test/functional/legacy/011_autocommands_spec.lua [hunk 1]
```diff
@@ -70,7 +70,7 @@ describe('file reading, writing and bufnew and filter autocommands', function()
       feed_command('let $GZIP = ""')
       --execute('au FileChangedShell * echo "caught FileChangedShell"')
       feed_command('set bin')
-      feed_command("au FileReadPost    *.gz   '[,']!gzip -d")
+      feed_command("au FileReadPost    *.gz   '[,']!GZIP= gzip -d")
```
Comment (mhinz) [inline test/functional/legacy/011_autocommands_spec.lua:73]: Why?

**Comment by mhinz** [comment]
LGTM.

I'm not merging it yet, because @janlazo assigned himself and I don't know why. :-)

File: test/functional/legacy/011_autocommands_spec.lua (hunk 1 above)
Comment (Shougo) [reply test/functional/legacy/011_autocommands_spec.lua:73]: Because:

https://github.com/neovim/neovim/pull/12784#issuecomment-683518366

GZIP environment must be cleared.  It changes the behavior.

**Comment by janlazo** [comment]
I assigned myself to review it because there were related patches to `readdir` when I was going though v8.1.x patches. I plan to merge this just after v0.5.0 unless other core devs and @Shougo  think that there is no risk to merging this.

**Comment by Shougo** [comment]
>  I plan to merge this just after v0.5.0 unless other core devs and @Shougo think that there is no risk to merging this now.

When 0.5.0 will be released?

:-)

**Comment by janlazo** [comment]
@Shougo When a core dev manages to get the runtime updates merged. There's just too many to deal with. Working on it tomorrow. Hopefully, it will be out mid next week if the newsletter is ready.

Some items in https://github.com/neovim/neovim/issues/11023 should be done now because of previous PRs that bump third-party deps.

File: src/nvim/fileio.c [hunk 2]
```diff
@@ -5203,38 +5203,115 @@ static void vim_maketempdir(void)
...
+
+theend:
+  set_vim_var_string(VV_VAL, NULL, 0);
+  restore_vimvar(VV_VAL, &save_val);
+  return retval;
+}
+
+/// Core part of "readdir()" function.
+/// Retrieve the list of files/directories of "path" into "gap".
+int readdir_core(
```
Comment (janlazo) [inline src/nvim/fileio.c:5239]: Why is this not `void` when it only returns 0?

Comment (Shougo) [reply src/nvim/fileio.c]: OK.  I have fixed.

Because the original patch checks the function failure.
But neovim does not check it.

File: src/nvim/fileio.c [hunk 3]
```diff
@@ -5203,38 +5203,114 @@ static void vim_maketempdir(void)
...
+  os_closedir(dirp);
+}
+
 /// Delete "name" and everything in it, recursively.
 /// @param name The path which should be deleted.
 /// @return 0 for success, -1 if some file was not deleted.
 int delete_recursive(const char *name)
 {
   int result = 0;
+  char_u *exp = vim_strsave((char_u *)name);
```
Comment (janlazo) [inline src/nvim/fileio.c:5289]: Nitpick.
`exp` can be `char`, not `char_u`, to reduce typecasts. `vim_strsave()` calls `xstrdup()`.

File: src/nvim/fileio.c [hunk 4]
```diff
@@ -5203,38 +5203,114 @@ static void vim_maketempdir(void)
...
+    const char *path,
+    typval_T *expr,
+    bool is_checkitem)
+{
+  ga_init(gap, (int)sizeof(char *), 20);
+
+  for (;;) {
+    bool ignore;
+
+    path = os_scandir_next(dirp);
```
Comment (janlazo) [inline src/nvim/fileio.c:5251]: Can you use a local variable, `p`, instead of overriding `path` like in the vim patch?

File: test/functional/legacy/packadd_spec.lua [hunk 5]
```diff
@@ -334,6 +334,8 @@ describe('packadd', function()
         let g:sequence = ''
         runtime! ALL extra/bar.vim
         call assert_equal('runstartopt', g:sequence)
+
+        call delete(s:topdir, 'rf')
```
Comment (janlazo) [inline test/functional/legacy/packadd_spec.lua:338]: This should be executed by TearDown() in `after_each` but I don't mind 1 more call.

**Review by janlazo — APPROVED** [review]
It's fine. The ported version of `readdir_` functions are simpler and smaller in scope compared to the vim patch. There are additional changes to the tests, some likely done in later patches, which I don't mind. Some test fixes specific to Neovim are appreciated, specifically `Test_display_registers`.

It is preferable to make followup changes or fixups after the vim-patch so that it's obvious which changes are from Vim.

**Comment by janlazo** [comment]
I'll merge tomorrow if there are no more changes. This is long overdue PR and I apologize for the delayed review.

**Comment by Shougo** [comment]
Thanks.  I will fix it for the review.

**Comment by Shougo** [comment]
Fixed.

**Comment by janlazo** [comment]
```diff
--- a/test/functional/legacy/packadd_spec.lua
+++ b/test/functional/legacy/packadd_spec.lua
@@ -20,6 +20,7 @@ describe('packadd', function()
 
       func SetUp()
         let s:topdir = expand(getcwd() . '/Xdir')
+        call delete(s:topdir, 'rf')
         exe 'set packpath=' . s:topdir
         let s:plugdir = expand(s:topdir . '/pack/mine/opt/mytest')
       endfunc
```

**Comment by Shougo** [comment]
Fixed.

**Comment by Shougo** [comment]
Thank you for the merge!

File: test/functional/legacy/011_autocommands_spec.lua (hunk 1 above)
Comment (jamessan) [reply test/functional/legacy/011_autocommands_spec.lua:73]: It's already cleared on line 70.  Using `GZIP=` here seems to be causing issues with the Windows CI.
