### PR TITLE
fix: make :restart respect 'confirm' option

### LINKED ISSUE #36499: :restart respects 'confirm'
### Problem

`:restart` works with `:confirm` to ask user configuration if buffers have been modified. However, it does not respect 'confirm'. That makes sense bc restart uses `qall!` by default, but I feel like respecting 'confirm' is expected.

### Steps to reproduce

1. `nvim --clean -u NONE +'set confirm'`
2. Modify buffer
3. `:restart`

### Expected behavior

Restart respects 'confirm' option.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-1149+g3f80e18a80-dirty

### PR DESCRIPTION
**Pull request by alf171**
When 'confirm' is set and there are unsaved buffers,
:restart now prompts before quitting, matching the behavior of :quit.

Fixes https://github.com/neovim/neovim/issues/36499

### CODE REVIEW

File: test/functional/terminal/tui_spec.lua [hunk 1]
```diff
@@ -378,6 +378,14 @@ describe('TUI :restart', function()
     tt.feed_data('C\013')
     screen:expect({ any = vim.pesc('[No Name]') })
 
+    -- Check :restart respects confirm
```
Comment (justinmk) [inline test/functional/terminal/tui_spec.lua]:
```suggestion
    -- Check :restart respects 'confirm' option.
```

File: src/nvim/ex_docmd.c [hunk 2]
```diff
@@ -4905,11 +4905,22 @@ static void ex_restart(exarg_T *eap)
...
+  bool confirm = (p_confirm || (cmdmod.cmod_flags & CMOD_CONFIRM));
+  if (confirm && check_changed_any(false, false)) {
     return;
   }
+
+  char *quit_cmd;
+  if (eap->do_ecmd_cmd) {
+    quit_cmd = eap->do_ecmd_cmd;
+  } else if (confirm) {
+    quit_cmd = "confirm qall";
```
Comment (zeertzjq) [inline src/nvim/ex_docmd.c]: This doesn't look right. `confirm qall` will call `check_changed_any()` again, but `check_changed_any()` is already called here.

Comment (alf171) [reply src/nvim/ex_docmd.c]: my understanding is the first call checks if the user has aborted the confirm, the second one, done by the quit_cmd checks is more so geared if the caller passes in a command which won't quit the server so it errors w/ `restart failed: +cmd did not quit the server`

Wouldn't `:restart +qall` also run `check_changed_any()` twice?

Comment (zeertzjq) [reply src/nvim/ex_docmd.c]: Hmm wait. Actually the previous `check_changed_any()` should have already marked the remaining buffers as unchanged, so adding `:confirm` won't do anything.

Comment (alf171) [reply src/nvim/ex_docmd.c]: yeah you're right. we could switch back to the ternary but with `qall` instead of `qall!` if that's preferred. I don't really get why `qall!` so not sure if to keep that

Comment (alf171) [reply src/nvim/ex_docmd.c]:
```
  if (eap->do_ecmd_cmd) {
    quit_cmd = eap->do_ecmd_cmd;
  } else if (confirm) {
    quit_cmd = "qall";
  } else {
    quit_cmd = "qall!";
  }

```
is the most minimal change since some test expect `qall!` as default i think

Comment (justinmk) [reply src/nvim/ex_docmd.c]: let's start with the minimal change. can discuss switching the default in a separate issue/pr

**Comment by alf171** [comment]
@justinmk. Anything else needed from me here?
