### PR TITLE
lsp: Handle unknown CompletionItemKind and  SymbolKind

### LINKED ISSUE #12200: lsp: attempt to concatenate local 'kind' (a nil value)
- `nvim --version`: 0.5 9678fe

### Steps to reproduce using `nvim -u NORC`

With neovim source code + ccls and this mapping:
`nnoremap <silent> g0    <cmd>lua vim.lsp.buf.document_symbol()<CR>`

Typing g0 on many symbols (e.g., `win_hl_attrs`) triggers:

```
Error executing vim.schedule lua callback: /home/teto/neovim2/runtime/lua/vim/lsp/util.lua:943: attempt to concatenate local 'kind' (a nil value)
```
It seems that our lua code `local kind = protocol.SymbolKind[symbol.kind]` is incorrect because kinds can be negotiated as well see
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentSymbol

### Expected behaviour
No error

### PR DESCRIPTION
**Pull request by h-michael**
fix: #12200
If the client set "symbolKind.valueSet", the client must handle it properly even if it receives a value outside the specification.

### CODE REVIEW

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -203,6 +203,13 @@ local function remove_unmatch_completion_items(items, prefix)
   end, items)
 end
 
+-- Acording to LSP spec, if the client set "completionItemKind.valueSet",
+-- the client must handle it properly even if it receives a value outside the specification.
+-- https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion
+function M.get_completion_item_kind_name(completion_item_kind)
```
Comment (mfussenegger) [inline runtime/lua/vim/lsp/util.lua:209]: Not sure if it's a good idea to clutter the public API with small methods like this. Is this motivated by the tests or with extensibility in mind?

Comment (clason) [reply runtime/lua/vim/lsp/util.lua:209]: Well, it might be useful to allow for customizable kind names (per server)?

(Since the built-in LSP is supposed to be low-level, having a larger, composable, API of small functions would be helpful.)

Comment (mfussenegger) [reply runtime/lua/vim/lsp/util.lua:209]: > Since the built-in LSP is supposed to be low-level, having a larger, composable, API of small functions would be helpful

I agree that it would be helpful, but it is a tradeoff. Once a method is public it becomes harder to change it because of BWC. (At least once 0.5 is out) - so I think being a bit conservative about exposing methods may be beneficial.

Just my opinion, not sure how the maintainers see that.

**Comment by tjdevries** [comment]
One option would be we can prefix functions like this for testing with a leading `_`. So `M._get_*`. We can document that these functions are not guaranteed for backwards compatibility (although obviously we won't just change them for no reason).

Any thoughts on that @mfussenegger and @h-michael

**Comment by clason** [comment]
On a related note, it would be really useful to export _all_ utility functions to allow overriding specific ones without having to copy&paste a rat's tail of local functions to your init.lua. With this convention, it'd be possible to do that without having to document/maintain compatibility.

**Comment by tjdevries** [comment]
@clason can you open an issue where we can discuss this? I'd like input from a few people on it that we can tag in the issue to try and figure out if that would make things more composable or more brittle :) I like where you're coming from though

**Comment by h-michael** [comment]
@tjdevries @clason 
I make those functions private for now.
We can make those public anytime we needed.

**Comment by tjdevries** [comment]
LGTM. Will wait for tests and see if anyone else has anything to say.

**Review by mfussenegger — APPROVED** [review]
