### PR TITLE
[RFC] Fix crash when set rightleft on terminal

### LINKED ISSUE #11438: Segmentation fault when setting 'rightleft' in terminal buffer
- `nvim --version`:

Affects 0.4.3 (official appimage) and master at d5f14b8:

```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-9a287301-34f2-4b86-92e3-462594f51f36

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
```

```
NVIM v0.5.0-177-gd5f14b837
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/user/projects/neovim/build/config -I/home/user/projects/neovim/src -I/home/user/projects/neovim/.deps/usr/include -I/usr/include -I/home/user/projects/neovim/build/src/nvim/auto -I/home/user/projects/neovim/build/include
Compiled by user@development

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently? `No crash with Vim 8.0 and Vim 8.1`
- Operating system/version: `Fedora 30 (Thirty)`
- Terminal name/version: `GNOME Terminal 3.32.2 using VTE 0.56.4 +GNUTLS`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

Requires htop to be installed:

```
nvim -u NORC +"terminal htop" +"setlocal rightleft"
```

### Actual behaviour

```
Segmentation fault (core dumped)
```

### Expected behaviour

Interactive terminal programs have their text shown from right to left.

### PR DESCRIPTION
**Pull request by erw7**
Fixes #11438.

Backtrace:
```
#0  schar_from_ascii ( p=0x801cc9e112c3 <error: Cannot access memory at address 0x801cc9e112c3>, c=32 ' ') at ../src/nvim/screen.c:5263
#1  0x00007f31460eccc5 in win_line (wp=wp@entry=0x7fffc9df6230, lnum=lnum@entry=11, startrow=startrow@entry=10, endrow=41, nochange=false, number_only=number_only@entry=false) at ../src/nvim/screen.c:4025
#2  0x00007f31460eed8e in win_update (wp=wp@entry=0x7fffc9df6230) at ../src/nvim/screen.c:1403
#3  0x00007f31460f011f in update_screen (type=<optimized out>) at ../src/nvim/screen.c:502
#4  0x00007f3146138ef4 in normal_redraw (s=s@entry=0x7fffd0a5f700) at ../src/nvim/normal.c:1247
#5  0x00007f314613b159 in normal_check (state=0x7fffd0a5f700) at ../src/nvim/normal.c:1324
#6  0x00007f31460accfe in state_enter (s=0x7fffd0a5f700) at ../src/nvim/state.c:28
#7  0x00007f3146143099 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at ../src/nvim/normal.c:463
#8  0x00007f314618b541 in main (argc=<optimized out>, argv=<optimized out>) at ../src/nvim/main.c:580
```

### CODE REVIEW

File: src/nvim/screen.c [hunk 1]
```diff
@@ -4021,10 +4021,16 @@ win_line (
       if (wp->w_buffer->terminal) {
         // terminal buffers may need to highlight beyond the end of the
         // logical line
-        while (col < grid->Columns) {
+        int n = 1;
+        if (wp->w_p_rl) {
+          n = -1;
+        }
```
Comment (justinmk) [inline src/nvim/screen.c]: ternary is more readable and less verbose.

```
int n = wp->w_p_rl ? -1 : 1;
```

File: test/functional/terminal/buffer_spec.lua [hunk 2]
```diff
@@ -224,6 +225,23 @@ describe(':terminal buffer', function()
...
+    screen:expect([[
+                                               ydaer ytt|
+      {1:a}aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa|
+                                                        |
+                                                        |
+                                                        |
+                                                        |
+      {3:-- TERMINAL --}                                    |
+    ]])
+    feed_command('bdelete!')
```
Comment (justinmk) [inline test/functional/terminal/buffer_spec.lua]: `feed_command` uses `feed()` (AKA `nvim_input`) so it is asynchronous. Better to use `command` usually.
```suggestion
    command('bdelete!')
```

File: test/functional/terminal/buffer_spec.lua [hunk 3]
```diff
@@ -224,6 +225,23 @@ describe(':terminal buffer', function()
       neq('terminal', eval('&buftype'))
     end)
   end)
+
+  it('it works with set rightleft #11438', function()
+    local columns = eval('&columns')
+    feed(string.rep('a', columns))
+    command('set rightleft')
+    wait()
```
Comment (justinmk) [inline test/functional/terminal/buffer_spec.lua]: did you try without `wait()`? Usually not needed before `screen:expect` .

Comment (erw7) [reply test/functional/terminal/buffer_spec.lua]: Oops! It is not necessary because it is a remnant during trial and error.

**Comment by blueyed** [comment]
Cherry-picked into release-0.4: 972dd75
