### PR TITLE
fix(lsp): send textDocument/didChange for each buffer

### LINKED ISSUE #16424: lsp: debounced textChanges are not segmented by buffer
### Neovim version (nvim -v)

NVIM v0.6.0-dev+619-gcfa5d0680

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

nvim-qt

### $TERM environment variable

nvim-qt

### Installation

Git

### How to reproduce the issue

Reproducing this is a bit tricky, and I haven't been able to narrow it down to
something small. I can however reliably reproduce the issue with a project of
mine. You'll need to have rust-analyzer configured for this to work. For
reference, I use the following settings (minus settings not relevant for this
issue):

```lua
config.rust_analyzer.setup({
  flags = {
    allow_incremental_sync = true,
    debounce_text_changes = 1000,
  },
  settings = {
    ['rust-analyzer'] = {
      diagnostics = {
        enable = true,
        enableExperimental = false,
      },
      inlayHints = {
        typeHints = false,
        chainingHints = false,
        enable = false,
      },
      server = {
        path = '/usr/bin/rust-analyzer',
      },
      lruCapacity = 64,
      completion = {
        postfix = {
          enable = false,
        },
      },
    },
  },
})
```

First, clone said project:

    git clone https://gitlab.com/inko-lang/inko.git --branch=single-ownership

Then run the following:

    cd inko
    git checkout fd6a75575aafc3be3b5d4a285d344ab907458f2f
    cargo build

Next, follow these steps:

1. Open `compiler/src/types.rs` `compiler/src/type_check.rs`
1. In `types.rs`, navigate to the `get_constant` function on line 254
1. Place the cursor on the start of the function name
1. Run `:lua vim.lsp.buf.rename()`
1. Enter `blorb` as the new name and confirm the rename
1. Note that in `type_check.rs` you'll see a bunch of syntax errors being
   reported, in spite of the code in question being valid
1. If you at this point try to undo the changes and rename the function again,
   nothing happens

With incremental sync disabled, I can't reproduce this. Instead I get a
different problem: after the first rename of `get_constant` to `blorb`, if I try
to rename the function again the replacement text includes a `(`. If you then
try to rename the function, your code gets all messed up.

Here is a recording that shows what happens when incremental sync is enabled:

[asciicast](https://asciinema.org/a/PNtEwCPUoYmpUU9pWiKhdled6)

And this is what happens when you disable incremental sync:

[asciicast](https://asciinema.org/a/gUy0bDmdTEqKcbetC56dCE5Lj)

### Expected behavior

Renaming works fine, and no syntax errors are produced

### Actual behavior

Either NeoVim, rust-analyzer or both end up getting messed up when incremental sync is enabled

### PR DESCRIPTION
**Pull request by mjlbach**
Closes https://github.com/neovim/neovim/issues/16424

### CODE REVIEW

File: runtime/lua/vim/lsp.lua [hunk 1]
```diff
@@ -402,27 +402,36 @@ do
       if state.use_incremental_sync then
         -- This must be done immediately and cannot be delayed
         -- The contents would further change and startline/endline may no longer fit
-        table.insert(state.pending_changes, incremental_changes(client))
+        if not state.pending_changes[uri] then
```
Comment (mjlbach) [inline runtime/lua/vim/lsp.lua:405]: Need to make sure URI is sanitized on windows. We can also track per bufnr like elsewhere but URI is more clear in this case IMO.

File: runtime/lua/vim/lsp.lua [hunk 2]
```diff
@@ -402,27 +402,36 @@ do
...
           return
         end
-        local contentChanges
         if state.use_incremental_sync then
-          contentChanges = state.pending_changes
+          for change_uri, content_changes in pairs(state.pending_changes) do
+            client.notify("textDocument/didChange", {
+              textDocument = {
+                uri = change_uri;
+                version = changedtick;
```
Comment (dmitmel) [inline runtime/lua/vim/lsp.lua:420]: Doesn't changedtick need to be saved per-buffer as well?

File: runtime/lua/vim/lsp.lua [hunk 3]
```diff
@@ -1159,6 +1168,7 @@ function lsp.buf_attach_client(bufnr, client_id)
       on_reload = function()
         local params = { textDocument = { uri = uri; } }
         for_each_buffer_client(bufnr, function(client, _)
+          changetracking.reset_buf(client, bufnr)
```
Comment (dmitmel) [inline runtime/lua/vim/lsp.lua:1171]: reset_buf has to clear the pending_changes here

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (dmitmel) [reply runtime/lua/vim/lsp.lua:405]: No, changedtick is used for the `version` parameter and is buffer-local

File: runtime/lua/vim/lsp.lua (hunk 3 above)
Comment (mfussenegger) [inline runtime/lua/vim/lsp.lua:1171]: Shouldn't this flush instead of throw it away?

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (dmitmel) [reply runtime/lua/vim/lsp.lua:405]: Also when debounce is off didChange is effectively sent per-buffer and not per-URI

Comment (mfussenegger) [reply runtime/lua/vim/lsp.lua:405]: Can you also update the comment here: 

https://github.com/neovim/neovim/blob/b5b025f6a3ad406929c096f63b5f1e7649d3c818/runtime/lua/vim/lsp.lua#L323

File: runtime/lua/vim/lsp.lua (hunk 3 above)
Comment (dmitmel) [reply runtime/lua/vim/lsp.lua:1171]: `client.notify` doesn't cause a flush

Comment (dmitmel) [reply runtime/lua/vim/lsp.lua:1171]: That can be fixed too, but I think that explicitly performing a reset here won't hurt

Comment (mfussenegger) [reply runtime/lua/vim/lsp.lua:1171]: I'm aware that notify doesn't flush. It can't flush as long as the debounce itself calls `client.notify` to do the debouncing.

My question is whether this here should be calling flush instead of reset_buf.

Comment (dmitmel) [reply runtime/lua/vim/lsp.lua:1171]: Well, currently calling `flush` makes more sense because `reset_buf` currently doesn't delete the entry in `pending_changes` for the buffer, but that is beside the point. The thing is that we are sending new buffer contents immediately afterwards, and with the pending didChange events meant to be applied to the version of the buffer before reload, they are basically useless because their results will be discarded as soon as the client processes didOpen. Thus I think that it is better to throw them away.

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp.lua:405]: > No, changedtick is used for the version parameter and is buffer-local

This isn't relevant, because URI is effectively bufnr in this case.

> Also when debounce is off didChange is effectively sent per-buffer and not per-URI

I don't see the issue with this

File: runtime/lua/vim/lsp.lua (hunk 3 above)
Comment (mjlbach) [reply runtime/lua/vim/lsp.lua:1171]: There's no point to flushing as we send the full document here https://github.com/mjlbach/neovim/blob/988fd1d825c99e6212f25c10236eda528a89dda1/runtime/lua/vim/lsp.lua#L478-L486

I'll modify reset_buf to flush pending changes (I thought we overwriting state entirely in change_tracking.init

File: runtime/lua/vim/lsp.lua (hunk 1 above)
Comment (dmitmel) [reply runtime/lua/vim/lsp.lua:405]: What's the deal with URI sanitization on Windows, then?

**Comment by YorickPeterse** [comment]
I'm giving the changes in this PR a spin. So far they seem to solve the issues outlined in https://github.com/neovim/neovim/issues/16424 nicely.

**Comment by YorickPeterse** [comment]
I think I found an issue that may be related, which happens on both `master` and this PR. To reproduce, create a Rust file with this content:

```rust
pub(crate) struct TypeParameter {
    name: String,
    requirements: Vec<()>,
}

impl TypeParameter {
    pub(crate) fn new(name: String) -> Self {
        Self { name, requirements: Vec::new() }
    }
}

fn main() {}
```

Then do the following:

1. Insert a space somewhere
2. Format and save the file using `exe 'lua vim.lsp.buf.formatting_sync(nil, 5000)' | w`
3. Undo the changes
4. Run `exe 'lua vim.lsp.buf.formatting_sync(nil, 5000)' | w` again

In my setup, this results in the buffer being formatted like this:

```
pub(crate) struct TypeParameter {
    name: String,
    requirements: Vec<()>,
}

impl TypeParameter {
    pub(crate) fn new(name: String) -> Self {
        Self {
            name,
           ,
        name, requirements: Vec::new() }
    }
}

fn main() {}
```

This happens even with debouncing disabled. It also happens regardless of what `allow_incremental_sync` is set to. It doesn't happen when I run `rustfmt` on the file directly, so I don't think it's a rustfmt issue.

**Comment by YorickPeterse** [comment]
The rust-analyzer buffer states in this case are:

**initial**:

```rust
pub(crate) struct TypeParameter {
    name: String,
    requirements: Vec<()>,
}

impl TypeParameter {
    pub(crate) fn new(name: String) -> Self {
        Self { name, requirements: Vec::new() }
    }
}

fn main() {}
```

**undo followed by the `exe` format**:

```rust
pub(crate) struct TypeParameter {
    name: String,
    requirements: Vec<()>,
}

impl TypeParameter {
    pub(crate) fn new(name: String) -> Self {
        Self {
            name,
            requirements: Vec::new(),
        }
    }
}

fn main() {}
```

**another undo followed by the `exe` format**:

```rust
pub(crate) struct TypeParameter {
    name: String,
    requirements: Vec<()>,
}

impl TypeParameter {
    pub(crate) fn new(name: String) -> Self {
        Self { name, requirements: Vec::new() }
    }
}

fn main() {}
```

At this point however the buffer in NeoVim looks like this:

```rust
pub(crate) struct TypeParameter {
    name: String,
    requirements: Vec<()>,
}

impl TypeParameter {
    pub(crate) fn new(name: String) -> Self {
        Self {
            name,
           ,
        name, requirements: Vec::new() }
    }
}

fn main() {}
```

So something in NeoVim (I guess?) is resulting in a mismatch between what NeoVim
is displaying, and what rust-analyzer thinks the buffer looks like.

**Comment by YorickPeterse** [comment]
LSP debug logs for when this is happening:

```
[START][2021-11-25 22:34:48] LSP logging initiated
[DEBUG][2021-11-25 22:35:03] .../lua/vim/lsp.lua:956	"LSP[rust_analyzer]"	"client.request"	1	"textDocument/formatting"	{  options = {    insertSpaces = true,    tabSize = 4  },  textDocument = {    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"  }}	<function 1>	1
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 2,  jsonrpc = "2.0",  method = "textDocument/formatting",  params = {    options = {      insertSpaces = true,      tabSize = 4    },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"    }  }}
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 2,  jsonrpc = "2.0",  result = { {      newText = "\n            name,\n           ",      range = {        end = {          character = 20,          line = 7        },        start = {          character = 14,          line = 7        }      }    }, {      newText = ",\n       ",      range = {        end = {          character = 45,          line = 7        },        start = {          character = 45,          line = 7        }      }    } }}
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:344	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 47,            line = 7          },          start = {            character = 45,            line = 7          }        },        rangeLength = 2,        text = ",\n        }"      }, {        range = {          end = {            character = 46,            line = 7          },          start = {            character = 14,            line = 7          }        },        rangeLength = 32,        text = "\n            name,\n            requirements: Vec::new(),"      } },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",      version = 6    }  }}
[DEBUG][2021-11-25 22:35:03] .../lua/vim/lsp.lua:956	"LSP[rust_analyzer]"	"client.request"	1	"textDocument/formatting"	{  options = {    insertSpaces = true,    tabSize = 4  },  textDocument = {    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"  }}	<function 1>	1
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 3,  jsonrpc = "2.0",  method = "textDocument/formatting",  params = {    options = {      insertSpaces = true,      tabSize = 4    },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"    }  }}
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 3,  jsonrpc = "2.0"}
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:344	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didSave",  params = {    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"    }  }}
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 11,  jsonrpc = "2.0",  method = "window/workDoneProgress/create",  params = {    token = "rustAnalyzer/cargo check"  }}
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/cargo check",    value = {      kind = "begin",      title = "cargo check"    }  }}
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:461	"server_request: callback result"	{  result = vim.NIL,  status = true}
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 11,  jsonrpc = "2.0",  result = vim.NIL}
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "dead_code",        message = "struct is never constructed: `TypeParameter`\n`#[warn(dead_code)]` on by default",        range = {          end = {            character = 31,            line = 0          },          start = {            character = 18,            line = 0          }        },        severity = 2,        source = "rustc",        tags = { 1 }      }, {        code = "dead_code",        message = "associated function is never used: `new`",        range = {          end = {            character = 21,            line = 6          },          start = {            character = 18,            line = 6          }        },        severity = 2,        source = "rustc",        tags = { 1 }      } },    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",    version = 6  }}
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/cargo check",    value = {      kind = "report",      message = "playground"    }  }}
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/cargo check",    value = {      kind = "report",      message = "playground"    }  }}
[DEBUG][2021-11-25 22:35:03] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/cargo check",    value = {      kind = "end"    }  }}
[DEBUG][2021-11-25 22:35:07] .../vim/lsp/rpc.lua:344	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 37,            line = 9          },          start = {            character = 14,            line = 7          }        },        rangeLength = 56,        text = " name, requirements: Vec::new(),"      }, {        range = {          end = {            character = 9,            line = 8          },          start = {            character = 45,            line = 7          }        },        rangeLength = 11,        text = " }"      } },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",      version = 9    }  }}
[DEBUG][2021-11-25 22:35:10] .../lua/vim/lsp.lua:956	"LSP[rust_analyzer]"	"client.request"	1	"textDocument/formatting"	{  options = {    insertSpaces = true,    tabSize = 4  },  textDocument = {    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"  }}	<function 1>	1
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 4,  jsonrpc = "2.0",  method = "textDocument/formatting",  params = {    options = {      insertSpaces = true,      tabSize = 4    },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"    }  }}
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 4,  jsonrpc = "2.0",  result = { {      newText = "\n            name,\n           ",      range = {        end = {          character = 20,          line = 7        },        start = {          character = 14,          line = 7        }      }    }, {      newText = ",\n       ",      range = {        end = {          character = 45,          line = 7        },        start = {          character = 45,          line = 7        }      }    } }}
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:344	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 47,            line = 7          },          start = {            character = 14,            line = 7          }        },        rangeLength = 33,        text = ",\n        name, requirements: Vec::new() }"      }, {        range = {          end = {            character = 15,            line = 7          },          start = {            character = 14,            line = 7          }        },        rangeLength = 1,        text = "\n            name,\n           ,"      } },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",      version = 12    }  }}
[DEBUG][2021-11-25 22:35:10] .../lua/vim/lsp.lua:956	"LSP[rust_analyzer]"	"client.request"	1	"textDocument/formatting"	{  options = {    insertSpaces = true,    tabSize = 4  },  textDocument = {    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"  }}	<function 1>	1
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 5,  jsonrpc = "2.0",  method = "textDocument/formatting",  params = {    options = {      insertSpaces = true,      tabSize = 4    },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"    }  }}
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected identifier",        range = {          end = {            character = 11,            line = 9          },          start = {            character = 11,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected COMMA",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 12,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        code = "dead_code",        message = "struct is never constructed: `TypeParameter`\n`#[warn(dead_code)]` on by default",        range = {          end = {            character = 31,            line = 0          },          start = {            character = 18,            line = 0          }        },        severity = 2,        source = "rustc",        tags = { 1 }      }, {        code = "dead_code",        message = "associated function is never used: `new`",        range = {          end = {            character = 21,            line = 6          },          start = {            character = 18,            line = 6          }        },        severity = 2,        source = "rustc",        tags = { 1 }      } },    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",    version = 12  }}
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 5,  jsonrpc = "2.0"}
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:344	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didSave",  params = {    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"    }  }}
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 12,  jsonrpc = "2.0",  method = "window/workDoneProgress/create",  params = {    token = "rustAnalyzer/cargo check"  }}
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/cargo check",    value = {      kind = "begin",      title = "cargo check"    }  }}
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:461	"server_request: callback result"	{  result = vim.NIL,  status = true}
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 12,  jsonrpc = "2.0",  result = vim.NIL}
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected identifier",        range = {          end = {            character = 11,            line = 9          },          start = {            character = 11,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected COMMA",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 12,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      } },    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",    version = 12  }}
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected identifier",        range = {          end = {            character = 11,            line = 9          },          start = {            character = 11,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected COMMA",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 12,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        message = "expected identifier, found `,`\nexpected identifier",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 11,            line = 9          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 7                },                start = {                  character = 8,                  line = 7                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "while parsing this struct"          }, {            location = {              range = {                end = {                  character = 12,                  line = 9                },                start = {                  character = 11,                  line = 9                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "remove this comma"          } },        severity = 1,        source = "rustc"      }, {        message = "while parsing this struct",        range = {          end = {            character = 12,            line = 7          },          start = {            character = 8,            line = 7          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 9                },                start = {                  character = 11,                  line = 9                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "original diagnostic"          } },        severity = 4,        source = "rustc"      }, {        message = "remove this comma",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 11,            line = 9          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 9                },                start = {                  character = 11,                  line = 9                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "original diagnostic"          } },        severity = 4,        source = "rustc"      } },    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",    version = 12  }}
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected identifier",        range = {          end = {            character = 11,            line = 9          },          start = {            character = 11,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected COMMA",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 12,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        message = "expected identifier, found `,`\nexpected identifier",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 11,            line = 9          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 7                },                start = {                  character = 8,                  line = 7                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "while parsing this struct"          }, {            location = {              range = {                end = {                  character = 12,                  line = 9                },                start = {                  character = 11,                  line = 9                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "remove this comma"          } },        severity = 1,        source = "rustc"      }, {        message = "while parsing this struct",        range = {          end = {            character = 12,            line = 7          },          start = {            character = 8,            line = 7          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 9                },                start = {                  character = 11,                  line = 9                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "original diagnostic"          } },        severity = 4,        source = "rustc"      }, {        message = "remove this comma",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 11,            line = 9          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 9                },                start = {                  character = 11,                  line = 9                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "original diagnostic"          } },        severity = 4,        source = "rustc"      }, {        code = "E0062",        codeDescription = {          href = "https://doc.rust-lang.org/error-index.html#E0062"        },        message = "field `name` specified more than once\nused more than once",        range = {          end = {            character = 12,            line = 10          },          start = {            character = 8,            line = 10          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 16,                  line = 8                },                start = {                  character = 12,                  line = 8                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "first use of `name`"          } },        severity = 1,        source = "rustc"      }, {        code = "E0062",        codeDescription = {          href = "https://doc.rust-lang.org/error-index.html#E0062"        },        message = "first use of `name`",        range = {          end = {            character = 16,            line = 8          },          start = {            character = 12,            line = 8          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 10                },                start = {                  character = 8,                  line = 10                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "original diagnostic"          } },        severity = 4,        source = "rustc"      } },    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",    version = 12  }}
[DEBUG][2021-11-25 22:35:10] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/cargo check",    value = {      kind = "end"    }  }}
[DEBUG][2021-11-25 22:35:15] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 6,  jsonrpc = "2.0",  method = "shutdown"}
[DEBUG][2021-11-25 22:35:15] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 6,  jsonrpc = "2.0"}
[DEBUG][2021-11-25 22:35:15] .../vim/lsp/rpc.lua:344	"rpc.send"	{  jsonrpc = "2.0",  method = "exit"}
[INFO][2021-11-25 22:35:18] .../lua/vim/lsp.lua:1273	"exit_handler"	{}
```

**Comment by YorickPeterse** [comment]
It seems a key step here is to undo the changes made by the formatting call. If I continue editing the file and format it after that, the buffer never gets messed up.

It doesn't appear to be a timing issue either: I can wait all I want after the undo, the next time I format the buffer it gets messed up.

**Comment by YorickPeterse** [comment]
Here are the logs when incremental sync is disabled:

```
[START][2021-11-25 22:47:15] LSP logging initiated
[DEBUG][2021-11-25 22:47:21] .../lua/vim/lsp.lua:956	"LSP[rust_analyzer]"	"client.request"	1	"textDocument/formatting"	{  options = {    insertSpaces = true,    tabSize = 4  },  textDocument = {    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"  }}	<function 1>	1
[DEBUG][2021-11-25 22:47:21] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 2,  jsonrpc = "2.0",  method = "textDocument/formatting",  params = {    options = {      insertSpaces = true,      tabSize = 4    },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"    }  }}
[DEBUG][2021-11-25 22:47:22] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 2,  jsonrpc = "2.0",  result = { {      newText = "\n            name,\n           ",      range = {        end = {          character = 20,          line = 7        },        start = {          character = 14,          line = 7        }      }    }, {      newText = ",\n       ",      range = {        end = {          character = 45,          line = 7        },        start = {          character = 45,          line = 7        }      }    } }}
[DEBUG][2021-11-25 22:47:22] .../vim/lsp/rpc.lua:344	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        text = "pub(crate) struct TypeParameter {\n    name: String,\n    requirements: Vec<()>,\n}\n\nimpl TypeParameter {\n    pub(crate) fn new(name: String) -> Self {\n        Self {\n            name,\n            requirements: Vec::new(),\n        }\n    }\n}\n\nfn main() {}\n"      } },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",      version = 5    }  }}
[DEBUG][2021-11-25 22:47:22] .../lua/vim/lsp.lua:956	"LSP[rust_analyzer]"	"client.request"	1	"textDocument/formatting"	{  options = {    insertSpaces = true,    tabSize = 4  },  textDocument = {    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"  }}	<function 1>	1
[DEBUG][2021-11-25 22:47:22] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 3,  jsonrpc = "2.0",  method = "textDocument/formatting",  params = {    options = {      insertSpaces = true,      tabSize = 4    },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"    }  }}
[DEBUG][2021-11-25 22:47:22] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 3,  jsonrpc = "2.0"}
[DEBUG][2021-11-25 22:47:22] .../vim/lsp/rpc.lua:344	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didSave",  params = {    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"    }  }}
[DEBUG][2021-11-25 22:47:22] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 11,  jsonrpc = "2.0",  method = "window/workDoneProgress/create",  params = {    token = "rustAnalyzer/cargo check"  }}
[DEBUG][2021-11-25 22:47:22] .../vim/lsp/rpc.lua:461	"server_request: callback result"	{  result = vim.NIL,  status = true}
[DEBUG][2021-11-25 22:47:22] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 11,  jsonrpc = "2.0",  result = vim.NIL}
[DEBUG][2021-11-25 22:47:22] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/cargo check",    value = {      kind = "begin",      title = "cargo check"    }  }}
[DEBUG][2021-11-25 22:47:22] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "dead_code",        message = "struct is never constructed: `TypeParameter`\n`#[warn(dead_code)]` on by default",        range = {          end = {            character = 31,            line = 0          },          start = {            character = 18,            line = 0          }        },        severity = 2,        source = "rustc",        tags = { 1 }      }, {        code = "dead_code",        message = "associated function is never used: `new`",        range = {          end = {            character = 21,            line = 6          },          start = {            character = 18,            line = 6          }        },        severity = 2,        source = "rustc",        tags = { 1 }      } },    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",    version = 5  }}
[DEBUG][2021-11-25 22:47:22] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/cargo check",    value = {      kind = "report",      message = "playground"    }  }}
[DEBUG][2021-11-25 22:47:22] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/cargo check",    value = {      kind = "report",      message = "playground"    }  }}
[DEBUG][2021-11-25 22:47:22] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/cargo check",    value = {      kind = "end"    }  }}
[DEBUG][2021-11-25 22:47:27] .../vim/lsp/rpc.lua:344	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        text = "pub(crate) struct TypeParameter {\n    name: String,\n    requirements: Vec<()>,\n}\n\nimpl TypeParameter {\n    pub(crate) fn new(name: String) -> Self {\n        Self { name, requirements: Vec::new() }\n    }\n}\n\nfn main() {}\n"      } },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",      version = 8    }  }}
[DEBUG][2021-11-25 22:47:30] .../lua/vim/lsp.lua:956	"LSP[rust_analyzer]"	"client.request"	1	"textDocument/formatting"	{  options = {    insertSpaces = true,    tabSize = 4  },  textDocument = {    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"  }}	<function 1>	1
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 4,  jsonrpc = "2.0",  method = "textDocument/formatting",  params = {    options = {      insertSpaces = true,      tabSize = 4    },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"    }  }}
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 4,  jsonrpc = "2.0",  result = { {      newText = "\n            name,\n           ",      range = {        end = {          character = 20,          line = 7        },        start = {          character = 14,          line = 7        }      }    }, {      newText = ",\n       ",      range = {        end = {          character = 45,          line = 7        },        start = {          character = 45,          line = 7        }      }    } }}
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:344	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        text = "pub(crate) struct TypeParameter {\n    name: String,\n    requirements: Vec<()>,\n}\n\nimpl TypeParameter {\n    pub(crate) fn new(name: String) -> Self {\n        Self {\n            name,\n           ,\n        name, requirements: Vec::new() }\n    }\n}\n\nfn main() {}\n"      } },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",      version = 11    }  }}
[DEBUG][2021-11-25 22:47:30] .../lua/vim/lsp.lua:956	"LSP[rust_analyzer]"	"client.request"	1	"textDocument/formatting"	{  options = {    insertSpaces = true,    tabSize = 4  },  textDocument = {    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"  }}	<function 1>	1
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 5,  jsonrpc = "2.0",  method = "textDocument/formatting",  params = {    options = {      insertSpaces = true,      tabSize = 4    },    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"    }  }}
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected identifier",        range = {          end = {            character = 11,            line = 9          },          start = {            character = 11,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected COMMA",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 12,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        code = "dead_code",        message = "struct is never constructed: `TypeParameter`\n`#[warn(dead_code)]` on by default",        range = {          end = {            character = 31,            line = 0          },          start = {            character = 18,            line = 0          }        },        severity = 2,        source = "rustc",        tags = { 1 }      }, {        code = "dead_code",        message = "associated function is never used: `new`",        range = {          end = {            character = 21,            line = 6          },          start = {            character = 18,            line = 6          }        },        severity = 2,        source = "rustc",        tags = { 1 }      } },    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",    version = 11  }}
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 5,  jsonrpc = "2.0"}
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:344	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didSave",  params = {    textDocument = {      uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"    }  }}
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 12,  jsonrpc = "2.0",  method = "window/workDoneProgress/create",  params = {    token = "rustAnalyzer/cargo check"  }}
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/cargo check",    value = {      kind = "begin",      title = "cargo check"    }  }}
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:461	"server_request: callback result"	{  result = vim.NIL,  status = true}
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 12,  jsonrpc = "2.0",  result = vim.NIL}
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected identifier",        range = {          end = {            character = 11,            line = 9          },          start = {            character = 11,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected COMMA",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 12,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      } },    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",    version = 11  }}
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected identifier",        range = {          end = {            character = 11,            line = 9          },          start = {            character = 11,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected COMMA",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 12,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        message = "expected identifier, found `,`\nexpected identifier",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 11,            line = 9          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 7                },                start = {                  character = 8,                  line = 7                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "while parsing this struct"          }, {            location = {              range = {                end = {                  character = 12,                  line = 9                },                start = {                  character = 11,                  line = 9                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "remove this comma"          } },        severity = 1,        source = "rustc"      }, {        message = "while parsing this struct",        range = {          end = {            character = 12,            line = 7          },          start = {            character = 8,            line = 7          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 9                },                start = {                  character = 11,                  line = 9                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "original diagnostic"          } },        severity = 4,        source = "rustc"      }, {        message = "remove this comma",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 11,            line = 9          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 9                },                start = {                  character = 11,                  line = 9                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "original diagnostic"          } },        severity = 4,        source = "rustc"      } },    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",    version = 11  }}
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected identifier",        range = {          end = {            character = 11,            line = 9          },          start = {            character = 11,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        code = "syntax-error",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#syntax-error"        },        message = "Syntax Error: expected COMMA",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 12,            line = 9          }        },        severity = 1,        source = "rust-analyzer"      }, {        message = "expected identifier, found `,`\nexpected identifier",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 11,            line = 9          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 7                },                start = {                  character = 8,                  line = 7                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "while parsing this struct"          }, {            location = {              range = {                end = {                  character = 12,                  line = 9                },                start = {                  character = 11,                  line = 9                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "remove this comma"          } },        severity = 1,        source = "rustc"      }, {        message = "while parsing this struct",        range = {          end = {            character = 12,            line = 7          },          start = {            character = 8,            line = 7          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 9                },                start = {                  character = 11,                  line = 9                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "original diagnostic"          } },        severity = 4,        source = "rustc"      }, {        message = "remove this comma",        range = {          end = {            character = 12,            line = 9          },          start = {            character = 11,            line = 9          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 9                },                start = {                  character = 11,                  line = 9                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "original diagnostic"          } },        severity = 4,        source = "rustc"      }, {        code = "E0062",        codeDescription = {          href = "https://doc.rust-lang.org/error-index.html#E0062"        },        message = "field `name` specified more than once\nused more than once",        range = {          end = {            character = 12,            line = 10          },          start = {            character = 8,            line = 10          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 16,                  line = 8                },                start = {                  character = 12,                  line = 8                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "first use of `name`"          } },        severity = 1,        source = "rustc"      }, {        code = "E0062",        codeDescription = {          href = "https://doc.rust-lang.org/error-index.html#E0062"        },        message = "first use of `name`",        range = {          end = {            character = 16,            line = 8          },          start = {            character = 12,            line = 8          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 12,                  line = 10                },                start = {                  character = 8,                  line = 10                }              },              uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs"            },            message = "original diagnostic"          } },        severity = 4,        source = "rustc"      } },    uri = "file:///home/yorickpeterse/Projects/rust/playground/src/main.rs",    version = 11  }}
[DEBUG][2021-11-25 22:47:30] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/cargo check",    value = {      kind = "end"    }  }}
[DEBUG][2021-11-25 22:47:37] .../vim/lsp/rpc.lua:344	"rpc.send"	{  id = 6,  jsonrpc = "2.0",  method = "shutdown"}
[DEBUG][2021-11-25 22:47:37] .../vim/lsp/rpc.lua:451	"rpc.receive"	{  id = 6,  jsonrpc = "2.0"}
[DEBUG][2021-11-25 22:47:37] .../vim/lsp/rpc.lua:344	"rpc.send"	{  jsonrpc = "2.0",  method = "exit"}
[INFO][2021-11-25 22:47:41] .../lua/vim/lsp.lua:1273	"exit_handler"	{}
```

File: runtime/lua/vim/lsp.lua (hunk 3 above)
Comment (mfussenegger) [reply runtime/lua/vim/lsp.lua:1170]: I think `debounce` should only debounce - not additionally optimize away change sets, even if they're most likely unnecessary. I'm pretty sure the optimization wouldn't have any practical impact.

And I think keeping the semantics of debounce on/off close to each other helps reasoning about potential issues or with trouble shooting. Both should result in the same set of changes getting eventually reported to the server (although in a different format due the batching)

File: runtime/lua/vim/lsp.lua [hunk 4]
```diff
@@ -402,27 +401,36 @@ do
...
+                uri = change_uri;
+                version = util.buf_versions[vim.uri_to_bufnr(change_uri)];
+              };
+              contentChanges = content_changes,
+            })
+          end
           state.pending_changes = {}
         else
-          contentChanges = { full_changes(), }
+          client.notify("textDocument/didChange", {
```
Comment (dmitmel) [inline runtime/lua/vim/lsp.lua:426]: Will this not result in the reported issue if incremental sync is disable? Doesn't the `if` above which adds to `pending_changes` be rewritten as
```lua
      if state.use_incremental_sync then
        if not state.pending_changes[uri] then
          state.pending_changes[uri] = {}
        end
        table.insert(state.pending_changes[uri], incremental_changes(client))
      else
        state.pending_changes[uri] = true
      end
```
or something like that, and this one to
```lua
        -- drop the outer `if state.use_incremental_sync`
        for change_uri, content_changes in pairs(state.pending_changes) do
          if state.use_incremental_sync then
            content_changes = full_changes()
          end
          client.notify("textDocument/didChange", {
            textDocument = {
              uri = change_uri;
              version = util.buf_versions[vim.uri_to_bufnr(change_uri)];
            };
            contentChanges = content_changes,
          })
        end
        state.pending_changes = nil
```

Comment (dmitmel) [reply runtime/lua/vim/lsp.lua:426]: @mjlbach Could you please take a look?

Comment (mfussenegger) [reply runtime/lua/vim/lsp.lua:426]: If you can provide an example that breaks (or even better, produce a test case) I can have a closer look.

Comment (dmitmel) [reply runtime/lua/vim/lsp.lua:426]: Nevermind, I checked the repro posted in the original instance with the exact same settings, but `allow_incremental_sync` disabled, and, apparently, it doesn't show up.

Comment (mjlbach) [reply runtime/lua/vim/lsp.lua:426]: I agree the way I chose to implement it is kinda messy and probably could be cleaned up to make more explicit
