### PR TITLE
fix(msgpack): flush incomplete big UI event before packing RPC event

### LINKED ISSUE #31316: Regression: race condition(?) in msgpack handling (from dc37c1550bed46fffbb677d343cdc5bc94056219)
### Problem

When sending very large completion lists to a GUI client that supports ext_popup with text input going at the same time, it's possible to trigger a race condition that causes neovim to return one of the completion results with the same message id as we expect for the RPC result response. I've attached a log with a debug trace of some of the RPC transactions happening between neovim-gtk and neovim that seem to cause this. [race-reproduced.txt](https://github.com/user-attachments/files/17877569/race-reproduced.txt)

I managed to do some bisecting on neovim and tracked the breaking change down to dc37c1550bed46fffbb677d343cdc5bc94056219

### Steps to reproduce

~~I know, I'm really sorry :(. There's supposed to be some steps here, but I am going to need a bit of assistance from y'all in coming up with a reasonable way to reproduce this without pulling in my whole setup. I'm going to do my best to figure something out next week or after Thanksgiving if I can, but hopefully this is a start and maybe you guys have some ideas on how I could come up with a simpler reproducer. I think the key is going to be figuring out how I can get nvim to spit out a super large list of completion results without having my .vimrc present or needing to be in a project source tree.~~

Sorry it took so long! [We have a reproducer now](https://github.com/neovim/neovim/issues/31316#issuecomment-2691626043)

Also FWIW: The good news is I can reproduce this very reliably on my own system, as can a number of other people with substantially different setups than my own (and am going to ask anyone with an easy reproducer for this to make a post here)[race-reproduced.txt](https://github.com/user-attachments/files/17877567/race-reproduced.txt)
. Anyway: I'm going to give you the steps I'm following locally here, and hopefully we can figure something out.

* Have LSP setup on neovim, the LSP configuration I'm currently using is for rust-analyzer and the code I'm using to reproduce this problem is a kernel source tree here
* Use neovim-gtk (hopefully other clients can hit this, but with how hard it was to find a consistent reproducer for this it's -probably- better just to use my client for now)
* Open up a project where you can get neovim to generate a really, really big set of results for autocompletion. Ideally, it should lag things a bit.
* Start typing such that neovim starts popping up completion results using neovim-gtk's ext_popup support
* Repeat until it crashes and says it no longer can read messages from neovim.

### Expected behavior

nvim_input should never return anything but a u64 in the response field when responding to an nvim_input call.

### Nvim version (nvim -v)

v0.10.2

### Vim (not Nvim) behaves the same?

N/A (this is related to RPC, so...)

### Operating system/version

Fedora 41

### Terminal name/version

neovim-gtk

### $TERM environment variable

N/A (I think?)

### Installation

From fedora repository, but I can trigger it by building from source

### PR DESCRIPTION
**Pull request by bfredl**
fixes #31316

### CODE REVIEW

File: src/nvim/msgpack_rpc/channel.c [hunk 1]
```diff
@@ -608,6 +608,12 @@ void serialize_response(Channel *channel, MsgpackRpcRequestHandler handler, Mess
 
 static void packer_buffer_init_channels(Channel **chans, size_t nchans, PackerBuffer *packer)
 {
+  for (size_t i = 0; i < nchans; i++) {
+    Channel *chan = chans[i];
+    if (chan->rpc.ui && chan->rpc.ui->incomplete_event) {
+      remote_ui_flush_pending_data(chan->rpc.ui);
```
Comment (justinmk) [inline src/nvim/msgpack_rpc/channel.c:614]: Why not always call `remote_ui_flush_pending_data`? Why only do it when `incomplete_event=true` ?

Also, can we find the UI here instead of storing it on the `ui` field? Is that a performance concern?

File: src/nvim/api/ui.c [hunk 2]
```diff
@@ -47,6 +47,7 @@
 # include "ui_events_remote.generated.h"  // IWYU pragma: export
 #endif
 
+// TODO(bfredl): just make UI:s owned by their channels instead
 static PMap(uint64_t) connected_uis = MAP_INIT;
```
Comment (justinmk) [inline src/nvim/api/ui.c:51]: Is the todo referring to the new `RpcState.ui` field?
