### PR TITLE
screen: fix problem with p_ch

### LINKED ISSUE #14263: Crash when resized below cmdline height
- `nvim --version`:
```
NVIM v0.5.0-dev+1191-gf89bfa686
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/projects/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-699

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

Same result using NVIM v0.4.4.

- `vim -u DEFAULTS` (version: VIM - Vi IMproved 8.1): behaves correctly and won't close
- Operating system/version: Windows 10
- Terminal name/version: PowerShell 7.1.2 or cmd
- `$TERM`: ?

NWBI8Kgzqa

### Steps to reproduce using `nvim -u NORC`

1. Run `nvim -u NORC`
2. Resize cmdline by `set cmdheight=99999`
3. Resize terminal window so its smaller than cmdline height.
4. Notice nvim closed and we are back at shell.

### Actual behaviour

Neovim closes without notice.

### Expected behaviour

Neovim should adapt to fit without closing.

### PR DESCRIPTION
**Pull request by erw7**
When the screen is resized, `p_ch` is not re-set to the appropriate value. As a result, access to invalid addresses was occurring.

fixes #14263.

### CODE REVIEW

File: src/nvim/screen.c [hunk 1]
```diff
@@ -7505,6 +7505,9 @@ void screen_resize(int width, int height)
   ++busy;
 
   Rows = height;
+  if (!ui_has(kUIMessages) && p_ch > Rows - min_rows() - 1) {
```
Comment (bfredl) [inline src/nvim/screen.c:7508]: Intentional that expressions are different? If not perhaps break out to a var.

Comment (erw7) [reply src/nvim/screen.c]: Oops. Just a mistake.

**Comment by erw7** [comment]
Hmm, I think this change should not change the behavior, but one of the tests in `multigrid_spec.lua` does not pass.

<details>
<summary>multigrid_spec.lua</summary>
<pre><code>
  test/functional/ui/multigrid_spec.lua:764: Expected screen height 8 differs from actual height 9.
  Expected:
    |## grid 1
    |  [2:------------]|
    |*  {11:[No Name]   }|
    |*  [3:------------]|
    |## grid 2
    |  ^            |
    |*## grid 3
    |*              |
  Actual:
    |## grid 1
    |  [2:------------]|
    |*  [2:------------]|
    |*  [2:------------]|
    |## grid 2
    |  ^            |
    |*  {1:~           }|
    |*  {1:~           }|
    |## grid 3
  
  To print the expect() call that would assert the current screen state, use
  screen:snapshot_util(). In case of non-deterministic failures, use
  screen:redraw_debug() to show all intermediate screen states.  
  
  stack traceback:
  	test/functional/ui/screen.lua:586: in function '_wait'
  	test/functional/ui/screen.lua:362: in function 'expect'
  	test/functional/ui/multigrid_spec.lua:764: in function <test/functional/ui/multigrid_spec.lua:762>
</pre></code>
</details>

File: src/nvim/screen.c [hunk 2]
```diff
@@ -7505,6 +7505,10 @@ void screen_resize(int width, int height)
   ++busy;
 
   Rows = height;
+  int max_p_ch = Rows - min_rows() + 1;
```
Comment (bfredl) [inline src/nvim/screen.c:7508]: you want this check below `check_shellsize()`, that should fix the text failure.

Comment (erw7) [reply src/nvim/screen.c:7510]: @bfredl thanks. With that change, it now passes the test locally.

**Review by bfredl — APPROVED** [review]
