### PR TITLE
fix(drawline): combine extmark highlight with area hl correctly

### LINKED ISSUE #23734: extmark-highlight does not cover a full tab (`\t`)
### Problem

highlight applied via extmarks only highlights the first column of a tab, instead of all 2/4/8/whatever.

Pre- efa9b299a:
screen
Post:
screen

Not completely sure if this should be a bug-report, just seems like a potentially undesired change.

### Steps to reproduce

1. `nvim --clean`
2. Insert some text with tabs into the buffer, for example
```
asdf
	asdf
	asdf
	asdf
asdf
```
(note that the "asdf" are indented by tabs.)
3. Call `:lua vim.api.nvim_create_namespace("") vim.api.nvim_buf_set_extmark(0,1,0,0, {end_row = 5, end_col=0, hl_group = "Visual"})` to highlight the lines.

### Expected behavior

As shown above, only the first column of a tab is highlighted, as opposed to all columns that belong to it.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-373+g07883940b2

### Vim (not Nvim) behaves the same?

not applicable I think

### Operating system/version

Linux 6.3.2

### Terminal name/version

foot

### $TERM environment variable

foot

### Installation

AUR

### PR DESCRIPTION
**Pull request by bfredl**
fixes #23734

Get rid of the weird `attr_pri` dance which always seemed like a kludge:
```
            if (!attr_pri) {
              wlv.char_attr = hl_combine_attr(wlv.char_attr, extmark_attr);
            } else {
              wlv.char_attr = hl_combine_attr(extmark_attr, wlv.char_attr);
            }
```

Instead combine extmark attrs with (old-skool) syntax attrs in a consistent way and then combine that with `attr_pri` and the rest in an unified code path

### CODE REVIEW

**Comment by luukvbaal** [comment]
This conflicts with #23726, will this also fix #23722?

File: src/nvim/drawline.c [hunk 1]
```diff
@@ -2110,21 +2106,34 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool nochange,
...
+
+          decor_conceal = decor_state.conceal;
+          if (decor_conceal && decor_state.conceal_char) {
+            decor_conceal = 2;  // really??
+          }
+
+          can_spell = TRISTATE_TO_BOOL(decor_state.spell, can_spell);
+        }
+
         // Get syntax attribute, unless still at the start of the line
```
Comment (luukvbaal) [inline src/nvim/drawline.c:2126]: Keeping this comment on top (and edited to mention extmark instead of syntax) like #23726 did might be preferred?

Comment (bfredl) [reply src/nvim/drawline.c]: done

**Comment by zeertzjq** [comment]
https://github.com/vim/vim/commit/3439028c8909aaa71ffe612a7191babdfe07c04c may also be related

File: src/nvim/drawline.c [hunk 2]
```diff
@@ -2110,21 +2106,34 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool nochange,
...
         v = (ptr - line);
+        if (has_decor && v > 0) {
+          decor_attr = extmark_attr;
+
+          decor_conceal = decor_state.conceal;
+          if (decor_conceal && decor_state.conceal_char) {
+            decor_conceal = 2;  // really??
+          }
+
+          can_spell = TRISTATE_TO_BOOL(decor_state.spell, can_spell);
```
Comment (luukvbaal) [inline src/nvim/drawline.c:2125]: This change from #23726 works to fix the failing test, without breaking others...
```diff
@@ -2121,8 +2121,6 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool nochange,
           if (decor_conceal && decor_state.conceal_char) {
             decor_conceal = 2;  // really??
           }
-
-          can_spell = TRISTATE_TO_BOOL(decor_state.spell, can_spell);
         }

         if (has_syntax && v > 0) {
@@ -2183,7 +2181,8 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool nochange,
         v = (ptr - line);
         if (has_spell && v >= word_end && v > cur_checked_col) {
           spell_attr = 0;
-          if (c != 0 && ((!has_syntax && !no_plain_buffer) || can_spell)) {
+          if (c != 0 && ((!has_syntax && can_spell) ||
+                         TRISTATE_TO_BOOL(decor_state.spell, can_spell))) {
             char *prev_ptr;
             char *p;
             int len;
```

**Comment by bfredl** [comment]
I tried to make the test case from #23739 work but it looks tricky. would be easier with something like https://github.com/vim/vim/commit/3439028c8909aaa71ffe612a7191babdfe07c04c . will consider it as a follow up.
