### PR TITLE
fix(events): don't exit on SIGTSTP

### LINKED ISSUE #33254: Neovim crashes when suspending via `SIGTSTP`
### Problem

On latest master, Neovim crashes when suspending the program via Ctrl-Z with the message: `Nvim: Caught deadly signal 'SIGTSTP'`

### Steps to reproduce

```
nvim --clean
<Ctrl-Z>
```

### Expected behavior

The program should be suspended successfully and be returned to using `fg`.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-67+gec18ebcb41

### Vim (not Nvim) behaves the same?

No, vim 9.1.754

### Operating system/version

macOS 15.3.2

### Terminal name/version

ghostty 1067cd3d

### $TERM environment variable

xterm-ghostty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by phanen**
Problem: after
https://github.com/neovim/neovim/commit/4dabeff308222307ede8e74a2bd341713a7f7d81,
neovim quit and crash on receive SIGTSTP (Ctrl-Z).

Solution: Don't exit on SIGTSTP (not a deadly signal).

Fix https://github.com/neovim/neovim/issues/33254.

### CODE REVIEW

File: src/nvim/os/signal.c [hunk 1]
```diff
@@ -215,6 +215,10 @@ static void on_signal(SignalWatcher *handle, int signum, void *data)
   case SIGTERM:
 #ifdef SIGTSTP
   case SIGTSTP:
+    if (p_awa) {
+      autowrite_all();
+    }
+    break;
 #endif
 #ifdef SIGQUIT
```
Comment (justinmk) [inline src/nvim/os/signal.c:223]: move `SIGTERM` above this

**Comment by onion108** [comment]
It's great that it doesn't crash anymore, but when I press `C-z` it just blink and then returned to `nvim`... rather than being paused normally, returning to shell and be able to resume again using `fg`

**Comment by phanen** [comment]
That's true... I didn't notice this. Since I'm using a wrapper.
```
echo 'VIMRUNTIME=runtime ./build/bin/nvim -u NONE' > wrapper.sh
bash ./wrapper.sh
```
No idea why now and I will debug for a while...

File: src/nvim/os/signal.c [hunk 2]
```diff
@@ -212,10 +212,14 @@ static void on_signal(SignalWatcher *handle, int signum, void *data)
     // Ignore
     break;
 #endif
-  case SIGTERM:
 #ifdef SIGTSTP
   case SIGTSTP:
+    if (p_awa) {
+      autowrite_all();
```
Comment (justinmk) [inline src/nvim/os/signal.c:218]: Should we drop this for now, given https://github.com/neovim/neovim/pull/33258#issuecomment-2772231011 ? May need to adjust a test.

Comment (onion108) [reply src/nvim/os/signal.c:218]: Yeah I think it couldn't be merged until we solved this problem, and although i kinda figured out why it doesn't work it seems to be really tricky to fix. Maybe need to turn it into a draft for now.

Comment (onion108) [reply src/nvim/os/signal.c:218]: Not enough to remove this line, we need also remove all the code that registers (and the corresponding cleanup code) `SIGTSTOP` handler, or it will still be a blink. As long as the handler exists, we need to suspend by ourselves.

Comment (onion108) [reply src/nvim/os/signal.c:218]: > Not enough to remove this line, we need also remove all the code that registers (and the corresponding cleanup code) `SIGTSTOP` handler, or it will still be a blink. As long as the handler exists, we need to suspend by ourselves.

It's basically reverting most of https://github.com/neovim/neovim/commit/4dabeff308222307ede8e74a2bd341713a7f7d81 (since it mainly adding handlers for `SIGSTOP`, along with some other stuffs)

Comment (justinmk) [reply src/nvim/os/signal.c:218]: Sure, let's revert all `sigstp`-related changes from that commit. But the changes for the other signals can stay.

Comment (onion108) [reply src/nvim/os/signal.c:218]: > Sure, let's revert all `sigstp`-related changes from that commit. But the changes for the other signals can stay.

I checked that commit carefully and confirmed that it's just all about adding handlers to `SIGTSTP` (and adding corresponding tests and documentation), so if removing the code is preferred solution, then it's just revert this commit and all done

Comment (zeertzjq) [reply src/nvim/os/signal.c:218]: You forgot this:
```c
  if (p_awa && signum != SIGTERM) {
    autowrite_all();
  } 
```

Comment (onion108) [reply src/nvim/os/signal.c:218]: > You forgot this:
> 
> ```c
>   if (p_awa && signum != SIGTERM) {
>     autowrite_all();
>   } 
> ```

oh yeah. but others are almost all about `SIGTSTP` and shall be removed

Comment (onion108) [reply src/nvim/os/signal.c:218]: Oh wait... I might find out a nice solution that can preserve this feature and also pause `nvim` normally. I'm going to run tests now.

**Comment by onion108** [comment]
I found a fix that works, but not modifying `src/nvim/os/signal.c`.

Just fire a `SIGSTOP` after https://github.com/neovim/neovim/blob/3af43cffa028b88022e6bdc78a4e2f5470643219/src/nvim/tui/tui.c#L1579 . And `C-z` now works perfectly.

**Comment by onion108** [comment]
> Sure let's try it

Some tests broke on my machine but I reran the tests with my changes discarded and same tests breaks, hence my change doesn't introduce any new bugs, so I guess it's time to call the author of the PR @phanen that this fix works perfectly.

**Comment by onion108** [comment]
The ubuntu's tests looks concerning....
But it's unlikely caused by my code i guess.

Also may I request a co-author on the pull request if it can be merged (?)

**Comment by phanen** [comment]
Test looks irrelated. I'm not sure I understand what happened... because libuv won't catch SIGSTOP? https://github.com/neovim/neovim/blob/bd0a65bc151a7a496e913125f54814f591845e91/runtime/doc/luvref.txt#L1234.

And can we just delete `SIGTSTP`? It seems skipped for unkown reason...

**Comment by onion108** [comment]
> Failed test looks irrelated. I'm not sure I understand what happened... because libuv won't catch SIGSTOP?
> 
> https://github.com/neovim/neovim/blob/bd0a65bc151a7a496e913125f54814f591845e91/runtime/doc/luvref.txt#L1234
> .
Exactly. Since `SIGTSTP` is catched and doesn't work anymore, we just trigger `SIGSTOP` manually to fix that.

> 
> And can we just delete `SIGTSTP`? It seems skipped for unkown reason...
Don't quite understand wdym...? If you're talking about the handler, removing the handler will break the `functionaltest` (added by *that* commit). If you're talking about the `kill(0, SIGTSTP)`, I actually didn't test it. You can try removing it and run `functionaltest`, see if `test/functional/autocmd/signal_spec.lua` breaks. If it didn't, then probably fine.

File: src/nvim/tui/tui.c [hunk 3]
```diff
@@ -1576,7 +1576,8 @@ void tui_suspend(TUIData *tui)
   tui_terminal_stop(tui);
   stream_set_blocking(tui->input.in_fd, true);   // normalize stream (#2598)
 
-  kill(0, SIGTSTP);
+  // kill(0, SIGTSTP);
+  kill(0, SIGSTOP);  // SIGTSTP don't work when also handle it in uv_signal
```
Comment (justinmk) [inline src/nvim/tui/tui.c:1580]:
```suggestion
  kill(0, SIGSTOP);  // Avoid SIGTSTP handler in os/signal.c. #33258
```

File: src/nvim/tui/tui.c [hunk 4]
```diff
@@ -1576,7 +1576,7 @@ void tui_suspend(TUIData *tui)
   tui_terminal_stop(tui);
   stream_set_blocking(tui->input.in_fd, true);   // normalize stream (#2598)
 
-  kill(0, SIGTSTP);
+  kill(0, SIGSTOP);  // Avoid SIGTSTP handler in os/signal.c. #33258
```
Comment (justinmk) [inline src/nvim/tui/tui.c:1579]: without `SIGTSTP`, the `autowrite_all()` won't be called, which defeats the purpose of your other change.
```suggestion
  kill(0, SIGTSTP);  // Triggers autowrite_all() in os/signal.c.
  kill(0, SIGSTOP);
```

Comment (onion108) [reply src/nvim/tui/tui.c:1579]: Weirdly though, I ran the test `test/functional/autocmd/signal_spec.lua` (which contains checks of autowrite) with `kill(0, SIGTSTP)` removed, and it seems to be totally fine... Anyway, let's see the test.

Comment (onion108) [reply src/nvim/tui/tui.c]: Oops. It seems the author pushed the change very quickly. It might be better to see the test result and then comment on it. Anyway I tested a lot on it and it *seems* adding or deleting the `kill(0, SIGTSTP)` doesn't affect anything though, including the functional tests (at least on my machine).

...also begging that ubuntu's tests don't have weird unrelated errors.

Comment (justinmk) [reply src/nvim/tui/tui.c]: > `ex_stop` has already a `auto_writeall` in it:

ok, makes sense. So we can drop the `kill(0, SIGTSTP);` in tui.c.

Comment (onion108) [reply src/nvim/tui/tui.c]: > Another thing: `kill -TSTP client_pid` now no longer ~detach~"stop" the ui. But it will before [4dabeff](https://github.com/neovim/neovim/commit/4dabeff308222307ede8e74a2bd341713a7f7d81).

I think that's quite fair since we don't stop the UI in the signal handler, we only did that in UI's event handler. We may need to call some function on such signal to stop the UI as if the user is stopping it, maybe.

**Comment by onion108** [comment]
>> Another thing: `kill -TSTP client_pid` now no longer ~detach~"stop" the ui. But it will before [4dabeff](https://github.com/neovim/neovim/commit/4dabeff308222307ede8e74a2bd341713a7f7d81).
>
>I think that's quite fair since we don't stop the UI in the signal handler, we only did that in UI's event handler. We may need to call some function on such signal to stop the UI as if the user is stopping it, maybe.

Workaround for this (super quick):
```diff
// in src/nvim/os/signal.c
...
#ifdef SIGTSTP
  case SIGTSTP:
    if (p_awa) {
      autowrite_all();
    }
+   do_cmdline_cmd("suspend");
    break;
#endif
...
```
Don't forget to include the corresponding header `nvim/ex_cmds2.h`.

**Review by justinmk — APPROVED** [review]
Thank you @phanen for seeing this through!
