### PR TITLE
fix(health): improve version check for nightly builds

### LINKED ISSUE #38141: checkhealth: don't consider `nightly` tag commit as outdated
I installed Neovim nightly via scoop: `scoop install versions/neovim-nightly`.

Running `:checkhealth` gives this information:

```
System Info ~
- ⚠️ WARNING Build is outdated. Local: b23d00ce99, Latest: 1901832f26fa
- Nvim version: `v0.12.0-dev-2468+gb23d00ce99` b23d00ce99
- Operating system: Windows_NT 10.0.26200
- Terminal: unknown
- $TERM: unknown
```

This is the same version as the [nightly release page](https://github.com/neovim/neovim/releases/tag/nightly):

```
NVIM v0.12.0-dev-2468+gb23d00ce99
Build type: RelWithDebInfo
LuaJIT 2.1.1772148810
```

It appears as though b23d00ce99 is the latest release, but here it says that 1901832f26fa is the latest version.

Does this qualify as a bug?

### PR DESCRIPTION
**Pull request by glepnir**
Problem: nightly builds were always compared against HEAD, causing false outdated warnings.

Solution: fetch both HEAD and refs/tags/nightly, match local commit against nightly first, fall back to HEAD if no match.

Fix #38141

Outdate Nightly:

image

Latest Nightly:

image

### CODE REVIEW

File: runtime/lua/vim/health/health.lua [hunk 1]
```diff
@@ -573,20 +573,37 @@ end
...
+  local head_sha = refs['HEAD']
+
+  if nightly_sha and vim.startswith(nightly_sha, commit) then
+    vim.health.ok('Up to date (nightly)')
+  elseif head_sha and vim.startswith(head_sha, commit) then
+    vim.health.ok('Up to date (HEAD)')
+  elseif head_sha then
     vim.health.warn(
-      ('Build is outdated. Local: %s, Latest: %s'):format(commit, upstream:sub(1, 12))
+      ('Build is outdated. Local: %s, HEAD: %s Nightly: %s'):format(
```
Comment (seandewar) [inline runtime/lua/vim/health/health.lua]:
```suggestion
      ('Build is outdated. Local: %s, HEAD: %s, Nightly: %s'):format(
```

**Review by seandewar — APPROVED** [review]

File: runtime/lua/vim/health/health.lua [hunk 2]
```diff
@@ -573,20 +573,37 @@ end
...
+  elseif head_sha and vim.startswith(head_sha, commit) then
+    vim.health.ok('Up to date (HEAD)')
+  elseif head_sha then
     vim.health.warn(
-      ('Build is outdated. Local: %s, Latest: %s'):format(commit, upstream:sub(1, 12))
+      ('Build is outdated. Local: %s, HEAD: %s, Nightly: %s'):format(
+        commit,
+        head_sha:sub(1, 12),
+        nightly_sha:sub(1, 12)
+      )
```
Comment (seandewar) [inline runtime/lua/vim/health/health.lua:605]: Actually, is it possible for the `git ls-remote` above to succeed but not return `HEAD`?

Maybe it's possible for the `nightly` tag to be missing though. (like if the release workflow fails after deleting the tag?)

```lua
  local head_sha = assert(refs['HEAD'])
  local nightly_sha = refs['refs/tags/nightly']

  if vim.startswith(head_sha, commit) then
    vim.health.ok('Up to date (HEAD)')
  elseif nightly_sha and vim.startswith(nightly_sha, commit) then
    vim.health.ok('Up to date (nightly)')
  else
    vim.health.warn(
      ('Build is outdated. Local: %s, HEAD: %s%s'):format(
        commit,
        head_sha:sub(1, 12),
        nightly_sha and (', Nightly: ' .. nightly_sha:sub(1, 12)) or ''
      )
    )
  end
```

Would this make sense? (I also gave precedence to printing `(HEAD)` over `(nightly)` if both commits are equal)

Comment (glepnir) [reply runtime/lua/vim/health/health.lua:605]: Oh nice catch!
