### PR TITLE
fix(mouse): click on global statusline with splits

### LINKED ISSUE #19186: Only half of global statusline is clickable when there are two vertical splits
### Neovim version (nvim -v)

v0.8.0-dev+533-g6486b0345

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Run `nvim --clean`
2. Source the following file:
```vim
let g:testvar = ''

function! MyClickFunc(minwid, clicks, button, mods)
  let g:testvar = printf("%d %d %s %d", a:minwid, a:clicks, a:button, localtime())
  if a:mods !=# '    '
    let g:testvar ..= '(' .. a:mods .. ')'
  endif
endfunction

set mouse=a
let &stl = '%0@MyClickFunc@Clicky stuff%T %{g:testvar} %= %0@MyClickFunc@Clicky stuff%T'

set laststatus=3
vsplit
```
3. Click on `Clicky stuff` on the left
4. Click on `Clicky stuff` on the right

### Expected behavior

The numbers on statusline change in steps 3 and 4

### Actual behavior

The numbers on statusline change in step 3 but not in step 4

### PR DESCRIPTION
**Pull request by MunifTanjim**
resolves #19186

### CODE REVIEW

File: src/nvim/normal.c [hunk 1]
```diff
@@ -1908,6 +1908,13 @@ bool do_mouse(oparg_T *oap, int c, int dir, long count, bool fixindent)
     StlClickDefinition *click_defs = in_status_line ? wp->w_status_click_defs
                                                     : wp->w_winbar_click_defs;
 
+    if (in_status_line && p_ls == 3) {
```
Comment (zeertzjq) [inline src/nvim/normal.c:1911]:
```suggestion
    if (in_status_line && gloal_stl_height() > 0) {
```

Comment (zeertzjq) [reply src/nvim/normal.c:1911]: Not sure if `click_grid` also needs to be check here.

Comment (MunifTanjim) [reply src/nvim/normal.c]: Updated.

Is there any documentation about the underlying architecture of the Neovim's UI? I'm not sure what this grid system is 🤔

File: test/functional/ui/statusline_spec.lua [hunk 2]
```diff
@@ -124,6 +124,56 @@ describe('global statusline', function()
...
+          if mods ==# ''
+            let g:testvar = printf("%d %d %s", a:minwid, a:clicks, a:button)
+          else
+            let g:testvar = printf("%d %d %s %s", a:minwid, a:clicks, a:button, mods)
+          endif
+        endfunction
+      ]=])
+    end)
+
+    it("works with vertical splits", function()
```
Comment (justinmk) [inline test/functional/ui/statusline_spec.lua:141]: please move this to the `describe('statusline clicks' ...` block instead of creating a new describe() block. The before_each you added also looks identical to the one there, so don't need it...

Comment (MunifTanjim) [reply test/functional/ui/statusline_spec.lua]: Updated.

File: src/nvim/normal.c (hunk 1 above)
Comment (zeertzjq) [reply src/nvim/normal.c]: Oh, `click_grid` must be `DEFAULT_GRID_HANDLE` if `on_status_line` is `true`, so there is no need to check `click_grid`.

**Review by zeertzjq — APPROVED** [review]
