### PR TITLE
fix(vim.ui): open() may wait indefinitely

### LINKED ISSUE #27986: `vim.ui.open` locks up Neovim until the opened process closes due to `:wait()`
### Problem

As can be seen [here](https://github.com/neovim/neovim/blob/849d82b80b8584fe7918bffc6480f0ec0fda9b9b/runtime/lua/vim/ui.lua#L155), `vim.ui.open` currently opens the process with `detach = true`, **which is good**, but then at the same time waits till it finishes (**is bad**).

This means that Neovim effectively locks up till you close the opened process again.

tbh, I don't really see a lot of cases where this kind of behavior could be useful.

The return value of the function, could still be an error if `vim.ui.open` failed to start the process.
Or even better, just return the task object itself (so `vim.system(cmd, { text = true, detach = true })`), then the caller can still use `:wait()` if they really want to.

I'm willing to make a small PR to fix this, but want to get some input first on wanted behavior.

See also https://github.com/LazyVim/LazyVim/pull/2758

### Steps to reproduce

use `vim.ui.open`

### Expected behavior

should not block

### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256-color

### Installation

bob

### PR DESCRIPTION
**Pull request by justinmk**
Problem:
vim.ui.open "locks up" Nvim if the spawned process does not terminate. #27986

Solution:
- Change `vim.ui.open()`:
    - Do not call `wait()`.
    - Return a `SystemObj`. The caller can decide if it wants to `wait()`.
- Change `gx` to `wait()` only a short time.
    - Allows `gx` to show a message if the command fails, without the risk of waiting forever.

Fix #27986

### CODE REVIEW

File: runtime/lua/vim/_defaults.lua [hunk 1]
```diff
@@ -94,10 +94,19 @@ do
...
-  --- Map |gx| to call |vim.ui.open| on the identifier under the cursor
+  --- Map |gx| to call |vim.ui.open| on the <cfile> at cursor.
   do
     local function do_open(uri)
-      local _, err = vim.ui.open(uri)
+      local cmd, err = vim.ui.open(uri)
+      local rv = cmd and cmd:wait(1000) or nil
+      if cmd and rv then
+        if rv.signal and rv.signal ~= 0 then
+          err = ('vim.ui.open: command timeout: %s'):format(vim.inspect(cmd.cmd))
```
Comment (justinmk) [inline runtime/lua/vim/_defaults.lua:104]: Checking `signal` to detect "timeout" seems hacky. Should we expose a `timeout=true` flag (or some other "status") on the `wait()` result?  @lewis6991

File: runtime/lua/vim/_system.lua [hunk 2]
```diff
@@ -321,7 +324,7 @@ function M.run(cmd, opts, on_exit)
   --- @type vim.SystemState
   local state = {
     done = false,
-    cmd = cmd,
+    cmd = vim.deepcopy(cmd),
```
Comment (justinmk) [inline runtime/lua/vim/_system.lua:327]: Expose `cmd` on `SystemObj`, because it's a basic info that may be needed by consumers (which didn't necessarily originate the `system()` invocation).

I also wonder if `vim.SystemObj` and `vim.SystemCompleted` should be one interface.

File: runtime/lua/vim/ui.lua [hunk 3]
```diff
@@ -114,14 +114,19 @@ end
...
 --- ```lua
+--- -- Asynchronous.
 --- vim.ui.open("https://neovim.io/")
 --- vim.ui.open("~/path/to/file")
---- vim.ui.open("$VIMRUNTIME")
+--- -- Synchronous (wait until the process exits).
+--- local cmd, err = vim.ui.open("$VIMRUNTIME")
+--- if cmd then
+---   cmd:wait()
+--- end
```
Comment (justinmk) [inline runtime/lua/vim/ui.lua:124]: Maybe we can do better than this pattern. Need to think carefully about https://github.com/neovim/neovim/issues/19624

File: runtime/lua/vim/_system.lua (hunk 2 above)
Comment (justinmk) [reply runtime/lua/vim/_system.lua:327]: Can revert this if needed. LMK

Comment (lewis6991) [reply runtime/lua/vim/_system.lua]: > I also wonder if vim.SystemObj and vim.SystemCompleted should be one interface.

I don't think so personally. Each object is mutually exclusive to the other. Merging them together just creates more entropy since each field would become optional, and I generally prefer return types to be as predictable as possible (i.e. avoid returning possible nils).

Comment (lewis6991) [reply runtime/lua/vim/_system.lua]: > Expose cmd on SystemObj, because it's a basic info that may be needed by consumers (which didn't necessarily originate the system() invocation). @lewis6991

As long as there's a concrete use case, then it makes sense. What's the use case here?

Comment (justinmk) [reply runtime/lua/vim/_system.lua]: Use-case is that vim.ui.open returns a SystemObj and the caller (`gx` mapping) wants to print info about the command that was run.

File: runtime/lua/vim/_defaults.lua (hunk 1 above)
Comment (lewis6991) [reply runtime/lua/vim/_defaults.lua:105]: Is it even sound since the signal could have originated from somewhere else? We could add it as a field to `SystemCompleted`?

Comment (justinmk) [reply runtime/lua/vim/_defaults.lua:105]: Hence "hacky" :) Just noticed that code=124 on timeout? https://github.com/neovim/neovim/blob/1d73ecda7f9be51371096989e5f1b351caf55d83/runtime/lua/vim/_system.lua#L283

Any reason not to set it to -1 ?
