### PR TITLE
fix(tui)!: remove `ESC NUL` forced escape

### LINKED ISSUE #14836: Ctrl-Alt-Space isn't recognized, even though terminal sends ^[^@ (works in vim)
- `nvim --version`: `v0.4.3`
- Operating system/version: (Arch)Linux, up to date
- Terminal name/version: Wezterm 20210502-154244-3f7122cb
- `$TERM`: `xterm-256color`

[YES] `vim -u DEFAULTS` (version: `8.2.2891`) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC (or vim -u DEFAULTS)
Then type `:` (to open the cmdline)
Then do Ctrl-v
Then do Ctrl-Alt-Space
Watch what is printed to the cmdline
```

### Actual behaviour

In vim: `^[^@`
In neovim: `^[`

### Expected behaviour

Get `^[^@` in both, or even have `<M-C-Space>` in neovim

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #14836

This make Nvim recognize `ESC NUL` as `<M-C-Space>` (unless terminfo declares it to be something else), as many terminal emulators (including libvterm) send `<M-C-Space>` as `ESC NUL`.

Nvim already supports another unambiguous way to encode a `ESC` key through libtermkey: `ESC [ 2 7 u`, which is an "extended keys" (a.k.a. "modifyOtherKeys" or `CSI u`) sequence.

For example, if one previously used `tmux send-keys 'Escape' 'C-@' 'C-W' j` (<https://github.com/neovim/neovim/pull/1820#issuecomment-74496769>) to leave Insert mode and go to the window below, that will no longer work, but they can still use `tmux send-keys 'Escape' [ 2 7 u 'C-W' j` to achieve that. I don't think many people use `ESC NUL` forced escape nowadays, as Nvim now reinterprets unmapped ALT- chords.

If one still wants to use `ESC NUL` as `ESC`, they can just map `<M-C-Space>` to `<Esc>`.

### CODE REVIEW

**Comment by justinmk** [comment]
> I don't think many people use `ESC NUL` forced escape nowadays, as Nvim now reinterprets unmapped ALT- chords.

Exactly. The "forced escape" thing was added literally in the first few months of Neovim's existence, isn't even _documented_, and was before ALT support. 

This is a nice observation and fix, thank you!

File: test/functional/terminal/tui_spec.lua [hunk 1]
```diff
@@ -229,6 +229,38 @@ describe('TUI', function()
     ]])
   end)
 
+  it('interprets <Esc>[27u as <Esc>', function()
```
Comment (justinmk) [inline test/functional/terminal/tui_spec.lua:232]:
```suggestion
  it('interprets <Esc>[27u as <Esc> #17198', function()
```

**Comment by justinmk** [comment]
> `ESC [ 2 7 u`, which is a `CSI u`

Should mention this in docs, e.g. for `nvim_input()` at least. Also worth having an explicit test for `nvim_input()`.

File: test/functional/terminal/tui_spec.lua (hunk 1 above)
Comment (zeertzjq) [reply test/functional/terminal/tui_spec.lua:232]: This behavior is not introduced in this PR. It is just the behavior of libtermkey.

**Comment by zeertzjq** [comment]
> > `ESC [ 2 7 u`, which is a `CSI u`
> 
> Should mention this in docs, e.g. for `nvim_input()` at least. Also worth having an explicit test for `nvim_input()`.

This is a behavior of libtermkey and doesn't work with `nvim_input()`.

**Comment by zeertzjq** [comment]
I guess this one is fine to merge before v0.7 release?

**Comment by justinmk** [comment]
Definitely. I do think it's worth mentioning in `:help tui` somewhere. Also just mentioning something about CSI codes being supported.

**Comment by zeertzjq** [comment]
I'll update docs in another PR #18072, as docs-only PR do not trigger CI.

**Comment by justinmk** [comment]
Does this also fix #2379 ?

**Comment by zeertzjq** [comment]
I think this is unrelated to #2379, and it is not clear if #2379 is a terminal configuration issue or a Nvim issue.
