### PR TITLE
fix(pack): use `uv.available_parallelism()` to compute number of threads

### LINKED ISSUE #38644: `vim.uv.cpu_info()` is slow if `/proc/cpuinfo` is large
## Problem

This may be setup or machine specific, but the startup is almost 4 seconds due to neovim spending 3.86 seconds on `require('vim.pack')`. Here is the startuptime file [startuptime.txt](https://github.com/user-attachments/files/26383526/startuptime.txt), and here is an excerpt with the points of interest, starting at line 63 (`:63`):

```
003.972  001.127  001.123: require('vim.diagnostic')
004.698  000.052  000.052: require('vim._async')
004.888  000.189  000.189: require('vim.version')
3864.424  3860.419  3860.179: require('vim.pack')
3864.472  000.034  000.034: require('vim.fs')
3865.047  000.311  000.311: require('catppuccin')
``` 

Upon commenting out all vim.plug instances in my `init.lua`, it startsup instantly. But the addition of a single package (catppuccin) results in the full ~3.85 second additional cost to startup-times. I could not find any other issue discussing this, and it was also encountered in both versions 0.12 and 0.13. 

## Steps to reproduce

Not sure why this is happening here.

## Expected behavior

Sub-second startup times.

## System info

- Nvim version (nvim -v): `v0.13.0-dev-29 g1bcf2d7f90` neovim/neovim@1bcf2d7f90
- Vim (not Nvim) behaves the same?: Not-Applicable
- Operating system/version: Linux 5.15.0-173-generic
- Terminal name/version: ghostty 1.3.1-arch1
- $TERM environment variable: `xterm-ghostty`
- Installation: Manual build (also seen via unstable PPA and tarball pre-built binaries)

## Additional Comments

Happy to run any diagnostics that could help y'all. Not sure if this is a `vim.pack` issue or a slow filesystem issue (this shouldn't be the case as it is a pretty powerful server machine).

### PR DESCRIPTION
**Pull request by echasnovski**
**Problem**: Computing number of threads for parallel asynchronous computation using `uv.cpu_info()` can be slow. This is especially noticeable since it is pre-computed on every `require('vim.pack')` and not only when parallelism is needed.

**Solution**: Use `uv.available_parallelism()` to compute number of threads in a helper function.

---

Fix #38644.

### CODE REVIEW

File: runtime/lua/vim/pack.lua [hunk 1]
```diff
@@ -499,9 +499,17 @@ local function new_progress_report(action)
   end)
 end
 
-local n_threads = 2 * #(uv.cpu_info() or { {} })
 local copcall = package.loaded.jit and pcall or require('coxpcall').pcall
 
+local function async_join_run_wait(funs)
+  local n_threads = 2 * (uv.available_parallelism() or 1)
```
Comment (justinmk) [inline runtime/lua/vim/pack.lua:505]: Should vim.async provide a default based on this? Perhaps with a "factor" parameter.

Comment (lewis6991) [reply runtime/lua/vim/pack.lua:505]: No. This number is quite arbitrary. The amount of git clones we can make could be much larger than this and depends on factors other than the amount of physical threads on a CPU. For network heavy jobs, I'm fairly confident 1 CPU can manage lots since it'll be sleeping most of the time anyway waiting for data packets. It'll be things like network bandwidth, IO bandwidth/latency that'll determine the real bottleneck.
