### PR TITLE
fix(terminal): reset `w_leftcol` after resizing terminal

### LINKED ISSUE #35331: Terminal window horizontal offset not updated after resize
### Problem

The w_leftcol in a terminal window is not updated after terminal buffer is resized.

Commit where the bug appears: 2784a5d3d28004f95dfd4e31a825722440437fe1

The logic of this bug:
- The window changes its width
- win_set_inner_size() detects that number of columns has changed and tries to recompute w_leftcol. At this moment, we still have old terminal dimensions and cursor position, so it sets new value to w_leftcol, which is correct at this moment
- An event is sent to update terminal size
- When terminal updates its width, the cursor column can change position, so w_leftcol should be recomputed, which is not happening

Was able to fix it by updating w_leftcol after terminal resize, but i think that this solution is a bit hacky, and i'm not familiar enough with neovim codebase to come up with something better.
```patch
diff --git a/src/nvim/terminal.c b/src/nvim/terminal.c
index b6af223ea6..18b789f12d 100644
--- a/src/nvim/terminal.c
+++ b/src/nvim/terminal.c
@@ -2109,6 +2109,19 @@ static void refresh_size(Terminal *term, buf_T *buf)
   term->invalid_start = 0;
   term->invalid_end = height;
   term->opts.resize_cb((uint16_t)width, (uint16_t)height, term->opts.data);
+
+  FOR_ALL_TAB_WINDOWS(tp, wp) {
+    if (wp->w_buffer == buf) {
+      // For some reason curs_columns just alone, doesn't work well with
+      // floating windows
+      if (wp->w_leftcol != 0) {
+        wp->w_leftcol = 0;
+        redraw_later(wp, UPD_NOT_VALID);
+      }
+
+      curs_columns(wp, true);
+    }
+  }
 }
 
 void on_scrollback_option_changed(Terminal *term)
```

### Steps to reproduce

```bash
nvim --clean
:term
btop # Open any tui app that take control over cursor and set it to the mid/end column (e.g. btop, yazi or lazygit)
# Resize neovim at large amount of width in single tick
```

Image

### Expected behavior

Terminal window should reset w_leftcol after resize

### Nvim version (nvim -v)

v0.11.3 and v0.12.0-dev-1011+g38986188ba-dirty

### Vim (not Nvim) behaves the same?

Can't reproduce it in latest stable vim

### Operating system/version

Linux archlinux 6.15.9-zen1-1-zen

### Terminal name/version

alacritty 0.15.1 (0c405d53)

### $TERM environment variable

screen-256color

### Installation

pacman -S neovim or built from the repo

### PR DESCRIPTION
**Pull request by def3r**
Problem: windows may scroll horizontally upon resize using the old terminal
size, which may be unnecessary and cause the content to be partially out-of-view.

Solution: reset the horizontal scroll after resizing.

Closes #35331

### CODE REVIEW

**Review by seandewar — COMMENTED** [review]
Doing this prevents horizontal scrolling from working even in Normal mode, and can cause the cursor to draw outside the viewport of the window it's in.

```vim
set splitright splitbelow
call chansend(nvim_open_term(0, #{}), "a"->repeat(99999))
normal! G
split
vnew
vsplit
wincmd 2W
" Keep moving the cursor to the right until it leaves the bottom-left window's viewport
call timer_start(20, {->execute('normal! l')}, #{repeat: -1})
```

**Comment by def3r** [comment]
I came up with this solution for now. We take a flag `may_resize` and set it in `terminal_check_size`. This flag is supposed to tell whether the proc running inside the terminal has responded to the resize. We set w_leftcol to 0 if may_resize is set. 

This seems to work but probably isn't the right idea. I feel terminal_recieve should have a better way to indicate that resize has happened.

**Comment by seandewar** [comment]
Tbh I think that's mostly fine, though it might be better if `refresh_size` returns whether it changed the size and have `refresh_terminal` reset `w_leftcol` and call `curs_columns` for its windows if so after `refresh_screen`?

**Comment by def3r** [comment]
I was avoiding iterating over all windows, because i thought that might be slow. But ig I ended up implementing something complex that can be done easily :)

This works fine, so ig we go with this version instead
```diff
-  refresh_size(term, buf);
+  bool size_refreshed = refresh_size(term, buf);
   refresh_scrollback(term, buf);
   refresh_screen(term, buf);
+  if (size_refreshed) {
+    FOR_ALL_TAB_WINDOWS(tp, wp) {
+      if (wp->w_buffer == buf && wp->w_leftcol) {
+        wp->w_leftcol = 0;
+        curs_columns(wp, true);
+      }
+    }
+  }
```

**Comment by seandewar** [comment]
Yeah I think that's better. It's simple and resizing shouldn't occur often enough for performance to be a concern. (plus `curs_columns` isn't always called for non-current windows, so a loop may have been needed anyway; `adjust_topline_cursor` is doing a lot of looping anyways)

Be sure to add some tests, and maybe a comment above the loop like:
```c
// Resized window may have scrolled horizontally to keep its cursor in-view using the terminal's old
// size. Reset the scroll, and let curs_columns correct it if that sends the cursor out-of-view.
```

File: src/nvim/terminal.c [hunk 1]
```diff
@@ -549,36 +498,18 @@ Terminal *terminal_alloc(buf_T *buf, TerminalOptions opts)
   term->invalid_start = 0;
   term->invalid_end = opts.height;
 
+  term->may_resize = 0;
```
Comment (justinmk) [inline src/nvim/terminal.c]:
```suggestion
  term->may_resize = false;
```

File: src/nvim/move.c [hunk 2]
```diff
@@ -878,43 +874,54 @@ void curs_columns(win_T *wp, int may_scroll)
     }
   } else if (may_scroll
              && !wp->w_cline_folded) {
```
Comment (justinmk) [inline src/nvim/move.c:880]: could avoid the extra nesting, and diff churn, with something like:

```c
} else if (!bt_terminal(wp->w_buffer) && may_scroll && !wp->w_cline_folded) {
  // ...
} else if (bt_terminal(wp->w_buffer) && may_scroll && !wp->w_cline_folded) {
  // ...
```

Comment (seandewar) [reply src/nvim/move.c:880]: This PR's planning on using a different approach ([contained within `refresh_terminal`](https://github.com/neovim/neovim/pull/37159#issuecomment-3847511696)), which should end up being neater. :+1:

File: test/functional/terminal/window_spec.lua [hunk 3]
```diff
@@ -33,6 +34,48 @@ describe(':terminal window', function()
...
+      {120:<ild/bin/shell-test [-]  }{2:[No Name]                }|
+                                                        |
+    ]])
+
+    -- Explicitly check for resize
+    feed('zlzlzlzl')
+    command('vertical resize 15')
+    command('redraw!')
+    screen:expect([[
+      nteract $ AAAA^ │                                  |
```
Comment (seandewar) [inline test/functional/terminal/window_spec.lua]: This isn't right. I think I know what's wrong.

File: test/functional/terminal/window_spec.lua [hunk 4]
```diff
@@ -33,6 +34,48 @@ describe(':terminal window', function()
...
+      ract $ AAAAAAAAA^A                                 |
+                                                        |*6
+    ]])
+    command('set splitright')
+    command('vnew') -- this resizes the window
+    command('wincmd 1w')
+    screen:expect([[
+      interact $ AAAAAAAAA^A   │                         |
+                              │{100:~                        }|*4
+      {120:<ild/bin/shell-test [-]  }{2:[No Name]                }|
```
Comment (seandewar) [inline test/functional/terminal/window_spec.lua]: Statusline is failing the CI on Windows.

**Review by seandewar — COMMENTED** [review]
I'll try some fixups in a bit.

**Comment by def3r** [comment]
should we add a `screen:expect` after we set up screen? Ig that would fix macos test thats failing

**Comment by seandewar** [comment]
Ah, I didn't realize I removed that `expect`. I was super confused for a while!

**Review by seandewar — APPROVED** [review]
Thanks, your comment saved me a bunch of time! 😅

I think this is fine now. Might exist other cases where a scroll reset could be useful; may look into that at some point.
