### PR TITLE
fix(pum): hide info floating window when insufficient space

### LINKED ISSUE #37098: Signed overflow during completion with small `columns`, `completeopt+=popup` and `showbreak` set
### Problem

UBSAN reports signed integer overflow in `charsize_regular` (via `plines_m_win` and friends) when displaying a completion info popup with `&showbreak` set and with a small number of `&columns`.

~~Though my repro relies on completion, the call to `plines_m_win` in `pum_adjust_info_position` looks pretty innocent to me... I suspect the issue is specifically with the plines stuff?~~
Nvm, as zeer points out it looks like `pum_adjust_info_position` is setting `w_view_width` to -1.

(I also did manage to hit a `glyph_cache` assert while trying to find a repro for this, but couldn't reproduce that one...)

```
neovim/src/nvim/plines.c:267:36: runtime error: signed integer overflow: 2147483647 + 1 cannot be represented in type 'int'
    #0 0x0000014321ed in charsize_regular neovim/src/nvim/plines.c:267:36
    #1 0x00000142dda2 in linesize_regular neovim/src/nvim/plines.c:447:13
    #2 0x00000143a3b4 in plines_win_nofold neovim/src/nvim/plines.c:798:11
    #3 0x000001439e21 in plines_win_nofill neovim/src/nvim/plines.c:776:21
    #4 0x00000143cd45 in plines_win_full neovim/src/nvim/plines.c:906:24
    #5 0x00000143cf7d in plines_m_win neovim/src/nvim/plines.c:925:14
    #6 0x00000145310d in pum_adjust_info_position neovim/src/nvim/popupmenu.c:986:25
    #7 0x000001447709 in pum_set_selected neovim/src/nvim/popupmenu.c:1197:13
    #8 0x000001442049 in pum_display neovim/src/nvim/popupmenu.c:428:12
    #9 0x000000eec65b in ins_compl_show_pum neovim/src/nvim/insexpand.c:1718:3
    #10 0x000000f06832 in show_pum neovim/src/nvim/insexpand.c:6286:3
    #11 0x000000efa53f in set_completion neovim/src/nvim/insexpand.c:3424:5
    #12 0x000000ef995b in f_complete neovim/src/nvim/insexpand.c:3450:7
    #13 0x000000a809d5 in call_internal_func neovim/src/nvim/eval/funcs.c:281:3
    #14 0x000000b592c0 in call_func neovim/src/nvim/eval/userfunc.c:1785:15
    #15 0x000000b56311 in get_func_tv neovim/src/nvim/eval/userfunc.c:580:11
    #16 0x000000b88a34 in ex_call_inner neovim/src/nvim/eval/userfunc.c:3352:9
    #17 0x000000b86fd7 in ex_call neovim/src/nvim/eval/userfunc.c:3594:14
    #18 0x000000c712a6 in execute_cmd0 neovim/src/nvim/ex_docmd.c:1759:7
    #19 0x000000c52e56 in do_one_cmd neovim/src/nvim/ex_docmd.c:2389:7
    #20 0x000000c47b77 in do_cmdline neovim/src/nvim/ex_docmd.c:679:20
    #21 0x000000701677 in apply_autocmds_group neovim/src/nvim/autocmd.c:1940:5
    #22 0x00000070ada1 in apply_autocmds neovim/src/nvim/autocmd.c:1573:10
    #23 0x0000017e79ac in may_trigger_modechanged neovim/src/nvim/state.c:276:3
    #24 0x000000958743 in insert_enter neovim/src/nvim/edit.c:263:3
    #25 0x00000094f91f in edit neovim/src/nvim/edit.c:1374:3
    #26 0x0000012f9720 in normal_finish_command neovim/src/nvim/normal.c:1065:7
    #27 0x000001296b6d in normal_execute neovim/src/nvim/normal.c:1257:3
    #28 0x0000017e42fc in state_enter neovim/src/nvim/state.c:100:26
    #29 0x000001278565 in normal_enter neovim/src/nvim/normal.c:523:3
    #30 0x000000fe0181 in main neovim/src/nvim/main.c:660:3
    #31 0x7f67f918c5b4 in __libc_start_call_main (/lib64/libc.so.6+0x35b4) (BuildId: f410d74336e800b1795d2fd97ddfd36c16ad6546)
    #32 0x7f67f918c667 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x3667) (BuildId: f410d74336e800b1795d2fd97ddfd36c16ad6546)
    #33 0x0000004017f4 in _start (neovim/build/bin/nvim+0x4017f4) (BuildId: 2f1ca933ccc1846e6509344f1d0836c943eb8d86)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior neovim/src/nvim/plines.c:267:36
```

### Steps to reproduce

```vim
set columns=12 showbreak=e completeopt+=popup
startinsert
autocmd ModeChanged *:i ++once call complete(col('.'),
      \ [#{word: 'foo', info: 'a'->repeat(99)},
      \  #{word: 'bar', info: 'a'->repeat(99)}])
```

### Expected behavior

No signed overflow.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-1898+g5a1a92cc7a

### Vim (not Nvim) behaves the same?

no, VIM 9.1.2017

### Operating system/version

Fedora 43 Workstation

### Terminal name/version

ghostty 1.2.3, tmux 3.5a

### $TERM environment variable

tmux-256color

### Installation

Source

### PR DESCRIPTION
**Pull request by glepnir**
Problem:
1.Info window was displayed even with insufficient space.
2.Tab characters counted as single cells.

Solution:
1. Hide window when space < 10 columns. Will be configurable
   via completepopup width option in the future.
2. Use win_linetabsize replace mb_string2cells.

### CODE REVIEW

File: src/nvim/popupmenu.c [hunk 1]
```diff
@@ -1191,7 +1202,9 @@ static bool pum_set_selected(int n, int repeat)
 
           if (use_float) {
             // adjust floating window by actually height and max info text width
-            pum_adjust_info_position(curwin, max_info_width);
+            if (!pum_adjust_info_position(curwin, max_info_width)) {
+              curwin = curwin_save;
```
Comment (seandewar) [inline src/nvim/popupmenu.c]: Setting `curwin` directly seems dubious. `curwin` after `win_close` in `pum_adjust_info_position` _should_ be `curwin_save` anyhow (makes this a no-op), but if that's somehow false then this is bugprone. (`curbuf` and other globals may remain out-of-sync)

Maybe use `win_enter`? (I'll assume `win_valid` isn't needed here as autocmds are blocked for popups... 😇)

```suggestion
              win_enter(curwin_save, false);
```

**Comment by seandewar** [comment]
Does this also fix #37098? (Assuming it can't regress later when the min size is made configurable via `&completepopup`?)

**Comment by glepnir** [comment]
Yes. When completepopup is present, the logic here will be as follows.

```C
int max_extra = MAX(right_extra, left_extra);
int final_width = max_extra;
bool used_user_width = false;
if (completepopup_width_opt > 0 && max_extra > completepopup_width_opt) {
    final_width = completepopup_width_opt;
    used_user_width = true;
}
if (final_width < 10 && !used_user_width) {
    wp->w_config.hide = true;
    return false;
}

wp->w_config.width = final_width;
```

File: src/nvim/popupmenu.c [hunk 2]
```diff
@@ -931,7 +931,7 @@ static void pum_preview_set_text(buf_T *buf, char *info, linenr_T *lnum, int *ma
       break;
     }
 
-    *max_width = MAX(*max_width, (int)mb_string2cells(curr));
+    *max_width = MAX(*max_width, linetabsize_str(curr));
```
Comment (seandewar) [inline src/nvim/popupmenu.c]: This'll use the tab width from `curwin`, which may be the wrong window.

E.g: the size of the preview window is wrong here: (add a test case for this)
```vim
set completeopt+=popup,menuone nolist
setlocal tabstop=1
startinsert
autocmd ModeChanged *:i ++once call complete(1, [#{word: 'a'}])
      \| call nvim__complete_set(0, #{info: "\tfloob\tfloob"})
```

I'm not an expert with the plines stuff, but maybe this'll work?

```diff
diff --git a/src/nvim/popupmenu.c b/src/nvim/popupmenu.c
index d3dd3e3104..57452196b6 100644
--- a/src/nvim/popupmenu.c
+++ b/src/nvim/popupmenu.c
@@ -910,15 +910,16 @@ void pum_redraw(void)
 /// Set the informational text in the preview buffer when the completion
 /// item does not include a dedicated preview or popup window.
 ///
-/// @param[in]  buf        Buffer where the text will be set.
+/// @param[in]  win        Window containing buffer where the text will be set.
 /// @param[in]  info       Informational text to display in the preview buffer.
 /// @param[in]  lnum       Where to start the text. Incremented for each added line.
 /// @param[out] max_width  Maximum width of the displayed text.
-static void pum_preview_set_text(buf_T *buf, char *info, linenr_T *lnum, int *max_width)
+static void pum_preview_set_text(win_T *win, char *info, linenr_T *lnum, int *max_width)
 {
   Error err = ERROR_INIT;
   Arena arena = ARENA_EMPTY;
   Array replacement = ARRAY_DICT_INIT;
+  buf_T *buf = win->w_buffer;
   buf->b_p_ma = true;
 
   // Iterate through the string line by line by temporarily replacing newlines with NUL
@@ -931,7 +932,7 @@ static void pum_preview_set_text(buf_T *buf, char *info, linenr_T *lnum, int *ma
       break;
     }
 
-    *max_width = MAX(*max_width, linetabsize_str(curr));
+    *max_width = MAX(*max_width, win_linetabsize(win, 0, curr, MAXCOL));
     ADD(replacement, STRING_OBJ(cstr_to_string(curr)));
     (*lnum)++;
 
@@ -941,9 +942,7 @@ static void pum_preview_set_text(buf_T *buf, char *info, linenr_T *lnum, int *ma
   }
 
   int original_textlock = textlock;
-  if (textlock > 0) {
-    textlock = 0;
-  }
+  textlock = 0;
   nvim_buf_set_lines(0, buf->handle, 0, -1, false, replacement, &arena, &err);
   textlock = original_textlock;
   if (ERROR_SET(&err)) {
@@ -1019,7 +1018,7 @@ win_T *pum_set_info(int selected, char *info)
   }
   linenr_T lnum = 0;
   int max_info_width = 0;
-  pum_preview_set_text(wp->w_buffer, info, &lnum, &max_info_width);
+  pum_preview_set_text(wp, info, &lnum, &max_info_width);
   no_u_sync--;
   RedrawingDisabled--;
   redraw_later(wp, UPD_NOT_VALID);
@@ -1178,7 +1177,7 @@ static bool pum_set_selected(int n, int repeat)
         if (res == OK) {
           linenr_T lnum = 0;
           int max_info_width = 0;
-          pum_preview_set_text(curbuf, pum_array[pum_selected].pum_info, &lnum, &max_info_width);
+          pum_preview_set_text(curwin, pum_array[pum_selected].pum_info, &lnum, &max_info_width);
           // Increase the height of the preview window to show the
           // text, but no more than 'previewheight' lines.
           if (repeat == 0 && !use_float) {
```

Comment (glepnir) [reply src/nvim/popupmenu.c]: oh right it use curwin..

Comment (glepnir) [reply src/nvim/popupmenu.c]:
```
set completeopt+=popup,menuone nolist
setlocal tabstop=1
startinsert
```
I assume this tabstop is you want set in preview buffer not main buffer tight ?

Edit: I know what is missing .😮‍💨

File: src/nvim/popupmenu.c [hunk 3]
```diff
@@ -1007,15 +1015,18 @@ win_T *pum_set_info(int selected, char *info)
     }
     wp->w_topline = 1;
     wp->w_p_wfb = true;
+    wp->w_buffer->b_p_ts = curbuf->b_p_ts;
```
Comment (seandewar) [inline src/nvim/popupmenu.c]:
```suggestion
```

I don't think it's worth only copying `&ts`; tab padding may also be affected by `&vts` (plus `&list` and `&lcs`).  
Also this code is only used by `nvim__complete_set`, so this change won't affect the info popup in the usual case. (`pum_set_selected`)

I think it's OK to not copy anything and just leave the buffer to use the global values from when it's created.

File: test/functional/ui/popupmenu_spec.lua [hunk 4]
```diff
@@ -2238,6 +2238,33 @@ describe('builtin popupmenu', function()
...
+        eq(30, api.nvim_win_get_width(info.preview_winid))
+        feed('<ESC>')
+        exec([[
+          setlocal tabstop=1
+          autocmd ModeChanged *:i ++once call complete(1, [#{word: 'a'}])
+                \| call nvim__complete_set(0, #{info: "\tfloob\tfloob"})
+        ]])
+        feed('i')
+        info = fn.complete_info()
+        eq(12, api.nvim_win_get_width(info.preview_winid))
```
Comment (seandewar) [inline test/functional/ui/popupmenu_spec.lua]:
```suggestion
        eq(21, api.nvim_win_get_width(info.preview_winid))
```

After making the other change, this should be 21. (default of `&ts=8` aligns the end of the 2nd tab to column 16)

(Note that expecting 12 here would've also passed with the prior buggy behaviour of `linetabsize_str` in https://github.com/neovim/neovim/commit/3ce9f63c498f4d5d11f3d67baa237fab46c52f5c, so maybe also add a screen test here to ensure the text isn't wrapped?)

Comment (glepnir) [reply test/functional/ui/popupmenu_spec.lua]: updated

File: src/nvim/popupmenu.c (hunk 3 above)
Comment (glepnir) [reply src/nvim/popupmenu.c]: okay removed

**Review by seandewar — APPROVED** [review]
