### PR TITLE
[RDY] vim-patch:8.0.{828,1254,1470,1517},8.1.{78,90,97,99}

### LINKED ISSUE #2251: signed integer overflow in nfa_regatom()
Triggered in `67435d9`, compiled with clang 6.0.0-trunk and `-fsanitize=address,undefined`.

./vim -u NONE -X -Z -e -s -S test022 ':qa!'

```
regexp_nfa.c:1610:14: runtime error: signed integer overflow: 700000000 * 10 cannot be represented in type 'int'
    #0 0xe464b0 in nfa_regatom /root/vim/src/./regexp_nfa.c:1610:14
    #1 0xe3b5b5 in nfa_regpiece /root/vim/src/./regexp_nfa.c:2055:11
    #2 0xe3b5b5 in nfa_regconcat /root/vim/src/./regexp_nfa.c:2296
    #3 0xe3ac67 in nfa_regbranch /root/vim/src/./regexp_nfa.c:2330:9
    #4 0xe3a114 in nfa_reg /root/vim/src/./regexp_nfa.c:2390:9
    #5 0xe2ff45 in re2post /root/vim/src/./regexp_nfa.c:2805:9
    #6 0xe2ff45 in nfa_regcomp /root/vim/src/./regexp_nfa.c:7257
    #7 0xdcc271 in vim_regcomp /root/vim/src/regexp.c:8153:16
    #8 0xf66486 in search_regcomp /root/vim/src/search.c:223:25
    #9 0x754919 in ex_global /root/vim/src/ex_cmds.c:6000:9
    #10 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
    #11 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
    #12 0x7ae076 in do_source /root/vim/src/ex_cmds2.c:4355:5
    #13 0x7ab31c in cmd_source /root/vim/src/ex_cmds2.c:3968:14
    #14 0x7ab31c in ex_source /root/vim/src/ex_cmds2.c:3943
    #15 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
    #16 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
    #17 0x13f138f in exe_commands /root/vim/src/main.c:2954:2
    #18 0x13f138f in vim_main2 /root/vim/src/main.c:799
    #19 0x13e5d3d in main /root/vim/src/main.c:415:12
    #20 0x7f67ec2ef3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #21 0x41bba9 in _start (/root/vim/src/vim+0x41bba9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior regexp_nfa.c:1610:14
```
[test022.gz](https://github.com/vim/vim/files/1418759/test022.gz)

### LINKED ISSUE #2255: undefined left shift in gethexchrs()
Triggered in `67435d9`, compiled with clang 6.0.0-trunk and `-fsanitize=address,undefined`.

./vim -u NONE -X -Z -e -s -c 'call search(getline("."))' -c ':qa!' test022

```regexp.c:3289:5: runtime error: left shift of 201326592 by 4 places cannot be represented in type 'int'
    #0 0xde43dd in gethexchrs /root/vim/src/regexp.c:3289:5
    #1 0xe4513b in nfa_regatom /root/vim/src/./regexp_nfa.c
    #2 0xe3b5b5 in nfa_regpiece /root/vim/src/./regexp_nfa.c:2055:11
    #3 0xe3b5b5 in nfa_regconcat /root/vim/src/./regexp_nfa.c:2296
    #4 0xe3ac67 in nfa_regbranch /root/vim/src/./regexp_nfa.c:2330:9
    #5 0xe3a114 in nfa_reg /root/vim/src/./regexp_nfa.c:2390:9
    #6 0xe2ff45 in re2post /root/vim/src/./regexp_nfa.c:2805:9
    #7 0xe2ff45 in nfa_regcomp /root/vim/src/./regexp_nfa.c:7257
    #8 0xdcc271 in vim_regcomp /root/vim/src/regexp.c:8153:16
    #9 0xf66486 in search_regcomp /root/vim/src/search.c:223:25
    #10 0xf69de2 in searchit /root/vim/src/search.c:621:9
    #11 0x70aec6 in search_cmn /root/vim/src/evalfunc.c:9363:17
    #12 0x6d83e1 in f_search /root/vim/src/evalfunc.c:9500:28
    #13 0x68b15b in call_internal_func /root/vim/src/evalfunc.c:1012:5
    #14 0x12341e6 in call_func /root/vim/src/userfunc.c:1446:14
    #15 0x1232b95 in get_func_tv /root/vim/src/userfunc.c:455:8
    #16 0x12575b6 in ex_call /root/vim/src/userfunc.c:3082:6
    #17 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
    #18 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
    #19 0x13f138f in exe_commands /root/vim/src/main.c:2954:2
    #20 0x13f138f in vim_main2 /root/vim/src/main.c:799
    #21 0x13e5d3d in main /root/vim/src/main.c:415:12
    #22 0x7fa33af993f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #23 0x41bba9 in _start (/root/vim/src/vim+0x41bba9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior regexp.c:3289:5
```
[test022.gz](https://github.com/vim/vim/files/1418822/test022.gz)

### PR DESCRIPTION
**Pull request by janlazo**
**vim-patch:8.0.0828: Coverity: may dereference NULL pointer**

Problem:    Coverity: may dereference NULL pointer.
Solution:   Bail out if calloc_state() returns NULL.
vim/vim@983b3a5

**vim-patch:8.0.1254: undefined left shift in gethexchrs()**

Problem:    Undefined left shift in gethexchrs(). (geeknik)
Solution:   Use unsigned long. (idea by Christian Brabandt, closes vim/vim#2255)
vim/vim@4c22a91

**vim-patch:8.0.1470: integer overflow when using regexp pattern**

Problem:    Integer overflow when using regexp pattern. (geeknik)
Solution:   Use a long instead of int. (Christian Brabandt, closes vim/vim#2251)
vim/vim@2c7b906

**vim-patch:8.0.1517: invalid memory acces with pattern using look-behind match**

Problem:    Invalid memory acces with pattern using look-behind match.
            (Dominique Pelle)
Solution:   Get a pointer to the right line.
vim/vim@bc19719

**vim-patch:8.1.0078: "..." used inconsistently in messages**

Problem:    "..." used inconsistently in messages.
Solution:   Drop the space before " ...".
vim/vim@c166927

**vim-patch:8.1.0090: "..." used inconsistently in a message**

Problem:    "..." used inconsistently in a message.
Solution:   Define the message with " ..." once. (hint by Ken Takata)
vim/vim@9b0c5c2

**vim-patch:8.1.0097: superfluous space before exclamation mark**

Problem:    Superfluous space before exclamation mark.
Solution:   Remove the space.  Don't translate debug message.
vim/vim@5efa010

**vim-patch:8.1.0099: exclamation mark in error message not needed**

Problem:    Exclamation mark in error message not needed.
Solution:   Remove the exclamation mark.
vim/vim@3c867da

Breaking up https://github.com/neovim/neovim/pull/8662 into smaller PRs so it's easier to debug 8.0.0286.

### CODE REVIEW

File: src/nvim/regexp.c [hunk 1]
```diff
@@ -3000,9 +2999,9 @@ static int gethexchrs(int maxinputlen)
  * Get and return the value of the decimal string immediately after the
  * current position. Return -1 for invalid.  Consumes all digits.
  */
-static int getdecchrs(void)
+static int64_t getdecchrs(void)
 {
-  int nr = 0;
+  int64_t nr = 0;
```
Comment (janlazo) [inline src/nvim/regexp.c]: Vim used `long_u` here to cast it to `long` on return. I used `int64_t` to remove the need to cast. Alternative is `int32_t` and `uint32_t` to maintain the cast but that requires style changes to pass the lint build.

**Comment by janlazo** [comment]
This error again on ASAN.

```
[----------] Running tests from /home/travis/build/neovim/neovim/test/functional/plugin/man_spec.lua
[ RUN      ] :Man man.lua: highlight_line() clears backspaces from text and adds highlights: 9.48 ms OK
==================== File /home/travis/build/neovim/neovim/build/log/ubsan.16920 ====================
= =================================================================
= ==16920==ERROR: AddressSanitizer: SEGV on unknown address 0x000001bb0d50 (pc 0x00000044f3d1 bp 0x000000000001 sp 0x7ffca7dfb2e0 T0)
= ==16920==The signal is caused by a WRITE memory access.
=     #0 0x44f3d0 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t> /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:90:10
=     #1 0x44f3d0 in AtomicallySetQuarantineFlagIfAllocated /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_allocator.cc:520
=     #2 0x44f3d0 in __asan::Allocator::Deallocate(void*, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_allocator.cc:597
=     #3 0x4ef346 in __interceptor_free /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:50:3
=     #4 0xfc2524 in xfree /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:134:3
=     #5 0x1211aa8 in free_string_option /home/travis/build/neovim/neovim/build/../src/nvim/option.c:2207:5
=     #6 0x1210f9d in free_all_options /home/travis/build/neovim/neovim/build/../src/nvim/option.c:923:9
=     #7 0xfc4e81 in free_all_mem /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:622:3
=     #8 0x12beffc in mch_exit /home/travis/build/neovim/neovim/build/../src/nvim/os_unix.c:153:3
=     #9 0x1095b73 in exit_event /home/travis/build/neovim/neovim/build/../src/nvim/msgpack_rpc/channel.c:542:5
=     #10 0xa6d583 in multiqueue_process_events /home/travis/build/neovim/neovim/build/../src/nvim/event/multiqueue.c:150:7
=     #11 0xa670df in loop_poll_events /home/travis/build/neovim/neovim/build/../src/nvim/event/loop.c:65:3
=     #12 0x12a8020 in os_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/os/input.c:162:5
=     #13 0x1038a77 in line_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/misc1.c:2691:5
=     #14 0x143e970 in nfa_regmatch /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6211:5
=     #15 0x141f1f9 in nfa_regtry /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6281:16
=     #16 0x141cf23 in nfa_regexec_both /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6449:12
=     #17 0x13cafbd in nfa_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6602:10
=     #18 0x137da90 in vim_regexec_both /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7215:16
=     #19 0x137e777 in vim_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7267:10
=     #20 0x971358 in find_some_match /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:12339:15
=     #21 0x8ef6d7 in f_matchstr /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:12606:3
=     #22 0x82b294 in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6368:11
=     #23 0x83f218 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6114:11
=     #24 0x8c79a1 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4218:15
=     #25 0x8c3f6b in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3915:7
=     #26 0x8c1c7f in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3766:7
=     #27 0x8bd49f in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3503:7
=     #28 0x8bc93c in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3421:7
=     #29 0x8bbddc in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3352:7
=     #30 0x8233e1 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3279:7
=     #31 0x823ba0 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3318:9
=     #32 0x82280b in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3239:9
=     #33 0x82f288 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1485:9
=     #34 0xb6c173 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2228:5
=     #35 0xb4e719 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:592:20
=     #36 0x85edc5 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:21447:3
=     #37 0x82abbb in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6353:11
=     #38 0x83f218 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6114:11
=     #39 0x8c79a1 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4218:15
=     #40 0x8c3f6b in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3915:7
=     #41 0x8c1c7f in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3766:7
=     #42 0x8bd49f in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3503:7
=     #43 0x8bc93c in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3421:7
=     #44 0x8bbddc in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3352:7
=     #45 0x8233e1 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3279:7
=     #46 0x82280b in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3239:9
=     #47 0x82f288 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1485:9
=     #48 0xb6c173 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2228:5
=     #49 0xb4e719 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:592:20
=     #50 0x85edc5 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:21447:3
=     #51 0x82abbb in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6353:11
=     #52 0x83f218 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6114:11
=     #53 0x8c79a1 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4218:15
=     #54 0x8c3f6b in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3915:7
=     #55 0x8c1c7f in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3766:7
=     #56 0x8bd49f in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3503:7
=     #57 0x8bc93c in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3421:7
=     #58 0x8bbddc in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3352:7
=     #59 0x8233e1 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3279:7
=     #60 0x82280b in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3239:9
=     #61 0x82f288 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1485:9
=     #62 0xb6c173 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2228:5
=     #63 0xb4e719 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:592:20
=     #64 0x85edc5 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:21447:3
=     #65 0x82abbb in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6353:11
=     #66 0x83f218 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6114:11
=     #67 0x8381d4 in ex_call /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2727:9
=     #68 0xb6c173 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2228:5
=     #69 0xb4e719 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:592:20
=     #70 0xb3852d in do_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:3002:3
=     #71 0xb31f6e in source_callback /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2345:9
=     #72 0xb3179f in do_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2423:15
=     #73 0xb31c08 in do_in_path_and_pp /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2467:12
=     #74 0xb31f41 in source_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2515:10
=     #75 0xeb923b in load_plugins /home/travis/build/neovim/neovim/build/../src/nvim/main.c:1346:5
=     #76 0xeaac33 in main /home/travis/build/neovim/neovim/build/../src/nvim/main.c:364:3
=     #77 0x7ffa86c5df44 in __libc_start_main /build/eglibc-ripdx6/eglibc-2.19/csu/libc-start.c:287
=     #78 0x44e3cb in _start (/home/travis/build/neovim/neovim/build/bin/nvim+0x44e3cb)
= 
= AddressSanitizer can not provide additional info.
= SUMMARY: AddressSanitizer: SEGV /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:90:10 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>
= ==16920==ABORTING
=====================================================================================================
test/helpers.lua:149: assertion failed!
stack traceback:
	test/helpers.lua:149: in function 'check_logs'
	test/functional/helpers.lua:749: in function <test/functional/helpers.lua:745>
```

**Comment by justinmk** [comment]
> This error again on ASAN. Happened before at #8833 

see https://github.com/neovim/neovim/pull/8833#issuecomment-412337960
