### PR TITLE
fix(exrc): ensure consistent loading sequence for all startup scripts

### LINKED ISSUE #35147: Parent directory exrc (`.nvim.lua`) scripts loaded too late
### Problem

After #33889, `.nvim.lua` startup scripts from parent directories are loaded via a `VimEnter` autocmd after the `FileType` event, unlike script in the current directory which are sourced earlier by `source_startup_scripts` function. This causes project-specific configurations, such as LSP settings, to be applied too late when nvim is started from a subdirectory, resulting in inconsistent behavior.

### Steps to reproduce

To reproduce this issue, modify the `init.lua` file rather than using the '-u' option. nvim [does not load exrc scripts](https://github.com/neovim/neovim/blob/78f4994627b7d9c3b85f30028fe55ff38024a39d/src/nvim/main.c#L2104-L2119) when this option is selected.

init.lua:
```lua
vim.lsp.config('clangd', {cmd={'clangd'},filetypes={'c'}})
vim.lsp.enable('clangd')
vim.opt.exrc = true
```

Create the .nvim.rc file and `:trust`
```lua
vim.lsp.config("clangd", {
  cmd = { "clangd", "--background-index" },
})
```

Run `nvim main.c` to launch neovim, then verify that the LSP configuration changes in `.nvim.lua` have been applied.
```lua
vim.lsp.get_clients({bufnr=0, name="clangd"})[1].config.cmd
-- result: { "clangd", "--background-index" }  
```

Run neovim in a subdirectory.
```sh
mkdir subdir
cd subdir
nvim main.c
```
Although the configuration had been loaded, it had not been applied in time for the server to use it.
```lua
vim.lsp.config.clangd.cmd
-- result: { "clangd", "--background-index" } 
vim.lsp.get_clients({bufnr=0, name="clangd"})[1].config.cmd
-- result: { "clangd" }  
```

### Expected behavior

The .nvim.lua scripts in parent directories are sourced at the same stage as those in the current directory.

### Nvim version (nvim -v)

NVIM v0.12.0-dev-926+g78f4994627

### Vim (not Nvim) behaves the same?

no

### Operating system/version

archlinux

### Terminal name/version

foot

### $TERM environment variable

xterm-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by memchr**
Problem:
The execution of startup scripts in parent directories are too late compared to scripts in current direcctory.

Solution:
Execute all startup scripts with `lua/_core/exrc.lua`.

closes: #35147

### CODE REVIEW

File: src/nvim/main.c [hunk 1]
```diff
@@ -2062,38 +2062,18 @@ static bool do_user_initialization(void)
...
-// Only do this if VIMRC_FILE is not the same as vimrc file sourced in
-// do_user_initialization.
+// current directory and all parent directories.  This is only done if the 'exrc'
+// option is set. Only do this if VIMRC_FILE is not the same as vimrc file
+// sourced in do_user_initialization.
 static void do_exrc_initialization(void)
 {
-  char *str;
-
-  if (os_path_exists(VIMRC_LUA_FILE)) {
```
Comment (justinmk) [inline src/nvim/main.c:2110]: Nice that we can delete all this code 👍

File: runtime/lua/vim/_core/exrc.lua [hunk 2]
```diff
@@ -0,0 +1,23 @@
+if not vim.o.exrc then
+  return
```
Comment (justinmk) [inline runtime/lua/vim/_core/exrc.lua]: can drop this check. this module would only be require()'d if it's needed.

**Comment by justinmk** [comment]
side-note: `_core/*` currently isn't built-in to the `nvim` binary, I'll get around to doing that at some point. Just mentioning this in case some `nvim -u NONE` tests fail because of it.

File: runtime/lua/vim/_core/exrc.lua [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+  if trusted then
+    if vim.endswith(file, '.lua') then
+      assert(loadstring(trusted, '@' .. file))()
+    else
+      vim.api.nvim_exec2(trusted, {})
+    end
+  end
+  -- If the user unset 'exrc' in the current exrc then stop searching
+  if not vim.o.exrc then
+    return
```
Comment (justinmk) [inline runtime/lua/vim/_core/exrc.lua]: just `break`

probably this block should be in a local function

File: runtime/lua/vim/_core/exrc.lua [hunk 4]
```diff
@@ -0,0 +1,20 @@
+local files = vim.fs.find({ '.nvim.lua', '.nvimrc', '.exrc' }, {
+  type = 'file',
+  upward = true,
+  limit = math.huge,
+  path = (vim.uv.cwd()),
```
Comment (yochem) [inline runtime/lua/vim/_core/exrc.lua]: This is the default value so can be left out

Comment (memchr) [reply runtime/lua/vim/_core/exrc.lua]: I don't understand. The `lua.txt` states that the default for `upward` is `false`, and for `limit`, it is `1`.

Comment (yochem) [reply runtime/lua/vim/_core/exrc.lua]: Sorry for being unclear, was solely talking about `path`, not the others.

**Comment by justinmk** [comment]
do you plan to finish this

**Comment by memchr** [comment]
Yes. 
> side-note: core/* is not currently built into the nvim binary.

Will this cause any problems?

**Review by gpanders — APPROVED** [review]

File: src/nvim/main.c [hunk 5]
```diff
@@ -2100,38 +2100,18 @@ static bool do_user_initialization(void)
 }
 
 // Read initialization commands from ".nvim.lua", ".nvimrc", or ".exrc" in
-// current directory.  This is only done if the 'exrc' option is set.
-// Only do this if VIMRC_FILE is not the same as vimrc file sourced in
-// do_user_initialization.
+// current directory and all parent directories.  This is only done if the 'exrc'
+// option is set. Only do this if VIMRC_FILE is not the same as vimrc file
+// sourced in do_user_initialization.
```
Comment (justinmk) [inline src/nvim/main.c:2105]: Is `Only if VIMRC_FILE is not the same as vimrc in do_user_initialization` still true?

Oh, that seems to be up to the caller.

**Review by justinmk — APPROVED** [review]
This is a nice change, thanks. I will followup with some changes in https://github.com/neovim/neovim/pull/35150
