### PR TITLE
env: use libuv v1.12 getenv/setenv API

### LINKED ISSUE #8398: Windows: E739 with multibyte HOMEPATH
- `nvim --version`: v0.2.2
- Vim (version: ) behaves differently? As far as I remember.
- Operating system/version: Windows 10 - 1709
- Terminal name/version: any, actually

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour

C:\Users\følx>nvim -u NORC
Error detected while processing function <SNR>14_LoadRemotePlugins[1]..<SNR>14_GetManifest[1]..<SNR>14_GetManifestPath:
line   16:
E739: Cannot create directory C:\Users\f<f8>lx: operation not permitted
Press ENTER or type command to continue

### Expected behaviour

Pressing ENTER or any other don't actually produce anything.

I guess the ø within the %HOMEPATH% is misinterpreted as <f8> somehow, but don't have any clue on how to avoid that.

### LINKED ISSUE #9267: startup fails if installation folder name includes Chinese chars
NVIM v0.3.2-913-g108566e7b
Build type: RelWithDebInfo
LuaJIT 2.0.5

Win10 home Chinese

I extract nvim to a folder with a Chinese char, so nvim will run failed.

`<d6><d0>` is cp936 code of `中`  

```
@ D:\Neovim中\bin
$ nvim
C:\Users\boom\vimfiles\plugin.vimrc
Vim(source):E484: € D:\Neovim<d6><d0>\share\nvim\runtime\syntax\syntax.vim
C:\Users\boom\vimfiles\face.vimrc
Vim(source):E484: € D:\Neovim<d6><d0>\share\nvim\runtime\syntax\syntax.vim
 ENTER
```

### PR DESCRIPTION
**Pull request by justinmk**
* use libuv v1.12 `uv_os_getenv`, `uv_os_setenv`
* Minimum required libuv is now v1.12
* Because `uv_os_getenv` requires allocating, we need to manage a map (`envmap` in `env.c`) to maintain the old behavior of `os_getenv` .

closes #8398
closes #9267 

todo

- [x] include @erw7 test case
- [x] Although `tui.c` is in a separate thread, as long as it and the main thread don't change each other's env vars, there may be no need for synchronization (`mutex`). Or the critical sections could at least be minimized to `envmap` access.
- [ ] Enhance `log.c` to deal with recursive invocation.
- [ ] Why does the `printenv-test.c` test fail on non-WIndows CI (Travis, Quickbuild)? (It fails even [on master, before the changes from this PR.](https://github.com/neovim/neovim/pull/9654))

### CODE REVIEW

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/7920/commits/0d36fe9aa22e1861b0152f93b09ff07442e4c423 failed also, this confirms that even before this change the new test fails (on AppVeyor):

```
C:/projects/neovim/test/functional\eval\let_spec.lua:55: Expected objects to be the same.
Passed in:
(string) 'A�aB'
Expected:
(string) 'AìaB'
```

File: src/nvim/os/env.c [hunk 1]
```diff
@@ -35,8 +35,25 @@
...
+    return NULL;
+  }
+  wchar_t *wvalue = _wgetenv(wname);
+  char *value;
+  int rv = utf16_to_utf8(wvalue, &value);
+  if (rv != 0 || *value == NUL) {
+    xfree(value);
+    return NULL;
+  }
+  return value;  // TODO(jmk): this was allocated, but callers don't free it ...
```
Comment (justinmk) [inline src/nvim/os/env.c]: This is passing tests now. But now we need to manage the allocations ...

**Comment by justinmk** [comment]
strange failures on Windows/AppVeyor.

```
CUSTOMBUILD : error 2019-02-27T01: 26:45.000 4744  os_getenv:70: uv_os_getenv(HOME) failed: -4075: file already exists [C:\projects\neovim\build\functionaltest.vcxproj]
CUSTOMBUILD : error 2019-02-27T01: 26:54.000 684   os_getenv:70: uv_os_getenv(LC_ALL) failed: -4094: unknown error [C:\projects\neovim\build\functionaltest.vcxproj]
CUSTOMBUILD : error 2019-02-27T01: 26:56.000 1316  os_getenv:70: uv_os_getenv(LC_ALL) failed: -4094: unknown error [C:\projects\neovim\build\functionaltest.vcxproj]
CUSTOMBUILD : error 2019-02-27T01: 27:02.000 2424  os_getenv:70: uv_os_getenv(LC_ALL) failed: -4094: unknown error [C:\projects\neovim\build\functionaltest.vcxproj]
CUSTOMBUILD : error 2019-02-27T01: 27:09.000 5108  os_getenv:70: uv_os_getenv(LC_ALL) failed: -4094: unknown error [C:\projects\neovim\build\functionaltest.vcxproj]
CUSTOMBUILD : error 2019-02-27T01: 27:23.000 300   os_getenv:70: uv_os_getenv(OPTWIN_CMD) failed: -4094: unknown error [C:\projects\neovim\build\functionaltest.vcxproj]
```
