### PR TITLE
fix(lsp): warn on missing configurations in `:checkhealth`

### LINKED ISSUE #33089: `:checkhealth vim.lsp` throws an error if `vim.lsp.enable` has been called without any configuration provided with `vim.lsp.config`
### Problem

If the user has used `vim.lsp.enable` to enable a language server which has not been configured with `vim.lsp.config` the checkhealth fails when listing enabled language servers. This is because the checkhealth is grabing the config with `vim.lsp.config[server]` which returns a table or `nil` and there is no case to check if the value is `nil`.

### Steps to reproduce

nvim --clean
:lua vim.lsp.enable("lua_ls")
:checkhealth vim.lsp

### Expected behavior

The checkhealth should handle errors such as this and return useful information to the user such as "configuration not found" to indicate to the user that they have enabled a language server that will not be used because no configuration was found.

### Nvim version (nvim -v)

0.11.0

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Arch Linux

### Terminal name/version

Kitty 0.40.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo release

### PR DESCRIPTION
**Pull request by mehalter**
Currently if a language server is enabled with `vim.lsp.enable` and is not configured previously with `vim.lsp.config` it just gives an error in the `:checkhealth vim.lsp`:

```
- ERROR Failed to run healthcheck for "vim.lsp" plugin. Exception:
  vim/shared.lua:0: t: expected table, got nil
```

This resolves the failure and instead gives the user a warning that an enabled language server could not be resolved to a configuration

Resolves #33089

### CODE REVIEW

**Comment by clason** [comment]
This does not happen out of the box. How did you install Nvim? Are you sure you made a clean install (i.e., there are no obsolete runtime files from a previous version that do not get uninstalled when building manually)?

**Comment by mehalter** [comment]
You are correct. But if the user runs `vim.lsp.enable` on a language server that is not configured then they no longer can look at the `:checkhealth vim.lsp` and get useful information. This is simply error checking to let the user know if they did something bad in their configuration.

Here is a recording using `nvim --clean` with the Neovim v0.11 release: https://asciinema.org/a/NKhCwoARcWyr4DllYi1HAOynq

**Comment by clason** [comment]
Then your PR (and commit) needs a much better description. Maybe start with an issue?

**Comment by mehalter** [comment]
Yeah, I revised the PR comment and added `vim.lsp` to my commit message. Not sure how much better to make the commit message since this just adds a warning to the checkhealth if a configuration is missing

**Comment by mehalter** [comment]
Ah, I see! I have revised the commit so that the body of the commit message contains the problem and solution information. I'm so sorry about that!

I have also gone ahead and made an issue and linked it to this PR as well

**Review by MariaSolOs — APPROVED** [review]

File: runtime/lua/vim/lsp/health.lua [hunk 1]
```diff
@@ -187,27 +187,31 @@ local function check_enabled_configs()
...
-      if k == 'name' then
-        v_str = nil
-      elseif k == 'filetypes' or k == 'root_markers' then
-        v_str = table.concat(v, ', ')
-      elseif type(v) == 'function' then
-        v_str = func_tostring(v)
-      else
-        v_str = vim.inspect(v, { newline = '\n  ' })
-      end
+    if config then
```
Comment (justinmk) [inline runtime/lua/vim/lsp/health.lua:190]: nit: put the error handling first, especially if it's short compared to the main logic.
```suggestion
    if not config then
      report_warn(...)
```

Comment (mehalter) [reply runtime/lua/vim/lsp/health.lua]: That makes sense! Thanks for the review!

**Review by justinmk — APPROVED** [review]
