### PR TITLE
fix(options): fix memory leaks in vim.api.nvim_*get_option

### LINKED ISSUE #32361: Potential memory leaks in `vim.api.nvim_*get_option`
### Problem

After prolonged runtime (~several days), Neovim exhibits abnormally high memory usage (~multi-GB). Through jemalloc + jeprof analysis, significant memory consumption was traced to the `nlua_api_nvim_*get_option` functions. Certain plugins periodically call these functions in the background, and the functions appear to fail releasing memory properly.

Image

The issue can be reliably reproduced and captured using valgrind in headless mode.

Notably, these deprecated functions [lack the `FUNC_API_RET_ALLOC` flag](https://github.com/neovim/neovim/blob/5371659524089b425887af1ce14bf9a374f0f234/src/nvim/api/deprecated.c#L633), whereas their replacement [`nvim_get_option` is properly annotated](https://github.com/neovim/neovim/blob/5371659524089b425887af1ce14bf9a374f0f234/src/nvim/api/options.c#L151). While unfamiliar with Neovim's internal API mechanics, I suspect this discrepancy might correlate with the observed issues.

### Steps to reproduce

1. `make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_C_FLAGS=-DEXITFREE"`

2. Valgrind reports leaks in deprecated function: `VIMRUNTIME=./runtime/ valgrind --leak-check=full -- ./build/bin/nvim -u NORC --headless +'lua print(vim.api.nvim_get_option("helpfile"))' +q`
  ```
  ==1487761== Memcheck, a memory error detector
  ==1487761== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
  ==1487761== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
  ==1487761== Command: ./build/bin/nvim -u NORC --headless +lua\ print(vim.api.nvim_get_option("helpfile")) +q
  ==1487761==
  ./runtime/doc/help.txt==1487761==
  ==1487761== HEAP SUMMARY:
  ==1487761==     in use at exit: 2,313 bytes in 18 blocks
  ==1487761==   total heap usage: 15,234 allocs, 15,216 frees, 21,348,696 bytes allocated
  ==1487761==
  ==1487761== 23 bytes in 1 blocks are definitely lost in loss record 2 of 8
  ==1487761==    at 0x4C39185: malloc (vg_replace_malloc.c:442)
  ==1487761==    by 0x59EDC8: try_malloc (memory.c:98)
  ==1487761==    by 0x59EF57: UnknownInlinedFun (memory.c:132)
  ==1487761==    by 0x59EF57: arena_alloc (memory.c:637)
  ==1487761==    by 0x59F0D6: UnknownInlinedFun (memory.c:704)
  ==1487761==    by 0x59F0D6: arena_memdupz (memory.c:711)
  ==1487761==    by 0x6F5B19: copy_string (helpers.c:643)
  ==1487761==    by 0x56B9E5: optval_copy (option.c:3097)
  ==1487761==    by 0x56BA6B: get_option_value (option.c:3342)
  ==1487761==    by 0x56BB63: get_option_value_for (option.c:3945)
  ==1487761==    by 0x7151AE: get_option_from (deprecated.c:746)
  ==1487761==    by 0x715569: nvim_get_option (deprecated.c:637)
  ==1487761==    by 0x5F603F: nlua_api_nvim_get_option.lto_priv.538 (lua_api_c_bindings.generated.h:2675)
  ==1487761==    by 0x786C85: lj_BC_FUNCC (in /data/build/neovim/build/bin/nvim)
  ==1487761==
  ==1487761== LEAK SUMMARY:
  ==1487761==    definitely lost: 23 bytes in 1 blocks
  ==1487761==    indirectly lost: 0 bytes in 0 blocks
  ==1487761==      possibly lost: 0 bytes in 0 blocks
  ==1487761==    still reachable: 2,290 bytes in 17 blocks
  ==1487761==         suppressed: 0 bytes in 0 blocks
  ==1487761== Reachable blocks (those to which a pointer was found) are not shown.
  ==1487761== To see them, rerun with: --leak-check=full --show-leak-kinds=all
  ==1487761==
  ==1487761== For lists of detected and suppressed errors, rerun with: -s
  ==1487761== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
  ```

3. No leaks in the new `nvim_get_option_value`: `VIMRUNTIME=./runtime/ valgrind --leak-check=full -- ./build/bin/nvim -u NORC --headless +'lua print(vim.api.nvim_get_option_value("helpfile", {}))' +q`
  ```
  ==1487857== Memcheck, a memory error detector
  ==1487857== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
  ==1487857== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
  ==1487857== Command: ./build/bin/nvim -u NORC --headless +lua\ print(vim.api.nvim_get_option_value("helpfile",\ {})) +q
  ==1487857==
  ./runtime/doc/help.txt==1487857==
  ==1487857== HEAP SUMMARY:
  ==1487857==     in use at exit: 2,290 bytes in 17 blocks
  ==1487857==   total heap usage: 15,234 allocs, 15,217 frees, 21,348,586 bytes allocated
  ==1487857==
  ==1487857== LEAK SUMMARY:
  ==1487857==    definitely lost: 0 bytes in 0 blocks
  ==1487857==    indirectly lost: 0 bytes in 0 blocks
  ==1487857==      possibly lost: 0 bytes in 0 blocks
  ==1487857==    still reachable: 2,290 bytes in 17 blocks
  ==1487857==         suppressed: 0 bytes in 0 blocks
  ==1487857== Reachable blocks (those to which a pointer was found) are not shown.
  ==1487857== To see them, rerun with: --leak-check=full --show-leak-kinds=all
  ==1487857==
  ==1487857== For lists of detected and suppressed errors, rerun with: -s
  ==1487857== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
  ```

### Expected behavior

Has reasonable memory consumption and does not leak resource.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1703+g878b3b89c3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux

### Terminal name/version

fish, version 3.3.1 + tmux 3.6

### $TERM environment variable

tmux-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by cairijun**
Problem: `get_option_value` returns caller owned `Object`s but the corresponding C apis do not marked `FUNC_API_RET_ALLOC` properly.

Solution: add `FUNC_API_RET_ALLOC` to the C apis.

Fix: #32361

### CODE REVIEW

File: test/functional/api/deprecated_spec.lua [hunk 1]
```diff
@@ -18,4 +18,19 @@ describe('deprecated', function()
       n.api.nvim_notify('hello world', 4, {})
     end)
   end)
+
+  describe('nvim_*get_option functions', function()
+    it('does not leak memory', function()
+      if not (n.is_asan() or os.getenv('VALGRIND')) then
+        pending('not running in valgrind or asan')
+        return
+      end
```
Comment (zeertzjq) [inline test/functional/api/deprecated_spec.lua:27]: I don't think this is needed. A test is usually only skipped if it cannot be run.

Comment (cairijun) [reply test/functional/api/deprecated_spec.lua]: Removed.
But just curious, doesn't this mean a test "pass" would give misleading false negative if it breaks again?

Comment (zeertzjq) [reply test/functional/api/deprecated_spec.lua]: Does that matter? Usually one only looks at a test if it fails.
