### PR TITLE
fix(cmd): filter stdin marker from v:argv on restart

### LINKED ISSUE #34417: `:restart` hangs when nvim reads stdin
### Problem

I am not sure if it is relevant, but `~/.local/state/nvim/log` records the following after nvim reads stdin:

```
WRN 2025-06-10T19:21:12.484 ui.842976  tui_handle_term_mode:240: TUI: terminal mode 69 detected, state 2
WRN 2025-06-10T19:21:12.484 ui.842976  tui_handle_term_mode:230: TUI: terminal mode 2026 unavailable, state 4
WRN 2025-06-10T19:21:12.484 ui.842976  tui_handle_term_mode:230: TUI: terminal mode 2027 unavailable, state 0
WRN 2025-06-10T19:21:12.484 ui.842976  tui_handle_term_mode:230: TUI: terminal mode 2031 unavailable, state 0
WRN 2025-06-10T19:21:12.484 ui.842976  tui_handle_term_mode:230: TUI: terminal mode 2048 unavailable, state 4
ERR 2025-06-10T19:21:12.846 nvim.842977.0 os_set_cloexec:501: Failed to get flags on descriptor 3: Bad file descriptor
```

Then I try to `:restart`, and nvim hangs.

### Steps to reproduce

1. `nvim --clean - < /dev/null`
2. `:restart`

### Expected behavior

nvim does not hang, or `:qall`.

### Nvim version (nvim -v)

v0.12.0-dev-93925fe

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

EndeavourOS

### Terminal name/version

GNOME Terminal 3.56.2 using VTE 0.80.2 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by glepnir**
Problem:
restart hangs when nvim was started with stdin input, "-" marker stays in v:argv, causing the restarted instance to block reading from stdin.

Solution:
filter out the "-" argument when rebuilding v:argv during restart. Stdin content is ephemeral and shouldn't be re-read after restart.

Fix #34417

### CODE REVIEW

**Comment by superatomic** [comment]
On Unix systems, should `/dev/stdin` also be filtered?

**Comment by glepnir** [comment]
`/dev/stdin` is treated as a regular file path, not a special stdin marker.

**Comment by justinmk** [comment]
this needs a rebase...

File: test/functional/terminal/tui_spec.lua [hunk 1]
```diff
@@ -440,6 +440,38 @@ describe('TUI :restart', function()
     restart_pid_check()
     gui_running_check()
   end)
+
+  it('filters stdin marker from v:argv on restart #34417', function()
+    if t.skip(is_os('win'), 'unstable on Windows') then
```
Comment (justinmk) [inline test/functional/terminal/tui_spec.lua]: maybe it works on Windows after rebasing? e.g. 19eb75831b93 and other commits improved tests/restart/etc on Windows.

File: test/functional/terminal/tui_spec.lua [hunk 2]
```diff
@@ -440,6 +440,38 @@ describe('TUI :restart', function()
...
+      '-u',
+      'NONE',
+      '-i',
+      'NONE',
+      '--cmd',
+      'set notermguicolors',
+      '-', -- stdin marker
+    })
+    tt.feed_data(':echo index(v:argv, "-") >= 0 ? v:true : v:false\013')
+    screen:expect({ any = 'v:true' })
```
Comment (justinmk) [inline test/functional/terminal/tui_spec.lua]: instead of this hack, can we connect to the child Nvim by returning the child address from `tt.setup_child_nvim` . E.g. 

1. get the job-id [here](https://github.com/neovim/neovim/blob/e8ace820934a9eb7f23b7a3f61ccea2c7de02043/test/functional/testterm.lua#L151) 
2. then get its address 
3. then use `n.connect()`
4. then use `n.set_session()`
5. then we can use `n.*` functions
6. then restore the main session again via `n.set_session()`

File: src/nvim/ex_docmd.c [hunk 3]
```diff
@@ -4938,27 +4938,31 @@ static void ex_quitall(exarg_T *eap)
...
+  int argc = tv_list_len(l);
+  list_T *argv_cpy = tv_list_alloc(eap->arg ? argc + 2 : argc);
+  bool added_startup_arg = false;
+
+  TV_LIST_ITER_CONST(l, li, {
+    const char *arg = tv_get_string(TV_LIST_ITEM_TV(li));
+    size_t arg_size = strlen(arg);
+    assert(arg_size <= (size_t)SSIZE_MAX);
+    // Skip "-" argument (stdin input marker).
+    if (strequal(arg, "-")) {
```
Comment (justinmk) [inline src/nvim/ex_docmd.c:4953]: would it be more reliable to use `VV_ARGF` , after we merge https://github.com/neovim/neovim/pull/35889 ?

Comment (glepnir) [reply src/nvim/ex_docmd.c:4953]: `VV_ARGF` only contains the file arguments (from global_alist),  not the full command line. ex_restart needs to rebuild the complete  v:argv including all flags, so VV_ARGF is not applicable here. main function of 35889
 
```C
static void set_argf_var(void)
{
  list_T *list = tv_list_alloc(kListLenMayKnow);

  for (int i = 0; i < GARGCOUNT; i++) {
    char *fname = alist_name(&GARGLIST[i]);Expand commentComment on line R1511Resolved
    if (fname != NULL) {
      (void)vim_FullName(fname, NameBuff, sizeof(NameBuff), false);
      tv_list_append_string(list, NameBuff, -1);
    }
  }

  tv_list_set_lock(list, VAR_FIXED);
  set_vim_var_list(VV_ARGF, list);
}
```

File: test/functional/terminal/tui_spec.lua (hunk 1 above)
Comment (glepnir) [reply test/functional/terminal/tui_spec.lua]: On Windows, seems like stdin is treated as a tty rather than a pipe, so `nvim -` does not create the same read-only stdin buffer as on Unix. The test is about filtering "-" from v:argv, not the exact UI state,  it's still failed on Windows so skip on Windows

File: src/nvim/ex_docmd.c (hunk 3 above)
Comment (justinmk) [reply src/nvim/ex_docmd.c:4953]: yes, but "-" should be in the file arguments, right? i'm wondering if there is a potential for a "false positive" here, and using VV_ARGF would avoid that.

Comment (glepnir) [reply src/nvim/ex_docmd.c:4953]: ye good point. The false positive case is `nvim -- -` where `-` is a filename. VV_ARGF stores file arguments expanded to their full paths. So a file literally named `-` will be stored as something like `/path/to/-`, whereas the stdin marker `-` will never appear in VV_ARGF at all. The cleanest fix would be to expose `had_stdin_file` as a vim variable (e.g. `v:stdin`) set during startup, so ex_restart can distinguish the stdin marker from a file named `-`.  implement that instead?

Comment (justinmk) [reply src/nvim/ex_docmd.c:4953]: in the case of `nvim -s -` , the `-s` also needs to be removed

Comment (glepnir) [reply src/nvim/ex_docmd.c:4953]: after reconsider if https://github.com/neovim/neovim/pull/35889 handle `-s` in `set_argf_var` then things become easy.

```C
static void set_argf_var(mparm_T *parmp)
{
  list_T *list = tv_list_alloc(kListLenMayKnow);
  for (int i = 0; i < GARGCOUNT; i++) {
    char *fname = alist_name(&GARGLIST[i]);
    if (fname != NULL) {
      (void)vim_FullName(fname, NameBuff, sizeof(NameBuff), false);
      tv_list_append_string(list, NameBuff, -1);
    }
  }
  tv_list_set_lock(list, VAR_FIXED);
  set_vim_var_list(VV_ARGF, list);

  // Also record if scriptin was "-" so ex_restart can filter "-s -"
  if (parmp->scriptin && strequal(parmp->scriptin, "-")) {
    set_vim_var_nr(VV_STDIN_SCRIPT, 1);  // or reuse existing var
  }
}
```

then we can use it like 

```C
TV_LIST_ITER_CONST(l, li, {
  const char *arg = tv_get_string(TV_LIST_ITEM_TV(li));

  // Skip stdin-related args: not in VV_ARGF means stdin marker not real file
  if (strequal(arg, "-") && tv_list_find_str(get_vim_var_list(VV_ARGF), arg) == NULL) {
    continue;
  }
  // Skip "-s -" if scriptin was stdin
  if (strequal(arg, "-s") && get_vim_var_nr(VV_STDIN_SCRIPT)) {
    li = TV_LIST_ITEM_NEXT(l, li);  // skip the following "-" too
    continue;
  }
   ...
});
```

ll optimize this further after #35889 is merged.
