### PR TITLE
jobwait(): fix race if job exits quickly

### LINKED ISSUE #8302: flaky test: job-control: failed jobwait() test
QB failure noticed in https://github.com/neovim/neovim/pull/8296 (but unrelated to that PR; possibly related to #8273 , or a side-effect of the recent quickbuild system upgrade):

```
05:05:00,790 INFO  - not ok 389 - jobs jobwait will run callbacks while waiting
05:05:00,790 INFO  - # test/functional/core/job_spec.lua @ 521
05:05:00,790 INFO  - # Failure message: test/functional/core/job_spec.lua:544: Expected objects to be the same.
05:05:00,790 INFO  - # Passed in:
05:05:00,790 INFO  - # (table) {
05:05:00,790 INFO  - #   [1] = 'notification'
05:05:00,790 INFO  - #   [2] = 'wait'
05:05:00,790 INFO  - #  *[3] = {
05:05:00,790 INFO  - #    *[1] = 3 } }
05:05:00,790 INFO  - # Expected:
05:05:00,790 INFO  - # (table) {
05:05:00,790 INFO  - #   [1] = 'notification'
05:05:00,791 INFO  - #   [2] = 'wait'
05:05:00,791 INFO  - #  *[3] = {
05:05:00,791 INFO  - #    *[1] = 4 } }
05:05:00,791 INFO  - # stack traceback:
05:05:00,791 INFO  - # >test/functional/core/job_spec.lua:544: in function <test/functional/core/job_spec.lua:521>
```

Are the streams all closed somehow before the process exits? Or is `proc->status` not set correctly (`>=0`) in some case? cc @bfredl

### PR DESCRIPTION
**Pull request by justinmk**
Test sometimes fails on macOS CI (and QuickBuild #8302):

    FAILED  test/functional/core/job_spec.lua: jobs jobwait will run callbacks while waiting
    test/functional/core/job_spec.lua:606: Expected objects to be the same.
    Passed in:
    (table: 0x1be77c80) {
      [1] = 'notification'
      [2] = 'wait'
     *[3] = {
       *[1] = 3 } }
    Expected:
    (table: 0x1be77d10) {
      [1] = 'notification'
      [2] = 'wait'
     *[3] = {
       *[1] = 4 } }
    stack traceback:
      test/functional/core/job_spec.lua:606: in function <test/functional/core/job_spec.lua:583

fix #8302

### CODE REVIEW

**Comment by justinmk** [comment]
macOS failure shows that the jobs indeed run, and only the exit is missed:

```
[1m[35m[  FAILED  ][0m[0m [36mtest/functional/core/job_spec.lua[0m @ [36m583[0m: [1mjobs jobwait will run callbacks while waiting[0m
test/functional/core/job_spec.lua:611: Expected objects to be the same.
Passed in:
(table: 0x1c9b98c8) {
  [1] = 'notification'
  [2] = 'wait'
 *[3] = {
    [1] = {
      [1] = 3
      [2] = 4
      [3] = 5
      [4] = 6 }
   *[2] = {
      [1] = 3
      [2] = 4
      [3] = 5 } } }
```

**Comment by blueyed** [comment]
> Test sometimes fails on macOS CI:

Has this started only recently?

**Comment by justinmk** [comment]
No, this is common on macOS CI for a long time. I can repro it locally, and it does appear to be a race. Investigating.

**Comment by justinmk** [comment]
this patch seems to fix it.  

- Without this change the exit handler is queued but `f_jobwait` returns before processing it.
- With this change `process_wait` will process the exit handler before `f_jobwait` returns.
- Not sure if there's any reason to avoid `process_wait` in this case.

```diff
diff --git a/src/nvim/eval.c b/src/nvim/eval.c
index 79e67f6d7bc9..8926ae9bc2ad 100644
--- a/src/nvim/eval.c
+++ b/src/nvim/eval.c
@@ -12480,20 +12480,27 @@ static void f_jobwait(typval_T *argvars, typval_T *rettv, FunPtr fptr)
     // if the job already exited, but wasn't freed yet
-    if (jobs[i] == NULL || jobs[i]->stream.proc.status >= 0) {
+    if (jobs[i] == NULL) {
       continue;
     }
 
     int status = process_wait(&jobs[i]->stream.proc, remaining,
                               waiting_jobs);
     if (status < 0) {
```

**Comment by blueyed** [comment]
For reference, this appears to come via f629f8312.  /cc @bfredl

**Comment by blueyed** [comment]
btw: why is clint failing for me, but not on CI?
```
[130/131] Generating ../../touches/ran-clint-eval-c
FAILED: touches/ran-clint-eval-c
cd …/Vcs/neovim && …/Vcs/neovim/src/clint.py --suppress-errors=…/Vcs/neovim/build/errors/eval-c.json src/nvim/eval.c && /usr/bin/cmake -E touch …/Vcs/neovim/build/touches/ran-clint-eval-c
src/nvim/eval.c:3370:  /*-style comment found, it should be replaced with //-style.  /*-style comments are only allowed inside macros.  Note that you should not use /*-style comments to document macros itself, use doxygen-style comments for this.  [readability/old_style_comment] [5]
…
src/nvim/eval.c:3377:  /*-style comment found, it should be replaced with //-style.  /*-style comments are only allowed inside macros.  Note that you should not use /*-style comments to document macros itself, use doxygen-style comments for this.  [readability/old_style_comment] [5]
Total errors found: 8
[131/131] Generating ../../touches/ran-clint-tui-terminfo_defs-h
ninja: build stopped: subcommand failed.
```

(both on this branch, and on a merge commit; the code is not changed (in this branch))

**Comment by bfredl** [comment]
@blueyed This was a direct translation of the "typval" based loop which behaved the same way. Though maybe this was not an issue back then as "exit" callback was processed earlier in the channel close ritual (because we didn't strictly order it after output callbacks).

**Comment by justinmk** [comment]
> because we didn't strictly order it after output callbacks

@bfredl ooh, does that mean we can enable this test now?

    pending('will only emit the "exit" event after "stdout" and "stderr"', function()

**Comment by bfredl** [comment]
Try it :)

**Comment by blueyed** [comment]
> Try it :)

Does not work (after removing "s:" with "s:OnEvent"):
```
[  FAILED  ] test/functional/core/job_new_spec.lua @ 737: jobs will only emit the "exit" event after "stdout" and "stderr"
test/functional/core/job_new_spec.lua:743: Expected objects to be the same.
Passed in:
(table: 0x411e0b98) {
  [1] = 'notification'
 *[2] = 'stderr'
  [3] = {
    [1] = 0
    [2] = {
      [1] = '' } } }
Expected:
(table: 0x4120cbe0) {
  [1] = 'notification'
 *[2] = 'j'
  [3] = {
    [1] = 0
    [2] = {
      [1] = 3
      [2] = 'stdout'
      [3] = {
        [1] = 'abcdef' } } } }

stack traceback:
        test/functional/core/job_new_spec.lua:743: in function <test/functional/core/job_new_spec.lua:737>

```

**Comment by justinmk** [comment]
@blueyed the test was written for https://github.com/neovim/neovim/blob/d3f81424e5a8de5d184f3ab3e14b632fa70f857d/test/functional/job/job_spec.lua#L19 and needs to be updated. https://github.com/neovim/neovim/pull/10929

File: test/functional/ui/wildmode_spec.lua [hunk 1]
```diff
@@ -98,8 +98,8 @@ describe("'wildmenu'", function()
     ]]}
 
     -- cmdline CTRL-D display should also be preserved.
-    feed([[<C-\><C-N>]])
-    feed([[:sign <C-D>]])   -- Invoke cmdline CTRL-D.
+    feed([[<C-U>]])
+    feed([[sign <C-D>]])   -- Invoke cmdline CTRL-D.
     expect_stay_unchanged{grid=[[
```
Comment (justinmk) [inline test/functional/ui/wildmode_spec.lua]: [still failing](https://travis-ci.org/neovim/neovim/builds/580949539), although now it's the one before this (line 92). It's simply a race, we should probably use `any=...` combined with `screen: expect_unchanged()`.

```
[  ERROR   ] test/functional/ui/wildmode_spec.lua @ 84: 'wildmenu' is preserved during :terminal activity
test/functional/ui/screen.lua:587: Row 1 did not match.
Expected:
  |*                         |
  |                         |
  |                         |
  |define  jump  list  >    |
  |:sign define^             |
Actual:
  |*0: !terminal_output!     |
  |                         |
  |                         |
  |define  jump  list  >    |
  |:sign define^             |
To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  
stack traceback:
	test/functional/ui/screen.lua:587: in function '_wait'
	test/functional/ui/screen.lua:370: in function 'expect'
	test/functional/ui/wildmode_spec.lua:22: in function 'expect_stay_unchanged'
	test/functional/ui/wildmode_spec.lua:92: in function <test/functional/ui/wildmode_spec.lua:84>
```
