### PR TITLE
fix(rpc): assertion failure due to invalid msgpack input

### LINKED ISSUE #23781: line buffering triggers "rbuffer_consumed: Assertion 'count && count <= buf->size' failed"
### Problem

Neovim crashes.

### Steps to reproduce

```
printf '' | nvim --embed
```

### Expected behavior

No crash. Note that while this reproducer may seem contrived, it actually comes from an actual use case (piping messagepack commands to an embedded neovim from the shell).

This crash may or may not be related to https://github.com/neovim/neovim/issues/21604 .

### Neovim version (nvim -v)

8e6971695383047ee5ba2921c91d98acb18c6d7a

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

linux

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

Built from source

### PR DESCRIPTION
**Pull request by ghost**
Problem:
  rbuffer_consumed assertion fails if Unpacker fails to parse msgpack,
  because it doesn't consume bytes on errors

Solution:
  Call rbuffer_consumed_compact only if Unpacker isn't closed  

fixes #23781

### CODE REVIEW

File: test/functional/core/channels_spec.lua [hunk 1]
```diff
@@ -4,7 +4,7 @@ local clear, eq, eval, next_msg, ok, source = helpers.clear, helpers.eq,
 local command, funcs, meths = helpers.command, helpers.funcs, helpers.meths
 local sleep = helpers.sleep
 local spawn, nvim_argv = helpers.spawn, helpers.nvim_argv
-local set_session = helpers.set_session
+local get_session, set_session= helpers.get_session, helpers.set_session
```
Comment (zeertzjq) [inline test/functional/core/channels_spec.lua:7]:
```suggestion
local get_session, set_session = helpers.get_session, helpers.set_session
```

File: src/nvim/msgpack_rpc/channel.c [hunk 2]
```diff
@@ -306,8 +306,11 @@ static void receive_msgpack(Stream *stream, RBuffer *rbuf, size_t c, void *data,
   p->read_ptr = rbuffer_read_ptr(rbuf, &size);
   p->read_size = size;
   parse_msgpack(channel);
-  size_t consumed = size - p->read_size;
-  rbuffer_consumed_compact(rbuf, consumed);
+
+  if (!unpacker_closed(p)) {
+    size_t consumed = size - p->read_size;
+    rbuffer_consumed_compact(rbuf, consumed);
+  }
```
Comment (zeertzjq) [inline src/nvim/msgpack_rpc/channel.c:313]: How about checking `if (consumed > 0)` instead? If the start of the buffer is valid it should still be consumed.

**Review by justinmk — APPROVED** [review]

File: src/nvim/msgpack_rpc/channel.c [hunk 3]
```diff
@@ -306,8 +306,11 @@ static void receive_msgpack(Stream *stream, RBuffer *rbuf, size_t c, void *data,
   p->read_ptr = rbuffer_read_ptr(rbuf, &size);
   p->read_size = size;
   parse_msgpack(channel);
-  size_t consumed = size - p->read_size;
-  rbuffer_consumed_compact(rbuf, consumed);
+
+  if (!unpacker_closed(p)) {
+    size_t consumed = size - p->read_size;
+    rbuffer_consumed_compact(rbuf, consumed);
```
Comment (justinmk) [inline src/nvim/msgpack_rpc/channel.c:312]: Although @KillTheMule says this doesn't fix https://github.com/neovim/neovim/issues/23781#issuecomment-1902176915 , checking `unpacker_closed` still looks like it's needed because there is nothing else in `channel.c` to stop `receive_msgpack` from being called if the unpacker is closed...

Do we need to call `chan_close_with_error` as we do above?
