### PR TITLE
vim-patch:8.2.{2198,3159}

### LINKED ISSUE #7528: internal error when creating popup attached to text property
**Describe the bug**

Creating a popup window attached to a text property might raise an internal error.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        call range(2)->setline(1)
        call prop_type_add('popupNumberColumn', {})
        call prop_add(1, 1, {'type': 'popupNumberColumn'})
        call popup_create('', {'textprop': 'popupNumberColumn'})
        $
        h
        call feedkeys("\r", 'xt')
    EOF
    )

`E315` and `E967` are raised:

    E315: ml_get: invalid lnum: 3
    E967: text property info corrupted

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2188
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

[backtrace](https://github.com/vim/vim/files/5731125/backtrace.txt)

### PR DESCRIPTION
**Pull request by janlazo**
Problem:    ml_get error when resizing window and using text property.
Solution:   Validate botline of the right window. (closes vim/vim#7528)

https://github.com/vim/vim/commit/23999d799cfe844b604f193183f8f84052c8e746

### CODE REVIEW

**Review by zeertzjq — COMMENTED** [review]
This makes `validate_botline()` inconsistent with `invalidate_botline()`. `invalidate_botline_win()` was renamed to `invalidate_botline()` in 008154954791001efcc46c28146e21403f3a698b.

File: src/nvim/move.c [hunk 1]
```diff
@@ -608,16 +611,30 @@ void changed_line_abv_curs_win(win_T *wp)
                    |VALID_CHEIGHT|VALID_TOPLINE);
 }
 
-// Make sure the value of wp->w_botline is valid.
-void validate_botline(win_T *wp)
+/// Make sure the value of curwin->w_botline is valid.
+void validate_botline(void)
+{
+  validate_botline_win(curwin);
+}
```
Comment (bfredl) [inline src/nvim/move.c]: We don't want these alias functions back. caller should spell out `curwin` if that is what is intended.

**Comment by zeertzjq** [comment]
I think these should be `refactor(move.c)`, not `fix(move.c)`

**Review by zeertzjq — APPROVED** [review]
