### PR TITLE
vim-patch:8.0.{725,1411}

### LINKED ISSUE #2469: global-buffer-overflow in get_op_type
Hello.

I found a global-buffer-overflow bug in vim.

Please confirm.

Thanks.

Summary: global-buffer-overflow
OS: CentOS 7 64bit
Version: b254af3
PoC Download: [OV_get_op_type.zip](https://github.com/vim/vim/files/1569842/OV_get_op_type.zip)

Steps to reproduce:
1.Download the .POC files.
2.Compile the source code with ASan.
3.Execute the following command
: ./vim -u NONE -Z -X -e -s -S $POC -c :qa!

```
=================================================================
==22103==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000001cbbd5a at pc 0x000000d4a251 bp 0x7ffd55706950 sp 0x7ffd55706948
READ of size 1 at 0x000001cbbd5a thread T0
    #0 0xd4a250 in get_op_type /home/karas/vim/src/ops.c:186:6
    #1 0xce414d in nv_operator /home/karas/vim/src/normal.c:8581:15
    #2 0xcee973 in nv_colon /home/karas/vim/src/normal.c:5374:2
    #3 0xce00c3 in nv_window /home/karas/vim/src/normal.c:7854:2
    #4 0xc914ca in normal_cmd /home/karas/vim/src/normal.c:1151:5
    #5 0x165a63c in main_loop /home/karas/vim/src/main.c:1357:3
    #6 0x91e4ff in open_cmdwin /home/karas/vim/src/ex_getln.c:7057:5
    #7 0x8ffd5a in getcmdline /home/karas/vim/src/ex_getln.c:834:7
    #8 0x92b3e5 in getexline /home/karas/vim/src/ex_getln.c:2390:12
    #9 0x8265f0 in do_cmdline /home/karas/vim/src/ex_docmd.c:967:46
    #10 0x8c036e in ex_at /home/karas/vim/src/ex_docmd.c:9490:12
    #11 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #12 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #13 0x813fb7 in do_source /home/karas/vim/src/ex_cmds2.c:4411:5
    #14 0x810477 in cmd_source /home/karas/vim/src/ex_cmds2.c:4024:14
    #15 0x810596 in ex_source /home/karas/vim/src/ex_cmds2.c:3999:2
    #16 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #17 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #18 0x82c835 in do_cmdline_cmd /home/karas/vim/src/ex_docmd.c:671:12
    #19 0x1658084 in exe_commands /home/karas/vim/src/main.c:2953:2
    #20 0x1651bc6 in vim_main2 /home/karas/vim/src/main.c:800:2
    #21 0x1642d2d in main /home/karas/vim/src/main.c:429:12
    #22 0x7fd4df8e282f in __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291
    #23 0x41aaa8 in _start (/home/karas/vim/src/vim+0x41aaa8)

0x000001cbbd5a is located 0 bytes to the right of global variable 'opchars' defined in 'ops.c:134:13' (0x1cbbd00) of size 90
SUMMARY: AddressSanitizer: global-buffer-overflow /home/karas/vim/src/ops.c:186:6 in get_op_type
Shadow bytes around the buggy address:
  0x00008038f750: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008038f760: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008038f770: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008038f780: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008038f790: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x00008038f7a0: 00 00 00 00 00 00 00 00 00 00 00[02]f9 f9 f9 f9
  0x00008038f7b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008038f7c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008038f7d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008038f7e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008038f7f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==22103==ABORTING
```
=================
[Acknowledgement]
This work was supported by ICT R&D program of MSIP/IITP. [R7518-16-1001, Innovation hub for high Performance Computing]

### PR DESCRIPTION
**Pull request by janlazo**
**vim-patch:8.0.0725: a terminal window does not handle keyboard input**
Problem:    A terminal window does not handle keyboard input.
Solution:   Add terminal_loop().  ":term bash -i" sort of works now.
vim/vim@938783d
de2e86a

**vim-patch:8.0.1411: reading invalid memory with CTRL-W :**
Problem:    Reading invalid memory with CTRL-W :.
Solution:   Correct the command characters. (closes vim/vim#2469)
vim/vim@2efb323

Follow-up from https://github.com/neovim/neovim/pull/9879. I included both patches just to see if vim-patch:8.0.0725 is really N/A such that only the test code from vim-patch:8.0.1411 is useful.

### CODE REVIEW

File: src/nvim/ops.c [hunk 1]
```diff
@@ -153,6 +153,10 @@ int get_op_type(int char1, int char2)
     if (opchars[i][0] == char1 && opchars[i][1] == char2) {
       break;
     }
+    if (i == (int)(sizeof(opchars) / sizeof(char [3]) - 1)) {
```
Comment (justinmk) [inline src/nvim/ops.c]: could use `ARRAY_SIZE`.

        if (i == (int)(ARRAY_SIZE(opchars) - 1)) {
