### PR TITLE
fix(autocmd): 'cmdheight' OptionSet with valid window grids

### LINKED ISSUE #34615: extui: `:tabnext` could crash nvim with cmdheight=0
### Problem

With extui and cmdheight=0, `:tabnext` could crash nvim

Note that the `noswapfile` in the reproducible steps below is only to avoid redundant swapfile generations due to the reproducible crashes.

### Steps to reproduce

nvim --clean -u NONE -c 'set noswapfile' -c "lua require('vim._extui').enable({})" -c 'set cmdheight=0' -p foo bar
:tabnext
@: " maybe twice or more

### Expected behavior

no crash

### Nvim version (nvim -v)

NVIM v0.12.0-dev-657+ga5c55d200b

### Vim (not Nvim) behaves the same?

no

### Operating system/version

NixOS 25.05

### Terminal name/version

kitty 0.42.1 created by Kovid Goyal

### $TERM environment variable

tmux-256color

### Installation

repo

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  OptionSet autocmd emitted with invalid grids after entering
          tabpage with different 'cmdheight'.
Solution: First call `tabpage_check_windows()` before changing 'cmdheight'.
          Add a test that exercises the `vim._extui` cmdline.

Fix #34615

### CODE REVIEW

File: test/functional/ui/cmdline2_spec.lua [hunk 1]
```diff
@@ -0,0 +1,39 @@
+local n = require('test.functional.testnvim')()
```
Comment (justinmk) [inline test/functional/ui/cmdline2_spec.lua:3]: Before I forget, let's add a note like this here and in messages2_spec.lua.

```suggestion
-- Tests for ui2 (protocol-driven UI), which will replace the legacy UI.

local n = require('test.functional.testnvim')()
```

**Review by justinmk — APPROVED** [review]
