### PR TITLE
TUI/background detection: hook into VimEnter event

### LINKED ISSUE #9675: Hangs after TUI background detection
- `nvim --version`: NVIM v0.4.0-dev at 2816bc8620ca373145842641ce77805f4321b2bc
- Vim (version: ) N/A
- Operating system/version: macOS 10.13 and 10.14
- Terminal name/version: iTerm 3.3.20190304-nightly, Kitty 0.13.3, Terminal.app
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

N/A, see below.

### Actual behaviour

Hello,

after commit 246408621c405a6c0f24e2e5cd66e8776eb04fe6 (Merge #9509 'TUI: detect background color') Neovim on macOS started hanging for upwards of a minute when started with a file from a Git repository as an argument.

After disabling plugins, I narrowed it down to GitGutter. However, an issue there (https://github.com/airblade/vim-gitgutter/issues/589) seems to suggest that the issue isn't in GitGutter per se. I bisected Neovim commits, and 246408621c405a6c0f24e2e5cd66e8776eb04fe6 and onwards is broken, everything before that - works fine.

If Neovim (even commits after 246408621c405a6c0f24e2e5cd66e8776eb04fe6) is started with no arguments - and then a Git-tracked file is opened from within - everything, including GitGutter, works fine. It's only the interaction between the terminal background query stalling for some reason, and GitGutter trying to execute an async job at the same time that results in the pseudo hang. If one waits it out, everything works, but it is very inconvenient to do so.

The issue only happens - for me at least - using iTerm and Kitty on macOS. Using Kitty and Konsole on Linux works fine.

Let me know if any other testing is required. Thanks.

### Expected behaviour

Neovim and GitGutter working fine.

### PR DESCRIPTION
**Pull request by justinmk**
If terminal response is received during startup, set 'background' from a nested ["one-shot"](https://github.com/neovim/neovim/pull/9706) (once) VimEnter autocmd.

The previous not-so-clever "self-rescheduling" approach could cause a long delay at startup (event-loop does not make forward progress).

fixes #9675
ref #9509

### CODE REVIEW

**Comment by tex** [comment]
Tested this branch and it does fix the issue. Kitty/NixOS.

File: src/nvim/tui/input.c [hunk 1]
```diff
@@ -357,15 +358,17 @@ static bool handle_forced_escape(TermInput *input)
...
-    // Wait until after startup, so OptionSet is triggered.
-    loop_schedule(&main_loop, event_create(set_bg_deferred, 1, bgvalue));
-    return;
-  }
   if (!option_was_set("bg") && !strequal((char *)p_bg, bgvalue)) {
     // Value differs, apply it.
-    set_option_value("bg", 0L, bgvalue, 0);
-    reset_option_was_set("bg");
+    if (starting) {
+      // Wait until after startup, so OptionSet is triggered.
```
Comment (dm1try) [inline src/nvim/tui/input.c]: > // Wait until after startup, so OptionSet is triggered.

nitpicking, but it is more like *"schedule the bg update, so OptionSet is triggered"* now

**Comment by mcepl** [comment]
Yes! Tested in https://build.opensuse.org/package/show/home:mcepl:neovim/neovim and the delay on startup of the command ``nvim filename`` is gone (or at least it is minimal).

File: src/nvim/tui/input.c (hunk 1 above)
Comment (justinmk) [reply src/nvim/tui/input.c]: shorter is better if it does not confuse.

Comment (dm1try) [reply src/nvim/tui/input.c]: hm, but we do not *wait* for something, we are scheduling relying on the fact that all autocommands run after startup. It depends on the reader of the code though, but someone could be confused.

Comment (justinmk) [reply src/nvim/tui/input.c]: The code is clear , though. Comment shouldn't merely restate what the code already says.

Comment (dm1try) [reply src/nvim/tui/input.c]: > Comment shouldn't merely restate what the code already says.

it does not.
 it says that we do if the editor is not started yet and why.
```c
if(starting){
// defer the update, so Option is triggered`
...
```
and the comment is needed because in the next line we do not have some specific API for schedule the things but have `do_cmdline_cmd` what rarely have being used for this purpose(deferring the things).

but I got your point

**Comment by tacho** [comment]
I have tested it too, and while it no longer hangs, it also no longer correctly reports the background (light/dark). With unpatched Neovim, I get the hang, but after it eventually starts up - background is set correctly to light or dark, depending on my iTerm colorscheme.

With this patch, startup delay is unnoticeable, if any, but background is always set to dark, regardless of the terminal theme. Verified without user init files as well as with.

**Comment by dm1try** [comment]
>  regardless of the terminal theme.

I was unable to reproduce, works as expected in my case(iterm2 Build 3.2.7beta3).
Screen Shot 2019-03-10 at 23 56 39
Screen Shot 2019-03-10 at 23 57 08

**Comment by dm1try** [comment]
I've reproduced ^ using ` nvim -u NORC -c "sleep 5m"` (not sure if this is the same that @tacho met)
Screen Shot 2019-03-11 at 00 30 34
Screen Shot 2019-03-11 at 00 30 50

**Comment by przepompownia** [comment]
Confirmed after building this branch from sources: hanging at start does not occur, while on master is still present.

**Comment by przepompownia** [comment]
`background=dark` on white terminal background also confirmed, unfortunately.

**Comment by justinmk** [comment]
yep there's a bug here. Should be fixed in the next push, took a minute to fix the tests.

**Comment by przepompownia** [comment]
I cannot reproduce the second bug: `:set bg` shows `light`. :+1: 

Thanks! The bug with hanging was present about two weeks.
