### PR TITLE
fix(api): load buffer first on nvim_buf_set_lines

### LINKED ISSUE #8659: nvim_buf_set_lines() doesn't play well with unloaded buffers
- `nvim --version`: v0.3.0
- Vim (version: ) behaves differently? N/A
- Operating system/version: Ubuntu 18.04

### Steps to reproduce using `nvim -u NORC`

I wrote some lua test code to verify that `nvim_buf_set_lines()` will work with a buffer that has been `:bunload`'ed. It doesn't :-( I experienced two incorrect behaviours:

1. A line range such as `0, -1` is always constrained to `0, 1` because internally `normalize_index()` thinks there is only 1 line in the buffer. Attempting to replace all lines in the file will only replace the first line.
2. You should be able to use a single `:undo` to revert the changes from `nvim_buf_set_lines()`, however if the buffer was unloaded then the undo information gets mangled and using :undo puts the buffer in weird states that it never even transitioned through.

You can paste the test code into e.g. `test/functional/api/buffer_spec.lua` to flag both bugs:

    it('set_lines works correctly for unloaded buffers', function()
      -- we'll need to know our bufnr for when it gets unloaded
      local bufnr = buffer('get_number', 0)
      -- replace the buffer contents with these two lines
      buffer('set_lines', bufnr, 0, -1, 1, {'line1', 'line2', 'line3'})
      -- confirm that getting lines works
      eq({'line2', 'line3'}, buffer('get_lines', bufnr, 1, 3, 1))
      -- save the file then unload it
      command('file some-test-file.txt')
      command('write')
      command('new')
      command('bunload '..bufnr)
      -- attempting to get lines now gives empty list
      eq({}, buffer('get_lines', bufnr, 1, 3, 1))
      -- use nvim_buf_set_lines() to override the entire file contents
      buffer('set_lines', bufnr, 0, -1, 1, {'LINE A', 'LINE B'})
      -- open the buffer again
      command('sbuf '..bufnr)
      -- entire file contents should have been replaced
      eq({'LINE A', 'LINE B'}, buffer('get_lines', bufnr, 0, -1, 1)) -- THIS FAILS
      -- undo should put everything back how it was
      command('undo')
      eq({'line1', 'line2', 'line3'}, buffer('get_lines', bufnr, 0, -1, 1)) -- THIS ALSO FAILS
    end)

### Actual behaviour

The test code fails at the lines mentioned.

### Expected behaviour

The test should pass - i.e. `nvim_buf_set_lines()` always works correctly with unloaded buffers. Or possibly `nvim_buf_set_lines()` could just raise an error if the buffer isn't loaded.

### LINKED ISSUE #22670: `nvim_buf_set_lines` does not (fully) load buffer given by `bufnr(..., true)`
### Problem

I'm trying to edit a file that might or might not be opened as a buffer, using `nvim_buf_set_lines`. Unfortunately, unless the buffer is visible in a window, it seems that `nvim_buf_set_lines` will only set the first line, instead of the range provided.
This might be related to [#8659](https://github.com/neovim/neovim/issues/8659), although the test circumstances are slightly different.

### Steps to reproduce

`printf "a\nb\nc" > testfile`
`nvim --clean`
`:lua vim.api.nvim_buf_set_lines(vim.fn.bufnr("testfile", true), 0, 4, false, {})`
`:e testfile` - You will see that only the first line was cleared

### Expected behavior

`nvim_buf_set_lines` should set the lines specified in the range even for buffers that are not opened in a window.
The command above should've cleared the whole file.

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

N/A - Lua API

### Operating system/version

Artix Linux 6.1.12

### Terminal name/version

Alacritty 0.11.0

### $TERM environment variable

alacritty

### Installation

Pacman

### PR DESCRIPTION
**Pull request by glepnir**
load buffer first when buffer is unload in `nvim_buf_set_lines`.

Fix #22670
Fix #8659

### CODE REVIEW

**Review by zeertzjq — COMMENTED** [review]
The test doesn't fail without the fix.

And a similar change should probably be applied to `nvim_buf_set_text` too.

File: test/functional/api/buffer_spec.lua [hunk 1]
```diff
@@ -713,6 +713,18 @@ describe('api/buf', function()
       feed('<c-w>p')
       eq(3, funcs.winnr())
     end)
+
+    it('set_lines on unload buffer #8659 #22670', function()
```
Comment (zeertzjq) [inline test/functional/api/buffer_spec.lua:717]:
```suggestion
    it('set_lines on unloaded buffer #8659 #22670', function()
```

File: test/functional/api/buffer_spec.lua [hunk 2]
```diff
@@ -713,6 +713,18 @@ describe('api/buf', function()
...
+      local bufnr = curbuf('get_number')
+      meths.buf_set_lines(bufnr, 0, -1, false, {'a', 'b', 'c'})
+      meths.buf_set_name(bufnr, 'set_lines')
+      command('write!')
```
Comment (zeertzjq) [inline test/functional/api/buffer_spec.lua:721]:
```suggestion
      finally(function()
        os.remove('set_lines')
      end)
      command('write!')
```
