### PR TITLE
fix(lsp): handle absence of a trailing newline

### LINKED ISSUE #24339: Inlay hints not working if a file does not have a newline at end of file
### Problem

If a file does not have a newline at end of file then inlay hints are not working and rust-analyzer sends an error
message: `rust-analyzer: -32603: Invalid offset`

### Steps to reproduce using "nvim -u minimal_init.lua"

<details>

<summary>Minimal configuration</summary>

```lua
local pattern = 'rust'
local cmd = {'rust-analyzer'}
local root_markers = {'.git', '.editorconfig', 'Cargo.toml'}
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'rust-analyzer',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})

vim.api.nvim_create_autocmd('LspAttach', {
    group = vim.api.nvim_create_augroup('InlayHintsAttach', {}),
    callback = function(args)
      local buf = args.buf
      vim.lsp.inlay_hint(buf, true)
    end,
})
```

</details>

1. Create an executable crate: `cargo new hints`
2. Write some code that should display inlay hints, e.g. `let x = 12;`
3. Delete the newline somehow, I did that using `vscode`
4. Open `main.rs`
5. Observe an error and no inlay hints

### Expected behavior

Working inlay hints and no error message.

### Neovim version (nvim -v)

v0.10.0-dev-664+g0ce391086

### Language server name/version

rust-analyzer 0.3.1583-standalone (2023-07-10)

### Operating system/version

Windows 11, WSL2

### Log file

No log messages produced

### PR DESCRIPTION
**Pull request by faergeek**
Fixes #24339

rust-analyzer sends "Invalid offset" error in such cases. Some other servers handle it specially.

LSP spec mentions that "A range is comparable to a selection in an editor". Most editors don't handle trailing newlines the same way Neovim/Vim does, it's clearly visible if it's present or not. With that in mind it's understandable why sending end position as simply the start of the line after the last one is considered invalid in such cases.

### CODE REVIEW

**Comment by faergeek** [comment]
I didn't even manually test the case when `only_visible` is true and I couldn't figure out how to trigger LspNotify autocommand in tests for pull diagnostics. Should I trigger it manually with `nvim_exec_autocmds` in tests?

**Comment by faergeek** [comment]
Here is the code I want to test

https://github.com/neovim/neovim/blob/f40a109716d7f748dd9e9f70b57e4d0bb285518b/runtime/lua/vim/lsp/diagnostic.lua#L434-L448

**Comment by faergeek** [comment]
I tested `only_visible` case manually with ruby lsp and rubocop. I tried to add a test for that as well, through pull diagnostics codepath, but I can't figure out how to trigger LspNotify callback in tests. I added some primitive logging to confirm that this `nvim_exec_autocmds` is executed:

https://github.com/neovim/neovim/blob/9cadbf1d36b63f53f0de48c8c5ff6c752ff05d70/runtime/lua/vim/lsp.lua#L1587-L1594

But then this callback does not run:

https://github.com/neovim/neovim/blob/9cadbf1d36b63f53f0de48c8c5ff6c752ff05d70/runtime/lua/vim/lsp/diagnostic.lua#L434-L448

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -2172,6 +2172,35 @@ function M.lookup_section(settings, section)
...
 
+--- Converts line range (0-based, end-inclusive) to lsp range,
+--- handles absence of a trailing newline
+---
+---@param bufnr integer
+---@param start_line integer
+---@param end_line integer
+---@param offset_encoding lsp.PositionEncodingKind
+---@return lsp.Range
+local function make_line_range_params(bufnr, start_line, end_line, offset_encoding)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/util.lua:2183]: Related discussion https://github.com/neovim/neovim/pull/24499#issuecomment-1659006873

We need a `Position` and `Range` interface that can convert to/from the various indexing conventions.

**Review by mfussenegger — APPROVED** [review]

**Comment by justinmk** [comment]
Could this failure on master be related?

```
FAILED   test/functional/plugin/lsp_spec.lua @ 278: LSP basic_init test should detach buffer in response to nvim_buf_detach
test/functional/plugin/lsp_spec.lua:301: exit code
Expected objects to be the same.
Passed in:
(number) 101
Expected:
(number) 0

stack traceback:
	test/functional/plugin/lsp_spec.lua:301: in function 'on_exit'
	test/functional/plugin/lsp/helpers.lua:167: in function 'test_rpc_server'
	test/functional/plugin/lsp_spec.lua:284: in function <test/functional/plugin/lsp_spec.lua:278>
```

**Comment by zeertzjq** [comment]
No
