### PR TITLE
fix(rpc): handle additional cases when identifying loopback

### LINKED ISSUE #30408: server -> client connecting to its own pipe address deadlocks under wrong XDG configuration
### Problem

Running the test [server -> client connecting to its own pipe address does not deadlock](https://github.com/muniter/neovim/blob/5792546777332361a9ac49107e46149c703de90e/test/functional/api/server_requests_spec.lua#L387) deadlocks on macos when the environment has `XDG_RUNTIME_DIR=/tmp`.

The value is incorrect, but It still shouldn't deadlock.

### Steps to reproduce

```
export XDG_RUNTIME_DIR=/tmp
TEST_FILE=test/functional/api/server_requests_spec.lua TEST_FILTER='deadlock' make test
```

### Expected behavior

Test passes, it does not deadlock.

### Neovim version (nvim -v)

v0.11.0-dev-724+g439d03174

### Vim (not Nvim) behaves the same?

doesn't apply

### Operating system/version

macos 14.6.1

### Terminal name/version

Kitty 0.36.2

### $TERM environment variable

xterm-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by MeanderingProgrammer**
fixes: https://github.com/neovim/neovim/issues/30408

Problem:

On MacOS it is a relatively common pattern to set XDG_RUNTIME_DIR under `/tmp` or `/var`. Both of these are symlinks to `/private/tmp` and `/private/var`. When checking for loopback the input address is normalized using `fix_fname`, however this is not applied to the addresses of the sockets. As a result of one address being normalized and the other not the comparison would fail.

Solution:

Normalize both sides of the comparison using `fix_fname`.

### CODE REVIEW

**Comment by justinmk** [comment]
Nice, thanks! Nit: could use `strequal` instead of `strcmp`.

We really should have a `path_equal` function to compare paths. We have `pathcmp` but I don't think it fully normalizes the paths. However it looks like `path_full_compare` may actually do some normalization...

File: src/nvim/msgpack_rpc/server.c [hunk 1]
```diff
@@ -139,7 +140,10 @@ char *server_address_new(const char *name)
 bool server_owns_pipe_address(const char *path)
 {
   for (int i = 0; i < watchers.ga_len; i++) {
-    if (!strcmp(path, ((SocketWatcher **)watchers.ga_data)[i]->addr)) {
+    char *addr = fix_fname(((SocketWatcher **)watchers.ga_data)[i]->addr);
+    bool same = strcmp(path, addr) == 0;
+    xfree(addr);
```
Comment (justinmk) [inline src/nvim/msgpack_rpc/server.c]: Although there's currently only 1 caller to `server_owns_pipe_address`, this makes an assumption about `path`, right? Does it work to use `path_full_compare` instead?

Comment (MeanderingProgrammer) [reply src/nvim/msgpack_rpc/server.c]: > this makes an assumption about path, right? 

Yeah there's a comment about that above the method `The argument must already be resolved to an absolute path!`, but normalizing everything internally is probably better.

> Does it work to use path_full_compare instead?

I'm not super familiar with C, all the methods here use `const char *` while `path_full_compare` uses `char *const`, is it safe to convert between the 2, I'm unsure when one would use one over the other.

Comment (MeanderingProgrammer) [reply src/nvim/msgpack_rpc/server.c]: ~Updated the PR to normalize the input of `server_owns_pipe_address` internally and replaced `strcmp` with `strequal`.~

~I don't think `path_full_compare` can be used here without some more refactoring. Based on what I've read the two `char*` types are not really interchangeable. I could definitely be missing something here though.~

Comment (MeanderingProgrammer) [reply src/nvim/msgpack_rpc/server.c]: ~Sorry for the multiple updates, I was able to get `path_full_compare` to work after modifying a couple function signatures, to the best of knowledge these were all safe changes to make but LMK if you have any concerns.~

**Comment by MeanderingProgrammer** [comment]
I was able to use `path_full_compare` locally and it passed most CI tests but would consistently fail the macos zig build & windows would now hang on the deadlock test: https://github.com/neovim/neovim/actions/runs/18387510468.

I'm not completely sure why, more so the macos zig build, the test that started failing seems pretty unrelated to any of these changes. Windows hanging could potentially be an issue with the inode comparison logic, or maybe something going on in the test environment, but also not entirely sure.

So I went back to using `fix_fname` to normalize the paths and compare.

**Comment by justinmk** [comment]
Thanks for looking into this!
