### PR TITLE
fix(ui): send multigrid message position and size when the UI is refreshed

### LINKED ISSUE #30581: multigrid UI: wrong command line position when multigrid UI reconnects
### Problem

When a multigrid UI reconnects, the command line is at the top of the screen and invisible.

### Steps to reproduce

1. Start a server `nvim --headless --listen /tmp/nvim.socket`
2. Connect with a multigrid UI like Neovide `neovide --server /tmp/nvim.socket`
3. Disconnect from the server `:call chanclose(nvim_list_uis()[0].chan)`
4. Reconnect  `neovide --server /tmp/nvim.socket`
5. Press `:` to enter command mode, and type something

Observe that the cursor is at the top, and the typed text is invisible. The code completion menu on the other hand is in the correct place.

image

### Expected behavior

The UI should work like normal.

### Nvim version (nvim -v)

0.10.1 and latest master

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

Neovide 0.13.3

### $TERM environment variable

N/A

### Installation

pacman

### PR DESCRIPTION
**Pull request by fredizzimo**
### Problem

The message grid position and size were not sent when a multigrid UI attaches, which causes it to show up in the wrong location. This occurs in at least two different situations
1. When a multigrid ui reattaches after first disconnecting
2. When nvim is started in `--headless` mode and a multigrid UI is attached

### Solution
Send the message position and size when the UI is refreshed. This might send too often, but I think it's safer to do that way, since it didn't seem to work when calling it from the attach function.

* fixes https://github.com/neovim/neovim/issues/30581

### CODE REVIEW

**Comment by fredizzimo** [comment]
I renamed the function to be consistent with that of https://github.com/neovim/neovim/pull/32691

Is there anything more that needs to be done to get this simple fix merged, so that my more complex PRs can be reviewed?

**Comment by fredizzimo** [comment]
This has now failed in many strange and different ways in the CI, but as far as I can tell, everything is unrelated. For example the latest failure is a memory leak in the messagepack code. But it's failing in the TUI tests, which have not been touched and does not even use multigrid, so they should be totally unaffected by the code.

```
==================== File /home/runner/work/neovim/neovim/build/log/asan.22731 ====================
= 
= =================================================================
= ==22731==ERROR: LeakSanitizer: detected memory leaks
= 
= Direct leak of 4096 byte(s) in 1 object(s) allocated from:
=     #0 0x55d197a49d93 in malloc (/home/runner/work/neovim/neovim/build/bin/nvim+0xcfcd93) (BuildId: 3eb2081a83cdb15a67f12a324561e28b4730b5dc)
=     #1 0x55d1986948b4 in try_malloc /home/runner/work/neovim/neovim/src/nvim/memory.c:98:15
=     #2 0x55d198694aa4 in xmalloc /home/runner/work/neovim/neovim/src/nvim/memory.c:132:15
=     #3 0x55d198696c6d in alloc_block /home/runner/work/neovim/neovim/src/nvim/memory.c:611:12
=     #4 0x55d198696d19 in arena_alloc_block /home/runner/work/neovim/neovim/src/nvim/memory.c:618:20
=     #5 0x55d198697023 in arena_alloc /home/runner/work/neovim/neovim/src/nvim/memory.c:640:5
=     #6 0x55d198761fe2 in api_parse_enter /home/runner/work/neovim/neovim/src/nvim/msgpack_rpc/unpacker.c:163:5
=     #7 0x55d19916df92 in mpack_parse_tok /home/runner/work/neovim/neovim/src/mpack/object.c:56:3
=     #8 0x55d1991706bb in mpack_parse /home/runner/work/neovim/neovim/src/mpack/object.c:82:16
=     #9 0x55d1987650a5 in unpacker_advance /home/runner/work/neovim/neovim/src/nvim/msgpack_rpc/unpacker.c:345:12
=     #10 0x55d19874dc29 in parse_msgpack /home/runner/work/neovim/neovim/src/nvim/msgpack_rpc/channel.c:248:10
=     #11 0x55d198744707 in receive_msgpack /home/runner/work/neovim/neovim/src/nvim/msgpack_rpc/channel.c:217:5
=     #12 0x55d19814a821 in read_event /home/runner/work/neovim/neovim/src/nvim/event/rstream.c:180:23
=     #13 0x55d19814a271 in invoke_read_cb /home/runner/work/neovim/neovim/src/nvim/event/rstream.c:233:3
=     #14 0x55d198147784 in read_cb /home/runner/work/neovim/neovim/src/nvim/event/rstream.c:135:3
=     #15 0x55d19929b988 in uv__read /home/runner/work/neovim/neovim/.deps/build/src/libuv/src/unix/stream.c:1148:7
=     #16 0x55d19929989a in uv__stream_io /home/runner/work/neovim/neovim/.deps/build/src/libuv/src/unix/stream.c:1208:5
=     #17 0x55d1992a3a7f in uv__io_poll /home/runner/work/neovim/neovim/.deps/build/src/libuv/src/unix/linux.c:1565:11
=     #18 0x55d199289e37 in uv_run /home/runner/work/neovim/neovim/.deps/build/src/libuv/src/unix/core.c:460:5
=     #19 0x55d1981365dd in loop_uv_run /home/runner/work/neovim/neovim/src/nvim/event/loop.c:61:3
=     #20 0x55d198136244 in loop_poll_events /home/runner/work/neovim/neovim/src/nvim/event/loop.c:82:26
=     #21 0x55d197c01845 in remote_ui_wait_for_attach /home/runner/work/neovim/neovim/src/nvim/api/ui.c:111:5
=     #22 0x55d1984efe83 in main /home/runner/work/neovim/neovim/src/nvim/main.c:401:5
=     #23 0x7f9761a2a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
=     #24 0x7f9761a2a28a in __libc_start_main csu/../csu/libc-start.c:360:3
=     #25 0x55d1979a9f64 in _start (/home/runner/work/neovim/neovim/build/bin/nvim+0xc5cf64) (BuildId: 3eb2081a83cdb15a67f12a324561e28b4730b5dc)
= 
= SUMMARY: AddressSanitizer: 4096 byte(s) leaked in 1 allocation(s).
===================================================================================================
nan ms test/testutil.lua:384: Found runtime errors in logfile(s): /home/runner/work/neovim/neovim/build/log/asan.22731

stack traceback:
	test/testutil.lua:384: in function 'check_logs'
	test/functional/testnvim.lua:1012: in function <test/functional/testnvim.lua:1011>

```

A previous test failed in the TUI paste test https://github.com/neovim/neovim/actions/runs/14018316724/job/39246851420#step:10:6648

**Comment by bfredl** [comment]
ye, that's very likely unrelated.

File: test/functional/ui/multigrid_spec.lua [hunk 1]
```diff
@@ -2857,4 +2857,71 @@ describe('ext_multigrid', function()
       }})
     end)
   end)
+
+  it('message grid is shown at the correct position remote re-attach', function()
```
Comment (justinmk) [inline test/functional/ui/multigrid_spec.lua:2861]: should this say "_after_ remote reattach"?
