### PR TITLE
[RDY] Keep unnamed register on restart

### LINKED ISSUE #4645: Unnamed register is overwritten with "0 value on restart
- Neovim version: NVIM v0.1.5-24-gef205c3
- Vim behaves differently? Vim version:  7.4.1556
- Operating system/version: FreeBSD 10.2-RELEASE (GENERIC) #0 r286666: Wed Aug 12 15:26:37 UTC 2015
- Terminal name/version:  iTerm2 Build 2.9.20160313
- `$TERM`: xterm-256color
### Actual behaviour

The unnamed register is set to "0 on restart of nvim.
### Expected behaviour

The unnamed register is preserved on restart on nvim. i.e. If the last operation done before existing is a delete operation, then on restart the unnamed register is set to "1 value. In other word, "" should be preserved on restart.
### Steps to reproduce using `nvim -u NORC`

```
0. nvim -u NORC
1. go into INSERT mode, type: cut
2. go into NORMAL mode, type: dd
3. exit (:q!)
4. execute nvim -u NORC again
5. type: :reg "
```

Expected: 

```
:reg
--- Registers ---
""   cut^J
"1  cut^J
```

Actual:

```
:reg
--- Registers ---
"1   cut^J
```

### PR DESCRIPTION
**Pull request by AdnoC**
Resolves https://github.com/neovim/neovim/issues/4645

Sets the unnamed register to the last-used one.

Adds a field `is_unnamed` to the ShaDa file for registers and sets the field to whatever register the unnamed register is set to.

Also added an option to `setreg` that sets the unnamed register to the set register (this was needed for testing).

~~Does this by finding the register with the most recent timestamp. If two registers have the same timestamp the first loaded one is used as the unnamed register.~~

~~I did it this way since I didn't really want to mess to much with the ShaDa file.~~

### CODE REVIEW

**Comment by jamessan** [comment]
Looks good to me.  I think @ZyX-I did a lot of the shada work, so his input would be useful.

File: test/functional/shada/registers_spec.lua [hunk 1]
```diff
@@ -1,6 +1,7 @@
 -- ShaDa registers saving/reading support
 local helpers = require('test.functional.helpers')
-local nvim_command, funcs, eq = helpers.command, helpers.funcs, helpers.eq
+local nvim_command, funcs, eq, execute = helpers.command, helpers.funcs,
+   helpers.eq, helpers.execute
```
Comment (ZyX-I) [inline test/functional/shada/registers_spec.lua]: Remove `execute`. There is `nvim_command`, use it.

File: src/nvim/ops.c [hunk 2]
```diff
@@ -5704,3 +5704,19 @@ const yankreg_T *op_register_get(const char name)
   }
   return &y_regs[i];
 }
+
+/// Set the previous yank register
+///
+/// @param[in]  name  Register name.
+///
+/// @return true on success, false on failure.
+bool op_previous_register_set(const char name)
```
Comment (ZyX-I) [inline src/nvim/ops.c]: That is better named `op_register_set_previous`.

**Comment by ZyX-I** [comment]
This actually changes the behaviour: Vim marks some register as the previous one (and so under some circumstances there may be no `"` set: e.g.

    vim -u NONE -i /tmp/viminfo -N --cmd 'call setreg("1", ["abc"])' --cmd 'q!'

). This variant always sets `"` to something, and that something may be different from Vim. Variant that does the same thing that Vim does is something like

```Patch
diff --git a/src/nvim/shada.c b/src/nvim/shada.c
index 32a02b0..6d4f2fd 100644
--- a/src/nvim/shada.c
+++ b/src/nvim/shada.c
@@ -103,6 +103,7 @@ KHASH_SET_INIT_STR(strset)
 #define REG_KEY_TYPE "rt"
 #define REG_KEY_WIDTH "rw"
 #define REG_KEY_CONTENTS "rc"
+#define REG_KEY_UNNAMED "ru"
 
 #define KEY_LNUM "l"
 #define KEY_COL "c"
@@ -287,6 +288,7 @@ typedef struct {
       char **contents;
       size_t contents_size;
       size_t width;
+      bool is_unnamed;
       dict_T *additional_data;
     } reg;
     struct global_var {
@@ -479,6 +481,7 @@ static const ShadaEntry sd_default_values[] = {
           .contents = NULL,
           .contents_size = 0,
           .width = 0,
+          .is_unnamed = false,
           .additional_data = NULL),
   DEF_SDE(Variable, global_var,
           .name = NULL,
@@ -1427,7 +1430,7 @@ static void shada_read(ShaDaReadDef *const sd_reader, const int flags)
           .y_width = (colnr_T) cur_entry.data.reg.width,
           .timestamp = cur_entry.timestamp,
           .additional_data = cur_entry.data.reg.additional_data,
-        })) {
+        }, cur_entry.data.reg.is_unnamed)) {
           shada_free_shada_entry(&cur_entry);
         }
         // Do not free shada entry: its allocated memory was saved above.
@@ -1868,6 +1871,7 @@ static ShaDaWriteResult shada_pack_entry(msgpack_packer *const packer,
           2  // Register contents and name
           + ONE_IF_NOT_DEFAULT(entry, reg.type)
           + ONE_IF_NOT_DEFAULT(entry, reg.width)
+          + ONE_IF_NOT_DEFAULT(entry, reg.is_unnamed)
           // Additional entries, if any:
           + (size_t) (entry.data.reg.additional_data == NULL
                       ? 0
@@ -1888,6 +1892,14 @@ static ShaDaWriteResult shada_pack_entry(msgpack_packer *const packer,
         PACK_STATIC_STR(REG_KEY_WIDTH);
         msgpack_pack_uint64(spacker, (uint64_t) entry.data.reg.width);
       }
+      if (!CHECK_DEFAULT(entry, reg.is_unnamed)) {
+        PACK_STATIC_STR(REG_KEY_UNNAMED);
+        if (entry.data.reg.is_unnamed) {
+          msgpack_pack_true(spacker);
+        } else {
+          msgpack_pack_false(spacker);
+        }
+      }
       DUMP_ADDITIONAL_DATA(entry.data.reg.additional_data, "register item");
       break;
     }
@@ -2741,7 +2753,8 @@ static ShaDaWriteResult shada_write(ShaDaWriteDef *const sd_writer,
     do {
       yankreg_T reg;
       char name = NUL;
-      reg_iter = op_register_iter(reg_iter, &name, &reg);
+      bool is_unnamed = false;
+      reg_iter = op_register_iter(reg_iter, &name, &reg, &is_unnamed);
       if (name == NUL) {
         break;
       }
@@ -2761,6 +2774,7 @@ static ShaDaWriteResult shada_write(ShaDaWriteDef *const sd_writer,
               .width = (size_t) (reg.y_type == MBLOCK ? reg.y_width : 0),
               .additional_data = reg.additional_data,
               .name = name,
+              .is_unnamed = is_unnamed,
             }
           }
         }
@@ -3769,6 +3783,7 @@ shada_read_next_item_start:
             entry->data.reg.contents[i] = BIN_CONVERTED(arr.ptr[i].via.bin);
           }
         }
+        BOOLEAN_KEY("register", REG_KEY_UNNAMED, entry->data.reg.is_unnamed)
         TYPED_KEY("register", REG_KEY_TYPE, "an unsigned integer",
                   entry->data.reg.type, POSITIVE_INTEGER, u64, TOU8)
         TYPED_KEY("register", KEY_NAME_CHAR, "an unsigned integer",
diff --git a/runtime/autoload/shada.vim b/runtime/autoload/shada.vim
index 9be85b6..e885e16 100644
--- a/runtime/autoload/shada.vim
+++ b/runtime/autoload/shada.vim
@@ -45,7 +45,7 @@ call map(copy(s:SHADA_ENTRY_NAMES),
 let s:SHADA_MAP_ENTRIES = {
   \'search_pattern': ['sp', 'sh', 'ss', 'sb', 'sm', 'sc', 'sl', 'se', 'so',
   \                   'su'],
-  \'register': ['n', 'rc', 'rw', 'rt'],
+  \'register': ['n', 'rc', 'rw', 'rt', 'ru'],
   \'global_mark': ['n', 'f', 'l', 'c'],
   \'local_mark': ['f', 'n', 'l', 'c'],
   \'jump': ['f', 'l', 'c'],
@@ -139,6 +139,7 @@ let s:SHADA_STANDARD_KEYS = {
   \'rt': ['type', 'regtype', s:SHADA_ENUMS.regtype.CHARACTERWISE],
   \'rw': ['block width', 'uint', 0],
   \'rc': ['contents', 'binarray', s:SHADA_REQUIRED],
+  \'ru': ['is unnamed', 'boolean', g:msgpack#false],
   \'n':  ['name', 'intchar', char2nr('"')],
   \'l':  ['line number', 'uint', 1],
   \'c':  ['column', 'uint', 0],
```

(I did not provide required changes to tests and ops.c).

**Comment by AdnoC** [comment]
Thanks@ZyX-I. I would never have figured out how to add that to the ShaDa file myself.

**Comment by ZyX-I** [comment]
Also needs documentation update: some file in runtime/doc contains complete ShaDa file description.

File: test/functional/plugin/shada_spec.lua [hunk 3]
```diff
@@ -715,6 +722,7 @@ describe('In autoload/shada.vim', function()
         '  # Unexpected enum value: expected one of 0 (CHARACTERWISE), '
         .. '1 (LINEWISE), 2 (BLOCKWISE)',
         '  + rt   type         10',
+        '  + ru   is_unnamed   FALSE',
```
Comment (ZyX-I) [inline test/functional/plugin/shada_spec.lua]: Note what tests are testing. Just adding this line to the failing tests is not enough.

File: src/nvim/ops.c [hunk 4]
```diff
@@ -5704,3 +5710,19 @@ const yankreg_T *op_register_get(const char name)
...
+bool op_register_set_previous(const char name)
+{
+  int i = op_reg_index(name);
+  if (i == -1) {
+    return false;
+  }
+
+  y_previous = &y_regs[i];
+  return true;
+}
```
Comment (ZyX-I) [inline src/nvim/ops.c]: This function is no longer needed.

File: test/functional/shada/registers_spec.lua [hunk 5]
```diff
@@ -160,4 +160,16 @@ describe('ShaDa support code', function()
...
+  function()
+    setreg('0', {'zero'}, 'c')
+    setreg('1', {'one'}, 'cu')
+    setreg('2', {'two'}, 'c')
+    nvim_command('qall')
+    reset()
+    eq({{'zero'}, 'v'}, getreg('0'))
+    eq({{'one'}, 'v'}, getreg('1'))
+    eq({{'one'}, 'v'}, getreg('"'))
+  end)
```
Comment (ZyX-I) [inline test/functional/shada/registers_spec.lua]: Missing test where unnamed register is not set and thus not restored.

File: test/functional/plugin/shada_spec.lua (hunk 3 above)
Comment (ZyX-I) [inline test/functional/plugin/shada_spec.lua]: Specifically I remember that I check each and every possible key with unexpected type. Also a test where header contains every single key which is defined for any kind of entry. And a test where header contains every single key which is defined for any kind of entry, but with value of another type.

File: src/nvim/eval.c [hunk 6]
```diff
@@ -14755,6 +14757,9 @@ static void f_setreg(typval_T *argvars, typval_T *rettv)
           --stropt;
         }
         break;
+      case 'u': case '"':
```
Comment (ZyX-I) [inline src/nvim/eval.c]: Different `case`s should be on different lines.

File: test/functional/plugin/shada_spec.lua (hunk 3 above)
Comment (ZyX-I) [inline test/functional/plugin/shada_spec.lua]: Also there are register entry tests which a) contain each key value equal to default one and b) contain each key value *not* equal to default (but yet with a correct type).

**Comment by AdnoC** [comment]
This fails Travis because of a linting error.

The `shada_write` function in [shada.c](https://github.com/AdnoC/neovim/blob/keep-default-register/src/nvim/shada.c#L2422) is over 500 lines long. However, it was originally 499 lines; I only added 3 lines.

**Comment by ZyX-I** [comment]
@AdnoC This means you should move something out. I have done this a few times, this is why it is close to 500.

**Comment by AdnoC** [comment]
Ummmm... I'm not sure what to do with the log output of the failed Travis job \([this one](https://travis-ci.org/neovim/neovim/jobs/128399189)\). It looks like test49.vim failed due to an error. Because of something?

There aren't any problems when I run `make` inside of src/nvim/testdir (I'm running Mac OS X 10.11.4) and I don't really know how to debug the error in the Travis log.

**Comment by justinmk** [comment]
@ZyX-I Anything pending here?

**Comment by justinmk** [comment]
@AdnoC Would you be able to rebase (or at least merge-resolve) this?

File: runtime/doc/starting.txt [hunk 7]
```diff
@@ -1265,29 +1265,32 @@ exactly four MessagePack objects:
...
+                       rc   Array of binary  N/A   Register contents.  Each
+                                                   entry in the array
+                                                   represents its own line.
+                                                   NUL characters inside the
+                                                   line should be represented
+                                                   as NL according to
+                                                   |NL-used-for-Nul|.
+                       ru   Boolean          false Unnamed register. If this
+                                                   is what the unnamed
+                                                   register is set to.
```
Comment (ZyX-I) [inline runtime/doc/starting.txt]: Strange sentence, needs to be fixed.

File: src/nvim/ops.c [hunk 8]
```diff
@@ -5732,3 +5738,19 @@ const yankreg_T *op_register_get(const char name)
   }
   return &y_regs[i];
 }
+
+/// Set the previous yank register
+///
+/// @param[in]  name  Register name.
+///
+/// @return true on success, false on failure.
+bool op_register_set_previous(const char name)
```
Comment (ZyX-I) [inline src/nvim/ops.c]: FUNC_ATTR_PURE FUNC_ATTR_WARN_UNUSED_RESULT

File: src/nvim/ops.c [hunk 9]
```diff
@@ -5704,18 +5705,23 @@ size_t op_register_amount(void)
 
 /// Set register to a given value
 ///
-/// @param[in]  name  Register name.
-/// @param[in]  reg   Register value.
```
Comment (ZyX-I) [inline src/nvim/ops.c]: Better save the previous line and make this line have one *less* space: aligning parameter name descriptions makes diffs larger and requires more work (I mean, to reformat if needed), so I no longer do this. AFAIK most other contributors do neither.

File: src/nvim/shada.c [hunk 10]
```diff
@@ -287,6 +288,7 @@ typedef struct {
       char **contents;
       size_t contents_size;
       size_t width;
+      bool is_unnamed;
```
Comment (ZyX-I) [inline src/nvim/shada.c]: AFAIK this better be placed after `char`. Here it increases size by `sizeof(void *)` (next pointer must be aligned), but putting it after `char` while both `char` and `bool` do not require to be aligned should not even alter the total size of the `struct reg`.

File: src/nvim/shada.c [hunk 11]
```diff
@@ -2402,6 +2413,46 @@ static inline ShaDaWriteResult shada_read_when_writing(
   return ret;
 }
 
+/// Initializes registers for writing to the ShaDa file
```
Comment (ZyX-I) [inline src/nvim/shada.c]: “Initialize”, not “initializes”.

File: src/nvim/shada.c [hunk 12]
```diff
@@ -2402,6 +2413,46 @@ static inline ShaDaWriteResult shada_read_when_writing(
...
+///
+/// @param[in]  wms  The WriteMergerState used when writing.
+/// @param[in]  max_reg_lines The maximum number of register lines.
```
Comment (ZyX-I) [inline src/nvim/shada.c]: Too few spaces before `The`.

File: src/nvim/shada.c [hunk 13]
```diff
@@ -2402,6 +2413,46 @@ static inline ShaDaWriteResult shada_read_when_writing(
...
+static void shada_initialize_registers(WriteMergerState *const wms,
+                                       int max_reg_lines) {
```
Comment (ZyX-I) [inline src/nvim/shada.c]: Should be

```C
static inline void shada_initialize_registers(WriteMergerState *const wms
                                                  const int max_reg_lines)
  FUNC_ATTR_NONNULL_ALL FUNC_ATTR_ALWAYS_INLINE
{
```

: missing inlining (optional, but better have it), NONNULL_ALL attribute and `{` must be on its own line.

File: test/functional/plugin/shada_spec.lua [hunk 14]
```diff
@@ -622,6 +622,7 @@ describe('In autoload/shada.vim', function()
         '  # Required key missing: rc',
```
Comment (ZyX-I) [inline test/functional/plugin/shada_spec.lua]: > …
> Also a test where header contains every single key which is defined for any kind of entry.
> And a test where header contains every single key which is defined for any kind of entry, but with value of another type.

Cannot find the third (guess I was wrong: next check looks like it, but has different purpose and less keys), but the second is on line 173.

**Review by ZyX-I — CHANGES_REQUESTED** [review]

File: src/nvim/shada.c (hunk 10 above)
Comment (jamessan) [inline src/nvim/shada.c]: It doesn't look like all of the other structs are optimally packed either.

**Comment by AdnoC** [comment]
@jamessan if this pull request is still usefull I'll work on this when I get home.

Wish I hadn't forgotten about this PR, I really need to configure my Github alert settings.

**Comment by jamessan** [comment]
> if this pull request is still usefull I'll work on this when I get home.

Yes, it's definitely still useful.  I've been meaning to get back to this, but haven't had time.

File: test/functional/plugin/shada_spec.lua (hunk 3 above)
Comment (AdnoC) [inline test/functional/plugin/shada_spec.lua]: What exactly do I need to add for these tests? Is it that I need to test that it errors correctly for each of the non-boolean messagepack types? I only had one with an incorrect type (passed an int instead of a boolean), so should I add more?

I can't find the  case where the values of each key are the default. Can you post the line number?

File: test/functional/plugin/shada_spec.lua (hunk 14 above)
Comment (AdnoC) [inline test/functional/plugin/shada_spec.lua]: ?

File: src/nvim/ops.c (hunk 8 above)
Comment (AdnoC) [inline src/nvim/ops.c]: If we warn on unused result, would it be a good idea to print an error message if it fails? I made it return a bool mainly for the sake of completeness.

File: src/nvim/shada.c (hunk 13 above)
Comment (AdnoC) [inline src/nvim/shada.c]: When I add `FUNC_ATTR_ALWAYS_INLINE` the compiler gives a warning ` always_inline function might not be inlinable [-Wattributes]`

File: src/nvim/ops.c (hunk 8 above)
Comment (AdnoC) [inline src/nvim/ops.c]: Also, it isn't a pure function. It modifies the global variable `y_previous`. When I compiled with `FUNC_ATTR_PURE` it never set `y_previous`. In fact, in gdb it just skipped over calling the function (since I wasn't using the result the compiler probably optimized it away. No reason to call a pure function if you aren't going to use it's return value after all).

File: test/functional/shada/registers_spec.lua (hunk 5 above)
Comment (AdnoC) [inline test/functional/shada/registers_spec.lua]: Isn't that what the test directly above it does?

File: src/nvim/ops.c (hunk 8 above)
Comment (ZyX-I) [inline src/nvim/ops.c]: I see. Why this is not void?

File: test/functional/plugin/shada_spec.lua (hunk 14 above)
Comment (ZyX-I) [inline test/functional/plugin/shada_spec.lua]: ??

**Comment by AdnoC** [comment]
So I rebased off of master and fixed all the conflicts. I made most of the requested changes. There are 2 changes I commented on asking for clarity on what was being requested. One change (adding `FUNC_ATTR_PURE` to a function that modifies global state) didn't make sense so I didn't add it.

File: test/functional/shada/registers_spec.lua (hunk 5 above)
Comment (ZyX-I) [inline test/functional/shada/registers_spec.lua]: All tests here test that there something in unnamed register. This does not look like “not set”.

File: src/nvim/eval.c [hunk 15]
```diff
@@ -14880,7 +14880,9 @@ static void f_setreg(typval_T *argvars, typval_T *rettv, FunPtr fptr)
   rettv->vval.v_number = 0;
 
   if (set_unnamed) {
-    op_register_set_previous(regname);
+    if (!op_register_set_previous(regname)) {
+      EMSG("Unable to set previous yank register");
```
Comment (ZyX-I) [inline src/nvim/eval.c]: Missing error number. Need to be something like `E5xxx`, one of the unoccupied. And I would suggest using `emsgf("E5542: Unable to set previous yank register to '%c' (<%02x>)", regname, (unsigned)regname)`: as far as I understand `regname` is the only possible reason of the inabliity so this variant will provide all needed details. (Though `(<%02x>)` is probably not needed, but I do not remember how different non-printable characters will work there.)

Comment (ZyX-I) [inline src/nvim/eval.c]: Oops, both missing the translation: `_("E5542: …")`.

File: test/functional/shada/registers_spec.lua (hunk 5 above)
Comment (AdnoC) [inline test/functional/shada/registers_spec.lua]: This matches the behavior in Vim as far as I can tell. Doing:

```VimL
call setreg('0', 'This is in reg 0', 'c')
echo getreg('"')
call setreg('3', 'This is in reg 3', 'c')
echo getreg('"')
```

Results in `This is in reg 0` being printed twice.

While I haven't tested the hypothetical case where the viminfo/shada file has something in register `0` but no info on the unnamed register, that won't occur and make a difference unless someone manually edits the file. I have the feeling that the behavior should be the same.

Comment (ZyX-I) [inline test/functional/shada/registers_spec.lua]: Just don’t do `setreg('0')`. `setreg('3')` does not set `'"'`.

Comment (ZyX-I) [inline test/functional/shada/registers_spec.lua]: The point is that you check what would be done if there are some registers stored in a ShaDa file, but among them there is no one linked with unnamed register. This is achieved by setting `'3'` without setting anything else. Or setting `'a'`. Better set both though.

File: src/nvim/eval.c [hunk 16]
```diff
@@ -14820,6 +14822,10 @@ static void f_setreg(typval_T *argvars, typval_T *rettv, FunPtr fptr)
           }
           break;
         }
+        case 'u': case '"': { // unnamed register
```
Comment (ZyX-I) [inline src/nvim/eval.c]: Two spaces before the comment or it would fail linter.

File: test/functional/shada/registers_spec.lua (hunk 5 above)
Comment (AdnoC) [inline test/functional/shada/registers_spec.lua]: If the unnamed register isn't set and nothing is stored in register `0`, it will be blank regardless of what the other registers are set to, just like Vim.

Comment (AdnoC) [inline test/functional/shada/registers_spec.lua]: Ah. You want a test to test that.

File: src/nvim/eval.c [hunk 17]
```diff
@@ -14872,6 +14878,12 @@ static void f_setreg(typval_T *argvars, typval_T *rettv, FunPtr fptr)
                           append, yank_type, block_len);
   }
   rettv->vval.v_number = 0;
+
+  if (set_unnamed) {
+    if (!op_register_set_previous(regname)) {
+      EMSG("Unable to set previous yank register");
```
Comment (ZyX-I) [inline src/nvim/eval.c]: And also note that if you have error you need a test where error is checked unless it is too hard (“too hard” mostly applies to FS errors and races). I have seen lots of bugs in error handling code just because it was not tested; some appeared after the refactoring which did not intend to change functionality.

File: src/nvim/shada.c [hunk 18]
```diff
@@ -1800,6 +1803,14 @@ static ShaDaWriteResult shada_pack_entry(msgpack_packer *const packer,
         PACK_STATIC_STR(REG_KEY_WIDTH);
         msgpack_pack_uint64(spacker, (uint64_t) entry.data.reg.width);
       }
+      if (!CHECK_DEFAULT(entry, reg.is_unnamed)) {
```
Comment (ZyX-I) [inline src/nvim/shada.c]: You have not specified the default. Currently it works only because when using `{ .attr = value }` syntax if some `.attr` is missing it is initialized with zeroes. Search for `DEF_SDE(Register` above.

File: src/nvim/ops.c (hunk 8 above)
Comment (AdnoC) [inline src/nvim/ops.c]: Because it can fail (if `name` is an invalid register name) and for completeness' sake I wanted it to communicate that.

File: src/nvim/eval.c (hunk 17 above)
Comment (AdnoC) [inline src/nvim/eval.c]: Thinking about this more, `f_setreg` already prints an error in the case where `op_register_set_previous` would fail (when `regname` isn't a valid name it errors with `E354`). So it would make sense to discard `op_register_set_previous`'s result and not print a separate error message.

File: src/nvim/shada.c (hunk 18 above)
Comment (AdnoC) [inline src/nvim/shada.c]: Added a default value.

File: src/nvim/shada.c [hunk 19]
```diff
@@ -2318,6 +2330,48 @@ static inline void add_search_pattern(PossiblyFreedShadaEntry *const ret_pse,
...
+      continue;
+    }
+    wms->registers[op_reg_index(name)] = (PossiblyFreedShadaEntry) {
+      .can_free_entry = false,
+      .data = {
+        .type = kSDItemRegister,
+        .timestamp = reg.timestamp,
+        .data = {
+          .reg = {
+            .contents = (char **) reg.y_array,
```
Comment (ZyX-I) [inline src/nvim/shada.c]: This would not pass linter either: need no space after a cast. Note that file was written before linter check in question was introduced and I was personally more fond of the space in most cases. (Also note that `(PossiblyFreedShadaEntry) {` above is not a cast, it needs not be changed.)

File: src/nvim/shada.c [hunk 20]
```diff
@@ -2318,6 +2330,48 @@ static inline void add_search_pattern(PossiblyFreedShadaEntry *const ret_pse,
   }
 }
 
+/// Initialize registers for writing to the ShaDa file
+///
+/// @param[in]  wms  The WriteMergerState used when writing.
+/// @param[in]  max_reg_lines  The maximum number of register lines.
+static void shada_initialize_registers(WriteMergerState *const wms,
```
Comment (ZyX-I) [inline src/nvim/shada.c]: ALWAYS_INLINE needs `inline` here as well.

**Comment by ZyX-I** [comment]
Other then last comments LGTM.

File: src/nvim/shada.c (hunk 19 above)
Comment (AdnoC) [inline src/nvim/shada.c]: That was copy-pasted from the body of another function, but I guess I might as well change it.

Comment (AdnoC) [inline src/nvim/shada.c]: It seems like it needs the `(PossibyFreedShadaEntry)` to use designated initialization. Removing gives a syntax error.

Comment (ZyX-I) [inline src/nvim/shada.c]: I did not mean you need to remove it. I meant that due to it being not a cast you don’t need to remove a space.

**Comment by AdnoC** [comment]
Oops. Forgot to copy something that changed in the copy-pasted section in `shada_initialize_registers` since I copied it.

**Comment by AdnoC** [comment]
Not sure why it would fail job spec tests.

File: src/nvim/shada.c (hunk 19 above)
Comment (AdnoC) [inline src/nvim/shada.c]: Ah

**Comment by justinmk** [comment]
QB failure is unrelated. @AdnoC is this ready, or was there another test to be added?

**Comment by AdnoC** [comment]
It's good. I want to squash related commits together first though. 

Once I do that I'll mark it as [RDY]. I'll do that once I get back from class in 2-3 hours.

**Comment by AdnoC** [comment]
Good to go. I mostly left the branches from last-year untouched, but I tried to merge singe-change lint commits.

Before rebasing I made a branch [which can be found here](https://github.com/AdnoC/neovim/tree/keep-default-register-original). Running `git diff keep-default-register..keep-default-register-original` showed there were no differences, so the rebase should have went well.

**Comment by justinmk** [comment]
I'll wait for @ZyX-I to change his review to "approved".

**Review by ZyX-I — APPROVED** [review]

**Comment by AdnoC** [comment]
Woo! Glad this is finally finished.
