### PR TITLE
fix(terminal): handle ED 3 (clear scrollback) properly

### LINKED ISSUE #21403: :terminal "clear" should clear scrollback, not just the screen
### Neovim version (nvim -v)

NVIM v0.9.0-dev-470+g50ffb8d7f4

### Vim (not Nvim) behaves the same?

Yes (9.0.0910)

### Operating system/version

Arch GNU/Linux

### Terminal name/version

foot `foot version: 1.13.1 +pgo +ime +graphemes -assertions`

### $TERM environment variable

foot

### Installation

AUR

### How to reproduce the issue
1. `nvim--clean`
1. `:terminal`
1. Confirm the output of `tput lines` is less than 10.
1. Inside the terminal do `echo "hello"; clear`.
1. Scroll up to confirm that clearing works. (in vim, use `C-w` `N` then navigate in normal mode)
1. Echo something longer than 10 lines. In fish: `for i in (seq 0 20); echo $i; end; clear`.
1. Scroll up again and see the output of the last command.

### Expected behavior

Terminal gets cleared every time.

### Actual behavior

The output from every single command before (maybe with some of it cut off or corrupted in some way) remains.

[recording.webm](https://user-images.githubusercontent.com/77174844/207610703-57f60cd0-c8b4-42b5-acc5-1a03a9306ce4.webm)

### Extra information

I had a conversation with someone else as I was troubleshooting, and they recommended I report the issue here. I believe the relevant line is [here](https://github.com/neovim/neovim/blob/d311c5481dede47d752fa39cb00d728ba18ef5bc/src/nvim/terminal.c#L163). Something about not being able to handle `.sb_clear` or `ED3`.

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #34087

Problem:  Terminal doesn't handle ED 3 (clear scrollback) properly.
Solution: Add vterm callback for sb_clear().

Also fix another problem that scrollback lines may be duplicated when
pushing to scrollback immediately after reducing window height, as can
be seen in the changes to test/functional/terminal/window_spec.lua.

### CODE REVIEW

File: src/nvim/terminal.c [hunk 1]
```diff
@@ -1070,6 +1071,25 @@ static int term_sb_pop(int cols, VTermScreenCell *cells, void *data)
...
+    return 1;
+  }
+
+  for (size_t i = 0; i < term->sb_current; i++) {
+    xfree(term->sb_buffer[i]);
+  }
+
+  term->sb_current = 0;
+  term->sb_pending = 0;
+  refresh_terminal(term);
```
Comment (zeertzjq) [inline src/nvim/terminal.c:1088]: Using `pmap_put(ptr_t)(&invalidated_terminals, term, NULL);` causes the test to fail: the first line becomes `line17` instead of `line26`. Not sure why.

**Comment by zeertzjq** [comment]
Hmm, this doesn't work on Windows either?

**Comment by vlada-dudr** [comment]
As I mentioned in #21403, deleting scrollback on `clear` is not really expected behaviour. None of the terminal emulators I am aware of does it, so current Neovim implementation is perfectly in line with others.

**Comment by justinmk** [comment]
yes, and `set scrollback=1` is the normal way to achieve this.

However, should we entertain the idea of allowing Lua callbacks for: 

- known terminal events. handling OSC codes is a particular case, but what if we exposed a `TermRequest` event and/or Lua callback?
    - so e.g. `:terminal clear` would invoke `autocmd TermEvent clear …`
- unknown terminal sequences https://github.com/neovim/neovim/issues/4413 :
    - `VTermParserCallbacks` added in https://github.com/neovim/neovim/pull/17197
    - also (older): https://github.com/neovim/neovim/pull/11290

**Comment by s-cerevisiae** [comment]
Nice, please *fix* this. It's a *bug* by all definitions and none of the proposed solutions will solve it other than implementing it directly.

**Comment by zeertzjq** [comment]
Regardless of whether it's possible to handle this in a `TermRequest` autocommand, I think that shouldn't be done, as that can cause performance problems:
- `TermRequest` is scheduled on the main loop and terminal output needs to be blocked before `TermRequest` handler finishes.
- ED 3 is included in the `clear` terminfo entry of `xterm-256color`, so some full-screen programs may use it frequently.

Additionally, ED 3 should only clear the scrollback buffer in the main screen, but `TermRequest` autocommands don't know whether the terminal was in the main screen or alternate screen when ED 3 was received.

**Review by justinmk — APPROVED** [review]
Let's mention this in news.txt ?
