### PR TITLE
Fix for issue #18112: nvim_eval_statusline() should throw an error for invalid statusline

### LINKED ISSUE #18112: nvim_eval_statusline() should throw an error for invalid statusline
### Feature already in Vim?

_No response_

### Feature description

Passing an invalid statusline to `nvim_eval_statusline()` can potentially cause unexpected behavior or a crash (e.g. `nvim_eval_statusline('%{%}', {})`), so `nvim_eval_statusline()` should throw an error for invalid statusline.

### PR DESCRIPTION
**Pull request by deforde**
Fix #18112

This change aims to address the issue raised [here](https://github.com/neovim/neovim/issues/18112).

Return an error in nvim_eval_statusline() when an invalid status line string is detected.

Added a functional test to demonstrate this functionality.

### CODE REVIEW

File: src/nvim/api/vim.c [hunk 1]
```diff
@@ -2276,6 +2276,12 @@ Dictionary nvim_eval_statusline(String str, Dict(eval_statusline) *opts, Error *
   bool use_tabline = false;
   bool highlights = false;
 
+  const char *const errmsg = check_stl_option((char_u *)str.data);
+  if (errmsg) {
+    api_set_error(err, kErrorTypeValidation, "%s", errmsg);
+    return result;
+  }
+
```
Comment (gpanders) [inline src/nvim/api/vim.c:2284]: You need to make an exception for when the string starts with `%!`, see:

https://github.com/neovim/neovim/blob/df4bdba58fed4d88681fe71ce644c42d5578613d/src/nvim/option.c#L2944-L2945

```suggestion
  if (str.size < 2 || memcmp(str.data, "%!", 2)) {
    const char *const errmsg = check_stl_option((char_u *)str.data);
    if (errmsg) {
      api_set_error(err, kErrorTypeValidation, "%s", errmsg);
      return result;
    }
  }
```

**Comment by zeertzjq** [comment]
This PR looks fine. Why is it still draft?

**Comment by deforde** [comment]
Just wanted to re-run `make test` first after adding the latest changes (for sanity's sake) - didn't have a chance to do so yesterday.

**Review by gpanders — APPROVED** [review]

File: src/nvim/api/vim.c [hunk 2]
```diff
@@ -2276,6 +2276,14 @@ Dictionary nvim_eval_statusline(String str, Dict(eval_statusline) *opts, Error *
   bool use_tabline = false;
   bool highlights = false;
 
+  if (str.size < 2 || memcmp(str.data, "%!", 2)) {
```
Comment (justinmk) [inline src/nvim/api/vim.c:2279]: why is this condition needed? should we not always check `check_stl_option()` ?
