### PR TITLE
use fseek instead of lseek for a file stream

### LINKED ISSUE #11196: macOS Catalina 10.15 search tag appear "E432: Tags file not sorted"
Screenshot 2019-10-10 at 20 27 19

- `nvim --version`:
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
- `vim -u DEFAULTS` (version: ) behaves differently?
No
- Operating system/version:
macOS Cataline 10.15
- Terminal name/version:
iTerm 3.3.6 and macOS Terminal
- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
Use the built in help :h
EIther with or without a topic

```

### Actual behaviour
Gives:
E432: Tags file not sorted: /usr/local/Cellar/neovim/0.4.2/share/nvim/runtime/doc/tags
E432: Tags file not sorted: /usr/local/Cellar/neovim/0.4.2/share/nvim/runtime/pack/dist/opt/matchit/doc/tags
when a topic is supplied and
E432: Tags file not sorted: /usr/local/Cellar/neovim/0.4.2/share/nvim/runtime/doc/tags
when help is started without a topic.
### Expected behaviour
No errors.

### Notes
This is a marked issue in Vim (https://github.com/vim/vim/issues/5039) as well.
Same issue using macOS builtin ctags, homebrews ctags and homebrews universal-ctags.
Issue persist when --HEAD is installed.

### PR DESCRIPTION
**Pull request by dm1try**
this also fixes #11196 as using lseek leads to file system misbehaviour on osx Catalina

### CODE REVIEW

**Comment by dm1try** [comment]
for filesize I used information from [here](https://wiki.sei.cmu.edu/confluence/display/c/FIO19-C.+Do+not+use+fseek%28%29+and+ftell%28%29+to+compute+the+size+of+a+regular+file)

File: src/nvim/tag.c [hunk 1]
```diff
@@ -1508,11 +1508,11 @@ find_tags (
            * compute the first offset.
            */
           if (state == TS_BINARY) {
-            // Get the tag file size.
-            if ((filesize = vim_lseek(fileno(fp), (off_T)0L, SEEK_END)) <= 0) {
+            if ((vim_fseek(fp, 0, SEEK_END) != 0)) {
```
Comment (mhinz) [inline src/nvim/tag.c]: Nitpick: One level of parentheses can be removed. :)

**Review by mhinz — APPROVED** [review]

**Comment by mhinz** [comment]
Thanks for digging into this, @dm1try!

**Comment by blueyed** [comment]
Thanks, cherry-picked to the release branch in a1f557690.

**Comment by dm1try** [comment]
@mhinz, thanks for the collaboration)

**Comment by justinmk** [comment]
> for `filesize` calculation I used information from [here](https://wiki.sei.cmu.edu/confluence/display/c/FIO19-C.+Do+not+use+fseek%28%29+and+ftell%28%29+to+compute+the+size+of+a+regular+file)

That should be in the commit message next time :)
