### PR TITLE
Extmarks: manually zero out `curbuf->deleted_bytes2` on substitute and join

### LINKED ISSUE #14333: Treesitter/Extmarks: substituting does not correctly flush `curbuf->deleted_bytes2`
Repro steps with `nvim -u NORC`:

edit the following file:

```
aaa
bbb
ccc
```

```
:lua vim.api.nvim_buf_attach(0, true, {on_bytes = function(_, bufnr, tick, ...) print(...) end})
gg:s/aaa/ddd<cr>
jdj
```

Expected output:
```
0 0 0 0 3 3 0 3 3
1 0 4 2 0 8 0 0 0
```

Actual output:

```
0 0 0 0 3 3 0 3 3
1 0 4 1 2 0 12 0 0 0
```

When working on #14317, I noticed some odd buffer updates when doing linewise deletes after a substitute operation. Normally, `extmark_splice_impl` will set `deleted_bytes2 = 0`. However, `do_sub` actually calls `ml_replace/ml_delete` after it calls `extmark_splice`, meaning that `deleted_bytes2` is then incremented again after it has been flushed. This causes a problem for things like `op_delete`, since they rely on that field to get the number of changed bytes after an operation.

I guess the most straightforward/stupid fix would be to reset `curbuf->deleted_bytes2` at the end of `do_sub`, but I'm not familiar enough with the code to do it in a less stupid fashion.

@bfredl

### PR DESCRIPTION
**Pull request by chentoast**
Fixes #14333.

Moves the `extmark_splice` call after any calls to `ml_delete/ml_replace`, to ensure that `deleted_bytes2` gets correctly set to 0. I'm not sure if this is the right fix; I'll need to investigate to make sure this doesn't accidentally break anything.

### CODE REVIEW

**Comment by chentau** [comment]
@bfredl Should be ready for review :)

**Comment by vigoux** [comment]
There's a failure in the tests, about multiple matches in one line, this may be why we did the splice right after every ml_replace call.

File: src/nvim/ex_cmds.c [hunk 1]
```diff
@@ -4157,6 +4156,17 @@ static buf_T *do_sub(exarg_T *eap, proftime_T timeout,
             nmatch = vim_regexec_multi(&regmatch, curwin, curbuf,
                                        sub_firstlnum, matchcol, NULL, NULL);
 
+          if (!preview || has_second_delim) {
+            if (!did_save) {
```
Comment (bfredl) [inline src/nvim/ex_cmds.c:4160]: instead of convoluting the code like this you could just add `curbuf->deleted_bytes2 = 0` here

**Comment by vigoux** [comment]
Is it possible to add a little test focusing on that in `buffer_update_spec.lua` ?

**Comment by chentau** [comment]
@vigoux  Is this something like what you were thinking?

**Comment by vigoux** [comment]
I'll check that the test you wrote fail without this patch, just to be sure we are actually fixing the bug we attempt to fix.
Otherwise I am not against it, I just think we should avoid relying on `del_bytes` anymore.

**Comment by bfredl** [comment]
> Otherwise I am not against it, I just think we should avoid relying on del_bytes anymore.

Yes, this is the plan (for 0.6)

**Comment by chentau** [comment]
Yep, the only place remaining that still uses delbytes is in extmark_adjust - I’m hoping to try and completely remove it after 0.5

**Comment by chentau** [comment]
@bfredl @vigoux Is there anything else that you think is needed for this pr?

File: test/functional/lua/buffer_updates_spec.lua [hunk 2]
```diff
@@ -1001,6 +1001,41 @@ describe('lua: nvim_buf_attach on_bytes', function()
       }
     end)
 
+    -- TODO: delete these two tests once curbuf->deleted_bytes2
```
Comment (bfredl) [inline test/functional/lua/buffer_updates_spec.lua:1004]: remove this TODO, we should not delete these tests.
