### PR TITLE
luv callbacks: throw error on deferred methods instead of crashing

### LINKED ISSUE #10298: Crash on api calls when in luv callbacks
- `nvim --version`: NVIM v0.4.0-1075-gbc10a15ea
- Vim (version: ) behaves differently? NA
- Operating system/version: Linux 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux
- Terminal name/version: kitty v0.13.1
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Save the following as /tmp/tmp.vim:
```vimscript
let g:port = luaeval('(function()
    \ local server = vim.loop.new_tcp()
    \ server:bind("127.0.0.1", 0)
    \ server:listen(128, function(err)
            \ assert(not err, err)
            \ local sock = vim.loop.new_tcp()
            \ server:accept(sock)
            \ sock:read_start(function(err, chunk)
                  \ vim.api.nvim_command("qall!")
                  \ end)
            \ end)
    \ return server:getsockname().port
    \ end)()')
execute "! echo hello | nc 127.0.0.1 " . g:port
```
And then run neovim
```
nvim -u NORC /tmp/tmp.vim -c "source %"
```

Neovim crashes when it reaches this line:
https://github.com/neovim/neovim/blob/bc10a15ea7a5e9108a0d60a2092b099b9a6a4805/src/nvim/event/loop.c#L42

### PR DESCRIPTION
**Pull request by bfredl**
Unfortunately "throw error" in luv callbacks currently means putting garbage on the screen. This is hardcoded in luv, we could use a registered hook that luv should call in case of callback errors instead of writing to stderr.

Test (compare master to PR): 
```
timer = vim.loop.new_timer()
timer:start(1000,0, function ()
  vim.api.nvim_command("sleep 100m")
  vim.api.nvim_command("echo 'test'")
end)
```

Replacement without error:
```
timer = vim.loop.new_timer()
timer:start(1000,0, vim.schedule_wrap(function ()
  vim.api.nvim_command("sleep 100m")
  vim.api.nvim_command("echo 'test'")
end))
```

NB:  `sleep` inside callback doesn't really make sense, it is only used to provoke the crash in a simple and deterministic way.

Fixes #10298 

I also think we should rename `NVIM_API_ASYNC` to `NVIM_API_UNDEFERRED`, to better describe what the attribute actually does. (a bikeshed option might be ASYNC_SAFE, but it still suffers some of the ambiguity of ASYNC, i e deferred methods are definitely "async safe" in the sense of an async notification, it might just get delayed a bit compared to undeferred ones).

### CODE REVIEW

**Comment by justinmk** [comment]
> I also think we should rename `NVIM_API_ASYNC` to `NVIM_API_UNDEFERRED`, to better describe what the attribute actually does. (a bikeshed option might be ASYNC_SAFE, but it still suffers some of the ambiguity of ASYNC, i e deferred methods are definitely "async safe" in the sense of an async notification, it might just get delayed a bit compared to undeferred ones).

"undeferred" is sort of  double-negative. We already call the events "fast events", how about `NVIM_API_FAST` (or `NVIM_API_IMMEDIATE`, but "fast" is shorter and consistent with existing jargon) ?

**Review by justinmk — APPROVED** [review]

**Comment by bfredl** [comment]
Seems we can do this more robustly with a simple luv patch to control the execution of callbacks. https://github.com/bfredl/luv/commit/4a4ff44cc57c148e45a48da35283a4a2f16c6250 . I will ask upstream what they think of it.

File: src/nvim/lua/executor.c [hunk 1]
```diff
@@ -546,6 +611,13 @@ Object executor_exec_lua_cb(LuaRef ref, const char *name, Array args,
   }
 }
 
+/// check if the current execution context is safe for calling deferred API
+/// methods. Luv callbacks are unsafe as they are called inside the uv loop.
+bool nlua_check_safe_cb(lua_State *lstate)
```
Comment (justinmk) [inline src/nvim/lua/executor.c]:
```suggestion
bool nlua_is_deferred_safe(lua_State *lstate)
```

Usually `_cb` suffix means the thing is itself a callback, no?

**Review by justinmk — APPROVED** [review]
