### PR TITLE
env: use putenv_s for LC_ALL, LANG, etc.

### LINKED ISSUE #11045: Non-english language is active
- `nvim --version`: 0.4.2
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version: win10
- Terminal name/version: cmd

Previous version of nvim (0.3+) I could make use english with:

`language messages en_US.UTF-8`

Now it doesn't work.

### Actual behaviour

`:lang`

image

`:lang mes`

image

### Expected behaviour

nvim should be in English, using english messages and `y/n` instead of `Да/Нет`
image

### PR DESCRIPTION
**Pull request by erw7**
```
Problem:  ":lang messages en_US.UTF-8" no longer overrides the language
          detected from the environment (at startup).
Solution: In os_setenv, special-case "LC_ALL", "LANG", et al. to use
          putenv_s instead of uv_os_setenv.
```

fixes #11045

### CODE REVIEW

File: src/nvim/os/env.c [hunk 1]
```diff
@@ -135,7 +135,20 @@ int os_setenv(const char *name, const char *value, int overwrite)
   }
 #endif
   uv_mutex_lock(&mutex);
-  int r = uv_os_setenv(name, value);
+  int r;
+#ifdef WIN32
+  // LC_ALL, LANG, LANGUAGE and LC_MESSAGES must be obtained using getenv()
+  // in libintl, so we must use _putenv_s().
+  if (strcmp(name, "LC_ALL") == 0 || strcmp(name, "LANG") == 0
+      || strcmp(name, "LANGUAGE") == 0 || strcmp(name, "LC_MESSAGES") == 0) {
```
Comment (justinmk) [inline src/nvim/os/env.c]: could use `strequal()`

File: src/nvim/os/env.c [hunk 2]
```diff
@@ -135,7 +135,20 @@ int os_setenv(const char *name, const char *value, int overwrite)
   }
 #endif
   uv_mutex_lock(&mutex);
-  int r = uv_os_setenv(name, value);
+  int r;
+#ifdef WIN32
+  // LC_ALL, LANG, LANGUAGE and LC_MESSAGES must be obtained using getenv()
+  // in libintl, so we must use _putenv_s().
```
Comment (justinmk) [inline src/nvim/os/env.c]: This is rather unfortunate. We are almost going in circles, with environment management. 

Would it make sense to do *both*? I.e. `_putenv_s` _and_ `uv_os_setenv`.

File: src/nvim/os/env.c [hunk 3]
```diff
@@ -137,10 +137,10 @@ int os_setenv(const char *name, const char *value, int overwrite)
   uv_mutex_lock(&mutex);
   int r;
 #ifdef WIN32
-  // LC_ALL, LANG, LANGUAGE and LC_MESSAGES must be obtained using getenv()
+  // LC_ALL, LANGUAGE, LANG and LC_MESSAGES must be obtained using getenv()
   // in libintl, so we must use _putenv_s().
-  if (strcmp(name, "LC_ALL") == 0 || strcmp(name, "LANG") == 0
-      || strcmp(name, "LANGUAGE") == 0 || strcmp(name, "LC_MESSAGES") == 0) {
+  if (striequal(name, "LC_ALL") == 0 || striequal(name, "LANGUAGE") == 0
+      || striequal(name, "LANG") == 0 || striequal(name, "LC_MESSAGES") == 0) {
```
Comment (justinmk) [inline src/nvim/os/env.c]: need to remove `== 0` for all cases.

File: src/nvim/os/env.c (hunk 2 above)
Comment (erw7) [reply src/nvim/os/env.c]: > Would it make sense to do both? I.e. _putenv_s and uv_os_setenv.

I do not think so. This problem occurs because the value written by `SetEnvironmentVariable()` cannot be read by `getenv()`. But the values ​​set with `putenv()`, `_putenv()` and `_putenv_s()` can be obtained with `GetEnvironmentVariable()`. So calling both will be useless.

I think there are other following solutions to this problem:

- Use `_wputenv_s()` and `_wgetenv_s()` instead of `uv_os_getenv()` and `uv_os_setenv()`
- Apply a patch to the library(`libintl` etc) that uses `getenv()`, Change to use `GetEnvironmentVariable()`.
- I don't know if I can do it, but we rewrite `IAT` and replace `getenv()` itself with a function provided by neovim.

**Comment by justinmk** [comment]
> ... `_putenv_s()` can be obtained with `GetEnvironmentVariable()`. So calling both will be useless.

👍 

> I think there are other following solutions to this problem:
> 
> * Use `_wputenv_s()` and `_wgetenv_s()` instead of `uv_os_getenv()` and `uv_os_setenv()`

Then we have to deal with multibyte conversion, which libuv does for us ;_;  

> * Apply a patch to the library(`libintl` etc) that uses `getenv()`, Change to use `GetEnvironmentVariable()`.

That would be nice, but I don't have high hopes :)

> * I don't know if I can do it, but we rewrite `IAT` and replace `getenv()` itself with a function provided by neovim.

For reference: [IAT = import address table](https://blog.neteril.org/blog/2016/12/23/diverting-functions-windows-iat-patching/). Interesting! But, let's avoid monkey-patching :)

Looking at `third-party/CMakeLists.txt`, I don't see any other libraries that are likely to have this problem. So maybe we're safe now. 😅 

@erw7 thank you so much for fixing this!

File: src/nvim/os/env.c [hunk 4]
```diff
@@ -135,7 +135,20 @@ int os_setenv(const char *name, const char *value, int overwrite)
...
+  if (striequal(name, "LC_ALL") || striequal(name, "LANGUAGE")
+      || striequal(name, "LANG") || striequal(name, "LC_MESSAGES")) {
+    r = _putenv_s(name, value);  // NOLINT
+    assert(r == 0);
+  } else {
+#endif
+  r = uv_os_setenv(name, value);
+#ifdef WIN32
+  }
+#endif
```
Comment (justinmk) [inline src/nvim/os/env.c]: Doing `uv_os_setenv` always, would avoid some `#ifdef` noise, and avoids the `else{` case. It's harmless--and it keeps `envmap` "up to date", which may avoid confusion.

File: src/nvim/os/env.c [hunk 5]
```diff
@@ -135,7 +135,20 @@ int os_setenv(const char *name, const char *value, int overwrite)
   }
 #endif
   uv_mutex_lock(&mutex);
-  int r = uv_os_setenv(name, value);
+  int r;
+#ifdef WIN32
+  // LC_ALL, LANGUAGE, LANG and LC_MESSAGES must be obtained using getenv()
```
Comment (justinmk) [inline src/nvim/os/env.c]:
```suggestion
  // libintl uses getenv() for LC_ALL/LANG/etc., so we must use _putenv_s().
```
