### PR TITLE
fix(lsp): clean the diagnostic cache  when buffer delete

### LINKED ISSUE #19322: vim.diagnostic.setqflist() execution error, E5108: Error executing lua Vim:E92: Buffer 11 not found
### Neovim version (nvim -v)

NVIM v0.8.0-dev+596-gac10c0f41

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.4

### Terminal name/version

wezterm 20220705-220116-00fb0c58

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

```sh
# Language server jdt.ls

cd javaProject
nvim
:e xxx.java
:lua vim.diagnostic.setqflist()
# open xxx.java
:bw
:lua vim.diagnostic.setqflist()
```

### Expected behavior

Expect vim.diagnostic.setqflist() to execute correctly
图片

### Actual behavior

```log
E5108: Error executing lua Vim:E92: Buffer 11 not found
stack traceback:
        [C]: in function 'setqflist'
        ...m/HEAD-ac10c0f/share/nvim/runtime/lua/vim/diagnostic.lua:489: in function 'set_list'
        ...m/HEAD-ac10c0f/share/nvim/runtime/lua/vim/diagnostic.lua:1433: in function 'setqflist'
        [string ":lua"]:1: in main chunk
```
nvim-lsp-bw

### PR DESCRIPTION
**Pull request by glepnir**
when use `bwipeout` command to delete a buffer. this buffer will remove from `bufinfo` , but there check the buffer in list or not at  `quickfix.c`. if not get an error . so check the buffer is valid before convert the diagnostic to `qflist` table

https://github.com/neovim/neovim/blob/243038188bc74c008e36fc005aa18dc23d7ae3f0/src/nvim/quickfix.c#L6383-L6387

Fix #19322

### CODE REVIEW

**Comment by gpanders** [comment]
I think we need to figure out why the diagnostics aren't being removed after `:bwipeout`. That is the actual underlying bug here.

**Comment by JavaHello** [comment]
> ondetach not watch the bw？
print(table.concat(vim.lsp.get_buffers_by_client_id(client.id), ', ')) can get the buffer information after `bw`. Is the problem related to this?

**Comment by glepnir** [comment]
@gpanders  this function just work on loaded buffer. so that is mean `on_detach` just work for current buffer. when we first set the diagnostic to cache ,it use lots of unloaded buffer. 

https://github.com/neovim/neovim/blob/bb7853a62dc32baafa7416b94c97f985287f39e2/runtime/lua/vim/diagnostic.lua#L51-L54

```lua
 local ok = vim.api.nvim_buf_attach(bufnr, false, { 
   on_detach = function() 
     rawset(t, bufnr, nil) -- clear cache 
   end, 
-- only current buffer is true. all unloaded bufnr is false
 print(ok)
```

so when open buffer , register `on_detach` callback for it. works fine for me.

**Comment by glepnir** [comment]
@gpanders  ping

File: runtime/lua/vim/diagnostic.lua [hunk 1]
```diff
@@ -715,6 +715,12 @@ function M.set(namespace, bufnr, diagnostics, opts)
   end
 
   if vim.api.nvim_buf_is_loaded(bufnr) then
+    vim.api.nvim_buf_attach(bufnr, false, {
+      on_detach = function()
+        rawset(diagnostic_cache, bufnr, nil) -- clear cache
+      end,
+    })
+
```
Comment (gpanders) [inline runtime/lua/vim/diagnostic.lua:723]: This will just call `nvim_buf_attach` twice for loaded buffers then, as it is also called in the `__index` function for the diagnostic cache's `metatable`.

What if instead we just force buffers to load when they are added to the diagnostic cache? I wonder what the performance cost of that would be?

**Review by gpanders — CHANGES_REQUESTED** [review]

File: runtime/lua/vim/diagnostic.lua (hunk 1 above)
Comment (glepnir) [reply runtime/lua/vim/diagnostic.lua:723]: @gpanders `use vim.fb.buload` doesn't fix that. it will load once of current buffer.like i said it not trigger on `__index`

Comment (gpanders) [reply runtime/lua/vim/diagnostic.lua:723]: >@gpanders use vim.fb.buload doesn't fix that.

Did you try it?

Comment (glepnir) [reply runtime/lua/vim/diagnostic.lua:723]: yup. still has error

Comment (glepnir) [reply runtime/lua/vim/diagnostic.lua]: done. I forget restore the `$VIMRUNTIME` .so it not take effect. confirm work. I forget this api can load buffer. my mistake

Comment (gpanders) [reply runtime/lua/vim/diagnostic.lua]: Please add the comment from the patch above:

```lua
-- Force buffer to load, nvim_buf_attach does not work on unloaded buffers
```

**Comment by gpanders** [comment]
A test case in `diagnostic_spec.lua` would be good too.

File: runtime/lua/vim/diagnostic.lua (hunk 1 above)
Comment (mfussenegger) [reply runtime/lua/vim/diagnostic.lua]: > What if instead we just force buffers to load when they are added to the diagnostic cache? I wonder what the performance cost of that would be?

This would trigger all autocmds right? If so I think this could be potentially very costly. Many language servers report diagnostcs for the full projects which can easily result in 10k+ diagnostics spanning several hundred files.

Comment (gpanders) [reply runtime/lua/vim/diagnostic.lua]: That's a good point. I suppose we could disable autocommands before loading the buffer, but that probably has *other* side effects.

Let's try using a `BufDelete` autocmd instead of an `on_detach` callback in `nvim_buf_attach`. That should still fire even for buffers that were never loaded.

Comment (glepnir) [reply runtime/lua/vim/diagnostic.lua]: I had think about it。but dont find a good place to write it

Comment (glepnir) [reply runtime/lua/vim/diagnostic.lua]: done.

**Comment by gpanders** [comment]
Just needs a test. You can use a simplified version of the issue in #19322. Add diagnostics for an unloaded buffer, then `bwipe` that buffer, then assert that that buffer is removed from the diagnostic cache.

File: test/functional/lua/diagnostic_spec.lua [hunk 2]
```diff
@@ -128,6 +128,26 @@ describe('vim.diagnostic', function()
     eq('Diagnostic #1', result[1].message)
   end)
 
+  it('clean the diagnostic cache when buf delete', function()
```
Comment (gpanders) [inline test/functional/lua/diagnostic_spec.lua:131]: This test still passes even without the changes in this PR. So it's not testing what you think it's testing.

Make sure the test fails on master, and passes when the changes from this PR are applied.

**Review by gpanders — CHANGES_REQUESTED** [review]

File: test/functional/lua/diagnostic_spec.lua (hunk 2 above)
Comment (glepnir) [reply test/functional/lua/diagnostic_spec.lua:131]: done

**Review by gpanders — APPROVED** [review]
LGTM, thanks @glepnir!

Ping @mfussenegger.

**Comment by mfussenegger** [comment]
Gave this a try to see how it interacts with LSP and I now wonder if we should make this configurable per namespace and have LSP deactive it by default.

LSP sends diagnostics on a project level. If you open a file and then delete the buffer this now loses the diagnostics and there is no good way to get them back.
If you worked on a file, had a compile error in it but saved & closed it without noticing and then use `vim.diagnostic.setqflist()` you'll no longer find it.

**Comment by gpanders** [comment]
>LSP sends diagnostics on a project level. If you open a file and then delete the buffer this now loses the diagnostics and there is no good way to get them back.

We could modify the diagnostic cache to use the file name rather than the buffer number as the key. But until that is done we should still clear invalid buffer numbers from the cache or we will continue to see errors like the linked issue.

We could also make use of the `textDocument/diagnostic` request for this. Though I'm not sure how widely supported that is at present.

**Comment by mfussenegger** [comment]
> we should still clear invalid buffer numbers from the cache or we will continue to see errors like the linked issue.

Maybe we could check the buftype & file and keep the diagnostics if it's still there.
The change as it is would break my usual workflow and I suspect I'm not alone with that

> We could also make use of the `textDocument/diagnostic` request for this. Though I'm not sure how widely supported that is at present.

It's an optional feature,  even if it were widespread we shouldn't depend on it

**Comment by glepnir** [comment]
@gpanders  @mfussenegger  How about this. test it ok on my local

```lua
local diagnostic_cache
do
  local group = vim.api.nvim_create_augroup('DiagnosticBufDelete', {})
  diagnostic_cache = setmetatable({}, {
    __index = function(t, bufnr)
      assert(bufnr > 0, 'Invalid buffer number')
      vim.api.nvim_create_autocmd('BufDelete', {
        group = group,
        buffer = bufnr,
        callback = function()
          local namespae_diagnostics = t[bufnr]
          rawset(t, bufnr, nil)
          vim.api.nvim_buf_set_name(bufnr,'')
          local fname = vim.fn.expand('%:p')
          local new_bufnr = vim.fn.bufadd(fname)
          vim.api.nvim_buf_set_option(new_bufnr,'buflisted',true)
          for _,diagnostics in pairs(namespae_diagnostics) do
            for _, diagnostic in pairs(diagnostics) do
              if diagnostic.bufnr == bufnr then
                diagnostic.bufnr = new_bufnr
              end
            end
          end
          rawset(t,new_bufnr,namespae_diagnostics)
        end,
      })
      t[bufnr] = {}
      return t[bufnr]
    end,
  })
end

```

**Comment by mfussenegger** [comment]
> @gpanders @mfussenegger How about this. test it ok on my local
> 
> ```lua
> local diagnostic_cache
> do
>   local group = vim.api.nvim_create_augroup('DiagnosticBufDelete', {})
>   diagnostic_cache = setmetatable({}, {
>     __index = function(t, bufnr)
>       assert(bufnr > 0, 'Invalid buffer number')
>       vim.api.nvim_create_autocmd('BufDelete', {
>         group = group,
>         buffer = bufnr,
>         callback = function()
>           local namespae_diagnostics = t[bufnr]
>           rawset(t, bufnr, nil)
>           vim.api.nvim_buf_set_name(bufnr,'')
>           local fname = vim.fn.expand('%:p')
>           local new_bufnr = vim.fn.bufadd(fname)
>           vim.api.nvim_buf_set_option(new_bufnr,'buflisted',true)
>           for _,diagnostics in pairs(namespae_diagnostics) do
>             for _, diagnostic in pairs(diagnostics) do
>               if diagnostic.bufnr == bufnr then
>                 diagnostic.bufnr = new_bufnr
>               end
>             end
>           end
>           rawset(t,new_bufnr,namespae_diagnostics)
>         end,
>       })
>       t[bufnr] = {}
>       return t[bufnr]
>     end,
>   })
> end
> ```

What's the idea behind that? If I understand it right it re-adds the buffer?

**Comment by glepnir** [comment]
是的，when use bwipeout remove buffer we use a new buffer number  then you will also get

**Comment by mfussenegger** [comment]
> LSP sends diagnostics on a project level. If you open a file and then delete the buffer this now loses the diagnostics and there is no good way to get them back.

I think I may have been wrong about this. The existing `on_detach` would already clear them. I think the reason I was under the impression it doesn't is that language servers publish them back.

If so it could be an option to keep the `on_detach` as is, and add a `BufWipeout` event in addition for the buffers that weren't loaded?

**Comment by glepnir** [comment]
`on_detach` just work on current load buffer.  it not work on unload buffer.so it only clear the cache of  current buffer when current buffer detach.

**Comment by mfussenegger** [comment]
> add `Bwipeout` event work with `bwipeout` and there need check the buffer has diagnostic or not? if has give it a new bufnr in `Bwipeout` cb. if not do nothing?

No, just delete the diagnostics, same as the current detach handler does.
If a user wipes a buffer, they don't want it to reappear as a loaded & listed buffer. They want it wiped.

**Comment by glepnir** [comment]
@mfussenegger  what is the process of this pr ?

**Comment by mfussenegger** [comment]
> what is the process of this pr ?

I double checked and merged it. The behavior on master with `:bd` was the same due to the `on_detach`. The reason I thought it would keep diagnostics is because the language server re-published them

Sorry for the holdup and confusion.
