### PR TITLE
lsp: `lsp.util.fancy_floating_markdown` improvements

### LINKED ISSUE #14594: lsp.util.fancy_floating_markdown uses lua syntax for all the markdown instead of the code block region
- `nvim --version`:
```
NVIM v0.5.0-dev+1327-gdc18c1e3e
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1621311335978.local
```
- language server name/version: sumneko-lua
- Operating system/version: macos latest

### Steps to reproduce using nvim -u minimal_init.lua
Activate lsp hover over any function like `split`

```lua
vim.split("")
```

### Actual behaviour

```lua
-- lsp.util.convert_input_to_markdown_lines of hover lsp result
local lines = {
  "```lua",
  "function vim.split(s: any, sep: any, plain: any)",
  "  -> table",
  "```",
  "---",
  " Splits a string at each instance of a separator.",
  "",
  "",
  "",
  " Examples:",
}
```

The lines have a correct code block, but all lines of the hover doc are using the `lua` syntax

image

### Expected behaviour

only the function signature (lua code block) should have the lua syntax.
other parts of the doc should be markdown.

### PR DESCRIPTION
**Pull request by folke**
This PR adds a couple of improvements and fixes #14594:

* don't add a separator after a code block when there is already a separator after it
* the `syn regions` for the code blocks didn't work. The first one for some reason always applied to the whole buffer. Adding `keepend` fixes this issue
* handle `<pre></pre>` inside markdown the same way as a markdown code block

### CODE REVIEW

**Comment by mjlbach** [comment]
I think the usual convention is to prefix commits based on the area of the code they touch, in this case `lsp: `

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -1123,9 +1127,14 @@ function M.fancy_floating_markdown(contents, opts)
     for i, h in ipairs(highlights) do
       h.start = h.start + i - 1
       h.finish = h.finish + i - 1
+      -- check if a seperator already exists and use that one instead of creating a new one
       if h.finish + 1 <= #stripped then
-        table.insert(stripped, h.finish + 1, string.rep("─", math.min(width, opts.wrap_at or width)))
-        height = height + 1
+        if stripped[h.finish + 1]:match("^---+$") then
```
[the remark this answers is not in the document]
Comment (folke) [reply runtime/lua/vim/lsp/util.lua:1132]: Definitely would make sense.

**Comment by folke** [comment]
@mjlbach sounds good. I'll remember to use the proper commit message convention next time. Thanks!

**Comment by mjlbach** [comment]
No worries, would you mind squashing your commits when you can? Just in case, `git rebase -i master`, change pick to squash for all but the first one (change to edit), and then rename the first one something like `lsp: lsp.util.fancy_floating_markdown improvements`, and include the subsequent commit messages in the body :)

Also, do you have a couple more examples where this is causing an issue so I can test? I think the code changes make sense, just want to test for corner cases.

**Comment by folke** [comment]
Pretty much any completion using sumneko lsp. It returns a markdown value where the first line is always a `lua` code block.
It also adds a separator after the title, so that's how I noticed the double seperators.

Simple test code:
```lua
local M = {}

--- testing 123
--- this should not be rendered as a "lua string"
--```plaintex
-- this should be plaintext, but gets lua syntax highlighting
-- 1 2 3 4
--```
-----
--foor
function M.foo()
end
return M
```

image

With the fixes:

image

**Comment by folke** [comment]
Something's not working as it should. I will look into it first.

In the code below, the second code block should be with syntax Lua, but it's not setting any highlights.

Will let you know once I squashed the commits and resolved this issue.

image

**Comment by mhinz** [comment]
I just wanted to chime in for a moment to talk about the commit style. It's not written anywhere yet, but we'd like to try changing to Angular style in the future, to make releases as automated as possible.

So, it would be `feat(lsp): imperative and lowercase without a dot at the end`.

For a quick summary, see: https://nitayneeman.com/posts/understanding-semantic-commit-messages-using-git-and-angular

**Comment by folke** [comment]
Fixed now. The problem was that `ownsyntax` was set and the `syn regions` never matched, because they already matched by the top-level `lsp_markdown`. The fix was to no longer set `ownsyntax` and create regions for the markdown like the rest of the code blocks.
image

I'll do the squash commit now.

**Comment by folke** [comment]
rebase is done, but apparently the commit messages were already included in the body, so they're double now :)

**Comment by mjlbach** [comment]
`git commit --amend` should let you reword it :)

**Comment by folke** [comment]
Amended the commit message and also fixed some typos and a one-off error where the first or last line potentially wouldn't get markdown syntax.

File: runtime/lua/vim/lsp/util.lua [hunk 2]
```diff
@@ -1155,16 +1163,20 @@ function M.fancy_floating_markdown(contents, opts)
...
   end
   -- Previous highlight region.
-  -- TODO(ashkan): this wasn't working for some reason, but I would like to
-  -- make sure that regions between code blocks are definitely markdown.
-  -- local ph = {start = 0; finish = 1;}
+  local ph = 1
   for _, h in ipairs(highlights) do
-    -- apply_syntax_to_region('markdown', ph.finish, h.start)
+    if ph <= h.start - 1 then
+      apply_syntax_to_region('lsp_markdown', ph, h.start - 1)
```
[the remark this answers is not in the document]
Comment (folke) [reply runtime/lua/vim/lsp/util.lua:1172]: The fix to make the different syn regions work, was to remove the `ownsyntax`.
The `highlights` list only contains markdown code blocks.

so in between code blocks, we apply the `lsp_markdown` syntax

[the remark this answers is not in the document]
Comment (folke) [reply runtime/lua/vim/lsp/util.lua:1172]: `ph` keeps track of the first line after the last code block (or the first line if we haven't added a code block yet)
When adding syn regions for a new code block, we add a markdown region from the line after the end of the last code block till the line before the start of the new code block.

**Comment by mjlbach** [comment]
Hmm, I'm noticing some formatting changes in for pyright that seem unintended. I need to dig more into this (pd.DataFrame hover for example)

**Comment by folke** [comment]
without changes:
image

with the fixes:
image

**Comment by folke** [comment]
ok, I see it. The `>>>` stuff. Will see what's happening there.

**Comment by mjlbach** [comment]
I'm not sure the prior behavior was correct, I just noticed the difference. I want to robustly test this as it's going into 0.5 and the syntax/highlight rulres around the mixed markdown approach we are currently doing still elude me a bit :)

File: runtime/lua/vim/lsp/util.lua [hunk 3]
```diff
@@ -1143,28 +1152,31 @@ function M.fancy_floating_markdown(contents, opts)
   api.nvim_win_set_option(winnr, 'conceallevel', 2)
   api.nvim_win_set_option(winnr, 'concealcursor', 'n')
 
-  vim.cmd("ownsyntax lsp_markdown")
   local idx = 1
   --@private
   local function apply_syntax_to_region(ft, start, finish)
-    if ft == '' then return end
+    if ft == '' then ft = "lsp_markdown" end
```
Comment (folke) [inline runtime/lua/vim/lsp/util.lua:1158]: Was able to fix it. Previously, the whole buffer was `markdown`, so this line skipped syn regions for code blocks without a language.

But now we need to markup those regions with markdown instead.

Comment (folke) [reply runtime/lua/vim/lsp/util.lua:1158]: Actually now that I think about it. Is it a good idea to use `lsp_markdown` for a code block without a lang?

For the `<pre>` blocks I actually used `plaintex` instead.

What do you think?

Comment (folke) [reply runtime/lua/vim/lsp/util.lua:1158]: I also wonder why the special handling is uberhaut needed. Shouldn't `vim_markdown_fenced_languages` be used instead and leave the code blocks as is?

Comment (mjlbach) [reply runtime/lua/vim/lsp/util.lua:1158]: The main point of lsp_markdown is to apply conceal rules not offered by markdown to hide escaped characters. In the case of there not being a language tag, there shouldn't be a difference between markdown and plaintex. If there isn't a tag probably plaintex is fine, I doubt there's a noticeable perf difference.

Comment (mjlbach) [reply runtime/lua/vim/lsp/util.lua:1158]: What special handling? The stripping of the code fences? It's mostly for aesthetics to avoid a bunch of concealed blank lines IIRC

Comment (folke) [reply runtime/lua/vim/lsp/util.lua:1158]: never mind. It's prettier when using the regions :)

Comment (folke) [reply runtime/lua/vim/lsp/util.lua:1158]: As an alternative, we can leave those code blocks ` ``` ` without lang and let the markdown render them as a code block:
image

Comment (folke) [reply runtime/lua/vim/lsp/util.lua:1158]: @mjlbach so should I change it to use `plaintex` instead? Then of course those darker `>>>` lines would be normal text. Or should I use a syn match and apply the markdown code block highlight group instead of a region?

Comment (mjlbach) [reply runtime/lua/vim/lsp/util.lua:1158]: I don't think either is more correct, you've proven to have an aesthetic eye for these things :) I learn towards *not* using plaintex but if someone complains we can always change it later

Comment (folke) [reply runtime/lua/vim/lsp/util.lua:1158]: Maybe something like this instead?

image

Comment (folke) [reply runtime/lua/vim/lsp/util.lua:1158]: Should be `markdownCodeBlock` but the idea is the same :)

I'm happy to keep it as was before and use `lsp_markdown` for code blocks without a language too. Let me know what you prefer.

Comment (folke) [reply runtime/lua/vim/lsp/util.lua:1158]: Would look like this then:
image

Comment (mjlbach) [reply runtime/lua/vim/lsp/util.lua:1158]: That looks good IMO, do you agree?

Comment (folke) [reply runtime/lua/vim/lsp/util.lua]: Yep, I prefer it that way. Also makes the most sense I guess. When a code block has a `lang`, we render it using that syntax, otherwise we render it as a code block.

I just pushed an update.

The `<pre>` is also rendered as a code block now.

Comment (folke) [reply runtime/lua/vim/lsp/util.lua]: I also fixed an issue I introduced with the seperators. The previous code expected a sep to be added for every block and shifted the highlight start and end. Since we now sometimes skip a sep, I had to change it to reflect this.

Comment (folke) [reply runtime/lua/vim/lsp/util.lua]: Im going to get some sleep now, but do let me know if you want any additional changes. I can work on them tomorrow morning. Thanks.

another example:
image
