### PR TITLE
[RFC] vim-patch:8.1.1365,8.1.1366,8.1.1367,8.1.1368,8.1.1382,8.1.1401

### LINKED ISSUE #10130: Fix for modeline vulnerability is incomplete
- <details><summary>`nvim --version`:</summary>
```
NVIM v0.4.0-944-g3305769ea
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/void/neovim/build/config -I/home/void/neovim/src -I/usr/include -I/home/void/neovim/build/src/nvim/auto -I/home/void/neovim/build/include
Compiled by void@node-a0

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
</details>

- Vim (version: ) behaves differently?
  Yes

### Steps to reproduce
1.
  <details><summary>Config file </summary>

  ```viml
  set shada=!,'150,<100,/50,:50,r/tmp,s256
  set modeline
  autocmd BufWinLeave *.* mkview
  autocmd BufWinEnter *.* silent! loadview
  ```
  </details>

2. 
  <details><summary>poc.txt</summary>

  [Source](https://github.com/numirias/security/blob/master/doc/2019-06-04_ace-vim-neovim.md)
  ```
  :!uname -a||" vi:fen:fdm=expr:fde=assert_fails("source\!\ \%"):fdl=0:fdt="
  ```
  </details>

3. Open poc.txt

4. Close it

5. Open it again

### Actual behaviour

`uname -a` is run.

### Expected behaviour

`uname -a` is not run

### PR DESCRIPTION
**Pull request by jamessan**
#### vim-patch:8.1.1365: source command doesn't check for the sandbox

Problem:    Source command doesn't check for the sandbox. (Armin Razmjou)
Solution:   Check for the sandbox when sourcing a file.
https://github.com/vim/vim/commit/53575521406739cf20bbe4e384d88e7dca11f040

#### vim-patch:8.1.1366: using expressions in a modeline is unsafe

Problem:    Using expressions in a modeline is unsafe.
Solution:   Disallow using expressions in a modeline, unless the
            'modelineexpr' option is set.  Update help, add more tests.
https://github.com/vim/vim/commit/110289e78195b6d01e1e6ad26ad450de476d41c1

#### vim-patch:8.1.1367: can set 'modelineexpr' in modeline

Problem:    can set 'modelineexpr' in modeline.
Solution:   Add P_SECURE flag.
https://github.com/vim/vim/commit/7e800c6047c8a9cc3e5cbc019a4dc91ec36616b1

#### vim-patch:8.1.1368: modeline test fails with python but without pythonhome

Problem:    Modeline test fails with python but without pythonhome.
Solution:   Correct test argument.
https://github.com/vim/vim/commit/e09244ee3567d658c293fb1ae0d47a1a8be870ac

#### vim-patch:8.1.1382: error when editing test file

Problem:    Error when editing test file.
Solution:   Remove part of modeline.
https://github.com/vim/vim/commit/3020a87cb121123abf1e9a1eca0eddac241fc481

#### vim-patch:8.1.1401: misspelled mkspellmem as makespellmem

Problem:    Misspelled mkspellmem as makespellmem.
Solution:   Drop duplicate help entry, fix test. (Naruhiko Nishino, Ken
            Takata, closes vim/vim#4437)
https://github.com/vim/vim/commit/076073950c44ea0e35bc39d539dc7ab41bf9c7ec

Closes #10130

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

File: src/nvim/generators/gen_options.lua [hunk 1]
```diff
@@ -79,6 +79,7 @@ local get_flags = function(o)
     {'pri_mkrc'},
     {'deny_in_modelines', 'P_NO_ML'},
     {'deny_duplicates', 'P_NODUP'},
+    {'honor_modelineexpr', 'P_MLE'},
```
Comment (justinmk) [inline src/nvim/generators/gen_options.lua]: just `modelineexpr` would make sense to me.
