### PR TITLE
Only waitpid() for processes that we care about

### LINKED ISSUE #8104: nvim.appimage: fzf window does not close on ESC
- `nvim --version`: `v0.2.3-1-gd6f9d1df0`
- Vim behaves differently? Not applicable
- Operating system/version: Arch Linux 4.14 and RHEL 7.4
- Terminal name/version: zsh 5.4 (for arch) and zsh 5.0 (for RHEL)
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

1. Open terminal mode with :term
2. Exit terminal session from terminal (such as `i<C-d>`)

### Expected behaviour

Terminal closes and returns to previous buffer (same behavior as package/full install)

### Actual behaviour

Terminal pane locks up, accepting no input other than ESC (which returns to normal mode). Normal mode will accept commands (other than <C-\\><C-n>) as usual.

### PR DESCRIPTION
**Pull request by dimbleby**
Fixes #8104.

It seems that when running in an appimage there are bonus `SIGCHLD`s flying around.  I haven't figured out the exact steps that lead to hangs - but it seems likely that if we're catching `SIGCHLD` that we don't really need, then someone else is not catching one that they do...

Anyway, fix is tested manually and the neovim appimage doesn't hang any more.

### CODE REVIEW

**Comment by dimbleby** [comment]
PS cf https://patchwork.kernel.org/patch/9949491/

**Review by jamessan — APPROVED** [review]

File: src/nvim/os/pty_process_unix.c [hunk 1]
```diff
@@ -273,26 +273,24 @@ static void chld_handler(uv_signal_t *handle, int signum)
...
+      continue;
+    }
+
+    if (WIFEXITED(stat)) {
+      proc->status = WEXITSTATUS(stat);
+    } else if (WIFSIGNALED(stat)) {
+      proc->status = WTERMSIG(stat);
     }
+    proc->internal_exit_cb(proc);
+    break;
```
Comment (oni-link) [inline src/nvim/os/pty_process_unix.c]: What if three or more children are terminated? Would the first signal be handled here, the second signal be marked pending and every further (of the same) signal be dropped (we miss a child termination)? Would that be fixed if we remove the `break` here?

Comment (jamessan) [reply src/nvim/os/pty_process_unix.c]: Although in both the original code and this PR we only process one job, I can understand oni-link's concern that we may be handling the wrong job because we end up reaping a different child than the one that delivered the signal.

In order to truly be deterministic, though, we would likely need to use `sigaction()` so we can be directly told which child delivered the signal.  Since we're using libuv's abstraction, that's not really an option here.

I wonder if a simpler fix is to change the original code to use `waitpid(0, &stat, WNOHANG);`.  It looks like that should still fix the problem.  If that does work, we probably want to actually loop until `waitpid()` tells us none of our children are waitable.

**Comment by justinmk** [comment]
@dimbleby This is a huge help, thanks for investigating. Could you please include the full explanation from https://github.com/AppImage/AppImageKit/issues/812#issuecomment-404662110 in the commit message, including the link to https://patchwork.kernel.org/patch/9949491/ ?

File: src/nvim/os/pty_process_unix.c (hunk 1 above)
Comment (dimbleby) [reply src/nvim/os/pty_process_unix.c]: If I understand correctly the concern is not that we handle jobs in the 'wrong' order - that really shouldn't matter.  (A dies, B dies, we handle B, we handle A - so what?  B might just as well have died first).  

Rather the worry was that we might somehow *miss* terminations.  I don't think that'll happen, though I'm not 100% sure and I can't see either how removing the `break` would be unsafe.  (But I still say, if you want to do that, let's do it in a new issue).

Either way, I'd favour sticking with being completely explicit about what PIDs we're waiting for as the most foolproof approach.

**Comment by dimbleby** [comment]
re-pushed with a bigger comment

File: src/nvim/os/pty_process_unix.c (hunk 1 above)
Comment (dimbleby) [reply src/nvim/os/pty_process_unix.c]: I've done some more googling and I now think that @oni-link is right all along - `SIGCHLD`s are not queued, so we might see fewer of them than terminated processes.  

I'll raise a new issue and propose that the fix is simply to remove the `break`
