### PR TITLE
fix(popup): wrong extmark data sync when lines changed in popup preview

### LINKED ISSUE #30601: treesitter: crash in `ts_parser_parse` with CompleteChanged
### Problem

Nvim crashes probably when trying to show documentation for `nvim_cmd`:

image

```cpp
#0  0x00005651437a8330 in ts_lexer_reset ()
(gdb) bt
#0  0x00005651437a8330 in ts_lexer_reset ()
#1  0x000056514378b736 in ts_parser_parse ()
#2  0x00005651435fb13d in parser_parse (L=0x7fa0ffd1c380) at .../src/nvim/lua/treesitter.c:475
#3  0x00005651437d01a6 in lj_BC_FUNCC ()
#4  0x00005651437bba5d in lua_pcall (L=L@entry=0x7fa0ffd1c380, nargs=nargs@entry=1, nresults=nresults@entry=1, errfunc=errfunc@entry=-3) at lj_api.c:1122
#5  0x00005651435eb379 in nlua_pcall (lstate=0x7fa0ffd1c380, nargs=1, nresults=1) at .../src/nvim/lua/executor.c:174
#6  0x00005651435f8198 in nlua_call_ref (ref=<optimized out>, name=<optimized out>, args=..., mode=kRetNilBool, arena=0x0, err=0x0) at .../src/nvim/lua/executor.c:1608
#7  0x00005651434f404e in call_autocmd_callback (ac=ac@entry=0x5651472a0cc0, apc=apc@entry=0x7ffd8bbd5270) at .../src/nvim/autocmd.c:2057
#8  0x00005651434f6263 in getnextac (c=<optimized out>, cookie=0x7ffd8bbd5270, indent=<optimized out>, do_concat=<optimized out>) at .../src/nvim/autocmd.c:2108
#9  0x0000565143587372 in do_cmdline (cmdline=<optimized out>, fgetline=0x5651434f60cb <getnextac>, cookie=0x7ffd8bbd5270, flags=7) at .../src/nvim/ex_docmd.c:580
#10 0x00005651434f4d59 in apply_autocmds_group (event=EVENT_COMPLETECHANGED, fname=0x565147585060 "/home/arctgx/dev/arctgx/nvim/issues/current/2024-09-25-00.55.02-xdiff-linematch-error/init.lua", fname_io=<optimized out>,
    force=<optimized out>, group=group@entry=-3, buf=0x5651471295c0, eap=0x0, data=0x0) at .../src/nvim/autocmd.c:1842
#11 0x00005651434f540d in apply_autocmds (event=<optimized out>, fname=<optimized out>, fname_io=<optimized out>, force=<optimized out>, buf=<optimized out>) at .../src/nvim/autocmd.c:1499
#12 0x00005651435ce8d5 in trigger_complete_changed_event (cur=cur@entry=23) at .../src/nvim/insexpand.c:1145
#13 0x00005651435ceed0 in ins_compl_show_pum () at .../src/nvim/insexpand.c:1377
#14 0x00005651435d4435 in show_pum (prev_w_wrow=prev_w_wrow@entry=3, prev_w_leftcol=prev_w_leftcol@entry=0) at .../src/nvim/insexpand.c:4665
#15 0x00005651435d4f76 in ins_complete (c=14, enable_pum=<optimized out>) at .../src/nvim/insexpand.c:4643
#16 0x000056514352f506 in insert_do_complete (s=s@entry=0x7ffd8bbd5640) at .../src/nvim/edit.c:1228
#17 0x0000565143536e6b in insert_handle_key (s=s@entry=0x7ffd8bbd5640) at .../src/nvim/edit.c:1146
#18 0x00005651435373e5 in insert_execute (state=0x7ffd8bbd5640, key=<optimized out>) at .../src/nvim/edit.c:702
#19 0x00005651436e1c71 in state_enter (s=0x7ffd8bbd5640) at .../src/nvim/state.c:100
#20 0x000056514352ee8c in insert_enter (s=0x7ffd8bbd5640) at .../src/nvim/edit.c:344
#21 0x000056514352f680 in edit (cmdchar=111, startln=<optimized out>, count=1) at .../src/nvim/edit.c:1305
#22 0x00005651436461e9 in invoke_edit (cap=cap@entry=0x7ffd8bbd57e0, repl=repl@entry=0, cmd=111, startln=startln@entry=1) at .../src/nvim/normal.c:6255
#23 0x0000565143646342 in n_opencmd (cap=cap@entry=0x7ffd8bbd57e0) at .../src/nvim/normal.c:5716
#24 0x00005651436465c9 in nv_open (cap=0x7ffd8bbd57e0) at .../src/nvim/normal.c:6593
#25 0x00005651436409b6 in normal_execute (state=0x7ffd8bbd5770, key=<optimized out>) at .../src/nvim/normal.c:1235
#26 0x00005651436e1c71 in state_enter (s=0x7ffd8bbd5770) at .../src/nvim/state.c:100
#27 0x000056514363db5d in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at .../src/nvim/normal.c:521
#28 0x00005651435fe87c in main (argc=6, argv=<optimized out>) at .../src/nvim/main.c:660
```
```
vim.treesitter:                       require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: c                    ABI: 14, path: .../lib/nvim/parser/c.so
- OK Parser: lua                  ABI: 14, path: .../lib/nvim/parser/lua.so
- OK Parser: markdown             ABI: 14, path: .../lib/nvim/parser/markdown.so
- OK Parser: markdown_inline      ABI: 14, path: .../lib/nvim/parser/markdown_inline.so
- OK Parser: query                ABI: 14, path: .../lib/nvim/parser/query.so
- OK Parser: vim                  ABI: 14, path: .../lib/nvim/parser/vim.so
- OK Parser: vimdoc               ABI: 14, path: .../lib/nvim/parser/vimdoc.so
- Can load WASM parsers: false
```

Please change the title to something more accurate.

### Steps to reproduce

`init.lua`:
```lua
vim.o.swapfile = false -- convenient after crash here

vim.api.nvim_create_autocmd('FileType', {
  pattern = {'lua'},
  group = vim.api.nvim_create_augroup('luals', {}),
  callback = function ()
    vim.lsp.start({
      name = 'luals',
      filetype = 'lua',
      cmd = {'lua-language-server'},
      root_dir = vim.uv.cwd(),
      settings = {
        Lua = {
          runtime = {
            path = {
              '?.lua',
              '?/init.lua',
            },
            version = 'LuaJIT',
            pathStrict = true,
          },
          workspace = {
            ignoreDir = {'lua'},
            checkThirdParty = false,
            library = {
              vim.fs.joinpath(vim.env.VIMRUNTIME, 'lua'),
              vim.fs.joinpath('${3rd}/luv/library', 'lua'),
            },
          },
          diagnostics = {
            globals = {'vim'},
          },
        },
      },
    })
  end,
})

local completionAugroup = vim.api.nvim_create_augroup('arctgx.completion', {clear = true})

local function showDocumentation(buf, clientId)
  local info = vim.fn.complete_info({'selected'})
  local completionItem = vim.tbl_get(vim.v.completed_item, 'user_data', 'nvim', 'lsp', 'completion_item')
  if nil == completionItem then
    return
  end

  local resolvedItem = vim.lsp.buf_request_sync(
    buf,
    vim.lsp.protocol.Methods.completionItem_resolve,
    completionItem,
    500
  )

  if nil == resolvedItem then
    return
  end

  -- vim.print(resolvedItem[clientId])
  local docs = vim.tbl_get(resolvedItem[clientId], 'result', 'documentation', 'value')
  if nil == docs then
    return
  end

  local winData = vim.api.nvim__complete_set(info['selected'], {info = docs})
  if not winData.winid or not vim.api.nvim_win_is_valid(winData.winid) then
    return
  end

  vim.api.nvim_win_set_config(winData.winid, {border = 'rounded'})

  -- vim.lsp.util.convert_input_to_markdown_lines, documentation.kind <> markdown?
  vim.treesitter.start(winData.bufnr, 'markdown')
  vim.wo[winData.winid].conceallevel = 3
end

vim.api.nvim_create_autocmd('LspAttach', {
group = vim.api.nvim_create_augroup('arctgx.completion', {clear = true}),
  callback = function (args)
    local clientId = args.data.client_id
    vim.lsp.completion.enable(true, clientId, args.buf, {autotrigger = true})

    vim.keymap.set({'i'}, '<C-Space>', function ()
      vim.lsp.completion.trigger()
    end, {buffer = args.buf})

    local client = assert(vim.lsp.get_client_by_id(clientId))
    if client.supports_method(vim.lsp.protocol.Methods.completionItem_resolve, {bufnr = args.buf}) then
      vim.api.nvim_create_autocmd('CompleteChanged', {
        group = completionAugroup,
        buffer = args.buf,
        callback = function ()
          -- vim.print(args.data)
          showDocumentation(args.buf, clientId)
        end,
      })
    end
  end
})

vim.go.completeopt = 'noinsert,menuone'
```

- `nvim --clean -u init.lua init.lua`
- after starting lua-ls type `Ovim.api.`, wait for completion items and using `<C-n>` scroll down to `nvim_cmd`. For me Nvim crashes repeatedly there.

I tried to open printed documentation with treesitter (markdown) but couldn't trigger the failure that way. 

### Expected behavior

No crash

### Nvim version (nvim -v)

v0.11.0-dev-867+g2c88cfcac

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian Sid

### Terminal name/version

alacritty 0.14.0-dev (6585d604), tmux 3.5

### $TERM environment variable

tmux-256color

### Installation

from repo

### LINKED ISSUE #30610: treesitter: `Invalid 'end_row': out of range` on CompleteChanged
### Problem

I get the following error on displaying markdown docs using `vim.api.nvim__complete_set`:
```
Error in decoration provider treesitter/highlighter.line:
Error executing lua: ...rc/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:340: Invalid 'end_row': out of range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...rc/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:340: in function 'fn'
        ...rc/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:213: in function 'for_each_highlight_state'
        ...rc/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:294: in function 'on_line_impl'
        ...rc/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:370: in function <...rc/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:364>
```

### Steps to reproduce

````lua
local docs = {
  [[```lua
function vim.api.nvim__get_lib_dir()
```]],
  [[

@*param*]],
  [[```lua
function vim.api.nvim_cmd(cmd: vim.api.keyset.cmd, opts: vim.api.keyset.cmd_opts)
```]]
}

vim.api.nvim_create_autocmd('CompleteChanged', {
  callback = function ()
    local info = vim.fn.complete_info({'selected'})
    local position = info.selected
    if position == -1 then
      return
    end

    local winData = vim.api.nvim__complete_set(position, {info = docs[1 + position]})

    vim.treesitter.start(winData.bufnr, 'markdown')
  end,
})

vim.keymap.set('i', '<Tab>', function ()
  vim.fn.complete(vim.fn.col('.'), {'nvim__get_lib_dir', 'nvim_buf_set_keymap', 'nvim_cmd'})
end)

vim.cmd.startinsert()
````
With the above init file press `<Tab>` and then `<C-n>` 5 times. 

### Expected behavior

No such errors even on broken markdown code

### Nvim version (nvim -v)

v0.11.0-dev-872+ga0c64fe81

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian Sid

### Terminal name/version

alacritty 0.14.0-dev (6585d604), tmux 3.5

### $TERM environment variable

tmux-256color

### Installation

from repo

### PR DESCRIPTION
**Pull request by glepnir**
Problem: when popup preview buffer has filetype like markdown and ts is enabled, the extmark clean and update not correct, if add the extmark sync there has lots of duplicate codes like nvim_buf_set_lines.

Solution: use nvim_buf_set_lines api internally to set info to popup preview buffer.

Fix #30601
Fix #30610

### CODE REVIEW

**Comment by przepompownia** [comment]
My reproduction suggest that it fixes both #30601 and #30610. Thank you for this PR (and also for lots of work on improving built-in completion).

File: src/nvim/popupmenu.c [hunk 1]
```diff
@@ -784,36 +785,34 @@ void pum_redraw(void)
   }
 }
 
-/// set info text to preview buffer.
 static void pum_preview_set_text(buf_T *buf, char *info, linenr_T *lnum, int *max_width)
```
Comment (justinmk) [inline src/nvim/popupmenu.c:788]: can the docstring be improved instead of deleted?

**Comment by justinmk** [comment]
Haven't looked closely at the code, but this needs a test, right?

**Comment by glepnir** [comment]
yes. currently the tests cover the text addition case. the bug is that when filetype is set to markdown (usually lsp return the doc attribute as markdown) and treesitter is enabled, a quick C-N or C-P will cause problems. But I haven't found a stable reproducible use case yet.

**Comment by przepompownia** [comment]
> Fix #30610 Fix #30610

@glepnir do you mean #30601 in the description?

**Comment by glepnir** [comment]
@przepompownia  the test case is for #30610 . after this patch #30610 also not crash right ? if true i may also need find a test case for it..

**Comment by glepnir** [comment]
I think it is related. so the test case should cover the tressitter crash report.

**Comment by przepompownia** [comment]
Thanks for merging master here again. I keep in mind that it sometimes can be not worth effort when conflicting changes arrive enough frequently.

**Comment by glepnir** [comment]
@justinmk  PTAL

File: src/nvim/popupmenu.c [hunk 2]
```diff
@@ -785,36 +787,41 @@ void pum_redraw(void)
   }
 }
 
-/// set info text to preview buffer.
+/// Set the informational text in the preview buffer when the completion
+/// item does not include a dedicated preview or popup window.
+///
+/// @param[in]  buf        Pointer to the buffer (buf_T) where the text will be set.
+/// @param[in]  info       Informational text to display in the preview buffer.
+/// @param[in]  lnum       Pointer to a line number (linenr_T), indicating where to start the text.
```
Comment (justinmk) [inline src/nvim/popupmenu.c:795]: don't repeat the types in the param descriptions

also, this is a pointer so the more interesting info is that it's updated. a hint about how it's updated would be useful.

I am just guessing about the "incremented for each..." part. please confirm it.

```suggestion
/// @param[in]  lnum       Where to start the text. Incremented for each added line.
```

File: src/nvim/popupmenu.c [hunk 3]
```diff
@@ -785,36 +787,41 @@ void pum_redraw(void)
   }
 }
 
-/// set info text to preview buffer.
+/// Set the informational text in the preview buffer when the completion
+/// item does not include a dedicated preview or popup window.
+///
+/// @param[in]  buf        Pointer to the buffer (buf_T) where the text will be set.
```
Comment (justinmk) [inline src/nvim/popupmenu.c:793]:
```suggestion
/// @param[in]  buf        Buffer where the text will be set.
```

File: src/nvim/popupmenu.c [hunk 4]
```diff
@@ -785,36 +787,41 @@ void pum_redraw(void)
...
+/// @param[in]  info       Informational text to display in the preview buffer.
+/// @param[in]  lnum       Pointer to a line number (linenr_T), indicating where to start the text.
+/// @param[out] max_width  Pointer to an integer to store the maximum width of the displayed text.
```
Comment (justinmk) [inline src/nvim/popupmenu.c:796]:
```suggestion
/// @param[out] max_width  Maximum width of the displayed text.
```

**Review by justinmk — APPROVED** [review]
You wrote the original `pum_preview_set_text` so I'll just assume this is an improvement :)
