### PR TITLE
fix(conceal): invalid row check for concealed lines

### LINKED ISSUE #36057: "conceal_line" callback invoked with `row == -1` when using `scrolloff`
### Problem

In the treesitter highlighter, the `on_conceal_line` callback sometimes gets called with `row == -1` when setting `scrolloff`. This is making it difficult to track injection ranges with extmarks, since this code path requests a parse at row -1, which is invalid. It also probably has unintended effects in the highlighter regardless.

### Steps to reproduce

```lua
-- minimal.lua
vim.o.scrolloff = 8
vim.api.nvim_tabpage_set_win(
  0,
  ({
    vim.lsp.util.open_floating_preview(
      { 'foo', '```lua', 'local bar', '```' },
      'markdown',
      {
        border = 'single',
        focus = true,
      }
    ),
  })[2]
)
```

With this patch:

```patch
diff --git a/src/nvim/decoration_provider.c b/src/nvim/decoration_provider.c
index 3019bd4df4..5e13c66a69 100644
--- a/src/nvim/decoration_provider.c
+++ b/src/nvim/decoration_provider.c
@@ -91,6 +91,7 @@ void decor_providers_invoke_spell(win_T *wp, int start_row, int start_col, int e
 /// @return whether a provider placed any marks in the callback.
 bool decor_providers_invoke_conceal_line(win_T *wp, int row)
 {
+  assert(row != -1);
   size_t keys = wp->w_buffer->b_marktree->n_keys;
   for (size_t i = 0; i < kv_size(decor_providers); i++) {
     DecorProvider *p = &kv_A(decor_providers, i);
```

Run:

```
nvim minimal.lua --clean
:so<CR>
vj
```

Observe the assertion failure. Backtrace:

```
           PID: 218243 (nvim)
           UID: 1000 (jdoe)
           GID: 100 (users)
        Signal: 6 (ABRT)
     Timestamp: Mon 2025-10-06 06:56:37 PDT (2min 41s ago)
  Command Line: /home/jdoe/neovim/bin/nvim --embed --luamod-dev test.lua --clean
    Executable: /home/jdoe/neovim/bin/nvim
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-ghostty-transient-2799.scope/surfaces/560976E5C2C0.scope
          Unit: user@1000.service
     User Unit: app-ghostty-transient-2799.scope
         Slice: user-1000.slice
     Owner UID: 1000 (jdoe)
       Boot ID: c21981ef5c464e7e902cf83b290d2668
    Machine ID: 6541f6ca719247c8b00690cbc51ddae1
      Hostname: computer
       Storage: /var/lib/systemd/coredump/core.nvim.1000.c21981ef5c464e7e902cf83b290d2668.218243.1759758997000000.zst (present)
  Size on Disk: 1.1M
       Message: Process 218243 (nvim) of user 1000 dumped core.
                
                Module /home/jdoe/neovim/bin/nvim without build-id.
                Module markdown_inline.so without build-id.
                Module markdown.so without build-id.
                Module lua.so without build-id.
                Module libgcc_s.so.1 without build-id.
                Stack trace of thread 218243:
                #0  0x00007f04ab49caac __pthread_kill_implementation (libc.so.6 + 0x9caac)
                #1  0x00007f04ab44190e raise (libc.so.6 + 0x4190e)
                #2  0x00007f04ab428942 abort (libc.so.6 + 0x28942)
                #3  0x00007f04ab42885e __assert_fail_base.cold (libc.so.6 + 0x2885e)
                #4  0x00007f04ab4396f7 __assert_fail (libc.so.6 + 0x396f7)
                #5  0x00000000004d1b32 decor_providers_invoke_conceal_line (/home/jdoe/neovim/bin/nvim + 0xd1b32)
                #6  0x00000000004cfa53 decor_conceal_line (/home/jdoe/neovim/bin/nvim + 0xcfa53)
                #7  0x000000000061f48e update_topline (/home/jdoe/neovim/bin/nvim + 0x21f48e)
                #8  0x00000000004ed70c cursor_down (/home/jdoe/neovim/bin/nvim + 0xed70c)
                #9  0x0000000000628dea nv_down (/home/jdoe/neovim/bin/nvim + 0x228dea)
                #10 0x000000000062eecb normal_execute (/home/jdoe/neovim/bin/nvim + 0x22eecb)
                #11 0x00000000006e0eda state_enter (/home/jdoe/neovim/bin/nvim + 0x2e0eda)
                #12 0x000000000062b939 normal_enter (/home/jdoe/neovim/bin/nvim + 0x22b939)
                #13 0x00000000004630d8 main (/home/jdoe/neovim/bin/nvim + 0x630d8)
                #14 0x00007f04ab42a4d8 __libc_start_call_main (libc.so.6 + 0x2a4d8)
                #15 0x00007f04ab42a59b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a59b)
                #16 0x00000000004651d5 _start (/home/jdoe/neovim/bin/nvim + 0x651d5)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 16.3
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/jdoe/neovim/bin/nvim...

warning: Can't open file anon_inode:[io_uring] during file-backed mapping note processing
[New LWP 218243]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/776irwlgfb65a782cxmyk61pck460fs9-glibc-2.40-66/lib/libthread_db.so.1".
Core was generated by `/home/jdoe/neovim/bin/nvim --embed --luamod-dev test.lua --clean'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f04ab49caac in __pthread_kill_implementation () from /nix/store/776irwlgfb65a782cxmyk61pck460fs9-glibc-2.40-66/lib/libc.so.6
Thread 1 (Thread 0x7f04ab65d740 (LWP 218243)):
#0  0x00007f04ab49caac in __pthread_kill_implementation () from /nix/store/776irwlgfb65a782cxmyk61pck460fs9-glibc-2.40-66/lib/libc.so.6
No symbol table info available.
#1  0x00007f04ab44190e in raise () from /nix/store/776irwlgfb65a782cxmyk61pck460fs9-glibc-2.40-66/lib/libc.so.6
No symbol table info available.
#2  0x00007f04ab428942 in abort () from /nix/store/776irwlgfb65a782cxmyk61pck460fs9-glibc-2.40-66/lib/libc.so.6
No symbol table info available.
#3  0x00007f04ab42885e in __assert_fail_base.cold () from /nix/store/776irwlgfb65a782cxmyk61pck460fs9-glibc-2.40-66/lib/libc.so.6
No symbol table info available.
#4  0x00007f04ab4396f7 in __assert_fail () from /nix/store/776irwlgfb65a782cxmyk61pck460fs9-glibc-2.40-66/lib/libc.so.6
No symbol table info available.
#5  0x00000000004d1b32 in decor_providers_invoke_conceal_line (wp=wp@entry=0x11b97210, row=row@entry=-1) at /home/jdoe/Documents/CodeProjects/neovim/src/nvim/decoration_provider.c:94
        __PRETTY_FUNCTION__ = "decor_providers_invoke_conceal_line"
        keys = <optimized out>
#6  0x00000000004cfa53 in decor_conceal_line (wp=wp@entry=0x11b97210, row=-1, check_cursor=check_cursor@entry=false) at /home/jdoe/Documents/CodeProjects/neovim/src/nvim/decoration.c:902
        pair = {start = {pos = {row = 2, col = 32767}, ns = 1136145152, id = 1089770029, flags = 62496, decor_data = {hl = {flags = 3, priority = 0, hl_id = 0, conceal_char = 3}, ext = {sh_idx = 3, vt = 0x3}}}, end_pos = {row = 0, col = 0}, end_right_gravity = false}
        itr = {{pos = {row = 0, col = 0}, lvl = 0, x = 0x11c45580, i = 0, s = {{oldcol = 1089770029, i = 0}, {oldcol = 0, i = 1136145152}, {oldcol = 1089770029, i = 297366032}, {oldcol = 0, i = 3}, {oldcol = 0, i = 3}, {oldcol = 0, i = 1}, {oldcol = 0, i = 0}, {oldcol = 0, i = 297366032}, {oldcol = 0, i = -1543424672}, {oldcol = 32767, i = 5769690}, {oldcol = 0, i = 2}, {oldcol = 0, i = 1136145152}, {oldcol = 1089770029, i = 0}, {oldcol = 0, i = 1136145152}, {oldcol = 1089770029, i = 297366032}, {oldcol = 0, i = 3}, {oldcol = 0, i = -1543424520}, {oldcol = 32767, i = 0}, {oldcol = 0, i = -1543424624}, {oldcol = 32767, i = 6686459}}, intersect_idx = 0, intersect_pos = {row = -1, col = 0}, intersect_pos_x = {row = -1, col = 0}}}
#7  0x000000000061f48e in update_topline (wp=0x11b97210) at /home/jdoe/Documents/CodeProjects/neovim/src/nvim/move.c:404
        lnum = 0
        line_count = 2
        check_botline = true
        so_ptr = 0x9e08d8 <p_so>
        save_so = <optimized out>
        old_topline = 1
        old_topfill = 0
        __PRETTY_FUNCTION__ = "update_topline"
#8  0x00000000004ed70c in cursor_down (n=1, upd_topline=<optimized out>) at /home/jdoe/Documents/CodeProjects/neovim/src/nvim/edit.c:2534
        lnum = 1
#9  0x0000000000628dea in nv_down (cap=0x7fffa4013790) at /home/jdoe/Documents/CodeProjects/neovim/src/nvim/normal.c:3860
No locals.
#10 nv_down (cap=0x7fffa4013790) at /home/jdoe/Documents/CodeProjects/neovim/src/nvim/normal.c:3838
No locals.
#11 0x000000000062eecb in normal_execute (state=0x7fffa4013720, key=<optimized out>) at /home/jdoe/Documents/CodeProjects/neovim/src/nvim/normal.c:1245
        s = 0x7fffa4013720
        __PRETTY_FUNCTION__ = "normal_execute"
#12 0x00000000006e0eda in state_enter (s=s@entry=0x7fffa4013720) at /home/jdoe/Documents/CodeProjects/neovim/src/nvim/state.c:100
        check_result = <optimized out>
        key = <optimized out>
        execute_result = <optimized out>
        getkey = <optimized out>
#13 0x000000000062b939 in normal_enter (cmdwin=cmdwin@entry=false, noexmode=noexmode@entry=false) at /home/jdoe/Documents/CodeProjects/neovim/src/nvim/normal.c:522
        state = {state = {check = 0x62d770 <normal_check>, execute = 0x62e970 <normal_execute>}, command_finished = false, ctrl_w = false, need_flushbuf = true, set_prevcount = false, previous_got_int = false, cmdwin = false, noexmode = false, toplevel = true, oa = {op_type = 0, regname = 0, motion_type = kMTLineWise, motion_force = 0, use_reg_one = false, inclusive = false, end_adjusted = false, start = {lnum = 0, col = 0, coladd = 0}, end = {lnum = 0, col = 0, coladd = 0}, cursor_start = {lnum = 0, col = 0, coladd = 0}, line_count = 0, empty = false, is_VIsual = false, start_vcol = 0, end_vcol = 0, prev_opcount = 0, prev_count0 = 0, excl_tr_ws = false}, ca = {oap = 0x7fffa4013738, prechar = 0, cmdchar = 106, nchar = 0, nchar_composing = '\000' <repeats 31 times>, nchar_len = 0, extra_char = 0, opcount = 0, count0 = 0, count1 = 1, arg = 0, retval = 0, searchbuf = 0x0}, mapped_len = 0, old_mapped_len = 0, idx = 107, c = 106, old_col = 0, old_pos = {lnum = 1, col = 0, coladd = 0}}
        prev_oap = 0x0
#14 0x00000000004630d8 in main (argc=<optimized out>, argv=<optimized out>) at /home/jdoe/Documents/CodeProjects/neovim/src/nvim/main.c:655
        fname = <optimized out>
        params = {argc = 5, argv = 0x7fffa4013cc8, use_vimrc = 0x848c5f "NONE", clean = true, n_commands = 0, commands = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, cmds_tofree = "\000\000\000\000\000\000\000\000\000", n_pre_commands = 0, pre_commands = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, luaf = 0x0, lua_arg0 = -1, edit_type = 1, tagname = 0x0, use_ef = 0x0, input_istext = false, no_swap_file = 0, use_debug_break_level = -1, window_count = 1, window_layout = 0, diff_mode = 0, listen_addr = 0x0, remote = 0, server_addr = 0x0, scriptin = 0x0, scriptout = 0x0, scriptout_append = false, had_stdin_file = false}
        cwd = <optimized out>
        has_term = <optimized out>
        use_builtin_ui = <optimized out>
        remote_ui = false
        __PRETTY_FUNCTION__ = "main"
        use_remote_ui = <optimized out>
        listen_and_embed = <optimized out>
        vimrc_none = <optimized out>
```

cc @luukvbaal 

### Expected behavior

This should not be called with `row == -1` (either it should not be called, or it should be called with a correct row value?)

### Nvim version (nvim -v)

Nightly e7a03dd4e8792d49c4c34fcc8a5bd981a0310208

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

NixOS 25.11

### Terminal name/version

Ghostty 1.2.0

### $TERM environment variable

xterm-ghostty

### Installation

nixos nightly overlay

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  May check for concealed lines on invalid line numbers.
Solution: Move checks after line number validation.

Fix #36057

### CODE REVIEW

File: src/nvim/move.c [hunk 1]
```diff
@@ -322,12 +322,12 @@ void update_topline(win_T *wp)
         // scrolled).
         n = 0;
         for (linenr_T lnum = wp->w_cursor.lnum; lnum < wp->w_topline + *so_ptr; lnum++) {
-          n += !decor_conceal_line(wp, lnum, false);
           // stop at end of file or when we know we are far off
           assert(wp->w_buffer != 0);
           if (lnum >= wp->w_buffer->b_ml.ml_line_count || n >= halfheight) {
             break;
           }
+          n += !decor_conceal_line(wp, lnum, false);
```
Comment (zeertzjq) [inline src/nvim/move.c]:
```suggestion
          if (lnum >= wp->w_buffer->b_ml.ml_line_count
              || (n += !decor_conceal_line(wp, lnum, false)) >= halfheight) {
            break;
          }
```

File: src/nvim/move.c [hunk 2]
```diff
@@ -401,11 +401,11 @@ void update_topline(win_T *wp)
           // botline - p_so (approximation of how much will be
           // scrolled).
           for (linenr_T lnum = wp->w_cursor.lnum; lnum >= wp->w_botline - *so_ptr; lnum--) {
-            line_count += !decor_conceal_line(wp, lnum - 1, false);
             // stop at end of file or when we know we are far off
             if (lnum <= 0 || line_count > wp->w_view_height + 1) {
               break;
             }
+            line_count += !decor_conceal_line(wp, lnum - 1, false);
```
Comment (zeertzjq) [inline src/nvim/move.c]:
```suggestion
            if (lnum <= 0
                || (line_count += !decor_conceal_line(wp, lnum - 1, false))
                > wp->w_view_height + 1) {
              break;
            }
```

File: src/nvim/move.c (hunk 1 above)
Comment (luukvbaal) [reply src/nvim/move.c]: Is this a stylistic suggestion? I don't think it matters logically?

Comment (zeertzjq) [reply src/nvim/move.c]: It avoid an unnecessary `hasFolding()` call.

File: test/functional/plugin/lsp/utils_spec.lua [hunk 3]
```diff
@@ -407,6 +407,10 @@ describe('vim.lsp.util', function()
       {1:~                                                    }|*8
                                                            |
     ]])
+    -- Not checking for concealed line on invalid line number #36057.
+    command('set scrolloff=3')
+    feed('ggvj')
```
Comment (justinmk) [inline test/functional/plugin/lsp/utils_spec.lua]: a bit risky for this to live in `test/functional/plugin/lsp/utils_spec.lua` since we have plans to remove much of `lsp.utils`.

not a blocker.

**Review by justinmk — APPROVED** [review]
