### PR TITLE
fix(api): `nvim_set_keymap` throws error even when called in `pcall`

### LINKED ISSUE #33128: `nvim_set_keymap` throws error even when called with `pcall`
### Problem

When using `pcall` to wrap a fallible keymap creation the error is not caught and is thrown to the user.
```
E227: Mapping already exists for ^A
```

### Steps to reproduce

```
nvim --clean
:lua vim.api.nvim_set_keymap("n", "<C-a>", ':echo "first keymap"', {})
:lua pcall(vim.api.nvim_set_keymap, "n", "<C-a>", ':echo "second keymap"', { unique = true })
```

### Expected behavior

`pcall` catches the error and is not shown to the user.

### Nvim version (nvim -v)

Both master and 0.11: `NVIM v0.12.0-dev-22+g5554fcc286`, `NVIM v0.11.0`

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

Built from repo (master), official Arch package (0.11)

### PR DESCRIPTION
**Pull request by tstsrt**
Problem: When `nvim_set_keymap` tries to overwrite a `<unique>` mapping, it throws an error even when called in `pcall`.
Solution: src/nvim/mapping.c:buf_do_map no longer calls `semsg`. Its callers now decide whether to ignore the error, or use `semsg` (not caught)/`api_set_error` (caught by `pcall`).

Fixes #33128

### CODE REVIEW

**Review by zeertzjq — CHANGES_REQUESTED** [review]

File: src/nvim/mapping.c [hunk 1]
```diff
@@ -2798,15 +2820,21 @@ void modify_keymap(uint64_t channel_id, Buffer buffer, bool is_unmap, String mod
...
-                            : e_mapping_already_exists_for_str, lhs.data);
+    if (parsed_args.buffer) {
+      api_set_error(err, kErrorTypeException,
+                    is_abbrev ? _(e_abbreviation_already_exists_for_str)
+                              : _(e_mapping_already_exists_for_str), lhs.data);
+    } else {
+      api_set_error(err, kErrorTypeException,
+                    is_abbrev ? _(e_global_abbreviation_already_exists_for_str)
+                              : _(e_global_mapping_already_exists_for_str), lhs.data);
+    }
```
[the remark this answers is not in the document]
Comment (tstsrt) [reply src/nvim/mapping.c:2837]: You're right. This can be fixed if `buf_do_map` returns a different error code (say 6) for the global vs local case. Since this error code is returned by `do_map`, which is exported, I can either keep it backwards compatible by converting the new error code back to 5, or change the behaviour of `do_map`. Which option is preferred?

[the remark this answers is not in the document]
Comment (zeertzjq) [reply src/nvim/mapping.c]: > If this is too ugly and `do_map`'s contract can be changed, I can let it return 6.

Yes, you can.

File: src/nvim/mapping.c [hunk 2]
```diff
@@ -2637,16 +2628,47 @@ static void do_exmap(exarg_T *eap, int isabbrev)
...
+    break;
+  case 1:
+    emsg(_(e_invarg));
+    goto free_rhs;
+    break;
+  default:
+    assert(false && "Unknown return code from str_to_mapargs!");
+    goto free_rhs;
+  }
+  switch (buf_do_map(maptype, &parsed_args, mode, isabbrev, curbuf)) {
```
Comment (zeertzjq) [inline src/nvim/mapping.c:2652]: This is now the same as what `do_map()` does.

Comment (tstsrt) [reply src/nvim/mapping.c:2652]: Not quite, since we need `parsed_args.lhs` for the error message, which `do_map` doesn't return.

Comment (zeertzjq) [reply src/nvim/mapping.c:2652]: Oh, right.

File: src/nvim/mapping.c [hunk 3]
```diff
@@ -2798,15 +2820,21 @@ void modify_keymap(uint64_t channel_id, Buffer buffer, bool is_unmap, String mod
...
-                            : e_mapping_already_exists_for_str, lhs.data);
+                  is_abbrev ? _(e_abbreviation_already_exists_for_str)
+                            : _(e_mapping_already_exists_for_str), lhs.data);
+    goto fail_and_free;
+    break;
+  case 6:
+    api_set_error(err, kErrorTypeException,
+                  is_abbrev ? _(e_global_abbreviation_already_exists_for_str)
+                            : _(e_global_mapping_already_exists_for_str), lhs.data);
     goto fail_and_free;
```
Comment (zeertzjq) [inline src/nvim/mapping.c:2838]: API errors should not be translated. See https://github.com/neovim/neovim/issues/18128#issuecomment-1107946770

**Review by zeertzjq — APPROVED** [review]
