### PR TITLE
fix(column): full redraw with 'stc, 'rnu' and inserted lines

### LINKED ISSUE #27709: When using a custom statuscolumn, an increase in the number width doesn't redraw lines properly
### Problem

When `numberwidth` is set to `3`, and a buffer is changed such that the width needs to be increased to `4`, _and_ a custom `statuscolumn` is set, the width change doesn't properly redraw all lines. The result is that the number/status column overlays one column of the buffer, until you somehow force a redraw or move the cursor around:

[Screencast from 2024-03-02 22-22-50.webm](https://github.com/neovim/neovim/assets/86065/21321001-8512-4f07-affe-71b6fb23ec05)

### Steps to reproduce

Create `repro.lua` with these contents:

```lua
vim.opt.numberwidth = 3
vim.opt.statuscolumn = '%s%=%{&relativenumber ? (v:virtnum == 0 ? (v:relnum > 0 ? v:relnum : v:lnum) : " ") : ""} '
vim.opt.relativenumber = true
vim.opt.number = true

local lines = {}

for i = 1, 99 do
	table.insert(lines, "line " .. i)
end

vim.api.nvim_buf_set_lines(0, 0, #lines - 1, false, lines)
```

Now run `nvim --clean -u repro.lua`, then:

1. Press `G` to go to the bottom of the buffer
2. Press `o` to create a new empty line
3. Observe how in the lines above the text changes from "line NN" to "ine NN"

When doing so, the following happens:

[asciicast](https://asciinema.org/a/nfBRPU3ZajtcNx5iMLuWBU10w)

`:redraw` doesn't help, but pressing `Control+L` does (which is what triggers the redraw at the end of the recording).

### Expected behavior

Lines are redrawn properly such that all buffer text remains visible.

### Neovim version (nvim -v)

b12d193b4a

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

Ghostty

### $TERM environment variable

xterm-ghostty

### Installation

AUR

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  Text is not redrawn with 'relativenumber' when only the 'statuscolumn' is redrawn after inserted lines.
Solution: Force a full redraw if statuscolumn width changed.

Fix #27709

### CODE REVIEW

File: test/functional/ui/statuscolumn_spec.lua [hunk 1]
```diff
@@ -927,4 +927,17 @@ describe('statuscolumn', function()
                                        |
     ]])
   end)
+
+  it('line increase properly redraws buffer text with relativenumber', function()
+    screen:try_resize(33, 4)
+    command('set rnu nuw=3 stc=%l\\ ')
```
Comment (zeertzjq) [inline test/functional/ui/statuscolumn_spec.lua:933]:
```suggestion
    command([[set rnu nuw=3 stc=%l\ ]])
```

File: test/functional/ui/statuscolumn_spec.lua [hunk 2]
```diff
@@ -927,4 +927,17 @@ describe('statuscolumn', function()
                                        |
     ]])
   end)
+
+  it('line increase properly redraws buffer text with relativenumber', function()
```
Comment (gpanders) [inline test/functional/ui/statuscolumn_spec.lua:931]:
```suggestion
  it('line increase properly redraws buffer text with relativenumber #27709', function()
```

**Review by zeertzjq — APPROVED** [review]
