### PR TITLE
fix(log): unintuitive message for undefined $TMPDIR

### LINKED ISSUE #31757: log: `$TMPDIR tempdir not a directory (or does not exist): $TMPDIR` when the variable is not set or null
### Problem

If nvim needs to create a temporary directory but `TMPDIR` environment variable *is unset or null*, log file has a warning like the following:
```
WRN 2024-12-28T21:24:45.965 nvim.32125.0 vim_mktempdir:3279: $TMPDIR tempdir not a directory (or does not exist): $TMPDIR
```

https://github.com/neovim/neovim/blob/48c09ed4d9edd92a7c665a62aed04e8597088e60/src/nvim/os/unix_defs.h#L17
https://github.com/neovim/neovim/blob/48c09ed4d9edd92a7c665a62aed04e8597088e60/src/nvim/fileio.c#L3275-L3282

### Steps to reproduce

Here diff is used for explanation.

```vim
" mwe.vim
set diffexpr=MyDiff()
function MyDiff()
   silent execute "!diff " .. v:fname_in .. " " .. v:fname_new .. " > " .. v:fname_out
   redraw!
endfunction

```

```sh
#!/bin/bash
NVIM_LOG_FILE=$(mktemp)
export NVIM_LOG_FILE

vim=nvim
case "$vim" in
  nvim)
    opts=(--headless);;
  vim)
    opts=(--log "$NVIM_LOG_FILE");;
esac

# when TMPDIR is not set
unset TMPDIR
"$vim" "${opts[@]}" -d -u mwe.vim -c qa a b
cat "$NVIM_LOG_FILE"
rm -f "$NVIM_LOG_FILE"

# when TMPDIR is set to empty
export TMPDIR=
"$vim" "${opts[@]}" -d -u mwe.vim -c qa a b
cat "$NVIM_LOG_FILE"
rm -f "$NVIM_LOG_FILE"
```

### Expected behavior

State that the environment variable is not set or empty (with lower level?):
```
WRN 2024-12-28T21:24:45.965 nvim.32125.0 vim_mktempdir:3279: $TMPDIR is unset or null
```

or expand it:

```
WRN 2024-12-28T21:24:45.965 nvim.32125.0 vim_mktempdir:3279: $TMPDIR tempdir not a directory (or does not exist): 
```

### Nvim version (nvim -v)

v0.11.0-dev-48c09ed4d9ed

### Vim (not Nvim) behaves the same?

no, vim 9.1.954

### Operating system/version

EndeavourOS

### Terminal name/version

GNOME Terminal 3.54.2 using VTE 0.78.2 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by deepsghimire**
fixes #31757
Problem:
If $TMPDIR is unset or null, logs show that
$TMPDIR is not directory.

Solution:
Check if $TMPDIR is unset or empty and output log accurately

### CODE REVIEW

**Comment by deepsghimire** [comment]
I am trying to figure out why the tests failed on macOS. Could this failed check on macOS be related to [this snippet](https://github.com/neovim/neovim/blob/master/test/functional/lua/watch_spec.lua#L93-L96)?

**Comment by glepnir** [comment]
Not relevant to this PR :)

**Comment by e-kwsm** [comment]
I don’t know the function of expand_env in detail, but it seems to return as is if the variable is unset or empty, whereas
https://github.com/neovim/neovim/blob/259573db831755ba55276f49f963679164dcb1b0/src/nvim/os/env.c#L59-L61

File: src/nvim/fileio.c [hunk 1]
```diff
@@ -3276,7 +3276,11 @@ static void vim_mktempdir(void)
     expand_env((char *)temp_dirs[i], tmp, TEMP_FILE_PATH_MAXLEN - 64);
     if (!os_isdir(tmp)) {
       if (strequal("$TMPDIR", temp_dirs[i])) {
-        WLOG("$TMPDIR tempdir not a directory (or does not exist): %s", tmp);
+        if (!os_getenv("TMPDIR")) {
+          WLOG("$TMPDIR is unset or null");
+        } else {
+          WLOG("$TMPDIR tempdir not a directory (or does not exist): %s", os_getenv("TMPDIR"));
```
Comment (justinmk) [inline src/nvim/fileio.c:3282]: why did you change this from `tmp`

Comment (deepsghimire) [reply src/nvim/fileio.c:3282]: I thought expanding `$TMPDIR` was a good idea, but since `expand_env` function does that already(if possible) there was no need to change. I will change this back to tmp promptly.

PS: Sorry for being late.

File: src/nvim/fileio.c [hunk 2]
```diff
@@ -3276,7 +3276,11 @@ static void vim_mktempdir(void)
     expand_env((char *)temp_dirs[i], tmp, TEMP_FILE_PATH_MAXLEN - 64);
     if (!os_isdir(tmp)) {
       if (strequal("$TMPDIR", temp_dirs[i])) {
-        WLOG("$TMPDIR tempdir not a directory (or does not exist): %s", tmp);
+        if (!os_getenv("TMPDIR")) {
+          WLOG("$TMPDIR is unset or null");
```
Comment (justinmk) [inline src/nvim/fileio.c:3280]:
```suggestion
          WLOG("$TMPDIR is unset");
```

File: src/nvim/fileio.c [hunk 3]
```diff
@@ -3276,7 +3276,11 @@ static void vim_mktempdir(void)
...
+        } else {
+          WLOG("$TMPDIR tempdir not a directory (or does not exist): %s", tmp);
```
Comment (justinmk) [inline src/nvim/fileio.c:3282]: while we're here, let's add quotes so that the "empty string" case is more obvious. this might require updating a test (can just see if CI passes)


```suggestion
          WLOG("$TMPDIR tempdir not a directory (or does not exist): \"%s\"", tmp);
```

**Comment by deepsghimire** [comment]
Hi @justinmk,

I hope you're doing well. I noticed that this PR has not been merged yet, and I wanted to check if there's anything I might be missing or any changes required from my side to help move it forward. Please let me know if there's anything I can do to assist.

Thank you!

**Comment by justinmk** [comment]
@deepsghimire thanks for the ping, I missed this or was waiting for an update. It also helps reviewers to rebase PRs occasionally.
