### PR TITLE
fix(completion): wrong CompleteDone reason for auto-inserted sole match

### LINKED ISSUE #38160: `CompleteDone` reason = discard when accepting the only possible match
### Problem

With `completeopt=menu` (as opposed to `menuone`, and specifically without `noinsert`), if there's a single possible completion match, it gets inserted into the buffer automatically without opening the `ins-completion` menu. However, the `CompleteDone` event that fires will set `vim.v.event.reason = "discard"` rather than `"accept"`, even though `vim.v.completed_item` does correctly reflect the sole match that gets selected.

Previously, #32600 amended the `CompleteDone` event with the `discard` reason to distinguish it from `cancel`. But it appears to have missed this edge case where `accept` seems more appropriate (unless I'm missing something).

This has downstream implications for `vim.lsp.completion`, which only applies side-effects (additional edits, snippet expansion, etc) when `reason == "accept"`: https://github.com/neovim/neovim/blob/6beb1fe0cd686cd0fe8a2a5f72704f7d1bbd252c/runtime/lua/vim/lsp/completion.lua#L889-L892 That said, if I patch this locally to always call `on_complete_done()`, there does seem to be a separate issue downstream of *that* where additional LSP text edits that I'm expecting are prevented by the logic here: https://github.com/neovim/neovim/blob/6beb1fe0cd686cd0fe8a2a5f72704f7d1bbd252c/runtime/lua/vim/lsp/completion.lua#L795-L801 So it could be that the insertion of the only match is updating `changedtick` in a way that's not anticipated by LSP completion either. But that's a separate issue I haven't fully dug into.

### Steps to reproduce

repro.lua

```lua
vim.o.completeopt = "menu"

local group = vim.api.nvim_create_augroup("repro", { clear = true })

vim.api.nvim_create_autocmd("CompleteDone", {
  group = group,
  callback = function()
    vim.print({
      event = vim.v.event,
      completed_item = vim.v.completed_item,
    })
  end,
})

vim.api.nvim_create_autocmd("UIEnter", {
  group = group,
  callback = function()
    local keys = vim.api.nvim_replace_termcodes("itest<cr><c-n><esc>", true, false, true)
    vim.fn.feedkeys(keys, "nt")
  end,
})
```

```console
$ nvim --clean -u repro.lua
```

After some setup to ensure `completeopt=menu` and to add some debug printing around the `CompleteDone` event, this repro will add the word `test` to the buffer, then use `<c-n>` to trigger keyword completion. With `test` being the only keyword, that's what gets inserted. However, the data set for `CompleteDone` tells a different story:

```
{
  completed_item = {
    abbr = "",
    info = "",
    kind = "",
    menu = "",
    user_data = "",
    word = "test"
  },
  event = {
    complete_type = "keyword",
    complete_word = "",
    reason = "discard"
  }
}
```

### Expected behavior

I expected `event.reason` to be `"accept"`, as the acceptance of the first/only result is automatic in this configuration. I also would expect `event.complete_word` to be `"test"` rather than empty in this repro.

### Nvim version (nvim -v)

NVIM v0.11.6 Build type: Release LuaJIT 2.1.1767980792

### Vim (not Nvim) behaves the same?

no, vim doesn't include the `reason` key at all in `v:event` (AFAICT)

### Operating system/version

macOS 26.3

### Terminal name/version

WezTerm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

Homebrew

### PR DESCRIPTION
**Pull request by glepnir**
Problem: #38169 used compl_used_match to determine the CompleteDone reason, but this fires too broadly, it also changes the reason to "accept" when the popup was shown and the user dismissed it with <Esc> or <Space>, breaking snippet completion with autocomplete.

Solution: Instead of checking compl_used_match in, check whether the pum was never shown (compl_match_array == NULL) in ins_compl_stop(). When a match was inserted but the pum never displayed, set the completed word so CompleteDone fires with reason "accept". This keeps the "discard" reason intact when the user dismisses a visible pum without confirming.

cc @gravndal

Fix #38160

### CODE REVIEW

File: src/nvim/insexpand.c [hunk 1]
```diff
@@ -2646,6 +2646,16 @@ static bool ins_compl_stop(const int c, const int prev_mode, bool retval)
     redrawWinline(curwin, curwin->w_cursor.lnum);
   }
 
+  // When a match was inserted but the pum was never displayed
+  // (eg: only one match with 'completeopt' "menu" without "menuone"),
+  // the user had no opportunity to explicitly accept or dismiss it,
```
Comment (gravndal) [inline src/nvim/insexpand.c:2651]: This isn't actually true, though the exact behaviour for some types of ins completion can depend on (at least) if `cot+=longest` is set.

E.g. try:

```
$ nvim --clean
ihello world<CR><C-X><C-L><C-E>
```

Notice that you're still in complete mode and can cancel (or accept) the completion after doing `<C-X><C-L>`.

Setting `cot+=longest` here would make it so the text remains in the buffer when cancelling, though this might just be a bug, I'm not too sure.

---

Anyway, I tested this and it works fine. Cancelling is still possible, and as there's nothing to indicate if something's a snippet, etc, this feature makes sense.

Though, would it be possible to make this configurable with a completeopt like `cot+=acceptsinglematch` or something like that?

Comment (glepnir) [reply src/nvim/insexpand.c:2651]: > Setting cot+=longest here would make it so the text remains in the buffer when cancelling, though this might just be a bug, I'm not too sure.
 
 This behavior also exists in Vim. When `longest` is active, `compl_leader` gets set to the first completion item `(test)` in `ins_compl_longest_match`. As a result, after deleting and restoring the text, the value remains `test` 😮‍💨 It looks like a bug. I’ll try submitting a pr to vim later.
