### PR TITLE
vim-patch:9.1.1507: symlinks are resolved on :cd commands

### LINKED ISSUE #15695: :cd causes the path of open files in sym-linked directories to change to their target path instead
### Neovim version (nvim -v)

NVIM v0.5.0

### Vim (not Nvim) behaves the same?

Yes.  Vim 8.2

### Operating system/version

macOS 11.6

### Terminal name/version

Terminal with zsh

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

* Create a temporary directory
* Create a sub directory named `source`
* Create a file inside `source` named `foo.txt`
* Execute `ln -s ./source ./dest` from the temporary directory
* `nvim -u NONE`
* `:e [PATH_TO_DEST]/foo.txt`
* `:echo expand('%')`
* Note that this displays the `dest` directory
* `:cd`
* `echo expand('%')`
* Note that this now displays the `source` directory

### Expected behavior

When editing a file inside a sym-linked directory, it would be really helpful if neovim continued to use the linked path instead of the source path at all times, instead of suddenly changing to the source path during seemingly unrelated commands.  Alternatively, it would be good to document what the actual intended behaviour is around editing files inside sym linked directories.

### Actual behavior

Neovim changes the path for open sym-linked files to the source path after executing certain commands like `cd`

### PR DESCRIPTION
**Pull request by glepnir**
Problem:  File paths change from symlink to target path after :cd command
          when editing files through symbolic links
Solution: Add "~" flag to 'cpoptions' to control symlink resolution.
          When not included (default), symlinks are resolved maintaining
          backward compatibility. When included, symlinks are preserved
          providing the improved behavior. (glepnir)

related: neovim/neovim#15695
closes: vim/vim#17628

https://github.com/vim/vim/commit/4ade668fb62ebf3f8be537fe451caed6bd1eba9

Fix https://github.com/neovim/neovim/issues/15695

### CODE REVIEW

File: src/nvim/ex_docmd.c [hunk 1]
```diff
@@ -6016,7 +6016,7 @@ static void post_chdir(CdScope scope, bool trigger_dirchanged)
   }
 
   last_chdir_reason = NULL;
-  shorten_fnames(true);
+  shorten_fnames(strchr(p_cpo, CPO_NOSYMLINKS) == NULL);
```
Comment (zeertzjq) [inline src/nvim/ex_docmd.c]:
```suggestion
  shorten_fnames(vim_strchr(p_cpo, CPO_NOSYMLINKS) == NULL);
```

File: test/old/testdir/test_options.vim [hunk 2]
```diff
@@ -2528,7 +2528,7 @@ func Test_string_option_revert_on_failure()
         "\ ['completepopup', 'width:20', 'border'],
         \ ['concealcursor', 'v', 'xyz'],
         "\ ['cpoptions', 'HJ', '~'],
```
Comment (zeertzjq) [inline test/old/testdir/test_options.vim]:
```suggestion
        "\ ['cpoptions', 'HJ', 'Q'],
```

File: test/old/testdir/test_options.vim
Comment (zeertzjq) [inline test/old/testdir/test_options.vim:1]: Missing change in `Test_VIM_POSIX()`

File: src/nvim/options.lua [hunk 3]
```diff
@@ -2002,6 +2002,13 @@ local options = {
         		character, the cursor won't move. When not included,
         		the cursor would skip over it and jump to the
         		following occurrence.
+                                                                *cpo-~*
+                ~       When included, don't resolve symbolic links when
+                        changing directory with |:cd|, |:lcd|, or |:tcd|.
+                        This preserves the symbolic link path in buffer names
+                        and when displaying the current directory.  When
+                        excluded (default), symbolic links are resolved to
+                        their target paths.
```
Comment (zeertzjq) [inline src/nvim/options.lua]: Please following the indent of other items
```suggestion
        							*cpo-~*
        	~	When included, don't resolve symbolic links when
        		changing directory with |:cd|, |:lcd|, or |:tcd|.
        		This preserves the symbolic link path in buffer names
        		and when displaying the current directory.  When
        		excluded (default), symbolic links are resolved to
        		their target paths.
```

Comment (glepnir) [reply src/nvim/options.lua]: I'm curious about the indentation symbol here. I used space formatting and pasted but there is still a problem. It seems to have been the same before.

**Review by zeertzjq — APPROVED** [review]

File: src/nvim/options.lua (hunk 3 above)
Comment (glepnir) [reply src/nvim/options.lua]: oh it's tab.. i set the tab symbol to space in `listchars` ...then i got mixed up sry.....
