### PR TITLE
fix(highlight): correct hi command output

### LINKED ISSUE #23474: Having `default = true` in `nvim_set_hl()` results into unnecessary `cterm= gui=` in output of `:hi`
### Problem

Having `default = true` in `nvim_set_hl()` always adds `cterm= gui=`, although it probably shouldn't and is relatively harmless.

### Steps to reproduce

1. `nvim --clean`
2. `:lua vim.api.nvim_set_hl(0, 'AAA', { default = true })`
3. `:hi AAA`. It shows `AAA            xxx cterm= gui=`. Although I'd expect it to show `AAA            xxx cleared` as is with Vimscript equivalent `:hi default AAA NONE`. 
    Also, `:=vim.api.nvim_get_hl(0, { name = 'AAA' })` shows `vim.empty_dict()`, as expected.
5. `:lua vim.api.nvim_set_hl(0, 'BBB', { default = true, fg = '#ffffff' })`.
6. `:hi BBB` shows `BBB            xxx cterm= gui= guifg=#ffffff` instead of expected `BBB            xxx guifg=#ffffff`. Again, `:=vim.api.nvim_get_hl(0, { name = 'BBB' })` shows `{ fg = 16777215 }`, as expected.

### Expected behavior

Adding `default = true` to options of `nvim_set_hl()` makes no difference on output of `:hi ...`.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-259+g143a17833

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.2.13-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

### PR DESCRIPTION
**Pull request by glepnir**
Fix #23474

### CODE REVIEW

**Comment by nullchilly** [comment]
I think you forgot steps 4 and 5 in the linked bug report:

### What this PR fixed:

```
:lua vim.api.nvim_set_hl(0, 'AAA', { default = true })
:hi AAA
AAA            xxx cleared
```

### What it didn't:

```
:lua vim.api.nvim_set_hl(0, 'BBB', { default = true, fg = '#ffffff' })
:hi BBB
BBB            xxx cterm= gui= guifg=#ffffff
```

**Comment by glepnir** [comment]
yes. I ignored 4 and 5. now should work.

**Comment by nullchilly** [comment]
Failed on this test:

```
:lua vim.api.nvim_set_hl(0, 'CCC', { default = true, fg = '#ffffff', cterm = { italic = true } })
:hi CCC
CCC            xxx guifg=#ffffff
```

While it should be `CCC            xxx cterm=italic guifg=#ffffff`

File: src/nvim/highlight_group.c [hunk 1]
```diff
@@ -824,7 +825,7 @@ void set_hl_group(int id, HlAttrs attrs, Dict(highlight) *dict, int link_id)
     g->sg_link = 0;
   }
 
-  g->sg_gui = attrs.rgb_ae_attr;
+  g->sg_gui = (!has_default && attrs.rgb_ae_attr == HL_DEFAULT) ? 0 : attrs.rgb_ae_attr;
```
Comment (bfredl) [inline src/nvim/highlight_group.c:828]: I think this can be simplified. once we get past the if statement above it shouldn't matter if it was set previously or not. so just `g->sg_gui =  attrs.rgb_ae_attr & ~ HL_DEFAULT;` (and similar below)
