### PR TITLE
fix(completion): cmdline completion does not complete items for `_defer_require` module

### LINKED ISSUE #33003: cmdline completion does not complete some items
### Problem

`:lua vim.lsp.c<tab>` does not list `vim.lsp.completion` in the completion list.

### Steps to reproduce

```
nvim --clean
:lua vim.lsp.c<tab>
```

### Expected behavior

should list all valid completion candidates.

### Nvim version (nvim -v)

0.11

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macos

### Terminal name/version

kitty

### $TERM environment variable

kitty

### Installation

source

### PR DESCRIPTION
**Pull request by phanen**
Fix https://github.com/neovim/neovim/issues/33003.

Problem:
`:lua vim.lsp.c<tab>` does not list vim.lsp.completion in the completion list after [`24cea4c` (#27216)](https://github.com/neovim/neovim/pull/27216/commits/24cea4c7f7417c7fe99a98a0487f51dd68c4f409).
This happened on all defer_require() modules.

Solution:
Include keys in `vim.lsp._submodule` into candidates.
Fix `vim.lsp.c<tab>` -> `vim.lsp.completion`.

~~Call `mt.__index` function to ensure module loaded to get its key.~~
Eager-load `vim.lsp.completion` to get its completion.
Fix `vim.lsp.completion.g<tab>` -> `vim.lsp.completion.get`.

### CODE REVIEW

File: test/functional/editor/completion_spec.lua [hunk 1]
```diff
@@ -945,6 +945,19 @@ describe('completion', function()
     end
   end)
 
+  it('cmdline completion include `_defer_require` module', function()
+    -- vim.lsp.c<tab> -> vim.lsp.completion
+    eq(
+      'completion',
+      table.concat(fn.getcompletion('lua vim.lsp.c', 'cmdline'), ':'):match('completion')
+    )
```
Comment (justinmk) [inline test/functional/editor/completion_spec.lua:953]:
```suggestion
    ok(vim.tbl_contains(fn.getcompletion('lua vim.lsp.c', 'cmdline'), 'completion'))
```

File: runtime/lua/vim/_editor.lua [hunk 2]
```diff
@@ -997,6 +1000,10 @@ function vim._expand_pat(pat, env)
     insert_keys(vim._extra)
   end
 
+  if final_env == vim.lsp or final_env == vim.treesitter or final_env == vim.provider then
```
Comment (justinmk) [inline runtime/lua/vim/_editor.lua:1003]: does this work (and avoids future maintenance)?
```suggestion
  elseif final_env._submodules then
```

**Review by justinmk — APPROVED** [review]

File: runtime/lua/vim/_editor.lua [hunk 3]
```diff
@@ -947,16 +947,7 @@ function vim._expand_pat(pat, env)
...
-    if field == nil then
-      local mt = getmetatable(final_env)
-      if mt and type(mt.__index) == 'table' then
-        field = rawget(mt.__index, key)
-      elseif final_env == vim and (vim._submodules[key] or vim._extra[key]) then
-        field = vim[key] --- @type any
-      end
-    end
-    final_env = field
+    final_env = final_env[key] ---@type any
```
Comment (justinmk) [inline runtime/lua/vim/_editor.lua:950]: From @bfredl : 

> the original rationality for not using `final_env[key]` unconditionally was to avoid surprising arbitrary code execution in an arbitrary environment (`__index` can be a function. not from a "security" side-point, more like avoiding surprising side-effects standpoint), but maybe it's fine.
>
> the alternative would be to change `final_env == vim and (vim._submodules[key] or vim._extra[key])` to `final_env._submodules and final_env._submodules[key]` . and same for `_extra`

Comment (phanen) [reply runtime/lua/vim/_editor.lua:950]: But for all `_defer_required` module, if we don't finally require/index it, we cannot get its completion (e.g. `vim.lsp.completion.g<tab>`), unless do something like this:
```diff
local lsp = vim._defer_require('vim.lsp', {
-  completion = ..., --- @module 'vim.lsp.completion'
+  completion = { get = true, ... }, },
```

File: runtime/lua/vim/_editor.lua [hunk 4]
```diff
@@ -952,8 +952,11 @@ function vim._expand_pat(pat, env)
       local mt = getmetatable(final_env)
       if mt and type(mt.__index) == 'table' then
         field = rawget(mt.__index, key)
-      elseif final_env == vim and (vim._submodules[key] or vim._extra[key]) then
-        field = vim[key] --- @type any
+      elseif
+        final_env._submodules and final_env._submodules[key]
+        or final_env._extra and final_env._extra[key]
```
Comment (justinmk) [inline runtime/lua/vim/_editor.lua:957]: use parens to make the intended logic here more obvious

File: test/functional/lua/command_line_completion_spec.lua [hunk 5]
```diff
@@ -102,6 +102,10 @@ describe('nlua_expand_pat', function()
 
     eq({ { 'treesitter' }, 4 }, get_completions('vim.treesi'))
 
+    eq({ { 'dev' }, 15 }, get_completions('vim.treesitter.de'))
+
+    eq({ { 'edit_query' }, 19 }, get_completions('vim.treesitter.dev.edit_'))
+
```
Comment (justinmk) [inline test/functional/lua/command_line_completion_spec.lua:108]: nit
```suggestion
    eq({ { 'treesitter' }, 4 }, get_completions('vim.treesi'))
    eq({ { 'dev' }, 15 }, get_completions('vim.treesitter.de'))
    eq({ { 'edit_query' }, 19 }, get_completions('vim.treesitter.dev.edit_'))
```

File: runtime/lua/vim/_editor.lua (hunk 3 above)
Comment (phanen) [reply runtime/lua/vim/_editor.lua]: Found some edge case: `vim.o.foo`, `vim.fn.foo.bar` both throw error now. I should fix it...

File: runtime/lua/vim/_editor.lua [hunk 6]
```diff
@@ -917,6 +917,30 @@ function vim._expand_pat(pat, env)
 
   local final_env = env
 
+  --- @param m table
+  --- @param k string
+  --- @return any
+  local function safe_tbl_get(m, k)
+    if rawget(m, k) then
+      return rawget(m, k)
+    end
```
Comment (glepnir) [inline runtime/lua/vim/_editor.lua:926]:
```suggestion
    local val = rawget(m, k)
    if val ~= nil then
      return val
    end
```

**Review by justinmk — APPROVED** [review]
Thanks for the very clear and concise test-cases.

The logic in _expand_pat() is way too complicated for its purpose, I wonder if it has overlap with anything and could benefit from some generalization or code reuse. Meanwhile, the change in this PR looks reasonable.

File: runtime/lua/vim/_editor.lua [hunk 7]
```diff
@@ -917,6 +917,31 @@ function vim._expand_pat(pat, env)
...
+
+    -- use mt.__index, _submodules as fallback
+    if type(mt.__index) == 'table' then
+      return rawget(mt.__index, k)
+    end
+
+    local sub = rawget(m, '_submodules')
+    if sub and type(sub) == 'table' and rawget(sub, k) then
+      return m[k] -- access to required module
```
Comment (justinmk) [inline runtime/lua/vim/_editor.lua:941]: Just noticed this in the commit message:

> Always access `._submodules` field to ensure `_defer_require` module loaded.

That is a rather important thing to clearly call out. Starting with this code comment. Is this comment correct?:


```suggestion
      -- Access the module to force _defer_require() to load the module.
      return m[k]
```

**Comment by phanen** [comment]
> Does [this](https://github.com/neovim/neovim/pull/33007#discussion_r2009280456) mean that cmdline completion of `vim.*` will un-defer a `_defer_require` module? If so, please update the docstring of `_defer_require`:

Yes, but a small correction:
* `vim.lsp.c<tab>` get candidates by `insert_keys(rawget(vim.lsp, "_submodules"))` (so it doesn't trigger a `require`)
* `vim.lsp.completion.g<tab>` get candidates by `insert_keys(vim.lsp.completion)`:
```patch
---- Cmdline completion (`:lua vim.lsp.c<tab>`) will eager-load the module anyway. #33007
----
+--- Cmdline completion (`:lua vim.lsp.completion.g<tab>`) will eager-load the module anyway. #33007
+---
```

File: runtime/lua/vim/_editor.lua (hunk 7 above)
Comment (phanen) [reply runtime/lua/vim/_editor.lua]: Yes. I should elaborate on it..

**Comment by justinmk** [comment]
Ok, that's good!
