### PR TITLE
fix(ui2): only set dialog on_key callback once

### LINKED ISSUE #37799: ui2: cursor placed in the middle of the first line after opening pager
### Problem

After opening the pager with some commands, the cursor will be placed in the middle of a line:

Image

### Steps to reproduce

- `nvim --clean`
- `:lua require('vim._core.ui2').enable {}`
- `:hi`
- `g<`

### Expected behavior

Cursor is either at column 1 or the final column of line one (the equivalent of `0` or `$`).

### Nvim version (nvim -v)

NVIM v0.12.0-dev-2246+g57fc77ed29

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Fedora 43

### Terminal name/version

kitty 0.43.1

### $TERM environment variable

xterm-kitty

### Installation

repo (`make`)

### LINKED ISSUE #37820: ui2: cursor move become laggy after print lots of msg in cmdline mode
## Problem

After https://github.com/neovim/neovim/pull/37730, if we produce lots of message in cmdline mode, then cursor become laggy if we quit cmdline mode. (This use nvim_parse_cmd to produce error, but should also reproducable with normal print)
```lua
require("vim._core.ui2").enable({})
vim.api.nvim_create_autocmd({ "CmdlineChanged" }, {
	callback = function(ev)
		if ev.match ~= ":" then
			return
		end
		pcall(vim.api.nvim_parse_cmd, vim.fn.getcmdline(), {})
	end,
})
vim.defer_fn(function() vim.api.nvim_input(":echo ") end, 10)
for i = 1, 200 do
	vim.defer_fn(function() vim.api.nvim_input(")") end, 10 + 10 * i)
end
-- then quit the cmdline mode, move the cursor, notice it become laggy.
```

## Expected behavior
Cursor move shouldn't be laggy.

## System info

- Nvim version (nvim -v): `v0.12.0-dev-2207 ge198037148` neovim/neovim@e198037148
- Vim (not Nvim) behaves the same?: ?
- Operating system/version: Linux 6.18.7-zen1-1-zen
- Terminal name/version: kitty
- $TERM environment variable: `xterm-kitty`
- Installation: ?

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  vim.on_key() called for each message while cmdline is open.
          Cursor is on a seemingly random column when pager is entered.
          Entering the pager while the cmdline is expanded can be more
          convenient than pressing "g<".
          Pager window is unnecessarily clamped to half the shell height.
          Setting 'laststatus' while pager is open does not adjust its
          dimensions.
Solution: Only call vim.on_key() once when dialog window is opened.
          Ensure cursor is at the start of the first message when
          entering the pager.
          Enter the pager window when `<CR>` is pressed while the
          cmdline is expanded.
          Don't clamp the pager window height.
          Set message windows dimensions when 'laststatus' changes.

Fix #37799
Fix #37820

### CODE REVIEW

File: runtime/lua/vim/_core/ui2/messages.lua [hunk 1]
```diff
@@ -507,7 +507,8 @@ function M.set_pos(type)
     local cfg = { hide = false, relative = 'laststatus', col = 10000 }
     local texth = type and api.nvim_win_text_height(win, {}) or {}
```
Comment (justinmk) [inline runtime/lua/vim/_core/ui2/messages.lua:508]: off topic, probably shouldn't shadow the `type` builtin? surprised that luals didn't flag this.

```suggestion
    local texth = type_ and api.nvim_win_text_height(win, {}) or {}
```

**Comment by superatomic** [comment]
I understand that configurable settings are not the priority right now, but I'd just like to mention that I prefer how the pager window looks with a clamped window height. I totally understand changing the default, but it would be nice to (eventually) have this be customizable.

**Comment by justinmk** [comment]
Isn't it already configurable via `autocmd FileType pager` ?

**Comment by luukvbaal** [comment]
Not currently, it's only fired when the window/buffer are created anew. Could also fire the FileType autocmd whenever the pager is entered to have it serve better as a configuration interface for the dynamically changed height.

Alternatively removing `WinEnter` from 'eventignorewin' for the pager could also work, should probably do that anyways.

```lua
vim.api.nvim_create_autocmd('WinEnter', {
  callback = function()
    local max = math.ceil(vim.o.lines * 0.5)
    if vim.o.filetype == 'pager' and vim.api.nvim_win_get_height(0) > max then
      vim.api.nvim_win_set_height(0, max)
    end
  end,
})
```
