### PR TITLE
fix(api): trigger buffer events for quickfix buffer updates

### LINKED ISSUE #31085: for quickfix, `vim.api.nvim_buf_attach()` `on_bytes` doesn't get called on `:caddexpr`
### Problem

I'm trying to use a plugin to colorize ANSI escape sequences in the quickfix window. The plugin needs to get a callback when the quickfix window updates. However `vim.api.nvim_buf_attach()` `on_bytes` doesn't get called on `:caddexpr`.

(Plugin issue at <https://github.com/m00qek/baleia.nvim/issues/27>).

### Steps to reproduce

The `minimal.lua`:

```lua
vim.cmd('copen')

for _, buffer in ipairs(vim.api.nvim_list_bufs()) do
  if vim.api.nvim_get_option_value('filetype', { buf = buffer }) == 'qf' then
    vim.api.nvim_buf_attach(buffer, false, {
      on_bytes = function()
        print('on_bytes')
      end,
    })
  end
end
```

- First run `/usr/bin/nvim --clean -u minimal.lua`.
- Inside *Neovim*, run `:caddexpr "foo"`.

### Expected behavior

The `on_bytes` callback runs.

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

Arch Linux kernel 6.11.6

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

wezterm

### Installation

system package manager

### PR DESCRIPTION
**Pull request by glepnir**
Problem: Buffer events (specifically on_bytes callbacks) weren't triggered when the 
quickfix list was modified, preventing buffer change notifications.

Solution: Add code to send both bytes and lines change notifications after 
quickfix buffer updates to properly trigger all attached callbacks.

Fix #31085

### CODE REVIEW

File: src/nvim/quickfix.c [hunk 1]
```diff
@@ -4184,6 +4189,33 @@ static void qf_update_buffer(qf_info_T *qi, qfline_T *old_last)
   qf_fill_buffer(qf_get_curlist(qi), buf, old_last, qf_winid);
   buf_inc_changedtick(buf);
 
+  if (buf_updates_active(buf)) {
```
[the remark this answers is not in the document]
Comment (glepnir) [reply src/nvim/quickfix.c:4194]: updated. but I am not familiar with the code related to buffer events. not sure if it is correct.😮‍💨

**Review by luukvbaal — COMMENTED** [review]
Still rather have @bfredl look at and sign off on this.

File: src/nvim/quickfix.c [hunk 2]
```diff
@@ -4182,7 +4187,30 @@ static void qf_update_buffer(qf_info_T *qi, qfline_T *old_last)
   qf_update_win_titlevar(qi);
 
   qf_fill_buffer(qf_get_curlist(qi), buf, old_last, qf_winid);
-  buf_inc_changedtick(buf);
+
+  linenr_T new_line_count = buf->b_ml.ml_line_count;
```
Comment (justinmk) [inline src/nvim/quickfix.c:4191]: Instead of all the new code (below), could we maybe change `qf_fill_buffer` to use `nvim_buf_set_lines` or `nvim_buf_set_text`, which already call `extmark_splice` + `changed_lines` in the expected way?

I guess not, because it looks like `qf_fill_buffer` is doing extra behavior per-line...

File: src/nvim/quickfix.c [hunk 3]
```diff
@@ -4149,6 +4152,8 @@ static void qf_update_buffer(qf_info_T *qi, qfline_T *old_last)
   }
 
   linenr_T old_line_count = buf->b_ml.ml_line_count;
+  colnr_T old_endcol = ml_get_buf_len(buf, old_line_count);
+  bcount_t old_byte_count = get_region_bytecount(buf, 1, old_line_count, 0, old_endcol);
```
Comment (justinmk) [inline src/nvim/quickfix.c]:
```suggestion
  bcount_t old_bytecount = get_region_bytecount(buf, 1, old_line_count, 0, old_endcol);
```

File: src/nvim/quickfix.c [hunk 4]
```diff
@@ -4182,7 +4187,30 @@ static void qf_update_buffer(qf_info_T *qi, qfline_T *old_last)
...
   qf_fill_buffer(qf_get_curlist(qi), buf, old_last, qf_winid);
-  buf_inc_changedtick(buf);
+
+  linenr_T new_line_count = buf->b_ml.ml_line_count;
+  colnr_T new_endcol = ml_get_buf_len(buf, new_line_count);
+  bcount_t new_byte_count;
+
+  if (old_last == NULL) {
+    new_byte_count = get_region_bytecount(buf, 1, new_line_count, 0, new_endcol);
+    extmark_splice(buf, 0, 0, old_line_count - 1, 0, old_byte_count, new_line_count - 1,
```
Comment (justinmk) [inline src/nvim/quickfix.c]: is `old_line_count` guaranteed to be >=1 ?

File: test/functional/lua/buffer_updates_spec.lua [hunk 5]
```diff
@@ -420,6 +420,35 @@ describe('lua buffer event callbacks: on_lines', function()
     feed('i<Tab>')
     eq({ '\ta' }, exec_lua('return _G.res[#_G.res]'))
   end)
+
+  it('quickfix buffer send change', function()
```
Comment (justinmk) [inline test/functional/lua/buffer_updates_spec.lua:424]: this test file is for the lua interface to bufupdates, whereas the fix is a low-level change, so probably fits better in `api/buffer_updates_spec`. perhaps after the diff-mode test here: https://github.com/neovim/neovim/blob/76d213efbee8e6857b3aa397827fa8756a327430/test/functional/api/buffer_updates_spec.lua#L584

#31085 mentions `on_bytes`, but the fix in this PR is simply to enable buffer-updates, so there is no need to test all the "lua callback" functionality. Instead we just need to verify that buffer updates are working in quickfix bufs (using `expectn('nvim_buf_lines_event',` or whatever common practice is in `api/buffer_updates_spec`).

File: src/nvim/quickfix.c [hunk 6]
```diff
@@ -4182,7 +4187,30 @@ static void qf_update_buffer(qf_info_T *qi, qfline_T *old_last)
...
+
+    changed_lines(buf, 1, 0, old_line_count > 0 ? old_line_count + 1 : 1,
+                  new_line_count - old_line_count, true);
+  } else {
+    linenr_T start_lnum = old_line_count + 1;
+    new_byte_count = get_region_bytecount(buf, start_lnum, new_line_count, 0, new_endcol);
+    extmark_splice(buf, old_line_count - 1, old_endcol,
+                   0, 0, 0,
+                   new_line_count - old_line_count, new_endcol,
+                   new_byte_count, kExtmarkNoUndo);
```
Comment (justinmk) [inline src/nvim/quickfix.c]: style nit: all the linebreaks here aren't really helping much. and line-length limit is 100, not 80.

```c
  linenr_T delta = new_line_count - old_line_count;
  if (old_last == NULL) {
    new_byte_count = get_region_bytecount(buf, 1, new_line_count, 0, new_endcol);
    extmark_splice(buf, 0, 0, old_line_count - 1, 0, old_byte_count, new_line_count - 1, new_endcol,
                   new_byte_count, kExtmarkNoUndo);
    changed_lines(buf, 1, 0, old_line_count > 0 ? old_line_count + 1 : 1, delta, true);
  } else {
    linenr_T start_lnum = old_line_count + 1;
    new_byte_count = get_region_bytecount(buf, start_lnum, new_line_count, 0, new_endcol);
    extmark_splice(buf, old_line_count - 1, old_endcol, 0, 0, 0, delta, new_endcol, new_byte_count,
                   kExtmarkNoUndo);
    changed_lines(buf, start_lnum, 0, new_line_count + 1, delta + 1, true);
  }
```

File: src/nvim/quickfix.c (hunk 4 above)
Comment (glepnir) [reply src/nvim/quickfix.c]: initial value of `ml_line_count` is 1 in `ml_open`, It is only set to 0 when buf_freeall is called.

File: test/functional/lua/buffer_updates_spec.lua (hunk 5 above)
Comment (glepnir) [reply test/functional/lua/buffer_updates_spec.lua:424]: extmark_splice called `buf_updates_send_splice` which trigger `on_bytes`

Comment (justinmk) [inline test/functional/lua/buffer_updates_spec.lua:424]:
```suggestion
  it('in quickfix buffer', function()
```

File: test/functional/lua/buffer_updates_spec.lua [hunk 7]
```diff
@@ -420,6 +420,35 @@ describe('lua buffer event callbacks: on_lines', function()
...
+    command('copen')
+    exec_lua(function()
+      vim.api.nvim_buf_attach(vim.api.nvim_get_current_buf(), false, {
+        on_lines = function(...)
+          vim.g.qf_on_lines = { ... }
+        end,
+        on_bytes = function(...)
+          vim.g.qf_on_bytes = { ... }
```
Comment (justinmk) [inline test/functional/lua/buffer_updates_spec.lua:432]: The other tests use `check_events`. Using a different approach makes the tests harder to understand. OTOH, this test is testing both "lines" and "bytes".
