### PR TITLE
fix(log): warn when NVIM_LOG_FILE is inaccessible

### LINKED ISSUE #38039: nvim.log file appearing in CWD
### Problem

Starting nvim causes a `nvim.log` file to be written to the current working directory. I did a git bisect, and the error first appeared in abfe6c9ef7f4bd41c1306f3c70ead00e4afaa736, which makes sense. However, I read the commit description, and I don't think it was intentional that the log file is always written to the current working directory - `$NVIM_LOG_FILE` is *not* set, and `stdpath('log')` exists. I checked the diff, but my C knowledge is quite limited. If I had to guess, I would say that this change in `src/nvim/log.c`, line 81 is unintentional

```c
char *defaultpath = stdpaths_user_state_subpath("nvim.log", 0, true);
```

### Steps to reproduce

```
nvim --clean +q
[[ -f nvim.log ]]
```

### Expected behavior

I would expect the log file to remain in `stdpath('log') .. 'log'`

### Nvim version (nvim -v)

NVIM v0.12.0-dev-2404+gd9d8c660fd Build type: Release LuaJIT 2.1.1771261233

### Vim (not Nvim) behaves the same?

no

### Operating system/version

MacOS 26.3

### Terminal name/version

ghostty/kitty

### $TERM environment variable

xterm-ghostty

### Installation

brew

### PR DESCRIPTION
**Pull request by anondeveg**
## Problem:
If NVIM_LOG_FILE, or the default fallback, is inaccessible (e.g. directory is owned by root), users get confused.

## Solution:
- Show a warning when $NVIM_LOG_FILE or $XDG_STATE_HOME are inaccessible.
- Also fix a latent memory leak: `os_mkdir_recurse` returns a uv error code (int), but it was stored as `bool`, causing `os_strerror` to receive an invalid error code and leak memory.

---

implements justinmk proposal in #38039. 

closes #38039

### CODE REVIEW

**Comment by anondeveg** [comment]
@justinmk 
would running the check on `VimEnter` autocmd be a better choice here? as we don't need to change anything in `main.c` unlike #27537, and it will prevent `windows (old)` from failing as much as i understand it.

**Comment by justinmk** [comment]
> would running the check on `VimEnter` autocmd be a better choice here?

yes, then the impl can be fully in Lua. but the question is how will the VimEnter handler know when to warn.

> prevent `windows (old)` from failing 

    RunTheTest[61]..Test_issue_3969 line 6: Expected 'hello' but got '"C:\\\\Users\\\\runneradmin\\\\AppData\\\\Local\\\\nvim-data\\\\nvim.log" is not accessible, logging to: "Xnvim.log"hello'

look at the test implementation to understand why that happens.
https://github.com/neovim/neovim/blob/5cbb9d613bf6d8983b5effd7e20343a4ef497c06/test/old/testdir/test_startup.vim#L828

File: test/functional/core/log_spec.lua [hunk 1]
```diff
@@ -99,4 +99,30 @@ describe('log', function()
     -- Child Nvim spawned by jobstart() prepends "c/" to parent name.
     assert_log('c/' .. tid .. '%.%d+%.%d +server_init:%d+: test log message', testlog, 100)
   end)
+
+  it('warns when NVIM_LOG_FILE is inaccessible', function()
+    local invalid_path = '/foo/bar'
+    if t.is_os('win') then
+      invalid_path = 'C:\\invalid\\path\\nvim.log'
```
Comment (justinmk) [inline test/functional/core/log_spec.lua]: just use regular "/" slashes. zero need for `\` slashes. and this shouldn't be needed anyway, `'/foo/bar'` should also work on Windows.

File: runtime/doc/news.txt [hunk 2]
```diff
@@ -390,8 +384,7 @@ PLUGINS
 • |:checkhealth| now checks for an available |vim.ui.open()| handler.
 
 STARTUP
-
-• todo
+• Nvim warns when the intended log path is inaccessible or falls back to a different location.
```
Comment (seandewar) [inline runtime/doc/news.txt]:
```suggestion

• Nvim warns when the intended log path is inaccessible or falls back to a different location.
```

File: src/nvim/log.c [hunk 3]
```diff
@@ -65,26 +65,35 @@ static void log_path_init(void)
...
       || os_isdir(log_file_path)
       || !log_try_create(log_file_path)) {
     // Make $XDG_STATE_HOME if it does not exist.
     char *loghome = get_xdg_home(kXDGStateHome);
     char *failed_dir = NULL;
-    bool log_dir_failure = false;
+    int log_dir_failure = 0;
     if (!os_isdir(loghome)) {
-      log_dir_failure = (os_mkdir_recurse(loghome, 0700, &failed_dir, NULL) != 0);
+      log_dir_failure = (os_mkdir_recurse(loghome, 0700, &failed_dir, NULL));
```
Comment (seandewar) [inline src/nvim/log.c]:
```suggestion
      log_dir_failure = os_mkdir_recurse(loghome, 0700, &failed_dir, NULL);
```

File: src/nvim/log.c [hunk 4]
```diff
@@ -65,26 +65,35 @@ static void log_path_init(void)
 {
   size_t size = sizeof(log_file_path);
   expand_env("$" ENV_LOGFILE, log_file_path, (int)size - 1);
+  char default_log_file_path[MAXPATHL + 1] = { 0 };
```
Comment (seandewar) [inline src/nvim/log.c]:
```suggestion
  char default_log_file_path[ARRAY_SIZE(log_file_path)] = { 0 };
```

Probably for the best, especially as the `+1` was forgotten in the first commit. (`sizeof` works too, as it's `char`)

**Comment by anondeveg** [comment]
so the reason test / ubuntu asan clang functionaltest (pull_request) was failing is because of a latent memory bug that @seandewar helped me solve.

the bug happened because log_dir_failure was declared as of type bool when it should have been of type int because it holds a uv error code. so as documented in https://docs.libuv.org/en/v1.x/errors.html#c.uv_strerror it would leak memory.

i've also fixed windows (old) by checking if it was running in es mode and not raise a warning if it was.
the pr is ready for merging.

File: test/functional/core/log_spec.lua [hunk 5]
```diff
@@ -99,4 +99,24 @@ describe('log', function()
...
+  end)
+
+  it('warns when NVIM_LOG_FILE and $XDG_STATE_HOME is inaccessible', function()
+    local invalid_path = '/foo/bar'
+    clear({
+      args_rm = { '-u' },
+      args = { '--clean' },
+      env = { NVIM_LOG_FILE = invalid_path, XDG_STATE_HOME = invalid_path },
+    })
+    t.matches('not accessible', n.exec_capture('messages'))
```
Comment (seandewar) [inline test/functional/core/log_spec.lua]: I'd maybe consider matching more of the message here, to ensure `$DEFAULT_NVIM_LOG_FILE` is being set correctly? (if not too fiddly to do)

**Review by seandewar — COMMENTED** [review]
Haven't looked at the discussion, but `$DEFAULT_NVIM_LOG_FILE` feels a bit icky to me. (is there a different way this could be made available to the warning message?)

I'll leave the rest to Justin to avoid stepping on any toes. 😁

File: test/functional/core/log_spec.lua (hunk 5 above)
Comment (anondeveg) [reply test/functional/core/log_spec.lua]: On it!

**Comment by anondeveg** [comment]
> is there a different way this could be made available to the warning message?

i thought about doing 

```c
nlua_exec("vim._default_log_file = ...", default_log_file_path);
``` 
then we can
```lua
local default_log_file = vim._default_log_file
```
not a hard change.  will wait for Justin's opinion.

File: runtime/lua/vim/_core/util.lua [hunk 6]
```diff
@@ -81,4 +81,30 @@ function M.source_is_lua(bufnr, line1, line2)
   return lang_tree:lang() == 'lua'
 end
 
+function M._warn_log_file_fallback()
+  local mode = vim.fn.mode()
+  if mode == 'c' then -- in es mode
+    return
+  end
+
+  local default_log_file = vim.fn.getenv('DEFAULT_NVIM_LOG_FILE')
```
Comment (justinmk) [inline runtime/lua/vim/_core/util.lua]: ~~env vars are yuck. how about setting a variable in this module, e.g.~~

```lua
require('vim._core.util').foo = '...'
```

To avoid depending on Lua from `log.c`, env var is acceptable. And besides, this env var is (1) short-lived and (2) only happens in rare circumstances.

File: src/nvim/log.c [hunk 7]
```diff
@@ -65,26 +65,35 @@ static void log_path_init(void)
...
     xfree(defaultpath);
+    if (default_log_file_path[0] == NUL) {
+      xstrlcpy(default_log_file_path, log_file_path, size);
+    }
     // Fall back to $CWD/nvim.log
     if (len >= size || !log_try_create(log_file_path)) {
       len = xstrlcpy(log_file_path, "nvim.log", size);
     }
+    // setenv before stderr because it might return..
+    os_setenv("DEFAULT_NVIM_LOG_FILE", default_log_file_path, true);
```
Comment (justinmk) [inline src/nvim/log.c]: instead of doing this, and instead of trying to call Lua from log.c (not wanted), return a boolean from `log_init` so that `main.c` can do something with it after it calls `nlua_init`

Comment (anondeveg) [reply src/nvim/log.c]: A boolean would only tell us that a fallback happened, not which path was inaccessible. Setting the module variable directly seems to me like the cleanest solution: 
```lua
nlua_exec("require('vim._core.util')._default_log_file = ...", default_log_file_path);
```
Is this acceptable?

File: runtime/lua/vim/_core/defaults.lua [hunk 8]
```diff
@@ -1016,6 +1016,17 @@ do
       end,
     })
   end
+  -- warn if $NVIM_LOG_FILE or $XDG_STATE_HOME are inaccessable. see #38039
```
Comment (justinmk) [inline runtime/lua/vim/_core/defaults.lua]:
```suggestion

  -- Warn if $NVIM_LOG_FILE or $XDG_STATE_HOME are inaccessible. #38039
```

File: runtime/lua/vim/_core/util.lua [hunk 9]
```diff
@@ -81,6 +81,32 @@ function M.source_is_lua(bufnr, line1, line2)
...
+      ('%q is not accessible, logging disabled (stderr)'):format(default_log_file),
+      vim.log.levels.WARN
+    )
+  elseif log_file ~= default_log_file then
+    vim.notify(
+      ('%q is not accessible, logging to: %q'):format(default_log_file, log_file),
+      vim.log.levels.WARN
+    )
+  end
+=======
```
Comment (justinmk) [inline runtime/lua/vim/_core/util.lua]:
```suggestion

```

File: runtime/doc/news.txt [hunk 10]
```diff
@@ -396,7 +396,11 @@ PLUGINS
 
 STARTUP
 
+<<<<<<< fix/warn-nvim-log-file-inaccessible
+• Nvim warns when the intended log path is inaccessible or falls back to a different location.
+=======
 • |v:argf| provides file arguments given at startup.
+>>>>>>> master
```
Comment (justinmk) [inline runtime/doc/news.txt]:
```suggestion
• Nvim warns when the intended log path is inaccessible or falls back to a different location.
• |v:argf| provides file arguments given at startup.
```

File: runtime/lua/vim/_core/util.lua [hunk 11]
```diff
@@ -81,6 +81,31 @@ function M.source_is_lua(bufnr, line1, line2)
   return lang_tree:lang() == 'lua'
 end
 
+<<<<<<< fix/warn-nvim-log-file-inaccessible
```
Comment (justinmk) [inline runtime/lua/vim/_core/util.lua]:
```suggestion
```

File: runtime/lua/vim/_core/util.lua [hunk 12]
```diff
@@ -97,6 +121,7 @@ function M.term_exitcode()
     return string.format('[Exit: %d]', info.exitcode)
   end
   return ''
+>>>>>>> master
```
Comment (justinmk) [inline runtime/lua/vim/_core/util.lua]:
```suggestion
```

File: runtime/lua/vim/_core/util.lua [hunk 13]
```diff
@@ -81,6 +81,30 @@ function M.source_is_lua(bufnr, line1, line2)
...
+    vim.notify(
+      ('%q is not accessible, logging disabled (stderr)'):format(default_log_file),
+      vim.log.levels.WARN
+    )
+  elseif log_file ~= default_log_file then
+    vim.notify(
+      ('%q is not accessible, logging to: %q'):format(default_log_file, log_file),
+      vim.log.levels.WARN
+    )
+  end
```
Comment (justinmk) [inline runtime/lua/vim/_core/util.lua]:
```suggestion
  end

```

File: src/nvim/log.c (hunk 7 above)
Comment (justinmk) [reply src/nvim/log.c]: On reflection, to avoid depending on Lua from `log.c`, env var is acceptable. And besides, this env var is (1) short-lived and (2) only happens in rare circumstances.

File: src/nvim/log.c [hunk 14]
```diff
@@ -65,26 +65,35 @@ static void log_path_init(void)
 {
   size_t size = sizeof(log_file_path);
   expand_env("$" ENV_LOGFILE, log_file_path, (int)size - 1);
+  char default_log_file_path[ARRAY_SIZE(log_file_path)] = { 0 };
+  if (!strequal("$" ENV_LOGFILE, log_file_path)) {
+    xstrlcpy(default_log_file_path, log_file_path, size);
```
Comment (justinmk) [inline src/nvim/log.c]: Do we actually need `default_log_file_path` or could we just call `os_setenv` when needed?

File: src/nvim/log.c [hunk 15]
```diff
@@ -65,26 +65,35 @@ static void log_path_init(void)
...
+  }
   if (strequal("$" ENV_LOGFILE, log_file_path)
       || log_file_path[0] == NUL
       || os_isdir(log_file_path)
       || !log_try_create(log_file_path)) {
     // Make $XDG_STATE_HOME if it does not exist.
     char *loghome = get_xdg_home(kXDGStateHome);
     char *failed_dir = NULL;
-    bool log_dir_failure = false;
+    int log_dir_failure = 0;
```
Comment (justinmk) [inline src/nvim/log.c:81]: Nice catch, thanks for explaining in the commit message.

File: runtime/lua/vim/_core/log.lua [hunk 16]
```diff
@@ -0,0 +1,30 @@
...
+    msg = ('log: %q not accessible, logging disabled (stderr)'):format(wanted)
+  elseif actual ~= wanted then
+    msg = ('log: %q not accessible, logging to: %q'):format(wanted, actual)
+  else
+    return
+  end
+
+  vim.defer_fn(function()
+    vim.notify(msg, vim.log.levels.WARN)
+  end, 100)
```
Comment (justinmk) [inline runtime/lua/vim/_core/log.lua:27]: when trying this locally, the warning doesn't actually show on startup (because of a redraw or something). using `defer_fn` to workaround that for now.

Comment (anondeveg) [reply runtime/lua/vim/_core/log.lua:27]: Iam unable to recreate the issue. Ill leave it with the vim.defer_fn anyways as it is more robust.

File: src/nvim/log.c [hunk 17]
```diff
@@ -83,6 +89,10 @@ static void log_path_init(void)
     xfree(defaultpath);
     // Fall back to $CWD/nvim.log
     if (len >= size || !log_try_create(log_file_path)) {
+      if (!user_set) {  // Default fallback path.
+        // Used by _core/log.lua:check_log_file to validate logfile on startup.
+        os_setenv("__NVIM_LOG_FILE_WANT", log_file_path, true);
```
Comment (justinmk) [inline src/nvim/log.c:94]: Key idea: `__NVIM_LOG_FILE_WANT` is set *only* in the failure case(s). We don't want to define it in the normal case.

File: runtime/lua/vim/_core/log.lua [hunk 18]
```diff
@@ -0,0 +1,30 @@
...
+  end
+
+  local wanted = vim.fn.getenv('__NVIM_LOG_FILE_WANT')
+  if not wanted or wanted == vim.NIL then
+    return
+  end
+
+  local actual = vim.fn.getenv('NVIM_LOG_FILE')
+
+  local msg = nil --luacheck: ignore
```
Comment (justinmk) [inline runtime/lua/vim/_core/log.lua]:
```suggestion
  local msg --[[@type string]]
```
