### PR TITLE
fix(api): adjust fix for reconfiguring float "relative"

### LINKED ISSUE #34286: floating window `win_set_config` weird behavior
### Problem

After https://github.com/neovim/neovim/pull/34271, there is some weird behavior with floating windows and `win_set_config`. I initially had some problems with `snacks.nvim` and some border and winhighlight being broken, but I was able to find another weird behavior which probably has the same root cause:

https://github.com/user-attachments/assets/797d8c74-0282-4ca9-82cf-d188ef576cd6

Notice how the floating window moves when the title is set through the config

### Steps to reproduce

```foo.lua
local bufnr = vim.api.nvim_create_buf(false, true)
local winid = vim.api.nvim_open_win(bufnr, true, {
  relative = 'win',
  width = 50,
  height = 10,
  col = 1,
  row = 1,
})

vim.api.nvim_win_set_config(winid, { border = 'single' })

vim.defer_fn(function()
  vim.api.nvim_win_set_config(winid, {
    title = 'foo',
  })
end, 5000)
```

`nvim --clean foo.lua` and `:source %`

### Expected behavior

I would expect only the `title` to change, and not something else

### Nvim version (nvim -v)

v0.12.0-dev-485+g33b0a004eb

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 15.4.1

### Terminal name/version

kitty 0.34.1

### $TERM environment variable

xterm-kitty

### Installation

Build from source

### PR DESCRIPTION
**Pull request by luukvbaal**
Problem:  "win" is cleared in float config after 96330843, even with
          unchanged "relative".
Solution: Don't clear "win". Avoid erroring for deleted "win" by setting
          the parent win to curwin directly when "win" is zero or not
          present in config.

Fix #34286

### CODE REVIEW

File: test/functional/ui/float_spec.lua [hunk 1]
```diff
@@ -379,7 +379,10 @@ describe('float window', function()
       row = 1,
     })
     eq(1001, api.nvim_win_get_config(winid).win)
+    api.nvim_win_set_config(winid, { title = 'foo' })
+    eq(1001, api.nvim_win_get_config(winid).win)
     command('close')
+    api.nvim_win_set_config(winid, { title = 'bar' })
```
Comment (luukvbaal) [inline test/functional/ui/float_spec.lua:386]: This now fails again because the relative window was closed. Should it? I guess not.

Comment (luukvbaal) [reply test/functional/ui/float_spec.lua:386]: Maybe these `win != -1` checks are just wrong? I don't think the win field is ever set or initialized to -1🤔
https://github.com/neovim/neovim/blob/33b0a004eb20fd5a0013b832414596190c059828/src/nvim/api/win_config.c#L240
https://github.com/neovim/neovim/blob/33b0a004eb20fd5a0013b832414596190c059828/src/nvim/api/win_config.c#L417

Oh, it's an explicitly supported option. I think we can just skip getting the window and set it to curwin directly with `win == 0`. That also avoids the error.

**Review by justinmk — APPROVED** [review]
