### PR TITLE
fix(treesitter): return correct match table in iter_captures()

### LINKED ISSUE #23664: Treesitter `Query#iter_captures` yields correct metadata only for the first capture in a match
### Problem

Treesitter `Query#iter_captures` yields correct metadata only for the first capture in a match.

I encountered the issue while implementing injection formatting in Python files. I decided to use the newer injection syntax introduced in `0.9.0` (e.g. `@injection.content`) so, my query includes a `@_id` capture to check the assignment identifier name, `@injection.content` capture for the content itself, and the `(#set! injection.language "...")` directive.

The issue is when iterating over captures in code using the `Query:iter_captures` method, the metadata object containing the `injection.language` value is only properly available for the first capture in the match. And, as `@_id` capture appears earlier in the match than the `@injection.content` capture, it is not possible to do checks like this:

```lua
...
if injections.captures[id] == "injection.content" and metadata["injection.language"] == "sql" then
  ...
end
...
```

Using `Query#iter_matches` does, in fact, work as intended, as match metadata is decoupled from a capture. But the `Query#iter_matches` API is more cumbersome and requires 2 levels of nesting to use. I find the `Query#iter_captures` API better suited to solve the problem, at least in theory.

I am not even sure if it is a bug, but it is surely the behavior that I was not expecting. From what I can see in the source code, all of the injection queries provided with `neovim` and `nvim-treesitter` only use single capture per match, and do not match against a broader context (such as variable names), so there is no way to verify the behavior using provided queries.

### Steps to reproduce

Consider the following Lua script:

```lua
local injections_query = [[
;; query
(assignment
  left: (identifier) @_id
  right: (string
    string_content: (string_content) @injection.content)
  (#set! injection.language "sql")
  (#contains? @_id "sql"))

(assignment
  left: (identifier) @_id
  right: (string
    string_content: (string_content) @injection.content)
  (#set! injection.language "toml")
  (#contains? @_id "toml"))
]]

local injections = vim.treesitter.query.parse("python", injections_query)

local python_source = [[
sql_blob = """
select * from information_schema.tables
"""

toml_blob = """
[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00
"""
]]

local parser = require("vim.treesitter.languagetree").new(python_source, "python")
local root = parser:parse()[1]:root()

---@param id integer
---@param node TSNode
---@param metadata TSMetadata
local function print_capture(id, node, metadata)
  print("--- capture [" .. tostring(id) .. "] ---")
  print("capture name: [" .. injections.captures[id] .. "]")
  print("metadata: [" .. vim.inspect(metadata) .. "]")
  local is_content = injections.captures[id] == "injection.content"
  local is_sql = metadata["injection.language"] == "sql"
  local is_toml = metadata["injection.language"] == "toml"
  if is_content and is_sql then
    print("sql content: [" .. vim.treesitter.get_node_text(node, python_source) .. "]")
  end
  if is_content and is_toml then
    print("toml content: [" .. vim.treesitter.get_node_text(node, python_source) .. "]")
  end
end

print "----- iter_captures -----"
for id, node, metadata in injections:iter_captures(root, python_source, 0, -1) do
  print_capture(id, node, metadata)
end

print "----- iter_matches -----"
for _, match, metadata in injections:iter_matches(root, python_source, 0, -1) do
  for id, node in pairs(match) do
    print_capture(id, node, metadata)
  end
end
```

Running it requires a Treesitter parser for Python to be installed, so I find it the easiest to open the example in neovim, and `:source %`.

Output (with empathis):

```
----- iter_captures -----
--- capture [1] ---
capture name: [_id]
metadata: [{								<- First capture in the match contains metadata
  ["injection.language"] = "sql"
}]
--- capture [2] ---
capture name: [injection.content]
metadata: [{}]								<- Second capture in the match contains NO metadata
--- capture [1] ---
capture name: [_id]
metadata: [{
  ["injection.language"] = "toml"
}]
--- capture [2] ---
capture name: [injection.content]
metadata: [{}]

----- iter_matches -----
--- capture [1] ---
capture name: [_id]
metadata: [{								<- First capture in the match contains metadata
  ["injection.language"] = "sql"
}]
--- capture [2] ---
capture name: [injection.content]
metadata: [{								<- Second capture in the match contains metadata
  ["injection.language"] = "sql"
}]
sql content: [								<- Capture content is correctly printed
select * from information_schema.tables
]
--- capture [1] ---
capture name: [_id]
metadata: [{
  ["injection.language"] = "toml"
}]
--- capture [2] ---
capture name: [injection.content]
metadata: [{
  ["injection.language"] = "toml"
}]
toml content: [
[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00
]
```

### Expected behavior

I expect `Query#iter_captures` to yield correct metadata for every yielded capture. The output in the example script should be the same between `Query#iter_captures` and `Query#iter_matches`.

### Neovim version (nvim -v)

v0.9.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

Windows Terminal

### $TERM environment variable

empty

### Installation

scoop

### PR DESCRIPTION
**Pull request by lewis6991**
Fixes #23664, #27239

### CODE REVIEW

**Comment by lewis6991** [comment]
@wookayin I hope you don't mind. I pulled your tests from https://github.com/neovim/neovim/pull/27274 and fixed the issues using memoization.

File: test/functional/treesitter/query_spec.lua [hunk 1]
```diff
@@ -696,4 +696,82 @@ void ui_refresh(void)
       '((identifier) @id \n(#eq? @id\n@ok.capture\n))'
     )
   end)
+
+  describe('Query:iter_captures', function()
+    it('includes metadata for all captured nodes #23664', function()
+      insert([[
+        const char *sql = "SELECT * FROM Students WHERE name = 'Robert'); DROP TABLE Students;--";
```
Comment (gpanders) [inline test/functional/treesitter/query_spec.lua:703]: Little Bobby at it again
