### PR TITLE
shada: fix failed assertion on exit

### LINKED ISSUE #11497: crash on exit with shada='100,:0
Likely a multiple-year old issue, as I've been experiencing this crash on exit for a while.
```
fish: “nvim” terminated by signal SIGSEGV (Address boundary error)
```

Caused by the following line:
```
set viminfo='1000,:0,<0,@0,f1,/0
```

Any of the `:0,<0,@0` options in combination with any number of lines (`'100`) are causing the crash. I'm not sure there's an expected behavior with Neovim's shada.

- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
```
- `vim -u DEFAULTS` (version: ) behaves differently? 
Yes

- Operating system/version: 
```
Linux c22 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64 GNU/Linux
```
- Terminal name/version:
rxvt-unicode v9.22

- `$TERM`:
screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set viminfo='100,:0
:q
```

### PR DESCRIPTION
**Pull request by erw7**
If set the number of history saves to 0, assertions failed when inserting an entry on exit. If the number of saves is 0, it will not insert an entry to fix the problem.

fixes #11497

### CODE REVIEW

**Review by jamessan — APPROVED** [review]

File: test/functional/shada/history_spec.lua [hunk 1]
```diff
@@ -237,4 +238,13 @@ describe('ShaDa support code', function()
     nvim_command('wshada')
   end)
 
+  it('does not crash when number of history save to zero (#11497)', function()
+    nvim_command('set shada=\'10')
+    nvim_feed(':" Test\n')
+    nvim_command('wshada')
+    nvim_command('set shada=\'10,:0')
+    nvim_command('wshada')
+    eq(2, eval('1+1')) -- check nvim still running
```
Comment (justinmk) [inline test/functional/shada/history_spec.lua:247]: could use `helpers.assert_alive()`
