### PR TITLE
Fix handling of incomplete bracketed paste and bg color responses

### LINKED ISSUE #11393: TUI: bg color response consumed as user input (inserts "g", "0000/2b2b/3636^G")
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: macOS Majave 10.14.6
- Terminal name/version: Alacritty 0.3.3 (also with iTerm 3.2.7)
- `$TERM`: xterm-256color (also with `$TERM`: alacritty)

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```
I cannot reproduce this 100% of the time. Often, when I open a file (even with nvim -u NORC file.txt), the first character of the file is replaced with g and then the command-line shows :0000/2b2b/3636^G. Sometimes the first letter isn't changed and only the command-line shows /3636.

The problem happens more often when I open nvim from [lf](https://github.com/gokcehan/lf). It seems like this may have to do with terminal colors. It also appears that [this](https://github.com/neovim/neovim/issues/11062) and [this](https://github.com/neovim/neovim/issues/9991) issue might somehow be related. 

The behavior that I'm seeing is the same as if I entered these characters after startup from normal mode: ``` ^[]11;rgb:0000/2b2b/3636^G ``` 
That string is what my terminal outputs when I execute ```echo -e "\e]11;?\a"``` or ```printf '\e]11;?\007'; read``` which I've read are sometimes used to check background colors.

### Actual behaviour
Nvim opens a file and often changes the first character to g and starts entering a command as if from one types ```:0000/2b2b/3636^G``` from normal mode.

### Expected behaviour
Nvim opens a file, doesn't change the buffer contents, and is in normal mode.

### LINKED ISSUE #11699: paste gets stuck with certain data on macOS
- `NVIM v0.5.0-305-g29b1a4761`:
- `vim -u DEFAULTS` (version: ) yes
- Operating system/version: macOS Catalina 10.15.3 Beta (19D49f)
- Terminal name/version: kitty/terminal

[test.txt](https://github.com/neovim/neovim/files/4048827/test.txt)
### Steps to reproduce using `nvim -u NORC`
- copy content of [test.txt](https://github.com/neovim/neovim/files/4048827/test.txt) to system clipboard
- insert using Cmd-V

### Actual behaviour
escape sequences are printed instead of normal text, input is broken(no way for leaving input mode)
Screen Shot 2020-01-11 at 04 36 13

### PR DESCRIPTION
**Pull request by erw7**
fixes #11699, #11991.
fixes #11393 (may be).

### CODE REVIEW

**Comment by dm1try** [comment]
👍  looks good to me

File: src/nvim/tui/input.c [hunk 1]
```diff
@@ -390,9 +405,15 @@ static bool handle_bracketed_paste(TermInput *input)
       // Paste phase: "disabled".
       input->paste = 0;
     }
-    return true;
+    return kComplete;
+  } else if (buf_size < 6
```
Comment (dm1try) [inline src/nvim/tui/input.c]: `but_size < 6` looks like "extra" condition?
 or this is done intentionally, for readability?

File: src/nvim/tui/input.c [hunk 2]
```diff
@@ -576,7 +609,34 @@ static void tinput_read_cb(Stream *stream, RBuffer *buf, size_t count_,
...
+  }
+
+  handle_raw_buffer(input, false);
   tinput_flush(input, true);
+
+  // An incomplete sequence was found. Leave it in the raw buffer and wait for
+  // the next input.
+  if (rbuffer_size(input->read_stream.buffer)) {
+    int ms = get_key_code_timeout();
+    // If ttimeout is not set, start the timer with a timeout of 0 to process
```
Comment (dm1try) [inline src/nvim/tui/input.c]: typo

File: src/nvim/tui/input.c [hunk 3]
```diff
@@ -576,7 +609,34 @@ static void tinput_read_cb(Stream *stream, RBuffer *buf, size_t count_,
...
+    // the next input.
+    ms = ms > 0 ? ms : 0;
+    // Stop the current timer if already running
+    time_watcher_stop(&input->timer_handle);
+    time_watcher_start(&input->timer_handle, tinput_timer_cb, (uint32_t)ms, 0);
```
Comment (dm1try) [inline src/nvim/tui/input.c]: so, scheduling the timer callback is the right thing for waiting the next input, is it right?

**Comment by dm1try** [comment]
> fixes #11393 (may be).

Screen Shot 2020-03-12 at 17 05 40

it looks like the bug is still reproducible, though I used `lldb` to run `nvim`

File: src/nvim/tui/input.c (hunk 1 above)
Comment (erw7) [reply src/nvim/tui/input.c]: Without this condition, receiving an input like `"\x1b[20000"` will cause unnecessary delay. It is unlikely that you will receive such input, but it is possible that you will receive such input if you paste without bracketed paste.

File: src/nvim/tui/input.c (hunk 2 above)
Comment (erw7) [reply src/nvim/tui/input.c]: `ttimeout` is the option name. I changed it to be quoted.

**Comment by erw7** [comment]
> it looks like the bug is still reproducible, though I used lldb to run nvim

@dm1try At that time, what is the content of `input->read_stream.buffer`?

File: src/nvim/tui/input.c (hunk 1 above)
Comment (dm1try) [reply src/nvim/tui/input.c]: @erw7 it makes sense

**Comment by dm1try** [comment]
> @dm1try At that time, what is the content of `input->read_stream.buffer`?

I'll check in tonight

**Comment by dm1try** [comment]
@erw7 
image
though it is rarely reproduced

**Comment by erw7** [comment]
@dm1try Thanks. But that is not the input that caused the problem. I tried to log bg response in the next branch. Could you build  when you're free? And can you show me the logs when the problem happened?

https://github.com/erw7/neovim/tree/debug-log

File: src/nvim/tui/input.c (hunk 3 above)
Comment (erw7) [reply src/nvim/tui/input.c]: I'm not sure if the answers below are appropriate for your question.

If there are more inputs or if the input has been split, the next call to `tinput_read_cb()` will process the remaining input in the buffer (`input->read_stream.buffer`). If there is no timer callback, if the input is a single `'\x1b'`, the remaining `'\x1b'` in the buffer will not be processed until the next input (As a result, it does not return to normal mode until the next input). To avoid that, we schedule a timer callback. That way, any remaining input will be processed when the timeout elapses.

I'm even sure that setting a timer callback with a timeout of 0 is correct. However, as far as I tried, it seems to work fine even if the input is split like `"\x1b [201"`, `"~"` (`"\x1b[201"` does not seem to be processed by the timer callback).

**Comment by dm1try** [comment]
@erw7 
```
INFO  2020-03-14T22:06:30.296 63612 os_exit:593: Nvim exit: 0
INFO  2020-03-14T22:06:30.296 63611 os_exit:593: Nvim exit: 0
INFO  2020-03-14T22:06:30.330 63613 os_exit:593: Nvim exit: 0
ERROR 2020-03-14T22:06:51.618 63652 tinput_read_cb:537: count: 5, input:size 6, 1b 5d 31 31 3b 72 
ERROR 2020-03-14T22:06:54.617 63652 tinput_read_cb:537: count: 4, input:size 19, 67 62 3a 31 65 31 65 2f 31 65 31 65 2f 31 65 31 65 1b 5c 
ERROR 2020-03-14T22:07:13.341 63660 tinput_read_cb:537: count: 5, input:size 1, 1b 
ERROR 2020-03-14T22:07:15.909 63660 tinput_read_cb:537: count: 4, input:size 24, 5d 31 31 3b 72 67 62 3a 31 65 31 65 2f 31 65 31 65 2f 31 65 31 65 1b 5c 
INFO  2020-03-14T22:07:17.587 63660 main:566: starting main loop
ERROR 2020-03-14T22:07:22.521 63660 tinput_read_cb:537: count: 2, input:size 1, 0a 
INFO  2020-03-14T22:07:35.673 63660 emsg_multiline:687: E481: No range allowed
ERROR 2020-03-14T22:07:37.608 63660 tinput_read_cb:537: count: 1, input:size 1, 69 
INFO  2020-03-14T22:07:41.033 63660 emsg_multiline:687: E37: No write since last change
INFO  2020-03-14T22:07:41.033 63660 emsg_multiline:687: E162: No write since last change for buffer "[No Name]"
INFO  2020-03-14T22:07:43.284 63660 os_exit:593: Nvim exit: 0
```
"starting main loop" logged after "tinput_read_cb" looks suspicious

**Comment by erw7** [comment]
@dm1try Thanks. Surprisingly, there is an interval of about 2 seconds between sending split bg responses. The default for `ttimeoutlen` is 50 ms, so it will time out and the first half of the bg response will be handled by the timer callback. As a result, it is not treated as a bg response but as normal input.

I don't know if that is appropriate, but if there is a possibility of a split bg response, we need to take action such as increasing the timeout. In that case, the terminal that does not return the bg response will have `ttimoutlen` of the first five inputs longer than necessary.

**Comment by erw7** [comment]
> "starting main loop" was logged after "tinput_read_cb" looks suspicious

Logging at line 566 in main.c starts the main loop at line 569, but tui starts at line 364 before that. Therefore, there should be no problem even if the "tinput_read_cb" log appears before the "starting main loop".

https://github.com/neovim/neovim/blob/2b00d1d09c0ff7ee6cc2de7ba70d9e84167540e5/src/nvim/main.c#L364

https://github.com/neovim/neovim/blob/2b00d1d09c0ff7ee6cc2de7ba70d9e84167540e5/src/nvim/main.c#L566-L569

**Comment by dm1try** [comment]
> @dm1try Thanks. Surprisingly, there is an interval of about 2 seconds between sending split bg responses.

I was unable to reproduce the behavior in normal usage, so I used `lldb` with breakpoint as previously; ~2 sec is for "disable breakpoint and continue"

**Comment by erw7** [comment]
From the log of https://github.com/neovim/neovim/pull/12004#issuecomment-599122959, it seems that the bg color response is split, which is the cause of this problem. In that case, I think the problem will be fixed by https://github.com/neovim/neovim/pull/12004/commits/569c21646874a2a47e4c6c69d96f00a9780f52b2. Nevertheless, if this has not been fixed, there are three possible causes:

1. When the interval between the divided responses is greater than to `ttimeoutlen`.
2. The format of the bg color response is incorrect.
3. If there is a bug in https://github.com/neovim/neovim/pull/12004/commits/569c21646874a2a47e4c6c69d96f00a9780f52b2.

I installed `Alacritty`, `ranger`, and `vifm` on `WSL` and tried it, but did not reproduce the phenomenon. Therefore, someone who has the environment in which the phenomenon occurs must determine the cause.

**Comment by iamjesper** [comment]
@erw7 i haven't been able to reproduce the issue with your changes. i was seeing both stuck paste and bg color responses on opening nvim _very_ frequently before (in kitty terminal). hoping this can be merged soon 🤞

**Comment by jamessan** [comment]
@erw7 Were there any other concerns you had with this pr, or was the WIP just because you wanted feedback from people that were experiencing the problem?

**Comment by erw7** [comment]
>  Were there any other concerns you had with this pr, or was the WIP just because you wanted feedback from people that were experiencing the problem?

I didn't have a reproducible environment for bg color response, and I wasn't sure if https://github.com/neovim/neovim/pull/12004/commits/779ed28eba18fe738b001a157a30e2792a88511d would solve the problem, so I went with WIP. There was some feedback that it was resolved, so if you look at it and the code looks OK, we should be fine to merge it in.

**Comment by erw7** [comment]
I just noticed that CI is failing, wait a minute.

**Comment by kylepollina** [comment]
Can we see if this can get merged? I believe it is fixing #11393

**Comment by clason** [comment]
@erw7 Would it be possible to add a functional test for this as well? Then it should be good to go.
