### PR TITLE
fix: considering opts.title as [string,string][] in _make_floating_pop_size

### LINKED ISSUE #33009: LSP: width calculation in util._make_floating_popup_size doesn't handle title as tuple
### Problem

https://github.com/neovim/neovim/pull/32585 will recalculate the width if we pass `title` opts by using `strdisplaywidth(opts.title)` without considering that we also supports `title` as tuple of `[string,hl-group]`

### Steps to reproduce using "nvim -u minimal_init.lua"

1. `nvim --clean`
2. `:lua vim.lsp.util.open_floating_preview({ 'Hello' }, 'plaintext', { title = {{'Title
', 'Normal'}} })`

Will give us `E5108: Error executing lua Vim:E730: Using a List as a String` error

### Expected behavior

_No response_

### Nvim version (nvim -v)

NVIM v0.11.0-dev-2060+g175c09bd66

### Language server name/version

NA

### Operating system/version

Linux alp 6.12.7-0-edge #\1-Alpine SMP PREEMPT_DYNAMIC Fri, 27 Dec 2024 17:33:58 +0000 x86_64 Linux

### Log file

_No response_

### PR DESCRIPTION
**Pull request by acehinnnqru**
Fix #33009

### CODE REVIEW

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -1412,7 +1412,18 @@ function M._make_floating_popup_size(contents, opts)
...
   if opts.title then
-    width = math.max(width, vim.fn.strdisplaywidth(opts.title))
+    local title = opts.title
+    local title_length = 0
+    if type(title) == 'string' then
+      title_length = vim.fn.strdisplaywidth(title)
+    else
+      if title ~= nil then
+        for i = 1, #title do
+          title_length = title_length + string.len(title[i][1])
```
Comment (phanen) [inline runtime/lua/vim/lsp/util.lua:1422]: maybe `string.len` -> `vim.fn.strdisplaywidth`
e.g. `string.len('你好') == 6`, but its actually 4.

Comment (luukvbaal) [reply runtime/lua/vim/lsp/util.lua:1422]: It seems the TODO comment above can be resolved and we should replace occurrences of `vim.fn.strdisplaywidth()` `vim.api.nvim_strwidth()` in this file?

Also, this entire block could be made a little less verbose like so:
```diff
diff --git a/runtime/lua/vim/lsp/util.lua b/runtime/lua/vim/lsp/util.lua
index 7c0d1a0ce8..8e68ff4fff 100644
--- a/runtime/lua/vim/lsp/util.lua
+++ b/runtime/lua/vim/lsp/util.lua
@@ -1411,20 +1411,12 @@ function M._make_floating_popup_size(contents, opts)
   width = math.min(width, screen_width - border_width)
 
   -- Make sure that the width is large enough to fit the title.
-  if opts.title then
-    local title = opts.title
-    local title_length = 0
-    if type(title) == 'string' then
-      title_length = vim.fn.strdisplaywidth(title)
-    else
-      if title ~= nil then
-        for i = 1, #title do
-          title_length = title_length + string.len(title[i][1])
-        end
-      end
-    end
-    width = math.max(width, title_length)
+  local title_length = 0
+  local chunks = type(opts.title) == 'string' and { { opts.title } } or opts.title or {}
+  for _, chunk in ipairs(chunks --[=[@as [string, string][]]=] ) do
+    title_length = title_length + api.nvim_strwidth(chunk[1])
   end
+  width = math.max(width , title_length)
 
   if wrap_at then
     wrap_at = math.min(wrap_at, width)
```

Comment (acehinnnqru) [reply runtime/lua/vim/lsp/util.lua]: That's pretty elegant, thanks for your advice.

Comment (zeertzjq) [reply runtime/lua/vim/lsp/util.lua]: `nvim_strwidth` does not respect 'tabstop', so it cannot be used for buffer text, but it can be used for float title where TABs do not work at all.

Comment (acehinnnqru) [reply runtime/lua/vim/lsp/util.lua]: Yeah, I found that the `nvim_strwidth` doesn't count the NUL char so some tests cannot pass

Comment (acehinnnqru) [reply runtime/lua/vim/lsp/util.lua]: so, I think I should use the `vim.fn.strdisplaywidth` but not `api.nvim_strwidth`

**Comment by acehinnnqru** [comment]
How should I change the `news.txt` @phanen

File: runtime/lua/vim/lsp/util.lua [hunk 2]
```diff
@@ -1411,10 +1411,16 @@ function M._make_floating_popup_size(contents, opts)
   width = math.min(width, screen_width - border_width)
 
   -- Make sure that the width is large enough to fit the title.
-  if opts.title then
-    width = math.max(width, vim.fn.strdisplaywidth(opts.title))
+  local title_length = 0
+  local chunks = type(opts.title) == 'string' and { { opts.title } } or opts.title or {}
+  for _, chunk in
+    ipairs(chunks --[=[@as [string, string][]]=])
+  do
```
Comment (zeertzjq) [inline runtime/lua/vim/lsp/util.lua:1418]:
```suggestion
  --- @type [string, string][]
  local chunks = type(opts.title) == 'string' and { { opts.title } } or opts.title or {}
  for _, chunk in ipairs(chunks) do
```
