### PR TITLE
fix(lsp): malformed edit if apply_text_edits() is called twice

### LINKED ISSUE #39344: LSP: applying vim.lsp.util.apply_text_edits twice causes an incorrect edit
### Problem

The diff preview logic breaks the edit and they are applied incorrectly after: https://github.com/ibhagwan/fzf-lua/issues/2701

### Steps to reproduce using "nvim --clean -u minimal_init.lua"

All steps to reproduce with the test are in the issue attached.

The test in the fzf-lua repo: https://github.com/IlyasYOY/fzf-lua/blob/0135a480db8e13cb4edd2c2a74ff4c10774c453c/tests/codeaction_spec.lua

### Expected behavior

The `vim.lsp.util.apply_text_edits` is safe to apply multiple times.

Maybe we should write the note about it in the docs.

### Nvim version (nvim -v)

NVIM v0.12.2

### Language server name/version

gopls

### Operating system/version

macos tahoe

### Log file

_No response_

### PR DESCRIPTION
**Pull request by geril07**
fix #39344

Problem:  
the same dict `text_edit` passed into `vim.lsp.util.apply_text_edit` twice(two independant function calls, but with the same `text_edit`) will result in incorrect "applying" behavior. Because of adding index and sorting in-place.

I found that it breaks `lspsaga` codeaction (specific actions), because the function is called once for preview, and then again to apply the action (second call with the same `text_edit`, described below).

Of course, it can be fixed on the plugin side, but you might consider handling it in core as well.

Reason:

1. `text_edits` is modified in place by setting `_index = index` for each `text_edit` in table order

   https://github.com/neovim/neovim/blob/8bccd07972523936fe536fdade22d2f72eab3ef0/runtime/lua/vim/lsp/util.lua#L322-L324

2. `text_edits` is reversed in place

   https://github.com/neovim/neovim/blob/8bccd07972523936fe536fdade22d2f72eab3ef0/runtime/lua/vim/lsp/util.lua#L343-L351

- The next `vim.lsp.util.apply_text_edit` call with the same `text_edits` will re-apply step 1, which results in wrong indexes, because the order was already reversed (step 2).

Real world example:

case: update multiline import

```typescript
import {
    x,
    y
} from "cool-lib";
```

To update the import, there are two edits:  
First is to add a comma after `y`,  
Second is to add the actual import name.

initial `text_edits`:

```lua
{ {
    newText = ",",
    range = {
      ["end"] = {
        character = 20,
        line = 12
      },
      start = {
        character = 20,
        line = 12
      }
    }
  }, {
    newText = "\n  useState",
    range = {
      ["end"] = {
        character = 20,
        line = 12
      },
      start = {
        character = 20,
        line = 12
      }
    }
  } }
```

After first call:

```lua
{ {
    _index = 2,
    newText = "\n  useState",
    range = {
      ["end"] = {
        character = 20,
        line = 12
      },
      start = {
        character = 20,
        line = 12
      }
    }
  }, {
    _index = 1,
    newText = ",",
    range = {
      ["end"] = {
        character = 20,
        line = 12
      },
      start = {
        character = 20,
        line = 12
      }
    }
  } }
```

After second call with the same `text_edit`:

```lua
{ {
    _index = 2,
    newText = ",",
    range = {
      ["end"] = {
        character = 20,
        line = 12
      },
      start = {
        character = 20,
        line = 12
      }
    }
  }, {
    _index = 1,
    newText = "\n  useState",
    range = {
      ["end"] = {
        character = 20,
        line = 12
      },
      start = {
        character = 20,
        line = 12
      }
    }
  } }
```

As you can see, because of incorrect `_index`(against initial `text_edits`), the order is after second call is different from result of first call.

Solution:  
Keep `_index` if it already exists. I haven't considered other use cases, so maybe this isn't the correct fix.

Another possible solution is to deepcopy `text_edits` to prevent in-place sorting.

Feel free to close this, as it can be solved on the plugin side(at least by deepcopying).

### CODE REVIEW

**Comment by ribru17** [comment]
Thanks for the thorough explanation. Just curious, what is the use case of storing text edits and potentially applying the same ones multiple times?

**Comment by geril07** [comment]
> Thanks for the thorough explanation. Just curious, what is the use case of storing text edits and potentially applying the same ones multiple times?

My use case is code actions, `lspsaga` and `fzf-lua`(only if a last element does not have comma at eol) are affected by this, `tiny-code-action.nvim` is fine though.
  
The issue because of preview implementation:
1. Request all code actions  - 1 time and provide them into callbacks(this is why sort in place affects them)
2. Generate preview(they use `apply_text_edits` on tmp buffer and then `vim.diff` to generate diff content) - first call of `vim.lsp.util.apply_text_edits`, sort in place + indexes for text_edits fetched in step 1.
3. User picks this code action - second call of `vim.lsp.util.apply_text_edits` with `text_edits` fetched in step 1 and modified in step 2 by preview implementation, wrong applying order if there are multiple edits per code action.

**Comment by ribru17** [comment]
Thanks, that makes sense.

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -321,7 +321,9 @@ function M.apply_text_edits(text_edits, bufnr, position_encoding, change_annotat
     -- Fix reversed range and indexing each text_edits
     for index, text_edit in ipairs(text_edits) do
       --- @cast text_edit lsp.TextEdit|{_index: integer}
-      text_edit._index = index
+      if text_edit._index == nil then
```
Comment (ribru17) [inline runtime/lua/vim/lsp/util.lua:326]: Maybe a comment here would be helpful

**Review by ribru17 — APPROVED** [review]

File: runtime/lua/vim/lsp/util.lua (hunk 1 above)
Comment (geril07) [reply runtime/lua/vim/lsp/util.lua:326]: Maybe `text_edits = vim.tbl_extend("force", {} ,text_edits)` or `text_edits = vim.deepcopy(text_edits)` or another way to shallow/deep copy at the top of the parent function would be more clear?

Comment (ribru17) [reply runtime/lua/vim/lsp/util.lua:326]: That could be expensive, especially if a lot of edits come in from a formatter eg. I think if deep copying is needed, it should be done in the plugin side. In fact, maybe a separate doc PR would be nice to explicitly say that this function modifies the table of edits?

Comment (geril07) [reply runtime/lua/vim/lsp/util.lua:326]: > In fact, maybe a separate doc PR would be nice to explicitly say that this function modifies the table of edits?

Yep, we can wait for another review and then decide what to do with that.

> That could be expensive, especially if a lot of edits come in from a formatter eg

Yeah, deepcopy is indeed can be expensive, but what about shallow copy like vim.tbl_extend, it will modify edits with indexes, but will sort only new object instead of provided one. I don't think it is expensive cause it only creates a new parent and fills it with existing children. For example formatting `eval.c` contains 1355 text edits with my config and `text_edits = vim.tbl_extend("force", {}, text_edits)` takes less than 1ms, `table.sort` is way more expensive.

**Comment by IlyasYOY** [comment]
I created the issue #39344 that seems to be solved by this PR.

I want to share the diff with the test-reproducer (using diff I faced problems with) and the fix: 

```diff
diff --git a/runtime/lua/vim/lsp/util.lua b/runtime/lua/vim/lsp/util.lua
index 9231976c58..b4dc06fde4 100644
--- a/runtime/lua/vim/lsp/util.lua
+++ b/runtime/lua/vim/lsp/util.lua
@@ -317,29 +317,36 @@ function M.apply_text_edits(text_edits, bufnr, position_encoding, change_annotat
   local has_eol_text_edit = false
 
   local function apply_text_edits()
-    -- Fix reversed range and indexing each text_edits
+    local normalized_edits = {}
+
+    -- Fix reversed range and index each text edit without mutating the caller's table.
     for index, text_edit in ipairs(text_edits) do
-      --- @cast text_edit lsp.TextEdit|{_index: integer}
-      text_edit._index = index
+      local start_range = text_edit.range.start
+      local end_range = text_edit.range['end']
 
       if
-        text_edit.range.start.line > text_edit.range['end'].line
-        or text_edit.range.start.line == text_edit.range['end'].line
-          and text_edit.range.start.character > text_edit.range['end'].character
+        start_range.line > end_range.line
+        or start_range.line == end_range.line and start_range.character > end_range.character
       then
-        local start = text_edit.range.start
-        text_edit.range.start = text_edit.range['end']
-        text_edit.range['end'] = start
+        start_range, end_range = end_range, start_range
       end
+
+      local new_text = string.gsub(text_edit.newText, '\r\n?', '\n')
+      normalized_edits[index] = {
+        range = {
+          start = start_range,
+          ['end'] = end_range,
+        },
+        newText = new_text,
+        _index = index,
+      }
     end
 
-    --- @cast text_edits (lsp.TextEdit|lsp.AnnotatedTextEdit|{_index: integer})[]
-
-    -- Sort text_edits
-    ---@param a (lsp.TextEdit|lsp.AnnotatedTextEdit|{_index: integer})
-    ---@param b (lsp.TextEdit|lsp.AnnotatedTextEdit|{_index: integer})
+    -- Sort text edits
+    ---@param a lsp.TextEdit|{_index: integer}
+    ---@param b lsp.TextEdit|{_index: integer}
     ---@return boolean
-    table.sort(text_edits, function(a, b)
+    table.sort(normalized_edits, function(a, b)
       if a.range.start.line ~= b.range.start.line then
         return a.range.start.line > b.range.start.line
       end
@@ -356,10 +363,7 @@ function M.apply_text_edits(text_edits, bufnr, position_encoding, change_annotat
       end
     end
 
-    for _, text_edit in ipairs(text_edits) do
-      -- Normalize line ending
-      text_edit.newText, _ = string.gsub(text_edit.newText, '\r\n?', '\n')
-
+    for _, text_edit in ipairs(normalized_edits) do
       -- Convert from LSP style ranges to Neovim style ranges.
       local start_row = text_edit.range.start.line
       local start_col = get_line_byte_from_position(bufnr, text_edit.range.start, position_encoding)
diff --git a/test/functional/plugin/lsp_spec.lua b/test/functional/plugin/lsp_spec.lua
index 84eb63beea..1f8e3a4d33 100644
--- a/test/functional/plugin/lsp_spec.lua
+++ b/test/functional/plugin/lsp_spec.lua
@@ -2244,6 +2244,57 @@ describe('LSP', function()
       }, buf_lines(1))
     end)
 
+    it('can apply the same text edit list to multiple buffers', function()
+      local result = exec_lua(function()
+        local function edit(start_col, end_col, new_text)
+          return {
+            range = {
+              start = { line = 0, character = start_col },
+              ['end'] = { line = 0, character = end_col },
+            },
+            newText = new_text,
+          }
+        end
+
+        local original_lines = {
+          'if strings.HasSuffix(name, suffix) {',
+          '\treturn strings.TrimSuffix(name, suffix)',
+          '}',
+        }
+
+        local text_edits = {
+          edit(3, 3, 'before, ok := '),
+          edit(3, 20, 'strings.CutSuffix'),
+        }
+        local before = vim.deepcopy(text_edits)
+
+        local function apply_to_new_buffer()
+          local bufnr = vim.api.nvim_create_buf(false, true)
+          vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, original_lines)
+          vim.lsp.util.apply_text_edits(text_edits, bufnr, 'utf-16')
+          local lines = vim.api.nvim_buf_get_lines(bufnr, 0, -1, false)
+          vim.api.nvim_buf_delete(bufnr, { force = true })
+          return lines
+        end
+
+        local first = apply_to_new_buffer()
+        local after_first = vim.deepcopy(text_edits)
+        local second = apply_to_new_buffer()
+
+        return {
+          before = before,
+          after_first = after_first,
+          after_second = text_edits,
+          first = first,
+          second = second,
+        }
+      end)
+
+      eq(result.first, result.second)
+      eq(result.before, result.after_first)
+      eq(result.before, result.after_second)
+    end)
+
     it('it restores marks', function()
       eq(true, api.nvim_buf_set_mark(1, 'a', 2, 1, {}))
       apply_text_edits({
```

Hope it helps!
