### PR TITLE
fix: show previews for nomodifiable buffers

### LINKED ISSUE #32016: command-preview: does not show in nomodifiable buffers
### Problem

Hello,

https://github.com/neovim/neovim/blob/e8a6c1b02122852da83dc52184e78369598d8240/src/nvim/ex_getln.c#L2706-L2709

`&& cmdpreview_may_show(s)) { `

won't run if the buffer is not modifiable, this makes it that so by default I can't add incremental previews for quickfix in custom user commands

### Steps to reproduce

```lua
vim.opt.icm = "split"

vim.api.nvim_create_user_command("PreviewTest", function() end, {
	preview = function()
		vim.api.nvim_buf_set_lines(0, 0, -1, false, { "if you see this it works" })
		return 2
	end,
})
```

`:set modifiable` works
`:set nomodifiable` does not work

### Expected behavior

I would expect incremental preview to work with nomodifiable buffers.

But I understand that it kinda makes sense to skip nomodifiable, because incremental preview should in theory change the buffer. But the preview function would just fail at that point and the plugin author is responsible that it wouldn't do that

Anyway, while I don't like it, this workaround works

```lua
	vim.api.nvim_create_autocmd("CmdlineEnter", {
		callback = function()
			vim.bo.modifiable = true 
		end,
	})
	vim.api.nvim_create_autocmd("CmdlineLeave", {
		callback = function()
			vim.bo.modifiable = false 
		end,
	})
```

### Nvim version (nvim -v)

0.10.3

### Vim (not Nvim) behaves the same?

no, does not have this functionality

### Operating system/version

Linux

### Terminal name/version

tmux

### $TERM environment variable

screen256

### Installation

pacman / tested with it built with source also

### Extra notes

I think that this should be in the help page ("Please note that incremental preview is skipped on nomodifiable buffers")

### PR DESCRIPTION
**Pull request by tronikelis**
closes #32016

The test fails if I add the check back in

### CODE REVIEW

File: test/functional/ui/inccommand_user_spec.lua [hunk 1]
```diff
@@ -253,6 +262,29 @@ describe("'inccommand' for user commands", function()
     ]]
   end)
 
+  it('preview shown with nomodifiable', function()
```
Comment (justinmk) [inline test/functional/ui/inccommand_user_spec.lua:265]:
```suggestion
  it("can preview 'nomodifiable' buffer", function()
```

File: test/functional/ui/inccommand_user_spec.lua [hunk 2]
```diff
@@ -253,6 +262,29 @@ describe("'inccommand' for user commands", function()
     ]]
   end)
 
+  it("can preview 'nomodifiable' buffer", function()
+    command('set nomodifiable')
```
Comment (justinmk) [inline test/functional/ui/inccommand_user_spec.lua:266]: You mentioned that you want to edit a quickfix buffer, so maybe it's worth setting up quickfix in this test. That gives extra coverage.

Also this test should make a small edit to the quickfix, then cancel the preview-command, then assert that the quickfix buffer was restored.

Also at the start and end of the test, assert that 'nomodifiable' is set on the buffer.

    eq(false, api.nvim_get_option_value('modifiable', {buf=<quickfix_buf_num>}))

File: test/functional/ui/inccommand_user_spec.lua (hunk 1 above)
Comment (tronikelis) [reply test/functional/ui/inccommand_user_spec.lua]: thanks

**Review by justinmk — APPROVED** [review]

File: test/functional/ui/inccommand_user_spec.lua (hunk 2 above)
Comment (justinmk) [reply test/functional/ui/inccommand_user_spec.lua:266]: What happens if the preview callback sets 'modifiable', is it able to edit the buffer?

Comment (tronikelis) [reply test/functional/ui/inccommand_user_spec.lua:266]: > What happens if the preview callback sets 'modifiable', is it able to edit the buffer?

Don't know, will check

Comment (tronikelis) [reply test/functional/ui/inccommand_user_spec.lua:266]: https://github.com/user-attachments/assets/f7542773-e37b-4dad-99fd-39b37e269aa4


nvim does not reset the modifiable, only the buffer lines it seems like

Comment (tronikelis) [reply test/functional/ui/inccommand_user_spec.lua:266]: I should add restoring  `modifiable` then right?

Comment (tronikelis) [reply test/functional/ui/inccommand_user_spec.lua:289]: Added in [`7b2e553` (#32034)](https://github.com/neovim/neovim/pull/32034/commits/7b2e553e47739081edc07e555246da5dc9ab54e5)

We can delete this commit if we decide that not restoring is the correct way to go

File: src/nvim/ex_getln.c [hunk 3]
```diff
@@ -168,6 +168,7 @@ typedef struct {
   pos_T save_b_op_end;
   varnumber_T save_changedtick;
   CpUndoInfo undo_info;
+  int save_b_p_ma;
```
Comment (justinmk) [inline src/nvim/ex_getln.c:171]: looking at `save_b_p_ul` above, should this be a `Opt...` type instead of `int`? 

rebase on latest master to make sure you have recent changes related to the options code.

File: test/functional/ui/inccommand_user_spec.lua [hunk 4]
```diff
@@ -253,6 +253,61 @@ describe("'inccommand' for user commands", function()
     ]]
   end)
 
+  it("restores 'modifiable'", function()
```
Comment (justinmk) [inline test/functional/ui/inccommand_user_spec.lua:256]: Don't need separate tests. The "can preview nomodifiable" test can also edit the buffer and assert the stuff this test is doing.

**Review by justinmk — APPROVED** [review]
This looks good after comments are resolved, thanks for following up. Would you mind adding an item to `:help news-features` "PLUGINS" section

File: src/nvim/ex_getln.c (hunk 3 above)
Comment (tronikelis) [reply src/nvim/ex_getln.c:171]: https://github.com/neovim/neovim/blob/8a236c242a76825a6a9266feda45794c7328c807/src/nvim/buffer_defs.h#L576-L576

It is `int` in the original spec, while ul is OptInt, so not sure, I guess we either change both to OptInt or leave as int?

Comment (zeertzjq) [reply src/nvim/ex_getln.c]: No

File: runtime/doc/news.txt [hunk 5]
```diff
@@ -148,7 +148,8 @@ OPTIONS
 
 PLUGINS
 
-• TODO
+• 'inccomand' incremental preview now runs on 'nomodifiable' buffers and
+  restores their 'modifiable' state
```
Comment (justinmk) [inline runtime/doc/news.txt:152]: this is in news-breaking. please find the PLUGINS section in news-features, below :)

File: runtime/doc/news.txt [hunk 6]
```diff
@@ -148,7 +148,8 @@ OPTIONS
 
 PLUGINS
 
-• TODO
+• 'inccomand' incremental preview now runs on 'nomodifiable' buffers and
```
Comment (justinmk) [inline runtime/doc/news.txt:151]:
```suggestion
• 'inccommand' incremental preview can run on 'nomodifiable' buffers and
```
