### PR TITLE
fix(lsp): set extra info only when it have value

### LINKED ISSUE #23867: Avoid triggering preview window in LSP omnicompletion when there is no info to display
### Problem

In [vim.lsp.util.text_document_completion_list_to_complete_items](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/util.lua#L696-L715), `info` defaults to `' '` (clear preview window) when it's not present. But this still results in the preview window opening when `completeopt` contains `preview` even when there is nothing to display for any of the entries.

### Expected behavior

I think if none of the entries have any documentation, `info` should not be populated for them so the preview window doesn't open at all.

### PR DESCRIPTION
**Pull request by glepnir**
problem: avoid show empty in preview buffer when `completeopt` has `preview`.

solution: check info byte size only insert when it have value 

Fix #23867

### CODE REVIEW

**Comment by mfussenegger** [comment]
Looks like some of the tests need to be changed

**Comment by glepnir** [comment]
should be fixed . other failed is random .

File: runtime/lua/vim/lsp/util.lua [hunk 1]
```diff
@@ -694,15 +694,15 @@ function M.text_document_completion_list_to_complete_items(result, prefix)
...
     local documentation = completion_item.documentation
     if documentation then
       if type(documentation) == 'string' and documentation ~= '' then
         info = documentation
       elseif type(documentation) == 'table' and type(documentation.value) == 'string' then
         info = documentation.value
-        -- else
-        -- TODO(ashkan) Validation handling here?
+      else
+        vim.notify('invalid type of documentation', vim.log.levels.WARN)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/util.lua:705]:
```suggestion
        vim.notify(('invalid documentation value: %s'):format(vim.inspect(documentation)), vim.log.levels.WARN)
```

**Review by justinmk — APPROVED** [review]

**Comment by glepnir** [comment]
can merge this.
