### PR TITLE
fix(api): allow empty list for cterm in nvim_set_hl

### LINKED ISSUE #17437: Allow `cterm` argument in `nvim_set_hl()` to be an empty table
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1101-g3230b3148

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Ubuntu 20.04

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

appimage

### How to reproduce the issue

1. `nvim --clean -u NONE`.
2. `:lua vim.api.nvim_set_hl(0, 'Comment', {foreground = 'blue', cterm = {}})`

### Expected behavior

Works the same as `:lua vim.api.nvim_set_hl(0, 'Comment', {foreground = 'blue'})`.

### Actual behavior

Gives a `E5108: Error executing lua [string ":lua"]:1: 'cterm' must be a Dictionary.` error.

### PR DESCRIPTION
**Pull request by clason**
Problem: when accessing `nvim_set_hl` from Lua, empty tables are converted
to empty lists, not dictionaries, resulting in an error for

    :lua vim.api.nvim_set_hl(0, "Comment", { cterm = {} })

Workaround: add an empty array as a special case when checking
`dict->cterm.type` and do nothing.

(Proper solution would be to handle this in `gen_api_dispatch.lua`.)

Resolves #17437 

@bfredl

### CODE REVIEW

File: src/nvim/highlight.c [hunk 1]
```diff
@@ -876,6 +876,9 @@ HlAttrs dict2hlattrs(Dict(highlight) *dict, bool use_rgb, int *link_id, Error *e
     CHECK_FLAG(cterm, cterm_mask, strikethrough, , HL_STRIKETHROUGH);
     CHECK_FLAG(cterm, cterm_mask, nocombine, , HL_NOCOMBINE);
 
+  } else if (dict->cterm.type == kObjectTypeArray && dict->cterm.data.array.size == 0) {
+    // empty list from Lua API should clear all cterm attributes
```
Comment (bfredl) [inline src/nvim/highlight.c:880]: should still have `cterm_mask_provided = true`

**Comment by bfredl** [comment]
I suppose this could have a simple test with `cterm={}` ?
