### PR TITLE
tui: Fix problem with italics when $TERM is screen in tmux

### LINKED ISSUE #12193: incorrect highlightning of italic text in tmux, introduced in commit: f3ffe0b32
- `nvim --version`:
NVIM v0.5.0-471-gfc98f2d58
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/petter/source/neovim/build/config -I/home/petter/source/neovim/src -I/home/petter/source/neovim/.deps/usr/include -I/usr/include -I/home/petter/source/neovim/build/src/n
vim/auto -I/home/petter/source/neovim/build/include
Compiled by petter@pwa-lnx

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/petter/local/share/nvim"

- `OS`: macOS/linux
- `$TERM`: screen-256color
- `tmux version`: tmux 2.9a 

### Steps to reproduce:
@erw7 
I have not investigated why the empty `plug` settings are needed to trigger the bug.

_/tmp/simple.vimrc:_
```
call plug#begin('~/.vim/plugged')
call plug#end()
" this is a comment

hi! Comment ctermfg=14 gui=italic guifg=#888888
set termguicolors
```

`nvim -u /tmp/simple.vimrc /tmp/simple.vimrc`

### Actual behaviour
Screenshot 2020-04-27 at 12 31 42

### Expected behaviour
Ignore the fact that the call to Plug was removed. It was just to _not_ trigger the bug, and show that the comment is correctly highlighted

Screenshot 2020-04-27 at 12 32 09

### PR DESCRIPTION
**Pull request by erw7**
Tmux uses `smso` to display italics when the default-terminal is `screen`, `screen-*`. That's not the display the user wants, so change it to do the same display as before f3ffe0b32.
fixes #12193.

### CODE REVIEW

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -1563,6 +1560,10 @@ static void patch_terminfo_bugs(TUIData *data, const char *term,
   bool mate_pretending_xterm = xterm && colorterm
     && strstr(colorterm, "mate-terminal");
   bool true_xterm = xterm && !!xterm_version && !bsdvt;
+  bool true_screen = screen && !os_getenv("TMUX");
```
Comment (teto) [inline src/nvim/tui/tui.c:1563]: do we really need `true_screen` ? I mean if TMUX is set while running screen, aren't you screwed anyway ?

Comment (erw7) [reply src/nvim/tui/tui.c:1563]: For `tmux` with `screen*` set in `$TERM`, `Ss/Se` etc. must output the `tmux` sequence(`CSI[%p1%d q/CSI[ q`) and only `sitm` must be treated like screen. So the name does not have to be `true_screen`, but it must identify the `tmux` and true `GNU Screen`.
