### PR TITLE
fix(cmdheight=0): fix various issues part3

### LINKED ISSUE #19834: cmdheight=0 breaks statusline
### Neovim version (nvim -v)

NVIM v0.8.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compiled by builder@5a2bfe33583d

### Vim (not Nvim) behaves the same?

no, vim doesn't have this option

### Operating system/version

Android 8.1

### Terminal name/version

Termux 0.118.

### $TERM environment variable

xterm-256color

### Installation

nightly build from apt

### How to reproduce the issue

# seems to only happen when you open a directory and not a file
vi "path/to/dir" +"set cmdheight=0" --clean

### Expected behavior

the statusline shouldn't overlap with commandline

### Actual behavior

https://user-images.githubusercontent.com/64137875/185442454-94da7665-99ca-429b-a5da-971474142268.mp4

this is likely caused by #19816

### PR DESCRIPTION
**Pull request by Shougo**
~~It is the port of https://github.com/vim/vim/pull/10893~~

And fixed in https://github.com/neovim/neovim/pull/19801 regression.

Fix #19834 #19184

### CODE REVIEW

File: src/nvim/message.c [hunk 1]
```diff
@@ -3135,6 +3135,8 @@ void msg_clr_eos_force(void)
               ' ', ' ', HL_ATTR(HLF_MSG));
     grid_fill(&msg_grid_adj, msg_row + 1, Rows, 0, Columns,
               ' ', ' ', HL_ATTR(HLF_MSG));
+  } else {
+    redraw_all_later(CLEAR);
```
Comment (bfredl) [inline src/nvim/message.c:3139]: use NOT_VALID plus `clear_cmdline = true`

Comment (Shougo) [reply src/nvim/message.c]: OK.

**Comment by Shougo** [comment]
I have found `:!{cmd}` is echoed doubled.  It is not dependent of `set cmdheight=0`.
It should be another PR?

**Comment by bfredl** [comment]
@Shougo yes, another PR.

**Comment by Shougo** [comment]
OK.  I will do it later.

**Comment by Shougo** [comment]
> I have found :!{cmd} is echoed doubled. It is not dependent of set cmdheight=0.
> It should be another PR?

I have created https://github.com/neovim/neovim/pull/19836 for it.

**Comment by zeertzjq** [comment]
This now needs a rebase.

**Comment by Shougo** [comment]
OK.  I have rebased.

**Comment by Shougo** [comment]
Some changes are not needed anymore.
I will check the code later.

**Comment by Shougo** [comment]
I have removed deprecated changes.

**Comment by Shougo** [comment]
I should fix command line problem like #19834.

**Comment by Shougo** [comment]
#19384 is already fixed in the PR.   I don't know other problems.

**Comment by akinsho** [comment]
> https://github.com/neovim/neovim/pull/19384 is already fixed in the PR. I don't know other problems.

@Shougo https://github.com/neovim/neovim/issues/19184 has regressed recently

**Comment by Shougo** [comment]
OK.  Reproduced.

File: src/nvim/getchar.c [hunk 2]
```diff
@@ -1697,7 +1697,7 @@ static void getchar_common(typval_T *argvars, typval_T *rettv)
 
   if (!ui_has_messages()) {
     // redraw the screen after getchar()
-    update_screen(UPD_NOT_VALID);
+    update_screen(UPD_CLEAR);
```
Comment (bfredl) [inline src/nvim/getchar.c:1700]: keep `NOT_VALID` but add `clear_cmdline` below.

**Comment by Shougo** [comment]
@akinsho Please test the branch.

**Comment by akinsho** [comment]
@Shougo seems to work correctly 👍🏿

**Comment by akinsho** [comment]
> @Shougo seems to work correctly 👍🏿

Ok turns out I was wrong on this one, I tested with a more minimal config than my normal one and the window redraw issue didn't reproduce (with the same sequence of windows), but when testing with my full config it does. I'm not sure what the difference is exactly without whittling it all the way down, also not sure if that's useful/relevant.

I went back to c08b408 and this works fine, but the latest commit (981881f) still triggers the bug.

**Comment by Shougo** [comment]
Thank you for the merge.

@akinsho Please create new issue with the minimal init.vim.  I will test it later.

@bfredl 

> keep NOT_VALID but add clear_cmdline below.

`NOT_VALID` does not work well.  What do you think?

**Comment by bfredl** [comment]
> NOT_VALID does not work well.

In what way does it not work? Need a screenshot or something so we can figure out what redraw is missing.

**Comment by akinsho** [comment]
The current behaviour I'm seeing looks like 👇🏿 (this is only with the last commit here, the one prior to that does not cause this)

https://user-images.githubusercontent.com/22454918/188838488-c3ace672-44c1-4de9-9438-6a045fb468da.mov

This however only happens with my full (non-minimal) config, using a minimal config that only loads `which-key.nvim` with some dummy keys this does not happen.

I'm currently trying to narrow down why this is and will open a new issue with a reproduction once I have it. It's essentially a regression of #19184

**Comment by akinsho** [comment]
I've opened #20106 tbh this issue is a direct regression of #19184 and reproduces in the same way, the only difference between the minimal config and my config I mentioned above was that I had pinned the plugin to an older commit and the author had since added in a workaround. He no longer calls `redraw` between windows and instead calls `mode` I've added a link to this work around in the issue. Either way I think it's down to the question of the difference between the commits and the redraw strategy which I'll leave to you.
