### PR TITLE
fix(stdpath): remove duplicate directories

### LINKED ISSUE #5462: XDG_* environment variables with doubled values source twice
- 0.1.4:

This is sure a problem of Gentoo (maybe Xfce of URxvt).
### Actual behaviour

When I am
- on Gentoo Linux (not on FreeBSD!)
- in Xfce4
- starting urxvt
- running directly zsh (not inside tmux!)

then I get XDG_\* paths with doubled values.

  % echo $XDG_DATA_DIRS 
  /usr/local/share:/usr/share:/usr/share
  % echo $XDG_CONFIG_DIRS 
  /etc/xdg:/etc/xdg

This sources the plugins under these directories twice
what leads to errors after unbanged function declarations.
### Expected behaviour

The misbehaviour is definitely not Neovim's fault.
Anyway it could be desirable that Neovim detects
the doubled directories and won't source the plugins
a second time.

### PR DESCRIPTION
**Pull request by glepnir**
Problem: XDG_* environment variables with doubled values source twice.

Solution: remove duplicate values in XDG_CONFIG_DIR or XDG_DATA_DIR.

Fix #5462
Close #12600

### CODE REVIEW

File: src/nvim/os/stdpaths.c [hunk 1]
```diff
@@ -93,6 +96,48 @@ bool appname_is_valid(void)
...
+    bool is_duplicate = false;
+    for (size_t i = 0; i < kv_size(data); i++) {
+      if (strcmp(kv_A(data, i), token) == 0) {
+        is_duplicate = true;
+        break;
+      }
+    }
+    // If it's not a duplicate, add it to the list
+    if (!is_duplicate) {
+      kv_push(data, xstrdup(token));
```
Comment (bfredl) [inline src/nvim/os/stdpaths.c:121]: I don't think the `xstrdup()` is necessary. I think the existing token will still remain valid even as `os_strtok()` returns the next.

Comment (glepnir) [reply src/nvim/os/stdpaths.c:121]: okay thx.

File: src/nvim/os/stdpaths.c [hunk 2]
```diff
@@ -2,13 +2,16 @@
 #include <stdbool.h>
 #include <string.h>
 
+#include "klib/kvec.h"
 #include "nvim/ascii_defs.h"
 #include "nvim/fileio.h"
+#include "nvim/garray.h"
```
Comment (zeertzjq) [inline src/nvim/os/stdpaths.c:8]: This doesn't seem needed

Comment (glepnir) [reply src/nvim/os/stdpaths.c:8]: seems like before auto import forget to remove.

File: src/nvim/runtime.h [hunk 3]
```diff
@@ -44,6 +44,8 @@ enum {
   DIP_DIRFILE = 0x200,  ///< find both files and directories
 };
 
+typedef kvec_t(char *) CharVec;
```
Comment (zeertzjq) [inline src/nvim/runtime.h:47]: I think this should be moved to `strings.h`

Comment (zeertzjq) [inline src/nvim/runtime.h:47]: This was only present in `runtime.c` because it is used in a function prototype. In `stdpaths.c` it can just be `kvec_t(char *)` as it's local variable.

Comment (glepnir) [reply src/nvim/runtime.h:47]: aha okay.  is it not useful in somewhere else for future usage?

Comment (zeertzjq) [reply src/nvim/runtime.h:47]: In any case `runtime.h` is not a suitable header for it, because it has nothing to do with "runtime".

Comment (glepnir) [reply src/nvim/runtime.h:47]: okay thanks got it.

**Comment by glepnir** [comment]
hmmm how xdg work on windows ..idk, build failed on windows inci.

File: src/nvim/runtime.h (hunk 3 above)
Comment (glepnir) [reply src/nvim/runtime.h]: could you please review

**Comment by glepnir** [comment]
emmm can someone review this ..

File: src/nvim/os/stdpaths.c [hunk 4]
```diff
@@ -131,6 +174,14 @@ char *stdpaths_get_xdg_var(const XDGVarType idx)
     ret = xmemdupz(ret, len >= 2 ? len - 1 : 0);  // Trim trailing slash.
   }
 
+  if ((idx == kXDGDataDirs || idx == kXDGConfigDirs)) {
+    char *sep = ":";
```
Comment (bfredl) [inline src/nvim/os/stdpaths.c:178]: I think we can use `ENV_SEPSTR` here which will be either `:` or `;` already.

File: src/nvim/os/stdpaths.c [hunk 5]
```diff
@@ -131,6 +174,14 @@ char *stdpaths_get_xdg_var(const XDGVarType idx)
...
+#ifdef BACKSLASH_IN_FILENAME
+    sep = ";",
+#endif
+    ret = xdg_remove_duplicate(ret, sep);
```
Comment (dundargoc) [inline src/nvim/os/stdpaths.c:182]:
```suggestion
    ret = xdg_remove_duplicate(ret, ENV_SEPSTR);
```

**Review by bfredl — APPROVED** [review]
LGTM, rebase

File: src/nvim/os/stdpaths.c [hunk 6]
```diff
@@ -93,6 +96,46 @@ bool appname_is_valid(void)
...
+{
+  kvec_t(char *) data = KV_INITIAL_VALUE;
+  char *saveptr;
+
+  char *token = os_strtok(ret, sep, &saveptr);
+  while (token != NULL) {
+    // Check if the directory is not already in the list
+    bool is_duplicate = false;
+    for (size_t i = 0; i < data.size; i++) {
+      if (striequal(kv_A(data, i), token)) {
```
Comment (zeertzjq) [inline src/nvim/os/stdpaths.c:112]: I don't think this is correct. It should use `path_fnamecmp()`.

Comment (glepnir) [reply src/nvim/os/stdpaths.c:112]: got it

File: src/nvim/os/stdpaths.c [hunk 7]
```diff
@@ -93,6 +96,46 @@ bool appname_is_valid(void)
   return true;
 }
 
+/// Remove duplicate directories in the given XDG directory.
+/// @param[in]  List of directories possibly with duplicates
+/// @param[out]  List of directories without duplicates
```
Comment (justinmk) [inline src/nvim/os/stdpaths.c:101]: params look wrong

File: src/nvim/os/stdpaths.c [hunk 8]
```diff
@@ -131,6 +174,10 @@ char *stdpaths_get_xdg_var(const XDGVarType idx)
     ret = xmemdupz(ret, len >= 2 ? len - 1 : 0);  // Trim trailing slash.
   }
 
+  if ((idx == kXDGDataDirs || idx == kXDGConfigDirs) && ret != NULL) {
+    ret = xdg_remove_duplicate(ret, ENV_SEPSTR);
```
Comment (justinmk) [inline src/nvim/os/stdpaths.c:178]: on Windows can we support both "/" and "\" ?

File: test/functional/options/defaults_spec.lua [hunk 9]
```diff
@@ -378,7 +378,7 @@ describe('XDG defaults', function()
             .. root_path
             .. ('/b'):rep(2048)
             .. '/nvim'
-            .. (',' .. root_path .. '/c/nvim'):rep(512)
+            .. (',' .. root_path .. '/c/nvim')
```
Comment (justinmk) [inline test/functional/options/defaults_spec.lua:381]: Nice!

File: src/nvim/os/stdpaths.c (hunk 8 above)
Comment (zeertzjq) [reply src/nvim/os/stdpaths.c:178]: How is that related to this line?

Comment (justinmk) [reply src/nvim/os/stdpaths.c:178]: Oh I thought `ENV_SEPSTR` was PATHSEP

**Comment by justinmk** [comment]
@glepnir coverity warning:

```
*** CID 488817:  Memory - illegal accesses  (STRING_NULL)
/src/nvim/os/stdpaths.c: 178 in stdpaths_get_xdg_var()
172         }
173         size_t len = strlen(ret);
174         ret = xmemdupz(ret, len >= 2 ? len - 1 : 0);  // Trim trailing slash.
175       }
176     
177       if ((idx == kXDGDataDirs || idx == kXDGConfigDirs) && ret != NULL) {
>>>     CID 488817:  Memory - illegal accesses  (STRING_NULL)
>>>     Passing unterminated string "ret" to "xdg_remove_duplicate", which expects a null-terminated string.
178         ret = xdg_remove_duplicate(ret, ENV_SEPSTR);
179       }
180     
181       return ret;
182     }
```

**Comment by ii14** [comment]
Looks like false positive? It thinks that xstrdup doesn't return a null terminated string
```
      4. string_null_source: Function xstrdup does not terminate its return value.[hide details]
      5. var_assign: Assigning: ret = xstrdup(env_val).
164    ret = xstrdup(env_val);
```
