### PR TITLE
fix(api): nvim_set_current_win doesn't reset Visual mode

### LINKED ISSUE #37072: ml_get error on redraw after switching window
## Steps to reproduce

```
local api, fn = vim.api, vim.fn
vim.cmd('new')
vim.cmd('wincmd w')
api.nvim_buf_set_lines(0, 0, -1, true, { 'a', 'b' })
api.nvim_win_set_cursor(0, { 2, 0 })
api.nvim_feedkeys(api.nvim_replace_termcodes('<C-q>', true, false, true), 'x', false)
-- vim.cmd('wincmd w') -- good
api.nvim_set_current_win(fn.win_getid(fn.winnr('#')))
vim.cmd.redraw() -- E315: ml_get: Invalid lnum: 2
```

## Expected behavior
no ml_get error on redraw

## System info

- Nvim version (nvim -v): `v0.12.0-dev-1877 ge1aceb0068` neovim/neovim@e1aceb0068
- Vim (not Nvim) behaves the same?: ?
- Operating system/version: Linux 6.17.9-zen1-1-zen
- Terminal name/version: kitty
- $TERM environment variable: `xterm-kitty`
- Installation: ?

### PR DESCRIPTION
**Pull request by glepnir**
Problem:
Using nvim_set_current_win() to switch windows while in Visual mode causes E315 ml_get error when target buffer has fewer lines. This doesn't happen with wincmd w since it properly resets Visual mode when switching buffers.

Solution:
Reset Visual mode when switching to different buffer, same as wincmd w.

Fix #37072

### CODE REVIEW

File: test/functional/api/vim_spec.lua [hunk 1]
```diff
@@ -2003,6 +2003,15 @@ describe('API', function()
       eq(api.nvim_list_wins()[2], api.nvim_get_current_win())
     end)
 
+    it('resets Visual mode when switching to different buffer #37072', function()
+      command('new | wincmd w')
+      api.nvim_buf_set_lines(0, 0, -1, true, { 'a', 'b' })
+      api.nvim_win_set_cursor(0, { 2, 0 })
+      api.nvim_feedkeys(api.nvim_replace_termcodes('<C-q>', true, false, true), 'x', false)
```
Comment (zeertzjq) [inline test/functional/api/vim_spec.lua]:
```suggestion
      feed('<C-q>')
      eq({ mode = '\022', blocking = false }, api.nvim_get_mode())
```
