### PR TITLE
fix(tui): don't set cursor color when there is none

### LINKED ISSUE #27611: `vim.opt.guicursor = "a:HIDDEN"` produces extra characters "ff" when entering command mode
### Problem

When entering command mode `:` extra characters "ff" show if the following options are active:
```lua
vim.api.nvim_set_hl(0, "HIDDEN", { blend = 100, nocombine = true })
vim.opt.guicursor = "a:HIDDEN"
```
This issue was initially discussed [here](https://github.com/folke/noice.nvim/issues/671) and it seems it is to be addressed to neovim core itself.

### Steps to reproduce

nvim --clean
```lua
vim.api.nvim_set_hl(0, "HIDDEN", { blend = 100, nocombine = true })
vim.opt.guicursor = "a:HIDDEN"
```
produces the flickering effect `ff` as per recording below:

https://github.com/neovim/neovim/assets/15387611/ac41e8f6-e0f0-44b6-8844-6c067e028d6c

### Expected behavior

No extra "ff" appear.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2433+g9418381cc

### Vim (not Nvim) behaves the same?

no, only on nightly

### Operating system/version

MacOs Monterey 12.7

### Terminal name/version

iTerm2 (Version 3.4.23)

### $TERM environment variable

TERM=xterm-256color

### Installation

building from source

### PR DESCRIPTION
**Pull request by Sam-programs**
*Presumably* Fixes: https://github.com/neovim/neovim/issues/27611
I say presumably, because i guessed since last time (https://github.com/neovim/neovim/issues/6584) writing the color from an undefined highlight caused a similar issue, it might be the same problem.

### CODE REVIEW

**Comment by Sam-programs** [comment]
Hey @gennaro-tedesco, Could you please check if this works ?

**Comment by gennaro-tedesco** [comment]
Building from this PR seems to indeed solve the problem (on `iTerm2` at least)!

File: src/nvim/tui/tui.c [hunk 1]
```diff
@@ -1233,6 +1233,9 @@ static void tui_set_mode(TUIData *tui, ModeShape mode)
     HlAttrs aep = kv_A(tui->attrs, c.id);
 
     tui->want_invisible = aep.hl_blend == 100;
+    if (tui->want_invisible || aep.rgb_bg_color == -1) {
+      return;
+    }
     if (!tui->want_invisible && aep.rgb_ae_attr & HL_INVERSE) {
```
Comment (zeertzjq) [inline src/nvim/tui/tui.c:1239]:
```suggestion
    if (aep.rgb_ae_attr & HL_INVERSE) {
```

File: src/nvim/tui/tui.c [hunk 2]
```diff
@@ -1233,6 +1233,9 @@ static void tui_set_mode(TUIData *tui, ModeShape mode)
     HlAttrs aep = kv_A(tui->attrs, c.id);
 
     tui->want_invisible = aep.hl_blend == 100;
+    if (tui->want_invisible || aep.rgb_bg_color == -1) {
+      return;
```
Comment (zeertzjq) [inline src/nvim/tui/tui.c:1237]: I don't think it should just return when the cursor background is invalid, because it still need to set cursor shape in the code below. Maybe the code to set cursor color should be moved into a separate function.
