### PR TITLE
fix(ui): empty line before the next message after :silent command

### LINKED ISSUE #12099: An extra line is displayed when using echo after an external command
- `nvim --version`: `NVIM v0.4.3`
- `vim -u DEFAULTS` (version: 8.0) behaves differently? This issue need a vimrc to be reproduced. 
- Operating system/version:`Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64`
- Terminal name/version: `Gnome terminal 3.28.2`
- `$TERM`: `xterm-256color`

### This is the vimrc that I am using to cause this problem. Save it a s 'minimal'
```
set nocompatible

function! DoEcho()
	silent !ls
	echo "llll"
endfunction

nnoremap <silent> p :call DoEcho()<CR>
```

### Steps to reproduce using `nvim -u minimal`

Press p

### Actual behaviour
After pressing p notice that you see a blank line the message that was echo'd and a prompt at the bottom of the screen.

```

llll
Press ENTER or type command to continue
```

### Expected behaviour
Just the echo'd message should be seen
```
llll
```

Vim version 8.0 only displays the echo'd message.

### Note
This only seems to happen when echo is called after running external commands, otherwise it behaves as expected.

### PR DESCRIPTION
**Pull request by ghost**
Problem:
  The next command after `silent !{cmd}` or `silent lua print('str')`
  prints an empty line before printing a message, because these commands
  set `msg_didout = true` despite not printing any messages.

Solution:
  Set `msg_didout = true` only if `msg_silent == 0`

fixes #12099

### CODE REVIEW

File: test/functional/ui/messages_spec.lua [hunk 1]
```diff
@@ -1061,6 +1062,39 @@ vimComment     xxx match /\s"[^\-:.%#=*].*$/ms=s+1,lc=1  excludenl contains=@vim
     -- luacheck: pop
   end)
 
+  it('no empty line after :silent #12099', function()
+    source([[
```
Comment (zeertzjq) [inline test/functional/ui/messages_spec.lua:1066]:
```suggestion
    exec([[
```

File: test/functional/ui/messages_spec.lua [hunk 2]
```diff
@@ -3,6 +3,7 @@ local Screen = require('test.functional.ui.screen')
 local clear, feed = helpers.clear, helpers.feed
 local eval = helpers.eval
 local eq = helpers.eq
+local source = helpers.source
```
Comment (zeertzjq) [inline test/functional/ui/messages_spec.lua:6]:
```suggestion
```
