### PR TITLE
input: Do not set high-bit. Preserve META modifier.

### LINKED ISSUE #2017: After pressing Escape and then a letter, it will output strange characters (eg <Esc>+j =ê)
I'm using one of the latest version of nvim:

```

NVIM 0.0.0-alpha (compiled Feb 17 2015 16:50:51)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/buildd/neovim-0.0.0+git201502170610+2~ubuntu14.10.1/build/config -I/build/buildd/neovim-0.0.0+git201502170610+2~ubuntu14.10.1/src -I/build/buildd/neovim-0.0.0+git201502170610+2~ubuntu14.10.1/.deps/usr/include -I/build/buildd/neovim-0.0.0+git201502170610+2~ubuntu14.10.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/buildd/neovim-0.0.0+git201502170610+2~ubuntu14.10.1/.deps/usr/include -I/usr/include -I/build/buildd/neovim-0.0.0+git201502170610+2~ubuntu14.10.1/build/src/nvim/auto -I/build/buildd/neovim-0.0.0+git201502170610+2~ubuntu14.10.1/build/include
Compiled by buildd@lgw01-13  Features included (+) or not (-):
+acl             +farsi           -mouse_gpm       +tag_old_static
+arabic          +file_in_path    +mouse_netterm   -tag_any_white
+autocmd         +find_in_path    +mouse_sgr       +termresponse
-browse          +folding         -mouse_sysmouse  +textobjects
+byte_offset     -footer          +mouse_urxvt     +title
+cindent         +fork()          +mouse_xterm     -toolbar
-clipboard       +gettext         +multi_byte      +user_commands
+cmdline_compl   +iconv           +multi_lang      +vertsplit
+cmdline_hist    +insert_expand   +path_extra      +virtualedit
+cmdline_info    +jumplist        +persistent_undo +visual
+comments        +keymap          +postscript      +visualextra
+conceal         +langmap         +printer         +viminfo
+cscope          +libcall         +profile         +vreplace
+cursorbind      +linebreak       +quickfix        +wildignore
+cursorshape     +lispindent      +reltime         +wildmenu
+dialog_con      +listcmds        +rightleft       +windows
+digraphs        +localmap        +scrollbind      +writebackup
-dnd             +menu            +signs           -X11
-ebcdic          +mksession       +smartindent     -xfontset
-emacs_tags      +modify_fname    +startuptime     -xsmp
+eval            +mouse           +statusline      -xterm_clipboard
+ex_extra        -mouseshape      +syntax
+extra_search    +mouse_dec       +tag_binary
   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "$HOME/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/nvim"
```

If I press `<Esc>` then `j` in insert mode, the character `ê` appears.
Same for all other keys.

However when I use `jj` (which I remapped), I don't get this behaviour. I don't get the behaviour on the console (inside tmux), and I don't get it with standard vim with the same configuration.

I have just rolledback to : NVIM 0.0.0-alpha (compiled Feb 16 2015 18:09:24) and this solves the problem (so the bug is really new)

Any Ideas ?

### LINKED ISSUE #2440: meta/alt chords, function keys, shift-tab broken in :terminal buffers
If I open a terminal buffer `:terminal` and attempt to use `Alt .` (to insert the last argument of the previous command) I get a unicode character instead (infact `Alt` with any key inserts a unicode character - thereby breaking many readline shortcuts that have become muscle memory)

`Ctrl` based readline chords work as expected.

OS: Debian Jessie
Nvim version: 0.0.0-alpha+201504141749 (compiled from `HEAD` on April 15th `a86193d` )
After checking - this has been the case since the introduction of `:terminal` buffers.

### LINKED ISSUE #3412: iTerm Option key as Esc works in vim but not neovim
I have the following in my .vimrc (which is also my .nvimrc):

```
map <ESC>0 :tabnext<CR>
map <ESC>9 :tabprevious<CR>
```

And in iTerm I have these settings:

preferences

So when I press Left-option+0 or Left-option+9 I navigate tabs in vim. neovim doesn't seem to recognize whatever iTerm does to send option as esc.

### LINKED ISSUE #3727: Meta/Alt key: Neovim does not follow the terminal behavior
As you know, a terminal emulator has two ways to handle the Alt (Meta) key:
* either it sets the 8th bit of the current character, i.e. `<M-j>` sends an `ê` — that’s what Gvim does;
* or it sends Escape before the character, i.e. `<M-j>` sends `<Esc>j` — which is the default behavior of most terminal emulators (xterm being an exception). Let’s call this the *8bit-clean* mode.

Unlike Vim and all TUI apps that I’ve used so far, Neovim never respects the terminal *8bit-clean* mode when set. This is particularily annoying in a `:terminal` buffer (see #2440), but can also be a blocker for editing any buffer that contains non-ASCII characters because Alt-* shortcuts cannot be used in insert mode any more.

As an example, an 8bit-clean Vim allows to use Alt-j/k instead of Ctrl-n/p in insert mode:
```vim
inoremap <Esc>j <C-n>
inoremap <Esc>k <C-p>
```

But in an non-8bit-clean Vim, this makes it impossible to insert an `ê` or an `ë` — it would trigger a Ctrl-n/p instead.

MacVim had a similar issue that has been solved with the `macmeta` pref:
* when true, the alt key sends Escape;
* when false, the alt key ~~sets the 8th bit~~ works as AltGr.

If it isn’t possible to follow the terminal emulator setting (= *“meta sets 8th bit”* or *“meta sends Escape”*), please consider implementing a similar `meta` setting.

### PR DESCRIPTION
**Pull request by justinmk**
Background: Vim internally wants to represent chorded input as
single-byte keys. extract_modifiers() _discards_ the meta/alt modifier,
but we need it for libvterm and libtermkey.

Closes #2440
Closes #3727
Closes #2017
Closes #3412 
References #2277
References #2254

https://github.com/neovim/neovim/issues/2017#issuecomment-140423557

> We [not libtermkey] are setting the high bit for some reason

https://github.com/neovim/neovim/issues/176#issuecomment-77834715

> libvtermkey requires the leading esc to parse alt/meta

https://github.com/neovim/neovim/pull/3246#issuecomment-136328450

> A program could do better than the current logic on some terminals, by
> asking for pure 8bit mode (S8C1T) and then immediately querying the
> mode again. If the result comes back as an 8bit single-byte CSI, then
> it can presume the mode setting was successful, and now the ESC prefix
> byte won't be seen in multibyte sequences; only as an Alt- prefix or
> a real Escape key. On such a terminal, it could therefore avoid
> needing to use that waiting timeout.

### CODE REVIEW

**Comment by justinmk** [comment]
If this tests pass, then this fixes some painful issues with `:term` and insert-mode. 

- It also seems to avoid the need for `setg escape-time` in tmux.
- Macros with `<esc>` and meta/alt keys seem to work at least as well as they do in Vim.

cc @leonerd @tarruda

**Comment by justinmk** [comment]
If there's a reason not to make this change (though tests seem fine with it, as well as all sanity checks I made locally), another option would be to "deserialize" the high-bit before it gets sent to libtermkey/libvterm.

File: src/nvim/keymap.c [hunk 1]
```diff
@@ -665,19 +662,12 @@ int extract_modifiers(int key, int *modp)
...
-    /* <C-@> is <Nul> */
-    if (key == 0)
+    if (key == 0) {  // <C-@> is <Nul>
       key = K_ZERO;
-  }
-  if ((modifiers & MOD_MASK_ALT) && key < 0x80
-      && !enc_dbcs                      /* avoid creating a lead byte */
-      ) {
-    key |= 0x80;
-    modifiers &= ~MOD_MASK_ALT;         /* remove the META modifier */
```
Comment (justinmk) [inline src/nvim/keymap.c]: By deleting this block, 

- we no longer set the high bit to represent alt
- the global `mod_mask` keeps the `MOD_MASK_ALT` flag

**Comment by leonerd** [comment]
I wholeheartedly endorse this concept.
This with any luck will mean that no longer will nvim conflate the ideas of the Unicode character ² and the modified key sequence <M-2> simply because of the coincidence that '2' | 0x80 == 0xb2 == U+00B2 == '²' and I for one would applaud.

**Comment by justinmk** [comment]
@leonerd Yes, I confirmed that this change fixes that (and reproduced the issue in the old build).

**Comment by myitcv** [comment]
I've had a look through the history of issues related to `imap` and meta keys... It's a long complicated history that I'm not sure I entirely follow so apologies if this repeats an existing issue or covers old ground.

With bcbcf235f61bd75f965f35897784ea618fe7acb8 I'm seeing a difference in behaviour between `xterm` and `urxvt`. Assuming the following common setup in each terminal:

```
nvim -u /dev/null
:imap <M-b> ffff
```

Now after entering insert mode and pressing `<M-b>` I see the following in `xterm`:

```
â
```

(which is wrong) and the following in `urxvt`:

```
ffff
```

(which is right)

Would very much appreciate any pointers on getting this resolved, but also improving my understanding of all this!

**Comment by myitcv** [comment]
Interestingly, if I try the example from [this comment](https://github.com/neovim/neovim/issues/3727#issuecomment-171592369) I see the same output from both terminals:

```
$ nvim -u NONE -c 'imap <m-e> X' -c 'nmap t iåäö <m-e><esc>ZZ' -s <(echo 't') test.txt  
$ cat test.txt 
åäö X
```

**Comment by myitcv** [comment]
Problem solved by setting the following in my `~/.Xresources`:

```
 XTerm*eightBitInput:   false
 XTerm*eightBitOutput:  true
```

(per [this article](https://www.gnu.org/software/emacs/manual/html_node/efaq/Meta-key-does-not-work-in-xterm.html))

Is it expected that these settings should be required?

**Comment by justinmk** [comment]
@myitcv this is the first I've heard of a problem with this change. What are xterm's defaults for those settings? 

> Is it expected that these settings should be required?

If your terminal is setting the high bit for meta, it won't work with most console apps AFAIK. We *could* support it without regressing this PR, I think...

 I don't know why the output setting would be needed...

**Comment by leonerd** [comment]
Setting eighth-bit high for meta would be a terrible idea. It breaks your Unicode/UTF-8 handling. In fact, not doing that is precisely the reason that mixed modified "lower" keypresses + Unicode input works at all.

**Comment by justinmk** [comment]
@leonerd Thanks. So there's really not much reason to support that mode anyways.

> I don't know why the output setting would be needed...

Explained nicely here ;) http://www.leonerd.org.uk/hacks/hints/xterm-8bit.html

@myitcv Based on http://superuser.com/q/285306 it sounds like something may have change your xterm settings. I would assume that most distros these days use the settings recommended by the above URL, so that meta can be sent while also allowing UTF8 input. At least this is how iTerm2 and mintty are configured by default.

**Comment by myitcv** [comment]
@leonerd @justinmk - thanks. As I said, I'm rather fumbling round in the dark here so appreciate your pointers.

@leonerd using http://www.leonerd.org.uk/hacks/hints/xterm-8bit.html (which explains things well) I've got things 'working', insofar as the `<M-b>` mapping is working. How does the entry of unicode characters work with these settings?
