### PR TITLE
screen: disable redrawing inside VimResized

### LINKED ISSUE #10002: Crash on terminal resize when :redraw in VimResized autocmd
Neovim crashes when I resized the terminal.

## Crash log from Console.app

```
Process:               nvim [18509]
Path:                  /usr/local/Cellar/neovim/HEAD-24f9dd7/bin/nvim
Identifier:            nvim
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        fish [2522]
Responsible:           nvim [18509]
User ID:               501

Date/Time:             2019-05-12 16:25:42.094 +0800
OS Version:            Mac OS X 10.14.4 (18E226)
Report Version:        12
Anonymous UUID:        88878A0D-0019-DE09-DD59-72FD5376FB50

Sleep/Wake UUID:       714D4EA0-4A4D-4222-908B-4D907A7A10AA

Time Awake Since Boot: 1300000 seconds
Time Since Wake:       2800 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [18509]

VM Regions Near 0x18:
--> 
    Kernel Alloc Once      0000000000a2b000-0000000000a2d000 [    8K] rw-/rwx SM=PRV  

Application Specific Information:
dyld2 mode

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   nvim                          	0x0000000100bea21d compose_line.llvm.11774104478415050106 + 277
1   nvim                          	0x0000000100be5b29 ui_call_raw_line + 115
2   nvim                          	0x0000000100be7439 ui_line + 113
3   nvim                          	0x0000000100b8f010 grid_puts_line_flush + 121
4   nvim                          	0x0000000100b63b5f pum_redraw + 2163
5   nvim                          	0x0000000100b89e99 update_screen + 1704
6   nvim                          	0x0000000100ac276c ex_redraw + 127
7   nvim                          	0x0000000100ab7127 do_one_cmd + 10840
8   nvim                          	0x0000000100ab3782 do_cmdline + 2619
9   nvim                          	0x0000000100ae18a0 apply_autocmds_group.llvm.2037159362387770779 + 1659
10  nvim                          	0x0000000100b8f46b screenalloc + 305
11  nvim                          	0x0000000100b8a1b4 screenclear + 19
12  nvim                          	0x0000000100b902cf screen_resize + 193
13  nvim                          	0x0000000100be6e39 ui_refresh + 667
14  nvim                          	0x0000000100a9cb4f multiqueue_process_events + 75
15  nvim                          	0x0000000100a9c289 loop_poll_events + 159
16  nvim                          	0x0000000100b5b553 inbuf_poll.llvm.14317494157321383050 + 441
17  nvim                          	0x0000000100b5b2a8 os_inchar + 280
18  nvim                          	0x0000000100bc766c state_enter + 98
19  nvim                          	0x0000000100a5694d edit + 2081
20  nvim                          	0x0000000100b3d479 invoke_edit + 80
21  nvim                          	0x0000000100b36470 normal_execute.llvm.7159707725037764212 + 4547
22  nvim                          	0x0000000100bc76d1 state_enter + 199
23  nvim                          	0x0000000100b080eb main + 9973
24  libdyld.dylib                 	0x00007fff60f213d5 start + 1

Thread 1:
0   libsystem_platform.dylib      	0x00007fff6110470a _platform_memchr$VARIANT$Haswell + 42
1   libunibilium.4.dylib          	0x0000000100d5691f unibi_format + 3605
2   nvim                          	0x0000000100be26c3 unibi_out_ext + 204
3   nvim                          	0x0000000100be48c0 update_attrs + 978
4   nvim                          	0x0000000100be4f94 print_cell + 51
5   nvim                          	0x0000000100be1d8b tui_raw_line.llvm.12076205206185074196 + 202
6   nvim                          	0x0000000100be9650 ui_bridge_raw_line_event + 72
7   nvim                          	0x0000000100a9cb4f multiqueue_process_events + 75
8   nvim                          	0x0000000100a9c289 loop_poll_events + 159
9   nvim                          	0x0000000100be2205 tui_main.llvm.12076205206185074196 + 852
10  libsystem_pthread.dylib       	0x00007fff6110f2eb _pthread_body + 126
11  libsystem_pthread.dylib       	0x00007fff61112249 _pthread_start + 66
12  libsystem_pthread.dylib       	0x00007fff6110e40d thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00000000ffffffae  rbx: 0x0000000000000000  rcx: 0x0000000000000002  rdx: 0x00007fea59409360
  rdi: 0x0000000000000053  rsi: 0x0000000100c85540  rbp: 0x00007ffeef1e2ff0  rsp: 0x00007ffeef1e2f50
   r8: 0x0000000000000065   r9: 0x0000000000000052  r10: 0x0000000000000000  r11: 0x0000000000000052
  r12: 0x0000000000000000  r13: 0xffffffffffffffae  r14: 0x0000000000000052  r15: 0x0000000000000018
  rip: 0x0000000100bea21d  rfl: 0x0000000000010293  cr2: 0x0000000000000018
  
Logical CPU:     4
Error Code:      0x00000004
Trap Number:     14


Binary Images:
       0x100a1b000 -        0x100c4dff7 +nvim (0) <6FD3D7AC-F90C-3F44-ABBF-0B5CBB9468E6> /usr/local/bin/nvim
       0x100cee000 -        0x100cf6ff7 +libintl.8.dylib (0) <2BE4B1C7-92C9-39E9-B4A7-F880907047DB> /usr/local/opt/gettext/lib/libintl.8.dylib
       0x100d00000 -        0x100d19ff7 +libuv.1.dylib (0) <1E72BC0F-C92C-3E7F-B395-187BDA95AFDC> /usr/local/opt/libuv/lib/libuv.1.dylib
       0x100d28000 -        0x100d2cfff +libmsgpackc.2.dylib (0) <5C85ECA5-64EC-3121-BD69-050BF482916C> /usr/local/opt/msgpack/lib/libmsgpackc.2.dylib
       0x100d34000 -        0x100d3dffb +libvterm.0.dylib (0) <26B9DB21-BE39-35C8-AFE9-74D421DCA2E9> /usr/local/opt/libvterm/lib/libvterm.0.dylib
       0x100d48000 -        0x100d4dffb +libtermkey.1.dylib (0) <F4D448A7-58DF-3771-B560-3C6E5177A1F6> /usr/local/opt/libtermkey/lib/libtermkey.1.dylib
       0x100d52000 -        0x100d59fff +libunibilium.4.dylib (0) <696AD650-DAC4-3C62-A298-6A5D04EA3061> /usr/local/opt/unibilium/lib/libunibilium.4.dylib
       0x100d60000 -        0x100de0ff7 +libluajit-5.1.2.dylib (0) <E35F8224-B3F2-3F6F-81EF-4D354AF1A877> /usr/local/opt/luajit/lib/libluajit-5.1.2.dylib
       0x10de88000 -        0x10def26ef  dyld (655.1.1) <F217F7F8-A795-3109-B77F-B1E2277F3E3B> /usr/lib/dyld
    0x7fff34a6e000 -     0x7fff34eb1fff  com.apple.CoreFoundation (6.9 - 1570.16) <F3DFF269-6705-35AD-9F01-66D77DD1B518> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff5d8a6000 -     0x7fff5d8a7ffb  libDiagnosticMessagesClient.dylib (107) <B5675E8C-2F34-3E0A-B7E8-6F2373589038> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff5dce5000 -     0x7fff5dce6ffb  libSystem.B.dylib (1252.250.1) <72841192-B0C9-36A0-8E55-ED651EADEF08> /usr/lib/libSystem.B.dylib
    0x7fff5df28000 -     0x7fff5df7bff7  libc++.1.dylib (400.9.4) <446DAE5E-4E97-3E4B-B2A3-AC0A74C0E453> /usr/lib/libc++.1.dylib
    0x7fff5df7c000 -     0x7fff5df91ff7  libc++abi.dylib (400.17) <A2D1FDAD-E10F-3E53-958F-CB6BC8485767> /usr/lib/libc++abi.dylib
    0x7fff5df92000 -     0x7fff5df92ff3  libcharset.1.dylib (51.200.6) <0D3A5F4C-8800-33E3-AFE5-307E8BEE462C> /usr/lib/libcharset.1.dylib
    0x7fff5eaad000 -     0x7fff5eb9dfff  libiconv.2.dylib (51.200.6) <E767B418-3531-3BB0-B58D-9ECB203407B7> /usr/lib/libiconv.2.dylib
    0x7fff5eb9e000 -     0x7fff5edfeff3  libicucore.A.dylib (62123.0.1) <3936C798-1978-3C6C-9050-3BBD57CDA53E> /usr/lib/libicucore.A.dylib
    0x7fff5f6df000 -     0x7fff5fe64fdf  libobjc.A.dylib (756.2) <4F86FC7C-496B-3E68-8A74-1EA2BA22FBCC> /usr/lib/libobjc.A.dylib
    0x7fff60493000 -     0x7fff60496ff7  libutil.dylib (51.200.4) <336F9184-A739-3770-ACFA-4659DFEEACC4> /usr/lib/libutil.dylib
    0x7fff605b5000 -     0x7fff605c7ff7  libz.1.dylib (70.200.4) <FDF169F3-F992-3E8E-B3F7-D4134FEBAE41> /usr/lib/libz.1.dylib
    0x7fff60da4000 -     0x7fff60da8ff3  libcache.dylib (81) <9A8C27B0-49C9-337F-8BE2-37171ED2D8EE> /usr/lib/system/libcache.dylib
    0x7fff60da9000 -     0x7fff60db3ff3  libcommonCrypto.dylib (60118.250.2) <17C4F395-9FF0-331F-8167-5E85AA3588E9> /usr/lib/system/libcommonCrypto.dylib
    0x7fff60db4000 -     0x7fff60dbbff7  libcompiler_rt.dylib (63.4) <8CB2B2B6-2C55-3733-9842-0E037AE3F46A> /usr/lib/system/libcompiler_rt.dylib
    0x7fff60dbc000 -     0x7fff60dc5ff7  libcopyfile.dylib (146.250.1) <24905E41-9E2F-3DD1-A255-5A17F9FCDAD7> /usr/lib/system/libcopyfile.dylib
    0x7fff60dc6000 -     0x7fff60e4afc7  libcorecrypto.dylib (602.250.23) <3A6CBD41-AFFE-3E06-B1EC-3E95BC79BAC5> /usr/lib/system/libcorecrypto.dylib
    0x7fff60ed1000 -     0x7fff60f0aff7  libdispatch.dylib (1008.250.7) <50235FCE-B399-3319-90DC-88F530D4FC5C> /usr/lib/system/libdispatch.dylib
    0x7fff60f0b000 -     0x7fff60f37ff7  libdyld.dylib (655.1.1) <54C6B494-4A3D-3EEC-B083-636A76AAD649> /usr/lib/system/libdyld.dylib
    0x7fff60f38000 -     0x7fff60f38ffb  libkeymgr.dylib (30) <BEA04E04-FCF1-3A70-810F-08D0FF54CA36> /usr/lib/system/libkeymgr.dylib
    0x7fff60f46000 -     0x7fff60f46ff7  liblaunch.dylib (1336.251.2) <30E6424E-4640-3DBA-9B64-D5F725263C6E> /usr/lib/system/liblaunch.dylib
    0x7fff60f47000 -     0x7fff60f4cfff  libmacho.dylib (927.0.2) <D8515A20-ED7B-3B13-9ADA-4BD7E19E38C4> /usr/lib/system/libmacho.dylib
    0x7fff60f4d000 -     0x7fff60f4fffb  libquarantine.dylib (86.220.1) <8A9BF971-DB7D-311A-B131-6C5025E82F8F> /usr/lib/system/libquarantine.dylib
    0x7fff60f50000 -     0x7fff60f51ff7  libremovefile.dylib (45.200.2) <950036B7-B91E-3B5D-853C-8C551E5B6A32> /usr/lib/system/libremovefile.dylib
    0x7fff60f52000 -     0x7fff60f69ff3  libsystem_asl.dylib (356.200.4) <16F632AD-FADA-3DE9-85E8-EBC7D619A1DA> /usr/lib/system/libsystem_asl.dylib
    0x7fff60f6a000 -     0x7fff60f6aff7  libsystem_blocks.dylib (73) <0CD6861B-EC5F-3345-9C24-B21EEB85E44F> /usr/lib/system/libsystem_blocks.dylib
    0x7fff60f6b000 -     0x7fff60ff2fff  libsystem_c.dylib (1272.250.1) <F3AA9047-EEDD-3D80-8CC1-023FB312EC8B> /usr/lib/system/libsystem_c.dylib
    0x7fff60ff3000 -     0x7fff60ff6ffb  libsystem_configuration.dylib (963.250.1) <02C7A973-014A-31D7-B7D2-247D384CB0D2> /usr/lib/system/libsystem_configuration.dylib
    0x7fff60ff7000 -     0x7fff60ffaff7  libsystem_coreservices.dylib (66) <4CF1C89B-FA6C-3DF3-B1F8-79F549849534> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff60ffb000 -     0x7fff61001fff  libsystem_darwin.dylib (1272.250.1) <6983A268-20F4-3F98-A3F5-D63848933B02> /usr/lib/system/libsystem_darwin.dylib
    0x7fff61002000 -     0x7fff61008ff7  libsystem_dnssd.dylib (878.250.4) <9FC5724C-DD03-3E14-A6E1-2DD009D79E0A> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff61009000 -     0x7fff61054ffb  libsystem_info.dylib (517.200.9) <F617D3CF-5A4A-36D0-8CBB-4A7C7CDB67AF> /usr/lib/system/libsystem_info.dylib
    0x7fff61055000 -     0x7fff6107dff7  libsystem_kernel.dylib (4903.251.3) <84EF0290-6CB5-36E5-A273-692A7E437B36> /usr/lib/system/libsystem_kernel.dylib
    0x7fff6107e000 -     0x7fff610c9ff7  libsystem_m.dylib (3158.200.7) <33105665-CCC3-36D5-82C9-9B21730CB3DF> /usr/lib/system/libsystem_m.dylib
    0x7fff610ca000 -     0x7fff610eefff  libsystem_malloc.dylib (166.251.2) <90DA09E3-1276-3FCF-8F5F-C9AA61AB9B6D> /usr/lib/system/libsystem_malloc.dylib
    0x7fff610ef000 -     0x7fff610f9ff7  libsystem_networkextension.dylib (767.250.2) <4575D797-B793-3D18-9E93-8696CF0B133B> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff610fa000 -     0x7fff61101fff  libsystem_notify.dylib (172.200.21) <679E9132-1A46-326E-9A11-D3FF9C86041C> /usr/lib/system/libsystem_notify.dylib
    0x7fff61102000 -     0x7fff6110bfef  libsystem_platform.dylib (177.250.1) <3CC59141-5365-3848-94C3-D65E6FCA1E74> /usr/lib/system/libsystem_platform.dylib
    0x7fff6110c000 -     0x7fff61116ff7  libsystem_pthread.dylib (330.250.2) <4344198A-A1A3-3C52-97B4-F168D56E9789> /usr/lib/system/libsystem_pthread.dylib
    0x7fff61117000 -     0x7fff6111aff7  libsystem_sandbox.dylib (851.250.12) <66E91015-F62A-3365-BB81-AA88707E8F12> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff6111b000 -     0x7fff6111dff3  libsystem_secinit.dylib (30.220.1) <F054DCB0-68CE-35E7-8B8C-D648C42124EC> /usr/lib/system/libsystem_secinit.dylib
    0x7fff6111e000 -     0x7fff61125ff3  libsystem_symptoms.dylib (820.257.1) <C8517F35-E9DA-3649-B07D-2B38349C6730> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff61126000 -     0x7fff6113bfff  libsystem_trace.dylib (906.250.5) <AE77ACC7-488F-3AE1-BB0C-1ACFC7E1CE77> /usr/lib/system/libsystem_trace.dylib
    0x7fff6113d000 -     0x7fff61142ffb  libunwind.dylib (35.4) <8F0BC197-B97C-3DDC-92B0-6A7D3CB72FD8> /usr/lib/system/libunwind.dylib
    0x7fff61143000 -     0x7fff61172ff7  libxpc.dylib (1336.251.2) <49138829-09C8-355C-B558-97E070B84EC5> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1268887
    thread_create: 0
    thread_set_state: 207

VM Region Summary:
ReadOnly portion of Libraries: Total=244.2M resident=0K(0%) swapped_out_or_unallocated=244.2M(100%)
Writable regions: Total=98.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=98.8M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                    8K        1 
MALLOC                            81.3M       27 
MALLOC guard page                   16K        4 
MALLOC_LARGE (reserved)            860K        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        2 
Stack                             16.0M        2 
VM_ALLOCATE                        128K        1 
__DATA                            4028K       57 
__LINKEDIT                       222.0M       10 
__TEXT                            22.2M       53 
__UNICODE                          564K        1 
shared memory                       12K        3 
===========                     =======  ======= 
TOTAL                            403.3M      163 
TOTAL, minus reserved VM space   402.4M      163 

```

- `nvim --version`:  Current master

```
NVIM v0.4.0-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190512-2929-1vmkkfc/build/config -I/tmp/neovim-20190512-2929-1vmkkfc/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190512-2929-1vmkkfc/build/src/nvim/auto -I/tmp/neovim-20190512-2929-1vmkkfc/build/include
Compiled by blahgeek@Rereturn

Features: +acl +iconv +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-24f9dd7/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently? N/A
- Operating system/version: macOS 10.14.4
- Terminal name/version: Kitty master
- `$TERM`: `xterm-256color`

### PR DESCRIPTION
**Pull request by bfredl**
Fixes #10002

While it doesn't crash anymore, master is still very glitchy with popupmenu (try completing on the end of a wrapped line and resize). I will see if I can make a test.

### CODE REVIEW

File: src/nvim/screen.c [hunk 1]
```diff
@@ -5989,7 +5993,14 @@ void grid_assign_handle(ScreenGrid *grid)
...
 {
-  static bool entered = false;  // avoid recursiveness
+  // It's possible that we produce an out-of-memory message below, which
+  // will cause this function to be called again.  To break the loop, just
+  // return here.
+  if (resizing) {
+    return;
+  }
+  resizing = true;
+
```
Comment (justinmk) [inline src/nvim/screen.c]: would clearing `default_grid.chars`  work instead?

Comment (bfredl) [reply src/nvim/screen.c]: Instead of what? `grid_alloc()` will clear the grid as a consequence of reallocating it.

Comment (justinmk) [reply src/nvim/screen.c]: instead of the extra `resize` variable. `default_grid.chars == NULL` is checked by `update_screen` already.

Comment (bfredl) [reply src/nvim/screen.c]: This would imply moving `VimResized` before `grid_alloc()`, and has other consequences. It could subtly change the behaviour other things (like if VimResized caused a message, will message.c think `printf()` should be used instead of the screen, as there is no screen)?

Also a resize shouldn't by necessity imply that the screen ever has to be deallocated. It would inhibit stuff like possibly use `xrealloc` as an optimization, or a later protocol revision avoiding `grid_clear` on resize (possibly by there being no `default_grid` to start with).

**Comment by blueyed** [comment]
Re the flaky test: https://github.com/neovim/neovim/pull/10401

**Comment by bfredl** [comment]
Unrelated failure:
```
[----------] Running tests from /home/travis/build/neovim/neovim/test/functional/plugin/man_spec.lua
[ RUN      ] :Man man.lua: highlight_line() clears backspaces from text and adds highlights: 18.49 ms OK
==================== File /home/travis/build/neovim/neovim/build/log/ubsan.16412 ====================
= =================================================================
= ==16412==ERROR: AddressSanitizer: SEGV on unknown address 0x000001ead170 (pc 0x0000004577a1 bp 0x7ffcfbaca5b0 sp 0x7ffcfbaca540 T0)
= ==16412==The signal is caused by a WRITE memory access.
=     #0 0x4577a0 in __asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType) (/home/travis/build/neovim/neovim/build/bin/nvim+0x4577a0)
=     #1 0x50ac5c in __interceptor_cfree.localalias.0 (/home/travis/build/neovim/neovim/build/bin/nvim+0x50ac5c)
=     #2 0x112cd14 in xfree /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:118:3
=     #3 0x13ba498 in free_string_option /home/travis/build/neovim/neovim/build/../src/nvim/option.c:2305:5
=     #4 0x13b9bb5 in free_all_options /home/travis/build/neovim/neovim/build/../src/nvim/option.c:969:9
=     #5 0x112f037 in free_all_mem /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:649:3
=     #6 0x146db75 in mch_exit /home/travis/build/neovim/neovim/build/../src/nvim/os_unix.c:102:3
=     #7 0x12176f2 in exit_event /home/travis/build/neovim/neovim/build/../src/nvim/msgpack_rpc/channel.c:557:5
=     #8 0xb87cdc in multiqueue_process_events /home/travis/build/neovim/neovim/build/../src/nvim/event/multiqueue.c:150:7
=     #9 0xb807ba in loop_poll_events /home/travis/build/neovim/neovim/build/../src/nvim/event/loop.c:66:3
=     #10 0x14553c3 in os_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/os/input.c:167:5
=     #11 0x11ac767 in line_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/misc1.c:2739:5
=     #12 0x15e9a9f in nfa_regmatch /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6252:5
=     #13 0x15c7b08 in nfa_regtry /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6326:16
=     #14 0x15c5ebc in nfa_regexec_both /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6496:12
=     #15 0x157ef53 in nfa_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6642:10
=     #16 0x1534c8e in vim_regexec_string /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7241:16
=     #17 0x1535b57 in vim_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7293:10
=     #18 0xa6797b in find_some_match /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:12802:15
=     #19 0x9d4187 in f_matchstr /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:13080:3
=     #20 0x906917 in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6553:11
=     #21 0x91a42e in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6294:11
=     #22 0x9af921 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4397:15
=     #23 0x9abec3 in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4094:7
=     #24 0x9a9637 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3942:7
=     #25 0x9a493f in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3678:7
=     #26 0x9a3e1c in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3596:7
=     #27 0x9a32ec in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3527:7
=     #28 0x8fecb2 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3454:7
=     #29 0x8ff430 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3493:9
=     #30 0x8fe0ca in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3414:9
=     #31 0x90b022 in ex_let_const /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1604:9
=     #32 0x90b4f6 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1545:3
=     #33 0xc9276e in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2248:5
=     #34 0xc70a10 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #35 0x93b1da in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22618:3
=     #36 0x90623b in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6538:11
=     #37 0x91a42e in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6294:11
=     #38 0x9af921 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4397:15
=     #39 0x9abec3 in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4094:7
=     #40 0x9a9637 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3942:7
=     #41 0x9a493f in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3678:7
=     #42 0x9a3e1c in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3596:7
=     #43 0x9a32ec in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3527:7
=     #44 0x8fecb2 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3454:7
=     #45 0x8fe0ca in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3414:9
=     #46 0x90bc94 in eval_for_line /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2666:7
=     #47 0xd40422 in ex_while /home/travis/build/neovim/neovim/build/../src/nvim/ex_eval.c:967:14
=     #48 0xc9276e in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2248:5
=     #49 0xc70a10 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #50 0x93b1da in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22618:3
=     #51 0x90623b in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6538:11
=     #52 0x91a42e in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6294:11
=     #53 0x9af921 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4397:15
=     #54 0x9abec3 in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4094:7
=     #55 0x9a9637 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3942:7
=     #56 0x9a493f in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3678:7
=     #57 0x9a3e1c in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3596:7
=     #58 0x9a32ec in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3527:7
=     #59 0x8fecb2 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3454:7
=     #60 0x8fe0ca in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3414:9
=     #61 0x90b022 in ex_let_const /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1604:9
=     #62 0x90b4f6 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1545:3
=     #63 0xc9276e in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2248:5
=     #64 0xc70a10 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #65 0x93b1da in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22618:3
=     #66 0x90623b in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6538:11
=     #67 0x91a42e in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6294:11
=     #68 0x912ece in ex_call /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2891:9
=     #69 0xc9276e in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2248:5
=     #70 0xc70a10 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
=     #71 0xc56060 in do_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:3228:3
=     #72 0xc508be in source_callback /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2368:9
=     #73 0xc50174 in do_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2446:15
=     #74 0xc5057b in do_in_path_and_pp /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2490:12
=     #75 0xc50891 in source_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2538:10
=     #76 0x10023ee in load_plugins /home/travis/build/neovim/neovim/build/../src/nvim/main.c:1351:5
=     #77 0xff4124 in main /home/travis/build/neovim/neovim/build/../src/nvim/main.c:382:3
=     #78 0x7feb0353882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
=     #79 0x4527b8 in _start (/home/travis/build/neovim/neovim/build/bin/nvim+0x4527b8)
= 
= AddressSanitizer can not provide additional info.
= SUMMARY: AddressSanitizer: SEGV (/home/travis/build/neovim/neovim/build/bin/nvim+0x4577a0) in __asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType)
= ==16412==ABORTING
=====================================================================================================
test/helpers.lua:152: assertion failed!
stack traceback:
	test/helpers.lua:152: in function 'check_logs'
	test/functional/helpers.lua:845: in function <test/functional/helpers.lua:841>
[ RUN      ] :Man man.lua: highlight_line() clears escape sequences from text and adds highlights: 17.85 ms OK
```
