### PR TITLE
fix(checkhealth): when plugin has nested lua directory

### LINKED ISSUE #32913: :checkhealth fails if plugin has nested "lua" directory
### Problem

I get this error when I run `:checkhealth`:

```
.:                                                 require("..health").check()

- ERROR Failed to run healthcheck for "." plugin. Exception:
  [string "require("..health").check()"]:1: module '..health' not found:
        no field package.preload['..health']
        no file './//health.lua'
        no file '/home/<user>/dev/neovim/.deps/usr/share/luajit-2.1///health.lua'
        no file '/usr/local/share/lua/5.1///health.lua'
        no file '/usr/local/share/lua/5.1///health/init.lua'
        no file '/home/<user>/dev/neovim/.deps/usr/share/lua/5.1///health.lua'
        no file '/home/<user>/dev/neovim/.deps/usr/share/lua/5.1///health/init.lua'
        no file './//health.so'
        no file '/usr/local/lib/lua/5.1///health.so'
        no file '/home/<user>/dev/neovim/.deps/usr/lib/lua/5.1///health.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './.so'
        no file '/usr/local/lib/lua/5.1/.so'
        no file '/home/<user>/dev/neovim/.deps/usr/lib/lua/5.1/.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

### Steps to reproduce

Create a folder structure in `.config/nvim` that looks like this:
```
$tree
.
└── lua
    └── lsp
        └── lua
            └── health.lua
```
open `nvim` and run `:checkhealt`

### Expected behavior

The healt chekc in `./lua/lsp/lua/health.lua` should run normally

### Nvim version (nvim -v)

NVIM v0.11.0-dev-2010+g4662ad5643

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

WezTerm

### $TERM environment variable

xterm-256color

### Installation

Compile From Source

### PR DESCRIPTION
**Pull request by phanen**
Problem: `:checkhealth` fails if plugin has nested "lua" directory

Solution: trim `{runtimepath}/lua` from fullpath to get subpath (`./**/{health, health/init.lua}`)

Fix https://github.com/neovim/neovim/issues/32913.

### CODE REVIEW

File: test/functional/plugin/health_spec.lua [hunk 1]
```diff
@@ -212,6 +212,18 @@ describe('vim.health', function()
       n.expect([[
       ERROR: No healthchecks found.]])
     end)
+
+    it('handle nested lua directory', function()
```
Comment (justinmk) [inline test/functional/plugin/health_spec.lua:216]:
```suggestion
    it('nested lua/ directory', function()
```

**Review by justinmk — APPROVED** [review]
Thanks! Nice approach too

File: runtime/lua/vim/health.lua [hunk 2]
```diff
@@ -118,7 +118,10 @@ local function filepath_to_healthcheck(path)
     func = 'health#' .. name .. '#check'
     filetype = 'v'
   else
-    local subpath = path:gsub('.*/lua/', '')
+    local rtp = vim.iter(vim.api.nvim_list_runtime_paths()):find(function(rtp0)
+      return vim.fs.relpath(rtp0, path)
+    end)
+    local subpath = path:gsub('^' .. vim.pesc(rtp .. '/lua/'), '')
```
Comment (justinmk) [inline runtime/lua/vim/health.lua:124]: just guessing, but maybe this will fix the windows ci failure: 

```suggestion
    local subpath = path:gsub('^' .. vim.pesc(rtp) .. '[\\/]lua[\\/]', '')
```

example diff of windows ci failure:

image

Comment (phanen) [reply runtime/lua/vim/health.lua:127]: The results of `nvim_get_runtime_file`/`nvim_list_runtime_paths` both need to normalized (`\` -> `/`) for windows.

**Comment by micampe** [comment]
@phanen since this commit (I verified by bisecting) all my plugins (telescope being the only exception) are failing check health with the same error:

```
`==============================================================================
.Users.micampe..local.share.nvim.site.pack.deps.opt.conform.nvim.lua.conform: require(".Users.micampe..local.share.nvim.site.pack.deps.opt.conform.nvim.lua.conform.health").check()

- ERROR Failed to run healthcheck for ".Users.micampe..local.share.nvim.site.pack.deps.opt.conform.nvim.lua.conform" plugin. Exception:
  [string "require(".Users.micampe..local.share.nvim.sit..."]:1: module '.Users.micampe..local.share.nvim.site.pack.deps.opt.conform.nvim.lua.conform.health' not found:
          no field package.preload['.Users.micampe..local.share.nvim.site.pack.deps.opt.conform.nvim.lua.conform.health']
          no file './/Users/micampe//local/share/nvim/site/pack/deps/opt/conform/nvim/lua/conform/health.lua'
          no file '/Users/micampe/src/neovim/.deps/usr/share/luajit-2.1//Users/micampe//local/share/nvim/site/pack/deps/opt/conform/nvim/lua/conform/health.lua'
          no file '/usr/local/share/lua/5.1//Users/micampe//local/share/nvim/site/pack/deps/opt/conform/nvim/lua/conform/health.lua'
          no file '/usr/local/share/lua/5.1//Users/micampe//local/share/nvim/site/pack/deps/opt/conform/nvim/lua/conform/health/init.lua'
          no file '/Users/micampe/src/neovim/.deps/usr/share/lua/5.1//Users/micampe//local/share/nvim/site/pack/deps/opt/conform/nvim/lua/conform/health.lua'
          no file '/Users/micampe/src/neovim/.deps/usr/share/lua/5.1//Users/micampe//local/share/nvim/site/pack/deps/opt/conform/nvim/lua/conform/health/init.lua'
          no file './/Users/micampe//local/share/nvim/site/pack/deps/opt/conform/nvim/lua/conform/health.so'
          no file '/usr/local/lib/lua/5.1//Users/micampe//local/share/nvim/site/pack/deps/opt/conform/nvim/lua/conform/health.so'
          no file '/Users/micampe/src/neovim/.deps/usr/lib/lua/5.1//Users/micampe//local/share/nvim/site/pack/deps/opt/conform/nvim/lua/conform/health.so'
          no file '/usr/local/lib/lua/5.1/loadall.so'
          no file './.so'
          no file '/usr/local/lib/lua/5.1/.so'
          no file '/Users/micampe/src/neovim/.deps/usr/lib/lua/5.1/.so'
          no file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by phanen** [comment]
I have no idea what happened, what's your `:=vim.api.nvim_list_runtime_paths()`?

Just guessing but if you have nested rtp?
e.g. have both `/a/` and `/a/b/`
then `/a/b/foo/lua/health.lua` could be mistakenly `gsub` with `/a/lua` rather than `/a/b/lua` so gsub will do nothing then `subpath` remain to be abspath.
https://github.com/neovim/neovim/blob/f5dd30948e67b0bfbfe0f1023a9b0c8a0b20b486/runtime/lua/vim/health.lua#L121-L127
