### PR TITLE
fix (#19250): make_filter_cmd for powershell commands with arguments

### LINKED ISSUE #19250: Powershell command to call jq broken in 0.7.2
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

Windows Terminal

### $TERM environment variable

unsure

### Installation

Download portable artifact from github releases

### How to reproduce the issue

Hey all,

Windows 10, Neovim 0.7.2, pwsh set as my shell using:

```
if (has('win32'))
	" let &shell = has('win32') ? 'powershell' : 'pwsh'
	let &shell = 'pwsh'
	let &shellcmdflag = '-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;'
	let &shellredir = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
	let &shellpipe = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
	set shellquote= shellxquote=
	set noshelltemp " FROM: https://superuser.com/a/1561892/69729, Sorts out the issue with shell returned 1, E485 and temp files
endif

```

I have this mapping, which worked for a long time, and recently stopped working for me:

```
nnoremap <leader>=j :%!jq --tab .<cr>:%s/\r<cr>
```

This sends my file to jq, uses tabs for indent and formats the file, and then I remove `\r` throughout the file.

The problem I'm now having is I get the following error when it's run:

```
:%!jq --tab .
shell returned 1

:%s/\r/e
```

When I press enter, I get the shell error:

```
[91mStart-Process: [91mA positional parameter cannot be found that accepts argument '.'.[0me
```

I run Neovim 0.7.2, in Windows. I've set my Neovim shell to be PowerShell.

This used to work, and I've just verified that this works in Neovim 0.7.0.

Does anyone know of anything that changed that I need to take into account in my mapping? Or do you think that they somehow broke something in 0.7.2?

I have run `set verbose=5` to see the command, and it's showing:
```
Executing command: "Start-Process jq --tab ."

shell returned 1
625 lines filtered
:%s/\r
Press ENTER or type command to continue

```

I have had a brief look at the ex commands file, and found a bunch of changes that COULD maybe impact this?
https://github.com/neovim/neovim/commit/f977f9445f7689fc32a136108ff92b3c2137968c

I hope I gave enough information, let me know if there is anything else I can help with.

Cheers,

### Expected behavior

It should format my json file.

### Actual behavior

It's throwing a shell error

### PR DESCRIPTION
**Pull request by 3N4N**
Closes #19250.

PowerShell's `Start-Process` requires the arguments of a shell command to be passed as a separate string, as the value of the `-ArgumentList` parameter.

### CODE REVIEW

**Comment by 3N4N** [comment]
There are two commits. Both requires attention.

1. First one removes a lot of duplicate code from `make_filter_cmd`
2. Second one is the actual fix for the bug

**Comment by 3N4N** [comment]
The Windows test needs a rerun. It tested green on my fork.

And I need guidance on this `os_strtok_r` suggestion made by "CI / lint".

**Comment by 3N4N** [comment]
@zeertzjq I'm facing the same crash I faced [here](https://github.com/neovim/neovim/pull/16271#issuecomment-1161098596). That time you noticed I was passing the wrong length to xstrcat. Could you check this commit, too?

**Comment by zeertzjq** [comment]
Actually this crash has been happening occasionally for some weeks.

**Comment by zeertzjq** [comment]
```
= =================================================================
= ==26705==ERROR: LeakSanitizer: detected memory leaks
= 
= Direct leak of 8 byte(s) in 1 object(s) allocated from:
=     #0 0x4df7ad in malloc ??:?
=     #1 0x1286502 in try_malloc /home/runner/work/neovim/neovim/src/nvim/memory.c:75:15
=     #2 0x12866fc in xmalloc /home/runner/work/neovim/neovim/src/nvim/memory.c:109:15
=     #3 0x1286c96 in xmallocz /home/runner/work/neovim/neovim/src/nvim/memory.c:188:15
=     #4 0x1286dee in xmemdupz /home/runner/work/neovim/neovim/src/nvim/memory.c:206:17
=     #5 0x12881f8 in xstrdup /home/runner/work/neovim/neovim/src/nvim/memory.c:425:10
=     #6 0xc6b423 in make_filter_cmd /home/runner/work/neovim/neovim/src/nvim/ex_cmds.c:1600:45
=     #7 0xc688a2 in do_filter /home/runner/work/neovim/neovim/src/nvim/ex_cmds.c:1358:13
=     #8 0xc669ab in do_bang /home/runner/work/neovim/neovim/src/nvim/ex_cmds.c:1242:5
=     #9 0xd9cf1a in ex_bang /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:8621:3
=     #10 0xd0ba85 in do_one_cmd /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:2321:5
=     #11 0xcf8cd5 in do_cmdline /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:596:20
=     #12 0x13beea6 in nv_colon /home/runner/work/neovim/neovim/src/nvim/normal.c:4034:20
=     #13 0x13a9ff1 in normal_execute /home/runner/work/neovim/neovim/src/nvim/normal.c:1164:3
=     #14 0x1a9a628 in state_enter /home/runner/work/neovim/neovim/src/nvim/state.c:88:26
=     #15 0x1378e70 in normal_enter /home/runner/work/neovim/neovim/src/nvim/normal.c:463:3
=     #16 0x10a4017 in main /home/runner/work/neovim/neovim/src/nvim/main.c:573:3
=     #17 0x7fddd4a58082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
= 
= SUMMARY: AddressSanitizer: 8 byte(s) leaked in 1 allocation(s).
```

File: src/nvim/ex_cmds.c [hunk 1]
```diff
@@ -1583,22 +1583,43 @@ char *make_filter_cmd(char *cmd, char *itmp, char *otmp)
...
-  // redirecting input and/or output.
   if (is_pwsh) {
     xstrlcpy(buf, "Start-Process ", len);
-    xstrlcat(buf, cmd, len);
+    if (cmd_args == NULL) {
+      xstrlcat(buf, cmd, len);
+    } else {
+      char *con = NULL;
+      char *dupcmd = xstrdup(cmd);
+      const char *const cmd_cmd = os_strtok(dupcmd, " ", &con);
```
Comment (justinmk) [inline src/nvim/ex_cmds.c:1601]: this looks fragile, won't it break if the command itself has a space in the name? e.g.

    "My Documents\foo" ...

File: test/functional/vimscript/system_spec.lua [hunk 2]
```diff
@@ -653,4 +653,34 @@ describe('shell :!', function()
         4]])
     end
   end)
+  it(':{range}! with powershell filter/redirect when command has arguments #19250', function()
```
Comment (justinmk) [inline test/functional/vimscript/system_spec.lua:656]: looks like we can just update the above test instead of adding an entirely new test. Just add `/R` to the above test.

**Review by justinmk — APPROVED** [review]
+1 to merge this after the test is adjusted, because this improves things and adds test coverage. But hopefully we can find a solution that doesn't involve parsing.

File: src/nvim/ex_cmds.c [hunk 3]
```diff
@@ -1583,22 +1583,43 @@ char *make_filter_cmd(char *cmd, char *itmp, char *otmp)
...
+      xstrlcat(buf, cmd_cmd, len);
```
Comment (justinmk) [inline src/nvim/ex_cmds.c:1602]: `cmd_cmd` may be NULL if `dupcmd` does not contains `" "`.

File: src/nvim/ex_cmds.c [hunk 4]
```diff
@@ -1583,22 +1583,43 @@ char *make_filter_cmd(char *cmd, char *itmp, char *otmp)
...
-  // Put delimiters around the command (for concatenated commands) when
-  // redirecting input and/or output.
   if (is_pwsh) {
     xstrlcpy(buf, "Start-Process ", len);
-    xstrlcat(buf, cmd, len);
+    if (cmd_args == NULL) {
+      xstrlcat(buf, cmd, len);
+    } else {
+      char *con = NULL;
+      char *dupcmd = xstrdup(cmd);
```
Comment (justinmk) [inline src/nvim/ex_cmds.c:1600]: why is `dupcmd` needed? `xstrlcat` takes care of copying stuff.

File: test/functional/vimscript/system_spec.lua (hunk 2 above)
Comment (3N4N) [reply test/functional/vimscript/system_spec.lua]: Done.

File: src/nvim/ex_cmds.c (hunk 3 above)
Comment (3N4N) [reply src/nvim/ex_cmds.c:1602]: I handled that case with `cmd_args`. If `cmd` (and by extension `dupcmd`) doesn't contain a space, then `cmd_args` will be NULL, so this block won't be executed.

File: src/nvim/ex_cmds.c (hunk 4 above)
Comment (3N4N) [reply src/nvim/ex_cmds.c:1600]: I am duplicating `cmd` into `dupcmd` so that the original `cmd` isn't modified, because `cmd` is used later in L1649 (of my commit; L1636 in master).

https://github.com/neovim/neovim/blob/1b462705d049fa0cf2bb99bae9112b84abea8d5a/src/nvim/ex_cmds.c#L1636

File: src/nvim/ex_cmds.c (hunk 3 above)
Comment (3N4N) [reply src/nvim/ex_cmds.c:1602]: But maybe I should add an if(!null) anyway, to be idiomatic.

File: test/functional/vimscript/system_spec.lua [hunk 5]
```diff
@@ -630,15 +630,18 @@ end)
...
     local found = helpers.set_shell_powershell(true)
+
     insert([[
       3
       1
       4
       2]])
+
+    -- when command has no argument
     feed(':4verbose %!sort<cr>')
```
Comment (justinmk) [inline test/functional/vimscript/system_spec.lua:645]: just change this one, we don't need a separate test case

Comment (3N4N) [reply test/functional/vimscript/system_spec.lua]: Oh, right.

Done.

**Comment by 3N4N** [comment]
I think this pipe may work:

```powershell
Get-Content .\in.txt | sort.exe -r | Out-File .\out.txt
```

One immediate problem with this is that the command can clash with powershell alias (that's why I had to add `.exe` after `sort`: pwsh by default has `sort` aliased to `Sort-Object`). But that should be handled by the user, right?

There probably are other edge cases. I'll try this out for a couple of days before preemptively opening a PR.

File: test/functional/vimscript/system_spec.lua [hunk 6]
```diff
@@ -639,18 +639,25 @@ describe('shell :!', function()
...
-    }
+    if iswin() then
+      feed(':4verbose %!sort /R<cr>')
+      screen:expect{
+        any=[[Executing command: .?Start%-Process sort %-ArgumentList " /R" %-RedirectStandardInput .* %-RedirectStandardOutput .* %-NoNewWindow %-Wait]]
+      }
+    else
+      feed(':4verbose %!sort -r<cr>')
+      screen:expect{
+        any=[[Executing command: .?Start%-Process sort %-ArgumentList " %-r" %-RedirectStandardInput .* %-RedirectStandardOutput .* %-NoNewWindow %-Wait]]
```
Comment (justinmk) [inline test/functional/vimscript/system_spec.lua:650]: Wonder if we need to worry about the leading space. Depends on how powershell sends the args to the process and whether the process is prepared to trim whitespace around args.
```suggestion
        any=[[Executing command: .?Start%-Process sort %-ArgumentList "%-r" %-RedirectStandardInput .* %-RedirectStandardOutput .* %-NoNewWindow %-Wait]]
```

Comment (3N4N) [reply test/functional/vimscript/system_spec.lua:650]: Leading spaces should be here. This PR is keeping the spaces in `cmd_args`. The command that gets executed is the one `make_filter_cmd()` returns, so the leading spaces should exist.

Or are you suggesting I trim the spaces around `cmd_args` myself? That seems too much hassle, honestly.

File: src/nvim/ex_cmds.c [hunk 7]
```diff
@@ -1583,22 +1583,43 @@ char *make_filter_cmd(char *cmd, char *itmp, char *otmp)
...
+      const char *const cmd_cmd = os_strtok(dupcmd, " ", &con);
+      xstrlcat(buf, cmd_cmd, len);
+      xstrlcat(buf, " -ArgumentList \"", len);
+      xstrlcat(buf, cmd_args, len);
+      xstrlcat(buf, "\"", len);
+      xfree(dupcmd);
```
Comment (justinmk) [inline src/nvim/ex_cmds.c:1606]: wait, why are we using strtok at all? We already got the pointer to `cmd_args` which tells us where the command name ends. So this becomes (not tested):

```suggestion
      xstrlcpy(buf + strlen(buf), cmd, cmd_arg - cmd);
      xstrlcat(buf, " -ArgumentList \"", len);
      xstrlcat(buf, cmd_args + 1, len);  // +1 to skip the leading space.
      xstrlcat(buf, "\"", len);
```

Comment (justinmk) [inline src/nvim/ex_cmds.c:1606]: wait, why are we using strtok at all? We already got the pointer to `cmd_args` which tells us where the command name ends. So this becomes (not tested):

```suggestion
      xstrlcpy(buf + strlen(buf), cmd, cmd_arg - cmd);
      xstrlcat(buf, " -ArgumentList \"", len);
      xstrlcat(buf, cmd_args + 1, len);  // +1 to skip the leading space.
      xstrlcat(buf, "\"", len);
```

File: test/functional/vimscript/system_spec.lua (hunk 6 above)
Comment (justinmk) [reply test/functional/vimscript/system_spec.lua:650]: we aren't trimming anything, we're just dealing with a consequence of the parsing we're doing. The example in https://github.com/neovim/neovim/issues/19250#issuecomment-1176757468 looks like:

```
Start-Process jq -ArgumentList "--tab . .\locations.json"
                                ^ no space here
```

Comment (3N4N) [reply test/functional/vimscript/system_spec.lua:650]:
```powershell
Start-Process jq -ArgumentList "--tab . .\locations.json"
                                ^ no space here
```

But there should be space. The user will run this command --

```vim
:!jq --tab . .\locations.json
```

This PR (as of now, before I commit your suggestion below) will convert the ex command above into the following --

```powershell
Start-Process jq -ArgumentList " --tab . .\locations.json"
                                ^ one space here
```

---

The test I have added, using `sort -r` is the same case. I may be confusing your query. Sorry.

File: src/nvim/ex_cmds.c (hunk 7 above)
Comment (3N4N) [reply src/nvim/ex_cmds.c]: Done. (I added the `+1`. But isn't it unnecessary? For example, if the user adds two spaces between the cmd and the args, then we'll still have a space. We'll just have one less space always.
