### PR TITLE
fix(lsp): handle relative='editor' in make_floating_popup_options()

### LINKED ISSUE #39306: Using `:checkhealth` in a `help` buffer with `vim.g.health` set changes the window location
### Problem

Setting the `vim.g.health` variable to `{ style = 'float' }` makes the `Health` buffer created upon `:checkhealth` be a floating window, which I like because it does not open a new tabpage or switch my main buffer. The window, in this case, is like a dropdown: horizontally centered within the "full" nvim window, and aligned at the top.

Calling `:checkhealth` from a help buffer instead places the floating window at the top-left of the "full" nvim screen.

Here is a `minimal.lua` reproduction file:

```lua
vim.g.health = { style = 'float' }
```

### Steps to reproduce

nvim --clean -u minimal.lua
:checkhealth
; Should open a centered window.
:h 'comments'
:checkhealth
; Should open in the top-left corner.

### Expected behavior

The floating window should always be in the same place: at the cursor, in the middle, as a "dropdown" as it currently is, doesn't matter.

### Nvim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux, Fedora 43

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

built from source

### PR DESCRIPTION
**Pull request by o6ivp**
## Problem

With `vim.g.health = { style = 'float' }`, running `:checkhealth` from a `:help` buffer places the float in the top-left corner instead of centered.

`make_floating_popup_options()` picks the float anchor (NW/NE/SW/SE) from cursor-relative metrics (`winline()`, `wincol()`, `winheight()`) even when the caller passes `relative='editor'`, where those metrics are meaningless. From a help buffer the cursor's `wincol()` flips the anchor to `NE`, pushing the float off-screen to the left.

Closes #39306.

## Solution

When `relative='editor'`, treat the whole editor area as available space (`lines_above=0`, `lines_below=&lines`, `wincol=0`). This selects the `NW` anchor regardless of cursor position.

### CODE REVIEW

File: test/functional/plugin/health_spec.lua [hunk 1]
```diff
@@ -99,6 +99,28 @@ describe(':checkhealth', function()
     eq('qf', api.nvim_get_option_value('filetype', { buf = 0 }))
   end)
 
+  it('float position is consistent across current buffer/cursor #39306', function()
```
Comment (glepnir) [inline test/functional/plugin/health_spec.lua]: You should add tests in `test/functional/plugin/lsp/utils_spec.lua`.

Comment (justinmk) [reply test/functional/plugin/health_spec.lua]: yes, either one new `it()` in `lsp/utils_spec.lua`, or update an existing test (there is hopefully already a test for `opts.relative`, and it should just be updated

File: test/functional/plugin/lsp/util_spec.lua [hunk 2]
```diff
@@ -1393,6 +1393,29 @@ describe('vim.lsp.util', function()
           eq('Title', opts.title)
         end)
       end)
+
+      describe('with relative = "editor" #39306', function()
```
Comment (glepnir) [inline test/functional/plugin/lsp/util_spec.lua]: feels a bit redundant.. these three cases all go through the same branch and assert the same thing. One should be enough to cover the regression

Comment (o6ivp) [reply test/functional/plugin/lsp/util_spec.lua]: Good point — consolidated to a single case using G, which picks an S* anchor in the pre-fix code, so it gives a clear regression signal. 979145cef2

File: runtime/lua/vim/lsp/util.lua [hunk 3]
```diff
@@ -917,9 +917,19 @@ function M.make_floating_popup_options(width, height, opts)
...
+  if opts.relative == 'mouse' then
+    lines_above = vim.fn.getmousepos().line - 1
+    lines_below = vim.fn.winheight(0) - lines_above
+  elseif opts.relative == 'editor' then
+    -- No cursor to anchor against; treat the whole editor as space below.
+    lines_above = 0
+    lines_below = vim.o.lines
+  else
+    lines_above = vim.fn.winline() - 1
+    lines_below = vim.fn.winheight(0) - lines_above
```
Comment (justinmk) [inline runtime/lua/vim/lsp/util.lua:931]: why not initialize to these? that avoids the `else` branch, and avoids the manual `--@type` annotations.

same for the `wincol` change below.
