### PR TITLE
test(tui_spec): flakiness, global highlight definitions

### LINKED ISSUE #34917: unreliable test: tui_spec: "TUI has no black flicker"
### Problem

```
FAILED   test/functional/terminal/tui_spec.lua @ 2505: TUI has no black flicker when clearing regions during startup with termguicolors
test/functional/terminal/tui_spec.lua:2528: Row 1 did not match.
Expected:
  |*^                                                   |
  |*                                                   |
  |*                                                   |
  |*                                                   |
  |*                                                   |
  |*                                                   |
  |*                                                   |
  |*                                                   |
  |*                                                   |
  |*                                                   |
  |                                                   |
Actual:
  |*{UNEXPECTED foreground = Screen.colors.NvimDarkGray2, background = Screen.colors.NvimLightGrey2:^                                                   }|
  |*{UNEXPECTED foreground = Screen.colors.NvimLightGray4, background = Screen.colors.NvimLightGrey2:~                                                  }|
  |*{UNEXPECTED foreground = Screen.colors.NvimLightGray4, background = Screen.colors.NvimLightGrey2:~                                                  }|
  |*{UNEXPECTED foreground = Screen.colors.NvimLightGray4, background = Screen.colors.NvimLightGrey2:~                                                  }|
  |*{UNEXPECTED foreground = Screen.colors.NvimLightGray4, background = Screen.colors.NvimLightGrey2:~                                                  }|
  |*{UNEXPECTED foreground = Screen.colors.NvimLightGray4, background = Screen.colors.NvimLightGrey2:~                                                  }|
  |*{UNEXPECTED foreground = Screen.colors.NvimLightGray4, background = Screen.colors.NvimLightGrey2:~                                                  }|
  |*{UNEXPECTED foreground = Screen.colors.NvimLightGray4, background = Screen.colors.NvimLightGrey2:~                                                  }|
  |*{UNEXPECTED foreground = Screen.colors.NvimLightGray3, background = Screen.colors.NvimDarkGrey3:[No Name]                        0,0-1          All}|
  |*{UNEXPECTED foreground = Screen.colors.NvimDarkGray2, background = Screen.colors.NvimLightGrey2:                                                   }|
  |          
```

### Expected behavior

@luukvbaal this test fails quite often, does it indicate that the bug is still present? maybe we should set it to `pending()` ?

### PR DESCRIPTION
**Pull request by luukvbaal**
Fix #34917

### CODE REVIEW

File: test/functional/terminal/tui_spec.lua [hunk 1]
```diff
@@ -2504,33 +2444,39 @@ describe('TUI', function()
...
+        },
+      })
       fn.jobstart({
         nvim_prog,
         '--clean',
         '--cmd',
         'set ' .. guicolors,
         '--cmd',
+        'echo "foo"',
+        '--cmd',
```
Comment (justinmk) [inline test/functional/terminal/tui_spec.lua:2460]: 👀
