### PR TITLE
fix: right click in clickable statusline

### LINKED ISSUE #18994: Right click behaves strangely with clickable statusline section
### Neovim version (nvim -v)

v0.8.0-dev+440-g98e2da7d5

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.2, also happens in neovim-qt

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Run `nvim --clean`
2. Source the following script
```vim
let g:testvar = ''

function! MyClickFunc(minwid, clicks, button, mods)
  let g:testvar = printf("%d %d %s %d", a:minwid, a:clicks, a:button, localtime())
  if a:mods !=# '    '
    let g:testvar ..= '(' .. a:mods .. ')'
  endif
endfunction

set mouse=a
let &stl = 'Not clicky stuff %0@MyClickFunc@Clicky stuff%T %{g:testvar}'
```
3. Right click on the clickable section on statusline
4. Press ESC
5. Left click on the clickable section on statusline
6. Right click out of the clickable section on statusline soon

### Expected behavior

3. `0 1 r` appears on statusline
5. `0 1 l` appears on statusline
6. Visual mode is started and statusline does not change

### Actual behavior

3. Visual mode is started and statusline does not change
5. `0 1 l` appears on statusline
6. Visual mode is started and `0 1 r` appears on statusline

### PR DESCRIPTION
**Pull request by famiu**
Previously, clickable statuslines didn't receive right click unless the statusline was focused. This fixes that behavior by making clickable statusline sections correctly receive right clicks regardless of whether the statusline is focused or not.

Closes #18994

### CODE REVIEW

**Comment by famiu** [comment]
Wondering if `status_line_offset` and `sep_line_offset` are good names for the variables that previously used to be `on_status_line` and `on_sep_line`, since those variables don't necessarily mean that the mouse is actually on the status line (or sep line) but rather indicate an offset from it.

File: src/nvim/mouse.c [hunk 1]
```diff
@@ -189,58 +191,72 @@ int jump_to_mouse(int flags, bool *inclusive, int which_button)
...
+  if (grid == DEFAULT_GRID_HANDLE && row + wp->w_winbar_height >= wp->w_height) {
+    // In (or below) status line
+    on_status_line = (row + wp->w_winbar_height - wp->w_height + 1 == 1);
+  } else {
+    on_status_line = false;
+  }
+  if (keep_focus) {
+    // If we can't change focus, set the value of row and col back to absolute values
+    // since the values relative to the window are only used when keep_focus is true
+    row = prev_row;
```
Comment (justinmk) [inline src/nvim/mouse.c:219]: the comment is confusing because keep_focus is true here.

File: src/nvim/mouse.c [hunk 2]
```diff
@@ -128,8 +128,9 @@ bool is_mouse_key(int c)
 /// @param which_button  MOUSE_LEFT, MOUSE_RIGHT, MOUSE_MIDDLE
 int jump_to_mouse(int flags, bool *inclusive, int which_button)
 {
-  static int on_status_line = 0;        // #lines below bottom of window
-  static int on_sep_line = 0;           // on separator right of window
+  static int status_line_offset = 0;        // vertical offset from status line
```
Comment (justinmk) [inline src/nvim/mouse.c:131]:
```suggestion
  static int status_line_offset = 0;        // #lines offset from status line
```

File: src/nvim/mouse.c [hunk 3]
```diff
@@ -128,8 +128,9 @@ bool is_mouse_key(int c)
...
+  static int sep_line_offset = 0;           // horizontal offset from sep line
```
Comment (justinmk) [inline src/nvim/mouse.c:132]:
```suggestion
  static int sep_line_offset = 0;           // #cols offset from sep line
```

File: src/nvim/mouse.c (hunk 1 above)
Comment (famiu) [reply src/nvim/mouse.c]: the comment was incorrect, I fixed it now

File: src/nvim/mouse.c [hunk 4]
```diff
@@ -189,58 +191,70 @@ int jump_to_mouse(int flags, bool *inclusive, int which_button)
   old_curwin = curwin;
   old_cursor = curwin->w_cursor;
 
-  if (!(flags & MOUSE_FOCUS)) {
-    if (row < 0 || col < 0) {                   // check if it makes sense
-      return IN_UNKNOWN;
-    }
+  if (row < 0 || col < 0) {                   // check if it makes sense
+    return IN_UNKNOWN;
+  }
```
Comment (justinmk) [inline src/nvim/mouse.c:196]: the docstring explains the `if (!(flags & MOUSE_FOCUS))` guard as follows, is this still the behavior?

```
/// If flags has MOUSE_FOCUS, then the current window will not be changed, and
/// if the mouse is outside the window then the text will scroll, or if the
/// mouse was previously on a status line, then the status line may be dragged.
```

Comment (famiu) [reply src/nvim/mouse.c:196]: yes, unless the statusline or winbar was clicked, then there will be no scroll

File: src/nvim/mouse.c [hunk 5]
```diff
@@ -189,58 +191,70 @@ int jump_to_mouse(int flags, bool *inclusive, int which_button)
...
+  if (grid == DEFAULT_GRID_HANDLE && row + wp->w_winbar_height >= wp->w_height) {
+    on_status_line = (row + wp->w_winbar_height - wp->w_height + 1 == 1);
+  } else {
+    on_status_line = false;
+  }
+  if (row == -1) {
+    on_winbar = wp->w_winbar_height != 0;
+  } else {
+    on_winbar = false;
+  }
```
Comment (justinmk) [inline src/nvim/mouse.c:212]:
```suggestion
  on_winbar = (row == -1)
    ? wp->w_winbar_height != 0
    : false;
```

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/18994#issuecomment-1176961485 gives a perfect, succinct explanation of the issue: 

> * Right-click won't work unless you left-click first
> * The modifier does not work, nothing happens when I do shift right click

Does shift right click work with this PR? Need a test for that.
