### PR TITLE
fix(lsp): use `vim.notify` with action-less `showMessage` requests

### LINKED ISSUE #34717: LSP showMessageRequest with no choices, use vim.notify
### Problem

When a language server issues `window/showMessageRequest`, LSP uses `vim.ui.select`. When there are no choices supplied, that just opens a "Press Enter" interaction. Maybe such LSes should use `window/showMessage` instead or something, but until every LS is fixed, it would be nice if LSP did the Right Thing

### Expected behavior

Ideally, `showMessageRequest` with no options should be treated as if it were a `showMessage` (i.e. `vim.notify` not `vim.ui.select`)

### PR DESCRIPTION
**Pull request by MariaSolOs**
Closes https://github.com/neovim/neovim/issues/34717

### CODE REVIEW

File: runtime/lua/vim/lsp/handlers.lua [hunk 1]
```diff
@@ -28,6 +28,22 @@ local function err_message(...)
   api.nvim_command('redraw')
 end
 
+--- @param params lsp.ShowMessageParams|lsp.ShowMessageRequestParams
+--- @param ctx lsp.HandlerContext
+local function show_message_notification(params, ctx)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/handlers.lua:33]: handlers should be prefixed with `on_`. or if we think of this function as "procedural" we can just call it `show_message()` ?



```suggestion
local function on_show_message(params, ctx)
```

**Review by justinmk — APPROVED** [review]

File: runtime/lua/vim/lsp/handlers.lua (hunk 1 above)
Comment (MariaSolOs) [reply runtime/lua/vim/lsp/handlers.lua:33]: Yeah I wouldn't consider this a proper handler, it's just the shared utility between the "showMessage" notification/request to invoke `vim.notify`. I'll stick with the current name though as `vim.ui.select` is another way to show the message, the `_notification` bit is just to clarify that it invokes `vim.notify`.
